- toolkit/tools/srpmpacker/srpmpacker.go
---
This PR changes the working directory used by srpmpacker for each spec. Currently srpmpacker packs each spec in its own folder that lives under `{build_dir}/{spec_file_name}`. Since srpmpacker runs parallelized this working directory must be unique.
There may be specs with identical names but different versions -- e.g. a `SPECS/foo-1.7/foo.spec` and a `SPECS/foo-1.8/foo.spec`. This would cause srpmpacker to reuse the same working directory for the `foo` specs, causing a collision and corrupted SRPMs.
Switch to the spec's SRPM name as the unique folder name to avoid collisions.
- Use the SRPM file name instead the spec nam as the folder name to pack inside of.
NO
- Ran `make …
> Use SRPM name as the working directory name to pack in

- toolkit/scripts/tools.mk
---
Currently the toolchain RPMs are placed into `/out/RPMS` by the bootstrapping process. They are normally expected to be in the cache folder however. It is not possible to do a full build from source in one step since the chroot worker packaging done by `create_worker_chroot.sh` doesn't know to look for the toolchain RPMs in the general RPMs folder.
We have a variable `$(toolchain_rpms_dir)` which is set based on `REBUILD_TOOLCHAIN=?` which tracks this folder. We need to pull the toolchain RPMs we actually build/download based on that variable into the chroot, rather than ALWAYS picking the ones in the cache (which could be stale).
Running `make copy-toolchain-rpms` obfuscates …
> Pull toolchain RPMs from the correct directory

- SPECS/libffi/libffi.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
libffi was successfully getting build as part of the toolchain build. However, when rebuilding it later as part of a `packages` or `image` Makefile target build, the libffi package would fail to build due to the `.so` files getting placed in a different directory. This change addresses this issue.
- Fix normal libffi build by replacing destination for .so files from $(toolexeclibdir) to $(libdir)  
- Replace ./configure and manual options with %%configure macro
**YES**
- Local normal package build (as opposed to a full toolchain build)
> Fix libffi normal package build

- SPECS/golang/golang-1.13.signatures.json
- SPECS/golang/golang-1.13.spec
- cgmanifest.json
---
Upgrade golang to 1.13.15 to resolve CVE-2020-14039 and CVE-2020-16845
Package: "golang"
CVEs: CVE-2020-14039 and CVE-2020-16845
No
None
- https://nvd.nist.gov/vuln/detail/CVE-2020-14039
- https://nvd.nist.gov/vuln/detail/CVE-2020-16845
- Local build
> Upgrade golang to 1.13.15

- toolkit/docs/building/building.md
---
Added info to the quick start instructions on which tag to use to successfully build from the branch of interest.
- Added info to the quick start instructions on which tag to use to successfully build from the branch of interest.
No.
- Viewed the changes locally.
> Adding a small build tip to the quick start instructions

- SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.signatures.json
- SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.spec
- cgmanifest.json
---
This PR adds cloud-init-vmware-guestinfo package, which is required for the cloud-init to work in the VMWare cloud environment. The package supplies cloud-init datasource for the vSphere's GuestInfo interface.
- Added cloud-init-vmware-guestinfo package.
NO
- Local build succeeded.
> Add cloud-init-vmware-guestinfo package

- SPECS/tpm2-abrmd/tpm2-abrmd.signatures.json
- SPECS/tpm2-abrmd/tpm2-abrmd.spec
- SPECS/tpm2-tools/tpm2-tools.spec
- cgmanifest.json
---
`tpm2-abrmd` 2.1.1 has a specific incompatibility with `tpm2-tss` 2.4.0. Update it to avoid this conflict. Also noticed while doing research that tpm2-tools has updated to use BSD-3 license.
- Update `tpm2-abrmd` to 2.1.1
- Change license of `tpm2-tools` to BSD 3-Clause
NO
- Targeted build of `tpm2-abrmd` 
- Full local rebuild in progress
> Update tpm2-abrmd to 2.3.3

- .github/workflows/quickstart.yml
---
Add a GitHub Action to automatedly verify our Quickstart instructions. Currently tests ISO Quick Start and VHDX Quick Start. Configured to run daily and on demand.
- Add Verify Quickstart GitHub Workflow. Currently tests ISO Quick Start and VHDX Quick Start. Configured to run daily and on demand.
NO
- Tested from fork - https://github.com/christopherco/CBL-Mariner/actions/runs/261935138
> Add Quick Start Verify GitHub Action

- SPECS/httpd/CVE-1999-0236.nopatch
- SPECS/httpd/CVE-1999-1412.nopatch
- SPECS/httpd/httpd.spec
- cgmanifest.json
---
`httpd` CVE-1999-0236 is unpatched, and appears to require the user to provide the mitigations through configuration (see "Server Side Includes" [docs](https://httpd.apache.org/docs/2.4/misc/security_tips.html)
`httpd` CVE-1999-1412 applies only to MacOS X.
- Nopatch `httpd` CVE-1999-0236
- Nopatch `httpd` CVE-1999-1412 
- Unify changelog format for `httpd.spec`
NO
- https://nvd.nist.gov/vuln/detail/CVE-1999-0236
- https://nvd.nist.gov/vuln/detail/CVE-1999-1412
> Nopatch httpd CVE-1999-0236, CVE-1999-1412

- SPECS/groff/CVE-2000-0803.nopatch
- SPECS/groff/groff.spec
---
`groff` CVE-2000-0803 is unpatched. Centos & Fedora do not appear to address this CVE either.
- Nopatch `groff` CVE-2000-0803
- Unify changelog format for `groff.spec`
NO
- https://nvd.nist.gov/vuln/detail/CVE-2000-0803
> Nopatch groff CVE-2000-0803

- SPECS/apparmor/CVE-2016-1585.nopatch
- SPECS/apparmor/apparmor.spec
---
`apparmor` CVE-2016-1585 is unpatched. At time of filing it only appeared to affect Ubuntu (via the "mount rules" feature). OpenSUSE and Debian are not affected since they disable this feature.
- Nopatch `apparmor` CVE-2016-1585
NO
- https://nvd.nist.gov/vuln/detail/CVE-2016-1585
> Nopatch apparmor CVE-2016-1585

- SPECS/qemu-kvm/CVE-2016-7161.nopatch
- SPECS/qemu-kvm/qemu-kvm.spec
---
`qemu-kvm`CVE-2016-7161 is already patched. It was fixed in version 2.7 but NVD was not updated.
- Nopatch`qemu-kvm`CVE-2016-7161
- Unify formatting in `qemu-kvm.spec`
NO
- https://nvd.nist.gov/vuln/detail/CVE-2016-7161
> Nopatch qemu CVE-2016-7161

- SPECS/lua/CVE-2020-15889.nopatch
- SPECS/lua/lua.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
`lua` CVE-2020-15889 does not affect Lua 5.3.5. The vulnerability is introduced in Lua 5.4.0.
- Nopatch `lua` CVE-2020-15889 
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-15889 
> Nopatch lua CVE-2020-15889

- SPECS/unzip/CVE-2008-0888.nopatch
- SPECS/unzip/unzip.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
`unzip` CVE-2005-0888 was fixed in 6.0. Verified the code changes from the patch (or close analogues) were present in the current sources.
- Nopatch `unzip` CVE-2005-0888
**YES**
- https://nvd.nist.gov/vuln/detail/ CVE-2005-0888 
> Nopatch unzip CVE-2008-0888

- toolkit/Makefile
- toolkit/docs/building/building.md
- toolkit/scripts/srpm_pack.mk
---
To support pulling SRPMs from multiple URLs replace the individual `SRPM_URL*` flags with a space separated `SRPM_URL_LIST` flag. The order to try downloading SRPMs is now `base` -> `update` -> `preview`.
- Replaced `SRPM_URL` and `SRPM_UPDATE_URL` with a new `SRPM_URL_LIST` flag.
- Add the preview SRPM url to the list.
NO
- Ran `make input-srpms DOWNLOAD_SRPMS=y`
> Support downloading preview SRPMs

- SPECS/chrony/chrony.spec
- cgmanifest.json
---
Example chrony-wait service definition in chrony source adds itself as a systemd boot dependency, which increases overall boot times from ~6s to ~2.75min. This patch comments out the offending line in the service definition file.
- Change
- Change
- Change
**NO**
- Rebuilt chrony locally
- Efficacy of fix was confirmed in 1.0.20200922 iso core image.
> Remove chrony-wait as a boot service dependency

- SPECS/initramfs/initramfs.spec
---
This change addresses a kdump scenario regression which can occur after issuing kernel package upgrade.
Failing Behavior: After a kernel upgrade and updated crash kernel is armed, if a panic occurs, the system just hangs on the panic.
Our kdump service currently uses the host system's initrd when enrolling a crash kernel and initrd. And there is a limitation where the kdump initrd must be generated with dracut in "host-only" mode.
If mkinitrd is called without `<image>` and `<kernel-version>` parameters, it will default to calling dracut in "host-mode" mode on every kernel version it can find in /boot.
If mkinitrd is called with `<image>` and `<kernel-version>` parameters, it …
> initramfs: Regenerate initrd using host-only mode on file-based trigger

- SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/kernel.spec
---
The `%postun` script was testing the the outcome of a statement that always returns empty string. As a consequence, `mariner.cfg` was not pointing to the next available `kernel` after an uninstall.
- Change the `%postun` script in `kernel.spec` to test whether any other `kernel` configurations are around.
YES
**NO**
- #xxxx
> Fix kernel specs' %postun scripts

- SPECS/fontconfig/fontconfig.signatures.json
- SPECS/fontconfig/fontconfig.spec
- cgmanifest.json
---
Fontconfig intermittently fails the tests when the machine is under a heavy IO pressure. Updating to 2.13.91 should fix this problem.
- Updated fontconfig to 2.13.91
- Reformatted spec slightly
NO
- Local build succeeded.
> Update fontconfig to 2.13.91

- SPECS/strongswan/0001-Extending-timeout-for-test-cases-with-multiple-read-.patch
- SPECS/strongswan/strongswan.spec
---
Extending the time-out for the 'valid/invalid data' test case. It hit a timeout in two of its test: one while in `fopen` and one while in `fclose`. I failed to repro the test failure locally but since the build machine is set to run up to 8 package builds (and their test) in parallel and both of the failing tests open/close/write to `/tmp/strongswan-settings-test` multiple times before they are done, it's possible that the tests need more time under these circumstances. If this change fails to resolve the issue, we will need to investigate further.
- Extended the time-out for the 'valid/invalid data' test case.
No
- Rebuilt the package locally.
> Extending 'strongswan' test timeout.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/file/file.go
---
Currently, the image tooling generates a random unique /etc/machine-id for our offline images. This has the side-effect where booting the same offline image on multiple devices (i.e. booting multiple copies of the same VHDx image on different VMs) will actually have the same /etc/machine-id. This machine-id is expected to be unique per device and persisted for the lifetime of the device. And having machine-id collisions like this can cause unexpected issues (i.e. same IP address assigned to different VMs)
From https://www.freedesktop.org/software/systemd/man/machine-id.html:
For operating system images which are created once and used on multiple machines, for example for …
> installutils: Supply blank /etc/machine-id file

- toolkit/tools/imagegen/installutils/installutils.go
---
In the current images, the root password expiry gets set to the default 90 days. If the root user was configured in the imageconfig.json, it is possible to customize this expiry date. However, if no root user is specified (which is the standard case), the default root user will get the password expiry notice after 90 days and can be locked out of the system.
This change removes the root password expiry only in the case when no root user is specified in the imageconfig file.
- Remove the root password expiry only in the case when no root user is specified in the imageconfig file.
NO
- Local image testing
> installutils: Remove root password expiry when no root user is specified in imageconfig file

- .github/workflows/check-package-cgmanifest.yml
---
Patches CVE-2020-15228 in our GitHub Actions scripts using the "::set-env" command (corresponds to PR against 1.0-dev branch microsoft/CBL-Mariner#178)
- Address [deprecation of "::set-env"" command](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w) due to CVE-2020-15228
- Replace deprecated command with ["Environment File Syntax"](https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-15228
- Tested push functionality in thcrain/test-workflow-set-env branch, tested PR functionality in thcrain/test-workflow-set-env-fix branch
- Both functioned as expected post-change
> [dev] Remove "::set-env" commands in GitHub Actions for CVE-2020-15228

- SPECS/httpd/CVE-2007-0086.nopatch
- SPECS/httpd/httpd.spec
---
Adding a .nopatch for `httpd` CVE-2007-0086. More details in checked-in file.
- Nopatching CVE-2007-0086.
No
- https://nvd.nist.gov/vuln/detail/CVE-2007-0086.
- Rebuilt package locally.
> Nopatching `httpd` CVE-2007-0086.

- SPECS/curl/curl.spec
- SPECS/gnutls/gnutls.spec
- SPECS/wget/wget.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Before the change `curl`, `gnutls`, and `wget` were using a legacy certificate bundle, which only contains certificates of trusted 
CAs, so blacklisting any **intermediate** CA was being ignored by these tools (**root** CAs were still blacklisted, as they were just removed from the bundle after being blacklisted). Right next to that bundle sits an extended version containing distrust/blacklist information, which is the one that should actually be used to make sure we properly handle blacklisting any interemediate CAs.
- Changed the cert bundle file used by `curl`, `gnutls` and `wget` to include distrust information about any (root **and** intermediate) CAs.
No.
- Rebuilt the …
> Updating cert bundle paths.

- SPECS/kernel/kernel.spec
- The `archdir` shell variable is defined in the `%build` section of `kernel.spec`, but it is later referenced in the `%install` section.
- As those two scriptlets have been run separately, `${archdir}` reference in `%install` returns an empty string.
- Address this problem by defining it as a spec variable.
---
- The `archdir` shell variable is defined in the `%build` section of `kernel.spec`, but it is later referenced in the `%install` section.
- As those two scriptlets have been run separately, `${archdir}` reference in `%install` returns an empty string.
- Address this problem by defining it as a spec variable.
- Define `arch` and …
> Replace the misuse of `archdir` shell variable

- SPECS/secilc/secilc.spec
---
Fix missing %libsepolver macro in secilc.spec, which caused a build error in graphpkgfetcher
- Add %libsepolver macro definition in the style of other specs from the SELinux PR (#100)
- Lint spec for style issues
**NO**
- Pipeline build id: Local build up to graphpkgfetcher step, low-risk change
> Fix missing macro in secilc

- toolkit/docs/building/building.md
---
Removing documentation for deprecated 'TERMINAL_ISO_INSTALLER' argument. It doesn't do anything anymore.
- Remoevd documentation for the 'TERMINAL_ISO_INSTALLER' argument.
No
- I looked at it.
> Removing documentation for deprecated 'TERMINAL_ISO_INSTALLER' argument.

- SPECS/cifs-utils/CVE-2020-14342-fix.patch
- SPECS/cifs-utils/CVE-2020-14342.patch
- SPECS/cifs-utils/cifs-utils.spec
---
This commit patches the privilege escalation CVE-2020-14342 in cifs-utils
Patch CVE-2020-14342 in cifs-utils
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-14342
- [Upstream patch] https://git.samba.org/cifs-utils.git/?p=cifs-utils.git;a=commitdiff;h=48a654e2e763fce24c22e1b9c695b42804bbdd4a#patch1
- Local build
- Observed that running "sudo mount.cifs -o username='\`sh\`' //1 /mnt" no longer drops into a root sh session but instead prompts for a password.
> Patch CVE-2020-14342 in cifs-utils

- toolkit/scripts/toolkit.mk
- Also add `version.txt` file in the toolkit archive as an easy way to verify toolkit version.
---
- Toolkit archive includes compiled binaries, so its version should include which architecture these binaries belong to.
- Add architecture at the end of the toolkit archive name.
- Add a `version.txt` file in the toolkit archive.
YES
**NO**
- #xxxx
> Add architecture at the end of toolkit archive name

- toolkit/tools/srpmpacker/srpmpacker.go
---
During container builds, `srpmpacker` was not copying any prepacked srpms to its output directory. This resulted in srpms being repacked.
- Copy any prepacked SRPMs into the chroot's output directory at the start of `srpmpacker`
NO
- Local build.
> [dev] Avoid repacking SRPMs during container builds

- toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
---
The fetchers would try to remove any existing repodata before initializing a new repo. However, it was incorrectly treating the repolock directory (`.repodata`) as a file. This resulted in failures when trying to remove it.
- Use `RemoveAll` to remove the `.repodata` directory if it exists.
NO
- Local builds
> Fix repolock removal

- SPECS/oniguruma/CVE-2020-26159.patch
- SPECS/oniguruma/oniguruma.spec
---
Fixes CVE-2020-26159.
- Use the patch from upstream. 
YES
**NO**
- #xxxx
- Local build
> Fix CVE-2020-26159 in oniguruma

- toolkit/Makefile
---
The toolkit is required to be run under a git repository to populate a non-empty `BUILD_NUMBER` variable. Later on, when `BUILD_NUMBER` is passed on to the go tools, i.e. `unravel`, the tools rejects the command as it expects a non-empty string.
- If the git does not return a revision, use a simple string to avoid `BUILD_NUMBER` being empty.
YES
**NO**
- #xxxx
> Remove implicit git repository dependency from toolkit

- toolkit/tools/internal/versioncompare/versioncompare.go
- toolkit/tools/internal/versioncompare/versioncompare_test.go
---
Add support for epochs to grapher and the version comparison logic. The current behavior treats epochs as simply another component of the version field. However this does not work correctly when dealing with specs that do not specify an epoch.
In the current behavior `2:1.2` is seen as a lower version than `4.2.1`, despite the epoch being higher. When a spec does not specify an epoch, it is implicitly assumed to be 0 by rpm ([reference](https://rpm-packaging-guide.github.io/#epoch)).
The fix is to prepend the implicit epoch of 0 when non is specified. This makes `4.2.1` be parsed as `0:4.2.1`, fixing the above example.
See https://rpm-packaging-guide.github.io/#epoch for more …
> [dev] Support epochs in spec versions

- SPECS/pugixml/pugixml.signatures.json
- SPECS/pugixml/pugixml.spec
- cgmanifest.json
---
Add pugixml package as it's required by some of our partners.
- Add pugixml package
**NO**
> Add pugixml package

- SPECS/nlohmann-json/nlohmann-json.spec
- [] Any updated packages successfully build (or no packages were changed)
---
nlohmann-json is a header-only library, we don't need to generate a debug package for it.
- Disable debug package generation for nlohmann-json
**NO**
> Disable debug package for nlohmann-json

- SPECS/ruby/ruby.signatures.json
- SPECS/ruby/ruby.spec
- cgmanifest.json
---
`ruby` has 6 outstanding CVEs associated at the moment, and their solution to these vulnerabilities is to upgrade the ruby version, as there are no specific patches released for them. 
Sample: https://www.ruby-lang.org/en/news/2020/03/31/heap-exposure-in-socket-cve-2020-10933/
- The list of CVEs fixed by this change is at the bottom of the PR.
- Upgrade `ruby` to `2.6.6`, update the signature file, and update `cgmanifest.json`
YES
**NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2020-5247
-https://nvd.nist.gov/vuln/detail/CVE-2020-10933
-https://nvd.nist.gov/vuln/detail/CVE-2019-16255 …
> Upgrade ruby to 2.6.6 to resolve CVE-2019-16255, CVE-2019-16201, CVE-2020-10933, CVE-2020-5247, CVE-2019-15845, CVE-2019-16254

- SPECS/qemu-kvm/CVE-2015-7504.nopatch
- SPECS/qemu-kvm/CVE-2016-7161.nopatch
- SPECS/qemu-kvm/CVE-2017-14167.nopatch
- SPECS/qemu-kvm/CVE-2017-5931.nopatch
- SPECS/qemu-kvm/qemu-kvm.spec
---
`qemu` CVE-2015-7504, CVE-2017-5931, CVE-2017-14167 have all been patched in our version but NVD isn't updated to match.
- Nopatch `qemu` CVE-2015-7504
- Nopatch `qemu` CVE-2017-5931
- Nopatch `qemu` CVE-2017-14167
- Add a commit hash to a previous nopatch so they all match
NO
- https://nvd.nist.gov/vuln/detail/CVE-2015-7504
- https://nvd.nist.gov/vuln/detail/CVE-2017-5931
- https://nvd.nist.gov/vuln/detail/CVE-2017-14167
> Nopatch qemu CVE-2015-7504, CVE-2017-5931, CVE-2017-14167

- SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
- SPECS/kernel/CVE-2010-3865.nopatch
- SPECS/kernel/CVE-2020-10757.nopatch
- SPECS/kernel/CVE-2020-11668.nopatch
- SPECS/kernel/CVE-2020-12653.nopatch
- SPECS/kernel/CVE-2020-12654.nopatch
- SPECS/kernel/CVE-2020-12657.nopatch
- SPECS/kernel/CVE-2020-24394.nopatch
- SPECS/kernel/CVE-2020-8428.nopatch
- SPECS/kernel/kernel.spec
---
`kernel` CVE-2020-10757, CVE-2020-12653, CVE-2020-12657, CVE-2010-3865, CVE-2020-11668, CVE-2020-12654, CVE-2020-24394, CVE-2020-8428 upstream fixes are already present in our 5.4.51 stable kernel source.
- Add nopatch files for `kernel` CVE-2020-10757, CVE-2020-12653, CVE-2020-12657, CVE-2010-3865, CVE-2020-11668, CVE-2020-12654, CVE-2020-24394, CVE-2020-8428. Includes commit ID mapping between upstream kernel commit ID to our stable kernel commit ID.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-10757
- https://nvd.nist.gov/vuln/detail/CVE-2020-12653
- https://nvd.nist.gov/vuln/detail/CVE-2020-12657
- https://nvd.nist.gov/vuln/detail/CVE-2010-3865
- …
> Nopatch kernel CVE-2020-10757, CVE-2020-12653, CVE-2020-12657, CVE-2010-3865, CVE-2020-11668, CVE-2020-12654, CVE-2020-24394, CVE-2020-8428

- SPECS/openssh/CVE-2019-16905.patch
- SPECS/openssh/openssh.spec
---
Updates openssh.spec with security patch for CVE-2019-16905
- Add patch for CVE-2019-16905
YES
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2019-16905
> patch openssh for CVE-2019-16905

- SPECS/git/git.spec
- SPECS/krb5/krb5.spec
- SPECS/libcap-ng/libcap-ng.spec
- SPECS/make/make.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix failing %check tests in the following spec files: git, make, krb5 and libcap-ng
- Fix failing tests
- Update toolchain mainfests
**YES**
NO
- #xxxx
- Local package builds. Example:
sudo make build-packages PACKAGE_BUILD_LIST="libcap-ng" RUN_CHECK=y -j$(nproc)
> Fix check tests for git, make, krb5 and libcap-ng

- SPECS/vim/CVE-2019-12735.patch
- SPECS/vim/vim.spec
---
It fixes CVE-2019-12735 in `vim`.
- Modify the upstream patch to apply to current version.
YES
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-12735
- Local build
> Fix CVE-2019-12735 in vim

- SPECS/systemd/100-portabled-allow-to-detach-an-image-with-a-unit-in-li.patch
- SPECS/systemd/101-Portabled-fix-inspect-on-image-attached-as-directory.patch
- SPECS/systemd/102-portablectl-add-now-and-enable-to-attach-detach.patch
- SPECS/systemd/103-core-allow-portablectl-to-load-new-services-without-.patch
- SPECS/systemd/104-portablectl-block-when-stopping-a-unit-on-detach-now.patch
- SPECS/systemd/105-portablectl-use-replace-unload-when-stopping-a-servi.patch
- SPECS/systemd/106-portabled-implement-container-host-os-release-interf.patch
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Portablectl is missing --now --enable and --no-block flags which are required in CBL-Mariner.
These flags are require for systemd generators. Systemd 239 version is stable hence back porting required patches.
These patches can be removed once we upgrade systemd version to latest. 
- Change
- Change
- Change
**YES**
NO
- #xxxx
> Portablectl patches for to support --now --enable and --no-block flags

- SPECS/ed/ed.spec
ed CVE-2015-2987 applies to a different program named ed.
---
Nopatching ed CVE-2015-2987 because it applies to a different program named ed.
- Nopatching ed CVE-2015-2987
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2015-2987
- local build
> Nopatch ed CVE-2015-2987

- SPECS/gnutls/CVE-2020-24659.patch
- SPECS/gnutls/gnutls.spec
Upstream CVE discussion: https://gitlab.com/gnutls/gnutls/-/issues/1071
---
Patches CVE-2020-24659 in gnutls.
Upstream CVE discussion here: https://gitlab.com/gnutls/gnutls/-/issues/1071
Upstream commit here: https://gitlab.com/gnutls/gnutls/-/merge_requests/1320
- Add CVE-2020-24659.patch to gnutls
- Switch gnutls from %setup to %autosetup
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-24659
- Local Build
> Patch gnutls CVE-2020-24659

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Each time a build is made, a new build version number is created (e.g. 1.0.20201023 or 1.0.20201024).  That build number gets embedded in the mariner-release package with every daily build, but the package version itself does not change.  Currently the last officially released mariner-release package number was 1.0-9 and contains the 1.0.20201003 version number stamped within.   This change ensures that a new mariner-release.1.0-10 package will be created, and the new package version will be stamped with 1.0.20201024 (or whatever version is ultimately built from the 1.0 branch).  
**YES**
NO
> Update mariner release vers

- SPECS/auoms/auoms.spec
---
Fix build break due to auoms tarball name used in %setup macro
- Modify auoms.spec %setup and bump release number
YES
**NO**
- Local build
> Fix auoms setup issue

- toolkit/docs/how_it_works/1_initial_prep.md
- toolkit/scripts/tools.mk
- toolkit/tools/validatechroot/validatechroot.go
Signed-off-by: Daniel McIlvaney <damcilva@microsoft.com>
---
There have been a few times when changes to package dependencies are not properly propagated back to the toolchain. This can at best cause unexpected package rebuilds, or at worst cause correctness issues since expected features may not be available in the chroot worker.
Add the make target `validate-chroot` which will run through the chroot worker and double check every RPM is correctly installed. The target will automatically rebuild the toolchain if needed. For checking a stable tag upstream packages can be used: `sudo make validate-chroot REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n  -j10 2>&1 | tee ./validate.log`.
- Add …
> Add validatechroot tool to check worker chroot dependencies

- .github/workflows/lint-specs.yml
---
Enables PR gating with the spec linting action
- PRs must now pass the spec linter before being merged
- Output is now in action logs rather than in an artifact
**NO**
> Enable spec lint PR gating

- .github/workflows/lint-specs.yml
---
Enables PR gating with the spec linting action in dev branch. Cherry-pick of #270
- PRs must now pass the spec linter before being merged
- Output is now in action logs rather than in an artifact
**NO**
> Enable PR gating (dev)

- .github/workflows/lint-specs.yml
---
Forgot a commit in the last push that breaks lint-specs: add that back in
- Correct lint-specs.yml bash syntax
NO
> Fix bash script issue in spec lint action

- .github/workflows/lint-specs.yml
---
Revamped failure test for spec linting action (cherry pick of #290)
- Only requires one run of spec-cleaner now
- Improved separation between linting output and error message
NO
- Validated in my fork
> Revamp failure test for spec linting action

- toolkit/Makefile
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `./.github/workflows/cgmanifest.json`)
- [x ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x ] All source files have up-to-date hashes in the `*.signatures.json` files
- [x ] …
> Corrected URL_LIST links to preview repo

- toolkit/scripts/imggen.mk
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/isomaker/maker.go
---
In both `configuration` and `isomaker`, the `AdditionalFiles` map was being modified while it was being iterated. This resulted in entries added to `AdditionalFiles` sometimes being iterated in the same loop they were added. This was not the desired behavior of the functions.
Per the [golang spec on the range clause](https://golang.org/ref/spec#RangeClause):
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
> ....
> **If a map entry is created during iteration, that entry may be produced during the iteration or may be skipped.**
This fix is to create a new map with the desired values and after iteration is …
> Prevent AdditionalFiles from being modified during iteration

- toolkit/scripts/imggen.mk
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/isomaker/maker.go
---
In both `configuration` and `isomaker`, the `AdditionalFiles` map was being modified while it was being iterated. This resulted in entries added to `AdditionalFiles` sometimes being iterated in the same loop they were added. This was not the desired behavior of the functions.
Per the [golang spec on the range clause](https://golang.org/ref/spec#RangeClause):
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
> ....
> **If a map entry is created during iteration, that entry may be produced during the iteration or may be skipped.**
This fix is to create a new map with the desired values and after iteration is …
> Prevent AdditionalFiles from being modified during iteration (#297)

- SPECS/libxml2/CVE-2020-24977.patch
- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2020-24977 in libxml2.
Upstream patch:
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/50f06b3efb638efb0abd95dc62dca05ae67882c2
- Patch CVE-2020-24977
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-24977
- Local toolchain and package build
> Patch CVE-2020-24977 in libxml2

- SPECS/liblogging/liblogging.spec
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `./.github/workflows/cgmanifest.json`)
- [ x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ x] …
> Address source RPM publishing issue on packages.microsoft.com

- toolkit/tools/isomaker/maker.go
---
The new code in `copyAndRenameAdditionalFiles` assumed `systemConfig` was a pointer, similar to how `configuration` worked.
The fix is to use operate on a pointer to the systemConfig object instead of a copy.
- Operate on pointer of systemconfig
NO
- Local build.
> [1.0] Properly update AdditionalFiles in isomaker

- toolkit/tools/isomaker/maker.go
---
The new code in `copyAndRenameAdditionalFiles` assumed `systemConfig` was a pointer, similar to how `configuration` worked.
The fix is to operate on a pointer to the systemConfig object instead of a copy.
- Operate on pointer of systemconfig
NO
- Local build.
> [dev] Properly update AdditionalFiles in isomaker

- toolkit/tools/isomaker/maker.go
---
The new code in `copyAndRenameAdditionalFiles` assumed `systemConfig` was a pointer, similar to how `configuration` worked.
The fix is to operate on a pointer to the systemConfig object instead of a copy.
- Operate on pointer of systemconfig
NO
- Local build.
> Properly update AdditionalFiles in isomaker

- toolkit/scripts/pkggen.mk
---
Merge pkggen from 1.0-dev to dev.
- Update pkggen merge to dev.
NO
> Update pkggen merge

- .github/workflows/mariner-spec-cleaner.patch
---
Updates spec-cleaner to 266f3ca, addressing linting issues from recent PRs.
- Add negative lookbehinds for path -> macro regexes, allowing for usage of hard-coded paths in sed, etc.
- Add systemd_*, check macros to the excludes-bracketing list
- Allow multi-line comments in changelogs
NO
- Pipeline build id: Local verification of tool + patch functionality
> Update spec-cleaner to 266f3ca

- SPECS/lua/lua.spec
---
Small cleanup of `lua.spec`. Upstream fedora spec already contained one of our CVE fixes.
- Do not claim credit for CVE-2019-6706 fix
- Move comment on origin of CVE-2019-6706 patch to the correct spot
NO
- Trivial fix with no functional changes, no testing
> Clean up lua.spec 1.0 to dev merge

- toolkit/tools/grapher/grapher.go
---
Allow cycles with only run nodes to be collapsed into a meta node. Pure runtime cycles are solvable and should not block a package from being built.
Example: 
- `A` runtime requires `B`.
- `B` runtime requires `A`.
- `C` buildtime requires `A`.
Since the cycle is runtime only, `A` and `B` are buildable. Once both are built, they can be installed at the same time to satisfy `C`.
- Remove check that a cycle only contains a single SRPM. The routine already enforces the cycle does not contain build nodes.
NO
> [dev] Support cycles that only contain run nodes

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/internal/shell/shell.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
Reduce unneeded log noise during builds that makes finding errors difficult. Also reword a few errors messages to be more informative.
- Remove duplicate error logs from `graphpkgfetcher`.
- Downgrade message of all nodes blocked on specific packages to `debug` level.
- Do not print all arguments of children processes on `ctrl-c` as programs like `pkgworker` take in many. Only print the program being stopped unless the process cannot be terminated.
- In `scheduler` change `Skipped SRPMs` to `Blocked SRPMs` in the summary.
- In `scheduler` change `graph is unsolvable` to `could not build all packages` and print instructions to check the summary section.
NO
> [dev] Reduce log noise and give more helpful errors

- SPECS/ruby/CVE-2020-25613.patch
- SPECS/ruby/ruby.spec
---
Patch CVE-2020-25613 in ruby
- Fixes CVE-2020-25613
**No**
- https://nvd.nist.gov/vuln/detail/CVE-2020-25613
- Local build
> Patch CVE-2020-25613 in ruby

- SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
- SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
- SPECS/grub2/CVE-2020-15705.patch
- SPECS/grub2/grub2.spec
---
Fixing CVE-2020-15705 in `grub2`.
- Fixed CVE-2020-15705.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2020-15705
Local package build.
> Fixing CVE-2020-15705 in `grub2`.

- SPECS/dpdk/dpdk.spec
---
The tools subpackage in dpdk created runtime dependencies on packages that do not exist in CBL-Mariner. **To unblock builds disable this build option for now.**
- Build without dpdk tools subpackage.
NO
> [dev] Build without dpdk tools

- toolkit/scripts/imggen.mk
---
The `$(image_external_package_cache_summary)` make target was using deprecated flags as input to `$(go-imagepkgfetcher)`, which caused it to generate invalid package summaries. Replace the two flags with the new `imagepkgfetcher_extra_flags`.
- Replaced deprecated make flags with `imagepkgfetcher_extra_flags`.
NO.
Local image build.
> Replacing deprecated flags with `imagepkgfetcher_extra_flags`.

- SPECS/dpdk/dpdk.spec
---
After disabling `build with tools`, there were unpackaged files which broke building. Ignore these files.
- Allow unpackaged files.
NO
- Local build.
> [dev] Allow unpackaged files in dpdk

- SPECS/mysql/mysql.spec
---
Nopatch to address CVE-2012-5627.  NIST description is misleading and vendors only fixed MariaDB, but not MySQL. However, Bugzilla decided to not fix this particular CVE for MySQL: https://bugzilla.redhat.com/show_bug.cgi?id=883719 
Nopatch to address CVE-2012-5627.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2012-5627
- local package build
> No patch for mySQL and CVE-2012-5627

- SPECS/bond/bond.signatures.json
- SPECS/bond/bond.spec
---
Cherrypick: https://github.com/microsoft/CBL-Mariner/pull/280
bond's `SOURCE1` changed depending on which architecture it was being processed on. This resulted in an architecture-specific SRPM being produced for it. SRPMs should contain all the needed sources for every supported architecture it can build on.
Change bond to always list both `aarch64` and `x86_64` specific sources, but selectively choose which one to use.
- Include both `aarch64` and `x86_64` sources in bond.
NO
> [dev] Include all sources in bond regardless of arch

- SPECS/qemu-kvm/CVE-2018-19665.patch
---
Fix a word-wrapping issue with CVE-2018-19665's patch. This issue was caught in testing, but the fix was not pushed to the merged PR #324.
- Fix word wrapping in CVE-2018-19665 patch
- Does not bump qemu-kvm release number, as the latest release has not been built
NO
- Pipeline build id: Locally building
> Fix word wrapping in qemu-kvm CVE-2018-19665 patch

- SPECS/autoconf/autoconf.spec
- SPECS/gpgme/gpgme.spec
- SPECS/net-snmp/net-snmp.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix failing %check tests in the following spec files: autoconf, gpgme, net-snmp
- Modify specs for autoconf, gpgme, net-snmp
- Update package manifest versions
**YES**
NO
> Fix check tests for autoconf, gpgme, net-snmp

- .github/workflows/validate-cg-manifest.sh
- SPECS/python-markupsafe/python-markupsafe.signatures.json
- SPECS/python-markupsafe/python-markupsafe.spec
- SPECS/python-zope-interface/python-zope-interface.signatures.json
- SPECS/python-zope-interface/python-zope-interface.spec
- cgmanifest.json
---
The upgrade to Python 3.7.9 from Python 3.7.7 included an upgrade to python3-setuptools. This new version of setuptools finally removed a long deprecated feature (~6 years), which was still in use by two of our packages. These two packages are upgraded to versions which no longer use this feature. Since the Python 3.7.9 upgrade fixes many CVEs, I opted to upgrade these two packages rather than rollback the 3.7.9 upgrade.
The python-markupsafe developers say that this upgrade should contain no breaking changes. Package rebuilds of dependent packages were done anyways.
The python-zope-interface upgrade has one small breaking change, and all packages depending on it have been …
> Upgrade python-markupsafe and python-zope-interface for setuptools compatibility

- SPECS/zsh/0001-Skipping-test-if-ran-as-superuser.patch
- SPECS/zsh/zsh.spec
---
The directories globbing test is supposed to fail but it doesn't since we're building everything as root.
It looks like `zsh` is solving similar cases by skipping single testcases when the test runs as root.
- Skipped one testcase when `rpmbuild` is run by the root user.
No.
> Skipping one `zsh` ptest testcase if ran as superuser.

- SPECS/librepo/CVE-2020-14352.patch
- SPECS/librepo/librepo.spec
---
Patches CVE-2020-14352 in librepo.
- Takes upstream fix from [here](https://github.com/rpm-software-management/librepo/commit/7daea2a2429a54dad68b1de9b37a5f65c5cf2600)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-14352
- Local build
> Patch CVE-2020-14352 in librepo

- SPECS/auoms/auoms.spec
---
The `auoms` package creates the file `/etc/init.d/auoms`, however the `chkconfig` package explictly claims ownership of the `/etc/init.d` directory. If `chkconfig` is installed after `auoms` it will find that directory already present and will fail to install (this ordering is common since package lists are alphabetical). Claim `chkconfig` as a runtime requirement for `auoms` so that the `chkconfig` package can create the directory as expected. Also add `procps-ng` and `initscripts` packages since post and preun stpeps call into 
`auomsctl` which relies on `pgrep` and `service`.
- Add `chkconfig` as a runtime requirement for `auoms`
- Add `procps-ng` as runtime requirement for …
> Add missing requires to auoms package

- .github/workflows/quickstart_1.0.yml
- README.md
---
1.0 is now our default branch, we should display a set of status badges for the current state of the *-stable tags. While doing a full build from sources is too slow to do with a github action we can at least validate the `REBUILD_PACKAGES=n` case. 
Each time we snap a new stable branch (2.0-stable, 3.0-stable, etc.) we will need to create a new workflow and badge to target that tag. As releases drop out of support we can remove the workflows. Scheduled workflows (like the quickstart workflow) will only run if they are part of the default branch, so we only need to maintain these badges and workflow definitions on the current leading edge stable branch (1.0 right now).
**NOTE:** …
> Add status badge, update quickstart workflow

- toolkit/tools/pkgworker/pkgworker.go
---
Many of the package tests run in the `%check` section install additional libraries (through `cpan` for instance) and we need network access from the worker chroot for that. This change still keeps the regular, non-test builds offline.
- Enabled network access for the worker chroot during package test runs.
No.
- Local `make go-tool REBUILD_TOOLS=y` run succeeded.
> Enabling network access for package builds running with `%check`.

- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/depsolver.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
When scheduler runs, multiple routines have access to the dependency graph for reading. However, when injecting implicit provides or sub-graphing, the graph and its edges are altered. It is possible for other routines to be traversing the graph when this happens, resulting in concurrent reads and writes to a non-thread-safe object. Implement a reader-writer mutex around the graph to prevent this.
- Implement a reader-writer mutex for graph access in scheduler.
NO
> [dev] Guard scheduler's graph to prevent concurrent reads and writes

- SPECS/ant/ant.spec
---
`ant` does not work by default after installing it on a clean system. There is an underspecified dependency on `which`. By default `ant` will check `$JAVA_HOME` for the java binary location, or fall back to calling `which java` to find it. Since on a default system `$JAVA_HOME` is not set and `which` is not installed, `ant` cannot find `java` so it will fail.
See the following ant source code: https://github.com/apache/ant/blob/81aee9ec90a14f35c54acb54299e2e23a2749423/src/script/ant#L188
To repro, run the following commands on a clean Core image:
```
root [ / ]# tdnf install ant
....
root [ / ]# ant
We cannot run Java, please ensure you have Java installed.
We have tried to …
```
> [dev] Fix ant to run without extra setup

- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Cherry-pick of: https://github.com/microsoft/CBL-Mariner/pull/375
When pam is built in the toolchain environment, cracklib-devel is not installed. This results in pam's auto configure skipping cracklib integration. However pam's cracklib integration is needed by other packages such as shadowutils.
- Install cracklib before pam is built in the toolchain.
**YES**
- Local end to end build.
> cherry-pick: Install cracklib before building pam

- SPECS/ant/ant.spec
---
cherry-pick of: https://github.com/microsoft/CBL-Mariner/pull/397
`ant` does not work by default after installing it on a clean system. There is an underspecified dependency on `which`. By default `ant` will check `$JAVA_HOME` for the java binary location, or fall back to calling `which java` to find it. Since on a default system `$JAVA_HOME` is not set and `which` is not installed, `ant` cannot find `java` so it will fail.
See the following ant source code: https://github.com/apache/ant/blob/81aee9ec90a14f35c54acb54299e2e23a2749423/src/script/ant#L188
To repro, run the following commands on a clean Core image:
```
root [ / ]# tdnf install ant
....
root [ / ]# ant
We cannot run …
```
> Fix ant to run without extra setup

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
---
1. Reduce error log noise generated by `graphpkgfetcher` when handling SPECs with many dynamic dependencies. Dynamic dependencies become available during the build, so it is expected that they may not be found Upstream. On SPECs with many dynamic dependencies `graphpkgfetcher` would generate hundreds of error messages.
2. Simplify error message  when a dependency could not be resolved to only contain relevant information: what package+version was trying to be cloned and what went wrong.
3. Print packages that were successfully fetched. Besides giving useful information, it also shows progress of the tool. When dealing with SPECs with many dynamic dependencies, `graphpkgfetcher` …
> [dev] Improve graphpkgfetcher logging

- toolkit/tools/internal/logger/log.go
---
Some commands which are run via `ExecuteLiveWithCallback()` (especially in the dev branch) output significantly more than is reasonable to store in the output buffer (1500 lines currently). We already log every line at trace level so there isn't much value in also printing the unbufferable lines at warn level. Just silently drop the unbufferable lines.
- Remove warning about dropping unbufferable stdout/stderr output from `StreamOutput()` when using `printOutputOnError = true`
NO
- Local go build, validated with Joe
> Don't warn about StreamOutput log buffer overflow

- SPECS/qemu-kvm/CVE-2018-12617.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
Backported commits from upstream `qemu` 5.0.0 to our 4.2.0 ([c1](https://github.com/qemu/qemu/commit/5d3586b834633c8ac462d4741b85b4036cbc0f93), [c2](https://github.com/qemu/qemu/commit/ead83a136d54f7faa315922aff26fa11d216909f), [c3](https://github.com/qemu/qemu/commit/1329651fb4d4c5068ad12fd86aff7e52f9e18c34)) to fix CVE-2018-12617.
- Backport three commits from `qemu` 5.0.0 to our version to fully address CVE-2018-12617
NO
- https://nvd.nist.gov/vuln/detail/CVE-2018-12617
- Local build
- Attempted self test via `make check` (test fails, but fails in the same way as prior to fix)
- Will need to be resolved later
> Fix qemu CVE-2018-12617

- SPECS/cpprest/cpprest.spec
- SPECS/libpwquality/libpwquality.spec
- SPECS/libxcrypt/libxcrypt.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We don't define `%ldconfig_scriptlets` as part of our standard RPM macros. So, let's remove the ones that remain in our specs.
- Replace `%ldconfig_scriptlets` with actual `%post`/`%postun` calls to `ldconfig` in libpwquality, cpprest, and libxcrypt.
**YES**
- Running a pipeline build currently
> Remove instances of %ldconfig_scriptlets in specs

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- cgmanifest.json
postgresql v12.5 resolves CVE-2020-25695 and CVE-2020-25694
---
postgresql v12.4 is impacted by CVE-2020-25695 and CVE-2020-25694, v12.5 resolves them.
- Update postgresql to v12.5 to fix CVE-2020-25695 and CVE-2020-25694
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-25695
- https://nvd.nist.gov/vuln/detail/CVE-2020-25694
- Local Build
> Upgrade postgresql to 12.5

- SPECS/libarchive/libarchive.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
libarchive.org/downloads page is returning a 502 error, causing the toolchain build to fail when pulling sources. Updating the source URL for libarchive to GitHub, which will be more reliable. Hash of the source tar is unchanged.
- Update libarchive source URL to pull from GitHub instead of libarchive.org. The hash of the source tar is unchanged.
**YES**
- Local build was able to pull libarchive source from GitHub and the md5sum hash checking section of the toolchain build approved it.
> Update libarchive source URL to GitHub

- SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
- SPECS/kernel/0001-Drivers-hv-vmbus-Allow-cleanup-of-VMBUS_CONNECT_CPU-.patch
- SPECS/kernel/kernel.spec
---
When invoking kexec() on a Linux guest running on a Hyper-V host, the kernel panics. Created and applied kernel patch that fixes this issue. This patch has also been sent upstream.
- Apply patch to `kernel` to fix kexec flow on HyperV
- Bump release numbers of `kernel-signed-<arch>` packages to match the `kernel` package release
NO
Local build and test.
> Fix kexec() flow in HyperV

- SPECS/hyperv-daemons/hv_set_ifconfig
- SPECS/hyperv-daemons/hyperv-daemons.signatures.json
- SPECS/hyperv-daemons/hyperv-daemons.spec
---
Support IP injection.
The current hv_set_ifconfig script from kernel source is used in Mariner. That is a sample script and based on RHEL, this script should be updated or customized based on the network manager used by distribution. Created a new hv_set_ifconfig script to configure the network settings for Mariner.
Added a new script hv_set_ifconfig
``` Package: hypervkvpd```
**NO**
```
1. Tested locally by copying the script in Deployed VM
2. Tested using the newly created hypervkvpd package. 
a. Build a new package(hypervkvpd)
b. Deploy a VM in HyperV Manager
c. Boot the VM & Deploy package
d. Run **NET-IP-INJECTION** from LISA test
e. Test completed successfully.
```
> HyperV IP injection support

- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Clean-up. Unifying toolchain build log file names with package builds.
- Made 2nd phase toolchain package builds generate the same log file names as regular package builds.
No.
- None, minor change.
> Unifying toolchain build log file names with package builds.

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
---
`graphpkgfetcher` may attempt to fetch the same package multiple times, incurring a non trivial time penalty during builds. This penalty is especially prominent when dealing with specs with multiple dynamic dependencies on external packages.
For example an external package `foo` may provide `foo(a)`, `foo(b)`, .... `foo(z)`. Every one of these provides is backed by the same rpm, but local specs may take a dependency on any one of them. Each one is treated as a different unresolved node in the dependency graph.  For each of these unresolved nodes, `graphpkgfetcher` currently resolves the dependency to an exact rpm and then fetches it using `tdnf download`. In its current form, …
> [dev] Skip refetching synonymous provides

- toolkit/tools/imagegen/configuration/systemconfig_test.go
---
Test fails in system config tests if other tests use "validSytemConfig" after the User test. The changes made in the user test persisted and changed expected output.  
- Change badUsers to use a copy of validSystemConfig's users rather than reference.
NO
- local build of go-tools
> Change systemConfig test to copy rather than reference valid users

- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Adding a timestamp to toolchain building logs for the sake of our package test runs and parsing.
- Added a timestamp to toolchain package builds.
No.
- Local toolchain build.
> Adding timestamp to toolchain builds.

- toolkit/docs/security/ca-certificates.md
---
`ca-certificates.md` contains a link to a private ADO instance- replace that with a relative link to the spec the text refers to.
- Link change in ca-certificates.md
NO
- Checked that link works in this branch
> Remove private ADO reference in docs

- toolkit/scripts/pkggen.mk
---
Fixing a `pkggen.mk` bug I've introduced with #436 with an invalid indent.
- Fixed a `pkggen.mk` bug.
No.
> Fixing `pkggen.mk` bug.

- toolkit/tools/grapher/grapher.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/implicitprovides.go
---
During package building the graph is manipulated when injecting implicit provide information. New nodes are added and edges are altered. During this process it is possible for a directed cycle to be created. In its current state cycles are never checked for and some nodes become unsolvable, leading to blocked SRPMs.
The fix is to scan the graph for cycles each time after manipulating it during a package build. If a cycle is found, it should be fixed if possible to keep the graph acyclic. If this is not possible, it should constitute a failed build as the graph is longer solvable.
- Create a common `g.MakeDAG()` call that `grapher` and `scheduler` can use.
- Ensure the graph is a …
> [dev] Ensure the graph is acyclic after injecting implicit provides

- SPECS/qemu-kvm/CVE-2020-25723.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
Patch CVE-2020-25723 in qemu-kvm
- CVE-2020-25723
No
None
- https://nvd.nist.gov/vuln/detail/CVE-2020-25723
Local Build
> Patch CVE-2020-25723 in qemu-kvm

- SPECS/grub2/grub2.spec
- SPECS/perl/perl.spec
- toolkit/resources/manifests/package/macros.override
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Modify specs to fix grub2 and perl check tests. Disable libsoup tests as errors are still seen on build machines when cleaning chroot mountpoints.
- Change perl and grub2 specs
- Add libsoup skip to macros.orverride
**YES**
NO
- Local build
> Fix tests for grub2, perl, and skip libsoup tests

- SPECS/shadow-utils/shadow-utils.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- [x ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [x ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x ] `sudo make go-tidy-all` and `sudo make …
> Remove password aging customized value to set default

- SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
- SPECS/hyperv-daemons/hyperv-daemons.signatures.json
- SPECS/hyperv-daemons/hyperv-daemons.spec
- SPECS/kernel-headers/kernel-headers.signatures.json
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/config
- SPECS/kernel-hyperv/kernel-hyperv.signatures.json
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/CVE-2020-14351.nopatch
- SPECS/kernel/CVE-2020-14381.nopatch
- SPECS/kernel/CVE-2020-25656.nopatch
- SPECS/kernel/CVE-2020-25704.nopatch
- SPECS/kernel/CVE-2020-29534.nopatch
- SPECS/kernel/CVE-2020-29660.nopatch
- SPECS/kernel/CVE-2020-29661.nopatch
- SPECS/kernel/config
- SPECS/kernel/config_aarch64
- SPECS/kernel/kernel.signatures.json
- SPECS/kernel/kernel.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/toolchain-md5sums
- toolkit/scripts/toolchain/container/toolchain-remote-wget-list
- toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
- toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
---
Update kernel source to 5.4.83. New kernel source contains fixes for many kernel CVEs flagged by our tooling so address the CVEs.
- Update kernel-headers, kernel, kernel-hyperv, and hyperv-daemons specs to use 5.4.83
- Refresh version numbers for kernel-signed- specs
- Update toolchain to use 5.4.83 source when building kernel headers
- Address CVE-2020-14351, CVE-2020-14381, CVE-2020-25656, CVE-2020-25704,
CVE-2020-29534, CVE-2020-29660, CVE-2020-29661
- Update cgmanifest's download URLs to point to 5.4.83 source location
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-14351
- https://nvd.nist.gov/vuln/detail/CVE-2020-14381
- https://nvd.nist.gov/vuln/detail/CVE-2020-25656
- …
> Update kernel to 4.5.83, Address 7 kernel CVEs 

- SPECS/ca-certificates/ca-certificates.spec
- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
---
The distroless PR included prebuilt-ca-certificates which had a wrong file list. This PR updates the list, solving the build break.
- Update files for the prebuilt-ca-certificates package
NO
- Local build
> Fix file paths for prebuilt certificates

- toolkit/docs/building/building.md
---
The documentation suggested that using the core update repo is optional, while in reality it is the default behaviour.
- Updated the documentation around the `USE_UPDATE_REPO` argument.
No.
- Viewed the file locally.
> Fixing misleading doc entry about update repo's defaults.

- SPECS/perl/perl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Reverting Perl ptest fix from #465 as it seems to be interfering with our builds. Will re-introduce after the December release.
- Reverted the ptest fixes for Perl.
Yes.
- None, reverting change.
> Reverting ptest fix for Perl from PR #465 (commit: 283d6cd).

- SPECS/python-py/python-py.signatures.json
- SPECS/python-py/python-py.spec
- cgmanifest.json
---
Fixing CVE-2020-29651 by updating `python-py` to 1.10.0. According to the authors the library is in maintenance mode and no significant changes have been made since 1.6.0.
- Fixed CVE-2020-29651.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2020-29651
- Local package build for `python-py` and `pytest`.
> Updating `python-py` to 1.10.0 to fix CVE-2020-29651

- toolkit/README.md
- toolkit/docs/building/building.md
- toolkit/docs/quick_start/quickstart.md
---
This change was instigated due to customer feedback.  This pull request splits the Quick Start Instructions out of the more advanced Building.md instructions.  The Quick Start instructions now focus on building a VHD's and ISO images, and now provides guidance on how to use those images with Hyper-V.  VHD build instructions were added as only VHDX was previously specified.  Because VHD(X)'s need Cloud Init, instructions on how to build and use the sample meta-user-data.iso were also added.  
The original Building.md file is now used for advanced building topics. Clarifications were added to redirect the casual user to the Quick Start.  The instructions for building in stages was …
> Split out Quick Start, Add CBL-Mariner Usage Instructions

- SPECS/unbound/CVE-2020-28935.patch
- SPECS/unbound/unbound.spec
---
- Adding a patch for unbound CVE-2020-28935. I'm using the [patch](https://nlnetlabs.nl/downloads/unbound/patch_cve-2020-28935_unbound.diff) recommended by [NIST](https://nvd.nist.gov/vuln/detail/CVE-2020-28935).
- Added a patch for unbound CVE-2020-28935.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-28935
> Adding a patch for 'unbound' to fix CVE-2020-28935

- SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec
- SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
---
This is a merge of a build fix from the `1.0` branch.
- Aligned contents of `SIGNED-SPECS` with their unsigned counterparts.
No.
- Verified by an end-to-end build on `1.0`.
> Updating signed specs to be aligned with their unsigned counterparts.

- SPECS/perl-WWW-Curl/WWW-Curl-4.17-Adapt-to-changes-in-cURL-7.69.0.patch
- SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
---
After updating to `curl` 7.74.0 this package fails to build. From [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1812910) it seems to be a known issue and I've applied the same patch Fedora used for their release 32 update.
- Applied a fix to enable building with `curl` >= 7.69.0.
No.
- Local package build with tests. Package built, tests passed.
> Adding Fedora 32 patch to make `perl-WWW-Curl` work with new version of `curl`

- toolkit/tools/imagegen/diskutils/diskutils.go
---
Virtual disk devices (i.e., qemu disks) do not enumerate in ISO installer
during the initial search for system block devices. This causes the
installer to fail immediately with "unexpected end of JSON input".
The reason is because virtual disk devices typically have major device
numbers of 252,253,254 and when the installer enumerates the system's
block devices with lsblk, it does not consider these device numbers.
Fix is to add the common virtual disk major device numbers to the
lsblk filter so the installer can enumerate them during startup.
- Add 252,253,254 to `lsblk` filter list
NO
local build
> diskutils: Include virtual disk devices in search

- SPECS/docbook-style-xsl/docbook-style-xsl.spec
- SPECS/guile/guile.spec
- SPECS/keyutils/keyutils.spec
- SPECS/ruby/ruby.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add compatibility symlinks to select packages for broader compatibility and add additional provides to other packages which they satisfy.
- Create compatibility symlinks for `guile*` binaries in the `guile` package.
- Create compatibility symlink from versioned stylesheets to the unversioned path `%{_datadir}/sgml/docbook/xsl-stylesheets` in the `docbook-style-xsl` package.
- Add missing runtime requirement on `docbook-dtd-xml` in the `docbook-style-xsl` package since the xsl stylesheets reference the DTD schema.
- Provide `keyutils-libs` and `keyutils-libs-devel` from `keyutils-devel`.
- Provide `ruby-devel` from the `ruby` package.
**YES**
> [dev] Add additional provides and compatibility links

- SPECS/libmodulemd/libmodulemd.spec
- SPECS/libmodulemd/test_v1_import_headers_timeout.patch
- SPECS/python-attrs/python-attrs.spec
- toolkit/resources/manifests/package/macros.override
---
Fix python-attrs test. Improve reliability of libmodulemd test by increasing timeout. Skip dracut tests which are expected to fail due to missing dependencies
- Fix python-attrs check test
- Add patch to increase timeout in libmodulemd
- Skip dracut in macros.override
YES
**NO**
> Fix test for python-attrs, libmodulemd, skip dracut tests

- SPECS/rust/ignore-linker-output-non-utf8-test.patch
- SPECS/rust/rust.spec
---
Rust package tests were failing due to a missing BR and a bad test- this PR fixes both.
- Add conditional dependency for rust on python-xml when running package tests
- Removed a low signal-to-noise ratio test from Rust. This test was removed in version 1.40.0- more context can be found in rust-lang/rust#63520
NO
> rust: Fix package test

- SPECS/strace/gen_tests_fixes.patch
- SPECS/strace/strace.spec
---
Fix broken strace tests by patching expected results from upstream. The proper values come from the upstream source repo from these two commits.
https://github.com/strace/strace/commit/4377e3a1535a0ec3a42da8a1366ad6943f4efa0e
https://github.com/strace/strace/commit/a75c7c4bcb6b48680275de3e99e17e0ebec811ec
- Patch strace test file
YES
**NO**
- Local package with with RUN_TESTS=y
> Fix check test for strace

- SPECS/kubernetes/golang-1.15-k8s-1.17-test.patch
- SPECS/kubernetes/golang-1.15-k8s-1.18-test.patch
- SPECS/kubernetes/kubernetes-1.17.11.signatures.json
- SPECS/kubernetes/kubernetes-1.17.11.spec
- SPECS/kubernetes/kubernetes-1.17.13.signatures.json
- SPECS/kubernetes/kubernetes-1.17.13.spec
- SPECS/kubernetes/kubernetes-1.18.10.signatures.json
- SPECS/kubernetes/kubernetes-1.18.10.spec
- SPECS/kubernetes/kubernetes-1.18.8.signatures.json
- SPECS/kubernetes/kubernetes-1.18.8.spec
- SPECS/kubernetes/kubernetes-1.19.1.spec
---
nopatch for CVE-2020-8563
fix %check failure when k8s 1.17 or 1.18 are built against golang 1.15
spec files, k8s patch file and CVE nopatch file
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-8563
> Kubernetes: nopatch CVE-2020-8563, fix tests issue when built against golang 1.15 (k8s 1.17 and 1.18)

- toolkit/docs/formats/imageconfig.md
- toolkit/resources/assets/efi/grub/grub.cfg
- toolkit/resources/assets/grub2/grub.cfg
- toolkit/tools/imagegen/attendedinstaller/views/hostnameview/hostnameview.go
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/disk.go
- toolkit/tools/imagegen/configuration/disk_test.go
- toolkit/tools/imagegen/configuration/partition.go
- toolkit/tools/imagegen/configuration/partition_test.go
- toolkit/tools/imagegen/configuration/partitionflag.go
- toolkit/tools/imagegen/configuration/partitionflag_test.go
- toolkit/tools/imagegen/configuration/partitionsetting.go
- toolkit/tools/imagegen/configuration/partitionsetting_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
- toolkit/tools/imagegen/configuration/testdata/test_configuration.json
- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/randomization/randomization.go
- toolkit/tools/internal/randomization/randomization_test.go
- ~~[ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass~~ Partial changes won't pass testing, need all 5/5 PRs.
- ~~[ ] Documentation has been updated to match any changes to the build system~~ Documentation to follow later.
---
Read-only root and dm-verity: This set of 5 PRs will enable dm-verity based read-only root file systems which can detect, and optionally repair modifications to files on the root file system. This supports both basic resilience to corruption as well as a number of additional security features.
PR [1/5] sets up some of the initial groundwork for this feature.
- Move RandomString() to `randomization` package to avoid redefining it for the 3rd time …
> [1/5 verity read-only root] Improve /boot and device mapper support, random string gen

- toolkit/scripts/imggen.mk
- toolkit/scripts/pkggen.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- ~~[ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass~~ Partial changes won't pass testing, need all 5/5 PRs.
- ~~[ ] Documentation has been updated to match any changes to the build system~~ Documentation to follow later.
---
Read-only root and dm-verity: This set of 5 PRs will enable dm-verity based read-only root file systems which can detect, and optionally repair modifications to files on the root file system. This supports both basic resilience to corruption as well as a number of additional security features.
PR [2/5] Enables the configuration checker to look at top level packages to make sure we include any required ones (ie we will need the verity packages to …
> [2/5 verity read-only root] Support validating packages during config check

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/diskutils/initramfs.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- ~~[ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass~~ Partial changes won't pass testing, need all 5/5 PRs.
- ~~[ ] Documentation has been updated to match any changes to the build system~~ Documentation to follow later.
---
Read-only root and dm-verity: This set of 5 PRs will enable dm-verity based read-only root file systems which can detect, and optionally repair modifications to files on the root file system. This supports both basic resilience to corruption as well as a number of additional security features.
PR [3/5] sets up additional groundwork required to support the feature.
- Disk mount/unmount improved
- BlockOnDiskIO will loop until the requested disk …
> [3/5 verity read-only root] Improve mount reliability, initramfs library, TdnfInstall

- SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec
- SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec
- SPECS/kernel-headers/kernel-headers.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The signed kernel specs should match their unsigned counterparts in both version and release tags. They've been out of sync for the dev branch since roughly October. It may not be a necessary change, if the desync hasn't been noticed yet, but it keeps the entanglement check from being red... which is probably a net good.
- kernel-signed-aarch64, kernel-signed-x64, and kernel-headers bumped to 5.4.51-12, to match kernel.
**YES**
- Local build of SRPMs, since this is a low-risk change
> Align kernel specs to have matching Version/Release tags

- SPECS/ruby/ruby.spec
- toolkit/resources/manifests/package/macros.override
---
- Fix ruby tests
- Disable asciidoc and ipv6calc tests, which are missing dependencies. I don't believe it's worth pulling in the dependency packages just for these test cases.
YES
**NO**
> Fix ruby tests and disable asciidoc and ipv6calc tests

- SPECS/e2fsprogs/e2fsprogs.signatures.json
- SPECS/e2fsprogs/e2fsprogs.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/toolchain-md5sums
- toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
Upgrade e2fsprogs to fix CVE-2019-5094 and CVE-2019-5188 in the dev branch.
- Update e2fsprogs from 1.44.6 to 1.45.6
**YES**
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5094
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5188
- Pipeline build id: 59240
> Update e2fsprogs from 1.44.6 to 1.45.6 in dev branch

- toolkit/tools/grapher/grapher.go
---
Fixing `Requires` cycles resolution across specs. Right now if a package from spec "A" run-time depends on a package from spec "B" that's considered an error, while it shouldn't.
This fix is already present inside the `dev` branch: #328.
- Made run-time cycle dependencies non-breaking.
No.
- Local package build run with run-time dependencies between specs.
> Fixing `Requires` cycles resolution across specs.

- SPECS/mariadb/mariadb.spec
---
Fix Mariadb check tests by disabling "test-connect" test which is known to fail (according to LFS: http://www.linuxfromscratch.org/blfs/view/svn/server/mariadb.html)
- Disable "test-connect" test in mariadb spec
YES
**NO**
> Fix test: mariadb

- SPECS/libpng/libpng.spec
---
Moving `Provides: pkgconfig(*)` for `libpng` to correct subpackage. So far we've been saying that the default `libpng` package is providing the package configs, while in reality they are included inside the `libpng-devel` subpackage. This is breaking any build depending on `pkgconfig(libpng)` or `pkgconfig(libpng16)`.
- Moved `Provides: pkgconfig(*)` for `libpng` to correct subpackage.
- Performed a linter spec clean-up.
No.
- None - simple configuration change.
> Moving "Provides: pkgconfig(*)" for "libpng" to correct subpackage.

- SPECS/e2fsprogs/CVE-2019-5188.patch
- SPECS/e2fsprogs/e2fsprogs.spec
- SPECS/e2fsprogs/libsupport-add-checks-to-prevent-buffer-overrun-bugs-CVE-2019-5094.patch
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2019-5094 and CVE-2019-5188 for `e2fsprogs` package in the 1.0 branch.
- fix CVE-2019-5094
- fix CVE-2019-5188
**YES**
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5094
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5188
- Pipeline build id: 59147
> Patch e2fsprogs CVE-2019-5094, CVE-2019-5188

- SPECS/kubernetes/kubernetes-1.17.13.signatures.json
- SPECS/kubernetes/kubernetes-1.17.13.spec
- SPECS/kubernetes/kubernetes-1.18.10.signatures.json
- SPECS/kubernetes/kubernetes-1.18.10.spec
- SPECS/kubernetes/kubernetes-1.19.3.signatures.json
- SPECS/kubernetes/kubernetes-1.19.3.spec
- cgmanifest.json
- toolkit/scripts/kubernertes-container/CreateContainerImages.sh
---
apply hotfixes for 1.19.3, 1.18.10 and 1.17.13
fix issue in script that builds k8s container when used from an Azure ADO pipeline
update relevant kubernetes's specs and CreateContainerImages.sh script
NO
> kubernetes: apply hotfixes for 1.19.3, 1.18.10 and 1.17.13 and fix container script

- SPECS/sudo/sudo.signatures.json
- SPECS/sudo/sudo.spec
- cgmanifest.json
---
This change updates sudo package to fix CVE-2021-23240.
- Update sudo to 1.9.5p1, fixing CVE-2021-23240 .
NO
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-23240
> Update sudo package to 1.9.5p1

- SPECS/python-cryptography/CVE-2020-25659.patch
- SPECS/python-cryptography/python-cryptography.spec
Backport CVE-2020-25659 patch to python-cryptography 2.3.1
---
Patch python-cryptography CVE-2020-25659
- Patch python-cryptography CVE-2020-25659
***NO***
- https://nvd.nist.gov/vuln/detail/CVE-2020-25659
- Local build
> Patch python-cryptography CVE-2020-25659

- SPECS/mariner-repos/mariner-repos.signatures.json
- SPECS/mariner-repos/mariner-repos.spec
- SPECS/mariner-repos/mariner-ui-preview.repo
- SPECS/mariner-repos/mariner-ui.repo
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We've recently set-up some new repositories on PMC and thus need to also provide appropriate .repo files.
- Added .repo files to point to the new repositories.
No.
> Extending `mariner-repos`.

- SPECS/WALinuxAgent/WALinuxAgent.spec
---
Currently WALinuxAgent is trying to write its log to /var/log/waagent.log, but that file is a symlink to /opt/waagent/log/waagent.log. Since /opt/waagent/log is not created by the package, those writes are silently failing. This change removes the symlink and just lets waagent log into /var/log/waagent.log directly.
- WALinuxAgent no longer creates the /var/log/waagent.log as a symlink and instead logs there directly.
**NO**
- Local build and installation
> WALinuxAgent change log directory

- SPECS/gnutls/gnutls.spec
---
Fix check tests for gnutls. Add missing dependency packages. Fix the default trust store file during configure; which resolves the error "doit:64: no certificates were found in system trust store!" from the "trust-store" test.
- Fix check tests for gnutls
YES
**NO**
> Fix check tests for: gnutls

- SPECS/sudo/sudo.signatures.json
- SPECS/sudo/sudo.spec
- cgmanifest.json
---
This PR fixes the regression in sudo regarding the default wheel group addition to sudoers. It also fixes CVE and makes prompt look nicer.
-   Update to version 1.9.5.p2 to fix CVE-2021-3156.
-   Change the password prompt to include ": " at the end.
-   Unconditionally add wheel/sudo groups.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3156
- Local build, buddy buid
> Fix sudo CVE-2021-3156 and sudoer config.

- toolkit/scripts/toolchain/cross/gcc_cross.sh
- toolkit/scripts/toolchain/cross/pathmax.patch
This PR adds a script that can be used to build the GCC cross-target toolchain targeting aarch64-linux. It downloads the source zips required and then creates a directory to build (under $HOME/cross and a separate directory to install the toolset at /opt/cross). I verified that the compiled GCC binary builds a simple lambda test cpp file and generates an ARM64 binary.
> Script to cross compile GCC for aarch64-linux

- toolkit/docs/formats/imageconfig.md
- toolkit/docs/security/intro.md
- toolkit/docs/security/read-only-roots.md
---
Read-only root and dm-verity: This set of ~~5~~ 6 PRs will enable dm-verity based read-only root file systems which can detect, and optionally repair modifications to files on the root file system. This supports both basic resilience to corruption as well as a number of additional security features.
PR [6/5] Adds documentation.
- Add documentation for read-only roots.
NO
None, only doc changes
> [6/5 verity read-only root] Read-only root configuraiton documentation

- SPECS/python3/CVE-2021-3177.patch
- SPECS/python3/python3.spec
---
Addresses CVE-2021-3177 in Python 3 package, moves package to autosetup.
- Addresses CVE-2021-3177 in Python 3 package.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3177
- Not Yet Completed
> Fixes CVE-2021-3177 in Python 3

- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/depsolver.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
Fix `scheduler`'s usage of its reader-writer mutex used to protect the graph. This mutex is currently passed by value, resulting in each routine having its own unique mutex, rendering it effectively a no-op. The fix is to pass this mutex by reference, so all routines are using the same mutex.
- In `scheduler`, pass the graph reader-writer mutex by reference instead of by value.
NO
- Local build.
> [dev] Fix mutex usage in scheduler

- .github/workflows/trigger-release-build.yml
---
This PR adds an automatic trigger of a release pipeline after merging a PR into 1.0 branch.
- Add automated build trigger for release PR
NO
> Add automated build trigger for release PR

- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/prebuilt.go
- toolkit/tools/specreader/specreader.go
---
Update `scheduler` to use the dependency graph to find all RPMs a given SRPM will produce instead of querying the spec. Querying the spec on the host system runs into problems when the spec uses complex macros that are defined in `mariner-rpm-macros` but not the host system. Instead, leverage the information already captured by `specreader` in the CBL-Mariner context.
Currently the dependency graph references RPMs that do not actually exist, e.g. if a spec does not produce a main package but instead only produces a subpackage, specreader will still return that the spec has a main rpm package. The fix for this is to alter the `rpmspec` invocation to only query RPM headers for …
> [dev] Use dependency graph to calculate RPMs from an SRPM

- SPECS/cppunit/cppunit.spec
---
Fix runtime requirement for cppunit-devel
- Add cppunit as runtime requirement for cppunit-devel
**YES**
NO
- #xxxx
- Local Build
> [dev] Fix runtime requirement for cppunit-devel

- .github/workflows/validate-cg-manifest.sh
- SPECS/azure-storage-cpp/azure-storage-cpp.spec
---
RPM complains about un-escaped macros in spec comments. However, the cgmanifest check doesn't handle escaped macros in `#Source0` lines properly when calculating `$source0alt`. This PR modifies the `sed` expression to handle this case.
- Handle escaped name/version/url macros in `#Source0` lines during the cgmanifest check.
NO
> Fix handling of double-percent in cgmanifest check

- .github/workflows/validate-cg-manifest.sh
---
This is just fixing some small issues in our cgmanifest-checking script + addressing simple bash linter's (`SpellCheck` extensions for VS Code) suggestions.
- Fixed `$@` expansion in the `for` loop to not re-expand elements with whitespaces in them.
- Added a missing `$`.
- Simple clean-up.
No.
- N/A.
> Addressing a few bash script issues highlighted by "SpellCheck".

- SPECS/dracut/dracut.spec
- toolkit/imageconfigs/core-fips.json
- toolkit/imageconfigs/packagelists/fips-packages.json
---
40-fips.conf adds the dracut "fips" module to the initramfs. Currently, we install this config in `/usr/lib/dracut.conf.d/`. This config should be installed in `/etc/dracut.conf.d/` since:
- Other Mariner dracut configs (fscks.conf and verity.conf) are installed in  `/etc/dracut.conf.d/`
- RHEL8 installs this conf in `/etc/dracut.conf.d/`
- Mariner's `initramfs` package does initramfs regeneration if `/etc/dracut.conf.d/` is modified. Initramfs regeneration is not triggered by `/usr/lib/dracut.conf.d/`.
Also, in core-fips image config, place `dracut-fips` package before `initramfs` package to prevent extra initramfs generation. This is a perf boost.
- Move dracut FIPS config to …
> Move dracut FIPS config to /etc/dracut.conf.d/

- toolkit/scripts/toolchain/cross/kernel_cross.sh
This script uses the baseline cross-compile toolchain to build the
linux kernel. It then installs the kernel image and modules into the
sysroot directory.
> [cross] add basic kernel cross compile script

- toolkit/scripts/toolchain/cross/generate_minimal_rootfs.sh
- toolkit/scripts/toolchain/cross/inittab
- toolkit/scripts/toolchain/cross/kernel_cross.sh
- toolkit/scripts/toolchain/cross/launch_qemu.sh
Update the kernel_cross script to also install the kernel image
into a standalone kernel folder under /opt/cross/kernel
Add a minimal init script and generate a minimal rootfs from the
contents of sysroot. Compress the rootfs into a gzipped cpio
archive which qemu can easily ingest as an initrd
Add a script to launch qemu-system-aarch64 with the special
settings needed to boot our standalone kernel and rootfs as an
initrd.
> [cross] create minimal aarch64 image that boots in qemu 

- toolkit/tools/grapher/grapher.go
- toolkit/tools/internal/pkggraph/cyclefind.go
- toolkit/tools/internal/pkggraph/cyclefind_test.go
- toolkit/tools/internal/pkggraph/pkggraph.go
---
Currently if a dependency graph is too large, grapher will consume excessive amounts of memory resulting in an out-of-memory crash on most reasonably resourced systems. On a local build machine, a 65MB dependency graph exhausted all 32GB of RAM.
The excessive memory usage stems from the dependency graph's cycle detection algorithm: [Johnson's algorithm](https://en.wikipedia.org/wiki/Johnson's_algorithm). While this works well for smaller dependency graphs, it is calculating a significant amount of extra information that is not needed by grapher, primarily it finds all cycles in a given graph. 
Grapher's cycle resolution code iteratively fixes one cycle at a time and then …
> [dev] Rework cycle detection in dependency graph to scale with larger graphs

- SPECS-CROSS/kernel-headers_cross/kernel-headers_cross.spec
%{arch} was not being set appropriately. Update the arch check
macro to consider the target architecture we are building for.
> [cross] kernel-headers: update arch macro to use target arch

- toolkit/scripts/toolchain/cross/aarch64-linux-gnu.xfail
- toolkit/scripts/toolchain/cross/gcc_cross_test.sh
This change adds the GCC emulation tests to the existing `gcc_cross_test.sh` script. There were some tests that weren't passing and seemed to be broken tests. I disabled them by adding them to a .xfail file so we have a clean baseline.
I tested the script in a new Ubuntu docker environment after running the `gcc_cross.sh` script to build the gcc cross toolchain. The docker environment is in an Ubuntu VM (run via Hyper-V) and the emulation tests took about 12 minutes to run on my 8 core Ryzen CPU.
> [cross] GCC emulation tests

- toolkit/tools/cgmanifest.json
- toolkit/tools/go.mod
- toolkit/tools/go.sum
- toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go
- toolkit/tools/imagegen/attendedinstaller/primitives/progressbar/progressbar.go
- toolkit/tools/imagegen/attendedinstaller/speakuputils/speakuputils.go
- toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go
- toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
The installer does not meet some accessibility requirements, when it comes to things like contrast and screen reading. This PR adds some tweaks to meet those requirements.
- Tweak and remove sections that are tricky for speakup to read in a sensible manner
- Adjust contrast in the exit modal
NO
- Local test of image
> Tweak installer to meet accessibility standards

- SPECS-CROSS/aarch64-mariner-linux-gnu-prebuilt-toolchain/aarch64-mariner-linux-gnu-prebuilt-toolchain.signatures.json
- SPECS-CROSS/aarch64-mariner-linux-gnu-prebuilt-toolchain/aarch64-mariner-linux-gnu-prebuilt-toolchain.spec
- SPECS-CROSS/aarch64-none-linux-gnu-toolchain/aarch64-none-linux-gnu-toolchain.signatures.json
- SPECS-CROSS/aarch64-none-linux-gnu-toolchain/aarch64-none-linux-gnu-toolchain.spec
- toolkit/scripts/toolchain/cross/busybox_container.sh
- toolkit/scripts/toolchain/cross/busybox_cross.sh
- toolkit/scripts/toolchain/cross/gcc_cross.sh
- toolkit/scripts/toolchain/cross/generate_minimal_rootfs.sh
- toolkit/scripts/toolchain/cross/kernel_cross.sh
This adds two cross compiling toolchain packages:
1. aarch64-mariner-linux-gnu-prebuilt-toolchain
2. aarch64-none-linux-gnu-toolchain
aarch64-mariner-linux-gnu-prebuilt-toolchain
package contains the prebuilt binaries generated from running the
cross toolchain scripts in the toolkit folder. We will use this
as a stop-gap while the actual aarch64-mariner-linux-gnu-toolchain
is being created.
Additionally set AutoReqProv no. By default, rpmbuild will
dynamically scan for provides/requires. So by default this
aarch64-linux-gnu-prebuilt-toolchain package leads to
unsatisfiable requires, found when installing the resulting package.
So tell rpmbuild not to do this.
aarch64-none-linux-gnu-toolchain adds the ARM/Linaro GCC 9.2
cross compiler toolchain so we can sanity check our cross compile …
> [cross] Add prebuilt cross compiling toolchains for early testing

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/diskutils/diskutils_test.go
---
In `diskutils.go`, the `blockDeviceInfo` struct is populated by lsblk's json output. In util-linux 2.33, the output format was changed from "every value is a string!" to "let's use the number type where it makes sense to do so". The current type of `blockDeviceInfo.Size` is `string`, so we get an error trying to unmarshal input from the newer util-linux versions. By changing `Size` to be a `json.Number`, the unmarshaler knows that it should accept either a quoted string or a number input. 
It's a bit odd that the unmarshaler accepts a string for `json.Number`... but the type underlying `json.Number` seems to be just a `string`, so we roll with it.
Currently we ship util-linux …
> [Tools] Fix parsing of new lsblk JSON output format in diskutils

- toolkit/Makefile
---
Fix two Makefile nits- nothing is broken, it's just grating to my eyeballs.
- Remove duplicate SSH_KEY_FILE definition
- Remove trailing path separator at the end of `toolchain_rpms_dir`
NO
- Local test of builds using affected variables
> Fix Makefile nits

- SPECS/gdb/gdb.spec
- SPECS/libxml2/libxml2.spec
- SPECS/net-snmp/net-snmp.spec
- SPECS/python-werkzeug/python-werkzeug.spec
- toolkit/resources/manifests/package/macros.override
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix tests for gdb, libxml2, net-snmp, python-werkzeug, skip python-psutil tests
- gdb tests: restrict check section to gdb.base default tests, since many of the gdb tests are known to fail (see http://www.linuxfromscratch.org/blfs/view/9.0/general/gdb.html)
- libxml2 tests: skip known bad python tests (we seem to have the same failures as F30 as seen here: https://github.com/GNOME/libxml2/commit/9acef289285008f81b4b66b4880baf600773cf67)
- net-snmp tests: run unit-tests in check section. This avoids the flaky tests in the testing/fulltests/default directory
- python-werkzeug tests: use tox to run tests. Remove test_cache tests that are not being maintained upstream and were …
> Fix tests for gdb, libxml2, net-snmp, python-werkzeug, skip python-psutil tests

- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
---
Images configs may create multiple unmounted partitions. They will all have the same mount point (`""`). The duplicate mount point detection was flagging these as conflicting. Don't check empty mount points for duplication to avoid this.
- Don't validate partition mounts are not duplicated when they are not mounted (ie `PartitionSetting.MountPoint = ""`)
- Add test to check this case
NO
- Local unit tests
- Ran validation against problematic config file
> Fix issue with multiple empty mount validation

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- cgmanifest.json
---
Update the postgresql version from 12.5 to 12.6 to fix CVE-2021-3393 and CVE-2021-20229 
Update the postgresql version from 12.5 to 12.6 to fix CVE-2021-3393 and CVE-2021-20229 
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-20229
local build
> Update postgresql for CVE-2021-20229 & CVE-2021-3393

- SPECS/libpng/libpng-fix-pngtest-random-failures.patch
- SPECS/libpng/libpng.spec
---
Add patch to fix random test failure in libpng
- Add libpng test patch
YES
**NO**
> Fix libpng random test failure

- SPECS/espeak-ng/espeak-ng.spec
- SPECS/espeak-ng/tests-fix-greek-letter-variants.patch
- SPECS/espeak-ng/tests-newline-fixes.patch
---
Initial addition of espeak-ng was missing a fix for the `language-pronunciation` test regarding Greek letters. This adds that in
- Add missing greek letter patch
- Change other patch to account for new patch
NO
> Fix failing test for espeak-ng

- toolkit/tools/imagegen/diskutils/diskutils.go
---
Our ISO installer, via diskutils, checks to see if there are valid disks
to install to before proceeding. If we boot the ISO on hardware where
the installer cannot find any disks, the installer panics with a very cryptic
error message:
PANI[0000] unexpected end of JSON input
This message leads people to believe that the error is with their
imageconfig JSON file, but in reality, the JSON referenced here is
from the output of our lsblk command. We use lsblk to see if the
system has any disks we can install to and we get this output in JSON
format. So in the case where no supported disk is found, we end up
feeding an empty JSON input into the json.Unmarshal() and we get
this panic …
> diskutils: add clearer error when no disk found

- SPECS-CROSS/binutils_cross/binutils_cross.spec
- SPECS-CROSS/cross-gcc/cross-gcc.spec
- SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap2_cross.spec
- SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap3_cross.spec
- SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap_cross.spec
- SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap2_cross.spec
- SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap_cross.spec
When running the build packages on the cross specs folder, the
cross toolchain packages are flagged as buildable for the target
arch. However, we do not want to have these packages build for
the target arch.
So add the ExclusiveArch field.
> [cross] cross-toolchain: Add ExclusiveArch

- toolkit/tools/imagegen/diskutils/diskutils.go
---
Currently, there is an issue where if when we attempt to partition a
virtual disk (/dev/vd*), we make the incorrect choice to append the
"p#" suffix for the partition name, thus failing the partitioning.
Instead of making certain assumptions about the path prefix,
let's actually detect the partition file in /dev and use that
knowledge to inform the rest of the partition initialization
- Test if specific /dev/<path># file exists. If not, test if /dev/path#p# exists. If not, bail.
NO
Local build
> diskutils: refactor partition detection

- SPECS/wpa_supplicant/CVE-2021-0326.patch
- SPECS/wpa_supplicant/CVE-2021-27803.patch
- SPECS/wpa_supplicant/wpa_supplicant.spec
---
Patch CVE-2021-0326, CVE-2021-27803 in wpa_supplicant. We aren't susceptible to either of these, since we don't build with `CONFIG_P2P=y` in our `wpa_supplicant` config, but we might as well add them.
- Patch CVE-2021-0326, CVE-2021-27803 in wpa_supplicant
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-0326
- https://nvd.nist.gov/vuln/detail/CVE-2021-27803
> Patch CVE-2021-0326, CVE-2021-27803 in wpa_supplicant

- toolkit/scripts/toolchain.mk
---
This PR aims at reducing the noise and confusion around the logs printed during toolchain RPMs download for derivative builds.
**Current successful** download:
```
mkdir -p /home/pawel/CBL-MarinerDemo/toolkit/../build/rpm_cache/cache/x86_64/ && \
cd /home/pawel/CBL-MarinerDemo/toolkit/../build/rpm_cache/cache/x86_64/ && \
for url in https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms; do \
wget ${url}/bash-4.4.18-6.cm1.x86_64.rpm \
--no-verbose \
\
\
&& \
break; \
done || { echo "Loop in /home/pawel/CBL-MarinerDemo/toolkit/../build/rpm_cache/cache/x86_64/bash-4.4.18-6.cm1.x86_64.rpm failed" ; …
```
> Improving toolchain download logs.

- SPECS/dnf/dnf.spec
- SPECS/libstoragemgmt/libstoragemgmt.spec
---
Package bash-completion files properly in packages that autodetect directory from pkg-config
- Use proper bash-completion dir in dnf, libstoragemgmt
NO
- Build of affected packages
> Package bash-completion files properly in packages that autodetect directory from pkg-config

- toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
---
Our test community builds are often failing due to download issues while trying to build the jdk8 part of the toolchain. Every now and then we'll get the 500 error, which is gone with the next retry, so I'm adding retry logic to our scripts until we're able to secure a more reliable source of the tarballs.
- Added retry logic to jdk8 source tarballs downloads
No.
- Internal community build.
> Adding retries to jdk8 tarballs downloads during toolchain builds

- toolkit/docs/building/building.md
- toolkit/tools/srpmpacker/srpmpacker.go
---
srpmpacker currently uses either the certificates provided with CA_CERT or none at all. This change enables the tool to also use the system provided certificates to authenticate to the provided SOURCE_URL.
This resolves the following error which would be seen when providing a SOURCE_URL that is trusted by the system cert store but not CA_CERT:
Error: Get "https://foo": x509: certificate signed by unknown authority
- Modify srpmpacker to use SystemCertPool()
YES
**NO**
- Local build  calling "sudo make expand-specs REBUILD_TOOLS=y SOURCE_URL=..." with and without setting CA_CERT
> Modify SRPMPacker tool to use system cert pool

- toolkit/tools/imagegen/diskutils/diskutils.go
---
```SetupLoopbackDevice``` does not account for a partitioned image being added to a loop device. While this function is currently only used with empty raws, ```SetupLoopbackDevice``` would result in misconfigured devices if in the future someone uses this function with a full raw image.
I ran across this issue while running this command outside of the function on a pipeline with a partitioned raw image. The result was nondeterministic behavior on the number of partitions and their sizes recognized by lsblk. 
Description of flag
--P, --partscan
Force the kernel to scan the partition table on a newly created loop device. Note that the partition table parsing depends on sector …
> diskutils: Add partscan flag to losetup cmd

- SPECS/cloud-utils-growpart/cloud-utils-growpart.signatures.json
- SPECS/cloud-utils-growpart/cloud-utils-growpart.spec
- cgmanifest.json
---
With the 5.10.13.1 kernel we're hitting an error in cloud-utils version 0.30 growpart where it doesn't parse kernel versions robustly. This is causing growpart to fail and stopping the rootfs from being resized to fill the remainder of the disk. Updating to cloud-utils version 0.32 fixes the bug.
- Update cloud-utils-growpart to version 0.32
NO
- Azure VM with this updated cloud-utils-growpart and kernel 5.10.13.1 successfully resizes the rootfs
> Update cloud-utils-growpart to 0.32 to fix kver parsing

- toolkit/docs/building/building.md
- toolkit/tools/srpmpacker/srpmpacker.go
---
srpmpacker currently uses either the certificates provided with CA_CERT or none at all. This change enables the tool to also use the system provided certificates to authenticate to the provided SOURCE_URL.
This resolves the following error which would be seen when providing a SOURCE_URL that is trusted by the system cert store but not CA_CERT:
Error: Get "https://foo": x509: certificate signed by unknown authority
- Porting from 1.0-dev branch: #739 
YES
**NO**
- Local builds. "sudo make go-tools REBUILD_TOOLS=y", "sudo make expand-specs REBUILD_TOOLS=y SOURCE_URL=..."
> Modify SRPMPacker tool to use system cert pool (dev branch)

- toolkit/scripts/srpm_expand.mk
---
I keep my repo nested a bit deep in my home directory. Because of this, Make errors out in the `$(STATUS_FLAGS_DIR)/build_specs.flag` target due to the expansion of `$(srpms)`, which contains the full path of each SRPM. Specifically, `sh` does not like having extremely long arguments. So, I modified the loop to only use the basename of each srpm, which keeps the length under `sh`'s comfort level.
- Change loop in `$(STATUS_FLAGS_DIR)/build_specs.flag` target to use basenames of SRPMs instead of full paths
NO
- Used with local build
> [dev] Curb expansion in srpm_expand.mk

- SPECS/coredns/coredns-1.6.5.spec
- SPECS/coredns/coredns-1.6.7.spec
- SPECS/coredns/coredns-1.7.0.spec
---
Minimal change to unify `coredns` specs to simplify automation efforts.
- Switched to using macros instead of hard-coded versions in the source URL.
No.
- None, minor change in comments.
> Unifying `coredns` specs for the sake of automation.

- .github/workflows/quickstart_1.0.yml
- toolkit/docs/building/prerequisites.md
- toolkit/tools/imagegen/diskutils/diskutils.go
---
* diskutils: Add partprobe after partition creation
There can be a timing issue where partition creation finishes but the
devtmpfs files are not populated in time for partition initialization.
So to deal with this, we call partprobe here to query and flush the
partition table information, which should enforce that the devtmpfs
files are created when partprobe returns control.
* diskutils: invoke partprobe with flock
Added flock because "partprobe -s" apparently doesn't always block.
flock is part of the util-linux package and helps to synchronize access
with other cooperating processes. The important part is it will block
if the fd is busy, and then execute the command. Adding a …
> diskutils: Add partprobe after partition creation

- SPECS/libtiff/CVE-2020-35522.patch
- SPECS/libtiff/CVE-2020-35523.patch
- SPECS/libtiff/CVE-2020-35524.patch
- SPECS/libtiff/libtiff.spec
---
Fixes for CVE-2020-35521, CVE-2020-35522, CVE-2020-35523, CVE-2020-35524
YES
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-35521
- https://nvd.nist.gov/vuln/detail/CVE-2020-35522
- https://nvd.nist.gov/vuln/detail/CVE-2020-35523
- https://nvd.nist.gov/vuln/detail/CVE-2020-35524
Ran self-test
time="2021-03-20T00:54:49-07:00" level=debug msg="============================================================================"
time="2021-03-20T00:54:49-07:00" level=debug msg="Testsuite summary for LibTIFF Software 4.1.0"
time="2021-03-20T00:54:49-07:00" level=debug msg="============================================================================"
**time="2021-03-20T00:54:49-07:00" …
> Fixes for CVE-2020-35521, CVE-2020-35522, CVE-2020-35523, CVE-2020-35524

- SPECS/ruby/macros.rubygems
- SPECS/ruby/ruby.signatures.json
- SPECS/ruby/ruby.spec
---
- Add bindir path to install rubygem executables under system bin directory instead of the bin directory created under the
gem home directory to correctly build some rubygem packages.
- Add more provides from ruby which will be used by other packages to build
- Add bindir path to gem installation to install executable at
system bin directory instead of bin directory under gem home directory
- Add Provides for rubygem-bigdecimal, rubygem-irb, rubygem-io-console, rubygem-did_you_mean
and rubygem-psych
NO
- #xxxx
- Local Build
> [dev] Update ruby spec

- toolkit/tools/imagegen/configuration/partitionflag.go
- toolkit/tools/imagegen/configuration/partitionflag_test.go
- toolkit/tools/imagegen/diskutils/diskutils.go
---
When we released the initial tools, "bios-grub" was a valid partition
Flag in the image configuration JSON. At some point, it got dropped
in favor of "bios_grub". However calamares GUI ISO installer produces
config files with the original "bios-grub" flag. So this change
restores the "bios-grub" flag as a legacy option. We still prefer
users to use "bios_grub" going forward.
NO
Local build. Tested GUI ISO install on Gen1
> add bios-grub partition flag

- SPECS/openssh/openssh.spec
---
Under the current default sshd_config settings SSH connections to Azure VMs are timing out after a period of user inactivity. This behavior does not occur on other images available on the platform. In order to fix this I've updated the default settings we're toggling in the sshd_config to more closely match those other distros. I've also reworked how we're setting values in sshd_config to do it in place instead with sed of blobbing them onto the end.
Additionally I cleaned up a little non-idiomatic spec syntax in favor of macros.
- Add the following changes to sshd_config
- Set PrintMotd to no
- Set PermitUserEnvironment to no
- Set ClientAliveInterval to 120
- Set UsePAM to yes …
> Update default sshd_config to match other distros

- SPECS/redis/redis.spec
---
CVE-2021-21309 affects only 32-bit redis executables. Mariner does not support nor build executables on any 32-bit system. Additionally we append flags such as -m64 to ensure 64-bit executables.
- Add nopatch for CVE-2021-21309
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-21309
- Pipeline build id: 74857
> Add nopatch for CVE-2021-21309 for redis

- SPECS-CROSS/cross-gcc/cross-gcc.spec
This change fixes two bugs in the cross gcc package:
1. Missing `libmpc` dependency
`libmpc` is needed when running the cross gcc package. A `Requires: libmpc` dependency was added to the cross gcc spec file to make sure that it's installed when the cross gcc package is installed. 
Testing in a Mariner container: Verified by trying to install the cross gcc package without the `libmpc` package installed. The installation failed. I then installed the libmpc package and tried installing the cross gcc package. The installation passed and gcc was able to find libmpc.
2. sysroot include headers not being found by cross gcc
The cross gcc tools were unable to find the sysroot include headers when gcc was invoked. Using the `-E -Wp,-v -` flags when invoking gcc, I found the header include paths it …
> Fix two bugs in cross gcc package

- .github/workflows/go-test-coverage.yml
- .github/workflows/quickstart_1.0.yml
---
Update workflows to use golang 1.15 to match our current version
- Change go-test-coverage.yml golang version
- Change quickstart_1.0.yml golang version
YES
**NO**
- Not validated (unsure how to test), but this is a trivial change
> Update workflows to use golang 1.15

- SPECS/busybox/CVE-2021-28831.patch
- SPECS/busybox/busybox.spec
---
Patch busybox CVE-2021-28831
- Patch busybox CVE-2021-28831
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-28831
- Local build
> busybox patch CVE-2021-28831

- toolkit/tools/cgmanifest.json
- toolkit/tools/go.mod
- toolkit/tools/go.sum
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/internal/sliceutils/sliceutils.go
- toolkit/tools/pkgworker/pkgworker.go
---
We've recently discovered an issue, where releasing a new version/release of a package, which is part of the pre-installed set of worker chroot packages, would break derivatives using older versions of the toolkit. The reason behind bug, was `tdnf install` finding a newer version of the package, but refusing to install it, since the same package (but with an older version) was already present inside the chroot.
We want to make sure derivatives build with the versions of the packages provided by the toolkit they are using and **not** silently update the packages without their knowledge. This is an initial step bringing us closer to that goal, where we remove any pre-installed …
> Fixing older toolkit builds. Ignoring 'BuildRequires' on pre-installed packages.

- toolkit/tools/imagegen/attendedinstaller/views/diskview/autopartitionwidget/autopartitionwidget.go
- toolkit/tools/imagegen/attendedinstaller/views/installationview/installationview.go
- toolkit/tools/imagegen/attendedinstaller/views/installerview/installerview.go
---
Remove shortcuts from ISO installer views for improved text-to-speech accessibility
- Removes shortcuts from `AutoPartitionWidget`, `InstallationView`, `InstallerView` views
NO
- Built and ran ISO with full configuration
> Remove shortcuts from ISO installer views

- .github/pull_request_template.md
---
Updates PR template with new cgmanifest and license map files. Also pulls in a better placeholder CVE url from the `main` branch.
- Add `.github/workflows/cgmanifest.json` to list of cgmanifest files to check
- Add `./SPECS/LICENSES-AND-NOTICES/data/licenses.json` to list of license map files
- Use a better placeholder CVE url
NO
- N/A
> Update PR template with new files

- toolkit/Makefile
- toolkit/scripts/pkggen.mk
- toolkit/scripts/srpm_expand.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/toolchain.mk
- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
This PR aims at reducing the noise and confusion around the logs printed during RPMs builds.
Used `realpath` to make file paths shorter and easier to follow.
We no longer directly print the bash command inside the .mk file, since it mostly produced a long list of file paths without providing any explanation to what is happening. Similarly, we were printing the output from `cpio` listing all extracted files for each SRPM and number of blocks:
```
for srpm in /home/pawel/CBL-Mariner_package_tests2/toolkit/../build/INTERMEDIATE_SRPMS/pyOpenSSL-18.0.0-6.cm1.src.rpm
/home/pawel/CBL-Mariner_package_tests2/toolkit/../build/INTERMEDIATE_SRPMS/ntp-4.2.8p13-3.cm1.src.rpm …
```
> Cleaning SRPM expansion and chroot creation console output

- toolkit/tools/imagegen/diskutils/diskutils.go
---
This change has two parts:
* diskutils: always flock disk/partition operations
Parted can't be trusted to fully complete all disk operations by
the time it returns control. So add flock to every disk or partition
operation.
Also add a flock partprobe -s command after parted commands but before
any other non-parted command could run.
* diskutils: add retry logic
Partition creation and dynamic /dev file generation are still racing and all
the "fixes" that supposedly prevent these timing issues are just not
sufficient to fully solve the problem. So add retry logic to deal with
this problem. Not ideal but also not worth wasting any more cycles on this.
Signed-off-by: Chris Co …
> diskutils: add more robust handling of disk/partition operations

- SPECS/qemu-kvm/CVE-2021-3416.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
Patch CVE-2021-3416 and add tests to qemu-kvm
- Patch CVE-2021-3416. Add test modules under check section.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3416
- Local build
> Patch CVE-2021-3416 and add tests to qemu-kvm

- toolkit/docs/formats/imageconfig.md
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/testdata/test_configuration.json
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
---
`Hidepid` is a mount option that prevents proc ids from being visible to all users. Without it, a non-privileged user can see all process identifiers (PIDs) and can `cat` the pid to see which process is involved.
Therefore, set ` hidepid` by default and allow users to opt out using the `HidepidDisable` config option. In order for these options to persist, the mount point is added to the fstab file. 
Since `/proc` is a pseudo file system, an argument was added to `addEntryToFstab` that specifies whether the mountpoint relates to a pseudo file system (such as /proc, /sys). This argument allows `device` to be set to the given path and the `pass num` be set to `0` since fsck checking …
> Configure /proc with hidepid by default and add doPseudoFsMount to addEntryToFstab

- SPECS/qemu-kvm/CVE-2021-3392.patch
- SPECS/qemu-kvm/CVE-2021-3409.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
Add patch to qemu-kvm to fix CVE-2021-3392 and CVE-2021-3409
- Add patch to qemu-kvm to fix CVE-2021-3392 and CVE-2021-3409
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3409
- https://nvd.nist.gov/vuln/detail/CVE-2021-3392
- Local build
> Fix CVE-2021-3392 and CVE-2021-3409 in qemu-kvm

- SPECS/redis/CVE-2021-3470.patch
- SPECS/redis/redis.spec
- SPECS/wpa_supplicant/CVE-2021-30004.patch
- SPECS/wpa_supplicant/wpa_supplicant.spec
---
Adding CVE-2021-3470 for redis and CVE-2021-30004 for wpa_supplicant.
- Change
Add CVE-2021-3470
- Change
Add CVE-2021-30004
YES
**NO**
- #xxxx
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-30004
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-3470 
Locally built both redis and wpa_supplicant packages with CVEs.
> Add CVE-2021-3470 for redis and CVE-2021-30004 for wpa_supplicant

- SPECS/chrony/chrony.spec
- SPECS/glib-networking/glib-networking.spec
- SPECS/gnutls/gnutls.spec
- SPECS/nettle/nettle.signatures.json
- SPECS/nettle/nettle.spec
- cgmanifest.json
---
Nettle was updated to 3.7.2 in order to fix CVE-2021-20305. However, in nettle 3.6, the .so's `libhogweed` and `libnettle` were renamed. Therefore, nettle's provides needed to be updated to reflect this change. 
This also required a release bump to the specs `chrony`, `glib-networking`, and `gnutls`, which contain `nettle` as a build requires.
- Update nettle to 3.7.2 to fix CVE-2021-20305
- Bump release of `chrony`, `glib-networking`, and `gnutls`
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-20305
- local build (x86, vhdx)
> Nettle: Update to 3.7.2 for CVE-2021-20305

- SPECS/keepalived/keepalived.spec
---
As part of a CVE fix, a recent update to `net-snmp` changed its shared libraries' version from 35 to 40 and we missed updating other binaries linking against `net-snmp`, so they now use the newer libs and don't force the users to stay on the outdated version.
- Bump release number of `keepalived` to produce a newer package compiled against the latest version of `net-snmp` libraries.
- Ran a spec linter for `keepalived`.
No.
- None, just a release number change.
> Making 'keepalived' link against latest 'net-snmp' libraries.

- SPECS/keepalived/keepalived.spec
This is a cherry-pick of an urgent fix from `1.0-dev`. See #854 for more details.
> 1.0-dev cherry-pick: Making 'keepalived' link against latest 'net-snmp' libraries.

- .github/workflows/check-license-map.yml
- toolkit/scripts/licenses/license_map.py
---
Updating the `license_map.py` script to allow markdown updates without running a check at the same time. These checks are not required for automated package updates and the error code returned in case of a licenses JSON outdated for unrelated reasons is confusing to use in the automation scripts.
- Added the `--only_update` flag to the `license_map.py` script.
- Moved the `licesense_map.py` script into the `toolkit/scripts/licenses` directory next to other scripts.
No.
> Moving `license_map.py` script to toolkit and updating its functionality.

- SPECS/azure-iotedge/azure-iotedge.spec
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
- SPECS/rpm-ostree/rpm-ostree.spec
- SPECS/rust/CVE-2020-36317.patch
- SPECS/rust/CVE-2020-36323.patch
- SPECS/rust/CVE-2021-28875.patch
- SPECS/rust/CVE-2021-28876.patch
- SPECS/rust/CVE-2021-28877.patch
- SPECS/rust/CVE-2021-28878.patch
- SPECS/rust/CVE-2021-28879.patch
- SPECS/rust/rust.spec
---
Adds patches for several High/Critical CVEs in Rust 1.47.0
- Address listed CVEs
- Bump versions of packages that build using Rust
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-36317
- https://nvd.nist.gov/vuln/detail/CVE-2020-36323
- https://nvd.nist.gov/vuln/detail/CVE-2020-28875
- https://nvd.nist.gov/vuln/detail/CVE-2020-28876
- https://nvd.nist.gov/vuln/detail/CVE-2020-28877
- https://nvd.nist.gov/vuln/detail/CVE-2020-28878
- https://nvd.nist.gov/vuln/detail/CVE-2020-28879
- Local build
> Patch several CVEs in Rust

- SPECS/dnsmasq/dnsmasq.signatures.json
- SPECS/dnsmasq/dnsmasq.spec
- cgmanifest.json
---
Update dnsmasq to 2.85 to fix CVE-2021-3348
- Update dnsmasq to 2.85
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3348
- Local build
> Update dnsmasq to 2.85 to fix CVE-2021-3348

- toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
- toolkit/tools/imagegen/attendedinstaller/speakuputils/speakuputils.go
- toolkit/tools/imagegen/attendedinstaller/views/installerview/installerview.go
---
Fixes two usability issues regarding text-to-speech in ISO installer
- Re-enable text-to-speech when entering the installer selection screen
- Don't enable espeakup service when using unattended install
NO
- Local image build
> Fix espeakup issues in ISO

- SPECS/clang/clang.spec
---
Enabling rtti for llvm causes lldb to have build errors of undefined reference to clang-related definitions. Fix the errors by enabling eh and rtti in clang.
- Enable eh/rtti, which are required by lldb.
NO
- #xxxx
- Local Build
> [dev] Update clang to fix lldb build error

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
This change should have been updated on the 1.0-dev branch.  This PR synchronizes the mariner-release and manifest files between 1.0 and 1.0-dev.
> Sync 1.0-dev branch with updated mariner-release version from March update

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
This change updates the mariner-release version number for the 1.0 April 2021 Update
> Bump version number of release package for April Update

- SPECS/python3/fix_broken_mariner_ssl_tests.patch
- SPECS/python3/python3.spec
---
Fix package test failures in python3. Mariner's openssl package disables SSLv2, leading to test_ssl failures. Since the test code already skips these broken tests on Ubuntu (which also disables SSLv2), I've added a patch to skip the same on Mariner.
- Add patch to fix python3 tests
Failing tests that are now skipped:
"======================================================================"
"ERROR: test__create_stdlib_context (test.test_ssl.ContextTests)"
"ValueError: invalid or unsupported protocol version"
"======================================================================"
"ERROR: test_constructor (test.test_ssl.ContextTests)" …
> Fix python3 test_ssl tests

- toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
---
Fix logic bugs regarding espeakup instantiation in `runliveinstaller`. These were caught previously in code review, but the fixing commit was not pushed to the remote branch.
- Make sure $CONFIG_ROOT is defined before use
- Negate test for unattended configuration
NO
- Local test
> Fix logic errors in runliveinstaller script

- SPECS/grpc/grpc.spec
---
Small change to the grpc spec to use our published c-ares package.
- Changes the value of a switch in the CMakeLists.txt for grpc to use the system-provided c-ares rather than a vendored copy.
NO
- Local build
> Added config line to unvendor c-ares in grpc; now uses system package

- SPECS/cloud-utils-growpart/cloud-utils-growpart.spec
- SPECS/cloud-utils-growpart/growpart-remove-flock-disk-locking.patch
---
Regression identified when using flock disk locking with 5.10 kernel and
systemd-239. During unlock_disk_and_settle(), udevadm settle will not
complete and eventually timeout after 2 minutes. When looking at the
systemd-udevd logs, the daemon crashes and produces the following stack
trace:
Stack trace of thread 1531:
#0  0x00007fd73d9be405 recvmsg (libpthread.so.0)
#1  0x00007fd73dab33b8 udev_monitor_receive_device (libsystemd-shared-239.so)
#2  0x0000600347316201 on_uevent (systemd-udevd)
#3  0x0000600347316667 on_inotify (systemd-udevd)
#4  0x00007fd73dbad6d7 source_dispatch (libsystemd-shared-239.so)
#5  0x00007fd73dbaf4e5 sd_event_dispatch (libsystemd-shared-239.so)
#6 …
> cloud-utils-growpart: Workaround for timeout

- cgmanifest.json
---
I've missed updating `cgmanifest.json` in #911.
- Updated the version of `ruby` inside `cgmanifest.json`.
No.
- N/A.
> Updating cgmanifest.json to match version of `ruby`.

- SPECS/uclibc-ng/uclibc-ng.signatures.json
- SPECS/uclibc-ng/uclibc-ng.spec
- cgmanifest.json
---
Updating `uclibc-ng` to version 1.0.37 to fix CVE-2021-27419.
See [MSRC blog entry](https://msrc-blog.microsoft.com/2021/04/29/badalloc-memory-allocation-vulnerabilities-could-affect-wide-range-of-iot-and-ot-devices-in-industrial-medical-and-enterprise-networks/) and section 3.2.18 from [CISA's web page](https://us-cert.cisa.gov/ics/advisories/icsa-21-119-04) for more details.
- Updated `uclibc-ng` to version 1.0.37 to fix CVE-2021-27419.
- Removed a duplicate in `cgmanifest.json`.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-27419
>  Updating `uclibc-ng` to version 1.0.37 to fix CVE-2021-27419.

- SPECS/maven/maven.signatures.json
- SPECS/maven/maven.spec
- cgmanifest.json
---
Updating `maven` to version 3.8.1 to fix CVE-2021-26291.
- Updating `maven` to version 3.8.1.
- Added a conditionally built `maven-cached-sources` subpackage to simplify future updates.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-26291
> Updating `maven` to version 3.8.1 to fix CVE-2021-26291.

- SPECS/espeak-ng/espeak-ng.spec
---
GNU Make does not like files with spaces in the name. Our espeak-ng package places a file with a space in its name into the ISO initrd, which is tracked by our build system. This results in weird target failures when running back-to-back ISO builds.
- Change "Mr serious" voice name in espeak-ng to "Mr_serious"
NO
- Local ISO build
> Fix "Mr serious" voice name in espeak-ng

- SPECS/python-pexpect/python-pexpect.spec
---
Dependency on `/usr/bin/man` in `python-pexpect` package caused dependency resolution in pipeline build 91482 to fail, since man-db is not in the toolchain. Dynamic dependencies are unable to be resolved from non-toolchain packages in 1.0. I tested the build in a derivative previously, which caused this failure to be missed.
NOTE: Not bumping package release, as an official version has never been built. 
- Change file requirement on `/usr/bin/man` to `man-db`, and make requirement check-time in python-pexpect
NO
- Local build
> Fix build break due to file dependency in python-pexpect

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/pkgjson/pkgjson.go
- toolkit/tools/internal/pkgjson/pkgjson_test.go
---
When reading packages from our packages JSON we didn't split the package name from its version constraint (if present). This change fixes that.
- Made sure we correctly split the package names inside the packages JSONs into separate `Name`, `Condition`, and `Version` parts.
No.
-Local image build.
> Fixing parsing the packages JSON.

- SPECS/bind/bind.spec
- SPECS/man-db/man-db.spec
---
Fix the build break caused by bind and man-db.
Fix certain file paths in bind.spec which are incorrectly replaced after applying the linter and removed duplicate contents detected in the spec.
sudo failed to build because both groff and man-db provided the same file: zsoelim man due to a recent change in groff. Remove the conflict file from man-db since groff is the right place to provide this file.
bind:
- Fix file path error caused by linting
- Remove duplicate %files section for bind-license
- Remove named.conf from main package, which is already provided by bind-utils
man-db:
-Remove zsoelim man page, which is provided by groff …
> [dev] Fix build break caused by bind and man-db

- SPECS/pygobject3/pygobject3.spec
- toolkit/scripts/pkggen.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
I noticed that in the 1.0->dev merge, in non-check builds, we were rebuilding RPMs which have `with_check`-gated build requirements that were not in the toolchain (namely Python3 with tzdata/iana-etc). 
Further investigation revealed that in our package graph, we always added these gated build requirements regardless of the value of the `RUN_CHECK`. These non-toolchain build requirements were then built, which caused the cached toolchain package to be invalidated because one of its requirements was built instead of cached.
Additionally, during package builds, we pulled in the gated build requirements regardless of the value of RUN_CHECK.
This is all because our default defines …
> [dev] Ensure RUN_CHECK Make flag and with_check RPM define match

- toolkit/docs/building/building.md
---
Updating the documentation to clarify a few details regarding reproducible builds.
- Updated the `Build Summaries` section of our docs.
No.
- Local check if the md file still renders correctly.
> Adding more details for reproducing builds with summary files.

- SPECS/rust/rust.spec
---
Other distros separate out `cargo` into a separate subpackage from `rust`. We will provide this package name from the `rust` package as a compatibility measure.
- Provide 'cargo' from rust package
NO
- Local build
> [dev] Add "cargo" provides to rust package

- SPECS/glib/glib.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
---
- Other distros have the contents of our `glib-schemas` in their `glib-devel` package. We runtime require the schemas subpackage from our devel subpackage to meet this expectation.
- Require `glib-schemas` from `glib-devel`
**YES**
- Local build
> [dev] Add runtime requirement on glib-schemas from glib-devel

- toolkit/docs/how_it_works/3_package_building.md
- toolkit/tools/graphanalytics/graphanalytics.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
- toolkit/tools/internal/sliceutils/sliceutils.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
The change improves how blocking packages are displayed in the logs to include the whole dependency chain, which lead to the conclusion that a particular package is blocking a given SRPM.
Before:
```
level=info msg="136: at-spi2-atk-2.34.2-1.cm1.src.rpm - 2 total unmet dependencies"
level=debug msg="--> gtk3-3.24.28-3.cm1.src.rpm"
level=debug msg="--> pkgconfig(atk-bridge-2.0)"
```
After:
```
level=info msg="136: at-spi2-atk-2.34.2-1.cm1.src.rpm - 1 total unmet dependencies"
level=debug msg="--> pkgconfig(atk-bridge-2.0): gtk2-devel-2.24.32-8.cm1.x86_64.rpm [gtk2-2.24.32-8.cm1.src.rpm] -> gtk2-2.24.32-8.cm1.x86_64.rpm [gtk2-2.24.32-8.cm1.src.rpm] -> …
```
> [dev] Improving logging of blocking packages.

- toolkit/scripts/toolkit.mk
---
Adding the .repo files to the toolkit, so that clients have them available if they'd like to build their packages/images with non-default CBL-Mariner RPMs more easily.
- Add all CBL-Mariner .repo files to the toolkit.
No.
- Local run of `make package-toolkit REBUILD_TOOLS=y` and checking the content of the resulting tarball.
> Adding CBL-Mariner .repo files to the toolkit.

- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adds explicit dependency on python-xml to libxml2's python module. This fixes an issue where libraries built using libxml2 assumed that python-xml had already been installed.
- Added explicit dependency on python-xml to libxml2.
***YES***
- Pipeline build id: Local package build
> Added explicit dependency on python-xml for libxml2

- SPECS/shadow-utils/shadow-utils.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
When users are provisioned using `useradd`, and a primary group is not specified with `-g`, the primary group for those users is the `users` group. Using a blanket default group like this is not following best practices. Users created without specified primary groups are able to read each others' files by default.
This problem is due to a bad configuration in the shadow-utils spec. The spec explicitly sets the `USERGROUPS_ENAB` setting in `/etc/login.defs` to `no`. The [useradd man page](https://linux.die.net/man/8/useradd) has a good explanation of how this setting affects the user’s primary group when a primary group is not specified:
“If [-g is] not specified, the behavior of …
> Enable usergroups by default in shadow-utils

- SPECS/ceph/ceph.signatures.json
- SPECS/ceph/ceph.spec
- SPECS/python-rsa/python-rsa.signatures.json
- SPECS/python-rsa/python-rsa.spec
- cgmanifest.json
---
Update version of ceph and python-rsa to fix CVEs
- Update ceph version to 16.2.0 to fix CVE-2020-25660, CVE-2020-25678 and CVE-2020-27781
- Update python-rsa version to 4.7.2 to fix CVE-2020-25658
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-25658
- https://nvd.nist.gov/vuln/detail/CVE-2020-25660
- https://nvd.nist.gov/vuln/detail/CVE-2020-25678
- https://nvd.nist.gov/vuln/detail/CVE-2020-27781
- Local build
> Update version of ceph and python-rsa to fix CVEs

- SPECS/libwebp/libwebp.signatures.json
- SPECS/libwebp/libwebp.spec
- cgmanifest.json
---
Update libwebp to 1.0.3 to fix various CVEs. This is a commit picked from the 1.0-dev branch.
- Update libwebp to 1.0.3
NO
- https://nvd.nist.gov/vuln/detail/CVE-2018-25009
- https://nvd.nist.gov/vuln/detail/CVE-2018-25010
- https://nvd.nist.gov/vuln/detail/CVE-2018-25011
- https://nvd.nist.gov/vuln/detail/CVE-2018-25012
- https://nvd.nist.gov/vuln/detail/CVE-2018-25013
- https://nvd.nist.gov/vuln/detail/CVE-2018-25014
- https://nvd.nist.gov/vuln/detail/CVE-2020-36329
- https://nvd.nist.gov/vuln/detail/CVE-2020-36330
- https://nvd.nist.gov/vuln/detail/CVE-2020-36331
- Local build
> Update libwebp to 1.0.3, fixing CVEs. (#987)

- SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
- SPECS/grub2/grub2.spec
- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Python2 buildrequires in libxml2 were causing rebuilds of toolchain packages in the regular package build phase. Additionally, grub2 failed to build due to the absence of python2.
- Explicitly use python3 when bootstrapping grub2
- Remove libxml2-python package
**YES**
- Pipeline build id: 95478
> [dev] Fix build breaks due to Python2 toolchain removal

- SPECS/alsa-lib/alsa-lib.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update alsa-lib to have a build-time requirement on python3 instead of python2
- Update alsa-lib to have a build-time requirement on python3 instead of python2
**YES**
- N/A
> [dev] Update python dependencies in alsa-lib to use python3

- SPECS/nss/nss.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
---
Disable the compilation of gtest assets in nss package in order to speed up the toolchain build. These take around 5 minutes to compile, and are not currently used by us. Since nss is built twice in the toolchain, this should reduce each toolchain build ~10 minutes. 
The nss package tests are also modified to run only the standard cycle tests. The tests now run in ~9 minutes instead of 3.5 hours.
- Change nss.spec to disable gtest compilation and use standard test cycle
- Change nss toolchain build script to disable gtest compilation
**YES**
NO
> Reduce toolchain build time (via nss) and speed up nss package tests

- SPECS/zeromq/zeromq.signatures.json
- SPECS/zeromq/zeromq.spec
- cgmanifest.json
---
Fixes critical CVE in zeromq.
Fixes critical CVE-2021-20236 
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-20236
- Local build with `RUN_CHECK=y` ticked
> Updated zeromq to 4.3.4 to address CVE-2021-20236

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- cgmanifest.json
---
Update postgresql to version 12.7 to resolve CVE-2021-32027
- Update postgresql to version 12.7 to resolve CVE-2021-32027
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-32027
- Local build
- %check section passed all tests
> Update postgresql to 12.7 to resolve CVE-2021-32027

- SPECS/libjpeg-turbo/CVE-2020-17541.patch
- SPECS/libjpeg-turbo/libjpeg-turbo.spec
---
Patch libjpeg-turbo CVE-2020-17541
- Patch libjpeg-turbo CVE CVE-2020-17541
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-17541
- Local Build
> Patch libjpeg-turbo CVE-2020-17541

- SPECS/python-sphinx/python-sphinx.spec
---
I was building a package that has a build dependency on python3-sphinx and discovered that python3-sphinx has an undeclared runtime dependency on python3-setuptools.
A minimal repro is `docker run cblmariner.azurecr.io/base/core:1.0.20210430 bash -c "tdnf install -y python3-sphinx && sphinx-build-3"`.
- Change Add python*-setuptools as a runtime dependency to python*-sphinx
**NO**
> python-sphinx: Add missing runtime dependency on setuptools

- SPECS/collectd/collectd.spec
---
Update collectd spec to require "perl" package instead of perl sub packages not on our platform (perl-Regexp-Common, perl-HTML-Parser, rrdtool-perl, perl(:MODULE_COMPAT_5.26.1)). This fixes build break errors such as:
PANI[0009] Failed to resolve graph. Error: No package perl(:MODULE_COMPAT_5.26.1) available 
- Change collectd spec Requires
**NO**
- Local package build:
sudo make build-packages -j$(nproc) CONFIG_FILE= REBUILD_TOOLS=y PACKAGE_IGNORE_LIST="openjdk8" SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core DISABLE_UPSTREAM_REPOS=y
> Update perl Requires for collectd

- SPECS/python-pycurl/python-pycurl.spec
- SPECS/python-pycurl/skip-incompatible-libcurl-tests.patch
---
Fix python-pycurl package tests, which were broken by the curl 7.76 package update.
Errors seen:
"FAIL: test_failonerror (tests.failonerror_test.FailonerrorTest)"
"pycurl.error: (22, 'The requested URL returned error: 403')"
"FAIL: test_failonerror_status_line_invalid_utf8_python3 (tests.failonerror_test.FailonerrorTest)"
"pycurl.error: (22, 'The requested URL returned error: 555')"
- Add patch to python-pycurl to fix package tests. Patch is based on upstream fix: https://github.com/pycurl/pycurl/pull/689
- Cleanup python-pycurl spec
**NO**
> Fix libcurl issue in python-pycurl tests

- SPECS/ceph/ceph.spec
---
disable debuginfo because ceph-debuginfo rpm is too large
- dwz is currently not available in 1.0-dev (available in dev), but Fedora is moving away from it. Compressing debuginfo using dwz was disabled in the original Fedora spec for ceph. Disabling ceph-debuginfo rpm for the time being.
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/28918515
- None
- Local build. Verified that ceph-debuginfo rpm doesn't get produced.
> disable debuginfo due to size

- SPECS/grpc/grpc.spec
- SPECS/protobuf/protobuf.signatures.json
- SPECS/protobuf/protobuf.spec
- cgmanifest.json
---
It looks like by default `grpc` build and published its own libraries for `protobuf`, which end up conflicting with the ones we provide through the `protobuf` package. This updated `grpc` to use that package instead.
- Switched `grpc` to using system's `protobuf`.
- Updated 'protobuf' to version 3.14.0 to satisfy dependencies from `grpc` and `collectd`.
No.
> Making `grpc` use system's `protobuf`.

- SPECS/python-pexpect/python-pexpect.spec
- SPECS/python-pexpect/sys_executable.patch
- SPECS/python-ptyprocess/python-ptyprocess.spec
---
Fixes broken package tests for `python-ptyprocess`, `python-pexpect`.
- `python-pexpect`: Add upstream patch to fix tests on systems without unversioned `/usr/bin/python` binaries
- Both: install testing requirements with pip, as we do with most python package tests
**NO**
- Local build, with and without testing enabled
> Fix ptests for python-ptyprocess, python-pexpect

- SPECS/chrony/chrony.spec
---
This change makes chronyd not listen on UDP port by default. The behavior can be overridden by a config change.
- Make chronyd not listen on UDP port.
NO
- Local build
> Make chronyd not listen on UDP port by default

- toolkit/Makefile
- toolkit/docs/building/building.md
- toolkit/scripts/pkggen.mk
---
Add an option to not rebuild rev deps, saving time during delta builds.
- Add option to trigger '--rebuild-missing-dep-chains' on or off for the graphoptimizer.
NO
- local build
> Add option to not rebuild reverse deps.

- cgmanifest.json
---
Remove tilde from version numbers in cgmanifest.json
Should resolve the following:
'[WARN] Version string grub2 2.06~rc1 for component grub2 is invalid or unsupported.  Registration will be submitted, but may be invalid.'
"[WARN] Version string moby-runc 1.0.0~rc95+azure for component moby-runc is invalid or unsupported.  Registration will be submitted, but may be invalid."
[ERROR] There was an unexpected error:  
[ERROR] SafelyExecute logged InvalidComponentVersionException: The provided version '2.06~rc1' was not valid.
- Remove tilde from version numbers in cgmanifest.json
**NO**
- N/A
> Remove tilde from version numbers in cgmanifest.json

- SPECS/dbus-glib/dbus-glib.spec
---
`dbus-glib` has a provides of `pkgconfig(dbus-glib-1)` on the base package, but the pkgconfig file is in the `devel` subpackage. This PR fixes that, as well as various fixes to the spec and the package tests.
- Move `pkgconfig(dbus-glib-1)` provides to the devel package from the base package
- License verified- corrected to "AFL OR GPLv2+" from "AFL AND GPLv2+"
- Fix test suite by compiling unit tests, assertions during `%with_check` builds
- Use configure/make macros
- Spec linted 
**NO**
> [dev] Fix location of dbus-glib pkgconfig provides

- cgmanifest.json
---
Remove tilde from version numbers in cgmanifest.json
Should resolve the following:
'[WARN] Version string grub2 2.06rc1 for component grub2 is invalid or unsupported. Registration will be submitted, but may be invalid.'
"[WARN] Version string moby-runc 1.0.0rc95+azure for component moby-runc is invalid or unsupported. Registration will be submitted, but may be invalid."
[ERROR] There was an unexpected error:
[ERROR] SafelyExecute logged InvalidComponentVersionException: The provided version '2.06~rc1' was not valid.
- Port change from #1094 to dev branch
**NO**
- N/A
> Remove tilde from version numbers in cgmanifest.json [dev branch]

- SPECS/libseccomp/libseccomp.spec
---
Some packages expect the existence of a `libseccomp-static` package. Since we ship the static libraries as part of the `devel` subpackage, we should add a `libseccomp-static` provides to the devel subpackage.
- Add `libseccomp-static` provides to devel subpackage
- Modernize spec with make, ldconfig macros
- Remove libtool archive files
**NO**
- Local build of affected package with `RUN_CHECK=y`
> [dev] Add static subpackage provides to libseccomp-devel

- SPECS/libconfig/libconfig.signatures.json
- SPECS/libconfig/libconfig.spec
- SPECS/libstoragemgmt/libstoragemgmt.spec
- SPECS/lldpad/lldpad.spec
- SPECS/swupdate/swupdate.spec
- cgmanifest.json
---
Our `libconfig` package does not follow the traditional base package/devel subpackage pattern that many of our packages follow. This PR updates `libconfig` to version 1.7.3 and gives it a devel subpackage. To match this change, direct dependents on libconfig have had their build-time requirements changed from `libconfig` to `libconfig-devel`.
- `libconfig`: Upgrade to 1.7.3, Add devel subpackage
- `libstoragemgmt`, `lldpad`, `swupdate`: Use `libconfig-devel` at build-time. Address various linting errors.
**NO**
- Local check builds of affected packages
> [dev] Add devel subpackage to libconfig, update to 1.7.3

- SPECS/libdnf/CVE-2021-3445.patch
- SPECS/libdnf/libdnf.spec
- SPECS/python-urllib3/python-urllib3.signatures.json
- SPECS/python-urllib3/python-urllib3.spec
- SPECS/qemu-kvm/CVE-2021-3546.patch
- SPECS/qemu-kvm/qemu-kvm.spec
- cgmanifest.json
---
- Update python-urllib3 to version 1.26.5 and resolve CVE-2021-33503
- Fix CVE-2021-3546
- Fix CVE-2021-3445
- Fix incorrect versioning for libdnf in cgmanifest
- Update to version 1.26.5
- Patch CVE-2021-3546
- Patch CVE-2021-3445
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-33503
- https://nvd.nist.gov/vuln/detail/CVE-2021-3445
- https://nvd.nist.gov/vuln/detail/CVE-2021-3546
- Local Build
> Fix CVE-2021-33503, CVE-2021-3445, CVE-2021-3546

- toolkit/tools/go.mod
- toolkit/tools/go.sum
- toolkit/tools/internal/pkggraph/pkggraph_test.go
- toolkit/tools/internal/pkgjson/pkgjson.go
- toolkit/tools/internal/pkgjson/pkgjson_test.go
- toolkit/tools/internal/versioncompare/versioncompare.go
- toolkit/tools/specreader/specreader.go
---
The spec parser was crashing for some unusual, but valid build-/run-time dependencies. Example:
```
BuildRequires: X < 4
BuildRequires: X < 3
```
I've fixed the interval generating method to better handle valid cases.
Similarly, double different version dependencies on a package were being recognized incorrectly as duplicates due to a bug where we assigned pointers instead of deep copies of moved objects.
- Fixed the interval generating method to better handle valid cases.
No.
- Local tooling build.
- Ran `sudo make go-tidy-all` and `sudo make go-test-coverage`.
> [dev] Fixing spec dependencies parsing bugs.

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/hyperv-daemons/hyperv-daemons.signatures.json
- SPECS/hyperv-daemons/hyperv-daemons.spec
- SPECS/kernel-headers/kernel-headers.signatures.json
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/config
- SPECS/kernel-hyperv/kernel-hyperv.signatures.json
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/CVE-2021-33624.nopatch
- SPECS/kernel/CVE-2021-34693.nopatch
- SPECS/kernel/config
- SPECS/kernel/config_aarch64
- SPECS/kernel/kernel.signatures.json
- SPECS/kernel/kernel.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/Dockerfile
- toolkit/scripts/toolchain/container/toolchain-md5sums
- toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
- toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh
---
Update kernel to 5.10.47.1
Config changes:
- removed (in x86_64 only) `# CONFIG_XILINX_ZYNQMP_DPDMA is not set` due to removal of dependency on `HAS_IOMEM` & `OF`, 
- removed `# CONFIG_DXGKRNL_DEBUG is not set` as a part of update from the latest upstream code (11e9a539)
- add `# CONFIG_SYSTEM_REVOCATION_LIST is not set`, a new config that depends on `SYSTEM_BLACKLIST_KEYRING` and  `PKCS7_MESSAGE_PARSER` which are currently set. This config provides system-wide ring of revocation certificates.
- Update source to 5.10.47.1
- Address CVE-2021-34693, CVE-2021-33624
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-34693
- https://nvd.nist.gov/vuln/detail/CVE-2021-33624
- local …
> Kernel: Update kernel to 5.10.47.1

- .github/workflows/validate-cg-manifest.sh
---
Upon error of parsing, script would respond with a missing source error message which may not be true if for instance there is a bad if condition. 
When the source error would show, the error message would either not have the name and version or would show the name of a previously check spec due to unintialized values. 
- Create check to see if parsing of spec was successful
- Move the source check to after the name and version variables have been intialized
**NO**
- Local tests
> Initialize values in validate cgmanifest script and check for parse success

- SPECS/glusterfs/glusterfs.spec
---
Removing unused run-time requirement from `glusterfs-thin-arbiter`. The subpackage is not using the `glusterfs-server` subpackage and the build fails due to that dependency, when one builds with the `glusterfs-server` subpackage and its dependencies disabled. Which is what we do for CBL-Mariner at the moment.
We haven't had a successful build since the changes in this spec were introduced, thus I'm not updating the release and treating this a part of the changes for the current release.
- Removed unused run-time requirement from `glusterfs-thin-arbiter`.
No.
> Removing unused run-time requirement from `glusterfs-thin-arbiter`.

- SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
- SPECS/grub2/grub2.spec
---
Adding provides for popular `grub2` subpackages to increase compatibility with other distros.
- Added provides for multiple `grub2` subpackages:
- `grub2-common`,
- `grub2-efi-aa64-modules`,
- `grub2-efi-modules`,
- `grub2-efi-x64`,
- `grub2-efi-x64-modules`,
- `grub2-pc-modules`,
- `grub2-tools`,
- `grub2-tools-efi`,
- `grub2-tools-extra`,
- `grub2-tools-minimal`.
No.
> [dev] Adding `Provides` for common `grub2` subpackages.

- SPECS/moby-containerd/CVE-2021-32760.patch
- SPECS/moby-containerd/moby-containerd.spec
> patch moby-containerd to resolve CVE-2021-32760 (#1153)

- SPECS/ant/ant.signatures.json
- SPECS/ant/ant.spec
- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
---
Upgrade version in ant, nodejs to resolve CVEs
- Update to version in ant to 1.10.11 to fix CVE-2021-36373 and CVE-2021-36374
- Update to version in nodejs to 14.17.2 to fix CVE-2021-22918
NO
- None
- https://nvd.nist.gov/vuln/detail/CVE-2021-36373
- https://nvd.nist.gov/vuln/detail/CVE-2021-36374
- https://nvd.nist.gov/vuln/detail/CVE-2021-22918
- Local build
> Upgrade version in ant, nodejs to resolve CVEs

- SPECS/logrotate/logrotate.signatures.json
- SPECS/logrotate/logrotate.spec
- cgmanifest.json
---
- Update logrotate to the latest release 3.18.1
- Add a systemd timer to logrotate so that it will run automatically once a day.
- Add a default logrotate configuration that will also run configs in /etc/logrotate.d/
**NO**
- Local build
- Tested install and observed timer scheduled and successful execution of logrotate
> Update logrotate and add systemd timer

- SPECS/curl/CVE-2021-22924.patch
- SPECS/curl/CVE-2021-22925.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2021-22922, CVE-2021-22923, CVE-2021-22924, CVE-2021-22925.
CVE-2021-22922 and CVE-2021-22923 are vulnerabilities with metalink.
We do not build curl with the --with-libmetalink option and so our
resulting curl binary does not support metalink. One can verify this by
attempting to run "curl --metalink" and observe the warning message:
Warning: --metalink option is ignored because the binary is built
without the Metalink support.
The patch for CVE-2021-22924 was backported to our current curl
version. Slight modification was needed so the patch applies cleanly.
Patch for CVE-2021-22925 was backported to our current curl version
7.76.0. No modification needed to the …
> curl: Address 4 CVEs

- SPECS/libseccomp/libseccomp.spec
---
Fix a missing requirement on the base libseccomp package from the devel subpackage. Without this requirement, the devel subpackage can create a dangling pointer to the actual libseccomp shared library.
- libseccomp: Add runtime requirement on base package from devel subpackage
- libseccomp: Add soname version to `%files` section
- libseccomp: Remove pkgconf provides (unnecessary in 2.0) 
**NO**
> [dev] libseccomp-devel: Add runtime requirement on base package

- SPECS/protobuf-c/protobuf-c.signatures.json
- SPECS/protobuf-c/protobuf-c.spec
- SPECS/protobuf/protobuf.signatures.json
- SPECS/protobuf/protobuf.spec
- cgmanifest.json
---
Our protobuf and protobuf-c packages are out-of-date. We upgrade those to the latest versions. Additionally, linting performed and compatibility provides added as appropriate.
- `protobuf`: Upgrade to 3.17.3. Lint spec. Remove python2 subpackage. Rename python3 subpackage to python3-protobuf. 
- `protobuf-c`: Upgrade to 1.4.0. Lint spec. Add compiler subpackage provide to base package. Add compiler, lite, lite-devel, lite-static subpackage provides to appropriate packages.
**NO**
> [dev] Upgrade protobuf to 3.17.3, protobuf-c to 1.4.0 and add compatibility provides

- SPECS/mysql/mysql.signatures.json
- SPECS/mysql/mysql.spec
- cgmanifest.json
---
Upgrades mysql to the latest critical patch update released upstream. This fixes 31 CVEs that applied to our previous version of mysql.
- mysql: upgrade from 8.0.24 to 8.0.26
**NO**
- A full list of CVEs patched by the 8.0.26 update can be found [here](https://www.oracle.com/security-alerts/cpujul2021.html#AppendixMSQL).
- The 8.0.25 update appears to [not fix any security issues](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-25.html).
> Upgrade mysql to  8.0.26 to fix several CVEs

- SPECS/mariner-release/mariner-release.spec
---
A previous change to mariner-release in #1118 caused the `os-release` file to reside in the `/lib` folder. This broke the image builds, as the `/lib` folder created by mariner-release conflicted with the `/lib` folder created by the filesystem package. To fix this, we revert that specific change.
Release number can stay the same, as we have not released the previous changes anywhere.
- Move `os-release` back to `/usr/lib`
- Remove %%clean section, buildroot cleaning step from the spec (both are automatically added by RPM)
**YES**
- Local image build with new mariner-release version
> [dev] Fix placement of os-release file in mariner-release

- SPECS/python-twisted/python-twisted.signatures.json
- SPECS/python-twisted/python-twisted.spec
- cgmanifest.json
Cherry-pick of #1220 to the 1.0 branch
---
Upgrade python-twisted to 20.3.0 to fix CVE-2020-10108, CVE-2020-10109
- Upgrade python-twisted to version 20.3.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-10108
- https://nvd.nist.gov/vuln/detail/CVE-2020-10109
- Local build of python-twisted and dependent packages
- Package tests do not pass. Tests were erroneously counting as passing in the previous version- no net change.
> Upgrade python-twisted to 20.3.0 to fix CVE-2020-10108, CVE-2020-10109

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/hyperv-daemons/0001-clocksource-drivers-hyper-v-Re-enable-VDSO_CLOCKMODE.patch
- SPECS/hyperv-daemons/hyperv-daemons.spec
- SPECS/kernel-headers/0001-clocksource-drivers-hyper-v-Re-enable-VDSO_CLOCKMODE.patch
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/0001-clocksource-drivers-hyper-v-Re-enable-VDSO_CLOCKMODE.patch
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/0001-clocksource-drivers-hyper-v-Re-enable-VDSO_CLOCKMODE.patch
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Our validation found that clock_gettime(CONFIG_REALTIME, &start) was
taking orders of magnitude longer to complete than before. This was due
to the following upstream commit e4ab4658f1cf which, while not
backported to the LTS stable trees, was backported into our specific
kernel source as part of our ARM64 support.
This change applies the upstream commit 3486d2c9be65 which fixes the
VDSO regression.
**YES**
Local build, pipeline build, local testing.
> kernel: Add patch to fix VDSO in HyperV

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/hyperv-daemons/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch
- SPECS/hyperv-daemons/hyperv-daemons.spec
- SPECS/kernel-headers/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Our validation found that cdrom eject is causing a udev event storm and
regressing many performance metrics. Issue isolated to a commit
introduced upstream and backported to stable kernel. Reverting this
commit to mitigate the issue. We will be working with LKML in the
meantime to fix the underlying issue.
cherry-pick of 7474d1b6974e27447a7d594bc77b0d751f2dfbba to 1.0
> kernel: Add patch to revert a cdrom eject commit

- SPECS/dpdk/dpdk.spec
---
`libvirt` changes from #1175 did not fully fix the build break mentioned in #1174 that caused their revert in the first place. While that build break is being investigated, we workaround the issue and unblock the build by disabling the dependency on `libvirt-devel` by `dpdk`. This is done by disabling the `dpdk-examples` subpackage.
- Turn off `dpdk-examples` subpackage
**NO**
- Local build
> [dev] Disable dpdk-examples subpackage

- SPECS/swig/swig.signatures.json
- SPECS/swig/swig.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Align the source used in the 2.0 version of `swig` with the source used by the `1.0` branch. 
PR #1236 upgraded the version of swig used by the 1.0 branch to match the version shipped by the dev branch. That PR included a switch to a GitHub-based tarball, which has the same name as the SourceForge-based tarball used in the dev branch. This actually led to the SourceForge-based tarball being overwritten on our source server. Now, this branch's build fails due to a mismatch between the tarballs' checksums. 
For simplicity, we'll just use the GitHub source URL in the dev branch as well. 
- Use GitHub source URL for `swig`
- Lint `swig` spec
- Remove entry for old `swig` version in …
> [dev] Use GitHub source tarball for swig

- toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
Fixes two bugs in the ManualPartitionWidget section of the ISO installer. 
The first bug concerns a disk size associated with the wrong disk showing up in the "space left" display field. This was due to a missing display update call when changing the selected disk.
The second bug concerns the incorrect title being shown on the partition table screen when navigating back from the partition addition page.. This was due to a missing title refresh call when processing escape key input in the partition addition page.
- Refresh the title of the ManualPartitionWidget when using the escape key to go from the partition addition page to the partition table page.
- Update the "space left" …
> [ISO] Fix display update issues in ManualPartitionWidget

- SPECS/etcd/etcd-3.4.13.spec
This PR adds an etcd-tools package, which contains the etcd-dump-* tools from the etcd repository. (I asked about this on the internal Mariner Linux Support team)
- Add etcd-tools package
No
Local build
> Add etcd-tools package

- SPECS/dbus-python/dbus-python.spec
---
Fix the follow build break from the dbus-python package by adding space between the package name and version number
ERRO[0010] Failed to clone dbus>=1.8.6(,):<ID:6546 Type:Remote State:Unresolved> from '<NO_SRPM_PATH>' in '<NO_REPO>' from RPM repo. Error: No package dbus>=1.8.6 available
- Change dbus-python build requires
**NO**
> Fix dbus-python build issue

- SPECS/ruby/CVE-2021-32066.patch
- SPECS/ruby/ruby.spec
---
Adding a patch to fix CVE-2021-32066 in `ruby`.
- Patched CVE-2021-32066 in `ruby`.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-32066
- Local package build with `RUN_CHECK=y`. All tests passed.
> Fixing CVE-2021-32066 in `ruby`

- toolkit/scripts/sodiff/mariner-sodiff.sh
---
Before, sodiff would report currently rebuilt and not yet published (including the triggering packages). A logic has been added to exclude such packages.
- Update sodiff to correctly handle rebuild but not published packages.
- Muffle some expected error messages.
**NO**
- Local build
> Update sodiff to correctly handle rebuilt/unreleased packages.

- toolkit/tools/srpmpacker/srpmpacker.go
---
When duplicate filenames are included as sources for a SPEC file, the srpmpacker tool, which does not support this, was producing a warning message:
"WARN[0000] Duplicate matching file found at (/data2/vsts/_work/16/s/SPECS/foo/SOURCES/src/CMakeLists.txt), skipping"
Instead of silently proceeding with source files that are not hash verified, this PR changes to an error that will stop the build, and require the duplicate file to be removed/renamed.
"WARN[0008] Error hydrating from local source directory (/data2/vsts/_work/16/s/SPECS/foo): Unable to process duplicate matching file …
> srpmpacker: Change warning to error when duplicate source files detected

- toolkit/scripts/sodiff/mariner-sodiff.sh
---
Instead of creating an empty file, sodiff was creating a very short file, causing errors. Fix to create an empty file instead.
- Change artifact creation to create empty file instead of a very short one.
**NO**
- Local build
> Fix sodiff file generation

- SPECS/cronie/cronie.spec
- SPECS/sysstat/sysstat.spec
- toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
- toolkit/imageconfigs/packagelists/core-packages-image.json
---
The split is more in-line with what users expect in terms of package names and their content. It also allows to use a smaller `cronie-noanacron` package, if needed.
- Split `cronie` into `cronie`, `cronie-anacron`, and `cronie-noanacron`.
- Added `Provides: dailyjobs`.
- Updated one spec depending on `cronie`.
- Updated package lists to use `cronie-anacron`.
- Basic spec linting for `cronie`.
No.
- Local build of `cronie` and `sysstat`.
> `cronie`: splitting into subpackages

- SPECS/mysql/mysql.spec
---
The upgrade to the latest version of `mysql` in #1198 enabled more tests than we were previously running. Some of these tests fail for various reasons- missing check-time requirements, being run under root user, etc. This PR fixes most of the newly failing tests.
- Add missing `tzdata` build/runtime dependency, additional check-time dependencies
- Run tests as a non-root user
- Add better test failure logging
**NO**
- Local package build with `RUN_CHECK=y`
> Fix majority of broken mysql package tests

- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
---
Update nodejs to version 14.17.5 to fix CVE-2021-22931
- Update nodejs to version 14.17.5
**NO**
- http://nvd.nist.gov/vuln/detail/CVE-2021-22931
- Local build. Confirmed package tests still pass.
- time sudo make build-packages -j$(nproc) PACKAGE_BUILD_LIST="nodejs" PACKAGE_REBUILD_LIST="nodejs" CONFIG_FILE= REBUILD_TOOLS=y REBUILD_DEP_CHAINS=n RUN_CHECK=y SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core
> Update nodejs to version 14.17.5

- toolkit/tools/imagegen/installutils/installutils.go
---
When `installutils` processes a user's provided SSH public keys, it creates the `$HOME/.ssh/authorized_keys` file regardless of whether the user provided any public keys. However, due to an error in our code, we only gave the user's SSH directory the proper permissions if keys were provided in the system configuration. This means that when a user is configured without keys, that user would need to fix the SSH directory permissions manually at a later date.
Since `ssh` handles the creation of a user's SSH directory when not present, we choose to skip generation of the SSH directory and the authorized keys file entirely when public keys are not provided for a user.
- Do not create …
> installutils: Fix generation of SSH user directories when keys not provided

- SPECS/ceph/ceph.spec
---
Making `ceph` build its `libradosstriper` subpackvages - commonly required package.
- Added `libradosstriper` subpackvages to `ceph`.
No.
> [dev] Adding `libradosstriper` subpackvages to `ceph`.

- SPECS/elfutils/elfutils.spec
---
elfutils package failed to compile in toolchain build process with the following error:
error: File must begin with "/": %{_sysctldir}/10-default-yama-scope.conf
I've changed usage of the missing macro %{_sysctldir} to %{_sysconfdir}/sysctl.d
Note that since this package has not built or been release yet, I'm not modifying the changelog.
- Change %{_sysctldir} to %{_sysconfdir}/sysctl.d in elfutils.spec
**YES**
- Pipeline build id: 128532
> Fix elfutils break from _sysctldir macro

- toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
Remove references to "toolchain-md5sums", which was replaced by "toolchain-sha256sums"
This typo caused the "toolchain-local-wget-list" file to not be created, meaning toolchain sources were always pulled from remote servers instead of the cache located at SOURCE_URL
- Replace "toolchain-md5sums" with "toolchain-sha256sums"
**YES**
- Trivial change, not tested.
> Remove references to toolchain-md5sums

- toolkit/imageconfigs/packagelists/azurevm-packages.json
Add rsyslog by default to Mariner cloud images .
---
Most of customers leverages syslog in some form as OS logging standard.
Adding rsyslog feature package by default to Mariner cloud images which is commonly used.
Change Log
Change
Add rsyslog by default to Mariner cloud images
Does this affect the toolchain?
NO
Associated issues
#xxxx
Links to CVEs
https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX
Test Methodology
Local validation
> Add rsyslog by default to Mariner cloud images (#1385)

- toolkit/scripts/srpm_expand.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/toolchain.mk
---
This is a port of applicable changes from #765 to the 2.0 branch. In particular, this cleans up SRPM expansion logs by excluding long filepath outputs and cpio outputs.
From the original PR: 
This PR aims at reducing the noise and confusion around the logs printed during RPMs builds.
- See #765 for a detailed list of changes.
**NO**
- Local test runs touching affected parts of the toolkit
> [dev] Cleaning SRPM expansion console output

- SPECS/shadow-utils/pam.d/system-password
- SPECS/shadow-utils/shadow-utils.signatures.json
- SPECS/shadow-utils/shadow-utils.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
2.0 branch images have been failing to provision using `cloud-init` since the last 1.0 merge. This issue was traced to a `pam` upgrade which removed the pam_cracklib.so library. `shadow-utils` uses that library when setting passwords, and the library's absence caused user provisioning failures. We follow shadow-utils maintainer advice and replace the removed library with `pam_pwquality.so`.
- Use `pam_pwquality.so` in system-password PAM config 
**YES**
- Local build of core VHD/VHDX images. Was able to setup and login to a user account using cloud-init.
> Use pam_pwquality in system-password PAM config

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
A recent kernel spec change ([link](https://github.com/microsoft/CBL-Mariner/commit/41e2db40dd2849da8e11380e02664b9b0b13e59c)) moved the “cn” module to be built into the kernel instead of as a loadable module. Since “cn” is still in dracut’s --add-drivers line, Dracut silently errors and does not install the additional drivers. Solution is to remove the cn from dracut's --add-drivers.
- Remove cn from drivers loaded for dracut
**YES**
- Pipeline build id: AMD: 131093 ARM: 130842
- Local package build and image and checking command ```sudo mkinitrd 2>&1 | tee log.txt``` runs without failure
> kernel: Remove cn from drivers argument

- SPECS/UI-cairo/UI-cairo.spec
- SPECS/binutils/binutils.spec
- SPECS/cairo/cairo.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adding the `libiberty` components to `binutils` to satisfy common requirements.
I've also updated `cairo` and `UI-cairo` builds. The new header and library triggers a build of the `symbol-lookup` feature, which fails to compile due to errors. Disabling that feature until required.
- Extended `binutils` with `libiberty`.
- Disabled `symbol-lookup` feature in `cairo` and `UI-cairo`.
Yes.
- Pipeline toolchain build.
> [dev] `binutils`: adding `libiberty` library and header

- SPECS/qemu-kvm/CVE-2020-12829.nopatch
- SPECS/qemu-kvm/CVE-2021-3713.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
This change fixes qemu CVE-2021-3713. I have also reorganized the patch files to support autopatching, removing some verbosity.
- Add patch for CVE-2021-3713
- Reorganize patch files to support autopatching
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3713
- Local build
> Fix qemu CVE-2021-3713

- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/rsyslog/rsyslog.spec
---
Fixing permissions on /etc/rsyslog.d and /sys/devices/virtual/dmi/id/product_uuid to improve compat with AMA and ASA VM extensions.
Porting 1.0-dev fix into dev: https://github.com/microsoft/CBL-Mariner/pull/1413
- Create /etc/rsyslog.d explicitly with correct permissions in the rsyslog package
- Add product_uuid permission udev rule to WALinuxAgent package
**NO**
- Local Build
> [dev] Fix rsyslog.d and product_uuid permissions

- SPECS/mariner-rpm-macros/gen-ld-script.sh
- SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
- SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The ELF metadata parameter "moduleVersion" should always be a 4 part version string. add padding when necessary.
Also build and install the mariner-release package at the beginning of the toolchain build process, so that the "/etc/os-release" file is available for all other packages.
- Change gen-ld-script.sh to pad moduleVersion
- Change build_official_toolchain_rpms.sh to install the mariner-release package
**YES**
- Pipeline build id: 134044
> Pad moduleVersion in ELF metadata and install mariner-release in toolchain

- toolkit/scripts/tools.mk
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/verityerrorbehavior_test.go
---
We did not catch several invalid configurations:
- We did not check if a `PartitionSetting` actually referred to a disk `partition` which existed.
- We did not check if multiple disk `partition`s shared an ID
- Add `checkForMissingDiskPartitions()` to `configuration.go:IsValid()` to make sure all `PartitionSettings` have a matching partition listed in `Disks`
- Add `checkDuplicatePartitionIDs()` to `configuration.go:IsValid()`  to find duplicated entries in `Disks`.
- Improve how we generate code coverage (union all tests together when calculating coverage, for example we did not include the coverage from testing `ConfigurationValidator` in our coverage report for …
> Add partition and disk config validation

- toolkit/docs/formats/imageconfig.md
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/mountidentifier.go
- toolkit/tools/imagegen/configuration/mountidentifier_test.go
- toolkit/tools/imagegen/configuration/partition.go
- toolkit/tools/imagegen/configuration/partition_test.go
- toolkit/tools/imagegen/configuration/partitionsetting.go
- toolkit/tools/imagegen/configuration/partitionsetting_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
- toolkit/tools/imagegen/configuration/testdata/test_configuration.json
---
Allow the user to decide how to identify devices to be mounted in the `fstab`: `UUID`, `PARTUUID`, or `PARTLABEL`. To preserve backwards compatibility `PARTUUID` is selected by default if the key is left unset.
Future PR will update `imager` to respect these configs.
- Add `[MountIdentifier]` key to `[PartitionSetting]`
- May be one of: `uuid`, `partuuid`, `partlabel`
- Default value if unset it `partuuid`
- ~**NOTE:** `configuration_test.go` is heavily dependent on #1440. Instead of teasing the changes apart I left the file as the union of both change sets here. A rebase will be needed once that PR is complete to get the tests passing.~ Fixed
**NO**
- Local builds
> Add MountIdentifier key to PartitionSetting struct

- SPECS/atftp/atftp.signatures.json
- SPECS/atftp/atftp.spec
- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
CVE fixes for atftp and vim.
1. Fix CVE-2021-3778 and CVE-2021-3796 CVEs by updating to vim version 8.2.3441
2. Fix CVE-2021-41054 by updating to atftp version to 0.7.5
---
CVE fixes for atftp and vim.
1. Fix CVE-2021-3778 and CVE-2021-3796 CVEs by updating to vim version 8.2.3441
2. Fix CVE-2021-41054 by updating to atftp version to 0.7.5
- Change
Fix CVE-2021-3778 and CVE-2021-3796 CVEs by updating to vim version 8.2.3441
- Change
Fix CVE-2021-41054 by updating to atftp version to 0.7.5
**NO**
- #xxxx
-  https://nvd.nist.gov/vuln/detail/CVE-2021-3778
-  https://nvd.nist.gov/vuln/detail/CVE-2021-3796
- …
> CVE fixes for atftp and vim

- SPECS/grpc/grpc.spec
---
The grpc-devel package pulls in a number of header files that are not part of grpc. This leads to conflicts when installing grpc-devel along with re2-devel (and possibly other packages). I've modified the grpc-devel subpackage to only include the needed grpc-related headers and libraries.
```bash
WARN[0227] file /usr/include/re2/filtered_re2.h from install of re2-devel-20190801-9.cm1.x86_64 conflicts with file from package grpc-devel-1.35.0-4.cm1.x86_64
WARN[0227] file /usr/include/re2/re2.h from install of re2-devel-20190801-9.cm1.x86_64 conflicts with file from package grpc-devel-1.35.0-4.cm1.x86_64
WARN[0227] file …
```
> Fix grpc-devel file conflict

- SPECS/ostree/0001-ostree-Copying-photon-config-to-boot-directory.patch
- SPECS/ostree/0002-ostree-Adding-load-env-to-menuentry.patch
- SPECS/ostree/0003-ostree-converting-osname-to-mariner.patch
- SPECS/ostree/dualboot-support.patch
- SPECS/ostree/ostree.signatures.json
- SPECS/ostree/ostree.spec
- SPECS/rpm-ostree/rpm-ostree-disable-selinux.patch
- SPECS/rpm-ostree/rpm-ostree-libdnf-build.patch
- SPECS/rpm-ostree/rpm-ostree.signatures.json
- SPECS/rpm-ostree/rpm-ostree.spec
- cgmanifest.json
---
Recent upgrade to libmodulemd broke rpm-ostree build. The attempted fix for that (upgrade rpm-ostree to 2021.11) ended up revealing some incompatibilities between our current versions of rust/systemd/rpm and newer versions of rpm-ostree. This new fix upgrades ostree and downgrades rpm-ostree to the newest version that will build with our package ecosystem. We can upgrade more once we get the above mentioned packages upgraded as part of our 2.0 push.
- Upgrade ostree to 2021.4 and rebase patches
- Downgrade rpm-ostree to 2020.4 from 2021.11 and rebase patches
- Note: rpm-ostree 2021.11 was never built and released in our pipelines
**YES/NO**
> [dev] Align rpm-ostree version with our packaging ecosystem

- SPECS/openssh/openssh.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Fixing the toolchain build after recent changes. I've missed the dependency `finger` has on `systemd`. Turns out, we don't need  `tcp_wrapper` (the only package depending on it) in the toolchain any more, so both are being removed from that phase of the build.
Also, I misconfigured `openssh.spec` while adding a new subpackage. The new package's `Version` tag overwrote the first declaration of `Version` and made `openssh-server` defined underneath the new package require a non-existing version of `openssh-client`.
- Remove `tcp_wrapper` and `finger` from toolchain builds.
- Fix version requirements inside `openssh.spec`.
Yes.
> [dev] Fixing toolchain and `openssh` builds.

- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Related to #1477 and #1480.
Another fix for the toolchain. I missed removing one package built by `cryptsetup` from the manifest and `cryptsetup` is no longer present in the toolchain.
- Remove `integritysetup` from the toolchain manifest.
Yes.
- #1477
- #1480
- Pipeline failure log check indicating that the removed package couldn't be installed. The toolchain itself built fine.
> [dev]: Another fix for the toolchain build.

- toolkit/scripts/srpm_expand.mk
---
When I cleaned up SRPM expansion logging output (#1384), I used an incorrect variable when comparing SRPM modification time to the modification time of a flag file. This broke re-expansion of modified SRPMs when initial expansion had already been done. Fix line to use correct variable.
- Fix variable referenced in srpm expansion check.
**NO**
- Used in local builds, able to re-expand SRPMs now
> [dev] Fix SRPM re-expansion detection logic

- SPECS/libinput/libinput.spec
- SPECS/systemd/systemd.spec
---
The additional `Provides: systemd-boostrap` inside `systemd.spec` was creating circular dependencies from packages, which explicitly pick `systemd-bootstrap`. We're making `systemd` obsolete `systemd-bootstrap`, but the latter still has to be considered an option, when `systemd` is not yet available.
- Removed `Provides: systemd-boostrap*` from `systemd.spec`.
- Made `libinput` BR explicitly `systemd-devel` instead of `pkgconfig(libudev)` to avoid confusion between `systemd-devel` and `systemd-bootstrap-devel`.
No.
- #1488
- Local package build of all packages involved in the circular dependency and `libinput`, which previously suffered from misconfigured dependencies and tooling …
> [dev] `systemd`: removing incorrect `Provides` and changing `libinput` BR.

- SPECS/moby-containerd/CVE-2021-41103.patch
- SPECS/moby-containerd/moby-containerd.spec
---
Patch CVE-2021-41103 in moby-containerd
- Patch CVE-2021-41103 in moby-containerd
- Refactor moby-containerd spec file to be more idiomatic
**NO**
- https://github.com/containerd/containerd/security/advisories/GHSA-c2h3-6mxw-7mvq
- https://nvd.nist.gov/vuln/detail/CVE-2021-41103
- Local build
- Tested package update on a running kubernetes cluster
> Fix moby-containerd CVE-2021-41103

- SPECS/moby-containerd/CVE-2021-41103.patch
- SPECS/moby-containerd/moby-containerd.spec
---
Patch CVE-2021-41103 in moby-containerd
Cherry-picked from 1.0-dev https://github.com/microsoft/CBL-Mariner/pull/1492
- Patch CVE-2021-41103 in moby-containerd
- Refactor moby-containerd spec file to be more idiomatic
**NO**
- https://github.com/containerd/containerd/security/advisories/GHSA-c2h3-6mxw-7mvq
- https://nvd.nist.gov/vuln/detail/CVE-2021-41103
- Local Build
- Tested package update on a running kubernetes cluster
> Fix moby-containerd CVE-2021-41103 (#1492)

- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/rpm/rpm_test.go
- toolkit/tools/internal/rpm/testdata/no_exclusive_architecture.spec
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
In #1511 I've missed the case where `ExclusiveArch` is not present. Fixing this here and unifying code with `dev` at the same time.
- Fix `SpecExclusiveArchIsCompatible` for the case where there's no `ExclusiveArch` tag.
- Unify code with the version from `dev`.
- Extend unit tests to cover the missed case.
No.
- #1511
- #1514
- Local test run.
> Fixing no `ExclusiveArch` tag case

- SPECS/openscap/openscap.spec
---
The oscap tool can query systemd services, but needs to be compiled with dbus-devel for that module to be included.
- Add dbus-devel to opscap spec
- Fix linter issues with openscap spec
**NO**
- Local build, local runs
> [1.0] openscap: Add dbus BuildRequire to oscap package

- .github/workflows/check-spec.yml
- .github/workflows/check_spec_guidelines.py
---
Adding expected spec source attributions for CentOS specs. We're expecting to be importing these every now and then.
I'm also updating specs check to always run, since the check is mandatory and would block PRs, which don't modify any .spec files.
- Added spec source attribution check for CentOS spec files.
- Updated specs check to always run.
No.
> [dev] Adding proper spec source attribution for CentOS specs

- SPECS/ansible/ansible.spec
---
Ansible does not run after installation.  It is missing two runtime requires to launch.  While the dependencies can be added manually, this change provides the missing packages.
NO
> Add missing runtime requires for ansible

- .github/workflows/validate-cg-manifest.sh
---
As per #1094, we are not allowed to use tildes in the cgmanifest file. We should be replacing tildes with dashes to meet the requirements of those consuming this file. However, we have no allowances for this behavior in our mandatory cgmanifest check. This substitution causes a failure.
So, I wrote a quick hack to allow for tilde substitutions when version matching the cgmanifest entries.
This could probably be a more robust check, but for now I just want to unblock #1603. This fix should keep people from seeing an erroneous check failure and undoing the change in #1094.
- Allow `jq` lookup in `validate-cg-manifest.sh` to account for tilde substitution.
**NO**
- Manual testing, …
> Fix cgmanifest validation script by allowing tilde substitution in version match

- SPECS/libgcrypt/CVE-2021-33560.patch
- SPECS/libgcrypt/CVE-2021-40528.patch
- SPECS/libgcrypt/libgcrypt.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add upstream patch for libgcrypt CVE-2021-33560.
Note: CVE-2021-33560 seems to have been renamed to CVE-2021-40528 at some point, and CVE-2021-33560 was given to a different bug. [This was also observed by the Ubuntu folks.](https://ubuntu.com/security/CVE-2021-33560)
- Rename CVE-2021-33560 patch to reflect that it actually applies to CVE-2021-40528.
- Add patch for CVE-2021-33560
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-33560
- Local build
> Add patch for libgcrypt CVE-2021-33560

- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
---
Upgrade vim to 8.2.3564 to fix CVE-2021-3903.
- Upgrade vim to 8.2.3564 to fix CVE-2021-3903
- Remove `rgb.txt` file from packaging
- Package the actual Vim license text with the `%license` macro
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3903
- Local build
> Upgrade vim to 8.2.3564 to fix CVE-2021-3903

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping Mariner Release version to support off-cycle update.  This update is to fix several accumulated CVE's in the toolchain.
> Bump mariner-release number for full-off-cycle build

- SPECS/libsepol/libsepol.signatures.json
- SPECS/libsepol/libsepol.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The `libsepol` build was failing completely during our test builds due to invalid `BuildRequires` entry. In addition to fixing the entry, I've fixed the tests as well.
- Using correct `BuildRequires` for `CUnit-devel` inside `libsepol.spec`.
- Fixing `libsepol` tests.
Yes.
- Local package build with `RUN_CHECK=y`.
> [dev] Fixing `libsepol` tests.

- toolkit/Makefile
- toolkit/docs/building/building.md
- toolkit/scripts/tools.mk
---
Due to how packages are built, the worker chroot kept being constantly rebuilt, even if it was unnecessary. Fixing the underlying issue with proper detection of when the rebuild is required will require more complex changes to our build infrastructure, so for now I'm adding the `REFRESH_WORKER_CHROOT` argument, to skip rebuilds, if you know they are not necessary. The default behaviour remains unchanged.
- Adding an new `REFRESH_WORKER_CHROOT` build tools argument.
- 
No.
> [dev] Adding a switch to skip chroot rebuilds

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
This change just bumps the Mariner-Release again in support of a second off-cycle build.
This build includes a fix to the toolchain package glibc and a fix for vi.
> Bump Mariner Release for 2nd Full Off-Cycle Build

- SPECS/harfbuzz/harfbuzz.signatures.json
- SPECS/harfbuzz/harfbuzz.spec
- cgmanifest.json
---
Update harfbuzz to 2.6.4. This is required to support librsvg2 in CBL-MarinerCoreUI.
- Update harfbuzz to 2.6.4 by porting from dev branch, and modified SPEC file to accommodate 1.0 branch.
**NO**
- local build
> update harfbuzz to 2.6.4

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The kernel's perf tools expose a python extension library. This PR adds this as a `python3-perf` subpackage in the kernel spec.
Additionally, a fix is included to stop accessibility driver modules from being packaged in both the `kernel` package and the `kernel-drivers-accessibility` subpackage. These drivers will only be available in the `kernel-drivers-accessibility` subpackage going forward. 
- Build and package the kernel's `python3-perf` extension.
- Exclude accessibility driver modules from being packaged in the main kernel package.
- Bump `kernel-signed` and `kernel-headers` releases, lint kernel-headers
**NO**
- Builds locally. Confirmed functionality of python extension …
> [dev] Add python3-perf subpackage to kernel

- SPECS/nodejs/clean-source-tarball.sh
- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- SPECS/nodejs/remove_unsupported_tlsv13_ciphers.patch
- cgmanifest.json
---
Upgrades nodejs to v14.18.1, the latest version of the v14 LTS branch. This fixes several CVEs, which are all linked further down.
An interaction between our OpenSSL configuration and Node's default cipher list was causing failures when creating secure contexts in the TLS library. The `TLS_CHACHA20_POLY1305_SHA256` ciphersuite is unsupported by our OpenSSL configuration, but is a default nodejs cipher. OpenSSL does not like being asked to use TLSv1.3 ciphersuites it does not support, so we remove this ciphersuite from the default cipher list. Note that this is not an issue with TLS <= v1.2 ciphers.
Node ships with a bundled OpenSSL source tree. This source tree contains patented …
> Upgrade nodejs to v14.18.1 to fix several CVEs and cryptography bugs

- SPECS/libxcrypt/libxcrypt.spec
---
Update libxcrypt.spec to require current version of glibc 2.34.
Fixes following error:
INFO[21250] Blocked SRPMs: 
INFO[21250] --> libxcrypt-4.4.17-3.cm2.src.rpm 
INFO[21250] Unresolved dependencies: 
INFO[21250] --> glibc 
INFO[21250] --> glibc-devel 
- Change libxcrypt to require glibc version 2.34
**NO**
- Local build
> update libxcrypt required glibc version

- SPECS/pcsc-lite-ccid/pcsc-lite-ccid.spec
---
Currently our build tooling is having issues with multiple packages providing the same version of `bundled(simclist)` and while we're waiting for the fix, we need to add this workaround.
Nothing is expected to ever require `bundled(simclist)` - that would probably be an invalid configuration, since `simclist` is compiled into the project, but is not exposed externally by the project's APIs/libraries. The `Provides` is there to make it easier to find packages, which would require an update in case a CVE is ever created against `simclist`.
- Disabled `Provides: bundled(simclist)` by hiding it behind an always-off macro.
No.
- None, simple .spec change, no build-time effect.
> [workaround] `pcsc-lite-ccid`: disabling `Provides: bundled(simclist)`.

- SPECS/pgbouncer/pgbouncer.signatures.json
- SPECS/pgbouncer/pgbouncer.spec
- cgmanifest.json
- pgbouncer: bump version to fix CVE-2021-3935
- cgmanifest: pgbouncer: bump version 1.11.0 -> 1.16.1
---
Bump version 1.11.0 -> 1.16.1 to fix CVE-2021-3935
- Bump version 1.11.0 -> 1.16.1
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3935
- Local Build with `RUN_CHECK=y`
> pgbouncer: bump version to fix CVE-2021-3935

- SPECS/pgbouncer/pgbouncer.signatures.json
- SPECS/pgbouncer/pgbouncer.spec
- cgmanifest.json
- pgbouncer: bump version to fix CVE-2021-3935
- cgmanifest: pgbouncer: bump version 1.11.0 -> 1.16.1
---
- Bump version 1.11.0 -> 1.16.1 to fix CVE-2021-3935
- It's a `cherry-pick` of #1686
- Bump version 1.11.0 -> 1.16.1
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3935
- Local Build with `RUN_CHECK=y`
> [dev] pgbouncer: bump version to fix CVE-2021-3935

- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
- toolkit/scripts/toolchain/container/Dockerfile
---
We have a fair number of packages in the toolchain. Toolchain packages should be a base set of packages needed to bootstrap a package building environment along with the packages needed to build them. After the recent removal of certain packages (`audit`, `openldap`, `tcp_wrappers`, `cryptsetup`, `lvm2`) from the toolchain, we no longer need several of their dependencies to be in the toolchain.
- Remove `golang` from the toolchain- not needed after previous removal of `audit`
- Remove `libcap-ng` from the toolchain- not needed after previous removal of `audit`
- Remove `groff` from the toolchain- not needed after previous removal of `openldap`
- Remove `perl-File-HomeDir` from …
> [dev] Prune unnecessary toolchain packages

- SPECS/blobfuse/blobfuse.spec
---
Re-add the CFLAGS changes from `blobfuse-1.3.6-5` to enable the ARM64 build.
- Re-add lines to turn off `-Werror=type-limits` in `blobfuse`.
**NO**
- Pipeline build underway
> [dev] Fix blobfuse build error on aarch64 with GCC11

- SPECS/gd/gd.signatures.json
- SPECS/gd/gd.spec
- cgmanifest.json
---
Updates libgd to 2.3.3 to address CVEs CVE-2021[-38115, -40145, -40812]
Updates libgd to 2.3.3 to address CVEs CVE-2021[-38115, -40145, -40812]
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-38115
- https://nvd.nist.gov/vuln/detail/CVE-2021-40145
- https://nvd.nist.gov/vuln/detail/CVE-2021-40812
> Upgraded libgd to 2.3.3 to address CVEs

- toolkit/tools/imagegen/attendedinstaller/views/diskview/autopartitionwidget/autopartitionwidget.go
- toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
When running the ISO installer we manually instantiate the `PartitionSettings` which skips the default value generation found in the json unmarshal code. We need to explicitly set the `MountIdentifer` added in #1444 when running the ISO installer to the default value (`partuuid`).
- Auto set the `MountIdentifier` to `partuuid` when using the ISO installer
**NO**
- Waiting on pipeline build of ISO installer to validate
> [main] Fix blank mountidentifiers in ISO installers

- toolkit/scripts/analysis.mk
- toolkit/scripts/sodiff/mariner-sodiff.sh
---
Current mechanism to parse final output of sodiff did not work. Changed to one based on word-count.
- Change sodiff detection mechanism to a more foolproof method.
**NO**
- Local build
> Fix sodiff's interpretation of final result file

- SPECS/systemd/99-dhcp-en.network
- SPECS/systemd/systemd-bootstrap.signatures.json
- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.cfg
- SPECS/systemd/systemd.signatures.json
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updating to systemd 249.7 caused some divergence from default behaviors that Mariner expects. This release addresses those changes and sets the default behaviors back to a working configuration.
Updated systemd-networkd setting with SendRelease=false so DHCP client won't release the IP address on shutdown.
Updated systemd cmdline args with systemd.unified_cgroup_hierarchy=0 to force cgroups v1
- Add SendRelease=false to 99-dhcp-en.network so IP addresses are retained across reboot.
- Add systemd.unified_cgroup_hierarchy=0 to systemd.cfg so that cgroups v1 is selected.
**YES**
- Full Local build
- Gen1 Hyper-V boot maintains IP addr on reboot and uses cgroups v1
> Fix systemd dhcp and cgroups

- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The 3.21.X+ version of `cmake` has[ an issue with one of its tests](https://gitlab.kitware.com/cmake/cmake/-/issues/22470), which hasn't been resolved, yet. I'm adding a workaround until the issue is resolved and the fix applied.
I've also restored generation of debug symbols for `cmake`.
- Adding a workaround for two failing `cmake` test cases.
- Restoring generation of `cmake` debug symbols.
Yes.
- Local package build and tests.
> [main] Fixing `cmake` tests and restoring generation of its debug symbols.

- SPECS/mcpp/mcpp.spec
Fix missing dependency/build break for libmcpp-devel
> Fix libmcpp-devel requires (Build break)

- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
- SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
---
The `prebuilt-ca-certificates-*` were making too many assumptions on the contents of the worker chroot in their build steps, which caused build breaks when the environment changed recently. This PR makes the build assume only the existence of the components, which absolutely need to be there for the build to succeed.
The `prebuilt-ca-certificates-base` package was also accidentally providing the certs from `ca-certificates`, which shouldn't happen. Fixed this as well.
- Fixed the build steps for `prebuilt-ca-certificates-*`.
- Removed certs from `ca-certificates` from `prebuilt-ca-certificates-base`.
No.
> [main] Fixing `prebuilt-ca-certificates-*` packages builds and contents.

- SPECS/kernel/kernel.spec
---
Temporarily disable arm64 kernel debuginfo package since it is getting stuck during builds
Builds are getting stuck after this line:
"Processing files: kernel-debuginfo-5.10.78.1-1.cm2.aarch64"
The next output (which is not seen with most recent builds) begins with:
"Provides: debuginfo(build-id) = 0f04bc135a0815018e14f5c337e681cf6dd1900e debuginfo(build-id) ...”
- Disable debuginfo package for arm64 kernel
- Exclude vmlinux from arm64 kernel build
**NO**
- Local build
> disable arm64 kernel debuginfo

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
---
In 2.0 the `%prep` stage populates the build directory with an `ld` script, which most specs use while linking but the file itself never ends up in the `BUILDROOT` folder. The `kernel-signed.spec` doesn't do any building, just extracts an already built RPM containing the `kernel` package, copies over its contents and the signed kernel, and bundles this all up in another RPM. The copying was now accidentally picking up the `ld` scripts and placing them inside the `BUILDROOT` folder, so it needed to be fixed.
**NOTE**: I'm not updating the `Release` tag as this package and its SRPM were never published for 2.0.
- Made sure we only copy over the files we need for `kernel-signed`. …
> [main] `kernel-signed`: skip copying `ld` scripts from `%prep` phase.

- .github/workflows/check-entangled-specs.yml
- .github/workflows/check_entangled_specs.py
- .github/workflows/validate-cg-manifest.sh
- SPECS/ca-certificates/ca-certificates.spec
- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
- SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
As part of updating `rust` in #1678 I added `ca-certificates` to the worker chroot, which caused `prebuilt-ca-certificates-base` to accidentally build with the contents of `ca-certificates`, so way more certificates, than we need there. I'm fixing this bug here.
While I'm here, I've also updated the versions and URLs for our certificate packages.
- Made sure we remove `ca-certificates` before building `prebuilt-ca-certificates`.
- Updated the versions of the cert packages to 2.0.0.
No.
> [main] Resetting the version of `ca-certificates` to something more meaningful.

- SPECS/python-lxml/python-lxml.signatures.json
- SPECS/python-lxml/python-lxml.spec
- cgmanifest.json
---
upgrade to 4.7.1 to fix CVE-2021-43818
- python lxml spec file
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-43818
> python-lxml - upgrade to 4.7.1 to fix CVE-2021-43818

- SPECS/dstat/dstat.spec
- SPECS/log4cpp/log4cpp.spec
---
Clean sections were removed from our specs en masse in #1782. This PR fixes a couple of build failures introduced by incomplete `%clean` section removal. 
- Fix incomplete %clean section removal in dstat, log4cpp
- Spec file release numbers were not bumped because these packages have not been published.
**NO**
- Re-running package build for stat, log4cpp
> Fix incomplete %clean section removal in dstat, log4cpp

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
This change bumps the mariner-release number in support of the Mariner 1.0 December 2021 update
> Bumpr release for Mariner 1.0 Dec 2021 Update

- SPECS/ca-certificates/ca-certificates.spec
- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
- SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
---
#1773 added an epoch to our certificate packages in order to allow for a version scheme reset. However, that PR did not update some of the requirements on certificate packages that were looking for specific versions, leading to unresolved dependencies. This PR remedies this by making the requirements epoch-aware.
- Update `ca-certificates`, `prebuilt-ca-certificates`, `prebuilt-ca-certificates-base` with epoch-aware requirements
- Package releases numbers were not bumped, as these packages have not built yet.
**YES**
- Re-seed pipeline build
> Fix version requirements on ca-certificates packages

- SPECS/bond/bond.spec
---
Only build bond against x86_64 architecture
- bond spec
**NO**
- #xxxx
> Only build bond against x86_64 architecture

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Currently aarch64 debug info rpm is disabled to generate.
Provides exclude /usr/lib/debug/.build-id to generate aarch64 debuginfo rpm
Fix missing brackets for os_post_install in kernel SPEC. 
- Change
Provides exclude debug build-id to generate aarch64 debuginfo rpm.
Fix missing brackets for os_post_install. 
**YES**
- #xxxx
> Provides exclude debug build-id to generate aarch64 debuginfo rpm

- SPECS/check-restart/check-restart.service
- SPECS/check-restart/check-restart.signatures.json
- SPECS/check-restart/check-restart.spec
- SPECS/check-restart/check-restart.timer
---
Avoid starting the service on reboot
- Fixes the service and timer so that the service is not started on every system reboot
- The timer starts on every system reboot. If it has a 'Require' on the service, it will start the service as well on reboot. Hence, removed that line
- A systemd service having an 'install' section marks its state as 'enabled'. This starts the service on every reboot. Removing this section marks the service unit's state as 'static'.
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/37411367
- None
- Local build, tested new package in VM on hyper-v and observed correct behavior
> Avoid starting the `check-restart` service on reboot

- SPECS-EXTENDED/bsh/bsh.spec
- SPECS-EXTENDED/flute/flute.spec
- SPECS-EXTENDED/jakarta-commons-httpclient/jakarta-commons-httpclient.spec
- SPECS-EXTENDED/jss/jss.spec
- SPECS-EXTENDED/lasso/lasso.spec
- SPECS-EXTENDED/libvirt-java/libvirt-java.spec
- SPECS-EXTENDED/openmpi/openmpi.spec
- SPECS-EXTENDED/sblim-cim-client2/sblim-cim-client2.spec
- SPECS-EXTENDED/tomcat/tomcat.spec
- SPECS-EXTENDED/tomcatjss/tomcatjss.spec
- SPECS/javapackages-tools/javapackages-tools.spec
- SPECS/javapackages-tools/remove-epoch-from-java-requires.patch
- SPECS/javapackages-tools/remove-headless-from-java-requires.patch
- cgmanifest.json
---
Our current RPM build of `msopenjdk-11` does not provide the `java-headless` name. This PR patches the `javapackages-tools` package to generate RPM dependencies on `java` rather than `java-headless` accordingly.
- Add patch to replace generated dependency on "java-headless" with "java"
- Amend epoch patch to fix expected test results
- Remove obsoletes statements that don't apply to Mariner
- Install test requirements with pip during check section
**NO**
- Ongoing pipeline build
> [main] Replace generated dependencies on java-headless with java

- SPECS/libvirt/libvirt.spec
- SPECS/lvm2/lvm2.spec
- cgmanifest.json
---
Some of `libvirt` components depend on `glusterfs`, which is having issues correctly installing in our build environment. Until that's resolved, I'm disabling the bits causing the issue.
For `lvm2` we're removing the services, which are no longer present in the newer versions and cause install-time warnings and errors.
- Disabled `libvirt` subpackages, which require `glusterfs`.
- Removed `lvm2` invalid services.
No.
> [main] Fixing `libvirt` and `lvm2` builds.

- SPECS/bash-completion/bash-completion.signatures.json
- SPECS/catch/catch.signatures.json
- SPECS/chkconfig/chkconfig.signatures.json
---
Fix input-srpms build break by changing incorrect hashes.
Fixes errors:
WARN[0023] no signature for file (bash-completion-2.11.tar.gz) found. full path is (/build/bash-completion-2.11-1.cm2.src.rpm/SOURCES/bash-completion-2.11.tar.gz) 
WARN[0028] no signature for file (Catch2-2.13.8.tar.gz) found. full path is (/build/catch-2.13.8-1.cm2.src.rpm/SOURCES/Catch2-2.13.8.tar.gz) 
WARN[0016] no signature for file (chkconfig-1.20.tar.gz) found. full path is (/build/chkconfig-1.20-1.cm2.src.rpm/SOURCES/chkconfig-1.20.tar.gz) 
- Change bash-completion
- Change catch
- Change chkconfig
**NO**
- #xxxx
- …
> Fix package signatures

- SPECS/mysql/mysql.spec
---
We've spotted a flaky test in `mysql`. Since it has no issues locally and isn't critical, we're disabling it for now.
- Disabled the `invalid_metadata` test for `mysql`.
No.
> Skipping flaky `invalid_metadata` test.

- SPECS/bash/bash-4.4.patch
- SPECS/bash/bash.spec
- SPECS/bash/bash44-019.patch
- SPECS/bash/bash44-020.patch
- SPECS/bash/bash44-021.patch
- SPECS/bash/bash44-022.patch
- SPECS/bash/bash44-023.patch
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Certain users of our bash package have encountered a rare hang in bash due to exhaustion of the hash table which bash uses to store exit codes. Our current version of bash is 4.4.18, and this hang was fixed in bash 4.4.20.  This PR upgrades our version to bash 4.4.23, which is the latest patch version of bash 4.4.
Bash 4.4.18 is the last source tar.gz they released for 4.4, and subsequent versions beyond are provided as patch files.
- Update bash to 4.4.23 to fix a rare hang.
- Update existing patch to work with `patch -p0`
**YES**
- Installed updated bash in a VM
> Update bash to version 4.4.23

- SPECS/moby-runc/moby-runc.spec
---
Reverting a change to BuildRequires for moby-runc. The spec is requiring pkgconfig when it should require pkg-config. pkgconfig is not available as a provides, causing a build break during graph creation for build-order scheduling.
- Update BuildRequires in moby-runc to fix a graph break.
**NO**
- moby-runc SRPM rebuilt and graph processed the BuildRequires successfully.
- moby-runc package built.
> Fix moby-runc BuildRequires

- SPECS/parted/parted.signatures.json
- SPECS/parted/parted.spec
- cgmanifest.json
Reverts microsoft/CBL-Mariner#1898
Parted is breaking boot from full.iso. Reverting upgrade until patch is thoroughly tested
> Revert "Upgrading Parted to v3.4"

- SPECS-EXTENDED/dnf-plugins-core/dnf-plugins-core.spec
- SPECS-EXTENDED/hfsplus-tools/hfsplus-tools.spec
- SPECS-EXTENDED/ocaml-findlib/bytes-lib-detection.patch
- SPECS-EXTENDED/ocaml-findlib/ocaml-findlib.spec
- SPECS-EXTENDED/zfs-fuse/zfs-fuse.spec
- cgmanifest.json
---
Fix builds of extended specs dnf-plugins-core, ocaml-findlib
- ocaml-findlib: Add patch for detection of ocaml stdlib features in ocaml 4.13.X
- dnf-plugins-core: Only ask for python3-nose during test builds
**NO**
- Local package builds
> [main extended] Fix dnf-plugins-core, ocaml-findlib builds

- SPECS/lttng-consume/lttng-consume.spec
---
lttng-consume breaks the build due to a dependency on a function `lib_ring_buffer_align`.
Disable tests to enable build.
- Disable tests to enable build
**NO**
- NA
- NA
> lttng-consume: disable tests to fix build break

- toolkit/scripts/license_map.py
---
The error message displayed by `license_map.py` was confusing, making the tool hard to use to fix any PR check failures. I hope this change will help a little bit. Now the printed error will look like so:
```bash
Specs' license information is out of date. Run the following command to regenerate:
toolkit/scripts/license_map.py --no_check --update --remove_missing \
SPECS/LICENSES-AND-NOTICES/data/licenses.json \
SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md \
SPECS SPECS-EXTENDED SPECS-SIGNED
NOTE: the script requires installation of the 'python-rpm-spec' module:
python3 -m pip install python-rpm-spec
```
- Updated message from `license_map.py`.
No.
> Updating tool message.

- SPECS/WALinuxAgent/WALinuxAgent.spec
---
WALinuxAgent depends on python3-distro but wasn't explicitly requesting it in the package. This was causing the agent to crash repeatedly on startup. After installing python3-distro the agent starts successfully.
- Add Requires python3-distro to WALinuxAgent
**NO**
- Local package build. Confirmed new RPM now has the dependency.
- Manually installed python3-distro on the system exhibiting the failure
> [main] WALinuxAgent add python3-distro as Requires

- SPECS/autofs/autofs.spec
---
Last night's build of `autofs` failed. It looks like `autofs` picked a different init directory during configuration than we expected, which led to an unpackaged file error. So, let's wipe both possible init directories in the `autofs` buildroot so we don't run into this again.
- Wipe `/etc/init.d` during `autofs` install
- Use `systemd-devel` BR so `autofs` detects `systemd` properly
**NO**
> [main] [core] Fix autofs packaging with regards to init directory

- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
---
vim: upgrade to v8.2.4120 to fix CVE-2022-0261
- vim: upgrade to v8.2.4120 to fix CVE-2022-0261
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-0261
> [1.0] vim:upgrade to v8.2.4120 to fix CVE-2022-0261

- SPECS/mysql/mysql.signatures.json
- SPECS/mysql/mysql.spec
- cgmanifest.json
---
Update mysql to v8.0.28 to resolve 16 CVEs
- Update mysql to v8.0.28 fix 16 CVE
- Fix CVE: 2022-21245, 2022-21253, 2022-21254, 2022-21256, 2022-21264, 2022-21270, 2022-21284, 2022-21285, 2022-21286, 2022-21287, 2022-21288, 2022-21289, 2022-21290, 2022-21301, 2022-21302 and 2022-21304
- New files were added to mysql in this commit: mysql/mysql-server@b3e00fe. Adding these files to the mysql-devel package.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-21245
- https://nvd.nist.gov/vuln/detail/CVE-2022-21253
- https://nvd.nist.gov/vuln/detail/CVE-2022-21254
- https://nvd.nist.gov/vuln/detail/CVE-2022-21256
- https://nvd.nist.gov/vuln/detail/CVE-2022-21264
- …
> [main] Update mysql to v8.0.28 to resolve 16 CVEs

- SPECS/mysql/mysql.signatures.json
- SPECS/mysql/mysql.spec
- cgmanifest.json
---
Update mysql to v8.0.28 fix 16 CVE
- Update mysql to v8.0.28 fix 16 CVE
- Fix CVE: 2022-21245, 2022-21253, 2022-21254, 2022-21256, 2022-21264, 2022-21270, 2022-21284, 2022-21285, 2022-21286, 2022-21287, 2022-21288, 2022-21289, 2022-21290, 2022-21301, 2022-21302 and 2022-21304
- New files were added to mysql in this commit: https://github.com/mysql/mysql-server/commit/b3e00fe93bd5f5176f73788021ef4624c88d766d. Adding these files to the mysql-devel package.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-21245
- https://nvd.nist.gov/vuln/detail/CVE-2022-21253
- https://nvd.nist.gov/vuln/detail/CVE-2022-21254
- https://nvd.nist.gov/vuln/detail/CVE-2022-21256
- …
> [1.0] Update mysql to fix 16 CVE

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
---
After the upgrade to RPM 4.17, when building on ARM64 only, we are
observing an unexpected /usr/lib/debug/.build-id/xx/yyyy.debug
file being packaged into the kernel.rpm package. This errant file is causing
build errors when repackaging in the kernel-signed build phase.
This patch workarounds the build issue by specifically excluding the
/usr/lib/debug/.build-id folder when building for ARM64. More investigation
underway to identify why this unexpect /usr/lib/debug/.build-id/xx/yyyy.debug
file is being included.
- Exclude repackaging /usr/lib/debug/.build-id in kernel-signed spec
**NO**
Local build on ARM64 system
> kernel-signed: workaround errant .build-id file

- .github/workflows/validate-cg-manifest.sh
- SPECS-EXTENDED/grubby/0013-Fix-build-RPM-416.patch
- SPECS-EXTENDED/grubby/grubby.spec
---
The `grubby` package regressed with our upgrade to RPM 4.17. This PR adds a patch to fix linking with our version of RPM.
- Add Fedora patch file (license: MIT) to fix linking with RPM >= 4.16.0
- Remove git setup steps, apply patches using %%autosetup
- Remove s390x-specific instructions
- Lint spec
**NO**
> [main] [extended] Fix grubby build with newer versions of RPM

- toolkit/tools/internal/pkggraph/pkggraph.go
---
Added a missing `return` statement when dealing with an error inside `pkggraph.go::fixPrebuiltSRPMsCycle()`.
- Added a missing `return` statement.
No.
- Local toolkit build.
> [main] Adding a missing `return` in `pkggragh.go`.

- SPECS/graphviz/graphviz.spec
- SPECS/libpq/libpq.signatures.json
---
- Fix graphviz build error and update libpq signature file
-Remove usage of {?ext_man}, which is not supported in CBL-Mariner
NO
- #xxxx
- Local Build
> [main] Fix graphviz build break and update libpq signature

- toolkit/imageconfigs/core-container.json
- toolkit/imageconfigs/postinstallscripts/core-container/cleanup.sh
---
Ports https://github.com/microsoft/CBL-Mariner/pull/1550 to Mariner 2.0.
Don't overwrite $TERM env-var in container images, the terminal (provided by dockerd or whatever) will set it correctly. the current setting causes issues in e.g. vim where some operations (like ctrl+left/ctrl+right) completely butcher the file being edited.
Probably doesn't need a CHANGELOG entry
No
- None
- None
Tested manually
> [main] Don't overwrite TERM in containers

- SPECS/expat/expat.signatures.json
- SPECS/expat/expat.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade expat to v.2.4.4 to fix CVE-2022-23852
- Upgrade expat to v.2.4.4 to fix CVE-2022-23852
YES
- https://nvd.nist.gov/vuln/detail/CVE-2022-23852
- Local build with RUN_CHECK=y, rebuilt toolchain locally
Closes: #2034 [Autopatcher]
> [1.0] Upgrade expat to v.2.4.4 to fix CVE-2022-23852

- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
I've missed removing the second line adding the `--noscripts` option while we install our Java package. This was still causing issues with Java tooling being unavailable during package builds.
- Removed the missed `--noscripts` option.
No.
- Local chroot build.
- Local build of a package depending on the Java tools.
> [main] Removing missed `--noscripts` option when building the worker chroot.

- toolkit/Makefile
- toolkit/scripts/pkggen.mk
- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
We've been having issues building packages and images in non-core environments. It looks like the main cause was a bug in the code picking the best candidate package when more than one provided the same capability.
- Update the tooling to not error out when choosing between multiple packages providing the same capability.
- Fixed support for using the preview repo for package and image builds.
- Added creation of empty local chroot repositories to avoid noisy TDNF errors inside the logs.
No.
- Local package and image builds wit the new toolkit.
> [main] Fixing tooling issues during package candidates resolution.

- toolkit/Makefile
---
Change #2091 made `USE_PREVIEW_REPO=y` add a .repo file to derivative builds, so they pull core RPMs from the correct repository. Unfortunately, if a core build was ran with this argument, the build would break (core's toolkit doesn't have the .repo files added to its `repos` subdirectory). While the argument is unnecessary for core builds, it shouldn't be breaking them, so I'm adding a check and printing a warning message.
Warning message:
```
Makefile:111: 
Makefile:112: ######################### WARNING #########################
Makefile:113: 'USE_PREVIEW_REPO=y' set but '/home/pawel/CBL-Mariner_package_tests_2.0/toolkit/repos/mariner-official-preview.repo' is missing. …
```
> [main] Preventing core build breaks when running with `USE_PREVIEW_REPO=y`.

- toolkit/Makefile
- toolkit/scripts/pkggen.mk
- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
A cherry-pick of a `main` branch tooling fix from #2091.
- See: #2091.
No.
- #2091
- Local package and image builds.
> [2.0] Fixing tooling issues during package candidates resolution. (CP #2091)

- SPECS-EXTENDED/perl-DateTime-Locale/perl-DateTime-Locale.spec
---
After removing epochs from most of our specs we were left with a few lingering misconfigurations in the specs. For instance `perl-DateTime-Locale` claimed contained a `Conflicts: perl-DateTime <= 1:0.7000-3.fc16` line, which caused build failures, since our current version of `perl-DateTime` has the default epoch 0 but is not actually the conflicting package, which used to cause issues with `perl-DateTime-Locale` in the past.
- Removed invalid `Conflicts` information from `perl-DateTime-Locale`.
No.
- None, simple change.
> [main] Removing invalid `Conflicts` tag form `perl-DateTime-Locale`.

- SPECS-EXTENDED/libguestfs/libguestfs-file-5.40.patch
- SPECS-EXTENDED/libguestfs/libguestfs-ocaml413compat.patch
- SPECS-EXTENDED/libguestfs/libguestfs.signatures.json
- SPECS-EXTENDED/libguestfs/libguestfs.spec
- SPECS-EXTENDED/libguestfs/tdnf-build-cache.repo
---
This PR addresses two bugs in the libguestfs package regarding dependency constraints and UUID parsing. Additionally, this PR cherry-picks changes to libguestfs from 2.0 onto the main branch.
- Add upstream patch to fix UUID parsing with file >= 5.40
- Make selinux-policy a recommended dependency, and remove version constraints
- Pull in changes from #2061, #2067
**NO**
- Local build + installation/functionality test in a 2.0 VM
> [main] [extended] Fix dependency constraints, UUID parsing in libguestfs

- SPECS/polkit/CVE-2021-4034.patch
- SPECS/polkit/polkit.spec
---
polkit: patch for CVE-2021-4034
- polkit: patch for CVE-2021-4034
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-4034
- Local build
> [main] polkit: patch for CVE-2021-4034

- SPECS/pciutils/pciutils.spec
---
A recent update (#1899) added a `libs` subpackage to `pciutils`, but did not add the appropriate requirement on the `libs` subpackage to the main subpackage. This caused the `lspci` utility to fail when the `libs` subpackage was not explicitly installed. This PR adds the appropriate requirement to the main package.
- Require libs subpackage from main package
- Remove libs from main package
**NO**
- Local mock build, Installation in 2.0 container, and successful `lspci` invocation
> [main] [core] pciutils: Require libs subpackage from main package

- toolkit/scripts/analysis.mk
---
"Microsoft" repository is available only for AMD64 architecture. Updated the tooling to skip that repo on non-AMD64 archs.
- Update sodiff .repo files list for non-amd64 architectures.
**NO**
- Local build
> Skip "Microsoft" repo for non-amd64 architectures

- SPECS/snappy/snappy-inline.patch
- SPECS/snappy/snappy.signatures.json
- SPECS/snappy/snappy.spec
- SPECS/telegraf/add-extra-metrics.patch
- SPECS/telegraf/telegraf.signatures.json
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
---
Upgrade snappy to v1.1.9, telegraf to 1.21.2
- Upgrade snappy to v1.1.9
- Add patch to fix compile error due to missing 'inline' 
- Upgrade telegraf to 1.21.2
- Modify patch to apply to new version
- Remove systemctl daemon reload to fix systemd issue with installing it in Mariner container
NO
- Verified that the systemd issue is fixed for telegraf by installing the new rpm in Mariner container
> Upgrade snappy to v1.1.9, telegraf to 1.21.2

- SPECS/python-py/python-py.spec
---
Remove `%file` section for the main package in `python-py`. I missed this when mass-deleting python2 packages last year. 
Since python2 isn't a requirement of `python-py`, `%python2_sitelib` evaluates to an empty string within the spec. This causes the main package to capture everything under the buildroot, resulting in the python3 subpackage being double packaged within the main package.
- Remove `%file` section for the main package in `python-py`.
**NO**
> [main] [core] Fix double packaging of python3-py

- SPECS/python-pytest-cov/0001-skip-tests-that-are-expected-to-fail.patch
- SPECS/python-pytest-cov/python-pytest-cov.signatures.json
- SPECS/python-pytest-cov/python-pytest-cov.spec
- cgmanifest.json
---
Bump version and fix ptest build. All tests pass!
- Bump version 2.10.1 -> 2.12.1
- Introduce patch to skip known test failures and cleanup up `%check` section
- Use `tox` instead of `pytest` to enable ptest
**NO**
- NA
- NA
Fun Fact: This is one of them notorious packages that sabotaged our ptest pipeline. Not anymore!
> python-pytest-cov: bump version to 2.12.1 & use `tox` to enable ptest

- SPECS/libserf/libserf-python3.patch
- SPECS/libserf/libserf.spec
- SPECS/scons/scons.spec
---
Remove `python2` from `scons` and `libserf` as part of our `python2` eradication effort
- `scons`: Build with python3 instead of python2
- `libserf`: Add Fedora patch to fix build with python3 version of `scons`
**NO**
- Local mock builds of `scons` and `libserf`
> [main] [core] Remove python2 from scons, libserf

- SPECS/OpenIPMI/OpenIPMI-py39.patch
- SPECS/OpenIPMI/OpenIPMI.spec
- SPECS/subversion/subversion.spec
---
Remove `python2` from `subversion` and `OpenIPMI` as part of our `python2` eradication effort.
- `subversion`: Run tests using `python3` instead of `python2`
- `OpenIPMI`: Use `python3` instead of `python2` in the python subpackage. Add Fedora 28 patch to enable build with python >= 3.9
**NO**
> [main] [core] Remove python2 from subversion, OpenIPMI packages

- SPECS/ceph/ceph-snappy-fix
- SPECS/ceph/ceph.spec
---
Add upstream patch to `ceph` to fix build break with `snappy` >= 1.1.9 (upgraded in #2206)
- Add upstream patch to `ceph` to fix build break with `snappy` >= 1.1.9
**NO**
- Successful pipeline build
> [main] [core] Fix ceph build with snappy >= 1.1.9

- toolkit/tools/internal/network/network.go
---
This PR resolves a bug where the golang HTTP transport code wasn't inheriting the default values which include respecting any http_proxy ENV values.  Thus running `srpmpacker` behind a proxy'd network would timeout prior to this change.
**NO**
- Checkout 1.0-stable branch and do a local build as follows.  
make clean
make toolchain -j$(nproc) CONFIG_FILE=./imageconfigs/core-legacy.json PACKAGE_IGNORE_LIST="openjdk8"
make image -j$(nproc) CONFIG_FILE=./imageconfigs/core-legacy.json REBUILD_TOOLS=y PACKAGE_IGNORE_LIST="openjdk8"
- The failure case is on a network which requires ENV values set for http_proxy, https_proxy and ftp_proxy.  Set those values and try to do a build.  With …
> golang inherit ENV proxy settings

- toolkit/tools/internal/network/network.go
---
This PR resolves a bug where the golang HTTP transport code wasn't inheriting the default values which include respecting any http_proxy ENV values.  Thus running `srpmpacker` behind a proxy'd network would timeout prior to this change.
Related to : 
- #2284
**NO**
- Checkout main branch and do a local build as follows.  
make clean
make toolchain -j$(nproc) CONFIG_FILE=./imageconfigs/core-legacy.json PACKAGE_IGNORE_LIST="openjdk8"
make image -j$(nproc) CONFIG_FILE=./imageconfigs/core-legacy.json REBUILD_TOOLS=y PACKAGE_IGNORE_LIST="openjdk8"
- The failure case is on a network which requires ENV values set for http_proxy, https_proxy and ftp_proxy.  Set those values and try to do …
> golang: inherit proxy settings

- SPECS/cloud-init/apply-netconfig-every-boot.patch
- SPECS/cloud-init/cloud-init.spec
- SPECS/cloud-init/update-metadata-on-BOOT_NEW_INSTANCE.patch
---
Cloud-init 21.3 has some compatibility issues with pre-provisioned VMs in Azure, leading to a long poll on IMDS that fails and a VM that doesn't have the correct networking configuration. The two patches included in this commit address the issue.
- cherry-pick e69a8874: Set Azure to only update metadata on BOOT_NEW_INSTANCE
- cherry-pick dc227869: Set Azure to apply networking config every BOOT
**NO**
- %check section passed without issue
- Marketplace image initialized successfully in Azure.
> [1.0] Add cloud-init patches to support preprovisioned VMs

- SPECS/bcc/bcc.signatures.json
- SPECS/bcc/bcc.spec
- SPECS/bpftrace/bpftrace.spec
- SPECS/clang/clang.spec
- SPECS/llvm/llvm.spec
- cgmanifest.json
---
- bcc: Update to 0.24.0
Includes 5.15+ kernel support
- bpftrace: Disable building bpftrace shared libs
Issues reported installing the bpftrace package.
```
Last metadata expiration check: 0:29:49 ago on Wed Feb  9 21:21:25 2022.
Error:
Problem: conflicting requests
- nothing provides libast.so()(64bit) needed by bpftrace-0.13.0-1.cm2.x86_64
- nothing provides libbpftrace.so()(64bit) needed by bpftrace-0.13.0-1.cm2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
We are not packaging the shared libraries produced by bpftrace's cmake
build. During the packaging, rpmbuild is finding these shared libraries and
And in general, we prefer to just package bpftrace …
> Update bcc to 0.24.0 and fix two issues found with bpftrace and bcc

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
@slaymaker1907 raised an issue (#2297) that the format of the `VERSION_ID` value inside `os-release` is invalid - it should be surrounded with double quotes if it contains non-alphanumeric characters (see: [here](https://www.freedesktop.org/software/systemd/man/os-release.html)). This PR is addressing that issue.
- Surrounded `VERSION_ID` inside `os-release` with double quotes.
Yes.
- #2297
- None, minor change.
> [main] Adding quotes in `os-release`.

- .github/workflows/validate-cg-manifest.sh
- SPECS/core-packages/core-packages.spec
- toolkit/imageconfigs/core-efi-aarch64.json
- toolkit/imageconfigs/core-efi-rt.json
- toolkit/imageconfigs/core-efi.json
- toolkit/imageconfigs/core-fips.json
- toolkit/imageconfigs/core-legacy.json
- toolkit/imageconfigs/core-ova.json
- toolkit/imageconfigs/full-aarch64.json
- toolkit/imageconfigs/full-rt.json
- toolkit/imageconfigs/full.json
- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2.json
- toolkit/imageconfigs/packagelists/core-tools-packages.json
- toolkit/imageconfigs/read-only-root-efi.json
- toolkit/imageconfigs/swuvm.json
---
1. Updating Mariner Core base and container images by keeping dnf, wget and vim as optional packages.
2. SELinux-Policy and its dependencies are consuming approximately ~18 MB of disk footprint in Core images. For now keeping it as an optional package in Mariner Core images only and adding it to Mariner Core-Fips, Mariner Full and other images by default. We will work with SELinux feature team to get this feature footprint reduced to required minimal footprint and will include in Mariner Core images. 
3. Created core-tools-packages.json with dnf, vim and wget packages. Added core-tools-packages.json in Mariner Market place images, Core-fips, Core-rt, Full images etc.
4. Current …
> Update Mariner Core base image keeping dnf wget vim as optional packages

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
@slaymaker1907 raised an issue (#2297) that the format of the `VERSION_ID` value inside `os-release` is invalid - it should be surrounded with double quotes if it contains non-alphanumeric characters (see: [here](https://www.freedesktop.org/software/systemd/man/os-release.html)). This PR is addressing that issue.
This is a 1.0 port of #2316.
- Surrounded `VERSION_ID` inside `os-release` with double quotes.
Yes.
- #2297
- #2316
- None, minor change.
> Using quotes in `os-release`. (CP #2316)

- SPECS/openssl-pkcs11/openssl-pkcs11.spec
---
Fix build which run without `RUN_CHECK=y`.
- Move BR on `doxygen` out of the `%{with_check}` gate to enable build.
**NO**
- #2177
- NA
- Pipeline build id: Local Build `without` RUN_CHECK=y
> openssl-pkcs11: move BR on doxygen out of the `%{with_check}` gate to fix build

- SPECS/javapackages-tools/javapackages-tools.signatures.json
- SPECS/javapackages-tools/javapackages-tools.spec
- SPECS/javapackages-tools/remove-headless-from-java-requires.patch
- cgmanifest.json
---
The 6.0.0 version of `javapackages-tools` removes some RPM macro we rely on heavily in our builds. It might take a while before we get an update, which works with our other specs. Until then, I'm reverting #2318 to unblock our builds.
- Reverted `javapackages-tools` back to version 5.3.0.
No.
- #2318
> [main] Reverting `javapackages-tools` update (6.0.0 -> 5.3.0)

- SPECS/icu/icu.spec
- SPECS/krb5/krb5.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We have a growing need to use Mariner's packages in distroless containers and one of the frequently hit issues is that packages have a an implicit dependency on the shell either by having a `%(post|pre)` section or by containing scripts, which depend on an interpreted through the `#!` line. This PR removes shell dependencies from the `icu` and `krb5` packages. The assumption is that distroless images do not include a shell, so there's no expectation to be able to run any shell scripts and **non**-distroless images always have a shell (Bash) installed, so it's present anyway.
- Removed dependency on a shell from `icu` and `krb5`.
No.
> [main] Removing shell dependency from `icu` and `krb5` packages.

- SPECS/python3/fix-xml-tests-expat.patch
- SPECS/python3/python3.spec
---
A recent `expat` security fix broke some of the package tests for `python3` by enforcing XML standards more thoroughly. So, let's take an upstream patch to fix these tests.
- `python3`: Add patch to fix tests with expat >= 2.4.5
**NO**
- Full pipeline build, tests now pass
> [1.0-dev] python3: Add patch to fix XML tests with newer expat

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner 1.0 Release version for March 2022 Update
> Bump Mariner 1.0 Release version for March 2022 Update

- SPECS/shim/shim.spec
- toolkit/scripts/check_spec_guidelines.py
---
A small clean-up making sure all of our specs follow a uniform `Release` tag format.
- Removed exception for the `release_number` macro in defining the value for the `Release` tag.
No.
- Local check script run.
> [main] Tidying up `Release` tag restrictions.

- toolkit/tools/internal/buildpipeline/buildpipeline.go
---
toolkit only - use local /run folder in chroot instead of mounted tmpfs
- Change
- Change
- Change
**YES/NO**
- #xxxx
> toolkit only - use local /run folder in chroot instead of mounted tmpfs

- toolkit/scripts/toolchain/cgmanifest.json
- toolkit/scripts/toolchain/container/Dockerfile
- toolkit/scripts/toolchain/container/version-check-container.sh
---
The Mariner toolchain builds have previously been bootstrapped with an ubuntu 18.04 container, to compile the initial toolchain packages from scratch. This change switches to a recent Mariner 1.0 container image (1.0.20220226), which removes our dependency on another distribution for full toolchain builds. I've also seen slightly faster (~15-30min) toolchain builds on x64. This could be due to some newer utilities in the Mariner container (gcc 7.5.0 -> 9.1.0, binutils 2.30 -> 2.36.1, glibc 2.27 -> 2.28)
- Change toolchain Dockerfile to use mariner 1.0 container instead of ubuntu 18.04 container
**YES**
- Pipeline build id: 174151 …
> Bootstrap toolchain build with mariner container

- SPECS/libedit/libedit.signatures.json
- SPECS/libedit/libedit.spec
- cgmanifest.json
---
This change upgrades libedit to the latest version for Mariner 2.0
NO
> Upgrade libedit to 3.1.20210910

- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add audit-libs requirement to pam package. This should resolve a boot issue where the login prompt does not appear.
Should also resolve the following warning message from image builds:
imager.log
"Installing: systemd-250.3-1.cm2.x86_64"
"systemctl: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory"
"Installing: pam-1.5.1-3.cm2.x86_64"
- Change pam.spec to require audit-libs
**YES**
- Local package build, local VHD build.
> Fix boot issue with pam

- SPECS/audit/audit.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Fix circular dependency by modifying audit.spec to Recommend systemd instead of Require it.
Fixes:
INFO[0001] Running cycle resolution to fix any cycles in the dependency graph 
ERRO[0004] Unfixable circular dependency found: {pam-1.5.1-4.cm2-RUN<Meta>} --> {libpwquality-1.4.4-1.cm2-RUN<Meta>} --> {cryptsetup-2.4.3-1.cm2-RUN<Meta>} --> {cryptsetup-devel-2.4.3-1.cm2-RUN<Meta>} --> {systemd-rpm-macros-250.3-1.cm2-BUILD<Build>} --> {systemd-rpm-macros-250.3-1.cm2-RUN<Meta>} --> {systemd-250.3-1.cm2-RUN<Meta>} --> {audit-3.0.6-3.cm2-RUN<Meta>} --> {Meta(15018)} --> {pam-1.5.1-4.cm2-RUN<Meta>} error: cycle contains no pre-build SRPMs, …
> Fix circular dependency from audit

- SPECS/audit/audit.spec
- SPECS/bubblewrap/bubblewrap.spec
- SPECS/shadow-utils/shadow-utils.spec
---
Fix build issues with audit and shadow-utils
Audit has unneeded runtime requirements that are forcing full package builds
ERRO[0028] Failed to clone 'glib-devel-2.71.0-1.cm2.x86_64' from RPM repo. Error: exit status 21 
WARN[0001] Could not create solvable subgraph, forcing full package build 
From: cached_graph.dot.log
Cloning: glib-devel-2.71.0-1.cm2.x86_64
1. nothing provides libcap-ng needed by audit-3.0.6-4.cm2.x86_64
Not updating release tags since the recent builds have been broken since the last changes to these packages.
- Change audit
- Change shadow-utils
**YES**
- Local build
> Fix build issue with audit and shadow-utils

- SPECS/python-nocasedict/python-nocasedict.signatures.json
- SPECS/python-nocasedict/python-nocasedict.spec
- cgmanifest.json
---
Upgrade `python-nocasedict` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream release
- Use tox as a test runner
- Lint spec
**NO**
> [main] python-nocasedict: Upgrade to 1.0.2

- SPECS/python-pycodestyle/python-pycodestyle.signatures.json
- SPECS/python-pycodestyle/python-pycodestyle.spec
- cgmanifest.json
---
Upgrade `python-pycodestyle` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream release
- Switch source from PyPI to GitHub
- Switch package test to use tox as a test runner
**NO**
> [main] python-pycodestyle: Upgrade to 2.8.0

- SPECS/polkit/polkit.spec
---
Update polkit to build with gtk-doc
Recent autoconf upgrade added gtk-doc dependency, which triggered polkit to build manpages (even though they haven't been included before).
Fix for error:
time="2022-03-17T22:46:42Z" level=debug msg="    Installed (but unpackaged) file(s) found:"
time="2022-03-17T22:46:42Z" level=debug msg="   /usr/share/man/man1/pkaction.1.gz"
time="2022-03-17T22:46:42Z" level=debug msg="   /usr/share/man/man1/pkcheck.1.gz"
time="2022-03-17T22:46:42Z" level=debug msg="   /usr/share/man/man1/pkexec.1.gz"
time="2022-03-17T22:46:42Z" level=debug msg="   /usr/share/man/man1/pkttyagent.1.gz" …
> Update polkit to disable man-pages

- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The only purpose of having `alsa-lib` built as part of the toolchain was to enable `openjdk8` to build in the toolchain. Since we no longer build `openjdk8` at all, we can safely remove `alsa-lib` from the toolchain. This work contributes to our ongoing toolchain minimization efforts.
Also, this PR fixes one line of the toolchain build script that should be a comment.
- Remove `alsa-lib` from the toolchain build script, the toolchain manifests, and the manifest update script.
**YES**
- Pipeline build id: 175675
> [main] toolchain: Remove alsa-lib

- SPECS/libtiff/CVE-2022-0561.patch
- SPECS/libtiff/CVE-2022-0562.patch
- SPECS/libtiff/CVE-2022-0891.patch
- SPECS/libtiff/libtiff.spec
---
Address CVE-2022-0561, CVE-2022-0562 & CVE-2022-0891
- Backport patches from upstream to fix CVE-2022-0561 & CVE-2022-0562
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-0561
- https://nvd.nist.gov/vuln/detail/CVE-2022-0562
- https://nvd.nist.gov/vuln/detail/CVE-2022-0891
> libtiff: backport patches from upstream to fix CVE-2022-0561 & CVE-2022-0562

- SPECS/cppunit/cppunit.signatures.json
- SPECS/cppunit/cppunit.spec
- cgmanifest.json
---
Update cppunit to v1.15.1
- Update cppunit to v1.15.1
- test in softhsm were failing because of old version of cppunit
NO
- Local build. Confirmed that the check section in softhsm passes with the new version of cppunit.
> Update cppunit to v1.15.1

- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Resolve boot issue seen with ISO installer. Systemd needs to have audit-libs installed at runtime. This change ensure that, since systemd requires pam, and pam now requires audit-libs.
Error seen during ISO build was: 
"WARN[0014] systemctl: error while loading shared libraries: libaudit.so.1: cannot open shared object file: No such file or directory"
- Change pam to require audit-libs
**NO**
- Local package build, local ISO build, booted the ISO to installer screen
> Modify pam to require audit-libs

- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Resolve boot issue seen with ISO installer. Systemd needs to have audit-libs installed at runtime. This change ensure that, since systemd requires pam, and pam now requires audit-libs.
Error seen during ISO build was: 
"WARN[0014] systemctl: error while loading shared libraries: libaudit.so.1: cannot open shared object file: No such file or directory"
- Change pam to require audit-libs
**NO**
- Local package build, local ISO build, booted the ISO to installer screen
> [2.0] Modify pam to require audit-libs

- SPECS/audit/audit.spec
- SPECS/blobfuse/blobfuse.spec
- SPECS/cni/cni.spec
- SPECS/coredns/coredns-1.7.0.spec
- SPECS/coredns/coredns-1.8.0.spec
- SPECS/coredns/coredns-1.8.4.spec
- SPECS/cri-tools/cri-tools.spec
- SPECS/etcd/etcd-3.4.13.spec
- SPECS/etcd/etcd-3.5.0.spec
- SPECS/flannel/flannel.spec
- SPECS/glide/glide.spec
- SPECS/go-md2man/go-md2man.spec
- SPECS/gobject-introspection/gobject-introspection.spec
- SPECS/golang/golang-1.16.signatures.json
- SPECS/golang/golang-1.16.spec
- SPECS/helm/helm.spec
- SPECS/moby-buildx/moby-buildx.spec
- SPECS/moby-cli/moby-cli.spec
- SPECS/moby-containerd/moby-containerd.spec
- SPECS/moby-engine/moby-engine.spec
- SPECS/moby-runc/moby-runc.spec
- SPECS/node-problem-detector/node-problem-detector.spec
- SPECS/nvidia-container-runtime/nvidia-container-runtime.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump version to 1.16.15 to address CVE-2022-24921
- Bump version to 1.16.15 to address CVE-2022-24921
- Bump version of dependent packages to force rebuild with go1.16.15
**YES**
- #2471
-  #2507 
[on hold as it needs to enable `CGO` which is disabled as of now]
- https://nvd.nist.gov/vuln/detail/CVE-2022-24921
- Pipeline build id: ~~In progress~~ 176925
> golang: bump version to 1.16.15 to address CVE-2022-24921

- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Change compression algorithm in systemd from zstd to lz4 for coredumps and journal logs. We already specified lz4 (-Dlz4=true), but since zstd is present in the build chroot environment, this is picked by default by systemd. Explicitly turn off zstd (with -Dzstd=false) to ensure that lz4 is used.
Note that in CBL-Mariner 1.0, systemd used lz4.
This will be a breaking change for CBL-Mariner 2.0 preview images that have previously used zstd compression (systemd coredumps and logs compressed with zstd will not be readable with the lz4-enabled systemd). journalctl calls will show something like: "Journal file …
> Use lz4 compression in systemd instead of zstd

- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/update_manifests.sh
---
Modify update_manifests.sh script to insert the libmetalink RPM into the pkggen_core files at the correct spot. This package was just added in #1751 and was noticed after merge.
Also modify the libmetalink order in pkggen_core_aarch64.txt to match the position from pkggen_core_x86_64.txt to keep the installation order consistent (after mpfr and before libmpc)
- Change update_manifests.sh script to insert libmetalink package
- Change pkggen_core_aarch64.txt to list libmetalink at same position as in x64 file
**YES**
> Fix libmetalink manifest issues

- toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
Fix the URL for a patch file used in the toolchain build, which has moved to a new directory on linuxfromscratch.org.
Resolves error in toolchain build:
https://www.linuxfromscratch.org/patches/blfs/svn/lua-5.4.3-shared_library-1.patch:
2022-03-23 23:40:20 ERROR 404: Not Found.
...
lua-5.4.3-shared_library-1.patch: FAILED open or read
sha256sum: lua-5.4.3-shared_library-1.patch: No such file or directory
- Change URL in toolchain-remote-wget-list
**YES**
- sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y 2>&1 | tee toolchain_build.log
> Fix URL for toolchain patch lua-5.4.3-shared_library-1.patch

- SPECS/cloud-init/azureds-set-ovf_is_accesible.patch
- SPECS/cloud-init/cloud-init.spec
---
Backporting fix ovf_is_accessible in DataSourceAzure.py.
Source Commit: https://github.com/canonical/cloud-init/commit/4496ad036505d0fbef80c8bf45a5e7ff8adea1e7 
Previously the code only considered ovf being accessible if iso could be
mounted, it missed the case where ovf was available in /var/lib/waagent.
For more context on the fix, contact Christopher Patterson/Anh Vo.
Ported cloud-init ovf_is_accessible DataSourceAzure.py fix.
**NO**
- Local build
> Port cloud-init ovf_is_accessible DataSourceAzure.py fix

- SPECS/powershell/powershell.signatures.json
- SPECS/powershell/powershell.spec
- cgmanifest.json
---
Update powershell to 7.2.2 to resolve CVE-2020-8927
- Update powershell to 7.2.2 to resolve CVE-2020-8927
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-8927
- Local build
> Update powershell to 7.2.2 to resolve CVE-2020-8927

- SPECS/ruby/ruby.spec
---
Build rubygems with ruby to fix build error in pipeline
- Build rubygem, openssl, io-console, json, psych rubygems
- Fixes error in pipeline build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=177953&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=266a177c-c74b-572c-2e05-3a6c5cd5b38a&l=10879
NO
- Local build
> Build rubygems with ruby to fix build error in pipeline

- SPECS/shadow-utils/shadow-utils.spec
---
https://microsoft.visualstudio.com/OS/_workitems/edit/37811423
Added a missing requires, `libpwquality`.  Without this requires, chpasswd fails to locate the pam_chauthtok() module needed by system-auth. 
- Add requires `libpwquality`
**NO**
> [main] shadow-utils: Add requires `libpwquality`

- SPECS/cloud-init/cloud-init.spec
- SPECS/cloud-init/mariner-22.1.patch
- toolkit/imageconfigs/packagelists/azurevm-packages.json
---
The default network config renderer in cloud-init for Mariner is currently systemd-networkd. This renderer is experimental in cloud-init and has some known shortcomings. This commit adds in some configs to the Mariner distro patch for cloud-init to support the use of netplan, and adds netplan into the marketplace image so that cloud-init will select it for network config rendering.
This is currently the behavior in 1.0, this commit brings the behavior over to 2.0.
- Add netplan defaults to cloud-init Mariner distro patch
- Add netplan package to the marketplace image so cloud-init uses it for network config rendering.
**NO**
- Local toolchain/package/image build
- Booted gen1 …
> [main] Add netplan support to cloud-init

- SPECS/ruby/ruby.spec
---
Our `ruby.spec` had incorrect version info about its `Provides` and the recent change to build all Ruby gems from sources (#2509) introduced duplicate `Provides` for the same capability without removing them from their previous source - the default `ruby` RPM. The combination of these two factors started causing build issues for the extended specs.
This change removes all duplicates and assigns correct versions to the provided capabilities.
- Removed duplicate `Provides` inside `ruby.spec`.
- Assigned correct version to the `Provides`.
No.
- #2509 
> [main] Adjusting `ruby` provides across subpackages.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
Recent update of TDNF made it display a few more yes/no questions, which caused failures for derivative builds reaching out to the PMC repository (no issues in core builds, since they relied on local packages). This is a temporary fix to unblock a preview release. Proper fix in #2640.
- Added `--assumeyes` to all TDNF calls.
No.
- #2640
- Local demo package and VHDX build.
> [main] Adding `--assumeyes` for TDNF calls.

- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
- SPECS/SymCrypt/SymCrypt.signatures.json
- SPECS/SymCrypt/SymCrypt.spec
- cgmanifest.json
---
Brings in the latest changes to SymCrypt and SCOSSL which include changes required for FIPS certification, and a fix for the build on aarch64.
- Update SymCrypt SPEC to consume v101.2.0, which includes changes required for FIPS certification, and a fix for building on Mariner aarch64. Remove ExclusiveArch: x86_64
- Update SymCrypt-OpenSSL SPEC to consume v1.1.0 which include changes required for FIPS certification (invokes SymCrypt with flags to run required self-tests). Remove ExclusiveArch: x86_64, as SymCrypt dependency should now build for aarch64.
**NO**
- Local build
> Update Mariner SPEC files with latest SymCrypt and SCOSSL source

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
See: #2641.
- See: #2641.
No.
- #2640
- #2641
- Local demo package and VHDX builds.
> [2.0] Adding `--assumeyes` for TDNF calls. (CP of #2640) (#2641)

- SPECS/prometheus-node-exporter/prometheus-node-exporter.spec
---
By specifying the name of a directory to build, the spec file was instructing go build to create an archive file, not an executable. Using a plain go build command makes it build an executable as intended.
- See above.
- Also added a sense test under %check that the output file can be run.
No
- OS Bug 38396447
I installed my locally-built RPM on a Mariner VM. prometheus-node-exporter is now an executable file, which is an improvement already:
```
centos@ci1382011-mt5-s-sde-2 [ ~ ]$ file $(which node_exporter)
/usr/bin/node_exporter: symbolic link to prometheus-node-exporter
centos@ci1382011-mt5-s-sde-2 [ ~ ]$ file $(which prometheus-node-exporter) …
```
> Make prometheus-node-exporter executable

- SPECS/dnf-plugins-core/dnf-plugins-core.spec
---
#2630 caused a build break due to a change to the cmake call in `dnf-plugins-core`. The change caused cmake to be given `python3` instead of the desired file path `/usr/bin/python3`. This caused the build of `dnf-plugins-core` to fail, since the cmake script expects either a major version number or a file path. 
This PR changes the cmake call to use the full `python3` binary file path.\
Cherry-pick of #2658.
- `dnf-plugins-core`: Pass cmake the file path of our `python3` binary to fix build
- `dnf-plugins-core`: no changelog entry/release bump, since this release has not been published
**NO**
- N/A
> dnf-plugins-core: Fix bad python path in cmake call

- SPECS/net-tools/net-tools.spec
---
https://microsoft.visualstudio.com/OS/_workitems/edit/38217259/
During testing, it appeared that the ifconfig executable was not being recognized in its new location `/bin` during the net-tools update to 2.10 (#2262). Therefore, a mv command was added to move it back to its original location of `/sbin`. 
After further investigation, the reason for this behavior was due to the fact that bash sessions cache the paths to executables. Therefore, if a user had run the `ifconfig` command, performed a net-tools package update, and tried to run `ifconfig` command again all in one session, an error would occur that the binary could not be found.  However if they ran `hash -d ifconfig`, …
> net-tools: Remove mv command

- SPECS/ocaml-cmdliner/ocaml-cmdliner.spec
- SPECS/ocaml-result/ocaml-result.spec
---
**NOTE**: the packages haven't built since the last update due to the macro issues, thus not updating the `Release` tag.
Fixing a post-linting issue with `%global` vs `%define`. It looks like `%global` macros referencing spec tags defined **after** the macro will not expand the way I expected. Switching to `%define` seems to have fixed the problem.
Example from `ocaml-cmdliner.spec`: the `libname` macro defined with `%global` expands to the value of `%name` (`ocaml-cmdliner`), while using `%define` returns `cmdliner`, which was the expected value.
- Replaced `%global` with `%define` in 2 `ocaml*.spec` files.
No.
- Local spec parsing.
> [main] Fixing `ocaml*.spec` macros.

- toolkit/imageconfigs/packagelists/azurevm-packages.json
---
Our `azurevm` package list contains `python-xml`, which was removed in #2604. This package was listed due to our 1.0 image requiring Python 2 XML libraries for the purpose of running Azure VM extensions. In this PR, we change the requirement from `python-xml` to `python3`, since (a) the extensions install just fine with Python 3, (b) we folded Python 3's XML libraries into the `python3-libs` package for 2.0, and (c) the extension actually requires `/usr/bin/python3` (which is in the `python3` package, which depends on `python3-libs`).
- `azurevm-packagelist.json`: Change `python-xml` requirement to `python3`
**NO**
- Local build of image
> Update python requirement in azurevm packagelist for 2.0

- SPECS/ocaml-fileutils/ocaml-fileutils.signatures.json
- SPECS/ocaml-fileutils/ocaml-fileutils.spec
---
During migration of `ocaml-fileutils` I had to update the source URL, since the previous one was no longer available. The new GitHub source is missing a few build config files and has a different signature but the same version, so we ended up with a file name conflict in our blob storage. Initially, I was hoping to replace the old source with the new one once the old one was no longer used, but it seems to have caused more issues, so for now I'm re-naming the new source by adding a suffix, which can be removed during the next version update. The re-named source is already uploaded.
- Re-named new source tarball for `ocaml-fileutils`.
No.
> [main] Adding a workaround for the source name conflict in `ocaml-fileutils`.

- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We've recently encountered a few issues with TDNF choosing `systemd-bootstrap-devel` over `systemd-devel`. While ideally, we should drop bootstrap versions of packages from PMC, we're making sure `systemd` now obsoletes all possible `systemd-bootstrap` packages until a better fix can be implemented.
I don't know how to obsolete `systemd-bootstrap-debuginfo` since it's automatically generated. Help greatly appreciated. The risk of running into conflicts with this package is minimal, however.
- Added `Obsoletes` inside `systemd.spec` for all possible `systemd-bootstrap` packages.
Yes.
- Pipeline build id: 181782
> Adding missing `Obsoletes` to `systemd`.

- SPECS/zfs-fuse/zfs-fuse.spec
Fixing a build break for zfs-fuse.  ARM64 fails.  Changed to ExclusiveArch for x86_64
> Build Break: Fix zfs-fuse ARM64

- SPECS/libguestfs/libguestfs.spec
Resolve ARM64 build break.  Libguestfs builds without edk2-aarch64.  So this quick change just allows the build to complete.
> Fix ARM64 Build Break due to missing requires on edk2-aarch64

- SPECS/systemd/Add-ptp_hyperv-udev-rule.patch
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Best practice for setting system time as an Azure VM is to retrieve it from the Hyper-V ptp device.
However, there's a race condition where the accelerated networking NIC can enumerate a ptp0 before Hyper-V's ptp device, meaning chrony shouldn't directly depend on /dev/ptp0. In upstream systemd they've fixed this with a udev rule to symlink the correct device to /dev/ptp_hyperv every boot. Backporting this rule to Mariner 1.0 so we can take a dependency on that device.
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync
- Backport ptp_hyperv udev rule to Mariner 1.0
**YES**
- Local toolchain and package build.
- Booted image in Azure and locally. Observed …
> [1.0] Add ptp_hyperv udev rule to systemd

- SPECS-EXTENDED/jlex/jlex.spec
- SPECS-EXTENDED/servletapi5/servletapi5.spec
---
It looks like `servletapi5` started failing to build due to a missing RPM macro after recent core package updates. I've added a `BuildRequires`, which should resolve this issue.
**NOTE:** not fixing missing URL in `cgmanifest.json` - we're going to cover that wholesale through a separate set of changes.
- Added `BuildRequires: javapackages-tools` to fix missing RPM macros.
No.
> [main][SPECS-EXTENDED] Fixing `cassandra` dependencies.

- SPECS/ruby/ruby.spec
---
A customer pointed out that our build-environment-specific linker flags are poisoning the flags that `ruby` stores to build C extensions with. This was causing gems with C extensions to fail to install, since they couldn't link with the stored flags.
This problem is pretty much the same as #1824. The solution is also similar- use our extension flag macros to tell `ruby` to only store linker flags that are usable outside of our RPM build environment. 
- `ruby`: Tell ruby to only store linker flags that are valid outside of our RPM build environment.
**NO**
- Pipeline build, installed new `ruby` version in a container, created a minimal Ruby C extension and verified the generated …
> ruby: Do not store certain compiler flags for extension building

- SPECS/golang/golang-1.17.signatures.json
- SPECS/golang/golang-1.17.spec
- cgmanifest.json
---
Upgrade version to 1.17.8 to address CVE-2021-44716
- Bump version to 1.17.8
**NO**
- NA
> golang: bump version to 1.17.8 to address CVE-2021-44716

- SPECS-EXTENDED/rubygem-rspec/rubygem-rspec.spec
- SPECS/ruby/macros.rubygems
- SPECS/ruby/ruby.signatures.json
- SPECS/ruby/ruby.spec
---
Some `rubygem-*` specs rely on the `gemdir` macro, while we used the `gem_dir` version. Some of the specs defined their own version of `gemdir` (in value identical to our `gem_dir`) but the ones, that didn't ended up installing files under directories like `/%{gemdir}/specifications` (the macro didn't get expanded). Example:
```
root [ / ]# dnf -q repoquery -l rubygem-coderay
/%{gemdir}/specifications
/%{gemdir}/specifications/coderay-1.1.3.rc1.gemspec
(...)
```
This change adds the `gemdir` macro alongside `gem_dir` to fix the paths.
There's also a small fix for `rubygem-rspec`.
- Added an alternative version of the `gem_dir` macro to enable compatibility with some Ruby specs.
- …
> [main] Fixing Ruby packages builds.

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- SPECS/vsftpd/vsftpd.signatures.json
- SPECS/vsftpd/vsftpd.spec
- cgmanifest.json
---
Current version of postgresql has CVE-2021-23214 and CVE-2021-23222. Upgrading to 14.2 addresses both.
Current version of vsftpd has CVE-2021-3618. Upgrading to version 3.0.5 fixes it.
- Update postgresql to version 14.2
- Update vsftpd to version 3.0.5
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-23214
- https://nvd.nist.gov/vuln/detail/CVE-2021-23222
- https://nvd.nist.gov/vuln/detail/CVE-2021-3618
- Individual containerized package builds for postgresql and vsftpd.
- Full local package build
> Update postgresql and vsftpd for CVE-2021-23214, CVE-2021-23222, CVE-2021-3618

- SPECS/systemd/fix-journald-audit-logging.patch
- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Systemd-journal was failing an assertion when logging especially long audit messages to the journal, causing systemd-journal to repeatedly crash. This is due to a bug in process_audit_string(), which fails to account for the meta fields in audit messages. The issue is fixed upstream here https://github.com/systemd/systemd/commit/df4ec48f45f518b6926e02ef4d77c8ed1a8b4e2c
- Backport of commit https://github.com/systemd/systemd/commit/df4ec48f45f518b6926e02ef4d77c8ed1a8b4e2c as patch fix-journald-audit-logging.patch
YES
- https://microsoft.visualstudio.com/OS/_workitems/edit/38575138
- Local build, upgraded VM with newly built systemd-* rpms, reboot, verify that the bug is no longer …
> [main] [bug] Address Constant Journald crash on Mariner 2.0 

- toolkit/scripts/toolchain.mk
---
Revert a change from #2628 which caused all toolchain RPMs to be extracted at the end of the build process. This added 1hour to X64 builds and 2.5 hours to ARM64 builds.
Also fix minor typo issues, and print a log message when the toolchain manifest verification step is complete.
- Revert toolchain_rpms target change in toolchain.mk
- Fix typos in toolchain.mk
- Print log message when toolchain manifest verification completes
**YES**
- Pipeline build id: 184806
> Reduce toolchain build time by reverting toolchain.mk modification

- toolkit/tools/depsearch/depsearch.go
- toolkit/tools/scheduler/schedulerutils/buildlist.go
---
Add tools to help debug toolchain build conflicts (ie the scheduler thinking it needs to rebuild toolchain packages, which it shouldn't)
- Add a few features to the depsearch tool:
- `--tree` now outputs a simple tree view of the subgraph.
- `--rpm-filter`  will limit the results to just those that aren't inside the filter list
- `--rpm-filter-file` sets the filter for the above flag. Defaults to the x86_64 toolchain manifest if it can find it.
- `--print-duplicates` sets the tree mode to print all nodes. By default it won't print a node if its already printed it once (warning, this takes a LONG time to run and can use up all your memory for even medium sized graphs, use with …
> Add toolchain debug features to the depsearch tool

- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/toolchain.mk
---
We were not updating some timestamps when working with the toolchain RPMs. This would result in re-scanning the toolchain RPMs, and regenerating the worker chroot unnecessarily.
We were also not calling the safe unmount script for the SRPM packer chroot.
- Call `safeunmount.sh` on `$(BUILD_DIR)/SRPM_packaging` before removing it.
- `touch` `$(STATUS_FLAGS_DIR)/toolchain_verify.flag` when we are done validating the toolchain so we don't revalidate it every time we build
- `touch` the toolchain RPMs when they are "rebuilt" but not extracted fresh from the archive (ie existing file is newer than the contents of the archive). This will ensure that the extracted RPMs are always newer …
> Makefile fixes to reduce undesirable rebuild of files, clean up a chroot

- toolkit/scripts/pkggen.mk
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildlist.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
The package build scheduler will print a list of files that it re-built that conflict with the toolchain manifests. No RPMs listed in the toolchain manifests should rebuild. Building them is the sole responsibility of the toolchain scripts.
- Add `--reserved-file-list-file` which should be a list of *.rpm filenames. By default this is the toolchain manifest file for the current build.
- The build report at the end of the build will now include  `RPM Conflicts with toolchain` and `SRPM Conflicts with toolchain` sections if any such conflicts exist.
**NO**
> Print conflicting toolchain files

- toolkit/scripts/pkggen.mk
- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
- toolkit/tools/internal/packagerepo/repocloner/repocloner.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/packagerepo/repoutils/repoutils.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
The scheduler will now accept capabilities from pre-built nodes (specifically toochain packges) as being available from the beginning. Previously they would be handled as if they were remote cached nodes, and would be left until all possible local nodes had been rebuilt before being used.
Now when the package fetcher translates a capability into a package that is part of the toolchain it will add a "prebult" node for it rather than a "cached" node.
- `go-graphpkgfetcher` now takes the toolchain manifest as an input
- Any capability/dynamic package that is translated to a package in the manifest will result in a `prebuilt` node rather than a cached node.
- Prebuilt nodes can be …
> Add scheduler support for prebuilt toolchain packages

- toolkit/tools/graphPreprocessor/graphPreprocessor.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
---
Adds the ability to prioritize certain build nodes in the graph. This means pre-built nodes can be scanned immediately, possibly unblocking other sections of the graph. This will also set the stage for future work on optimizing the order we process the graph.
- Add a `PriorityRequest` queue to the package workers.
- Workers will check for jobs in that queue before checking the other queues. Added a `Done` channel to signal a graceful exit should be made.
**NO**
> Add priority queue to scheduler

- .github/workflows/check-clean-stage.yml
- .github/workflows/check-package-cgmanifest.yml
- .github/workflows/check-spec.yml
- .github/workflows/lint-specs.yml
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/rpm/rpm_test.go
- toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec
- toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
One of our extended packages failed to be correctly recognized as not buildable for ARM64 because it was using the `ExcludeArch` tag. So far, we were only supporting the `ExclusiveArch` tag when determining if a package should be queued for building and so that one package made it through our initial check and then failed during the build phase. This PR extends this initial check to also take into account the `ExcludeArch` tag.
- Added support for the `ExcludeArch` tag.
- Modified our specs GitHub check to only look at specs inside the `SPECS*` directories and not the test ones.
No.
- Local Go tests run.
> [main] Adding support for the `ExcludeArch` spec tag.

- SPECS/xerces-c/CVE-2018-1311.patch
- SPECS/xerces-c/xerces-c.spec
---
This patch removes the Janitor responsible for the use after free in CVE-2018-1311.
This introduces a slight memory leak, but there is no upstream fix, so this is an acceptable tradeoff
for the security given that xerces-c is not commonly used and the package is removed in Mariner 2.0.
Patch adapted from the RH fix as noted in the upstream jira bug for the issue.
https://issues.apache.org/jira/browse/XERCESC-2188
- Patch CVE-2018-1311 in xerces-c
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2018-1311
- Full local package build
> [1.0] Patch xerces-c CVE-2018-1311

- SPECS/pycairo/pycairo.signatures.json
- SPECS/pycairo/pycairo.spec
- cgmanifest.json
---
Upgrade `pycairo` to the latest upstream version as part of our 2.0 package upgrade efforts.
- Switch python3-pytest BR to check-time 
- Lint spec
**NO**
> pycairo: Upgrade to 1.21.0

- SPECS/firewalld/firewalld.spec
---
`firewalld` currently fails to install on a system with `selinux-policy` installed, due to a `Conflicts: selinux-policy` line inherited from the Fedora spec. This conflict doesn't make any sense for Mariner, so let's remove it. Let's also remove a spattering of `Obsoletes` lines in the spec, for packages that haven't been shipped by Mariner.
- `firewalld`: Drop package obsoletes/conflicts that don't apply to Mariner
**NO**
- Local build passes
- Was able to install `selinux-policy` and the full suite of `firewalld` packages at the same time in a Mariner 2.0 container after this change
> firewalld: Drop package obsoletes/conflicts that don't apply to Mariner

- toolkit/docs/building/building.md
- toolkit/docs/formats/imageconfig.md
- toolkit/imageconfigs/core-legacy-unattended-hyperv.json
---
Our building doc says using core-legacy.json to build unattended ISO, which is incorrect. core-legacy.json and all other imageconfig jsons in Mariner do not set the TargetDisk entry and thus makes the installer believe this is an offline installation and eventually runs into failure when doing mounting. Adding a core-legacy-unattended-hyperv.json to Mariner so that users can use this as an example to build an unattended ISO that's able to work and updating the build and imageconfig doc.
- Update building.md
- Update imageconfig.md
- Add core-legacy-unattended-hyperv.json
NO
- #xxxx
- …
> [main] Update Unattended ISO Build Instruction

- SPECS/shadow-utils/shadow-utils.spec
---
change /etc/shadow permission to 000 
- After the /etc/shadow folder is created by pwconv command. We immediately change its permission to 000 
NO
- [Bug 38190102](https://microsoft.visualstudio.com/OS/_workitems/edit/38190102)
- Local package and image build
- Install the build image, verify that the /etc/shadow folder has changed permission to 000
- Verify that shadow folder has dependency on shadow-utils rpm package by running: dnf provides /etc/shadow
> change /etc/shadow permission to 000 

- SPECS/lvm2/lvm2.spec
---
Co-installation of `lvm2` and `lvm2-dbusd` packages currently fails due to duplicate files between the two packages. We only need the duplicate files to be installed in the `dbusd` subpackage, so let's exclude them from the base package.
- `lvm2`: Exclude `dbusd` subpackage files from base package
- `lvm2`: Remove manual pkgconfig provides
**NO**
- Local build, manual check of lvm package contents
> lvm2: Fix double-packaging of dbusd files

- toolkit/tools/scheduler/schedulerutils/printresults.go
---
The `scheduler` tools prints a build summary at the end of each build. As part of that summary, we print unresolved dependencies. Sometimes, an unresolved dependency may be a package name that is present during the build (either cached or built), but with version constraints that the available package does not fulfill.
We should make it more obvious to our toolkit consumers that version constraints are causing a dependency to be unresolved. To reduce confusion in such cases, let's print out the version constraints for unresolved dependencies.
Logging sample pre-change:
```
INFO[27562] Unresolved dependencies:                    
INFO[27562] --> pkgconfig(atk-bridge-2.0) …
```
> scheduler: Include version constraint info when printing unresolved dependencies

- SPECS/vim/vim.spec
---
Out of curiosity, I looked through our specs for the string `%{release}-%{version}`. I found one instance of this string in the `vim` package, in a provide for `vi`. Besides being factually incorrect, we could run into problems if we publish this package with a release number greater than the major version of `vim`. It will effectively leave and force us to introduce an epoch.
This PR changes the `vi` provide to use `%{version}-%{release}` as the EVR string.
- `vim`: Fix `vi` provide to have the proper EVR string 
**NO**
- Built correctly in pipeline build 187324
> vim: Fix vi provides with reversed EVR

- SPECS/cri-o/cri-o.spec
---
`cri-o` was imported from openSUSE and uses openSUSE's systemd macros. Mariner doesn't support those, so let's switch the macros to their equivalent in Mariner.
- `cri-o`: Replace openSUSE systemd macros with Mariner's
**NO**
- Local build passes, produced RPM has the correct scriptlets expanded
> cri-o: Replace openSUSE systemd macros with Mariner's

- SPECS/audit/audit.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The `audit` package was recently added to the toolchain in #2416.  The `audit` package uses `systemd` macros to handle service management. This was fine when `audit` was outside the toolchain, since `systemd-bootstrap-rpm-macros` is in the worker chroot and the `systemd` macros expand just fine at build-time. 
However, the raw toolchain does not have any `systemd` macros defined until `systemd-bootstrap` is built and installed into the raw toolchain chroot. So, specs in the toolchain built before `systemd-bootstrap` can't use `systemd` macros since they can't expand into a proper scriptlet at build-time. This causes scriptlet failures when upgrading the `audit` package.
So, let's …
> toolchain: Rebuild audit with systemd-bootstrap-rpm-macros installed

- toolkit/tools/imagegen/installutils/installutils.go
---
Add parameters to distroless manifest to extend those added in #2391 
The file "/var/lib/rpmmanifest/container-manifest-2" now contains the output of:
"rpm", "--dbpath", rpmDir, "-qa", "--qf", "%{NAME}\t%{VERSION}-%{RELEASE}\t%{INSTALLTIME}\t%{BUILDTIME}\t%{VENDOR}\t(none)\t%{SIZE}\t%{ARCH}\t%{EPOCHNUM}\t%{SOURCERPM}\n"
Field 6 contains a hard-coded value of "(none)" instead of "%{INSTPREFIXES}"
Sample output:
$ docker run -it --rm marinerdistroless:latest busybox cat /var/lib/rpmmanifest/container-manifest-2
mariner-release 2.0-11.cm2      1651010830      1650940870      Microsoft Corporation   (none)  580     noarch  0 …
> Add parameters to distroless manifest

- toolkit/docs/building/building.md
---
cloud-init provisioning is required for unattended installation. Include this information in the Mariner build doc
**NO**
> [main] Minor fix to build doc regarding unattended installation instruction

- toolkit/docs/building/building.md
- toolkit/imageconfigs/core-legacy-unattended-hyperv.json
---
Cherry-picking https://github.com/microsoft/CBL-Mariner/commit/34efd7a763286612925b292cd7741bf8eb6b1d01 and https://github.com/microsoft/CBL-Mariner/commit/c2da2d8c51724357ee05a583d1392347e0039a7f to resolve credscan failure in 2.0 caused by unattended installer image config json
NO
> [2.0] Cherry-pick credscan failure caused by unattended installer image config

- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
In the toolchain, after a failed build, the buildroot folders of failed RPMs are preserved in the LFS chroot. Preservation of the buildroot folders is great, since it allows us a bit more flexibility when debugging failures. However, the preserved buildroot folder is never actually removed. When the LFS chroot is re-used for another toolchain build (common when doing rebuilds during development), the contents of the preserved buildroot folder can cause build failures. These failures usually occur because the buildroot contains files that are not packaged by the new RPM build. To get around this, let's wipe the LFS chroot's buildroot folder before each build.
- toolchain: wipe the …
> toolchain: Remove raw toolchain chroot's old buildroots prior to RPM build

- SPECS-EXTENDED/rubygem-semantic_puppet/rubygem-semantic_puppet.spec
- SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec
---
These gems were missing lib files (.rb), that have now been copied from source.tar.gz
- Earlier, we were using .gem files to build rubygems, that would install lib files. Now, these files have to be copied from the source and added to files section. Without lib files, their functionality was impacted.
NO
- Installed the new rpm on a Mariner VM, could 'require' these gems in test programs successfully.
> Add lib files to rubygems from source

- toolkit/tools/internal/logger/log.go
---
StreamOutput was intended to preserve the last N lines of error. Instead it was preserving the first N lines instead.
Drop the oldest line of saved output if the buffer becomes full instead of dropping the new line.
- Check if the output buffer is full in StreamOutput and drop the oldest line if so
**NO**
- Quick local test
> Drop old lines from StreamOutput if full

- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
---
In #2953 util-linux-libs was created and installed in the default worker chroot (in pkggen_core) instead of util-linux-devel. The uuid.h and uuid.pc files, contained in util-linux-devel, are no longer present by default. Add this package back into pkggen_core.
Should fix the following package issues:
INFO[37332] Failed SRPMs: 
INFO[37332] --> parted-3.4-1.cm2.src.rpm , error: exit status 2, for details see: /tmp/mariner/build/logs/pkggen/rpmbuilding/parted-3.4-1.cm2.src.rpm.log 
"checking uuid/uuid.h presence... no"
INFO[37332] --> xfsprogs-5.0.0-3.cm2.src.rpm , error: exit status 2, for details see: …
> Add util-linux-devel into pkgggen_core

- toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
Cleanup unnecessary files found in toolchain_from_container.tar.gz intermediate toolchain file.
1) Fix typo when removing "procps-3.3.17" source build directory
2) Remove "/tools/libexec/gcc". This contains the bootstrapped gcc compiler used in the early part of the raw toolchain build. It is not needed for building the rest of the toolchain, and takes a large amount of space. Reducing the size will improve download/upload speed of artifacts in the full build pipelines.
Reduces compressed size of toolchain_from_container.tar.gz by around 600MB (from ~1.9GB to ~1.3 GB)
- Remove proper "procps-3.3.17" source folder
- Remove …
> Remove unnecessary files in toolchain_from_container.tar.gz

- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
`wget` was added to the toolchain in the pre-1.0 days as a build dependency of `openjdk` ([internal PR link](https://dev.azure.com/mariner-org/mariner/_git/mariner/pullrequest/694)). We no longer build `openjdk` in the toolchain and we have no other need for `wget` in the toolchain. So, let's remove `wget` from our toolchain to work towards our minimal toolchain goals.
- toolchain: Remove `wget`
**YES**
> toolchain: Remove wget

- toolkit/scripts/tools.mk
---
We embed the toolkit version in our Go tooling at link-time. This embedding requires the import path of the toolkit version variable to be fully specified to the linker. This import path became out-of-date after #2976.
This PR correct the path to the toolkit version variable to use the new base import path of `github.com/microsoft/CBL-Mariner/toolkit/tools`.
- `toolkit/scripts/tools.mk`: update import path of toolchain version variable in linker flags
**NO**
- Local tooling build. Quick validation by modifying one of the built executables to print the toolkit version string
> toolkit: Update toolkit version linker argument for new module path

- SPECS/freetype/CVE-2022-27404.patch
- SPECS/freetype/freetype.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
[1.0] freetype: patch CVE-2022-27404
- freetype: patch CVE-2022-27404
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-27404
> [1.0] freetype: patch CVE-2022-27404

- SPECS/nodejs/nodejs.spec
---
This PR removes python3 package from nodejs because it is only a build time dependency and not a runtime dependency. Removing python3 from nodejs reduces the package size.
- Removed python3 as a runtime dependency for nodejs
**NO**
none
none
- Pipeline build id: 194041, 194317, 194220
- Successfully built the nodejs package locally.
> Remove python3 as a runtime dep for nodejs

- SPECS/supermin/supermin.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/imggen.mk
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/tdnf/tdnf.go
- toolkit/tools/internal/tdnf/tdnf_test.go
- toolkit/tools/pkgworker/pkgworker.go
---
Remove the `mariner-release` package from the toolchain.
Bumping the `mariner-release` package release is mostly a symbolic move to denote that a new monthly release has occurred. However, since this package is in the toolchain, this version bump causes a full toolchain rebuild, which in turn forces us to do a full package rebuild. Removing `mariner-release` from the toolchain allows us the possibility of doing a delta build release some months instead of a full rebuild release.
The biggest issue is that `tdnf` uses the version of `mariner-release` to determine the value of the `$releasever` variable in our repo files. We can correct for this by overriding the release version …
> toolchain: Remove mariner-release package

- toolkit/imageconfigs/additionalconfigs/configure-image.sh
---
Remove 99-dhcp-en.network for marketplace img
- Remove dhcp config file that assigns IP to all ethernet ports (by matching with e*) (https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/systemd/99-dhcp-en.network) . Fixes bug in Azure VMs having accelerated networking enabled. We have netplan enabled which takes care of bringing up the correct network configuration in Azure VMs
- Removing contents rather than removing the file to ensure the file doesn't get reintroduced on systemd package updates
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/39528347
- Built a new image and verified that the file is deleted. On a separate VM with Accelerated Networking enabled, …
> Overwrite 99-dhcp-en.network for marketplace img

- SPECS/cpio/CVE-2021-38185.patch
- SPECS/cpio/cpio.spec
- toolkit/.gitignore
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/container/Dockerfile
- toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
cpio: address CVE-2021-38185
Apply upstream fix and associated fixes for additional regressions found
upstream.
For more context, see mail thread:
https://lists.gnu.org/archive/html/bug-cpio/2021-08/msg00000.html
This patch file was sourced from #1365
- Apply patch CVE-2021-38185 to cpio package
- Update toolchain scripts to build with patched cpio
- Update manifest files
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-38185
- Local build
- Pipeline build x86_64 (195028), ARM64 (195038)
> cpio: address CVE-2021-38185

- SPECS/cracklib/cracklib.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The `cracklib` package has a symlink from `/usr/sbin/packer` to `/usr/sbin/cracklib-packer`. The symlink conflicts with the HashiCorp's Packer utility. Specifically, some users will install `packer` as `/usr/bin/packer` and call the `packer` binary without a fully qualified path. Due to the ordering of our default `PATH`, users will end up calling `cracklib-packer` when they really intend to .
Normally I would say we shouldn't change our package because of this... but I can't find any historical reason for this symlink. Fedora actually ended up removing this symlink for the exact same reason we are.
So, let's just remove the symlink in this case. 
- Remove `/usr/sbin/packer` …
> cracklib: remove /usr/sbin/packer symlink due to conflict

- SPECS/dnf-plugins-core/Fix-wrong-boot-time-RhBug-1960437.patch
- SPECS/dnf-plugins-core/dnf-plugins-core.spec
---
dnf-plugins-core: Add patch to fix wrong boot time
Current needs-restarting relies on the stat mtime from /proc/1/cmdline
to determine when the system booted. However this value can update over
the lifetime of the VM for various reasons, causing needs-restarting to
think that a kernel/systemd package was installed before the system
rebooted, so it won't try to trigger a reboot when it is actually
required.
Backport upstream fix for this issue:
https://github.com/rpm-software-management/dnf-plugins-core/commit/ece8e77155919409d344d405ec4ed19d16a522aa
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/39382859
- Local build
> dnf-plugins-core: Add patch to fix wrong boot time

- SPECS/libxml2/libxml2.signatures.json
- SPECS/libxml2/libxml2.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update libxml2 to 2.9.14 to address CVE-2022-29824
Addresses CVE-2022-29824 for both libxml2 and libxslt
- Update libxml2 to 2.9.14 
YES
- https://nvd.nist.gov/vuln/detail/CVE-2022-29824
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=196776&view=results
> Update libxml2 to 2.9.14 to address CVE-2022-29824

- SPECS/unixODBC/unixODBC.spec
---
Require `glibc-iconv` for `unixODBC`.
Without `glibc-iconv`, `unixODBC` will produce the below error whenever you attempt to connect to SQL.
```
> isql -v -k "driver={ODBC Driver 17 for SQL Server};server=*.database.windows.net;database=*;authentication=ActiveDirectoryInteractive;"
('IM004', "[IM004] [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed (0) (SQLDriverConnect)")
```
https://github.com/mkleehammer/pyodbc/issues/738#issuecomment-825219716
- Require `glibc-iconv` for `unixODBC`
**NO**
- https://github.com/mkleehammer/pyodbc/issues/738
- Locally tested in container running in Docker using `isql` command and `pyodbc` Python package.
> Require glibc-iconv for unixODBC

- SPECS/mariadb/mariadb.signatures.json
- SPECS/mariadb/mariadb.spec
- cgmanifest.json
---
Upgrade to the latest release in `mariadb`'s 10.3 release series to fix 20 CVEs.
- `mariadb`: Version bump 10.3.34 -> 10.3.35
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-46669
- https://nvd.nist.gov/vuln/detail/CVE-2022-21427
- https://nvd.nist.gov/vuln/detail/CVE-2022-27376
- https://nvd.nist.gov/vuln/detail/CVE-2022-27377
- https://nvd.nist.gov/vuln/detail/CVE-2022-27378
- https://nvd.nist.gov/vuln/detail/CVE-2022-27379
- https://nvd.nist.gov/vuln/detail/CVE-2022-27379
- https://nvd.nist.gov/vuln/detail/CVE-2022-27380
- https://nvd.nist.gov/vuln/detail/CVE-2022-27381
- https://nvd.nist.gov/vuln/detail/CVE-2022-27383
- https://nvd.nist.gov/vuln/detail/CVE-2022-27384
- …
> mariadb: Upgrade to 10.3.35 to fix 20 CVEs

- SPECS/ruby/ruby.signatures.json
- SPECS/ruby/ruby.spec
- cgmanifest.json
---
Upgrade `ruby` to the latest release in the 2.6 branch to fix CVE-2022-28739.
- `ruby`: Version bump 2.6.9 -> 2.6.10
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-28739
- Internal buddy build 199189
> ruby: Upgrade to 2.6.10 to fix CVE-2022-28739

- SPECS/node-problem-detector/node-problem-detector.spec
---
`node-problem-detector` had a test regression after `mariner-release` was removed from the worker chroot. Adding it in as a check-time/run-time dependency to fix tests and ensure functionality.
- `node-problem-detector`: Add explicit check/run-time dependencies on mariner-release
**NO**
- Buddy build pipeline 199731
> node-problem-detector: Add explicit check/run-time dependencies on mariner-release

- SPECS/selinux-policy/0017-Add-cloud-init.patch
- SPECS/selinux-policy/0018-Add-compatibility-for-container-selinux.patch
- SPECS/selinux-policy/0019-systemd-Remove-systemd-run-domain.patch
- SPECS/selinux-policy/0020-unconfined-Add-missing-capability2-perms.patch
- SPECS/selinux-policy/0021-lvm-Updates-for-multipath-LVM.patch
- SPECS/selinux-policy/0022-locallogin-Use-init-file-descriptors.patch
- SPECS/selinux-policy/0023-systemd-Misc-fixes.patch
- SPECS/selinux-policy/0024-isns-Updates-from-testing.patch
- SPECS/selinux-policy/0025-container-docker-Fixes-for-containerd-and-kubernetes.patch
- SPECS/selinux-policy/0026-devices-Add-type-for-SAS-management-devices.patch
- SPECS/selinux-policy/0027-devices-Add-file-context-for-dev-vhost-vsock.patch
- SPECS/selinux-policy/0028-Add-dac_read_search-perms.patch
- SPECS/selinux-policy/0029-iptables-Ioctl-cgroup-dirs.patch
- SPECS/selinux-policy/0030-container-allow-containers-to-manipulate-own-fds.patch
- SPECS/selinux-policy/0031-devices-Add-type-for-infiniband-devices.patch
- SPECS/selinux-policy/0032-storage-Add-fc-for-dev-ng-n-devices.patch
- SPECS/selinux-policy/0033-files-Add-prerequisite-access-for-files_mounton_non_.patch
- SPECS/selinux-policy/0034-files-Make-etc_runtime_t-a-config-file.patch
- SPECS/selinux-policy/0035-systemd-Fixes-for-coredumps-in-containers.patch
- SPECS/selinux-policy/0036-container-Allow-container-engines-to-connect-to-http.patch
- SPECS/selinux-policy/0037-container-Getattr-generic-device-nodes.patch
- SPECS/selinux-policy/0038-application-Allow-apps-to-use-init-fds.patch
- SPECS/selinux-policy/selinux-policy.spec
---
Backporting:
[selinux-policy: Add additional patches from containers and kubernetes testing.
](https://github.com/microsoft/CBL-Mariner/pull/2937)
[selinux-policy: Fixes from baremetal testing](https://github.com/microsoft/CBL-Mariner/pull/3047)
SELinux policy
* Mon May 23 2022 Chris PeBenito <chpebeni@microsoft.com> - 2.20220106-6
- Fix previous multipath LVM changes.
- Add types for devices.
- Cherry pick upstream commit for container fds.
- Allow container engines to connect to http cache ports.
- Allow container engines to stat() generic (device_t) devices.
* Mon May 02 2022 Chris PeBenito <chpebeni@microsoft.com> - 2.20220106-5
- Additional compatibility for Fedora …
> selinux-policy: (backport) additional container/kubernetes patches + fixes from baremetal testing. 

- SPECS/ntfs-3g/ntfs-3g.signatures.json
- SPECS/ntfs-3g/ntfs-3g.spec
- cgmanifest.json
---
ntfs-3g: Updating to 2022.5.17 to fix CVE-2021-46790
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-46790
> ntfs-3g: Updating to 2022.5.17 to fix CVE-2021-46790

- SPECS/hyperv-daemons/hyperv-daemons.spec
- SPECS/hyperv-daemons/hypervkvpd.service
**No instances of Mariner 2 are currently emitting KVP telemetry for cloud-init.**
kvpd must start before cloud-init-local which comes before network.target.
1. Add ConditionVirtualization=microsoft to only start under Hyper-V.
2. Remove After=network.target dependency.
3. Add After=sys-devices-virtual-misc-vmbus\x21hv_kvp.device which
should be combined with BindTo=.
Signed-off-by: Chris Patterson <cpatterson@microsoft.com>
---
- Ensure hypervkvpd.service starts prior to cloud-init-local.service.
- Mariner 2 Azure image rebooted multiple times with changes
> hyperv-daemons/hypervkvpd.service: fix service ordering

- SPECS/ca-certificates/ca-certificates.spec
- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
- SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We made `ca-certificates-microsoft` and `ca-certificates-mozilla` an alias for `ca-certificates` but we missed doing a similar thing for `prebuilt-ca-certificates`. Fixing this here. A separate update for `1.0-dev` is already done (#3099).
- Add `Provides` for `%{name}-microsoft` and `%{name}-mozilla` to `prebuilt-ca-certificates`.
No.
- #3094 
- #3099
> [main] `prebuilt-ca-certificates`: adding `Provides` for `*-microsoft` and `*-mozilla`.

- SPECS-EXTENDED/edk2/edk2.spec
- SPECS/nasm/nasm.spec
- SPECS/ostree/ostree.spec
---
For ARM64 builds we've had 2 blocked packages: `buildah` and `edk2`. The former was blocked on `ostree`, which used to be built exclusively for AMD64 and this PR makes it build for ARM64 as well. The latter was blocked on `nasm` for the same reason but since [officially `nasm` doesn't support ARM64](https://github.com/netwide-assembler/nasm/pull/3), we've decided to disable building `edk2` on ARM64 for now.
- Removed `ExclusiveArch` from `ostree.spec`.
- Added `ExclusiveArch: x86_64` to `edk2.spec`.
No.
- Pipeline builds 199805 and 199870.
> ARM64 `buildah` and `edk2` blocked packages fix.

- SPECS-EXTENDED/php/php-7.4.14-gd.patch
- SPECS-EXTENDED/php/php.spec
---
Our version of `php` doesn't contain the fix to make it build with the 2.3.3 version of `gd` we've switched to recently (#3084). I've backported [a patch](https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-php-4175700816/#post6285319) for now, since a version update would require intrusive changes with potential to destabilize other packages.
- Added a patch to build with `gd` 2.3.3+.
- Linted `php.spec`.
No.
- #3084
> `php`: adding a patch to build with updated `gd`.

- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
---
Fixing 3 CVEs in `vim` by updating it to the latest version (8.2.5064).
- Updated `vim` to version 8.2.5064.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-1851
- https://nvd.nist.gov/vuln/detail/CVE-2022-1886
- https://nvd.nist.gov/vuln/detail/CVE-2022-1898
> `vim`: updating to version 8.2.5064 to fix CVE-2022-1851, CVE-2022-1886, and CVE-2022-1898.

- toolkit/tools/imagegen/installutils/installutils.go
---
This is a port to 1.0-dev from #2889
Add parameters to distroless manifest to extend those added in https://github.com/microsoft/CBL-Mariner/pull/2391
The file "/var/lib/rpmmanifest/container-manifest-2" now contains the output of:
"rpm", "--dbpath", rpmDir, "-qa", "--qf", "%{NAME}\t%{VERSION}-%{RELEASE}\t%{INSTALLTIME}\t%{BUILDTIME}\t%{VENDOR}\t(none)\t%{SIZE}\t%{ARCH}\t%{EPOCHNUM}\t%{SOURCERPM}\n"
Field 6 contains a hard-coded value of "(none)" instead of "%{INSTPREFIXES}"
- Change installutils.go to generate additional information in manifest
**NO**
> [1.0] Add parameters to distroless manifest

- SPECS/mariner-release/mariner-release.spec
Bumping Mariner release version in support of off-cycle CVE Fixes.
> Bump Mariner Release for Incremental CVE Fixes

- SPECS/clamav/clamav.spec
---
Various fixes to clamav
https://microsoft.visualstudio.com/OS/_queries/edit/39607373
ClamAV fixes:
- don't look in buildroot for config/data at runtime
- create clamav data dir and user/group so freshclam can download clamav db
- add default config for freshclam so it runs without error by default
No
local build:
```bash
root [ /src ]# freshclam
ClamAV update process started at Wed Jun  8 18:16:12 2022
daily database available for download (remote version: 26566)
Time:    5.8s, ETA:    0.0s [========================>]   56.03MiB/56.03MiB
Testing database: '/var/lib/clamav/tmp.e8bddd1b6f/clamav-0511a9c7e4b14c4c181af44406dcb3fc.tmp-daily.cvd' ...
Database test passed.
daily.cvd …
```
> Fix clamav

- SPECS-EXTENDED/ruby-augeas/ruby-augeas.spec
- cgmanifest.json
---
After recent extraction of built-in gems from `ruby` into separate packages `ruby-augeas` stopped building because it depends on `rubygem-rake` but it didn't mention that in the spec. Fixing this now.
- Added explicit `BuildRequires: rubygem(rake)` to `ruby-augeas.spec`.
No.
> `ruby-augeas`: fixing build by adding missing BR.

- SPECS/cloud-init/add-mariner-distro-support.patch
- SPECS/cloud-init/cloud-init.signatures.json
- SPECS/cloud-init/cloud-init.spec
- cgmanifest.json
Minor fixes to distro patch:
- formatting, etc. to comply with upstream linting
- add .py extension to tests/unittests/distros/test_mariner
- fixup broken imports for test_mariner module
Cloud-init 22.2 includes several fixes/improvements for Azure's
datasource, full changelog is here:
https://github.com/canonical/cloud-init/blob/22.2/ChangeLog
Signed-off-by: Chris Patterson <cpatterson@microsoft.com>
---
- Created image based off latest Azure image with latest RPMs and provisioned new instance.
> cloud-init: uprev to 22.2

- SPECS/cloud-init/cloud-init.spec
---
The cloud-init module [resizefs](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#resizefs) uses the program resize2fs to resize e.g. ext4 filesystems on Linux.
resize2fs is part of the e2fsprogs package, but cloud-init package does not depend on e2fsprogs, hence cloud-init may fail when using the resizefs module.
https://microsoft.visualstudio.com/OS/_workitems/edit/39587683
- Add missing e2fsprogs dependency to cloud-init
**NO**
- Local build
> add missing e2fsprogs dep to cloud-init

- SPECS/selinux-policy/0039-unconfined-Manage-own-fds.patch
- SPECS/selinux-policy/selinux-policy.spec
Fixes SELinux BVTs.
---
Allow unconfined domains to manipulate their own fds. Fixes SELinux BVTs.
-  Allow unconfined domains to manipulate their own fds.
**NO**
- Static analysis, local build.
> selinux-policy: Allow unconfined domains to manipulate their own fds.

- SPECS/zsh/fix-script-shebangs.patch
- SPECS/zsh/zsh.spec
---
`zsh` source ships with some scripts with `#!/usr/local/bin/zsh` shebang lines. That's not the proper location for the `zsh` binary- we put in it `%{_bindir}`. RPM sees these lines and generates a requirement on `/usr/local/bin/zsh` for the `zsh` package. Since this requirement isn't fulfillable by any package, install of `zsh` fails.
To fix this, we just patch out the faulty shebang lines and make them match up with what we ship.
- `zsh`: Fix package install by fixing shebang lines in included scripts
**NO**
- Buddy build 
- `rpm -qp --requires <path to newly built RPM>` does not include `/usr/local/bin/zsh`
- Newly built RPM is installable in container
> zsh: Fix package install by fixing shebang lines in included scripts

- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Package `filesystem` fails to upgrade in a container from versions `1.1-8` to `1.1-9`. The culprit is an interaction between rootless containers' population of `/proc` and `/sys`
Repro: `docker run --rm -it mcr.microsoft.com/cbl-mariner/base/core:2.0.20220426 tdnf --rpmverbosity info upgrade -y`
I've personally seen two different errors:
```
error: unpacking of archive failed on file /proc: cpio: chown failed - Directory not empty
error: filesystem-1.1-9.cm2.x86_64: install failed
```
```
...
Installing/Updating: filesystem-1.1-9.cm2.x86_64
error: unpacking of archive failed on file /sys: cpio: chmod failed - Device or resource busy
error: filesystem-1.1-9.cm2.x86_64: install …
```
> filesystem: Fix issues when upgrading in container

- SPECS/kpatch/kpatch.spec
Fix Build Break on ARM64.  Make kpatch have exclusive arch for x86_64
> Fix ARM64 Build Break

- SPECS-EXTENDED/t1lib/t1lib.spec
- SPECS-EXTENDED/t1lib/t1lib_5.1.2-3.patch
- cgmanifest.json
---
#3147 removed a patch file from `t1lib` due to it being a compressed file. This broke SRPM packing for `t1lib`. This PR returns the patch to its proper place, unpacked and renamed.
- `t1lib`: Fix SRPM packing issues with Patch0
**NO**
- Local SRPM pack
> t1lib: Fix SRPM packing

- SPECS-EXTENDED/dpkg/dpkg.signatures.json
- SPECS-EXTENDED/dpkg/dpkg.spec
- cgmanifest.json
---
Bump version to 1.20.10 to address CVE-2022-1664
- Bump version to 1.20.10 to address CVE-2022-1664
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-1664
> dpkg: bump version to 1.20.10 to address CVE-2022-1664

- SPECS/core-packages/core-packages.spec
---
Our `core-packages` spec should ideally be treated as a listing of end goal packages for our images- a sort of API saying which packages should be expected in every image. Unfortunately, we've strayed from that, and we've put packages in that list that are _requirements_ of our goal packages. So, when we change the requirements of a goal package, we can be left with extraneous packages in our `core-packages` list.
This happened with the `rpm` package. We ideally want `rpm` in every image, which makes it one of our goal packages. At some point, our `rpm` package required `nss-libs` and `nspr` as dependencies. With our upgrade to `rpm 4.17.X` in Mariner 2.0, these packages are no …
> core-packages: Remove nspr, nss-libs from base container image

- SPECS/mariadb-connector-c/mariadb-connector-c.spec
- cgmanifest.json
---
Resolve /etc/my.cnf conflict seen in full core package builds. mariadb-connector-c requries /etc/my.cnf, which is provided by mariadb-connector-c-config. Require this package explicitly instead of requiring the file "%{_sysconfdir}/my.cnf".
```
INFO[16450] Unresolved dependencies: 
INFO[16450] --> /etc/my.cnf:C:''V:'',C2:''V2:'' 
INFO[16450] Writing DOT graph to /tmp/mariner/build/pkg_artifacts/built_graph.dot 
FATA[16451] Unable to build package graph. 
file /etc/my.cnf conflicts between attempted installs of mariadb-server-10.6.7-1.cm2.x86_64 and mariadb-connector-c-config-3.1.10-4.cm2.noarch
ERRO[1593] Failed while trying to pick …
```
> Resolve /etc/my.cnf conflict

- SPECS-EXTENDED/libcdio/fix_format_security.patch
- SPECS-EXTENDED/libcdio/libcdio.spec
---
Add patch for libcdio to build with ncurses 6.3.
Resolves error:
```
"cdda-player.c: In function 'action':"
"cdda-player.c:296:28: error: format not a string literal and no format arguments [-Werror=format-security]"
"  296 |   mvprintw(LINE_ACTION, 0, psz_action_line);"
"      |                            ^~~~~~~~~~~~~~~"
"cdda-player.c: In function 'display_tracks':"
"cdda-player.c:1023:31: error: format not a string literal and no format arguments [-Werror=format-security]"
" 1023 |         mvprintw(i_line++, 0, line);"
"      |                               ^~~~"
"cdda-player.c:1026:31: error: format not a string literal and no …
```
> Add patch for libcdio to build with ncurses 6.3

- SPECS-EXTENDED/numatop/fix-format-security.patch
- SPECS-EXTENDED/numatop/numatop.spec
---
#3160 upgraded ncurses to version 6.3. This update changed some function attributes that are causing GCC to recognize more instances of -Werror=format-security in packages utilizing ncurses. So, we fix these errors in `numatop` by taking the relevant patches from upstream.
- `numatop`: Add patch to fix -Werror=format-security errors after ncurses 6.3 upgrade
**NO**
- Local build
> numatop: Fix format-security errors caused by ncurses-6.3 upgrade

- SPECS/libxslt/libxslt.spec
---
Nopatch CVE-2022-29824 in libxslt. The vulnerability has been fixed in libxml2 version 2.9.14, and libxslt loads it as a shared object instead of statically linking.
Verified against the repro instructions [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=2272). xsltproc segfaults with 2.9.13 libxml2 installed but succeeds with version 2.9.14. Signature of the segfault on 2.9.13 matches the project-zero repro.
- Nopatch CVE-2022-29824 in libxslt
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-29824 
- Verified our existing version isn't vulnerable as per project-zero repro steps.
> `libxslt`: nopatch CVE-2022-29824

- SPECS/rubygem-elasticsearch/rubygem-elasticsearch.signatures.json
- SPECS/rubygem-elasticsearch/rubygem-elasticsearch.spec
- cgmanifest.json
---
update rubygem-elasticsearch to 8.2.2
- update rubygem-elasticsearch to 8.2.2
NO
- [Bug 40019289](https://microsoft.visualstudio.com/OS/_workitems/edit/40019289): [CVE][Patching] Patching CVE-2022-23712 for the 1.0 branch - Score: 7.5 [rubygem-elasticsearch 8.2.0]
- https://nvd.nist.gov/vuln/detail/CVE-2022-23712
> update rubygem-elasticsearch to fix CVE-2022-23712

- SPECS/mysql/mysql.signatures.json
- SPECS/mysql/mysql.spec
- cgmanifest.json
---
Update mysql to version 8.0.29 to fix 17 CVEs
- Update mysql to version 8.0.29 to fix 17 CVEs
- Fixes CVE-2022-21460, CVE-2022-21454, CVE-2022-21427, CVE-2022-21425, CVE-2022-21417, CVE-2022-21412, CVE-2022-21489, CVE-2022-21444, CVE-2022-21451, CVE-2022-21485, CVE-2022-21484, CVE-2022-21483, CVE-2022-21482, CVE-2022-21479, CVE-2022-21478, CVE-2022-21486, CVE-2021-22570
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-21460
- https://nvd.nist.gov/vuln/detail/CVE-2022-21454
- https://nvd.nist.gov/vuln/detail/CVE-2022-21427
- https://nvd.nist.gov/vuln/detail/CVE-2022-21425
- https://nvd.nist.gov/vuln/detail/CVE-2022-21417
- https://nvd.nist.gov/vuln/detail/CVE-2022-21412
- …
> `mysql`: update to version 8.0.29 to fix 17 CVEs

- SPECS/libxslt/CVE-2022-29824.nopatch
Clearing CVE-2022-29824 against libxslt.  Libxslt takes a depenency on libxml2.  As libxml2 is fixed, the specific finding against libxslt is also now resolved. See commit  https://github.com/microsoft/CBL-Mariner/commit/66338d14261b3aeb4649e29048ec3ec11287eb29
> Nopatch CVE-2022-29824 the libxslt issue is fixed by libxml2 patch

- SPECS/python-jwt/python-jwt.signatures.json
- SPECS/python-jwt/python-jwt.spec
- cgmanifest.json
---
upgrade python-jwt to 2.4.0 to fix 2022-29217
- upgrade python-jwt to 2.4.0 to fix 2022-29217
- remove setup.cfg as it causes a bug resulting egg package name is UNKNOWN-0.0.0 (mariner 2.0 also removes it)
- remove non-exist files in %file section from previous version 
NO
- [Bug 39916509](https://microsoft.visualstudio.com/OS/_workitems/edit/39916509): [CVE][Patching] Patching CVE-2022-29217 for the 1.0 branch - Score: 7.5 [python-jwt 1.7.1]
- https://nvd.nist.gov/vuln/detail/CVE-2022-29217
> upgrade python-jwt to 2.4.0 to fix 2022-29217

- SPECS/libinput/libinput.signatures.json
- SPECS/libinput/libinput.spec
- cgmanifest.json
---
Our current version of libinput is rather old and vulnerable to CVE-2022-1215
Upgrading to libinput 1.21.0 fixes the CVE and puts us in a better position to take minor version upgrades for future issues.
- Upgrade libinput to version 1.21.0 to fix CVE-2022-1215
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1215
- Local build ongoing
> `libinput`: upgrade to version 1.21.0 for CVE-2022-1215

- SPECS/uclibc-ng/uclibc-ng.signatures.json
- SPECS/uclibc-ng/uclibc-ng.spec
- cgmanifest.json
---
Update uclibc-ng to version 1.0.41 to fix CVE-2022-30295
- Update uclibc-ng to version 1.0.41 to fix CVE-2022-30295
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-30295
- Local build
> `uclibc-ng`: upgrade to 1.0.41 to fix CVE-2022-30295

- toolkit/tools/scheduler/schedulerutils/depsolver.go
---
When the scheduler determines whether a node can be subgraphed, it currently stops at the first unsolvable node. This change will allow it to print the full set of unsolvable nodes. We can then track the amount of unsolvable nodes in daily builds, with the goal of reducing them over time to speed up builds.
- Change depsolver to print all nodes blocking subgraph
**NO**
- Local build
> Print all unsolvable nodes blocking subgraph

- toolkit/scripts/toolchain/container/toolchain-remote-wget-list
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
The toolchain scripts first attempt to download sources from $SOURCE_URL/toolchain, and then try the upstream servers defined in toolchain-remote-wget-list. With this change the sources are downloaded directly from $SOURCE_URL.
Also fix remote URL for some xcb packages that failed to download in my testing.
- Change toolchain to download from  $SOURCE_URL instead of $SOURCE_URL/toolchain
- Fix libxcb and xcb-proto URLs
**YES**
- local build
> [1.0] Use core sources folder for toolchain

- toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
---
For PXE boot scenario, the liveinstaller needs to download the image config file from the pxe server thru network and it is possible that the installation may not have network access yet when the script is run, especially on the first boot. Thus, add retry logic to ping the pxe server ip address to guard against the network timing condition to make sure that the pxe client is able to communicate with the pxe server.
NO
> Add retry logic in runliveinstaller to ensure network access during pxe boot

- .github/workflows/validate-cg-manifest.sh
- toolkit/scripts/rpmops.sh
- toolkit/scripts/update_spec.sh
---
Another step towards making our tools and GitHub checks more reliable. Up until now, calls to `rpmspec` from our scripts didn't take into account the macros we use during spec parsing for package builds. This sometimes caused parsing issues, because RPM didn't understand some macros.
Example: GitHub checks for multiple Python specs (see: [check](https://github.com/microsoft/CBL-Mariner/runs/7083367370?check_suite_focus=true) for #3251) will fail because `rpmspec` cannot expand `pypi_source` used for the `Source0` tag and thus the check will claim that `%{pypi_source}` doesn't match the entry inside `cgmanifest.json`.
The change introduces a `mariner_rpmspec` wrapper, which passes …
> Introducing `mariner_rpmspec` function.

- SPECS/qemu-kvm/CVE-2021-3750.patch
- SPECS/qemu-kvm/qemu-kvm.spec
---
patch qemu-kvm for CVE-2021-3750
- Partially patch qemu-kvm for CVE-2021-3750 according to [upstream](https://bugzilla.redhat.com/show_bug.cgi?id=1999073) 
- For those upstream patches that are not in our QEMU version, they are ignored although the changes are meant to solve the CVE. These upstream changes related to some functions that are not in our version of QEMU.
NO
-[Bug 39601650](https://microsoft.visualstudio.com/OS/_workitems/edit/39601650): [CVE][Patching] Patching CVE-2021-3750 for the 1.0 branch - Score: 8.2 [qemu-kvm 4.2.0]
- https://nvd.nist.gov/vuln/detail/CVE-2021-3750
> patch qemu-kvm for CVE-2021-3750

- .github/workflows/check-package-cgmanifest.yml
- SPECS/coreutils/coreutils.spec
---
My recent change (#3258) seems to have broken our CGmanifest checks in GitHub. It looks like the `rpmspec` version available on Ubuntu 18.04 doesn't support the `--load` argument. Updating to 22.04 fixes the issue.
- Updated PR check to use Ubuntu 22.04.
No.
- #3258
- Ran a check for a test spec change in this PR.
> Update Ubuntu version to 22.04 for CGmanifest check.

- SPECS/coreutils/coreutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The `coreutils` package is able to ship an `arch` program, which is equivalent to running `uname -m`. Other distros ship `arch`, but we don't (since building it is off by default). This PR opts-in to building `arch`, to satisfy a customer request and reduce friction for those migrating from other distros.
- `coreutils`: Ship the `arch` binary
**YES**
- Pipeline delta build 207969
- Package install succeeds in container, and `arch` output matches that of `uname -m`
> coreutils: Build arch binary

- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
- [x Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
---
Cherrypick the fix from 1.0-dev: Upgrade Vim version to 8.2.5154 to fix CVEs: CVE-2022-2124, CVE-2022-2125, CVE-2022-2126 and CVE-2022-2129
- Upgrade to 8.2.5154 to fix CVEs: 2022-2124, 2022-2125, 2022-2126 and 2022-2129
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2124
- https://nvd.nist.gov/vuln/detail/CVE-2022-2125
- https://nvd.nist.gov/vuln/detail/CVE-2022-2126
- https://nvd.nist.gov/vuln/detail/CVE-2022-2129
- Local build
> Upgrade Vim version to 8.2.5154 to fix CVEs (cherry-pick from 1.0-dev)

- SPECS-EXTENDED/hunspell/hunspell-1.7.0-print-format.patch
- SPECS-EXTENDED/hunspell/hunspell.spec
- SPECS-EXTENDED/liboping/liboping-1.10-fix-format-ncurses63.patch
- SPECS-EXTENDED/liboping/liboping.spec
- cgmanifest.json
---
Added patch to fix compliation with ncurses 6.3.
- Change: ncurses [6.3__2.13-3](https://github.com/microsoft/CBL-Mariner/commit/f73c0ea84b87cd3f0352822878941d01d21c2522) patch files for hunspell and liboping
local build
> Added patch to fix compilation with ncurses 6.3 for hunspell and liboping

- toolkit/scripts/toolchain.mk
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
When incrementally building the toolchain, there are 2 attempts at downloading msopenjdk; first from the toolchain.mk file, and then again during build_official_toolchain_rpms.sh. I've added the --no-clobber argument to wget to avoid the following error:
```
Validating contents of toolchain against manifest...
...
ERROR: Mismatched packages between '/__w/1/s/toolkit/resources/manifests/package/toolchain_x86_64.txt' and '/__w/1/s/ToBePublished/build-artifacts/toolchain_built_rpms_all.tar.gz':
msopenjdk-11-11.0.14.1+1-LTS-31207.x86_64.rpm.1
```
- Change build_official_toolchain_rpms.sh to use wget --no-clobber
- Change toolchain.mk to …
> Use --no-clobber for toolchain downloads

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/internal/rpm/rpm.go
---
The current implementation of `ResolveCompetingPackages` assumes it is running on a
distro that doesn't use RPM. Specifically, it doesn't set the root directory which
allows for confusion between the packages being built for CBL-Mariner and the packages
installed on the build system. This change fix this problem by setting the root
directory when calling the `rpm` command.
- Bug fix for `ResolveCompetingPackages` when building on RPM-based distro
NO
- Local build
> Bug fix for `ResolveCompetingPackages` when building on RPM-based distro

- SPECS/cloud-init/CVE-2022-2084.patch
- SPECS/cloud-init/cloud-init.spec
Signed-off-by: Chris Patterson <cpatterson@microsoft.com>
Built, installed, rebooted on a mariner2 instance with no obvious concerns.
> cloud-init: patch for CVE-2022-2084

- SPECS/qemu/qemu.spec
---
Fix build break on `aarch64`
- Remove `x86_64` artifacts for `aarch64`
**NO**
- #3294
- NA
- Pipeline build id: InProgress
NOTE: Did not bump the release, because we did not get a good build yet for the overall pipeline (both ARM & AMD)
> qemu: fix build break on aarch64

- SPECS/kernel-rt/kernel-rt.spec
---
Fix build break in kernel-rt package:
```
"error: File must begin with \"/\": lib/debug"
"Processing files: kernel-rt-5.15.44.1-3.cm2.x86_64"
```
Not bumping release since this package has not yet built.
- Change _lib ("lib") to _libdir ("/usr/lib") in kernel-rt.spec
**NO**
- Pipeline build id: 210208
> Fix kernel-rt build break

- SPECS-EXTENDED/python-argcomplete/python-argcomplete.spec
- SPECS/fish/fish.signatures.json
- SPECS/fish/fish.spec
- SPECS/gh/gh.spec
- cgmanifest.json
---
Fish is a new package, updating to the latest version to resolve a CVE rather than patching since it is so new.
Note: I tried to bump to the latest RHEL spec but it is fairly incompatible with our current environment. Went with piecemeal updates to the spec instead.
- Update Fish to 3.5.0 to resolve CVE-2022-20001
- Add a runtime requirement on `util-linux` to fix an error in Fish
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-20001
- Local build and testing.
- Waiting on check build
> Update fish to 3.5.0 to resolve CVE-2022-20001

- SPECS/python3/python3.spec
---
The bad interpreter fix from #3328 is incomplete- it fixes `/usr/bin/pip3`, but not `/usr/bin/pip3.7`. Unlike similarly versioned files under `/usr/bin`, `/usr/bin/pip3` and `/usr/bin/pip3.7` are separate files, and one is not a symlink to the other. So, let's apply the fix from that PR to `/usr/bin/pip3.7`.
- Apply #3328 interpreter fix to `/usr/bin/pip3.7`
- Not bumping the release number, as this release has not been built yet.
**NO**
- Local build
> python3: Additionally fix shabang for pip3.7 script

- SPECS/redis/disable_active_defrag_big_keys.patch
- SPECS/redis/redis.signatures.json
- SPECS/redis/redis.spec
- cgmanifest.json
---
Backport of redis 6.2.7 fixes from 2.0 to 1.0 to address CVEs.
**NO**
> backported redis 6.2.7 to 1.0 to fix CVE-2021-24736

- SPECS/python3/python3.spec
---
The bad interpreter fix from #3328 and #3333 is incomplete- it fixes `/usr/bin/pip3` and `/usr/bin/pip3.7`, but not `/usr/bin/easy_install-3.7`. So, let's apply the fix from those PRs to `/usr/bin/easy_install-3.7`.
- Apply #3328 interpreter fix to `/usr/bin/easy_install-3.7`
- Not bumping the release number, as this release has not been built yet.
**NO**
- Local build
> python3: Fix bad shabang for easy_install

- SPECS/crash-gcore-command/crash-gcore-command.spec
---
crash-gcore-command seems to have started failing on aarch64 builds after the "arch" command was added to coreutils in #3270 
```
"./libgcore/gcore_defs.h:596:34: error: 'ELF_NGREG' undeclared here (not in a function); did you mean 'ELF_NOTES'?"
```
Disable for aarch64 to unblock our release builds until this can be further investigated and fixed.
- Change crash-gcore-command to build only on x86_64
**NO**
- Pipeline build id: 211180
> Only build crash-gcore-command on x86_64

- SPECS/pygobject3/pygobject3.spec
---
The package has a BR on both `python-setuptools` and `python3-setuptools`. I believe this is causing issues on the `$easy_install_3 pytest` line where the tool tries to install a Python module written for Python 3 but is using Python 2. Removing the Python 2 package and switching to `pip3` from `easy_install`.
- Removed BR on `python-setuptools`.
- Running `pip3 install` instead of `easy_install`.
No.
- Pipeline build: 211188.
> Updating `pygobject3` to fix ptest.

- SPECS-EXTENDED/libftdi/libftdi.spec
---
Package builds for `libftdi` are flaky and they are breaking every now and then on building their docs. Since the file the build complain about is auto-generated during the build, I am suspecting some incorrect configuration causing a race condition where sometimes the file is parsed before it's flushed to the disk. Since we weren't installing the generated documentation anyway, only building it, I am disabling it completely now to stabilize the build.
- Disabled building docs for `libftdi`.
- Removed BR on `doxygen`.
No.
> `libftdi`: disabling docs building to stabilize the build.

- SPECS/clang/clang.spec
---
`clang` currently fails to compile basic C programs on Mariner 1.0 due to missing runtime headers: the necessary headers are only included in the `clang-devel` package. This PR backports the `clang-libs` subpackage from Mariner 2.0's `clang` specfile that provides the necessary libraries and headers for normal operation of `clang`.
- `clang`
- add dependency on `clang-libs`
- remove "%{_libdir}/*.so.*" from "%files"
- `clang-devel`
- remove "%{_libdir}/clang/*" from "%files"
- `clang-libs`
- create package
- add "%{_libdir}/clang/*" and "%{_libdir}/*.so.*" to "%files"
**NO**
- Fixes #3351
- Local build: https://github.com/onalante-msft/mariner-clang/tree/clang-spec
> [1.0] Add clang-libs subpackage to clang specfile

- SPECS/coreutils/CVE-2013-0221.nopatch
- SPECS/coreutils/CVE-2013-0222.nopatch
- SPECS/coreutils/CVE-2013-0223.nopatch
- SPECS/coreutils/CVE-2016-2781.nopatch
- SPECS/coreutils/coreutils.spec
- SPECS/coreutils/fix_test_env_signal_handler.patch
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
`Coreutils` package tests have failed a couple of times in our pipelines due to a [known race condition](https://bugs.gnu.org/51793) in the `env-signal-handler` test. This PR adds the upstream patch fixing this race.
- `coreutils`: Add upstream patch to fix race in env-signal-handler test
- `coreutils`: Ensure SRPMs built on any architecture include all patches
- `coreutils`: Remove nopatch files from spec
**YES**
- Ran 3 check runs with my machine under load and didn't encounter the flaky test issue- here's hoping it's fully fixed!
> coreutils: Fix flaky env-signal-handler test

- toolkit/Makefile
- toolkit/docs/building/building.md
---
Not having a default `SOURCE_URL` in our Makefile has proven to be a user pain point. We shouldn't make users dig through our documentation to find the proper `SOURCE_URL` location. Anyone needing to set an alternative URL can override the default, and most of our downstream internal users store sources directly in `git` anyways.
So, let's set the default `SOURCE_URL` to the sources blobstore for Mariner.
- Add default `SOURCE_URL` of `https://cblmarinerstorage.blob.core.windows.net/sources/core` in `Makefile`
- Update documentation to remove redundant `SOURCE_URL` definitions in `make` calls
**NO**
- Local test of `make input-srpms` with no source URL specified outside of the …
> Set default SOURCE_URL in Makefile

- SPECS/kernel/CVE-2022-34494.nopatch
- SPECS/kernel/CVE-2022-34495.nopatch
---
Address cve-2022-34494 and cve-2022-34495
Address cve-2022-34494 and cve-2022-34495
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-34494
- https://nvd.nist.gov/vuln/detail/CVE-2022-34495
- local build
> kernel: Address cve-2022-34494 and cve-2022-34495

- SPECS/maven/maven.signatures.json
- SPECS/maven/maven.spec
Maven: Fix aarch64 builds by including 1.0 maven aarch64 rpm in sources list.
---
Adding dependent maven binary from 1.0 PMC for aarch64 in sources list. This is needed for packages building using maven for aarch64.
- Fix aarch64 builds by including 1.0 maven aarch64 rpm also sources in spec file
NO
- #xxxx
- Local build
> Maven: For aarch64 builds

- SPECS/vim/vim.spec
---
- [Bug 40363041](https://microsoft.visualstudio.com/OS/_workitems/edit/40363041?src=WorkItemMention&src-action=artifact_link) indicates that when installing vim into a Mariner 2.0 container, the post-install script fails because the sed tool is not there by default.
- While working on this issue, I noticed that the sed package exists in the Mariner 2.0 container, but I have added `Requires(post): sed` in `SPECS/vim/vim.spec` file to ensure that the sed tool is present when the post-install script runs.
- Added a `Requires(post): sed` in the `SPECS/vim/vim.spec` file
**NO**
- Local build
- Using rpm to manually install the updated …
> Adding sed as a post install requirement in the vim spec

- SPECS/e2fsprogs/e2fsprogs.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Some of the `e2fsprogs` ptests are failing inconsistently and running them in a single thread seems to make them more stable. They still fail every now and then, but it doesn't look like a regression. I've added a few lines to print more logs for failing tests to make it easier for us to debug in the future.
- Running `e2fsprogs` tests in a single thread.
- Printing logs for failing tests to ease debugging.
Yes.
- Pipeline build 215120.
> Update `e2fsprogs`: running tests in a single thread to make them more consistent.

- SPECS-EXTENDED/python-pytest-timeout/python-pytest-timeout.spec
- cgmanifest.json
---
- Drop BR on pytest and install latest deps to enable ptest
**NO**
- NA
- NA
> python-pytest-timeout: drop BR on pytest and install latest deps to enable ptest

- SPECS/selinux-policy/0039-unconfined-Manage-own-fds.patch
- SPECS/selinux-policy/0040-usermanage-Add-sysctl-access-for-groupadd-to-get-num.patch
- SPECS/selinux-policy/0041-systemd-systemd-cgroups-reads-kernel.cap_last_cap-sy.patch
- SPECS/selinux-policy/0042-kernel-hv_utils-shutdown-on-systemd-systems.patch
- SPECS/selinux-policy/0043-Container-Minor-fixes-from-interactive-container-use.patch
- SPECS/selinux-policy/selinux-policy.spec
---
Backporting 3 SELinux patch PRs to maintain parity between 1.0 and 2.0 SELinux policy. 
https://github.com/microsoft/CBL-Mariner/pull/3176
https://github.com/microsoft/CBL-Mariner/pull/3331
https://github.com/microsoft/CBL-Mariner/pull/3397
- Fixes for interactive container use.
- Add sysctl access for groupadd and systemd-cgroups
- Allow access for hv_utils shutdown sequence access to poweroff.target.
- Unconfined domains can manipulate thier own fds.
**NO**
- Pipeline build running now
> SELinux backport for (interactive container use, fds manipulation and minor fixes)

- SPECS/python-jinja2/python-jinja2.signatures.json
- SPECS/python-jinja2/python-jinja2.spec
- cgmanifest.json
---
Update python-jinja2 to v2.11.3 to fix CVE-2020-28493
- Update python-jinja2 to v2.11.3 to fix CVE-2020-28493
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-28493
> Update python-jinja2 to v2.11.3 to fix CVE-2020-28493

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- cgmanifest.json
---
Update postgresql to v12.8 to fix CVE-2021-3677
- Update postgresql to v12.8 to fix CVE-2021-3677
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3677
> Update postgresql to v12.8 to fix CVE-2021-3677

- SPECS/perl-File-Which/perl-File-Which.spec
---
- Add BR on `perl(Test::More)`, `perl(Env)` & `perl(ExtUtils::MakeMaker)` to enable ptest
**NO**
- NA
- NA
> perl-File-Which: add BR on `perl-{(Env),(ExtUtils::MakeMaker),(Test::More)}` to enable ptest

- SPECS/k3s/install.patch
- SPECS/k3s/k3s.spec
---
This change patches the rpm install. Without this patch you will not be able to properly integrate k3s at build time. It will work via the package manager on a live system. However, it will fail in the Mariner build environment while building a VHDX when systemd is not up and running in the chroot environment.
- Fixes the install section. Allows integration of k3s at runtime in the Mariner build environment.
**YES/NO**
- #xxxx
- build locally
> Fixes the k3s install to allow VHDX integration.

- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
---
Update nodejs to v14.20.0 to fix CVEs 2022-32213, 2022-32214, 2022-32215
- Update nodejs to v14.20.0 to fix CVEs 2022-32213, 2022-32214, 2022-32215
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-32213
- https://nvd.nist.gov/vuln/detail/CVE-2022-32214
- https://nvd.nist.gov/vuln/detail/CVE-2022-32215
> Update nodejs to v14.20.0 to fix CVEs 2022-32213, 2022-32214, 2022-32215

- SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
- SPECS/grub2/grub2.spec
---
- Remove the provides with grub2-efi-binary-noprefix in grub spec in order to resolve the comparison failure during build process
NO
- Local Build
> Remove unneeded provides for grub2-efi-binary-noprefix

- SPECS/python-mistune/CVE-2022-34749.nopatch
---
CVE-2022-34749 applies to the inline_parser, which is not introduced until v2.0.0+. Our v0.8.3 python-mistune is not vulnerable. 
- Nopatch CVE-2022-34749
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-34749
> Add nopatch for python-mistune cve CVE-2022-34749

- SPECS/cloud-init/add-mariner-distro-support.patch
- SPECS/cloud-init/cloud-init.spec
---
Update cloud-init service to add sysinit.target as one of its dependencies. 
- Add sysinit.target as dependency for cloud-init.service on Mariner
- Change is made by modify add-mariner-distro-support patch. After the change, the line "Before=sysinit.target" is in cloud-init.service 
NO
- [Bug 39862391](https://microsoft.visualstudio.com/OS/_workitems/edit/39862391): [2.0] Update cloud-init systemd units to ensure that sysinit.target means cloud-init.service has finished
- Pipeline build id: local package build
> update cloud-init service to add sysinit.target dependency

- SPECS/kernel/CVE-2021-4135.nopatch
- SPECS/kernel/CVE-2022-2380.nopatch
- SPECS/kernel/CVE-2022-33743.nopatch
- SPECS/kernel/CVE-2022-33744.nopatch
…22-33744
---
nopatch kernel CVES 2022-2380, 2022-33743, 2021-4135, 2022-33744
- nopatch kernel CVES 2022-2380, 2022-33743, 2021-4135, 2022-33744
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-2380
- https://nvd.nist.gov/vuln/detail/CVE-2022-33743
- https://nvd.nist.gov/vuln/detail/CVE-2021-4135
- https://nvd.nist.gov/vuln/detail/CVE-2022-33744
> Kernel CVE - nopatch kernel CVES 2022-2380, 2022-33743, 2021-4135, 2022-33744

- SPECS/python-pexpect/python-pexpect.spec
---
The `spawn_uses_env` test in `python-pexpect` is flaky (see: [here](https://github.com/pexpect/pexpect/issues/699)). I'm disabling it until the issue gets resolved in upstream.
- Disabled the `spawn_uses_env` test.
No.
- Pipeline buddy build: 223552.
> python-pexpect: disable flaky `spawn_uses_env` test.

- SPECS/perl-Object-Accessor/perl-Object-Accessor.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(ExtUtils::MakeMaker)` & other check deps to enable ptest
**Yes**
- NA
- NA
> perl-Object-Accessor: add BR on `perl(ExtUtils::MakeMaker)` & check deps to enable ptest

- SPECS/gnupg2/gnupg2.signatures.json
- SPECS/gnupg2/gnupg2.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update gnupg2 to 2.3.7 to resolve CVE-2022-34903
- Change gnupg2 to version 2.3.7
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-34903
- Pipeline build id: 22361 (AMD64), 223605 (ARM64)
> Update gnupg2 to 2.3.7 to resolve CVE-2022-34903

- SPECS/gnutls/gnutls.signatures.json
- SPECS/gnutls/gnutls.spec
- cgmanifest.json
---
Update gnutls to 3.7.7 to resolve CVE-2022-2509
- Change gnutls to version 3.7.7
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2509
- Pipeline build id: 223613 (AMD64), 223582 (ARM64)
> Update gnutls to 3.7.7 to resolve CVE-2022-2509

- SPECS/busybox/CVE-2022-30065.patch
- SPECS/busybox/ash-fix-use-after-free-in-bash-pattern-substitution.patch
- SPECS/busybox/ash-fix-use-after-free-in-pattern-substituon-code.patch
- SPECS/busybox/awk-input-numbers-are-never-octal-or-hex-only-progra.patch
- SPECS/busybox/busybox.spec
Reference: https://bugs.busybox.net/show_bug.cgi?id=14781
---
Patch CVE-2022-30065
- Patch CVE-2022-30065
Also introduce three more fixes from upstream:
- e2952dfaf awk: input numbers are never octal or hex
- daa66ed62 ash: fix use-after-free in pattern substituon code
- 7c2a3bdde ash: fix use-after-free in bash pattern substitution
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-30065
- Buddy Build: [223682](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=223682&view=results)
> busybox: patch CVE-2022-30065

- SPECS-EXTENDED/xterm/xterm-defaults.patch
- SPECS-EXTENDED/xterm/xterm-desktop.patch
- SPECS-EXTENDED/xterm/xterm-man-paths.patch
- SPECS-EXTENDED/xterm/xterm.signatures.json
- SPECS-EXTENDED/xterm/xterm.spec
- cgmanifest.json
`NOTE: The tarball for this download has a certificate issue :(` 
---
Address CVE-2021-27135
- Bump version to 372 to address CVE-2021-27135
- Refresh all patches to apply cleanly
- Switch url to `https` instead of `ftp`
- Cosmetic changes to spec formating
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-27135
> xterm: bump version to 372 to address CVE-2021-27135

- SPECS/zlib/CVE-2022-37434.patch
- SPECS/zlib/zlib.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Use upstream patches to fix CVE-2022-37434 in the `zlib` package.
The upstream commits used are as follows: madler/zlib@eff308af425b67093bab25f80f1ae950166bece1 (original fix), madler/zlib@1eb7682f845ac9e9bf9ae35bbfb3bad5dacbd91d (fixes [segfaults](https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1#commitcomment-80589094) caused by original fix)
- `zlib`: Add upstream patches for CVE-2022-37434
- `zlib`: Fix packaged license- actual license is contained within README
- `zlib`: License verified
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-37434
- Check and non-check buddy builds outside toolchain pass
- Full toolchain build succeeds
> Patch CVE-2022-37434 in zlib

- SPECS/nodejs/nodejs.spec
---
When updating to nodejs v16.16.0, I forgot to bump the npm_version to reflect the version of npm bundled with node. 
- Change npm_version to 8.11.0 to reflect what is actually installed with node 16.16.0
NO
- noop
> Fix npm version in nodejs.spec

- SPECS/audit/audit.spec
- SPECS/blobfuse/blobfuse.spec
- SPECS/cni/cni.spec
- SPECS/coredns/coredns-1.8.0.spec
- SPECS/coredns/coredns-1.8.4.spec
- SPECS/coredns/coredns-1.8.6.spec
- SPECS/cri-tools/cri-tools.spec
- SPECS/etcd/etcd-3.4.13.spec
- SPECS/etcd/etcd-3.5.0.spec
- SPECS/etcd/etcd-3.5.1.spec
- SPECS/flannel/flannel.spec
- SPECS/glide/glide.spec
- SPECS/go-md2man/go-md2man.spec
- SPECS/gobject-introspection/gobject-introspection.spec
- SPECS/golang/golang.signatures.json
- SPECS/golang/golang.spec
- SPECS/helm/helm.spec
- SPECS/libnvidia-container/libnvidia-container.spec
- SPECS/moby-buildx/moby-buildx.spec
- SPECS/moby-cli/moby-cli.spec
- SPECS/moby-containerd/moby-containerd.spec
- SPECS/moby-engine/moby-engine.spec
- SPECS/moby-runc/moby-runc.spec
- SPECS/node-problem-detector/node-problem-detector.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade golang 1.18 to 1.18.5 to fix ten CVEs, and bump dependent packages.
- `golang`: - Upgrade to version 1.18.5 to fix CVE-2022-1705, CVE-2022-1962, CVE-2022-28131, CVE-2022-30630, CVE-2022-30631, CVE-2022-30632, CVE-2022-30633, CVE-2022-30635, CVE-2022-32148, and CVE-2022-32189 
- Bump packages depending on `golang`
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1705
- https://nvd.nist.gov/vuln/detail/CVE-2022-1962
- https://nvd.nist.gov/vuln/detail/CVE-2022-28131
- https://nvd.nist.gov/vuln/detail/CVE-2022-30630
- https://nvd.nist.gov/vuln/detail/CVE-2022-30631
- https://nvd.nist.gov/vuln/detail/CVE-2022-30632
- https://nvd.nist.gov/vuln/detail/CVE-2022-30633
- …
> Upgrade go 1.18 to 1.18.5 to fix ten CVEs

- SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
- SPECS/cloud-hypervisor/config.toml
- SPECS/rust/rust.signatures.json
- SPECS/rust/rust.spec
- cgmanifest.json
---
This change upgrades cloud-hypervisor package to v26.0. This version of cloud-hypervisor requires a higher version of rust, so this change set also updates rust to v1.62.1
- Update cloud-hypervisor to v26.0
- Update rust to v1.62.1
- Update cgmanifest entries for rust and cloud-hypervisor
**NO**
Local build
> Update cloud-hypervisor to v26.0 and rust to v1.62.1

- SPECS/rubygem-yajl-ruby/CVE-2022-24795.patch
- SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.spec
---
rubygem-yajl-ruby: fix CVE 2022 24795
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE 2022 24795
> rubygem-yajl-ruby: fix CVE 2022 24795

- toolkit/docs/formats/imageconfig.md
- toolkit/tools/imagegen/configuration/networkconfig.go
- toolkit/tools/imagegen/installutils/installutils.go
---
- Enable performing adding custom package repo and network configuration for normal ISO installation instead of gating these behaviors for kickstart-like installation only
NO
> Enable package repo generation and network config for non-kickstart like ISO installation

- toolkit/imageconfigs/additionalconfigs/chrony.cfg
- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2-aarch64.json
- toolkit/imageconfigs/marketplace-gen2.json
---
Add a new crony config into additional configs folder and start using the new configurations in gen1, gen2 and gen2 aarch64. The new configurations include the [new configurations](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync) for chrony starting from ubuntu 19.10.
- Change marketplace jsons to start using new chrony config
**NO**
- [#Task](https://microsoft.visualstudio.com/OS/_sprints/taskboard/Mariner%20Platform/OS/2208?workitem=39161704)
- Created 3 Mariner virtual machines (gen1, gen2 and aarch64) and run chrony commands, compared the timing results with ubuntu machine.
> Add an additional chrony config with updated version

- SPECS/libsemanage/libsemanage.signatures.json
- SPECS/libsemanage/libsemanage.spec
- SPECS/libsemanage/semanage.conf
This will cause /root to get inappropriate default_t labels.
---
Change semanage.conf not to ignore `/root`. With this ignored, /root gets the wrong SELinux labels.
- Remove ignoredirs from semanage.conf.
**NO**
- Pipeline build id: 228350
- Local builds
> libsemanage: Do not ignore /root.

- SPECS/dpdk/dpdk.signatures.json
- SPECS/dpdk/dpdk.spec
- cgmanifest.json
---
Address CVE-2022-2132
- Bump version to 21.11.2 to address CVE-2022-2132
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-2132 (not on NIST yet)
- https://www.openwall.com/lists/oss-security/2022/08/29/4
- BuddyBuild: [230591](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=230591&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2084)
> dpkd: bump version to 21.11.2 to address CVE-2022-2132

- SPECS/mariadb/mariadb.signatures.json
- SPECS/mariadb/mariadb.spec
- cgmanifest.json
---
Update mariadb to v10.6.9 to fix CVE-2022-32091, CVE-2022-32081
- Update mariadb to v10.6.9
- Fix CVE-2022-32091, CVE-2022-32081
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-32091
- https://nvd.nist.gov/vuln/detail/CVE-2022-32081
- Full local build succeeded
- Check section ran successfully in individual package build
> `mariadb`: update to v10.6.9 to fix CVE-2022-32091, CVE-2022-32081

- .github/workflows/cgmanifest.json
- cgmanifest.json
- toolkit/scripts/toolchain/cgmanifest.json
- toolkit/tools/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
> Add `$schema` to `cgmanifest.json`

- SPECS-EXTENDED/python-ntlm-auth/python-ntlm-auth.spec
---
- Add BR on `pip` & drop BR on `pytest` to enable ptest
**NO**
- NA
- NA
- BuddyBuild: [231478](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=231478&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1785)
> python-ntlm-auth: add BR on `pip` & drop BR on `pytest` to enable ptest

- SPECS/kata-containers/kata-containers.spec
---
Resolve arm64 build break of kata-containers package by excluding "configuration-acrn.toml" which is not available on arm64.
```
"Processing files: kata-containers-2.5.0-1.cm2.aarch64"
"error: File not found: /usr/src/mariner/BUILDROOT/kata-containers-2.5.0-1.cm2.aarch64/usr/share/kata-containers/defaults/configuration-acrn.toml"
```
Configuration for arm64:
```
"• hypervisors:"
="\tDefault: qemu"
="\tKnown: acrn cloud-hypervisor firecracker qemu"
="\tAvailable for this architecture: cloud-hypervisor firecracker qemu"
```
Configuration for x64:
```
"• hypervisors:"
="\tDefault: qemu"
="\tKnown: acrn cloud-hypervisor firecracker …
```
> kata-containers: remove acrn config for arm64

- SPECS/libguestfs/libguestfs.spec
---
Resolve issue delta building libguestfs
```
1. cannot install both qemu-img-6.2.0-6.cm2.x86_64 and qemu-img-6.2.0-5.cm2.x86_64
2. Found 1 problem(s) while resolving
3. Error(1301) : Solv general runtime error
```
- Change libguestfs to require qemu-img package
**NO**
> libguestfs: require qemu-img package instead of binary

- SPECS/colord/CVE-2021-42523.patch
- SPECS/colord/colord.spec
---
Patch CVE-2021-42523 in colord
- Patch CVE-2021-42523 in colord
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-42523
- Individual local package build succeeded
- Full package build succeeded
> `colord`: fix CVE-2021-42523

- SPECS/python3/CVE-2021-28861.patch
- SPECS/python3/python3.spec
---
add patch for python3 to fix CVE-2021-28861
- add patch for python3 to fix CVE-2021-28861 according to [upstream fix](https://github.com/python/cpython/pull/93879)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-28861
- Local package build with RUN_TEST=y
> add patch for python3 to fix CVE-2021-28861

- SPECS/mariadb/mariadb.signatures.json
- SPECS/mariadb/mariadb.spec
- cgmanifest.json
Pulling to 2.0 branch to release fix for this high CVE
> [2.0] `mariadb`: update to v10.6.9 to fix CVE-2022-32091, CVE-2022-32081

- .github/workflows/validate-cg-manifest.sh
- SPECS/virglrenderer/CVE-2022-0135.patch
- SPECS/virglrenderer/virglrenderer.signatures.json
- SPECS/virglrenderer/virglrenderer.spec
- cgmanifest.json
---
Patch CVE-2022-0135 in virglrenderer
- Patch CVE-2022-0135 in virglrenderer
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0135
- Individual local build succeeded
- Full local build succeeded
> `virglrenderer`: fix CVE-2022-0135

- SPECS/openvswitch/CVE-2021-3905
- SPECS/openvswitch/openvswitch.spec
---
Add patch for openvswtich to fix CVE-2021-3905
- Add patch for openvswtich to fix CVE-2021-3905
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3905
- Local package build with RUN_TEST=y
> Add patch for openvswtich to fix CVE-2021-3905

- SPECS/libtar/libtar-1.2.11-mem-deref.patch
- SPECS/libtar/libtar-1.2.20-CVE-2021-33643-CVE-2021-33644.patch
- SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
- SPECS/libtar/libtar-1.2.20-fix-resource-leaks.patch
- SPECS/libtar/libtar-1.2.20-static-analysis.patch
- SPECS/libtar/libtar-gen-debuginfo.patch
- SPECS/libtar/libtar.spec
---
The NIST database does not mark these fixes as available, however Redhat has patched them in Fedora along with several other correctness issues.
We already had analogues to a pair of the patches were left in place. 
- Apply Fedora patches for CVE-2021-33643, CVE-2021-33644, CVE-2021-33645, CVE-2021-33646
- Apply misc. Fedora patches for other correctness issues
**NO**
-  https://nvd.nist.gov/vuln/detail/CVE-2021-33643
-  https://nvd.nist.gov/vuln/detail/CVE-2021-33644
-  https://nvd.nist.gov/vuln/detail/CVE-2021-33645
-  https://nvd.nist.gov/vuln/detail/CVE-2021-33646
Local build, full pipeline queued
pipeline passed: 233004
> libtar: Pull misc Fedora patches, fix CVE-2021-33643, CVE-2021-33644, CVE-2021-33645, CVE-2021-33646

- SPECS-EXTENDED/ripgrep/ripgrep.spec
- SPECS/clamav/clamav.spec
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
- SPECS/librsvg2/librsvg2.spec
- SPECS/mozjs/mozjs.spec
- SPECS/rpm-ostree/rpm-ostree.spec
- SPECS/rust/rust.spec
---
Currently, our version of `rustc` is shipped in a development release mode with unstable features enabled. Oops! That's unintentional and goes against what most customers would expect. This PR sets up our `rust` package to build as a stable release.
Rust:
- Configure as a stable release, which disables unstable features
- Add runtime requirements on gcc, binutils, glibc-devel
- Package ASL 2.0 license, additional copyright information
- Fix licensing info- dual-licensed, not multiply-licensed
Other packages:
- Bump release to rebuild with new Rust package
**NO**
- Test build of affected packages- no regressions in package tests
> Build Rust as a stable release and disable unstable features

- SPECS/qemu/CVE-2021-4158.patch
- SPECS/qemu/qemu.spec
---
Add a patch for Qemu to fix CVE-2021-4158
- Patch Qemu CVE-2021-4158
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4158
- Local build with check
- Pipeline build in progress  (buddy build 233382)
> qemu: Patch CVE-2021-4158

- SPECS/libtar/libtar.spec
---
Libtar spec had some undesirable parts from our initial import. Sanitize the formatting, remove the .la files, and remove the explicit `Provides: libtar.so.0()(64bit)` which rpmbuild should be auto including (validated with `rpm -qlPp
- Remove .la files
- Remove explicit provide on library, rely on generator instead
- Misc formatting
**NO**
Local build
> libtar: Fixup spec formatting, remove .la files, remove explicit provides

- SPECS/libtar/libtar-1.2.11-mem-deref.patch
- SPECS/libtar/libtar-1.2.20-CVE-2021-33643-CVE-2021-33644.patch
- SPECS/libtar/libtar-1.2.20-CVE-2021-33645-CVE-2021-33646.patch
- SPECS/libtar/libtar-1.2.20-fix-resource-leaks.patch
- SPECS/libtar/libtar-1.2.20-static-analysis.patch
- SPECS/libtar/libtar-gen-debuginfo.patch
- SPECS/libtar/libtar.spec
---
Back porting libtar CVE fixes from Mariner 2.0.
1. https://github.com/microsoft/CBL-Mariner/pull/3686 
2. https://github.com/microsoft/CBL-Mariner/pull/3698
CVE fixes for CVE-2021-33643, CVE-2021-33644, CVE-2021-33645, CVE-2021-33646
The NIST database does not mark these fixes as available, however Redhat has patched them in Fedora along with several other correctness issues.
We already had analogues to a pair of the patches were left in place.
Libtar spec had some undesirable parts from our initial import. Sanitize the formatting, remove the .la files, and remove the explicit Provides: libtar.so.0()(64bit) which rpmbuild should be auto including (validated with `rpm -qlPp
- …
> Fixes for libtar CVE-2021-33643 CVE-2021-33644 CVE-2021-33645 CVE-2021-33646

- SPECS/libvirt/libvirt.spec
---
libvirt: require qemu-img package instead of binary to resolve delta build issue.
```
1. cannot install both qemu-img-6.2.0-7.cm2.x86_64 and qemu-img-6.2.0-5.cm2.x86_64
Found 1 problem(s) while resolving
Error(1301) : Solv general runtime error
```
- Change libvirt to require qemu-img package
**NO**
- Pipeline build id: 234436
> libvirt: require qemu-img package instead of binary

- SPECS/livepatching/livepatching.spec
---
Disabling building of `livepatching.spec` for ARM64 - the package depends on AMD64-only `kpatch` and there's no livepatching available for ARM64 anyway. At least not yet.
**NOTE**: not updating the `Release` tag, since the package hasn't been released or even built properly, yet.
- Made `livepatching.spec` build only under x86_64.
No.
- N/A
> livepatching: make exclusive to x86_64.

- SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.spec
- cgmanifest.json
---
- Add BR on python-pip and drop BR on pytest to enable ptest
**NO**
- NA
- NA
- Local Build with RUN_CHECK=y && RUN_CHECK=n
- BuddyBuild: [235687](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=235687&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2070)
> python-kdcproxy: add BR on python-pip and drop BR on pytest to enable ptest

- SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.spec
---
- Add BR on `perl(blib)` to enable ptest
**NO**
- NA
- NA
- BuddyBuild: [235712](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=235712&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2144)
> perl-Config-IniFiles: add BR on `perl(blib)` to enable ptest

- SPECS-EXTENDED/mock/mock.spec
---
- Add BR on `python3-pip` & drop un-needed deps to enable ptest
**NO**
- NA
- NA
- BuddyBuild: [PR-3678](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=236249&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1893)
> mock: add BR on `python3-pip` & drop un-needed deps to enable ptest

- SPECS/cloud-init/add-mariner-distro-support.patch
- SPECS/cloud-init/cloud-init.spec
---
This is PR is aimed to revert the recent changes that adding sysinit.target dependency on cloud-init as it introduced issues on Mariner derivative builds. See [Bug 41171461](https://microsoft.visualstudio.com/OS/_workitems/edit/41171461): GCS services starts 2 mins late in Mariner2.0 (5.15.57.1-3.cm2) causing VM create to fail and [Bug 41238224](https://microsoft.visualstudio.com/OS/_workitems/edit/41238224): Performance regression, takes a long time to start the VM, used to be faster
- Revert change made on https://github.com/microsoft/CBL-Mariner/pull/3485 and https://github.com/microsoft/CBL-Mariner/pull/3606
- Bump cloud-init version to 22.2-8
NO
- [Bug …
> revert cloud-init dependency

- SPECS/libjpeg-turbo/libjpeg-turbo.signatures.json
- SPECS/libjpeg-turbo/libjpeg-turbo.spec
- cgmanifest.json
---
Upgrade libjpeg-turbo version to 2.1.4 to fix [CVE-2020-35538](https://github.com/advisories/GHSA-grwc-h387-x9h2)
- Change
Upgrade libjpeg-turbo version to 2.1.4 to fix [CVE-2020-35538](https://github.com/advisories/GHSA-grwc-h387-x9h2)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-35538
- local build
> Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538

- SPECS/cloud-init/add-mariner-distro-support.patch
- SPECS/cloud-init/cloud-init.spec
- SPECS/libtirpc/CVE-2021-46828.nopatch
- SPECS/mariner-release/mariner-release.spec
Merge updates for September 2.0 release 2:
Bump mariner-release to 2.0-20
cloud-init: update to 22.2-8
libtirpc: add nopatch for CVE-2021-46828
> Merge updates for September 2.0 release 2

- SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec
---
The permissions applied to keysinuse.so during KeysInUse-OpenSSL package install were not consistent with other OpenSSL engines. This prevented using the KeysInUse engine in user mode, until the engine's permissions were corrected.
- Simplified KeysInUse-OpenSSL installation
- Fixed permissions issue present in KeysInUse-OpenSSL package
**NO**
- local build, manual test
> KeysInUse-OpenSSL: reintroduce keysinuseutil & simplify package install

- SPECS/expat/CVE-2022-40674.patch
- SPECS/expat/expat.spec
- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Pull CVE-2022-40674 fix for expat
Bump mariner-release to 2.0-21
> Update expat CVE and mariner-release bump for 2.0 September update 3

- SPECS/finger/CVE-1999-0150.nopatch
- SPECS/finger/CVE-1999-0612.nopatch
This is a nopatch of two CVE's against the finger utility.  Neither CVE-1999-0150 nor CVE-1999-0612 apply to the version in c-based BSD version provided by Mariner.
> Clear CVE's against finger source

- SPECS/xmlsec1/xmlsec1.signatures.json
- SPECS/xmlsec1/xmlsec1.spec
- cgmanifest.json
---
Fix for error building openscap, by updating xmlsec1 to latest version 1.2.34.
```
"make[2]: Leaving directory '/usr/src/mariner/BUILD/openscap-1.3.5/build'"
"/usr/bin/ld: /usr/lib/libxmlsec1.so: undefined reference to `xmlNanoFTPInit@LIBXML2_2.4.30'"
"/usr/bin/ld: /usr/lib/libxmlsec1.so: undefined reference to `xmlNanoFTPCleanup@LIBXML2_2.4.30'"
"/usr/bin/ld: /usr/lib/libxmlsec1.so: undefined reference to `xmlIOFTPRead@LIBXML2_2.4.30'"
"/usr/bin/ld: /usr/lib/libxmlsec1.so: undefined reference to `xmlIOFTPOpen@LIBXML2_2.4.30'"
"/usr/bin/ld: /usr/lib/libxmlsec1.so: undefined reference to `xmlIOFTPMatch@LIBXML2_2.4.30'"
"/usr/bin/ld: …
```
> xmlsec1: update to 1.2.34 to fix openscap build break

- SPECS/msft-golang/msft-golang.spec
---
Drop the explicit VERSION info while build. `msft-golang` now ships with this file pre-populated
- Drop the explicit VERSION for build.
**NO**
- https://github.com/microsoft/go/issues/262
- https://github.com/microsoft/CBL-Mariner/pull/3819
- NA
Buddy Build:
- AMD64: [PR-3833](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=241597&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2040)
- ARM64: [PR-3833](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=241598&view=logs&j=c …
> msft-golang: drop explicit VERSION in build

- SPECS/python-mako/CVE-2022-40023.patch
- SPECS/python-mako/python-mako.signatures.json
- SPECS/python-mako/python-mako.spec
- cgmanifest.json
---
In #3828 we've updated `python-mako` to version 1.2.2 in order to fix CVE-20220-40023. It turns out, however, that [since version 1.2.0](https://docs.makotemplates.org/en/latest/changelog.html#change-1.2.0) this project depends on either Python 3.8+ (we're below that at the moment) or on the `python3-importlib-metadata` package, which we don't have in for Mariner 1.0. Updating Python or adding the missing package turned out to be a larger change, which we need to schedule for after we're done with this month's release, so for the time being I'm reverting the version bump and backporting the [CVE fix](https://github.com/sqlalchemy/mako/commit/925760291d6efec64fda6e9dd1fd9cfbd5be068 …
> python-mako: revert to 1.0.7, patch CVE-2022-40023.

- SPECS/python-jwt/CVE-2022-39227.nopatch
- SPECS/python-jwt/python-jwt.spec
---
- To address CVE-2022-39227
- Add a clarifying statement in python-jwt.spec file noting the difference between PyJWT and python-jwt
- Add a nopatch file indicating why CVE-2022-39227 does not apply
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/41568697
- https://nvd.nist.gov/vuln/detail/CVE-2022-39227
> Add CVE-2022-39227 nopatch file for python-jwt
