microsoft/azurelinux

SPECS/libxml2/libxml2.signatures.json, SPECS/libxml2/libxml2.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
A CVE fix in `libxml2`.
- Updated `libxml2` to 2.9.13.
Yes.
- https://nvd.nist.gov/vuln/detail/CVE-2022-23308
=> [1.0] Updating `libxml2` to version 2.9.13 to fix CVE-2022-23308.

SPECS/libxml2/libxml2.signatures.json, SPECS/libxml2/libxml2.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Porting a CVE fix for `libxml2` from `1.0-dev`.
- Ported `libxml2` update from `1.0-dev`.
Yes.
- #2454
- https://nvd.nist.gov/vuln/detail/CVE-2022-23308
=> [main] Updating `libxml2` to fix CVE-2022-23308. Port from `1.0-dev`.

SPECS/nodejs/nodejs.signatures.json, SPECS/nodejs/nodejs.spec, cgmanifest.json
---
Fixing CVE-2021-44531 in `nodejs` by updating the package to version 14.18.3.
- Updated `nodejs` to version 14.18.3.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-44531
- Pipeline build id: 173757.
=> Updating `nodejs` to version 14.18.3 to fix CVE-2021-44531.

SPECS/kernel/CVE-2022-0847.nopatch, SPECS/kernel/kernel.spec
---
Address CVE-2022-0847
- Address CVE-2022-0847
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0847
- local build
=> kernel: Address CVE-2022-0847

SPECS/kernel/CVE-2021-20320.nopatch, SPECS/kernel/CVE-2021-20321.nopatch, SPECS/kernel/CVE-2021-4090.nopatch, SPECS/kernel/CVE-2021-4093.nopatch, SPECS/kernel/CVE-2022-0382.nopatch, SPECS/kernel/CVE-2022-0617.nopatch, SPECS/kernel/CVE-2022-0847.nopatch, SPECS/kernel/CVE-2022-25265.nopatch, SPECS/kernel/kernel.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> kernel: cherry-pick CVE nopatches

SPECS/python-pynacl/fix_average_value_hypothesis_error.patch, SPECS/python-pynacl/fix_import_unlimited_error.patch, SPECS/python-pynacl/python-pynacl.spec
---
Fix ptest for package python-pynacl
- BR necessary packages
- Patch test code written for older library version
**NO**
Local build
=> fix python pynacl ptest

SPECS/net-snmp/net-snmp.signatures.json, SPECS/net-snmp/net-snmp.spec, cgmanifest.json
---
upgrade net-snmp to v3.9.1 and avoid enabling services by default
- Upgrade net-snmp to v3.9.1
- In SPEC, removing the lines in post section that enabling snmpd and snmptrapd services. Also remove relevant lines in preun, postun section
NO
-  https://microsoft.visualstudio.com/OS/_workitems/edit/38277837
- Local build. Test by installing the new rpm packages in Mariner VM. Observe that the snmpd and snmptrapd services are disabled
=> upgrade net-snmp to v3.9.1

SPECS/pcre/pcre.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Compile in JIT support in the PCRE library (only on supported architectures).
The same change was made in Mariner 1.0 here: https://github.com/microsoft/CBL-Mariner/pull/2122
- Compile in JIT support in the PCRE library.
- Update manifests.
**YES**
Local build
=> PCRE: Enable JIT feature on supported architectures

SPECS/libestr/libestr.signatures.json, SPECS/libestr/libestr.spec, cgmanifest.json
- [x The toolchain has been rebuilt successfully (or no changes were made to it)
---
Upgrade libestr
**NO**
=> Upgrade libestr to 0.1.11

SPECS/libevent/libevent.signatures.json, SPECS/libevent/libevent.spec, cgmanifest.json
---
Upgrade libevent to latest stable version
**NO**
=> Upgrade libevent to 2.1.12

SPECS/libpq/libpq.spec, SPECS/postgresql/postgresql.spec
---
Fix build.
- Gate `--with-ldap` with a `%{with_check}` to enable build
**NO**
- NA
- NA
- Pipeline build id: Local Build with `RUN_CHECK=n`
=> libpq, postgresql: gate `--with-ldap` with `%{with_check}` to enable build

SPECS/openldap/CVE-2015-3276.patch, SPECS/openldap/CVE-2021-27212.patch, SPECS/openldap/openldap-2.4.40-gssapi-1.patch, SPECS/openldap/openldap-2.4.44-consolidated-2.patch, SPECS/openldap/openldap.signatures.json, SPECS/openldap/openldap.spec, cgmanifest.json
---
Regressions were seen with openldap 2.6.1 from PR #2458  . Revert to previous version 2.4.57. Issue relates to an openldap_r library that has moved in the new version.
- Change openldap from 2.6.1 to 2.4.57
**NO**
- Local build
=> Revert openldap upgrade

SPECS/python-jinja2/python-jinja2.signatures.json, SPECS/python-jinja2/python-jinja2.spec, SPECS/python-markupsafe/python-markupsafe.signatures.json, SPECS/python-markupsafe/python-markupsafe.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updates markupsafe to fix build break from jinja upgrade.
- Markupsafe updated to 2.1.0
- Update to jinja2 restored with addition of version constraint for markupsafe
**YES**
=> Upgraded markupsafe to fix Jinja build

SPECS/python-jmespath/python-jmespath.signatures.json, SPECS/python-jmespath/python-jmespath.spec, cgmanifest.json
---
Upgrade `python-jmespath` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream version 0.10.0
- Switch source from PyPI to GitHub
**NO**
=> [main] python-jmespath: Upgrade to 0.10.0

SPECS/libxml2/libxml2.spec, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The newer version of `libxml2` requires `pythonX-xml` in order to build and I missed the fact, that we don't install these during the toolchain build of `libxml2`.
- Added missing `libxml2` build-time dependencies for the toolchain build.
- 
Yes.
- #2454
- Pipeline toolchain build: 174661
=> [1.0] Installing missing dependencies for `libxml2`.

SPECS/qt5-qtsvg/qt5-qtsvg.spec
---
Nopatching CVE-2022-25634 inside `qt5-qtsvg`. The vulnerability is only present inside Windows code.
- Added a .nopatch for CVE-2022-25634.
- Linted the spec.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-25634
- None, added a simple .nopatch file.
=> [1.0] Nopatching CVE-2022-25634 in `qt5-qtsvg`.

SPECS/kernel/CVE-2021-3609.nopatch, SPECS/kernel/CVE-2021-3656.nopatch, SPECS/kernel/CVE-2021-3744.nopatch, SPECS/kernel/kernel.spec
---
- Address CVE-2021-3656, CVE-2021-3609, CVE-2021-3744
- Address CVE-2021-3656, CVE-2021-3609, CVE-2021-3744
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3656
- https://nvd.nist.gov/vuln/detail/CVE-2021-3609
- https://nvd.nist.gov/vuln/detail/CVE-2021-3744
- local build
=> [1.0] kernel: Address CVE-2021-3656, CVE-2021-3609, CVE-2021-3744

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> Bump Release for CBL-Mariner 1.0 March 2022 Update 2

SPECS/qemu-kvm/CVE-2021-3607.patch, SPECS/qemu-kvm/CVE-2021-3608.patch, SPECS/qemu-kvm/CVE-2021-3930.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
- Address CVE-2021-4145 as nopatch:
CVE-2021-4145 is a NULL-pointer dereference of the `self` pointer in `mirror_wait_on_conflicts()`.
This function in v4.2.0 only checks the `self` pointer with another op, which will not cause a NULL-pointer dereference.
The Code path for CVE-2021-4145 does not occur in the current version (v4.2.0) shipped with `Mariner-1.0`.
- Address CVE-2021-3947 as nopatch:
CVE-2021-3947 is a stack-buffer-overflow in the NVME component. The current version (v4.2.0) does not ship it.
- Patch CVE-2021-3607 & CVE-2021-3930
- Backport patch to address …
=> qemu-kvm: address CVE-2021-{3607, 3608, 3930, 3947, 4145}

cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Our OpenJDK folks have a new release of `msopenjdk-11` for our consumption. This PR updates the package to version `11.0.14.1+1-LTS-31207`.
- Update the version of `msopenjdk-11` downloaded by the toolchain in the toolchain build script, the component governance manifest file, the toolchain manifest files, and the worker chroot manifest files.
**YES**
- Pipeline build id: 175675
=> [main] msopenjdk-11: Upgrade to 11.0.14.1+1-LTS-31207

SPECS/python-pycparser/python-pycparser.signatures.json, SPECS/python-pycparser/python-pycparser.spec, cgmanifest.json
---
Upgrade `python-pycparser` to the latest upstream version to keep our 2.0 repo updated.
- Switch tests to be automatically discovered by the unittest module
**NO**
=> [main] python-pycparser: Upgrade to 2.21

SPECS/python-netifaces/python-netifaces.signatures.json, SPECS/python-netifaces/python-netifaces.spec, cgmanifest.json
---
Upgrade `python-defusedxml` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream version 0.11.0
- Add package test
**NO**
=> [main] python-netifaces: Upgrade to 0.11.0

SPECS/python-defusedxml/python-defusedxml.signatures.json, SPECS/python-defusedxml/python-defusedxml.spec, cgmanifest.json
---
Upgrade `python-defusedxml` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream version 0.7.1
- Switch source from PyPI to GitHub
**NO**
=> [main] python-defusedxml: Upgrade to 0.7.1

SPECS/python-jsonpointer/python-jsonpointer.signatures.json, SPECS/python-jsonpointer/python-jsonpointer.spec, cgmanifest.json
---
Upgrade `python-jsonpointer` to the latest upstream version to keep our 2.0 repo updated.
- Upgrade to latest upstream version 2.2
- Switch source from PyPI to GitHub
**NO**
=> [main] python-jsonpointer: Upgrade to 2.2

SPECS/fakeroot/fakeroot.spec, SPECS/fakeroot/relax_tartest.patch
---
- Update `relax_tartest.patch` to enable ptest
**NO**
- NA
- NA
=> fakeroot: update `relax_tartest.patch` to enable ptest

SPECS/autoconf/autoconf.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix ptest build. All tests pass.
NOTE: Drop the `TESTSUITEFLAGS` as we were skipping `test #38` and only running `500` tests.
This package as of now has `599` tests.
- Add an explicit BR on `perl(File::Find)` to enable ptest
- Cosmetic cleanup of `%changelog`
**YES**
- NA
- NA
=> autoconf: add an explicit BR on `perl(File::Find)` to enable ptest

SPECS/bind/bind.signatures.json, SPECS/bind/bind.spec, cgmanifest.json
---
Bump version to 9.16.27 to address CVE-2021-25220 & CVE-2022-0396
- Bump version to 9.16.27 to address CVE-2021-25220 & CVE-2022-0396
- Cosmetic cleanup of `%changelog`
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-25220
- https://nvd.nist.gov/vuln/detail/CVE-2022-0396
=> bind: bump version to 9.16.27 to address CVE-2021-25220 & CVE-2022-0396

SPECS/pam/pam.spec
---
Modify pam runtime requirements to Recommends. This resolves circular dependencies in the graph and also resolves a boot issue where the login prompt fails to load. Changed cracklib to cracklib-dicts since the dictionary package is usually needed as well.
Note: not updating release version since this is a build fix for a recent change to this package.
- Change pam to Recommend audit-libs and cracklib-dicts
**YES**
- Local VHD build. Booted VM from VHD and confirmed the login prompt is loading properly.
=> Modify pam to use Recommends for runtime dependencies

SPECS/open-vm-tools/open-vm-tools.spec
---
11.3.0 (actually 11.2.0, see https://github.com/vmware/open-vm-tools/issues/576) was changed upstream to error out on platforms other than VMware. Therefore we need to have the virtualization condition in the service unit file instead. However, that condition is currently removed by the Mariner spec file.
- Remove sed calls in open-vm-tools spec file which removed ConditionVirtualization from the service files.
- Apply fixes suggested by spec linting job.
I believe not.
- https://microsoft.visualstudio.com/OS/_workitems/edit/38383347
- No testing done yet; I'd appreciate advice on how to test Mariner changes as this is my first PR here.
=> Bug 38383347: vmtoolsd.service should only run on VMware

SPECS/iperf3/disablepg.patch, SPECS/iperf3/iperf3.signatures.json, SPECS/iperf3/iperf3.spec, cgmanifest.json
---
Updated to 3.11 which requires autoconf  2.71 or higher
- Update to 3.11
**NO**
=> [main] iperf3: Update to 3.11

toolkit/tools/imagegen/installutils/installutils.go
---
Fix ignored post-install script args in imageconfig
- imagegen tool calls shell with `-c` argument but doesn't quote the entire command in a single string
**YES**
- See #1189 for 1.0 fix
=> Fix ignored post-install script args in imageconfig

SPECS/coreutils/coreutils.spec, SPECS/coreutils/skip_test_if_run_as_root.patch, SPECS/file/file.spec, SPECS/file/fix_xz_mime_type_reporting.patch, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix coreutils and file package PTest
**YES**
[- Pipeline build id: 175443](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=175443&view=results)
Closes: #2482
=> [main] fix toolchain pkgs - coreutils, file

SPECS/python-attrs/python-attrs.spec, SPECS/python-botocore/python-botocore.spec, SPECS/python-cherrypy/python-cherrypy.spec, SPECS/python-coverage/python-coverage.spec, SPECS/python-execnet/python-execnet.spec, SPECS/python-jinja2/python-jinja2.spec, SPECS/python-mako/python-mako.spec, SPECS/python-pbr/python-pbr.spec, SPECS/python-pytest-cov/python-pytest-cov.spec, SPECS/python-repoze-lru/python-repoze-lru.spec, SPECS/python-requests/python-requests.spec, SPECS/python-routes/python-routes.spec, SPECS/python-tox-current-env/python-tox-current-env.spec, SPECS/python-twisted/python-twisted.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix `tox` invocation for `%check` section. Use a macro `py%{python3_version_nodots}` instead of hardcoding `py39`
- Use `py%{python3_version_nodots}` instead of hardcoding `py39`
**YES**
- NA
- NA
=> python-*: use `py%{python3_version_nodots}` instead of `py39` as tox env

SPECS/libburn/libburn.signatures.json, SPECS/libburn/libburn.spec, SPECS/libcap-ng/libcap-ng.signatures.json, SPECS/libcap-ng/libcap-ng.spec, SPECS/libconfini/libconfini.signatures.json, SPECS/libconfini/libconfini.spec, SPECS/libfastjson/libfastjson.signatures.json, SPECS/libfastjson/libfastjson.spec, SPECS/libgudev/libgudev.signatures.json, SPECS/libgudev/libgudev.spec, SPECS/libisoburn/libisoburn.signatures.json, SPECS/libisoburn/libisoburn.spec, SPECS/libisofs/libisofs.signatures.json, SPECS/libisofs/libisofs.spec, cgmanifest.json
---
upgrade libburn libfastjson libgudev libisoburn libisofs libcap-ng libconfini
- Change
- Change
- Change
**NO**
- #xxxx
=> upgrade libburn libfastjson libgudev libisoburn libisofs libcap-ng libconfini

SPECS/pyasn1-modules/pyasn1-modules.signatures.json, SPECS/pyasn1-modules/pyasn1-modules.spec, cgmanifest.json
---
Upgrade `pyasn1-modules` to the latest version to keep our 2.0 repo updated.
- Switch source from PyPI to GitHub source
- Clean up test invocation
**NO**
- Local check/non-check build
=> [main] pyasn1-modules: Upgrade to 0.2.8

SPECS/c-ares/c-ares.spec
---
Drop `*LiveSearch*` DNS lookup queries for check section. This seems to be a flaky test(s) which break in our pipeline.
- Drop all `*LiveSearch*` tests in `%check` section
**NO**
- #2402
- NA
=> c-ares: drop all `LiveSearch` DNS lookup tests to enable ptest

SPECS/kernel/CVE-2021-3640.nopatch, SPECS/kernel/CVE-2021-3732.nopatch, SPECS/kernel/CVE-2021-3739.nopatch, SPECS/kernel/CVE-2021-4095.nopatch, SPECS/kernel/CVE-2022-0433.nopatch, SPECS/kernel/CVE-2022-0492.nopatch, SPECS/kernel/CVE-2022-0516.nopatch, SPECS/kernel/kernel.spec
---
- Address CVE-2021-3640, CVE-2021-3739, CVE-2022-0492, CVE-2022-0516, CVE-2021-3732, CVE-2022-0433, CVE-2021-4095
- Address CVE-2021-3640, CVE-2021-3739, CVE-2022-0492, CVE-2022-0516, CVE-2021-3732, CVE-2022-0433, CVE-2021-4095
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3640
- https://nvd.nist.gov/vuln/detail/CVE-2021-3739
- https://nvd.nist.gov/vuln/detail/CVE-2022-0492
- https://nvd.nist.gov/vuln/detail/CVE-2022-0516 
- https://nvd.nist.gov/vuln/detail/CVE-2021-3732
- https://nvd.nist.gov/vuln/detail/CVE-2022-0433
- https://nvd.nist.gov/vuln/detail/CVE-2021-4095
=> kernel: Address CVE-2021-3640, CVE-2021-3739, CVE-2022-0492, CVE-2022-0516, CVE-2021-3732, CVE-2022-0433, CVE-2021-4095

SPECS/leveldb/0001-Allow-leveldbjni-build.patch, SPECS/leveldb/0002-Added-a-DB-SuspendCompations-and-DB-ResumeCompaction.patch, SPECS/leveldb/0003-allow-Get-calls-to-avoid-copies-into-std-string.patch, SPECS/leveldb/0004-bloom_test-failure-on-big-endian-archs.patch, SPECS/leveldb/0006-revert-no-rtti.patch, SPECS/leveldb/0007-detect-system-gtest.patch, SPECS/leveldb/leveldb.signatures.json, SPECS/leveldb/leveldb.spec, cgmanifest.json
---
Upgrade leveldb to latest
- Change
- Change
- Change
**NO**
- #xxxx
=> upgrade leveldb to 1.23

SPECS/ModemManager/ModemManager.spec
---
Fixing build for `ModemManager`. Looks like we installed `ModemManager.service` but didn't list it in the `%files` section.
- Extended `%files` in `ModemManager.spec` to include the systemd unit definition.
No.
=> [main] Fixing `ModemManager` build.

SPECS/iscsi-initiator-utils/iscsi-initiator-utils.spec
---
It turns out that we never packaged iscsi-init.service as part of iscsi-initiator-utils. This causes issues in other installed services:
```
root@cbl-mariner-kqoBhCYisYw5 [ ~ ]# systemctl restart iscsid
Failed to restart iscsid.service: Unit iscsi-init.service not found.
```
- Package iscsi-init.service
NO
- Local mock build. Installed in VM and verified that the dependent service now runs/restarts properly.
=> package iscsi-init.service with iscsi-initiator-utils

SPECS/python-mock/python-mock.signatures.json, SPECS/python-mock/python-mock.spec, cgmanifest.json
---
Upgraded python-mock to 4.0.3 for 2.0
- Upgraded python-mock to 4.0.3
- Changed URL to be stable for future upgrades
**NO**
- local build
=> Upgraded python-mock to 4.0.3

SPECS-EXTENDED/python-uamqp/python-uamqp.spec
PS: Not following the proper process as its SPECS-EXTENDED.
---
Fix build when run with `RUN_CHECK=y`
- NA
**NA**
- NA
- NA
- NA
=> python-uamqp: fix typo in BR

SPECS-EXTENDED/fio/fio-3.29-link-t-io_uring-with-libaio.patch, SPECS-EXTENDED/fio/fio-3.29-use-LDFLAGS-for-dynamic-engines.patch, SPECS-EXTENDED/fio/fio.signatures.json, SPECS-EXTENDED/fio/fio.spec, SPECS-EXTENDED/iio-sensor-proxy/iio-sensor-proxy.spec, SPECS-EXTENDED/ldns/ldns.spec, SPECS-EXTENDED/nbdkit/nbdkit.spec, cgmanifest.json
---
Another batch of `SPECS-EXTENDED` fixes.
- Fixed `fio` and `nbdkit`.
- Corrected `configure` calls in `iio-sensor-proxy` and `ldns`.
No.
=> [main][SPECS-EXTENDED] Fixing `fio` and `nbdkit`.

SPECS/leveldb/leveldb.spec, SPECS/snappy/detect_system_gtest.patch, SPECS/snappy/snappy.spec
---
Fix build break -> Fix snappy so it does not provide gtest/gmock headers and binaries
- Change
- Change
- Change
**NO**
- #xxxx
=> Fix snappy so it does not provide gtest/gmock headers and binaries

SPECS/moby-containerd/containerd.service, SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec
---
Currently, the containerd service is not configured to restart after crash. Enabling restart so the service can recover from crash as it is required dependency for k8s functionality.
- Enable containerd service restart
**NO**
- Full Local build
=> enable containerd service restart

toolkit/tools/imagegen/installutils/installutils.go
---
ISO installer is failing to launch due to an installation order issue. This change detects when the systemd RPM is being installed and forces the audit-libs RPM to be installed first.
- Change installutils 
**NO**
- Pipeline build id: 177656
=> Modify installutils to install audit-libs before systemd

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Update vim to 8.2.4563 to fix CVE-2022-0943
- Change vim.spec to latest version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0943
- Local build
=> Update vim to 8.2.4563 to fix CVE-2022-0943

SPECS/openvswitch/openvswitch.signatures.json, SPECS/openvswitch/openvswitch.spec, cgmanifest.json
---
Upgrades Open vSwitch to the 2.17.0 version.
**NO**
=> Upgrade openvswitch to 2.17.0

SPECS/selinux-policy/0005-systemd-Add-systemd-homed-and-systemd-userdbd.patch, SPECS/selinux-policy/0006-systemd-ssh-Crypto-sysctl-use.patch, SPECS/selinux-policy/0007-systemd-Additional-fixes-for-fs-getattrs.patch, SPECS/selinux-policy/0008-systemd-Updates-for-generators-and-kmod-static-nodes.patch, SPECS/selinux-policy/0009-Add-containers-policy.patch, SPECS/selinux-policy/modules_targeted.conf, SPECS/selinux-policy/selinux-policy.signatures.json, SPECS/selinux-policy/selinux-policy.spec, toolkit/imageconfigs/packagelists/selinux-full.json
---
SELinux updates
- Fix policy issues
- Update patches to upstreamed versions
- Split SELinux packages to reduce size on core images.
**NO**
- Pipeline build id: 173249
=> [main] SELinux policy updates and SELinux size reduction for policy base.

SPECS/python-werkzeug/python-werkzeug.signatures.json, SPECS/python-werkzeug/python-werkzeug.spec, cgmanifest.json
---
Update python-werkzeug to 2.0.3
- Update python-werkzeug to 2.0.3
**NO**
- PKGLIST="python3-werkzeug"
time sudo make build-packages PACKAGE_BUILD_LIST="$PKGLIST" PACKAGE_REBUILD_LIST="$PKGLIST" SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core RUN_CHECK=y
=> Update python-werkzeug to 2.0.3

SPECS/python-yamlloader/python-yamlloader.signatures.json, SPECS/python-yamlloader/python-yamlloader.spec, cgmanifest.json
---
Update python-yamlloader to 1.1.0
- Update python-yamlloader to 1.1.0
**NO**
- PKGLIST="python3-yamlloader"
time sudo make build-packages PACKAGE_BUILD_LIST="$PKGLIST" PACKAGE_REBUILD_LIST="$PKGLIST"  SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core RUN_CHECK=y
=> Update python-yamlloader to 1.1.0

SPECS/python-zope-interface/python-zope-interface.signatures.json, SPECS/python-zope-interface/python-zope-interface.spec, cgmanifest.json
---
Update python-zope-interface to 5.4.0
- Update python-zope-interface to 5.4.0
**NO**
- PKGLIST="python3-zope-interface"
time sudo make build-packages PACKAGE_BUILD_LIST="$PKGLIST" PACKAGE_REBUILD_LIST="$PKGLIST"  SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core RUN_CHECK=y
=> Update python-zope-interface to 5.4.0

SPECS/python-pytest-benchmark/python-pytest-benchmark.signatures.json, SPECS/python-pytest-benchmark/python-pytest-benchmark.spec, SPECS/python-pytest-forked/python-pytest-forked.signatures.json, SPECS/python-pytest-forked/python-pytest-forked.spec, SPECS/python-pytest-mock/python-pytest-mock.signatures.json, SPECS/python-pytest-mock/python-pytest-mock.spec, SPECS/python-pytest-mock/skip_broken_tests_since_3.6.1.patch, SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json, SPECS/python-pytest-xdist/python-pytest-xdist.spec, cgmanifest.json
---
Updating `python-pytest-*` packages to latest versions.
- Updated 4 `python-pytest-*` packages.
No.
- Local package builds with `RUN_CHECK=y`
=> [main] Updating `python-pytest-*` packages.

SPECS/pytest/pytest.spec
---
We were missing the `/usr/bin/pytest` file/link, which is required for the `%pytest` macro to work. Adding it here.
- Added `/usr/bin/pytest` -> `/usr/bin/pytest%{python3_version}`.
No.
- Local package build of another package depending on the `%pytest` macro.
=> [main] Adding missing links to 'pytest' inside `python3-pytest`.

SPECS/nvme-cli/nvme-cli.spec
---
Update nvme-cli spec to more closely match the upstream project's [reference spec](https://github.com/linux-nvme/nvme-cli/blob/master/nvme.spec.in).
Also remove %check tests which were recently added but do not work on nightly build machines.
- Change nvme-cli spec
**NO**
- Local build
=> Update nvme-cli spec and remove broken tests

SPECS/python-werkzeug/python-werkzeug.spec
---
Fix python-werkzeug url
- Fix python-werkzeug url
**NO**
- Local build
=> Fix python-werkzeug url

SPECS/python-snowballstemmer/python-snowballstemmer.signatures.json, SPECS/python-snowballstemmer/python-snowballstemmer.spec, cgmanifest.json
---
Upgrade python-snowballstemmer
**NO**
=> Upgrade python-snowballstemmer

SPECS/python-routes/python-routes.signatures.json, SPECS/python-routes/python-routes.spec, cgmanifest.json
---
Upgrade python-routes to version 2.5.1
**NO**
=> Upgrade python-routes to 2.5.1

SPECS/perl-generators/perl-generators.spec
---
Fix ptest build.
- Add an explict BR on `perl{(ExtUtils::MakeMaker), (Test::More)}` to fix ptest build
**NO**
- NA
- NA
=> perl-generators: add an explicit BR on `perl(ExtUtils::MakeMaker)` to enable ptest

SPECS/selinux-policy/0004-Set-default-login-to-unconfined_u.patch, SPECS/selinux-policy/0010-domain-Allow-lockdown-for-all-domains.patch, SPECS/selinux-policy/0011-systemd-Drop-systemd_detect_virt_t.patch, SPECS/selinux-policy/0012-fstools-Handle-resizes-of-the-root-filesystem.patch, SPECS/selinux-policy/0013-mount-Get-the-attributes-of-all-filesystems.patch, SPECS/selinux-policy/0014-systemd-Misc-updates.patch, SPECS/selinux-policy/0015-rpm-Add-dnf-and-tdnf-labeling.patch, SPECS/selinux-policy/0016-logging-Change-to-systemd-interface-for-tmpfilesd.patch, SPECS/selinux-policy/0017-Add-cloud-init.patch, SPECS/selinux-policy/selinux-policy.spec
Signed-off-by: Chris PeBenito <Christopher.PeBenito@microsoft.com>
---
Add SELinux rules for enforcing mode core images.
- Add SELinux rules for enforcing mode core images.
**NO**
- Pipeline build id: 179075
- Local testing.
=> selinux-policy: Additional policy fixes for enforcing core images.

SPECS/coreutils/coreutils.spec, SPECS/findutils/findutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
coreutils/findutils: Add missing requires to enable SELinux support. Needed so common commands on SELinux systems, such as `ls -Z` and `find -context` work.
- coreutils: Add missing BuildRequires for libselinux.
- findutils: Add missing BuildRequires and Requires for libselinux.
**YES**
- Pipeline build id: 179074
=> coreutils/findutils: Add missing requires to enable SELinux support.

SPECS/coreutils/coreutils.spec, SPECS/findutils/findutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Backporting changes from [this PR ](https://github.com/microsoft/CBL-Mariner/pull/2576)
- Issues with current functionality is described best in [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/35455721/)
- Key functionality needed for viewing SELinux labels is currently missing but resolved with addition of these BRs.
Coreutils
- chpebeni@microsoft.com, 8.32-3: Add missing BuildRequires needed 
to correctly enable SELinux support.
Findutils
- - chpebeni@microsoft.com, 4.8.0-3: Add missing (Build)Requires 
needed to enable SELinux support.
**YES**
- Local build 
- Pipeline build ID 178962.
- Manual testing of pipeline generated iso
=> [1.0-dev] [backport] Adding libselinux BR to find/coreutils for SELinux support

SPECS/python-execnet/python-execnet.signatures.json, SPECS/python-execnet/python-execnet.spec, cgmanifest.json
---
Upgrade `python-execnet` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-execnet`: bump version 1.7.1 -> 1.9.0
- - `python-execnet`: lint spec
**NO**
=> python-execnet: Upgrade to 1.9.0

SPECS/python-remoto/python-remoto.signatures.json, SPECS/python-remoto/python-remoto.spec, cgmanifest.json
---
Upgrade `python-remoto` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-remoto`: version bump 1.2.0 -> 1.2.1
- `python-remoto`: fix tests by running using pytest directly
- `python-remoto`: lint spec
**NO**
- Local build passes
=> python-remoto: Upgrade to 1.2.1

SPECS/python-simplejson/python-simplejson.signatures.json, SPECS/python-simplejson/python-simplejson.spec, cgmanifest.json
---
Upgrade `python-simplejson` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-simplejson`: version bump 3.17.0 -> 3.17.6
**NO**
=> python-simplejson: Upgrade to 3.17.6

SPECS/python-atomicwrites/python-atomicwrites.signatures.json, SPECS/python-atomicwrites/python-atomicwrites.spec, cgmanifest.json
---
Upgrade `python-atomicwrites` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-atomicwrites`: version bump 1.2.1 -> 1.4.0
- `python-atomicwrites`: simplify dependencies and self-test invocations
**NO**
=> python-atomicwrites: Upgrade to 1.4.0

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/hyperv-daemons/CVE-2022-1016.patch, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/CVE-2022-1016.patch, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/CVE-2022-1016.patch, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2022-1016.patch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Applying a patch for CVE-2022-1016
- Patch CVE-2022-1016
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1016
- Pipeline build id AMD: 179192
- Pipeline build id ARM (rpms): 179108
=> kernel: Address CVE-2022-1016

SPECS/mariner-release/mariner-release.spec, toolkit/Makefile, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner Release for Preview F
=> Bump mariner 2.0 Release number for preview F Image

SPECS/python-responses/python-responses.signatures.json, SPECS/python-responses/python-responses.spec, cgmanifest.json
---
Upgrade `python-responses` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-responses`: version bump 0.10.15 -> 0.20.0
**NO**
=> python-responses: Upgrade to 0.20.0

SPECS/dietlibc/dietlibc.signatures.json, SPECS/java-cup/java-cup-bootstrap.signatures.json, SPECS/java-cup/java-cup.signatures.json, SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
---
Fixes multiple signature files. There may have been some vesteges remaining in our signature files due to upgrades/updates.
- NA
**NO**
- NA
- NA
=> SPECS: update multiple signature files

SPECS/python-prettytable/python-prettytable.signatures.json, SPECS/python-prettytable/python-prettytable.spec, cgmanifest.json
---
Upgrade `python-prettytable` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-prettytable`: version bump 0.7.2 -> 3.2.0
- `python-prettytable`: switch to tox test runner
**NO**
=> python-prettytable: Upgrade to 3.2.0

SPECS/python-pytest-xdist/python-pytest-xdist.signatures.json
---
While fixing other signature issues in #2645 we accidentally modified a correct value in `python-pytest-xdist.signatures.json`.
- Reverted signature update for `python-pytest-xdist`.
No.
- #2645
=> [main] Reverting `python-pytest-xdist` signature change.

SPECS/installkernel/installkernel, SPECS/installkernel/installkernel.signatures.json, SPECS/installkernel/installkernel.spec
---
The installkernel script is generating the /boot/mariner.cfg symlink
that required the presence of /boot, which is not guaranteed.
ln -sf "$DEST_DIR"/linux-"$KERNEL_VERSION".cfg "$DEST_DIR"/mariner.cfg
where $DEST_DIR can be /boot. When there is a dedicated /boot partition,
once grub loads, it will try to load mariner.cfg, which would be a
broken path to /boot/linux-<version>.cfg. This leads to the grub error
message:
error: not a regular file
Instead the symlink should be relative to the current directory. So
remove the reference to $DEST_DIR in the symlink generation step.
**NO**
Local build
=> installkernel: Fix mariner.cfg symlink

SPECS/calamares/calamares.spec, SPECS/calamares/round-to-full-disk-size.patch
---
fix calamares partitioning bug
- Change
- Change
- Change
**NO**
- #xxxx
=> fix calamares partitioning bug

SPECS/python-tomli/python-tomli.spec
---
Breaking a circular dependency for test builds.
- Replaced BR on `python3-pytest` with `pip3 install pytests` inside the `%check` section.
No.
- Local package build with `RUN_CHECK=y`.
=> Removing BR on `python3-pytest`.

SPECS/python-sphinx_rtd_theme/python-sphinx_rtd_theme.spec
---
Fixes ptest for Python-Sphinx_rtd_theme
- Pip install latest Sphinx package
**NO**
Local build
=> Fix python-sphinx_rtd_theme ptest

SPECS/selinux-policy/0004-Set-default-login-to-unconfined_u.patch, SPECS/selinux-policy/0010-domain-Allow-lockdown-for-all-domains.patch, SPECS/selinux-policy/0011-systemd-Drop-systemd_detect_virt_t.patch, SPECS/selinux-policy/0012-fstools-Handle-resizes-of-the-root-filesystem.patch, SPECS/selinux-policy/0013-mount-Get-the-attributes-of-all-filesystems.patch, SPECS/selinux-policy/0014-systemd-Misc-updates.patch, SPECS/selinux-policy/0015-rpm-Add-dnf-and-tdnf-labeling.patch, SPECS/selinux-policy/0016-logging-Change-to-systemd-interface-for-tmpfilesd.patch, SPECS/selinux-policy/0017-Add-cloud-init.patch, SPECS/selinux-policy/selinux-policy.spec
---
Backporting [these selinux-policy changes from main](https://github.com/microsoft/CBL-Mariner/pull/2587)
- chpebeni@microsoft.com, 2.20220106-3: Additional policy fixes for enforcing core images.
**NO**
-Local build
=> selinux-policy: Additional policy fixes for enforcing core images

SPECS/SymCrypt/SymCrypt.spec
---
Fix SymCrypt build in aarch64 by BuildRequiring clang
- Fix SymCrypt build in aarch64 by BuildRequiring clang
NO
- local build (x86)
- ARM build in mock
=> [main] [ARM] Fix SymCrypt build in aarch64 by BuildRequiring clang

toolkit/scripts/toolchain/container/Dockerfile
---
Support building Mariner 2.0 on Mariner 1.0 host build machine.
High level steps:
1) Download latest Mariner 1.0 Core ISO or Gen2 VHDX image to prepapre build environment.
a) Make sure minimum disk size available ~500 GB
b) If using Mariner 1.0 Gen2 VHDX image expand disk size to 500 GB from Hyper-V settings.
2)  sudo tdnf install -y cloud-utils-growpart openssh-server
3)  sudo systemctl enable sshd
4)  sudo systemctl start sshd
5)  sudo reboot now
6)  If using Gen2 VHDX image confirm disk size is expanded to 500 GB by running command "df -h".
7)  sudo tdnf install -y git make tar wget curl rpm rpm-build genisoimage bison gawk parted pigz python2 createrepo_c jq
8)  sudo tdnf …
=> Support building Mariner 2.0 on Mariner 1.0 host build machine

toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
A few toolchain packages have been rebuilding outside of the toolchain build process (in the package build phase). This should never happen, since the environments can differ. An analysis showed that the following packages are required for existing toolchain packages, and should therefore be added to the toolchain:
lua-rpm-macros
lua-srpm-macros
perl-Fedora-VSP
perl-generators
python3-Cython
python3-lxml
- Build missing packages in toolchain
- Update toolchain manifests
- Remove unnecessary rebuild of mariner-release, which was built twice
**YES**
- Pipeline build id: 181034
=> Add missing packages to toolchain

SPECS-EXTENDED/perl-Module-Install-AutoLicense/perl-Module-Install-AutoLicense.spec
---
A small fix for one failing Perl package in `SPECS-EXTENDED`.
- Added `BuildRequires: perl(File::Remove)` to `perl-Module-Install-AutoLicense.spec`.
No.
=> [SPECS-EXTENDED][main] Adding a missing BR in `perl-Module-Install-AutoLicense.spec`.

SPECS/python-msgpack/python-msgpack.signatures.json, SPECS/python-msgpack/python-msgpack.spec, cgmanifest.json
---
Upgrade `python-msgpack` to the latest version as part of our 2.0 package upgrade efforts.
- `python-msgpack`: version bump 0.6.2 -> 1.0.3
- `python-msgpack`: switch to tox test runner
**NO**
=> python-msgpack: Upgrade to 1.0.3

SPECS/wayland-protocols/wayland-protocols.spec, SPECS/wayland/wayland.spec
---
wayland_devel requires libffi_devel. this is porting from https://github.com/microsoft/CBL-MarinerCoreUI/pull/97.
- Change
- Change
- Change
**YES/NO**
- #xxxx
- Local build
=> [main] fix wayland_devel require libffi_devel

SPECS-EXTENDED/edk2/edk2.spec, SPECS-EXTENDED/openblas/No-Fortran-Build.patch, SPECS-EXTENDED/openblas/openblas.spec
---
fix OpenBlas and edk2 so they build from containerized env
- Change
- Change
- Change
**NO**
- #xxxx
=> fix OpenBlas and edk2 so they build from containerized env

SPECS/libdb/CVE-2019-2708.patch, SPECS/libdb/libdb.spec
---
libdb: Patch CVE-2019-2708, Nopatch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-2708
- https://nvd.nist.gov/vuln/detail/CVE-2017-3604 to 3617
- https://nvd.nist.gov/vuln/detail/CVE-2017-2981
=> libdb: Patch CVE-2019-2708, Nopatch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981

.github/workflows/validate-cg-manifest.sh, SPECS-EXTENDED/libecb/libecb.spec, SPECS/expat/expat.spec, SPECS/gnu-efi/gnu-efi.spec, SPECS/harfbuzz/harfbuzz.spec, SPECS/libisoburn/libisoburn.spec, SPECS/libnl3/libnl3.spec, SPECS/ndctl/ndctl.spec, SPECS/pigz/pigz.spec, SPECS/python-boto3/python-boto3.spec, SPECS/python-linux-procfs/python-linux-procfs.signatures.json, SPECS/python-linux-procfs/python-linux-procfs.spec, SPECS/rapidjson/rapidjson.spec, SPECS/sg3_utils/sg3_utils.spec, SPECS/sgml-common/sgml-common.spec, SPECS/tuna/tuna.signatures.json, SPECS/tuna/tuna.spec, SPECS/vnstat/vnstat.spec, SPECS/xml-commons-apis/xml-commons-apis.spec, SPECS/zchunk/zchunk.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/update_cgmanifest.py
---
Initial clean-up of the `cgmanifest.json` file. Mostly URL fixes but also additions of a few missing ones.
- Fixed/Added entries inside `cgmanifest.json`.
- Updated a few specs to point to a working URL.
- Updated the error message from the `updates_cgmanifest.py` script.
No.
- Local URL download checks.
=> [main] Initial `cgmanifest.json` clean-up.

toolkit/resources/imageconfigs/packagelists/iso-initrd-packages-arm64.json, toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
---
Devices with certain hardware (i.e., QLogic NIC) requires firmware blobs
to be available for their driver to load and function. However today our
ISO environment does not have these firmware blobs in the initrd
enfironment. The firmware blobs are supplied by our linux-firmware
package. So add the linux-firmware package into the ISO environment
package list to support a wider set of hardware.
- Add linux-firmware package to iso-initrd package list
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/38112035
Local build
=> iso-initrd: Add linux-firmware package

SPECS/squashfs-tools/squashfs-tools.signatures.json, SPECS/squashfs-tools/squashfs-tools.spec, cgmanifest.json
---
Update to version 4.5.1 to address CVE-2021-41072 and CVE-2021-40153
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-41072
- https://nvd.nist.gov/vuln/detail/CVE-2021-40153
=> squashfs-tools: Update to version 4.5.1 to address CVE-2021-41072 and CVE-2021-40153

SPECS/strongswan/strongswan.signatures.json, SPECS/strongswan/strongswan.spec, cgmanifest.json
---
strongswan: upgrade to 5.9.5 to fix CVE-2021-45079
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-45079
=> Nicogbg/fix strongswan CVE

toolkit/imageconfigs/marketplace-gen2-aarch64.json
---
Adds an ARM marketplace gen2 image. The next step is to configure the build pipelines to publish this image.
- Adds an ARM marketplace gen2 image. 
NO
- Image tested on azure, where I was able to create a VM successfully
=> [main] add config for ARM marketplace img gen2

SPECS/gd/CVE-2021-40145.patch, SPECS/gd/gd.spec
---
Backport a patch from upstream to address CVE-2021-40145
- CVE-2021-40145
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-40145
=> gd: backport patch from upstream to address CVE-2021-40145

SPECS/pciutils/pciutils.spec
---
Do not change libpci.so rights during install
- Change
- Change
- Change
**NO**
- #xxxx
=> pciutils: Do not change libpci.so rights during install

SPECS-EXTENDED/cassandra/cassandra.signatures.json
---
Cleanup the `signature` file for cassandra.
- NA
**NO**
- NA
- NA
- Pipeline build id: NA
=> cassandra: cleanup signature file

toolkit/docs/formats/imageconfig.md, toolkit/tools/imagegen/diskutils/diskutils.go
---
Adding support for swap partitions diskutils.
Continuing with assumption that all partitions are primary partitions. 
- Added case for linux-swap FsType in diskutils.go
**NO**
- Local builds and used python scripts to stress test swap partition works as intended.
=> Adding Swap Partition Support

SPECS/python-attrs/python-attrs.signatures.json, SPECS/python-attrs/python-attrs.spec, cgmanifest.json
---
Upgrade `python-attrs` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-attrs`: version bump  18.2.0 -> 21.4.0
**NO**
=> python-attrs: Upgrade to 21.4.0

SPECS/python-asn1crypto/python-asn1crypto.signatures.json, SPECS/python-asn1crypto/python-asn1crypto.spec, cgmanifest.json
---
Upgrade `python-asn1crypto` to the latest upstream version as part of our 2.0 package upgrade efforts.
- `python-asn1crypto`: version bump 0.24.0 -> 1.5.1
- `python-asn1crypto`: Add tests using tox
- Change
**NO**
=> python-asn1crypto: Upgrade to 1.5.1

SPECS/python-daemon/python-daemon.signatures.json, SPECS/python-daemon/python-daemon.spec, cgmanifest.json
---
upgraded python-daemon to 2.3.0 for 2.0
**NO**
=> [main] upgraded python-daemon to 2.3.0

SPECS/python-lxml/python-lxml.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The python-lxml package claims to build a debuginfo rpm, but we don't build one in the toolchain. The scheduler sees this mismatch and triggers an unintended rebuild.
- Add the `debug_package %{nil}` global to python-lxml.spec
**YES**
- Both local and pipeline builds
=> Remove python-lxml debuginfo packge

SPECS/libdb/libdb.spec
---
fix missed to increment release nb in previous libdb PR
- Change
- Change
- Change
**NO**
- #xxxx
=> fix missed to increment release nb in previous libdb PR

SPECS/python-lxml/python-lxml.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/pkggen.mk, toolkit/scripts/srpm_pack.mk, toolkit/scripts/toolchain.mk, toolkit/tools/depsearch/depsearch.go, toolkit/tools/graphPreprocessor/graphPreprocessor.go, toolkit/tools/graphpkgfetcher/graphpkgfetcher.go, toolkit/tools/imagepkgfetcher/imagepkgfetcher.go, toolkit/tools/internal/packagerepo/repocloner/repocloner.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/packagerepo/repoutils/repoutils.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/buildlist.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/scheduler/schedulerutils/printresults.go
---
Merge of tooling update staging branch with the following PRs:
#2765 
#2676 
#2675 
#2674 
#2673
**YES**
=> Toolchain tooling staging branch

SPECS-EXTENDED/python-requests_ntlm/python-requests_ntlm.spec
---
Disable check section to unblock extended ptest pipeline
- Disable check section
**NO**
- NA
- NA
=> python-requests_ntlm: disable check section to unblock ptest pipeline

SPECS-EXTENDED/nbd/nbd.spec
---
Disable check section for `nbd` to unblock extended ptest pipeline.
- Disable check section
**NO**
- NA
- NA
=> nbd: disable check section to unblock ptest pipeline

SPECS/kernel/CVE-2022-0995.nopatch, SPECS/kernel/CVE-2022-1055.nopatch, SPECS/kernel/CVE-2022-27666.nopatch, SPECS/kernel/kernel.spec
---
[main] kernel: fix CVE-2022-0995, 2022-1055, 2022-27666
- kernel: fix CVE-2022-0995, 2022-1055, 2022-27666: all nopatch
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-0995
- https://nvd.nist.gov/vuln/detail/CVE-2022-1055
- https://nvd.nist.gov/vuln/detail/CVE-2022-27666
- No build required as only adding nopatch files
=> [main] kernel: fix CVE-2022-0995, 2022-1055, 2022-27666

SPECS-SIGNED/kernel-signed/kernel-signed.spec
---
Revert the workaround added to the kernel-signed spec from #2032. This is no longer required after the changes from #2720 
- Revert kernel-signed workaround
**NO**
=> Revert: kernel-signed: workaround errant .build-id file 

SPECS/java-cup/java-cup-bootstrap.signatures.json, SPECS/java-cup/java-cup.signatures.json
---
Fix signatures files for `java-cup`
- NA
**NO**
- NA
- NA
- Pipeline build id: Local `expand-specs` only
=> java-cup: cleanup signature files

SPECS/python-pip/CVE-2021-3572.patch, SPECS/python-pip/python-pip.spec
---
Backport patch for CVE-2021-3572 into python-pip 19.2
- Backport patch for CVE-2021-3572 into python-pip 19.2
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3572
- Full local package build
- Verified with test repo https://github.com/frenzymadness/CVE-2021-3572
=> [1.0] python-pip backport patch for CVE-2021-3572

toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh
---
Add gnupg2 chkconfig newt lang packages to toolchain resources manifests
- Change
Add gnupg2 chkconfig netw lang packages to toolchain resources manifests
**YES**
- #xxxx
=> Add gnupg2 chkconfig newt lang packages to toolchain resources manifests

toolkit/imageconfigs/marketplace-gen2-aarch64.json
---
Adds an ARM marketplace gen2 image. The next step is to configure the build pipelines to publish this image.
- Adds an ARM marketplace gen2 image.
NO
- Image tested on azure, where I was able to create a VM successfully
=> Generate marketplace gen2 ARM image

SPECS/libtiff/libtiff.spec
---
%autosetup was trying to call patch with a nopatch. The PatchX: nopatch is no longer needed in the specfile, so remove it. 
- remove reference to nopatch in spec file
NO
- Local build
=> [main] [CVEs] Fix libtiff build break

SPECS/kernel/CVE-2021-44879.nopatch, SPECS/kernel/CVE-2022-0955.nopatch, SPECS/kernel/CVE-2022-1055.nopatch, SPECS/kernel/CVE-2022-27666.nopatch, SPECS/kernel/CVE-2022-44879.nopatch, SPECS/kernel/kernel.spec
---
Addressing  CVE-2022-1055, CVE-2022-27666, CVE-2022-0955, CVE-2021-44879 with nopatches.
- Addressing  CVE-2022-1055, CVE-2022-27666, CVE-2022-0955, CVE-2021-44879 with nopatches.
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-1055
- https://nvd.nist.gov/vuln/detail/CVE-2022-27666
- https://nvd.nist.gov/vuln/detail/CVE-2022-0955
- https://nvd.nist.gov/vuln/detail/CVE-2021-44879
- Local Build
=> kernel: Address CVE-2022-1055, CVE-2022-27666, CVE-2022-0955, CVE-2021-44879

SPECS/rsync/CVE-2020-14387.patch, SPECS/rsync/rsync.spec
---
rsync: Address CVE-2020-14387
The upstream patch for CVE-2020-14387 was added after 3.2.3 and will be
included in the upcoming 3.2.4 release. For now, backport the patch to
our current 3.2.3 version.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/38981578
Local build
=> rsync: Address CVE-2020-14387

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
The `graphpkgfetcher` tool downloads dependencies for resolution into the chroot's `/outputrpms`, which in Docker builds is not mounted to anything, so the packages get discarded before `graphpkgfetcher` attempts a resolution when 2+ packages satisfy the same dependency. This is a temporary workaround, the correct fix will be provided in the next few weeks, as it is a lot more involved and potentially build-breaking before we get it right.
- Made `graphpkgfetcher` download packages to the mounted directory for Docker builds.
No.
- Pipeline build id: 185775
=> [main] Build break workaround.

SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch, SPECS/pango/pango.signatures.json, SPECS/pango/pango.spec, cgmanifest.json
---
Bump version to 1.45.5 to address CVE-2019-1010238
- Bump version to 1.45.5 to address CVE-2019-1010238
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2019-1010238
- Pipeline build id: Local Build with RUN_CHECK=y. All tests pass!
=> pango: bump version to 1.45.5 to address CVE-2019-1010238

SPECS/logrotate/logrotate.spec
---
Currently the logrotate spec has ProtectClock, ProtectHostname, and ProtectKernelLogs systemd hardening options disabled because they're incompatible with our systemd in 1.0. When we update systemd for 2.0 we need to revisit this spec and reenable them. 
- Reenable ProtectClock=true|ProtectHostname=true|ProtectKernelLogs=true flags for logrotate service
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/34764350?src=WorkItemMention&src-action=artifact_link 
- Locally built, installed in test VM, ran a test command `logrotate -d /etc/logrotate.conf`
=> [main] Reenable systemd hardening flags in logrotate

SPECS/rubygem-bigdecimal/rubygem-bigdecimal.spec, SPECS/rubygem-concurrent-ruby/rubygem-concurrent-ruby.spec, SPECS/rubygem-io-console/rubygem-io-console.spec, SPECS/rubygem-json/rubygem-json.spec, SPECS/rubygem-minitest/rubygem-minitest.spec, SPECS/rubygem-mocha/rubygem-mocha.spec, SPECS/rubygem-openssl/rubygem-openssl.spec, SPECS/rubygem-power_assert/rubygem-power_assert.spec, SPECS/rubygem-psych/rubygem-psych.spec, SPECS/rubygem-rdoc/rubygem-rdoc.spec, SPECS/rubygem-test-unit/rubygem-test-unit.spec
---
Add provides in rubygems to fix build failure
- Add provides in rubygems to fix build failure
**NO**
- Build break in pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=186115&view=results
- Just added provides
=> Add provides in rubygems to fix build failure

SPECS/logrotate/logrotate.spec
---
Back out change from https://github.com/microsoft/CBL-Mariner/pull/2792 
- Back out change for GA
NO
=> [main] back out change in #2792

SPECS/busybox/CVE-2022-28391.patch, SPECS/busybox/busybox.spec
---
Patch CVE-2022-28391 in busybox
- Patch CVE-2022-28391 in busybox
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-28391
=> [1.0] busybox patch CVE-2022-28391

SPECS/cpio/CVE-2021-38185.patch, SPECS/cpio/cpio.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2021-38185 in cpio package by adding patch file
- Add patch to cpio.spec
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-38185
=> Patch cpio to fix CVE-2021-38185

SPECS/numpy/numpy.signatures.json, SPECS/numpy/numpy.spec, cgmanifest.json
---
Upgrade `numpy` to the latest upstream version as part of our 2.0 package upgrade efforts. 
- `numpy`: Upgrade to latest upstream version
- `numpy`: Consolidate python requirements
- `numpy`: Add specific requirements on gcc-c++, gcc-gfortran
- `numpy`: Fix test invocation so we actually catch failures
- `numpy`: Remove f2py3 binary from python3-numpy package (doubly packaged)
**NO**
=> numpy: Upgrade to 1.22.3

SPECS/lua/CVE-2020-15889.nopatch, SPECS/lua/CVE-2020-24342.nopatch, SPECS/lua/CVE-2021-43519.nopatch, SPECS/lua/CVE-2022-28805.patch, SPECS/lua/lua.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2022-28805 in lua
- Patch CVE-2022-28805 in lua
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-28805
- Local Toolchain build
=> [1.0] Patch lua CVE-2022-28805

SPECS-EXTENDED/graphite2/graphite2.spec
---
- Add an explicit BR on `pip` to enable ptest
**NO**
- NA
- NA
=> graphite2: add an explicit BR on `pip` to enable ptest

SPECS-EXTENDED/javapackages-tools-meta/javapackages-tools-meta.signatures.json
---
Cleanup `signature` file.
- NA
**NO**
- NA
- NA
- Local `expand-specs`
=> javapackages-tools-meata: cleanup signature file

SPECS-EXTENDED/convmv/convmv.spec
---
- Add an explicit BR on `perl(File::Find)` to enable ptest
**NO**
- NA
- NA
=> convmv: add an explicit BR on `perl(File::Find)` to enable ptest

SPECS/binutils/CVE-2021-45078.patch, SPECS/binutils/binutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add patch to resolve binutils CVE-2021-45078
- Add patch to binutils
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-45078
- Local build
=> Patch binutils to fix CVE-2021-45078

SPECS-EXTENDED/glm/glm.spec
---
- skip `test-core_func_integer` to enable ptest
**NO**
- NA
- NA
=> glm: skip `test-core_func_integer` to enable ptest

SPECS-EXTENDED/perl-B-Debug/perl-B-Debug.spec
---
Fix ptest bulid. All tests pass!
- Add an explicit BR on `perl(deprecate)` to enable ptest
**NO**
- NA
- NA
=> perl-B-Debug: add an explicit BR on `perl(deprecate)` to enable ptest

SPECS-EXTENDED/nbdkit/nbdkit.spec
---
A non-zero exit from the `%check` section aborts the build. Avoid non-zero exits from the `%check` section.
- Avoid non-zero exit from `%check` section
**NO**
- NA
- NA
=> nbdkit: avoid non-zero exit from `%check` section

SPECS-EXTENDED/python-xmltodict/python-xmltodict.spec
---
- Add an explicit BR on `pip` to enable ptest
**NO**
- NA
- NA
=> python-xmltodict: add an explicit BR on `pip` to enable ptest

SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.signatures.json, SPECS/rubygem-yajl-ruby/rubygem-yajl-ruby.spec, cgmanifest.json
---
Update yajl-ruby to 1.4.2 to fix CVE-2022-24795
- Update yajl-ruby to 1.4.2 to fix CVE-2022-24795
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-24795
- Individual package build
=> [1.0] Update rubygem-yajl-ruby to 1.4.2 for CVE-2022-24795

SPECS/avahi/avahi-libevent-pc-fix.patch, SPECS/avahi/avahi.spec
---
Add upstream patch to `avahi` package to fix an issue where an improper pkgconfig requirement was being generated by RPM.
- `avahi`: Add patch from https://github.com/lathiat/avahi/pull/265
- `avahi`: No dash roll, package not built/published
**NO**
- Local build passes
=> avahi: Add patch to fix pkgconfig requires generation on libevent

SPECS/openssl/CVE-2021-4160.nopatch, SPECS/openssl/openssl.spec
---
CVE-2021-4160 - Only affects the MIPS32 and MIPS64 platforms
- Nopatch openssl CVE-2021-4160
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-4160
No code changes
=> openssl: Nopatching CVE-2021-4160

SPECS/sqlite/CVE-2021-36690.patch, SPECS/sqlite/sqlite.spec, toolkit/.gitignore, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/container/Dockerfile, toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh, toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
Fix an issue with the SQLite Expert extension when a column
has no collating sequence
Upstream patch: https://sqlite.org/src/info/b1e0c22ec981cf5f
Forum post: https://sqlite.org/forum/forumpost/78165fa250
This is a port of the upstream commit to the SQLite Expert extension
which addresses CVE-2021-36690.
We do not ship the extensions separately so instead we need to directly
patch the offending code which is found in shell.c.
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/38981755
- https://nvd.nist.gov/vuln/detail/CVE-2021-36690
Local build
=> sqlite: Address CVE-2021-36690

SPECS/audit/audit.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Various security certifications expect that audit logs be placed in a separate partition. If a symlink is used (from `/var/log/audit` to `/var/opt/audit/log`) rpm will refuse to install the package if a mountpoint is present at /var/log/audit (since there is already a something there).
We should just store our audit logs in the standard location instead of using a symlink.
- Remove the symlink from `/var/log/audit` to `/var/opt/audit/log`
- Give ownership of '/var/log/audit` directory to the audit package.
**YES**
- Local build in progress
=> Remove symlink for audit log location

SPECS/graphviz/CVE-2020-18032.patch, SPECS/graphviz/graphviz.spec
---
Add graphviz patch for CVE-2020-18032
- Add graphviz patch for CVE-2020-18032
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-18032
=> Add graphviz patch for CVE-2020-18032

SPECS/rubygem-rake/rubygem-rake.spec
---
fix rubygem-rake failing files
- Remove files that are not building
- Remove extra files that we don't want to add
**NO**
- Local build
=> [main] fix rubygem-rake failing files

SPECS-EXTENDED/perl-App-FatPacker/perl-App-FatPacker.spec
=> perl-App-FatPacker: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-Devel-CheckLib/perl-Devel-CheckLib.spec
=> perl-Devel-CheckLib: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/python-webencodings/python-webencodings.spec
---
- Drop BR on pytest & pip install latest version
- Use py.test instead of py.test-3
**NO**
- NA
- NA
=> python-webencodings: use `py.test` instead of `py.test-3` to enable ptest

SPECS-EXTENDED/perl-ExtUtils-Config/perl-ExtUtils-Config.spec
=> perl-ExtUtils-Config: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-Error/perl-Error.spec
=> perl-Error: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/rust-packaging/rust-packaging.spec
---
- Drop BR on pytest & pip install deps
- Use `py.test` instead of `py.test-3.9` to enable ptest
**NO**
- NA
- NA
=> rust-packaging: drop BR on pytest & pip install deps to enable ptest

SPECS/openssh/openssh.spec
---
By default, ssh and sshd are configured to allow using weak hashing
algorithms like MD5 and SHA1. They are also configured to use weak
encryption ciphers such as 3DES and CBC mode ciphers.
Configure ssh and sshd to use strong MAC and encryption ciphers by
default.
Strong MACs are hmac-sha2 (hmac-sha2-256, hmac-sha2-512)
Strong ciphers are aes128-ctr, aes192-ctr, aes256-ctr.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/39214466
- https://microsoft.visualstudio.com/OS/_workitems/edit/39214473
- https://microsoft.visualstudio.com/OS/_workitems/edit/39214481
Local build
=> openssh: Use strong MACs and ciphers for ssh/sshd

SPECS-EXTENDED/puppet/puppet.spec, SPECS-EXTENDED/rubygem-asciidoctor/rubygem-asciidoctor.spec
---
Updating to Ruby 3.1.2 caused a change in the default installation paths. Two Ruby packages (`puppet` and `rubygem-asciidoctor`) were using hard-coded paths instead of standard Ruby macros and thus failed after the update. This PR addresses this issue.
- Updated installation paths for Ruby packages.
No.
=> [main] Fixing installation paths with new version of Ruby.

SPECS-EXTENDED/perl-File-Find-Object/perl-File-Find-Object.spec
=> perl-File-Find-Object: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-File-Remove/perl-File-Remove.spec
=> perl-File-Remove: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-Package-Stash-XS/perl-Package-Stash-XS.spec
---
- add an explicit BR on `perl(blib)` to enable ptest
**NO**
- NA
- NA
=> perl-Package-Stash-XS: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-Package-Stash/perl-Package-Stash.spec
=> perl-Package-Stash: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/python-winrm/python-winrm.spec
---
- Drop BR on pytest and pip install deps to enable ptest
**NO**
- NA
- NA
=> python-winrm: drop BR on pytest and pip install deps to enable ptest

SPECS-EXTENDED/perl-Class-ISA/perl-Class-ISA.spec
---
- Add an explicit BR on `perl(deprecate)` to enable ptest
**NO**
- NA
- NA
=> perl-Class-ISA: add an explicit BR on `perl(deprecate)` to enable ptest

SPECS-EXTENDED/perl-Test-Portability-Files/perl-Test-Portability-Files.spec
=> perl-Test-Portability-Files: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/perl-Test-TrailingSpace/perl-Test-TrailingSpace.spec
=> perl-Test-TrailingSpace: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/python-click/python-click.spec
---
- Drop BR on pytest & pip install latest deps to enable ptest
**NO**
- NA
- NA
=> python-click: drop BR on pytest & pip install latest deps to enable ptest

SPECS-EXTENDED/python-dbus-python-client-gen/python-dbus-python-client-gen.spec
---
- Use `py.test` instead of `py.test-3` to enable ptest
**NO**
- NA
- NA
=> python-dbus-python-client: use `py.test` instead of `py.test-3` to enable ptest

SPECS-EXTENDED/perl-Test-Warn/perl-Test-Warn.spec
=> perl-Test-Warn: add an explicit BR on `perl(blib)` to enable ptest

SPECS-EXTENDED/pyxattr/pyxattr.spec
---
- Drop BR on `pytest` & pip install latest deps to enable ptest
**NO**
- NA
- NA
=> pyxattr: drop BR on `pytest` & pip install latest deps to enable ptest

SPECS/nginx/CVE-2021-3618.patch, SPECS/nginx/nginx.spec
---
Address CVE-2021-3618. Fix is present in non-stable/newer versions of nginx but we've previously made the choice to stick to the stable release so a patch is being applied. 
- Address CVE-2021-3618
**NO**
- Local Build
=> nginx: Address CVE-2021-3618

SPECS/subversion/subversion.spec
---
What does the PR accomplish, why was it needed? 
subversion was packaging libsvn_swig_perl in both the subversion and subversion-perl packages, causing a dnf transaction failure when installed together. Fixes that by excluding libsvn_swig_perl from the main subversion package. 
- exclude libsvn_swig_perl from the main subversion package
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/39258133/
- Local build
=> [main] Fix duplicate packaging of libsvn_swig_perl.so

SPECS-EXTENDED/rpm-mpi-hooks/rpm-mpi-hooks.spec, SPECS-EXTENDED/sblim-cmpi-syslog/sblim-cmpi-syslog.spec, SPECS-EXTENDED/servletapi4/servletapi4.spec, SPECS-EXTENDED/servletapi5/servletapi5.spec, SPECS-EXTENDED/setuptool/setuptool.spec, SPECS-EXTENDED/sgpio/sgpio.spec, SPECS-EXTENDED/splix/splix.spec, SPECS-EXTENDED/ttmkfdir/ttmkfdir.spec, SPECS-EXTENDED/virt-who/virt-who.spec, SPECS-EXTENDED/wsmancli/wsmancli.spec, SPECS-EXTENDED/xhtml1-dtds/LICENSE.PTR, SPECS-EXTENDED/xhtml1-dtds/xhtml1-dtds.signatures.json, SPECS-EXTENDED/xhtml1-dtds/xhtml1-dtds.spec, SPECS-EXTENDED/xmldb-api/xmldb-api.spec, SPECS-EXTENDED/xrestop/xrestop.spec, cgmanifest.json
---
Adding entries to cgmanifest for some packages that do not have them yet, from SPECS-EXTENDED.
- Add entries to cgmanifest for packages rpm-mpi-hooks, sblim-cmpi-syslog, servletapi4, servletapi5, setuptool, sgpio, splix, ttmkfdir, virt-who, wsmancli, xhtml1-dtds, xmldb-api, xrestop
**NO**
- N/A
=> Update cgmanifest with some SPECS-EXTENDED entries

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec, SPECS/grub2/CVE-2021-3981.patch, SPECS/grub2/grub2.spec
---
Grub2 CVE-2021-3981 fix.
- Change
Fix CVE-2021-3981
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-3981
=> Grub2 CVE-2021-3981 fix

cgmanifest.json
---
It looks like we missed reverting the `cgmanifest.json` changes while doing a revert for #2747 in https://github.com/microsoft/CBL-Mariner/commit/8386b66a2c71f68083e2949fe35acaa6c79da6f1. Addressing this here.
- Updated `cgmanifest.json` entry for `python-daemon`.
No.
- Local validation for `python-daemon.spec` with the GitHub check.
=> [main] Fixing 'python-daemon' registration in 'cgmanifest.json'.

SPECS/kernel/CVE-2022-0500.nopatch, SPECS/kernel/CVE-2022-0995.nopatch, SPECS/kernel/kernel.spec
---
no patch CVE-2022-0500
fixing CVE number on CVE-2022-0995
- no patch CVE-2022-0500
- fixing CVE number on CVE-2022-0995
**NO**
- no code changes
=> kernel: addressing CVE-2022-0500, CVE-2022-0995

toolkit/imageconfigs/core-legacy-unattended-hyperv.json
---
core-legacy-unattended-hyperv.json includes hardcoded password which causes failure in credential scanning. Remove the "Users" field from core-legacy-unattended-hyperv.json since the users can perform cloud-init provisioning to log into the Mariner OS after unattended installation completes.
- Change
- Change
- Change
NO
- #xxxx
=> [main] Fix credscan error caused by unattended installer image config

SPECS-EXTENDED/perl-FreezeThaw/perl-FreezeThaw.spec
---
- Add an explict BR on `perl(dumpvar.pl)` to enable ptest.
**NO**
- NA
- NA
=> perl-FreezeThaw: add an explict BR on `perl(dumpvar.pl)` to enable ptest

SPECS-EXTENDED/perl-Locale-Codes/perl-Locale-Codes.spec
---
- Add an explicit BR on `perl(deprecate)` to enable ptest.
**NO**
- NA
- NA
=> perl-Locale-Codes: add an explicit BR on `perl(deprecate)` to enable ptest

SPECS-EXTENDED/python-dbus-client-gen/python-dbus-client-gen.spec
---
- Drop BR on pytest & pip install latest deps to enable ptest.
**NO**
- NA
- NA
=> python-dbus-client-gen: drop BR on pytest & pip install latest deps to enable ptest

SPECS-EXTENDED/nodejs-nodemon/nodejs-nodemon.spec, SPECS-EXTENDED/objectweb-anttask/objectweb-anttask.spec, SPECS-EXTENDED/ocaml-xml-light/LICENSE.PTR, SPECS-EXTENDED/ocaml-xml-light/ocaml-xml-light.signatures.json, SPECS-EXTENDED/ocaml-xml-light/ocaml-xml-light.spec, SPECS-EXTENDED/perl-Class-Data-Inheritable/perl-Class-Data-Inheritable.spec, SPECS-EXTENDED/perl-XML-SAX/perl-XML-SAX.spec, SPECS-EXTENDED/plexus-component-api/plexus-component-api.spec, SPECS-EXTENDED/psutils/psutils.spec, SPECS-EXTENDED/publicsuffix/publicsuffix.spec, SPECS-EXTENDED/python-curio/python-curio.spec, SPECS-EXTENDED/python-d2to1/python-d2to1.spec, SPECS-EXTENDED/python-hwdata/python-hwdata.spec, SPECS-EXTENDED/python-sniffio/python-sniffio.spec, SPECS-EXTENDED/python-trio/python-trio.spec, cgmanifest.json
---
Updates to cgmanifest.json with missing sources for extended packages.
Add entries to cgmanifest for packages
- nodejs-nodemon
- objectweb-anttask
- ocaml-xml-light
- perl-Class-Data-Inheritable
- perl-XML-SAX
- plexus-component-api
- psutils
- publicsuffix
- python-curio
- python-d2to1
- python-hwdata
- python-sniffio
- python-trio
**No**
N/A, no build changes.
=> [main] Adding missing cgmanifest.json entries

SPECS/crash/crash.signatures.json, SPECS/crash/crash.spec, cgmanifest.json
---
Update crash utility to 8.0.1
- Update crash utility to 8.0.1
**NO**
- Local build
=> Update crash to 8.0.1

SPECS-EXTENDED/python-uritemplate/python-uritemplate.spec
---
- Enable tests by removing build gates
- Drop BR on pytest & pip install latest deps to enable pytest
**NO**
- NA
- NA
=> python-uritemplate: pip install latest deps & fix check section to enable ptest

SPECS-EXTENDED/python-curio/python-curio.spec
---
- Drop BR on pytest & pip install latest deps
- Use py.test instead of py.test-3 to enable ptest
**NO**
- NA
- NA
=> python-curio: build with tests & pip install latest deps to enable ptest

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Now that msopenjdk-11 RPM has been published to the production folder on PMC, we should use this location instead of "preview"
- Change script to download msopenjdk rpm from prod folder instead of preview
**YES**
- Pipeline build id: 188680
=> Download msopenjdk from prod folder on PMC

SPECS/perl-YAML/perl-YAML.signatures.json, SPECS/perl-YAML/perl-YAML.spec, cgmanifest.json
---
Update perl-YAML to 1.30
- Update perl-YAML to 1.30
**NO**
=> Update perl-YAML to 1.30

SPECS/perl-Net-SSLeay/perl-Net-SSLeay.signatures.json, SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec, cgmanifest.json
---
Updates perl-Net-SSLeay to 1.92
- Update perl-Net-SSLeay to 1.92
**NO**
- Local build
=> Update perl-Net-SSLeay to 1.92

SPECS/perl-Test-Warnings/perl-Test-Warnings.signatures.json, SPECS/perl-Test-Warnings/perl-Test-Warnings.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update perl-Test-Warnings package to 0.031
- Update perl-Test-Warnings package to 0.031
**YES**
- Local toolchain and package build.
=> Update perl-Test-Warnings to 0.031

SPECS/perl-Text-Template/perl-Text-Template.signatures.json, SPECS/perl-Text-Template/perl-Text-Template.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update perl-Text-Template to 1.60
- Update perl-Text-Template to 1.60
**YES**
- Local build
=> Update perl-Text-Template to 1.60

SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.signatures.json, SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.spec, cgmanifest.json
---
Update perl-Module-ScanDeps to 1.31
- Update perl-Module-ScanDeps to 1.31
**NO**
- Local build
=> Update perl-Module-ScanDeps to 1.31

SPECS/perl-Module-Build/perl-Module-Build.signatures.json, SPECS/perl-Module-Build/perl-Module-Build.spec, cgmanifest.json
---
Update perl-Module-Build to 0.4231
- Update perl-Module-Build to 0.4231
**NO**
- Local build
=> Update perl-Module-Build to 0.4231

SPECS/perl-libintl-perl/perl-libintl-perl.signatures.json, SPECS/perl-libintl-perl/perl-libintl-perl.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update perl-libintl-perl to 1.32
- Update perl-libintl-perl to 1.32
**YES**
- Local build
=> Update perl-libintl-perl to 1.32

SPECS/perl-List-MoreUtils/perl-List-MoreUtils.signatures.json, SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec, cgmanifest.json
---
Update perl-list-moreutils to 0.430
- Update perl-list-moreutils to 0.430
**NO**
- Local build
=> Update `perl-list-moreutils` to 0.430

SPECS/perl-JSON-XS/perl-JSON-XS.signatures.json, SPECS/perl-JSON-XS/perl-JSON-XS.spec, cgmanifest.json
---
Update perl-JSON-XS to 4.03
- Update perl-JSON-XS to 4.03
**NO**
- Local build
=> Update perl-json-xs to 4.03

SPECS/perl-JSON/perl-JSON.signatures.json, SPECS/perl-JSON/perl-JSON.spec, cgmanifest.json
---
Update perl-JSON to 4.05
- Update perl-JSON to 4.05
**NO**
- Local build
=> Update perl-JSON to 4.05

SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.signatures.json, SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.spec, cgmanifest.json
---
Update perl-IO-Socket-SSL to 2.074
- Update perl-IO-Socket-SSL to 2.074
**NO**
- Local build
=> Update perl-IO-Socket-SSL to 2.074

SPECS/perl-File-Which/perl-File-Which.signatures.json, SPECS/perl-File-Which/perl-File-Which.spec, cgmanifest.json
---
Update perl-File-Which to 1.27
- Update perl-File-Which to 1.27
**NO**
- Local build
=> Update perl-File-Which to 1.27

SPECS/perl-Exporter-Tiny/perl-Exporter-Tiny.signatures.json, SPECS/perl-Exporter-Tiny/perl-Exporter-Tiny.spec, cgmanifest.json
---
Update perl-Exporter-Tiny to 1.0020002
- Update perl-Exporter-Tiny to 1.0020002
**NO**
- Local build
=> Update perl-Exporter-Tiny to 1.002002

SPECS/perl-DBI/perl-DBI.signatures.json, SPECS/perl-DBI/perl-DBI.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update perl-DBI to 1.643
- Update perl-DBI to 1.643
**YES**
- Local build
=> Update perl-DBI to 1.643

SPECS/perl-common-sense/perl-common-sense.signatures.json, SPECS/perl-common-sense/perl-common-sense.spec, cgmanifest.json
---
Update perl-common-sense to 3.75
- Update perl-common-sense to 3.75
**NO**
- Local build
=> Update perl-common-sense to 3.75

SPECS/perl-File-HomeDir/perl-File-HomeDir.signatures.json, SPECS/perl-File-HomeDir/perl-File-HomeDir.spec, cgmanifest.json
---
Update perl-File-HomeDir to 1.006
- Update perl-File-HomeDir to 1.006
**NO**
- Local build
=> Update perl-File-HomeDir to 1.006

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Now that msopenjdk-11 RPM has been published to the production folder on PMC, we should use this location instead of "preview"
- Change script to download msopenjdk-11 from prod folder
**YES**
- Pipeline build id: 188713
=> [2.0] Download msopenjdk from prod folder on PMC 

SPECS/ninja-build/ninja-build.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
`gtest` is only in the toolchain because it is listed as a build requirement of `ninja-build`. However, this is incorrect- `gtest` is only a check-time requirement of `ninja-build`. `ninja-build` builds just fine in non-check scenarios without `gtest` present. In the interest of toolchain minimization, we can safely remove `gtest` from the toolchain.
- `ninja-build`: Change `gtest` to a check-time build requirement
- toolchain: Remove `gtest`
**YES**
- Pipeline build id: 1872968
=> toolchain: Remove gtest

SPECS/perl-App-cpanminus/perl-App-cpanminus.signatures.json, SPECS/perl-App-cpanminus/perl-App-cpanminus.spec, cgmanifest.json
---
Update perl-App-cpanminus to 1.7045
- Update perl-App-cpanminus to 1.7045
**NO**
- Local build
=> Update perl-App-cpanminus to 1.7045

SPECS/perl-Canary-Stability/perl-Canary-Stability.signatures.json, SPECS/perl-Canary-Stability/perl-Canary-Stability.spec, cgmanifest.json
---
Update perl-Canary-Stability to version 2013
- Update perl-Canary-Stability to version 2013
**NO**
- Local build
=> Update perl-Canary-Stability to version 2013

SPECS/perl-CGI/perl-CGI.signatures.json, SPECS/perl-CGI/perl-CGI.spec, cgmanifest.json
---
Update perl-CGI to 4.54
- Update perl-CGI to 4.54
**NO**
- Local build
=> Update perl-CGI to 4.54

SPECS/perl-Archive-Zip/perl-Archive-Zip.signatures.json, SPECS/perl-Archive-Zip/perl-Archive-Zip.spec, cgmanifest.json
---
Update perl-Archive-Zip to 1.68
- Update perl-Archive-Zip to 1.68
**NO**
- Local build
=> Update perl-Archive-Zip to 1.68

SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.8.0.spec, SPECS/coredns/coredns-1.8.4.spec, SPECS/coredns/coredns-1.8.6.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.5.0.spec, SPECS/etcd/etcd-3.5.1.spec, SPECS/flannel/flannel.spec, SPECS/glide/glide.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/CVE-2022-24675.patch, SPECS/golang/golang-1.16.spec, SPECS/helm/helm.spec, SPECS/libnvidia-container/libnvidia-container.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/node-problem-detector/node-problem-detector.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, SPECS/telegraf/telegraf.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Golang CVE fix for CVE-2022-24675
- Change
Golang CVE fix for CVE-2022-24675
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-24675
=> Golang CVE fix for CVE-2022-24675

SPECS-EXTENDED/python-hs-dbus-signature/python-hs-dbus-signature.spec
---
- Drop BR on `pytest` & `hypothesis` to enable ptest
**NO**
- NA
- NA
=> python-hs-dbus-signature: drop BR on `pytest` & `hypothesis` to enable ptest

SPECS-EXTENDED/python-flake8/python-flake8.spec
---
- Drop BR on `pytest` and add an explict BR pip to enable ptest
**NO**
- NA
- NA
=> python-flake8: pip install latest deps & fix check section to enable ptest

SPECS-EXTENDED/python-jwcrypto/python-jwcrypto.spec
---
- Add BR on `pip` to enable ptest
**NO**
- NA
- NA
=> python-jwcrypto: add BR on `pip` to enable ptest

SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
---
- Drop BR on pytest & pip install latest deps to enable ptest
**NO**
- NA
- NA
=> python-into-dbus-python: pip install latest deps to enable ptest

SPECS-EXTENDED/python-justbytes/python-justbytes.spec, cgmanifest.json
---
- Drop BR on pytest & pip install latest deps
- Use `py.test` instead of `py.test-3` to enable ptest
**NO**
- NA
- NA
=> python-justbytes: use `py.test` instead of `py.test-3` to enable ptest

SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.8.0.spec, SPECS/coredns/coredns-1.8.4.spec, SPECS/coredns/coredns-1.8.6.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.5.0.spec, SPECS/etcd/etcd-3.5.1.spec, SPECS/flannel/flannel.spec, SPECS/glide/glide.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/CVE-2022-24675.patch, SPECS/golang/golang-1.16.spec, SPECS/helm/helm.spec, SPECS/libnvidia-container/libnvidia-container.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/node-problem-detector/node-problem-detector.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, SPECS/shadow-utils/shadow-utils.spec, SPECS/telegraf/telegraf.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
merge 1.0 dev into 1.0
- Change
- Change
- Change
**YES**
- #xxxx
=> merge 1.0 dev into 1.0

SPECS-EXTENDED/python-uamqp/python-uamqp.spec
---
- Drop BR on `pytest`, `six` & pip install deps to enable ptest
**NO**
- NA
- NA
=> python-uamqp: drop BR on pytest, six & pip install deps to enable ptest

SPECS-EXTENDED/python-sniffio/python-sniffio.spec
---
- Use `py.test` instead of `py.test-3` to enable ptest
**NO**
- NA
- NA
=> python-sniffio: use `py.test` instead of `py.test-3` to enable ptest

SPECS-EXTENDED/python-mccabe/python-mccabe.spec
---
- Drop BR on pytest & pip install latest deps to enable ptest
**NO**
- NA
- NA
=> python-mccabe: drop BR on pytest & pip install latest deps to enable ptest

SPECS-EXTENDED/cassandra/cassandra.spec
---
Fix cassandra package install and uninstall issues.
Include fqltool to Cassandra package
Cleanup build cache.
Autoreq set to no because it is pulling for runtime dependencies libkstat, libnm which are not required and also complaining about libnsl.so.1 which is present in the image.
- Change
Fix cassandra package install and uninstall issues.
**NO**
- #xxxx
=> Fix cassandra package install and uninstall issues

toolkit/imageconfigs/marketplace-gen1.json, toolkit/imageconfigs/marketplace-gen2-aarch64.json, toolkit/imageconfigs/marketplace-gen2.json, toolkit/imageconfigs/packagelists/core-tools-packages.json, toolkit/imageconfigs/packagelists/marketplace-tools-packages.json
---
Remove vim to include by default in Mariner marketplace images.
It can be included customer images if required or users can install at runtime using tdnf/dnf. 
- Change
Remove vim to include by default in marketplace mariner images
**NO**
- #xxxx
=> Remove vim to include by default in marketplace mariner images

SPECS-EXTENDED/python-requests-kerberos/python-requests-kerberos.spec
---
- Use `py.test` instead of `py.test-3` to enable ptest
**NO**
- NA
- NA
=> python-requests-kerberos: use `py.test` instead of `py.test-3` to enable ptest

SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
---
Fixed ansible CVE-2021-3620 with upgrade to 2.9.27
- Fixed ansible CVE-2021-3620 with upgrade to 2.9.27
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3620
=> Fixed ansible CVE-2021-3620 with upgrade to 2.9.27

SPECS/systemd/systemd.spec, SPECS/util-linux/util-linux.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Change systemd.spec to depend on util-linux-libs
---
Split libraries from util-linux-devel into util-linux-libs.
Add necessary runtime dependencies on util-linux-libs.
util-linux-devel
systemd
YES
- #2946
N/A
=> Create util-linux-libs RPM package with libraries

SPECS/core-packages/core-packages.spec
---
Add gzip and sed to base container image
- Change
Add gzip and sed to base container image
**NO**
- #xxxx
=> Add gzip and sed to base container image

SPECS/mariadb/mariadb.spec
---
`mariadb` and `mariadb-connector-c` share some common shipped libraries, which causes file conflicts between the two packages. Following in Fedora's footsteps, we should let `mariadb-connector-c` provide the common files and remove the common files from `mariadb` prior to final RPM packaging.
- `mariadb`: Remove files that are shared with `mariadb-connector-c` and add appropriate requirements on that package
**NO**
- Pipeline buddy build, local install test
=> mariadb: Fix mariadb-connector-c conflicts

SPECS/qemu/qemu.spec
---
We do not support qemu x86_64 sub packages on aarch64 currently, so we need to remove all the associated files. 6.2.0 added a new file (multiboot_dma.bin) which also needs to be removed.
- Remove multiboot_dma.bin during aarch64 builds
**NO**
Build in progress
=> qemu: Remove multiboot_dma.bin from x86_64 files during aarch64 builds

SPECS/terraform/CVE-2018-9057.nopatch
---
This change only adds a nopatch file to clear a CVE against terraform which is not applicable/present in the Mariner version.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2018-9057
=> No-Patch CVE-2018-9057

toolkit/scripts/toolchain/container/Dockerfile
---
Changes toolchain Dockerfile to use Microsoft mirror of Ubuntu to remove warning from build pipelines.
- Changed Ubuntu source to Microsoft mirror.
**YES**
- Pipeline build id: raw toolchain build
=> Altered Dockerfile for toolchain build to avoid build warning

SPECS/logrotate/logrotate.spec
---
Readd systemd hardening flags to logrotate. This was originally merged in https://github.com/microsoft/CBL-Mariner/pull/2792 but was taken out to preserve stability for the 2.0 release. 
- Reenable ProtectClock=true|ProtectHostname=true|ProtectKernelLogs=true flags for logrotate service
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/34764350?src=WorkItemMention&src-action=artifact_link
- Locally built, installed in test VM, ran a test command logrotate -d /etc/logrotate.conf
=> [main] Re-Reenable systemd hardening flags in logrotate

SPECS/qemu-kvm/CVE-2021-20257.patch, SPECS/qemu-kvm/CVE-2021-3638.patch, SPECS/qemu-kvm/CVE-2021-3748.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
- Patch CVE-2021-20257, CVE-2021-3638, CVE-2021-3748
- Nopatch CVE-2022-1050, CVE-2021-20295
- Patch CVE-2021-20257, CVE-2021-3638, CVE-2021-3748
- Nopatch CVE-2022-1050, CVE-2021-20295
**NO**
=> Fixed several CVEs in qemu-kvm

SPECS/gdb/gdb.signatures.json, SPECS/gdb/gdb.spec, cgmanifest.json
---
Upgrade gdb to 11.2
Upgrade gdb to 11.2
**YES/NO**
- #xxxx
=> upgrade gdb to 11.2

toolkit/scripts/download-packages.sh
---
Update download-packages.sh script to support downloading packages from CBL-Mariner 2.0 repos.
The 2.0 repo directory structure is different in that the "rpm" subdirectory is not present, and "debuginfo" packages are in separate repos.
- Change download-packages.sh to handle 1.0 and 2.0 repo URLs
**NO**
- Pipeline build id: 192600
./scripts/download-packages.sh -d "base update" -t "x86_64" -u https://packages.microsoft.com/cbl-mariner/1.0/prod/ -z
./scripts/download-packages.sh -d "base" -t "x86_64" -u https://packages.microsoft.com/cbl-mariner/2.0/prod/ -z
=> Update download-packages.sh script to support 2.0 repo

SPECS/freetype/CVE-2022-27404.patch, SPECS/freetype/freetype.spec
---
Apply upstream fix to freetype
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-27404
Local build
=> freetype: address CVE-2022-27404

SPECS/kernel/CVE-2022-1015.nopatch, SPECS/kernel/CVE-2022-1048.nopatch, SPECS/kernel/CVE-2022-1195.nopatch, SPECS/kernel/CVE-2022-1353.nopatch, SPECS/kernel/CVE-2022-29968.nopatch, SPECS/kernel/kernel.spec
---
Nopatch kernel CVE-2022-1048, CVE-2022-1195, CVE-2022-1353, CVE-2022-29968, CVE-2022-1015
- Nopatch kernel CVE-2022-1048, CVE-2022-1195, CVE-2022-1353, CVE-2022-29968, CVE-2022-1015
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1048
- https://nvd.nist.gov/vuln/detail/CVE-2022-1195
- https://nvd.nist.gov/vuln/detail/CVE-2022-1353
- https://nvd.nist.gov/vuln/detail/CVE-2022-29968
- https://nvd.nist.gov/vuln/detail/CVE-2022-1015
- N/A
=> [main] [CVEs] Nopatch kernel CVEs

toolkit/resources/assets/grub2/grub.cfg, toolkit/resources/assets/isomaker/iso_root_static_files/boot/grub2/grub.cfg
---
grub.cfg: disable unprivileged bpfs in kernel cmdline
Set sysctl.kernel.unprivileged_bpf_disabled=1 in kernel cmdline to set
the sysctl setting prior to init process. This sysctl will disable
unprivileged access to bpf entirely and this setting cannot change until
the next reboot.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/38553356
Local build and test
=> grub.cfg: disable unprivileged bpfs in kernel cmdline

SPECS/fluent-bit/fluent-bit.spec
---
This PR compiles fluent-bit with the -DFLB_JEMALLOC=on
N/A
NO
This change is expected to reduce memory fragmentation and improve performance.
pipeline build
=> compile fluent bit with jemalloc

toolkit/tools/go.mod
---
Bump go verison in `go.mod` file from `1.13` -> `1.17`.
Command: `make go-tidy-all`
- Bump go version in `go.mod` from `1.13 -> 1.17`
**YES**
- #3013
- NA
- Local Build
Closes: #3013
=> toolkit: gomod: bump go version `1.13` -> `1.17`

SPECS/filesystem/filesystem.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Signed-off-by: Brendan Kerrigan <bkerrigan@microsoft.com>
---
Many distributions have input handling in terminals bound to Ctrl+LeftArrow (move backward a word) and Ctrl+RightArrow (move forward a word). This change adds that as a default within CBL-Mariner.
- Add binding for forward-word jump to /etc/inputrc
- Add binding for backward-word jump to /etc/inputrc
NO
Manually made change in CBL-Mariner container, spawn a new shell (to reload the /etc/inputrc), and used the new key bindings. Previously using those key bindings would result in a 5C or 5D being printed in the console.
=> filesystem: add input handling for {forward,backward}-word

toolkit/imageconfigs/core-efi-selinux.json
---
- Adding core-efi-selinux image config for BVT testing
- Adding core-efi-selinux image config for BVT testing
**NO**
=> Adding core-efi-selinux.json image config

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> Bump Mariner 1.0 Release for May 2022 Update

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
vim: Update to 8.2.4925 to address CVEs
Addresses CVE-2022-1381, CVE-2022-1420, CVE-2022-1616, CVE-2022-1619,
CVE-2022-1620, CVE-2022-1621, CVE-2022-1629
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1381
- https://nvd.nist.gov/vuln/detail/CVE-2022-1420
- https://nvd.nist.gov/vuln/detail/CVE-2022-1616
- https://nvd.nist.gov/vuln/detail/CVE-2022-1619
- https://nvd.nist.gov/vuln/detail/CVE-2022-1620
- https://nvd.nist.gov/vuln/detail/CVE-2022-1621
- https://nvd.nist.gov/vuln/detail/CVE-2022-1629
- Local build
=> vim: Update to 8.2.4925 to address CVE-2022-1381, CVE-2022-1420, CVE-2022-1616, CVE-2022-1619, CVE-2022-1620, CVE-2022-1621, CVE-2022-1629

SPECS/mariner-release/mariner-release.spec
Bump release for May 2022 Update
=> Bump Mariner 2.0 Release for May 2022 Update

SPECS/qemu/CVE-2022-26353.patch, SPECS/qemu/qemu.spec
---
qemu: add patch for CVE-2022-26353
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-26353
Local build
=> qemu: add patch for CVE-2022-26353

SPECS/haproxy/CVE-2022-0711.nopatch, SPECS/haproxy/haproxy.spec
---
haproxy: Add nopatch for CVE-2022-0711
Already patched in haproxy stable release 2.4.13
Upstream: https://github.com/haproxy/haproxy/commit/bfb15ab34ead85f64cd6da0e9fb418c9cd14cee8
Stable release notes: http://git.haproxy.org/?p=haproxy-2.4.git;a=log;h=refs/tags/v2.4.13
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0711
Local build
=> haproxy: Add nopatch for CVE-2022-0711

SPECS/kernel/CVE-2022-29968.nopatch, SPECS/kernel/kernel.spec
---
Address CVE-2022-29968
- Address CVE-2022-29968
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-29968
- local build
=> kernel: Add nopatch for CVE-2022-29968

SPECS-EXTENDED/libwpe/libwpe.signatures.json, SPECS-EXTENDED/libwpe/libwpe.spec, SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.signatures.json, SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.spec, cgmanifest.json
---
Update libwpe and wpebackend-fdo to 1.12.0
N/A
NO
N/A
local build
=> update libwpe and wpebackend fdo

SPECS-EXTENDED/wpebackend-fdo/wpebackend-fdo.signatures.json
---
Updates the signature matching the wpebackend-fdo-1.12.0 source
N/A
NO
N/A
local build
=> Fix signature for wpebackend-fdo

SPECS/zsh/0001-Skipping-test-if-ran-as-superuser.patch, SPECS/zsh/zsh.signatures.json, SPECS/zsh/zsh.spec, cgmanifest.json
---
Update zsh to v5.9 to address CVE-2021-45444
- Update zsh to v5.9 to address CVE-2021-45444
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-45444
- Local build
=> Update zsh to v5.9 to address CVE-2021-45444

SPECS/libxslt/CVE-2021-30560.patch, SPECS/libxslt/libxslt.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address libxslt CVE-2021-30560
- Applying patch for CVE-2021-30560.
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-30560
- Pipeline build id: 196788
=> Address libxslt CVE-2021-30560

SPECS/rsyslog/CVE-2022-24903.patch, SPECS/rsyslog/rsyslog.spec
---
Address rsyslog CVE-2022-24903
- Add Patch for CVE-2022-24903
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-24903
- Pipeline build id: 196798
=> Address rsyslog CVE-2022-24903

SPECS/iotop/iotop.spec
---
fix iotop python3-curses dependency
- Change
- Change
- Change
**NO**
- #xxxx
=> fix iotop python3-curses dependency

SPECS/curl/curl.signatures.json, SPECS/curl/curl.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade curl version to 7.83.0
To get the fix for this issue https://github.com/curl/curl/issues/8559
- Change
Upgrade curl version to 7.83.0
**YES**
- #xxxx
- Pipeline build id: LocalBuild
=> Upgrade curl version to 7.83.0

SPECS/selinux-policy/0021-lvm-Updates-for-multipath-LVM.patch, SPECS/selinux-policy/0030-container-allow-containers-to-manipulate-own-fds.patch, SPECS/selinux-policy/0031-devices-Add-type-for-infiniband-devices.patch, SPECS/selinux-policy/0032-storage-Add-fc-for-dev-ng-n-devices.patch, SPECS/selinux-policy/0033-files-Add-prerequisite-access-for-files_mounton_non_.patch, SPECS/selinux-policy/0034-files-Make-etc_runtime_t-a-config-file.patch, SPECS/selinux-policy/0035-systemd-Fixes-for-coredumps-in-containers.patch, SPECS/selinux-policy/0036-container-Allow-container-engines-to-connect-to-http.patch, SPECS/selinux-policy/0037-container-Getattr-generic-device-nodes.patch, SPECS/selinux-policy/0038-application-Allow-apps-to-use-init-fds.patch, SPECS/selinux-policy/selinux-policy.spec
---
Add additional rules found from testing.
- Fix previous multipath LVM changes.
- Add types for devices.
- Cherry pick upstream commit for container fds.
- Allow container engines to connect to http cache ports.
- Allow container engines to stat() generic (device_t) devices.
**NO**
- Local buid
=> selinux-policy: Fixes from baremetal testing.

SPECS/pcre2/pcre2.signatures.json, SPECS/pcre2/pcre2.spec, cgmanifest.json
---
Update pcre2 to v10.40 to address CVE-2022-1586, CVE-2022-1587 
10.39 --> 10.40 is a small bugfix update
https://github.com/PCRE2Project/pcre2/blob/pcre2-10.40/ChangeLog
- Update pcre2 to v10.40
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1586
- https://nvd.nist.gov/vuln/detail/CVE-2022-1587
- Local build
=> Update pcre2 to v10.40 to address CVE-2022-1586, CVE-2022-1587

SPECS/fping/fping.spec
fping code uses getprotobyname() library call
which rely on /etc/protocols as protocols database.
https://linux.die.net/man/3/getprotobyname
/etc/protocols is provided by iana-etc pkg.
Signed-off-by: Eric Desrochers <edesrochers@microsoft.com>
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Add iana-etc as runtime dep for fping

SPECS/pcre2/CVE-2022-1586.patch, SPECS/pcre2/CVE-2022-1587.patch, SPECS/pcre2/pcre2.spec, cgmanifest.json
---
Apply patches for pcre2 CVEs CVE-2022-1586, CVE-2022-1587
- Apply patches for pcre2 CVEs CVE-2022-1586, CVE-2022-1587
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1586
- https://nvd.nist.gov/vuln/detail/CVE-2022-1587
=> Apply patches for pcre2 CVEs CVE-2022-1586, CVE-2022-1587

SPECS/cert-manager/cert-manager.spec
---
In the 2.0 development cycle, the cert-manager spec file was disabled using an "ExclusiveArch" tag for an architecture we do not support. Removing this tag now to enable building the package. Not bumping the release number since this package is not yet published.
- Remove "exclusivearch: mips" from cert-manager.spec
**NO**
- Local build
- AMD64 buddybuild: 198241
- ARM64 buddybuild: 198261
=> Restore cert-manager package

SPECS/openldap/CVE-2022-29155.patch, SPECS/openldap/openldap.spec
---
openldap: fix CVE-2022-29155
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-29155
=> openldap: fix CVE-2022-29155

SPECS/ca-certificates/ca-certificates.spec, SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec, SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We made `ca-certificates-microsoft` and `ca-certificates-mozilla` an alias for `ca-certificates` but we missed doing a similar thing for `prebuilt-ca-certificates`. Fixing this here. A separate update for `main` is on its way.
- Add `Provides` for `%{name}-microsoft` and `%{name}-mozilla` to `prebuilt-ca-certificates`.
No.
- #3094 
=> `prebuilt-ca-certificates`: adding `Provides` for `*-microsoft` and `*-mozilla`.

SPECS-EXTENDED/python-mutagen/python-mutagen.spec
---
- Drop BR on pytest & pip install latests deps to enable ptest
**NO**
- NA
- NA
=> python-mutagen: drop BR on pytest & pip install latests deps to enable ptest

SPECS/moby-runc/moby-runc.signatures.json, SPECS/moby-runc/moby-runc.spec, cgmanifest.json
---
Upgrade to 1.1.2 to fix CVE-2022-29162
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-29162
=> moby-runc: Upgrade to 1.1.2 to fix CVE-2022-29162

SPECS-EXTENDED/edk2/edk2.spec, SPECS-EXTENDED/perl-Module-Install-Repository/perl-Module-Install-Repository.signatures.json, SPECS/ostree/ostree.spec
Fix some build regressions in the extended folder
=> Cherry Pick build fixes to Extended

SPECS/hyperv-daemons/hyperv-daemons.signatures.json
---
Fix signature of hypervkvpd.service
- Fix signature of hypervkvpd.service for https://github.com/microsoft/CBL-Mariner/pull/3096/files
NO
- None
=> Fix signature of hypervkvpd.service

.gitignore, toolkit/scripts/download_spec_sources.sh
---
Slight modification to where the `download_spec_sources.sh` script places the extracted sources, so they don't clutter the repository.
- Moved the sources download directory outside the repo.
No.
- Local script run
=> Updating `.gitignore` to ignore default sources download directory.

SPECS/td-agent/td-agent.patch, SPECS/td-agent/td-agent.spec
---
Fixes build break introduced by the upgrading of ruby from 2.6.9 to 2.6.10. 
- `td-agent`: Change required ruby version, update patch for new ruby version
**NO**
- Local build
=> td-agent: Bump ruby version requirement to 2.6.10

SPECS/subversion/subversion.signatures.json, SPECS/subversion/subversion.spec, cgmanifest.json
---
Fixing CVE-2021-28544 by updating `subversion` to version 1.14.2.
- Updated `subversion` to 1.14.2.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-28544
=> `subversion`: updating to 1.14.2 to fix CVE-2021-28544.

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump the Mariner Release version for Mariner 1.0 June 2022 Update
=> Bump Mariner Release version for Jun 2022 update

SPECS/httpd/CVE-2009-1890.nopatch
=> Nopatching CVE-2009-1890 as this is not in Apache version 2.4.53

SPECS/cracklib/cracklib.spec, SPECS/packer/packer.spec, SPECS/terraform/terraform.signatures.json, SPECS/terraform/terraform.spec, cgmanifest.json
---
Upgrade terraform version to 1.2.2.
Update date correctly in change log for cracklib and packer SPECs.
- Change
Upgrade terraform version to 1.2.2
**NO**
- #xxxx
=> Upgrade terraform version to 1.2.2

SPECS/bind/CVE-2019-6470.nopatch, SPECS/bind/bind-9.10-dist-native-pkcs11.patch, SPECS/bind/bind-9.14-config-pkcs11.patch, SPECS/bind/bind.signatures.json, SPECS/bind/bind.spec, cgmanifest.json
---
Fixing a CVE in `bind`.
- Updated `bind` to version 9.16.29.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-25219
=> `bind`: updating to 9.16.29 to fix CVE-2021-25219.

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json, SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, SPECS/SymCrypt/SymCrypt.signatures.json, SPECS/SymCrypt/SymCrypt.spec, cgmanifest.json
---
Improves performance of TLS handshakes by updating flow for FIPS self-tests in SCOSSL + SymCrypt. Fixes some minor bugs in SCOSSL.
- Update SymCrypt and SCOSSL SPEC files to point to latest tags
**NO**
- Local build to verify that Mariner build still working as expected. Brought updated files into CBL-MarinerDemo and built image containing the updated packages successfully.
=> Update SymCrypt and SCOSSL SPEC files to latest

toolkit/docs/how_it_works/5_misc.md
---
Add distroless RPM manifest format to the toolkit docs, to ease integration.
- Change Doc update
**NO**
=> add distroless RPM manifest format to toolchain doc

SPECS/libarchive/libarchive.signatures.json, SPECS/libarchive/libarchive.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump version `3.6.0 -> 3.6.1` to address CVE-2022-26280
- Bump version to 3.6.1
**NO**
- https://github.com/libarchive/libarchive/issues/1672
- https://nvd.nist.gov/vuln/detail/CVE-2022-26280
=> libarchive: bump version to 3.6.1 to address CVE-2022-26280

toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh
---
When updating `util-linux`, PR #3132 introduced an incorrect source filename in `toolchain_build_in_chroot.sh`. This PR fixes the filename to match what is downloaded in the raw toolchain build.
- `toolchain_build_in_chroot.sh`: Fix source filename for `util-linux`
**YES**
- Local test
=> Fix util-linux source unpacking in raw toolchain

SPECS/logrotate/logrotate.signatures.json, SPECS/logrotate/logrotate.spec, cgmanifest.json
---
Bump version to 3.20.1 to address CVE-2022-1348
- Bump version to `3.18.1 -> 3.20.1` to address CVE-2022-1348      
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-1348
=> logrotate: bump version to 3.20.1 to address CVE-2022-1348

SPECS/libxml2/libxml2.signatures.json, SPECS/libxml2/libxml2.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE 2022-29824
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Upgrade libxml2 to 2.9.14 to fix CVE-2022-29824

SPECS/qemu/CVE-2021-4206.patch, SPECS/qemu/qemu.spec
---
Introduce patch from upstream to address CVE-2021-4206.
- Address CVE-2021-4206 
**/NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-4206
=> qemu: address CVE-2021-4206

SPECS/redis/redis.signatures.json, SPECS/redis/redis.spec, cgmanifest.json
---
Bump version to 6.2.6 to address CVE-2022-24736
- Bump version to 6.2.6 to address CVE-2022-24736.
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-24736
=> redis: bump version to 6.2.7 to address CVE-2022-24736

SPECS/telegraf/telegraf.signatures.json, SPECS/telegraf/telegraf.spec, cgmanifest.json
---
Bump version to 1.23.0
- Bump version to 1.23.0
**NO**
Depends on `go1.18.x` :
- #3163
- NA
=> telegraf: bump version to 1.23.0

README.md
---
Looks like we lost the markdown link in the readme (probably copy/paste didn't preserve it).
Restore the link.
- Restore  `[Toolkit Documentation](./toolkit/README.md)` link
**NO**
=> Restore link to documentation in readme

SPECS/kernel/CVE-2022-1966.nopatch, SPECS/kernel/CVE-2022-1998.nopatch, SPECS/kernel/CVE-2022-32296.nopatch
---
kernel: nopatch CVE-2022-1966, 2022-1998, 2022-32296
- kernel: nopatch CVE-2022-1966, 2022-1998, 2022-32296
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1966
- https://nvd.nist.gov/vuln/detail/CVE-2022-1998
- https://nvd.nist.gov/vuln/detail/CVE-2022-32296
- Only adding nopatch, no build required
=> kernel: nopatch CVE-2022-1966, 2022-1998, 2022-32296

SPECS/audit/audit.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Somewhere in the past, we added a requirement on `audit` to `audit-libs`. This shouldn't be necessary and increases the base image size. So, let's make the necessary changes to remove this dependency.
- `audit`: Remove requirement on `audit` from `audit-libs`
- `audit`: Move `/etc/libaudit.conf` to `audit-libs`, since consumers of audit libraries will expect it to be present.
**YES**
- Pipeline build, BVTs pass
- Packages update successfully in container
=> audit: Remove requirement on base package from libs subpackage

SPECS/git/git.spec
---
added less to runtime Requires
-  added less to runtime Requires
NO
- [#39650685](https://microsoft.visualstudio.com/OS/_queries/query/96d827c1-529f-4801-88ad-b73e59379e98)
- local build
- tested the new rpm on azure vm of Mariner 2.0
=> git: added less to runtime Requires

SPECS/libcap-ng/libcap-ng.spec, SPECS/util-linux/util-linux.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
add buildrequires libcap-ng-devel in order to generate setpriv binary
https://microsoft.visualstudio.com/OS/_workitems/edit/38909093
-  add buildrequires libcap-ng-devel for setpriv
**YES**
- local build of toolchain and package w/ check 
- pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=205156&view=results
=> util-linux: add buildrequires libcap-ng-devel

.github/CODEOWNERS
---
We want to keep raw toolchain changes to a minimum for 2.0. As part of that, we want all changes to the raw toolchain to undergo admin approval.
- `CODEOWNERS`: Add microsoft/cbl-mariner-admins as the owner of `toolkit/scripts/toolchain/container/*`
**NO**
- GitHub says the CODEOWNERS file is valid after change
=> CODEOWNERS: Require admin approval for raw toolchain changes

SPECS/emacs/CVE-2007-6109.nopatch, SPECS/emacs/emacs.spec
---
Nopatch CVE-2007-6109
- Nopatch CVE-2007-6109
- Cosmetic cleaup of `%changelog`
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2007-6109
- Local Build
=> emacs: nopatch CVE-2007-6109

SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec, cgmanifest.json
---
Update moby-containerd to 1.6.6 to fix CVE-2022-31030
- Update moby-containerd to 1.6.6 to fix CVE-2022-31030
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-31030
- Local build in the Mariner build system
- Directly ran rpm-build on the srpm using a local VM with networking disabled to ensure build didn't fetch additional sources at runtime.
- Ran %check section during rpm-build on the local VM and observed all tests passing.
=> `moby-containerd`: upgrade to version 1.6.6 to fix CVE-2022-31030

SPECS-EXTENDED/powertop/0001-ncurses.patch, SPECS-EXTENDED/powertop/powertop.spec
---
Added patch to fix compliation with ncurses 6.3.
version: n 2.12-3
=> Added patch to fix compilation with ncurses 6.3__2.13-3

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner Release for Mariner 1.0 June Update 2
=> Bump Mariner Release for Mariner 1.0 June Update 2

SPECS/mariner-release/mariner-release.spec
=> Bump Mariner Release version for Mariner 2.0 June Update 2

SPECS/usrsctp/CVE-2019-20503.nopatch
---
Nopatch CVE-2019-20503 because its already fixed in version 0.9.5.0
- Nopatch CVE-2019-20503 because its already fixed in version 0.9.5.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2019-20503
- No package changes, only a nopatch.
=> `usrsctp`: nopatch CVE-2019-20503

toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
The toolchain scripts first attempt to download sources from $SOURCE_URL/toolchain, and then try the upstream servers defined in toolchain-remote-wget-list. With this change the sources are downloaded directly from $SOURCE_URL.
- Change toolchain to download from $SOURCE_URL instead of $SOURCE_URL/toolchain
**YES**
=> [2.0] Use core sources folder for toolchain

SPECS/gd/gd.spec
---
Fix %check failure in gd
- Change
- Change
- Change
**NO**
- #xxxx
=> gd: fix test

SPECS/mcpp/mcpp.spec, SPECS/mcpp/patch.mcpp.2.7.2
---
mcpp already has a patch that addresses this CVE, but it isn't marked. Add inline comments to the patch file that the scanner can read.
- Update mcpps's `patch.mcpp.2.7.2` with comments mentioning the fix for CVE-2019-14274.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2019-14274
- Local build, no functional changes made to package
=> Mark mcpp CVE-2019-14274 as fixed

SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.spec, SPECS/python-sphinxcontrib-htmlhelp/test_htmlhelp_path_fix.patch, SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.spec, SPECS/python-sphinxcontrib-jsmath/test_jsmath_path_fix.patch, SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.spec, SPECS/python-sphinxcontrib-qthelp/test_qthelp_path_fix.patch
---
Fixing ptests inside 3 of our `python-sphinxcontrib*` packages.
**NOTE**: The CGmanifest check is failing because the tools doesn't support all of our build macros at the moment. The binary URLs are actually present and correct.
- Added upstream patches to `*htmlhelp` and `*jsmath` packages.
- Used previous packages to fix `*qthelp`.
No.
- Local package builds with `RUN_CHECK=y`.
=> `python-sphinxcontrib-*`: fixing 3 failing ptests.

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade Vim version to 8.2.5154 to fix CVEs: CVE-2022-2124, CVE-2022-2125, CVE-2022-2126 and CVE-2022-2129
- Change
Upgrade to 8.2.5154 to fix CVEs: 2022-2124, 2022-2125, 2022-2126 and 2022-2129
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2124
- https://nvd.nist.gov/vuln/detail/CVE-2022-2125
- https://nvd.nist.gov/vuln/detail/CVE-2022-2126
- https://nvd.nist.gov/vuln/detail/CVE-2022-2129
=> Upgrade Vim version to 8.2.5154 to fix CVEs

SPECS/logrotate/logrotate.signatures.json, SPECS/logrotate/logrotate.spec, cgmanifest.json
---
Upgrade logrotate to 3.20.0 to fix CVE-2022-1348
- Change
Upgrade logrotate to 3.20.0 to fix CVE-2022-1348
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-1348
=> Upgrade logrotate to 3.20.0 to fix CVE-2022-1348

SPECS/kernel/CVE-2022-1652.nopatch, SPECS/kernel/CVE-2022-32981.nopatch
---
nopatch CVE-2022-1652, CVE-2022-32981
- nopatch CVE-2022-1652, CVE-2022-32981
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1652
- https://nvd.nist.gov/vuln/detail/CVE-2022-32981
=> kernel: address CVEs CVE-2022-1652, CVE-2022-32981

SPECS/kernel-rt/kernel-rt.spec
---
Builds and packages cpupower and turbostat programs
Builds and packages cpupower and turbostat programs
kernel-rt-tools
NO
=> build and include cpupower and turbostat in kernel-rt-tools package

SPECS/qemu/qemu.spec
---
Ship the missing `pxe*rom` & `efi*rom` files for `x86_64` arch
- Ship missing `pxe*rom` & `efi*rom` files.
**NO**
- #3293
- NA
Closes: #3293
=> qemu: ship missing `efi*rom` & `pxe*rom` romfiles

toolkit/docs/building/prerequisites-ubuntu.md
---
It does not seem like Ubuntu comes with git installed. Adding git to the installation requirements.
- Added git to the Ubuntu pre-req doc file.
**NO**
=> Adding git to the requirements doc install instructions

SPECS/autoconf213/autoconf213.spec, cgmanifest.json
---
See https://github.com/microsoft/CBL-Mariner/issues/3161
- Replace `autoconf213` FTP source with HTTPS source
**NO**
- #3161
=> Switch to HTTPS source for `autoconf213`

cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Our OpenJDK folks have a new release of msopenjdk-11 ready for our consumption. This PR updates the package to version 11.0.15+10-LTS-1.
- toolchain: Upgrade version of msopenjdk-11 pulled from Microsoft repo
**YES**
- Validated with an incremental toolchain build
=> msopenjdk-11: Upgrade to 11.0.15+10-LTS-1

SPECS/python3/python3.spec
---
Pip3 fails to run with bad bad interpreter error.
Pip3 reference to /usr/bin/python instead of /usr/bin/python3.7.
Update pip3 with /usr/bin/python3.7 to use correct version of python.
- Change
Fix bad interpreter error when run pip3
**NO**
- #xxxx
=> Fix bad interpreter error when run pip3

SPECS/qemu-kvm/CVE-2021-4206.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Patches CVE-2021-4206 in QEMU.
- Added patch for CVE-2021-4206 to qemu-kvm.
**NO**
=> Added patch for CVE-2021-4206 to qemu-kvm

cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Revert #3323. New `msopenjdk-11` RPM has a new requirement that we don't have:
`nothing provides dejavu-sans-fonts needed by msopenjdk-11-11.0.15+10_LTS-1.x86_64`
- Revert #3323 
**YES**
- N/A
=> Revert "msopenjdk-11: Upgrade to 11.0.15+10-LTS-1 (#3323)"

SPECS/redis/disable_defrag_test.patch, SPECS/redis/redis.spec
---
Disabled spuriously failing test in redis due to build failure. This resolution is fine [according to the redis developers](https://github.com/redis/redis/issues/8265#issuecomment-756764695), as the test has differing behaviors on systems with different page size configurations.
- Added patch to disable spuriously failing test.
**NO**
=> disabled spuriously failing defrag test in redis

SPECS/mariner-release/mariner-release.spec
=> Bump Mariner 2.0 Release for July 2022 Update

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade to 8.2.5172 to fix CVEs: 2022-2207, 2022-2208, 2022-2210, 2022-2206
Upgrade to 8.2.5172 to fix CVEs: 2022-2207, 2022-2208, 2022-2210, 2022-2206
**NO**
=> Updated vim to 8.2.5172 to fix CVEs

SPECS/selinux-policy/0040-usermanage-Add-sysctl-access-for-groupadd-to-get-num.patch, SPECS/selinux-policy/0041-systemd-systemd-cgroups-reads-kernel.cap_last_cap-sy.patch, SPECS/selinux-policy/0042-kernel-hv_utils-shutdown-on-systemd-systems.patch, SPECS/selinux-policy/selinux-policy.spec
---
Minor SELinux policy fixes for groupadd, systemd-cgroups, and hv_utils. Issues found with BVTs.
- Add kernel.* sysctl access to groupadd.
- Add kernel.* sysctl access to systemd-cgroups.
- Add poweroff.target access to kernel/hv_utils.
**NO**
- Local build
=> selinux-policy: Minor fixes for groupadd, systemd-cgroups, hv_utils.

SPECS/cloud-init/cloud-init.spec
---
Enable ptest for `cloud-init`. All tests pass!
- pip install `test-requirments.txt` to enable ptest
**NO**
- NA
- NA
=> cloud-init: pip install `test-requirements.txt` to enable ptest

SPECS/python-attrs/fix-mypy-tests.patch, SPECS/python-attrs/python-attrs.spec
---
Package tests for `python-attrs` are currently failing due to a change in upstream mypy. We don't have mypy in Mariner, but better to add the upstream fix patch in case someone ends up using it.
- Add upstream patch to python-attrs to fix mypy tests
**NO**
- Local check build passes
=> Add upstream patch to python-attrs to fix mypy tests

SPECS/unbound/unbound.spec
---
In unbound, add libevent-devel as a build requires and configure build to use libevent. This results in unbound-devel having the needed headers for libreswan.
- Add BR libevent devel and build with libevent
**NO**
- local build
=> unbound: build with libevent to fix libreswan

SPECS/libsafec/libsafec-3.7.1-issue119.patch, SPECS/libsafec/libsafec.spec
---
Back apply fix for https://github.com/rurban/safeclib/issues/119
No
-  https://github.com/rurban/safeclib/issues/119
- Local build, install, and smoke
=> Libsafec issue119

SPECS/opensc/opensc.spec
---
#3360 fixed the check builds of `opensc`, but broke non-check builds due to the removal of `libcmocka-devel` from non-check builds. This fixes the configuration step of `opensc` to not build unit tests during non-check builds.
- `opensc`: Disable unit tests in non-check builds
**NO**
- Local check, non-check builds
=> Fix opensc non-check build by disabling unit tests

SPECS/mcpp/CVE-2019-14274.nopatch
---
My understanding was the CVE tools were able to read the contents of a patch file to scan for CVE-###-### comments. This does not appear to be functioning/implemented. Adding a .nopatch to explicitly mark this as fixed.
- Add CVE-2019-14274.nopatch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2019-14274
- No testing, observation only
=> Add nopatch for mcpp CVE-2019-14274

SPECS/git/git.signatures.json, SPECS/git/git.spec, cgmanifest.json
---
Upgrade git to 2.33.4 to address CVE-2022-29187
- Upgrade git to 2.33.4
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-29187
- Local build
=> Upgrade git to 2.33.4 to address CVE-2022-29187

SPECS/selinux-policy/0043-Container-Minor-fixes-from-interactive-container-use.patch, SPECS/selinux-policy/selinux-policy.spec
---
Fixes for interactive container use.
- Fixes for interactive container use.
**NO**
- Local build
=> selinux-policy: Fixes for interactive container use.

SPECS-EXTENDED/argparse-manpage/argparse-manpage.spec
---
- pip install latest deps to enable ptest
**NO**
- NA
- NA
=> argparse-manpage: pip install latest deps to enable ptest

SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.spec, cgmanifest.json
---
- Drop BR on pytest & pip install latest deps to enable ptest
**NO**
- NA
- NA
=> python-pytest-subtests: drop BR on pytest & pip install latest deps to enable ptest

SPECS-EXTENDED/python-requests-toolbelt/python-requests-toolbelt.spec
---
Fix ptest build. All tests pass
- Drop BR on pytest and pip install latest deps to enable ptest
- Cosmetic fixes for changelog
**NO**
- NA
- NA
=> python-requests-toolbelt: pip install latest deps to enable ptest

SPECS-EXTENDED/python-whoosh/python-whoosh.signatures.json, SPECS-EXTENDED/python-whoosh/python-whoosh.spec, cgmanifest.json
---
- python-whoosh: pip install `wheel` in %check section to enable ptest
- python-whoosh: switch to github tarball instead of pypi
**NO**
- NA
- NA
=> python-whoosh: pip install `wheel` in %check section to enable ptest

SPECS/blobfuse/blobfuse.signatures.json, SPECS/blobfuse/blobfuse.spec, cgmanifest.json
---
Blobfuse version updated to 1.4.4 in Mariner 2.0
- Blobfuse version updated to 1.4.4 in Mariner 2.0
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/40449706
- Local build ongoing
- Containerized build succeeded
=> [2.0] Update blobfuse version to 1.4.4

SPECS/mariner-release/mariner-release.spec
---
A `mariner-release` bump for the second July update.
- Updated `mariner-release.spec`
No.
- N/A - simple `Release` change.
=> Updating `mariner-release` version for July update 2.

SPECS-EXTENDED/perl-File-Find-Object-Rule/perl-File-Find-Object-Rule.spec
---
- Add an explicit BR on `perl(blib)` to enable ptest.
**NO**
- NA
- NA
=> perl-File-Find-Object-Rule: add BR on `perl(blib)` to enable ptest

SPECS/sysbench/enable-python3.patch, SPECS/sysbench/sysbench.spec
---
Fix to enable the check section for sysbench package
- patch added to sysbench to allow for the use of python3 when running %check section tests
NO
- Fixes bug #40639901
- local build
=> fixed ptest issue with sysbench.

SPECS/perl-Crypt-SSLeay/perl-Crypt-SSLeay.spec
---
- Add BR on `perl(Test::More)` & `perl(Bytes::Random::Secure)` to enable ptest
**NO**
- NA
- NA
=> perl-Crypt-SSLeay: add BR on `perl(Test::More)` & `perl(Bytes::Random::Secure)` to enable ptest

SPECS-EXTENDED/perl-Object-Deadly/perl-Object-Deadly.spec
---
- Add an explicit BR on `perl(English)` to enable ptest.
**NO**
- NA
- NA
=> perl-Object-Deadly: add an explicit BR on `perl(English)` to enable ptest

SPECS-EXTENDED/python-testscenarios/python-testscenarios.spec
---
- Add an explicit BR on `pip` to enable ptest
**NO**
- NA
- NA
=> python-testscenarios: add BR on `pip` to enable ptest

SPECS-EXTENDED/python-requests-mock/0001-tox-add-py39-environment.patch, SPECS-EXTENDED/python-requests-mock/python-requests-mock.spec
---
- Introduce patch to test using `tox`
**NO**
- NA
- NA
=> python-requests-mock: switch to `tox` for testing

toolkit/tools/imagegen/configuration/packagerepo.go, toolkit/tools/internal/network/network.go
---
Customer's environment may not have outbound network access and may only have internal network access. Therefore, modify the original network access check logic to check the status of systemd-networkd-wait-online service instead. If the service is active, then there's network access in the installation environment which can then do package install.
NO
-Local Image Build
=> Fix network access check during package repo file generation

SPECS/ldns/CVE-2017-1000231.nopatch, SPECS/ldns/CVE-2017-1000232.nopatch
---
Nopatch CVEs which were already addressed by existing patch files in codebase (ldns-1.7.0-parse-limit, ldns-1.7.0-realloc)
For example, the fix commit https://github.com/NLnetLabs/ldns/commit/3bdeed02505c9bbacb3b64a97ddcb1de967153b7 is the content of ldns-1.7.0-parse-limit.patch
- Nopatch CVEs which were already addressed by existing patch files in codebase (ldns-1.7.0-parse-limit, ldns-1.7.0-realloc)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2017-1000231
- https://nvd.nist.gov/vuln/detail/CVE-2017-1000232
=> Add nopatches for ldns CVES CVE-2017-1000231, CVE-2017-1000232

SPECS/fluent-bit/fluent-bit.signatures.json, SPECS/fluent-bit/fluent-bit.spec, cgmanifest.json
---
Upgrade fluent-bit version to latest 1.9.6 which provides the option to use socket as output.
Add build time dependency libyaml-devel.
- Change
Upgrade fluent-bit version to latest 1.9.6
Add build time dependency libyaml-devel
**NO**
- #xxxx
=> Upgrade fluent-bit version to latest 1.9.6

SPECS-EXTENDED/cassandra/Readme, SPECS-EXTENDED/cassandra/cassandra.signatures.json, SPECS-EXTENDED/cassandra/cassandra.spec, cgmanifest.json
---
Upgrade Cassandra version to latest 4.0.5
- Change
Upgrade Cassandra version to latest 4.0.5
**NO**
- #xxxx
=> Upgrade cassandra version to 4.0.5

SPECS/mariner-release/mariner-release.spec
---
Incrementing the `Release` tag in `mariner-release.spec` to start off the August release.
- Updated `mariner-release.spec`.
No.
=> Updating `mariner-release` for the August release.

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump the release version for our August 2022 1.0 release.
- Change mariner-release version
**YES**
=> Update mariner-release for August 1.0 release

SPECS/perl-File-HomeDir/perl-File-HomeDir.spec
---
- Add BR on `perl-{(ExtUtils::MakeMaker),(Test::More)}` to enable ptest
**NO**
- NA
- NA
=> perl-File-HomeDir: add BR on `perl-{(ExtUtils::MakeMaker),(Test::More)}` to enable ptest

SPECS/perl-JSON-Any/perl-JSON-Any.spec
---
- Add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest
**NO**
- NA
- NA
=> perl-JSON-Any: add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest

SPECS/perl-DBD-SQLite/perl-DBD-SQLite.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(Test::More)` & `perl(Digest::MD5)` to fix ptest
**Yes**
- NA
- NA
=> perl-DBD-SQLite: add BR on `perl(Test::More)` & `perl(Digest::MD5)` to fix ptest

SPECS/perl-Path-Class/perl-Path-Class.spec
---
- Add BR on `perl-{(Test),(Test::More),(Perl::OSType)}` to enable ptest
**NO**
- NA
- NA
=> perl-Path-Class: add BR on `perl-{(Test),(Test::More),(Perl::OSType)}` to enable ptest

SPECS/perl-libintl-perl/perl-libintl-perl.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(ExtUtils::MakeMaker)` & `perl(Test)` to enable ptest
**Yes**
- NA
- NA
=> perl-libintl: add BR on `perl-{(ExtUtils::MakeMaker),(Test)}` to enable ptest

SPECS/perl-generators/perl-generators.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(Fedora::VSP)` to fix ptest build
**NO**
- NA
- NA
- Pipeline ID: [219922](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=219922&view=results)
=> perl-generators: add BR on `perl(Fedora::VSP)` to fix ptest build

SPECS-EXTENDED/perl-Pod-POM/perl-Pod-POM.spec
---
- Add an explicit BR on `perl(FindBin)` to enable ptest
**NO**
- NA
- NA
=> perl-Pod-POM: add BR on `perl(FindBin)` to enable ptest

SPECS/perl-DBI/perl-DBI.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(blib)` & `perl(Test::More)` to fix ptest
**Yes**
- NA
- NA
=> perl-DBI: add BR on `perl(blib)` & `perl(Test::More)` to fix ptest

SPECS/perl-YAML-Tiny/perl-YAML-Tiny.spec
---
- Add BR on `perl(JSON::PP)` & `perl(Test::More)` to fix ptest
**NO**
- NA
- NA
=> perl-YAML-Tiny: add BR on `perl(JSON::PP)` & `perl(Test::More)` to fix ptest

SPECS/perl-Exporter-Tiny/perl-Exporter-Tiny.spec
---
- Add BR on `perl(Test::More)` to fix ptest build
**NO**
- NA
- NA
=> perl-Exporter-Tiny: add BR on `perl(Test::More)` to fix ptest

SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.spec
---
- Add BR on `perl(ExtUtils::MakeMaker)` & check deps to enable ptest
**No**
- NA
- NA
=> perl-IO-Socket-SSL: add BR on `perl(ExtUtils::MakeMaker)` & check deps to enable ptest

toolkit/tools/internal/safechroot/safechroot_test.go
---
- Closes: #3244
- Fix if/else condition in `TestInitializeShouldCreateRoot`
**YES**
- #3244
- NA
- Local Build.
- Buddy Build: [223399](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=223399&view=results)
=> tools: safechroot: TestInitializeShouldCreateChroot: fix if condition

SPECS/perl-Test-Warnings/perl-Test-Warnings.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(Test::More)` to enable ptest
**YES**
- NA
- NA
=> perl-Test-Warnings: add BR on `perl(Test::More)` to enable ptest

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Updating `vim` to the latest version to fix CVEs.
- Updated `vim` to version 9.0.0181.
- Sorted `cgmanifest.json` contents.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-2522
- https://nvd.nist.gov/vuln/detail/CVE-2022-2571
- https://nvd.nist.gov/vuln/detail/CVE-2022-2580
- https://nvd.nist.gov/vuln/detail/CVE-2022-2581
- Buddy build green.
=> vim: update version to 9.0.0181 to fix CVEs 2022-2522, 2022-2571, 2022-2580, 2022-2581.

SPECS/perl-DBIx-Simple/perl-DBIx-Simple.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(Test::More)` to fix ptest
**YES**
- NA
- NA
=> perl-DBIx-Simple: add BR on `perl(Test::More)` to fix ptest

SPECS/perl-JSON-XS/perl-JSON-XS.spec
---
Fix ptest. All tests pass!
- Add BR on `perl(ExtUtils::MakeMaker)` & `perl(Test::*)` to enable ptest
**NO**
- NA
- NA
=> perl-JSON-XS: add BR on `perl(ExtUtils::MakeMaker)` & `perl(Test::*)` to enable ptest

SPECS/kernel-rt/kernel-rt.signatures.json
---
Fix the signature file for kernel-rt, required to match the sources.
Update the signature file for kernel-rt
kernel-rt
N/A
NO
N/A
=> Fix signature file for kernel-rt

SPECS/zlib/CVE-2022-37434.patch, SPECS/zlib/Fix-extra-field-processing-bug-that-dereferences-NULL.patch, SPECS/zlib/zlib.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2022-37434
- Patch CVE-2022-37434
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-37434
- BuddyBuild: [225305](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225305&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1822)
=> zlib: patch CVE-2022-37434

SPECS/unbound/unbound.signatures.json, SPECS/unbound/unbound.spec, cgmanifest.json
---
Address CVE-2022-30698
- Bump version to 1.16.2 to address CVE-2022-30698
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-30698
- BuddyBuild: [225391](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225391&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1790)
=> unbound: bump version to 1.16.2 to address CVE-2022-30698

SPECS/m2crypto/CVE-2020-25657.patch, SPECS/m2crypto/m2crypto.spec
---
Address CVE-2020-25657
- Patch CVE-2020-25657
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2020-25657
- BuddyBuild: [225367](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225367&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1787)
=> m2crypto: patch CVE-2020-25657

SPECS/libtiff/CVE-2022-34526.patch, SPECS/libtiff/libtiff.spec
---
Address CVE-2022-34526
- Patch CVE-2022-34526
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-34526
- BuddyBuild: [225337](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225337&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1784)
=> libtiff: patch CVE-2022-34526

SPECS-EXTENDED/exempi/exempi.spec
---
`zlib` was patched for CVE-2022-37434 in #3537. `exempi` is the only package that links with the static library in the `zlib-devel` package. So, let's bump the release of `exempi` to rebuild with the fixed version of the static library.
- `exempi`: Bump release number to force rebuild/republish
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-37434
- Local package built
=> Bump exempi release to rebuild with zlib's CVE-2022-37434 fix

SPECS/lldpd/lldpd.signatures.json, SPECS/lldpd/lldpd.spec, cgmanifest.json
---
Address CVE-2020-27827
- Bump version to 1.0.14 to address CVE-2020-27827
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2020-27827
- BuddyBuild: [225298](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225298&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1790) [arm64 225549](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=225549&view=results)
=> lldpd: bump version to 1.0.14 to address CVE-2020-27827

SPECS/mariner-release/mariner-release.spec
---
Bump mariner-release for August update 2
- Change mariner-release version
**NO**
=> [2.0] Bump mariner-release for August update 2

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Preparing for mid-August release by incrementing the `Release` tag inside `mariner-release.spec`.
- Bumped `Release` tag in `mariner-release.spec`.
Yes.
- None, no actual build changes.
=> mariner-release: bump `Release` tag for August Update 2.

SPECS/kernel/CVE-2021-4135.nopatch, SPECS/kernel/CVE-2022-1158.nopatch, SPECS/kernel/CVE-2022-2380.nopatch
---
Address CVE-2021-4135 CVE-2022-2380 CVE-2022-1158
- Address CVE-2021-4135 CVE-2022-2380 CVE-2022-1158
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4135
- https://nvd.nist.gov/vuln/detail/CVE-2022-2380
- https://nvd.nist.gov/vuln/detail/CVE-2022-1158
- n/a
=> kernel: Address CVE-2021-4135 CVE-2022-2380 CVE-2022-1158

SPECS/perl-YAML/perl-YAML.spec
---
- Add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest
**NO**
- NA
- NA
=> perl-YAML: add BR on `perl(ExtUtils::MakeMaker)` & `cpan` to enable ptest

SPECS/perl-Fedora-VSP/perl-Fedora-VSP.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add BR on `perl(Test::More)` to fix ptest
**Yes**
- NA
- NA
=> perl-Fedora-VSP: add BR on `perl(Test::More)` to fix ptest

toolkit/.gitignore, toolkit/scripts/toolchain/container/Dockerfile, toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh, toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
#3539 removed CVE-2021-36690.patch, but not the references to it for toolchain building. This broke local building of the toolchain.
- N/A
**YES**
- #3539
- local build: `sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y`
=> Remove refs to sqlite CVE-2021-36690.patch

SPECS/golang/golang-1.17.signatures.json, SPECS/golang/golang-1.17.spec, cgmanifest.json
---
Upgrade golang 1.17 to 1.17.13 to fix 15 CVEs.
- `golang-1.17`: - Upgrade to version 1.17.13 to fix CVE-2022-1705, CVE-2022-1962, CVE-2022-28131, CVE-2022-30630, CVE-2022-30631, CVE-2022-30632, CVE-2022-30633, CVE-2022-30635, CVE-2022-32148, and CVE-2022-32189 
- No dependent packages to bump in this repository
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-29526
- https://nvd.nist.gov/vuln/detail/CVE-2022-30634
- https://nvd.nist.gov/vuln/detail/CVE-2022-30629
- https://nvd.nist.gov/vuln/detail/CVE-2022-30580
- https://nvd.nist.gov/vuln/detail/CVE-2022-29804
- https://nvd.nist.gov/vuln/detail/CVE-2022-1705
- https://nvd.nist.gov/vuln/detail/CVE-2022-1962
- …
=> Upgrade go 1.17 to 1.17.13 to fix 15 CVEs

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade `vim` to the latest upstream tag to fix several CVEs.
- `vim`: version bump to 9.0.0228
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2571
- https://nvd.nist.gov/vuln/detail/CVE-2022-2580
- https://nvd.nist.gov/vuln/detail/CVE-2022-2581
- https://nvd.nist.gov/vuln/detail/CVE-2022-2598
- https://nvd.nist.gov/vuln/detail/CVE-2022-2816
- https://nvd.nist.gov/vuln/detail/CVE-2022-2817
- https://nvd.nist.gov/vuln/detail/CVE-2022-2819
- Buddy builds passed!
=> Upgrade vim to 9.0.0228 to fix seven CVEs

SPECS-EXTENDED/xdelta/xdelta.spec
---
- Run the `%check` section via a non-root user to fix ptest build
**NO**
- NA
- NA
=> xdelta: run `%check` section via a non-root user to fix ptest build

SPECS/perl-Try-Tiny/perl-Try-Tiny.spec
---
- Add BR on `perl(Test::More)` to fix ptest build
**NO**
- NA
- NA
=> perl-Try-Tiny: add BR on `perl(Test::More)` to fix ptest build

SPECS-EXTENDED/flac/flac.signatures.json, SPECS-EXTENDED/flac/flac.spec, cgmanifest.json
---
Bump version & fix ptest build. All tests pass!
- Bump version to 1.3.4 & run `%check` as non-root to fix ptest
**NO**
- NA
- NA
- Local Build
=> flac: bump version to 1.3.4 & run `%check` as non-root to fix ptest

SPECS-EXTENDED/cppcheck/cppcheck.spec
---
- Fix `testrunner` binary path to fix ptest build
**NO**
- NA
- NA
=> cppcheck: fix `testrunner` binary path to fix ptest build

SPECS/openssl/CVE-2022-2097.nopatch
---
openssl - nopatch CVE-2022-2097 since only for 32-bit x86 platforms
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2097
=> openssl - nopatch CVE-2022-2097 since only for 32-bit x86 platforms

SPECS/qemu/CVE-2022-35414.patch, SPECS/qemu/qemu.spec
---
qemu fix cve-2022-35414
- Change
- Change
- Change
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-35414
=> qemu : fix CVE-2022-35414

SPECS/perl-Module-Build/perl-Module-Build.spec
---
- Add BR on `perl(ExtUtils::*)` & `cpan` to enable ptest
**NO**
- NA
- NA
=> perl-Module-Build: add BR on `perl(ExtUtils::*)` & `cpan` to enable ptest

SPECS/perl-NetAddr-IP/perl-NetAddr-IP.spec
---
- Add BR on `perl-{(Autoloader), (Test::More)}` to enable ptest
**NO**
- NA
- NA
=> perl-NetAddr-IP: add BR on `perl-{(Autoloader), (Test::More)}` to enable ptest

SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec
---
- Add BR on `perl-{(Math::Trig),(Test::More),(Tie::Array)}` to enable ptest
**NO**
- NA
- NA
=> perl-List-MoreUtils: add BR on `perl-{(Math::Trig),(Test::More),(Tie::Array)}` to enable ptest

SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.spec
---
- Add BR on `perl-{(CPAN::*),(FindBin),(Test::More)}` to enable ptest
**NO**
- NA
- NA
=> perl-Module-ScanDeps: add BR on `perl-{(CPAN::*),(FindBin),(Test::More)}` to enable ptest

SPECS/libxml2/libxml2.signatures.json, SPECS/libxml2/libxml2.spec, SPECS/python-lxml/python-lxml.signatures.json, SPECS/python-lxml/python-lxml.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
fix CVE-2022-2309 in libxml2 and python-lxml
- Change
- Change
- Change
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2309
=> libxml2 and python-lxml: fix CVE-2022-2309

SPECS/perl-Net-SSLeay/0001-local-tests-skip-2-failing-tests.patch, SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
---
- Add missing BRs
- Skip two failing tests to enable ptest
**NO**
- NA
- NA
=> perl-Net-SSLeay: add missing BRs & skip two failing tests

SPECS/openssl/CVE-2022-2097.nopatch
---
openssl : nopatch CVE-2022-2097 since against 32 bit platform only
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2097
=> openssl : nopatch CVE-2022-2097 since against 32 bit platform only

SPECS/libtirpc/CVE-2021-46828.patch, SPECS/libtirpc/libtirpc.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add upstream patch for CVE-2021-46828 in `libtirpc`.
- `libtirpc`: Patch CVE-2021-46828
- Change
- Change
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-46828
- Pipeline build 228213
=> Patch CVE-2021-46828 in libtirpc

SPECS/qemu-kvm/CVE-2022-35414.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
qemu-kvm : fix CVE-2022-35414
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-35414
=> qemu-kvm : fix CVE-2022-35414

toolkit/tools/imagegen/configuration/networkconfig_test.go
---
- networkconfig unit test will test the creation of a network file given user input in image config under /etc/systemd/network. However, this directory does not exist on some systems without systemd-networkd, which will then throw an error. To resolve the problem, add logic to check whether this network file path exists in the system or not and if not exist, manually create the directory for testing purpose.
NO
- https://github.com/microsoft/CBL-Mariner/issues/3483
- Local Test Run
=> Fix networkconfig test case 

SPECS-EXTENDED/perl-Unicode-LineBreak/perl-Unicode-LineBreak.spec
---
- Add BR on `perl(FindBin)` to fix ptest build
**NO**
- NA
- NA
- Local build with RUN_CHECK=y & RUN_CHECK=n
=> perl-Unicode-LineBreak: add BR on `perl(FindBin)` to fix ptest build

SPECS/kernel/CVE-2022-1651.nopatch, SPECS/kernel/CVE-2022-1671.nopatch
---
nopatching CVE-2022-1651, CVE-2022-1671
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1651
- https://nvd.nist.gov/vuln/detail/CVE-2022-1671
=> nopatching kernel CVE-2022-1651, CVE-2022-1671

SPECS-EXTENDED/python-suds/python-suds.spec
---
- Add BR on `python3-pip` & drop `python3-pytest` to enable ptest
**NO**
- NA
- NA
=> python-suds: add BR on `python3-pip` & drop `python3-pytest` to enable ptest

SPECS-EXTENDED/python-tornado/python-tornado.signatures.json, SPECS-EXTENDED/python-tornado/python-tornado.spec, cgmanifest.json
---
- Bump version to 6.2.0
**NO**
- NA
- NA
=> python-tornado: bump version to 6.2.0

SPECS/clamav/clamav.spec
---
Fix various aspects of `clamav` to allow for proper user provisioning, database downloading, and logging according to [upstream instructions](https://docs.clamav.net/manual/Installing/Installing-from-source-Unix-old.html).
This is a port of #3136, adjusted for 1.0 as necessary.
- Fix freshclam DB download (backport of Tom Fay's 2.0 changes)
- Create/delete clamav user and group on preinstall/postuninstall
- Move database directory to %{_sharedstatedir} from %{_datadir}
- Give ownership of %{_sharedstatedir}/clamav, %{_var}/log/freshclam.log to clamav user
**NO**
- Buddy build
- Running `freshclam` and `clamscan` now succeed without additional configuration.
=> Fix freshclam db download for clamav

SPECS/kernel/CVE-2022-36123.nopatch
---
Address CVE-2022-36123
Note that the patch on NIST is not the correct upstream fix
[CVE-2022-36123 – A vulnerability in Linux kernel mainline v5.18-rc1 through v5.19-rc6 does not clear statically allocated variables in the block starting symbol (.bss) due to a failed early_xen_iret_patch leading to an asm_exc_page_fault, or arbitrary code execution](https://sick.codes/sick-2022-128)
- Add nopatch for CVE-2022-36123
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-36123
- N/A
=> kernel: Address CVE-2022-36123

SPECS/selinux-policy/0044-systemd-Minor-coredump-fixes.patch, SPECS/selinux-policy/0045-rpm-Minor-fixes.patch, SPECS/selinux-policy/0046-init-Allow-nnp-nosuid-transitions-from-systemd-initr.patch, SPECS/selinux-policy/0047-selinuxutil-Semanage-reads-policy-for-export.patch, SPECS/selinux-policy/0048-sysnetwork-ifconfig-searches-debugfs.patch, SPECS/selinux-policy/0049-usermanage-Add-dac_read_search-to-useradd.patch, SPECS/selinux-policy/0050-Temp-kubernetes-fix.patch, SPECS/selinux-policy/selinux-policy.spec
---
Add rules to SELinux policy for proper functioning.
- Fixed denials during coredump.
- Allow NoNewPerms transition from init scripts/systemd unit commands.
- Minor fixes in semanage, ifconfig, rpm, and useradd.
- Fix incorrect label for kubernetes runtime dir when created by initrc_t.
**NO**
- Local builds
=> selinux-policy: Various fixes.

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
upgrade vim to fix CVE-2022-2982, CVE-2022-2946
- upgrade vim to fix CVE-2022-2982, CVE-2022-2946
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-2982
- https://nvd.nist.gov/vuln/detail/CVE-2022-2946
- 
=> upgrade vim to fix CVE-2022-2982, CVE-2022-2946

SPECS/binutils/CVE-2022-38533.patch, SPECS/binutils/binutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2022-38533 in binutils
- Fix CVE-2022-38533 in binutils
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-38533
- Individual package build succeeded
- Full local toolchain build succeeded
- Full local package build succeeded
- No regressions in already failing %check section
=> `binutils`: fix CVE-2022-38533

SPECS/kata-containers/kata-containers.spec
---
set DEFSANDBOXCGROUPONLY to false
- set DEFSANDBOXCGROUPONLY to false
**NO**
- [41150250](https://microsoft.visualstudio.com/OS/_workitems/edit/41150250)
- Pipeline build id: [233248](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=233248&view=results)
=> kata-containers : set DEFSANDBOXCGROUPONLY to false

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade vim to 9.0.0348 to fix CVE-2022-3016 and CVE-2022-3037
- Change
Upgrade to 9.0.0348 to fix CVE-2022-3016 and CVE-2022-3037
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-3016
- https://nvd.nist.gov/vuln/detail/CVE-2022-3037
=> Upgrade vim to 9.0.0348 to fix CVEs

SPECS/qemu-kvm/qemu-kvm.spec
---
CVE-2022-0358 is in the tools component for qemu-kvm source code.
Version v4.2.0 of qemu-kvm does not have tools component.
CVE and provided patch are not applicable hence adding nopatch.
CVE: https://nvd.nist.gov/vuln/detail/CVE-2022-0358
upstream patch: https://gitlab.com/qemu-project/qemu/-/commit/449e8171f96a6a944d1f3b7d3627ae059eae21ca
- Change
Nopatch CVE-2022-0358
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-0358
=> Qemu-kvm nopatch CVE-2022-0358

SPECS/clamav/clamav.spec
---
Install/uninstall of `clamav` can fail due to a missing explicit requirement on `shadow-utils` (needed for `useradd`, `groupadd`, `groupdel`, and `userdel`). This PR adds an explicit requirement on `shadow-utils` during the pre-install and post-uninstall phases.
- `clamav`: Add `Requires(pre): shadow-utils` and `Requires(postun): shadow-utils`
**NO**
- Local test build
=> Add preinstall/postuninstall requirement on shadow-utils to clamav

SPECS/rubygem-faraday/rubygem-faraday.signatures.json, SPECS/rubygem-faraday/rubygem-faraday.spec, cgmanifest.json
---
update rubygem-faraday to v.2.5.2
- update rubygem-faraday to v.2.5.2
- this version is required by rubygem-faraday-multipart
**NO**
- Local build
=> update rubygem-faraday to v.2.5.2

SPECS-EXTENDED/audiofile/audiofile.spec
---
Fix build break of ptest pipeline.
The check section of this spec produces a 35Gb log file which breaks the
ptest pipeline.
Disable the check section temporarily till we investigate further.
- Disable `%check` section
**NO**
- NA
- NA
- Local Build
=> audiofile: disable check section to fix ptest pipeline break

SPECS/gzip/gzip.signatures.json, SPECS/gzip/gzip.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade gzip version to 1.12 to fix CVE-2022-1271.
Fix formatting issues.
- Change
Upgrade gzip version to 1.12 to fix CVE-2022-1271
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-1271
=> Upgrade gzip version to 1.12 to fix CVE-2022-1271

SPECS/emacs/emacs.spec
---
Add emacs-filesystem subpackage to enable some package builds.
- Add emacs-filesystem subpackage.
**NO**
- Pipeline buddy build
=> Add emacs-filesystem subpackage

SPECS/mariner-release/mariner-release.spec
---
Bump mariner-release for early September CVE fix release
- Change mariner-release version
**NO**
- Pipeline build id: N/A
=> [2.0] Update mariner-release for September CVE release

SPECS/libvirt/libvirt.spec
Pull libvirt fix to 2.0 branch
=> fix br in libvirt (#3726)

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Release for Mariner 1.0 Sept 2022 Update
=> Bump Release for Mariner 1.0 Sept 2022 Update

SPECS/libjpeg-turbo/libjpeg-turbo.signatures.json, SPECS/libjpeg-turbo/libjpeg-turbo.spec, cgmanifest.json
---
Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538
- Change
Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2020-35538
=> Upgrade libjpeg-turbo version to 2.1.4 to fix CVE-2020-35538

SPECS-EXTENDED/perl-namespace-clean/perl-namespace-clean.spec
---
- Add BR on perl-debugger to enable ptest
**NO**
- NA
- NA
- BuddyBuild: [232802](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=232802&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1898)
=> perl-namespace-clean: add BR on perl-debugger to enable ptest

SPECS/kernel-uvm/kernel-uvm.spec
---
Create modules folder for uvm kernel
- Create modules folder for uvm kernel and copy the vmlinux there
- This would enable us to create initrd for this guest kernel
- The convention is for every kernel version installed on the disk to have a modules folder under /lib/modules
**NO**
- [41159815](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/41159815)
- Pipeline build id: [236044](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=236044&view=results)
=> Create modules folder for UVM kernel

SPECS/mariadb/mariadb.spec
---
Fix errors upgrading mariadb when util-linux pacakge is not installed.
```
groupadd: command not found<nl> useradd: command not found<nl> Error(1525) : rpm transaction failed
```
- Change mariadb spec
**NO**
=> mariadb - fix upgrade by adding shadow-utils pre/postun requirement

SPECS/reaper/reaper.spec
- Adding Runtime requirement on msopenjdk-11
- Fix adding cassandra reaper custom user/group
- Fix issues with starting unit service due to permission errors when executing binaries copied
to /usr/local/bin (by default, subdir bin does not allow any other user/group to access except root)
Copying reaper binaries to /usr/sbin instead.
- Add post steps during uninstallation to stop service and remove custom user/group.
---
Fix RPM install errors
- error when adding custom user and group
- failing to start unit service
- Adding Runtime requirement on msopenjdk-11
- Fix adding cassandra reaper custom user/group
- Fix issues with starting unit service due to permission errors when …
=> Fix errors when installing reaper RPM in CBL-Mariner

SPECS/selinux-policy/selinux-policy.spec
---
Fix this error:
```
touch: cannot touch '/etc/selinux/targeted/.rebuild': No such file or direectory
error: %prein(selinux-policy-2.20220106-9.cm2.noarch) scriptlet failed, exit status 1
```
- Fix issue with preinst on systems that do not have selinux-policy.
**NO**
- Local build
=> selinux-policy: Fix issue with preinst on systems that do not have selinux-policy.

SPECS/tcl/tcl.spec
---
Add explicit provides for tcl(abi) to enable some package builds.
- Add explicit provides for tcl(abi)
**NO**
- Pipeline buddy build
=> Add explicit provides for tcl(abi)

SPECS/libtiff/CVE-2022-2953.patch, SPECS/libtiff/libtiff.spec
---
Patch [CVE-2022-2953](https://github.com/advisories/GHSA-xcmj-v3mr-j4qc)
- Change
Patch [CVE-2022-2953](https://github.com/advisories/GHSA-xcmj-v3mr-j4qc)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2953
- BuddyBuild-spec pipeline: buildId=237188
=> libtiff: Patch CVE-2022-2953

SPECS/numpy/numpy.spec
---
Some of the NumPy header files, required during the build time of TensorFlow were missing. This change added those header files.
- Change: Replaced %py3_install macro with %{__python3} setup.py install --root %{buildroot}.
- Change: %py3_install macro is  %{__python3} setup.py install --skip-build --root %{buildroot}.
- Change: --skip-build flag is removed essentially.
**YES/NO**
NO
-  https://github.com/numpy/numpy/issues/16005
- Pipeline build id: 237723
=> Replace NumPy spec %py3_install macro

SPECS/libtirpc/CVE-2021-46828.nopatch
---
Adds nopatch to libtirpc for CVE-2021-46828 due to nonapplicability.
- Adds nopatch to libtirpc for CVE-2021-46828 due to nonapplicability.
**NO**
- Pipeline build id: Not Applicable
=> Added nopatch to libtirpc for CVE-2021-46828

SPECS/mariner-release/mariner-release.spec
---
Bump mariner-release for 2.0 September update 2
- Change mariner-release
**NO**
- Pipeline build id: N/A
=> update mariner-release to 2.0-21

SPECS/rpcbind/rpcbind.spec
---
Add portmap as an explicit `Provides` to enable build of some packages.
- Add `portmap` to rpcbind `Provides`
**NO**
- Pipeline buddy build
=> Add portmap to rpcbind provides

SPECS/libbpf/libbpf.signatures.json, SPECS/libbpf/libbpf.spec, SPECS/qemu/0001-ebpf-replace-deprecated-bpf_program__set_socket_filt.patch, SPECS/qemu/qemu.spec, cgmanifest.json
---
Bump version to latest 1.0.0
- libbpf: bump version to 1.0.0
- qemu: introduce patch to replace deprecated `bpf_program__set_socket_filter`
**NO**
- NA
- NA
BuddyBuild:
-  [Attempt I -- Failure](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=234392&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2020)
- [Attempt II -- Passed](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=234457&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2000)
=> libbpf: bump version to 1.0.0

SPECS/blobfuse/blobfuse.signatures.json, SPECS/blobfuse/blobfuse.spec, cgmanifest.json
---
Bump version to `1.4.5`
- Bump version to `1.4.5`
**NO**
- #3771
- NA
- BuddyBuild: [PR-3785](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=239113&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1957)
Closes: #3771
=>  blobfuse: bump version to 1.4.5

SPECS/expat/CVE-2022-40674.patch, SPECS/expat/expat.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix the CVE-2022-40674
- Apply new patch for expat
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-40674
- Local toolchain build succeeded, local full build succeeded
- Buddy build runs are successful: 
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=239907&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=239906&view=results
=> expat: patch CVE-2022-40674

SPECS/gzip/gzip.signatures.json, SPECS/gzip/gzip.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update gzip version to fix CVE-2022-1271
- Update gzip version to 1.12
YES
- https://nvd.nist.gov/vuln/detail/CVE-2022-1271
- Test using buddy-build:
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=240242&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=240075&view=results
=> gzip: version update CVE-2022-1271

SPECS/sos/sos.signatures.json, SPECS/sos/sos.spec, cgmanifest.json
---
Update sos to 4.4 to fix patch CVE-2022-2806
- Change
Update sos to 4.4 to fix patch CVE-2022-2806
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2806
- local build
=> Update sos to 4.4 to fix patch CVE-2022-2806

SPECS/virglrenderer/CVE-2022-0175.patch, SPECS/virglrenderer/virglrenderer.spec
---
Patch CVE-2022-0175
- Change
Patch CVE-2022-0175
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0175
- Pipeline(BuddyBuild-spec) build id: 237244
=> virglrenderer: Patch CVE-2022-0175

SPECS/kernel-mshv/kernel-mshv.spec
---
copy vmlinuz to efi partition
- copy vmlinuz to efi partition
**NO**
- Pipeline build id: [240404](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=240404&view=results)
=> kernel mshv: copy vmlinuz to efi partition

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
msft-golang - upgrade to 1.19.1-1
- Change
- Change
- Change
**NO**
- #xxxx
=> msft-golang - upgrade to 1.19.1-1

SPECS-EXTENDED/pyflakes/pyflakes.signatures.json, SPECS-EXTENDED/pyflakes/pyflakes.spec, cgmanifest.json
---
Bump version to v2.5.0 to fix ptest build. All tests pass!
- Bump version to 2.5.0 to fix ptest
**NO**
- NA
- NA
- BuddyBuild: [PR-3816](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=240515&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2086)
- BuddyBuild: (pyflakes + python-flake8) [PR-3816](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=241068&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=2103)
=> pyflakes: bump version to 2.5.0 to fix ptest

SPECS/python-mako/python-mako.signatures.json, SPECS/python-mako/python-mako.spec, cgmanifest.json
---
Python-mako version update
Python-mako version update to 1.2.2
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-40023
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=241015&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=241043&view=results
=> python-mako: version update CVE-2022-40023

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner Release for Mariner 1.0 September Update 2
=> Bump Mariner Release for Mariner 1.0 September Update 2

SPECS/python-mako/python-mako.signatures.json, SPECS/python-mako/python-mako.spec, cgmanifest.json
---
python-mako upgrade to 1.2.2 to fix CVE-2022-40023
- Change
- Change
- Change
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-40023
- BuddyBuild passed
- Toolchain was able to be built
- Pipeline build id: 241104
=> python-mako: Updating to 1.2.2 to fix CVE-2022-40023

SPECS/mariner-release/mariner-release.spec
Bump Mariner 2.0 Release for Accumulated September Update 3
=> Bump Mariner 2.0 Release for Accumulated September Update 3

toolkit/tools/imagegen/installutils/installutils.go
---
The network configuration module in the Mariner installer is performing a restart of the systemd-networkd service and that will throw an error in the ARM64 image build. Currently add a mitigating fix to not call the network config function if there's no Networks input in the imageconfig to silent the issue for now. 
- Change
- Change
- Change
NO
- #xxxx
- Pipeline Build 241404
=> Mitigate ARM64 Image Build

toolkit/scripts/toolkit.mk
---
I've used the wrong switch to remove the log files from building RPMs snapshots, so the `make clean` run for out toolkit started failing, if no snapshot was present.
- Replaced `rm -r` with `rm -f` inside `toolkit.mk`.
No.
- Local `make clean` run.
=> toolkit.mk: fix `clean-rpms-snapshot` target.

SPECS/kernel/CVE-2022-1976.nopatch, SPECS/kernel/CVE-2022-2905.nopatch, SPECS/kernel/CVE-2022-2977.nopatch, SPECS/kernel/CVE-2022-3078.nopatch, SPECS/kernel/CVE-2022-3170.nopatch, SPECS/kernel/CVE-2022-40307.nopatch
---
Address Cves
- CVE-2022-1976
- CVE-2022-2905
- CVE-2022-2977
- CVE-2022-3078
- CVE-2022-3170
- CVE-2022-4030
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1976
- https://nvd.nist.gov/vuln/detail/CVE-2022-2905
-  https://nvd.nist.gov/vuln/detail/CVE-2022-2977
-  https://nvd.nist.gov/vuln/detail/CVE-2022-3078
-  https://nvd.nist.gov/vuln/detail/CVE-2022-3170
-  https://nvd.nist.gov/vuln/detail/CVE-2022-4030
- N/A
=> kernel: Address CVE-2022-1976, CVE-2022-2905, CVE-2022-2977, CVE-2022-3078, CVE-2022-3170, CVE-2022-4030

SPECS/mlocate/0001-tests-updatedb-reduce-heirarchy-to-300-from-950.patch, SPECS/mlocate/mlocate.spec
---
Fix ptest build. All test pass!
- Introduce patch to fix deep hierarchy ptest
**NO**
- NA
- NA
BuddyBuild:
- ARM64: [PR-3838](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=242006&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=08703039-49d0-5b78-7691-5b9414c62c1d&l=1344)
- AMD64: [PR-3838](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=242003&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1468)
=> mlocate: introduce patch to fix deep heirarchy ptest

toolkit/scripts/rpmops.sh
---
I've noticed that the Mariner chroot includes two more RPM macro files I missed while writing `mariner_rpmspec`. I'm adding them now.
- Added Python and Perl RPM macros.
No.
- Local test.
=> rpmops.sh: load missed macro files

toolkit/tools/imagegen/attendedinstaller/views/diskview/autopartitionwidget/autopartitionwidget.go, toolkit/tools/imagegen/attendedinstaller/views/diskview/diskview.go, toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go, toolkit/tools/imagegen/configuration/parse_partition.go, toolkit/tools/imagegen/configuration/parse_partition_test.go, toolkit/tools/imagegen/configuration/partition.go, toolkit/tools/imagegen/diskutils/diskutils.go, toolkit/tools/liveinstaller/liveinstaller.go
---
- Add support for UEFI partition in Mariner partition parser for PXE boot on UEFI platforms
- Fix partition flag implementation for legacy boot scenarios
NO
=> Add UEFI support in Mariner partition parser

SPECS/python-mako/python-mako.spec
---
fix build break due to missing python-mako dependencies
- Change
- Change
- Change
**NO**
- #xxxx
=> fix build break due to missing python-mako dependencies

SPECS/csi-driver-lvm/csi-driver-lvm.spec
---
Split csi-driver-lvm binaries to two required packages, for the usage of creating golden container.
%changelog
Tue Sep 27 2022 Lanze Liu <lanzeliu@microsoft.com> - 0.4.1-2
- Split binaries into separate packages
Thu Sep 23 2022 Lanze Liu <lanzeliu@microsoft.com> - 0.4.1-1
- Original version for CBL-Mariner
- License Verified
**NO**
- Local build
- BuddyBuild
=> Split csi-driver-lvm binaries to two packages.

toolkit/docs/formats/imageconfig.md, toolkit/tools/imagegen/attendedinstaller/_manualrun/manualrun.go, toolkit/tools/imagegen/attendedinstaller/views/installationview/installationview.go, toolkit/tools/imagegen/configuration/configuration.go, toolkit/tools/imagegen/configuration/configuration_test.go, toolkit/tools/imagegen/configuration/systemconfig.go, toolkit/tools/imagegen/configuration/testdata/test_configuration.json, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imager/imager.go, toolkit/tools/isomaker/maker.go
---
Add option to provide a final script that modifies the chroot before creating an image
- Add option to provide a final script that modifies the chroot before creating an image
**NO**
- #[41439909](https://microsoft.visualstudio.com/OS/_workitems/edit/41439909)
- Functional testing done: tested path with different number of scripts (no script, 1 script, multiple script paths), with and without args
=> Add initial support for finalizeImage

SPECS-EXTENDED/toolbox/toolbox.signatures.json
---
Add missing `signatures.json` file.
- NA
**NO**
- NA
- NA
- NA
=> toolbox: add missing `signatures.json` file

SPECS-EXTENDED/cassandra/cassandra.signatures.json, SPECS-EXTENDED/cassandra/cassandra.spec, cgmanifest.json
---
Upgrade cassandra version to 4.0.6
- Change
Upgrade cassandra version to 4.0.6
**NO**
- #xxxx
=> Upgrade cassandra version to 4.0.6

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Fix CVEs listed below
- CVE-2022-3278
- CVE-2022-3297
- CVE-2022-3324
- CVE-2022-3296
- CVE-2022-3256
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3278
- https://nvd.nist.gov/vuln/detail/CVE-2022-3297
- https://nvd.nist.gov/vuln/detail/CVE-2022-3324
- https://nvd.nist.gov/vuln/detail/CVE-2022-3296
- https://nvd.nist.gov/vuln/detail/CVE-2022-3256
- ARM(succeeded): https://dev.azure.com/mariner-org/mariner/_build/results?buildId=244385&view=results
- AMD(succeeded): https://dev.azure.com/mariner-org/mariner/_build/results?buildId=244384&view=results
=> vim: upgrade to version 9.0.0598

SPECS/python-jwt/CVE-2022-39227.nopatch, SPECS/python-jwt/python-jwt.spec
---
Address CVE-2022-39227
- CVE-2022-39227
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-39227
=> address CVE-2022-39227

SPECS/libbpf/libbpf.signatures.json, SPECS/libbpf/libbpf.spec, cgmanifest.json
---
Bump version to 1.0.1 to address bugs from the jump to 1.0.0
- Bump version to 1.0.1
**NO**
- NA
- NA
- BuddyBuild: [validating]
=> libbpf: bump version to 1.0.1

SPECS/cryptsetup/cryptsetup.signatures.json, SPECS/cryptsetup/cryptsetup.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade cryptsetup to version 2.3.7 to fix CVE-2021-4122
- Upgrade cryptsetup to version 2.3.7 to fix CVE-2021-4122
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4122
- Private build
=> cryptsetup: update v2.3.7 to fix CVE-2021-4122

SPECS/libvirt/CVE-2021-3975.patch, SPECS/libvirt/libvirt.spec
---
fix CVE-2021-3975
- Add patch CVE-2021-3975.patch to libvirt - Protect qemuMonitorUnregister with proper lock
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3975
- local build
=> fix CVE-2021-3975

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner Release number for October 2022 Update
=> Bump Mariner Release number for October 2022 Update

SPECS/libtiff/CVE-2022-2953.patch, SPECS/libtiff/libtiff.spec
---
Fix CVE-2022-2953 for package libtiff
- Patch CVE-2022-2953
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2953
- Local build
=> Patch libtiff to fix CVE 2022 2953

SPECS/python-absl-py/python-absl-py.spec, SPECS/python-astunparse/python-astunparse.spec
---
Adding missed `Distribution` and `Vendor` tags. I've also linted the specs.
- Added missing tags.
- Linter spec.
- Updated licensing info.
No.
- #3927
- #3937
- None.
=> python-absl-py, python-astunparse: adding missing spec tags + clean-up.

SPECS/mariner-release/mariner-release.spec
---
Starting the October release.
- Updated `mariner-release.spec`.
No.
- None, just a `Release` tag change.
=> mariner_release: bumping version for October release.

toolkit/imageconfigs/additionalconfigs/configure-image.sh
* Remove 99-dhcp-en.network for marketplace img
* Remove contents
* Truncating, to preserve file permission
Fixes: #3917
(cherry picked from commit 7550271f2485fc4c860866366ee4931ce00b85e4, PR #3024)
---
* Remove 99-dhcp-en.network for marketplace img
otherwise networkd starts dhcp on all interfaces
* Remove 99-dhcp-en.network for marketplace img
no
#3024
#3917
=> Overwrite 99-dhcp-en.network for marketplace img

SPECS/terraform/CVE-2018-9057.nopatch, SPECS/terraform/terraform.signatures.json, SPECS/terraform/terraform.spec, cgmanifest.json
---
- Resolve CVE-2021-36230
NO
- https://nvd.nist.gov/vuln/detailCVE-2021-36230
- Local Build
=> Resolve terraform CVE-2021-36230

toolkit/docs/how_it_works/5_misc.md
---
This PR updates the Miscellaneous Topics markdown file of the how_it_works section in CBL-Mariner docs. The update is to include an instruction to filter gpg-pubkey from `rpm` command's output since gpg-pubkey is not an rpm package.
- Not applicable.
**No**
=> Add Instruction to filter gpg-pubkey from rpm cmd's output.

SPECS/sos/CVE-2022-2806.patch, SPECS/sos/sos.spec
---
sos: patch CVE-2022-2806
- sos: patch CVE-2022-2806
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2806
- Local build
=> sos: patch CVE-2022-2806

SPECS/unbound/unbound.signatures.json, SPECS/unbound/unbound.spec, cgmanifest.json
---
- Resolve unbound CVE-2022-3204
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-3204
- Local Build
=> Resolve unbound CVE-2022-3204

SPECS/maven/maven.spec
---
Small clean-up to use the `_mariner_sources_url` macro for our blob storage sources.
- Replaced hard-coded path with the `_mariner_sources_url` macro.
No.
- N/A
=> maven.spec: using macro instead of hard-coded source URL.

toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
- mitigation fix for attended installation regression caused by incorrect input for partition table type
NO
=> Mitigation fix for attended ionstallation regression

SPECS/qemu-kvm/qemu-kvm.spec
---
[What does the PR accomplish, why was it needed?
qemu: nopatch CVE-2022-26354
- qemu: nopatch CVE-2022-26354 as it doesn't apply to v4.2.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-26354
- Local build
=> qemu: nopatch CVE-2022-26354

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Update Mariner 1.0 Release for October 2022 Update 2
=> Update Mariner 1.0 Release for October 2022 Update 2

toolkit/tools/pkggen/worker/create_worker_chroot.sh
Cherry-pick #4024 to the 1.0 branch
=> Support Mariner 1.0 build on Mariner 2.0 host (#4024)

SPECS/libtasn1/libtasn1.signatures.json, SPECS/libtasn1/libtasn1.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updating `libtasn1` to version 4.19.0 to fix CVE-2021-46848.
- Updated `libtasn1` to version 4.19.0.
Yes.
- https://nvd.nist.gov/vuln/detail/CVE-2021-46848
- Local package build with tests.
- Buddy build with tests for ARM64: 255490.
=> Updating `libtasn1` to 4.19.0 to fix CVE-2021-46848.

SPECS/mariner-release/mariner-release.spec
---
Updating `mariner-release` for the October update.
- Bumped `mariner-release`.
No.
- None, just `Release` tag bump.
=> Updated `mariner-release` for October update.

SPECS/libtasn1/libtasn1.signatures.json, SPECS/libtasn1/libtasn1.spec, SPECS/libtiff/CVE-2022-3570.patch, SPECS/libtiff/libtiff.spec, SPECS/mariner-release/mariner-release.spec, SPECS/nodejs/nodejs.signatures.json, SPECS/nodejs/nodejs.spec, SPECS/rubygem-minitest/rubygem-minitest.spec, SPECS/rubygem-power_assert/rubygem-power_assert.spec, SPECS/rubygem-rake/rubygem-rake.spec, SPECS/rubygem-test-unit/rubygem-test-unit.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
Merging a few `main` PRs for the October CVE fixes update.
- Merged 3 CVE fixes from `main`.
- Merged Mariner 2.0 host building fixes.
- Merged extended delta build fixes.
Yes,
- N/A - merge from `main`. Final validation will be a full pipeline build.
=> October 2022 update `main` -> `2.0` merge.

SPECS/kernel/CVE-2022-3541.nopatch, SPECS/kernel/CVE-2022-3544.nopatch
---
NoPatch kernel to fix CVE-2022-3541, CVE-2022-3544
- NoPatch kernel to fix CVE-2022-3541,  CVE-2022-3544
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3541
- https://nvd.nist.gov/vuln/detail/CVE-2022-3544
=> NoPatches kernel to fix CVE-2022-3541, CVE-2022-3544

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We were discarding/not packaging any of our built gpu driver kernel modules. Add them back in as a new kernel subpackage. 
- Add kernel-drivers-gpu package
YES
- https://microsoft.visualstudio.com/OS/_workitems/edit/41518258
- [pipeline run](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=256257&view=results)
=> [main] Add kernel-drivers-gpu package

SPECS/python-cffi/python-cffi.spec, SPECS/python-execnet/python-execnet.spec, SPECS/python-pytest-forked/python-pytest-forked.spec, SPECS/python-pytest-mock/python-pytest-mock.spec
---
Some of our Python package test depend on external modules and we often take the latest version available, which can cause the tests to become unstable every now and then. This change addresses an issue with the latest 7.2.0 version of `pytest`.
- Set 4 Python packages test dependency to a specific version of `pytest`.
No.
- Local package builds with tests.
=> Updated ptests to use a specific version of 'pytest'.

SPECS/kernel/CVE-2022-3541.nopatch, SPECS/kernel/CVE-2022-3543.nopatch, SPECS/kernel/CVE-2022-3544.nopatch, SPECS/kernel/CVE-2022-3595.nopatch
…E-2022-3595
---
Nopatch CVE-2022-3541,  CVE-2022-3543,  CVE-2022-3544,  CVE-2022-3595
- Nopatch CVEs
- 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3541
- https://nvd.nist.gov/vuln/detail/CVE-2022-3543
- https://nvd.nist.gov/vuln/detail/CVE-2022-3544
- https://nvd.nist.gov/vuln/detail/CVE-2022-3595
-N/A
=> NoPatch Kernel to fix CVE-2022-3541, CVE-2022-3543, CVE-2022-3544, CVE-2022-3595

SPECS/libtar/CVE-2021-33644.nopatch, SPECS/libtar/CVE-2021-33646.nopatch
---
Add nopatches for CVE-2021-33644 and CVE-2021-33646: they were fixed in #3716, but the nopatch files are missing.
**NO**
- CVE-2021-33644
- CVE-2021-33646
- Pipeline build id: [256751](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=256751&view=results)
=> libtar: add nopatches for CVE-2021-33644 and CVE-2021-33646

SPECS/perl-CGI/perl-CGI.spec, SPECS/python-pytest-benchmark/python-pytest-benchmark.spec, SPECS/python-requests/python-requests.spec
---
A mix of "freezing" test dependencies, so external updates don't break our test builds, as well as replacing dependency on external test dependencies with Mariner's packages.
- Set `pytest` version to 7.1.2.
- Switched to Perl packages available in core Mariner for `perl-CGI`.
- Disabled `python-pytest-benchmark` test currently broken upstream.
No.
- Local package build with tests.
=> Updated test dependencies to increase stability.

toolkit/imageconfigs/packagelists/azurevm-packages.json
---
Based on https://microsoft.visualstudio.com/OS/_workitems/edit/41326625/. There's a need to include kexec-tools into the mariner AKS image. Adding it to the marketplace image makes it so its also included in the AKS image
- Include kexec-tools in marketplace image
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/41326625/
- Built locally using `sudo make image CONFIG_FILE=./imageconfigs/marketplace-gen2.json TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=n REBUILD_TOOLS=y`
- Verified kexec-tools is already installed using an azure vm
=> include kexec-tools in marketplace image

SPECS/redis/CVE-2022-3647.patch, SPECS/redis/redis.spec
---
Apply patch for CVE-2022-3647
- Patch CVE-2022-3647
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-3647
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=257295&view=results
=> redis: patch for CVE-2022-3647

SPECS/libtar/CVE-2021-33644.nopatch, SPECS/libtar/CVE-2021-33646.nopatch
---
Add nopatches for libtar cves CVE-2021-33644 CVE-2021-33646. Previous PR https://github.com/microsoft/CBL-Mariner/pull/3686 addressed these CVEs but did not leave a nopatch file that our tooling can recognize. Clean this up by adding nopatch files. 
- Add nopatches for libtar cves CVE-2021-33644 CVE-2021-33646
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-33644
- https://nvd.nist.gov/vuln/detail/CVE-2021-33646
=> Add nopatches for libtar cves CVE-2021-33644 CVE-2021-33646

SPECS-EXTENDED/cassandra/cassandra.signatures.json, SPECS-EXTENDED/cassandra/cassandra.spec, cgmanifest.json
---
Upgrade cassandra version to 4.0.7.
- Change
Upgrade cassandra version to 4.0.7
**NO**
- #xxxx
- Pipeline build id: LocalBuild.
=> Upgrade cassandra version to 4.0.7

SPECS/libtasn1/CVE-2021-46848.patch, SPECS/libtasn1/libtasn1.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix the spec to use `%autosetup` so that patches are actually applied, following an oversight from #4112.
**NO**
- Pipeline build id: [amd64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=257491&view=results) [arm64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=257492&view=results)
=> libtasn1: fix spec to actually apply patches

SPECS/mariner-release/mariner-release.spec
---
Bumping `mariner-release` for the full October release of Mariner 2.0.
No.
- None.
=> Bumped `mariner-release` for the full October release.

SPECS/sqlite/CVE-2022-35737.patch, SPECS/sqlite/sqlite.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2022-35737 in `sqlite`
- Add upstream patch for CVE-2022-35737
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-35737
[AMD64 BB](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=259240&view=results)
[ARM64 BB](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=259241&view=results)
=> Patch CVE-2022-35737 in sqlite

toolkit/scripts/tools.mk
---
Disable CGO when building go-tools. This will statically compile the applications instead of dynamically linking them with glibc, which should make them more portable.
Porting change from 1.0-dev - #4154 
- Change toolkit/scripts/tools.mk to compile go tools with "CGO_ENABLED=0"
**NO**
- Local build:
```
$ sudo make go-tools REBUILD_TOOLS=y
$ file ../toolkit/out/tools/liveinstaller
../toolkit/out/tools/liveinstaller: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
$ ldd ../toolkit/out/tools/liveinstaller
not a dynamic executable
```
=> Toolkit: set CGO_ENABLED=0 (2.0)

SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
---
Another Python tests failing with `pytest` 7.2.0.
- Froze `pytest` dependency on 7.1.3.
No.
=> Fixed flaky tests in 'python-into-dbus-python'.

SPECS/kubevirt/kubevirt.spec, SPECS/rust/rust.spec
---
After a recent `glibc-static` split some packages are missing static dependencies because and we're fixing these issues as we find them.
- Added BR on `glibc-static` to `rust.spec`.
- Added missing `%{?dist}` inside `kubevirt.spec`.
No.
=> Updating `rust` test deps to include 'glibc-static'.

SPECS/kernel/CVE-2022-3521.nopatch, SPECS/kernel/CVE-2022-3542.nopatch, SPECS/kernel/CVE-2022-3586.nopatch, SPECS/kernel/CVE-2022-3594.nopatch, SPECS/kernel/CVE-2022-41850.nopatch
---
Address kernel CVEs 2022-3521, 2022-3542, 2022-3586, 2022-3594, 2022-41850
- Address CVEs 2022-3521, 2022-3542, 2022-3586, 2022-3594, 2022-41850
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-3521
- https://nvd.nist.gov/vuln/detail/CVE-2022-3542
- https://nvd.nist.gov/vuln/detail/CVE-2022-3586
- https://nvd.nist.gov/vuln/detail/CVE-2022-3594
- https://nvd.nist.gov/vuln/detail/CVE-2022-41850
=> kernel: Address CVEs 2022-3521, 2022-3542, 2022-3586, 2022-3594, 2022-41850

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade to latest version of blobfuse2 
- Upgrade to latest version of blobfuse2 
NO
- Pipeline build id: [260775](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=260775&view=results)
=> Upgraded blobfuse2 to preview 4

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
Updating `sudo` to fix CVE-2022-43995.
- Updated `sudo` to version 1.9.12p1.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-43995
- Pipeline buddy builds: 262322 [AMD64], 262323 [ARM64].
=> Updated `sudo` to version 1.9.12p1 to fix CVE-2022-43995.

.github/workflows/validate-cg-manifest.sh, SPECS-EXTENDED/go-rpm-macros/go-rpm-macros.spec
---
- Added `sudo` to commands, which might require root privileges.
No.
- #4163
- #4166
- Local script runs.
=> Fixed `cgmanfiest.json` PR check to support Mariner LUA scripts.

toolkit/docs/building/building.md
=> Fix misspelling of targeted

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> upgrade sudo to version 1.9.12p1

docs.md
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> removed references to marketplace VM

docs.md
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> removed another reference to containers

SPECS/distroless-packages/distroless-packages.spec
---
This PR replaces the `prebuilt-ca-certificates-base` with `prebuilt-ca-certificates` in the distroless minimal container image. It also add `tzdata` to it. These changes are required to unblock AKS adoption by making the Mariner distroless minimal a drop in replacement for gcr distroless container.
- Updated `distroless-packages.spec` to replace prebuilt-ca-certificates-base with prebuilt-ca-certificates and add tzdata.
**NO**
- Tested the container image locally.
=> add prebuilt-ca-certificates and tzdata to 2.0 distroless minimal container

SPECS/distroless-packages/distroless-packages.spec
---
This PR replaces the prebuilt-ca-certificates-base with prebuilt-ca-certificates in the distroless minimal container image. It also add tzdata to it. These changes are required to unblock AKS adoption by making the Mariner distroless minimal a drop in replacement for gcr distroless container.
- Updated distroless-packages.spec to replace prebuilt-ca-certificates-base with prebuilt-ca-certificates and add tzdata.
**NO**
- #xxxx
- Tested the container image locally.
=> add prebuilt-ca-certificates and tzdata to 1.0 distroless minimal container

SPECS/sysstat/CVE-2022-39377.nopatch
---
sysstat: nopatch CVE-2022-39377 (N/A)
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-39377
=> sysstat: nopatch CVE-2022-39377 (N/A)

SPECS/libtiff/CVE-2022-3970.patch, SPECS/libtiff/libtiff.spec
---
libtiff patch CVE-2022-3970
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-3970
=> libtiff patch CVE-2022-3970

SPECS/libtiff/CVE-2022-3597.patch, SPECS/libtiff/CVE-2022-3598.nopatch, SPECS/libtiff/CVE-2022-3599.patch, SPECS/libtiff/CVE-2022-3626.nopatch, SPECS/libtiff/CVE-2022-3627.nopatch, SPECS/libtiff/CVE-2022-3970.patch, SPECS/libtiff/libtiff.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Libtiff patch

docs.md
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Removing references to microsoft email

SPECS/python3-twisted/python3-twisted.spec
---
The separate `python3-twisted` package I introduced in #4207 is creating binaries links, which conflict with `python-twisted` (Python 2 version of the package). I've updated the former to skip the links and provide only the Python 3 versions of the binaries.
**NOTE**: no `Release` bump, because we haven't published, yet.
- Re-named binaries provided by `python3-twisted`.
No.
- #4207
- Pipeline buddy builds.
=> Fixed `python-twisted` binaries conflicts.

SPECS/buildah/CVE-2022-27651.patch, SPECS/buildah/buildah.spec
---
Add patch for CVE-2022-27651
- CVE-2022-27651
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-27651
- Patch applied locally without issue
- Pipeline build id: 266377 (AMD64), 266378 (ARM64)
=> Patch buildah for CVE-2022-27651

SPECS/systemd/CVE-2022-3821.patch, SPECS/systemd/systemd-bootstrap.spec, SPECS/systemd/systemd.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch for CVE-2022-3821
- Add .patch file for CVE-2022-3821 for systemd
- Updated systemd.spec to include new patch file
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3821
- Patch applied to local version cleanly.
- Pipeline build id: 266017 (AMD64), 266016 (ARM64)
=> Patched `systemd` to fix CVE-2022-3821

toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/rpm/rpm.go, toolkit/tools/internal/sliceutils/sliceutils.go, toolkit/tools/internal/sliceutils/sliceutils_test.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
…4211)
---
This commit needs to be cherry-picked from branch `main` to branch `2.0` to get a successful RPMs build.
**NO**
=> Updated toolkit's package resolution to accept installed packages. (#4211)

SPECS/systemd/CVE-2022-3821.patch, SPECS/systemd/systemd.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add patch to systemd to resolve CVE-2022-3821
- Change systemd with patch for CVE-2022-3821
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3821
- Pipeline build id: 268613
ARM64: 268631
=> systemd: patch CVE-2022-3821

SPECS-EXTENDED/libtomcrypt/CVE-2019-17362.patch, SPECS-EXTENDED/libtomcrypt/libtomcrypt.spec
---
Patch for CVE-2019-17362 in `libtomcrypt`.
- Patched CVE-2019-17362 in `libtomcrypt`.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2019-17362
- Local build.
=> Patched CVE-2019-17362 in `libtomcrypt`.

SPECS/sysstat/sysstat.signatures.json, SPECS/sysstat/sysstat.spec, cgmanifest.json
---
Fixing CVE-2022-39377 by upgrading `sysstat` to version 12.7.1.
- Upgraded `sysstat` to version 12.7.1.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-39377
=> Upgraded `sysstat` to version 12.7.1 to fix CVE-2022-39377.

SPECS-EXTENDED/mutt/CVE-2021-32055.patch, SPECS-EXTENDED/mutt/mutt.spec
---
Patch CVE-2021-32055
- Patch CVE-2021-32055
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-32055
- Local Build
Buddy Build: 
- [AMD64 PR-4303](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=270567&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=246631ef-4e63-576d-3b21-bc52cd4b0a93&l=1790)
- [ARM64 PR-4303](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=270578&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520&l=32467)
=> Patch `mutt` CVE-2021-32055

SPECS/grpc/grpc.spec
---
- Change: make gRPC python package available to only AMD64
**YES/NO**
NO
- Pipeline build id: 271065
- Pipeline build id: 271064
=> Update gRPC python package to make it exclusive to AMD64

.github/workflows/check-package-cgmanifest.yml, SPECS-EXTENDED/libntlm/libntlm.signatures.json, SPECS-EXTENDED/libntlm/libntlm.spec, cgmanifest.json
---
Upgrading `libntlm` to version 1.6 to fix CVE-2019-17455.
- Upgraded `libntlm` to version 1.6.
- Updated CG manifest check to correctly parse the spec.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2019-17455
- Pipeline buddy build (ARM64) 269544.
=> Upgraded `libntlm` to version 1.6 to fix CVE-2019-17455.

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade to latest version of Blobfuse2
- Upgrade to latest version of Blobfuse2
**NO**
- Pipeline build id: 271520
=> Update Blobfuse2 version to 2.0.0

SPECS/nginx/nginx.spec
This change adds the http2 transport support to nginx.
=> Enable http2 support in nginx

toolkit/tools/imagegen/configuration/networkconfig.go
---
- Remove the systemd operation during image build as it breaks image build since the build chroot does not contain systemd. The systemd operation is also not needed for any custom features.
- Update networkconfig.go to remove systemd operations and related implementations
NO
- https://dev.azure.com/microsoft/OS/_workitems/edit/41459704/
=> Fix incorrect systemd operation during image build

SPECS/libarchive/CVE-2022-36227.patch, SPECS/libarchive/libarchive.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2022-36227
- Patch CVE-2022-36227
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-36227
- Local Build
=> Patch `libarchive` for CVE-2022-36227

SPECS/libxml2/CVE-2022-40303.patch, SPECS/libxml2/libxml2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch for CVE 2022-40303  https://nvd.nist.gov/vuln/detail/CVE-2022-40303
=> Patch libxml2 for CVE-2022-40303

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping Release for Mariner 2022 Update
=> Update Mariner Release for December 2022 Update

SPECS/kernel/CVE-2021-4037.nopatch, SPECS/kernel/CVE-2022-40768.nopatch
---
- Address cves
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-40768
- https://nvd.nist.gov/vuln/detail/CVE-2022-4037
- 
- n/a
=> Nopatch CVE-2022-40768 and CVE-2021-4037 for kernel

SPECS-SIGNED/livepatch-5.15.48.1-4.cm2-signed/livepatch-5.15.48.1-4.cm2-signed.spec
---
Reverting incorrect spec update made in #4257. I've also created a separate fix in our pipelines to prevent this from happening in the future.
- Reverted invalid spec change in `livepatch-5.15.48.1-4.cm2-signed.spec`.
No.
- #4257
- N/A, simple spec change.
=> Reverted invalid livepatch spec change.

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade Blobfuse2 to 2.0.1. This was necessary soon after 2.0.0 to ensure the GA release of blobfuse2 resolves after any preview versions.
- Upgrade Blobfuse2 to 2.0.1
NO
- Pipeline build id: 272725
=> Upgrade Blobfuse2 to 2.0.1

SPECS/emacs/CVE-2022-45939.patch, SPECS/emacs/emacs.spec
---
Apply upstream patch for emacs CVE-2022-45939
- Apply upstream patch for CVE-2022-45939
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-45939
- Local package build succeeded.
- Pipeline build id: 275155
=> Patch emacs for CVE-2022-45939

SPECS/tensorflow/tensorflow.spec
---
one of the runtime dep name is incorrect while installing the package.
- Change: correct package name for python3-markupsafe package
**YES/NO**
NO
- Pipeline build id: 273797
=> Update: TensorFlow correct package name

SPECS/kernel/CVE-2022-3910.nopatch, SPECS/kernel/CVE-2022-4127.nopatch, SPECS/kernel/CVE-2022-41849.nopatch, SPECS/kernel/CVE-2022-43945.nopatch, SPECS/kernel/CVE-2022-45869.nopatch
CVE-2022-3910, CVE-2022-4127, CVE-2022-41849, CVE-2022-43945, CVE-2022-4586
---
Address CVEs
- Address CVEs
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3910
- https://nvd.nist.gov/vuln/detail/CVE-2022-4127
- https://nvd.nist.gov/vuln/detail/CVE-2022-41849
- https://nvd.nist.gov/vuln/detail/CVE-2022-43945
- https://nvd.nist.gov/vuln/detail/CVE-2022-45869
NA
=> Nopatch kernel CVE-2022-3910, CVE-2022-4127, CVE-2022-41849, CVE-2022-43945, CVE-2022-4586

toolkit/imageconfigs/marketplace-gen1.json, toolkit/imageconfigs/marketplace-gen2-aarch64.json, toolkit/imageconfigs/marketplace-gen2.json
---
This change is to revert apparmor disable change made by [PR4188](https://github.com/microsoft/CBL-Mariner/pull/4118). Background and details can be found in linked issue
- revert apparmor disable change made by [PR4188](https://github.com/microsoft/CBL-Mariner/pull/4118)
NO
- [Task 42533643](https://microsoft.visualstudio.com/OS/_workitems/edit/42533643): [Mariner 1.0] Revert AppArmor disable change due to AKS customer regression
- Local image build
=> revert apparmor disable change

SPECS/rsync/CVE-2022-29154.patch, SPECS/rsync/rsync.spec
---
patch rsync CVE-2022-29154 from [upstream](https://github.com/WayneD/rsync/commit/b7231c7d02cfb65d291af74ff66e7d8c507ee871)
- patch rsync CVE-2022-29154 from [upstream](https://github.com/WayneD/rsync/commit/b7231c7d02cfb65d291af74ff66e7d8c507ee871)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-29154
- local package build
=> add patch for rsync CVE-2022-29154

SPECS/glib/CVE-2021-3800.patch, SPECS/glib/glib.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
add patch for glib CVE-2021-3800 
- add patch for glib CVE-2021-3800 
YES
- https://nvd.nist.gov/vuln/detail/CVE-2021-3800
- local toolchain and package build
=> add patch for glib CVE-2021-3800

SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
---
This pr adds in the hwdata and gawk dependencies to the rpm spec file, which are needed for the plugin to function
* Tue Dec 06 2022 Aditya Dubey <adityadubey@microsoft.com> - 3.4.0-3
- Adding in the hwdata and gawk dependencies
**NO**
Successfully generated the sriov rpm using a local build via the toolchain. Verified the rpm worked as intended by installing and running the rpm in a golden container for sriov and verified the pod functioned as intended (also reproduced the same successful results with the rpm built from the pipeline run linked below):
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=275910&view=results
=> Adding in the hwdata and gawk dependencies

SPECS/k3s/k3s-1.23.8.signatures.json, SPECS/k3s/k3s-1.23.8.spec, SPECS/k3s/k3s-1.24.3.signatures.json, SPECS/k3s/k3s-1.24.3.spec, SPECS/k3s/k3s.signatures.json, SPECS/k3s/k3s.spec, cgmanifest.json
---
The PR corrects the spec files for all the three minor versions of k3s with the corrected vendor tarball dependency versions. Earlier we were packaging some wrong versions from the upstream and this PR corrects them. The signature files have also been updated due to new vendor tarballs being created for each of the 3 versions.
The vendor tarball on the Mariner blob storage has also been updated by running the requisite pipeline.
- Update the vendor tarball with the corrected versions of the dependencies
**NO**
Built locally with the Mariner Toolchain.
BuddyBuild:
- AMD64 - [275850](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=275850&view=results)
- ARM64 - …
=> k3s: Update the vendor tarball with the corrected versions of the dependencies

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner 1.0 Release for December Update 2
=> Bump Mariner 1.0 Release version for December Update 2

SPECS/unbound/CVE-2022-3204.patch, SPECS/unbound/unbound.spec
---
add upstream [patch](https://github.com/NLnetLabs/unbound/commit/137719522a8ea5b380fbb6206d2466f402f5b554#diff-a2e718645e9a7975c151c2c206bf10b7ffcbaf57f81251402e3f65233dadb3efL2563) for Unbound CVE-2022-3204
- add upstream [patch](https://github.com/NLnetLabs/unbound/commit/137719522a8ea5b380fbb6206d2466f402f5b554#diff-a2e718645e9a7975c151c2c206bf10b7ffcbaf57f81251402e3f65233dadb3efL2563) for Unbound CVE-2022-3204
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-3204
- local package build
=> add patch for Unbound CVE-2022-3204

SPECS/selinux-policy/macros.selinux-policy, SPECS/selinux-policy/selinux-policy.signatures.json, SPECS/selinux-policy/selinux-policy.spec
---
Some of our packages like `openvswitch-selinux-policy` depend on `selinux-policy` RPM macros, which are missing in our packages. This PR adds the missing macros into the `selinux-policy-devel` package.
- Added `selinux-policy` RPM macros.
No.
- Local package build and installation.
=> Added `selinux-policy` macros.

SPECS/moby-containerd/CVE-2022-23471.patch, SPECS/moby-containerd/moby-containerd.spec
---
Fix CVE-2022-23471 for moby-containerd SPEC.
- Change
Fix CVE-2022-23471 for moby-containerd
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-23471
=> Fix CVE-2022-23471 for moby-containerd

SPECS/sqlite/CVE-2022-46908.patch, SPECS/sqlite/sqlite.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Backport patch from https://sqlite.org/src/info/cefc032473ac5ad2 to apply to our source files.
- Backport commit cefc032473ac5ad2 and adjust to apply correctly.
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/42600039
- https://nvd.nist.gov/vuln/detail/CVE-2022-46908
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=277771&view=results
- Local toolchain rebuild in progress
=> Add patch to sqlite to resolve CVE-2022-46908

SPECS/nodejs/nodejs.spec
---
Nodejs code uses the Artistic 2.0 license as listed [here](https://github.com/nodejs/node/blob/main/LICENSE#L1110). Update nodejs.spec to include reference to this license.
- Change nodejs.spec to reference Artistic 2.0 license
**NO**
- Pipeline build id: 277762
=> nodejs: add reference to artistic 2.0 license

toolkit/scripts/toolchain.mk
---
Modify toolchain makefile so toolchain RPM packages are only downloaded once. Modify the wget command with "-nv --no-clobber" arguments, which are already used in another spot of this same file. This saves time building locally since once the toolchain is downloaded, they will not be repeatedly downloaded again.
- Change toolchain.mk to wget toolchain rpms with "-nv --no-clobber" arguments
**YES**
- Local build
=> Optimize toolchain rpm download

toolkit/docs/building/building.md
Correct the host `packages.microsoft.com` in the link text to match the correct URL.
---
This corrects a simple typo in the documentation
- Correct the host `packages.microsoft.com` in the link text to match the correct URL.
**NO**
- N/A
- N/A
- Preview - it's just an edit to documentation
=> Correct typo in overview

SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.8.0.spec, SPECS/coredns/coredns-1.8.4.spec, SPECS/coredns/coredns-1.8.6.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.5.0.spec, SPECS/etcd/etcd-3.5.1.spec, SPECS/flannel/flannel.spec, SPECS/glide/glide.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/CVE-2022-41717.patch, SPECS/golang/golang-1.17.spec, SPECS/golang/golang.spec, SPECS/helm/helm.spec, SPECS/libnvidia-container/libnvidia-container.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/node-problem-detector/node-problem-detector.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, SPECS/telegraf/telegraf.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix for CVE-2022-41717 and bump up golang dependencies minor release version.
- Change
Fix for CVE-2022-41717
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-41717
=> Fix for CVE-2022-41717

SPECS/mariner-release/mariner-release.spec
Full monthly 2.0 release for December 2022
=> Bump Mariner 2.0 Release for December Update 3

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Mariner 1.0 December 2022 Update 3
=> Bump Mariner 1.0 Release for December Update 3

SPECS/qemu/CVE-2022-3872.patch, SPECS/qemu/qemu.spec
---
Add a patch for Qemu to fix CVE-2022-3872
- Adress CVE-2022-3872
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3872
- Pipeline build id: Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=280037&view=results
=> qemu: Patch CVE-2022-3872

SPECS/pyproject-rpm-macros/pyproject-rpm-macros.spec, SPECS/python-coverage/python-coverage.spec, SPECS/python-nocasedict/python-nocasedict.spec, SPECS/python-pbr/python-pbr.spec, SPECS/python-prettytable/python-prettytable.spec, SPECS/python-pynacl/python-pynacl.spec, SPECS/python-tqdm/python-tqdm.spec, SPECS/python-twisted/python-twisted.spec, SPECS/python-virtualenv/python-virtualenv.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The following python packages are using tox as a part of their package tests. The 3.27.1 version (or higher) is being specified as a breaking change was introduced in tox v4.0.0 to the way some variables are handled.
pyproject-rpm-macros
python-coverage
python-nocasedict
python-pbr
python-prettytable
python-pynacl
python-tqdm
python-twisted
python-virtualenv
- Specified tox version for pip install as >=3.27.1 and < 4.0.0 to allow for patches to the 3.X.X version to be taken
**NO**
- x86 buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=278979&view=results
- ARM64 buddy build: …
=> Specify tox ver. to not use 4.0.0+ to correct some python package tests

SPECS/curl/CVE-2022-43551.patch, SPECS/curl/CVE-2022-43552.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2022-43551 and CVE-2022-43552 in curl
- Patch CVE-2022-43551 and CVE-2022-43552 in curl
**YES**
- #xxxx
- https://www.openwall.com/lists/oss-security/2022/12/21/1
- https://www.openwall.com/lists/oss-security/2022/12/21/2
- Local builds
- Pipeline build in progress
=> Patch curl to resolve CVE-2022-43551 and CVE-2022-43552

SPECS/qemu-kvm/CVE-2021-4207.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Patches CVE-2021-4207
- Patch CVE-2021-4207
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4207
- Pipeline build id: Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=281664&view=results
=> Patch qemu-kvm to fix CVE-2021-4207

SPECS/qemu/CVE-2021-3929.patch, SPECS/qemu/CVE-2021-4207.patch, SPECS/qemu/qemu.spec
---
Add patches for Qemu to fix CVE-2021-3929, CVE-2021-4207
- Patched CVE-2021-3929, CVE-2021-4207
**NO**
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-3929
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-4207
- Pipeline build id: Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=280371&view=results
=> qemu: Patched CVE-2021-3929, CVE-2021-4207

SPECS/qemu-kvm/CVE-2021-3929.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
I added a patch file for CVE-2021-3929.
I added a patch file for CVE-2021-3929.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3929
- Pipeline build id: 283218
=> Patch CVE-2021-3929 in qemu-kvm

SPECS/ctags/CVE-2022-4515.nopatch, SPECS/ctags/ctags.spec
---
Created a nopatch file for CVE-2022-4515
- created a nopatch with explanation for why it does not affect us in 2.0 version
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-4515
- Pipeline build id: 284102
=> nopatch CVE-2022-4515 for ctags in 2.0

SPECS/helm/helm.spec
---
Introduce the helm self-tests
- Enable the check tests
**NO**
https://microsoft.visualstudio.com/OS/_workitems/edit/42721162
- Tests were run and passed, verified in the log from Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=281671&view=results
=> Enabled helm self checks

SPECS/libksba/CVE-2022-47629.patch, SPECS/libksba/libksba.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Addresses CVE-2022-47629
- Backport patch from [this](https://dev.gnupg.org/T6284) link
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-47629#range-8700773
- AMD64 [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=286259&view=results)
- ARM64 [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=286260&view=results)
- Pipeline build id: 286142
=> Patch CVE-2022-47629 in libksba

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec, SPECS/grub2/CVE-2022-2601.patch, SPECS/grub2/grub2.spec
---
Patches CVE-2022-2601
- Patched CVE-2022-2601
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2601
- Pipeline build id: 283832
=> grub2: patch CVE-2022-2601 in 2.0

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Update Mariner Release for January update
=> Bump Mariner for January Update

SPECS/krb5/CVE-2022-42898.patch, SPECS/krb5/krb5.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Addresses CVE-2022-42898 for Krb5
- Backport patch from this [commit](https://github.com/krb5/krb5/commit/ea92d2f0fcceb54a70910fa32e9a0d7a5afc3583)
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-42898
- Local build
- [AMD64 Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=287525&view=results) - PASS
- [ARM64 Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=287526&view=results) - PASS
=> Patch CVE-2022-42898 in krb5

SPECS/coredns/generate_source_tarball.sh, SPECS/etcd/generate_source_tarball.sh
---
create script to generate vendored modules tarball for etcd and coredns
- Change
- Change
- Change
**NO**
- #xxxx
=> create script to generate vendored modules tarball for etcd and coredns

SPECS/ansible/ansible.spec
---
Fixed package tests for `ansible` by selecting latest version of tox prior to 4.0.0. pip always pulls the latest version by default, specifying a version resolves the test issue.
Specify tox 3.27.1 or better but less then 4.0.0 in the ansible.spec file
**NO**
- AMD Buddy Build Pipeline build id: 291867
- ARM Buddy Build Pipeline build id: 291810
=> Specify tox version to fix ansible package tests

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imager/imager.go
---
Package installation for setup chroot during PXE boot process has been failing as tdnf was not able to determine the correct repo file to look at. Resolve the error by moving the package repo update function call before trying to perform setup chroot package installation so that tdnf will be fed with the correct package repo file
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/42951298/
=> Fix package installation failure for PXE boot scenario

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Bump Mariner 1.0 Release for January Update 2"

README.md, toolkit/docs/security/iso-image-verification.md
---
Add instructions for verifying our pre-built ISO images.
- `iso-image-verification.md`: Page added with instructions for checking the integrity of the ISO image as well as the checksum file
- `README.md`: Add link to the above documentation
- `README.md`: Fix minor formatting issues with headers and errant spaces.
**NO**
- Used included script to verify 1.0 and 2.0 images
=> Add ISO image verification instructions

SPECS/git/git.signatures.json, SPECS/git/git.spec, cgmanifest.json
---
Upgrade git to v2.33.6 to address critical CVE-2022-23521
- Upgrade git to v2.33.6 to address critical CVE-2022-23521
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-23521
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=297052&view=results
=> Upgrade git to v2.33.6 to address critical CVE-2022-23521 & CVE-2022-41903

SUPPORT.md, toolkit/README.md, toolkit/docs/building/building.md
added an explanation of the packages.microsoft.com repo structure.
=> packages.microsoft.com repo structure info

SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
- [x ] LICENSE-MAP files are up-to-date …
=> application-gateway-kubernetes-ingress: Fix  CVE-2021-4235 & CVE-2022-3064

SPECS/mariner-release/mariner-release.spec
Bump Mariner Release for January 2023 Update 2
=> Bump Mariner Release Mariner 2.0 January 2023 Update 2

SPECS/openvswitch/CVE-2021-3905.nopatch
---
Add CVE-2021-3905.nopatch to openvswitch
- Add CVE-2021-3905.nopatch to openvswitch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3905
- Pipeline build id: N/A
=> openvswitch - add CVE-2021-3905.nopatch

SPECS/openldap/openldap.spec
Enable building with cyrus-sasl
---
Enable building with cyrus-sasl
NO
local build
=> enable cyrus sasl

cgmanifest.json
---
add missing coredns version in cgmanifest
- Change
- Change
- Change
**NO**
- #xxxx
=> add missing coredns version in cgmanifest

SPECS/mozjs60/CVE-2023-22895.patch, SPECS/mozjs60/mozjs60.spec
---
Patch mozjs60 to address CVE-2023-22895
- Patch mozjs60 to address CVE-2023-22895
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-22895
Buddy Build: validating
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=299329&view=results)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=299301&view=results)
=> Patch mozjs60 to address CVE-2023-22895

SPECS/pkgconf/CVE-2023-24056.patch, SPECS/pkgconf/pkgconf.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Backport https://gitea.treehouse.systems/ariadne/pkgconf/commit/628b2b2bafa5d3a2017193ddf375093e70666059 to pkgconf 1.8.0
- Backport https://gitea.treehouse.systems/ariadne/pkgconf/commit/628b2b2bafa5d3a2017193ddf375093e70666059 to pkgconf 1.8.0
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/43157204
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-24056
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=302144&view=results
=> Patched pkgconf to address CVE-2023-24056

SPECS/vim/CVE-2023-0433.patch, SPECS/vim/vim.spec
---
- Add patch to resolve CVE-2023-0433
- Add patch to resolve CVE-2023-0433
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-0433
- Local Build
=> [1.0] Resolve vim CVE-2023-0433

SPECS-EXTENDED/whois/whois.signatures.json, SPECS-EXTENDED/whois/whois.spec, cgmanifest.json
whois command need /etc/services to work.
/etc/services file is contained in iana-etc package. This change add requirement of iana-etc package.
whois command without /etc/services:
```
getaddrinfo(whois.verisign-grs.com): Servname not supported for ai_socktype
```
---
whois command need /etc/services to work
/etc/services file is contained in iana-etc package. This change add requirement of iana-etc package.
**NO**
- #xxxx
=> whois command need /etc/services to work

SPECS/redis/CVE-2022-35977.patch, SPECS/redis/CVE-2023-22458.patch, SPECS/redis/redis.spec
---
- Add patch for CVE-2022-35977 and CVE-2023-22458
- Add patch for CVE-2022-35977 and CVE-2023-22458
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-35977
- https://nvd.nist.gov/vuln/detail/CVE-2023-22458
- Local Build
=> [1.0] Resolve redis CVE-2022-35977, CVE-2023-22458

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
- cmake build fails during the toolchain build phase because cmake is now dependent on system curl instead of the bundled one during the build process and during the toolchain build phase, curl is currently not installed when building cmake. Thus, resolve the error by moving installation of curl before building cmake during toolchain build phase.
YES
- Pipeline build id: x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=303881&view=results
-  ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=303882&view=results
=> [1.0] Modify toolchain build order to resolve cmake build failure

SPECS/mariner-release/mariner-release.spec
Bump Mariner 2.0 Release for Feb 2023 Update
=> Bump Mariner 2.0 Release for Feb 2023 Update

SPECS/apr-util/apr-util.signatures.json, SPECS/apr-util/apr-util.spec, cgmanifest.json
---
Update apr-util to 1.6.3
Update license to use SPDX identifier
-Update apr-util to 1.6.3
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-25147
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304073&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304093&view=results
=> Update apr-util to 1.6.3 for CVE-2022-25147

SPECS/httpd/httpd-2.4.53-blfs_layout-3.patch, SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec, cgmanifest.json
Fixes CVE-2022-36760
---
CVE-2022-36760
CVE-2022-36760
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-36760
- Pipeline build id: 304492
- Clean-up run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304774&view=results
=> Update httpd to version 2.4.55 for CVE-2022-36760

.github/workflows/check-manifests.yml, .github/workflows/go-test-coverage.yml
---
GitHub workflows updated to use `ubuntu-latest`. This is because https://github.com/actions/runner-images/issues/6002 is requiring updates. 
- GitHub workflows updated to use `ubuntu-latest`
**NO**
- https://github.com/actions/runner-images/issues/6002
- See PR : https://github.com/microsoft/CBL-Mariner/pull/4787
=> Update GitHub workflows to use latest Ubuntu

SPECS/ltp/ltp.signatures.json, SPECS/ltp/ltp.spec, cgmanifest.json
---
Updating our LTP package to bring in a few more kernel tests and test fixes.
**NOTE**: submodules tarball's contents didn't change, it's not a typo.
- Updated `ltp` to version 20230127.
- Fixed package's `URL` tag.
No.
- Local package build with `RUN_CHECK=1`
=> Updated `ltp` to version 20230127.

toolkit/docs/building/building.md
Signed-off-by: Easwar Hariharan <easwar.hariharan@microsoft.com>
---
Add adjectives to describe how REPO_LIST is to be provided to the build system.
- Docs change
**NO**
=> docs: Make clearer how REPO_LIST is to be used

SPECS/hyperv-daemons/CVE-2022-27666.nopatch
---
Nopatch hyperv-daemons for CVE-2022-27666
- Nopatch hyperv-daemons for CVE-2022-27666
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-27666
=> Nopatch hyperv-daemons for CVE-2022-27666

SPECS/redis/redis.signatures.json, SPECS/redis/redis.spec, cgmanifest.json
---
Bump version 6.2.9 for CVE-2022-35977 and CVE-2023-22458
Remove CVE-2022-3647.patch as it is fixed by update
1.0 PR #4765
- Bump version 6.2.9 for CVE-2022-35977 and CVE-2023-22458
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-35977
- https://nvd.nist.gov/vuln/detail/CVE-2023-22458
- AMD Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305309&view=results
- ARM Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305336&view=results
=> redis: update to 6.2.9 for CVE-2022-35977 and CVE-2023-22458

SPECS/libtiff/CVE-2022-48281.patch, SPECS/libtiff/libtiff.spec
---
Patch CVE-2022-48281
1.0 PR: https://github.com/microsoft/CBL-Mariner/pull/4755
- Patch CVE-2022-48281
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-48281
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305400&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305429&view=results
=> Patch libtiff for CVE-2022-48281

SPECS/tpm2-tss/CVE-2023-22745.patch, SPECS/tpm2-tss/tpm2-tss.spec
---
Patch tpm2-tss for CVE-2023-22745
1.0 PR: https://github.com/microsoft/CBL-Mariner/pull/4726
- Patch tpm2-tss for CVE-2023-22745
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-22745
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305441&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305474&view=results
=> Patch tpm2-tss for CVE-2023-22745

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
Update sudo to 1.9.12p2 to address CVE-2023-22809
Lint changelog (fix spacing)
1.0 PR: https://github.com/microsoft/CBL-Mariner/pull/4801
- Update sudo to 1.9.12p2 to address CVE-2023-22809
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-22809
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305479&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305499&view=results
=> Update sudo to 1.9.12p2 to address CVE-2023-22809

SPECS/libksba/CVE-2022-3515.patch, SPECS/libksba/libksba.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
CVE-2022-3515
CVE-2022-3515
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-3515
- Pipeline build id: 305116
=> libksba: CVE-2022-3515

SPECS/tmux/CVE-2022-47016.patch, SPECS/tmux/tmux.spec
---
CVE-2022-47016
CVE-2022-47016
no
- #xxxx
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305334&view=results
=> tmux: CVE 2022 47016 

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, SPECS/tmux/CVE-2022-47016.patch, SPECS/tmux/tmux.spec, cgmanifest.json
---
CVE 2023 22809
CVE 2023 22809
no
- #xxxx
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305326&view=results
=> sudo: CVE-2023-22809

SPECS/pixman/CVE-2022-44638.patch, SPECS/pixman/pixman.spec, SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, SPECS/tmux/CVE-2022-47016.patch, SPECS/tmux/tmux.spec, cgmanifest.json
---
CVE-2022-44638
CVE-2022-44638
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-44638
- Pipeline build id: 305245
=> pixman: CVE-2022-44638

SPECS/binutils/CVE-2022-4285.patch, SPECS/binutils/binutils.spec, SPECS/pixman/CVE-2022-44638.patch, SPECS/pixman/pixman.spec, SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, SPECS/tmux/CVE-2022-47016.patch, SPECS/tmux/tmux.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
CVE-2022-4285
CVE-2022-4285
yes
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-4285
- Pipeline build id: 306049
306053
=> binutils: CVE 2022 4285

SPECS/binutils/CVE-2022-4285.patch, SPECS/binutils/binutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch binutils for CVE-2022-4285
- Patch binutils for CVE-2022-4285
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-4285
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305815&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305816&view=results
- Full build
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306121&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306122&view=results
=> Patch binutils for CVE-2022-4285

SPECS/kernel/CVE-2023-0266.nopatch
---
Nopatch kernel to address CVE-2023-0266
- Nopatch kernel to address CVE-2023-0266
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0266
=> Nopatch kernel to address CVE-2023-0266

SPECS/mariadb/CVE-2022-47015.patch, SPECS/mariadb/mariadb.spec
---
Patch mariadb for CVE-2022-47015
- Patch mariadb for CVE-2022-47015
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-47015
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306382&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306431&view=results
With check sections 100%
=> Patch mariadb for CVE-2022-47015

SPECS/influx-cli/influx-cli.spec
---
When trying to install `influx-cli` package it tries to install `influx-cli-bash-completion` as it supplements `bash-completion` package and also depends on it. Fixing naming for it in the spec file.
- Fixed name reference to `bash-completion` so that `influx-cli-bash-completion` does not conflict with it when installing.
**NO**
- Pipeline build id: [Official pipeline](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307304&view=results)
=> Fixing influx-cli-bash-completion package conflicting with bash-completion

SPECS-EXTENDED/podman/podman.spec
---
Revert podman to version 4.1.1-5. The later revisions were bumped only to re-compile this package with golang 1.19, but it doesn't build properly with golang 1.19.
- Change podman to version 4.1.1-5
**NO**
=> podman: revert to release 5

SPECS/unzip/CVE-2021-4217.patch, SPECS/unzip/unzip.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
CVE 2021 4217
- Change
- Change
- Change
CVE 2021 4217
no
- #xxxx
CVE 2021 4217
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307082&view=results
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307084&view=results
=> unzip: CVE 2021 4217

SPECS/tmux/CVE-2022-47016.patch, SPECS/tmux/tmux.spec
---
Patch tmux for CVE-2022-47016
- Patch CVE-2022-47016
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-47016
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307237&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307238&view=results
=> Patch tmux for CVE-2022-47016

SPECS/Cython/Cython.signatures.json, SPECS/Cython/Cython.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Cython 0.29.33 has fixes for [failing package tests due to a deprecation in numpy](https://github.com/cython/cython/pull/5190). Let's just take the full patch version upgrade to pick up the other bug fixes available in that release.
- `Cython`: Upgrade from 0.29.32 -> 0.29.33
**YES**
- Test build: [in progress](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=308493)
=> Upgrade Cython to 0.29.33 to fix failing package tests

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Release for Mariner 1.0 Feb Update 2
=> Bump Release for Mariner 1.0 Feb Update 2

SPECS/apr/apr.signatures.json, SPECS/apr/apr.spec, cgmanifest.json
---
Upgrade package apr to 1.7.2 to fix CVE-2022-24963
- NA
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-24963
Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=308505&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=308484&view=results)
=> Upgrade package apr to 1.7.2 to fix CVE-2022-24963

SPECS/qemu/qemu.spec
---
Adds missing romfiles to system-aarch64-core package.
- Adds missing romfiles to system-aarch64-core package.
**NO**
=> qemu: Add, don't delete, romfiles when building for aarch64

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec, SPECS/grub2/CVE-2022-3775.patch, SPECS/grub2/grub2.spec
---
CVE-2022-3775
CVE-2022-3775
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-3775
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305337&view=results
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=305338&view=results
=> grub2: CVE-2022-3775

SPECS/libconfuse/CVE-2022-40320.patch, SPECS/libconfuse/libconfuse.spec
---
CVE-2022-40320
CVE-2022-40320
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-40320
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306941&view=results
=> libconfuse: CVE-2022-40320

SPECS/helm/CVE-2022-23524.patch, SPECS/helm/helm.spec
---
CVE-2022-23524
CVE-2022-23524
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-23524
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306967&view=results
=> helm: CVE-2022-23524

SPECS/syslog-ng/CVE-2022-38725.patch, SPECS/syslog-ng/syslog-ng.spec
---
CVE-2022-38725
- Change
- Change
- Change
CVE-2022-38725
no
- #xxxx
CVE-2022-38725
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=307003&view=results
=> syslog-ng: CVE-2022-38725

SPECS/helm/CVE-2023-25165.patch, SPECS/helm/helm.spec
---
Patch for CVE-2023-25165
- CVE-2023-25165
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-25165
Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=310339&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=310340&view=results)
=> Patch helm for CVE-2023-25165

SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
---
Fix build for package
- Drop generating docs to fix build
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/4717
- NA
- Local Build
BuddyBuild:
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=309082&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520&l=87607)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=309090&view=results)
=> Fix build-break for libappstream-glib

SPECS/less/CVE-2022-46663.patch, SPECS/less/less.spec
---
Patch less with CVE 2022 46663
- CVE-2022-46663
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-46663
- Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=311053&view=results)
=> Patch less with CVE-2022-46663

SPECS/libtiff/CVE-2023-0800.patch, SPECS/libtiff/libtiff.spec
---
CVE-2023-0800 CVE-2023-0801 CVE-2023-0802 CVE-2023-0803 CVE-2023-0804
**NO**
- CVE-2023-0800 CVE-2023-0801 CVE-2023-0802 CVE-2023-0803 CVE-2023-0804
- [Pipeline build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=310655&view=results)
- Local build
=> libtiff: CVE 2023-0800

SPECS/strongswan/CVE-2022-40617.patch, SPECS/strongswan/strongswan.spec
---
CVE-2022-40617
CVE-2022-40617
no
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-40617
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=306944&view=results
=> strongswan: CVE 2022 40617

.gitignore, toolkit/Makefile
---
If we build with `USE_CCACHE=y` then we end up with a `ccache` directory created in the repo's root. There's ongoing discussion where it should land (user's home directory, repo's `build` directory, elsewhere?), so for now I'm only marking it as ignored.
- Added `ccache` to ignored directories.
No.
- N/A
=> Ignored `ccache` directory.

SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec, SPECS/cyrus-sasl/cyrus-sasl.spec
---
Solve cyrus-sasl dependency issue when building kata images
- cyrus-sasl
- cyrus-sasl-bootstrap
**NO**
- Able to build kata image locally
=> cyrus-sasl: bump release

SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec, SPECS/cyrus-sasl/cyrus-sasl.spec
Pull cyrus-sasl fix into 2.0: #4894
=> cyrus-sasl: bump release (#4894)

SPECS/python-cryptography/CVE-2023-23931.patch, SPECS/python-cryptography/python-cryptography.spec
---
This PR applies a patch to python-cryptography to fix CVE-2023-23931.
- Updated the package spec file to apply the patch to fix CVE-2023-23931.
**NO**
N/A
- https://nvd.nist.gov/vuln/detail/CVE-2023-23931
Buddy build
- AMD64 Pipeline build id: 316240
- ARM64 Pipeline build id: 316175
Thanks to Pawel for helping with correctly applying the patch.
=> patch python cryptography for CVE-2023-23931

toolkit/docs/nvidia/nvidia.md
---
Fix the documentation for Nvidia repo download
- Update wget URL for mariner-nvidia.repo
**NO**
- run the wget command locally
=> [1.0] Update wget URL for mariner-nvidia.repo

toolkit/docs/nvidia/nvidia.md
---
Fix the documentation for Nvidia repo download
- Update wget URL for mariner-nvidia.repo
**NO**
- run the wget command locally
=> [2.0] Fix URL to mariner-nvidia.repo

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump mariner-release for February 2023 Release 3.
- `mariner-release` release number is now 57
**YES**
- N/A
=> Bump mariner-release for February 2023 Release 3

SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec, SPECS/kernel-hci/0022-net-mlx5-Bridge-refactor-groups-sizes-and-indices.patch, SPECS/kernel-hci/0023-net-mlx5-Bridge-rename-filter-fg-to-vlan_filter.patch, SPECS/kernel-hci/0024-net-mlx5-Bridge-extract-VLAN-push-pop-actions-creati.patch, SPECS/kernel-hci/0025-net-mlx5-Bridge-implement-infrastructure-for-VLAN-pr.patch, SPECS/kernel-hci/0026-net-mlx5-Bridge-implement-QinQ-support.patch, SPECS/kernel-hci/kernel-hci.spec
---
This PR adds patches to enable QinQ support to kernel-hci
- Add QinQ support to kernel-hci
**NO**
=> kernel-hci: Add QinQ patches

SPECS/python3/CVE-2023-24329.patch, SPECS/python3/python3.spec
---
Patch CVE-2023-24329
- Patch CVE-2023-24329
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-24329
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=317860&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=317861&view=results
=> Patch python3 to address CVE-2023-24329

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
---
- Upgrade erlang to version 25.2
**NO**
- AMD64 Buddy Build ID: 310109, 310883, 316516
- ARM64 Buddy Build ID: 310856, 310890, 316517
=> Upgrade erlang to version 25.2 to support rabbitmq

SPECS/gnutls/CVE-2023-0361.patch, SPECS/gnutls/gnutls.spec
---
Patch CVE-2023-0361
- Patch CVE-2023-0361
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0361
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=317980&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=317981&view=results
=> Patch gnutls to address CVE-2023-0361

SPECS/moby-containerd/CVE-2023-25173.patch, SPECS/moby-containerd/moby-containerd.spec
---
Patch CVE-2023-25173
- Patch CVE-2023-25173
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-25173
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=318591&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=318594&view=results
=> Add patch to fix CVE-2023-25173

SPECS/fluent-bit/fluent-bit.signatures.json, SPECS/fluent-bit/fluent-bit.spec, cgmanifest.json
---
Upgrade fluent-bit to latest upstream version to support certain customer requirements. Major version bump here has been approved by leads.
- Upgrade fluent-bit from 1.9.6 to 2.0.9
- Explicitly disable luajit- not on before, new behavior places a vendored static library right in `%{_libdir}`, which is less than desirable.
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319280&view=results)
=> Upgrade fluent-bit to 2.0.9

SPECS/helm/CVE-2023-25165.patch, SPECS/helm/helm.spec
---
Patch CVE-2023-25165
- Patch CVE-2023-25165
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-25165
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319349&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319350&view=results
=> Add patch to fix CVE-2023-25165

SPECS/clamav/clamav.signatures.json, SPECS/clamav/clamav.spec, SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec, SPECS/cyrus-sasl/cyrus-sasl.spec, SPECS/haproxy/haproxy.signatures.json, SPECS/haproxy/haproxy.spec, cgmanifest.json
Pull the following fixes:
#4957 
#4905 
#4881
=> Pull 2.0 fixes for: cyrus-sasl, clamav, haproxy

SPECS/moby-containerd/CVE-2023-25153.patch, SPECS/moby-containerd/moby-containerd.spec
---
Patch CVE-2023-25153
- Patch CVE-2023-25153
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-25153
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319452&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319453&view=results
=> Add patch to fix CVE-2023-25153

SPECS/mariner-release/mariner-release.spec
---
mariner-release: bump to version 35 for March 2023 update 1
- mariner-release: bump to version 35 for March 2023 update 1
**NO**
- N/A trivial change
=> mariner-release: bump to version 35 for March 2023 update 1

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade Blobfuse2 to latest version
- Upgrade Blobfuse2 to latest version
NO
- #xxxx
- Pipeline build id: 317866
=> Upgrade Blobfuse2 to 2.0.2

SPECS/coreutils/coreutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/tags
- amd64 toolchain build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=312396&view=results
- arm64 toolchain build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=312397&view=results
---
Skip pwd-long tests from coreutils which is failing in chroot
- Run pwd-long test from Makefile before running the check section
**YES**
- Pipeline build id: 312393
=> Skip pwd-long tests from coreutils which is failing in chroot

.github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/check-spec.yml, .github/workflows/go-test-coverage.yml
---
Backport from https://github.com/microsoft/CBL-Mariner/pull/4789
GitHub workflows updated to use `ubuntu-latest`. This is because https://github.com/actions/runner-images/issues/6002 is requiring updates. 
- Update workflows to use latest Ubuntu
**NO**
- https://github.com/actions/runner-images/issues/6002
- See workflows below :)
=> Update workflows in 1.0 to use latest Ubuntu

SPECS/python2/CVE-2023-24329.patch, SPECS/python2/python2.spec
---
Fixed the broken patch for CVE-2023-24329 in python2
- Fixed the broken patch for CVE-2023-24329 in python2. isascii() is only available from python 3.7 and onward. Fixed original patch build error by copying [python's implementation of isascii()](https://github.com/python/cpython/blob/main/Lib/curses/ascii.py).
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2023-24329
- Tested patch change locally
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=322549&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=322550&view=results
=> Fix patch to address CVE-2023-24329

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner 1.0 release for March 2023 Update
=> Bump Mariner 1.0 release for March 2023 Update

SPECS/gnutls/CVE-2023-0361.patch, SPECS/gnutls/gnutls.spec
---
gnutls: apply patch to fix CVE-2023-0361
- Add patch to fix CVE-2023-0361
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-0361 ((NIST's tagged patch is for tlsfuzzer. The actual gnutls fix gets mentioned by the original gitlab issue))
- https://gitlab.com/gnutls/gnutls/-/commit/22e3dc0c415654d0ac2170209e763175c7547069
- Pipeline build id: [322635](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=322635&view=results)
=> gnutls: Apply patch to fix CVE-2023-0361

SPECS/systemd/systemd.spec
---
Build with tpm2-tss to enable TPM2 support in systemd-cryptenroll/systemd-cryptsetup
Add systemd dep on tpm2-tss
package libcryptsetup-token-systemd-tpm2.so in rpm
no
ado bug:
https://microsoft.visualstudio.com/OS/_workitems/edit/43591705
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=323093&view=results
=> Build with tpm2-tss to enable TPM2 support in systemd-cryptenroll/systemd-cryptsetup

SPECS/harfbuzz/harfbuzz.spec
Build Break: Add pkg-config to harfbuzz
=> Build Break: Add pkg-config to harfbuzz

SPECS/graphviz/graphviz.spec
---
Graphviz errors when trying to render text since there aren't any default GUI fonts in Mariner, so this adds some default fonts.
- Added freefonts requirement to graphviz
- Linted graphviz spec file
NO
- Pipeline build id: 323756 (AMD64), 323757 (ARM64)
=> Adding freefont to graphviz

SPECS/harfbuzz/harfbuzz.spec
---
Fix build break for harfbuzz
- Add BR on cairo instead of pkgconfig(cairo)
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/4962
- NA
- Local Build.
Full Build: [Validating]
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=323518&view=logs&s=444ee1b5-8b3f-5598-a629-e88326f0c2f9)
Buddy Build: [Passed]
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=323537&view=logs&j=21e55549-fa44-57d8-4936-64132e3ceec0&t=0085d9b2-2408-5abe-87ce-b702734e35d8&l=1732)
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId= …
=> harfbuzz: add cairo as BR to resolve build-break

SPECS/python-cherrypy/python-cherrypy.spec
---
Fixing ptest for python-cherrypy 
- Change: Suppress warning that was causing the whole build to fail
**YES/NO**
NO
- Pipeline build id: [324077](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=324077&view=results)
=> Fix python-cherrypy ptest failing

SPECS/rust/rust.signatures.json
---
A recent upgrade of rust sources was done in the blobstore. We missed to update the signatures.
Reference: [pipeline run](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=325475&view=results)
NA
**NO**
- NA
- NA
- Full Build: [in progress](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=326388&view=results)
=> rust: update signatures to fix build break

SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec, cgmanifest.json
---
Update httpd version to 2.4.56
- Update httpd version to 2.4.56 to fix CVE-2023-27522, CVE-2023-25690
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-27522
- https://nvd.nist.gov/vuln/detail/CVE-2023-25690
- x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327191&view=results
- aarch64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327192&view=results
=> httpd: upgrade httpd to 2.4.56 to fix CVE-2023-27522, CVE-2023-25690 

SPECS-EXTENDED/python-msal/python-msal.signatures.json, SPECS-EXTENDED/python-msal/python-msal.spec, SPECS-EXTENDED/python-msrestazure/python-msrestazure.signatures.json, SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec
---
- python-msrestazure: change source0 to %{name}-%{version}
- python-msal: change source0 to %{name}-%{version}
**NO**
- NA
- NA
- Local build
Buddy Build: validating
=> Change source0 for python-msal & python-msrestazure

SPECS/systemd/systemd-bootstrap.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
[What does the PR accomplish, why was it needed?]
systemd-bootstrap: fix CVE-2022-4415
- Change
- Change
- Change
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-4415
=> systemd-bootstrap: fix CVE-2022-4415

SPECS/heimdal/CVE-2022-45142.patch, SPECS/heimdal/heimdal.spec
---
Add a patch for CVE-2022-45142 affecting heimdal package. The fix is extracted from this mailing list discussion: https://www.openwall.com/lists/oss-security/2023/02/08/1
- Add patch file for CVE-2022-45142
- Bump release number for heimdal
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-45142
- aarch64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327303&view=results
- x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327304&view=results
=> heimdal: add patch for CVE-2022-45142

SPECS/moby-engine/CVE-2023-25153.patch, SPECS/moby-engine/moby-engine.spec
---
moby-engine address CVE-2023-25153
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-25153
=> moby-engine address CVE-2023-25153

toolkit/docs/formats/imageconfig.md
---
Clean up the documentation for customization scripts a bit. They were missing `PostInstallScripts` completely, and had a lot of duplicated content.
Also add a note to `ExtraCommandLine` about overwriting existing kernel command line options.
- Update customization script docs
- Update ExtraCommandLine docs
**NO**
-  Doc changes only
=> Add PostInstallScript entry to docs, add note to ExtraCommandLine

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
upgrade sudo package to 1.9.13p3 to fix CVE-2023-27320
- bump sudo package version
- update signature and cgmanifest
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-27320
- x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328134&view=results
- aarch64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328135&view=results
=> sudo: update sudo to 1.9.13p3 to fix CVE-2023-27320

SPECS/emacs/CVE-2022-48337.patch, SPECS/emacs/CVE-2022-48338.patch, SPECS/emacs/CVE-2022-48339.patch, SPECS/emacs/CVE-2023-27986.patch, SPECS/emacs/emacs.signatures.json, SPECS/emacs/emacs.spec, cgmanifest.json
Cherry pick accumulated emacs cve fixes.
=> Off Cycle merge of emacs CVE fixes.

SPECS/perl-WWW-Curl/WWW-Curl-4.17-Adapt-to-curl-7.87.0.patch, SPECS/perl-WWW-Curl/WWW-Curl-4.17-Work-around-a-macro-bug-in-curl-7.87.0.patch, SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
---
Fix build break for perl-Curl-WWW.
**NO**
cherry-pick of:
- https://github.com/microsoft/CBL-Mariner/pull/5116
- NA
BuddyBuild: 
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328681&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=a3bfadd1-83e5-5c19-e443-1c88a6f53803&l=1741)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328681&view=logs&j=21e55549-fa44-57d8-4936-64132e3ceec0&t=0085d9b2-2408-5abe-87ce-b702734e35d8&l=1721)
Full Reseeded Build: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328720& …
=> perl-WWW-Curl: introduce patches to work around macro bug

SPECS/kernel/CVE-2022-1943.nopatch, SPECS/kernel/CVE-2023-22996.nopatch, SPECS/kernel/CVE-2023-22997.nopatch, SPECS/kernel/CVE-2023-23001.nopatch, SPECS/kernel/CVE-2023-23003.nopatch, SPECS/kernel/CVE-2023-23005.nopatch
---
Address CVE-2023-22996, CVE-2023-22997, CVE-2023-23001, CVE-2023-23003, CVE-2023-23005, CVE-2022-1943
- Address CVE-2023-22996, CVE-2023-22997, CVE-2023-23001, CVE-2023-23003, CVE-2023-23005, CVE-2022-1943
**NO**
-https://nvd.nist.gov/vuln/detail/CVE-2023-22996
-https://nvd.nist.gov/vuln/detail/CVE-2023-22997
-https://nvd.nist.gov/vuln/detail/CVE-2023-23001
-https://nvd.nist.gov/vuln/detail/CVE-2023-23003
-https://nvd.nist.gov/vuln/detail/CVE-2023-23005
-https://nvd.nist.gov/vuln/detail/CVE-2022-1943
=> Nopatch kernel to address CVE-2023-22996, CVE-2023-22997, CVE-2023-23001, CVE-2023-23003, CVE-2023-23005, CVE-2022-1943

SPECS/gnupg2/gnupg2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Use the correct versionn of libgpg-error-devel as BR
- gnupg2: add correct version of libgpg-error-devel as BR
- gnupg2: manifests: bump release
**YES**
- NA
- NA
- validating
=> gnupg2: add correct version of libgpg-error-devel as BR

toolkit/tools/scheduler/schedulerutils/buildworker.go
---
- 
No.
- #
- https://nvd.nist.gov/vuln/detail/
- Pipeline buddy builds: [AMD64], [ARM64].
=> trying file.copy instead of os.rename (#4992)

SPECS/nginx/nginx.spec
---
This PR update the nginx spec to build it with `ngx_http_realip_module` module. This change was requested under [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/43187680/).
Change: enable building `nginx` with `ngx_http_realip_module` module.
- nginx
- nginx-filesystem
**NO**
Successful local build.
- AMD64 Buddy Build Id: 333769
- ARM64 Buddy Build Id: 333770
=> build nginx with ngx_http_realip_module

SPECS/kernel/CVE-2022-3108.nopatch, SPECS/kernel/CVE-2022-3110.nopatch, SPECS/kernel/CVE-2022-3707.nopatch
---
- Address CVE-2022-3110, CVE-2022-3707
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-3110
- https://nvd.nist.gov/vuln/detail/CVE-2022-3707
=> Nopatch kernel to address CVE-2022-3110, CVE-2022-3707

SPECS/dnsmasq/CVE-2023-28450.patch, SPECS/dnsmasq/dnsmasq.spec
---
Patch [CVE-2023-28450 (dnsmasq)](https://nvd.nist.gov/vuln/detail/CVE-2023-28450)
- Patch [CVE-2023-28450 (dnsmasq)](https://nvd.nist.gov/vuln/detail/CVE-2023-28450)
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-28450
- AMD Buddy Build id: [331806](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=331806&view=results)
- ARM Buddy Build id: [331807](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=331807&view=results)
=> dnsmasq: patch CVE-2023-28450

SPECS/emacs/CVE-2023-28617.patch, SPECS/emacs/emacs.spec
---
Patching CVE-2023-28617.
- Patched CVE-2023-28617 in `emacs`.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-28617
- Local AMD64 package build.
- [ARM64 buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=333907).
=> Patched `emacs` to fix CVE-2023-28617.

toolkit/tools/graphanalytics/graphanalytics.go, toolkit/tools/imagegen/configuration/kernelcommandline.go, toolkit/tools/imagegen/configuration/mountidentifier.go, toolkit/tools/imagegen/configuration/veritydisk.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/buildpipeline/buildpipeline.go, toolkit/tools/internal/pkggraph/pkggraph_test.go, toolkit/tools/internal/pkgjson/pkgjson.go, toolkit/tools/internal/safechroot/safechroot.go, toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
Some of the older go files no longer match the expected formatting for the `go fmt` tool. This PR fixes the formatting for those files. The changes are generally all whitespace related in comments.
- Ran go-tidy-all to fix formatting for some older go files
**NO**
- Local go tools build
=> Update old go file formatting with go-tidy-all.

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner 1.0 Release For March 2023 Update 2
=> Bump Mariner 1.0 Release For March 2023 Update 2

SPECS/curl/curl.signatures.json, SPECS/curl/curl.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump version to 8.0.1 to address CVE-2023-27533 to CVE-2023-27538
- Bump version to 8.0.1 to address CVE-2023-27533 to CVE-2023-27538
**YES**
- NA
- [CVE-2023-27533](https://curl.se/docs/CVE-2023-27533.html)
- [CVE-2023-27534](https://curl.se/docs/CVE-2023-27534.html)
- [CVE-2023-27535](https://curl.se/docs/CVE-2023-27535.html)
- [CVE-2023-27536](https://curl.se/docs/CVE-2023-27536.html)
- [CVE-2023-27537](https://curl.se/docs/CVE-2023-27534.html)
- [CVE-2023-27538](https://curl.se/docs/CVE-2023-27538.html)
Buddy Build:
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=334883&view=logs&j=75cba72d-09cb-503a-3927 …
=> curl: bump version to 8.0.1 to address CVE-2023-27533 to CVE-2023-27538

CONTRIBUTING.md
---
Add additional info to our current contribution guide. This includes
- pointing users to CBL-MarinerTutorials if their use case requires it (added mermaid diagram)
- offering clarity into SPECS vs SPECS-EXTENDED
- adding PR guidelines for target branches, titles, and how to complete the PR checklist
- pointing users to the Issues page if a bug is found
There is still work to be done on expanding tooling documentation and our tools to integrate some of the checks from the PR but these should be done in a seperate PR.
- Update contribution guide to include more detailed instructions
**NO**
https://microsoft.visualstudio.com/OS/_queries/edit/43474965/?triage=true
- view file on …
=> Update contribution guide to include more detailed instructions

SPECS/pytorch/pytorch.signatures.json, SPECS/pytorch/pytorch.spec, cgmanifest.json
---
Fix CVE-2022-25882
- Change Upgrade PyTorch to 2.0.0
**YES/NO**
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-25882
- Arm64 Pipeline build id: [337846](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=337846&view=results)
- x86_64 Pipeline build id: [337845]https://dev.azure.com/mariner-org/mariner/_build/results?buildId=337845&view=results)
=> PyTorch: Fix CVE-2022-25882 by upgrading PyTorch to 2.0.0

SPECS/sos/sos.spec
---
To fix [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/43796653) added `python3-magic` missing runtime dependency to sos package.
- Added `python3-magic` missing runtime dependency
- Linted the spec file
**NO**
- Local build
- Installed the built RPM inside of Mariner 2.0 container and ran the sos command to verify that it resolves the issue.
=> Add missing runtime dependency to sos package

SPECS/nginx/nginx.spec
---
This PR update the nginx spec to build it with `ngx_http_gzip_static_module` module. This change was requested under [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/43992128).
Change: enable building `nginx` with `ngx_http_gzip_static_module` module.
- nginx
- nginx-filesystem
**NO**
Successful local build.
- AMD64 Buddy Build Id: [338381](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338381&view=results)
- ARM64 Buddy Build Id: [338382](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338382&view=results)
=> build nginx with ngx_http_gzip_static_module

SPECS/xinetd/CVE-2013-4342.patch, SPECS/xinetd/xinetd.spec
---
Patch xinetd with CVE-2013-4342 fix
- CVE-2013-4342
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2013-4342
Buddy Builds
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338816&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338817&view=results)
=> Patch xinetd with CVE-2013-4342 fix

SPECS/xinetd/CVE-2013-4342.patch, SPECS/xinetd/xinetd.spec
---
Patch xinetd with CVE-2013-4342
- CVE-2013-4342
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2013-4342
Buddy Builds
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338819&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338818&view=results)
=> Patch xinetd with CVE-2013-4342

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
address CVE-2023-24534, CVE-2023-24536, CVE-2023-24537, CVE-2023-24538
- Bump version to address CVE-2023-24534, CVE-2023-24536, CVE-2023-24537, CVE-2023-24538
**NO**
- #5228
Reference: https://github.com/golang/go/issues?q=milestone%3AGo1.19.8+label%3ASecurity
- CVE-2023-24534
- CVE-2023-24536
- CVE-2023-24537
- CVE-2023-24538
- Local Build.
Buddy Build: [PR-5231](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=338832&view=results)
=> msft-golang: upgrade to 1.19.8 to address CVE-2023-24534, CVE-2023-24536, CVE-2023-24537, CVE-2023-24538

toolkit/scripts/livepatching/template_livepatch.spec
---
Updating livepatch spec template, so that failing builds automatically print more logs.
- Updated livepatch template.
No.
- Local livepatch build using the updated template.
=> Updated livepatch spec template to print more logs.

SPECS/maven/maven.spec, SPECS/maven/maven3.spec
---
Added changes made to `maven` package in PR#5203.
- Added changes made to `maven` package in PR#5203.
- Applied linter suggestions to both maven and maven3 packages
**NO**
=> Updating maven3 to match maven changes

SPECS/kata-containers/kata-containers.signatures.json
---
Forgot to update signature in this recent merged PR by me https://github.com/microsoft/CBL-Mariner/pull/5147/files#diff-7cd5459bb1e5a947c2a87599bc0cb4a92fcc7945e6c42d41991df822f80d9a46
- kata-containers 
**NO**
- #xxxx
=> kata-containers: update kata-osbuilder.sh signature

SPECS/dracut/dracut.signatures.json, SPECS/dracut/dracut.spec, SPECS/dracut/megaraid.conf, SPECS/initramfs/initramfs.spec
---
This PR adds the dracut-megaraid package that contains configuration for dracut to add megaraid drivers to initramfs for HCI scenarios
- Add dracut-megaraid package
- Add regeneration hook for it in initramfs package
**NO**
=> Add dracut-megaraid package

toolkit/scripts/imggen.mk
---
Backporting #5233 from `main` to fix usage of the `UNATTENDED_INSTALLER` argument.
- Building an ISO will not correctly interpret the `UNATTENDED_INSTALLER` argument.
No.
- #5233
- Local build with `sudo make iso REBUILD_PACKAGES=n REBUILD_TOOLS=y CONFIG_FILE=./imageconfigs/full.json UNATTENDED_INSTALLER=n`. Same as the `main` fix.
=> Fixing `UNATTENDED_INSTALLER` argument.

SPECS/mariner-release/mariner-release.spec
Bump Mariner 2.0 Release for April 2023 Update
=> Bump Mariner 2.0 Release for April 2023 Update

SPECS/influxdb/influxdb.spec
---
My changes to the BuddyBuild that test installation/uninstallation of packages revealed that influxdb package cannot be uninstalled. Fixing the issue here.
- Fixed uninstallation of influxdb. Bug https://microsoft.visualstudio.com/OS/_workitems/edit/44136951
**NO**
- Local, installed built package into docker container and uninstalled it.
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=342515&view=results
=> Fix uninstallation of InfluxDB package

toolkit/tools/imagegen/configuration/kernelcommandline.go, toolkit/tools/imagegen/configuration/veritydisk.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/buildpipeline/buildpipeline.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/pkggraph/pkggraph_test.go, toolkit/tools/internal/pkgjson/pkgjson.go, toolkit/tools/internal/safechroot/safechroot.go
---
Run go-fmt on toolkit directory
- NA
**NO**
- NA
- NA
- NA
=> Run go-fmt on toolkit

SPECS/bcc/bcc.spec, SPECS/lld/lld.spec, SPECS/mesa/mesa.spec
---
The build for bcc, ldd & mesa does not work with llvm == 16.0.0
Add an explicit constraint to allow build
- Add an explicit constraint on llvm < 16.0.0
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/5242
- NA
- Full Reseed Build: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=342319&view=results)
=> Add an explicit constraint on llvm-devel < 16.0.0 for bcc, ldd & mesa

SPECS/maven-resolver/maven-resolver.spec, SPECS/sisu/sisu.spec
---
- Change: Remove epoch from the spec files
**YES/NO**
NO
- Pipeline build id: [343811](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=343811&view=results)
=> Remove epoch from some spec files 

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Mariner 1.0 release for April 2023 update
=> Bump Mariner 1.0 release for April 2023 update

SPECS/nginx/nginx.signatures.json, SPECS/nginx/nginx.spec
---
Upgrade bundled version of `njs` in `nginx` to fix newly-surfaced CVEs.
- nginx: Upgrade bundled njs to 0.7.12 from 0.2.1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-19692
- https://nvd.nist.gov/vuln/detail/CVE-2020-19695
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=345567&view=results)
=> Upgrade bundled njs version in nginx to 0.7.12 to fix CVE-2020-19692, CVE-2020-19695

toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/amd64/isolinux/isolinux.cfg, toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/arm64/isolinux/isolinux.cfg, toolkit/resources/assets/isomaker/iso_root_static_files/boot/grub2/grub.cfg
---
Enable serial console for ISO installer when mounting in labs remotely
- Enable serial console with linux cmdline for ISO installer
NO
- local build of full ISO
- manually booted ISO in both UEFI and legacy BIOS VMs
- minicom to VM serial port confirmed password still displayed as ******
=> Enable serial console for ISO installer

toolkit/imageconfigs/packagelists/azurevm-packages.json
---
Some Azure VM extensions, such as the Azure Disk Encryption VM Extension, need to be able to update the kernel command line parameters for the extension to function. The method to do this is by utilizing grubby to update the grubenv block to set the kernelopts= grub environment variable. And to do this, the grubby package must be already present on the image prior to the VM extension execution.
So this change adds the grubby package into the azurevm-packages.json package definition, which is included in every Azure VM image definition.
grubby requires the grub2 package. Together, these two packkages increase the image footprint by ~34 MB.
```
$ rpm -qi grubby
Name        : grubby …
```
=> azurevm-packages: Add grubby to package list

SPECS/selinux-policy/0036-iptables-Support-Mariner-non-standard-config-locatio.patch, SPECS/selinux-policy/0037-cloudinit-Add-permissions-derived-from-sysadm.patch, SPECS/selinux-policy/0038-systemd-Fix-run-systemd-shutdown-handling.patch, SPECS/selinux-policy/0039-modutils-Temporary-fix-for-mkinitrd-dracut.patch, SPECS/selinux-policy/selinux-policy.spec
---
Fix issues with iptables and cloud-init access as reported by downstream teams.
- Handle save location of iptables rules
- Add broad admin access to cloud-init to support more scenarios out of the box.
- Fix scheduled shutdown/reboot.
**NO**
- Pipeline build id: 344147
- Static analysis
- Local build manual testing
=> selinux-policy: Add rules for cloud-init and iptables.

SPECS/memcached/CVE-2021-45985.patch, SPECS/memcached/memcached.spec, SPECS/ntopng/CVE-2021-45985.patch, SPECS/ntopng/ntopng.spec
---
Patch lua source that comes along with `memcached` and `ntopng` packages
- CVE-2021-45985
**NO**
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-45985
- local build
=> Fix CVE-2021-45985 on memcached and ntopng

SPECS/reaper/CVE-2022-37601.patch, SPECS/reaper/reaper.spec
---
Fix CVE=2022-4761 for webpack's loader-utils that come along with reaper package
- New patch CVD-2022-37601
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-37601
- Local build
=> Fix CVE 2022 37601 on webpack loader-utils integrated with webpack

SPECS/nmap/nmap.signatures.json, SPECS/nmap/nmap.spec, SPECS/nmap/remove_openssl_macro.patch, cgmanifest.json
---
New version contains new zlib version https://github.com/nmap/nmap/commit/ea9344ef3db8a55f77e9d2c90a11fe5ccb7c4274, which fixes https://nvd.nist.gov/vuln/detail/CVE-2018-25032
- https://nvd.nist.gov/vuln/detail/CVE-2018-25032
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2018-25032
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=346389&view=results
=> Upgrade nmap to version 7.93 to fix CVE-2018-25032

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
---
Upgrade erlang to version 25.2 to fix CVE-2018-25032
- Upgrade to version 25.2, aligned with 2.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2018-25032
- Buddy Build
- AMD64: [346291](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=346291&view=results)
- ARM64: [346351](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=346351&view=results)
=> Upgrade erlang to 25.2 to fix CVE-2018-25032

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
This reverts commit f57a9c1f095593949c953182e52ce338eb11709b.
---
Revert merged erlang upgrade
- Revert erlang upgrade in favor of a patch fix
**NO**
=> Revert "Upgrade erlang to 25.2 to fix CVE-2018-25032 (#5324)"

SPECS/mariner-release/mariner-release.spec
Bump for Mariner 2.0 April 2023 Update 2
=> Bump for Mariner 2.0 April 2023 Update 2

SPECS/kernel/CVE-2023-1829.nopatch, SPECS/kernel/CVE-2023-1989.nopatch, SPECS/kernel/CVE-2023-1990.nopatch
---
nopatch cves: CVE-2023-1829, CVE-2023-1989, CVE-2023-1990
- CVE-2023-1829
- CVE-2023-1989
- CVE-2023-1990
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-1829
- https://nvd.nist.gov/vuln/detail/CVE-2023-1989
- https://nvd.nist.gov/vuln/detail/CVE-2023-1990
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=349014&view=logs&j=e3e4c90c-f47a-552d-9399-c51e3747740e&t=97a0aa58-1cd5-5faa-2410-5d8e670febf7
=> Nopatch kernel for CVE-2023-1829, CVE-2023-1989, CVE-2023-1990

SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Use kernel header to query the kernel version

SPECS/nodejs/nodejs18.signatures.json
---
We've updated the nodejs18 tar to remove OpenSSL that was loaded into the upstream tar. This achieves parity with nodejs package.
**YES/NO**
=> update signature for nodejs18 source tar

SPECS/qt5-qtbase/CVE-2023-24607.patch, SPECS/qt5-qtbase/qt5-qtbase.spec
---
Adds patch to qt5-qtbase. Patch from upstream did not apply cleanly and there are no other backports out, so this is a bespoke backported patch. Was able to buddy build and verify that qmake-qt5 binary still worked (qmake-qt5 --version)
- FIXES CVE-2023-24607
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-24607
- Pipeline build id: [350278](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=350318&view=results)
=> Fix: patch CVE-2023-24607 for qt5-qtbase

SPECS/perl-File-HomeDir/perl-File-HomeDir.spec, SPECS/perl-File-Which/perl-File-Which.spec, SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec
---
Update File Extension of files named in the man3 directory of 3 packages which depended on the previous .3.gz name to .3pm.gz
- update perl-List-MoreUtils %files section
- update perl-File-Which %files section
- update perl-File-HomeDir %files section
**NO**
- [AMD64 Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=350350&view=results)
- [ARM64 Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=350355&view=results)
- Use grep to determine all specs affected by command `grep .3.gz */*` from the SPECS directory
result compared to the command `grep .3pm.gz */*` from the SPECS …
=> Add 3pm extension to perl-File-Which, perl-File-HomeDir, and perl-List-MoreUtils following update to perl man3 naming change

SPECS/erlang/CVE-2018-25032.patch, SPECS/erlang/erlang.spec
---
Fixes CVE-2018-25032 on zlib, which is used by erlang
- Add patch for zlib CVE-2018-25032
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2018-25032
- local build,
- AMD buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=349960
- ARM buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=349961
=> Patch erlang for CVE-2018-25032

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump Release for April 2023 Update 2
=> Bump Release for April 2023 Update 2

SPECS/kernel/CVE-2023-1872.nopatch, SPECS/kernel/CVE-2023-22997.nopatch, SPECS/kernel/CVE-2023-23005.nopatch
---
- Nopatch kernel for CVE-2023-1872, CVE-2023-22997, CVE-2023-23005
- Nopatch kernel for CVE-2023-1872, CVE-2023-22997, CVE-2023-23005
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-1872
- https://nvd.nist.gov/vuln/detail/CVE-2023-22997
- https://nvd.nist.gov/vuln/detail/CVE-2023-23005
=> Nopatch kernel for CVE-2023-1872, CVE-2023-22997, CVE-2023-23005

cgmanifest.json
---
Recent changes to the changelog have made entries be out of order- let's fix it.
- Ran `update_cgmanifest.py` script to get everything in proper order
**NO**
- N/A
=> Fix cgmanifest ordering

SPECS/kernel/CVE-2023-1382.nopatch, SPECS/kernel/CVE-2023-2008.nopatch, SPECS/kernel/CVE-2023-30772.nopatch
---
- Nopatch kernel for CVE-2023-1382, CVE-2023-2008, CVE-2023-30772
- Nopatch kernel for CVE-2023-1382, CVE-2023-2008, CVE-2023-30772
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-1382
- https://nvd.nist.gov/vuln/detail/CVE-2023-2008
- https://nvd.nist.gov/vuln/detail/CVE-2023-30772
=> Nopatch kernel for CVE-2023-1382, CVE-2023-2008, CVE-2023-30772

SPECS/bcc/bcc.signatures.json, SPECS/bcc/bcc.spec, cgmanifest.json
---
Bump version to 0.27.0
- Bump version to 0.27.0
**NO**
- NA
- NA
- Local build and test in a mariner VM
- Buddy Build: [PR-5420](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=351539&view=results)
=> bcc: bump version to 0.27.0
