- SPECS/python3/CVE-2015-20107.patch
- SPECS/python3/python3.spec
---
Cherry-picking CVE-2015-20107 fix from #3644.
- Patched CVE-2015-20107.
No.
- #3644
- https://nvd.nist.gov/vuln/detail/CVE-2015-20107.
- Local patch application.
- Buddy build: 246145.
> python3: patch CVE-2015-20107.

- SPECS/bind/bind.spec
---
The `utils` subpackage of `bind` contains a [systemd tmpfiles configuration](https://www.man7.org/linux/man-pages/man8/systemd-tmpfiles.8.html). This configuration requires the `named` user to exist, but that user is created by the main package's postinstall scripts. When the `utils` subpackage is installed without the main package, the missing user causes `systemd-tmpfiles-setup.service` to fail.
It's more appropriate for the tmpfiles config to be in the main package with the rest of the server stuff anyways, since we should only need `/run/named` when running the server. In the same spirit, this PR also moves some server configuration files from the `utils` subpackage to the …
> Move bind server config files to base package from utils package

- SPECS/fping/fping.spec
---
Cherry-pick of #2994 to the 1.0-dev branch. 
User reported that calls to `fping` consistently fail in a container without `iana-etc` installed.
As Eric said in that PR- "`fping` code uses `getprotobyname()` library call which rely on `/etc/protocols` as protocols database. `/etc/protocols` is provided by `iana-etc` pkg." So, let's reflect this dependency in the spec by adding a runtime requirement on `iana-etc` to `fping`.
- `fping`: Add runtime requirement on iana-etc
**NO**
- Buddy build passes
- Installing `fping` now installs `iana-etc`, and `/usr/sbin/fping 8.8.4.4` works after install out-of-the-box in a fresh container without `iana-etc` pre-installed.
> Add runtime requirement on iana-etc to fping

- SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
- SPECS/kata-containers/kata-containers.signatures.json
- SPECS/kata-containers/kata-containers.spec
- SPECS/kata-containers/kata-osbuilder.sh
---
add patch to avoid memory hotplug timeout, fix systemd service, add libseccomp to requires
- add patch to avoid memory hotplug timeout
- fix service to start osbuilder on installation
- remove unnecessary testing of osbuilder from spec
- Add libseccomp to requires
**NO**
- Local build with testing on AKS/hyper-v
> kata : add patch to avoid memory hotplug timeout, fix systemd service

- toolkit/scripts/livepatching/generate_livepatch-signed_spec.sh
- toolkit/scripts/livepatching/generate_livepatch_spec.sh
- toolkit/scripts/livepatching/template_livepatch.spec
- toolkit/scripts/livepatching/update_livepatches.sh
---
In order to stick to our conventions of keeping a single package spec per spec subdirectory, I'm updating the livepatch generation scripts, since previously all livepatch specs were generated under `SPECS/livepatch` and `SPECS-SIGNED/liveptach-signed`.
In addition to that I'm skipping generation of specs for signed livepatches, if the unsigned version doesn't generate any signable content (e.g. it generates only an "empty" livepatch without any CVE patches).
- Generate each livepatch in its own specs subdirectory.
- Generate signed specs only for signable livepatches.
No.
- Local scripts run.
> livepatch spec generation: unifying naming with other core specs

- SPECS/systemd/gpt-auto-devno-not-determined.patch
- SPECS/systemd/systemd-bootstrap.signatures.json
- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.signatures.json
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
gpt-auto-generator returns 1 on Sphere because the backing block device or `/` and `/usr` can't be determined. In systemd >= 251  this error is better handled. This applies the fix from later versions to 250.3.
- systemd and systemd-bootstrap specs updated to include patch for https://github.com/systemd/systemd/pull/22506
**YES**
- https://github.com/Azure/azure-sphere-v2-are-fs/issues/114
- Local build
- [Sphere pipeline](https://dev.azure.com/msazuresphere/Public/_build/results?buildId=298232&view=results)
> systemd: gpt-auto fixes for backing device detection

- SPECS/unzip/CVE-2008-0888.nopatch
- SPECS/unzip/unzip.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
User observed that our version of `unzip` doesn't support files over 4GB- indeed, we don't compile with the right feature flags for that currently. So, let's add the `LARGE_FILE_SUPPORT` and `ZIP64_SUPPORT` flags when we compile `unzip`.
- Compile with large file support, zip64 support
- Remove i*86 configuration- Mariner doesn't build for those architectures
- Lint spec
- Remove nopatch files from spec
**YES**
- Installed buddy-built package, piped 10GB of /dev/random into a file, zipped the garbage (final size was about the same), and was able to successfully unzip the garbage!
> Add large file support to unzip

- toolkit/scripts/imggen.mk
---
Currently making subsequent calls to "make iso" will fail due to some firmware files that contain spaces. Make will incorrectly the two strings on either side of the filename's space character are separate files that need building. This change avoids passing make files with a space in the name. Similar logic was introduced previously for names that contained the ":" character.
- Add a new filter for imager_disk_output_files in imggen.mk
NO
- [WorkItem 41743128](https://microsoft.visualstudio.com/OS/_sprints/taskboard/Mariner%20Platform/OS/2210?workitem=41743128)
- Built locally
> stop make from tracking imager disk output files that contain spaces

- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
Support Mariner 1.0 build on Mariner 2.0 host
As of today, Mariner 1.0 package build environment does not work on Mariner 2.0 hosts. This is due to the rpm version (4.17+) in Mariner 2.0 which defaults to an sqlite database backend and does not support bdb (Berkeley DB) database. Mariner 1.0 has rpm version 4.14 which only supports bdb. When the package worker chroot is created, the host machine's rpm tool is used to install the packages and create the database. I've modified the create_worker_chroot.sh script re-created the database using the rpm version in the chroot (which creates a valid bdb database).
Various symptoms seen when …
> Support Mariner 1.0 build on Mariner 2.0 host

- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
Optimize the create_worker_chroot.sh script to only rebuild the rpm backend database when necessary. The host machine rpm version creates the rpm database in the chroot, which could be incompatible. Common scenarios are as follows:
- Mariner 2.0 host creates sqlite database, which is compatible with Mariner 2.0 being built (rpm db is not rebuilt)
- Mariner 1.0 host creates bdb database, which is not compatible with Mariner 2.0 being built (rpm db is rebuilt in sqlite format)
- Ubuntu 18.04 host creates bdb database, which is not compatible with Mariner 2.0 being built (rpm db is rebuilt in sqlite format)
Also create /dev/null and …
> [2.0] Rebuild worker chroot rpm db only when necessary

- toolkit/scripts/pkggen.mk
- toolkit/scripts/toolchain.mk
---
Change toolkit scripts to not use ARCHIVE_TOOL when extracting tarballs (rpms.tar.gz, srpms.tar.gz, toolchain_built_rpms_all.tar.gz, toolchain_built_srpms_all.tar.gz). The tar command is smart enough to figure out which decompression library to use (see [gnu tar](https://www.gnu.org/software/tar/manual/tar.html#gzip) "Reading compressed archive is even simpler: you don’t need to specify any additional options as GNU tar recognizes its format automatically.". Removing the explicit ARCHIVE_TOOL makes the scripts more flexible, and they can handle cases where these tarballs might not be compressed.
Relevant example below. In this case …
> 1.0 toolkit: skip ARCHIVE_TOOL on extraction

- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
Fix two issues importing gpg keys in the worker chroot. The first change is to create the "/dev/null" node before installing packages in the worker chroot (so that "mariner-repos-shared" can import gpg keys). The second is to make sure the call to manually import gpg keys happens even when the rpm database is not rebuilt.
Fixes errors seen when building on Mariner 2.0 host such as:
```
ERRO[0015] Failed to clone 'libestr-0.1.11-1.cm2.x86_64' from RPM repo. Error: exit status 9 
ERRO[0017] Failed to clone 'postgresql-devel-14.5-1.cm2.x86_64' from RPM repo. Error: exit status 9 
ERRO[0020] Failed to clone …
```
> Fix gpg key import in worker chroot

- SPECS/rsyslog/rsyslog.signatures.json
---
Fix for build break:
```
ERRO[0195] unable to hydrate file: rsyslog.logrotate    
ERRO[0195] Failed to pack (/specs/rsyslog/rsyslog.spec). Error: unable to hydrate file: rsyslog.logrotate 
```
- Change ryslog.signatures.json with correct sha256sum for rsyslog.logrotate
**NO**
- sudo make input-srpms REBUILD_TOOLS=y SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core
> Fix rsyslog.logrotate signature

- toolkit/scripts/pkggen.mk
- toolkit/scripts/toolkit.mk
---
In 2.0 we made the package fetchers use a chroot, we have a separate clean target for the pkg fetcher (`clean-cache`) which did not have an enforced ordering with the more general `clean-workplan`. If the package fetcher was killed halfway through it could leave behind a chroot which hasn't been cleaned up. Running `make clean` will generally run `clean-workplan` before running `clean-cache` which will try (and fail) to remove the chroot's `/proc/*` etc., and possibly put the host system into a bad state. This adds an explicit dependency so the chroot is cleaned up first.
We were also missing cleanups for the spec parsing chroot and snapshot chroots.
- Add a dependency on …
> Fix chroot cleanup scripts

- SPECS/libtiff/CVE-2022-3570.patch
- SPECS/libtiff/libtiff.spec
---
Fixes critical vulnerability in libtiff package
- [CVE-2022-3570](https://nvd.nist.gov/vuln/detail/CVE-2022-3570) 
NO
None
- https://nvd.nist.gov/vuln/detail/CVE-2022-3570
- Pipeline build id: [254923](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=254923&view=results)
> patch 1.0 - CVE-2022-3570 for vuln. in libtiff package

- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
Reverts microsoft/CBL-Mariner#4071
missed Jon's comment about the version jump
> Revert "[AUTOPATCHER-CORE] nodejs upgrade to version 16.17.1 - CVE-2022-32213 - "

- SPECS/rubygem-minitest/rubygem-minitest.spec
- SPECS/rubygem-power_assert/rubygem-power_assert.spec
- SPECS/rubygem-rake/rubygem-rake.spec
- SPECS/rubygem-test-unit/rubygem-test-unit.spec
---
A while ago we removed bundled Ruby gems from the `ruby` package and moved them to separate packages (#3035). Since now both the new packages and the older version of `ruby` provide the same files, we can hit package installation conflicts in some corner cases. To alleviate that, I'm adding an `Obsoletes: ruby <= [old_ruby_version]` to make RPM or the package managers choose the right combination of packages.
- Added `Obsoletes` to `rubygem-minitest`, `rubygem-power_asser`, `rubygem-rake`, and `rubygem-test-unit`.
No.
- #3035
> Updated 4 `rubygem-*` packages to obsolete older versions of `ruby`.

- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
---
This is a revert of a revert #4082. Or in other words a repeated #4071.:)
In the end we've decided to go with the 16.17.1 version in order to fix the current CVEs due to complications with building newer versions.
- Updated `nodejs` to version 16.17.1.
No.
- #4071
- #4082
- https://nvd.nist.gov/vuln/detail/CVE-2022-32213
> Upgrading `nodejs` to version 16.17.1.

- toolkit/scripts/toolchain/check_manifests.sh
---
Cherry-pick of #4095 for 2.0.
[RPM 4.18.0 changed the default query](https://github.com/rpm-software-management/rpm/commit/82dafa39a2dfd3e24858681ca75f467c1e1b3635) used by `rpmspec -q` when no query format string is specified. The old behavior uses the `%{nvra}` format string, which uses the final architecture of a package (through the `%{arch}` tag) regardless of whether we're querying a source package or not. RPM 4.18.0 introduces a new tag, `%{archsuffix}` which is the same as `%{arch}` except that it returns `src` or `nosrc` when querying a source package. The new default query format string was changed to `%{nvr}.%{archsuffix}`.
This broke our manifest checking script, …
> Fix manifest checks with RPM 4.18

- SPECS/qemu/qemu.spec
---
RPM has trouble choosing which package provides `/usr/libexec/virtiofsd`. For our series of `qemu-6.1.0` releases, this file resided in `qemu-common`. For our series of `qemu-6.2.0` releases, this file resides in `qemu-virtiofsd`. Since these packages have different names, RPM gives up on choosing a single provider for that file.
So, let's help RPM choose by explicitly stating that `qemu-virtiofsd` obsoletes all versions of `qemu-common` prior to 6.2.0. That way, RPM will always choose `qemu-virtiofsd` when querying for the latest owner of `/usr/libexec/virtiofsd`.
For more context, see the original bug report at the bottom of this description.
- `qemu-virtiofsd` now obsoletes …
> Add obsoletes between qemu-common, qemu-virtiofsd

- SPECS/nginx/nginx.signatures.json
- SPECS/nginx/nginx.spec
- cgmanifest.json
---
The autopatcher moved us to 1.23, which is not a stable release. Bumping nginx back to 1.22. 
https://github.com/microsoft/CBL-Mariner/pull/4092
- Move nginx back to v1.22.1
NO
- Version 1.22.1 of the source was built already for 1.0-dev https://github.com/microsoft/CBL-Mariner/pull/4119/files
- ARM64 buddy build ID: 257426.
> [main] Revert nginx to stable version 1.22.1

- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2-aarch64.json
- toolkit/imageconfigs/marketplace-gen2.json
---
This PR addresses a behavior introduced to the Mariner 1.0 AKS Container Host by this PR https://github.com/microsoft/CBL-Mariner/pull/3261
https://github.com/microsoft/CBL-Mariner/pull/3261 introduced apparmor as a runtime requires for containerd, which unintentionally enabled very strict apparmor default policies in situations where containerd runtime is used. This enforcement is blocking customer container functionality that is expected to work.
So this change restores prior behavior by disabling AppArmor at the host/kernel level. We will be re-evaluating the default apparmor policies to ensure customer container functionality continues to work when we re-add AppArmor …
> Disable apparmor LSM at boot time

- SPECS/audit/audit.spec
- SPECS/blobfuse/blobfuse.spec
- SPECS/cni/cni.spec
- SPECS/coredns/coredns-1.8.0.spec
- SPECS/coredns/coredns-1.8.4.spec
- SPECS/coredns/coredns-1.8.6.spec
- SPECS/cri-tools/cri-tools.spec
- SPECS/etcd/etcd-3.4.13.spec
- SPECS/etcd/etcd-3.5.0.spec
- SPECS/etcd/etcd-3.5.1.spec
- SPECS/flannel/flannel.spec
- SPECS/glide/glide.spec
- SPECS/go-md2man/go-md2man.spec
- SPECS/gobject-introspection/gobject-introspection.spec
- SPECS/golang/golang.signatures.json
- SPECS/golang/golang.spec
- SPECS/helm/helm.spec
- SPECS/libnvidia-container/libnvidia-container.spec
- SPECS/moby-buildx/moby-buildx.spec
- SPECS/moby-cli/moby-cli.spec
- SPECS/moby-containerd/moby-containerd.spec
- SPECS/moby-engine/moby-engine.spec
- SPECS/moby-runc/moby-runc.spec
- SPECS/node-problem-detector/node-problem-detector.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Happy Go 1.18.8 release day! We're upgrading to the latest version to get the security fixes from the 1.18.6 and 1.18.7 releases.
- Upgrade to Go 1.18.5 to 1.18.8
- No change to Go 1.17- we need these for k8s, but that branch no longer receives security updates
- Bump release of packages that depend on `golang` to force rebuild
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2879
- https://nvd.nist.gov/vuln/detail/CVE-2022-2880
- https://nvd.nist.gov/vuln/detail/CVE-2022-41715
- https://nvd.nist.gov/vuln/detail/CVE-2022-27664
- https://nvd.nist.gov/vuln/detail/CVE-2022-32190
[AMD64 BB](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=259146&view=results) …
> Upgrade golang to 1.18.8 to fix CVE-2022-2879, CVE-2022-2880, CVE-2022-41715, CVE-2022-27664, CVE-2022-32190

- toolkit/scripts/tools.mk
---
Disable CGO when building go-tools. This will statically compile the applications instead of dynamically linking them with glibc, which should make them more portable. When we updated build machines to Mariner 2.0, we started seeing the following error from the Mariner 1.0 ISO's liveinstaller application. (Mariner 2.0 has a newer glibc version than 1.0)
```
./liveinstaller: /lib/libc.so.6: version `GLIBC_2.32` not found (required by ./liveinstaller)
```
Our build machines (Mariner 2.0) appear to have CGO_ENABLED set to 1 by default.
```
$ docker run --rm -it mcr.microsoft.com/cbl-mariner/base/core:2.0 bash
1
```
More info: …
> Toolkit: Set CGO_ENABLED=0 when building go tools

- .github/workflows/validate-cg-manifest.sh
---
Some of the spec macros like `%forgemeta` require the `mariner.common` and/or `marnier.srpm.forge` lua modules. These modules are correctly installed in the Mariner environment (like a worker chroot or a full image) but our PR checks run on Ubuntu, where these modules are not present. This PR conditionally installs these modules for the duration of the PR check, if they are not present, and makes sure they are removed afterwards, if such clean-up is needed.
**CALL FOR HELP**: I believe this fix could be more elegantly implemented by manipulating the [`LUA_PATH` env variable](https://community.exasol.com/t5/database-features/exasol-loves-lua-part-3-handling-modules/ta-p/2134). …
> Fixed cgmanifest validation's dependency on lua.

- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/rpm/rpm_test.go
- toolkit/tools/internal/rpm/testdata/no_default_package.spec
---
After a recent `rpm` package update to version 4.18.0 the results for `rpmspec --builtrpms [spec_path]` print "src" instead of the architecture as the last component.
Before:
```bash
root [ / ]# rpmspec --builtrpms -q --target x86_64 -D "dist .cm2" mariner-repos.spec 
mariner-repos-2.0-8.cm2.noarch
mariner-repos-debug-2.0-8.cm2.noarch
mariner-repos-debug-preview-2.0-8.cm2.noarch
mariner-repos-extended-2.0-8.cm2.noarch
mariner-repos-extended-debug-2.0-8.cm2.noarch
mariner-repos-extended-preview-2.0-8.cm2.noarch
mariner-repos-extended-debug-preview-2.0-8.cm2.noarch
mariner-repos-extras-2.0-8.cm2.noarch
mariner-repos-extras-preview-2.0-8.cm2.noarch …
```
> Fixed printing built RPMs from spec.

- SPECS/mariner-release/mariner-release.spec
Bump release version for November 2022 Mariner Release.
> Bump Mariner Release version for off-cycle CVE fixes

- SPECS/mariner-release/mariner-release.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Bump release for off-cycle CVE fixes.
> Bump Mariner Release For Nov 2022 Update

- SPECS/python-six/python-six.spec
---
Pytest recently updated to a version that causes the self-test to fail.  This change forces the self-test to use python version 7.1.3.  This change also removes the pytest2 test.  It was previously failing and the result was overridden by the py3 test.  Since python2 is only supported for build reasons, it was decided to remove the test.
> Fix python-six test to use explicit version 7.1.3

- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/sliceutils/sliceutils.go
- toolkit/tools/internal/sliceutils/sliceutils_test.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
---
Our RPM resolution mechanism is broken, when we have multiple candidates providing the same functionality and the best candidate is already installed in the build chroot. We never hit this case during full builds, but it happens for delta builds, where the set of available packages is the whole content of PMC (including package versions from previous releases) and not just the packages built during this run.
The fix adds the `--replacepkgs` argument to the RPM command we run during resolution, so that it doesn't error out if it finds an installed package. Other changes are just code refactoring.
- Made RPM accept installed packages during packages resolution.
- Add a …
> Updated toolkit's package resolution to accept installed packages.

- SPECS/coreutils/coreutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- This PR is trying to move all the binaries back into default install location from /bin/ to /usr/bin/
- We moved all the binaries to /bin at frist place as we followed Centos coreutils.spec but later they moved all the binaries into /usr/bin/ [upstream PR](https://github.com/vmware/photon/commit/3a7b668080aefefa61f30f42d165d51b7283a5f0#diff-2c1479545d88b270d5949996da652f11dc9feae915beba7eaef20c2efc2970af)
- remove the code that moves binaries from /usr/bin to /bin
YES
- [Bug 41031409](https://microsoft.visualstudio.com/OS/_workitems/edit/41031409): tdnf coreutils package dependency resolution
- local toolchain and package build
> change binary install location in coreutils package

- toolkit/scripts/imggen.mk
---
Conversation with one of our partners made me realize that the explicit `initrd` target makes it seem like this is part of Mariner's toolkit public interface and can/should be used when building initrds. I'm modifying the toolkit to make it clearer that the official image building interfaces are only `image` and `iso`.
- Replaced the `initrd` target with the initrd's file path.
No.
- Pipeline buddy build: 266631
> Removed explicit `initrd` target from the toolkit.

- SPECS/coreutils/coreutils.spec
- SPECS/findutils/findutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Build coreutils and findutils after libselinux so that SELinux features are enabled in these packages.
- Build coreutils and findutils after libselinux.
- Fix findutils spec lint issues.
**YES**
- Pipeline build id: 268640
> toolchain: Build coreutils and findutils after libselinux.

- SPECS/rust/rust.spec
---
Following @eric-desrochers findings in #4282 we're splitting out Rust's documentation into a separate package to reduce the default one's size by ~600 MB. Great find, Eric!
- Moved Rust's documentation into a new `doc` subpackage.
No.
- #4282
- Pipeline buddy build: 269227.
> Split out 'doc' subpackage from Rust.

- SPECS-EXTENDED/cglib/cglib.spec
---
Update Requires section of package to fix install failure
- change runtime requirement to objectweb-asm instead of mvn(org.ow2.asm:asm)
NO
- Pipeline build id: Buddy Build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=270268&view=results
> cglib: Fix package install failure due to missing runtime dependency

- SPECS/libarchive/CVE-2022-36227.patch
- SPECS/libarchive/libarchive.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
* Patch `libarchive` for CVE-2022-36227
* libarchive: manifests: update entry
---
Fix for CVE-2022-36227
> Patch `libarchive` for CVE-2022-36227

- SPECS/libxml2/CVE-2022-40304.patch
- SPECS/libxml2/libxml2.spec
---
This fixes CVE-2022-40304.  Note that the release number was not bumped here because this package has not been released yet.
> Patch libxml2 for CVE-2022-40304

- SPECS/mariner-release/mariner-release.spec
- toolkit/imageconfigs/marketplace-gen2.json
---
This PR increases the Max Disk Size for the marketplace mariner image to 5GB by the request of Chris Co for the continuation of ADE VM extension work with Mariner.
Changed `MaxSize: 1500` in `marketplace-gen2.json` to `MaxSize: 5000` to represent increase to 5GB disk size.
**NO**
- Pipeline build id: 268321
- Booted VHD in Hyper-V and command `df -H` showed that increase was implemented.
> Increase Marketplace image size to 5GB

- SPECS/WALinuxAgent/WALinuxAgent.signatures.json
- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/WALinuxAgent/ephemeral-disk-warning
- SPECS/WALinuxAgent/ephemeral-disk-warning.conf
- SPECS/WALinuxAgent/ephemeral-disk-warning.service
---
Mariner doesn't place the dataloss warning on its ephemeral resource disk for the VMs with temporary storage, which caused test failures in BVT and Hotpatch. In Ubuntu there's a systemd service ([ephemeral-disk-warning.service](https://git.launchpad.net/ubuntu/+source/walinuxagent/tree/debian)) that writes the dataloss warning file. So this PR adds ephemeral-disk-warning configuration and service files into WALinuxAgent package to write the dataloss warning on each boot.
- Add ephemeral-disk-warning.service
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/41968484/
- Local build
- Tested by building custom Gen1 and …
> add ephemeral disk warning

- SPECS-EXTENDED/apache-commons-compress/apache-commons-compress.spec
---
Correct Requires section to fix package installation failure
- Add Requires on xz instead of mvn(org.tukaani:xz)
NO
- Pipeline build id: Buddy Build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=270268&view=results
> apache-commons-compress: Fix package install failure due to missing runtime dependency

- toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
- toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
- toolkit/tools/liveinstaller/liveinstaller.go
---
Current behavior:
Mariner installs itself onto Disk and reboots. Leaving boot order untouched, which causes seconds of failed booting into PXE after the post-install reboot and subsequent reboots.
Introduced behavior:
When in an EFI boot type'd iso install, we have the ability to set our boot order via the EFI boot manager (i.e., efibootmgr). Using this tool's functionality, and the knowledge specified by our image config files (e.g., unattended.json configs, attendedconfig.json, etc) we can set the first target in the boot order to our shim 'bootx64.efi' which typically lives in /boot/efi
Primary:
- When installing a gen2 image via ISO, set the newly installed shim (bootx64.efi) …
> update generation 2 boot order during iso installation

- SPECS/kernel/CVE-2022-1204.nopatch
- SPECS/kernel/CVE-2022-2785.nopatch
- SPECS/kernel/CVE-2022-3344.nopatch
- SPECS/kernel/CVE-2022-3586.nopatch
- SPECS/kernel/CVE-2022-3595.nopatch
- SPECS/kernel/CVE-2022-3910.nopatch
- SPECS/kernel/CVE-2022-40768.nopatch
- SPECS/kernel/CVE-2022-4127.nopatch
- SPECS/kernel/CVE-2022-41849.nopatch
- SPECS/kernel/CVE-2022-41850.nopatch
- SPECS/kernel/CVE-2022-43945.nopatch
CVE-2022-1204, CVE-2022-2785, CVE-2022-3586, CVE-2022-3595, CVE-2022-3910, CVE-2022-40768, CVE-2022-4127, CVE-2022-41849, CVE-2022-41850, CVE-2022-43945, CVE-2022-3344 for kernel
---
- Nopatch CVE-2022-1204, CVE-2022-2785, CVE-2022-3586, CVE-2022-3595, CVE-2022-3910, CVE-2022-40768, CVE-2022-4127, CVE-2022-41849, CVE-2022-41850, CVE-2022-43945, CVE-2022-3344 for kernel
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-1204
- https://nvd.nist.gov/vuln/detail/CVE-2022-2785
- https://nvd.nist.gov/vuln/detail/CVE-2022-3586
- https://nvd.nist.gov/vuln/detail/CVE-2022-3595
- https://nvd.nist.gov/vuln/detail/CVE-2022-3910
- …
> Nopatch several CVEs for kernel

- toolkit/tools/roast/formats/qcow.go
- toolkit/tools/roast/roast.go
Adds `qcow2` as an additional output image format, similar to `vhd` and `vhdx`. Intended primarily as a convenience facility for engineers testing VM images on Linux hosts (e.g., under KVM).
---
Adds `qcow2` as a supported output format from the `roast` tool. This is a minor convenience simplification for engineers who test by booting an output Mariner image under a Linux host (e.g., KVM).
Adds new `roast` implementation for `qcow2`; implementation looks very similar to other formats, using `qemu-img` to convert from the input raw image to the desired output type.
Affects image generation tools.
Validated with a local build.
> Add support for qcow2 output images

- SPECS/gnutls/CVE-2022-2509.patch
- SPECS/gnutls/gnutls.spec
---
patch gnutls CVE-2022-2509 from [upstream](https://gitlab.com/gnutls/gnutls/-/commit/ce37f9eb265dbe9b6d597f5767449e8ee95848e2)
- patch gnutls CVE-2022-2509 from [upstream](https://gitlab.com/gnutls/gnutls/-/commit/ce37f9eb265dbe9b6d597f5767449e8ee95848e2) with modification applied to Mariner
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-2509
> patch gnutls CVE-2022-2509

- SPECS/strongswan/strongswan.signatures.json
- SPECS/strongswan/strongswan.spec
- cgmanifest.json
---
Upgrade strongswan to 5.9.8 to fix CVE-2022-40617
- Upgrade strongswan to 5.9.8 to fix CVE-2022-40617
- Set -Wno-format-security because strongswan enabled -Werror and is [explicitly incompatible](https://github.com/strongswan/strongswan/commit/1f242e772b7076b32136d86d403e77874a8f83e4#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R1457) with -Wformat-security.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-40617
- Local build succeeded
- %check section tests show same results as previous version.
- Buddy build 275418 succeeded
> Update strongswan for CVE-2022-40617

- SPECS/libconfuse/CVE-2022-40320.patch
- SPECS/libconfuse/libconfuse.spec
---
Apply libconfuse upstream patch for CVE-2022-40320
- Apply libconfuse upstream patch for CVE-2022-40320
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-40320
- Local build succeeded
- Added check section tests all pass
- Pipeline build id: 275555
> Patch libconfuse for CVE-2022-40320

- SPECS/ca-certificates/ca-certificates.spec
- SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
- SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
While I was replacing `ca-certificates-microsoft` with `ca-certificates` I forgot to add an `Obsoletes: ca-certificate-microsoft < [version]` to make sure package manager update cleanly from `ca-certificates-microsoft` to `ca-certificates`. Fixing this here.
- Add an `Obsoletes: ca-certificates-microsoft`.
Yes.
- Pipeline buddy build: 277100.
- Validated on local VM:
> Fixed updating from `ca-certificates-microsoft` to `ca-certificates`.

- SPECS/ruby/ruby.spec
---
Fix https://github.com/microsoft/CBL-Mariner/pull/4434 which had a typo, and failed to obsolete the previously separate `rubygem-bundler` package.
- Add `Obsoletes: ` entries for rubygem-bundler since it is now part of the full ruby package.
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/4434
- Local test to parse spec
> Fix rubygem-bundler provides with obsoletes

- SPECS/core-packages/core-packages.spec
---
The #4433 PR remove the `mariner-repos` -> `rpm` dependency. It turns out this made us drop `rpm` from `core-packages-container`, since we never explicitly mentioned it in the dependencies. We require `rpm` to be part of our base images, so I'm now adding it back as an explicit dependency.
- Added an explicit `Requires: rpm` to `core-packages-container`.
No.
- #4433
- None, trivial spec change.
> Made sure `rpm` is included in all base images.

- SPECS/ltp/ltp.spec
---
I've noticed that `ltp` was leaving behind files it generated while the tests were ran. Addressing this issue in this PR.
- Made sure we clean-up files generated during test runs.
- Added explicit dependency on `gawk` to be on the safe side.
No.
> Improved `ltp` package clean-up.

- SPECS/moby-containerd/add_ptrace_readby_tracedby_to_apparmor.patch
- SPECS/moby-containerd/moby-containerd.spec
---
- This PR backports an [upstream fix](https://github.com/containerd/containerd/commit/8d868dadb746aabfd3583d834510109afe9b1919) in containerd to add ptrace readby and tracedby to default AppArmor profile
- It is needed because dotnet-dump fails on Mariner and this is the root cause
- Add the upstream containerd fix through a patch - `add_ptrace_readby_tracedby_to_apparmor.patch`
- Update `moby-containerd.spec` file accordingly
**NO**
- [Overall dotnet-dump bug](https://microsoft.visualstudio.com/OS/_sprints/taskboard/Mariner%20Platform/OS/2212?workitem=41597402)
- [Backport containerd fix task on Mariner …
> Patch moby-containerd to add ptrace readby and tracedby to default AppArmor profile

- SPECS/helm/CVE-2022-23525.patch
- SPECS/helm/CVE-2022-23526.patch
- SPECS/helm/helm.spec
This change fixes CVE-2022-23525 and CVE-2022-23526.  This change was cherry-picked from main (2.0) and adapted for 1.0-dev.  It also introduces the helm self-tests.
This we verified by adding the helm self-tests and running them
> Patch helm to fix CVE fix CVE-2022-23525 and CVE-2022-23526

- SPECS/kubevirt/disks-images-provider.yaml
- SPECS/kubevirt/kubevirt.signatures.json
- SPECS/kubevirt/kubevirt.spec
- cgmanifest.json
---
Mariner HCI (AODS) needs a newer version of kubevirt. This change upgrades the package to the current latest version 0.58.0
Package upgraded to 0.58.0
No
https://dev.azure.com/mariner-org/ECF/_workitems/edit/3092/
- Buddy build id: 282644
> kubevirt: Upgrade to 0.58.0

- SPECS/python-setuptools/CVE-2022-40897.patch
- SPECS/python-setuptools/python-setuptools.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Addresses CVE-2022-49897
- Backport patch from [this](https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be) commit
- However, the change to `setuptools/tests/test_packageindex.py` that is in the commit does not apply here since the line that is being removed is not present in setuptools version 40.2.0
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-40897
- AMD64 [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=286257&view=results)
- ARM64 [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=286258&view=results)
- …
> Patch CVE-2022-40897 in python-setuptools

- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2-aarch64.json
---
This PR increases the Max Disk Size for remaining marketplace mariner images to 5GB. Initially only the marketplace gen2 image was updated. https://github.com/microsoft/CBL-Mariner/pull/4277. Like the previous PR stated, this doesn't affect BVT testing because it is only a marketplace image change, not core images.
-Changed MaxSize: 1500 in marketplace-gen2-aarch64.json & marketplace-gen1.json to MaxSize: 5000 to represent increase to 5GB disk size.
**NO**
- Pipeline build id: 285298
> Increasing marketplace images os disk size to 5GB

- SPECS/mariner-release/mariner-release.spec
Bump Mariner Release for first January update (pick-up Critical CVE fix)
> Bump Mariner Release for January 2023 Update

- toolkit/Makefile
---
Allow the msopenjdk toolchain package to be downloaded from the Microsoft repo on PMC. Currently, msopenjdk is being downloaded from the core PMC repo, but this is not the proper location for this package.
PACKAGE_URL_LIST is used in some scenarios to download toolchain packages from PMC. See [here](https://github.com/microsoft/CBL-Mariner/blob/349509304d7d3f4c4a50bf306d1b6a378e5ca01d/toolkit/scripts/toolchain.mk#L147)
This change is also present in #4573 , but am holding off on that PR after seeing issues in the test builds.
- Change PACKAGE_URL_LIST in the Makefile to include the Microsoft repo
**YES**
> Add Microsoft repo to PACKAGE_URL_LIST

- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`) …
> Disabling systemd-oomd by default in Mariner

- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Reverts microsoft/CBL-Mariner#4580
Post-merge feedback: 
A better approach was advised.
it would be better to disable the service inside the preset file, and avoid masking the service.
@aditjha-msft will start next week on the revised improvement :)
> Revert "Disabling systemd-oomd by default in Mariner"

- SPECS/curl/curl.spec
- SPECS/nghttp2/nghttp2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/resources/manifests/package/update_manifests.sh
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
This PR enables HTTP/2 support in `curl` as requested by internal customers.
- Build `curl` with HTTP/2 support by adding `nghttp2` as a build requirement
- Move `nghttp2` to the toolchain to support above change
**YES**
- Delta toolchain build succeeded
- Tested HTTP/2 functionality with new packages in a container
```console
$ curl -sI https://curl.se -o/dev/null -w '%{http_version}\n'
2
$ curl --version
curl 7.86.0 (x86_64-pc-linux-gnu) libcurl/7.86.0 OpenSSL/1.1.1k zlib/1.2.12 zstd/1.5.0 libssh2/1.9.0 nghttp2/1.46.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp …
```
> Build curl with HTTP/2 support

- toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
---
Change lock-passwd to lock_passwd in cloud-init.cfg. lock-passwd works same as lock_passwd and lock-passwd will deprecate after 2027. However, lock-passwd logs as an error in dmesg "Schema error in /etc/cloud/cloud.cfg " so we need to update it.
- Change lock-passwd to lock_passwd in cloud-init.cfg
NO
- [Bug 40934428](https://microsoft.visualstudio.com/OS/_workitems/edit/40934428): [Quality][Guest][Mariner] cloud-init schema error for 'users'
- local image build
- boot VM on Azure and verify that change is made in cloud.cfg
> update cloud-int.cfg lock-passwd to lock_passwd

- toolkit/scripts/imggen.mk
---
The ISO target (`make iso ...`) can be fragile, both to changes in the files included in the ISO's initrd, and to parallel builds. We can harden this by tracking the files included with the ISO in the makefile, as well as defining some order-only prerequisites for the initrd target.
Order-only prerequisites mean that a given target will allways be built after another target, but changing the prerequisite won't actually case a follow-on rebuild of the target. (ie `a: b | c`, `c` will always be completed before `a` starts, but changing `c` won't cause `a` to rebuild during future builds). By making all of the `iso:` target's prerequisites also order-only prerequisites for the …
> Improve robustness of ISO initrd builds

- SPECS/curl/CVE-2022-43551.patch
- SPECS/curl/curl.signatures.json
- SPECS/curl/curl.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This reverts #4577 because curl 7.87 breaks perl-WWW-Curl (also [tracked by Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027632)) and instead applies the upstream patch to fix CVE-2022-43551.
**YES**
- Pipeline builds: [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=291803&view=results) [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=291812&view=results) (both curl & perl-WWW-Curl)
> curl: downgrade to 7.86 to fix perl-WWW-curl and patch CVE-2022-43551 

- toolkit/Makefile
- toolkit/docs/coding_guide/makefiles.md
- toolkit/docs/how_it_works/5_misc.md
- toolkit/scripts/build_tag.mk
- toolkit/scripts/imggen.mk
- toolkit/scripts/pkggen.mk
- toolkit/scripts/rpmops.sh
- toolkit/scripts/srpm_expand.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/toolchain.mk
- toolkit/scripts/toolkit.mk
- toolkit/scripts/tools.mk
- toolkit/scripts/utils.mk
---
The `input-srpms` build target has not been tracking changes to miscellaneous source files in the `./SPECS/pkg/*` directories. In Mariner 1.0 we tracked these files with https://github.com/microsoft/CBL-Mariner/blob/e72e08fdf005802a4dec67c5fc9906df954b5e36/toolkit/scripts/srpm_pack.mk#L18 which was used as a dependency of srpm packing; however, this was lost in the refactor for 2.0.
Unfortunately adding this dependency tracking back has the unintended side effect of breaking Make's `--dry-run` behavior. This is used when tab completing on the command line among other things. The call to `$(shell find $(local_spec_dirs) -type f -name '*')` takes a long time to complete and is …
> Fix missing dependency tracking for spec sources, refactor Makefile to skip shell commands during dry-run

- toolkit/Makefile
- toolkit/scripts/build_tag.mk
- toolkit/scripts/rpmops.sh
---
While working on #4181 we've introduced `make` commands to retrieve the distribution tag. Accidentally, we used the `-q` switch instead of `-s` to run `make` in silent mode, thus breaking the `mainrer_rpmspec` function, which relied on `make` to retrieve the distribution tag.
- Used the correct switch for a silent `make` run.
- Fixed error when running as non-root.
No.
- #4181
> Fixed `mariner_rpmspec` command.

- SPECS/libkcapi/libkcapi.spec
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
Package builds may fail randomly while resolving the best package to provide a `BuildRequires`. This is due to an [RPM bug](https://github.com/rpm-software-management/rpm/issues/2359), where it may choose multiple conflicting packages to provide the same capability, thus causing a build break,
This change replaces makes use of the order, in which TDNF lists packages after running `tdnf provides`. Since it starts with the latest version of each package, RPM should resolve the packages correctly, when handed in this order.
This is an alternative solution to #4492 and #4645.
- Made sure we analyze packages in order printed by `tdnf provides`.
- Updated `libkcapi` to fix its …
> Worked around RPM package resolution bug.

- SPECS/python-certifi/python-certifi.signatures.json
- SPECS/python-certifi/python-certifi.spec
- cgmanifest.json
---
Upgrade python-certifi to version 2022.12.07 to address CVE-2022-23491
- Upgrade python-certifi to version 2022.12.07 to address CVE-2022-23491
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-23491
- Local Build
BuddyBuild:
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=297229&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520&l=18006)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=297230&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520&l=17947)
> Upgrade python-certifi to version 2022.12.07 to address CVE-2022-23491

- SPECS/openldap/openldap.spec
Reverts microsoft/CBL-Mariner#4693.
[Nightly build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=299222) of `main` branch failed due to a circular dependency introduced by this change.
```
ERRO[0009] Unfixable circular dependency found:	{openldap-2.4.57-8.cm2-RUN<Meta>} --> {postgresql-libs-14.5-1.cm2-BUILD<Build>} --> {postgresql-libs-14.5-1.cm2-RUN<Meta>} --> {cyrus-sasl-devel-2.1.28-1.cm2-BUILD<Build>} --> {cyrus-sasl-devel-2.1.28-1.cm2-RUN<Meta>} --> {openldap-2.4.57-8.cm2-BUILD<Build>} --> {openldap-2.4.57-8.cm2-RUN<Meta>}	error: cycle contains no pre-build SRPMs, unresolvable
```
> Revert "enable cyrus sasl"

- SPECS/calamares/calamares.spec
- SPECS/calamares/install-progress-bar-fix.patch
- SPECS/calamares/serialize-read-access.patch
---
This PR fixes two Calamares bugs:
- Calamares would crash sometimes when refreshing partition bars during partitioning step due to a race condition.
- Calamares would crash sometimes when installing due to wrong expectations of a return code from a process.
- Patch race condition leading to SEGFAULT.
- Patch invalid treatment of return code from installation step.
- Add requires for cryptography/lvm2 binaries used by Calamares explicitly. 
**NO**
-  ADO bug 42752147
- Local ISO build. I was able to consistently trigger previously fatal paths and successfully install Mariner.
- BuddyBuild of calamares.
> Fix calamares bugs and update requires

- SPECS-EXTENDED/tk/tk.spec
- cgmanifest.json
---
Fix install requires on tcl/tcl-devel
- fix install requires on tcl/tcl-devel by using version constraints
- lint spec
- update cgmanifest entry to use https in downloadUrl
NO
[AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=294120)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=294129)
> Fix package tk install requires on tcl & tcl-devel

- SPECS/systemd/99-mariner.preset
- SPECS/systemd/systemd-bootstrap.signatures.json
- SPECS/systemd/systemd-bootstrap.spec
- SPECS/systemd/systemd.signatures.json
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This PR creates a mariner specific preset file and uses this to disable the systemd-oomd service and socket because these are dependent on cgroupv2 being enabled and that is not currently the case with Mariner by default. This was originally causing Mariner's state to be degraded, and we will be disabling systemd-oomd by default, and allow someone to enable if needed.
- Created 99-mariner.preset file to store any future mariner specific preset decisions
- Added logic in spec files for systemd to apply preset file in respective locations
NO
- https://dev.azure.com/microsoft/OS/_workitems/edit/41521816
- Pipeline build id: 299675
> Disable systemd-oomd service & socket through 99-mariner.preset file

- toolkit/scripts/build_tag.mk
---
Previous fix for a tooling bug introduces some odd behavior on some systems (those that may not link /bin/sh to /bin/bash).
Make invokes `/bin/sh` for its `$(shell ...)` operator by default, and `[[ ... ]]` is generally not supported there. Convert this test from `[[ $UID == 0 ]]` to the much more confusing `[ -n "$$UID" ] && [ "$$UID" -eq 0 ]` (Using [ expr1 -a expr2 ] gave the error `/bin/sh: 1: [: Illegal number:` Clearly `sh`'s test is evaluating the full expression and not bailing out early in the case of an empty string)
- Use POSIX compliant test when calculating `$BUILD_NUMBER`.
**NO**
-https://github.com/microsoft/CBL-Mariner/pull/4663/files#diff-176d60ee660777d79f61acdf5 …
> Switch to posix compliant invocation of test in mk file

- SPECS/flux/disable-static-library.patch
- SPECS/flux/flux.signatures.json
- SPECS/flux/flux.spec
- SPECS/influx-cli/influx-cli.signatures.json
- SPECS/influx-cli/influx-cli.spec
- SPECS/influxdb/influxdb.signatures.json
- SPECS/influxdb/influxdb.spec
- cgmanifest.json
---
- Fixed `libflux.so` file linking in `flux` package
- Upgraded `flux` from `0.179.0` to version `0.191.0`
- Upgraded `influxdb` from `2.4.0` to version `2.6.1`
- Upgraded `influx-cli` from `2.4.0` to version `2.6.1`
**NO**
- Local
- [Official Pipeline](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=300976&view=results)
> upgrading flux, influxdb, influx-cli

- SPECS/mariadb/generate_source_tarball.sh
---
The `generate_source_tarball.sh` scripts  were updated to use parameters. The mariadb version needs to use the current version in additional locations but is currently  using `$1` which leads to the internal directory inside the tarball being `mariadb-` rather than `mariadb-x.y.z`.
- Correctly use `$PKG_VERSION` in mariadb's `generate_source_tarball.sh`
**NO**
- local build
> Update mariadb generate_source_tarball.sh to use pkgver correctly

- SPECS/mariadb/generate_source_tarball.sh
---
Cherry-pick of commit 271aac9fe62f7c5893bc2152ec9d4bd484347782 (#4724) into 1.0-dev
> Cherry-pick 'Pass pkgver to tar in mariabd src tar generation script (#4724)'

- SPECS/influx-cli/influx-cli.spec
- SPECS/influxdb/influxdb.spec
---
Auto upgrader upgraded go from 1.18 to 1.19. Which made influxdb and influx-ci build it using 1.19 version which they are not compatible with. Fixed influxdb and influx-cli build by requiring to use go 1.18.8
- Fixed influxdb by requiring to use go 1.18.8
- Fixed influx-cli by requiring to use go 1.18.8
**NO**
- Local
- Pipeline build id: [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=302206&view=results)
> Fixing influxdb and influx-cli build

- SPECS/dbus/CVE-2022-42010.patch
- SPECS/dbus/CVE-2022-42011.patch
- SPECS/dbus/CVE-2022-42012.patch
- SPECS/dbus/dbus.spec
---
- Resolve CVE-2022-42010, CVE-2022-42011 and CVE-2022-42012
- Resolve CVE-2022-42010, CVE-2022-42011 and CVE-2022-42012
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-42010
- https://nvd.nist.gov/vuln/detail/CVE-2022-42011
- https://nvd.nist.gov/vuln/detail/CVE-2022-42012
- Local Build
> [1.0] Resolve dbus CVE-2022-42010, CVE-2022-42011, CVE-2022-42012

- SPECS/influx-cli/influx-cli.spec
- SPECS/influxdb/influxdb.spec
---
Fix `influxdb` & `influx-cli` build break
- Drop requirement on `golang-packaging` which causes to install latest go `1.19` while there is hard requirement for go1.18
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/4598
- NA
- Local Build
Buddy Build: 
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=303716&view=results)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=303720&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520)
- Full Build: [Delta …
> influxdb: fix build break

- SPECS/util-linux/libblkid-src-probe-check-for-ENOMEDIUM.patch
- SPECS/util-linux/util-linux.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch util-linux to add patch to prevent cdrom probe on Azure VMs
- Patch util-linux to add patch to prevent cdrom probe on Azure VMs
**NO**
- fixes #[41166398](https://microsoft.visualstudio.com/OS/_workitems/edit/41166398?src=WorkItemMention&src-action=artifact_link): many noise messages show up in dmesg
- NA
- [BuddyBuild](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304077&view=results)
- Tested built RPM on an AKS cluster node
> Patch util-linux to add patch to prevent cdrom probe on Azure VMs

- SPECS/apr-util/apr-util.signatures.json
- SPECS/apr-util/apr-util.spec
- cgmanifest.json
---
Update 1.6.3 to address CVE-2022-25147
Update license to use SPDX identifier
- Update 1.6.3 to address CVE-2022-25147
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-25147
- AMD: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304511&view=results
- ARM: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=304510&view=results
> Update apr-util to 1.6.3 for CVE-2022-25147

- SPECS/kernel/CVE-2022-41218.nopatch
- SPECS/kernel/CVE-2022-42328.nopatch
- SPECS/kernel/CVE-2022-42329.nopatch
- SPECS/kernel/CVE-2022-4662.nopatch
- SPECS/kernel/CVE-2023-0266.nopatch
- SPECS/kernel/CVE-2023-0468.nopatch
- SPECS/kernel/CVE-2023-23559.nopatch
---
Nopatch CVE-2022-41218, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-0266, CVE-2023-0468, CVE-2023-23559 
- Address CVE-2022-41218, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-0266, CVE-2023-0468, CVE-2023-23559 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-41218 
- https://nvd.nist.gov/vuln/detail/CVE-2022-42328 
- https://nvd.nist.gov/vuln/detail/CVE-2022-42329 
- https://nvd.nist.gov/vuln/detail/CVE-2022-4662 
- https://nvd.nist.gov/vuln/detail/CVE-2023-0266 
- https://nvd.nist.gov/vuln/detail/CVE-2023-0468 
- https://nvd.nist.gov/vuln/detail/CVE-2023-23559
> Nopatch kernel to address CVE-2022-41218, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-0266, CVE-2023-0468, CVE-2023-23559 

- SPECS-EXTENDED/podman/podman.spec
---
Fix podman build break by forcing it to build with golang 1.18.8 instead of 1.19 (which fails to build)
- Change podman to build with golang <= 1.18.8
**NO**
- Pipeline build id: 306334 (x64) 306379 (arm64)
> podman: update to build with golang 1.18

- SPECS/hyperv-daemons/CVE-2022-0742.nopatch
- SPECS/hyperv-daemons/CVE-2022-27666.nopatch
- SPECS/hyperv-daemons/CVE-2023-0266.nopatch
---
Nopatch hyperv-daemons for CVE-2023-0266, CVE-2022-0742, CVE-2022-27666
- Nopatch hyperv-daemons for CVE-2023-0266, CVE-2022-0742, CVE-2022-27666
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-27666
- https://nvd.nist.gov/vuln/detail/CVE-2022-0742
- https://nvd.nist.gov/vuln/detail/CVE-2023-0266
> Nopatch hyperv-daemons for CVE-2023-0266, CVE-2022-0742, CVE-2022-27666

- SPECS/kubevirt/fgetxattr-for-relabel.patch
- SPECS/kubevirt/kubevirt.spec
---
Add an upstream patch to fix kubevirt issue #8544, PR #8594. This bug has been fixed only in the latest version v0.59.0 which is still at alpha2 release. Without this fix, virt-handler containers do not start on a system with selinux set to enforced. 
To unblock mariner HCI and AODS testing on v0.58.0 the required patch has been pulled in v0.58.0. Once version 0.59.0 is released, the rpms will be upgraded, and this patch can be removed.
Added an upstream patch to fix kubevirt issue #8544, PR #8594
**NO**
- Pipeline build id: Full pipeline build 304370
The golden containers consuming the new rpms have been tested to confirm kubevirt is deployed as expected.
> Add an upstream patch to kubevirt to fix an SELinux issue

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
debuginfo packages are generated via find-debuginfo script. This script is packaged in the [debugedit rpm](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/debugedit/debugedit.spec). The script is run after the %install phase of an rpm. It looks at the BUILDROOT for its sources. Specifically it will look for all the executables in this [line](https://sourceware.org/git/?p=debugedit.git;a=blob;f=scripts/find-debuginfo.in;h=7dec3c3bfdc59a5b3cd53838f9cf748c0b1a932c;hb=HEAD#l422).  Because we were initally installing vmlinux with 644 permissions, it was not seen as an executable and not analyzed by find-debuginfo. Thus, only the modules had their debuginfo extracted leading …
> Install vmlinux with root executable permissions

- SPECS/kernel/CVE-2022-36280.nopatch
- SPECS/kernel/CVE-2022-41218.nopatch
- SPECS/kernel/CVE-2022-4139.nopatch
- SPECS/kernel/CVE-2022-42328.nopatch
- SPECS/kernel/CVE-2022-42329.nopatch
- SPECS/kernel/CVE-2022-4662.nopatch
- SPECS/kernel/CVE-2023-23559.nopatch
---
Address CVE-2022-36280, CVE-2022-41218, CVE-2022-4139, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-23559
- Nopatch CVE-2022-36280, CVE-2022-41218, CVE-2022-4139, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-23559
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-36280
- https://nvd.nist.gov/vuln/detail/CVE-2022-41218
- https://nvd.nist.gov/vuln/detail/CVE-2022-4139
- https://nvd.nist.gov/vuln/detail/CVE-2022-42328
- https://nvd.nist.gov/vuln/detail/CVE-2022-42329
- https://nvd.nist.gov/vuln/detail/CVE-2022-4662
- https://nvd.nist.gov/vuln/detail/CVE-2023-23559
> Nopatch kernel to address CVE-2022-36280, CVE-2022-41218, CVE-2022-4139, CVE-2022-42328, CVE-2022-42329, CVE-2022-4662, CVE-2023-23559

- SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
Pull libappstream-glib update to fix 2.0 extended build
* libappstream-glib: drop generating docs to fix build
> Fix build-break for libappstream-glib (#4852)

- SPECS-EXTENDED/podman/podman.signatures.json
- SPECS-EXTENDED/podman/podman.spec
---
Bump version of `gvproxy` to enable build with go1.19
- Bump version of `gvproxy`
**NO**
- NA
- NA
- Local Build
BuddyBuild:
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=312966&view=logs&j=28fbb862-d6a2-53ee-8718-d863c03f3031&t=2ebaed91-a9fa-55b6-3efb-2aa507a8a8f8&l=1685)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=312966&view=logs&j=522c83f1-8899-5fcf-b21d-13b08414df79&t=f489d446-2b7c-5358-0b1a-188291f003bd&l=1685)
> Fix podman build-break

- SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
- SPECS/kernel-hci/kernel-hci.spec
Cherry-pick of abe0019
There was a bug where debug sources were missing from sources that were built into vmlinux. This is because find_debuginfo, the script which extracts debug sources, looks only at files which are executable. Because we were installing vmlinux as 644, it was being skipped. Therefore, change to install with permissions 744.
---
Cherry-pick of abe001946ec6e9889b03dc8fe8d2ff0a89cd7660
debuginfo packages are generated via find-debuginfo script. This script is packaged in the [debugedit rpm](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/debugedit/debugedit.spec). The script is run after the %install phase of an rpm. It looks at the BUILDROOT for its …
> kernel-hci: Install vmlinux with root executable permissions

- SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
- SPECS/kernel-azure/kernel-azure.spec
Cherry-pick of abe001946ec6e9889b03dc8fe8d2ff0a89cd7660
There was a bug where debug sources were missing from sources that were built into vmlinux. This is because find_debuginfo, the script which extracts debug sources, looks only at files which are executable. Because we were installing vmlinux as 644, it was being skipped. Therefore, change to install with permissions 744.
---
Cherry-pick of abe001946ec6e9889b03dc8fe8d2ff0a89cd7660
debuginfo packages are generated via find-debuginfo script. This script is packaged in the [debugedit rpm](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/debugedit/debugedit.spec). The script is run after the %install phase of an rpm. It looks …
> kernel-azure: Install vmlinux with root executable permissions

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel-hyperv/kernel-hyperv.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
There was a bug where debug sources were missing from sources that were built into vmlinux. This is because find_debuginfo, the script which extracts debug sources, looks only at files which are executable. Because we were installing vmlinux as 644, it was being skipped. Therefore, change to install with permissions 744.
---
Backport of [abe0019](https://github.com/microsoft/CBL-Mariner/commit/abe001946ec6e9889b03dc8fe8d2ff0a89cd7660)
debuginfo packages are generated via find-debuginfo script. This script is packaged in the [debugedit rpm](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/debugedit/debugedit.spec). The script is run after the %install phase of an rpm. It looks …
> [1.0] kernel, kernel-hyperv: Install vmlinux with root executable permissions

- SPECS/kernel-mshv/kernel-mshv.spec
Cherry-pick of abe0019
There was a bug where debug sources were missing from sources that were built into vmlinux. This is because find_debuginfo, the script which extracts debug sources, looks only at files which are executable. Because we were installing vmlinux as 644, it was being skipped. Therefore, change to install with permissions 744.
---
Cherry-pick of abe001946ec6e9889b03dc8fe8d2ff0a89cd7660
debuginfo packages are generated via find-debuginfo script. This script is packaged in the [debugedit rpm](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/debugedit/debugedit.spec). The script is run after the %install phase of an rpm. It looks at the BUILDROOT for its …
> kernel-mshv: Install vmlinux with root executable permissions

- SPECS/haproxy/CVE-2023-25725.nopatch
- SPECS/haproxy/haproxy.signatures.json
- SPECS/haproxy/haproxy.spec
- cgmanifest.json
---
Bump package version to 2.4.22 to patch CVE-2023-25725
Reference:
Upstream: https://github.com/haproxy/haproxy/commit/a8598a2eb11b6c989e81f0dbf10be361782e8d32
Release Note: https://git.haproxy.org/?p=haproxy-2.4.git;a=log;h=refs/tags/v2.4.22
- Bump version to 2.4.22
- Lint spec
NO
NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-25725
[AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=314554)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=314555)
> Bump haproxy version to 2.4.22 for CVE-2023-25725

- toolkit/docs/formats/imageconfig.md
This PR adds basic documentation related to using the `CGroup` key with its associated values to enable cgroupv2 in Mariner images on boot. The CGroup key is used in the KernelCommandLine options to enable either version one (default) or version two, which triggers the systemd.cfg file to use a config value of `systemd.unified_cgroup_hierarchy=1` on boot.
> Documentation for CGroup toggle in toolkit/docs/formats/imageconfig.md to generate Mariner images with cgroupv2

- SPECS/mstflint/mstflint.spec
---
This PR enables adb-generic-tools for mstflint's build config which results into compiling the following tools: mstreg and mstlink. This config flag was requested by Nvidia.
**NO**
- Built with RUN_CHECK=y
- Installed the mstflint rpm package using tdnf on Mariner2.0 successfully
> Enable adb-generic-tools in mstflint build config

- SPECS/telegraf/telegraf.signatures.json
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
---
Upgrade telegraf to 1.25.2 to fix several CVEs in vendored components and support customer requirements.
- Upgrade to latest upstream version to fix the following CVEs in vendored packages:
CVE-2019-3826, CVE-2022-1996, CVE-2022-29190, CVE-2022-29222, CVE-2022-29189, 
CVE-2022-32149, CVE-2022-23471
**NO**
https://nvd.nist.gov/vuln/detail/CVE-2019-3826
https://nvd.nist.gov/vuln/detail/CVE-2022-1996
https://nvd.nist.gov/vuln/detail/CVE-2022-29190
https://nvd.nist.gov/vuln/detail/CVE-2022-29222
https://nvd.nist.gov/vuln/detail/CVE-2022-29189
https://nvd.nist.gov/vuln/detail/CVE-2022-32149
https://nvd.nist.gov/vuln/detail/CVE-2022-23471
- [Test build for amd64, …
> Upgrade telegraf to 1.25.2 to fix several vendored CVEs

- CVE-2023-0796.nopatch
- CVE-2023-0797.nopatch
- CVE-2023-0798.nopatch
- CVE-2023-0799.nopatch
- SPECS/libtiff/CVE-2023-0795.patch
- SPECS/libtiff/CVE-2023-0800.patch
- SPECS/libtiff/libtiff.spec
---
CVE-2023-0795 CVE-2023-0796 CVE-2023-0797 CVE-2023-0798 CVE-2023-0799
**NO**
- Dependent on https://github.com/microsoft/CBL-Mariner/pull/4876
- combination of libtiff rotateImage() changes from https://gitlab.com/libtiff/libtiff/-/commits/master/tools/tiffcrop.c:  9c22495e5eeeae9e00a1596720c969656bb8d678, 688012dca2c39033aa2dc7bcea9796787cfd1b44, 69818e2f2d246e6631ac2a2da692c3706b849c38
- CVE-2023-0795 CVE-2023-0796 CVE-2023-0797 CVE-2023-0798 CVE-2023-0799
- [pipeline build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=310670&view=results)
- local build
> libtiff: CVE 2023-0795

- SPECS/libtiff/CVE-2023-0795.patch
- SPECS/libtiff/CVE-2023-0796.nopatch
- SPECS/libtiff/CVE-2023-0797.nopatch
- SPECS/libtiff/CVE-2023-0798.nopatch
- SPECS/libtiff/CVE-2023-0799.nopatch
- SPECS/libtiff/CVE-2023-0800.patch
- SPECS/libtiff/CVE-2023-0801.nopatch
- SPECS/libtiff/CVE-2023-0802.nopatch
- SPECS/libtiff/CVE-2023-0803.nopatch
- SPECS/libtiff/CVE-2023-0804.nopatch
- SPECS/libtiff/libtiff.spec
---
Add patches to fix below CVE's:
CVE-2023-0795
CVE-2023-0796
CVE-2023-0797
CVE-2023-0798
CVE-2023-0799
CVE-2023-0800
CVE-2023-0801
CVE-2023-0802
CVE-2023-0803
CVE-2023-0804
- Add patch for CVE-2023-0795,CVE-2023-0796,CVE-2023-0797,CVE-2023-0798 & CVE-2023-0799
Also includes fixes for
. tiffcrop correctly update buffersize after rotateImage(). fix#520
. TIFFClose() avoid NULL pointer dereferencing. fix#515
- Add patch for CVE-2023-0800,CVE-2023-0801,CVE-2023-0802,CVE-2023-0803 & CVE-2023-0804
NO
NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-0795
- https://nvd.nist.gov/vuln/detail/CVE-2023-0796
- https://nvd.nist.gov/vuln/detail/CVE-2023-0797
- …
> Patch libtiff for CVE-2023-0795(to 0799) and CVE-2023-0800(to 0804)

- SPECS-EXTENDED/buildah/buildah.spec
---
Fix buildah install error
- Change runtime dependency to libcontainers-common and moby-runc
- Lint spec
NO
NA
NA
[AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=318252)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=318253)
[NOTE: buildah srpm is built.
The failure is due to "unresolved dependency" on runtime package podman.
The reason is PMC has multiple podman versions. However, tdnf is unable to download
version 2.2.1-5: "stderr: 1. nothing provides container-selinux needed by podman-2.2.1-5.cm2"]
> Fix package install error for buildah

- SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
- SPECS/cyrus-sasl/cyrus-sasl.spec
---
Fixes several issues with the cyrus-sasl and bootstrap packages to address a build break. 
Found 5 problems
file /usr/lib/libsasl2.so.3.0.0 conflicts between attempted installs of cyrus-sasl-bootstrap-lib-2.1.28-3.cm2.x86_64 and cyrus-sasl-lib-2.1.28-2.cm2.x86_64
file /usr/lib/sasl2/libanonymous.so.3.0.0 conflicts between attempted installs of cyrus-sasl-bootstrap-lib-2.1.28-3.cm2.x86_64 and cyrus-sasl-lib-2.1.28-2.cm2.x86_64
file /usr/lib/sasl2/libsasldb.so.3.0.0 conflicts between attempted installs of cyrus-sasl-bootstrap-lib-2.1.28-3.cm2.x86_64 and cyrus-sasl-lib-2.1.28-2.cm2.x86_64
file /usr/sbin/sasldblistusers2 conflicts …
> Move -lib obsoletes to correct subpackage and remove AutoProv: No in cyrus-sasl-bootstrap to address build break

- toolkit/tools/scheduler/schedulerutils/buildworker.go
---
Fix a bug in parseCheckSection of the go tooling & upgrade test failures to warning.
- Removed a colon from buildworker.go
- Upgraded a log statement from debug to warning.
NO
- Pipeline build id: 320300
> Fixing CHECK_BUILD_RETRIES issues

- SPECS/initramfs/initramfs.spec
- SPECS/kernel-mshv/kernel-mshv.signatures.json
---
- conditionally move kernel-mshv initrd if it exists
NO
- rpm installed on a kata image, verified it reboots and systemd reinstall works. 
Fixes: 
- https://github.com/microsoft/CBL-Mariner/pull/4436
> Only conditionally move kernel-mshv initrd if it exists

- SPECS/gnupg2/gnupg2.signatures.json
- SPECS/gnupg2/gnupg2.spec
- SPECS/libgpg-error/libgpg-error.signatures.json
- SPECS/libgpg-error/libgpg-error.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Upgrade gnupg2 to 2.4.0
- Upgrade libgpg-error to 1.46 to support gnupg2-2.4.0
- https://nvd.nist.gov/vuln/detail/CVE-2022-3515
Build started under buildId - 320624
- https://nvd.nist.gov/vuln/detail/CVE-2022-3515
- Pipeline build id: 320624
> Upgrade gnupg2 to v2.4.0 to address CVE-2022-3515

- SPECS/grpc/grpc.spec
---
Add python3-grpcio (python binding for gRPC) for aarch64 machine. 
- Change: Remove usages of python macros as it was causing the aarch64 build to get stuck.
**YES/NO**
NO
- AMD Pipeline build id:  [319306](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319306&view=results)
- ARM Pipeline build id:  [319302](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=319302&view=results)
> gRPC: add python binding for gRPC (python3-grpcio) for aarch64

- SPECS/rust/rust.signatures.json
Reverts microsoft/CBL-Mariner#5064
After talking with Jon, I was able to get the original cargo from the source RPM of the built package and uploaded it. The revert of PR and restoring original cargo file is needed so that it does not invalidate already built rust versions.
Original cargo tarball was restored in this pipeline https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327188&view=results
> Revert "rust: update signatures to fix build break"

- SPECS/heimdal/CVE-2022-45142.patch
- SPECS/heimdal/heimdal.spec
---
Add a patch for CVE-2022-45142 affecting heimdal package. The fix is extracted from this mailing list discussion: https://www.openwall.com/lists/oss-security/2023/02/08/1
- Add patch file for CVE-2022-45142
- Bump release number for heimdal
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-45142
- aarch64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327269&view=results
- x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=327268&view=results
> heimdal: add patch for CVE-2022-45142

- SPECS/vim/vim.signatures.json
- SPECS/vim/vim.spec
- cgmanifest.json
Upgrade vim to v9.0.1402 Fix CVE-2023-1264
Auto upgrade pipeline run -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328371&view=results
AMD64 build -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328405&view=results
ARM64 build -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=328406&view=results
CVE link: https://nvd.nist.gov/vuln/detail/CVE-2023-1264
> vim: Upgrade vim to 9.0.1402 Fix CVE-2023-1264

- SPECS/rpm-ostree/rpm-ostree-drop-lint-which-treats-warning-as-error.patch
- SPECS/rpm-ostree/rpm-ostree.spec
---
With the recent bump of rust to 1.62.0 -> 1.68.0 some of lints break the build.
Modify the lint `#![forbid(unused_must_use)]` -> `#![warn(unused_must_use)]`
This change does not change anything semantically and enables the build with
the recent compiler (1.68.0).
This is a workaround till, we upgrade `rpm-ostree` to a more recent version.
- Modify a lint to enable build
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/5091
- NA
- Buddy Build (both ARM & AMD): [PR-5122](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=329695&view=results)
- Full Delta …
> rpm-ostree: introduce patch to workaround a breaking lint

- toolkit/docs/building/prerequisites-mariner.md
- toolkit/docs/building/prerequisites-ubuntu.md
---
Update the documents describing the build machine prerequisites.
- Use tdnf instead of dnf to install on Mariner
- Remove python2, bison and gcc from Mariner prereqs
- Remove python-minimal and bison from Ubuntu prereqs
**NO**
- Manual builds on Azure virtual machines using the images and script below.
Mariner test image: (note: some additional parameters are used as well, such as --admin-username and --ssh-key-values)
```
az vm create --image MicrosoftCBLMariner:CBL-Mariner:cbl-mariner-2-gen2:latest --size Standard_D16ds_v5 --os-disk-size-gb 120 --public-ip-sku Standard
```
Ubuntu test image:
```
az vm create --image …
```
> Update CBL-Mariner build prerequisites

- toolkit/tools/scheduler/schedulerutils/buildworker.go
---
Other parts of the pipeline couldn't parse the log names to mark test pass/fail because of the log renaming, so the last attempt isn't getting renamed anymore. Also, the logic has been fleshed out more for buildAttempts / checkAttempts.
- Doing retry.Run multiple times to separate buildAttempts, checkAttempts, and the last buildAttempt (not renaming log file on check failure for this single attempt).
NO
- Pipeline build id: 322456
> Separating buildAttempts & checkAttempts in build tooling & edge case fix

- SPECS/kata-containers/kata-containers.spec
- SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
---
This PR improves UVM memory consumption behavior in kata-containers
The associated commit is the only change. It adds a patch file and introduce new variables for kata-containers make.
**NO**
- Internal work item:¨https://microsoft.visualstudio.com/OS/_workitems/edit/43668151
- Buddy build: https://github.com/microsoft/CBL-Mariner/pull/5134
- verified RPM was patched and that CLH config contains proper variables/values
- Application of the patched RPM in AKS clusters, testing various pod deployments with different memory limits and without memory limits
> kata-containers: integrate fix to reduce UVM memory consumption

- SPECS/ccache/ccache.signatures.json
- SPECS/ccache/ccache.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade to latest version of ccache- 4.8. See [release notes](https://ccache.dev/releasenotes.html#_ccache_4_8)
Remove ccache symlinks to clang when clang is not installed. This resolves issues building some packages (such as systemd) where meson detects clang in the path, but errors out (since the clang symlinks were created and the clang package was not installed).
- Update ccache to version 4.8
- Modify ccache to remove broken clang symlinks
**YES**
- X64 buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=331983&view=results
- ARM64 buddy build: …
> ccache: update to 4.8

- SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
---
Latest LTS `kernel` is no longer compatible with this version of the `mlnx-ofa_kernel`. Set BuildRequires on last known good kernel. This package should be upgraded to match the kernel package.
- Update mlnx-ofa_kernel's BuildRequires to use kernel 5.15.87.1
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=332043&view=results
- Delta build (shows 5.15.102.1 kernel built and new mlnx-ofa_kernel): https://dev.azure.com/mariner-org/mariner/_build/results?buildId=332063&view=logs&s=444ee1b5-8b3f-5598-a629-e88326f0c2f9
- Full build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=3323 …
> Update mlnx-ofa_kernel's BuildRequires to use kernel 5.15.87.1

- SPECS/msft-golang/msft-golang.signatures.json
- SPECS/msft-golang/msft-golang.spec
- cgmanifest.json
---
- Bump version to 1.19.7 to address CVE-2022-41722, CVE-2022-41724, CVE-2022-41725, CVE-2022-41723, CVE-2023-24532
- Bump version to 1.19.7 to address CVE-2022-41722, CVE-2022-41724, CVE-2022-41725, CVE-2022-41723, CVE-2023-24532
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-41722
- https://nvd.nist.gov/vuln/detail/CVE-2022-41723
- https://nvd.nist.gov/vuln/detail/CVE-2022-41724
- https://nvd.nist.gov/vuln/detail/CVE-2022-41725
- https://nvd.nist.gov/vuln/detail/CVE-2023-24532
- Local Build
Buddy Build: [PR-5162](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=334336&view=results)
> msft-golang: bump version to 1.19.7 to address CVE-2022-41722, CVE-2022-41724, CVE-2022-41725, CVE-2022-41723, CVE-2023-24532

- SPECS/telegraf/generate_source_tarball.sh
- SPECS/telegraf/telegraf.signatures.json
- SPECS/telegraf/telegraf.spec
- cgmanifest.json
---
Updating `telegraf` to fix a CVE in its vendored sources for `containerd`.
- Updated `telegraf` to version 1.26.0.
- Added the `generate_source_tarball.sh` script to enable auto-upgrades.
No.
- https://github.com/influxdata/telegraf/pull/12693
- https://nvd.nist.gov/vuln/detail/CVE-2022-23471
> Updated `telegraf` to 1.26.0 to fix CVE-2022-23471

- SPECS-EXTENDED/libgxps/libgxps.spec
- SPECS-EXTENDED/netpbm/netpbm.spec
- SPECS-EXTENDED/openjpeg2/openjpeg2.spec
- SPECS/gd/gd.spec
- SPECS/gdk-pixbuf2/gdk-pixbuf2.spec
- SPECS/lcms2/lcms2.spec
- SPECS/libgdiplus/libgdiplus.spec
- SPECS/libtiff/libtiff.spec
- SPECS/libwebp/libwebp.spec
---
Recent version bump for `libtiff` (#5154) introduced a bump in the version of its shared library. I missed that during build validation and I'm fixing this here.
**NOTE**: skipping the release bump in `libtiff.spec` itself despite the change, since we haven't had a successful build in our pipelines, yet.
- Forced rebuild of packages with a BR on `libtiff`.
No.
- #5154
- https://nvd.nist.gov/vuln/detail/
Buddy builds:
- [Buddy builds](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=336641&view=results).
- ^Failing ptest runs due to unrelated issues with test runs for `gtk2` and `gdk-pixbuf2`.
- ^Failing `lcms2` build related to our tooling not being smart enough …
> Updated packages with a BR on `libtiff`.

- SPECS/R/0001-configure-fix-compilation-with-curl-8.0.0.patch
- SPECS/R/R.spec
---
Fix Build break with bump of curl to 8.0.1
- Introduce patch to resolve build break with curl >= 8.0.0
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/5172
- NA
- Local Build
- Full Build [PR-5194](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=336378&view=results)
NOTE: The bump to curl 8.0.0 is not a real breaking change from 7.x as per [this](https://daniel.haxx.se/blog/2023/03/20/curl-8-0-0-is-here/)
> R: fix build with curl >= 8.0.0

- SPECS/cloud-hypervisor/CVE-2023-28448.patch
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
The versionize crate used by cloud-hypervisor is impacted by CVE-2023-28448. This PR patches the vulnerability in the vendored crate.
- Patch CVE-2023-28448 in cloud-hypervisor's vendored versionize crate
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-28448
- Pipeline build id: 337951
> cloud-hypervisor: patch vendored versionize crate to fix CVE-2023-28448

- toolkit/scripts/imggen.mk
---
We had a bug where we used `$(if $(UNATTENDED_INSTALLER),--unattended-install)` to gate unattended iso installations instead of `$(if $(filter y,$(UNATTENDED_INSTALLER)),--unattended-install)`. This means that `UNATTENDED_INSTALLER=n` would still enable unattended installer mode.
- iso tools now respect `UNATTENDED_INSTALLER=n` 
**NO**
- Local builds: `sudo make iso REBUILD_PACKAGES=n REBUILD_TOOLS=y CONFIG_FILE=./imageconfigs/full.json UNATTENDED_INSTALLER=n` now works while it failed before.
> Fix unattended flag handling

- SPECS/cloud-hypervisor/CVE-2023-28448.patch
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
Patch cloud-hypervisor for CVE-2023-28448 in vendored versionize crate
- Patch cloud-hypervisor for CVE-2023-28448 in vendored versionize crate
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-28448
- Local individual package build succeeded
- Pipeline build id: 339285
> Patch cloud-hypervisor for CVE-2023-28448 in vendored versionize crate

- SPECS/mariner-release/mariner-release.spec
The Mariner Release version on main was behind the version on the Mariner 2.0 branch.  This fix merges the change I just made to bump the Mariner Release with the version that was on the 2.0 branch.  This fixes the ChangeLog and bumps the release version by 1 again.
In short the main branch was at -35, the 2.0 branch was at -36.  My previous PR bumped main to -36.  But main should have already been at -36 and the bump should have taken it to -37.  This change corrects that.
> Fix Mariner Release Bump

- toolkit/scripts/tools.mk
---
When we invoke our build commands it is usually of the form `sudo make ...` since we need permissions to create mount points, overlays, chroots, etc. 
`go build` will automatically pull any missing go modules during the build. This has a side-effect of polluting the `$GOPATH` (default is `~/go`) with modules owned by the root user when we build the go tools (since we are invoking `sudo make ...`). This can be fixed via an occasional invocation of `sudo chown -R $USER:$USER ~/go` but it would be better if we just never broke the files in the first place.
We can query the variable `$SUDO_USER` to see if the command is being invoked via a call to `sudo`, it will be empty otherwise. …
> Don't make go modules owned by root

- SPECS/moby-runc/generate-sources.sh
- SPECS/moby-runc/moby-runc.signatures.json
- SPECS/moby-runc/moby-runc.spec
- cgmanifest.json
---
moby-runc: Upgrade to 1.1.5 to fix CVE-2023-28642, CVE-2023-27561, CVE-2023-25809
- CVE-2023-28642
- CVE-2023-27561
- CVE-2023-25809
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-28642
- https://nvd.nist.gov/vuln/detail/CVE-2023-27561
- https://nvd.nist.gov/vuln/detail/CVE-2023-25809
- [Buddy Build AMD: 343538](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=343538&view=results)
- [Buddy Build ARM: 343537](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=343537&view=results)
> moby-runc: Upgrade to 1.1.5 to fix CVE-2023-28642, CVE-2023-27561, CVE-2023-25809

- toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
---
This PR is to change disable_root option to true in cloud-init.cfg to prevent SSH logging in for root access. The Penguinator test called verify_no_pre_exist_users() which also failed due to this as when disable_root is set to false.
From cloud-init: [Root login can be enabled/disabled using the disable_root config key.](https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/modules.html)
Verify_no_pre_exist_users() checks if [matching pattern string](https://github.com/microsoft/lisa/blob/ae6f8998fafc4b8c8b746ad67f1c5f7d9f11acf9/microsoft/testsuites/core/azure_image_standard.py#L892) exits in …
> Cloud-init disable root

- toolkit/scripts/imggen.mk
---
The `$(image_package_cache_summary):` target in imggen.mk isn't called during normal builds. It was missing the `--toolchain-rpms-dir=` that the normal branch has.
- Add `--toolchain-rpms-dir=` to the call to `imagepkgfetcher` used for repopulating based on cache files.
**NO**
Inspection
> Also pass toolchain dir to external package cache fetcher

- SPECS/nginx/nginx.signatures.json
- SPECS/nginx/nginx.spec
Cherry-pick critical nginx CVE fix to 2.0 branch
> Upgrade bundled njs version in nginx to 0.7.12 to fix CVE-2020-19692 and CVE-2020-19695

- SPECS/gcovr/gcovr.spec
---
`gcovr` fails to run on fresh install due to missing runtime dependencies. The original Fedora spec we added assumes runtime requirements are generated automatically, which is not the case for Mariner at this time. So, we add those runtime requirements in manually.
- `gcovr`: Add runtime deps on `python3-lxml`, `python3-jinja2`, `python3-pygments`
**NO**
- [OS/43161208](https://microsoft.visualstudio.com/OS/_workitems/edit/43161208)
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=345599)
> Add runtime requirements to gcovr package

- SPECS-EXTENDED/kernel-rt/kernel-rt.spec
- SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
- SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-azure/kernel-azure.spec
- SPECS/kernel-hci/kernel-hci.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Because the kernel's vmlinux is now being scanned by `find-debuginfo` as a result of #4871, the default arguments set by `rpm` for `find-debuginfo` cause vmlinux's build-id to no longer match the vmlinuz shipped with the kernel. 
By default, `rpm` sets a series of macros for the arguments it passes to `find-debuginfo.sh`, the script which extracts debug symbols. One of these arguments is `_unique_build_ids` which sets `--build-id-seed`. This causes `find-debuginfo` to recompute the build-ids for binaries. Setting the `rpm` flag `_no_recompute_build_ids` (which sets `-n` for `find-debuginfo`)  is not enough as it conflicts with the build-id-seed and causes an error. This is not …
> Disable recomputing build-ids for kernel debuginfo packages

- SPECS/kernel/CVE-2021-3923.nopatch
- SPECS/kernel/CVE-2023-0179.nopatch
- SPECS/kernel/CVE-2023-0590.nopatch
- SPECS/kernel/CVE-2023-1249.nopatch
- SPECS/kernel/CVE-2023-1252.nopatch
- SPECS/kernel/CVE-2023-1838.nopatch
- SPECS/kernel/CVE-2023-30456.nopatch
---
Nopatch CVE-2021-3923, CVE-2023-0179, CVE-2023-0590, CVE-2023-1249, CVE-2023-1252, CVE-2023-1838, CVE-2023-30456
- Nopatch CVE-2021-3923, CVE-2023-0179, CVE-2023-0590, CVE-2023-1249, CVE-2023-1252, CVE-2023-1838, CVE-2023-30456
**NO**
-https://nvd.nist.gov/vuln/detail/CVE-2021-3923
-https://nvd.nist.gov/vuln/detail/CVE-2023-0179
-https://nvd.nist.gov/vuln/detail/CVE-2023-0590
-https://nvd.nist.gov/vuln/detail/CVE-2023-1249
-https://nvd.nist.gov/vuln/detail/CVE-2023-1252
-https://nvd.nist.gov/vuln/detail/CVE-2023-1838
-https://nvd.nist.gov/vuln/detail/CVE-2023-30456
> Nopatch kernel for CVE-2021-3923, CVE-2023-0179, CVE-2023-0590, CVE-2023-1249, CVE-2023-1252, CVE-2023-1838, CVE-2023-30456

- SPECS/etcd/CVE-2021-28235.patch
- SPECS/etcd/etcd-3.5.0.spec
- SPECS/etcd/etcd-3.5.1.spec
- SPECS/etcd/etcd-3.5.3.spec
- SPECS/etcd/etcd-3.5.4.spec
- SPECS/etcd/etcd-3.5.5.spec
- SPECS/etcd/etcd-3.5.6.spec
---
Patch CVE-2021-28235 for etcd packages
- Patch CVE-2021-28235
**NO**
[- https://nvd.nist.gov/vuln/detail/CVE-2021-28235](https://nvd.nist.gov/vuln/detail/CVE-2021-28235)
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=346766&view=results
**Set the variable `_default_patch_fuzz` to 1**. So that single patch can be applied to all the versions and the patch didn't require any modification from upstream.
> Patch CVE-2021-28235 for etcd packages

- SPECS/ccache/ccache.spec
---
Update ccache to use system zlib to address CVE-2018-25032
- CVE-2018-25032
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2018-25032
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=347049&view=results
> Updated SPEC to not include bundled zlib to fix CVE-2018-25032

- SPECS-EXTENDED/podman/CVE-2022-2989.patch
- SPECS-EXTENDED/podman/podman.spec
---
This patches CVE-2022-2989 in podman.
- Added a patch file to fix CVE-2022-2989 for podman.
- Updated changelog and release version.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2989
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=348096&view=results and https://dev.azure.com/mariner-org/mariner/_build/results?buildId=348097&view=results 
Note: the pipeline fails due to an issue unrelated to the changes made to podman. The podman package builds successfully. Here is the failure shown even when building podman in the 2.0 branch: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=347701&view=logs&j=ca395085-040a-526b-2ce8-bdc …
> Patch CVE-2022-2989 in podman

- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The toolchain scripts download the msopenjdk RPM package from packages.microsoft.com, since this is built by another team. I've updated the scripts to download the latest available version: `msopenjdk-11-11.0.18-1`
- Change toolchain manifests to reference latest msopendjk-11 version
- Change toolchain build script to pull latest msopenjdk
**YES**
- Delta pipeline build: 347306
- Full pipeline build: 347341
> toolchain: update to use msopenjdk-11.0.18-1

- toolkit/imageconfigs/marketplace-gen2.json
---
Increase amd64 2.0 market place image EFI partition size from 2MB to 64MB to accommodate space for Kata packages during the new Kata image AgentBaker curation flow.
- Increased amd64 2.0 market place image EFI partition size from 2MB to 64MB.
**NO**
- Manually tested image by creating a VM that has increased EFI partition. After installing all Kata packages, the EFI partition has 35MB of content.
- Existing Kata release image has been shipping with 64MB EFI partition.
> Increase amd64 market place image EFI boot partition size

- toolkit/imageconfigs/marketplace-gen2-aarch64.json
---
Increase aarch64 2.0 market place image EFI partition size from 2MB to 64MB to accommodate space for Kata packages during the new Kata image AgentBaker curation flow.
- Increased aarch64 2.0 market place image EFI partition size from 2MB to 64MB.
**NO**
- Manually tested image by creating a VM that has increased EFI partition. After installing all Kata packages, the EFI partition has 35MB of content.
- Existing Kata release image has been shipping with 64MB EFI partition.
> Increase aarch64 EFI boot partition size

- SPECS/kernel/CVE-2022-4095.nopatch
- SPECS/kernel/CVE-2022-4379.nopatch
- SPECS/kernel/CVE-2023-1855.nopatch
- SPECS/kernel/CVE-2023-1989.nopatch
- SPECS/kernel/CVE-2023-1990.nopatch
- SPECS/kernel/CVE-2023-25012.nopatch
---
Nopatch Kernel for CVE-2022-4095, CVE-2022-4379, CVE-2023-1855, CVE-2023-1989, CVE-2023-1990, CVE-2023-25012
-Nopatch Kernel for CVE-2022-4095, CVE-2022-4379, CVE-2023-1855, CVE-2023-1989, CVE-2023-1990, CVE-2023-25012
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-4095
- https://nvd.nist.gov/vuln/detail/CVE-2022-4379
- https://nvd.nist.gov/vuln/detail/CVE-2023-1855
- https://nvd.nist.gov/vuln/detail/CVE-2023-1989
- https://nvd.nist.gov/vuln/detail/CVE-2023-1990
- https://nvd.nist.gov/vuln/detail/CVE-2023-25012
> Nopatch Kernel for CVE-2022-4095, CVE-2022-4379, CVE-2023-1855, CVE-2023-1989, CVE-2023-1990, CVE-2023-25012

- SPECS/git/git.signatures.json
- SPECS/git/git.spec
- cgmanifest.json
---
Fixes CVE-2023-25652 and CVE-2023-29007
Disregards Windows-specific vulnerabilities: [CVE-2023-25815](https://github.com/git-for-windows/git/security/advisories/GHSA-9w66-8mq8-5vm8), [CVE-2023-29011](https://github.com/git-for-windows/git/security/advisories/GHSA-g4fv-xjqw-q7jm), and [CVE-2023-29012](https://github.com/git-for-windows/git/security/advisories/GHSA-gq5x-v87v-8f7g)
- Fixes CVE-2023-25652
- Fixes CVE-2023-29007
**NO**
- [Github Blogpost](https://github.blog/2023-04-25-git-security-vulnerabilities-announced-4/)
- [Additional Link](https://lwn.net/ml/git/xmqqa5yv3n93.fsf@gitster.g/)
- …
> fix: upgrade git to 2.33.8 to address CVE-2023-25652 and CVE-2023-29007

- SPECS/perl-WWW-Curl/perl-WWW-Curl.spec
---
`perl-WWW-Curl` tests are failing due to missing check-time dependencies, so let's add them!
- `perl-WWW-Curl`: Fix package test by adding check-time requirement on perl(Test::More), perl(File::Temp)
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=350979&view=results), check section now passes
> Fix perl-WWW-Curl tests by adding check-time requirements

- SPECS-SIGNED/kernel-mstflint-signed/kernel-mstflint-signed.spec
---
When the kernel-mstflint-signed.spec is built, the mstflint_access.ko kernel module signature is being stripped. Set `__os_install_post_leave_signatures` macro to avoid this. The macro was added in #3954 
- Change kernel-mstflint-signed.spec to use macro __os_install_post_leave_signatures
- remove unnecessary `/` characters from the %files section
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=350815&view=results
> mstflint: fix signature issue

- SPECS/tidy/CVE-2021-33391.patch
- SPECS/tidy/tidy.spec
- cgmanifest.json
---
This adds a bespoke backport patch to fix the Critical [CVE-2021-33391](https://nvd.nist.gov/vuln/detail/CVE-2021-33391). This patch was created because the two PRs that originally introduce this fix to the upstream, do not cleanly apply to the currently latest stable version of the upstream (v5.8.0). The two PRs mentioned are ([PR-984](https://github.com/htacg/tidy-html5/pull/984), [PR-981](https://github.com/htacg/tidy-html5/pull/981/files)). PR-984 fixes the vulnerability, while parts of PR-981 (namely the changes to lexer.h and lexer.c) are included to support the new Stack structure utilized in the fix.
The fix was tested using the repro provided in the NIST report ([repro …
> Fix: backport patch for CVE-2021-33391 for tidy

- SPECS/fluent-bit/CVE-2021-46878.patch
- SPECS/fluent-bit/CVE-2021-46879.patch
- SPECS/fluent-bit/fluent-bit.spec
---
Add patches for CVE-2021-46878 and CVE-2021-46879
- Add patch files
- Update spec file
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-46878
- https://nvd.nist.gov/vuln/detail/CVE-2021-46879
[AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=353793)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=353796)
> Patch fluent-bit for CVE-2021-46878 and CVE-2021-46879

- SPECS/redis/redis.signatures.json
- SPECS/redis/redis.spec
- cgmanifest.json
---
Upgrade to version 6.2.12 to fix CVE-2023-28856
- upgrade to 6.2.12
- update cgmanifest
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-28856
[AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355108)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355109)
> Upgrade redis to 6.2.12 to fix CVE-2023-28856

- SPECS/nodejs/nodejs.spec
- SPECS/nodejs/nodejs18.spec
---
The Nodejs packages take a long time to build - up to 6 hours for x86_64 when part of full builds. I've changed them to build with ninja, which is much quicker.
Buddy build of just nodejs 16 with make: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355493&view=results
1 hour 21 min
Budd build of just nodejs 16 with ninja: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355496&view=results
37 min
- Change nodejs to build with ninja
- Change nodejs18 to build with ninja
**NO**
X64 buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355936&view=results
ARM64 buddy build: …
> nodejs: use ninja to speed up build

- toolkit/tools/internal/buildpipeline/buildpipeline.go
---
When removing the contents of worker chroots before they are provisioned, our toolkit attempts to delete the `/toolchainrpms` folder within the chroot. In our docker-based builds, this folder is populated as a mount that persists between chroot folder usages. Attempting to delete `/toolchainrpms` in the chroot creates warnings like the following:
```
WARN[0000] Removing files in chroot /temp/DockerStage/docker-chroot-10 failed: unlinkat /temp/DockerStage/docker-chroot-10/toolchainrpms: device or resource busy 
```
This doesn't break anything, and this folder isn't even used for 1.0 builds, but it does pollute the logs with a harmless warning.
So, let's not try to delete that …
> Add toolchainrpms to protected directory list for docker-based builds

- SPECS/mariner-rpm-macros/macros.python-srpm
- SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json
- SPECS/mariner-rpm-macros/mariner-rpm-macros.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
So this is controversial, however, it's kinda annoying when running tools like rpmlint, etc, which expand out __python to a non existing interpreter. With Mariner2.0 only shipping python3.0 I feel that it is time to point __python to the python3 interpreter. In addition, other standard python macro paths, already point to the respective interpreter paths that exist on the system today
```
$ rpm  --eval '%python_version'
3.9
$ rpm --eval '%python_sitelib'
/usr/lib/python3.9/site-packages
```
After making the change
```
$ rpm --eval %{__python}
/usr/bin/python3
```
- Update the macros file to point to the installed python interpreter
**NO**
- Added the macro to the file
- ran rpm …
> Update __Python macro to point to existing interpreter

- SPECS/libtiff/CVE-2023-0795.patch
- SPECS/libtiff/CVE-2023-0796.nopatch
- SPECS/libtiff/CVE-2023-0797.nopatch
- SPECS/libtiff/CVE-2023-0798.nopatch
- SPECS/libtiff/CVE-2023-0799.nopatch
- SPECS/libtiff/libtiff.spec
---
- CVE-2023-0795 is still affecting libtiff  version 4.5.0
- The patch [linked ](https://gitlab.com/libtiff/libtiff/-/commit/69818e2f2d246e6631ac2a2da692c3706b849c38)in NIST was made after 4.5.0 was tagged in the libtiff gitlab repo
- The patch still needs to be applied to 4.5.0
- CVE-2023-0795.patch consists of the following changes (in order):
- https://gitlab.com/libtiff/libtiff/-/commit/9c22495e5eeeae9e00a1596720c969656bb8d678
- https://gitlab.com/libtiff/libtiff/-/commit/688012dca2c39033aa2dc7bcea9796787cfd1b44
- https://gitlab.com/libtiff/libtiff/-/commit/69818e2f2d246e6631ac2a2da692c3706b849c38 (This is the patch that NIST …
> Add patch for CVE-2023-0795 in libtiff

- SPECS/libtiff/CVE-2023-0800.nopatch
- SPECS/libtiff/CVE-2023-0801.nopatch
- SPECS/libtiff/CVE-2023-0801.patch
- SPECS/libtiff/CVE-2023-0802.nopatch
- SPECS/libtiff/CVE-2023-0803.nopatch
- SPECS/libtiff/CVE-2023-0804.nopatch
- SPECS/libtiff/libtiff.spec
---
Add patch to libtiff for CVE-2023-0801. The patch also fixes CVE-2023-0800 CVE-2023-0802 CVE-2023-0803 CVE-2023-0804
- Add patch for CVE-2023-0801 CVE-2023-0802 CVE-2023-0803 CVE-2023-0804
- Not incrementing release number since the current has not been published
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0800
- https://nvd.nist.gov/vuln/detail/CVE-2023-0801
- https://nvd.nist.gov/vuln/detail/CVE-2023-0802
- https://nvd.nist.gov/vuln/detail/CVE-2023-0803
- https://nvd.nist.gov/vuln/detail/CVE-2023-0804
X64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=362011&view=results
ARM64: …
> libtiff: add patch for CVE-2023-0801

- SPECS/gd/gd.spec
---
The last release bump to rebuild `gd` with new `libtiff` didn't actually take a dependency on the newer version of the library, for some reason. So, we re-do the bump.
- `gd`: Bump release
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=362514&view=results), validated that new RPM depends on `libtiff.so.6()(64bit)`
> Bump gd for libtiff update

- SPECS/rust/CVE-2023-27477.patch
- SPECS/rust/rust.spec
---
Patch `rust` for [CVE-2023-27477](https://nvd.nist.gov/vuln/detail/CVE-2023-27477), which is a vulnerability in `cranelift`, upon which `rust` depends. Tweaked the [cranelift patch](https://github.com/bytecodealliance/wasmtime/commit/5dc2bbccbb363e474d2c9a1b8e38a89a43bbd5d1) to apply to the `rust` vendor sources.
Patch [CVE-2023-27477](https://nvd.nist.gov/vuln/detail/CVE-2023-27477)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-27477
- Locally built and verified patch was applied during the %config step.
- ARM64 Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=359212&view=results
- AMD64 Buddy Build: …
> Fix CVE-2023-27477 by patching cranelift vulnerability that is exposed in rust

- toolkit/imageconfigs/marketplace-gen2-aarch64.json
- toolkit/imageconfigs/marketplace-gen2.json
---
Add rootfs partition name in gen2 market place image to enable kata image's grub.cfg to find mshv-bootloader file.
- Add rootfs partition name in amd64 gen2 market place image 
- Add rootfs partition name in aarch64 gen2 market place image (for future images only)
**NO**
- Manual test done with https://dev.azure.com/mariner-org/mariner/_build/results?buildId=361715&view=results
> Add rootfs partition name in gen2 market place image

- SPECS/python-pbr/python-pbr.spec
- SPECS/python-pbr/test-pin-sphinx.patch
---
`python-pbr` package tests started failing around the time when `sphinx 7.0.0` was release. That release removed sphinx's setuptools integration, which is used by some `python-pbr` tests. So, let's restrict the versions of sphinx that `tox` considers when installing test requirements.
- Add patch to pin version of sphinx used in tests to a known compatible version
- Remove check-time install of packages that should be handled by tox
- Use SPDX license expression in license tag
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=364051), tests now pass!
> Fix python-pbr tests by pinning sphinx version used

- SPECS/ocaml-ppxlib/ocaml-ppxlib.spec
- SPECS/ocaml-ppxlib/test-fix-sexplib0-0.15.0.patch
---
`ocaml-ppxlib` tests are failing due to an incompatibility with `ocaml-sexplib0 >= 0.15.0`. Add the upstream patch to fix the bad test data.
- Add upstream patch to fix tests with ocaml-sexplib0-0.15.0
- Remove %{arm} arch gating on tests (not supported by Mariner)
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=363967&view=results), tests now pass
> Fix ocaml-ppxlib tests failure due to ocaml-sexplib0-0.15.0 changes

- toolkit/resources/manifests/package/macros.override
---
We have been skipping `zstd` tests since May 2020. Back then, we were on version 1.4.4, [which had an issue with `/dev/null` having its ownership modified](https://github.com/facebook/zstd/issues/1904). That issue was [fixed in version 1.4.5](https://github.com/facebook/zstd/commit/d6e0a44576feb3da8858eed8454407f27c20a338). Now that `zstd` is on version 1.5.0, we can start running the tests again.
- Stop excluding `zstd` tests in `macros.override`
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=365035), tests are passing!
> Remove zstd from package test exclusion list

- SPECS/dnf-plugins-core/dnf-plugins-core.spec
---
Tests for `dnf-plugins-core` are failing, since they use the name `nosetests-%{python3_version}` to invoke the test runner. That was the correct entrypoint to use when this package used the now-deprecated `python3-nose` package for testing, but became incorrect when upstream switched to the built-in unittests module to run tests in version 4.0.21. So, let's use the correct test runner here.
- Invoke `dnf-plugins-core` tests using `python3 -m unittests`.
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=365183&view=results), tests pass!
> Fix dnf-plugins-core tests by using unittests runner

- SPECS/bash/bash.spec
- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Refactor how we configure `umask`.
---
CIS recommends setting `umask` to `027` in `/etc/profile` and `/etc/bashrc` to ensure that files created by users are not group- or world-writable. This PR refactors how we configure `umask` to make it easier to change the value in the future. Note that we already set `umask` to `027` but we do it in a way that is not easily discoverable, and the CIS audit script trips on it.
Before this change, `umask` was configured thusly:
1. In `filesystem.spec`, we set `umask` to `027` in `/etc/profile` *after* sourcing everything in `/etc/profile.d`. This means any scripts in `/etc/profile.d` that set `umask` will be overridden.
2. In `bash.spec`, we create a file `/etc/profile.d/umask.sh` that sets `umask`, but to values we don't want. But this is then …
> Remove umask handling from bash.spec and change it in filesystem.spec

- SPECS/numpy/numpy.spec
---
The `numpy` package relies on `hypothesis` as a test dependency.  `hypothesis` 6.72.0 added a deprecation warning for something used in `numpy` tests, which broke testing for that package. So, let's pin `hypothesis` to a version that doesn't break our tests.
- Pin version of hypothesis used in numpy tests to avoid deprecation errors
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=365111&view=results)
> Pin version of hypothesis used in numpy tests to avoid test breakage

- toolkit/resources/assets/isomaker/iso_root_arch-dependent_files/arm64/isolinux/isolinux.cfg
---
x86-specific serial console parameters were added to all grub config files.  This change removes these parameters from the ARM-specific grub config file.  For UEFI ARM platforms, the serial console was already enabled and was not impacted by these parameters.
- Remove x86 console params from the ARM-specific grub config file
NO
- local VM boot from ISO and tested serial with "sudo minicom -D /dev/pts/2" password still displays as **** 
"systemctl status serial-getty@ttyAMA0.service" shows active (running)
also installed from ISO to virtual disk and booted installed OS from disk
> Remove x86 console params from ARM-specific grub config

- SPECS/reaper/CVE-2022-37601.patch
- SPECS/reaper/reaper.spec
loader-utils module is used by multiple other modules which reaper is depending upon. Instead of reusing already downloaded code, npm redownloades the same module at different subtree level of node_modules. So the same CVE has to be fixed in other two places as well.
---
Update CVE-2022-37601.patch to fix multiple occurrences
- Update CVE-2022-37601.patch to fix multiple occurrences
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-37601
- BuddyBuild Pipeline build id: local build with msopenjdk-11-11.0.18-1.x86_64.rpm from build_cache
> Update CVE-2022-37601.patch to fix multiple occurrences

- SPECS/shadow-utils/shadow-utils.spec
- SPECS/util-linux/util-linux.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
A [change from last year](https://github.com/microsoft/CBL-Mariner/pull/3713) changed the mode on some executables to `0755`, as a security lockdown. However, for `passwd`, `mount` and `umount`, the `set-uid` bit should be set so they can elevate as needed. Without it, for example, users can't change their own password. Our security tools for Ubuntu allow these executables as exceptions for the "don't have set-uid" check, but they have a different path in Ubuntu so we accidentally didn't exempt them from this change.
This change sets the mode on those files to `4755`, which adds the `set-uid` back.
- packages: shadow-utils and util-linux
- Changed the file copy `%attr` command to …
> fix: add setuid bit to necessary binaries so regular users can run them

- SPECS/reaper/CVE-2023-28155.patch
- SPECS/reaper/reaper.spec
---
Patch reaper to fix [CVE-2023-28155](https://nvd.nist.gov/vuln/detail/CVE-2023-28155), which is a vulnerability in the `request` npm module, upon which `reaper` depends. This is somewhat complicated by the fact that `request` has been [deprecated](https://github.com/request/request/blob/master/README.md) and is no longer taking updates. The patch is actually adapted from a [pull request](https://github.com/request/request/pull/3444) that was never and will never be merged.
Patch [CVE-2023-28155](https://nvd.nist.gov/vuln/detail/CVE-2023-28155)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-28155
- Built locally and validated in logs and compiled files that the patch was …
> Fix tobiasb/CVE-2023-28155 by patch request module in reaper

- SPECS/nodejs/CVE-2023-28155.patch
- SPECS/nodejs/nodejs.spec
---
Patch nodejs to fix [CVE-2023-28155](https://nvd.nist.gov/vuln/detail/CVE-2023-28155), which is a vulnerability in the `request` npm module, upon which `reaper` depends. This is somewhat complicated by the fact that `request` has been [deprecated](https://github.com/request/request/blob/master/README.md) and is no longer taking updates. The patch is actually adapted from a [pull request](https://github.com/request/request/pull/3444) that was never and will never be merged.
Patch [CVE-2023-28155](https://nvd.nist.gov/vuln/detail/CVE-2023-28155)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-28155
- Built locally and validated in logs and compiled files that the patch was …
> Fix CVE-2023-28155 by patching request module in nodejs

- SPECS/influx-cli/influx-cli.spec
---
Removed `bash-completion` subpackage from `influx-cli` package. It seems like `bash-completion` is already including the `influx` script that we produce in `influx-cli` for `bash-completion` subpackage. This causes file conflict when installing both, but given that they are the same script we do not need the `bash-completion` subpackage for `influx-cli`.
- Removed `bash-completion` subpackage from `influx-cli` pacakge.
**NO**
- Built locally
- Pipeline id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=367167&view=results
> Remove influx-cli-bash-completion subpackage as duplicate and conflict with bash-completion

- toolkit/tools/internal/timestamp/timestamp_test.go
---
- Fix a flaky test due to using duplicate test output file and missing explicit type conversion
- Duplicate test output filename between different test cases in timestamp_test.go led to a specific test case being flaky. Dedupped the filename helps avoid any unexpected behaviour
- Fix type error in assertion statements
- Compare structs instead of pointers
**NO**
- Local test run
> Fix occasional test failure in timestamp test

- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
---
- Removing timestamp code from scheduler.go and and buildworker.go to investigate possible nil pointer exception
**NO**
> Remove timestamp code from scheduler

- SPECS/python-click/python-click.spec
---
The package test for `python-click` fails with `pytest >= 7.3.0` for reasons documented [upstream](https://github.com/pallets/click/issues/2489). So, let's pin `pytest` to a version we know is compatible with `python-click`.
- Pin pytest used in python-click package test to 7.2.2
**NO**
- [ADO#44714945](https://microsoft.visualstudio.com/OS/_workitems/edit/44714945)
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=369014&view=results)
> Install known-good pytest for python-click package test

- SPECS/edk2/CVE-2023-0464.patch
- SPECS/edk2/edk2.spec
---
`edk2` has a bundled copy of `openssl` included with it. Include the back-ported patch for CVE-2023-0464 from the main OpenSSL package to edk2.
Since it is a vendored .tar.gz which is not part of the core source files a two stage approach is needed for patching. The `%autosetup` macro now runs with `-N` to disable patching, and we use `%autopatch -M 999` to apply all patches <= 999. The vendored component patch is number 1000 and is applied manually. 
- Apply openssl CVE-2023-0464 patch to edk2's bundled copy
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0464
- Local builds
-https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372933&view=results
> Resolve CVE-2023-0464 in edk2's bundled openssl

- SPECS/cmake/CVE-2023-28322-lib-unify-the-upload-method-handling.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch vendored curl for CVE-2023-28322
- Add patch file to address CVE-2023-28322
- Update toolchain manifest files
YES
- https://nvd.nist.gov/vuln/detail/CVE-2023-28322
[AMD64 ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373451)
[ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373452)
Full Build
[AMD64 Toolchain 
](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373462) - DONE
[AMD64 BuildRpms 
](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373500) - DONE
[ARM64 Toolchain 
](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373463) - DONE
[ARM64 …
> Patch cmake vendored curl for CVE-2023-28322

- SPECS/strace/strace.spec
- SPECS/strace/testfix-landlock-brackets.patch
---
Fix failing `landlock_create_ruleset-y` test in `strace` by backporting an upstream patch to fix that test with `kernel>=5.15.33.1`. 
- Add upstream patch to fix landlock_create_ruleset-y test
- Modernize calls to make by using macros
- Use SPDX license expression in license tag
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373383&view=results), test suite passes now
> Fix strace tests by adding patch to account for newer kernel

- SPECS-EXTENDED/debootstrap/debootstrap.signatures.json
- SPECS/debootstrap/debootstrap.signatures.json
- SPECS/debootstrap/debootstrap.spec
- cgmanifest.json
---
An internal user needs `debootstrap` to be promoted to the base repo. For good measure, we'll update to the latest upstream version while doing so.
I removed the requirement on `dpkg` (from extended) to speed up the process of getting this promoted- this package functions equivalently by replacing `dpkg` extraction functionality with the `ar` tool from `binutils`.
- Upgrade to latest upstream version and promote to base repo
- Remove requirement on dpkg- ar (from binutils) is sufficient to unpack debs
- Verified license
- Verified license tag uses SPDX expression
**NO**
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372584&view=results)
- Was …
> Upgrade debootstrap to 1.0.128+nmu2 and promote to base repo

- toolkit/tools/grapher/grapher.go
- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/timestamp/timestamp_mgr.go
- toolkit/tools/roast/roast.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
- Make timestamp flag optional for build tools. If the timestamp output path is not specified when running a go tool, timestamp recording will be skipped for that run.
- Make timestamp flag optional for build tools
- Add some logging to inform users when timestamping is disabled 
- Small formatting changes
**NO**
- Local package/image/iso build. Verified that iso installer works and could run until completion.
> timestamp: Make timestamp flag optional for go tools

- toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
- toolkit/scripts/imggen.mk
---
The ISO installer will start on every available console (currently `tty1` and `ttyS0`). For normal install flows this is fine since they will both wait for the user to select the desired installer flow. The unattended installer however will proceed automatically. Since we have two instances they will both attempt to install at the same time generally causing one to fail to partition. Anecdotally this is usually the serial console failing making it look like the install has failed, however the `tty1` installer is actually running successfully in the background. If left alone the image will generally install correctly and restart after a minute or two.
Lets prioritize` ttyS0` as …
> Fix against race condition in unattended install

- toolkit/tools/internal/buildpipeline/buildpipeline.go
- toolkit/tools/pkgworker/pkgworker.go
---
Exclude the `ccache-dir` directory from cleanup. Since this directory persists across builds to accumulate ccache artifacts, there is no need to perform the cleanup.
This should resolve errors like the following seen building multiple packages with USE_CCACHE=y:
```
Unable to remove lib archive file: lstat /ccache-dir/0/stats.alive: no such file or directory"
Unable to remove lib archive file: lstat /ccache-dir/0/stats.lock: no such file or directory
```
- Change CleanupDockerChroot() to skip ccache-dir
- Change removeLibArchivesFromSystem() to skip ccache-dir
**NO**
- Local build
> toolkit: exclude ccache directory from cleanup

- SPECS/cloud-hypervisor/CVE-2023-2650.patch
- SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
Patch CVE-2023-2650 in cloud-hypervisor
**Details**
- Following details show that the [CVE](https://nvd.nist.gov/vuln/detail/CVE-2023-2650) is impacted for 1.0
ssh2 → vendored_openssl → libssh2-sys/vendored-openssl → openssl-sys/vendored → openssl-src
- openssl-src has version 111.17.0+1.1.1m which is affected by the [CVE](https://nvd.nist.gov/vuln/detail/CVE-2023-2650). So this means we have an impact of this CVE in 1.0
- My analysis revealed that the given CVE is fixed in OpenSSL 1.1.1u [(git commit)](https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=9e209944b35cf82368071f160a744b6178f9b098)
- So we need to make sure …
> Patch CVE-2023-2650 in cloud-hypervisor

- toolkit/Makefile
- toolkit/docs/building/building.md
- toolkit/scripts/incremental_building.mk
- toolkit/scripts/pkggen.mk
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/scheduler/buildagents/chrootagent.go
- toolkit/tools/scheduler/buildagents/definition.go
- toolkit/tools/scheduler/scheduler.go
---
Add MAX_CPU flag to limit number of CPUS used for package building. When set, this value is used to set the `%_smp_ncpus_max` in each package build chroot. This value sets an upper limit on CPUs to use for all packages that build with `make %{?_smp_mflags}`.
Our immediate need for this is to prevent OOM errors on ARM64 machines, which are typically 32 core, and regularly run out of memory during full package builds.
- Add MAX_CPU option to toolkit
- Update documentation
**NO**
- Local build test - setting MAX_CPU to 3:
- -  time sudo make build-packages SRPM_PACK_LIST="tree" REBUILD_TOOLS=y REFRESH_WORKER_CHROOT=n USE_CCACHE=y …
> Toolkit: Add MAX_CPU flag to limit number of CPUS used for package building

- SPECS/qemu/CVE-2021-3750.patch
- SPECS/qemu/qemu.spec
---
Added [patch](https://gitlab.com/qemu-project/qemu/-/commit/a2e1753b8054344f32cf94f31c6399a58794a380) to QEMU for [CVE-2021-3750](https://nvd.nist.gov/vuln/detail/CVE-2021-3750)
- Pulled in [patch](https://gitlab.com/qemu-project/qemu/-/commit/a2e1753b8054344f32cf94f31c6399a58794a380) to QEMU for [CVE-2021-3750](https://nvd.nist.gov/vuln/detail/CVE-2021-3750)
- Modified line numbers in patch to apply to v6.2.0
- Changed `MEMTX_ACCESS_ERROR` usage in patch (only available in QEMU 7.0+) to `MEMTX_ERROR`, and searched source to verify that no code checks for the specific `MEMTX_ACCESS_ERROR` error.
**NO**
- NONE
- https://nvd.nist.gov/vuln/detail/CVE-2021-3750
- …
> Patch QEMU to fix CVE-2021-3750

- .github/workflows/check-kernel-config.yml
- .github/workflows/check_new_kernel_configs.py
- toolkit/scripts/check_new_kernel_configs.py
- toolkit/scripts/check_required_kernel_configs.py
- toolkit/scripts/kernel_sources_analysis.py
- toolkit/scripts/mariner-required-configs.json
---
In an effort to reduce relying on my memory and to ensure that critical customer configs are not modified, add a new PR check which checks if
1. any configs with known required values have been changed to undesired values/removed
2. new configs are being added and have not added to the json of required kernel configs
Required configs are currently only set for the "kernel" spec but other kernels can created fields in the json to account for their configs.
For case 1, a failure looks like
```
===============================================================================
== Results for SPECS/kernel/config ==
========================================================================== …
```
> Add workflow to check for required kernel configs

- SPECS/systemd/systemd.spec
---
Enabled audit integration in systemd package. This is needed so that systemd will report any SELinux violations for service control operations (start/stop/etc.) to the audit logs. This will ensure that audits of a system's security can be done accurately. In addition, it greatly helps with debugging SELinux issues.
- Enabled audit integration in systemd package.
NO
1. Built the package locally.
2. Installed the updated package in a test VM.
3. Ran a `systemctl restart` command that I knew would hit an SELinux violation.
4. Ensured that the expected SELinux violation showed up in the audit logs.
> systemd: Enable audit integration.

- toolkit/scripts/toolchain/cgmanifest.json
- toolkit/scripts/toolchain/container/Dockerfile
---
Update the bootstrap toolchain code to use the latest 2.0 Mariner container image (replacing an older 1.0 image)
- Change toolchain bootstrap code to use mcr.microsoft.com/cbl-mariner/base/core:2.0.20230609
- Change cgmanifest to reference new image
- Add `tar` to the container image, since it has been removed from the 2.0 base container
**YES**
- AMD64 toolchain build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=382271&view=results
- ARM64 toolchain build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=382269&view=results
> toolchain: use latest 2.0 Mariner container for bootstrap build

- SPECS/kernel-mshv/kernel-mshv.spec
---
When booting, grub should still be getting its systemd-related parameters from one place: systemd.cfg which is packaged in systemd.rpm. Prevent the kernel-mshv package from stomping over these settings. 
- Remove "net.ifnames=0 plymouth.enable=0 systemd.legacy_systemd_cgroup_controller=yes systemd.unified_cgroup_hierarchy=0" from $kernel_cmdline_mshv
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/45063749/
- Buddy building and installing the resulting rpm artifact to ensure no regressions. 
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=382761&view=results
> Remove duplicate systemd parameters from kernel-mshv cfg

- SPECS/freefont/freefont.spec
- SPECS/graphviz/graphviz.spec
---
This adds freefont to graphviz-gd & fontconfig to freefont to address the issue of converting `dot` files to `png`. Graphviz still puts an error out about not having URW fonts, but that doesn't impact function/performance.
- Added `freefont` to BuildRequires for `graphviz-gd`
- Added `fontconfig` to BuildRequires for `freefont` and run fc-cache after installing fonts
NO
- Pipeline build id: 381379 (Running right now)
> Patching graphviz dot to png error

- SPECS/containerized-data-importer/containerized-data-importer.spec
---
Add nbkdit as a dependency for the importer in containerized-data-importer package. This can be done now that nbdkit has been promoted from SPECS-EXTENDED/ to SPECS/.
- containerized-data-importer: Add nbkdit as a dependency for the importer
**NO**
- Pipeline build id: 385118
> containerized-data-importer: Add nbkdit as a dependency for the importer

- SPECS/core-packages/core-packages.spec
---
Moving `curl` out of `core-packages-base-image` and into `core-packages-container`. Recent TDNF upgrade removed the TDNF -> cURL dependency, which was pulling in cURL even for container builds. After the update the base container image lost cURL and that introduced a regression for our users. Since that's a basic tool for many users, we're moving it.
I'm also doing the same thing for `grep`, which already is part of our container images but was not mentioned explicitly and could have suffered the same fate as `curl`.
- Moved `curl` and `grep` into the `core-packages-container` package.
No.
> Included `curl` and `grep` in all core packages.

- SPECS/dbus/dbus.spec
---
dbus has implemented its own SELinux rules. When dbus blocks an operation based on SELinux, it has logic to log the violation to the security audit logs (as it should). Unfortunatley, this logic is currently incorrectly disabled by a build flag. This changes fixes this problem.
Note: The audit client lib supports and actively encourages clients to not fail when the audit service is not available on the system. So, this does not add a dependency on the audit package.
- Enable dbus audit logs.
NO
Ran a command that was known to trigger dbus SELinux violation (while using an SELinux enable image) and ensured that the correct log showed up in the audit logs.
> Enable dbus audit logs.

- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imagegen/configuration/disk.go
- toolkit/tools/imagegen/configuration/disk_test.go
- toolkit/tools/imagegen/configuration/kernelcommandline.go
- toolkit/tools/imagegen/configuration/kernelcommandline_test.go
- toolkit/tools/imagegen/configuration/packagerepo.go
- toolkit/tools/imagegen/configuration/parse_partition.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/diskutils/verity.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/storage/storage.go
- toolkit/tools/internal/timestamp/timestamp.go
- toolkit/tools/pkg/profile/profile.go
- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
- toolkit/tools/roast/formats/ova.go
- toolkit/tools/specreader/specreader.go
---
Adjusted some of our `fmt.Error*` logs to keep them consistent and align them with the linter's suggestions we kept as a convention.
- Refactored `fmt.Error*` messages by removing periods at the end and making them start with lowercase letters.
No.
- N/A, single character change to a few logs.
> Unified `fmt.Error` formatting with Go's conventions.

- SPECS/bash/bash.spec
- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
Revert pull request #5528, which refactored how we configure `umask` in profile.
---
Change #5528 refactored how `umask` is set during profile load. However, this broke certain customers who had modified/replaced `/etc/profile`. This pull reverts those changes.
- Reverted the actual changes in the bash and filesystem specs.
- Updated versions (rather than reverting versions) and change log.
- Updated package manifests
YES -- both bash and filesystem are in the toolchain.
- Manually upgraded packages in a VM, in both possible orders.
- [BuddyBuild](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=386662&view=results)
- [ToolChain](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=386180&view=results)
> revert: Remove umask handling from bash.spec and change it in filesytem.spec

- SPECS/llvm/llvm.spec
- SPECS/llvm/llvm16.spec
---
Modify the value of LLVM_PARALLEL_COMPILE_JOBS for llvm and llvm16. These packages build with ninja, and we've run into out-of-memory errors when building on 32 core machines. This parameter was previously set to 2, which resolved the memory issues, but resulted in slow builds. This PR modifies the value to `_smp_ncpus_max` if it is set (this can be set with the MAX_CPU parameter; see #5677), and if not, will use `_smp_build_ncpus`. In our ARM64 pipeline builds, this change reduces the package build times from ~120min to ~25min, and I've run three full package builds without hitting the memory errors.
- Change llvm …
> llvm: modify LLVM_PARALLEL_COMPILE_JOBS

- SPECS/perl/CVE-2023-31486.patch
- SPECS/perl/perl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This patches CVE-2023-31486 for perl. This patch changes the default behavior of the embedded HTTP-Tiny package to verify certificates by default and adds support for an environment variable to switch back to pre-patch behavior (don't verify by default). The patch for HTTP-Tiny was created for v0.0.86 and included extra tests and documentation changes. These extras were omitted from this patch. Additionally, a subsequent commit to HTTP-Tiny fixed a defect in the original patch. The relevent portion of that fix is also included here.
- Patches CVE-2023-31486 for perl-5.30.3
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2023-31486
- Pipeline builds: 
- [ARM64 …
> Patch CVE-2023-31486 in perl

- SPECS/cloud-hypervisor/CVE-2023-0465.patch
- SPECS/cloud-hypervisor/CVE-2023-2650.patch
- SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
Patch CVE-2023-2650 and CVE-2023-0465 in cloud-hypervisor
My analysis has reveled that the solution for these CVEs is to have openssl-src crate with the version "111.26.0+1.1.1u". Hence added a patch CVE-2023-2650.patch which takes care of this and all other dependencies.
If we take care of applying this patch in the spec file then cloud-hypervisor build goes smoothly when Network is enabled.. But the offline Buddy Build was failing. 
In the recent versions of Rust, “cargo vendor” option is officially supported which will vendor all crates.io and git dependencies into a specified directory by default "vendor". Making use of this …
> Patch CVE-2023-2650 and CVE-2023-0465 in cloud-hypervisor

- SPECS/kubevirt/Hotplug_detach_grace_period.patch
- SPECS/kubevirt/kubevirt.spec
---
Add patch for kubevirt related to hotplug volume pods being deleted.  Patched code introduces delay so that IO can continue through the time between when a hotplug volume pod gets deleted and when it is recreated.
KubeVirt changes introduce a grace period to allow IO to continue on a hotplug volume when the backing pod is deleted.  If the backing pod is recreated within the grace period (5 seconds), the /dev storage on the virt-launcher pod will not be removed/recreated.  If the backing pod is not recreated within the grace period, existing behavior will continue.
**NO**
- #xxxx
- manual testing by creating kubevirt node, adding hotplug volume, and deleting the backing pod.
> KubeVirt: Add grace period for hotplug detach when hotplug pod is deleted

- SPECS/strace/strace.spec
- SPECS/strace/testfix-landlock-brackets.patch
- SPECS/strace/testfix-netlink-list-memberships.patch
---
Recent `strace` package test runs have been failing on the `sockopt-sol_netlink` test. This test fails due to a kernel commit (backported to our kernel in 5.15.116.1) that changes the expected output for a syscall. The test 
Kernel change: microsoft/CBL-Mariner-Linux-Kernel@7dc379f8856bd334582c35c7fe28952e8bd8fb5d
Upstream bug: strace/strace#257.
Upstream fix: strace/strace@f31c2f4494779e5c5f170ad10539bfc2dfafe967
Fix requires following patch be applied first: strace/strace@3bbfb541b258baec9eba674b5d8dc30007a61542
- Add upstream patch to fix sockopt-sol_netlink test with kernel >= 5.15.116.1
- Modify landlock test patch to properly apply with `git am`
- Package full license texts …
> Fix strace's sockopt-sol_netlink test for kernel >= 5.15.116.1

- toolkit/docs/how_it_works/3_package_building.md
- toolkit/tools/depsearch/depsearch.go
- toolkit/tools/graphPreprocessor/graphPreprocessor.go
- toolkit/tools/graphanalytics/graphanalytics.go
- toolkit/tools/grapher/grapher.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/implicitprovides.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
Filter implicit run nodes before passing to `pkgGraph.CreateCollapsedNode()`. The new delta fetcher will create build nodes that point into the cache (prebuilt nodes). When we parse these prebuilt nodes to see if we can resolve any implicit nodes we match based on `node.RpmPath`. Previously those paths would always point into `out/RPMS`, and cache nodes will never point into that directory. With the new delta nodes some build nodes will now point into the cache. These can now match against remote cache nodes, which are not a valid node to squash implicit provides into.
Filter to only real run nodes and discard cache nodes.
- In `replaceNodesWithProvides()` filter out cach nodes …
> Filter implicit run nodes before passing to collapse.

- SPECS/uclibc-ng/0001-gettimeofday-fix-static-build.patch
- SPECS/uclibc-ng/uclibc-ng.spec
---
The recent bump with uclibc-ng had a bug where the static builds of the library had an issue with gettimeofday.
This caused busybox build to break. Introduce a patch from upstream that fixes this.
- Introduce patch to fix busybox build
**NO**
- https://github.com/microsoft/CBL-Mariner/pull/5792
- NA
- Pipeline build id: [PR-5821](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=391933&view=results)
> uclibc-ng: introduce patch to fix static build

- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- cgmanifest.json
---
Bump nodejs (16) to 16.20.1 to resolve CVE-2022-25881 in http-cache-semantics depended on by npm. 
- bump nodejs to 16.20.1
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-25881
@reviewer please could you run the pipeline to add nodejs16.20.1, https://github.com/nodejs/node/releases/tag/v16.20.1 the  script SPECS/nodejs/generate_source_tarball.sh will need to be run to create a "clean" tar.
> Bump nodejs to 16.20.1

- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
If there are any naming mismatches, or we change the set of sub-packages in a toolchain package, we can get into the state where we try to do an incremental build but end up with ether too many or too few packages relative to the manifest.
For example, say we add the subpackage `foo-devel` to `foo.spec`, but it has not been published yet. The old incremental build would try to download and then check if `foo.rpm` is present. It checks using `foo*` to copy all associated packages into the output folder. So long as the core `foo.rpm` file is present the tools assumed all associated packages must also be present and it would skip rebuilding. When we reach the manifest validation …
> Map the expected RPMs to specs in toolchain

- SPECS/grpc/grpc.spec
---
I've encounted some source code that expects to find gRPCConfig.cmake under /usr/lib/cmake. The grpc upstream package typically provides this, but the Mariner spec was deleting these cmake files for some reason.
Removes the logic to delete the *.cmake files, and packages them up in grpc-devel.
No.
In progress.
> Package cmake modules in grpc-devel

- toolkit/docs/how_it_works/3_package_building.md
- toolkit/tools/depsearch/depsearch.go
- toolkit/tools/graphPreprocessor/graphPreprocessor.go
- toolkit/tools/graphanalytics/graphanalytics.go
- toolkit/tools/grapher/grapher.go
- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/implicitprovides.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
This reverts commit 27f23fe5c0f367431f14757da3ccf31b7c072c46.
---
[1/3]: reverting #5813 to stabilize our nightly builds.
Following reverts:
- #5595,
- #5744.
- Reverted #5813.
No.
- #5813,
- #5595,
- #5744.
- N/A - revert.
> Revert "Filter implicit run nodes before passing to collapse. (#5813)"

- SPECS/kernel/CVE-2023-21102.nopatch
- SPECS/kernel/CVE-2023-32250.nopatch
- SPECS/kernel/CVE-2023-32254.nopatch
---
- Add nopatch for CVE-2023-21102, CVE-2023-32250, CVE-2023-32254
- https://nvd.nist.gov/vuln/detail/CVE-2023-21102
- https://nvd.nist.gov/vuln/detail/CVE-2023-32250
- https://nvd.nist.gov/vuln/detail/CVE-2023-32254
> Nopatch kernel for CVE-2023-21102, CVE-2023-32250, CVE-2023-32254

- toolkit/tools/scheduler/scheduler.go
---
Currently we fail to link `font(fontawesome)` to its associated delta node. The issue is that a delta node will point into the cache, but a newly build node will instead point into `out/RPMS`. The halding for linking an implicit node expects an exact match for the rpm path. Fix the delta path for nodes first, before trying to link implicit nodes. Since we won't have fixed the implict nodes yet, we will also need to allow the delta path update code to skip over implicit nodes (since they will be unexpectedly pointing into the cache rather than `out/RPMS`).
This command should now work: `sudo make build-packages CONFIG_FILE="" …
> Update delta paths prior to implicit handling

- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/tools.mk
---
We've been having build issues depending on the configuration of the host we've been building on. Since [`rpmbuild` sets `umask` to 022 by default in the `%prep` section](http://ftp.rpm.org/max-rpm/ch-rpm-b-command.html#S2-RPM-B-COMMAND-BP-OPTION), it seems that the host's extended ACLs are the source of issue, which manifested in the following way:
```
(...)
WARN[0067] Installing:                                  
WARN[0067] systemd-rpm-macros noarch       250.3-17.cm2     local-repo     6.01k    22.85k 
WARN[0067]                                              
WARN[0067] Total installed size:   6.01k                
WARN[0067] Total download size:  22.85k …
```
> Disabled extended ACLs for the `build` directory.

- .pipelines/prchecks/PackageBuildPRCheck.yml
---
Fixed 'ob_artifactBaseName' for RPM builds inside `PackageBuildPRCheck.yml`.
- Replaced `$(System.JobDisplayName)` with `${{ packageBuildJob.name }}`.
No.
- [Test pipeline build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=399578&view=results).
> Fixed `ob_artifactBaseName` for RPM builds inside `PackageBuildPRCheck.yml`.

- SPECS/initramfs/initramfs.spec
---
In order to align our kernel-mshv boot path with Mariner, stop treating the kernel-mshv initrd differently and leave it in /boot. 
- Instead of putting *mshv* initrds in /boot/efi (required for old linuxloader), leave it in boot. Conditionally copy it to /boot/efi to maintain compatibility with old loader. 
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/45235152
> Tweak behavior of kernel-mshv initrd; let it remain in /boot.

- SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
- SPECS/kernel-hci/0028-net-mlx5-Bridge-use-debug-not-warn-if-entry-not-found.patch
- SPECS/kernel-hci/kernel-hci.spec
---
Prevents a debug message in net/mlx5 driver from flooding the log by switching it to warn.
- Add 0028-net-mlx5-Bridge-use-debug-not-warn-if-entry-not-found.patch to kernel-hci
**NO**
- Official pipeline build id: 398165
- HCI pipeline build id: 399404
> kernel-hci: Add net/mlx5 patch (27) switching warn message to debug

- SPECS/kernel/CVE-2023-38426.nopatch
- SPECS/kernel/CVE-2023-38427.nopatch
- SPECS/kernel/CVE-2023-38428.nopatch
- SPECS/kernel/CVE-2023-38429.nopatch
- SPECS/kernel/CVE-2023-38430.nopatch
- SPECS/kernel/CVE-2023-38431.nopatch
- SPECS/kernel/CVE-2023-38432.nopatch
---
CBL-Mariner does not enable ksmbd (CONFIG_SMB_SERVER not present) and therefore the following CVEs do not apply. 
Address CVE-2023-38426, CVE-2023-38427, CVE-2023-38428, CVE-2023-38429, CVE-2023-38430, CVE-2023-38431, CVE-2023-38432
- Address CVE-2023-38426, CVE-2023-38427, CVE-2023-38428, CVE-2023-38429, CVE-2023-38430, CVE-2023-38431, CVE-2023-38432
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-38426
- https://nvd.nist.gov/vuln/detail/CVE-2023-38427
- https://nvd.nist.gov/vuln/detail/CVE-2023-38428
- https://nvd.nist.gov/vuln/detail/CVE-2023-38429
- https://nvd.nist.gov/vuln/detail/CVE-2023-38430
- https://nvd.nist.gov/vuln/detail/CVE-2023-38431
- …
> Nopatch kernel for CVE-2023-38426, CVE-2023-38427, CVE-2023-38428, CVE-2023-38429, CVE-2023-38430, CVE-2023-38431, CVE-2023-38432

- SPECS/iperf3/iperf3.signatures.json
- SPECS/iperf3/iperf3.spec
- cgmanifest.json
---
Fixing the CVE-2023-38403 in `iperf3`.
- Updated `iperf3` to version 3.14.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-38403.
- Local package build and test.
> Updated `iperf3` to 3.14 to fix CVE-2023-38403.

- SPECS/keras/keras.spec
- SPECS/python-tensorboard/python-tensorboard.spec
- SPECS/tensorflow/tensorflow.spec
---
=> tensorflow, keras and python3-tensorboard could be build with our latest Bazel. i.e 5.3.2. 
- Change: 
Remove tightly coupled dependency on a particular bazel version while building bazel packages by removing the .bazelversion file as well as removing the version provided in the buildRequires. 
**YES/NO**
NO
- Fixes #45595561
- Pipeline build id (AMD64) :  [401515](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=401515&view=results)
- Pipeline build id (ARM64) : [401275](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=401275&view=results)
> Fix Bug 45595561: Remove .bazelversion file

- SPECS/reaper/CVE-2018-11694.patch
- SPECS/reaper/reaper.spec
---
Add patch for CVE-2018-11694
- Add patch for CVE-2018-11694
- Update spec file
NO
- https://nvd.nist.gov/vuln/detail/CVE-2018-11694
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=402680
> Patch reaper for CVE-2018-11694 in libsass module

- SPECS/python-certifi/certifi-2022.12.07-use-system-cert.patch
- SPECS/python-certifi/python-certifi.signatures.json
- SPECS/python-certifi/python-certifi.spec
- cgmanifest.json
---
Fixing CVE-2023-37920. The CVE is about removing a CA from the bundled list of trusted anchors inside `python-certifi`. Since we don't want to use any other bundles except for the ones provided by `ca-certificates`, the change is about switching `python-certifi` to use the system certificates instead of its own bundle.
- Switched `python-certifi` to use the system trusted CAs instead of its own bundle.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-37920
- Local package build and test.
> Made `python-certifi` stop using its bundled certificates to fix CVE-2023-37920.

- toolkit/docs/formats/imageconfig.md
- toolkit/tools/imagegen/configuration/configuration.go
- toolkit/tools/imagegen/configuration/configuration_test.go
- toolkit/tools/imagegen/configuration/fileconfig.go
- toolkit/tools/imagegen/configuration/fileconfig_test.go
- toolkit/tools/imagegen/configuration/filepermissions.go
- toolkit/tools/imagegen/configuration/filepermissions_test.go
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/configuration/systemconfig_test.go
- toolkit/tools/imagegen/configuration/testdata/test_configuration.json
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imagegen/installutils/installutils_test.go
- toolkit/tools/imagegen/installutils/testdata/a.txt
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/ptrutils/ptrutils.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/isomaker/maker.go
---
This change extends the `AdditionalFiles` field of the image system config to support copying to multiple destination files and changing the file permissions of the destination files.
- Change `AdditionalFiles` to an array of `FileConfig` structs and add support for changing the destination file permissions.
- Add a custom [un]marshaler for `AdditionalFiles` so that the existing schema is still supported.
- Extend and add new image configuration tests to cover the new options for `AdditionalFiles`.
- Add a test for `installutils` to verify file copying behavior during image builds.
NO
- All existing toolkit tests pass.
- New toolkits tests were added to test the new features.
- …
> Extend `AdditionalFiles` config

- toolkit/tools/imagegen/diskutils/diskutils.go
---
Use a sparse raw image file for the intermediate build image file. This will allow images to be built that have a larger capacity than the free disk space available on the build machine (so long as the committed size is within the free disk space). This will also speed up the build a little bit since it will no longer be pointlessly writing zeros to disk.
- Use sparse image file in imager utility.
NO
- Manually run image builds on dev box.
> Use sparse raw image file

- toolkit/scripts/tools.mk
---
Add a hard error condition if you try to rebuild the tools with a version of go that is too old. The go compiler itself will report this error, but it is easy to lose that message in the output. Now we will immediately stop parsing the makefile if the version is wrong. We only check if `REBUILD_TOOLS=y` is set to 'y'.
- Add check for go compiler version if `REBUILD_TOOLS=y`
**NO**
- Pipeline build id: local test
- Needs full pipeline run
> Add hard check on go version

- toolkit/docs/how_it_works/3_package_building.md
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/pkgjson/pkgjson.go
- toolkit/tools/internal/pkgjson/pkgjson_test.go
- toolkit/tools/specreader/specreader.go
---
We've been parsing package strings with version like `gcc >= 1.2.3` with different logic inside `specreader.go` and `pkgjson.go`. The version from `specreader.go` failed to properly handle cases with missing spaces like `gcc>=1.2.3`. Since these instances are not consider erroneous by `rpmbuild` and we handle them correctly with the `PackagesListEntryToPackageVer` function from `pkgjson.go`, I've made `specreader.go` call into `PackagesListEntryToPackageVer` as well.
The unhandled `gcc>=1.2.3` cases in `specreader.go` made us create `PkgVer` structs with their `Name` fields set to `gcc>=1.2.3` and so far we only lucked out that this didn't cause any issues, as only one spec seems …
> Clarified handling of rich dependencies and unified package string parsing.

- SPECS/javapackages-bootstrap/CVE-2023-37460.patch
- SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
---
Fix CVE-2023-37460 by patching plexus-archiver. Patch has been adapted from https://github.com/codehaus-plexus/plexus-archiver/commit/54759839fbdf85caf8442076f001d5fd64e0dcb2 (Omitted parts of the patch that update testing since it causes compile issues. E.g a part of the patch adds a new junit test, but they didn't switch to junit until 4.5.0, currently using 4.2.2)
- javapackages-bootstrap
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-37460
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=407028&view=results: using new unified pipeline buddy builds. Failed `build-arm64-check` but passed `build-arm64` …
> Fix CVE-2023-37460 by patching plexus-archiver

- SPECS/javapackages-bootstrap/CVE-2023-37460.patch
- SPECS/javapackages-bootstrap/javapackages-bootstrap.spec
---
Fix CVE-2023-37460 by patching plexus-archiver. Patch has been adapted from https://github.com/codehaus-plexus/plexus-archiver/commit/54759839fbdf85caf8442076f001d5fd64e0dcb2 (Omitted parts of the patch that update testing since it causes compile issues. E.g a part of the patch adds a new junit test, but they didn't switch to junit until 4.5.0, currently using 4.2.2)
- javapackages-bootstrap
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-37460
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=407028&view=results: using new unified pipeline buddy builds. Failed `build-arm64-check` but passed `build-arm64` …
> Fix CVE-2023-36617 by patching plexus-archiver

- SPECS/ruby/CVE-2023-36617.patch
- SPECS/ruby/ruby.spec
---
Patch ruby-uri version and fix CVE-2023-36617 (vulnerability not present in rub uri 12.2) https://github.com/hsbt/ruby/commit/ab5421547c5546603c2383085005272ba7754fea
- CVE-2023-36617
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-36617
- Unified build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=408103&view=results
> Update ruby default uri to 0.12.2 and bundled uri to 0.10.3 and fix CVE-2023-36617

- SPECS/reaper/reaper.signatures.json
- SPECS/reaper/reaper.spec
---
Fix CVE-2023-0286 by removing openssl from reaper
- Remove openssl from local-n bundle
- Make openssl as BR for reaper
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0286
- [Pipeline build id: 409362](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=409362&view=results)
> Fix CVE-2023-0286 by removing bundled openssl from reaper and adding openssl-devel as a BR

- SPECS/golang/golang.signatures.json
- SPECS/golang/golang.spec
- SPECS/golang/permit-requests-with-invalid-header.patch
- SPECS/moby-cli/moby-cli.signatures.json
- SPECS/moby-cli/moby-cli.spec
- SPECS/moby-containerd/moby-containerd.signatures.json
- SPECS/moby-containerd/moby-containerd.spec
- SPECS/moby-engine/moby-engine.signatures.json
- SPECS/moby-engine/moby-engine.spec
- SPECS/moby-runc/moby-runc.signatures.json
- SPECS/moby-runc/moby-runc.spec
- cgmanifest.json
---
This touches moby-* and golang:
- Golang bumped to 1.20.7. Note that for go versions >= 1.20, the minimum compiler required is 1.17.
First the go1.4 bootstrap compiler is built.
The result of 1.4 compiler is used to build a 1.19.12 compiler.
The 1.19.12 compiler is used to build the actual 1.20.7 compiler.
Since go builds fairly quickly, the overhead of this is ~2-3 minutes on a reasonable machine.
- moby-engine & moby-cli -> bumped to 20.10.25 (which contain the fix `http: invalid host header`.
If we build moby-enginne & moby-cli with 1.19.12 compiler, it still does not work.
- moby-runc bumped to 1.1.9
- moby-containerd bumped to …
> golang: bump golang 1.19.12 -> 1.20.7

- toolkit/tools/internal/retry/retry.go
- toolkit/tools/internal/retry/retry_test.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
During testing of the new parallel build PR gates, it was noticed that the build agents often dropped connections. We can run most of the packing step highly parallelized, but limiting the number of concurrent network operations significantly improves reliability.
Also adding a configurable exponent to the retry backoff logic allows us to be more accommodating by significantly slowing down network requests when things start to go wrong.
- Add retry.RunWithExpBackoff() which has a configurable backoff exponent (rather than the implicit `1.0` in `Run()`).
- Add a semaphore to limit concurrent network traffic in the packer
**NO**
- Local builds
> Add better backoff, semaphore to packer

- SPECS/bpftrace/bpftrace.spec
---
Currently the bpftrace-0.11.4-1 package has an implicit strict dependency on an older binutils-2.32-5.
This is causing bpftrace installs to pull in the older binutils-2.32-5 instead of the latest binutils-2.36.1-3.
By revision bumping bpftrace we will get a new package that depends on the latest binutils.
- Revision bump bpftrace to depend on the latest binutils.
**NO**
- Verified during dnf install that new package depends on binutils-2.36.1-3
- Verified that bpftrace works on an AKS node after upgrading to this new release
> Revision bump bpftrace to rebuild with binutils 2.36.1

- SPECS/guava/CVE-2020-8908.patch
- SPECS/guava/guava.spec
---
Address CVE-2020-8908 for guava
- Add patch for CVE-2020-8908
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-8908
- amd64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=412302&view=results
- arm64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=412316&view=results
> Add patch to guava for CVE-2020-8908

- SPECS/etcd/CVE-2023-32082-v3.5.0.patch
- SPECS/etcd/CVE-2023-32082-v3.5.3.patch
- SPECS/etcd/CVE-2023-32082.patch
- SPECS/etcd/etcd-3.5.0.spec
- SPECS/etcd/etcd-3.5.1.spec
- SPECS/etcd/etcd-3.5.3.spec
- SPECS/etcd/etcd-3.5.4.spec
- SPECS/etcd/etcd-3.5.5.spec
- SPECS/etcd/etcd-3.5.6.spec
---
Patch etcd and bump fuzzing for CVE-2023-32082
Versions 3.5.0 and 3.5.1 use a backport of the patch upstream (CVE-2023-32082-v3.5.0.patch)
Versions 3.5.3 and 3.5.4 use a backport of the patch upstream (CVE-2023-32082-v3.5.3.patch)
Versions 3.5.5 and 3.5.6 use the original patch upstream (CVE-2023-32082.patch)
- Patch etcd 
- Bump default fuzzing value to 2
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-32082
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=412407&view=results
> Patch etcd and bump fuzzing for CVE-2023-32082

- toolkit/tools/grapher/grapher.go
---
We skip creating new nodes in case a duplicate is found. This usually happens due to `Provides` in specs where each provides the same capability. In such cases we skip creating a new pair of run and build nodes. If a test node was not created for the first spec but the one creating the duplicate does have a test, then the test node ended up being attached to the wrong build node. In such cases we're going to skip creating the test node entirely. This should not prevent us from testing the packages themselves, as a test node for non-Provides package will still be created and attached to the correct build node.
- Skipped test node creation for duplicates.
No.
- Local tests.
> Skipping test node creation for duplicate nodes.

- toolkit/tools/scheduler/schedulerutils/buildlist.go
---
This is a fix to PR#5863.
ISO build fails with above PR because scheduler wrongly adds packages from image config to test list along with build list.
This is causing the ISO build to fail since there are not test nodes in the lookup Table.
Test list is getting added even though run_check is not enabled.
To summarize, scheduler wrongly considers packages in imageconfig that are to be built as packages to run tests.
Fix ensures local packages from imageconfig are considered as packages to be built but not be considered as packages to be tesed (since run_check is not enabled when building iso)
- Passing a flag isBuildList from …
> Fixed image build issues with packages lacking tests.

- toolkit/scripts/imggen.mk
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/internal/tdnf/tdnf.go
---
Generate a new output file `image_pkg_manifest.json` when creating images. This contains all packages used to compose the image, as well as version, architecture and distribution information for each package.
The new file will be generated in the following location:
`build/imagegen/$(config_name)/image_pkg_manifest.json`
The current use case for this file is to server as an input to assist in generating an SBOM for each image.
- Change image generation to create a `image_pkg_manifest.json` file for each image type
**NO**
- Pipeline build id x64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414169&view=results
- …
> toolkit: generate image_pkg_manifest.json with image builds

- SPECS/qemu/CVE-2022-36648.patch
- SPECS/qemu/qemu.spec
---
CVE-2022-36648 Detail
Description
The hardware emulation in the of_dpa_cmd_add_l2_flood of rocker device model in QEMU, as used in 7.0.0 and earlier, allows remote attackers to crash the host qemu and potentially execute code on the host via execute a malformed program in the guest OS.
Added patch as described by https://lists.nongnu.org/archive/html/qemu-devel/2022-06/msg04469.html (which was referenced by https://nvd.nist.gov/vuln/detail/CVE-2022-36648).
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-36648
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414204&view=results
> CVE-2022-36648: QEMU fix

- .github/workflows/validate-cg-manifest.sh
---
`cgmanifest` checks fail if we do not use `TLSv1_2` protocol for download.
- NA
**NO**
- https://github.com/orgs/community/discussions/65227
- NA
Picked a random failing `cgmanifest` PR; rebased with this fix and raise a draft PR.
- https://github.com/microsoft/CBL-Mariner/pull/6087
> workflows: use curl with TLSv1_2 to fix cgmanifest check

- toolkit/docs/formats/imageconfig.md
- toolkit/resources/assets/grub2/grub.cfg
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imagegen/configuration/kernelcommandline.go
- toolkit/tools/imagegen/configuration/kernelcommandline_test.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
---
This commit introduces a new EnableFIPS configuration option to the
KernelCommandline image schema. EnableFIPS is a boolean option that
controls whether the image tools should configure the system with FIPS
enabled or not.
To enable FIPS on a system, 3 parts must be present:
1. The argument fips=1 must be passed to the kernel via the kernel
commandline during boot. To do this, updates are needed to the grub.cfg
to make sure the command line parameter is passed when the kernel is
loaded into memory.
2. The dracut-fips package must be installed on the system. The
dracut-fips package contains FIPS self-tests which will halt the system
if any FIPS-approved kernel crypto algorithm is …
> Add new EnableFIPS image configuration option

- SPECS/clamav/CVE-2022-48579.patch
- SPECS/clamav/clamav.spec
Patch `clamav` to fix [CVE-2022-48579](https://nvd.nist.gov/vuln/detail/CVE-2022-48579).
Note that this patch did not apply cleanly and required quite a bit of hand-massaging.
---
Patch `clamav` to fix [CVE-2022-48579](https://nvd.nist.gov/vuln/detail/CVE-2022-48579).
Updated `clamav`. See notes in patch file for specifics about the patch apply.
Updated cargo cache: 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-48579
Buddy Builds: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414177&view=results
> fix: CVE-2022-48579 in clamav

- SPECS/hyperv-daemons/CVE-2023-3439.nopatch
- SPECS/kernel/CVE-2023-3439.nopatch
- toolkit/scripts/mariner-required-configs.json
---
Nopatch CVE-2023-3439 as mctp is not enabled in CBL-Mariner 
Update required configs to reflect the need for the fix if mctp is enabled
- Nopatch CVE-2023-3439 as mctp is not enabled in CBL-Mariner
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-3439
> Nopatch kernel and hyperv-daemons for CVE-2023-3439 as mctp is not enabled in CBL-Mariner

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/internal/file/file.go
- toolkit/tools/internal/file/file_test.go
- toolkit/tools/internal/network/network.go
---
When `network.DownloadFile()` it was leaving files on the disk. The pre-cacher tool would create empty `.rpm` files which would confuse the fetcher and scheduler further downstream.
- network.DownloadFile() will now clean up its dst file on error
- Added `file.RemoveFileIfExists()`
- Add file_test.go 
**NO**
- Local test
> Remove dst file on failed network download

- SPECS/cloud-init/cloud-init.spec
---
There is a customer request that asking content of cloud-init-output.log to be available on Azure diagnostics serial log for Mariner VM, same as Ubuntu. In cloud-init.spec file, there is a particular line that makes the StandardOutput logs from cloud-init systemd service only dump to journal but not system console, which causes the content of cloud-init-output.log missing on Azure diagnostics serial log. We need to remove this line to resolve this issue.
- Remove the line that replaces "StandardOutput=journal+console" to "StandardOutput=journal" in cloud-init systemd service: "find systemd -name "cloud*.service*" | xargs sed -i …
> make cloud-init-output.log available to serial console

- SPECS/qt5-qtsvg/qt5-qtsvg.spec
---
Rebuild qt5-qtsvg package to resolve vulnerability to CVE-2023-37369. While the [`CVE-2023-37369.patch`](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/qt5-qtbase/CVE-2023-37369.patch) does not apply to any source code used by qt5-qtsvg, this package compiles against potentially vulnerable code from qt5-qtbase via `BuildRequires: qt5-qtbase-private-devel`. I've bumped the release version of qt5-qtsvg so that it recompiles against the updated qt5-qtbase which contains the CVE fix.
- Change qt5-qtsvg release number
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-37369
- Buddy build: …
> qt5-qtsvg: rebuild with qt5-qtbase fix for CVE-2023-37369

- toolkit/scripts/containerized-build.mk
- toolkit/scripts/containerized-build/create_container_build.sh
---
Honor `$SPECS_DIR` instead of hardcoding the value.
```bash
sudo make containerized-rpmbuild SRPM_PACK_LIST=vim
* Mount points:
/home/mfrw/mariner-org/cve/cve-ext/build/container-build' -> '/usr/src/mariner/BUILD
/home/mfrw/mariner-org/cve/cve-ext/build/container-buildroot' -> '/usr/src/mariner/BUILDROOT
/home/mfrw/mariner-org/cve/cve-ext/out/RPMS' -> '/mnt/RPMS
/home/mfrw/mariner-org/cve/cve-ext/build/containerized-rpmbuild/tmp' -> '/mariner_setup_dir
/home/mfrw/mariner-org/cve/cve-ext/build/INTERMEDIATE_SRPMS' -> '/mnt/INTERMEDIATE_SRPMS …
```
> toolkit: containerized-build: honor $SPECS_DIR instead of hard-coding

- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot_test.go
---
Some packages use uncommon release numbers which include '_'. Generally a release is expected to be a number only, but this is not required. Relax the regex used by the `rpmssnapshot` tool to calculate the version of a `.spec` file.
- Allow `rpmssnapshot` to handle `.spec` files which contain '_' in their release.
- Add basic unit tests to the regex in `rpmssnapshot.go`
**NO**
- Local test via `jq -r '.Repo | sort_by(.Name)' ./out/rpms_snapshot.json > sort.json` to compare results before/after.
> Fix parsing of releases containing '_'

- toolkit/imageconfigs/marketplace-gen1-fips.json
---
This commit adds a new Azure VM Gen1 image with FIPS enabled by default. This image definition is identical to the current marketplace gen1 image definition, except for the following specific changes:
1. Include the fips-packages.json package list before the initramfs package in the overall package list
2. Set KernelCommandLine.EnableFIPS to true, to inform image generation tools to enable FIPS during image creation
3. Set basename for image as "cblmariner-gen1-fips"
**NO**
- #6010 
Local build & penguinator testing
> feat: add Azure Marketplace Gen1 FIPS definition

- toolkit/imageconfigs/marketplace-gen2-fips.json
---
This commit adds a new Azure VM Gen2 image with FIPS enabled by default.
This image definition is identical to the current marketplace gen2 image
definition, except for the following specific changes:
1. Include the fips-packages.json package list before the initramfs
package in the overall package list
2. Set KernelCommandLine.EnableFIPS to true, to inform image generation
tools to enable FIPS during image creation
3. Set basename for image as "cblmariner-gen2-fips"
**NO**
- #6010 
local testing, penguinator testing
> feat: add Azure Marketplace Gen2 FIPS definition

- toolkit/scripts/pkggen.mk
- toolkit/tools/grapher/grapher.go
---
Not to pass toolchainManifest to grapher and clean grapher worker during workplan clean
- Not to pass toolchainManifest to grapher and clean grapher worker during workplan clean
**NO**
- local build
> Not to pass toolchainManifest to grapher and clean grapher worker during workplan clean

- toolkit/scripts/containerized-build.mk
- toolkit/scripts/pkggen.mk
- toolkit/scripts/utils.mk
---
The `setfacl` command was ran every time we used the toolkit, even for cases where it wasn't needed. In some of these scenarios the environment was stripped down and did have (or need) the `acl` package, which cause the toolkit to complain about missing `setfacl`, even though it didn't need it.
- Limited the runs of `setfacl` only to scenarios when we're building packages.
No.
- Local tests.
> Limited running `setfacl` to package builds

- SPECS-EXTENDED/ibus-table/ibus-table.spec
- SPECS-EXTENDED/libpmemobj-cpp/libpmemobj-cpp.spec
---
Two remaining extended packages cause build failures during our ptest runs. Until the cause is found and fixed, I'm disabling their **test-time** `BuildRequires`. The fix will be done in separate PRs.
- Removed test-time `BuildRequires` for `ibus-table` and `libpmemobj-cpp`.
No.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=416729&view=results)
> Mitigating build failures in SPECS-EXTENDED during tests.

- SPECS-EXTENDED/fetchmail/fetchmail.signatures.json
- SPECS-EXTENDED/fetchmail/fetchmail.spec
- cgmanifest.json
---
Upgrade version 6.4.8 -> 6.4.22 to address CVE-2021-39272 & CVE-2021-36386
- fetchmail: drop asc file
- fetchmail: add changelog
- fetchmail: verify license
- fetchmail: lint spec
- fetchmail: swith to %autosetup, %make_build & %make_install
- fetchmail: prefer https instead of http
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-39272
- https://nvd.nist.gov/vuln/detail/CVE-2021-36386
- Pipeline build id: [PR-6158](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417451&view=results)
- Local build
> Upgrade fetchmail 6.4.8 -> 6.4.22 to address CVE-2021-39272 & CVE-2021-36386

- SPECS-EXTENDED/xterm/xterm-defaults.patch
- SPECS-EXTENDED/xterm/xterm-desktop.patch
- SPECS-EXTENDED/xterm/xterm-man-paths.patch
- SPECS-EXTENDED/xterm/xterm.signatures.json
- SPECS-EXTENDED/xterm/xterm.spec
- cgmanifest.json
---
Upgrade version to address CVE-2022-45063 & CVE-2023-40359
- xterm: 372 -> 380 [patch bkport pending]
- xterm: backport patches
- xterm: add changelog
- xterm: cgmannifest: update entry
- xterm: lint spec
- xterm: switch to https instead of http
- xterm: swith to %make_build
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-45063
- https://nvd.nist.gov/vuln/detail/CVE-2023-40359
- Local build w w/o `RUN_CHECK=y`
- Pipeline build id: [PR-6146](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417391&view=results)
> Upgrade xterm 372 -> 380 to address CVE-2022-45063 & CVE-2023-40359

- SPECS-EXTENDED/buildah/CVE-2022-2990.patch
- SPECS-EXTENDED/buildah/buildah.spec
---
CVE-2022-2990 Detail
An incorrect handling of the supplementary groups in the Buildah container engine might lead to the sensitive information disclosure or possible data modification if an attacker has direct access to the affected container where supplementary groups are used to set access permissions and is able to execute a binary code in that container.
- https://nvd.nist.gov/vuln/detail/CVE-2022-2990
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2990
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417914&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=7909073b-e471-53c1-2c44-627e2efc0564
> User/bfjelds/buildah CVE 2022 2990

- .pipelines/templates/PackageBuild.yml
---
Making artifact feeds for pip installations optional. By default package tests analysis shouldn't require the user to have a custom feed and allow them to use the default upstream one instead. It's a configuration I missed in #6141.
- Making `pipArtifactFeeds` parameter optional.
No.
- #6141
- Test fast-track package build.
> Made `PipAuthenticate` artifact feeds optional for package test analysis.

- .pipelines/prchecks/PackageBuildPRCheck.yml
---
Moving the agent definitions to a shared variable group. This way we can update the pools across our pipelines globally instead of keeping them defined per-pipeline.
- Switched to grabbing the agent pool names from the `Agent pools (DEV)` variable group.
No.
- #6026
- PR check for a test PR #6026
> Switched the PR check pipeline to grab agent pools from a shared group.

- SPECS/cmake/CVE-2023-35945.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Modified patch described in NIST page to apply to cmake (using nghttp2 version 1.40.0) by:
* adjusting paths to reflect embedded nature of nghttp2 in cmake
* adjusting line numbers in patch file
* removing test files which are not included in source tar
- https://nvd.nist.gov/vuln/detail/CVE-2023-35945
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-35945
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418301&view=logs&j=21e55549-fa44-57d8-4936-64132e3ceec0
> cmake patch for CVE-2023-35495

- SPECS/nodejs/CVE-2022-25883-v18.patch
- SPECS/nodejs/nodejs.signatures.json
- SPECS/nodejs/nodejs.spec
- SPECS/nodejs/nodejs18.signatures.json
- SPECS/nodejs/nodejs18.spec
- cgmanifest.json
---
Bump nodejs from 16.20.1 to 16.20.2 and nodejs18 from 18.16.0 to 18.17.1 to address CVE-2023-32002 CVE-2023-32006 CVE-2023-32559
- https://nvd.nist.gov/vuln/detail/CVE-2023-32002
- https://nvd.nist.gov/vuln/detail/CVE-2023-32006
- https://nvd.nist.gov/vuln/detail/CVE-2023-32559
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-32002
- https://nvd.nist.gov/vuln/detail/CVE-2023-32006
- https://nvd.nist.gov/vuln/detail/CVE-2023-32559
- [build nodejs and nodejs18](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418417&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=fbeef549-39ab-510c-faa3-78579a516b53)
- [build nodejs, nodejs18, reaper, …
> Address nodejs CVEs 32002 32006 32559

- SPECS-EXTENDED/libtommath/CVE-2023-36328.patch
- SPECS-EXTENDED/libtommath/libtommath.spec
---
Adapt nist linked patch to libtommath 1.1.0 to address CVE-2023-36328
- CVE-2023-36328
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-36328
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418762&view=results
> patch libtommath for CVE-2023-36328

- SPECS-EXTENDED/libmicrohttpd/libmicrohttpd.signatures.json
- SPECS-EXTENDED/libmicrohttpd/libmicrohttpd.spec
- cgmanifest.json
---
Upgrade libmicrohttpd 0.9.71 -> 0.9.76 to address CVE-2023-27371
- Upgrade libmicrohttpd 0.9.71 -> 0.9.76 to address CVE-2023-27371
- libmicrohttpd: lint spec
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-27371
- Pipeline build id: [PR-6161](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417589&view=results)
- Local Build w/ & w/o `RUN_CHECK=y`
> Upgrade libmicrohttpd 0.9.71 -> 0.9.76 to address CVE-2023-27371

- SPECS-EXTENDED/opencryptoki/opencryptoki.signatures.json
- SPECS-EXTENDED/opencryptoki/opencryptoki.spec
- cgmanifest.json
---
Upgrade opencryptoki 3.13.0 -> 3.17.0 to address CVE-2021-3798
- opencryptoki: lint spec
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3798
- Pipeline build id: [PR-6163](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417649&view=results)
- Local build with Dependents: `opencryptoki opendnssec openssl-ibmpkcs11 tpm-tools`
> Upgrade opencryptoki 3.13.0 -> 3.17.0 to address CVE-2021-3798

- SPECS-EXTENDED/flac/flac.signatures.json
- SPECS-EXTENDED/flac/flac.spec
- cgmanifest.json
---
Upgrade flac 1.3.4 -> 1.40 to address CVE-2020-22219
- Lint Spec
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2020-22219
- Pipeline build id: [PR-6146](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417750&view=results)
- Local build w/ & w/o `RUN_CHECK=y` of dependents: `audiofile flac SDL_sound sox vorbis-tools`
> Upgrade flac 1.3.4 -> 1.4.3 to address CVE-2020-22219

- toolkit/scripts/tools.mk
- toolkit/tools/grapher/grapher.go
---
Whenever we found multiple packages providing the same capability (for instance `bundled(gnulib)`), we would only add a run-build(-test) set of nodes for it once. Every other package providing the same capability would generate a warning but not a new node. However, when we later generated graph edges to indicate node dependencies, we would read the dependencies for all the packages providing the duplicate capability and attach them to the original node. This caused some packages to be unnecessarily re-built.
Example: `augeas` and `libguestfs` provide `bundled(gnulib)`. We only add a node for the run and build nodes of the `augeas` version of `bundled(gnulib)`. However, later we …
> Cleaned-up invalid edges from duplicate nodes.

- toolkit/scripts/containerized-build.mk
- toolkit/scripts/containerized-build/create_container_build.sh
---
Add custom build mount
- Give optional argument to specify a directory to create mountpoints for build chroot in the container
- The build/ from container will be mounted at $BUILD_MOUNT/container-build
- The buildroot/ from container will be mounted at $BUILD_MOUNT/container-buildroot
**NO**
- Local build: tested by providing path to a new directory. The script created container-build and container-buildroot folders in the directory, and mounted the build and buildroot folders from container.
> Add custom build mount

- SPECS/libguestfs/libguestfs.spec
---
Fix [build break](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=421960&view=results) from libguestfs seen below. Enable the `toolchain-repo` so that the `binutils` package, and all other toolchain packages, are 
available.
`
"+ cp /usr/src/mariner/SOURCES/tdnf-build-cache.repo /etc/yum.repos.d/allrepos.repo"
"+ mkdir -pv /var/cache/tdnf"
`
`
"+ tdnf install --downloadonly -y '--disablerepo=*' --enablerepo=local-repo --enablerepo=upstream-cache-repo --alldeps --downloaddir /var/cache/tdnf acl attr augeas-libs bash binutils btrfs-progs bzip2 coreutils cpio cryptsetup curl dhclient diffutils dosfstools e2fsprogs file …
> libguestfs: remove toolchain package requirements to fix build break

- SPECS/libssh2/CVE-2020-22218.patch
- SPECS/libssh2/libssh2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch libssh2 to address CVE-2020-22218
- CVE-2020-22218
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2020-22218
Buddy build for amd64 & arm64 is [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=420740&view=results)
> Patch libssh2 to address CVE-2020-22218

- toolkit/scripts/containerized-build/create_container_build.sh
- toolkit/scripts/containerized-build/resources/welcome.txt
---
Add platform arch to welcome text, so we can show the correct folder for RPMs. It is currently hardcoded to x86
- Add platform arch to welcome text, so we can show the correct folder for RPMs. It is currently hardcoded to x86
**YES/NO**
- Local build
> containerized-rpmbuild: add arch to welcome txt

- SPECS-EXTENDED/exiv2/exiv2.signatures.json
- SPECS-EXTENDED/exiv2/exiv2.spec
- SPECS-EXTENDED/libgexiv2/libgexiv2.signatures.json
- SPECS-EXTENDED/libgexiv2/libgexiv2.spec
- cgmanifest.json
---
Upgrade version to address 24 CVEs.
- exiv2: 0.27.5 -> 0.28.0
- exiv2: add changelog
- exiv2: cgmanifest: update entry
- libgexiv2: 0.12.1 -> 0.14.2
- libgexiv2: add changelog
- libgexiv2: cgmanifest: update entry
- libgexiv2: prefer Source0 as %{name}-%{version}.ext
**NO**
- NA
- NA
- Pipeline build id: [PR-6226](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=422429&view=results)
- Local build w/ & w/o `RUN_CHECK=y`
> Upgrade exiv2 0.27.5 -> 0.28.0

- toolkit/scripts/containerized-build.mk
- toolkit/scripts/containerized-build/create_container_build.sh
---
use folder definitions from Makefile, and allow user to override the default definitions
- use folder definitions from Makefile, and allow user to override the default definitions
- this makes the tool more usable by giving the user the freedom to choose any folder location as one of the Mariner folders
- draft PR: https://github.com/microsoft/CBL-Mariner/pull/6114
Below figures show example usages. Some have errors intentionally, so one can see how the tool overrides default Mariner directory structure and instead, uses the user provided directory.
Using another directory as build directory. The mount points show the user defined directory being used for storing build artifacts …
> containerized-rpmbuild: use folder definitions from Makefile

- .github/workflows/quickstart_1.0.yml
- .github/workflows/quickstart_2.0.yml
- toolkit/Makefile
- toolkit/docs/building/building.md
---
**This will remove the default value `CONFIG_FILE=./imageconfigs/core-efi.json` and replcae it with `CONFIG_FILE=""**
One of the most common sources of frustration for users of the toolkit is the default selection of the `core-efi.json` config file. This would cause pointless package rebuilds since even `sudo make build-packages` would be configured to create all the packages needed to build the image (including the kernel which is quite slow).
- Make the default value for `CONFIG_FILE` be `""`
**NO**
- Local builds
> Remove default CONFIG_FILE=

- SPECS-EXTENDED/gnome-desktop-testing/gnome-desktop-testing.spec
- SPECS-EXTENDED/iio-sensor-proxy/iio-sensor-proxy.spec
- SPECS-EXTENDED/iwd/iwd.spec
- SPECS-EXTENDED/pacemaker/pacemaker.spec
- SPECS-EXTENDED/samba/samba.spec
- SPECS-EXTENDED/systemd-bootchart/systemd-bootchart.spec
- cgmanifest.json
---
Full builds of the extended packages have been broken for an unknown amount of time.  The build was incorrectly trying to use systemd-bootstrap or systemd-bootstrap-devel as a build time dependency.  This change fixes sevearl SPEC files by explicitly requiring systemd or systemd-devel for the build time dependencies.
> Fix systemd/systemd-bootstrap confusion by adding explicit requires

- toolkit/scripts/containerized-build/create_container_build.sh
- toolkit/scripts/containerized-build/resources/mariner.Dockerfile
---
set starting directory based on mode
- Earlier we were starting at the same directory, /usr/src/mariner inside the container, but this directory is not created in the 'test ' mode
- Now, we set the starting directory based on the mode (build v/s test)
**NO**
- Local test
> set starting directory based on mode

- toolkit/resources/manifests/package/macros.override
---
Our test runner environment has changed drastically throughout the years and packages have been changed/upgraded, so we should re-evaluate tests that have been turned off in `macros.override` since the days of pre-1.0.
`gnutls`, `libsoup`: I can't track down the reason for these tests being disabled, but they seem to run without issues in our pipelines
`jna`: We no longer run tests for toolchain packages in the toolchain environment, so concerns over missing dependencies no longer apply.
`strongswan`: Test no longer hangs, most likely fixed by the solution to [this issue](https://github.com/strongswan/strongswan/issues/752)
- Remove `skip_check_*` macros from `macros.override` …
> Re-enable tests for gnutls, jna, libsoup, strongswan

- .github/workflows/go-test-coverage.yml
- toolkit/tools/go.mod
- toolkit/tools/imagecustomizer/main.go
- toolkit/tools/imagecustomizerapi/README.md
- toolkit/tools/imagecustomizerapi/fileconfig.go
- toolkit/tools/imagecustomizerapi/fileconfig_test.go
- toolkit/tools/imagecustomizerapi/filepermissions.go
- toolkit/tools/imagecustomizerapi/filepermissions_test.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/imagecustomizerapi/systemconfig_test.go
- toolkit/tools/imagecustomizerapi/utils.go
- toolkit/tools/imagecustomizerapi/utils_test.go
- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/main_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/files/a.txt
---
This creates the boilerplate for Mariner Image Customizer (imgcustomizer) tool. In addition, it implements `AdditionalFiles` since that is one of the simplest features to implement.
- Added feature to `chroot` to allow partitions to be mounted before the default partitions.
- Create imgcustomizer tool boilerplate.
- Implement `AdditionalFiles` in imgcustomizer.
- Added tests for:
- Unmarshalling of `AdditionalFiles` JSON/YAML.
- imgcustomizer's top level functions.
- `AdditionalFiles` logic.
NO
- Tests added.
> Mariner Image Customizer boilerplate

- SPECS/shadow-utils/CVE-2023-29383.patch
- SPECS/shadow-utils/shadow-utils.spec
---
Fixes CVE-2023-29383
This fix is based on https://github.com/NixOS/nixpkgs/pull/233924. An earlier attempt that included just the first patch caused a build break.
No
- https://nvd.nist.gov/vuln/detail/CVE-2023-29383
- Buddy Build: 424052. (Please note the tdnf install step fails due to a bug in InstallPackagesTdnf.sh)
- Full Pipeline build id: 424088
> Address CVE-2023-29383 in shadow-utils

- toolkit/scripts/check_spec_guidelines.py
---
The spec guidelines check script points to Fedora shortnames as the standard for license names in spec files. The new standard is using SPDX license expressions, so change the script's guidance to reflect that.
- Link to SPDX license expression explainer in spec guidelines check script
- Ran script locally
> Add SPDX license guidance to spec guidelines check

- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
Disable the TestCustomizeImageCopyFiles test as it appears to be unreliable.
- Disable TestCustomizeImageCopyFiles test.
NO
> Disable unreliable test

- toolkit/tools/imagegen/configuration/networkconfig.go
- toolkit/tools/imagegen/configuration/networkconfig_test.go
- toolkit/tools/imagegen/installutils/installutils_test.go
- toolkit/tools/internal/safechroot/safechroot_test.go
- toolkit/tools/internal/timestamp/timestamp_test.go
---
The go tools' unit tests presently don't run cleanly in VSCode. The main blockers are tests that require running as `root` / under `sudo`. While triaging some of those failures, I also noticed a unit test that is writing to `/etc` on the host system--that should be remedied.
- Fix the network config unit test so that it arranges to write to a test dir, not to real `/etc`. Actually makes the test simpler since we can leverage `t.TempDir()` and rely on it being existent (and empty) and cleaned up for us afterwards.
- Identify unit tests that require running in a chroot and arrange for them to be skipped when the effective UID isn't 0 (i.e., when we're running as non-root, and not …
> Get go tools unit tests to pass in VSCode

- toolkit/tools/depsearch/depsearch.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
---
Fix some go warnings, formatting issues, fix bug in depsearch.
- Fix go warnings.
- Fix bug with depsearch verbosity 4
**NO**
- Local
> Resolve Golang warnings, fix text output in depsearch.

- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
- Skip TestCustomizeImageEmptyConfig test in container builds, since loopback block devices aren't available.
- Skip TestCustomizeImageEmptyConfig test in container builds 
NO
> Skip TestCustomizeImageEmptyConfig test

- toolkit/scripts/tools.mk
- toolkit/tools/grapher/grapher.go
This reverts commit 47c831d5b1fae3b0a2816e95d2ed5921083cc8bb.
---
We suspect this change is causing some unexpected and semi-random build issues, so we're reverting it for the sake of the current release and will re-apply it with additional logging afterwards.
- Reverting toolkit changes from #6143.
No.
- #6143
- None - reverting to previous building state.
> Reverted "Cleaned-up invalid edges from duplicate nodes. #6143"

- toolkit/tools/grapher/grapher.go
This reverts commit cae9dd7dc36a3bf70664b9c2ae9b40a835346f0c.
---
Re-applying #6143 to get ready for the next release.
- Re-applied #6143.
No.
- #6143
- #6288
- Done in #6143.
> Restored "Cleaned-up invalid edges from duplicate nodes. #6143"

- toolkit/tools/scheduler/schedulerutils/implicitprovides.go
---
There is an edge case that may break builds using implicit provides. The symptoms are: `pkgA` queues for build, the scheduler calculates its build-time dependencies: `pkgB-1, pkgB-2, pkgC, ...`. When the packages are installed into the build environment, `pkgB-1` conflicts with `pkgB-2` and the build fails.
The scheduler calculates the build-time dependencies by doing a walk of the build graph starting from the node to be built (`pkgA_build`). In this example, lets say we have a newly updated `pkgB` with `version:2`. Our package also relies on `pkgC`. Both `pkgB` and `pkgC` have a dependency on the implicit package `/usr/bin/tool_b` (which by observation we know will come from …
> Allow scheduler to update cached implicit nodes

- toolkit/scripts/pkggen.mk
- toolkit/scripts/safeunmount.sh
---
Make `safeunmount.sh` optionally run in parallel. It will now accept multiple arguments, and for each argument it will behave the same as before, but in parallel (i.e., for each directory under the path provided it will check if that is a mountpoint and unmount it).
It can still be called the same way as before, but it can also now be called like `safeunmount.sh /path/to/chroot_container/*`, and for each directory inside `chroot_container` it will invoke the unmount logic (i.e., it will check if `/path/to/chroot_container/actual_chroot/*` is mounted and unmount as needed).
- Make `safeunmount.sh` run in parallel.
**NO**
- Pipelines will generally not exhibit …
> Make safeunmount.sh run in parallel

- toolkit/tools/go.mod
- toolkit/tools/go.sum
- toolkit/tools/internal/safechroot/safechroot.go
---
Sometimes the chroots we use do not unmount correctly. There seem to be many different reasons this can occur (but `/dev/hugepages` has been a recent culprit). Generally, we try to gracefully unmount them when we call `.Close()`, but the `safechroot` package tracks active chroots and calls `cleanupAllChroots()` when the tool exits. Currently we will make an attempt to clean, but if the unmount fails (often due to a busy mount) we give up and leave the mountpoint present. If the user isn't cautious and deletes this folder, it can mess up the host system until a reboot.
Linux offers a lazy unmount option. This will detatch the mountpoint from the fileystem even if it can't fully …
> Add a fallback lazy mode to chroot unmount

- toolkit/scripts/precache.mk
- toolkit/tools/precacher/precacher.go
---
The `precacher` tool will now also understand custom repo files passed (via `REPO_LIST=...`). For each repo file passed, the tool will query the associated repo and add the packages on that server to the URL list it uses (and outputs to `$(precache_state_dir)/repo_urls.txt`).
- `precacher` tool now supports `--repo-file` which can be used multiple times to add repo files to its list of package sources.
**NO**
> Support repofiles in precacher tool

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
---
Ensure the assets mount point directory name (i.e. "installer") is only specified in a single place.
In addition, modify the grub install functions so that the assets directory is a param instead of being a static path. This allows those functions to be useful in more scenarios (e.g. creating a fake image file in a unit test).
- Do not repeat the assets mount point directory name.
- Make grub install functions more generic.
NO
> Do not repeat the assets mount point directory name.

- toolkit/tools/imagecustomizerapi/fileconfig.go
- toolkit/tools/imagecustomizerapi/filepermissions.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/diskutils/fstab.go
- toolkit/tools/internal/safemount.go/safemount.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/main_test.go
---
In the imgcustomizer tool, detect the partitions available on the disk and how they should be mounted by reading the `grub.cfg` file on the boot partition and the `/etc/fstab` file on the OS partition. This will allow the tool to work on a variety of images with custom partition layouts.
- In imgcustomizer, detect partitions using `grub.cfg` and `fstab` files.
- Update some `installutils` functions so that they are usable by imgcustomizer.
- Ensure that the assets directory mount point is only specified once within the code.
NO
- Updated the UTs for imgcustomizer.
> Imgcustomizer: Discover partitions using grub.cfg and fstab files

- toolkit/tools/imagecustomizerapi/script.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/finalizeimagescript.sh
- toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/postinstallscript.sh
---
Add and implement the `PostInstallScripts` and `FinalizeImageScripts` config values in the image customizer.
- Image customizer: Implement `PostInstallScripts` and `FinalizeImageScripts`.
NO
- Manually run image customizer.
> Image customizer: Implement `PostInstallScripts` and `FinalizeImageScripts`.

- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/imagecustomizerapi/systemconfig_test.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
---
In the Image Customizer, add support for setting the hostname.
- Image Customizer: Support Hostname
NO
- Added UTs.
- Manually run image customizer.
> Image Customizer: Support Hostname

- toolkit/resources/imageconfigs/iso_initrd.json
- toolkit/resources/imageconfigs/iso_initrd_arm64.json
---
ISO-based installs were failing because we forgot to include the new grub template file in the iso manifests. This means that the isoinstaller would reference a file which is not present. 
- Add mkconfig-based template to iso installer manifests
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/46783936?src=WorkItemMention&src-action=artifact_link 
- Tested locally, verified we now boot from an installed iso image.
> Add mkconfig-based template to iso installer manifest

- SPECS-EXTENDED/libspiro/libspiro.signatures.json
- SPECS-EXTENDED/libspiro/libspiro.spec
- cgmanifest.json
---
Bump version 20190731 -> 20221101 to address CVE-2019-19847
- libsprio: upgrade version 20190731 -> 20221101 to address CVE-2019-19847
- libsprio: lint spec
- libsprio: verify license
- libsprio: cgmanifest: update entry
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2019-19847
- Pipeline build id: [PR-6267](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=425378&view=results)
> libsprio: upgrade version 20190731 -> 20221101 to address CVE-2019-19847

- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
---
Make the rpm commands needed for `srpms-snapshot` run in parallel.
Old time: 144 sec 
New time: 23 sec
`rpms-snapshot` is a prerequisite for running the `precacher` tool, and the longer it takes to generate the snapshot the longer we wait for the precacher to begin utilizing the network. We would like to optimize the utilization of the network so it can start as early as possible in the build.
- make `rpm.filterCompatibleSepcs() run in parallel`
- make `rpmsnapshot.readBuiltRpms()` run in parallel
**NO**
- Local
> Make rpms-snapshot run faster

- toolkit/scripts/precache.mk
- toolkit/tools/precacher/precacher.go
---
If there are no repo files present, `repoquery` treats `--enablerepo=*` as a repo with the literal name `*`, and returns `Error: Unknown repo: '*'`.
In the `precacher` tool don't even run `repoquery` if the user passes no repo files to query (it will still query each repo URL given though).
- Skip running `repoquery` in the precacher if the user passes no repo files.
**NO**
- Local testing against main and 2.0-stable
> Only query precacher repos if one is passed in

- toolkit/imageconfigs/additionalconfigs/51-ptp-hyperv.rules
- toolkit/imageconfigs/additionalconfigs/chrony.cfg
- toolkit/imageconfigs/additionalconfigs/configure-image.sh
- toolkit/imageconfigs/additionalconfigs/wait-for-ptp-hyperv.conf
- toolkit/imageconfigs/marketplace-gen1-fips.json
- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2-aarch64.json
- toolkit/imageconfigs/marketplace-gen2-fips.json
- toolkit/imageconfigs/marketplace-gen2.json
---
adds files for the image builder to install into azure marketplace images to fix #6233 
adds files for the image builder to install into azure marketplace images to fix #6233 
- Change
- Change
- Change
YES
- #6233 
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=423367&view=results
> Add files into azure marketplace image to make chronyd.service require /dev/ptp_hyperv before starting

- toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
---
Change cloud-int modules running order to make sure yum_add_repo running before package-update-upgrade-install otherwise it will cause issues when user want to add new package repos and install packages using cloud-init customize script.
- move yum_add_repo module to run earlier stage
- move package-update-upgrade-install back to cloud_final_modules following upstream pattern in [cloud.cfg](https://github.com/canonical/cloud-init/blob/main/config/cloud.cfg.tmpl)
NO
- [Bug 46139895](https://microsoft.visualstudio.com/OS/_workitems/edit/46139895): Observed issue while deploying packages in Mariner 2.0 VM with cloud-init script.
- …
> cloud-init modify running order of modules 

- SPECS/kubernetes/kubernetes.spec
---
Static glibc version check is failing currently because kubernetes.spec is pointing to glibc-static 2.35-5 instead of 2.35-6.
Bump kubernetes release to rebuild against glibc 2.35-6
- Bump kubernetes release to rebuild against glibc 2.35-6
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=432680&view=results
> Bump kubernetes release to rebuild against glibc 2.35-6

- .pipelines/templates/PackageBuild.yml
- .pipelines/templates/PackageTestResultsAnalysis.yml
---
We've been having issues installing Python modules through `pip` in our PR check pipelines. It looks like package builds were interfering with the configuration set by the `PipAuthenticate@1` task, so we're now making sure we call it every time we need `pip`, regardless if it's been called before.
- Adding `PipAuthenticate@1` to the ptest analysis templates.
No.
- [Sample PR check run.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=432694&view=results)
> Running `PipAuthenticate@1` in each template separately.

- SPECS/irqbalance/fix-load-unsigned-overflow.patch
- SPECS/irqbalance/irqbalance.spec
---
Currently irqbalance has an unsigned subtraction overflow that can cause it to leave IRQs pinned to a core that should actually be rebalanced. This PR applies an upstream fix to that calculation to avoid the overflow.
https://github.com/Irqbalance/irqbalance/commit/2a66a666d3e202dec5b1a4309447e32d5f292871
- Patch unsigned subtraction overflow in irqbalance.
**NO**
- Local package build succeeded. Tested binaries from local package build on a K8s cluster.
- Buddy build succeeded: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=432669&view=results
1) Start a Standard_D8ads_v5 Azure VM with current irqbalance binary (1.8.0-3)
2) Load the system with network …
> Patch irqbalance to fix incorrect balancing behavior

- toolkit/Makefile
- toolkit/docs/building/building.md
---
There is currently an inconsistency in how `USE_PREVIEW_REPO=y` treats `PACKAGE_URL_LIST`, `SRPM_URL_LIST`, and `REPO_LIST`. Currently the preview repos are appended to `REPO_LIST` regardless of how the initial value was set.
> In make, variables may come from several places like env, cmdline, or inside the makefile. `?=` will set a variable if it is undefined. `+=` will append to a variable. However, `+=` will ONLY append to variables that are set inside the makefile (generalizing slightly here). This means that if a user passed `make my-target MY_VAR=value`, and inside the makefile we see `MY_VAR ?= default` and `MY_VAR += new_value`, the final result will still be `"value"`. …
> Unify behavior of `USE_PREVIEW_REPO` on url and repo lists

- toolkit/tools/imagecustomizerapi/config.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/addusers-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/services-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml
---
Currently, the image customizer API uses the `SystemConfig` struct directly for its config. However, there is supposed to be a parent `Config` struct on top. This is so the API better mirrors the new image config.
- Image Customizer: Add `Config` struct to API.
NO
- Ran UTs
> Image Customizer: Add `Config` struct.

- SPECS/cmake/CVE-2023-38545.patch
- SPECS/cmake/CVE-2023-38546.patch
- SPECS/cmake/cmake.spec
- SPECS/curl/CVE-2023-38545.patch
- SPECS/curl/CVE-2023-38546.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patches high and low curl CVEs as well as vendored `curl` in `cmake`
- patched CVE-2023-38545 for curl
- patched CVE-2023-38546 for curl
- patched CVE-2023-38545 for vendored `curl` in `cmake`
- patched CVE-2023-38546 for vendored `curl` in `cmake`
**NO**
- https://curl.se/docs/CVE-2023-38545.html
- https://curl.se/docs/CVE-2023-38546.html
- PR fasttrack check
> Patched CVE-2023-38545, CVE-2023-38546 for `cmake` and `curl`.

- toolkit/scripts/tools.mk
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
When running the toolkit UTs as part of the toolkit build, enable to go's test short mode flag. Then use that flag to disable a couple of the longer running and less reliable image customizer tests.
- Toolkit: Use test short mode flag.
- Ensure tests that need root privileges are skipped when not running as root.
NO
> Toolkit: Use test short mode flag.

- toolkit/docs/building/prerequisites-ubuntu.md
- toolkit/tools/go.mod
Cherry-pick the update to the prerequisite instructions into the 2.0 branch from #6348
> [2.0] Updated Ubuntu requirements doc with better Golang instructions.

- toolkit/tools/internal/safemount/safemount.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/rpmsourcesmounts.go
---
Improve the safemount class so that if an unmount fails (usually because the device is still busy), then the unmount is reattempted using the asynchronous flag (MNT_DETACH). This reduces the likelihood that the user's system will be left in a bad state.
To be specific, the `Close()` function has been split into a synchronous and asynchronous version. The synchronous version is intended to be used in the code's golden path. Whereas the asynchronous version should be used with `defer`.
- safemount: Provide synchronous and asynchronous versions of `Close`.
- Fix name of `safemount.go` module to `safemount`.
- Remove redundant `diskutils.WaitForDevicesToSettle()` call.
NO
- Ran …
> Image Customizer: Improve safemount.

- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
Allow image customizer to customize images that use xfs partitions.
- Ensure `xfs` partitions are included in search for rootfs partition.
- Fix for golang's weird for-loop/pointers behavior.
NO
> Image Customizer: Fix XFS disk handling.

- SPECS/cni-plugins/cni-plugins.signatures.json
- SPECS/cni-plugins/cni-plugins.spec
- cgmanifest.json
---
To address issues stated in #6339 
- cni-plugins has been updated to latest available version v1.3.0 and will now correctly print installed version when binaries are run with `-v`
**YES/NO**
NO
- #6339 
- None
> SPECS/cni-plugins: update to v1.3.0 and set version while building

- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Using the absolute paths ensures there aren't any weird issues that can occur when dealing with relative paths.
---
Image Customizer: Convert the config file parent directory's path to an absolute path to avoid issues with relative paths. (e.g. passing an empty string to `mount` will fail.).
- Image Customizer: Use absolute path for base config path.
NO
> Image Customizer: Use absolute path for base config path.

- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
---
For the following package dependencies:
```
A_build <-- A_test
^
|
A_run
B_build <-- B_test
^
|
B_run
```
and the following run command:
```
sudo make build-packages RUN_CHECK=y TEST_RERUN_LIST="A B" PACKAGE_REBUILD_LIST="B"
```
the toolkit would skip building and testing package `A`. The issue was the subgraphing logic to only build the required nodes was not updated to correctly handle the test nodes added a month ago. The tool would only look for run nodes and since `A` was not mentioned inside `PACKAGE_REBUILD_LIST`, then the run node `A` would be skipped and thus assumed it was already pre-built. The same logic would ignore test nodes, thus `A` ended up being skipped for …
> Fixed toolkit missing package rebuilds.

- .github/workflows/go-test-coverage.yml
---
We were not correctly detecting build breaks in our go tools due to tooling version changes. The Github Action worker was always using a very recent version of the Go tools and this could mask breaking changes.
We use `sudo` to run out tools, which clears the environment of the calling user by default. The action used to install Go does so by modifying the user's PATH. We need to explicitly pass this updated PATH to the tools if we want them to use the correct go.
Also add a check that validates the workflow against the `go.mod` file and alert if they get out of sync.
- Add a step to run `sudo make go-tools REBUILD_TOOLS=y` to the `go-test-coverage.yml` tests.
- Use correct …
> Update go-test-coverage.yml to verify go version.

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/safeloopback/main_test.go
- toolkit/tools/internal/safeloopback/safeloopback.go
- toolkit/tools/internal/safeloopback/safeloopback_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
After requesting a loopback device to detach (`losetup --detach), the loopback device will remain open until all file handles to the device have closed. This change ensures that the Image Customizer waits for the loopback device to fully close before outputting the final image.
- Image Customizer: Ensure loopback cleanly detaches.
NO
- Added toolkit UT.
> Image Customizer: Ensure loopback cleanly detaches.

- toolkit/tools/imagecustomizerapi/module.go
- toolkit/tools/imagecustomizerapi/service.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/modules-config.yaml
---
add support to load or unload modules to image customizer tool
Image customizer: add support to load or unload modules
NO
did `go run  . --build-dir ./build --config-file ../pkg/imagecustomizerlib/testdata/modules-config.yaml --image-file core-2.0.20231004.vhdx --o
utput-image-file ./out/image1.vhd --output-image-format vhd --log-file=trace` and test with output image , the modules specified in the testdata file are loaded and unloaded.
note: This feature only supports loading existing modules or those with the required environment, and unloading modules without dependencies. For example, it can't load 'ptp_kvm' due to a 'No such device' error, nor unload 'nfit' because of its …
> Image Customizer: Add support to load and unload modules

- SPECS/skopeo/skopeo.signatures.json
- SPECS/skopeo/skopeo.spec
- cgmanifest.json
---
Update skopeo to v1.13.3 to fix CVE 2023-33199 in rekor
- Update skopeo to v1.13.3 to fix CVE 2023-33199 in rekor
- skopeo v1.12.0 comes with rekor v1.1.0 and skopeo v1.13.3 comes with rekor v1.2.2
- The CVE is fixed for rekor >=1.2.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-33199
- Local build
> Update skopeo to v1.13.3 to fix CVE-2023-33199 in rekor

- toolkit/scripts/imggen.mk
---
Image package fetcher was searching for required packages having access to only a subset of the toolchain packages. This was causing issues if a newer version of the toolchain package was available in Mariner's upstream RPMs repository and the imager tried to access it instead of the version from the local toolchain.
Context: 
- An image requires `python3-pip`.
- `python3-pip` is part of the toolchain but not part of the worker chroot.
- The toolchain manifest declares version `N` of `python3-pip`.
- The upstream repo has version `N+1`.
Imager now tries to install `python3-pip` through `tdnf install python3-pip --installroot /installroot ...` and fails with the following error: …
> Giving image package fetcher access to all toolchain packages.

- SPECS/edk2/CVE-2023-0465.patch
- SPECS/edk2/CVE-2023-2650.patch
- SPECS/edk2/edk2.spec
---
Fix CVE-2023-04-65 and CVE-2023-2650 in edk2.
- CVE-2023-0465: Apply this patch [b013765](https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=b013765abfa80036dc779dd0e50602c57bb3bf95) ([github](https://github.com/openssl/openssl/pull/20588/commits/616b48c880f06cd7d5d2a027c308cb38c574c663))
- CVE-2023-2650: Apply this patch [9e20994](https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=9e209944b35cf82368071f160a744b6178f9b098) ([github](https://github.com/openssl/openssl/commit/9e209944b35cf82368071f160a744b6178f9b098)) The code section of the original patch applies cleanly, but the CHANGES/NEWS sections don't because the original patch is for a newer minor …
> Patch edk2 to fix CVE-2023-0465 and CVE-2023-2650

- toolkit/tools/internal/ccachemanager/ccachemanager.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/scheduler/scheduler.go
---
Two Fixes:
(1)
CCache is a build optimization and any failure of its path should not cause the build to fail.
The problem this change is fix is that the ccache code path was returning errors into the `err` variable - which is automatically returned from the higher-level build function. This caused those function to report failure even all rpms were built successfully. The fix creates a new variable to hold the error object returned from ccachemanager functions. That way, we do not pollute the `err` object used by the core build code path.
(2)
CCache configuration allows the user to specify where to download ccache artifacts before …
> CCache failure should not fail the build + Allow in-place updates of remote artifacts

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
Currently, the Image Customizer doesn't handle the case where the boot partition is separate from the rootfs partition. So, it fails to find the rootfs partition.
- Image Customizer: Handle separate boot partition.
NO
> Image Customizer: Handle separate boot partition.

- SPECS/libcontainers-common/libcontainers-common.spec
> Bump libcontainers-common release to rebuild with updated version of Go for cve-2023-44487

- SPECS/grpc/grpc.spec
- SPECS/libcontainers-common/libcontainers-common.spec
> Bump grpc release to rebuild with updated version of Go.

- SPECS/systemd/mariner-2-do-not-default-zstd-journal-files-for-backwards-compatibility.patch
- SPECS/systemd/systemd.spec
Also for mariner 2, force journald to not use zstd compression, to retain backwards compatibility.
---
allows journalctl to read zstd compressed journal files
- Change
- Change
- Change
build systemd with zstd support
disable journald from defaulting to zstd-compressed journal file creation, to retain backwards compatibility for mariner 2
**/NO
- #6424
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=438674&view=results
-
> systemd: enable zstd support in journald

- toolkit/docs/building/prerequisites-mariner.md
- toolkit/docs/building/prerequisites-ubuntu.md
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/userutils/main_test.go
- toolkit/tools/internal/userutils/userutils.go
- toolkit/tools/internal/userutils/userutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
---
Currently, the situation where a user is specified in the new-image config or the image-customizer config without a password is not handled. This change ensures that the user password login is disabled in such situations (by either not passing a password value to `useradd` or by setting the password value to `!` in the /etc/shadow file).
In addition, this change fixes a bug that could allow the plain-text password to be printed when the trace logs are enabled.
- Image config: Handle case where user is specified without a password.
- Don't print plain-text password to trace logs.
NO
> Image config: Fix for when no user password is specified.

- SPECS/httpd/httpd.signatures.json
- SPECS/httpd/httpd.spec
- cgmanifest.json
---
- httpd: upgrade 2.4.56 -> 2.4.58 to address CVE-2023-45802, CVE-2023-43622 & CVE-2023-31122
- Reference: https://[downloads.apache.org/httpd/CHANGES_2.4.58](https://downloads.apache.org/httpd/CHANGES_2.4.58)
- upgrade httpd `2.4.56 -> 2.4.58`
**NO**
- NA
- https://seclists.org/oss-sec/2023/q4/149
- https://seclists.org/oss-sec/2023/q4/150
- https://seclists.org/oss-sec/2023/q4/151
- Local build.
- Pipeline build id: [PR-6559](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=439004&view=results)
> httpd: upgrade 2.4.56 -> 2.4.58 to address CVE-2023-45802, CVE-2023-43622 & CVE-2023-31122

- toolkit/scripts/tools.mk
- toolkit/scripts/utils.mk
- toolkit/tools/internal/pkggraph/pkggraph_test.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
Some of the toolkit UTs are unreliable. Use the test short mode flag to disable these tests.
- Toolkit: Use test short mode flag to disable some unreliable tests.
- Call setfacl on the chroot dir directly in case it is set by the user.
NO
> Toolkit: Disable unreliable tests

- toolkit/Makefile
- toolkit/scripts/repoquerywrapper.mk
- toolkit/scripts/tools.mk
- toolkit/scripts/update-target-if-output-changed.sh
- toolkit/tools/internal/packagerepo/repoutils/repoquery.go
- toolkit/tools/precacher/precacher.go
- toolkit/tools/repoquerywrapper/repoquerywrapper.go
* Add the repoquerywrapper tool.
The repoquerywrapper tools creates a chroot, installs dnf packages, and runs specific repoquery commands within that environment.
This tools allows us to run repoquery on systems that may not have repoquery installed/available.
It also allows us to run queries that are not directly supported by repoquery - for example, in this check-in, it allows us to check which packages in a list are available on the target repros.
Such queries are very specific - and can be added incrementally to the tool as the need arises.
* Fix formatting (make go-tidy-all).
* Fix typo in help message.
---
Needed to unblock the 3.0-dev image build
- Add tool change to unblock …
> Add the repoquerywrapper tool. (#6390)

- toolkit/scripts/build_tag.mk
- toolkit/scripts/tools.mk
- toolkit/tools/imagecustomizer/main.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
Add a version to the image customizer tool. This version and the version format will be different from the CBL-Mariner OS.
This change updates the `Makefile` files to handle this new version. It also ensures that the `--version` CLI option reports the calculated version.
- Image Customizer: Add tool version.
NO
> Image Customizer: Add tool version.

- toolkit/tools/imagegen/installutils/installutils.go
---
Previously, if the user didn't specify a password in the config then the imager tool would corrupt the `/etc/shadow` file by putting the value `<NULL>` (which came from `openssl` CLI) in the password field.
PR #6443 fixed this for the Image Customizer tool by using the correct value of `!` in the `/etc/shadow` file to disable password login. However, that change didn't apply the fix properly to the Image tool.
- Imager: Fix for when user password is empty.
NO
- Manually built and test live installer ISO.
> Imager: Fix for when user password is empty.

- toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
- toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
- toolkit/tools/internal/packagerepo/repocloner/repocloner.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/packagerepo/repoutils/repoutils.go
---
There can be situations where we end up with conflicting package versions. Consider a config file with two packages listed (either directly or in a package list). `pkgA` which depends on a specific version of `dep`, and `pkgB` which also depends on a specific version of `dep`. Lets say that `dep-v1-1` is available in the toolchain, but we published `dep-v1-2` via a fasttrack publish. `pkgA` is also available in the toolchain.
In the current implementation we clone each package one at a time, prioritizing chroot, then toolchain, then local packages, then PMC. If we clone `pkgA`, we will try the toolchain …
> Add single transaction for image package cloner

- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
This commit addresses a bug to ensure that the correct rootfs partition is returned when MIC identifies it.
- When MIC attempts to locate the rootfs partition for an image with an EFI boot type, it uses the boot partition to pinpoint the rootfs partition. However, instead of returning the correct rootfs partition, it previously returned the boot partition. This led the MIC to mistakenly believe that the boot partition was the root one.
**NO**
- #xxxx
- local build
> Bugfix: Correctly Return Rootfs Partition Instead of Boot Partition

- toolkit/scripts/toolchain.mk
- toolkit/tools/downloader/downloader.go
---
The delta toolchain downloader is fully serial, so the new retry logic on the downloads has a significant effect on the runtime. We expect many of these downloads to return 404 errors. Even if we limit the retry to 5s we get a maximum of `594 * 5sec = ~45min`. This is too much for a delta build. Generally, a 404 won't resolve with retrying, so just give up immediately for 404 errors.
We also hide output from the tool (`2> /dev/null`) since we will expect some errors (we will 404 debuginfo no matter what since its not in the base repo). The makefile will report an error if all options faile.
- `downloader` considers `404` a "valid" response, so does not continue to retry.
**NO**
- …
> go-downloader: abort immediately on 404 errors

- SPECS/systemd/systemd.spec
---
After enabling zstd support in systemd build, one can encounter an error where libzstd.so.1 is missing in /sbin/init.
[    0.593882] Run /sbin/init as init process
/sbin/init: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
[    0.647950] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    0.648635] CPU: 0 PID: 1 Comm: init Not tainted 6.1.0.mshv11 #1
[    0.649059] Call Trace:
[    0.649251]  <TASK>
[    0.649529]  dump_stack_lvl+0x3b/0x59
[    0.649881]  panic+0xfb/0x264
[    0.650240]  do_exit.cold+0x15/0x15
[    0.650639]  do_group_exit+0x28/0x80
[    0.651034] …
> systemd: Add missing Requires on zstd-libs

- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers-cc/keep-uvm-rootfs-dependencies.patch
---
The kata-cc UVM build process pulls in core-packages-base-image as a meta package and removes some unused packages to reduce the image size and optimize boot time. Package zstd-libs is one of these removed packages but has since become a dependency necessary to boot the UVM. This change adds zstd-libs back to the UVM.
Boot sequence with missing zstd-libs:
```
[    0.593882] Run /sbin/init as init process
/sbin/init: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
[    0.647950] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    0.648635] CPU: 0 PID: 1 Comm: init Not tainted 6.1.0.mshv11 #1
[ …
```
> Add kata-containers-cc patch to retain uvm dependencies

- toolkit/tools/internal/userutils/userutils.go
- toolkit/tools/internal/userutils/userutils_test.go
---
When sshd has `UsePAM yes` in its config, then sshd defers the decision about whether or not the user is disabled to PAM. And PAM does not consider the value of `!` in the shadow file to represent the user being disabled.
However, when sshd has `UsePAM no`, then sshd must make the determination itself about whether the user is disabled or not. And sshd considers `!` in the shadow file to mean the user is disabled.
- No password: Use `*` instead of `!`.
NO
- Manual testing
> No password: Use `*` instead of `!`.

- SPECS/mysql/mysql.signatures.json
- SPECS/mysql/mysql.spec
- cgmanifest.json
---
Update mysql to v8.0.34 to resolve unavailable medium cves
- Update mysql to v8.0.34 
- Fix CVE: CVE-2023-22053, CVE-2023-22054, CVE-2023-22056, CVE-2023-22058, CVE-2023-22065, CVE-2023-22110, CVE-2023-22111, CVE-2023-22113, CVE-2023-22115
- New files were added, upgrade ICU lib to v73 to mysql in this commit and [commit link] (https://github.com/mysql/mysql-server/commit/6b0c75e9d2283d09b572514c790ff25a7d701699) Adding these files to the mysql-devel package.
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-22053
- https://nvd.nist.gov/vuln/detail/CVE-2023-22054
- https://nvd.nist.gov/vuln/detail/CVE-2023-22056
- …
> upgrade mysql to 8.0.34

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Cherry pick of bug and feature template updates to main.  This is a non-code change.  It only applies to github templates
> Cherry Pick bug and feature template updates to main

- toolkit/resources/assets/meta-user-data/user-data
Per internal audit clarified the text for usage of passwords
> Clarify that passwords are not permitted for production use in meta user data configuration file

- toolkit/docs/quick_start/quickstart.md
- toolkit/resources/assets/meta-user-data/user-data
Removed sample username and password information. Instructions now describe how to use provisioned username and password.
> Merge meta user data fixes to 3.0-dev branch

- .config/CredScanSuppressions.json
---
[Recent CredScan runs](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=448990&view=results) have revealed two new secrets in our code. Fortunately, one is a sample secret in the documentation and another inside a configuration file used as test data. No actual secrets to worry about, so I'm extending the CredScan exceptions to cover these two files.
The CredScan is blocking fast-track PR checks.
- Updated `CredScanSuppressions.json` to ignore `toolkit/imagecustomizer/docs/configuration.md` and `toolkit/pkg/imagecustomizerlib/testdata/addusers-config.yaml`.
No.
- #6696
- N/A - doc changes.
> Added CredScan exception for doc and test sample secrets.

- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
---
Occasionally, we'd get [a segfault coming from inside `rpmssnapshot.go:convertResultsToRepoContents()`](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=449140&view=logs&j=e459516c-3865-59c8-4722-7df34429222e&t=9c0c2a89-c5ad-507a-8d51-259303ab0653&l=1279). My current suspicion is that this might be due to the `builtRPMs` slice shared by multiple threads inside the `readBuiltRPMs`. Since slices are not thread-safe, it's possible for it to get partially overwritten by a different thread while it's `SnapshotResult.rpms` is being populate to be sent into the results channel.
- Switched to using a separate output buffer for each worker thread inside …
> Using separate buffer per analyzed spec in `rpmssnapshot.go`.

- SPECS/chrony/chrony.spec
---
A small cosmetic change, Azure Linux does not use Network Manager, removing references to it.
- Remove NetworkManager include files
**NO**
- Built package
```
INFO[0112][scheduler] Tested: chrony-4.1-3.cm2.src.rpm
INFO[0112][scheduler] 0 currently active build(s): [].
INFO[0112][scheduler] 0 currently active test(s): [].
INFO[0112][scheduler] All packages built
INFO[0113][scheduler] ---------------------------
INFO[0113][scheduler] --------- Summary ---------
INFO[0113][scheduler] ---------------------------
INFO[0113][scheduler] Number of built SRPMs:             1
INFO[0113][scheduler] Number of tested SRPMs:            1
INFO[0113][scheduler] Number of prebuilt SRPMs: …
```
> Cosmetic change with chrony removed references to NetworkManager

- .pipelines/prchecks/PackageBuildPRCheck.yml
- .pipelines/templates/PackageBuild.yml
---
Limiting the number of CPUs used per package build to unblock the `pytorch` builds. This should also help with a few other packages, which tend to hug resources like `ceph`.
- Decreased the number of CPUs used per package build.
No.
- PR check.
> Switched to building with fewer CPUs per package.

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imagegen/installutils/installutils.go
---
Some preliminary changes in preparation of the image customizer partitioning change:
1. Create a new UpdateFstabFile function that takes the absolute path of the fstab file instead of the root directory path.
2. Remove the `blockSize` parameter from `CreateSparseDisk` since it is no longer needed.
- Toolkit: Improvements for UpdateFstab and CreateSparseDisk
NO
- Ran toolkit UTs,
- Built core-efi image and booted it.
> Toolkit: Improvements for UpdateFstab and CreateSparseDisk

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
---
Move the `ConfigureDiskBootloader` function into the `installutils` package. This is being done so that it is usable by the image customizer tool.
- Toolkit: Move `ConfigureDiskBootloader` function.
NO
- Ran toolkit UTs,
- Built core-efi image and booted it.
> Toolkit: Move `ConfigureDiskBootloader` function.

- toolkit/scripts/toolchain/toolchain_verify.sh
---
toolkit: fix user instructions in case of error
- If toolchain_verify.sh script detects an error with mounts, it outputs `It looks like a toolchain directory is still mounted. Unmount the directory, then run make toolchain-cleanup` to the user, but we don't have a `toolchain-cleanup` make target. Changing it to the correct target, `clean-toolchain`
**NO**
- None
> toolkit: fix user instructions on toolchain build error

- toolkit/tools/internal/safemount/main_test.go
- toolkit/tools/internal/safemount/safemount.go
- toolkit/tools/internal/safemount/safemount_test.go
---
Adds a retry loop when safemount attempts to unmount the directory. This should hopefully prevent the resource busy errors that very occasionally appear.
- Toolkit: Add retry to safemount.Close().
NO
- Add UT.
> Toolkit: Add retry to safemount.Close().

- SPECS/kubernetes/kubernetes.spec
---
Fixes: #6719
The KUBE_GIT_VERSION_FILE seems to be not present in the release.
Use the alternative KUBE_GIT_VERSION instead.
Reference: https://github.com/kubernetes/kubernetes/blob/v1.28.3/hack/lib/version.sh#L26
- Fix `version` subcommand for components
**NO**
- #6719
- NA
- Pipeline build id: [PR-6722](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=450075&view=results)
- Local build w/o `RUN_CHECK=y` & verified with an install in a AzureLinux VM
```bash
root [ ~ ]# rpm -qa | grep kubeadm
kubernetes-kubeadm-1.28.3-2.cm2.x86_64
root [ ~ ]# kubeadm version …
```
> kubernetes: fix version subcommand for components

- SPECS/cloud-init/cloud-init.signatures.json
- SPECS/cloud-init/cloud-init.spec
- SPECS/cloud-init/make_fallback_network_config_work.patch
- cgmanifest.json
---
update to cloud-init 23.3.3, and disable the Photon-specific behavior of refusing to perform fallback network configuration.
> update to cloud-init 23.3.3 and make cloud-init network fallback configuration work

- SPECS/cloud-init/cloud-init.signatures.json
- SPECS/cloud-init/cloud-init.spec
---
Fix the following build break:
```
WARN[0058][srpmpacker] Failed to download (https://cblmarinerstorage.blob.core.windows.net/sources/core/23.3.3.tar.gz#cloud-init-23.3.3.tar.gz). Error: invalid response: 404 
ERRO[0058][srpmpacker] unable to hydrate file: 23.3.3.tar.gz#cloud-init-23.3.3.tar.gz 
ERRO[0058][srpmpacker] unable to hydrate file: 10-azure-kvp.cfg     
ERRO[0058][srpmpacker] Failed to pack (/specs/cloud-init/cloud-init.spec). Cancelling outstanding workers. Error: unable to hydrate file: 10-azure-kvp.cfg 
PANI[0078][srpmpacker] unable to hydrate file: 10-azure-kvp.cfg     
panic: (*logrus.Entry) 0xc003800070
```
- Change …
> fix cloud init sources

- toolkit/tools/srpmpacker/srpmpacker.go
---
Our tooling is expected to fail the build by default in case of a spec source signature mismatch. Right now we were ignoring the errors returned by out validation logic for local files and only displayed a warning.
- Made sources' signatures mismatches fatal by default.
No.
- Local tests.
- Buddy build for a successful case.
> Fixed signature checking for local sources to break the build on a mismatch.

- .pipelines/templates/PackageBuild.yml
- SPECS/systemd/systemd.spec
---
We want to make the cascading rebuilds flag for the package builds configurable in the template. By default `QUICK_REBUILD=y`` sets it to `1`, while it is normally left unset. This gives us 'n+1' package builds which are good for validation and testing, but for a full build we may not want to rebuild those additional packages.
- Add `maxCascadingRebuilds` parameter to `PackageBuild.yml`
**NO**
> Make cascanding rebuilds configurable

- SPECS/man-pages/man-pages.spec
---
Fix for error seen building packages: `acl` / `nfs4-acl-tools` / `squashfs-tools`
```
Found 1 problems\nfile /usr/share/man/man3/crypt.3.gz from install of man-pages-5.13-1.cm2.noarch conflicts with file from package libxcrypt-devel-4.4.27-3.cm2.x86_64"
```
- Change man-pages to remove crypt pages that are in `libxcrypt-devel`
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=455024&view=results
> man-pages: remove file conflicts from libxcrypt-devel

- toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
---
Cherry pick the fix for #6706 into 3.0 dev to fix random errors like: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=455033&view=logs&j=2ccbf1db-6c73-5af8-5ba2-cf05469dcf51&t=62118ca4-5f53-54b3-7ec9-8ef4ab0e9237
```
ERRO[0014][rpmssnapshot] Failed to convert RPMs list to a packages summary file. Error: RPM package name () doesn't match the regular expression (^(.*)-([^-]+-[^-]+)\.([^.]+)\.([^.]+)$).
ERRO[0014][rpmssnapshot] Failed to generate snapshot from specs folder (/mnt/vss/_work/1/s/SPECS) into (/mnt/vss/_work/1/s/build/rpms_snapshots/SPECS_rpms_snapshot.json). Error: RPM package name () doesn't match the …
```
> 3.0-dev: Using separate buffer per analyzed spec in `rpmssnapshot.go`

- .pipelines/templates/PackageBuild.yml
---
The toolkit should generally be called with a static set of inputs, we are using `TOOLCHAIN_ARCHIVE=./path/to/toolchain.tar.gz` when we call `make toolchain`. We should continue to use the same input for future commands. Generally we won't re-create the toolchain .rpms since nothing will cause a rebuild, but we should be defensive. If something DOES change, without setting `TOOLCHAIN_ARCHIVE` the toolkit will assume it should download the .rpms. This may fail if one of the toolchain packages has been bumped and was rebuild in the previous stage.
If we pass `TOOLCHAIN_ARCHIVE` to all commnads that use the toolchain the toolkit will know to extract antying that is missing from the …
> Pass toolchain archive to make  in pipeline template

- toolkit/tools/scheduler/schedulerutils/buildworker.go
---
Currently, our build output only shows if test of SRPM(s) failed. It doesn't point to the logs which contain details on failure.
This change prints the path to logs so we can debug the failure
Before the log message was:
`Test build for /path/to/srpm failed on a non-test build issue. Error: exit status 2`
`Tests failed for /path/to/srpm. Error: package test failed. Test status line ... EXIT STATUS 127`
and now the log message will look like:
`Test build for /path/to/srpm failed on a non-test build issue. Error: exit status 2, for details see /path/to/logs`
`Tests failed for /path/to/srpm. Error: package test failed. Test status line ... EXIT STATUS 127, for details see …
> Print logs on build/test failure

- SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
- SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-azure/kernel-azure.spec
- SPECS/kernel-hci/kernel-hci.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
When testing kernel builds in the latest Mariner 2.0 container, it was noted that the list of kernel's BuildRequires is missing cpio. The container (unlike our core images used in VMs) does not include "cpio" by default as defined in [core-package.spec](https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/core-packages/core-packages.spec#L20). This led to kheaders errors. Therefore, add as a buildRequires.
- Update kernel, kernel-hci, kernel-azure BuildRequires to include cpio
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/47270456
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=455974&view=results
```
sudo docker run -it --rm --pull=always …
```
> [2.0] Update kernel, kernel-hci, kernel-azure BuildRequires to include cpio

- SPECS/kernel/kernel.spec
---
Cherry-pick from https://github.com/microsoft/CBL-Mariner/commit/1f4f655bb15892177e9d4e8b950d538bd26ea6a8
When testing kernel builds in the latest Mariner 2.0 container, it was noted that the list of kernel's BuildRequires is missing cpio. The container (unlike our core images used in VMs) does not include "cpio" by default as defined in core-package.spec. This led to kheaders errors. Therefore, add as a buildRequires.
- Update kernel BuildRequires to include cpio
**NO**
-
> [3.0] Update kernel BuildRequires to include cpio

- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/rpm/rpm_test.go
---
In preparation for an implicit provides optimization PR (RFC/PoC: https://github.com/microsoft/CBL-Mariner/pull/6298), add a function to rpm:
- `ExtractNameFromRPMPath()`: Extracts the name of a package from it full filename. i.e., `pkg-name-1.2.3-4.cm2.x86_64.rpm` -> `pkg-name`. This needs to run on paths to files thay may not exist to using `rpm -q ...` isn't possible here.
- Add `ExtractNameFromRPMPath()` 
**NO**
- Local
> Add ExtractNameFromRPMPath() to rpm.go

- toolkit/scripts/containerized-build/create_container_build.sh
---
containerized-build: The newly added downloader tool was missing from the list of tools to build, leading to containerized-rpmbuild erroring out. This fix checks if downloader tool is built, or builds if missing.
- The make command for containerized-rpmbuild would error out with this message
- Added a check for downloader, and build it in case missing
**NO**
- Local build
> containerized-build: Add downloader to list of tools to build

- SPECS/msft-golang/msft-golang.signatures.json
- SPECS/msft-golang/msft-golang.spec
- cgmanifest.json
---
Upgrade msft-golang to version 1.20.11. I've utilized the same bootstrapping method we have in golang.spec. go 1.4 is used as the first stage bootstrap, as it compiles in C. go 1.4 is used to compile the most recent go version it can, which is go 1.19. The go 1.19 bootrap is capable of compiling the final version, go 1.20.11.
- Upgrade msft-golang to 1.20.11
**NO**
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=457018&view=results
- Manual install of package on `mcr.microsoft.com/cbl-mariner/base/core:2.0.20231115`
> msft-golang: upgrade 1.20.11

- toolkit/scripts/toolchain/container/Dockerfile
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
Remove toolchain references to patch files that were recently deleted, to resolve build break:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=458736&view=logs&j=db98f19e-da46-5e4d-a4ba-372cf3771a92&t=49710eeb-120d-5327-a9f7-33c000ddb429&l=439
```
+ cp -v /mnt/vss/_work/1/s/SPECS/cpio/cpio_extern_nocommon.patch ./container
cp: cannot stat '/mnt/vss/_work/1/s/SPECS/cpio/cpio_extern_nocommon.patch': No such file or directory
```
- Remove references to deleted patch files
**YES**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=458771&view=results
> 3.0 toolchain: remove references to deleted patches

- toolkit/tools/internal/pkggraph/pkggraph.go
- toolkit/tools/internal/pkggraph/pkggraph_test.go
---
In preparation for an implicit provides optimization PR (RFC/PoC: https://github.com/microsoft/CBL-Mariner/pull/6298), add a couple of functions to pkgraph:
- HasNode(): Returns true if a specific node object is present in a graph, the node must point to the same underlying object, equivalence is not sufficient.
- AllImplicitNodes(): Like the other `All*Nodes():` returns a list of all run/remote nodes in the graph that have `n.Implicit == true`
- AddGoalNodeToNodes(): Creates a goal node that links to arbitrary node objects in the graph rather than package versions.
- Add `HasNode()` `AllImplicitNodes()`  `AddGoalNodeToNodes()`
**NO**
- Local
> Add additional functions to pkggraph.go

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/boottype.go
- toolkit/tools/imagecustomizerapi/boottype_test.go
- toolkit/tools/imagecustomizerapi/config.go
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/disk.go
- toolkit/tools/imagecustomizerapi/disk_test.go
- toolkit/tools/imagecustomizerapi/filesystemtype.go
- toolkit/tools/imagecustomizerapi/mountidentifier.go
- toolkit/tools/imagecustomizerapi/partition.go
- toolkit/tools/imagecustomizerapi/partition_test.go
- toolkit/tools/imagecustomizerapi/partitionflag.go
- toolkit/tools/imagecustomizerapi/partitionsetting.go
- toolkit/tools/imagecustomizerapi/partitionsetting_test.go
- toolkit/tools/imagecustomizerapi/partitiontabletype.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/imagecustomizerapi/systemconfig_test.go
- toolkit/tools/internal/sliceutils/sliceutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
- toolkit/tools/pkg/imagecustomizerlib/imageConnection.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
---
This change implements the default/fallback logic for partition customization. This will be used when the partition layout changes are too complex for modifying the partitions directly.
The fallback logic creates the desired partition layout and then does a file copy from the base image to the new image. After that, some minor fix-ups are done (e.g. configuring the boot-loader).
The Image Customizer partition config schema mostly mirrors that of the new-image config. Some features were not included (e.g. dm-verity, encryption, overlays) to avoid making a large change even larger. In addition, a lot of additional config validity checks were added to try to limit it to only things …
> Image Customizer: Implement fallback partition customization.

- toolkit/docs/formats/imageconfig.md
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imagegen/configuration/kernelcommandline.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/roast/formats/targzip.go
---
Some projects need to build only a targzip or squashfs image format of rootFS using Mariner toolkit. The existing logic for SELinux labeling was not working for those cases because they are not building an ISO or VHD images that include different image partitions. 
Here are the changes that are introduced in this PR:
-	Factor out the SELinux labeling logic from !isRootFS {} condition block.
-	Allow overwriting the SELinux policy RPM package name through a parameter in image config json file. Currently it’s expecting the `selinux-policy` package, however some projects need their own policies. 
-	“—xattrs” option is added to tar command to capture the extended attributes as well. …
> Enable SELinux labelling for targzip rootFS image formats

- toolkit/tools/internal/timestamp/timestamp_mgr.go
- toolkit/tools/internal/timestamp/timestamp_test.go
---
- When we re-run build commands that has timestamp feature on, the timestamp log file for that specific program should be overwritten. This is not an issue most of the time, but it could error out if we try to read the timestamp file content and some unexpected data are present. Adding os.O_TRUNC flag when opening log file for the first time to make sure existing content is erased before we proceed with the program.
- Add os.O_TRUNC flag when beginning timestamp for a program.
**NO**
- Local build
> timestamp: overwrite timestamp logs on different builds

- SPECS/ocaml-ounit/fix-backtrace-parser.patch
- SPECS/ocaml-ounit/ocaml-ounit.spec
---
The package test for `ocaml-ounit` is failing due to a bug in parsing backtraces from ocaml>=4.11. This PR adds an upstream patch to fix this.
- Add upstream patch to fix backtrace parsing with ocaml>=4.11
**NO**
- Pipeline build id: [460973](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=460973&view=results)
> Fix backtrace parsing in ocaml-ounit

- SPECS/future/future.spec
---
The package tests for `future` invoke the `py.test-3.9` name, which doesn't exist on Mariner. I changed the test to invoke `py.test3.9`, which is present on Mariner. I also cleaned out a bit of Fedora cruft from the check section of the spec, but I don't aim to completely clean up the package in this PR.
Will create an action item to investigate the addition of a `py.test-3.9` symlink in the future, to make sure Mariner provides all common aliases.
- Invoke `pytest` properly in `future` package test
**NO**
- Pipeline build id: [460932](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=460932&view=results)
> Fix test runner invocation in future

- SPECS/openssl/openssl.spec
---
The upstream `openssl.spec` file uses a slightly different mechanism that our standard to specificy general compiler options. This change moves to our standard mechanism.
- Changed variable/macro names to reflect Azure Linux standard.
**YES**
- Builds Locally
- Pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=463070&view=results
> switch RPM_OPT_FLAGS for our more standard way of doing it

- SPECS/openssl/openssl.spec
---
The upstream `openssl.spec` decided whether to enabled `ktls` based on the architecture of the system. 
After confirming that `ktls` is approved security-wise, this change removes the architecture-specific decision and just uses the flag directly.
- Remove architecture-specific logic around `enable-ktls` and use the flag directly.
**YES**
- Builds Locally
- Pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=463860&view=results
> hard-code enable-ktls

- SPECS/llvm/llvm.spec
---
Fix `llvm 12.0.1` build break due to gcc 13 upgrade. Note that we plan to upgrade llvm to version 18, but for now this unblocks other package builds.
```
"/usr/src/mariner/BUILD/llvm-12.0.1.src/include/llvm/Support/Base64.h:29:5: error: 'uint32_t' was not declared in this scope"
```
The break is expected from the gcc 13 upgrade; see notes: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
```
Header dependency changes
Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without …
```
> llvm: fix build break due to <cstdint> header

- SPECS/openssl/openssl.spec
---
Initial merge of `openssl.spec` included some `BuildRequires` and `Requires` statements that were not needed and had them formatted counter to our standard. This removes spurious `*Requires` statements and organizes sorts them with one per line.
Note that it's not easy to actually tell what's required -- some things will simply be there. For example, even without the `BuildRequires: gcc`, the compiler was already in the `chroot` we use to build. I made a best attempt from reading docs and experimenting.
- Removed spurious `*Requires` statements.
- Separated them out into individual lines and sorted them
**YES**
- Built locally
- Pipeline: …
> removed unneeded requires and reformat them

- toolkit/tools/pkgworker/pkgworker.go
---
With running regular and test package builds separately we ended up copying the SRPM for the same package twice. There's no need to do that and in scenarios where we only run tests and skip building the RPMs, copying the SRPM to the output would give a false indication, that the RPMs were actually built. With that in mind, I update the logic to skip copying of SRPMs for test package builds.
- Updated the logic inside `pkgworker.go` to copy SRPMs only during regular (non-test) package builds.
No.
- PR check.
> Made only non-test package builds produce SRPMs.

- toolkit/scripts/get_config_deps.sh
- toolkit/scripts/imggen.mk
---
If config file lies outside the imageconfig/ directory, makefile is not able to find it, and errors out with '*** multiple target patterns. Stop'. This change modifies makefile to extract all .json and .sh filenames from config_name, fixes their paths relative to the makefile, and watches them to set imageconfigvalidator flag.
- Extract config directory for CONFIG_FILE into CONFIG_BASE_DIR
- Extract all filenames with .sh or .json type in CONFIG_FILE
- Fix paths to these files wrt the makefile using CONFIG_BASE_DIR
- Pass this list of paths to imageconfigvalidator flag to watch for changes
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/44648678
- Built image …
> toolkit image build: Fix make error for config files outside imageconfig directory

- toolkit/tools/internal/azureblobstorage/azureblobstorage.go
- toolkit/tools/internal/ccachemanager/ccachemanager.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/scheduler/scheduler.go
---
Naming tweak for the `ccachemanager` and `azureblobstorage` toolkit Go packages to align them with the naming convention of our other packages.
- `ccachemanagerpkg` -> `ccachemanager`,
- `azureblobstoragepkg` -> `azureblobstorage`.
No.
- #6954
- Local Go toolkit build and test.
> Aligned Go package names with other ones for `ccachemanager` and `azureblobstorage`.

- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Prior to filesystem-1.1-16, /media used to be a symlink to /run/media but this was
replaced with a directory. The RPM upgrade operation generally worked when the /media
symlink is a dangling link, which is commonly the case, however not always the case.
And when the /media symlink is indeed properly pointing to a real /run/media, RPM has a
known limitation where it is not possible to replace an active symlink with a directory,
and thus the RPM transation fails.
To workaround this, a %pretrans scriptlet must run to test and remove the symlink
before RPM attempts to install the new directory.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Directory_Replacement
Fixes: …
> fix: add scriptlet to workaround rpm transaction limitation to update /media symlink to directory

- SPECS/libgcrypt/libgcrypt.signatures.json
- SPECS/libgcrypt/libgcrypt.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade `libgcrypt` to version 1.10.3, which is the latest stable version. This resolves bug `48127839`
- Change `libgcrypt` to 1.10.3
**YES**
- [[FIPS] GPG in FIPS mode spits out useless "out of core handler ignored in FIPS mode" message on every execution](https://microsoft.visualstudio.com/OS/_workitems/edit/48127839)
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=466990&view=results
> [2.0] libgcrypt: upgrade to 1.10.3

- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
When the image's partitions are customized, then initrd file needs to refreshed so that the hardcoded partition UUIDs within the initrd file can be updated. The initrd file is refreshed by reinstalling the `initramfs` package. It is done this way because only the RPM post- install scripts within the `initramfs` package know how to properly refresh the initrd file.
- Image Customizer:
- Refresh initrd when partitions are customized.
- Check that we have RPM sources (when needed) during config validation.
NO
> Image Customizer: Refresh initrd when partitions are customized

- SPECS/clamav/clamav.spec
---
Clamav user disappeared from passwd and group file on package updates. This fixes the pre and postun scriptlet to add/delete the user depending on whether it's a package installation, update or removal.
- User would disappear from passwd and group files on package updates.
- Fixed pre and postun scriptlets to run based on input argument so that clamav user does not disappear on package update.  We now add user iff it's a package installation, and remove user iff it's a package removal. For package update, we neither add nor remove the user. Since we know that clamav doesn't have multiple packages by the same name which are 'parallel installable', this should work.
- …
> clamav: Fix resetting of user and group on package update

- toolkit/Makefile
---
The `$(build_arch)` variable may not be set when parsing the daily build arguments the first time, move `util.mk` higher up so it it sets these variables before we get to the daily build section.
Also, improve daily build URL to include the base repo URL so the `precacher` tool will work. Currently it can't locate the repodata.xml at the existing URL.
- Move `util.mk` higher in the `Makefile` so it sets `build_arch` sooner.
- Add the repo base URL for the daily builds in addition to the all build rpms sub-directory.
**NO**
- Local build with `sudo make build-packages QUICK_REBUILD_PACKAGES=y DAILY_BUILD_ID=3-0-20231214 PACKAGE_REBUILD_LIST=grub2`
> Fix $(build_arch) being unset in some use-cases for daily builds, support precacher

- SPECS/netplan/force-bringup-interface-no-ipadd.patch
- SPECS/netplan/netplan.spec
---
The PR address a bug raised by Nexus (https://dev.azure.com/mariner-org/ECF/_workitems/edit/6364) where in the newer mariner guest images for NAKS now no longer set network interfaces admin UP if they do not have an IP address assigned.   This resulted in the MACVLAN and IPVLAN network attachment types from working properly as the macvlan/ipvlan interface created and injected into the pod depend on the parent/base interface being UP.
This was a direct consequence of the version of netplan (0.95) included with this release of Mariner includes a bug that prevents the creation of .network files for interfaces without IP configuration:  [Bug #1763608 “Netplan ignores Interfaces …
> fix: Adding patch to netplan to force bring up devices with no IP addresses

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/safemount/safemount_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
---
The Image Customizer tool uses a tools from the host OS. (Unlike imager which uses the toolchain chroot for its tools.) This means that when calling tools like mkfs, the defaults options come from the host OS. So, if one has a host OS with a newer version of mkfs.ext4 (i.e. mke2fs), then ext4 can be formatted with options that aren't supported by Mariner's version of grub and/or kernel. This change explicitly sets the filesystem options.
- Image Customizer: Fix ext4 formatting
NO
> Image Customizer: Fix ext4 formatting

- SPECS/moby-cli/moby-cli.signatures.json
- SPECS/moby-cli/moby-cli.spec
- SPECS/moby-containerd/moby-containerd.signatures.json
- SPECS/moby-containerd/moby-containerd.spec
- SPECS/moby-engine/moby-engine.signatures.json
- SPECS/moby-engine/moby-engine.spec
- cgmanifest.json
---
Fix CVE-2020-8694, CVE-2020-8695 and CVE-2020-12912 in moby-engine and moby-containerd
As mentioned in Advisory: https://github.com/advisories/GHSA-jq35-85cj-fj4p
- Fix CVE-2020-8694, CVE-2020-8695 and CVE-2020-12912 
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2020-8694
- https://nvd.nist.gov/vuln/detail/CVE-2020-8695
- https://nvd.nist.gov/vuln/detail/CVE-2020-12912
- Pipeline build id: [469622](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=469622&view=results)
> Fix CVE-2020-8694, CVE-2020-8695 and CVE-2020-12912

- SPECS/sudo/disable-newgroup-query-when-netgroup-base-is-not-set.patch
- SPECS/sudo/sudo.spec
sudo backed by ldap is no longer working after moving to the new version of sudo. Patched the fix upstream to get ldap sudo to work with NETGROUP_QUERY
cherry-pick of a48d432a1102fb27c18961d7e594d82c2f345b74
> Sudo ldap netgroup_query bug fix patch

- toolkit/tools/imagecustomizer/docs/cli.md
- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizer/main.go
- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
Introducing an optional `--output-split-partitions-format` flag.
When specified, separate files for all partitions of the image will be created. Currently only supports raw and raw-zstd formats.
- Added flag in main.go for output-split-partitions-format
- Added conditional in imagecustomizer.go to handle case when output-split-partitions-format is provided.
- Added extractpartitions.go to imagecustomizerlib which handles partition extraction. 
- Reuses several functions from other internal libraries. 
- createRawFile is inspired from createRawArtifact in installutils.
- Formatted all files with `go fmt`.
- Updated test file function calls to match new function definition …
> Image Customizer: Support for partition extraction - raw, raw-zstd

- SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
Add CONF_GUEST Kata UVM build script variable
---
- Change
- Change
- Change
**NO**
- optional -->
Related:
https://github.com/microsoft/kata-containers/pull/125
> Add CONF_GUEST Kata UVM build script variable

- SPECS/mysql/CVE-2023-46218.patch
- SPECS/mysql/mysql.spec
The patch is actually for curl. Since mysql uses vendor version of curl we are fixing it in mysql
---
Patch CVE-2023-46218 mysql
- CVE-2023-46218
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-46218
-Unified buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=471924&view=results)
> Patch CVE-2023-46218 mysql

- toolkit/scripts/containerized-build/create_container_build.sh
---
Fixes an issue encountered when running `make -C <toolkit_dir_path> containerized-rpmbuild` from, say, the root of the cloned repo. Without this change, the affected `make` invocations seem to see the typical `make: Entering directory` output from `make` and can't correctly parse the printed variables.
Changes `create_container_build.sh`'s invocation of `make` to use `--no-print-directory`.
NO
Local build
> Fix for using make -C with containerized-rpmbuild

- SPECS/libtirpc/libtirpc.signatures.json
- SPECS/libtirpc/libtirpc.spec
- SPECS/nfs-utils/nfs-utils.signatures.json
- SPECS/nfs-utils/nfs-utils.spec
- cgmanifest.json
---
Upgrade nfs-utils to 2.6.4 and libtirpc to 1.3.4 
'nfs-utils' requires a newer version of 'libtirpc' due to an API change to struct rpc_gsss_sec. A good explanation can be seen on this email chain ([link](https://www.spinics.net/lists/linux-nfs/msg100712.html) )  :
```
> I would imagine distros would build matching
> libtirpc and nfs-utils that would either both not have the fix or have
> the fix.
I don't think distros work that way unless they are forced to.
There doesn't seem to be a reason why the nfs-utils change has
to break things -- we can do this without the ABI disruption.
The change to struct rpc_gss_sec can't remain. IMO both
f5b6e6fdb1e6 ("gss-api: expose gss …
```
> Upgrade nfs-utils to 2.6.4 and libtirpc to 1.3.4 

- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
- cgmanifest.json
…
---
update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870 (CP #7138)
- update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5868
- https://nvd.nist.gov/vuln/detail/CVE-2023-5869
- https://nvd.nist.gov/vuln/detail/CVE-2023-5870
- None,  CP #7138
> postgresql: update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870 (CP #7138)

- toolkit/imageconfigs/baremetal.json
- toolkit/imageconfigs/qemu-guest.json
Reverts microsoft/CBL-Mariner#6572
With the addition of customize partitions support through MIC, the image size increase is no longer needed. 
Users of the image can customize it using the MIC APIs.
> Revert "Increase image size for baremetal and qemu guest to 4GB"

- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
---
Resolves bug https://dev.azure.com/mariner-org/ECF/_workitems/edit/6500 where it was found that the copying of user ssh key paths did not work like additional files. This is because when copying additional files we join the baseConfigPath to the file path, but we did not follow this same practice for ssh key paths. This PR adds support for relative paths to SSH public key paths.
- Joined baseConfigPath to ssh key paths.
- If path is already absolute, no change is made.
**NO**
- Fixes https://dev.azure.com/mariner-org/ECF/_workitems/edit/6500
- Validated by testing in a local setup that repro'd the bug.
- Tested with no ssh key paths provided, as well as with. 
- Tested with …
> Image Customizer: Resolves bug with SSH public key paths - support for relative path

- toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
This is a port from the same fix in 3.0-dev #7188 
Fix logging issue when creating the worker chroot. It currently stops just before 50% instead of showing 100% completion, whenever the rpm database does not need to be rebuilt. 
Before:
```
Adding RPM to worker chroot 0%: filesystem-1.1-18.azl3.x86_64.rpm.
...
Adding RPM to worker chroot 49%: audit-libs-3.1.2-1.azl3.x86_64.rpm.
Current host 'RPM version 4.18.0' with rpm db 'sqlite', guest has 'RPM version 4.18.0' with rpm db 'sqlite'
The host rpm db 'sqlite' matches the guest. Not rebuilding the database.
```
After:
```
Adding RPM to worker chroot 0%: …
```
> toolkit: fix worker chroot progress [main]

- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
Bugfix - Skip Dracut Module and Mariner.cfg Update with no Verity Cfg.
---
Title says, skip Dracut module re-building and Mariner.cfg updating when users do NOT customize Verity related configs.
- Add an additional if statement checking for Verity field exists or not.
**NO**
- #xxxx
- Local
> Bugfix - Skip Dracut Module and Mariner.cfg Update with no Verity Cfg.

- toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
This resolves a bug wherein the rootfs partition was not able to be found for images with verity configured. We were using ImageConnection object to connect with the existing image which looks through all the partitions and finds their mountpoints. All we really need is the loopback device connected to the image so using safeloopback.Loopback object instead to connect to the image.
- Use safeloopback.Loopback instead of imageConnection
**NO**
- Fixes https://dev.azure.com/mariner-org/ECF/_workitems/edit/6534
- Locally with a config with verity
> Image Customizer: Use safeloopback.Loopback instead of ImageConnection for split partitions

- toolkit/tools/imagegen/installutils/installutils_test.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/packagerepo/repoutils/repoquery.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/internal/safechroot/safechroot_test.go
- toolkit/tools/internal/shell/shell.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageConnection.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go
- toolkit/tools/pkgworker/pkgworker.go
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
- toolkit/tools/validatechroot/validatechroot.go
---
Currently, the `safechroot.Chroot` class will auto-mount a bunch of the special directories (e.g. /dev, /proc, etc.). This is done (presumably) to permit more Linux utils to be runnable under the chroot.
However, when the image customizer tool is doing file-copy based partition customization, it has to make sure it avoids copying the contents of the special directories to avoiding messing up the host system. Currently, this is done by just explictly excluding the special directories from the copy operation. However, this can result in problems. For example, a directory not being created (e.g. /tmp) or a mount directory not receiving the correct extended attributes (e.g. SELinux). …
> Image Customizer: Fix special directories and partition customization.

- SPECS/elixir/elixir.spec
- SPECS/erlang/CVE-2023-48795.patch
- SPECS/erlang/erlang.spec
- SPECS/rabbitmq-server/rabbitmq-server.spec
Patching erlang package to fix CVE-2023-48795 (Terrapin vulnerability) https://github.com/erlang/otp/commit/ea595ed835e05653fd981e62ee3f60086a3c490c
---
To backport a patch to `erlang` that resolves CVE-2023-48795.
- Include patch to `erlang` to fix CVE-2023-48795
- Bump the release version of packages `elixir` and `rabbitmq-server` to consume new version of `erlang`.
**NO**
- Pipeline build id: [Unified-Buddy-Build-PR-7299](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=485583&view=results)
> Patch erlang for CVE-2023-48795

- toolkit/tools/imagecustomizer/docs/cli.md
- toolkit/tools/imagecustomizer/main.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
We want to allow user to extract just the partition files and not the image file itself. We also want the user to be able to extract the image and not partition files.
This change makes either one of the two flags, `--output-split-partitions-format` and `--output-image-format`, required to allow for this.
Previously, output image format was a required argument.
- Add conditionals to make either one of the flags required.
- Documentation updated.
**NO**
- Tested all cases locally: Neither flag mentioned. Output image format specified only. Output split partitions format specified only. Both specified.
Error example:
sudo go run ./imagecustomizer   --build-dir ./build …
> Image Customizer: Make either one of split partitions format and output image format required

- toolkit/tools/imagegen/diskutils/diskutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/safemount/safemount_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
---
When formatting a disk for Mariner, the default filesystem formatting options from the host are used. This can cause a problem if the host's default enables filesystem features not yet supported in Mariner (kernel or grub2). This change ensures that the enabled filesystem features are consistent across build hosts.
This fix was previously only done for the imagecustomizer tool under the incorrect belief that this bug didn't affect the imager tool. This change ensures that the fix is applied to imager as well.
- Imager: Ensure ext4 formatting is consistent across build hosts
NO
- Manually built and tested image.
> Imager: Ensure ext4 formatting is consistent across build hosts

- SPECS/openssl/0001-Replacing-deprecated-functions-with-NULL-or-highest.patch
- SPECS/openssl/openssl.spec
---
Apply a patch we had in `main` (for `openssl1.1.1k`) that returns `NULL` or a default when getting some methods that are turned off by default. There's a discussion of why this is necessary/desirable on the [openssl github](https://github.com/openssl/openssl/issues/7048).
- Copy patch file from `main` and update `openssl.spec`.
**YES**
- Builds locally
> take patch from main that relaces deprecated functions with a NULL or the latest version

- SPECS/cert-manager/CVE-2023-48795.patch
- SPECS/cert-manager/cert-manager.spec
---
Patches CVE-2023-48795 for the `cert-manager` package.
- Fixed up the patch file, based on [upstream](https://github.com/golang/crypto/commit/9d2ee975ef9fe627bf0a6f01c1f69e8ef1d4f05d).
- Changed `prep` stage in spec file to be able to handle multiple sources.
**NO**
- Builds locally
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486648&view=results
> apply patch for CVE-2023-48795

- SPECS/libdwarf/libdwarf.spec
---
The PR adds an epoch version to the package.
The versioning of the package has changed from date versioning to normal versioning in the last [upgrade](https://github.com/microsoft/CBL-Mariner/pull/6827).
version before upgrade: 20200114
version after upgrade: 0.9.0
Since the version after upgrade is numerically lower, package manager treats it as an older version and the CVEs on the earlier versions are being detected on the current version even though they're not applicable.
- Add Epoch to fix version ordering as date versioning had changed to normal versioning
**NO**
- #xxxx
- …
> Add epoch to libdwarf spec to fix versioning order

- SPECS/mariadb/fix_symlink_location_db_install.patch
- SPECS/mariadb/mariadb.spec
---
The post scripts for mariadb don't run due to missing script. As part of cmake install, mariadb-install-db script is removed. Adding patch to ensure script is correctly added to buildroot
```
Installing/Updating: mariadb-connector-c-config-3.1.10-6.cm2.noarch
Installing/Updating: mariadb-server-10.6.9-5.cm2.x86_64
/var/tmp/rpm-tmp.wjMLcK: line 3: mysql_install_db: command not found
```
- patch upstream mariadb to ensure scripts that RPM post scripts need to finalise the install, work as expected
**NO**
- Rebuilt package and confirmed
Rebuild mariadb package with CMake patch
```
INFO[0000][scheduler] Reading DOT graph from …
```
> Fix mariadb install post script

- SPECS/kernel/config
- SPECS/kernel/config_aarch64
- SPECS/kernel/kernel.signatures.json
- SPECS/kernel/kernel.spec
- toolkit/scripts/mariner-required-configs.json
.
---
Change the default Linux Security module to be SELinux. Previously, it was Apparmor. Note that both modules are still available
- Set SELinux as default LSM
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/47059310
- [Prep](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486483&view=results)
- [AMD Rpms](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486589&view=results)
- [AMD image](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486850&view=results)
- [ARM Rpms](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486636&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce …
> Set SELinux as default LSM

- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This change reverts the /etc/host.conf fix for issue https://github.com/microsoft/CBL-Mariner/issues/6925 which had an unintended impact on some container images built using this filesystem package. Running these containers within a K8s cluster started returning the IPv6 address for localhost instead of the prior behavior of an IPv4 address.
The "multi on" behavior for /etc/host.conf is desirable, but changing the default now is too risky.
- Revert the change in https://github.com/microsoft/CBL-Mariner/commit/070adde7a1d6925811439e0fb0a18648defa1c3e with a version bumped package to ensure it installs through package updates.
**YES**
- …
> Remove /etc/host.conf from filesystem

- SPECS/rdma-core/rdma-core.signatures.json
- SPECS/rdma-core/rdma-core.spec
- cgmanifest.json
---
- Upgrade to version 49.1 for AzL 3.0 release.
- Disable pyverbs as it cannot build with Cython > 3, the default for AzL 3.0. We don't have any packages that
depend on pyverbs, so this should be fine.
- New files present in v49.1 are packaged.
Note: The released source tarball (vs sources.tar.gz) is used, as that includes the prebuilt doc files. Without this the 
build will fail as AzLinux does not have pandoc.
**NO**
Buddy build -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489061&view=results
Local build
INFO[0069][scheduler] All packages built                           
INFO[0070][scheduler] --------------------------- …
> Upgrade rdma-core to v49.1

- SPECS/python-jinja2/CVE-2024-22195.patch
- SPECS/python-jinja2/python-jinja2.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix [CVE-2024-22195](https://nvd.nist.gov/vuln/detail/CVE-2024-22195) in python-jinja2 by backporting the [upstream patch](https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7).
- Backported patch to apply to version 3.0.3
- updated a `with_check` to work in a containerized build
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-22195
- Built locally in container
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489572&view=results
- Full Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=490014&view=results
> python-jinja2: add patch for CVE-2024-22195

- toolkit/tools/imagegen/installutils/installutils.go
---
fix a bug if condition to not skip processing sshkeys when sshkeypaths is empty
fix a bug if condition to not skip processing sshkeys when sshkeypaths is empty
NO
test emu invocation in trident in local dev, and in the log, key was copied into .ssh/authorized_keys, and i can ssh into the vm with the private key on my local machine
> OS modifier: fix a bug if condition to not skip processing sshkeys when sshkeypaths is empty

- SPECS/kata-containers-cc/kata-containers-cc.signatures.json
- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
---
With our upstream kata-containers fork being able to enforce a restrictive policy through a variable, this package change now transitions to enforcing a restrictive security policy for CC pods
- Enforce a restrictive policy for CC pods
**NO**
- Related microsoft/kata-containers PR: https://github.com/microsoft/kata-containers/pull/123
- Manual testing using a pre-release Kata-CC image with the package changes, and using pod YAMLS with and w/o policy annotations
> Kata-CC: Enforce a restrictive pod security policy

- SPECS/mysql/mysql.spec
---
The mysql package install does not add a user, add the mysql user as part of package install operations. This mimics the behaviour that the mariadb package also has.
- Add mysql user as part of mysql package install
**NO**
- #xxxx
- Built the package via tool chain
```
INFO[0000][scheduler] Reading DOT graph from /home/azaugg/CBL-Mariner/build/pkg_artifacts/preprocessed_graph.dot
INFO[0000][scheduler] Reading DOT graph from /home/azaugg/CBL-Mariner/build/pkg_artifacts/preprocessed_graph.dot
INFO[0000][scheduler] Successfully created solvable subgraph
INFO[0000][scheduler] Building 20 …
```
> Add Mysql user with package install

- toolkit/tools/downloader/downloader.go
- toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- toolkit/tools/internal/retry/retry.go
- toolkit/tools/precacher/precacher.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
Migrating #7373 to this PR as a hand-off from @reubeno.
We continue to intermittently see HTTP 502 errors (Bad Gateway) when TDNF downloads packages from packages.microsoft.com, usually in build pipelines. This PR introduces granular retry logic for that specific failure case. (We can't retry on any HTTP error, as 404 is an expected error that shows up in normal execution.)
- Update the `rpmrepcloner` to inspect stderr on TDNF download failure. If an error string indicating a 5XX error is found, then we retry with exponential backoff.
- Unified the retry logic for network downloads.
- Removed outdated logic from `rpmrepocloner` looking for errors related with the `toybox` …
> Specialcased 5XX errors during package downloads.

- SPECS/dracut/allow-liveos-overlay-no-user-confirmation-prompt.patch
- SPECS/dracut/dracut.spec
---
Update dracut to allow supressing user confirmation prompt when the liveos overlay is backed by memory.
Dracut allows the creation of a LiveOS using a read-only squashfs and an read-write overlay on top.
If the read-write overlay is backed by a ram-disk, Dracut halts booting and prompts the user to confirm
whether to continue or not.
This interaction during the boot process is not desired in all cases.
This change introduces a new flag (rd.live.overlay.nouserconfirmprompt) that when defined, it supresses
the prompt and allows the boot process to continue to completion without user interation.
There is no impact to existing configurations and their associated behavior. Only when …
> Update dracut to allow supressing user confirmation prompt when the liveos overlay is backed by memory.

- SPECS/mysql/mysql.spec
Missing shadow-utils packages caused nightly job to fail to missing binary used by rpm post scripts
---
Fix regression caused by(https://github.com/microsoft/CBL-Mariner/pull/7220)  adding user in postscript during mysql package install. Nightly build fails due to missing dependency package
- Explicitly call out shadow-utils package dependency that the mysql package now has
**NO**
- Will kick off a nightly build
> Add shadow-utils as a hard dependency for mysql package

- SPECS/application-gateway-kubernetes-ingress/CVE-2022-21698.patch
- SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `application-gateway-kubernetes-ingress`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
- Modified the [upstream patch](https://github.com/prometheus/client_golang/commit/9075cdf61646b5adf54d3ba77a0e4f6c65cb4fd7) to work with the older version of `client_golang` used by this package, along with getting rid of tests.
- Modified the spec file to do all the source-related munging in the `prep` stage.
**NO**
- Buddy Build: …
> patch CVE-2022-21698 in application-gateway-kubernetes-ingress

- SPECS/xdp-tools/xdp-tools.signatures.json
---
Fix [build break](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=494697&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667&l=2657) which seems to be from #7532 
```
ERRO[0015][srpmpacker] Signature validation for (/build/xdp-tools-1.4.1-2.azl3.src.rpm/SOURCES/xdp-tools-1.4.1.tar.gz) failed. 
Error: file (/build/xdp-tools-1.4.1-2.azl3.src.rpm/SOURCES/xdp-tools-1.4.1.tar.gz) has mismatching signature: 
expected (68e15d8e45ac56326e0b9a4afa8b49a3dfe8aba3488221d098c84698bca65b45) - 
actual (71c042899bdd1ed8a84cc038b0ced5b21febb47eb2f2ef85d2e2ef5a6a09c42d).
```
- Change xdp-tools …
> fix xdp-tools signature

- toolkit/imageconfigs/packagelists/core-packages-image.json
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
- toolkit/tools/imagegen/installutils/installutils.go
---
Mariner toolkit didn't have a capability to set a predefined list of users and groups when building a rootFS image type.
Given some packages also define some users or groups, there is a chance that the user/group is already defined if we do the use/group add after installing the packages in chroot.
This PR is related to https://github.com/microsoft/CBL-Mariner/pull/6876 change.
 
- Change toolkit to shift user/group creation earlier in image build for rootfs image types
**NO**
Manually tested with a derivative image and verified it works as expected.
- Pipeline build id: 482218
> Shift user/group creation earlier in image build for rootfs image types

- SPECS/systemd/systemd.spec
This is needed since currently the `systemd` and `polkit` packages cannot be installed together on a system.
Also `polkit` FTBFS because it is not packaging one of the built libs.
> systemd: do not conflict with polkit dir

- SPECS/moby-buildx/CVE-2022-21698.patch
- SPECS/moby-buildx/moby-buildx.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `moby-buildx`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495243&view=results
> fix cve-2022-21698 in moby-buildx

- SPECS/local-path-provisioner/CVE-2022-21698.patch
- SPECS/local-path-provisioner/local-path-provisioner.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `local-path-provisioner`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
- Modified the [upstream patch](https://github.com/prometheus/client_golang/commit/9075cdf61646b5adf54d3ba77a0e4f6c65cb4fd7) to work with the older version of `client_golang` used by this package, along with getting rid of tests.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495065&view=results
> fix cve-2022-21698 in local-path-provisioner

- SPECS/coredns/CVE-2023-44487.patch
- SPECS/coredns/coredns.signatures.json
- SPECS/coredns/coredns.spec
- Replace all uses of golang.org/x/net with version v0.17.0 in go.mod
---
`coredns` still has vendored code that is vulnerable to CVE-2023-44487 (`golang.org/x/net/http2`). The version requirement is coming from a 3rd order dependency (`github.com/openzipkin/zipkin-go v0.4.2` -> `github.com/IBM/sarama v1.40.1` -> `golang.org/x/net v0.12.0` for example). There were multiple conflicting requirements for the version of `net`, so a blanket module upgrade is used. (I'm hoping the `golang.org/x/net` module will generally be fairly stable and backwards compatible which may not be the case for the intermediate modules).
`IBM/sarama` does have a version that updates to use updated `x/net` …
> Fix coredns CVE-2023-44487 by patching vendor tar

- SPECS/mariner-release/mariner-release.spec
- SPECS/supermin/supermin-azurelinux.patch
- SPECS/supermin/supermin.spec
---
A mini version of PR #7545. This mainly changes the file provided by `mariner-release` package to be `azurelinux-release` and changes the `MARINER_BUILD_NUMBER` property of the file to be called `AZURELINUX_BUILD_NUMBER`
- changes the file provided by `mariner-release` package to be `azurelinux-release`
- changes the `MARINER_BUILD_NUMBER` property of the file to be called `AZURELINUX_BUILD_NUMBER`
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=496506&view=results
> Small rebranding of mariner-release file changes

- SPECS/open-vm-tools/open-vm-tools.signatures.json
- SPECS/open-vm-tools/open-vm-tools.spec
- cgmanifest.json
---
Upgrade open-vm-tools for 3.0
Upgrade open-vm-tools to 12.3.5
**NO**
** Building in buddy-build is continuously failing due to the missing package `xmlsec`. `xmlsec` is upgraded but it's not build and hosted in any repo. Building `xmlsec` and `open-vm-tools` also fails saying `nss` is missing. Building all three together fails with `nss` failing to build and other two are blocked. Ref: [pipeline](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495798&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=fbeef549-39ab-510c-faa3-78579a516b53)
Build building them locally with containerized build succeeds. Logs can be found below.
```
Checking …
```
> upgrade open-vm-tools to 12.3.5 for 3.0

- toolkit/tools/imagegen/installutils/installutils.go
---
When the `mariner-repos-shared` package is installed, the GPG keys for the Microsoft repos are installed. This can start some start GPG daemons, such as `gpg-agent` and `keyboxd`. The Imager tool already code to kill the `gpg-agent` process. This change ensures that `keyboxd` is also killed.
- Imager: Stop keyboxd
NO
- Manually built image.
> Imager: Stop keyboxd

- toolkit/scripts/toolkit.mk
---
Looks like we accidentally lest an extra double quote inside `toolkit.mk`. This is a small change fixing that.
- Removed the extra double quote in `--log-color="$(LOG_COLOR)""`.
No.
- Local test.
> Removed extra double quote in the toolkit.

- SPECS/node-problem-detector/CVE-2022-21698.patch
- SPECS/node-problem-detector/node-problem-detector.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `node-problem-detector`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499380&view=results
> fix cve-2022-21698 in node-problem-detector

- SPECS/sriov-network-device-plugin/sriov-network-device-plugin.signatures.json
- SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
- cgmanifest.json
> sriov-network-device-plugin: upgrade from 3.5.1 -> 3.6.2

- SPECS/nfs-utils/nfs-utils.spec
---
Installing nfs-utils creates a unnecessary group with a GID that is not generally standard for squash on NFS. 
- Create a nobody group as stated in the LSB
- Add the nobody group, so when installing nfs-utils we don't get a new group with a non expected GID
- nfs-utils generally should create the user nobody, not named
**YES**
- Build package filesystem
```
azaugg@azaugg-ld77 [ ~/CBL-Mariner/toolkit ]$ sudo make build-packages -j$(nproc) REBUILD_TOOLS=y SRPM_PACK_LIST="filesystem" PACKAGE_REBUILD_LIST="filesystem" REFRESH_WORKER_CHROOT=y RUN_CHECK=y
...
...
azaugg@azaugg-ld77 [ ~/CBL-Mariner/out/RPMS/x86_64 ]$ cp filesystem-1.1-18.cm2.x86_64.rpm /tmp/
azaugg@azaugg-ld77 [ /tmp ]$ …
```
> Fixing missing nobody user/group for nfs squash

- toolkit/imageconfigs/baremetal.json
- toolkit/imageconfigs/postinstallscripts/cleanup.sh
- toolkit/imageconfigs/qemu-guest.json
- toolkit/imageconfigs/scripts/cleanup.sh
Remove /srv linking that is created by the toolchain & filesystems package.  Toolkit and filesystem package unnecessarily symlink /var/srv & /srv which interferes with other scenarios. This will be fixed in Mariner 3.0, this PR is a mitigation for 2.0 images.
More details:
> ln -svfn var/srv %{buildroot}/srv
srv symlink created by the toolkit https://github.com/microsoft/CBL-Mariner/blob/4e4223205fdd0154713821430f2224290ff94a74/toolkit/scripts/toolchain/container/toolchain_initial_chroot_setup.sh#L41
The symlink is also created by  https://github.com/microsoft/CBL-Mariner/blob/4e4223205fdd0154713821430f2224290ff94a74/SPECS/filesystem/filesystem.spec#L63 
On any mariner image, the symlink is left behind which is interfering with scenarios where customers want to mount a volume over /srv
PR …
> Add cleanup script to base images 

- SPECS/python-virtualenv/pin-pytest-version.patch
- SPECS/python-virtualenv/python-virtualenv.spec
---
The python-virtualenv package pip installs pytest for the check section. The latest release of pytest (v8.0.0) contains a breaking change, treating use of certain deprecated parameters as errors. This caused failures in the python-virtualenv tests since it's an older version which predates the API changes to pytest. To fix the tests, this PR pins the pytest version to `<8`, ensuring we use a compatible version of pytest.
- Added patch to pin pytest version to `<8`
- Fixed check section macro
NO
- Local build
- Pipeline build id: [501105](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501105&view=results)
> Fix pytest version for python-virtualenv

- toolkit/tools/imagecustomizer/docs/cli.md
- toolkit/tools/imagecustomizer/main.go
- toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
---
Changes option for image customizer extract partitions format from raw-zstd to raw-zst to be more inline with the extension of the output produced.
- Change all instances of raw-zstd to raw-zst where needed.
**NO**
- Local run
> Image Customizer: change raw-zstd to raw-zst

- SPECS/prometheus-node-exporter/CVE-2022-21698.patch
- SPECS/prometheus-node-exporter/prometheus-node-exporter.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `prometheus-node-exporter`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501224&view=results
> fix cve-2022-21698 in prometheus-node-exporter

- SPECS/rook/CVE-2022-21698.patch
- SPECS/rook/rook.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `rook`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501233&view=results
> fix cve-2022-21698 in rook

- SPECS/dtc/dtc.signatures.json
- SPECS/dtc/dtc.spec
- cgmanifest.json
---
Dtc's latest version is 1.7.0. Therefore, update to this version. To support this version, set the SETUPTOOLS_SCM_PRETEND_VERSION to properly register the version and alter the logic to setting the root directory. Additionally, add check section according to [makefile](https://git.kernel.org/pub/scm/utils/dtc/dtc.git/tree/tests/Makefile.tests?h=v1.7.0#:~:text=check%3A%09tests%20%24%7BTESTS_BIN%7D%20%24(TESTS_PYLIBFDT)%0A%09cd%20%24(TESTS_PREFIX)%3B%20./run_tests.sh).
Note that the `SETUPTOOLS_SCM_PRETEND_VERSION ` is a workaround as desribed here: https://github.com/pypa/setuptools_scm/issues/357 but will not be needed in future versions thanks to dtc commit …
> Update dtc to 1.7.0

- SPECS/prometheus-process-exporter/CVE-2022-21698.patch
- SPECS/prometheus-process-exporter/prometheus-process-exporter.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `prometheus-process-exporter`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501225&view=results
> fix cve-2022-21698 in prometheus-process-exporter

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizer/docs/iso.md
- toolkit/tools/imagecustomizerapi/additionalfilesmap.go
- toolkit/tools/imagecustomizerapi/config.go
- toolkit/tools/imagecustomizerapi/iso.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/imagecustomizerapi/utils.go
- toolkit/tools/internal/safechroot/dummychroot.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
- toolkit/tools/pkg/isomakerlib/isomaker.go
---
Today, to add files to the LiveOS ISO image, the files need to be embedded within the LiveOS rootfs. This means MIC has to:
1. customize the rootfs
2. regenerate initrd
3. regenerate the squahfs
4. create the final LiveOS ISO.
In scenarios where the user wants to just replace/add files to the ISO, we can save so much time (30 secs out of 35 secs) if we can skip the steps 1-3 above. This can be done if the files are placed directly on the ISO file system.
This change allows the user to include arbitrary files unto the ISO media. It is introducing a new section for the iso configuration, and is re-using the `AdditionalFile` construct already in use unde the `SystemConfig`.
Note …
> Add support for additional files in mic generated isos.

- SPECS/node-problem-detector/CVE-2022-21698.patch
- SPECS/node-problem-detector/node-problem-detector.spec
Cherry-pick commit 0f52e8f7282e68c138b991afc38c070e88a3e9e4to main. Original PR: #7689
Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502202&view=results
> [CHERRYPICK FROM FASTTRACK/2.0] fix cve-2022-21698 in node-problem-detector (#7689)

- SPECS/nmi/nmi.signatures.json
- SPECS/nmi/nmi.spec
- cgmanifest.json
Cherry-pick commit 916f9d28c179456d7658fcae4a5eb1caec4b5022 to main. Original PR: #7681
Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502165&view=results
> [CHERRYPICK FROM FASTTRACK/2.0] fix cve-2022-21698 in nmi (#7681)

- docs.md
---
current link points to https://packages.microsoft.com/cbl-mariner which returns a 404 response
after the fix:
**NO**
> Update docs.md - fix Available Packages link

- SPECS/coredns/CVE-2023-44487.patch
---
Fixing a cherry-pick merge error from #7804.
- Removed merge artifacts from cherry-picking #7804 into `main`.
No.
- #7804
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=503621&view=results)
> Fixed merge leftovers in a `coredns` patch.

- SPECS/python-pycurl/python-pycurl.signatures.json
- SPECS/python-pycurl/python-pycurl.spec
- cgmanifest.json
Upgrade python-pycurl to version 7.45.2 for Mariner 3.0 together with its signatures.json and change in cgmanifest files. Tests have been disabled until python 3.11 support makes into the mainline.
---
This PR upgrades python-pycurl to version 7.45.2 for Mariner 3.0.
- Upgrade python-pycurl to version 7.45.2
- No other packages impacted
- No previous CVEs
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=503872&view=results
> Upgrade python-pycurl to version 7.45.2 for Mariner 3.0

- SPECS/moby-buildx/CVE-2021-44716.patch
- SPECS/moby-buildx/moby-buildx.spec
---
Added a patch to the vendored module of moby-buildx to address CVE-2021-44716
- Address CVE-2021-44716 by patching vendored golang.org/x/net
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504394&view=results
> Patch golang related module in moby-buildx  for CVE-2021-44716

- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
Backport of #7764 to properly display failing ptests in the build summary.
- Backported #7764.
No.
- #7764
- Local runs.
> Split failing and passing tests in the summary. (#7764)

- .pipelines/containerSourceData/Dockerfile-Initial
- SPECS/fontpackages/dnf.patch
- SPECS/fontpackages/fontpackages.spec
- toolkit/scripts/containerized-build/resources/setup_functions.sh
- toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
---
PR #7715 upgrades `createrepo_c` package from version `0.17.5` to `1.0.3` which introduces breaking changes to how `createrepo` command creates metadata files, their format changes entirely which makes `tdnf` unable to read it properly. However if run with `--compatibility` flag, it will preserve the format as much as it can and thus `tdnf` can use the created metadata files for the repo. This PR adds such flags to all of our `createrepo` commands used so that we can upgrade the package. This flag does not change behavior of the command in our current version of the package, so it won't break anything in adding this now.
- Added `--compatibility` flag to all `creatrepo` commands …
> Add compatibility flag to all createrepo commands

- toolkit/tools/internal/exe/exe.go
- toolkit/tools/internal/exe/exe_test.go
---
For build parameters like `SRPM_PACK_LIST` we take a space-separated list, like `SRPM_PACK_LIST="openssl SymCrypt"`. Currently, the code that parses those into an array of packages doesn't handle multiple spaces between the package names. For example, if you add an extra space between the package names, like `"openssl  SymCrypt"`, it will parse it into three packages: "`openssl`", "``", and "`SymCrypt`" -- note the empty package name. This makes our build tools fail down the line, as they try to handle an empty package name.
- Updated the list parsing code to handle multiple spaces/whitespace between package names.
- Added tests.
**YES**
- fixes #7895
- Full …
> use strings.Fields to handle whitespace between items in list

- SPECS/cloud-init/ci-Pin-pytest-8.0.0.patch
- SPECS/cloud-init/cloud-init.spec
---
Latest pytest 8.0.0 release had breaking changes which broke the cloud-init tests. Pin to previous versions of pytest.
See https://github.com/canonical/cloud-init/commit/7c96c9cd9318e816ce4564b58a2c98271363c447
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/48917787
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502644&view=results
- `cloud-init` tests are now passing (results from same build as above) - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502644&view=ms.vss-test-web.build-test-results-tab
> tests: pin cloud-init's pytest to <8.0.0

- SPECS/cri-tools/CVE-2024-21626.patch
- SPECS/cri-tools/cri-tools.spec
- SPECS/kubernetes/CVE-2024-21626.patch
- SPECS/kubernetes/kubernetes.spec
- SPECS/kubevirt/CVE-2024-21626.patch
- SPECS/kubevirt/kubevirt.spec
---
Fix CVE-2024-21626 by patching venodred runc in kubernetes, kubevirt, and cri-tools
- Change:  Add patch to mitigate CVE-2024-21626.
- Change: Patch imported for cri-tools from [3245240](https://github.com/kubernetes-sigs/cri-tools/commit/32452408ae7697d7dcd3da90ef4eebb922b2bf63)
- Change: Patch imported for kubevirt from [22dfc39](https://github.com/kubevirt/kubevirt/commit/22dfc39b5f6a1b16e05875412000a7b7b98d22e6)
- Change: Patch imported for kubernetes from [2dd8156](https://github.com/kubernetes/kubernetes/commit/2dd81563a9629f9f88fa3d52f5be3c4a24e6ace8)
**YES/NO**
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-21626
- Pipeline …
> Fix CVE-2024-21626 by patching vendored runc in kubernetes, kubevirt, cri-tools

- SPECS/systemd/systemd.spec
---
Especially during image builds it is possible for `systemd-bootstrap` to be installed, and then for a follow on install step to install `systemd` itself. Until we can update the tools to discard the bootstrap packages we need to allow the real `systemd` package to gracefully replace the bootstrap versions. This behavior is seen most often with `systemd-bootstrap-rpm-macros` since many packages will reference them, and they are needed as part of the core toolchain build.
- Add `%{?azure:Obsoletes:      systemd-bootstrap-... <= %{version}-%{release}}` entries for each subpackage found in `systemd-bootstrap.spec`
**NO** (This change only affects the main systemd which comes later)
- …
> Re-add systemd-bootstrap obsoletes to systemd

- SPECS/xfsprogs/xfsprogs.signatures.json
- SPECS/xfsprogs/xfsprogs.spec
- cgmanifest.json
Upgrade xfsprogs to latest stable release, 6.6.0. This version moves the scrub cron job to the data dir. Additionally, the check section was using a make target which doesn't exist and then would report as passing. Therefore, remove misleading check section.
---
Upgrade xfsprogs to latest stable release, 6.6.0. This version moves the scrub cron job to the data dir [[3d37d8bf535fd6a8ab241a86433b449152746e6a](https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/commit/?h=v6.6.0&id=3d37d8bf535fd6a8ab241a86433b449152746e6a)]. 
Additionally, the check section was using a make target which doesn't exist and then would report as passing. Therefore, remove misleading check section. Based …
> Upgrade xfsprogs to 6.6.0

- SPECS/kata-containers-cc/kata-containers-cc.signatures.json
- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers/0001-Append-systemd-kernel-cmdline-params-for-initrd.patch
- SPECS/kata-containers/0001-Merged-PR-9607-Allow-10-seconds-for-VM-creation-star.patch
- SPECS/kata-containers/0001-osbuilder-Add-support-for-CBL-Mariner.patch
- SPECS/kata-containers/0002-Merged-PR-9671-Wait-for-a-possibly-slow-Guest.patch
- SPECS/kata-containers/0003-Merged-PR-9805-Add-support-for-MSHV.patch
- SPECS/kata-containers/0004-Merged-PR-9806-Fix-enable_debug-for-hypervisor.clh.patch
- SPECS/kata-containers/0005-Merged-PR-9956-shim-avoid-memory-hotplug-timeout.patch
- SPECS/kata-containers/drop-mut-for-variables-that-are-not-mutated.patch
- SPECS/kata-containers/kata-containers.signatures.json
- SPECS/kata-containers/kata-containers.spec
- SPECS/kata-containers/runtime-reduce-uvm-high-mem-footprint.patch
- cgmanifest.json
---
This reverts commit 8acb776cef55386473a5d1bdf6eed0edbf7d30ec.
This commit breaks build break for aarch64 because of dependent virtiofsd package.
- Revert commit 8acb776cef55386473a5d1bdf6eed0edbf7d30ec
NO
- #xxxx
> Revert "Kata: Release v3.2.0.azl0 for both vanilla and CC based on aligned sources (#6942)"

- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/WALinuxAgent/add_firewall_rules.patch
---
Add EnableFirewall flag to waagent.conf to protect access to Azure host node services.
- Patch waagent.conf to add firewall rules to protect access to Azure host node
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=494151&view=results
> Patch waagent.conf to add firewall rules

- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
---
For the grub.cfg being used by the MIC generated ISOs:
- Sync'ed grub.cfg template with Mariner's (use of bootprefix, kernel arguments).
- Re-enabled SELinux.
- Moved the kernel extra parameters to be at the end so users can override defaults.
- [[MIC ISO] Update default liveos iso grub.cfg to match Mariner's default.](https://github.com/microsoft/CBL-Mariner/commit/226b1b6685654685d451c3a8d74ce8923b84556b)
**NO**
- n/a
- n/a
- Built and deployed locally.
> [MIC ISO] Update default liveos iso grub.cfg to match Mariner's default.

- toolkit/tools/imager/imager.go
- toolkit/tools/internal/file/file.go
- toolkit/tools/internal/rpm/rpm.go
- toolkit/tools/internal/safechroot/safechroot.go
---
Pass error instead of logging in go utility code
- Remove error logging from go utility code
- Construct new error with message and error and return that to caller
- Log error in caller if missing
**NO**
- Successful full pipeline build id: [506062](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=506062&view=results)
> go-tool: pass error instead of logging utility files

- toolkit/tools/imagegen/installutils/installutils.go
---
The `systemd` package now includes a dummy `/etc/machine-id` file. Previously the installer tools were responsible for creating this file. Update the tools to only create the file if it is missing.
- Make `addMachineID()` skip if `/etc/machine-id` is already present.
**NO**
- Local  build of tools
- core-efi build in progress
> Skip machine-id if already present

- toolkit/tools/imagegen/installutils/installutils.go
---
There is a bug in the `installutils.ProvisionUserSSHCerts` function where it incorrectly skips processing SSH keys if the `sshPubKeyPaths` is empty but `sshPubKeys` is not.
- Cherry-pick: Do not skip processing sshkeys when sshkeypaths is empty
NO
- Manually run image customizer tool.
> Cherry-pick: Do not skip processing sshkeys when sshkeypaths is empty

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
---
Allow absolute paths for the `AdditionalFiles`, `PasswordPath`, `SSHPubKeyPaths`, and package list files.
- Image Customizer: Support abs paths
NO
- Manually run image customizer.
> Image Customizer: Support abs paths

- SPECS/core-packages/core-packages.spec
- SPECS/distroless-packages/distroless-packages.spec
- SPECS/openssl/openssl.spec
---
Add `SymCrypt` and `SymCrypt-openssl` as `Recommends` packages for `openssl` and add them to images with `openssl`.
In AZL 3 `openssl` relies on `SymCrypt` for `FIPS` mode. As such, we want `SymCrypt` and the related `SymCrypt-openssl` packages installed where `openssl` is installed. To accomplish this, we do two things:
1. Add these packages as `Recommends` in the `openssl` spec. This means that if the package manager can find these packages, it will install them when `openssl` is installed, but it won't refuse to install `openssl` if it can't find them.
2. Add these packages to any image that has `openssl`.
One may wonder why we didn't simply add these packages as `Requires` to …
> Add SymCrypt and SymCrypt-openssl to images with openssl

- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
https://github.com/microsoft/CBL-Mariner/pull/7928/files#diff-642be5aa16a8fe207d6d360bb91652eeab7c7164cd2d6670f1d8ace078869282R200 Calls the wrong function, the actual build is likely running so we need to call the test node variant.
- Fix `testNodesToRequests()` to use `IsSRPMTestActive()` instead of `IsSRPMBuildActive()`.
**NO**
- Local Build
> Fix call to IsSRPMTestActive in new multi build fix

- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
---
There is a missing `err` check in the `findRootfsPartitionFromEsp` function. This can result in normal errors instead resulting in process crashes.
- Image Customizer: Add missing err check
NO
> Image Customizer: Add missing err check

- toolkit/scripts/containerized-build/resources/mariner.Dockerfile
- toolkit/scripts/containerized-build/resources/setup_functions.sh
Fix errors in the `containerized-rpmbuild` environment for 3.0 when using helper functions that call `tdnf`.
---
In the `containerized-rpmbuild` environment, we have an alias for `tdnf` that adds a `--releasever` flag in all cases and for `3.0` builds adds some flags to fix up what repo we will go to. However, as currently implemented the extra flags for `3.0` are added after sourcing `setup_functions.sh`. Because aliases are expanded when functions are read, not when they are executed, this means that any function from `setup_functions.sh` (like `install_dependencies`) will have the wrong flags. This results in seeing a failure, though oddly the packages still get installed.
To fix …
> fix error when using tdnf inside of functions from setup_functions.sh

- SPECS/core-packages/core-packages.spec
- SPECS/distroless-packages/distroless-packages.spec
- SPECS/openssl/openssl.spec
---
Change #7977 broke `core-packages` due to a typo.
**YES**
> Revert "Add SymCrypt and SymCrypt-openssl to images with openssl (#7977)

- SPECS/moby-containerd-cc/fix_cc_tests_for_golang1.21.patch
- SPECS/moby-containerd-cc/moby-containerd-cc.spec
- SPECS/moby-containerd/fix_tests_for_golang1.21.patch
- SPECS/moby-containerd/moby-containerd.spec
---
After upgrading to golang 1.21 containerd tests started failing. This is a known issue upstream and they have a fix that inlines the offending functions. This change backports those fixes into our current versions of containerd.
- Backport containerd upstream patches to fix tests when built with golang 1.21
**NO**
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510660&view=results
> moby-containerd: fix test compatibility with golang 1.21

- SPECS/golang/golang.spec
---
Include go.env in GOROOT which is now the default value from where GOPROXY value is read
Cherry-Pick of: #8004
- Include `go.env` in GOROOT
**NO**
- https://github.com/golang/go/issues/61928
- NA
- Pipeline build id: [PR-8021](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510749&view=results)
/cc @dagood
> golang: include go.env in GOROOT

- toolkit/tools/imagecustomizer/README.md
- toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
- toolkit/tools/imagecustomizer/container/build-mic-container.sh
- toolkit/tools/imagecustomizer/container/run-mic-container.sh
- toolkit/tools/internal/buildpipeline/buildpipeline.go
---
It is desired for some MIC users to run MIC from within a container. This change enables that scenario by:
- updating MIC dependencies to work within a container.
- buildpipeline.go: has code to assume that if run from a container, it's a CDPX/OneBranch build with a pool of Chroot to re-use. However, for user scenarios that does not apply. To avoid breaking backward compatibility, we are defining a new file within the container (`./mariner-toolkit-ignore-dockerenv`). If this file is present, it will allow the buildpipeline.go to behave as usual. Then, in our MIC container, we include that file.
- adding bash scripts/docker file to show how to build and launch the container.
- …
> [MIC] Enable MIC to run in a container.

- SPECS/python-sphinxcontrib-applehelp/python-sphinxcontrib-applehelp.spec
- SPECS/python-sphinxcontrib-devhelp/python-sphinxcontrib-devhelp.spec
- SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.spec
- SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.spec
- SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.spec
- SPECS/python-sphinxcontrib-serializinghtml/python-sphinxcontrib-serializinghtml.spec
- SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
---
In the sphinxcontrib package specs, some places the hyphenated form such as sphinxcontrib-applehelp and other places the underscore form e.g. sphinxcontrib_applehelp is used. Enhancing the variable naming to add pypi_name_underscore to improve generalization / usage of variables.
- Updated 7 sphinxcontrib packages to have the new variable naming format.
- Note: did not update changelog or bump release since this is ahead of the Mariner 3.0 release and does not affect the inner workings of the spec in any meaningful way.
- Installing packages in jsmath check section for tests to run successfully.
**NO**
- Locally built / tested successfully
Note: websupport tests fail, but a …
> sphinxcontrib: variable naming enhancement to sphinxcontrib packages

- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
---
When SELinux is enabled, the LiveOS ISO does not boot. We need to investigate the root cause and fix it. However, for the time being, MIC will disable SELinux for generated ISOs until the fix is available. That way, at least, users can generate ISOs.
To track the correct fix, we have: [[MIC ISO] Enable SELinux in MIC generated ISOs](https://dev.azure.com/mariner-org/ECF/_workitems/edit/6959)
- [[MIC ISO] Disable selinux by default temporarily.](https://github.com/microsoft/CBL-Mariner/commit/22dace1777b34e7a06622075a80167d23c8430e8)
**NO**
- [[MIC ISO] Temporarily disable SELinux in MIC generated ISO to allow successful booting](https://dev.azure.com/mariner-org/ECF/_workitems/edi …
> [MIC ISO] Disable selinux by default temporarily.

- toolkit/resources/assets/meta-user-data/meta-data
This purely a rebranding change in a sample resource file.
> Replace the mariner-vm default localhost name with azurelinux-vm

- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/printresults.go
---
My changes in #7764 introduced a bug, which caused ptest failures to fail the whole build. The intended behaviour is for the test failures to be reported in the summary but the package build itself succeed.
The change keeps failing ptests reported as failures but the test nodes themselves are still marked as available, so the top goal node depending on them can unblocked and thus mark the whole build as finished.
- Made test failures not fail the package build.
No.
- #7764
- Local test build.
- [Buddy build of a package with a known failing test](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=515381&view=results).
> Made test failures not fail the package build.

- toolkit/scripts/containerized-build/resources/setup_functions.sh
Make `install_dependencies` function in the `containerized-rpmbuild` environment work on more complex `Requires` statements.
---
`install_dependencies` in the `containerized_rpmbuild` environment was initially done as a quick script to install multiple dependencies in spec files. This change makes it more robust to handle some cases it wouldn't handle. Notably:
- Dependencies with special characters in their names like `Perl(Digest::SHA)`
- Dependencies with macros in them like `%{name}-libs`
- Dependencies with version specifications
- Make `install_dependencies` use `rpmspec` to parse `Requires` statements in a spec file.
- Install all packages for a given spec at one time.
**YES** …
> make install_dependencies more reslient to weirdness in different spec files

- SPECS/libnotify/disable-gtk.patch
- SPECS/libnotify/libnotify.signatures.json
- SPECS/libnotify/libnotify.spec
- cgmanifest.json
---
Upgrade libnotify from 0.7.9 to 0.8.3 for Mariner 3.0
- Upgrade to 0.8.3
- Update patch to use meson options to disable tests and gtk_doc
- Remove build dependency on gtk-doc
**YES**
- #xxxx
- local build
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=515489&view=results
> Upgrade libnotify from 0.7.9 to 0.8.3

- .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
- .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> updates containers source for marinara updates

- toolkit/scripts/spec_source_attributions.py
For new packages in 3.0, the changelog entry where we mention the source of the spec file should be allowed to contain either CBL-Mariner or Azure Linux. Updating the regex in spec file check to use that logic.
> Allow both CBL-Mariner and Azure Linux in spec source changelog entry

- SPECS/systemd-bootstrap/macros.sysusers
- SPECS/systemd-bootstrap/systemd-bootstrap.signatures.json
- SPECS/systemd-bootstrap/systemd-bootstrap.spec
- SPECS/systemd-bootstrap/sysusers.attr
- SPECS/systemd-bootstrap/sysusers.generate-pre.sh
- SPECS/systemd-bootstrap/sysusers.prov
- SPECS/systemd-bootstrap/use-255-macros.patch
- SPECS/systemd/systemd.signatures.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
There is currently no quick path to upgrading systemd-bootstrap, but we need to align to the macros in the new systemd-255. Packages that use macros like `%systemd_requires` or `%systemd_post` use them statically, i.e., the macros are evaluated at `rpmbuild` time and encoded into the `.rpm`. This means that any package using `systemd-bootstrap-rpm-macros` to build would be left using outdated macros.
Until we can get `systemd-bootstrap` aligned with `systemd` we should at least make sure the macros and associated components are updated to match.
- Port systemd-255's macros to systemd-250
**YES**
- Local builds
- Full build: …
> Use systemd-255 macros in systemd-bootstrap

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/internal/resources/assets/grub2/grub.cfg
- toolkit/tools/internal/resources/resources.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
---
The Image Customizer tool needs the ability to customize Mariner 2.0 images. This includes needing the ability to reset the bootloader configuration (e.g. when the partition layout is changed). However, in a previous change (#7618) the legacy grub.cfg file was removed from the toolkit since it is no longer being used in Mariner 3.0. This change restores this file but only for the Image Customizer tool.
- Image Customizer: Restore legacy grub.cfg file.
NO
> Image Customizer: Restore legacy grub.cfg file.

- SPECS/rsyslog/rsyslog.spec
---
Currently rsyslog has a strict dependency on net-snmp-libs which in-turn requires Perl. This is the only consumer of Perl in our standard Azure VM image and removing the dependency will remove the need for over 180 packages in the image.
The rsyslog snmp capabilities will still be available by installing the rsyslog-netsnmp and rsyslog-mmsnmptrapd subpackages.
- Add rsyslog-netsnmp and rsyslog-mmsnmptrapd subpackages to remove strict rsyslog dependency on Perl.
**NO**
> rsyslog: move snmp capabilities into subpackage

- SPECS/gobject-introspection/gobject-introspection.signatures.json
- SPECS/gobject-introspection/gobject-introspection.spec
- SPECS/gobject-introspection/testWorkaround.patch
- SPECS/meson/meson.signatures.json
- SPECS/meson/meson.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
gobject-introspection: upgrade 1.71.0->1.78.1; meson: upgrade 1.2.1->1.31
- gobject-introspection: upgrade 1.71.0->1.78.1
- Added patch to fix gobject test for 78 version
- meson: upgrade 1.2.1->1.31
- Skipped some meson tests cause of flakiness
**YES**
- Buddy build id: [517708](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517708&view=results)
- Full build: [516777](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=516777&view=results)
- Full build BuildRpms ARM64: [517468](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517468&view=results)
- Full build BuildRpms AMD64: …
> gobject-introspection: upgrade 1.71.0->1.78.1; meson: upgrade 1.2.1->1.3.1

- toolkit/tools/internal/file/file.go
- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
---
When writing out embedded resources to file, if the destination file already exists, then the resulting file will be an amalgamation of the two files because the `open` call is missing the truncate flag.
- Image Customizer: Fix grub.cfg corruption.
NO
- Manually testing image customizer tool.
> Image Customizer: Fix grub.cfg corruption.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
---
When the /etc/fstab file is being written, the order in which it is written is determined by the hash function used by the map type. Since, the hash function is randomized (for security), this means the ordering of the fstab file changes every time.
This change ensures the fstab file is written in the correct order.
- Write fstab file in correct order.
NO
- Manually ran image build.
> Write fstab file in correct order.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/safemount/safemount.go
---
When labelling SELinux volumes, we use bind mounts to ensure that the entire volume is correctly labeled, including directories that are being used for nested mounts. However, when labelling multiple volumes, the root directory used for the bind mount targets isn't emptied.
- Fix failure when SELinux labelling image with multiple partitions.
NO
> Fix failure when SELinux labelling image with multiple partitions.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imager/imager.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
---
Backporting #8217 to 2.0.
- Cherry-pick: Write fstab file in correct order. (#8217)
NO
- Manually ran imager tool.
> Cherry-pick: Write fstab file in correct order. (#8217)

- toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
---
Fix up some of the errors in `getFilesystemSizeInSectors()` to help make the function easier to debug.
- Image Customizer: Improve/fix errors in getFilesystemSizeInSectors().
NO
> Image Customizer: Improve/fix errors in getFilesystemSizeInSectors().

- SPECS/kernel-headers/kernel-headers.spec
- SPECS/libselinux/libselinux.spec
---
fix libselinux and kernel-headers spec issues
The bogus changelog date in kernel-headers causes:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=519508&view=logs&j=db98f19e-da46-5e4d-a4ba-372cf3771a92&t=8831c5ce-9476-5d69-9bf5-bfd7485723f1&l=226074
```
++ rpmspec -q /mnt/vss/_work/1/s/SPECS/kernel-headers/kernel-headers.spec --srpm -D 'with_check 0' -D '_sourcedir /mnt/vss/_work/1/s/SPECS/kernel-headers' -D 'dist .azl3' --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.src.rpm' 
error: %changelog not in descending chronological order
```
The BR from a toolchain package (libselinux) to a non-toolchain package …
> fix libselinux and kernel-headers spec issues

- SPECS/leveldb/leveldb.spec
- SPECS/libcgroup/libcgroup.spec
---
Fix build breaks in libcgroup and leveldb by using C++ 14 standard
Errors seen in nightly builds:
leveldb-1.23-3.azl3.src.rpm
```
"/usr/include/gtest/internal/gtest-port.h:279:2: error: #error C++ versions less than C++14 are not supported."
```
libcgroup-3.1.0-1.azl3.src.rpm.log
```
"/usr/include/gtest/internal/gtest-port.h:279:2: error: #error C++ versions less than C++14 are not supported."
```
- Fix build breaks in libcgroup and leveldb by using C++14 standard
**NO**
- Local build
- leveldb buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=520352&view=results
- libcgroup buddy build: (unable to run …
> fix libcgroup and leveldb

- toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/consume-space.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/consume-space.sh
---
When shrinking partitions, the image customizer tool gets confused when the `resize2fs -M` reports that the filesystem is already at its minimum size. This change fixes this.
In addition, some of the logging for shrinking filesystems is improved.
- Image Customizer: Fix for when shrinking filesystem is NOP.
NO
- Manually testing image customizer tool.
> Image Customizer: Fix for when shrinking filesystem is NOP.

- SPECS/ndctl/ndctl.spec
---
Package started failing in nightly build (https://dev.azure.com/mariner-org/mariner/_build/results?buildId=520496&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667), despite passing when I upgraded it in https://github.com/microsoft/azurelinux/pull/7576. I'm not sure yet what changed, but the build was failing due to not being able to find systemd
Adding `BuildRequires: systemd` fixes the issue
- ndctl
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=520905&view=results [Pass]
> ndctl: update buildRequires

- SPECS/kernel-uvm/kernel-uvm.spec
---
A check that runs make oldconfig against the kernel config present as a source fails. The check expects make oldconfig to not alter the supplied config. With new toolchains being used, this check fails, example:
`
time="2024-03-05T11:45:18Z" level=debug msg="-CONFIG_GCC_VERSION=130200"
time="2024-03-05T11:45:18Z" level=debug msg="+CONFIG_GCC_VERSION=110200"
`
This check was set in place by the Kata team to ensure the LSG-supplied kernel configs have been properly generated.
We disable this check for 3.0 and once the UVM kernel is being made use of, we will revisit supplying a properly pre-generated configuration.
- Removes a check prior to building whether the kernel config has …
> kernel-uvm: Disable failing config check (due to toolchain upgrade)

- SPECS/kata-containers-cc/kata-containers-cc.spec
---
The kernel-uvm-cvm package was already removed on 2.0, but not for 3.0-dev. This PR drops references to kernel-uvm-cvm from kata-containers-cc in preparation for deprecation, similar to https://github.com/microsoft/azurelinux/pull/7455 
**Note:** This is likely a temporary PR. The package should be updated in 3.0 the proper way, following the proper history as present in 2.0. When porting all our latest Kata package changes from 2.0 into 3.0, we will likely revert this PR and apply proper commit history on top of the packages.
- remove references to kernel-uvm-cvm in kata-containers-cc
NO
> kata-containers-cc: Remove references to kernel-uvm-cvm from kata-containers-cc

- toolkit/imageconfigs/scripts/cleanup.sh
---
A previous PR added log directory clean-up to the clean-up script. However, that leads to services like `auditd` failing due to missing directories and incorrect selinux labeling even if the directories are created later.
**NO**
Tested locally.
> revert cleaning up log directories for base image

- SPECS/openmpi/openmpi.spec
---
Fix build issue with `openmpi` by reverting previous change made to this package in PR #6949 
It appears that other packaging changes result in the `libOpenIPMIglib.so` library no longer building.
Fix for:
```
"RPM build errors:"
"    File not found: /usr/src/azl/BUILDROOT/openmpi-4.1.5-2.azl3.x86_64/usr/lib/libOpenIPMIglib.so*"
```
- Change openmpi to remove `libOpenIPMIglib.so` file
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=521497&view=results
> revert openmpi changes

- toolkit/tools/imagegen/installutils/installutils.go
---
In a previous change (#7618), the template for the EFI grub.cfg file was changed slightly so that the "grub2" directory was appended by the Go code instead of being included in the template file. However, this change accidentally broke images that use a separate boot partition due to a missing "/" in the path.
- Fix grub.cfg file when there is a separate boot partition.
NO
> Fix grub.cfg file when there is a separate boot partition.

- SPECS/libvirt-python/libvirt-python.signatures.json
- SPECS/libvirt-python/libvirt-python.spec
- SPECS/mdevctl/mdevctl.spec
- cgmanifest.json
libvirt-python is a runtime dependency for libvirt
mdevctl is a dependency for libvirt that currently only builds for x86_64
---
- Update libvirt-python version and signature
- Add iniconfig install for libvirt-python check
- Remove mdevctl ExclusiveArch
**NO**
- [only arm qemu is stopping libvirt and libvirt-python from building in this buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522515&view=results)
> azl3: upgrade libvirt-python and enable mdevctl for arm

- SPECS/libdnf/libdnf.signatures.json
- SPECS/libdnf/libdnf.spec
- cgmanifest.json
---
dnf 4.19.0 requires the optional_metadata_types configuration present in libdnf 0.73.0. Upgrade libdnf to version 0.73.0 as a result
- Upgrade libdnf to version 0.73.0
**NO**
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522104&view=results)
> Upgrade libdnf to version 0.73.0

- .github/workflows/check-signatures.yml
- toolkit/scripts/check_signatures.py
add signature check to list of other checks.  validation of files (that exist in this repo, not downloaded src tarballs) that show up in *.signatures.json for directories included in a given PR.
ways to make this better:
* check downloaded tarballs as well
> add signature check

- toolkit/scripts/toolchain/cgmanifest.json
- toolkit/scripts/toolchain/container/Dockerfile
---
Update toolchain container bootstrap to version 2.0.20240123. This contains an updated ca-certificates package, which seems to be required to accesss PMC. The previous version 2.0.20231004 recently started hitting the following errors during toolchain builds:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522720&view=logs&j=b8434940-6313-5e68-756c-eb07a355d9c5&t=47ceba65-52ed-50aa-b33b-d0e02de1d7d0
```
Refreshing metadata for: 'CBL-Mariner Official Microsoft 2.0 x86_64'
Error(1261) : SSL peer certificate or SSH remote key was not OK
Error: Failed to synchronize cache for repo 'CBL-Mariner Official Base 2.0 x86_64' …
```
> update toolchain container bootstrap to 2.0.20240123

- toolkit/scripts/toolchain/cgmanifest.json
- toolkit/scripts/toolchain/container/Dockerfile
---
Update toolchain container bootstrap to version 2.0.20240123. This contains an updated ca-certificates package, which seems to be required to accesss PMC. The previous version 2.0.20231004 recently started hitting the following errors during toolchain builds:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522720&view=logs&j=b8434940-6313-5e68-756c-eb07a355d9c5&t=47ceba65-52ed-50aa-b33b-d0e02de1d7d0
```
Refreshing metadata for: 'CBL-Mariner Official Microsoft 2.0 x86_64'
Error(1261) : SSL peer certificate or SSH remote key was not OK
Error: Failed to synchronize cache for repo 'CBL-Mariner Official Base 2.0 x86_64' …
```
> [main] update toolchain container bootstrap to 2.0.20240123

- toolkit/imageconfigs/qemu-guest.json
---
Move all base images to use `kernel` by default. Customers who needs a different kernel can customize that through uninstalling & installing the desired kernel.
For 3.0, `kernel-hci` is going away so this is related prep work.
**NO**
Local testing.
> Switch qemu-guest base image to kernel instead of kernel-hci

- SPECS/pam_wrapper/pam_wrapper.spec
This reverts commit abc4f4e5fe19ba774c52fb36aed8bd7adea78743.
---
Revert the temporary changes in PR #8194 related to pam_wrapper.
Now that cmake has been updated from version 3.21.4 to 3.28.2, our nightly builds are again compiling the pypamtest.so module. 
The new cmake seems to have resolved an issue finding PythonLibs, which allows pypamtest.so to build.
With cmake 3.21.4, when pypamtest.so was not built:
```
"-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version \"3\")"
```
With cmake 3.28.2, when pypamtest.so is being built:
```
"CMake Warning (dev) at …
```
> Revert "fix pam_wrapper build (#8194)"

- SPECS/pam/CVE-2024-22365.patch
- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
patch CVE-2024-22365
- CVE-2024-22365
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-22365
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523637&view=results[IPass (failed install tests due to dependency on tdnf. Non blocking)]
> pam: patch CVE-2024-22365

- SPECS/kernel/CVE-2015-5157.nopatch
- SPECS/kernel/CVE-2022-2585.nopatch
- SPECS/kernel/CVE-2022-2586.nopatch
- SPECS/kernel/CVE-2023-50431.nopatch
- SPECS/kernel/CVE-2023-6200.nopatch
- SPECS/kernel/CVE-2023-6560.nopatch
---
Address kernel CVE-2015-5157, CVE-2022-2585, CVE-2022-2586, CVE-2023-50431, CVE-2023-6200, CVE-2023-6560
- Address kernel CVE-2015-5157, CVE-2022-2585, CVE-2022-2586, CVE-2023-50431, CVE-2023-6200, CVE-2023-6560
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2015-5157
- https://nvd.nist.gov/vuln/detail/CVE-2022-2585
- https://nvd.nist.gov/vuln/detail/CVE-2022-2586
- https://nvd.nist.gov/vuln/detail/CVE-2023-50431
- https://nvd.nist.gov/vuln/detail/CVE-2023-6200
- https://nvd.nist.gov/vuln/detail/CVE-2023-6560
> Address kernel CVE-2015-5157, CVE-2022-2585, CVE-2022-2586, CVE-2023-50431, CVE-2023-6200, CVE-2023-6560

- toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
- toolkit/tools/pkg/imagecustomizerlib/extractpartitions_test.go
---
When MIC customizes Mariner images, it produces multiple output image files (with the `.zst` extension) that correspond to different partitions on the system. Currently, combining partition images from multiple runs of MIC is not supported and has resulted in customer bugs. Today, we have no way to detect whether a user has accidentally mixed images from different runs.
Zstd has a concept of “skippable frames",  which are blocks of data that can be included in a compressed stream but do not impact the result of decompression (https://github.com/facebook/zstd/blob/release/doc/zstd_compression_format.md#skippable-frames). Given a zst compressed file, a skippable frame can be …
> Image Customizer: Adding skippable frames with unique metadata to generated partitions

- toolkit/tools/pkg/specreaderutils/specreaderutil.go
---
specreaderutils: return error from FindSpecFiles after parsing full list
- Parse entire list of specs in `FindSpecFiles` before returning error
- Remove error logging in `parseSPECs` as the error message is misleading. Error caught from `FindSpecFiles` has required information for debug. Throw to caller.
- Fix error format in `ParseSPECsWrapper`
**NO**
- Local build with command
` sudo make build-packages SRPM_PACK_LIST="invalid_spec_A invalid_spec_B grpc" REBUILD_TOOLS=y`
before:
Even if there are multiple incorrect specs listed in the make command, an execution would notify of only one error, as the function `FindSpecFiles` returns on first erroneous spec.
after: …
> specreaderutils: return error from FindSpecFiles after parsing full list

- SPECS/azurelinux-release/azurelinux-release.spec
---
Restore 'Microsoft' and full version number in azurelinux-release; they were removed as part of #8028 
Before (3.0.20240301 build):
```
Welcome to Azure Linux 3.0 (x86_64)
$ cat /etc/os-release
NAME="Azure Linux"
VERSION="3.0"
ID=azurelinux
VERSION_ID="3.0"
PRETTY_NAME="Azure Linux 3.0"
...
$ cat /etc/lsb-release
DISTRIB_ID="azurelinux"
DISTRIB_RELEASE="3.0"
DISTRIB_CODENAME=AzureLinux
DISTRIB_DESCRIPTION="Azure Linux 3.0"
$ cat /etc/azurelinux-release
Azure Linux 3.0
AZURELINUX_BUILD_NUMBER=a91c3fa
```
After:
```
Welcome to Microsoft Azure Linux 3.0 (x86_64)
$ cat /etc/os-release
NAME="Microsoft Azure Linux"
VERSION="3.0.20240307" …
```
> Restore 'Microsoft' and full version number in azurelinux-release

- toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
- toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go
- toolkit/tools/imagegen/attendedinstaller/views/eulaview/eulaview.go
- toolkit/tools/imagegen/diskutils/verity.go
- toolkit/tools/internal/ccachemanager/ccachemanager.go
- toolkit/tools/internal/directory/directory.go
- toolkit/tools/internal/jsonutils/jsonutils.go
- toolkit/tools/repoquerywrapper/repoquerywrapper.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
Remove and replace references to deprecated ioutil package.
https://pkg.go.dev/io/ioutil
"Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code."
- Remove all references in .go files of io/ioutil package
- Replace with their corresponding implementation io and os package, specifically:
ioutil.ReadDir -> os.ReadDir
ioutil.ReadFile -> os.ReadFile
ioutil.WriteFile -> os.WriteFile
ioutil.Discard -> io.Discard
ioutil.ReadAll -> io.ReadAll
**NO**
- Searched through our github repo to find all the files using this package
- Used a golang …
> golang: replace deprecated ioutil package references

- toolkit/tools/imagegen/installutils/installutils.go
---
When applying SELinux labels, bind mounts are used to ensure all directories are labelled (even those used for nested mounts). However, the bind mount root directory cleanup was accidentally targeting a directory on the host system instead of in the image. This change fixes this.
- Fix SELinux labelling image with multiple partitions - Take 2.
NO
> Fix SELinux labelling image with multiple partitions - Take 2.

- SPECS/python-gevent/python-gevent.spec
---
Fix CVE-2021-22931. Nist mentions this is a CVE against nodejs, despite deep scan alerting about sources inside deps/c-ares.
Another link from nist clarifies this is really a CVE against c-ares https://security.gentoo.org/glsa/202401-02. 
Embedded c-ares is [set to 1.16.1](https://github.com/gevent/gevent/commits/21.1.2/deps/c-ares), but we'd need to upgrade to 1.19 to fix CVE. eg add all these commits as patches from https://github.com/gevent/gevent/commits/master/deps/c-ares
It seems easier to disable the module, provided no clients depend on this functionality.
By setting `GEVENTSETUP_DISABLE_ARES=1`, the c-ares module is …
> python-gevent: disable c-ares module and fix CVE-2021-22931

- SPECS/dracut/20overlayfs/overlayfs-mount.sh
- SPECS/dracut/dracut.signatures.json
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/pkg/imagecustomizerlib/customizeoverlay.go
---
Optimize the existing MIC Overlay API to support multiple volumes. Users can assign different persistent volumes to distinct Overlays. If no volumes are set, a volatile Overlay will be created.
**NO**
- (internal) https://dev.azure.com/mariner-org/ECF/_sprints/taskboard/Mariner%20Operator%20Edge/ECF/2403?workitem=7107
- Local build
> imagecustomizer: Optimize MIC Overlay supporting multiple volumes.

- SPECS/python-setuptools/python-setuptools.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Prevent *-devel packages from being pulled into core images. These should not be needed in the core images, and they increase the disk usage.
Reduces core EFI VHDX by ~2MB.
- Modify `python-setuptools` to Require `python3` instead of `python3-devel` at runtime.
This prevents `python3-devel` (and `expat-devel`) from being included in the core images. 
Reduces core image size by ~2MB.
Add BuildRequires to fix buddybuild/regular package build for `python-setuptools`
**YES**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526144&view=results
- Local build. Built core VHDX before and after this change. …
> Prevent -devel package inclusion in core images (from python-setuptools)

- SPECS/calamares/calamares.signatures.json
- SPECS/calamares/calamares.spec
- SPECS/calamares/license.conf
- toolkit/imageconfigs/full.json
- toolkit/resources/imageconfigs/iso_initrd.json
- toolkit/resources/imageconfigs/iso_initrd_arm64.json
- toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
- toolkit/tools/imagegen/attendedinstaller/views/installationview/installationview.go
- toolkit/tools/imagegen/attendedinstaller/views/installerview/installerview.go
---
Add in a few fixes to the azl-3.0 iso to stabilize the environment for grub mk config and calamares file references.
- allow grub mk config flag retention for attended installer configs
- Add grub mk config flag to full.json configs
- calamares filename change mariner-eula > azl-eula
- add audit to iso_initrd to reduce kernel printk spew in iso environment
**NO**
- Local iso Builds
> fix iso files for calamares eula, add retention of GrubMkConfig for attended installer

- SPECS/python-setuptools/python-setuptools.spec
---
Remove explicit `Requires: python3` from python-setuptools.spec. This is not necessary and leads to a circular dependency loop in the specs.
```
PANI[0004][grapher] unfixable circular dependency in dependency graph ({python3-3.12.0-2.azl3-RUN<Meta>} --> {python3-setuptools-69.0.3-2.azl3-RUN<Meta>} --> {libselinux-3.6-1.azl3-BUILD<Build>} --> {libselinux-3.6-1.azl3-RUN<Meta>} --> {coreutils-9.4-1.azl3-RUN<Meta>} --> {openssl-3.1.4-2.azl3-RUN<Meta>} --> {python3-3.12.0-2.azl3-RUN<Meta>}):
cycle can't be resolved with prebuilt/PMC RPMs. Unresolvable
```
- Change python-setuptools to remove python3 requires
**YES**
- Local build
> remove explicit python3 requires

- SPECS/dhcp/dhcp.spec
---
Azure configures classless routes and cloud-init requires the configuration to be included in the lease file to behave correctly.
- Add rfc3442-classless-static-routes option to dhclient.conf
No
Build & installed RPM locally and validated cloud-init behavior.
> [2.0] dhcp/dhclient.conf: add option rfc3442-classless-static-routes in dhclient.conf

- SPECS/dhcp/dhcp.spec
Add manual definition of RFC3442 classless static routes, to fix #8334 
This is the 3.0 version of #8318
> [3.0] dhcp/dhclient.conf: add option rfc3442-classless-static-route in dhclient.conf

- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
- toolkit/tools/pkg/isomakerlib/isomaker.go
There are a few different implmentations of the `mkisofs` tool. And there isn't a consistent value for what the default volume ID (i.e. filesystem label) should be. This change ensures that Azure Linux ISOs always use the same volume ID regardless of the host they are build on.
This is a bug fix for the Image Customizer Live-CD generator which uses the ISO's filesystem label in the grub.cfg file.
---
NO
> Ensure ISO has consistent volume ID.

- toolkit/scripts/containerized-build/resources/setup_functions.sh
---
A recent rebranding change #8238 changed the repo name used by the `containerized-rpmbuild` container for mariner to `azl-3.0-daily-build`, but didn't change the default `tdnf` argument, which continued to use `mariner-3.0-daily-build`. This results in `tdnf` not working in the container.
This fix updates the `tdnf` argument, basing it on the string in the repo file, so we don't have to copy/paste it later.
- Updated the `--enablerepo` flag used by `tdnf` in the `containerized-rpmbuild` environment.
**NO**
> containerized-rpmbuild: fix tdnf --enablerepo value for 3.0

- SPECS/systemd-bootstrap/systemd-bootstrap.spec
- SPECS/systemd/systemd.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The new systemd package includes a `systemd-libs` subpackage which some packages `Requires:`. If a system has `systemd-bootstrap` installed, and we go to install that package, it will cause conflicts. The main `systemd` package correctly obsoletes `systemd-bootstrap`, but `systemd-libs` does not. It is not sufficient to just add an obsoletes to `systemd-libs` for `systemd-bootstrap` since the new libs subpackage offers only the `*.so` files. It is cleaner to just split the `*.so` files into their own bootstrap version of the `-libs` subpackage.
In a more general sense additional `Obsoletes` should be added to `systemd-bootstrap-libs` so it can replace an older copy of …
> Add systemd-bootstrap-libs subpackage.

- toolkit/docs/building/building.md
- toolkit/scripts/incremental_building.mk
- toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
In 2.0 `CLEAN_TOOLCHAIN_CONTAINERS` defaults to `y` unless `QUICK_REBUILD_TOOLCHAIN=y` is set. This means that most of the time when running `make clean` we will remove all the build containers associated with the current checkout (they are identified via the docker variable `MARINER_BUILD_DIR` which is included in each image).
The containers are tagged with a hash of the interesting input components (`./container/toolchain-sha256sums` `./container/toolchain_build_in_chroot.sh` `./create_toolchain_in_container.sh`). This means if a branch changes any of these files the previous containers will not be valid and the bootstrap will be re-run.
The bootstrap container is generally …
> Used cached toolchain containers by default.

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/bootloaderresettype.go
- toolkit/tools/imagecustomizerapi/config.go
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/systemconfig.go
- toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
The change does two things.
Firstly, it moves bootloader reset operation so that it is done after package installation. If a new partition layout requires additional dependencies (e.g. the grub2 package), this allows those dependencies to be easily installed before the bootloader is reset.
Secondly, a new config field called `ResetBootLoaderType` has been added. This field doesn't add any additional logic. Instead, it used to make the user explicitly acknowledge that the bootloader must be reset when partitions are customized.
---
NO
> Image Customizer: Changes to bootloader reset.

- toolkit/tools/internal/file/file.go
- toolkit/tools/internal/file/filecopybuilder.go
- toolkit/tools/internal/file/filecopybuilder_test.go
- toolkit/tools/internal/safechroot/safechroot.go
- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/isomakerlib/isomaker.go
Fix a couple of bugs related to taking image that uses the kernel-mshv package and turning it into an ISO.
Firstly, when uninstalling the kernel package, the /usr/lib/modules/<version> directory is emptied but it isn't removed. This confuses the image customizer's logic to discover the list of installed kernels. This change updates the logic to filter out empty directories.
Secondly, when generating the ISO, the files under the /boot directory are copied into the ISO. But this logic fails if it encounters a broken symlink. For example, a `mariner.cfg` file that wasn't removed when the `kernel` package was uninstalled. This change ensures that symlinks are copied as symlinks.
NO
- …
> Image Customizer: Fix bugs for ISO gen + kernel-mshv

- toolkit/tools/imagegen/diskutils/fstab.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
---
The PR is for bugfixing the Remount service down on Verity enabled image. This is due to fstab file not updated.
```
[FAILED] Failed to start Remount Root and Kernel File Systems.
Mar 04 05:04:49 mariner-image systemd-remount-fs[548]: mount: /: cannot remount /dev/sda3 read-write, is write-protected.
```
**NO**
- Local MIC image build -> boot up the image seeing this service is up and running.
> Bugfix on Verity enabled images Remount service down.

- SPECS/dracut/20overlayfs/module-setup.sh
- toolkit/scripts/check_signatures.py
Signature check was not handling PRs that changed files embedded in subfolders.
This BuidlRpms break (https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526527&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667) happened because a .sh file had a mismatched signature.  The .sh file was not a file in the same folder as the signatures/spec file, it was in a subfolder.
The changes here:
* look for SPECS|SPECS-EXTENDED folder that have changed in PR to get signatures from, search all signatures.json with corresponding spec file.
* when finding files to check signatures for, search all subfolders for a file with the matching name
> Fix: Signature check not handling files in subfolders

- toolkit/tools/imagegen/installutils/installutils.go
---
Make the tools install /etc/default/grub with 0644 perms.
Justification: 0400 forces normal users to escalate privilege simply to read files. Furthermore, 0400 never made much sense for me even for the /boot/grub2/grub.cfg. Not having write permissions for root is a little silly; surely at least root must be able to edit the configuration? 644 makes it so that everyone can read the boot configuration and must escalate to root in order to edit it.
/boot dir is 0700 so the 0400 in /boot/grub2/grub.cfg is redundant as far as groups,others is concerned and only narrows the scope of what root can do in there. 
- Install /etc/default/grub …
> fix: Make tools install /etc/default/grub with 0644 perms

- toolkit/scripts/toolchain.mk
---
`clean-toolchain` and `clean-toolchain-rpms` were both not actually cleaning `./build/toolchain_rpms`, they should do that.
We have a list (`$(toolchain_out_rpms)`) of absolute paths, so just do a for-each on that list and make sure any copied rpms are gone from `./out/RPMS` (we can't delete the whole thing, since it may contain other rpms from the normal build stage). We can just delete the entire `$(TOOLCHAIN_RPMS_DIR)` directory if it is present since the toolchain creates it.
- Fix `clean-toolchain-rpms` to actually clean the toolchain rpms
- Have `clean-toolchain` call `clean-toolchain-rpms` as a depenency.
**YES**
- Local test
> Fix 'clean-toolchain-rpms' so it actually removes them

- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
The 'nogroup' group has differing implementations across major distros:
Ubuntu:        'nogroup' GID 65534
Fedora/RHEL:   'nobody'  GID 65534
OpenSUSE/SLES: 'nobody'  GID 65534 *and* 'nogroup' GID 65533
However, *all* distros provide the 'nobody' user with *both* UID and GID 65534.
This brings our group settings in line with OpenSUSE/SLES (providing *both* 'nogroup' and 'nobody' groups), and brings our 'nobody' user settings in line with *all* other distros (uid:gid of 65534:65534).
> filesystem: fix nobody GID

- toolkit/tools/internal/resources/assets/grub2/grub
We want to use cgroups v2 in azl3; this removes the cmdline parameters that force use of cgroups v2.
> remove cmdline that forces cgroupv1

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/10_kernel.cfg
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/tools/internal/resources/assets/grub2/grub
This removes both the toolkit manual addition of `init=/lib/systemd/systemd` to the `/etc/default/grub` file, as well as the kernel package addition of a `/etc/default/grub.d/10_kernel.cfg` file that contains the same setting (it also adds a `ro` but that's also unnecessary because `grub2-mkconfig` adds `ro` by default).
> remove boot cmdline 'init='

- SPECS/systemd/mariner-2-force-use-of-lz4-for-coredump.patch
- SPECS/systemd/systemd.spec
Azure Watson cannot handle ZSTD compression, so force Mariner 2 systemd-coredump to always use LZ4 compression.
> systemd: force coredump to use LZ4 compression

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/os.go
- toolkit/tools/imagecustomizerapi/packages.go
- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-force-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-permissive.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml
Move all the packages properties under a single `packages` property.
---
NO
> Image Customizer: Add `packages` struct.

- toolkit/tools/imagecustomizerapi/kernelcommandline.go
- toolkit/tools/imagecustomizerapi/os.go
- toolkit/tools/imagecustomizerapi/selinux.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-disabled.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-force-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-permissive.yaml
- toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Move the `selinuxMode` property from the `kernelCommandLine` property into a dedicated `selinux` property. While SELinux can impact the kernel command-line, it is its own feature and therefore should be separate.
---
NO
> Image Customizer: Move selinuxMode into its own struct.

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- toolkit/tools/internal/resources/assets/grub2/grub
We don't even provide plymouth, we don't need a cmdline parameter to 'disable' it.
> toolkit: remove cmdline parameter to disable plymouth

- SPECS/coreutils/coreutils.signatures.json
- SPECS/coreutils/coreutils.spec
- SPECS/coreutils/serial-console.sh
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
This script was not correctly saving/restoring the cursor position, resulting in the first letter of the login prompt starting at the screen bottom right position immediately on login (only to a serial console).
Also, this should not be setting TERM to 'screen'.
> coreutils: fix serial-console.sh

- SPECS/cryptsetup/cryptsetup.spec
Previously there were "circular dependency" problems, but `openssh` now build deps the "bootstrap" version of `systemd-rpm-macros` which avoids the "circular dependency".
> cryptsetup: enable ssh-token

- toolkit/tools/imagecustomizerapi/boottype.go
- toolkit/tools/imagecustomizerapi/config.go
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/os.go
- toolkit/tools/imagecustomizerapi/os_test.go
- toolkit/tools/imagecustomizerapi/storage.go
- toolkit/tools/imagecustomizerapi/storage_test.go
- toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
Add a new `storage` property and move `disks`, `partitionSettings`, and `bootType` under it. This ensures related concepts are grouped together.
---
NO
> Image Customizer: Add storage struct.

- SPECS/systemd/systemd.spec
Currently, our systemd maintainer scripts are all broken, because the systemd rpm macros aren't available during the systemd build.
This results in all the systemd packages having the actual macros in the maint scripts, e.g.:
```
$ rpm -q --scripts systemd-udev | grep '%systemd'
%systemd_post systemd-udev{d,-settle,-trigger}.service systemd-udevd-{control,kernel}.socket systemd-homed.service systemd-boot-update.service systemd-oomd.service systemd-portabled.service systemd-pstore.service systemd-timesyncd.service remote-cryptsetup.target
%systemd_preun systemd-udev{d,-settle,-trigger}.service systemd-udevd-{control,kernel}.socket systemd-homed.service systemd-boot-update.service systemd-oomd.service systemd-portabled.service systemd-pstore.service systemd-timesyncd.service …
```
> systemd: require our "bootstrap" macros when building

- toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
---
Since the idtype has changed including `-`, update format logic for verity / overlay.
**NO**
- Local build.
> Update format idtype function.

- SPECS/dracut/20overlayfs/overlayfs-mount.sh
- SPECS/dracut/dracut.signatures.json
---
This PR removes `set -ex` from the overlay Dracut module script. 
When image with overlays enabled, it always requires `rd.debug` to be enabled, otherwise the overlayfs can not be mounted properly. I compared the output logs between images with / without `rd.debug`:
```
with `rd.debug` enabled
[ 2.011899] dracut-pre-pivot[483]: +++ getarg rd.overlayfs= 
[ 2.014243] dracut-pre-pivot[483]: +++ debug_off 
[ 2.016424] dracut-pre-pivot[483]: +++ set +x 
[ 2.018382] dracut-pre-pivot[483]: +++ return 0 
[ 2.020595] dracut-pre-pivot[479]: ++ overlayfs='/etc,upper1,work1, /var,upper2,work2,'
```
``` 
with `rd.debug disabled
[    2.047313] …
```
> Remove set -ex from the overlay script.

- SPECS/qemu/0002-disable-migration-tests.patch
- SPECS/qemu/qemu.spec
---
- Disable migration tests and move qemu package to use pcre2
- Add the 0002-disable-migration-tests patch to disable migration patch that were causing test freeze
- Moves qemu package to use pcre2 instead of pcre
**NO**
- Buddy build id: [532175](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=532175&view=results)
- Local build
> qemu: tests unfreeze patch, pcre2 move

- SPECS/systemd/systemd.spec
This reverts commit e2f7ca6f2f705b2447aa3e98f6ef8bf76ec6f08f.
This commit exposes a limitation in our build-cycle resolution code. Will need to fix it, but revert in the meantime.
We should not have been able to publish this package as-is, so I believe the revert of the release number is ok.
Bug: https://microsoft.visualstudio.com/OS/_workitems/edit/49601294
Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=533021&view=results
> Revert "systemd: add Provides: for the "bootstrap" package names"

- SPECS/golang/golang.signatures.json
- SPECS/golang/golang.spec
- cgmanifest.json
---
Bump golang version to 1.21.8-1, build version to 1.21.8-2
* Thu Mar 21 2024 Davis Goodin - 1.21.8-1
- Bump version to 1.21.8-1, build version to 1.21.8-2
No
- https://nvd.nist.gov/vuln/detail/CVE-2024-1394
- Others mentioned in upstream 1.21.8 release notes:
- https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=532723&view=results
> Bump golang version to 1.21.8-1, build version to 1.21.8-2

- SPECS/Cython/Cython.spec
- SPECS/Cython/fix_testcycache.patch
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix Cython package tests. Use the requirements.txt file specific to python 3.12, this allows the latest version of setuptools to be installed. Previously, the requirements.txt file downgraded setuptools to an old version, which broke the tests.
I've also disabled the file-based tests, since these take over 6 hours to run, and patched one broken test.
- Change Cython to use python312 requirements
- Disable long running file based tests
- Patch TestPyCache test
**YES**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=533428&view=results
> Cython: fix package test by using python312 requirements

- SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
- SPECS/grub2/grub2.spec
- toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
- toolkit/imageconfigs/packagelists/core-packages-image.json
- toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
---
Originally, grub2-mkconfig (which is needed to generate the boot configuration for a grub-based image) was packaged in grub2.rpm. This rpm has a 35MB footprint which is undesirable for a slimmed down core image. 
Introduce grub2-mkconfig.rpm which contains only the necessary utilities for mkconfig. 
- Introduce grub2-mkconfig subpackage
NO
- Inspected subpackage RPM for size: a mere 7.5MB needed for the core image as opposed to 35MB.
-
> Split off mkconfig from grub2 package to reduce image footprint

- SPECS/filesystem/filesystem.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
The /srv dir is provided via systemd tmpfiles.d configuration
> filesystem: remove /srv and /var/srv

- SPECS/dracut/dracut.spec
---
Exclude the dracut-overlayfs sub-package out of main dracut package to clear conflict caused by this sub-package.
**NO**
- Pipeline build id: buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=533662&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=533685&view=results
> Exclude overlayfs module from main dracut package.

- .github/workflows/check-circular-deps.yml
- SPECS/systemd/systemd.spec
---
Add a github workflow to verify changes will not introduce a circular dependency into the full builds. Circular dependencies are difficult to catch during code review, and our buddybuild pipeline does not catch them (since it only builds with a small graph, including the packages specifically requested in that build). We typically catch circular dependency breaks in nightly full builds.
This PR check is currently only enabled for 3.0 branches, as it relies on the DAILY_BUILD_ID repos.
- Add workflow to check for circular dependency loops
**NO**
- Pipeline build id: This PR has a link to the check: …
> Add workflow to check for circular deps (3.0 only)

- SPECS/msft-golang/msft-golang.signatures.json
- SPECS/msft-golang/msft-golang.spec
- cgmanifest.json
---
Bump version to 1.21.8
**NO**
- Related: https://github.com/microsoft/azurelinux/pull/8500
- 
- Pipeline build id: [PR-8516](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=533044&view=results)
/cc @dagood
> msft-golang: upgrade version 1.21.6 -> 1.21.8

- SPECS/cri-o/cri-o.spec
- SPECS/fio/fio.spec
- SPECS/libnbd/libnbd.spec
---
Fix package build breaks with `fio` and `cri-o`
- crio-o: remove dependency on `apparmor-devel`, which was removed in #6966 
- fio: remove BuildRequires on `libpmemblk-devel` and remove related `engine-pmemblk` subpackage. When `nvml` was upgraded to version 2.0.1, it no longer produced the `libpmemblk-devel` subpackage. See #7562 
**NO**
- Local build
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=525647&view=results
- Note that `crio-o` and `fio` cannot build in buddybuild due to `ceph` build errors
> Fix build breaks with fio and cri-o

- SPECS/kernel-mshv/kernel-mshv.spec
---
This PR removes the kernel-mshv-tools subpackage to unblock Azure Linux 3.0 builds. We will address at a later point whether and how to re-include the subpackage.
- Remove the tools subpackage to unblock Azure Linux 3.0 builds
**NO**
- N/A
- N/A
- Pipeline build id: 535264
> Remove kernel-mshv-tools

- SPECS/distroless-packages/distroless-packages.spec
---
This PR adds `libgcc` package as an explicit runtime dependency to distroless base container image. `libgcc` package is present in the image in Azure Linux 2.0, however, it was coming in as a dependency from some other package. Changes in Azure Linux 3.0 have resulted in `libgcc` being removed from the distroless base container image. To maintain the composition, we need to add this package back to the distroless base image.
Package: `distroless-packages-base`
**NO**
Manual comparison of packages in the distroless/debug containers from Azure Linux 2.0 and 3.0.
| Azure Linux 2.0 distroless/debug | Azure Linux 3.0 distroless/debug | …
> add libgcc back in distroless base image

- SPECS/etcd/etcd.signatures.json
- SPECS/etcd/etcd.spec
- cgmanifest.json
---
Cherry-pick of fast-track #8447.
Yes.
- #8477
- Buddy build.
> Upgraded `etcd` to version 3.5.12. (CP: #8477)

- SPECS/distroless-packages/distroless-packages.spec
---
This PR adds `libgcc` package explictly as a runtime dependency for distroless/base subpackage to ensure that the distroless/base container image continues to have it. Currently, `libgcc` is brought it by some other package as its dependency. It was observed that the changes in Azure Linux 3.0 had resulted in the removal of `libgcc` package from distroless base, so it was explictly added to not cause a breaking change. For reference, this is the merged PR in Azure Linux 3.0: https://github.com/microsoft/azurelinux/pull/8520.
Package: `distroless-packages-base`
**NO**
This is considered a non-breaking change as we are just explicitly …
> explicitly add libgcc as a Requires to distroless base

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/disk_test.go
- toolkit/tools/imagecustomizerapi/filesystem.go
- toolkit/tools/imagecustomizerapi/filesystem_test.go
- toolkit/tools/imagecustomizerapi/partition.go
- toolkit/tools/imagecustomizerapi/partition_test.go
- toolkit/tools/imagecustomizerapi/storage.go
- toolkit/tools/imagecustomizerapi/storage_test.go
- toolkit/tools/internal/sliceutils/sliceutils.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
Move the `fileSystemType` property from the `partition` type to the `fileSystem` type and rename it to just `type`.
---
NO
> Image Customizer: Move fileSystemType to fileSystem type.

- SPECS/Cython/Cython.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Cython package tests take over 3 hours to run in our ptest pipelines ([link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=534745&view=ms.vss-test-web.build-test-results-tab)). Disable long-running file and examples tests to ensure the tests can complete in a reasonable amount of time.
- Change Cython tests to skip long-running tests
**YES**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=535499&view=results
> Cython: skip long tests

- .pipelines/prchecks/PackageBuildPRCheck.yml
---
The ccache should significantly shorten package build times.
The artifact suffix will prevent artifact upload failures during job re-runs as each run will generate an artifact with a different name.
No.
- PR check run.
> Enabled ccache and artifact suffixes for fast-track PR check

- SPECS/expat/expat.signatures.json
- SPECS/expat/expat.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrading to 2.6.2 to fix CVE-2023-52425. This also fixes CVE-2024-28757. 
libexpat through 2.6.1 allows an XML Entity Expansion attack when there is isolated use of external parsers (created via 
XML_ExternalEntityParserCreate). Affected packages: cmake, python3, and expat. 
Upgrading expat solves the issue for the 3 packages
- Upgraded package to version 2.6.2 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-52425
- https://nvd.nist.gov/vuln/detail/CVE-2024-28757
- Buddy build id: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=532877&view=results)
- Passed PR pipeline build check
> Upgrade expat to 2.6.2 CVE-2023-52425 and CVE-2024-28757

- .github/workflows/check-spec.yml
- SPECS/vim/vim.spec
- toolkit/scripts/check_spec_guidelines.py
- toolkit/scripts/pkggen.mk
- toolkit/scripts/srpm_pack.mk
- toolkit/scripts/toolchain.mk
- toolkit/scripts/toolchain/check_manifests.sh
- toolkit/scripts/toolchain/list_toolchain_specs.sh
- toolkit/tools/internal/packlist/packagelist.go
- toolkit/tools/specreader/specreader.go
- toolkit/tools/srpmpacker/srpmpacker.go
---
remove srpm_pack_list_file
- Remove srpm_pack_list_file
- Pass SRPM_PACK_LIST to specreader and srpmpacker
- This change will remove the a few file ops, remove unnecessary logic from makefile and thereby make go tools more independent in handling user input
**NO**
- Locally built packages successfully:
- without providing SRPM_PACK_LIST in make command : all packages in SPECS_DIR built
- providing empty SRPM_PACK_LIST `SRPM_PACK_LIST=""` : all packages in SPECS_DIR built
- providing empty SRPM_PACK_LIST with spaces `SRPM_PACK_LIST="        "` : all packages in SPECS_DIR built
- providing one package `SRPM_PACK_LIST="vim"` : vim built
- providing one package with leading/trailing …
> remove srpm_pack_list_file

- SPECS/abseil-cpp/abseil-cpp.signatures.json
- SPECS/abseil-cpp/abseil-cpp.spec
- SPECS/grpc/grpc.spec
- SPECS/nginx/nginx.signatures.json
- SPECS/nginx/nginx.spec
- SPECS/opentelemetry-cpp/opentelemetry-cpp.signatures.json
- SPECS/opentelemetry-cpp/opentelemetry-cpp.spec
- SPECS/protobuf-c/protobuf-c.spec
- SPECS/protobuf/protobuf.spec
- SPECS/re2/re2.spec
- cgmanifest.json
---
[What does the PR accomplish, why was it needed?
abseil-cpp: upgrade to 20240116.0, opentelemetry-cpp: upgrade to 1.14.2, nginx: upgrade to 1.25.4
- Upgrade abseil-cpp to 20240116.0 (for opentelemetry + it was failing tests on previous version)
- Add testing libraries for abseil-cpp, so it will pass the new version tests
- Bump releases for grpc, re2, protobuf and protobuf-c because of new abseil-cpp version
- Upgrade opentelemetry-cpp to 1.14.2 (added abseil-cpp dependency)
- Upgrade nginx to 1.25.4 and njs_version to 0.8.3
- Move nginx to pcre2
- Remove opentelemetry-cpp-contrib as we don't need it anymore with the new versions
**NO**
- Package build buddy build …
> abseil-cpp: upgrade to 20240116.0, opentelemetry-cpp: upgrade to 1.14.2, nginx: upgrade to 1.25.4

- toolkit/tools/imagecustomizerapi/iso.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
The ISO struct was missed in the change to convert the YAML API to use camelCase.
---
NO
> Image Customizer: Apply missing camelCase to ISO struct.

- SPECS/qt5-qtbase/CVE-2022-25643.patch
- SPECS/qt5-qtbase/qt5-qtbase.spec
Changes to be committed:
new file:   SPECS/qt5-qtbase/CVE-2022-25643.patch
modified:   SPECS/qt5-qtbase/qt5-qtbase.spec
---
Add patch to package qt5-qtbase to address CVE-2022-25643
new file:   SPECS/qt5-qtbase/CVE-2022-25643.patch
modified:   SPECS/qt5-qtbase/qt5-qtbase.spec
NO
[- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX](https://nvd.nist.gov/vuln/detail/CVE-2020-0569)
> Add patch to package qt5-qtbase to address CVE-2022-25643

- SPECS/libvirt/CVE-2024-2496.patch
- SPECS/libvirt/libvirt.spec
---
Address medium CVE-2024-2496
- CVE-2024-2496
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-2496
- Pipeline buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537774&view=results
> libvirt: Address Medium CVE-2024-2496 

- SPECS-EXTENDED/perl-Test-File/perl-Test-File.spec
---
Fix for build break in SPECS-EXTENDED: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537290&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667)
```
WARN[0010][srpmpacker] error: /specs/perl-Test-File/perl-Test-File.spec: line 3: Macro %rpmversion is a built-in (%global)
error: query of specfile /specs/perl-Test-File/perl-Test-File.spec failed, can't parse 
ERRO[0010][srpmpacker] Failed to check (/specs/perl-Test-File/perl-Test-File.spec). Error: exit status 1
```
Defining `%global rpmversion` in the SPEC became an error after upgrading to rpm 4.18.2
- Change …
> perl-Test-File: fix macro issue

- toolkit/imageconfigs/packagelists/base-image-packages.json
---
The `baremetal_vhdx` and `qemu_guest_vhdx` images have been broken in the past few days in our 3.0-dev branch. See [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=538431&view=logs&j=2ccbf1db-6c73-5af8-5ba2-cf05469dcf51&t=62118ca4-5f53-54b3-7ec9-8ef4ab0e9237&l=1989). The break appears related to some of the references to renamed packages in base-image-packages.json from PR #8389 
Rename these to reference the new package names.
- Change base-image-packages.json references to azurelinux packages
**NO**
- Pipeline build id: I modified the image build pipeline to fix these package names inline with sed commands. …
> Use azurelinux instead of mariner pacakges in base-image-packages.json

- SPECS/btrfs-progs/btrfs-progs.spec
---
[What does the PR accomplish, why was it needed?
](btrfs-progs: disable zstd)
- Disable zstd in btrfs-progs
**NO**
- Pipeline build id: [538851](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=538851&view=results)
> btrfs-progs: disable zstd

- .pipelines/templates/PackageBuild.yml
---
Our pipeline build PR check was accidentally configured to recursively rebuild all of the dependents of the modified package, which caused very long builds in some cases. It was caused by `MAX_CASCADING_REBUILDS=""` overwriting the defaults set by `QUICKREBUILD_PACKAGES=y`. The change makes sure the defaults are maintained, if `MAX_CASCADING_REBUILDS` is not set to a specific value.
CP of #8564.
No.
- PR check for #8564.
> Fixing setting of `MAX_CASCADING_REBUILDS` in the `PackageBuild.yml` template. (CP: #8564)

- toolkit/tools/pkg/imagecustomizerlib/rpmsourcesmounts.go
When detecting the filename extension of `--rpm-source`s, the extension was incorrectly being taken from the first period instead of the last period.
---
NO
> Image Customizer: Fix .repo extension detection.

- SPECS/php-pecl-zip/php-pecl-zip.signatures.json
- SPECS/php-pecl-zip/php-pecl-zip.spec
- cgmanifest.json
---
upgrade `php-pecl-zip` to version 1.22.3 and fix tests by ensuring `tzdata` is available.
Without `tzdata` available, the tests were failing (even in the previous version) with the following:
```
="Notice: date_default_timezone_set(): Timezone ID 'UTC' is invalid in /usr/src/azl/BUILD/php-pecl-zip-1.21.1/NTS/run-tests.php on line 193"
"/var/tmp/rpm-tmp.W1fncF: line 56: 3135402 Segmentation fault      (core dumped) TEST_PHP_ARGS=\"-n -d extension_dir=$PWD/modules -d extension=zip.so\" TEST_PHP_EXECUTABLE=/usr/bin/php /usr/bin/php -n run-tests.php -q --show-diff"
```
- Change php-pecl-zip: upgrade to version 1.22.3 and fix tests …
> php-pecl-zip: upgrade to version 1.22.3 and fix tests

- SPECS/kernel/10_kernel.cfg
- SPECS/kernel/kernel.spec
Cherrypick from 3.0-dev did not properly remove the 10_kernel.cfg file and did not remove the references to the file in kernel.spec.  The file was properly removed from the kernel.signatures.json file.  T
> Fix build break of kernel

- SPECS-SIGNED/kernel-mshv-signed/kernel-mshv-signed.spec
- SPECS/kernel-mshv/kernel-mshv.spec
---
We hit a build break in the signing pipelines because kernel-mshv-signed does not properly expand its grub2-related macro. Correctly buildreq grub2-rpm-macros to ensure the grub-related behavior matches across kernel-mshv, its signed equivalent. 
- kernel-mshv-signed: buildrequire grub2-rpm-macros
NO
- TBD
> kernel-mshv: buildrequire grub2-rpm-macros to fix macro expansion

- SPECS/gnupg2/gnupg2.signatures.json
- SPECS/gnupg2/gnupg2.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The latest version for `gpg` has an update fixing an issue with `gpg` hanging due to a stale store lock. The new version moves the time the lock is acquired and resolve the issue. See also:
- https://discussion.fedoraproject.org/t/gpg-blocking-forever-cant-git-commit-as-a-result/96605/6
- https://bugzilla.redhat.com/show_bug.cgi?id=2249218
- https://dev.gnupg.org/T6838
- Updated `gnupg2` to 2.4.4.
- Added an empty `gpgconf.conf` file to prevent some of the package's tools from crashing (they expect it to be present).
Yes.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=539443&view=results)
- Local builds with tests.
> Upgraded `gnupg2` to version 2.4.4.

- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/userutils/userutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/users-config.yaml
1. When user exists, append to `authorized_keys` file instead of overwriting it.
2. Return error if UID is provided but the user already exists.
---
---
NO
> Image Customizer: Fix modify existing user.

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
This is related to fix build break of kernel (https://github.com/microsoft/azurelinux/pull/8635).  A cherrypick from 3.0-dev did not properly remove references to the 10_kernel.cfg file in kernel-signed.spec as well.
> Fix Build Break for kernel-signed

- SPECS/perftest/perftest.signatures.json
- SPECS/perftest/perftest.spec
- cgmanifest.json
Upgrade perftest to 24.01.0
---
- Update src package
NO
NA
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=542516&view=results
> perftest: Upgrade to 24.01.0 version 

- .github/workflows/check-manifests.yml
- SPECS/sed/sed.spec
- toolkit/scripts/toolchain.mk
- toolkit/scripts/toolchain/check_manifests.sh
---
check-manifests.sh: replace positional args with named, populate values by default
- check-manifests.sh: replace positional args with named
- check-manifests.sh: populate values by default
- this will make it easier for user to call check-manifests.sh script directly, instead of relying on the make target
- call the script directly in check-manifests.yml
- we can remove the now defunct make target, making our makefile leaner
**NO**
- Locally: successfully invoked check-manifests.sh directly
- Locally: successfully invoked modified check-manifests make target
- Pipeline: pipeline successfully passed when no toolchain specs were modified, and successfully caught error when …
> add named args to check-manifest.sh

- SPECS/WALinuxAgent/WALinuxAgent.signatures.json
- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/WALinuxAgent/ephemeral-disk-warning.service
Path for ephemeral-disk-waring shell script was changed in mariner 3.0 from `/usr/bin` to `/usr/sbin` directory.
---
Provide correct script path for the systemd `ephemeral-disk-warning` service.
The path for `ephemeral-disk-warning` script was changed in 3.0 from `/usr/bin` to `/usr/sbin`, it affected the `ephemeral-disk-waring.service` which writes a data loss warning file to the ephemeral disk mounted with azurelinux virtual machines.
- fix script/binary path for `ephemeral-disk-warning.service`
- WALinuxAgent
**NO**
- Pipeline build id: [PR-8658](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=541879&view=results)
> Fix ephemeral-disk-warning.service not running in mariner 3.0

- SPECS/kexec-tools/kexec-tools.spec
---
This change removes `makedumpfile-R.pl` from the kexec-tools package.
Currently kexec-tools in 3.0 has an implicit dependency on perl because `makedumpfile-R.pl` was brought into the files list during a version upgrade. This perl dependency brings in over 60MB of perl binaries into the default marketplace image. This script was present during the build but unpackaged for 2.0, and there are no known consumers of it for 3.0.
- Remove makedumpfile-R.pl from kexec-tools to remove implicit dependency on perl.
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543404&view=results
- Tested the buddy build package and confirmed there's no longer a …
> kexec-tools: remove implicit perl dependency

- toolkit/tools/depsearch/depsearch.go
---
~Add `--runtime-only` and `--runtime-only-plus-build` flags to `depsearch` tool (for examining the build graphs).~
Add `--runtime-filter-level` flag to `depsearch` tool (for examining the build graphs).
This will filter out all build nodes beyond the layer specified.
```bash
sudo make go-depsearch REBUILD_TOOLS=y
./out/tools/depsearch --input ../build/pkg_artifacts/graph.dot  --reverse --verbosity 3 --tree --packages device-mapper-multipath --max-depth=4 --print-duplicates --runtime-filter-level 1
```
Note that is shows both the run and build node for device-mapper-multipath, but if `--runtime-filter-level 0` is used, it will drop the build node.
- Add runtime filtering to …
> Add runtime filter to depsearch

- toolkit/scripts/containerized-build/resources/azl.Dockerfile
---
Change #7982 introduced a typo in the variable name we use to print which extra packages `containerized-rpmbuild` will install. The correct packages are installed, but the string informing the user what's being installed doesn't print the extra packages.
This change fixes that.
- Fix typo mentioned above.
**NO**
- Tested locally in `containerized-rpmbuild`
> containerized-rpmbuild: fix typo in installing packages string

- SPECS/libvirt/libvirt.spec
---
Remove systemd-bootstrap dependency in libvirt
libguesfs wasn't building because of the error:
"package systemd-255-9.azl3.x86_64 obsoletes systemd-bootstrap <= 255-9.azl3 provided by systemd-bootstrap-250.3-17.azl3.x86_64"
To fix the error we decided to remove the systemd-bootstrap dependency from libvirt-daemon-common.
**NO**
- Local build
- Pipeline build id: [543524](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543524&view=results)
- Full Build: [543589](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543589&view=results)
> Remove systemd-bootstrap dependency in libvirt

- toolkit/docs/formats/imageconfig.md
- toolkit/imageconfigs/core-efi.json
- toolkit/imageconfigs/core-legacy.json
- toolkit/imageconfigs/marketplace-gen1-fips.json
- toolkit/imageconfigs/marketplace-gen1.json
- toolkit/imageconfigs/marketplace-gen2-aarch64.json
- toolkit/imageconfigs/marketplace-gen2-fips.json
- toolkit/imageconfigs/marketplace-gen2.json
- toolkit/imageconfigs/postinstallscripts/core-container/cleanup.sh
- toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
- toolkit/tools/imagegen/configuration/systemconfig.go
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/internal/file/file.go
- toolkit/tools/internal/file/file_test.go
---
The toolkit should be able to handle cleaning up the `tdnf` cache itself, no need to oblige users to call a post-install script for ever image.
- By default run `tdnf clean all` and remove `/var/cache/tdnf` at the end of image builds.
- Add `PreserveTdnfCache` to `systemconfig` to keep old behavior.
**NO**
- #xxxx
- local build of baremetal and core-efi
> Auto clean tdnf cache

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/disk.go
- toolkit/tools/imagecustomizerapi/disk_test.go
- toolkit/tools/imagecustomizerapi/disksize.go
- toolkit/tools/imagecustomizerapi/disksize_test.go
- toolkit/tools/imagecustomizerapi/partition.go
- toolkit/tools/imagecustomizerapi/partition_test.go
- toolkit/tools/imagecustomizerapi/storage_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
When specifying the disk and partition sizes, allow the suffixes K, M, G, and T which mean KiB, MiB, GiB, and TiB respectively.
This change also forces the user to provide a suffix. Previously, the unsuffixed number meant MiBs. But it should probably be bytes instead. To help with this transition, unsuffixed numbers have been blocked for now. But we may support them in the future.
---
NO
> Image Customizer: Support disk size suffixes.

- toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/main_test.go
A lot of code within the image customizer requires a base image to work correctly. So, this change adds the option to pass in a core-efi image file to the tests that can be used as a base image. If the image isn't provided then the tests that need it will be skipped.
The tests that previously used a fake image have been changed to use the real base image. And a new test has been added to test partition customization.
---
NO
- Ran the tests that were added.
> Image Customizer: Functional tests boilerplate.

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/disk.go
- toolkit/tools/imagecustomizerapi/disk_test.go
- toolkit/tools/imagecustomizerapi/disksize.go
- toolkit/tools/imagecustomizerapi/disksize_test.go
- toolkit/tools/imagecustomizerapi/partition.go
- toolkit/tools/imagecustomizerapi/partition_test.go
- toolkit/tools/imagecustomizerapi/partitionsize.go
- toolkit/tools/imagecustomizerapi/partitionsize_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
Currently, to specify that a partition fills up the remainer of the disk, the user must omit both the `end` and `size` field. This change allows the user to set the `size` field to `grow`.
---
NO
> Image Customizer: Support explicit grow partition size.

- toolkit/scripts/imggen.mk
- toolkit/tools/go.mod
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imagegen/installutils/installutils_test.go
- toolkit/tools/imager/imager.go
---
This PR introduces a new functionality to Azure Linux tooling which generates a file `/etc/image-id` to contain the metadata for the images as they are built in the pipelines. 
Background:
We are adding a new file called image-id inside the /etc directory which includes the metadata for the image.
There are 3 fields in this file. Below is an example of this file's content:
```
BUILD_NUMBER=""       # ["3.0.20240320-3.0-531186", "2.0.20240225-fasttrack-513397", "local"]
IMAGE_BUILD_DATE=""   # ["YYYYMMDDHHMMSS"]
IMAGE_UUID=""         # ["6746853c-e6e6-11ee-9319-0242ac110002"]
```
BUILD_NUMBER is the build number of the ado pipeline …
> add image-id file in etc dir

- toolkit/imageconfigs/baremetal.json
---
With the move to Azure Linux 3.0, the selinux needs to be updated to work with the new versions of the packages.
To unblock testing and development until the selinux policies are updated, we are setting selinux to permissive for now.
I've opened a bug to re-enable selinux after fixing the known scenarios: https://dev.azure.com/mariner-org/ECF/_workitems/edit/7476
- [baremetal image: temporarily set selinux to permissive](https://github.com/microsoft/azurelinux/commit/be3c91c557b8e1142e41968509a581ab3eff179b)
**YES**
- [7416: azl 3.0 qemu guest image is failing 2 image-tests](https://dev.azure.com/mariner-org/ECF/_workitems/edit/7416)
- n/a
- Privately built the image, booted …
> Temporarily set selinux to permissive in the baremetal image to unblock tests

- SPECS/kata-packages-uvm/kata-packages-uvm.spec
---
Adds cifs-utils package. The package is needed to support cifs mount in kernel-uvm.
- kata-packages-uvm: add cifs-utils to the list of dependencies
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=548501&view=results
> [kata-cc] kata-packages-uvm: add cifs-utils as dependency 

- SPECS/ruby/CVE-2024-27280.patch
- SPECS/ruby/CVE-2024-27281.patch
- SPECS/ruby/ruby.spec
---
Patch CVE-2024-27280 and CVE-2024-27281 in gem files bundled with ruby.
- Change: ruby: patch CVE-2024-27280 and CVE-2024-27281
**NO**
- https://portal.microsofticm.com/imp/v3/incidents/incident/490845437/summary
- https://nvd.nist.gov/vuln/detail/CVE-2024-27280
- https://www.ruby-lang.org/en/news/2024/03/21/buffer-overread-cve-2024-27280/
- https://nvd.nist.gov/vuln/detail/CVE-2024-27281
- https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=549505&view=results
> ruby: patch CVE-2024-27280 and CVE-2024-27281

- .github/workflows/validate-cg-manifest.sh
---
Increase the timeout in the "Check Package CGManifests" PR check from 2 seconds to 30 seconds.
Some sites are slow to respond and take more than 2 seconds to respond.
Example failing in 2 seconds:
```
$ wget --secure-protocol=TLSv1_2 --spider --timeout=2 --tries=10 https://code.opensuse.org/adrianSuSE/cal
10n/blob/factory/f/cal10n-0.8.1.10.tar.xz
Spider mode enabled. Check if remote file exists.
--2024-04-12 23:21:08--  https://code.opensuse.org/adrianSuSE/cal10n/blob/factory/f/cal10n-0.8.1.10.tar.xz
Resolving code.opensuse.org... 195.135.223.57, 2a07:de40:b27e:1204::13
Connecting to code.opensuse.org|195.135.223.57|:443... …
```
> increase timeout for "Check Package CGManifests" github check

- .github/workflows/validate-cg-manifest.sh
---
Increase the timeout in the "Check Package CGManifests" PR check from 2 seconds to 30 seconds.
Some sites are slow to respond and take more than 2 seconds to respond.
Example failing in 2 seconds:
```
$ wget --secure-protocol=TLSv1_2 --spider --timeout=2 --tries=10 https://code.opensuse.org/adrianSuSE/cal
10n/blob/factory/f/cal10n-0.8.1.10.tar.xz
Spider mode enabled. Check if remote file exists.
--2024-04-12 23:21:08--  https://code.opensuse.org/adrianSuSE/cal10n/blob/factory/f/cal10n-0.8.1.10.tar.xz
Resolving code.opensuse.org... 195.135.223.57, 2a07:de40:b27e:1204::13
Connecting to code.opensuse.org|195.135.223.57|:443... …
```
> [main] increase timeout for "Check Package CGManifests" github check

- SPECS/ruby/CVE-2024-27280.patch
- SPECS/ruby/CVE-2024-27281.patch
- SPECS/ruby/ruby.spec
---
Cherry-pick #8784 to `fasttrack/2.0`
Patch CVE-2024-27280 and CVE-2024-27281 in gem files bundled with ruby.
- Change: ruby: patch CVE-2024-27280 and CVE-2024-27281
**NO**
- https://portal.microsofticm.com/imp/v3/incidents/incident/490845437/summary
- https://nvd.nist.gov/vuln/detail/CVE-2024-27280
- https://www.ruby-lang.org/en/news/2024/03/21/buffer-overread-cve-2024-27280/
- https://nvd.nist.gov/vuln/detail/CVE-2024-27281
- https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=549505&view=results
> [fasttrack-2.0] ruby: patch CVE-2024-27280 and CVE-2024-27281 (#8784)

- toolkit/tools/scheduler/schedulerutils/buildworker.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
Cherry-pick of #8777.
This fixes and occasional issue, where packages depending on an updated version of another package would not get triggered to re-build despite cascading rebuilds being set to 1.
The issue was caused by the order, in which we verify if a rebuild is needed and propagate the "freshness" of a node. Scenario where the issue reproed:
- Packages: `A`, `B`, and `X`.
- Both `A` and `B` were modified in the PR.
- `X` has a build-time dependency on `B`.
- **`B` has a build-time dependency on `A`.**
- Cascading rebuilds are set to 1 meaning "rebuild only the first level of packages depending on the modified packages".
Expected:
In this scenario `A` and `B` should build, …
> Fixing cascading rebuilds. (CP: #8777)

- SPECS/cloud-init/cloud-init.signatures.json
- SPECS/cloud-init/cloud-init.spec
- SPECS/cloud-init/overrideDatasourceDetection.patch
- cgmanifest.json
---
Up epoch to downgrade cloud-init to 23.3. cloud-init 23.4 introduced a change which requires rfc3442 support. Currently, Mariner's dhclient does not fully support rfc3442. This leads to failure in establishing global routing. Downgrade cloud-init to remove rfc3442 requirement.
Note that the diff in version of `23.3` and not `23.3.3` as mentioned in source url is intentional 
- Downgrade to 23.3 using epoch 1
- Add back overrideDatasourceDetection.patch
- Remove ci-Pin-pytest-8.0.0.patch as pytest is pinned to pytest<=7.3.1
- Remove Retain-exit-code-in-cloud-init-status-for-recoverabl.patch
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/49661506
- Pipeline build id …
> Downgrade cloud-init to 23.3 via epoch 

- SPECS/libreswan/capng_apply.patch
- SPECS/libreswan/libreswan.spec
---
Fix `libreswan` build break by adding upstream patch.
```
ERROR - /usr/src/azl/BUILD/libreswan-4.7/programs/pluto/plutomain.c:1718:9: error: ignoring return value of 'capng_apply' declared with attribute 'warn_unused_result' [-Werror=unused-result]
```
- Fix `libreswan` build break
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552489&view=results
> libreswan: fix build break

- toolkit/scripts/imggen.mk
- toolkit/tools/go.mod
- toolkit/tools/imagegen/installutils/installutils.go
- toolkit/tools/imagegen/installutils/installutils_test.go
- toolkit/tools/imager/imager.go
---
This PR introduces a new functionality to Azure Linux tooling which generates a file `/etc/image-id` to contain the metadata for the images as they are built in the pipelines. 
Corresponding change in main: https://github.com/microsoft/azurelinux/pull/8663.
Background:
We are adding a new file called image-id inside the /etc directory which includes the metadata for the image.
There are 3 fields in this file. Below is an example of this file's content:
```
BUILD_NUMBER=""       # ["3.0.20240320-3.0-531186", "2.0.20240225-fasttrack-513397", "local"]
IMAGE_BUILD_DATE=""   # ["YYYYMMDDHHMMSS"]
IMAGE_UUID=""         # …
```
> functionality to add image-id file in etc dir

- SPECS/rubygem-addressable/rubygem-addressable.spec
- SPECS/rubygem-fluentd/rubygem-fluentd.spec
---
Update `rubygem-fluentd` requirements based on https://github.com/fluent/fluentd/blob/v1.16/fluentd.gemspec
This resolves the following:
```
"Unresolved dependencies:"
"--> rubygem-http_parser.rb:C:'<'V:'0.7.0',C2:''V2:''"
```
Update `rubygem-addressable` requirements based on # https://github.com/sporkmonger/addressable/blob/addressable-2.8.5/addressable.gemspec
This resolves the following:
```
"Unresolved dependencies:"
"--> rubygem-public_suffix:C:'<'V:'5.0',C2:''V2:''"
```
- Update `rubygem-fluentd` requirements
- Update `rubygem-addressable` requirements
**NO** …
> fix rubygem-fluentd and rubygem-addressable requirements 
