microsoft/azurelinux

SPECS/kernel/CVE-2023-2162.nopatch, SPECS/kernel/CVE-2023-2166.nopatch, SPECS/kernel/CVE-2023-2177.nopatch, SPECS/kernel/CVE-2023-2194.nopatch, SPECS/kernel/CVE-2023-28327.nopatch, SPECS/kernel/CVE-2023-28328.nopatch
---
Nopatch CVE-CVE-2023-2162, CVE-2023-2166, CVE-2023-2177, CVE-2023-2194, CVE-2023-28327, CVE-2023-28328
- Nopatch CVE-CVE-2023-2162, CVE-2023-2166, CVE-2023-2177, CVE-2023-2194, CVE-2023-28327, CVE-2023-28328
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-CVE-2023-2162
- https://nvd.nist.gov/vuln/detail/CVE-2023-2166
- https://nvd.nist.gov/vuln/detail/CVE-2023-2177
- https://nvd.nist.gov/vuln/detail/CVE-2023-2194
- https://nvd.nist.gov/vuln/detail/CVE-2023-28327
- https://nvd.nist.gov/vuln/detail/CVE-2023-28328
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=354149&view=logs&j=e3e4c90c-f47a-552d-9399-c51e3747740e&t=9 …
=> Nopatch kernel for CVE-CVE-2023-2162, CVE-2023-2166, CVE-2023-2177, CVE-2023-2194, CVE-2023-28327, CVE-2023-28328

SPECS/openvswitch/CVE-2023-1668.patch, SPECS/openvswitch/openvswitch.spec
---
To fix CVE-2023-1668
- Add patch for CVE-2023-1668
- Bump release version to 2.17.5-2
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-1668
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=353849&view=results)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=353850&view=results)
=> openvswitch: Add patch for CVE-2023-1668

.github/CODEOWNERS
---
The change adds codeowners for core packages, specifically packages for bootloaders, kernel, dracut, systemd, debug tools, openssl, package managers, container runtimes, virtualization, and provisioning. Aim is to have dedicated reviews from these codeowners to improve the quality of these packages.
- Add codeowners to tie cbl-mariner teams to specific bootloaders, kernel, dracut, systemd, debug tools, openssl, package managers, container runtimes, virtualization, and provisioning
**NO**
=> CODEOWNERS: Add owners for core packages

SPECS-EXTENDED/frr/frr.spec
… create_package (available) for FRR installation
---
This PR removes an unavailable macro (sysusers_create_compat) and replaces it with an available variant (sysusers_create_package) that allows FRR to be successfully installed from the extended repo.
Version was incremented, and the above mentioned macros were corrected, allowing successful installation.
This does not affect the toolchain.
- Internally this is bug #44265925
This change has been tested for package installation and execution on a clean Mariner VM
=> Correct FRR installation macro to resolve installation errors.

SPECS/kernel/CVE-2023-2006.nopatch, SPECS/kernel/CVE-2023-2019.nopatch
---
Nopatch kernel for CVE-2023-2006, CVE-2023-2019
- CVE-2023-2006, CVE-2023-2019
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2006
- https://nvd.nist.gov/vuln/detail/CVE-2023-2019
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355982&view=logs&j=e3e4c90c-f47a-552d-9399-c51e3747740e&t=97a0aa58-1cd5-5faa-2410-5d8e670febf7
=> Nopatch kernel for CVE-2023-2006, CVE-2023-2019

SPECS/moby-engine/moby-engine.signatures.json, SPECS/moby-engine/moby-engine.spec, cgmanifest.json
---
Upgrades moby-engine to version 20.10.24 to be consistent with the current moby-cli version. Moby-cli was updated in the previous release update to the current version and moby-engine was missed.
- moby-engine
**NO**
- Buddy Build AMD64 Pipeline Build Id: [355933](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355933&view=results).
- Buddy Build ARM64 Pipeline Build Id: [355948](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=355948&view=results).
=> Cblmargh/moby engine upgrade to 20.10.24 main

SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec, SPECS/kernel-hci/0027-mstflint-This-driver-enables-under-the-secure-boot.patch, SPECS/kernel-hci/config, SPECS/kernel-hci/kernel-hci.signatures.json, SPECS/kernel-hci/kernel-hci.spec
---
This PR adds the mstflint kernel driver for secure boot as a patch into the kernel-hci source tree.
**NO**
- Pipeline build id: [359641](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=359641&view=results)
- Upgraded kernel with kernel-hci-5.15.110.1-2.cm2.x86_64.rpm, disabled the secure boot and checked the module is loaded.
=> Add mstflint Driver to the kernel-hci

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade to 9.0.1562 to address CVE-2023-2609 & CVE-2023-2610
- Upgrade to 9.0.1562 to address CVE-2023-2609 & CVE-2023-2610
**NO**
- #5516
- https://nvd.nist.gov/vuln/detail/CVE-2023-2609
- https://nvd.nist.gov/vuln/detail/CVE-2023-2610
- Local build
Buddy Build: validating
- [AMD](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=362085&view=logs&s=444ee1b5-8b3f-5598-a629-e88326f0c2f9)
- [ARM](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=362086&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774)
=> vim: upgrade to 9.0.1562 to address CVE-2023-2609 & CVE-2023-2610

SPECS/nodejs/nodejs.spec, SPECS/nodejs/nodejs18.spec
This reverts commit b8ea8ffa33bd9c2437044f3da4f9bd3338d8a5ff.
---
Revert #5463 
While using ninja does drastically speed up the nodejs builds, it also seems to cause out of memory issues when building all packages, especially on ARM64.
- Revert nodejs-16 and nodejs18 changes to build with ninja
**NO**
=> Revert "nodejs: use ninja to speed up build (#5463)"

SPECS/chrony/chrony.spec, SPECS/nodejs/nodejs.spec, SPECS/nodejs/nodejs18.spec, SPECS/rust/CVE-2023-27477.patch, SPECS/rust/rust.spec
Merge from main to fix nodejs build break on ARM64.  Also pick up additional CVE fixes.
=> Merge from main to fix nodejs build break on ARM64

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-license-map.yml, .github/workflows/check-livepatches.yml, .github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/check-spec.yml, .github/workflows/check-static-glibc.yml, .github/workflows/go-test-coverage.yml, .github/workflows/lint-specs.yml, .github/workflows/quickstart_1.0.yml, .github/workflows/quickstart_2.0.yml, SPECS-EXTENDED/whois/whois.spec
---
Updating PR checks to use the latest versions of GitHub's tasks.
- Updated all `actions/checkout` tasks to version 3.
- Updated all `actions/setup-python` tasks to version 4.
No.
- PR checks run as part of this PR.
=> Updated PR checks

SPECS/frr/CVE-2023-31490.patch, SPECS/frr/frr.spec
---
Patch package frr with CVE-2023-31490
- CVE-2023-31490
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-31490
Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=364983&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=364982&view=results)
=> Patch frr with CVE-2023-31490

.github/CODEOWNERS
---
Symcrypt and KeysInUse are OpenSSL engines, so changes to these should be reviewed by our openssl maintainers groups.
**NO**
=> codeowners: Add maintainers for openssl engines

SPECS/kata-containers-cc/kata-containers-cc.spec
---
- Use static resource management by default instead of dynamic resource management
- Avoid building OpenSSL from vendored code and use the host system's openssl-devel package
- 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0464
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=366512&view=results
=> Use static resource management and build using the host OpenSSL for kata-containers-cc

toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
---
There is a race condition where we check if the cdrom mount is created, if not we go to mount it with `retry`. But the mount might be established during that period, and `mount` returns an error code if its target is already mounted so the retry will never exit early. Switch to using `eval` so we can pass a more complex bash command: `{ <check> || mount... ; }` which will first test the mount before trying to remount an existing mountpoint.
- Check if the ISO cdrom mount has been created every time we retry
**NO**
- Local build with Hyper-V testing
=> Fix ISO mount retry race condition

SPECS/kernel-mshv/0001-Implement-dom0-kernel-patch-for-loader-as-of-0524.patch, SPECS/kernel-mshv/kernel-mshv.spec
---
Support new lxhvloader by applying a patch with the current changes from our topic branch for linux-dom0, pending upstreaming.
This change is backwards-compatible with the old loader.
Introduces mariner-mshv.cfg which symlinks to the kernel used for the
dom0 host.
Signed-off-by: Cameron Baird <cameronbaird@microsoft.com>
- patch kernel-mshv with HV loader patch as of 20230412
NO
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=367174&view=results
=> [kernel-mshv]: Support new lxhvloader

SPECS/sysstat/CVE-2023-33204.patch, SPECS/sysstat/sysstat.spec
---
Patch CVE-2023-33204.
NOTE: The [patch linked on NIST](https://github.com/sysstat/sysstat/commit/954ff2e2673cef48f0ed44668c466eab041db387) has a typo which fails to compile. I used the merged [commit ](https://github.com/sysstat/sysstat/commit/6f8dc568e6ab072bb8205b732f04e685bf9237c0) instead. However, git shows the BAD commit when using .patch but the good commit when using .diff. Spooky
- Patch sysstat for CVE-2023-33204
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-33204
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=367588&view=results
=> Patch sysstat for CVE-2023-33204

SPECS/libtiff/CVE-2023-2731.patch, SPECS/libtiff/libtiff.spec
---
Patch libtiff for CVE-2023-2731
- Patch libtiff
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2731
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=367597&view=results
=> Patch libtiff for CVE-2023-2731

SPECS/qt5-qtbase/CVE-2023-24607.patch, SPECS/qt5-qtbase/qt5-qtbase.spec, SPECS/qt5-qtsvg/CVE-2023-32573.patch, SPECS/qt5-qtsvg/qt5-qtsvg.spec, cgmanifest.json
---
- Add remaining change for CVE-2023-24607, original diff file can be downloaded from `download.qt.io`
- Add patch for CVE-2023-24607 affecting qt5-qttools
- CVE-2023-24607
- CVE-2023-32573
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-24607
- https://nvd.nist.gov/vuln/detail/CVE-2023-32573
- Pipeline builds:
- x86_64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=359810&view=results
- aarch64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=359811&view=results
=> qt5: Patch CVE-2023-24607, CVE-2023-32573

SPECS-EXTENDED/cassandra/cassandra.signatures.json, SPECS-EXTENDED/cassandra/cassandra.spec, cgmanifest.json
---
Upgrade version to 4.0.10 to address CVE-2023-30601
- Change
Upgrade version to 4.0.10 to address CVE-2023-30601
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-30601
Local build.
=> Upgrade version to 4.0.10 to address CVE-2023-30601

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json, SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, SPECS/SymCrypt/SymCrypt.signatures.json, SPECS/SymCrypt/SymCrypt.spec, cgmanifest.json
---
- In preparation for FIPS certification, rev SymCrypt version
- Also bump SymCrypt-OpenSSL version to pick up latest changes
- Add basic %check sections to the SPECs
- SymCrypt upgraded to v103.0.1
- SymCrypt-OpenSSL upgraded to v1.3.0
**NO**
- Local build to verify that Mariner build still working as expected. Brought updated files into CBL-MarinerTutorials and built image containing the updated packages successfully.
=> Update SymCrypt and SCOSSL SPECs

SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.signatures.json, SPECS/KeysInUse-OpenSSL/KeysInUse-OpenSSL.spec, cgmanifest.json
---
The KeysInUse engine was updated to prevent being loaded by applications statically linked to OpenSSL. Due to the interaction between the engine and libcrypto, engine load by statically linked applications can lead to a crash. Normally KeysInUse will only be loaded by dynamically linked applications on Mariner, via a patch to libcrypto, but the engine still should not load for statically linked applications via other means (e.g. openssl config or the dynamic engine)
- Updated KeysInUse-OpenSSL.SPEC to the latest sources, which include a fix to prevent loading by applications statically linked to OpenSSL.
- Updated signatures and cgmanifest files to reflect the new sources
NO
- …
=> Upgrade KeysInUse-OpenSSL to 0.3.3

SPECS/cryptsetup/cryptsetup.spec
---
Removes cryptsetup-ssh-token package since it creates a circular build dependency through its reliance on libssh-devel.
- Remove cryptsetup-ssh-token
**NO**
- Pipeline build id: 369589
=> Remove new cryptsetup-ssh-token package which creates circular build dependency

SPECS/cryptsetup/cryptsetup.spec
---
Fix extra line continuation in cryptsetup build spec causing build failure.
- Fix extra line continuation in cryptsetup build spec
**YES/NO**
- Pipeline build id: 370091
=> Fix extra line continuation in cryptsetup build spec

SPECS/containerized-data-importer/containerized-data-importer.signatures.json, SPECS/containerized-data-importer/containerized-data-importer.spec, cgmanifest.json
---
This PR upgrades cdi to v1.55.0
- Upgrade cdi to v1.55.0
**NO**
- #xxxx
- BuddyBuild: [Link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=370331&view=results)
- Pipeline build id: Pending
- Validation golden container test: Pending
=> Upgrading cdi to v1.55.0

SPECS/llvm/llvm.spec, SPECS/llvm/llvm16.spec
---
Modify llvm and llvm16 to limit to 2 parallel compile jobs to avoid running out of memory in build. This should resolve OOM errors in ARM64 builds that are causing the build agents to disconnect ("##[error]Agent has stopped responding. RequestId:")
- Change llvm
- Change llvm16
**NO**
- Pipeline build id: 370457
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=370573&view=results
=> llvm: limit 2 compile jobs in parallel

SPECS/gnupg2/CVE-2022-34903.patch, SPECS/gnupg2/gnupg2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch gnupg2 CVE-2022-34903
- Patch gnupg2 CVE-2022-34903
YES
- https://nvd.nist.gov/vuln/detail/CVE-2022-34903
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=370139&view=results
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=370140&view=results
=> Patch gnupg2 CVE-2022-34903

SPECS/kernel-mshv/kernel-mshv.spec
---
Align mariner_cmdline_mshv with old linuxloader's config. This was originally in linuxloader.conf and parsed by bootmgfw.efi. Now pass the cmdline to the grub menuentry in the standard mariner way. 
- Align mariner_cmdline_mshv
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=369162&view=results
=> Align mariner_cmdline_mshv with old linuxloader's config

toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md
---
Change prerequisite instructions to recommend installing the latest golang version on Mariner (which is currently 1.19). For Ubuntu build machines, the recommendation is also golang 1.19.
- Change mariner prereqs to install latest golang
- Change ubuntu prereqs to install golang 1.19
**NO**
- N/A, documentation change
=> Documentation: Update recommended golang version

SPECS/qt5-qtsvg/CVE-2023-32573.patch
---
- A missing newline character at the end of the patch file caused a failure in applying the patch
- Add newline character to the end of CVE-2023-32573.patch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-32573
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372543&view=results
=> qt5-qtsvg: fix file format for CVE-2023-32573 patch

SPECS/cmake/CVE-2023-23914-0001-share-add-sharing-of-HSTS-cache-among-handles.patch, SPECS/cmake/CVE-2023-23914-0002-hsts-handle-adding-the-same-host-name-again.patch, SPECS/cmake/cmake.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch vendored curl inside cmake for CVE-2023-23914
Patch vendored curl inside cmake for CVE-2023-23914
YES
- https://nvd.nist.gov/vuln/detail/CVE-2023-23914
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372469&view=results
=> Patch cmake vendored curl for CVE-2023-23914

SPECS/c-ares/c-ares.signatures.json, SPECS/c-ares/c-ares.spec, SPECS/grpc/grpc.spec, SPECS/nodejs/nodejs.spec, cgmanifest.json
---
Upgrade c-ares and its dependencies to resolve CVE-2023-32067, CVE-2023-31130, and CVE-2023-31147
- Upgrade c-ares
- Rebuild dependent packages
- Build nodejs against the system c-ares
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-32067
- https://nvd.nist.gov/vuln/detail/CVE-2023-31130
- https://nvd.nist.gov/vuln/detail/CVE-2023-31147
- Pipeline build id AMD64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372485&view=results
- Pipeline build id ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=372573&view=results
=> Upgrade c-ares for CVE-2023-32067, CVE-2023-31130, and CVE-2023-31147

SPECS/curl/CVE-2023-28322.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Apply patch to address CVE-2023-28322
- Add patch for CVE-2023-28322
- Update toolkit manifest versions
YES
- https://nvd.nist.gov/vuln/detail/CVE-2023-28322
- https://github.com/curl/curl/commit/7815647d6582c0a4900be2e1de
[AMD64 BuiltToolchain
](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373142)
[ARM64 BuildToolchian](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373021)
[AMD64 BuildRpms](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373193): In Progress
[ARM64 BuildRpms ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373173): In Progress
=> Patch curl to address CVE-2023-28322

SPECS/haproxy/CVE-2023-25725-http-properly-reject-empty-http-header-.patch, SPECS/haproxy/haproxy.spec
Patch haproxy for CVE-2023-25725
---
Patch haproxy for CVE-2023-25725
- Change
- Change
- Change
Patch haproxy for CVE-2023-25725
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-25725
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=373219&view=results
=> Patch haproxy for CVE-2023-25725

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec, SPECS/grub2/CVE-2022-3775.patch, SPECS/grub2/grub2.spec
---
Cherry-pick and apply CVE-2022-3775 in the grub2 package from 1.0 branch.
- Patch CVE-2022-3775 in the grub2 package
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-3775
- https://cvedashboard.azurewebsites.net/#/security/CVE-2022-3775
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=374260&view=results
=> Patch CVE-2022-3775 in grub2

SPECS/opensc/CVE-2023-2977.patch, SPECS/opensc/opensc.spec
---
Patch CVE-2023-2977 in opensc
- Patch CVE-2023-2977 in opensc
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2977
- Local package build with %check
- SUCCEEDED - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=376602&view=results
=> Patch CVE-2023-2977 in opensc

SPECS/python-requests/CVE-2023-32681.patch, SPECS/python-requests/python-requests.spec
---
Patch CVE-2023-32681 in python-requests
- CVE-2023-32681
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-32681
Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=376418&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=376417&view=results)
=> Patch CVE-2023-32681 in python-requests

SPECS/openssh/CVE-2023-28531-upstream-include-destination-constraints-for-smartca.patch, SPECS/openssh/openssh.spec
---
Patch openssh handling of smartcard details for CVE-2023-28531
- Change
- Change
- Change
Patch openssh handling of smartcard details for CVE-2023-28531
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-28531
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=375177&view=results
=> Patch openssh handling of smartcard details for CVE-2023-28531

SPECS/yasm/CVE-2023-31975.patch, SPECS/yasm/yasm.spec
---
Patch CVE-2023-31975 in yasm
- Patch CVE-2023-31975 in yasm
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-31975
- SUCCEEDED - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=377265&view=results
=> Patch CVE-2023-31975 in yasm

SPECS/filesystem/filesystem.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- [] The toolchain has been rebuilt successfully (or no changes were made to it)
---
The location /usr/local/sbin is part of FHS (Filesystem Hierarchy Standard) however is missing from the package, registering this standard path with the filesystem package.
- Add /usr/local/sbin  to %files in the filesystems package
**YES**
- rpmbuild -bb SPEC/filesystem.spec
- Compared package result
```
azaugg@azaugg-ld77 [ ~/rpmbuild/RPMS/x86_64 ]$ rpm -qpl filesystem-1.1-13.cm2.x86_64.rpm | grep local | grep bin
/usr/local/bin
azaugg@azaugg-ld77 [ ~/rpmbuild/RPMS/x86_64 ]$ rpm -qpl filesystem-1.1-14.cm2.x86_64.rpm|grep local|grep bin
/usr/local/bin
/usr/local/sbin
```
=> Registering /usr/local/sbin within filesystem package

SPECS/qt5-qtbase/CVE-2023-32762.patch, SPECS/qt5-qtbase/qt5-qtbase.spec
---
- Resolve CVE-2023-36762 for qy5-qtbase
- Add patch to resolve CVE-2023-36762
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-36762
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=376789&view=results
=> [1.0] Fix qt5-qtbase CVE-2023-36762

SPECS/qt5-qtbase/CVE-2023-32763.patch, SPECS/qt5-qtbase/qt5-qtbase.spec
---
- Resolve qt5-qtbase CVE-2023-32763
- Add patch to resolve CVE-2023-32763
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-32763
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=377870&view=results
=> Fix qt5-qtbase CVE-2023-32763

SPECS/mozjs60/CVE-2023-34411.patch, SPECS/mozjs60/mozjs60.spec
---
Patch CVE-2023-34411 in mozjs60
- Patch CVE-2023-34411 in mozjs60
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-34411
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=378660
=> Patch CVE-2023-34411 in mozjs60

SPECS/yajl/CVE-2023-33460.patch, SPECS/yajl/yajl.spec
---
Patch CVE-2023-33460.patch in yajl
- CVE-2023-33460
*NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-33460
Buddy Build
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=379102&view=results)
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=379103&view=results)
=> Patch CVE-2023-33460.patch in yajl

SPECS/libcap/CVE-2023-2603.patch, SPECS/libcap/libcap.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add patch to resolve CVE-2023-2603
- Add patch to resolve CVE-2023-2603
YES
- https://nvd.nist.gov/vuln/detail/CVE-2023-2603
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=380880&view=results
=> [1.0] Fix libcap CVE-2023-2603

SPECS/postgresql/postgresql.signatures.json, SPECS/postgresql/postgresql.spec, cgmanifest.json
---
Fix CVE-2023-2454, CVE-2023-2455 and CVE-2022-41862 by upgrading
- Fix CVE-2023-2454, CVE-2023-2455 and CVE-2022-41862 by upgrading
**NO**
- CVE-2023-2454
- CVE-2023-2455
- CVE-2022-41862
- https://nvd.nist.gov/vuln/detail/CVE-2023-2454
- https://nvd.nist.gov/vuln/detail/CVE-2023-2455
- https://nvd.nist.gov/vuln/detail/CVE-2022-41862
- 381256
=> Fix CVE-2023-2454, CVE-2023-2455 and CVE-2022-41862 by upgrading

SPECS/libcap/libcap.spec
---
- Fix a typo in the changelog of libcap which causes local build failure
- Fix a typo in the changelog of libcap spec
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=381581&view=results
=> Minor fix of typo in libcap spec changelog

.github/policies/resourceManagement.yml, SPECS-EXTENDED/kde-filesystem/kde-filesystem.spec
---
While working on #5710 @mfrw noticed we were missing changes to the `SPECS-EXTENDED` folder to be labeled as `Packaging`. Fixing this here.
- Added `SPECS-EXTENDED` changes to be labeled as packaging.
- YAML formatting changes.
No.
- #5710
- N/A.
=> Added extended specs to GitOps config.

SPECS/cloud-init/CVE-2023-1786.patch, SPECS/cloud-init/cloud-init.spec
---
add upstream patch for CVE-2023-1786 cloud-init
- add [upstream patch](https://github.com/canonical/cloud-init/commit/a378b7e4f47375458651c0972e7cd813f6fe0a6b) for CVE-2023-1786 cloud-init
NO
- #xxxx
https://nvd.nist.gov/vuln/detail/CVE-2023-1786
- Local image build
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=382279&view=results
=> add patch for CVE-2023-1786 cloud-init

SPECS/postgresql/postgresql.signatures.json, SPECS/postgresql/postgresql.spec, cgmanifest.json
---
Fix CVE-2023-2454 by upgrading postgresql to 12.15
- Fix CVE-2023-2454 by upgrading postgresql to 12.15
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2454
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=383048&view=results
=> Fix CVE-2023-2454 by upgrading postgresql to 12.15

SPECS/selinux-policy/0037-cloudinit-Add-permissions-derived-from-sysadm.patch, SPECS/selinux-policy/0039-modutils-Temporary-fix-for-mkinitrd-dracut.patch, SPECS/selinux-policy/selinux-policy.spec
---
- Fix missing role associations in cloud-init patch.
- Fix missing require in mkinitrd patch.
**NO**
- Pipeline build id: 382541
=> selinux-policy: Fix issues in patches.

.pipelines/prchecks/PackageBuildPRCheck.yml, .pipelines/templates/PackageBuild.yml
INCOMPLETE, DON'T MERGE AND/OR REVIEW!
=> Added RPM builds to PR checks.

SPECS/bash/bash.spec, SPECS/filesystem/filesystem.spec
---
We consider changelog dates to be breaking for the purposes of packaging toolchain packages (Did we modify the Mariner parser to not error out on these while the Ubuntu version does maybe?)
Thursday July 29th should be Thursday Jun 29.
- Fix dates in toolchain packages `filesystem` and `bash`
**YES**
- Packaged SRPMs for toolchain locally.
-
=> Fix bogus changelog times in filesystem and bash toolchain packages

SPECS/rust/rust.spec
---
This PR adds the clippy tool to the rust package. Clippy is a linter to catch common mistakes and improve Rust code. Like rustfmt (which is already included in the rust package), clippy is commonly used in pipelines to validate that changes conform to a project's code standards.
- Added clippy linter to rust package
**NO?** 
This modifies the _Rust_ toolchain package. I believe doesn't qualify, but someone should confirm.
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=387181&view=results
=> rust: Include clippy linter tool in package

SPECS/apr/CVE-2022-28331.nopatch, SPECS/apr/apr.spec
---
Applies a nopatch for CVE-2022-28331 for `apr` package
- nopatch CVE-2022-28331
- Applied linter changes
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-28331
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=388397&view=results
=> Adding nopatch for CVE-2022-28331 for apr package

SPECS/uclibc-ng/uclibc-ng.signatures.json, SPECS/uclibc-ng/uclibc-ng.spec, cgmanifest.json
---
Upgrade v1.0.41 -> v1.0.43 to address CVE-2022-29503
- Upgrade v1.0.41 -> v1.0.43 to address CVE-2022-29503
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-29503
- Local Build
- Pipeline build id: [unified buddy build](https://dev.azure.com/mariner-org/mariner/_build?definitionId=2110&_a=summary)
=> uclibc-ng: upgrade v1.0.41 -> v1.0.43 to address CVE-2022-29503

SPECS/cloud-init/CVE-2022-2084.patch, SPECS/cloud-init/CVE-2023-1786.patch, SPECS/cloud-init/cloud-init.spec
---
add patches for cloud-init CVE-2022-2084, CVE-2023-1786
- add [upstream patch](https://github.com/canonical/cloud-init/commit/4d467b14363d800b2185b89790d57871f11ea88c#diff-5978682d3313395486da4847761e13e175e6303251fe7ddf81552db99779760eR459) for cloud-init CVE-2022-2084
- modify CVE-2023-1786.patch as it causes issue on azure VM deployment
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-1786
- https://nvd.nist.gov/vuln/detail/CVE-2022-2084
- Pipeline build id: [386924](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=386924&view=results)
- Local package and image build
- Azure VM deployment
=> add patches for cloud-init CVE-2022-2084, CVE-2023-1786

SPECS/cloud-init/CVE-2022-2084.patch, SPECS/cloud-init/CVE-2023-1786.patch, SPECS/cloud-init/cloud-init.spec
* add patch for CVEs
* modify change log
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Merge cloud-init fix into 1.0 branch

SPECS/systemd/serve-stale-0001-resolved-added-serve-stale-feature-implementation-of.patch, SPECS/systemd/serve-stale-0002-resolved-Initialize-until_valid-while-storing-negati.patch, SPECS/systemd/systemd.spec
---
adds functionality to serve stale DNS records
add config param to systemd-resolved to retain dns records after expiry, and serve those stale records to clients if upstream ns is unreachable or reports error
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=390272&view=results
=> Add functionality to serve stale DNS records

SPECS/nodejs/CVE-2022-25883-v18.patch, SPECS/nodejs/nodejs18.spec
---
Patch CVE-2022-25883
- Patch CVE-2022-25883
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-25883
- Local Build
- Pipeline build id: [PR-5810](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=391442&view=results)
=> Patch CVE-2022-25883 for nodejs18

SPECS/nodejs/CVE-2022-25883.patch, SPECS/nodejs/nodejs.spec
---
Patch CVE-2022-25883 in the vendored copy of `semver` used by `npm`, which itself is vendored by `nodejs`.
- Backport upstream patches for inital CVE fix + follow-up bugfixes for initial fix
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-25883
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=392185&view=results)
=> Patch CVE-2022-25883 in nodejs v16

SPECS/nginx/nginx.spec
---
This updates the nginx package, adding the capability to serve gzip compressed static files to clients that cannot decode on the fly. This enables us to significantly reduce the size of static content on disk transparently for consumers. This functionality is the default in many distrobutions.
- Enable building with http_gunzip_module
**NO**
- n/a
- n/a
- local build, validated `gunzup on;` configuration works as expected.
=> build nginx with http_gunzip_module

SPECS/kernel/CVE-2023-23003.nopatch
---
Nopatch CVE-2023-23003. Also solves https://portal.microsofticm.com/imp/v3/incidents/details/405020320/home
- CVE-2023-23003
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-23003
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=392807&view=logs&j=e3e4c90c-f47a-552d-9399-c51e3747740e&t=97a0aa58-1cd5-5faa-2410-5d8e670febf7
=> Nopatch CVE-2023-23003

toolkit/docs/building/building.md, toolkit/scripts/incremental_building.mk, toolkit/scripts/pkggen.mk, toolkit/tools/graphpkgfetcher/graphpkgfetcher.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/timestamp/timestamp_mgr.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/buildlist.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/depsolver.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/initializegraph.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/scheduler/schedulerutils/printresults.go
This reverts commit 27f23fe5c0f367431f14757da3ccf31b7c072c46.
---
[2/3]: reverting #5595 to stabilize our nightly builds.
Previous reverts:
- #5813.
Following PRs to revert:
- #5744.
- Reverted #5813.
No.
- #5843,
- #5813,
- #5595,
- #5744.
- N/A - revert.
=> Revert "Enable the graphpkgfetcher to pull build nodes from upstream..."

SPECS/nghttp2/CVE-2023-35945.patch, SPECS/nghttp2/nghttp2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2023-35945 in `nghttp2`.
- Add upstream fix for CVE-2023-35945 from nghttp2/nghttp2@feb5ff560a4dcbd9a9f83faee41a3c8f9d9940ae
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2023-35945
- https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=394472&view=results)
=> Add upstream patch for CVE-2023-35945 in nghttp2

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade Blobfuse2 to latest version
- Upgrade Blobfuse2 to latest version
**NO**
- #xxxx
- Pipeline build id: 394317
=> Upgrade Blobfuse2 to 2.0.4

toolkit/tools/graphpkgfetcher/graphpkgfetcher.go, toolkit/tools/imagepkgfetcher/imagepkgfetcher.go, toolkit/tools/internal/packagerepo/repocloner/repocloner.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/packagerepo/repoutils/repoutils.go, toolkit/tools/internal/rpm/rpm.go, toolkit/tools/internal/rpm/rpm_test.go, toolkit/tools/internal/rpm/testdata/no_default_package.spec, toolkit/tools/internal/rpm/testdata/with_epoch.spec
---
[1/3] We believe we found the issue introduced in the 3 reverted PRs (#5744, #5595, #5813).
Restoring #5744 **without changes**. Issue detected in #5595 and it will be fixed in the PR restoring that change.
- Restored #5744.
No.
- #5845,
- #5744
- None - no changes since #5744, performed test there.
=> Restored "Fixed the `PACKAGE_CACHE_SUMMARY` build option. (#5744)"

toolkit/docs/building/building.md, toolkit/scripts/incremental_building.mk, toolkit/scripts/pkggen.mk, toolkit/tools/graphpkgfetcher/graphpkgfetcher.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/timestamp/timestamp_mgr.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/buildlist.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/depsolver.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/initializegraph.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/scheduler/schedulerutils/printresults.go
---
[2/3] We believe we found the issue introduced in the 3 reverted PRs (#5744, #5595, #5813).
Restoring #5595 **with 1 change**. The first commit is the original PR, the following commit represent the fix.
- Restored #5744.
- Fixed a merge conflict mishap in `rpmrepocloner.go::clonePackage()`.
No.
- #5595,
- #5844.
- [Full package build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=394878&view=results).
=> Restored "Enable the graphpkgfetcher to pull build nodes from upstream repos if available V2"

toolkit/docs/how_it_works/3_package_building.md, toolkit/tools/depsearch/depsearch.go, toolkit/tools/graphPreprocessor/graphPreprocessor.go, toolkit/tools/graphanalytics/graphanalytics.go, toolkit/tools/grapher/grapher.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/pkggraph/pkggraph_test.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/implicitprovides.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/scheduler/schedulerutils/printresults.go
---
[3/3] We believe we found the issue introduced in the 3 reverted PRs (#5744, #5595, #5813).
Restoring #5813 **without changes**. The only fix was included in the restoration of #5595 (#5851).
- Restored #5813.
No.
- #5813,
- #5843.
- None - restored commit without changes.
=> Restored "Filter implicit run nodes before passing to collapse. (#5813)"

SPECS/kernel/CVE-2023-32250.nopatch, SPECS/kernel/CVE-2023-32254.nopatch
---
- https://nvd.nist.gov/vuln/detail/CVE-2023-32250
- https://nvd.nist.gov/vuln/detail/CVE-2023-32254
=> Address CVE-2023-32250, CVE-2023-32254 with nopatches

SPECS/kernel/CVE-2022-45884.nopatch, SPECS/kernel/CVE-2022-45886.nopatch
---
Nopatch kernel CVE-2022-45884 and CVE-2022-45886
- Nopatch kernel CVE-2022-45884 and CVE-2022-45886
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-45884
- https://nvd.nist.gov/vuln/detail/CVE-2022-45886
=> Nopatch kernel CVE-2022-45884 and CVE-2022-45886

SPECS/kernel/CVE-2022-45884.nopatch, SPECS/kernel/CVE-2022-45886.nopatch, SPECS/kernel/CVE-2023-1295.nopatch
---
Nopatch kernel CVE-2023-1295, CVE-2022-45884, and CVE-2022-45886
- Nopatch kernel CVE-2023-1295, CVE-2022-45884, and CVE-2022-45886
**NO**
https://nvd.nist.gov/vuln/detail/CVE-2022-45884
https://nvd.nist.gov/vuln/detail/CVE-2022-45886
https://nvd.nist.gov/vuln/detail/CVE-2023-1295
=> Nopatch kernel CVE-2023-1295, CVE-2022-45884, and CVE-2022-45886

SPECS/prometheus-adapter/prometheus-adapter.spec, SPECS/prometheus/prometheus.spec
---
Title. It's being done to reduce package sizes and make docker containers smaller.
- Moved `prometheus` docs to `prometheus-docs`
- Moved `prometheus-adapter` docs to `prometheus-adapter-docs`
- Removed `prometheus` from `prometheus-adapter`
NO
- Pipeline build id: 398866
=> Removing prometheus from prometheus-adapter and making separate *-docs packages

SPECS/openssh/CVE-2023-38408.patch, SPECS/openssh/openssh.signatures.json, SPECS/openssh/openssh.spec, cgmanifest.json
---
Fixes CVE-2023-38408 and updates openssh to 8.9p1
- Change: Fixes CVE-2023-38408 and updates openssh to 8.9p1
**YES/NO**
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-38408
- Pipeline build id  AMD: [398755](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=398755&view=results)
- Pipeline build id ARM: [398764](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=398764&view=results)
=> Fixes openssh CVE-2023-38408 and Update openssh to 8.9p1

SPECS/bind/CVE-2023-2828.patch, SPECS/bind/bind.spec
---
Patch CVE-2023-2828 in bind
- CVE-2023-2828
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-2828
Buddy Build
- [ARM64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=397912&view=results)
- [AMD64](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=397953&view=results)
=> Patch CVE-2023-2828 in bind

SPECS/openssh/CVE-2023-38408.patch, SPECS/openssh/openssh.spec
---
Fixes CVE-2023-38408
- Change: Add patch file for CVE-2023-38408
**YES/NO**
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-38408
- Pipeline build id  AMD: [399367](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=399367&view=results)
- Pipeline build id ARM: [399374](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=399374&view=results)
=> Fix openssh CVE-2023-38408

SPECS/kernel/CVE-2023-38427.nopatch, SPECS/kernel/CVE-2023-38430.nopatch, SPECS/kernel/CVE-2023-38431.nopatch
---
Nopatch kernel for CVE-2023-38427, CVE-2023-38430, and CVE-2023-38431
- CVE-2023-38427
- CVE-2023-38430
- CVE-2023-38431
**NO**
=> Nopatch kernel for CVE-2023-38427, CVE-2023-38430, and CVE-2023-38431

SPECS/pcre2/pcre2.signatures.json, SPECS/pcre2/pcre2.spec, cgmanifest.json
---
Updating `pcre2` to fix CVE-2022-41409.
- Updated `pcre2` to version 10.42.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-41409
- Local build.
- [Pipeline buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=400714&view=results).
=> Updated `pcre2` to version 10.42 to fix CVE-2022-41409.

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade Blobfuse2 to latest version
- Upgrade Blobfuse2 to latest version
**NO**
- #xxxx
- Pipeline build id: 401731
=> Upgrade Blobfuse2 to 2.0.5

SPECS/gmp/gmp.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The libgmpxx header file specifically provides C++ bindings for the GMP library. This header file was absent from gmp-devel sub-package of GMP. This PR accomplishes addition of the same.
- gmp: adds c++ support in gmp-devel sub-package)
**YES**
Pipeline build ids: 
- AMD64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=400474&view=results
- ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=400366&view=results
=> gmp: adds c++ support in gmp-devel sub-package

SPECS/nginx/nginx.spec
---
Connfigure with `--with-compat` to enable support for loading modules at runtime.
This is for workitem: [45146424](https://microsoft.visualstudio.com/OS/_workitems/edit/45146424)
- Configure with `--with-compat`
**NO**
- NA
- NA
- Local Build
- BuddyBuild with test: [PR-5913](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=400987&view=results)
=> nginx: configure with `--with-compat` to enable dynamic modules compatibility

toolkit/docs/building/developer-tools.md
---
Add a readme for developer-tool containerized-rpmbuild
- Add a readme for developer-tool containerized-rpmbuild
- The tool was added in https://github.com/microsoft/CBL-Mariner/pull/5855 where it was suggested that a readme section be added
**NO**
=> Readme for containerized-rpmbuild

toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go, toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go, toolkit/tools/imagegen/attendedinstaller/views/hostnameview/hostnameview.go, toolkit/tools/imagegen/diskutils/verity.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/randomization/randomization.go
---
The randomization class requires the caller to pass a class of characters to build random strings with, we should just have a set of well-known consts for these sets.
- Move `randomization.RandomString()` `legalCharacters` strings into the class instead of requiring the callers to redefine them.
**NO**
- local build
=> Refactor randomization to have const input strings

SPECS/valgrind/valgrind.spec
---
Resolve issue with some package tests such as librelp where valgrind did not function properly following this update: https://github.com/microsoft/CBL-Mariner/pull/5795
- Add Requires: glibc-debuginfo to valgrind.spec and bump version
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=404866&view=results
=> Add requires for glibc-debuginfo to valgrind spec

toolkit/scripts/pkggen.mk, toolkit/scripts/tools.mk
---
Reverting removal of the `cache` subdirectory from #5961. Looks like our older buddy build pipelines have a hard-coded dependency on it and they'll need to be updated before this clean-up can be re-added.
- Restored the `cache` subdirectory.
No.
- #5961
- [Pipeline buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=405645&view=results).
=> Restored the `cache` subdirectory.

SPECS/nginx/nginx.spec
---
Enable support for a stream proxy server to work with the SSL/TLS protocol.
For workitem: [45246196](https://microsoft.visualstudio.com/OS/_workitems/edit/45246196/)
- Configure with `--with-stream_ssl_module`
**NO**
- NA
- NA
- Local Build.
- Pipeline Build: [PR-5975](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=405914&view=results)
=> nginx: configure with `--with-stream_ssl_module` to enable support for stream proxy server with SSL/TLS

SPECS/vim/CVE-2023-3896.patch, SPECS/vim/vim.spec
---
Patch CVE-2023-3896 vulnerability in vim
- Add patch to fix CVE-2023-3896 vulnerability in vim
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-3896
- local build
=> Patch CVE-2023-3896 vulnerability in vim

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
Update msft-golang to 1.19.12-1 to address https://nvd.nist.gov/vuln/detail/CVE-2023-39533.
msft-golang contains a submodule pointing at a commit in golang.  Updating the version of msft-golang indirectly updates the version of golang.
Update msft-golang to 1.19.12-1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39533
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=409492&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564
=> Fix CVE-2023-39533: update msft-golang to use 1.19.12 which contains fix

toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md
---
Fixes: 
- #6013
- Add `acl` as an install prerequisite.
**NO**
- NA
- NA
- NA [doc addition only]
=> docs: add `acl` as an install prerequisite

SPECS/ipset/ipset.service, SPECS/ipset/ipset.signatures.json, SPECS/ipset/ipset.spec
- [] The toolchain has been rebuilt successfully (or no changes were made to it)
---
Fixes ipset systemd unit file. The iptables package provided by Mariner does not have a ip6tables.service. Removing the Before reference.
- Remove reference to ip6tables service file
**NO**
=> ipset systemd unit file points to a non existent service file

SPECS/nginx/nginx.signatures.json, SPECS/nginx/nginx.spec, cgmanifest.json
---
For workitem [45146424](https://microsoft.visualstudio.com/OS/_workitems/edit/45146424/)
- nginx: add otel_ngx_module
- nginx: add otel_ngx_module as a dynamic module
- nginx: add otel_ngx_module subpackage
- nginx: add %license for otel_ngx_module subpackage
**NO**
- #5947
- #5913
- NA
- Local Build.
- Pipeline build: [PR-6012](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=409443&view=results)
PS: I used the new `containerized-build` feature for this and a big kudos to @neha170 for this feature
/cc @christopherco
=> nginx: add otel_ngx_module subpackage

toolkit/resources/assets/grub2/grub.cfg
---
In a world where kata images are produced directly from Mariner marketplace images, we will want to have this part of the grub menuentry already set up. 
- On boot, check for mariner-mshv.cfg (just as we do for mariner.cfg). If present, load_env it.
I don't _think so?_
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=374244&view=results
=> Conditionally load kernel-mshv variables in grub if they are installed.

toolkit/tools/internal/retry/retry.go
---
Saw a failure in this unit test: https://github.com/microsoft/CBL-Mariner/blob/main/toolkit/tools/internal/retry/retry_test.go#L151
If a cancel signal is sent before the retry function is called, we would expect the retry function to always abort immediately. However, the first invocation of the sleep function will be with time=0, and that means that the select may pick either the cancel path OR the sleep path:
``` golang
select {
case <-time.After(delay):
case <-cancel:
cancelled = true
}
```
If we add an outer layer of select that preferentially checks the `cancel` channel we will guarantee the expected behavior here.
- Make `backoffSleep` deterministic when a `cancel` signal …
=> Fix retry backoff sleep non-determinism

toolkit/scripts/containerized-build/resources/mariner.Dockerfile
---
To help improve the developer expeirience w.r.t to the `containerized-build` feature,
add a minimal set of tools, so that we dont have to install them everytime we start.
- Add `git` & `vim` to build container
**NO**
- NA
- NA
- Local build and test
=> toolkit: containerized-build: add vim & git in the build env

toolkit/tools/scheduler/schedulerutils/buildlist.go
@sindhu-karri, what do you think about this? I'd like to keep testing packages triggered to build by the image's package list. Assuming, of course, that the packages have tests.
=> Proposed changes for image building fix

SPECS/heimdal/0001-lib-krb5-krb5_pac_parse-mem-leak-if-pac_header_size-.patch, SPECS/heimdal/0002-kdc-Check-generate_pac-return-code.patch, SPECS/heimdal/0003-kdc-avoid-re-encoding-KDC-REQ-BODY.patch, SPECS/heimdal/CVE-2022-42898.patch, SPECS/heimdal/heimdal.spec
---
Address CVE-2022-42898
- address CVE-2022-42898
- Introduce 3 more patches for misc security fixes.
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-42898
- Local build with/without check.
- Pipeline Build: [PR-6046](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=412559&view=results)
=> heimdal: address CVE-2022-42898

SPECS/telegraf/telegraf.spec
---
- Bump release to rebuild with go 1.20.7
NO
- pipeline build:  https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414228&view=results
=> Bump telegraf release to rebuild with go 1.20.7

SPECS/libreswan/CVE-2023-38710.patch, SPECS/libreswan/CVE-2023-38711.patch, SPECS/libreswan/CVE-2023-38712.patch, SPECS/libreswan/libreswan.spec
---
Backport patches for CVE-2023-38710, CVE-2023-38711, CVE-2023-38712 in libreswan
- Patch CVE-2023-38710, CVE-2023-38711, CVE-2023-38712
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-38710
- https://nvd.nist.gov/vuln/detail/CVE-2023-38711
- https://nvd.nist.gov/vuln/detail/CVE-2023-38712
- Local build succeeded with %check section
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414310&view=results
=> Fix CVE-2023-38710, CVE-2023-38711, CVE-2023-38712 in libreswan

SPECS/json-c/CVE-2021-32292.patch, SPECS/json-c/json-c.spec
---
Apply upstream patch for CVE-2021-32292 in json-c
- Apply upstream patch for CVE-2021-32292 in json-c
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-32292 
- Local package build, %check succeeded.
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=414260&view=results
=> Fix CVE-2021-32292 in json-c

SPECS/httpd/httpd-fix-apache-layout-log-path.patch, SPECS/httpd/httpd.spec
---
The default config.layout being used with Mariner is Apache, which points to non existent log directory. As a result the default httpd config provided with Mariner has an error in it, preventing httpd service from starting
- Patched layout.config and updated log path
- Updated PID path to /run/httpd/httpd.pid so systemd stops complaining about new path
**NO**
- Applied patch to httpd rpm
```
azaugg@azaugg-ld77 [ ~/CBL-Mariner/toolkit ]$ sudo make build-packages -j$(nproc) REBUILD_TOOLS=y SRPM_PACK_LIST="httpd" PACKAGE_REBUILD_LIST="httpd" REFRESH_WORKER_CHROOT=y
Makefile:17: CONFIG_FILE is undefined, defaulting to toolkit's core-efi.json.
make: setfacl: No such file or directory …
```
=> BugFix: httpd.conf log location incorrect

SPECS/kernel/CVE-2023-2007.nopatch
---
This change addresses the CVE-2023-2007 vulnerability. The [upstream fix](https://github.com/torvalds/linux/commit/b04e75a4a8a81887386a0d2dbf605a48e779d2a0) is to remove support entirely. On the off chance someone was still using the driver in the stable release, the patch was not backported as discussed [here](https://lore.kernel.org/stable/2023060702-anemic-grinch-0d3e@gregkh/T/). The stable [fix ](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/daeab37ddb6f7185dd8b0a3497a278c2f011aeb7)resolved some issues including this CVE by removing some functionality.
- Nopatch CVE-2023-2007
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2007
=> Nopatch CVE-2023-2007 for kernel

toolkit/tools/precacher/precacher.go
---
Use the new exponential backoff for the pre-cache tool to reduce network conflicts on systems with restricted networking
- Use retry.RunWithExpBackoff() in precacher.go
**NO**
- Local
=> Make precache also use new backoff

.pipelines/prchecks/PackageBuildPRCheck.yml, toolkit/Makefile, toolkit/scripts/incremental_building.mk
---
We've observed occasional package build failures when CCache was enabled on a larger set of built packages. Disabling it from the quick builds for now until we investigate the issue more closely.
- Disabled CCache for quick builds.
No.
- [Sample PR check runs with disabled CCache.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=415509&view=results)
=> Disabled CCache for quick rebuilds.

SPECS/hwloc/CVE-2022-47022.patch, SPECS/hwloc/hwloc.spec
---
Apply upstream patch for CVE-2022-47022 in hwloc
- Apply upstream patch for CVE-2022-47022 in hwloc
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-47022
- Local package build with successful %check section
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=415443&view=results
=> Patch CVE-2022-47022 in hwloc

toolkit/tools/grapher/grapher.go, toolkit/tools/internal/pkggraph/pkggraph.go
@0xba1a, @sindhu-karri: here are my remaining suggestions to your PR. Please take a look and let me know, if you have questions.
=> Adding suggestions.

SPECS/vim/vim.spec
---
Bumping `vim` for a fast-track build test.
- Bumped `Release` number for `vim`.
No.
- PR check.
=> Dummy `vim` bump.

SPECS/vim/vim.spec
Dummy change to test the cherry-pick bot.
=> Dummy `vim` bump to test the cherry-pick bot.

toolkit/scripts/toolchain/build_mariner_toolchain.sh
---
During incremental toolchain builds it's possible to build no new toolchain packages. In such cases the `tar` command we've used there was creating a non-gzip file. Other tooling expects a gzip file and failed in such cases. Adding a switch to make sure empty tarballs don't break other tooling.
- Added the `-z` switch to the compression command.
Yes.
- Local tests.
=> Making sure we always create gzip file.

toolkit/tools/go.mod, toolkit/tools/go.sum
---
Address CVE-2022-28948 for toolkit
- NA
**Yes**
- https://github.com/microsoft/CBL-Mariner/security/dependabot/8
Cherry Pick of:
- https://github.com/microsoft/CBL-Mariner/pull/6108
- https://nvd.nist.gov/vuln/detail/CVE-2022-28948
- Local Build
=> Bump gopkg.in/yaml.v3 to 3.0.0 to address CVE-2022-28948

SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec, SPECS-EXTENDED/ibus-table/ibus-table.spec, SPECS-EXTENDED/libpmemobj-cpp/libpmemobj-cpp.spec, SPECS-EXTENDED/libuser/libuser.spec, SPECS-EXTENDED/perl-Color-RGB-Util/perl-Color-RGB-Util.spec, SPECS-EXTENDED/pybind11/pybind11.spec, SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec, cgmanifest.json
---
We still had 7 specs inside `SPECS-EXPANDED`, which depended on packages we don't have during test runs. To get our test builds more reliable again, I'm disabling these dependencies - they'll have to be re-enabled as part of our efforts to get to 100% of running and passing package tests.
- Removed missing test-time dependencies from 7 spec files.
No.
- None - simple removal of `BuildRequires`.
=> Disabled missing ptest dependencies for 7 extended specs.

SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec, SPECS-EXTENDED/ibus-table/ibus-table.spec, SPECS-EXTENDED/libpmemobj-cpp/libpmemobj-cpp.spec, SPECS-EXTENDED/libuser/libuser.spec, SPECS-EXTENDED/perl-Color-RGB-Util/perl-Color-RGB-Util.spec, SPECS-EXTENDED/pybind11/pybind11.spec, SPECS-EXTENDED/python-msrestazure/python-msrestazure.spec, SPECS/vim/vim.spec, cgmanifest.json
---
Test `Release` bump for a few packages to verify the fast-track builds.
- Bumped 1 core and 7 extended specs.
No.
- PR check
=> Dummy change for fast-track tests

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-kernel-config.yml, .github/workflows/check-license-map.yml, .github/workflows/check-livepatches.yml, .github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/check-spec.yml, .github/workflows/check-static-glibc.yml, .github/workflows/go-test-coverage.yml, .github/workflows/lint-specs.yml
---
Enabling our standard set of PR check to run for PRs created against the `fasttrack/*` branches.
- Enabled 11 PR checks.
No.
- [PR check against a different PR.](https://github.com/microsoft/CBL-Mariner/pull/6139)
=> Enabled PR checks for the fast-track branches.

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade blobfuse2 to latest version
**NO**
- #xxxx
- Pipeline build id: 417346
=> Update blobfuse2 to 2.1.0

SPECS-EXTENDED/dovecot/dovecot-2.1.10-waitonline.patch, SPECS-EXTENDED/dovecot/dovecot-2.2.20-initbysystemd.patch, SPECS-EXTENDED/dovecot/dovecot-2.3.11-bigkey.patch, SPECS-EXTENDED/dovecot/dovecot.signatures.json, SPECS-EXTENDED/dovecot/dovecot.spec, cgmanifest.json
---
Upgrade dovecot to 2.3.20 to address the following:
Component: dovecot (4 CVE(s))
- CVE-2021-33515
- CVE-2021-29157
- CVE-2022-30550
- CVE-2020-28200
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-33515
- https://nvd.nist.gov/vuln/detail/CVE-2021-29157
- https://nvd.nist.gov/vuln/detail/CVE-2022-30550
- https://nvd.nist.gov/vuln/detail/CVE-2020-28200
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=415264&view=results
=> Upgrade dovecot to 2.3.20 to address CVEs

SPECS-EXTENDED/mod_auth_openidc/mod_auth_openidc.signatures.json, SPECS-EXTENDED/mod_auth_openidc/mod_auth_openidc.spec, cgmanifest.json
---
Upgrade mod_auth_openidc 2.4.2.1 -> 2.4.14.2 to address CVE-2021-20718, CVE-2021-39191, CVE-2022-23527, CVE-2023-28625 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-20718
- https://nvd.nist.gov/vuln/detail/CVE-2021-39191
- https://nvd.nist.gov/vuln/detail/CVE-2022-23527
- https://nvd.nist.gov/vuln/detail/CVE-2023-28625
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417512&view=results
=> Upgrade mod_auth_openidc 2.4.2.1 -> 2.4.14.2 to address CVE-2021-20718, CVE-2021-39191, CVE-2022-23527, CVE-2023-28625

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-kernel-config.yml, .github/workflows/check-license-map.yml, .github/workflows/check-livepatches.yml, .github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/check-spec.yml, .github/workflows/check-static-glibc.yml, .github/workflows/cherry-pick.yml, .github/workflows/go-test-coverage.yml, .github/workflows/lint-specs.yml, .github/workflows/quickstart_1.0.yml, .github/workflows/quickstart_2.0.yml
---
Bump actions/checkout v3 (Node 16) to v4 (Node 20) as Node 16 reaches EoL on September 11.
- NA
**NO**
- NA
- NA
Took a random PR, rebased that with the changes introduced in this PR:
- https://github.com/microsoft/CBL-Mariner/pull/6168 (Works as expected)
=> workflows: bump version of actions/checkout 3 -> 4

SPECS-EXTENDED/advancecomp/advancecomp.signatures.json, SPECS-EXTENDED/advancecomp/advancecomp.spec, cgmanifest.json
---
Upgrade advancecomp to 2.5 to address CVE-2023-2961
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-2961
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418135&view=results
=> Upgrade advancecomp 2.4 -> 2.5 to address CVE-2023-2961

SPECS-EXTENDED/usbguard/usbguard.signatures.json, SPECS-EXTENDED/usbguard/usbguard.spec, cgmanifest.json
---
Upgrade usbguard 1.0.0->1.1.0 to address CVE-2019-25058 
NO
- https://nvd.nist.gov/vuln/detail/CVE-2019-25058
- Pipeline build id: [417860](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=417860&view=results)
=> Upgrade usbguard 1.0.0->1.1.0 to address CVE-2019-25058

SPECS/python-more-itertools/python-more-itertools.spec, SPECS/python-twisted/python-twisted.spec
---
This adds `tox` to the packages installed in the %check section of `python-more-itertools`
- Added `python3-pip` to `python-more-itertools`
- Added tox as well
NO
- Pipeline build id: 418272
=> Fixing python-more-itertools tests

toolkit/scripts/containerized-build/resources/setup_functions.sh, toolkit/scripts/containerized-build/resources/welcome.txt
---
Update welcome text
- Add colors to welcome text to make it easier to read
- Revise text to improve readability
**NO**
=> Update welcome text

toolkit/scripts/containerized-build/create_container_build.sh
---
fix docker command to get rid of '127' error
- docker command was giving a '127' error
- fix docker command to get rid of the error
**NO**
- Local build
=> fix docker command

SPECS/tcl/CVE-2023-36328.patch, SPECS/tcl/tcl.spec, cgmanifest.json
---
Adapt nist linked patch to libtommath embedded in tcl to address CVE-2023-36328
- CVE-2023-36328
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-36328
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418862&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=7909073b-e471-53c1-2c44-627e2efc0564
=> patch tcl for CVE-2023-36328

SPECS/bind/bind.signatures.json, SPECS/bind/bind.spec, cgmanifest.json
---
- Bump the bind version to 9.16.37 to fix CVE-2022-3924, CVE-2022-3094, CVE-2022-3736
- - Bump the bind version to 9.16.37
**YES*
- https://nvd.nist.gov/vuln/detail/CVE-2022-3924
- https://nvd.nist.gov/vuln/detail/CVE-2022-3094
- https://nvd.nist.gov/vuln/detail/CVE-2022-3736
- Pipeline build id: [418733](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=418733&view=results)
=> Bump the bind version to 9.16.37 to fix CVE-2022-3924, CVE-2022-3094, CVE-2022-3736

SPECS/librelp/librelp.spec
---
- Added `glibc-debuginfo` in order to satisfy requirement of `strlen` for tests
- Added `glibc-debuginfo` in order to satisfy requirement of `strlen` for tests
**NO**
- Pipeline build id: 418714
=> Fix `librelp` tests by adding `glibc-debuginfo`

toolkit/scripts/containerized-build/create_container_build.sh
---
make tools in parallel
- Instead of serially issuing make commands to build required tools, make them in parallel to save time
**NO**
- Local build
=> make tools in parallel

toolkit/scripts/containerized-build/create_container_build.sh
---
use chroot-tools make target to build worker-chroot.tar.gz
- use chroot-tools make target to build worker-chroot.tar.gz
**NO**
- local build
=> containerized rpmbuild: fix make target for worker chroot

SPECS/lldpd/CVE-2023-41910.patch, SPECS/lldpd/lldpd.spec
---
Patch CVE-2023-41910 in lldpd package
- CVE-2023-41910
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-41910
Buddy build results for AMD64 and ARM64 is [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=420096&view=results)
=> Patch CVE-2023-41910 in lldpd package

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
- Upgrade vim to the latest version to resolve multiple CVEs
- Upgrade version to resolve CVE-2023-4738, CVE-2023-4750, CVE-2023-4781, CVE-2023-4752 and CVE-2023-4733
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-4738
- https://nvd.nist.gov/vuln/detail/CVE-2023-4750
- https://nvd.nist.gov/vuln/detail/CVE-2023-4781
- https://nvd.nist.gov/vuln/detail/CVE-2023-4752
- https://nvd.nist.gov/vuln/detail/CVE-2023-4733
- Pipeline build id: 420577
=> Resolve vim CVE-2023-4738, CVE-2023-4750, CVE-2023-4781, CVE-2023-4752 and CVE-2023-4733

SPECS-EXTENDED/imaptest/imaptest.signatures.json, SPECS-EXTENDED/imaptest/imaptest.spec, cgmanifest.json
---
Upgrade imaptest 20210305 to 20210511.
Upgrading dovecot broke imaptest as there were some API changes. This PR fixes the same.
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=421227
=> Upgrade imaptest 20210305 to 20210511

SPECS/supermin/supermin.spec
---
Removing and `exit 1` call from the `%check` section inside `supermin.spec`. Calling `exit` fails the whole package build instead of just failing the test. Replaced it with `false`.
- Replaced `exit 1` with `false` inside `supermind.spec`.
No.
- None, simple change.
=> Removed 'exit 1' from 'supermin'.

SPECS/lldpd/CVE-2023-41910.patch, SPECS/lldpd/lldpd.spec
---
Cherry-pick of #6205 into the fast-track branch.
- Patched CVE from the title.
No.
- #6205
- https://nvd.nist.gov/vuln/detail/CVE-2023-41910
- Relying on testing for #6205.
=> Patch CVE-2023-41910 in lldpd package (#6205 cherry-pick)

SPECS/kernel/CVE-2023-4208.nopatch, SPECS/kernel/CVE-2023-4622.nopatch
---
Nopatch kernel to fix CVE-2023-4208, CVE-2023-4622
- CVE-2023-4208
- CVE-2023-4622
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-4208
- https://nvd.nist.gov/vuln/detail/CVE-2023-4622
Nopatch
=> Nopatch kernel to fix CVE-2023-4208, CVE-2023-4622

SPECS-EXTENDED/wavpack/wavpack.signatures.json, SPECS-EXTENDED/wavpack/wavpack.spec, cgmanifest.json
---
Upgrade wavpack: 5.4.0 -> 5.6.0 to address CVE-2021-44269 & CVE-2022-2476
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2476
- https://nvd.nist.gov/vuln/detail/CVE-2021-44269
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=419784&view=results
=> Upgrade wavpack: 5.4.0 -> 5.6.0 to address CVE-2021-44269 & CVE-2022-2476

toolkit/tools/depsearch/depsearch.go, toolkit/tools/internal/sliceutils/sliceutils.go, toolkit/tools/internal/sliceutils/sliceutils_test.go, toolkit/tools/scheduler/schedulerutils/buildlist.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
fix merge
---
Add generic `SliceToSet()`, and related `RemoveDuplicatesFromSlice()` functions to `sliceutils`.
- Add `SliceToSet[K comparable](inputSlice []K)`
- Add `RemoveDuplicatesFromSlice[K comparable](inputSlice []K)`
**NO**
- Local
=> Add SliceToSet() to sliceutils

toolkit/scripts/containerized-build/resources/setup_functions.sh
---
createrepo in all repos defined in local.repo
- Remove hardcoded repo generation in local.repo locations
- Iterate over file locations in local.repo and 'createrepo' there
**NO**
- Local setup
=> createrepo in all repos defined in local.repo

SPECS-EXTENDED/re2c/re2c.signatures.json, SPECS-EXTENDED/re2c/re2c.spec, cgmanifest.json
---
Upgrade re2c to version 2.0 to resolve CVE-2018-21232
- Change re2c to version 2.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2018-21232
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=422830&view=results)
=> re2c: upgrade to version 2.0 to fix CVE-2018-21232

toolkit/scripts/tools.mk
---
Adding a simple check for the tooling required to build Mariner packages and images. The list is not complete - feel free to add more to it and we can expand later as well.
- Added a tooling check inside `tools.mk`.
No.
- Local tests.
- Buddy build.
=> Added a toolkit check for required tooling.

SPECS/binutils/binutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Use the PIC versioned static object instead of the non -fPIC
- Use the PIC'ed version of libiberty.a static object
**YES**
- Build out binutills-devel
- Exploded RPM
- Checked library
```
azaugg@azaugg-ld77 [ /tmp/b/usr/lib ]$ readelf --relocs libiberty.a | grep 'R_X86_64_PLT32'
0000000001e7  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
00000000027c  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
0000000003db  002600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
```
=> Use the PIC'ed version of libiberty.a static object

toolkit/scripts/tools.mk
---
This reverts commit d3fd41653a532e9f9f3a871c49786982ed904223.
This seems to be breaking in the pipeline.
/cc @anphel31
- Change
- Change
- Change
**NO**
- #6199
- NA
- NA
Trigger a Buddy build by rebasing a failing PR with this change. [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=423605&view=results)
=> Revert "Added a toolkit check for required tooling. (#6199)"

SPECS-EXTENDED/python-ldap/python-ldap.signatures.json, SPECS-EXTENDED/python-ldap/python-ldap.spec, cgmanifest.json
---
Upgrade python-ldap 3.3.1 -> 3.4.0 to address CVE-2021-46823
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-46823
- Pipeline build id: [424040](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=424040&view=results)
=> Upgrade python-ldap 3.3.1 -> 3.4.0 to address CVE-2021-46823

.pipelines/templates/PackageBuild.yml, .pipelines/templates/PackageTestResultsAnalysis.yml
---
Moving authentication to custom pip feeds, since package tests may require pip modules as well. Hopefully this will also fix the issues during test results passing we've seen in [some of our PR check runs](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=421751&view=logs&j=fda77280-e959-554f-2c0f-774bb847990c&t=253ed593-ee9d-5b7f-0624-a12c34810ba9).
- Moved pip feed authentication to the top of `PackageBuild.yml`.
No.
- [Test PR run](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=421908&view=results).
=> Updated usage of `pip` in the package build template.

SPECS/frr/frr.spec, SPECS/grpc/grpc.signatures.json, SPECS/grpc/grpc.spec, SPECS/opentelemetry-cpp/opentelemetry-cpp.spec, cgmanifest.json
---
Fixing CVE-2023-4785. The version gap was big enough, that backporting the upstream didn't backport the patch and it seems risky to attempt to make the backport ourselves, so I'm upgrading the package instead.
- Upgraded `grpc` to version 1.54.3.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-4785
- Buddy build.
=> Updated `grpc` to fix CVE-2023-4785.

toolkit/Makefile
---
On some systems `CONFIG_FILE ?= ""` evaluates to `''`, while on other systems it evaluates to `'""'`. Unify the assignment with the others so we always get `''`.
- Change `CONFIG_FILE` default to `` instead of `""`.
**NO**
- Local check
=> Make CONFIG_FILE default assignment consistent

SPECS-EXTENDED/freeradius/fix-error-for-expansion-of-macro-in-thread.h.patch, SPECS-EXTENDED/freeradius/freeradius-Use-system-crypto-policy-by-default.patch, SPECS-EXTENDED/freeradius/freeradius-no-buildtime-cert-gen.patch, SPECS-EXTENDED/freeradius/freeradius.signatures.json, SPECS-EXTENDED/freeradius/freeradius.spec, SPECS-EXTENDED/freeradius/freeradius.sysusers, cgmanifest.json
---
- Upgrade to 3.2.3 
- Address CVE-2022-41860, CVE-2022-41861
- Update Patch2 & Patch4
- Add Patch6 to address build error
- Add Source105 for user management during installation
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-41860
- https://nvd.nist.gov/vuln/detail/CVE-2022-41861
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=419788&view=results
=> Upgrade freeradius 3.0.21 -> 3.2.3 to address 2 CVEs

toolkit/tools/internal/shell/shell.go
---
Allow executing tools with a custom working directory (things like `cpio` only work in the current directory.
- Add `shell.ExecuteInDirectory()`
**NO**
- Local
=> Add shell.ExecuteInDirectory()

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
=> [2.0] Skip TestCustomizeImageEmptyConfig test

SPECS/openmpi/openmpi.spec
---
Bump package version to rebuild with pmix fix for CVE-2023-41915
- Bump version
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=424607
=> Bump openmpi version to rebuild with pmix for CVE-2023-41915

toolkit/docs/nvidia/nvidia.md
---
Update link to nvidia pmc repo to point to 2.0
- NA
**NO**
- NA
- NA
NA
=> docs: nvidia: update pmc link to 2.0

.pipelines/prchecks/PackageBuildPRCheck.yml, .pipelines/templates/PackageBuild.yml, .pipelines/templates/PackageTestResultsAnalysis.yml
---
Tweak to make the package test suite name configurable.
- Added the `testSuiteName` parameter.
No.
- [PR check run](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=425355&view=results).
=> Made package test name configurable.

toolkit/scripts/containerized-build.mk, toolkit/scripts/pkggen.mk, toolkit/scripts/toolchain.mk, toolkit/scripts/utils.mk
---
While working on #6133 I've forgot to include disabling the ACLs for toolchain builds. As a result our PR check pipeline started failing if it needed to rebuild a toolchain package, because later any other package, which needed to be installed into the chroot and shared a directory with one of the rebuilt toolchain packages ended up signaling a conflict.
- Disabled ACLs before building the toolchain.
No.
- #6133
- [PR check build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=425773&view=results)
=> Disabled ACLs for toolchain builds.

toolkit/tools/imagegen/configuration/partitionsetting.go, toolkit/tools/imagegen/configuration/systemconfig.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imager/imager.go
---
Make a couple of the partition setup functions usable in contexts outside of building new images. This is being done so that the functions can be used in the image customizer UTs in a subsequent change.
- Make the `installutils.UpdateFstab` function public.
- Remove `installutils.CreateMountPointPartitionMap` dependency on `configuration.SystemConfig`.
NO
=> Genericize partition functions

toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt
---
Our basic worker chroot should consist of a set of "self-sufficient" packages, where each package has its run-time dependencies satisfied. Running the `make validate-chroot` target has revealed that to not be the case and we've recently had a broken build due to `gtk-doc` missing its run-time dependencies. This PR addresses only the `gtk-doc` issue, the remaining missing dependencies will be addressed in a separate PR.
 
- Extended the worker chroot with missing run-time dependencies for `gtk-doc`.
No.
- Local chroot build.
=> Added `gtk-doc` dependencies to the chroot.

SPECS/sriov-network-device-plugin/sriov-network-device-plugin.signatures.json, SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec, cgmanifest.json
---
This PR updated the sriov-network-device-plugin SPEC to v3.5.1 (which is the lastest release at this time). This update should fix unaddressed CVEs related to this SPEC.
**NO**
- #xxxx
- https://github.com/advisories/GHSA-c3h9-896r-86jm
- Successful build: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=428746&view=results)
- Successful container test run: [link](https://dev.azure.com/mariner-org/ECF/_build/results?buildId=428990&view=results)
=> Update sriov to v3.5.1

toolkit/imageconfigs/baremetal.json, toolkit/imageconfigs/packagelists/baremetal-packages.json, toolkit/imageconfigs/packagelists/qemu-guest-packages.json, toolkit/imageconfigs/qemu-guest.json
---
Add qemu-guest and bare-metal image definitions and related package lists.
- The qemu-guest image is designed to run inside qemu/kvm environment.
- The bare-metal image is targeted to runn on physical hosts.
**YES/NO**
NO
- local build. Generated images validated to boot using qemu, hyper-v & baremetal machine
=> QEMU guest & BareMetal image definitions

SPECS/kernel/CVE-2023-4921.nopatch, SPECS/kernel/kernel.spec
---
kernel: nopatch CVE-2023-4921
- kernel: nopatch CVE-2023-4921
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-4921
- none as it's a nopatch
=> kernel: nopatch CVE-2023-4921

SPECS/libwebp/libwebp.signatures.json, SPECS/libwebp/libwebp.spec, cgmanifest.json
---
Cherry-pick of #6265 from `main` to fix CVE-2023-4863.
- Updated `libwebp` to version `1.3.2`.
No.
- #6265
- https://nvd.nist.gov/vuln/detail/CVE-2023-4863
- PR check build.
=> CP: Upgrade libwebp to 1.3.2 to address CVE-2023-4863 (#6265)

SPECS/xmlsec1/xmlsec1.spec
---
Recently `xmlsec1` started failing due to `/usr/bin/ld: cannot find -lxslt`. Adding and explicit `BuildRequires: libxslt-devel` to address this issue.
- Added BR on `libxslt-devel` to `xmlsec1.spec`.
No.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=430073&view=results).
=> Added explicit BR on `libxslt-devel` to `xmlsec1.spec`.

toolkit/imageconfigs/read-only-root-efi.json
---
Remove to explicit comment mentioning our demo password for the read-only image config.
- Remove verity demo credential comment.
**NO**
- Local build
=> Update read-only-root-efi.json to remove demo credentials

toolkit/tools/imagecustomizerapi/systemconfig.go, toolkit/tools/imagecustomizerapi/user.go, toolkit/tools/imagecustomizerapi/utils.go, toolkit/tools/imagegen/configuration/user.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/userutils/userutils.go, toolkit/tools/internal/userutils/userutils_test.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/testdata/addusers-config.yaml
---
Add the ability to add or update users to the Image Customizer tool.
- Image Customizer: Add/update users.
- Moved a bunch of user utilities to their own module.
NO
=> Image Customizer: Add/update users.

SPECS/debugedit/BUG-28161.patch, SPECS/debugedit/debugedit.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This fixes the failing tests in debugedit by adding a patch and fixing a typo in the spec file
- Added `BUG-28161.patch` to `SPECS/debugedit`
- Changed a typo in the spec
YES
- #xxxx
- Pipeline build id: 430153
=> Fixing `debugedit` ptests

toolkit/scripts/tools.mk
---
Add the image customizer tool to the Makefile.
- Image Customizer: Add to Makefile.
NO
- Ran `make go-tools REBUILD_TOOLS=y`.
=> Image Customizer: Add to Makefile.

SPECS/vim/vim.spec
ignore this PR -- testing a pipeline
=> [Test PR] vim: bump release number

toolkit/docs/building/prerequisites-ubuntu.md, toolkit/tools/go.mod
---
Our Ubuntu prerequisites instructions were outdate and mentioned Ubuntu 18.04, while the current tested and supported version is 22.04. We're also switching the instructions to suggest the official Ubuntu repo to download Go.
- Updated suggested Ubuntu version to 22.04.
- Updated Go's installation instructions to use the official Ubuntu repository.
- Bumped Go version in `go.mod` missed in #6336.
No.
- #6336
- N/A.
=> Updated Ubuntu requirements doc with better Golang instructions.

SPECS/vim/vim.spec
testing cherry pick pipeline -- ignore this PR
=> dummy bump vim release number

toolkit/tools/scheduler/scheduler.go
Issue being debugged has not repo'd, and this can cause significant build slowdowns in worst case.
Reverts microsoft/CBL-Mariner#6290
=> Revert "Damcilva/2.0/tools/add scheduler stuck debug code"

toolkit/tools/go.mod, toolkit/tools/go.sum, toolkit/tools/imagecustomizer/main.go, toolkit/tools/imagecustomizerapi/packagelist.go, toolkit/tools/imagecustomizerapi/systemconfig.go, toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go, toolkit/tools/pkg/imagecustomizerlib/customizepackages.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go, toolkit/tools/pkg/imagecustomizerlib/rpmsourcesmounts.go, toolkit/tools/pkg/imagecustomizerlib/testdata/lists/dracut-fips.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml
---
Add the ability to add and remove packages to the image customizer.
- Image Customizer: Add/remove packages
NO
- Ran toolkit tools UTs.
- Add toolkit tools UTs.
=> Image Customizer: Add/remove packages

SPECS/vim/CVE-2023-5344.patch, SPECS/vim/vim.spec
---
Add patch to vim to fix CVE-2023-5344
- Add CVE-2023-5344.patch to vim
- Bump vim release
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5344
- Unified BuddyBuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=433605&view=results
=> patch vim for CVE-2023-5344

SPECS/vim/CVE-2023-5344.patch, SPECS/vim/vim.spec
---
Cherry-pick of #6372 from the `fasttrack/2.0` branch.
- Patched `vim` for CVE-2023-5344.
No.
- #6372
- https://nvd.nist.gov/vuln/detail/CVE-2023-5344
- PR checks in #6372.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=433661&view=results).
=> Patched `vim` for CVE-2023-5344 (CP of #6372)

SPECS/vim/vim.spec
testing cherry pick pipeline -- ignore this PR
=> Test PR - dummy bump vim version 

SPECS/nano/nano.spec
PR for testing cherry pick pipeline -- please ignore
=> nano: dummy bump release number

SPECS/libcgroup/libcgroup.spec
---
I was unaware the cgconfigs supported "drop files", after going through the upstream source, i noticed that it provided the drop files pattern. Adding this folder as part of the install, so users don't need to dig through the [source code](https://github.com/libcgroup/libcgroup/blob/444159e29c5323bdcb42d8bd3900f5516dffaead/src/libcgroup-internal.h#L57) to work out that the drop files pattern is supported.
- Create /etc/cgconfig.d as part of RPM install
**NO**
- Built package
- Confirmed that drop file directory is included
```
azaugg@azaugg-ld77 [ ~/CBL-Mariner/toolkit ]$ sudo make build-packages -j$(nproc) REBUILD_TOOLS=y SRPM_PACK_LIST="libcgroup" …
```
=> Libcgroup create drop file folder

toolkit/scripts/precache.mk, toolkit/tools/precacher/precacher.go
---
Cherry-pick of fix from main (https://github.com/microsoft/CBL-Mariner/pull/6342)
- Cherry-pick ff133d6c92b57b88edeb2789f47f3daefceb0f89 from main
- 
**YES/NO**
- #xxxx
=> Only query precacher repos if one is passed in (#6342)

SPECS/rust/rust.spec
---
In some environments calling `x.py ...` seems to work as expected, but on others its not found on the `$PATH`... just use `./x.py...` always to avoid this.
- Use `./x.py` in rust.spec
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=434180&view=results
=> Update rust.spec to use ./x.py instead of x.py

SPECS/filesystem/filesystem.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Currently, /media is a symlink to /run/media, however /run is a tmpfs so
the symlink does not persist across reboots.
Generally the symlink is not useful and having it present is fragile. So
instead change /media to a proper directory in accordance with the Linux
Filesystem Hierarchy standard.
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/46029046
- Pipeline build id: [433836](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=433836&view=results)
=> fix: make /media a directory

SPECS/python-urllib3/CVE-2023-43804.patch, SPECS/python-urllib3/python-urllib3.spec
---
Patches CVE-2023-43804 in urllib3
- Add a patch for CVE-2023-43804
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-43804
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=435457&view=results)
=> Patch urllib3 CVE-2023-43804

SPECS/vim/CVE-2023-5441.patch, SPECS/vim/vim.spec
---
Adds a patch for CVE-2023-5441 for `vim`
- patched CVE-2023-5441 for vim
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5441
- PR check
=> Patched CVE-2023-5441 for vim

SPECS/vim/CVE-2023-5441.patch, SPECS/vim/vim.spec
---
Cherry-pick of fast-track fix for CVE-2023-5441 in `vim`.
- Fixed CVE-2023-5441 in `vim`.
No.
- #6411
- https://nvd.nist.gov/vuln/detail/CVE-2023-5441
- PR check from #6411.
=> Patched CVE-2023-5441 for vim (CP of #6411)

toolkit/tools/imagegen/diskutils/diskutils.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
---
Add support for customizing images that use the legacy boot system. (Specifically, BIOS boot with GPT partitions.)
- Image Customizer: Support legacy boot images.
NO
=> Image Customizer: Support legacy boot images.

SPECS/tensorflow/tensorflow.signatures.json, SPECS/tensorflow/tensorflow.spec, cgmanifest.json
---
Cherry-picking a fast-track CVE fix in `tensorflow`.
- Cherry-picked #6418.
No.
- #6418
- https://nvd.nist.gov/vuln/detail/[multiple]
- PR check for #6418.
=> Upgrade tensorflow to 2.11.1 to address CVEs (CP of #6418)

SPECS/kernel/CVE-2023-39189.nopatch, SPECS/kernel/CVE-2023-39192.nopatch, SPECS/kernel/CVE-2023-39193.nopatch, SPECS/kernel/CVE-2023-39194.nopatch, SPECS/kernel/CVE-2023-42753.nopatch, SPECS/kernel/CVE-2023-42755.nopatch
---
Address kernel cves CVE-2023-39189, CVE-2023-39192, CVE-2023-39193, CVE-2023-39194, CVE-2023-42753, CVE-2023-42755
- Address kernel cves CVE-2023-39189, CVE-2023-39192, CVE-2023-39193, CVE-2023-39194, CVE-2023-42753, CVE-2023-42755
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39189
- https://nvd.nist.gov/vuln/detail/CVE-2023-39192
- https://nvd.nist.gov/vuln/detail/CVE-2023-39193
- https://nvd.nist.gov/vuln/detail/CVE-2023-39194
- https://nvd.nist.gov/vuln/detail/CVE-2023-42753
- https://nvd.nist.gov/vuln/detail/CVE-2023-42755
=> Address kernel cves CVE-2023-39189, CVE-2023-39192, CVE-2023-39193, CVE-2023-39194, CVE-2023-42753, CVE-2023-42755

SPECS/edk2/CVE-2023-3817.patch, SPECS/edk2/edk2.spec
---
To fix CVE-2023-3817
Fix for CVE-2023-3817 in bundled openSSL in edk2 package
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-3817
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=435786&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=d723e8ff-9fe0-5a1d-bed2-08b8dc44a520
=> Fix CVE-2023-3817 in edk2 package

toolkit/scripts/tools.mk
- [x ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
---
Ideally `go-test-coverage` should use the full test suite, but there have been intermittent failures in a test in the Github Actions runner, so switching to just short tests until this is resolved.
- Make `go-test-coverage` use `--test.short`.
**NO**
=> Add short test flag to full go-test-coverage

SPECS/kernel/CVE-2023-4244.nopatch, SPECS/kernel/CVE-2023-5197.nopatch
---
Nopatch CVE-2023-4244 and CVE-2023-5197
- Nopatch CVE-2023-4244 and CVE-2023-5197
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-4244 
- https://nvd.nist.gov/vuln/detail/CVE-2023-5197
=> Nopatch CVE-2023-4244 and CVE-2023-5197

toolkit/Makefile, toolkit/scripts/repoquerywrapper.mk, toolkit/scripts/tools.mk, toolkit/scripts/update-target-if-output-changed.sh, toolkit/tools/internal/packagerepo/repoutils/repoquery.go, toolkit/tools/precacher/precacher.go, toolkit/tools/repoquerywrapper/repoquerywrapper.go
The repoquerywrapper tools creates a chroot, installs dnf packages, and runs specific repoquery commands within that environment.
This tools allows us to run repoquery on systems that may not have repoquery installed/available.
It also allows us to run queries that are not directly supported by repoquery - for example, in this check-in, it allows us to check which packages in a list are available on the target repros.
Such queries are very specific - and can be added incrementally to the tool as the need arises.
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Add the repoquerywrapper tool.

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
---
The `TestCustomizeImageCopyFiles` test currently has an assumption that the same loopback device will be assigned when creating its test image and when verifying the changes made by the customizer. While this usually is the case, it is far from guaranteed.
- Image Customizer: Fix TestCustomizeImageCopyFiles.
NO
=> Image Customizer: Fix TestCustomizeImageCopyFiles.

SPECS/cmake/cmake.spec, SPECS/cmake/cve-2023-44487.patch, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> cmake: patch vendored nghttp2 for cve-2023-44487

SPECS/grpc/grpc.spec, SPECS/libcontainers-common/libcontainers-common.spec, SPECS/nodejs/nodejs18.spec
We can just ignore the dirs conflict failure in the pipelines! :)
- [x ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, …
=> nodejs18: Re-enable building debuginfo. 

SPECS/grpc/grpc.spec
---
Bump grpc release to rebuild with updated version of Go. cve-2023-44487
- Change
- Change
- Change
Bump grpc release to rebuild with updated version of Go. cve-2023-44487
NO
- #xxxx
Bump grpc release to rebuild with updated version of Go. cve-2023-44487
Bump grpc release to rebuild with updated version of Go. cve-2023-44487
=> Bump grpc release to rebuild with updated version of Go. cve-2023-44487

SPECS/libcontainers-common/libcontainers-common.spec
---
fasttrack libcontainers common CVE 2023 44487
- Change
- Change
- Change
fasttrack libcontainers common CVE 2023 44487
/NO
- #xxxx
fasttrack libcontainers common CVE 2023 44487
fasttrack libcontainers common CVE 2023 44487
=> fasttrack libcontainers common CVE 2023 44487

SPECS/cmake/cmake.spec, SPECS/cmake/cve-2023-44487.patch, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
fasttrack cmake CVE 2023 44487
- Change
- Change
- Change
fasttrack cmake CVE 2023 44487
**/NO**
- #xxxx
fasttrack cmake CVE 2023 44487
fasttrack cmake CVE 2023 44487
=> fasttrack cmake CVE 2023 44487

toolkit/scripts/sodiff/mariner-sodiff.sh
---
Image builds for main on the dev branch are failing due to an error being thrown from sodiff addition. Removing the error to unblock builds.
- Removing error from sodiff
**NO**
=> Remove error from sodiff to unblock main builds

SPECS/libnbd/CVE-2023-5215.patch, SPECS/libnbd/libnbd.spec
---
libnbd: patch CVE 2023-5215
- libnbd: patch CVE 2023-5215
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5215
- Local build
- Buddy build pipeline successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=439146&view=results
=> libnbd: patch CVE-2023-5215

toolkit/scripts/analysis.mk
* remove additional error check logic moved into script
* add input redirection
---------
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Remove additional error logic from sodiff-check command (#6565)

toolkit/README.md
Test CI trigger for fast-track branch
=> Add newline to README.md

toolkit/README.md
This reverts commit 839e937ba1cd66166c3bdba0b84ba58673a2904f.
=> Revert "add newline to README.md (#6573)"

SPECS/zlib/CVE-2023-45853.patch, SPECS/zlib/zlib.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2023-45853
- Add patch to address CVE-2023-45853
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-45853
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=438765&view=results
=> Fix zlib CVE-2023-45853

toolkit/imageconfigs/baremetal.json, toolkit/imageconfigs/qemu-guest.json
---
Increase os disk size to 4GB to account for additional customizations. This change will be reverted once image customizer has the ability to customize/grow paritions.
- Increase size to 4GB
**NO**
Local
=> Increase image size for baremetal and qemu guest to 4GB

toolkit/scripts/containerized-build/create_container_build.sh
---
containerized-rpmbuild: Build image if missing
- containerized-rpmbuild: Build image if missing
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/46964604
- Deleted worker chroot hash, invoked the tool. A new container image was created with worker chroot as fs.
- Deleted old container images by force, and invoked tool. New container image was created.
=> containerized-rpmbuild: Build image if missing

toolkit/scripts/tools.mk, toolkit/scripts/utils.mk
Add chroot dir to facl
---
In the pipelines we use a directory that is external to the core repo. The toolkit uses `setfacl` to configure the repo directory's ACLs, but this won't affect the external chroot dirs.
If the ACLs are different we can get directories in toolchain packages that have different permissions than packages made with the scheduler. `rpm` will refuse to install these packages if that is the case.
- Call `setfacl` on `CHROOT_DIR` as well as `PROJECT_ROOT`
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=440420&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=7909073b-e471-53c1-2c44-627e2efc0564
=> Call setfacl on chroot directories

toolkit/tools/imagecustomizer/README.md, toolkit/tools/imagecustomizer/docs/cli.md, toolkit/tools/imagecustomizer/docs/configuration.md
---
Add some documentation on how to use the Mariner Image customizer. This includes a Getting Started guide, descriptions of the CLI arguments, and descriptions of the configuration file.
- Image Customizer: Add documentation.
NO
n/a
=> Image Customizer: Add documentation.

toolkit/scripts/tools.mk, toolkit/scripts/utils.mk
Reverts microsoft/CBL-Mariner#6581
This fails on certain pipelines, reverting for now.
=> Revert "Call setfacl on chroot directories"

SPECS-EXTENDED/freeradius/freeradius.spec
---
This PR resolves installation [issues](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=438017&view=logs&j=07865233-51ab-5d41-0449-213a59f39222&t=f2af52f9-4eda-51e9-a4f9-9a649c7e11e9) of freeradius and sub-packages of freeradius. 
- Correct unavailable sysusers_create_compat macro to available sysusers_create_package macro
- Add runtime requirement for utils subpackage
- Update build requirement for postgresql subpackage
- Disable generation of debuginfo package as its files conflict with filsystem package
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=438432&view=results …
=> Fix freeradius installation issues

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-kernel-config.yml, .github/workflows/check-license-map.yml, .github/workflows/check-livepatches.yml, .github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/check-spec.yml, .github/workflows/check-static-glibc.yml, .github/workflows/go-test-coverage.yml, .github/workflows/lint-specs.yml
---
Github PR checks against the 3.0-dev branch were not working, I believe this should fix the issue
- Change workflows to support `3.0*` branches
- Change workflow to use golang 1.20
**YES/NO**
- #xxxx
=> update workflows for 3.0

SPECS/boost/CVE-2023-45853.patch, SPECS/boost/boost.spec
---
Fix CVE-2023-45853 for boost
- CVE-2023-45853
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-45853
- Pipeline build id: [441203](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=441203&view=results)
=> Patch CVE-2023-45853 for boost

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
Updating sudo to version 1.9.14p3
- Updating sudo to version 1.9.14p3
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/46193544
- Pipeline build id: [413175](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=413175&view=results)
=> Bumping sudo to version 1.9.14p3

SPECS/zchunk/CVE-2023-46228.patch, SPECS/zchunk/zchunk.spec
---
Patch zchunk to fix CVE-2023-46228
- Patch zchunk to fix CVE-2023-46228
**YES?**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-46228
- Pipeline build id: 441228
=> Fix zchunk CVE-2023-46228

SPECS/tcl/CVE-2023-45853.patch, SPECS/tcl/tcl.spec
---
- Fix CVE-2023-45853 for tcl
- CVE-2023-45853
**YES/NO**
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-45853
- Pipeline build id: [441107](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=441107&view=results)
=> Patch CVE-2023-45853 for tcl

SPECS/hyperv-daemons/CVE-2023-4622.nopatch, SPECS/hyperv-daemons/CVE-2023-5345.nopatch
---
- Nopatch CVE-2023-5345 and CVE-2023-4622 for hyperv-daemons
- Nopatch CVE-2023-5345 and CVE-2023-4622 for hyperv-daemons
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5345
- https://nvd.nist.gov/vuln/detail/CVE-2023-4622
=> Nopatch CVE-2023-5345 and CVE-2023-4622 for hyperv-daemons

.github/workflows/quickstart_2.0.yml
---
We now require golang 1.20, so update the workflow steps to use 1.20 instead of 1.19
- Change workflow to use golang 1.20
**NO**
=> workflow: install golang 1.20

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Fix the handling of the value of `with_check` defined in the toolchain chroot. When the toolchain builds, check tests are supposed to be turned off. When `RUN_CHECK` was not set, `rpmbuild` was being called with `--nocheck`, but it still defined `with_check 1`. Now, it will define `with_check 0` when `RUN_CHECK` is not set.
- Change build_official_toolchain_rpms.sh to set `with_check 0` when RUN_CHECK is not set
**YES**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=440504&view=results
=> toolchain: fix with_check handling

SPECS/libtiff/libtiff.signatures.json, SPECS/libtiff/libtiff.spec, cgmanifest.json
---
Update libtiff to v4.6.0 to fix CVE 2023-40745 and 2023-41175
- Update libtiff to v4.6.0 to fix CVE 2023-40745 and 2023-41175
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-40745
- https://nvd.nist.gov/vuln/detail/CVE-2023-41175
- buddy build pipeline: successfully built libtiff and direct dependencies https://dev.azure.com/mariner-org/mariner/_build/results?buildId=439242&view=logs&j=07865233-51ab-5d41-0449-213a59f39222&t=f2af52f9-4eda-51e9-a4f9-9a649c7e11e9
=> Update libtiff to v4.6.0 to fix CVE 2023-40745 and 2023-41175

SPECS/zchunk/CVE-2023-46228.patch, SPECS/zchunk/zchunk.spec
---
This is a manual squash and cherry-pick of #6580 because [auto cherry-pick failed](https://github.com/microsoft/CBL-Mariner/pull/6580#issuecomment-1781495901).
- Patch zchunk to fix CVE-2023-46228
**YES?**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-46228
=> Fix zhash CVE-2023-46228

SPECS/cronie/cronie.spec
---
The pam/crond file shipped in the cronie 1.5.7 source is different than the previous (1.5.2) version source. The sed command we used to fixup this file needed to be modified to make the changes.
- Change cronie.spec to properly modify /etc/pam.d/crond
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/41410479
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=442202&view=results
=> cronie: fix pam/crond file contents

SPECS/cloud-hypervisor/CVE-2023-45853.patch, SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
Fix CVE-2023-45853
- Fix zlib CVE-2023-45853 in cloud-hypervisor
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-45853
- Pipeline build id: [441558](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=441558&view=results)
=> Fix zlib CVE-2023-45853 in cloud-hypervisor

toolkit/resources/manifests/package/ccache-configuration.json, toolkit/tools/pkgworker/pkgworker.go
---
Porting support for enabling ccache per package and the use of a remote store to download/upload ccache artifacts.
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Porting support for enabling ccache per package and the use of a remote store to download/upload ccache artifacts.

SPECS/selinux-policy/0041-docker-Silence-io.containerd.internal.v1.opt-opt-con.patch, SPECS/selinux-policy/selinux-policy.spec
---
Silence io.containerd.internal.v1.opt denial noise in permissive mode.
- Silence io.containerd.internal.v1.opt denial noise in permissive mode.
**NO**
- Pipeline build id: 440269
=> selinux-policy: Silence io.containerd.internal.v1.opt denial noise.

toolkit/scripts/srpm_pack.mk, toolkit/scripts/toolchain.mk, toolkit/scripts/tools.mk, toolkit/tools/downloader/downloader.go
---
When gathering toolchain .rpms we use `wget`. While `wget` is generally quite resilient there are a few error conditions it can't recover from easily. We should retry the download if possible. A simple retry wrapper in bash would likely be sufficient but with an eye to the future (enabling caching etc.) we can just wrap the download operation in a simple go tool. This tool accepts a subset of arguments used by wget.
- Add `downloader` tool
**YES** - Just downloading it with REBUILD_TOOLCHAIN=n
- https://microsoft.visualstudio.com/OS/_workitems/edit/47288886
- Local
=> Add wget replacement go-downloader

toolkit/tools/downloader/downloader.go
---
`downloader` wasn't respecting `--no-clobber` when an explicit output destination wasn't set. The tool should now respect it in all cases.
- Handle `--no-clobber` in `go-downloader` correctly.
**NO**
- Local test
=> go-downloader: handle --no-clobber correctly without explicit dst

toolkit/tools/imagegen/installutils/installutils.go
---
Cherry-pick #6632 to 3.0-dev to fix image build pipelines
- Change
- Change
- Change
**NO**
=> Imager: Fix for when user password is empty. (#6632)

SPECS/libxml2/CVE-2023-45322.patch, SPECS/libxml2/libxml2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2023-45322 in libxml2
- CVE-2023-45322
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-45322
Unified buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=442988&view=results)
=> Patch CVE-2023-45322 in libxml2

SPECS/snappy/build-with-rtti.patch, SPECS/snappy/snappy.spec
This is done to enable Synapse team to build folly which is depending on Snappy with RTTI. Though this patch is generic as it is added to Snappy's main branch after the last major release. So, it will be included in the next major release of Snappy.
---
Patch snappy to fix build with RTTI enabled
- Patch snappy to fix build with RTTI enabled
**NO**
https://microsoft.visualstudio.com/OS/_workitems/edit/47187688
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=444435&view=results)
=> Patch snappy to fix build with RTTI enabled

toolkit/tools/internal/azureblobstorage/azureblobstorage.go, toolkit/tools/internal/ccachemanager/ccachemanager.go
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Switch ccache to use azure managed identity.

toolkit/docs/quick_start/quickstart.md
=> Clarify login instructions

.pipelines/templates/PackageTestResultsAnalysis.yml
---
workaround to Fix BUG-47150744 
- Change: Add retry to the installation of python package
**YES/NO**
NO
- Pipeline build id: [447251](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=447251&view=results)
=> Add retry workaround when Package Installation fail.

toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> fix wrong rights for toolkit/imageconfigs/postinstallscripts/remove-tdnf-cache.sh

.pipelines/prchecks/PackageBuildPRCheck.yml
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Add debug to PR check to debug intermittent issue

SPECS/traceroute/traceroute.signatures.json, SPECS/traceroute/traceroute.spec, cgmanifest.json
---
Bump package version to 2.1.3 to fix CVE-2023-46316
- Bump version to 2.1.3
- Lint spec
- Update cgmanifest entry for the package
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-46316
=> Patch CVE-2023-46316 for traceroute

SPECS/frr/CVE-2023-46752.patch, SPECS/frr/CVE-2023-46753.patch, SPECS/frr/frr.spec
---
Patch CVE-2023-46752 and CVE-2023-46753
- Patch CVE-2023-46752 and CVE-2023-46753
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-46752
- https://nvd.nist.gov/vuln/detail/CVE-2023-46753
- confirmed on "main" patches build ([Pipelines - Run rlmenge+2.0+cve-frr (azure.com)](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=447173&view=results)), pass check section, and install on a vhdx
=> Patch frr for CVE-2023-46752 and CVE-2023-46753

SPECS/PyYAML/PyYAML.signatures.json, SPECS/PyYAML/PyYAML.spec, cgmanifest.json
---
Upgraded `PyYAML` to 5.4 to fix CVEs: 2020-1747, CVE-2020-14343.
- Upgraded PyYAML to 5.4.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2020-1747
- https://nvd.nist.gov/vuln/detail/CVE-2020-14343
- PR check.
=> Upgraded `PyYAML` to 5.4 to fix CVEs: 2020-1747, CVE-2020-14343.

SPECS/multus/multus.signatures.json, SPECS/multus/multus.spec, cgmanifest.json
---
This updates the multus package to v4.0.2.
**NO**
- #xxxx
- Successful build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=449200&view=results
- Successful test: https://dev.azure.com/mariner-org/ECF/_build/results?buildId=449185&view=results
=> Update multus to v4.0.2

toolkit/tools/imagegen/diskutils/diskutils.go
---
Currently, the `dd` command is used to create an empty sparse raw disk file. Unfortunately, if the file already exists, then the `dd` call won't change the file at all (without failing).
This change ensures that if there is an existing file, then it is cleared. Specifically, `dd` is replaced with normal file calls to truncate and then resize the file.
- Fix sparse disk creation bug fix.
NO
=> Sparse disk creation bug fix.

toolkit/tools/internal/safechroot/safechroot.go
---
Currently, the `safechoot.Chroot` mounts devices in the order that the caller specified. But then it unmounts using the reverse of the string order of the target directories.
Ideally, mounting should happen in the string order of target directories. This ensures that any sub-directory mounts (e.g. /boot/efi) occur after the mounts of their parent directory (e.g. /boot). Therefore, anything that uses `safechoot.Chroot` will probably have to pre-sort their mounts this way. Though it is possible that more complex mounts (e.g. overlays, dm-verity, LUKS) might need a different order.
But `safechoot.Chroot` should not be sorting the devices only for unmounting. The unmounts should only …
=> Fix safechoot unmount ordering.

SPECS/kured/kured-imagePullPolicy.patch, SPECS/kured/kured.signatures.json, SPECS/kured/kured.spec, cgmanifest.json
---
- Upgrade kured to 1.13.2 for cves in vendored go code
- Upgrade kured to 1.13.2
**NO**
- Incident 437025392
- https://nvd.nist.gov/vuln/detail/CVE-2022-27664
- https://nvd.nist.gov/vuln/detail/CVE-2022-28948
- https://nvd.nist.gov/vuln/detail/CVE-2022-25891
- https://nvd.nist.gov/vuln/detail/CVE-2022-29526
- Confirmed on main in a [pipeline ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=449205&view=logs&j=e222995d-d1b7-557d-9808-e96e55b509dd) build and booted in a vhdx
=> Upgrade kured to 1.13.2 for CVEs on vendor code

SPECS/blobfuse2/blobfuse2.signatures.json, SPECS/blobfuse2/blobfuse2.spec, cgmanifest.json
---
Upgrade Blobfuse2 to latest version
- Upgrade Blobfuse2 to latest version
**NO**
- #xxxx
- Pipeline build id: 444644
=> Upgrade Blobfuse2 to 2.1.1

SPECS/memcached/memcached.signatures.json, SPECS/memcached/memcached.spec, cgmanifest.json
---
This PR upgrades the version of the memcached package from 1.6.13 to 1.6.22. Doing so lets us include the patches for CVEs 2023-46852 and 2023-46853.
- Upgrade memcached version to 1.6.22
- Fixes CVE-2023-46852
- Fixes CVE-2023-46853
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-46852
- https://nvd.nist.gov/vuln/detail/CVE-2023-46853
- Pipeline build id: [PR-6710](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=449507&view=results)
=> Upgrade memcached to v1.6.22: Fixes CVEs 2023-46852 and 2023-46853

.pipelines/prchecks/PackageBuildPRCheck.yml, .pipelines/templates/PackageTestResultsAnalysis.yml
---
Currently, prcheck pipeline is intermittently failing. 
i ) Add debugging to the PR-check pipeline 
ii) Add retry to the failing step ie pr check's Python dep installation step
- Change: Added system.debug variable 
- Change: add retryCountOnTaskFailure on failed step
**YES/NO**
No
=> Cherry pick few commits to retry and debug the PR check pipeline

toolkit/scripts/build_tag.mk
---
Bump the RELEASE_MAJOR_ID from `2.0` to `3.0` on the 3.0-dev branch
- Change RELEASE_MAJOR_ID to 3.0
**YES**
- Toolchain build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=450393&view=results
- RPMs build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=450496&view=results
=> 3.0-dev: bump RELEASE_MAJOR_ID to 3.0

SPECS/multus/multus.signatures.json, SPECS/multus/multus.spec, cgmanifest.json
---
Cherry-pick of #6313. External team's CVE scanning has found high priority CVEs inside our version of `multus`.
- Cherry-picked #6313 into `fasttrack/2.0`.
No.
- #6313
- https://nvd.nist.gov/vuln/detail/<multiple>
- PR check.
=> Update multus to v4.0.2 (CP: #6313)

SPECS/nano/nano.spec
testing cherry pick feature - ignore this PR
=> [TEST PR] dummy bump nano version

SPECS/kernel/CVE-2023-5178.nopatch
---
nopatch CVE-2023-5178
- CVE-2023-5178
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5178
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=453995&view=logs&j=e3e4c90c-f47a-552d-9399-c51e3747740e&t=97a0aa58-1cd5-5faa-2410-5d8e670febf7
=> kernel: nopatch CVE-2023-5178

SPECS/valgrind/valgrind.signatures.json, SPECS/valgrind/valgrind.spec, cgmanifest.json
Upgrade Valgrind to 3.22.0
---
Upgrade valgrind to 3.22.0
NO
- Pipeline build id: 454192
=> Upgrade valgrind to 3.22.0

SPECS/opensc/CVE-2023-4535.patch, SPECS/opensc/opensc.spec
---
Fix CVE-2023-4535
- Change: Add a patch file
**YES/NO**
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-4535
- Pipeline build id: [455029](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=455029&view=results)
=> Fix opensc CVE-2023-4535

toolkit/resources/manifests/package/ccache-configuration.json
---
A new package `kernel-mos` was added recently (see #6714 ). Adding this package to the ccache configuration file, so it shares ccache content with the other kernel packages using the same source.
- Change ccache config file to include `kernel-mos`
**NO**
=> add kernel-mos to ccache config

toolkit/tools/imagepkgfetcher/imagepkgfetcher.go
---
The output from the image fetcher isn't clear when a package download fails. While it isn't trivial to parse and diagnose the error in code, we can at least provide more information to the user on next steps.
- Add error message when both attempts to fetch packages fail.
**NO**
- Local build
=> Print more details on image fetch failures

SPECS/kernel/CVE-2023-39198.nopatch
---
Nopatch kernel CVE-2023-39198
- Nopatch kernel CVE-2023-39198
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39198
=> Nopatch kernel CVE-2023-39198

.github/ISSUE_TEMPLATE/questions-feedback.md, README.md
Merging documentation from the 2.0 branch to the main branch.
=> Joslobo/update docs from 2.0

SPECS/openssl/0025-for-tests.patch, SPECS/openssl/openssl.signatures.json
---
openssl's check section failed because of a conflict between a test patch file and modifications to other patches and config.
This change fixes that patch file and all tests pass.
- Update test patch file and associated signature.
**YES**
- Built and tested locally
- Pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=462408&view=results
=> Fix patch failure in check section of openssl

SPECS/filesystem/filesystem.spec, SPECS/zsh/zprofile.rhs, SPECS/zsh/zsh.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Removes umask 027 from the bash/zsh profiles
Removes umask 027 from the bash/zsh profiles.
This setting causes widespread problems and should not be used as a default.
YES
=> Remove umask 027 from bash/zsh profiles

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/mariner-required-configs.json
---
For better supportability and debuggability, it is good to get additional kernel boot messages on the console (serial / tty).
Currently, the first boot messages from the system happen when systemd init happens, which is already well into the boot sequence
- Remove loglevel=3 from the (legacy) boot parameter, $mariner_cmdline, which is sourced from the /boot/mariner.cfg symlink installed by kernel RPMs. 
YES
- https://github.com/microsoft/CBL-Mariner/issues/6870 
=> Remove loglevel=3 for legacy boot flow

SPECS/zsh/zsh.signatures.json
fix hash in zsh signature file
=> fix hash in zsh signature file

.pipelines/CodeQL/CodeQL.yml, CodeQL.yml
---
CodeQL Mariner toolkit
- Change
- Change
- Change
**NO**
- #xxxx
=> CodeQL Mariner toolkit

.pipelines/CodeQL/CodeQL.yml, CodeQL.yml
---
cherry pick 'codeQL' changes from main to 2.0 (59331eb12e8f4e0bf93896636b3cd4a024509b85)
- Change
- Change
- Change
**NO**
- #xxxx
=> CodeQL Mariner toolkit (#6885)

SPECS/wget/wget.spec
---
The package test for `wget` currently fails due to missing dependency `perl(English)`. This PR adds that dependency at check-time.
Additional cleanup: SPDX license migration, cleaning up make/configure invocations, removing use of CPAN dependencies.
- Require test-related perl modules at check-time
- Invoke make/configure with macros 
- Use SPDX license expression for license tag
**NO** (surprisingly)
- Pipeline build id: [460948](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=460948)
=> Fix wget package tests by adding missing test dep

SPECS/python-attrs/python-attrs.spec
---
Every so often, the `python-attrs` package test will start to fail due to changes in the upstream `mypy` package.  We don't ship `mypy` in Mariner, so the benefit of keeping the `mypy` tests in `python-attrs` passing is slim-to-none compared to the engineering time spent to triage the issues.
- Skip `mypy` tests in `python-attrs` package test
**NO**
- Pipeline build id: [460958](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=460958&view=results)
=> Skip mypy tests in python-attrs

toolkit/tools/roast/formats/squashfs.go, toolkit/tools/roast/roast.go
---
squahsfs is a compressed and read-only file system that is commonly used in embedded systems. This PR adds the support for composing a squashfs image type to Mariner toolkit.
**NO**
=> Add support for squashfs image format

.pipelines/templates/PackageBuild.yml, .pipelines/templates/PackageTestResultsAnalysis.yml
---
Switching to using Mariner's version of the `junit-xml` Python module. This way we'll avoid the issues we've been hitting in our PR check pipelines when we tried to install it from our internal feed with `pip`.
This change can only be merged once `python3-junit-xml` is published to PMC!
- Switched test conversion to use Mariner's `junit-xml` module.
No.
- #6812
- PR check.
=> Switched to using Mariner's `python-junit-xml`.

SPECS/kata-containers/kata-containers.spec
---
qemu-kvm-core is  not required for vanilla kata containers to builld/install/run, hence this PR removes it.
- Drop qemu-kvm-core dependency
**NO**
- [ADO 45707231](https://microsoft.visualstudio.com/OS/_queries/edit/45707231/?triage=true)
- Pipeline build id: [463491](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=463491&view=results)
=> kata-containers: drop qemu-kvm-core dependency

SPECS/python-distlib/python-distlib.spec
---
The `python-distlib` package test fails on `test_is_writable`. This test fails because we have write access to `/etc`, but that's expected since we run 
- Disable `test_is_writable` in `python-distlib`
**NO**
- Pipeline build id: [461735](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=461735)
=> Disable faulty test_is_writable for python-distlib

SPECS/filesystem/filesystem.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Fixes: #6925
---
add /etc/host.conf with multi on
adds /etc/host.conf file to filesystem package
YES
- #6925 
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=465204&view=results
=> add /etc/host.conf with multi on

SPECS/libdnf/libdnf.signatures.json, SPECS/libdnf/libdnf.spec, cgmanifest.json
---
Upgrade `libdnf` to the latest version, 0.72.0. This version fixes a compilation error with gcc 13:
```
"/usr/src/mariner/BUILD/libdnf-0.63.1/libdnf/sack/../transaction/../utils/sqlite3/Sqlite3.hpp:100:33: error: 'std::int64_t' has not been declared"
```
- Upgrade libdnf to 0.72.0
**NO**
- Local build
=> libdnf: upgrade to 0.72.0

SPECS/kernel/CVE-2023-1193.nopatch, SPECS/kernel/CVE-2023-1194.nopatch
---
- Add nopatch for CVE-2023-1193, CVE-2023-1194
- CVE-2023-1193
- CVE-2023-1194
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-1193
- https://nvd.nist.gov/vuln/detail/CVE-2023-1194
=> Nopatch kernel for CVE-2023-1193, CVE-2023-1194

toolkit/scripts/containerized-build/resources/setup_functions.sh
---
containerized-rpmbuild: create sources_dir correctly
- containerized-rpmbuild: create sources_dir correctly
**NO**
- Local build
=> containerized-rpmbuild: create sources_dir correctly

SPECS/fluent-bit/CVE-2023-48105.patch, SPECS/fluent-bit/fluent-bit.spec
---
fluent-bit: CVE-2023-48105
- fluent-bit: CVE-2023-48105
- fluent-bit: Enable package tests
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-48105
- Enabled package tests.
=> fluent-bit: CVE-2023-48105

SPECS/strongswan/strongswan-5.9.7-5.9.11_charon_tkm_dh_len.patch, SPECS/strongswan/strongswan.spec
---
- strongswan [CVE-2023-41913](https://github.com/advisories/GHSA-g7mg-4vgp-5j3h)
- strongswan [CVE-2023-41913](https://github.com/advisories/GHSA-g7mg-4vgp-5j3h)
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-41913 and patch available here https://download.strongswan.org/security/CVE-2023-41913/
- buddy build pass: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=468600&view=results
=> strongSwan: CVE-2023-41913

README.md
---
1.0 is no longer used and 
- remove 1.0 link from readme
**NO**
=> Remove 1.0 ISO link from README.md

SPECS/bind/bind.spec
---
named user disappeared from passwd and group file on package updates. This fixes the postun scriptlet to delete the user only on package removal, but not on update.
- Remove user only if it's not a package update
- Making changes similar to https://github.com/microsoft/CBL-Mariner/pull/6972 for bind
**NO**
- Local build and test that verified correct behavior: adding user on install, removing user on uninstall, no change on upgrade
=> bind: fix passwd and group reset on package upgrade

SPECS/rsyslog/rsyslog.spec
---
syslog user disappeared from passwd and group file on package updates. This fixes the postun scriptlet to delete the user only on package removal, but not on update.
- Remove user only if it's not a package update
- Making changes similar to https://github.com/microsoft/CBL-Mariner/pull/6972 for rsyslog
**NO**
- Local build and test that verified correct behavior: adding user on install, removing user on uninstall, no change on upgrade
=> rsyslog: fix passwd and group reset on package upgrade

SPECS/hyperv-daemons/CVE-2023-5972.nopatch, SPECS/hyperv-daemons/CVE-2023-6111.nopatch
---
Address hyperv-daemon CVE-2023-6111 and CVE-2023-5972
- Address hyperv-daemon CVE-2023-6111 and CVE-2023-5972
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-6111
- https://nvd.nist.gov/vuln/detail/CVE-2023-5972
=> Address hyperv-daemon CVE-2023-6111 and CVE-2023-5972

SPECS/libnftnl/libnftnl.signatures.json, SPECS/libnftnl/libnftnl.spec, cgmanifest.json
---
Upgrade libnftnl to 1.2.6
- Upgrade libnftnl to 1.2.6
**NO**
- Local build. All 32 tests passed
=> Upgrade libnftnl to 1.2.6

README.md
Cherry-pick #7023 to 2.0 branch
=> [2.0] Remove 1.0 ISO link from README.md

SPECS/kata-containers-cc/kata-containers-cc.spec
This PR targets a feature branch
=> Adapt kata-containers-cc package descriptions

.github/CODEOWNERS
---
Update the GitHub codeowners file to automatically add the cbl-mariner-kata-containers team as reviewers for kata-containers and confidential containers packages.
**NO**
=> ci: update kata codeowner packages

SPECS/sudo/sudo.spec
applying  disable-newgroup-query-when-netgroup-base-is-not-set.patch
---
applying  disable-newgroup-query-when-netgroup-base-is-not-set.patch
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> applying  disable-newgroup-query-when-netgroup-base-is-not-set.patch

SPECS/sudo/sudo.spec
---
Currently, sudo package rpmbuild is not applying patches specified in the spec. So in %prep stage, change %setup macro to %autosetup macro which will automatically apply spec patch files to the source in patch number order.
Fixes: 834484e3c2d4 ("Sudo ldap netgroup_query bug fix patch (#7070)")
**NO**
- Fixes: #7070
=> fix: use autosetup macro in sudo package

SPECS/bcc/bcc.signatures.json, SPECS/bcc/bcc.spec, cgmanifest.json
---
- bcc: upgrade 0.28.0 -> 0.29.1
**NO**
- NA
- NA
- Local Build
- Pipeline build id: [validating]
=> bcc: upgrade 0.28.0 -> 0.29.1

SPECS/python-cryptography/CVE-2023-49083.patch, SPECS/python-cryptography/python-cryptography.spec, SPECS/pytorch/pytorch.spec
---
This PR patches python-cryptography for CVE-2023-49083. It also set the MAX_JOBS to 8 for pytorch to prevent build failures in ADO pipelines.
- CVE-2023-49083
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-49083
- Pipeline build id: [AMD64 RPMs Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=472274&view=results)
- Pipeline build id: [ARM64 RPMs Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=472283&view=results)
=> Patch CVE-2023-49083 in python-cryptography

.github/CODEOWNERS
---
Update the GitHub codeowners file to automatically add tooling codeowners as reviewers to the toolkit code. Retain general dev reviewers for docs, imageconfigs, and package manifests.
**NO**
=> ci: add codeowners for toolkit folders

SPECS/bluez/CVE-2023-45866.patch, SPECS/bluez/bluez.spec
---
Patch CVE-2023-45866 in bluez
- CVE-2023-45866
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-45866
- Unified Buddy Build Results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=472478&view=results)
=> Patch CVE-2023-45866 in bluez

SPECS/moby-containerd-cc/containerd.service, SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json, SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
This PR forms the counterpart to https://github.com/microsoft/CBL-Mariner/pull/6819
- see above
**NO**
Internal end to end validation for the Mariner Kata AKS scenario, passed.
=> Set OOMScoreAdjust to -999 for containerd-cc

.github/CODEOWNERS
---
Update the GitHub codeowners file to automatically add the cbl-mariner-kata-containers team as reviewers for kata-containers and confidential containers packages.
Update the GitHub codeowners file to automatically add tooling codeowners as reviewers to the toolkit code. Retain general dev reviewers for docs, imageconfigs, and package manifests.
Cherry-pick of 71792f5d694321ecbcc00eea4775fc2abc171bbb and 7e792c13f9ebbe7c16949ca7ceedf425f4b8445c
**NO**
=> ci: update codeowners for kata packages and toolkit

SPECS/libunistring/libunistring.signatures.json, SPECS/libunistring/libunistring.spec, cgmanifest.json
---
Update libunistring to v1.1
- Update libunistring to v1.1
**NO**
- Local build
=> Update libunistring to v1.1

SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
---
ansible: update to v2.14.12 to fix CVE-2023-5764
- ansible: update to v2.14.12 to fix CVE-2023-5764
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5764
- Local build
=> ansible: update to v2.14.12 to fix CVE-2023-5764

SPECS/openssh/CVE-2023-51384.patch, SPECS/openssh/CVE-2023-51385.patch, SPECS/openssh/openssh.spec
---
patch CVE-2023-51384 and CVE-2023-51385
- patch CVE-2023-51384
- patch CVE-2023-51385
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-51384
- https://nvd.nist.gov/vuln/detail/CVE-2023-51385
- Local build
=> openssh: patch CVE-2023-51384 and CVE-2023-51385

SPECS/xorg-x11-server/CVE-2023-6377.patch, SPECS/xorg-x11-server/CVE-2023-6478.patch, SPECS/xorg-x11-server/xorg-x11-server.spec
---
xorg-x11-server: add patches for CVE-2023-6377 and CVE-2023-6478 
- xorg-x11-server: add patches for CVE-2023-6377 and CVE-2023-6478 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-6377
- https://nvd.nist.gov/vuln/detail/CVE-2023-6478
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=474719&view=results
=> xorg-x11-server: add patches for CVE-2023-6377 and CVE-2023-6478

SPECS/python-cryptography/CVE-2023-49083.patch, SPECS/python-cryptography/python-cryptography.spec, SPECS/pytorch/pytorch.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Patch CVE-2023-49083 in python-cryptography (#7104)

SPECS/dbus/dbus.signatures.json, SPECS/dbus/dbus.spec, cgmanifest.json
---
Update to v1.15.6 to fix CVE-2023-34969
- Update to v1.15.6 to fix CVE-2023-34969
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-34969
- Local build
- Buddy build succeeded: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=475019&view=results
=> dbus: Update to v1.15.6 to fix CVE-2023-34969

SPECS/postgresql/postgresql.signatures.json, SPECS/postgresql/postgresql.spec, cgmanifest.json
---
update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870
- update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-5868
- https://nvd.nist.gov/vuln/detail/CVE-2023-5869
- https://nvd.nist.gov/vuln/detail/CVE-2023-5870
- Local build, all tests passed
=> postgresql: update to v14.10 to fix CVE-2023-5868, CVE-2023-5869 and CVE-2023-5870

SPECS/openssh/CVE-2023-51384.patch, SPECS/openssh/CVE-2023-51385.patch, SPECS/openssh/openssh.spec
---
Add patches for CVE-2023-51384 and CVE-2023-51385
- Add patches for CVE-2023-51384 and CVE-2023-51385
**NO**
- CVE-2023-51384
- CVE-2023-51385
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=474768&view=results
=> openssh: Add patches for CVE-2023-51384 and CVE-2023-51385

SPECS/apparmor/CVE-2023-50471.patch, SPECS/apparmor/apparmor.spec
---
apparmor: add patches for CVE-2023-50471 and CVE-2023-50472
- apparmor: add patches for CVE-2023-50471 and CVE-2023-50472
**NO**
- CVE-2023-50471 
- CVE-2023-50472
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=475464&view=results
=> apparmor: add patches for CVE-2023-50471 and CVE-2023-50472

SPECS/iperf3/iperf3.signatures.json, SPECS/iperf3/iperf3.spec, cgmanifest.json
---
Upgrade version 3.14 -> 3.16
- upgrade version 3.14 -> 3.16
**NO**
- NA
- NA
- [PR-7145](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=476415&view=results) ❌ 
- [PR-7145](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=476507&view=results) ✅
=> iperf3: upgrade version 3.14 -> 3.16

SPECS/haproxy/haproxy.signatures.json, SPECS/haproxy/haproxy.spec, cgmanifest.json
---
Upgrade version 2.4.24 -> 2.9.1
- Upgrade version 2.4.24 -> 2.9.1
**NO**
- NA
- NA
- Pipeline build id: [PR-7146](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=476427&view=results)
Local Build:
=> haproxy: upgrade version 2.4.24 -> 2.9.1

SPECS/perl-Data-Dump/perl-Data-Dump.signatures.json, SPECS/perl-Data-Dump/perl-Data-Dump.spec, cgmanifest.json
---
Mariner 3.0 - perl-Data-Dump upgrade
- Change
- Change
- Change
**NO**
- #xxxx
=> Mariner 3.0 - perl-Data-Dump upgrade

SPECS/moby-cli/CVE-2023-48795.patch, SPECS/moby-cli/moby-cli.spec
---
Patch CVE-2023-48795 for moby-cli.
Patch was obtained from https://github.com/golang/crypto/commit/9d2ee975ef9fe627bf0a6f01c1f69e8ef1d4f05d and backported. 
Required changes for backport:
* Remove all changes for 'handshake_test.go' which doesn't exist in our version of the package.
* Add initialization of missing variable that is used in the CVE patch
- Patches CVE-2023-48795 for moby-cli
**NO**
None
- Pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=480783&view=results
=> Patch CVE-2023-48795 in moby-cli

SPECS/python-cytoolz/python-cytoolz.spec
---
This change is needed to fix the p-test failure.
Remove CPython from %check pip3 install.
**NO**
N/A
N/A
Failing Test before change: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=480176&view=results
Successful Test after change: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=480195&view=results
=> Remove CPython from %check pip3 install in cytools

SPECS/python-gevent/python-gevent.signatures.json, SPECS/python-gevent/python-gevent.spec, SPECS/python-gevent/tests_to_ignore.txt
---
- Address the test failures in python-gevent v21.1.2, disabling a couple of flaky test cases that require network access.
- Add tests_to_ignore.txt containing the test files to be skipped
- Update the test run command to disable network access, since only the basic functionalities of the package needs to be tested.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/48415017
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=481314&view=results
=> python-gevent: Disable flaky test failure

SPECS/guile/guile.signatures.json, SPECS/guile/guile.spec, cgmanifest.json
---
Upgrade guile for mariner 3.0.
**YES/NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=481392&view=results
=> Upgrade guile from 2.0.14 to 3.0.9

SPECS/fluent-bit/CVE-2023-52284.patch, SPECS/fluent-bit/fluent-bit.spec
---
- Fix CVE-2023-52284
- Address CVE-2023-52284
- Change to autosetup
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-52284
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=481309&view=results
=> [2.0] Fix fluent-bit CVE-2023-52284

SPECS/openssh/CVE-2023-48795-0001-upstream-Always-return-allocated-strings-from-the-ke.patch, SPECS/openssh/CVE-2023-48795-0002-upstream-fix-double-free-caused-by-compat_kex_propos.patch, SPECS/openssh/CVE-2023-48795-0003-upstream-Remove-now-unused-compat-bit-SSH_BUG_BIGEND.patch, SPECS/openssh/CVE-2023-48795-0004-upstream-Remove-now-unused-compat-bit-SSH_BUG_RSASIG.patch, SPECS/openssh/CVE-2023-48795-0005-upstream-Don-t-leak-the-strings-allocated-by-order_h.patch, SPECS/openssh/CVE-2023-48795-0006-upstream-Remove-leftover-line.patch, SPECS/openssh/CVE-2023-48795-0007-upstream-Refactor-creation-of-KEX-proposal.patch, SPECS/openssh/CVE-2023-48795-0008-upstream-Limit-number-of-entries-in-SSH2_MSG_EXT_INF.patch, SPECS/openssh/CVE-2023-48795-0009-upstream-implement-strict-key-exchange-in-ssh-and-ss.patch, SPECS/openssh/openssh.spec
---
Fix CVE-2023-48795 for openssh
Also fixes openssh build tests
Add patches to fix CVE-2023-48795
Remove -fvisibility=hidden from build CFLAGS
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=482307&view=results
=> Fix CVE-2023-48795 for openssh

SPECS/reaper/CVE-2023-26159.patch, SPECS/reaper/reaper.spec
---
- Add patch to resolve CVE-2023-26159
- Add patch to resolve CVE-2023-26159
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-26159
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=482510&view=results
=> [2.0] Fix reaper CVE-2023-26159

SPECS/freeipmi/freeipmi.signatures.json, SPECS/freeipmi/freeipmi.spec, cgmanifest.json
---
Upgrade freeipmi for 3.0-dev
- 1.6.6 -> 1.6.11
**NO**
- None
- None
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=482325&view=results
=> upgrade freeipmi to 1.6.11.1 3.0 dev

SPECS/cracklib/cracklib.signatures.json, SPECS/cracklib/cracklib.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- 3.0 package upgrade effort
- upgrade from 2.9.7 to 2.9.11
- adds man pages to files section
**YES**
- Pipeline build id: [484007](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=484007&view=results)
=> cracklib: upgrade from 2.9.7 to 2.9.11

SPECS/freetds/freetds.signatures.json, SPECS/freetds/freetds.spec, cgmanifest.json
---
Upgrade 1.1.20 -> 1.3.20
- Upgrade 1.1.20 -> 1.3.20
**NO**
- NA
- NA
- [PR-7094](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=479824&view=logs&j=21e55549-fa44-57d8-4936-64132e3ceec0&t=8e6f9516-5704-5480-d4b1-637f5c23550a) ❌ 
- [PR-7094](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=481552&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=fbeef549-39ab-510c-faa3-78579a516b53) ✅ 
local build:
=> freetds: upgrade 1.1.20 -> 1.4.10

SPECS/gsm/gsm-makefile.patch, SPECS/gsm/gsm.signatures.json, SPECS/gsm/gsm.spec, cgmanifest.json
---
- gsm: upgrade version 1.0.19 -> 1.0.22
- gsm: add newline EOF
- gsm: upgrade version 1.0.19 -> 1.0.22
- gsm: add newline EOF
**NO**
- NA
- NA
- Pipeline build id: [PR-7192](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=479937&view=results)
Local Build:
=> gsm: upgrade version 1.0.19 -> 1.0.22

.github/workflows/go-test-coverage.yml, .github/workflows/quickstart_1.0.yml, .github/workflows/quickstart_2.0.yml
---
Bump `setup-go` github action to v5
**NO**
- NA
- NA
- NA
=> workflows: bump setup-go to v5

SPECS/kured/kured-imagePullPolicy.patch, SPECS/kured/kured.signatures.json, SPECS/kured/kured.spec, cgmanifest.json
---
This PR updates kured to version 1.14.2 to fix CVE-2023-39325.
- kured is upgraded to 1.14.2 to fix CVE-2023-39325
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39325
- Pipeline build id: [484633](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=484633&view=results)
=> Upgrade kured to 1.14.2 for vendored go CVE-2023-39325

SPECS/postfix/CVE-2023-51764.patch, SPECS/postfix/postfix.spec
---
- Fix postfix CVE-2023-51764
- Fix CVE-2023-51764
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-51764
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=481432&view=results
=> [2.0] Fix postfix CVE-2023-51764

SPECS/asciidoc/asciidoc.signatures.json, SPECS/asciidoc/asciidoc.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade asciidoc to 10.2.0
- NA
**NO**
- NA
- NA
- Uniform Buddy Build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=484390)
=> Upgrade asciidoc to 10.2.0

SPECS/libslirp/libslirp.signatures.json, SPECS/libslirp/libslirp.spec, cgmanifest.json
---
libslirp package upgrade from 4.6.1 to 4.7.0
3.0 package upgrades
- Upgrade slirp to 4.7.0
- Updated source URL to a generic URL that allows autoupgrades in the future
**NO**
- #xxxx
- local,
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486225&view=results
=> Upgrade libslirp from 4.6.1 to 4.7.0

toolkit/tools/imagecustomizerapi/user.go, toolkit/tools/imagegen/configuration/user.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
---
https://github.com/microsoft/CBL-Mariner/pull/6824#discussion_r1406527775
as recommended, this is a follow-up separate pt for previous emu pr, 
NO
=> OS Modifier (EMU): Add sshkeys to user config

SPECS/cloud-init/cloud-init.spec, cgmanifest.json
---
Recently ptests for `cloud-init` started to fail. The culprit seems to be an update to `jsonschema` - one of the test dependencies. I'm switching to using our `python3-jsonschema` package.
- Replaced upstream `jsonschema` module with ours.
- Fixed the source URL.
No.
- Local test run.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=486690&view=results).
=> Fixed `cloud-init` tests.

SPECS/numad/0001-numad_log-fix-buffer-overflow.patch, SPECS/numad/numad.spec
---
Add patch from several months ago (the only meaningful change in the last several years).
- add patch file
**YES/NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=487402&view=results
=> Add patch to numad

.pipelines/containerSourceData/memcached/Dockerfile-Memcached, .pipelines/containerSourceData/memcached/memcached.pkg, .pipelines/containerSourceData/scripts/BuildGoldenContainers.sh
---
This PR adds the source files utilized in constructing the CBL-Mariner-based memcached container image within the ADO repository. These files include dockerfile and package composition file specific to the container. The build script is also updated. The pipeline yaml files and some additional scripts required by the build pipelines are updated in [this](https://dev.azure.com/mariner-org/mariner/_git/CBL-Mariner-Pipelines/pullrequest/17659) PR.
No changes were made to packages or toolkit.
**NO**
Osama Esmail did the original work for this PR. This PR is simply bringing the files overs.
=> add memcached container files

toolkit/tools/imagegen/installutils/installutils.go
---
Building a Mariner image occurs within a chroot environment. To make the chroot environment more useful, a bunch of special directories (e.g. /dev, /proc) are mounted into the OS image. However, this causes problems when applying the SELinux labels to the filesystem since mount-point directories are hidden by the mounts and therefore don't receive their SELinux labels.
This change fixes this problem by using bind mounts to get an unobstructed view of each filesystem.
- Fix SELinux labeling of special dirs
NO
- Manually built and verified SELinux image.
=> Fix SELinux labeling of special dirs

SPECS/color-filesystem/color-filesystem.spec
---
Upgrade color-filesystem to 3.0
**NO**
- Pipeline build id: [488456](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488456&view=results)
Color-filesystem is a dependency for colord (in specs) and icc-profiles-openicc (in specs-extended).
Build of colord and color-filesystem together doesn't work because colord is blocked on other dependencies.
=> Update color-filesystem to 3.0 

SPECS/libnfs/libnfs.signatures.json, SPECS/libnfs/libnfs.spec, cgmanifest.json
---
- libnfs: upgrade version 4.0.0 -> 5.0.2
- libnfs: upgrade version 4.0.0 -> 5.0.2
**NO**
- NA
- NA
- Pipeline build id: [PR-7362](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488252&view=results)
=> libnfs: upgrade version 4.0.0 -> 5.0.2

SPECS/sleuthkit/sleuthkit.signatures.json, SPECS/sleuthkit/sleuthkit.spec, cgmanifest.json
---
Upgrade sleuthkit to version 4.12.1
- Upgrade sleuthkit to version 4.12.1
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488520&view=results
=> sleuthkit: upgrade to 4.12.1

SPECS/git-lfs/git-lfs.signatures.json, SPECS/git-lfs/git-lfs.spec, cgmanifest.json
---
- git-lfs: upgrade version 3.1.4 -> 3.4.1
- git-lfs: upgrade version 3.1.4 -> 3.4.1
**NO**
- NA
- NA
- Pipeline build id: [PR-7361](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488238&view=results)
=> git-lfs: upgrade version 3.1.4 -> 3.4.1 

SPECS/skopeo/skopeo.signatures.json, SPECS/skopeo/skopeo.spec, cgmanifest.json
---
Upgrade version to 1.14.1 to address https://github.com/advisories/GHSA-jq35-85cj-fj4p
- Upgrade Version 1.13.3 -> 1.14.1
**NO**
- https://github.com/advisories/GHSA-jq35-85cj-fj4p
- NA
- Pipeline build id: [PR-7357](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488131&view=results)
=> skopeo: upgrade version 1.13.3 -> 1.14.1 to address GHSA-jq35-85cj-fj4p

SPECS/environment-modules/environment-modules.signatures.json, SPECS/environment-modules/environment-modules.spec, cgmanifest.json
---
Upgrade environment-modules to version 5.3.1
- Upgrade environment-modules to version 5.3.1
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488512&view=results
=> environment-modules: upgrade to 5.3.1

SPECS/autogen/allow-guile-3.0.patch, SPECS/autogen/autogen.spec
---
Patch autogen to build with guile 3.x
The current autogen release (5.18.16) does not build with Guile > 2.2. The
guile version available in AzL 3 is 3.0.9. Patch atutogen to
allow Guile 3.x versions as well.
See https://sourceforge.net/p/autogen/bugs/196/
**No**
Buddy build -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489039&view=results
=> Patch autogen to build with guile 3.x

SPECS/helm/helm.signatures.json, SPECS/helm/helm.spec, cgmanifest.json
---
- helm: update version 3.13.2 -> 3.14.0 to address CVE-2023-44487
- helm: update version 3.13.2 -> 3.14.0 to address CVE-2023-44487
**NO**
- NA
- [PR-7359](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488156&view=results) ❌ 
- [PR-7359](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488177&view=results) ✅
=> helm: update version 3.13.2 -> 3.14.0 to address CVE-2023-44487

toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
---
This PR commit switches to use the default way mkinitrd to build / update the initrd img for DM-Verity, instead of using dracut to build another new initramfs img. The reasons:
1. Streamlining the update process: By updating the existing initrd, we eliminate an extra step previously required for updating initramfs.
2. Ensuring consistency during downstream operations: When the image is passed to downstream Trident for RAID operations, it necessitates the rebuilding of initrd. Adopting this approach ensures consistency in the initrd images.
**NO**
- Internal bug: 6541
- Local build
=> Switch to mkinitrd for updating initrd img for DM-Verity.

SPECS/firewalld/firewalld.signatures.json, SPECS/firewalld/firewalld.spec, cgmanifest.json
---
Upgrade for mariner 3.0
* Update version in spec
* Update source tar
**YES/NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=483051&view=results
=> Upgrade firewalld from 1.0.3 to 2.0.2

SPECS/isns-utils/isns-utils.signatures.json, SPECS/isns-utils/isns-utils.spec, cgmanifest.json
---
Upgrade for mariner 3.0
- Update 0.101 to 0.102
- Update spec to include new devel *.pc file
**YES/NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=484660&view=results
- local tdnf install for pipeline RPMs
=> Upgrade isns-utils from 0.101 to 0.102

SPECS/dbus/dbus.signatures.json, SPECS/dbus/dbus.spec, cgmanifest.json
---
Upgrade dbus for 3.0 from 1.15.2 to 1.15.8
* Update version
* Update source tar
* Update spec build bits
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=483059&view=results
=> Upgrade dbus from 1.15.2 to 1.15.8

SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec, SPECS/kernel-hci/0028-net-mlx5-Bridge-Use-debug-instead-of-warn-if-entry-d.patch, SPECS/kernel-hci/kernel-hci.spec
---
Add missing commit subject to patch 27 to fix downstream automation errors
- Add missing commit subject to patch 27
- Rename patch
No
- Pipeline build id: [488401](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488401)
=> kernel-hci: Add missing commit subject to patch 27

SPECS/python-pluggy/python-pluggy.signatures.json, SPECS/python-pluggy/python-pluggy.spec, cgmanifest.json
---
Upgrade python-pluggy to 1.3.0
- Upgrade python-pluggy to 1.3.0
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489788&view=results
=> python-pluggy: upgrade to 1.3.0

SPECS/c-ares/c-ares.signatures.json, SPECS/c-ares/c-ares.spec, cgmanifest.json
---
Upgrade c-ares to 1.25.0
- NA
**NO**
- NA
- NA
- Uniform Buddy Build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=489853)
=> Upgrade c-ares to 1.25.0

SPECS/squashfs-tools/squashfs-tools.signatures.json, SPECS/squashfs-tools/squashfs-tools.spec, cgmanifest.json
---
Upgrade squashfs-tools to target version in 3.0-dev
- squashfs-tools 4.5.1 -> 4.6.1
**NO**
- None
- None
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=483100
=> upgrade squashfs-tools to 4.6.1 3.0-dev

SPECS/python-virtualenv/python-virtualenv.spec
---
The python3-virtualenv package was missing a runtime dependency (python3-six).
- Fixed runtime dependency for python3-virtualenv 
**NO**
- Pipeline build id: 491080
- Local build, install and test
=> Fix runtime dependency for python3-virtualenv

.github/CODEOWNERS
---
As discussed previously in https://github.com/microsoft/CBL-Mariner/pull/7374, the Kata team should own the virtiofsd package since that will be a dependency of the upcoming Kata releases and we should ensure virtiofsd changes don't break Kata.
**NO**
=> Set ownership of virtiofsd package to Kata team

toolkit/README.md, toolkit/docs/how_it_works/0_intro.md, toolkit/docs/how_it_works/5_misc.md, toolkit/docs/how_it_works/6_logs.md
---
This is to start a manual page where we can explain common build errors and how to fix them.
- Added an entry about circular build dependencies.
No.
- Manual click-through.
=> Added initial doc about reading error logs.

toolkit/README.md, toolkit/docs/how_it_works/0_intro.md, toolkit/docs/how_it_works/5_misc.md, toolkit/docs/how_it_works/6_logs.md
---
Port of #7475:
This is to start a manual page where we can explain common build errors and how to fix them.
- Added an entry about circular build dependencies.
No.
- #7475
- See: #7475
=> Port #7475: Added initial doc about reading error logs.

SPECS/kpatch/kpatch.signatures.json, SPECS/kpatch/kpatch.spec, cgmanifest.json
---
- kpatch: upgrade version 0.9.7 -> 0.9.8
- kpatch: upgrade version 0.9.7 -> 0.9.8
**NO**
- NA
- NA
- Pipeline build id: [PR-7363](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=488256&view=results)
Local Build:
=> kpatch: upgrade version 0.9.7 -> 0.9.8

SPECS/byacc/byacc.signatures.json, SPECS/byacc/byacc.spec, cgmanifest.json
---
Upgrade package byacc to latest version for 3.0
**NO**
- Local build
=> Upgrade byacc package to latest version

toolkit/scripts/containerized-build/create_container_build.sh
---
**NO**
- NA
- NA
- Local Build
=> containerized-build: avoid failure if lkg file does not exist

SPECS/kube-vip-cloud-provider/CVE-2022-21698.patch, SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `kube-vip-cloud-provider`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
- Modified the [upstream patch](https://github.com/prometheus/client_golang/commit/9075cdf61646b5adf54d3ba77a0e4f6c65cb4fd7) to work with the older version of `client_golang` used by this package, along with getting rid of tests.
- Fixed up `%prep` section to apply patch.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buil …
=> fix cve-2022-21698 in kube-vip-cloud-provider

SPECS/azure-iot-sdk-c/azure-iot-sdk-c.signatures.json, SPECS/azure-iot-sdk-c/azure-iot-sdk-c.spec, cgmanifest.json
- [NA] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [NA] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
---
Upgrade azure-iot-sdk for mariner 3.0
- Updated spec file
- Downloaded and generated tar for package manually
- Changed to tar.gz to match standard of all other packages (and upstream)
NO
=> Upgrade azure-iot-sdk-c 3.0

toolkit/imageconfigs/baremetal.json
kernel-hci and kernel are converging in the near future.
---
kernel should be the default. customers needing different kernel should be able to customize their image through image customization tooling.
- Move to kernel from kernel-hci
**NO**
=> Use main kernel for baremetal base image

SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec, SPECS/kernel-mos/config, SPECS/kernel-mos/kernel-mos.signatures.json, SPECS/kernel-mos/kernel-mos.spec, cgmanifest.json
---
Update kernel-mos to 5.15.148.1
- Update kernel-mos to 5.15.148.1
NO
- [Pipeline build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495284)
=> Update kernel-mos to 5.15.148.1

SPECS/gsettings-desktop-schemas/gsettings-desktop-schemas.signatures.json, SPECS/gsettings-desktop-schemas/gsettings-desktop-schemas.spec, cgmanifest.json
---
Upgrade to version 45.0
- Bump version
- lint spec
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495966
=> gsettings-desktop-schemas: Upgrade package to version 45.0

SPECS/intel-ipsec-mb/intel-ipsec-mb.signatures.json, SPECS/intel-ipsec-mb/intel-ipsec-mb.spec, cgmanifest.json
---
Bump version to 1.5.0
- bump version
- lint spec
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=496144
NOTE: This package has ExclusiveArch set to x86_64, so arm64 specific stages will do nothing.
=> intel-ipsec-mb: Upgrade to version 1.5.0

SPECS/tpm2-tss/tpm2-tss.spec
---
Break tpm2-tss circular dependency with systemd-bootstrap-devel
- Break tpm2-tss circular dependency with systemd-bootstrap-devel
**YES/NO**
=> Break tpm2-tss circular dependency with systemd-bootstrap-devel

toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
---
Bug issue:
```
$ dracut --print-cmdline
/etc/dracut.conf.d/systemd-veritysetup.conf:add_dracutmodules+="systemd-veritysetup"
dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file
```
**NO**
- Internal bug link: https://dev.azure.com/mariner-org/ECF/_workitems/edit/6760
=> Bugfix adding dracut config recommended white spaces.

SPECS/libedit/libedit.signatures.json, SPECS/libedit/libedit.spec, cgmanifest.json
---
Upgrade libedit to 3.1.20230828
- NA
**NO**
- NA
- NA
- Uniform Buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=495834&view=results)
=> Upgrade libedit to 3.1.20230828

SPECS/acpica-tools/acpica-tools.spec, SPECS/acpica-tools/gcc-fix-dangling-pointer-error.patch
---
Fix `acpica-tools` build break with gcc 13 by adding patch
- Fix `acpica-tools` build break with gcc 13 by adding patch
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=497915&view=results
=> acpica-tools: fix break

toolkit/tools/imagecustomizerapi/systemconfig_test.go, toolkit/tools/imagecustomizerapi/verity.go, toolkit/tools/imagecustomizerapi/verity_test.go, toolkit/tools/imagecustomizerapi/veritypartition.go, toolkit/tools/imagecustomizerapi/veritypartition_test.go
---
Append MIC Verity related unit tests.
**NO**
- Local go test
=> imagecustomizer: append unit tests for MIC Verity related.

SPECS/lz4/lz4.signatures.json, SPECS/lz4/lz4.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade lz4 to 1.9.4-1 to fix CVE-2021-3520
- CVE-2021-3520
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-3520
- Local Build
- Build ID: 499070
=> lz4: Upgrade to 1.9.4-1 to fix CVE-2021-3520

SPECS/moby-cli/CVE-2022-21698.patch, SPECS/moby-cli/moby-cli.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `moby-cli`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- #xxxx
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499146&view=results
=> fix cve-2022-21698 in moby-cli

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
- msft-golang: upgrade 1.20.11 -> 1.21.6
PS: none of the packages depend on msft-golang. So there is no dash-roll required for any other packages.
- msft-golang: upgrade 1.20.11 -> 1.21.6
**NO**
- WorkItem: [48735802](https://microsoft.visualstudio.com/OS/_workitems/edit/48735802)
- Related: #7640
- Fixes: #7643 
- NA
- Pipeline build id: [PR-7569](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=494871&view=results)   ✅  (The pipeline install fails because msft-golang conflicts with go)
=> msft-golang: upgrade version 1.20.11 -> 1.21.6

SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch, SPECS/pango/pango.signatures.json, SPECS/pango/pango.spec, cgmanifest.json
---
Upgrade pango to 1.90.0 for 3.0
- Upgrade pango to 1.90.0
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499786&view=results
=> Upgrade pango to 1.90.0

SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, cgmanifest.json
---
Upgrade nvidia-container-toolkit to 1.14.4 for AzL-3.0
Upgrade nvidia-container-toolkit to 1.14.4 for AzL-3.0
**NO**
- Pipeline build id: (498962)[https://dev.azure.com/mariner-org/mariner/_build/results?buildId=498962&view=results]
=> Upgrade nvidia-container-toolkit to 1.14.4 for AzL-3.0

SPECS/nspr/nspr.signatures.json, SPECS/nspr/nspr.spec, SPECS/nss/nss.signatures.json, SPECS/nss/nss.spec, cgmanifest.json
---
Upgrade nspr and upgrade nss
Upgrading nss to version 3.96.1 requires nspr >= 4.34
Upgrade nspr from 4.9.6 to 4.35
**NO**
Local build: 
Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499752&view=results
=> Upgrade nspr; Upgrade nss

SPECS/openssl/openssl.spec
---
with `SymCrypt` handling `FIPS`, we want a runtime dependency on it for `openssl`.
- Added a `Requires` for `SymCrypt`
**YES**
- Tested locally and on a vm that it forces the require.
=> add runtime dependency on SymCrypt

SPECS/graphviz/graphviz.spec
add missing build dep so the package will build
=> graphviz: add build dep gc-devel

SPECS/libcontainers-common/CVE-2021-44716.patch, SPECS/libcontainers-common/libcontainers-common.spec
---
Patches CVE-2021-44716
- Patches CVE-2021-44716
NO
- Pipeline build id: 500206
=> Patch `CVE-2021-44716` in `libcontainers-common`

SPECS/moby-engine/CVE-2022-21698.patch, SPECS/moby-engine/moby-engine.spec
---
Fixes [CVE-2022-21698](https://nvd.nist.gov/vuln/detail/CVE-2022-21698) for `moby-engine`. The vulnerability is in the `client_golang` go module, which is vendored in this package. Fix is to apply a (modified) patch to the vendored code.
**NO**
- #xxxx
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499175&view=results
=> fix cve-2022-21698 in moby-engine

SPECS/iputils/iputils.signatures.json, SPECS/iputils/iputils.spec, cgmanifest.json
---
Upgrade iputils to 20240117
- NA
**NO**
- #xxxx
- NA
- Uniform buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=496225&view=results)
=> Upgrade iputils to 20240117

toolkit/imageconfigs/packagelists/core-packages-image.json, toolkit/tools/imageconfigvalidator/imageconfigvalidator.go, toolkit/tools/imagegen/installutils/installutils.go
…mage types (#6957)"
This reverts commit b5f92064f69b83f20f1191bd9610db713db79300.
---
This PR reverts [PR#6957](https://github.com/microsoft/CBL-Mariner/pull/6957/files), because image validator checks for `shadow-utils` package caused failure in some Mariner images that could be confusing to some customers.
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Revert "Shift user/group creation earlier in image build for rootfs image type"

SPECS/openssl/openssl.spec
---
The new `Requires` added in #7722 created an unresolvable circular dependency. Until we figure out a solution, I'm reverting this change to unblock our builds.
- Reverted #7722.
No.
- #7722
- N/A.
=> Revert "add runtime dependency on SymCrypt (#7722)"

toolkit/tools/imagecustomizer/docs/configuration.md, toolkit/tools/imagecustomizerapi/additionalfilesmap.go, toolkit/tools/imagecustomizerapi/iso.go, toolkit/tools/imagecustomizerapi/systemconfig.go, toolkit/tools/imagecustomizerapi/utils.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> PR comments.

SPECS/createrepo_c/createrepo_c.signatures.json, SPECS/createrepo_c/createrepo_c.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade createrepo_c to 1.0.3
- NA
**YES**
- NA
- NA
- Full toolchain build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=499833&view=results)
=> Upgrade createrepo_c to 1.0.3

SPECS/ctags/ctags.signatures.json, SPECS/ctags/ctags.spec, cgmanifest.json
---
Upgrade ctags to 6.1.0
- NA
**NO**
- NA
- NA
- Uniform buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501682&view=results)
=> Upgrade ctags to 6.1.0

SPECS/iana-etc/iana-etc.signatures.json, SPECS/iana-etc/iana-etc.spec, cgmanifest.json
---
Upgrade iana-etc package to 20240125 ahead of Mariner 3.0 release.
- Upgraded package.
- Uploaded source tarball. 
- Updated signatures and cgmanifest.
**NO**
- Locally built successfully
- Pipeline build id: [https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502275&view=results](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502275&view=results)
=> iana-etc: package upgrade to 20240125

toolkit/imageconfigs/baremetal.json
Increase the verbosity to allow minimum level of debugging. 
Note: Adding extra logging for dracut comes with a penalty on boot time, but it is a trade-off with debuggability. This is another reason why I didn't use `rd.debug` as it is more verbose and will make that worse. 
---
More verbose dracut logs
- Add kernel cmdline args
**NO**
=> Allow dracut info logs to be visible for baremetal base image

SPECS/ed/ed.signatures.json, SPECS/ed/ed.spec, cgmanifest.json
---
Upgrade ed to 1.20
- NA
**NO**
- NA
- NA
- Uniform buddy build pipeline resutls are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501016&view=results)
=> Upgrade ed to 1.20

SPECS/python-pbr/python-pbr.signatures.json, SPECS/python-pbr/python-pbr.spec, cgmanifest.json
Upgrade python-pbr to version 6.0.0 for Mariner 3.0 along with the corresponding changes to signatures and cgmanifest files
---
This PR upgrades python-pbr to version 6.0.0 for Mmariner 3.0.
- Upgrade python-pbr to version 6.0.0
- No existing packages impacted
- No previous CVEs
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502650&view=results
=> Upgrade python-pbr to version 6.0.0 for Mariner 3.0

SPECS/python-pecan/python-pecan.signatures.json, SPECS/python-pecan/python-pecan.spec, cgmanifest.json
Upgrade python-pecan to version 1.5.1 for Mariner 3.0 together with its signatures.json and updates to cgmanifest files
---
This PR upgrades python-pecan to version 1.5.1 for Mariner 3.0.
- Upgrade python-pecn to version 1.5.1
- No other package impacted
- No previous CVEs
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502660&view=results
=> Upgrade python-pecan to version 1.5.1 for Mariner 3.0

SPECS/kube-vip-cloud-provider/CVE-2021-44716.patch, SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
---
Cherry-pick of a fast-track change.
- 
No.
- #7698
- Done during the fast-track PR.
=> Cherry-picked fast-track fix for 'kube-vip-cloud-provider' (#7698).

SPECS/application-gateway-kubernetes-ingress/CVE-2021-44716.patch, SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec, SPECS/cf-cli/CVE-2021-44716.patch, SPECS/cf-cli/cf-cli.spec, SPECS/csi-driver-lvm/CVE-2021-44716.patch, SPECS/csi-driver-lvm/csi-driver-lvm.spec, SPECS/git-lfs/CVE-2021-44716.patch, SPECS/git-lfs/git-lfs.spec, SPECS/jx/CVE-2021-44716.patch, SPECS/jx/jx.spec, SPECS/keda/CVE-2021-44716.patch, SPECS/keda/keda.spec, SPECS/moby-cli/CVE-2021-44716.patch, SPECS/moby-cli/moby-cli.spec
Cherry-pick of #7717.
---
Fix CVE-2021-44716
- Change
- Change
- Change
**NO**
- #7717
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=502971&view=results).
=> Fix CVE-2021-44716 (CP #7717).

.github/CODEOWNERS
---
Require CBL-Mariner-Tooling approval for toolchain manifest modifications
We've seen a number of breaks recently due to toolchain changes.
- Change CODEOWNERS file to require a member of [CBL-Mariner-Tooling](https://github.com/orgs/microsoft/teams/cbl-mariner-tooling) to review toolchain manifest changes
- Fix typo in CODEOWNERS file and provide link to browse mariner team rosters
**NO**
- N/A
=> Require CBL-Mariner-Toolchain approval for toolchain manifest modifications

SPECS/cni-plugins/cni-plugins.signatures.json, SPECS/cni-plugins/cni-plugins.spec, cgmanifest.json
---
Update cni-plugins to 1.4.0
**NO**
- Locally tested
- Pipeline build id: [503780](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=503780&view=results)
=> cni-plugins: update to 1.4.0

SPECS/python-psycopg2/python-psycopg2.signatures.json, SPECS/python-psycopg2/python-psycopg2.spec, cgmanifest.json
Upgrade python-psycopg2 to version 2.9.9 for Mariner 3.0
---
This PR upgrades python-psycopg2 to version 2.9.9 together with its signatures.json and change to cgmanifest.
- Upgrade python-psycopg2 to version 2.9.9
- No exising packages impacted
- No previous CVEs
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=503805&view=results
=> Upgrade python-psycopg2 to version 2.9.9 for Mariner 3.0

SPECS/python-decorator/python-decorator.signatures.json, SPECS/python-decorator/python-decorator.spec, cgmanifest.json
---
Upgraded `python-decorator` to 5.1.1 for 3.0 release
- Upgraded `python-decorator` to 5.1.1 for 3.0 release
NO
- Pipeline build id: 504248
=> Upgrading `python-decorator` to 5.1.1

SPECS/python-pyudev/python-pyudev.signatures.json, SPECS/python-pyudev/python-pyudev.spec, cgmanifest.json
---
python-pyudev: Upgrade to 0.24.1
- python-pyudev: Upgrade to 0.24.1
**NO**
- #xxxx
- Pipeline build id: [504479](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504479&view=results)
=> python-pyudev: Upgrade to 0.24.1

SPECS/moby-engine/CVE-2024-23651.patch, SPECS/moby-engine/CVE-2024-23652.patch, SPECS/moby-engine/moby-engine.spec
---
A bundle of critical and high CVE patches for `moby-engine`.
- Patched CVEs from the title.
No.
- https://nvd.nist.gov/vuln/detail/2024-23651
- https://nvd.nist.gov/vuln/detail/2021-23652
- PR check.
=> Patched `moby-engine` CVEs: 2024-23651 and 2024-23652.

SPECS/python-typing-extensions/python-typing-extensions.signatures.json, SPECS/python-typing-extensions/python-typing-extensions.spec, cgmanifest.json
---
python-typing-extensions: Upgrade to 4.9.0
- python-typing-extensions: Upgrade to 4.9.0
**NO**
- #xxxx
- Pipeline build id: [504516](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504516&view=results)
=> python-typing-extensions: Upgrade to 4.9.0

.github/CODEOWNERS
---
Just like it was done in #7474 for 2.0:
> As discussed previously in https://github.com/microsoft/CBL-Mariner/pull/7374, the Kata team should own the virtiofsd package since that will be a dependency of the upcoming Kata releases and we should ensure virtiofsd changes don't break Kata.
**NO**
=> [3.0-dev] Set Kata team as owners of virtiofsd

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Removes obsolete no-vmw-sta from the command line to clean it up
- Remove no-vmw-sta from kernel command line
**YES**
- Pipeline build id: [504858](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504858&view=results)
=> kernel: Remove no-vmw-sta command line argument

SPECS/python-docutils/python-docutils.signatures.json, SPECS/python-docutils/python-docutils.spec, cgmanifest.json
---
Upgrading `python-docutils` to 0.20.1
- Upgrading `python-docutils` to 0.20.1
NO
- Pipeline build id: 504983
=> Upgrading `python-docutils` to 0.20.1

SPECS/python-pytest-benchmark/python-pytest-benchmark.signatures.json, SPECS/python-pytest-benchmark/python-pytest-benchmark.spec, cgmanifest.json
---
Upgrade python-pytest-benchmark to 4.0.0
- NA
**NO**
- NA
- NA
- Uniform buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504860&view=results).
=> Upgrade python-pytest-benchmark to 4.0.0

toolkit/tools/internal/packagerepo/repomanager/rpmrepomanager/rpmrepomanager.go
---
Add --compatibility flag while updating the repo metadata.
Similar to the changes added to our Github repo tools in PR https://github.com/microsoft/CBL-Mariner/pull/7837 , this pr adds --compatibility flag while calling createrepo with --update flag as well. This flag does not change any existing behavior to previous versions of the package so it can be safely merged any time
- NA
**NO**
- NA
- NA
=> Add --compatibility flag while updating the repo metadata

SPECS/node-problem-detector/node-problem-detector.spec, SPECS/prometheus-process-exporter/prometheus-process-exporter.spec, SPECS/rook/rook.spec
---
Update the change logs to keep correct published order
- Update the change logs
**NO**
=> Fix the change logs to keep correct published order

toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
---
[MIC] ensure that an absent iso configuration is permitted.
A user may choose to set the MIC output format to iso and not specify any iso configurations. In such a scenario, the iso data structure will be nil and the code need to handle that gracefully. This fix protects the code from crashing.
- [[MIC] ensure that an absent iso configuration is permitted](https://github.com/microsoft/CBL-Mariner/commit/b00cb06fa0995b0bfbfb1263846135bb4fcbce5d)
**NO**
- n/a
- n/a
- local build/run
=> [MIC ISO] fix crash and ensure that an absent iso configuration is permitted.

SPECS/tuned/skip-gui-files.patch, SPECS/tuned/tuned.signatures.json, SPECS/tuned/tuned.spec, cgmanifest.json
---
This PR makes changes to upgrade tuned from v2.15.0 to v2.21.0
- Upgrade package version to 2.21.0
- Modifying SPEC file to reflect upstream changes (https://github.com/redhat-performance/tuned/blob/v2.21.0/tuned.spec)
**NO**
- Pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=504449&view=results
=> tuned: Update from 2.15.0 to 2.21.0 in Mariner 3.0

SPECS/libpsm2/libpsm2.signatures.json, SPECS/libpsm2/libpsm2.spec, cgmanifest.json
---
Upgrading libpsm2 to 12.0 version for mariner 3.0
- Upgrading to latest version for Mariner 3.0
- Adding BuildRequires: perl and BuildRequires: systemd-rpm-macros
**NO**
- Passed buddy build : [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505931&view=results)
=> libpsm2 upgrade to v12.0

SPECS/lshw/lshw.signatures.json, SPECS/lshw/lshw.spec, cgmanifest.json
---
Upgrading lshw to latest version for 3.0
**NO**
- Passed local build
- Passed buddy build : [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505198&view=results)
=> Upgrading lshw to B.02.20

SPECS/libnetfilter_cthelper/libnetfilter_cthelper.signatures.json, SPECS/libnetfilter_cthelper/libnetfilter_cthelper.spec, cgmanifest.json
---
Upgrading the libnetfilter_cthelper package in Mariner 3.0 to 1.0.1
- Update version from 1.0.0 to 1.0.1
**NO**
- Pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505965&view=results
=> libnetfilter_cthelper: Update from 1.0.0 to 1.0.1 in Mariner 3.0

SPECS/python-zope-interface/python-zope-interface.signatures.json, SPECS/python-zope-interface/python-zope-interface.spec, cgmanifest.json
---
python-zope-interface: upgrade to 6.1
- python-zope-interface: upgrade to 6.1
**NO**
- #xxxx
- Pipeline build id: [505626](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505626&view=results)
=> python-zope-interface: upgrade to 6.1

SPECS/kernel/CVE-2023-6531.nopatch
---
Address CVE-2023-6531
- Address CVE-2023-6531
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-6531
=> Kernel: Address CVE-2023-6531

SPECS/gdk-pixbuf2/gdk-pixbuf2.signatures.json, SPECS/gdk-pixbuf2/gdk-pixbuf2.spec, cgmanifest.json
---
- upgrades gdk pixbuf2 to latest
NO
- Pipeline build id: buddy build - 506814
=> upgrade gdk-pixbuf2 to 2.42.10

SPECS/xcursor-themes/xcursor-themes.signatures.json, SPECS/xcursor-themes/xcursor-themes.spec, cgmanifest.json
---
Upgrading xcursor-themes package to 1.0.7 
**NO**
- Passed local build
- Pipeline build id: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=506917&view=results)
=> Upgrading xcursor-themes to 1.0.7

SPECS/virtiofsd/virtiofsd.spec
---
Build for ARM64 failed due to `virtiofsd` not compiled on ARM architecture.
Drop ExclusiveArch: x86_64 to enable build on all supported platforms
**NO**
- #7215
- NA
- Pipeline build id: [PR-7921](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=507264&view=results)
=> [RFC] virtiofsd: enable build on all supported platforms

SPECS/libgit2/libgit2.signatures.json, SPECS/libgit2/libgit2.spec, cgmanifest.json
---
Upgrade libgit2 to latest 1.7.2
**Buddy build passes partially due to active bug access to dependencies - https://microsoft.visualstudio.com/OS/_workitems/edit/48642241
Local build + install passes.**
- upgrade libgit2 to 1.7.2
NO
- Pipeline build id: buddy build - 506912 
- Local build + install
=> libgit2: upgrade to 1.7.2 

SPECS/dconf/dconf.signatures.json, SPECS/dconf/dconf.spec, cgmanifest.json
---
Upgrading dconf from 0.36.0 to 0.40.0 for Azure Linux 3.0
- Upgrading dconf from 0.36.0 to 0.40.0 for Azure Linux 3.0
NO
- local build
- buddy build [[Link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=507898&view=results)]
=> upgrade: dconf from 0.36.0 to 0.40.0

SPECS/hivex/hivex.signatures.json, SPECS/hivex/hivex.spec, cgmanifest.json
---
upgrade hivex to 1.3.23
- upgraded to 1.3.23
NO
- Pipeline build id: [507698](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=507698&view=results)
- Local build and install successful
=> hivex: upgrade hivex to 1.3.23

SPECS/flannel/flannel.signatures.json, SPECS/flannel/flannel.spec, cgmanifest.json
---
Upgrade to version 0.24.2
- Bump version
NO
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=509530&view=results
=> flannel: Upgrade to version 0.24.2

toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
There have been several instances of unexpected package rebuilds (often leading to build failures due to multiple builds attempting to use a single worker chroot). Packages in the graph should never be processed more than once.
Add a check to flag this state immediately.
(A tentative cause was the revert of https://github.com/microsoft/CBL-Mariner/pull/6288 which may have resolved this).
- Add checks to the scheduler for duplicated build requests.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/49027231
- 
- Local builds of 3.0
=> Don't allow multiple build queues

SPECS/kernel-mshv/kernel-mshv.signatures.json
---
Fix build break due to kernel-mshv mismatched signature. I forgot to update the sigs after correcting a whitespace nit in https://github.com/microsoft/CBL-Mariner/pull/6343 
NO
=> fix: correct kernel-mshv signatures.json

SPECS/python-sphinxcontrib-devhelp/python-sphinxcontrib-devhelp.signatures.json, SPECS/python-sphinxcontrib-devhelp/python-sphinxcontrib-devhelp.spec, cgmanifest.json
---
Upgrade python-sphinxcontrib-devhelp package to 1.0.6 ahead of Mariner 3.0 release.
- Upgraded package.
- Uploaded source tarball. 
- Updated signatures and cgmanifest.
- Updated tests and build commands to use modern pyproject instead of setup.py in line with upstream changes.
**NO**
- Locally built successfully with RUN_CHECK=y 
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510411&view=results
=> python-sphinxcontrib-devhelp: package upgrade to 1.0.6

SPECS/python-pywbem/python-pywbem.signatures.json, SPECS/python-pywbem/python-pywbem.spec, cgmanifest.json
---
Upgrades python-pywbem to the latest version
- Upgrade to 1.6.2
NO
- Pipeline build id: [510435](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510435&view=results)
=> python-pywbem: upgrade to 1.6.2

SPECS/python-sphinxcontrib-serializinghtml/python-sphinxcontrib-serializinghtml.signatures.json, SPECS/python-sphinxcontrib-serializinghtml/python-sphinxcontrib-serializinghtml.spec, cgmanifest.json
---
Upgrade python-sphinxcontrib-serializinghtml package to 1.1.10 ahead of Mariner 3.0 release.
- Upgraded package.
- Uploaded source tarball. 
- Updated signatures and cgmanifest.
- Updated tests and build commands to use modern pyproject instead of setup.py in line with upstream changes.
**NO**
- Locally built successfully with RUN_CHECK=y 
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510472&view=results
=> python-sphinxcontrib-serializinghtml: package upgrade to 1.1.10

SPECS/efivar/efivar.signatures.json, SPECS/efivar/efivar.spec, cgmanifest.json
---
Upgrade efivar to version 39
- Spec upgrade and add two new build dependencies
**NO**
- Pipeline build id: 509801, 510471
=> Upgrade efivar to version 39

SPECS/golang/golang.spec
---
Include `go.env` in GOROOT which is now the default value from where GOPROXY value is read
- Include `go.env` in GOROOT
**NO**
- Fixes: #7640
- NA
- Pipeline build id: [PR-8004](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510488&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=fbeef549-39ab-510c-faa3-78579a516b53)
=> golang: include go.env in GOROOT

SPECS/javapackages-tools/javapackages-tools.signatures.json, SPECS/javapackages-tools/javapackages-tools.spec, cgmanifest.json
---
Update javapackages-tools to v6.1.0
- Update javapackages-tools to v6.1.0
**NO**
- BuddyBuild: [506936](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=506936&view=results)
=> javapackages-tools: upgrade to 6.1.0

SPECS/python-h5py/0001-Fix-compiling-fileobj-file-driver-with-Cython-3.0.patch, SPECS/python-h5py/python-h5py.signatures.json, SPECS/python-h5py/python-h5py.spec, cgmanifest.json
---
Upgrade h5py to latest 3.10.0
- Upgrade h5py to latest 3.10.0
NO
- Pipeline build id: [510523](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510523&view=results)
=> python-h5py: upgrade to 3.10.0

SPECS/efibootmgr/efibootmgr.signatures.json, SPECS/efibootmgr/efibootmgr.spec, cgmanifest.json
---
This PR upgrades the version of efibootmgr from 16 to 18, which is the latest official release: https://github.com/rhboot/efibootmgr/releases/tag/18. This PR is part of Mariner 3.0 package upgrades.
- Upgraded efibootmgr to 18
**NO**
- Buddy build succeeded: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510579&view=results.
=> Upgrading efibootmgr to the latest official release version 18

SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch, SPECS/pango/pango.signatures.json, SPECS/pango/pango.spec, cgmanifest.json
---
Pango was recently updated to version 1.90.0, but that is not the correct latest official release from the upstream project. The correct latest supported version is 1.51.2.
- Updated to package version 1.51.2 since this is the current latest official release
- Updated the patch to skip tests to skip known failures
**NO**
- Local build passed with RUN_CHECK=y
- Buddy build passed: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510573&view=results)
=> Updating Pango to the latest official release version (1.51.2) 

SPECS/python-sphinx-theme-alabaster/python-sphinx-theme-alabaster.signatures.json, SPECS/python-sphinx-theme-alabaster/python-sphinx-theme-alabaster.spec, cgmanifest.json
---
This PR upgrades the version of python-sphinx-theme-alabaster from 0.7.12 to 0.7.16, which is the latest official release: https://codeload.github.com/sphinx-doc/alabaster/tar.gz/refs/tags/0.7.16. This PR is part of Mariner 3.0 package upgrades.
- Upgraded python-sphinx-theme-alabaster to 0.7.16.
**NO**
- Buddy build succeeded: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510853&view=results
- Local build with RUN_CHECK=y succeeded.
=> Upgrading python-sphinx-theme-alabaster to the latest official release version 0.7.16

SPECS/wayland/wayland.signatures.json, SPECS/wayland/wayland.spec, cgmanifest.json
---
Upgrades wayland to 1.22.0
- Upgrade wayland to 1.22.0
**NO**
- Pipeline build id: [505762](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505762&view=logs&j=7909073b-e471-53c1-2c44-627e2efc0564&t=fbeef549-39ab-510c-faa3-78579a516b53)
=> Upgrade wayland to 1.22.0

SPECS/python-packaging/python-packaging.signatures.json, SPECS/python-packaging/python-packaging.spec, cgmanifest.json
---
Upgrade python-packaging for AzL 3.0
**NO**
- Local build
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510313&view=results
=> Upgrade python-packaging for AzL 3.0

SPECS/glib-networking/glib-networking.signatures.json, SPECS/glib-networking/glib-networking.spec, cgmanifest.json
---
Upgrades glib-networking to 2.78.0
- Upgrade glib-networking to 2.78.0
**NO**
- Pipeline build id: [505061](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505061&view=results)
=> Upgrade glib-networking to 2.78.0

SPECS/elixir/elixir.signatures.json, SPECS/elixir/elixir.spec, cgmanifest.json
---
Updating `elixir` to the latest version.
- Updated `elixir`.
No.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=509858&view=results)
- Local build.
=> Updated `elixir` to version 1.16.1.

SPECS/python-distro/python-distro.signatures.json, SPECS/python-distro/python-distro.spec, cgmanifest.json
---
Upgrading `python-distro` to 1.9.0 for 3.0 upgrade
- Upgrading `python-distro` to 1.9.0
NO
- Pipeline build id: 510518
=> Upgrading `python-distro` to 1.9.0

toolkit/tools/imagegen/diskutils/diskutils.go, toolkit/tools/imagegen/diskutils/initramfs.go, toolkit/tools/imagegen/diskutils/lvm.go, toolkit/tools/imagegen/diskutils/verity.go
---
fix error logging in imagegen diskutils
- fix error logging in imagegen diskutils
**NO**
- Local build
=> fix error logging in imagegen diskutils

toolkit/tools/downloader/downloader.go
---
fix error format in downloader
- fix error format in downloader
**NO**
- Local build
=> downloader: fix error format

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imagegen/installutils/overlay.go
---
fix error logging in imagegen installutils
- fix error logging in imagegen installutils
**NO**
- Local build
=> fix logging in imagegen installutils

toolkit/tools/imager/imager.go
---
fix error logging in imager
- Catch and print/throw error wherever missing
- Throw instead of log error in util code
- Fix print format
**NO**
- Local build
=> fix logging in imager

toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go
---
fix error logging in rpmssnaphot
- fix error logging in rpmssnaphot
**NO**
- Local build
=> fix error logging in rpmssnapshot

SPECS/python-prettytable/0001-replace-to-flit.patch, SPECS/python-prettytable/python-prettytable.signatures.json, SPECS/python-prettytable/python-prettytable.spec, cgmanifest.json
---
Updates the package to 3.10.0 for Azl3.0. Needed for upcoming preview release.
- Updated spec to build version 3.10.0 for Mariner 3.0
- Added patch to use python3-flit-core as build-backend rather than hatchling (which is not yet supported on Mariner)
**NO**
- Passed local build and package tests
- Passed buddy build and package tests: [Link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=512468&view=results)
=> Updating python-prettytable to 3.10.0

SPECS/cpprest/cpprest.signatures.json, SPECS/cpprest/cpprest.spec, cgmanifest.json
---
cpprest: Upgrade to 2.10.19
- cpprest: Upgrade to 2.10.19
**NO**
- #xxxx
- Pipeline build id: 513469
- Local Build
=> cpprest: Upgrade to 2.10.19

toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
---
fix logging in graphpkgfetcher
- fix logging in graphpkgfetcher
**NO**
- Local build
=> fix logging in graphpkgfetcher

toolkit/tools/grapher/grapher.go
---
fix logging in grapher
- fix logging in grapher
**NO**
- Local build
=> fix logging in grapher

SPECS/libnbd/libnbd.spec, SPECS/policycoreutils/policycoreutils.spec
---
Fix policycoreutils and libnbd breaks due to python 3.12 upgrade. This should unblock the selinux vhdx image build
- Fix policycoreutils
- Fix libnbd
**NO**
- Full package build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=513482&view=results
=> fix policycoreutils and libnbd packages

SPECS/initramfs/initramfs.spec
---
Symantic change, updating initramfs to 3.0 for Azure Linux 3.0
- Version bump
**YES**
NONE
NONE
- local build
=> Upgrade: initramfs from 2.0 to 3.0

SPECS/bpftrace/bpftrace.signatures.json, SPECS/bpftrace/bpftrace.spec, cgmanifest.json
---
Upgrade version 0.16.0 -> 0.19.1
- Upgrade version 0.16.0 -> 0.19.1
**NO**
- NA
- NA
- Pipeline build id: [validating]
Local Build:
=> bpftrace: upgrade version 0.16.0 -> 0.19.1

SPECS/build-essential/build-essential.spec
---
Upgarde version: 0.1 -> 3.0
- Add file, gzip, pkgconf & tar to the metapackage
**NO**
- NA
- NA
- Local Build
- Pipeine Build: [PR-7089](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=472497&view=results)
=> build-essential: upgrade 0.1 -> 3.0

SPECS/asc/asc.spec
---
Cosmetic Version bump - no real change
**NO**
- NA
- NA
- NA
=> asc: upgrade version 1.0 -> 3.0

SPECS/kubernetes/kubernetes.signatures.json, SPECS/kubernetes/kubernetes.spec, cgmanifest.json
---
upgrade k8s to 1.28.7
- Change
- Change
- Change
**NO**
- #xxxx
=> upgrade k8s to 1.28.7

SPECS/python-jsonpatch/python-jsonpatch.signatures.json, SPECS/python-jsonpatch/python-jsonpatch.spec, cgmanifest.json
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
- Pipeline build id: 514004
=> Upgrading `python-jsonpatch` from `1.32` to `1.33` for 3.0 release

CONTRIBUTING.md, README.md, SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md, SPECS/LICENSES-AND-NOTICES/data/licenses.json, SPECS/tboot/README.md, SUPPORT.md, toolkit/README.md, toolkit/docs/building/building.md, toolkit/docs/building/developer-tools.md, toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md, toolkit/docs/building/prerequisites.md, toolkit/docs/formats/imageconfig.md, toolkit/docs/how_it_works/2_local_packages.md, toolkit/docs/nvidia/nvidia.md, toolkit/docs/quick_start/quickstart.md, toolkit/docs/security/read-only-roots.md, toolkit/docs/security/security-features.md, toolkit/imageconfigs/full-aarch64.json, toolkit/imageconfigs/full.json
---
Replace all references of `CBL-Mariner` with `Azure Linux` in documentation files. Replace references to PMC and github links from old to new
- Replace all references of `CBL-Mariner` with `Azure Linux` in documentation files
- Replace references to PMC and github links from old to new
**NO**
=> Replace references to CBL-Mariner in documentation files with Azure linux as well as links

SPECS/python-zipp/python-zipp.signatures.json, SPECS/python-zipp/python-zipp.spec, cgmanifest.json
---
python-zipp: Upgrade to 3.17.0
- python-zipp: Upgrade to 3.17.0
**NO**
- #xxxx
- Pipeline build id: [515925](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=515925&view=results)
=> python-zipp: Upgrade to 3.17.0

toolkit/tools/scheduler/schedulerutils/buildlist.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/implicitprovides.go, toolkit/tools/scheduler/schedulerutils/initializegraph.go
---
fix error logging in scheduler utils
- fix error logging in scheduler utils
**NO**
- Local build
=> fix error logging in scheduler utils

SPECS/python-idna/python-idna.signatures.json, SPECS/python-idna/python-idna.spec, cgmanifest.json
---
Upgrades `python-idna` for 3.0 preview
- Upgrading `python-idna`
**NO**
- Pipeline build id: 513931
=> Upgrading `python-idna` from `3.3` to `3.6` for 3.0

SPECS/tboot/tboot.signatures.json, SPECS/tboot/tboot.spec
---
Fixes signatures for REAME.md fix and bump the release in the `tboot` package that was changed by #8128  
- Fixes signatures for `REAME.md` of `tboot` package
- bump the release in the `tboot` package
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=516223&view=results
=> Fix tboot signatures and up the release version

.pipelines/containerSourceData/scripts/BuildBaseContainers.sh, .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> updates for containers in 3.0

toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/printresults.go
---
Cherry-picking the #8121 fix from fasttrack/2.0.
- Ported fix from #8121.
No.
- #8121
- #8129
- Checked in original change.
- Local test builds.
=> Made test failures not fail the package build. (CP of #8121)

SPECS/python-retrying/python-retrying.signatures.json, SPECS/python-retrying/python-retrying.spec, SPECS/python-retrying/test_retrying.py, cgmanifest.json
---
Upgrade the package to latest 1.3.4
- Publish source tarball
- Upgrade to latest
**NO**
- Pipeline build id: [514369](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=514369&view=results)
=> python-retrying: upgrade to 1.2.4

SPECS/build-essential/build-essential.spec
---
The `installkernel` package was removed in #8029, as the `installkernel` utility is now provided by `systemd-udev`. However, the dependency wasn't fixed in the `build-essential` package.
Unfortunately, changing `build-essential` to require `systemd-udev` creates a circular dependency. However, `build-essential` was only added to `build-essential` as a convenience to the user. (See, #2632.) So, it is fine to remove it.
- Remove `installkernel` requires in `build-essential` package.
NO
=> Fix installkernel requires in build-essential package

SPECS/pciutils/pciutils.signatures.json, SPECS/pciutils/pciutils.spec, cgmanifest.json
---
- Upgrade pciutils to 3.11.1
NO
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=516388&view=results
=> Upgrade pciutils to 3.11.1

SPECS/dnf/dnf.signatures.json, SPECS/dnf/dnf.spec, SPECS/systemd/systemd.spec, cgmanifest.json
---
Upgrade dnf for Azure Linux 3.0 to latest version 4.19.0
- Upgrade to version 4.19.0
**NO**
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=514338&view=results)
- NOTE: The package test for dnf fails, this is consitent behavior for both 2.0 and 3.0-dev currently and fails for the same reason, a python function _setlocale not being supported
=> Upgrade dnf to version 4.19.0

SPECS/filesystem/filesystem.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
fixes /etc/hosts (see commit for details)
adds /etc/host.conf with 'multi on'
=> filesystem: fix /etc/hosts and add /etc/host.conf

SPECS/libmspack/libmspack.signatures.json, SPECS/libmspack/libmspack.spec, cgmanifest.json
Upgrade libmspack to version 0.11alpha from 0.10.1
buddy build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=516482&view=results
=> Upgrade libmspack to version 0.11alpha

SPECS/python-netaddr/python-netaddr.spec
---
Fix circular dependency issue - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517052&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667&l=3591
- Require pytest only when running check
**NO**
- Pipeline build id: [517169](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517169&view=results)
=> python-netaddr: fix circular dependencies

SPECS/python-wrapt/python-wrapt.spec
---
fix python-wrapt build
```
time="2024-02-29T01:19:47Z" level=debug msg="Processing files: python3-wrapt-1.15.0-1.azl3.x86_64"
time="2024-02-29T01:19:47Z" level=debug msg="error: File not found: /usr/src/mariner/BUILDROOT/python-wrapt-1.15.0-1.azl3.x86_64/usr/lib/python3.12/site-packages/wrapt-1.15.0-py?.?.egg-info"
```
- fix python-wrapt build
**NO**
- Pipeline build id https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517192&view=results
=> fix python-wrapt build

SPECS/snappy/snappy.spec
---
Fix build break in `snappy` package:
```
"/usr/include/gtest/internal/gtest-port.h:279:2: error: #error C++ versions less than C++14 are not supported."
```
- Fix snappy build
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517220&view=results
=> fix snappy build break

SPECS/python-fields/python-fields.spec, SPECS/python-filelock/python-filelock.spec
---
- Fixing build failures in python-fields and python-filelock due to incorrect `sphinx-build` command
- Change `sphinx-build3` -> `sphinx-build`
**NO**
- Local build with `RUN_CHECK=y` passed
=> Use correct sphinx-build name for python-fields and python-filelock

SPECS/rubygem-td/fix-file_list.patch
---
Fix the patch file in rubygem-td so it applies
```
time="2024-02-29T00:24:52Z" level=debug msg="+ /usr/lib/rpm/rpmuncompress /usr/src/mariner/SOURCES/fix-file_list.patch"
time="2024-02-29T00:24:52Z" level=debug msg="+ /bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f"
time="2024-02-29T00:24:52Z" level=debug msg="1 out of 1 hunk FAILED -- saving rejects to file td.gemspec.rej"
```
Note: since the package hasn't built/released yet, I'm not bumping the release number.
- Change rubygem-td patch
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517228&view=results
=> fix rubygem-td patch

SPECS/pam_wrapper/pam_wrapper.spec
---
Fix pam_wrapper build due to error:
```
time="2024-02-29T21:26:03Z" level=debug msg="Processing files: python3-libpamtest-1.1.5-1.azl3.x86_64"
time="2024-02-29T21:26:03Z" level=debug msg="error: File not found: /usr/src/mariner/BUILDROOT/pam_wrapper-1.1.5-1.azl3.x86_64/usr/lib/python3.12/site-packages/pypamtest.so"
```
Note: pypamtest.so appears to not build due to an upstream issue. This could be related to the following: https://bugzilla.samba.org/show_bug.cgi?id=15484
Since we currently have no solution to get this building, I've temporarily removed the subpackage to allow our 3.0-dev builds to complete.
- Fix pam_wrapper build …
=> fix pam_wrapper build

SPECS/protobuf/protobuf.signatures.json, SPECS/protobuf/protobuf.spec, cgmanifest.json
---
Upgrade protobuf to 25.3 for mariner 3.0
- Upgrade to 25.3
- Added BR on abseil-cpp
- Using cmake build system                                                                                                                              
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=516763&view=results
=> Upgrade protobuf to 25.3

SPECS/kata-containers-cc/kata-containers-cc.spec, SPECS/kernel-uvm/config, SPECS/kernel-uvm/kernel-uvm.signatures.json, SPECS/kernel-uvm/kernel-uvm.spec, cgmanifest.json
---
Upgrade kernel-uvm and kata-conatainers-cc for LSG release v2402.26.1
- upgrade kernel-uvm and kata-conatainers-cc for LSG release v2402.26.1
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=517049&view=results
=> Kata-CC: upgrade kernel-uvm and kata-conatainers-cc for LSG release v2402.26.1

toolkit/tools/internal/rpm/rpm.go, toolkit/tools/internal/rpm/rpm_test.go
---
fix error logging in rpmtool
- fix error logging in rpmtool
**NO**
- Local build
=> fix logging in rpmtool

SPECS/kernel/CVE-2024-0775.nopatch
---
Nopatch CVE-2024-0775
- Nopatch CVE-2024-0775
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-0775
=> Nopatch CVE-2024-0775

SPECS/python-toml/python-toml.spec
---
Adding a re-branding change I missed while working on #8034.
- Updated BR for `python-toml.spec`.
No.
- #8034
- Local build.
=> Added a missed re-name in `python-toml.spec`.

toolkit/tools/imagegen/diskutils/diskutils.go, toolkit/tools/imagegen/diskutils/encryption.go
---
fix error logging in imagegen/diskutils utilities
- fix error logging in imagegen/diskutils utilities
**NO**
- Local build
=> fix logging in diskutils

SPECS/python-attrs/0001-add-version-limits.patch, SPECS/python-attrs/python-attrs.spec
---
Fix package test failures by limiting the version of pytest-mypy-plugins
- Add patch to limit version of pytest-mypy-plugins for package tests
**NO**
- Local Build
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=520320&view=results)
=> Add patch to limit pytest-mypy-plugins version for python-attrs test

SPECS/clamav/CVE-2024-20328.patch, SPECS/clamav/clamav.spec
---
Patch CVE-2024-20328
- CVE-2024-20328
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-20328
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=519920&view=results
=> clamav: Patch CVE-2024-20328

SPECS/xorg-x11-server/CVE-2024-21885.patch, SPECS/xorg-x11-server/xorg-x11-server.spec
---
Patch CVE-2024-21885. Backport from master https://gitlab.freedesktop.org/xorg/xserver/-/commit/4a5e9b1895627d40d26045bd0b7ef3dce503cbd1
- CVE-2024-21885
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-21885
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=520005&view=results
=> xorg-x11-server: patch CVE-2024-21885

SPECS/kubernetes/kubernetes.signatures.json, SPECS/kubernetes/kubernetes.spec, cgmanifest.json
---
Upgrade kubernetes to 1.29.1
- Change
- Change
- Change
**NO**
- #xxxx
=> Upgrade kubernetes to 1.29.1

SPECS/python-certifi/certifi-2022.12.07-use-system-cert.patch, SPECS/python-certifi/python-certifi.signatures.json, SPECS/python-certifi/python-certifi.spec, cgmanifest.json
---
upgrade python-certifi to 2024.02.02
- upgrade python-certifi to 2024.02.02
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=521410&view=results
=> upgrade python-certifi to 2024.02.02

SPECS/protobuf-c/protobuf-c.spec
Add missing dependency protobuf-c static subpackage.
---
To solve protobuf package upgrade failure issue.
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=521400&view=results
=> Add missing dependency protobuf-c static subpackage.

toolkit/tools/internal/safechroot/safechroot.go, toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go
---
fix error logging in chroot tools
- fix error logging in chroot tools
**NO**
- Local build
=> fix logging in chroot tools

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/pkggraph/pkggraph.go
---
fix error logging in tools/internal utilities
- fix error logging in tools/internal utilities
**NO**
- Local build
=> fix logging in tools/internal

toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go, toolkit/tools/imagegen/configuration/configuration.go, toolkit/tools/imagegen/configuration/configuration_test.go, toolkit/tools/imagegen/configuration/networkconfig.go, toolkit/tools/imagegen/configuration/networkconfig_test.go, toolkit/tools/imagegen/configuration/packagerepo.go, toolkit/tools/imagegen/configuration/packagerepo_test.go, toolkit/tools/imagegen/configuration/parse_partition.go, toolkit/tools/imagegen/configuration/systemconfig.go, toolkit/tools/imagegen/configuration/systemconfig_test.go
---
fix error logging in imagegen/configuration utilities
- fix error logging in imagegen/configuration utilities
**NO**
- Local build
=> fix logging in imagegen-config files

SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
---
Fixed incorrect macro usage
Fixed incorrect macro usage
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=521898&view=results
=> Fix bug in sphyinx webcontrib

SPECS/azurelinux-repos/azurelinux-repos.spec, SPECS/azurelinux-rpm-macros/azurelinux-rpm-macros.spec, SPECS/ca-certificates/ca-certificates.spec, SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec, SPECS/prebuilt-ca-certificates/prebuilt-ca-certificates.spec
…nd ca-certificates for toolchain builds
---
The toolchain will not bootstrap with the %{azl} macros added by https://github.com/microsoft/azurelinux/pull/8232. This PR allows the toolchain to build until a better solution is devised by returning the versions to hardcoded values
- Change %{azl} tags in version to '3' instead for azurelinux-repos azurelinux-rpm-macros and ca-certificates
**YES**
=> Return hardcoded versions to azurelinux-repos azurelinux-rpm-macros and ca-certificates

SPECS/protobuf-c/protobuf-c.spec
---
Remove protobuf-c static sub-package. Firstly, there is no other packages which depend on protobuf-c-static. The primary motivation is to streamline CVE management and reduce security risks. Static libraries make it challenging to address CVEs effectively, as each statically linked binary needs to be individually updated and re-distributed. By eliminating these static subpackages, we aim to simplify vulnerability management and ensure that dependencies are dynamically linked, allowing for easier updates and better security practices.
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=521925&v …
=> Remove protobuf-c static sub-package.

toolkit/tools/imagecustomizerapi/service.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/testdata/services-config.yaml
---
Allow the user to specify the name of a service to enable/disable as just a string, instead of an object with a `Name` field. This ensures the API matches what is in the documentation.
Note: This doesn't exclude us from having a more complex API for services in the future, as we can write a custom unmarshaller that can handle both strings and objects. (Like what was done for `FileConfig`.)
- Image Customizer: Simplify services API.
NO
- Manually ran Image Customizer tool.
=> Image Customizer: Simplify services API.

SPECS/python-pywbem/python-pywbem.spec
---
Fix requirements for package
**NO**
=> python-pywbem: fix requirements

SPECS/cloud-utils-growpart/cloud-utils-growpart.signatures.json, SPECS/cloud-utils-growpart/cloud-utils-growpart.spec, cgmanifest.json
---
Upgrade upgrade cloud-utils-growpart package to 0.33
- Upgrade upgrade cloud-utils-growpart package to 0.33
- Skip adding %check section as the tests provided by cloud-utils contains commands (mkfs.ext4) not provided in our build
NO
- Local pakcage build 
- Buddy build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522869&view=results
=> upgrade cloud-utils-growpart to 0.33

SPECS/wpa_supplicant/CVE-2023-52160.patch, SPECS/wpa_supplicant/wpa_supplicant.spec
---
Patch CVE-2023-52160 for wpa_supplicant
- Add CVE-2023-52160.patch for wpa_supplicant
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-52160
- Pipeline build id: [522598](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=522598&view=results)
=> Patch CVE-2023-52160 for wpa_supplicant

SPECS/bazel/bazel.signatures.json, SPECS/bazel/bazel.spec, cgmanifest.json
---
We need to downgrade bazel from 7.0.2 to 6.5.0 as TensorFlow requires 6.x.x version to build. 
- Change: Change bazel spec
**YES/NO**
NO
- Pipeline build id: [523457](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523457&view=results)
=> Downgrade bazel to 6.5.0 for tensorflow 2.15.0

SPECS/expat/CVE-2023-52426.patch, SPECS/expat/expat.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch CVE-2023-52426
- CVE-2023-52426
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523455&view=results [pass]
- Built locally
=> expat: patch CVE-2023-52426

SPECS/containerd/containerd.service, SPECS/containerd/containerd.signatures.json, SPECS/containerd/containerd.spec, SPECS/moby-containerd-cc/containerd.service, SPECS/moby-containerd-cc/moby-containerd-cc.signatures.json, SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
Add `OOMScoreAdjust=-999` to containerd service files for parity with changes that went into 2.0 after the fork.
* PR https://github.com/microsoft/azurelinux/pull/6819
* PR https://github.com/microsoft/azurelinux/pull/7121
- Add OOMScoreAdjust=-999 to containerd service files 
**NO**
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523555&view=results
=> containerd: add OOMScoreAdjust to containerd service

SPECS/policycoreutils/policycoreutils.spec
---
Reverting a change in `policycoreutils`. It's one fix we missed while working on #8226.
- Re-added the Python cache directory in `policycoreutils`.
No.
- #8226
- Local build.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523553&view=results).
=> Fixed `policycoreutils` after macros update.

SPECS/python-gevent/python-gevent.spec
---
Fix CVE-2021-22931. Additional context in https://github.com/microsoft/azurelinux/pull/8269
- CVE-2021-22931
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-22931
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=523598&view=results [pass]
=> python-gevent: disable c-ares module and fix CVE-2021-22931

SPECS/qemu/qemu.spec
---
Fix qemu spec for ARM builds
Fix an unclosed quote
Minor cleanup
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=524755&view=results
=> Fix qemu spec to build for ARM

SPECS/gnutls/CVE-2024-0567.patch, SPECS/gnutls/gnutls.spec
---
Fix CVE-2024-0567 with backported patch from Ubuntu
- added CVE-2024-0567.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-0567
- Pipeline build id: [525225](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=525225&view=results)
=> Add patch for CVE-2024-0567

toolkit/tools/imagegen/attendedinstaller/views/installerview/installerview.go
---
Hide the gui installer temporarily while waiting to stabilize calamares
- hide Graphical installer option in during iso installation
**NO**
- Local Iso build
-
=> hide Graphical Installer option

toolkit/tools/imagecustomizer/README.md
Adds `zstd` to the list of prerequisites.
Also, fixes the prerequisites list so that the list of tools is clearly differentiated from the list of packages.
NO
=> Image Customizer: Fix prereqs in README.

SPECS/bazel/0001-JDK17.patch, SPECS/bazel/bazel.spec
---
fix upstream issue of bazel not working with jdk-17 
- Change: fix upstream issue of bazel not working with jdk-17 
**YES/NO**
NO
- Pipeline build id: [526645](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526645&view=results)
=> Fix Bazel issue caused by msopenjdk-17 update

SPECS/dracut/dracut.signatures.json
---
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526719&view=results
=> Fix `dracut` signature mismatch issue.

.pipelines/prchecks/PackageBuildPRCheck.yml
---
Checking a suggested fix for the ADO pipeline PR check ran for all fast-track PRs. This is to resolve the following errors we've been seeing for a while:
```
##[error]A container resource with name linux_onebranch_container could not be found. The container resource does not exist. If you intended to specify an image, use NAME:TAG or NAME@DIGEST. For example, ubuntu:latest
```
- 
No.
- PR check for this PR.
=> Removed the `runOnHost` flag to fix the fast-track PR check pipelines.

SPECS/boost/boost.spec
Add filesystem, random, system, program-options packages to boost
Buddy build :
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526802&view=results
=> Add filesystem, random, system, program-options packages  to boost

SPECS/gperftools/gperftools.spec
updating build step and adding libs package 
Buddy Build: 
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526843&view=results
=> update build step and add libs pkg to gperftools

SPECS/xorg-x11-server/CVE-2023-6816.patch, SPECS/xorg-x11-server/xorg-x11-server.spec
---
- Adds patches to address CVE-2023-6816
- CVE-2023-6816
- Mailing list: https://www.openwall.com/lists/oss-security/2024/01/18/1
- Patch: https://gitlab.freedesktop.org/xorg/xserver/-/commit/9e2ecb2af8302dedc49cb6a63ebe063c58a9e7e3
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-6816
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526880&view=results
=> Add patch in xorg-x11-server to address CVE-2023-6816

SPECS/azure-iot-sdk-c/CVE-2024-25110.patch, SPECS/azure-iot-sdk-c/CVE-2024-27099.patch, SPECS/azure-iot-sdk-c/azure-iot-sdk-c.spec
---
- Adds patches to address CVE-2024-25110 and CVE-2024-27099
- For CVE-2024-25110
- GitHub Advisory: https://github.com/Azure/azure-uamqp-c/security/advisories/GHSA-c646-4whf-r67v
- Upstream Patch: https://github.com/Azure/azure-uamqp-c/commit/30865c9ccedaa32ddb036e87a8ebb52c3f18f695
- For CVE-2024-27099
- GitHub Advisory: https://github.com/Azure/azure-uamqp-c/security/advisories/GHSA-6rh4-fj44-v4jj
- Upstream Patch: https://github.com/Azure/azure-uamqp-c/commit/2ca42b6e4e098af2d17e487814a91d05f6ae4987
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-25110
- https://nvd.nist.gov/vuln/detail/CVE-2024-27099
- Buddy Build: …
=> Add patches in azure-iot-sdk-c to address CVE-2024-25110 and CVE-2024-27099

SPECS/core-packages/core-packages.spec
---
Switching default PMC repos for the time of the 3.0 preview. We will revert this change for GA.
- Switched to `azurelinux-repos-preview` and `azurelinux-repos-ms-non-oss-preview` in the `core-packages-container` subpackage.
No.
- Buddy build.
=> Switched `core-packages` to use the preview repo.

SPECS/telegraf/CVE-2024-28110.patch, SPECS/telegraf/telegraf.spec
---
Address CVE-2024-28110 by patching vendored github.com/cloudevents
- add CVE-2024-28110.patch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-28110
- local build
=> Add patch for CVE-2024-28110

SPECS/kubevirt/CVE-2022-41723.patch, SPECS/kubevirt/kubevirt.spec
---
CVE fix
- Adds patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-41723
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526599&view=results
=> kubevirt: Add patch for CVE-2022-41723

SPECS/grpc/grpc.signatures.json, SPECS/grpc/grpc.spec, SPECS/grpc/grpcio-cython3.patch, cgmanifest.json
---
mariner 3.0 grpc upgrade
- Change
- Change
- Change
**NO**
- #xxxx
=> mariner 3.0 grpc upgrade

SPECS/libnbd/libnbd.spec
---
Fix package build break with `libnbd`
- libndb: revert change that removed pycache files. This was missed when reverting other pycache changes in #8226 
**NO**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=528400&view=results
=> libnbd: fix python build break

toolkit/tools/imagecustomizer/docs/cli.md, toolkit/tools/imagecustomizer/docs/partitionmetadatajson.md, toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
---
Writes partition metadata json file. This helps customers examine details of their image partitions easily.
- Added functionality to write partition metadata json
- Customized the output to include info that is interesting and relevant to the customer
- Updated docs
**NO**
- Tested locally.
INFO[0061][main] Partition metadata file created: out/image5_partition_metadata.json 
INFO[0061][main] Success!
=> Image Customizer: write partition metadata json

.github/CODEOWNERS
Switch the ownership of image customizer directories to a dedicated team.
=> Image Customizer: Update CODEOWNERS

toolkit/tools/imagecustomizer/docs/configuration.md
Fix partition customizer example to include `ResetBootLoaderType` field.
---
NO
=> Image Customizer: Minor docs fix

SPECS/less/CVE-2022-48624.patch, SPECS/less/less.spec
---
Patch CVE-2022-48624
- Create patch for CVE
- Update changelog
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-48624
- Pipeline build id: [528415](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=528415&view=results)
=> less: patch CVE-2022-48624

SPECS/glib/glib.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This change unblocks the build of `glib-networking` along with:
- `libsoup` (builds),
- `ostree` (builds),
- `rpm-ostree` (fails).
- Made `glib` provide `gio-querymodules` under the standard path.
Yes.
- Local build.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=528737&view=results)
=> Providing `gio-querymodules` from `glib`.

toolkit/tools/imagecustomizer/README.md, toolkit/tools/imagecustomizer/docs/configuration.md, toolkit/tools/imagecustomizer/docs/iso.md, toolkit/tools/imagecustomizerapi/config.go, toolkit/tools/imagecustomizerapi/config_test.go, toolkit/tools/imagecustomizerapi/os.go, toolkit/tools/imagecustomizerapi/os_test.go, toolkit/tools/pkg/imagecustomizerlib/customizepackages.go, toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go, toolkit/tools/pkg/imagecustomizerlib/testdata/addfiles-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/commandline-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/consume-space.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/modules-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/nochange-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-disabled.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-force-enforcing.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-permissive.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/services-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/updatepackages-config.yaml, toolkit/tools/pkg/osmodifierlib/modifierutils.go, toolkit/tools/pkg/osmodifierlib/osmodifier.go
=> Image Customizer: Rename 'systemConfig' to 'os'

SPECS/azurelinux-release/15-azurelinux-default.conf, SPECS/azurelinux-release/azurelinux-release.spec, toolkit/tools/internal/resources/assets/grub2/grub
Instead of placing this sysctl setting on the cmdline, put it into a normal sysctl config file
=> move boot parameter from grub cmdline into sysctl file

SPECS/kata-containers-cc/kata-containers-cc.spec
---
Emulate kata-containers and switch to the new Rust virtiofsd. This was missed earlier. No runtime impact in prod because this is only used for debugging.
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=526879&view=results
=> kata-containers-cc: fix virtiofsd dependency

.pipelines/templates/PackageBuild.yml, toolkit/scripts/pkggen.mk
---
Cherry-pick of #7425 from 2.0.
- Cherry-picked #7425.
No.
- #7425.
- Tested in 2.0's fast-track builds.
=> Adding support for multiple cache inputs (CP: #7425)

SPECS/docker-compose/docker-compose.spec
---
docker-compose license should be listed as ASL 2.0 instead of MIT
- Change docker-compose license from MIT to the corrected ASL 2.0
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=531766&view=results
=> docker-compose: fix license to ASL 2.0

SPECS/moby-compose/moby-compose.spec
---
moby-compose license should be listed as ASL 2.0 instead of MIT
- Change moby-compose license from MIT to the corrected ASL 2.0
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=531786&view=results
=> moby-compose: fix license to ASL 2.0

SPECS/azurelinux-release/azurelinux-release.signatures.json
This is to fix a build break.
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Fix Build Break: Missing sha256 sum for new file

toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md
---
#8243 added zstd support, but a bare bones OS may not have the required package. Since we run unit tests on these functions we want that tool generally available.
- Add zstd to prereq lists.
**NO**
=> Add zstd to the prereqs

toolkit/imageconfigs/full-aarch64.json
---
On https://github.com/microsoft/azurelinux/pull/8459 I had missed adding these configurations to the aarch64 full.json. This PR corrects that issue
- add 10-console-messages.conf and 99-dhcp-en.network to aarch64 full.json
**NO**
- Local Build - see previous PR
=> add network and kernel print config files to full-aarch.json

SPECS/usbip/extract_usbip.sh, SPECS/usbip/usbip.signatures.json, SPECS/usbip/usbip.spec, cgmanifest.json, toolkit/scripts/check_entangled_specs.py
---
Update `usbip` to `6.6.14.1` to match the kernel.
~Also add it to the entangled specs list. `usbip` is built with kernel sources, so it should match the current kernel version.~
- ~Add `usbip` to `check_entangled_specs.py` with the kernel.~
- Upgrade `usbip` to `6.6.14.1`
- Fix supporting script for generating source tar
**NO**
- Local build
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=531922&view=results
- Testing path is  unclear
=> Update usbip to 6.6.14.1

SPECS/libvirt/CVE-2024-1441.patch, SPECS/libvirt/libvirt.spec
---
Address CVE-2024-1441
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-1441
- Pipeline build id: [PR-8447](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=530654&view=results)
=> libvirt: address CVE-2024-1441

toolkit/tools/imagecustomizer/README.md, toolkit/tools/pkg/imagecustomizerlib/checkfilesystem.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
After customization is complete, check for any file system errors and fail if any are found.
---
NO
=> Image Customizer: Check for file system errors.

toolkit/tools/liveinstaller/liveinstaller.go
---
The `eject` call is erroring out likely due to the cdrom currently being mounted by the ISO. Adding a --force to the call allows it to go through in all environments.
- Add --force to eject call
**NO**
- Local ISO Build
=> Fix Disk Not Ejecting Post Install on Gen-1 Hyper-v VM

toolkit/tools/imagecustomizer/docs/configuration.md
This PR handles NBD dependency requirements, along with OverlayFS guidance doc.
Internal tracking tasks:
- https://dev.azure.com/mariner-org/ECF/_sprints/taskboard/Mariner%20Operator%20Edge/ECF/2403?workitem=7016
- https://dev.azure.com/mariner-org/ECF/_sprints/taskboard/Mariner%20Operator%20Edge/ECF/2403?workitem=7204
=> Supplement the documentation content of Verity and Overlay.

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
---
Upgrade erlang to the latest version for azurelinux 3.0
- Upgrade erlang to version 26.2.3
**NO**
- Local Build
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=532747&view=results)
=> upgrade erlang to version 26.2.3

SPECS/vim/vim.spec
---
Double escape has to be the most annoying thing in the world, removing it. As well as remove the warning bell, adding auto indent as well as shortcut for :W for sudo write
- Set ai on
- Allow :W for sudo write
- disable warning bell
**NO**
- #xxxx
=> Fix vimrc bindings

SPECS/kernel/CVE-2023-52434.nopatch, SPECS/kernel/CVE-2023-52435.nopatch
---
Address kernel CVEs 2023-52434, 2023-52435
- Nopatch kernel CVEs 2023-52434, 2023-52435
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-52434
- https://nvd.nist.gov/vuln/detail/CVE-2023-52435
=> Address kernel CVEs 2023-52434, 2023-52435

toolkit/README.md, toolkit/docs/building/add-package.md
---
Add documentation on how to add new package to CBL Mariner.
- Add documentation
**NO**
=> docs: Add documentation on how to add a new package.

toolkit/tools/pkg/isomakerlib/isomaker.go
Currently, the `IsoMaker` class uses the `mount` and `umount` commands to build the `efiboot.img` file. However, there have been reports of `IsoMaker` hitting device busy errors during unmount. So, this change converts the code over to use `safeloopback` and `safemount`, which can handle these types of issues.
---
NO
- Manually built Azure Linux installer ISO.
=> IsoMaker: Fix unmount

toolkit/tools/pkg/imagecustomizerlib/checkfilesystem.go, toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/testdata/files/sshd-keygen.service, toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/ssh-move-host-keys.sh, toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
Firstly, move the shared file system integrity checks to be after file system shrinking and verity setup.
Secondly, add a second set of integrity checks to the extracted partitions.
Thirdly, add a test config for verity.
---
NO
=> Image Customizer: Improve file system checks.

SPECS/kubernetes/kubernetes.spec
---
k8s - Fix build break due to golang version upgrade
- Change
- Change
- Change
**NO**
- #xxxx
=> k8s - Fix build break due to golang version upgrade

toolkit/scripts/build_tag.mk
NO
- Manually built image customizer tool.
=> Image Customizer: Bump version to v0.2.0

SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec, SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec, SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/hyperv-daemons/hyperv-daemons.signatures.json, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-azure/config, SPECS/kernel-azure/config_aarch64, SPECS/kernel-azure/kernel-azure.signatures.json, SPECS/kernel-azure/kernel-azure.spec, SPECS/kernel-hci/config, SPECS/kernel-hci/kernel-hci.signatures.json, SPECS/kernel-hci/kernel-hci.spec, SPECS/kernel-headers/kernel-headers.signatures.json, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel/config, SPECS/kernel/config_aarch64, SPECS/kernel/kernel.signatures.json, SPECS/kernel/kernel.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade to 5.15.151.2
This contains an LSG backported [patch ](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/27b7b5779b95fe7be1dd71e3b193bfcf6c3f16b1)for hv_netvsc. Note that all versions afterward (>=5.15.152.1) contain this [patch ](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/b6d46f306b3964d05055ddaa96b58cd8bd3a472c)within the stable source
- Upgrade kernel to 5.15.151.2
**YES**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=536216&view=results (ARM fails due to pipeline error for kernel-hci not being able to pack because it only builds for amd)
- ARM build proof for kernel and kernel-headers only: …
=> Upgrade kernel to 5.15.151.2

SPECS/unixODBC/CVE-2024-1013.patch, SPECS/unixODBC/unixODBC.spec
---
Address CVE-2024-1013 by applying upstream patch
- CVE-2024-1013
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-1013
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=535631&view=results
=> unixODBC: Address HIGH CVE-2024-1013

SPECS/OpenIPMI/OpenIPMI.spec
---
OpenIPMI 2.0.32 can build in 3.0 with the fix
- OpenIPMI
**NO**
- None
- Pipeline build id: [537432](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537432&view=results)
=> Fix build issues with OpenIPMI 2.0.32 in 3.0

SPECS/google-guice/google-guice.signatures.json, SPECS/google-guice/google-guice.spec, cgmanifest.json
---
Update google-guice to 5.1.0 for azl 3.0
- Change: Update google-guice to 5.1.0 for azl 3.0
**YES/NO**
NO
- Pipeline build id: [537593](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537593&view=results)
=> Update google-guice to 5.1.0

SPECS/nfs-utils/nfs-utils.spec
---
Cherry-pick https://github.com/microsoft/azurelinux/pull/6652
- Fix missing nobody user/group for nfs squash
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/47370661?src=WorkItemMention&src-action=artifact_link
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=525976&view=results
=> Fix missing nobody user/group for nfs squash

SPECS/dhcp/dhcp.spec
---
Revert of #8517. The change has caused partner tests to start failing - we need to investigate before bringing this change back in.
Broken tests:
- [First one on 03/16 after a change in the `main` branch](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=528978&view=ms.vss-test-web.build-test-results-tab&runId=174754&resultId=100038&paneView=debug).
- [Fast-track test failure](https://penguinatorstarter.powerappsportals.com/SignIn?ReturnUrl=%2Fmytests%2Fmyjobs%2Fresults%2F%3Fid%3Df7e1c8e7-c5eb-ee11-a1ff-7c1e521a3378).
No.
- #8517
- https://nvd.nist.gov/vuln/detail/
- PR check.
=> Revert "[2.0] dhcp/dhclient.conf: add option rfc3442-classless-static…" (#8517)

SPECS/perl-HTTP-Cookies/perl-HTTP-Cookies.signatures.json, SPECS/perl-HTTP-Cookies/perl-HTTP-Cookies.spec, SPECS/perl-HTTP-Daemon/HTTP-Daemon-6.04-EU-MM-is-not-deprecated.patch, SPECS/perl-HTTP-Daemon/perl-HTTP-Daemon.signatures.json, SPECS/perl-HTTP-Daemon/perl-HTTP-Daemon.spec
---
Upgrade both perl-HTTP-Cookies and perl-HTTP-Daemon to the latest version for Azure Linux 3.0
NOTE: the cgmanifest has already been updated (albiet a bit preemptively) by this PR: https://github.com/microsoft/azurelinux/pull/7136/files#diff-45a0a38d395bf4427d0291d9c72bd99b57fa43e14b00e059ae170d657949f1f2
- Upgrade perl-HTTP-Cookies to version 6.11
- Upgrade perl-HTTP-Daemon to version 6.16
**NO**
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537534&view=results)
=> Upgrade perl-HTTP-Cookies and perl-HTTP-Daemon to the Latest Version

toolkit/tools/imagecustomizer/docs/configuration.md, toolkit/tools/imagecustomizer/docs/iso.md
---
Minor doc fixes for MIC ISO generation.
- [MIC ISO: minor doc fixes](https://github.com/microsoft/azurelinux/commit/00d25f0aed6eeb9a61b96545ebcdc62c23a0f0d6)
**NO**
- [1711 Image Customizer: ISO gen has out-dated docs](https://dev.azure.com/mariner-org/ECF/_workitems/edit/7311)
- n/a
- n/a
=> MIC ISO: minor doc updates.

SPECS/OpenIPMI/OpenIPMI.signatures.json, SPECS/OpenIPMI/OpenIPMI.spec, cgmanifest.json
---
Upgrade OpenIPMI to targetd version 2.0.33 for 3.0-dev
- Upgrade OpenIPMI from 2.0.32 to 2.0.33
**NO**
- None
- Pipeline build id: [538569](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=538569&view=results)
=> upgrade OpenIPMI to 2.0.33 for 3.0-dev

SPECS/btrfs-progs/btrfs-progs.signatures.json, SPECS/btrfs-progs/btrfs-progs.spec, cgmanifest.json
---
btrfs-progs: upgrade to 6.8
- Upgrade btrfs-progs to 6.8
**NO**
- Containerized build
- Buddy build id: [538765](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=538765&view=results)
=> btrfs-progs: upgrade to 6.8

SPECS/llvm/llvm.spec
---
Update `llvm` to build the LLVM gold plugin `LLVMgold.so` to support link time optimization.
- Change llvm to build `LLVMgold.so`
**NO**
- #6999
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=537654&view=results
- Local build. Install new llvm.rpm on Azure Linux 3.0 VM and run the repro steps from the github issue.
=> llvm: update to build with llvmgold.so

SPECS/policycoreutils/policycoreutils.signatures.json, SPECS/policycoreutils/policycoreutils.spec, SPECS/policycoreutils/selinux-autorelabel, SPECS/policycoreutils/selinux-autorelabel-generator.sh, SPECS/policycoreutils/selinux-autorelabel-mark.service, SPECS/policycoreutils/selinux-autorelabel.service, SPECS/policycoreutils/selinux-autorelabel.target, cgmanifest.json
---
Mariner 3.0 package upgrades for policycoreutils
- Change policycoreutils spec to the latest upstream version
**NO**
- Pipeline buddy build id: [539194](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=539194&view=results)
=> Upgrade policycoreutils to 3.6

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-kernel-config.yml, .github/workflows/check-signatures.yml, .github/workflows/check-source-signatures.yml, .github/workflows/check-spec.yml, .github/workflows/check-static-glibc.yml, toolkit/scripts/os-required-configs.json
---
Remove references to `CBL-Mariner` in the .github folder and replace them with `Azure Linux`. Some references cannot be changed yet, including team group names, bot name
- Remove references to CBL-Mariner in .github folder
**NO**
- [Task 48676445](https://microsoft.visualstudio.com/OS/_workitems/edit/48676445): references to mariner in .github folder
- Confirmed all of the workflow checks for this PR are still passing
- `grep -rnwi mariner ../.github/ | grep -v CODEOWNERS`
=> Remove references to CBL-Mariner in .github folder

SPECS/open-vm-tools/CVE-2023-34058.patch, SPECS/open-vm-tools/CVE-2023-34059.patch, SPECS/open-vm-tools/open-vm-tools.spec
---
Address CVE-2023-34058 & CVE-2023-34059 with two patches
- CVE-2023-34058 
- CVE-2023-34059 
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-34058
- https://nvd.nist.gov/vuln/detail/CVE-2023-34059
- Pipeline buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=539284&view=results
=> open-vm-tools: patch to address CVE-2023-34058 & CVE-2023-34059 

SPECS/mariner-release/mariner-release.spec
Bump Mariner Release for April 2024 update
=> Bump Mariner Release for April 2024 update

SPECS/iptables/iptables, SPECS/iptables/iptables.signatures.json, SPECS/iptables/iptables.spec, SPECS/iptables/iptables.stop
---
Stopping the iptables services does not remove all rules from the system. Ensure that the raw table is flushed as well
- Flush and reset raw table on iptables stop
**NO**
- #xxxx
=> iptables, flush and restore raw table

SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
Currently the moby-containerd-cc package is being preferentially installed when running `dnf install containerd`. This is because its marked as obsoleting containerd which is a hold-over from the naming in 2.0. This change removes that `Obsoletes: containerd` since it's no longer necessary.
- Remove `Obsoletes: containerd` from moby-containerd-cc
**NO**
- Bug 49769800
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=541145&view=results
=> moby-containerd-cc: remove obsoletes containerd

SPECS/cmake/cmake.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
cmake: fix package test
- Change fix cmake ptest
**YES**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=541180&view=results
=> cmake: fix package test

SPECS/softhsm/softhsm-openssl3-tests.patch, SPECS/softhsm/softhsm.spec
---
softhsm: fix tests
- Change softhsm: fix tests
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=540750&view=results
=> softhsm: fix tests

SPECS/perl-HTML-Parser/perl-HTML-Parser.signatures.json, SPECS/perl-HTML-Parser/perl-HTML-Parser.spec, cgmanifest.json
---
Upgrade perl-HTML-Parser to the latest version as a part of Azure Linux 3.0 upgrade.
- Upgrade perl-HTML-Parser to version 3.82
**NO**
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=536704&view=results)
=> Upgrade perl-HTML-Parser to version 3.82 for 3.0-dev

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Our delta toolchain builds were skipping a rebuild of a spec, which needed to build more than once in the toolchain phase (for example `pam` or `selinux`). Building more than once is required, if we couldn't provide the package with all of its required build-time dependencies, because these dependencies required that package to build them. Later builds are expected to run with more/all build-time dependencies where the final build should have all of them.
During the delta toolchain build, we would build the spec for the first time but later attempts would be skipped, because we'd check for the presence of the RPM files produced by the built spec. Since they were all present from …
=> Fixing toolchain rebuilds for delta builds.

SPECS/emacs/emacs.spec
---
- Fix the date in logs
**NO**
- Pipeline build id: [543213](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543213&view=results)
=> Fix the date in logs

SPECS/rust/rust.spec
---
Enable the profiler runtime. It is required when compiling with options that
depend on this runtime, such as `-C profile-generate` or `-C instrument-coverage`
- Enable profiler support
**NO**
- Fixes: #8655
- NA
- LocalBuild
- Pipeline build id: [PR-8656](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=541552&view=results)
=> rust: enable profiler support

SPECS/python-tqdm/python-tqdm.signatures.json, SPECS/python-tqdm/python-tqdm.spec, cgmanifest.json
---
- Upgrade python-tqdm to the latest v4.66.2 and enable package test to run
- Upgrade version to v4.66.2
- Modify Source0
- Add python3-pip, python3-packaging and python3-setuptools_scm as BR
- Add python3-pytest and python3-tensorflow as BR for package test
- Refine build, install and test implementation to enable build and package test
- Add additional files to %files section
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=536655&view=results
=> [3.0] Upgrade python-tqdm to v4.66.2

SPECS/clang/clang.signatures.json, SPECS/clang/clang.spec, SPECS/compiler-rt/compiler-rt.signatures.json, SPECS/compiler-rt/compiler-rt.spec, SPECS/lld/lld.signatures.json, SPECS/lld/lld.spec, SPECS/lldb/lldb.signatures.json, SPECS/lldb/lldb.spec, SPECS/llvm/llvm.signatures.json, SPECS/llvm/llvm.spec, cgmanifest.json
---
Upgrade LLVM, and all other entangled specs, to version 18.1.2 This version contains fixes for a thread sanitizer issue.
- Change `llvm` to 18.1.2
- Change `clang` to 18.1.2
- Change `lld` to 18.1.2
- Change `lldb` to 18.1.2
- Change `compiler-rt` to 18.1.2
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/47682610
- https://microsoft.visualstudio.com/OS/_workitems/edit/48802814
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543766&view=results
=> llvm: upgrade to 18.1.2

SPECS/python-nose2/pyproject-use-flit-core.patch, SPECS/python-nose2/python-nose2.signatures.json, SPECS/python-nose2/python-nose2.spec, cgmanifest.json
---
Upgrade python-nose2 for AzL 3.0.
**NO**
- Local build OK
- Buddy build OK: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=544664&view=results
=> Upgrade python-nose2 for AzL 3.0

SPECS/erlang/OTP-24-Code.patch, SPECS/erlang/erlang.spec, SPECS/rabbitmq-server/executeRabbitMQTests.sh, SPECS/rabbitmq-server/generate-rabbitmq-server-tarball.sh, SPECS/rabbitmq-server/rabbitmq-server.signatures.json, SPECS/rabbitmq-server/rabbitmq-server.spec, cgmanifest.json
---
Upgrade rabbitmq-server to the latest version, additionally the vendor tarballs are no longer needed for build, but I have left the script included in the repo JIC it becomes required in the future.
- Upgrade rabbitmq-server to version 3.13.0
- Add patch for erlang bug on aarch64 causing large heap size allocations
**NO**
- Local Build
- Local test script - Run in progress
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=542247&view=results)
=> Upgrade rabbitmq to Version 3.13.0

SPECS/pytorch/pytorch.signatures.json, SPECS/pytorch/pytorch.spec, cgmanifest.json
---
Update pytorch to 2.2.2
- Change: Update pytorch to 2.2.2
**YES/NO**
NO
- Pipeline build id: [542342](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=542342&view=results)
=> Update pytorch to 2.2.2

SPECS/conmon/conmon.signatures.json, SPECS/conmon/conmon.spec, cgmanifest.json
---
Bump version to address CVE-2022-1708
[Reference](https://github.com/containers/conmon/releases/tag/v2.1.2): add log-global-size-max option to limit the total output conmon processes. This is needed to fix [CVE-2022-1708](https://nvd.nist.gov/vuln/detail/CVE-2022-1708).
- Bump version to address CVE-2022-1708
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-1708
- Pipeline build id:[ Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=545007)
=> Bump conmon version to 2.1.2 for CVE-2022-1708

SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
Remove obsolete `btrfs-progs-devel` build dependency from `moby-containerd-cc`.
- Remove obsolete `btrfs-progs-devel` build dependency from `moby-containerd-cc`. The same change has been ported to 3.0-dev
**NO**
- BuddyBuild: [546723](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=546723&view=results)
=> moby-containerd-cc: remove obsolete build dependency

SPECS/kubernetes/CVE-2023-5408.patch, SPECS/kubernetes/kubernetes.spec
---
kubernetes - fix CVE-2023-5408
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-5408
=> kubernetes - fix CVE-2023-5408

SPECS/azurelinux-release/azurelinux-release.spec
---
Bump Azure Linux release version for preview
- Bump Azure Linux Release Version
**NO**
=> Bump Azure Linux 3.0 Release Version

SPECS/R/R.spec, SPECS/haproxy/haproxy.spec, SPECS/httpd/httpd.spec, SPECS/hyperscan/hyperscan.spec, SPECS/liblognorm/liblognorm-2.0.6-pcre2.patch, SPECS/liblognorm/liblognorm.spec, SPECS/mc/mc.spec
---
Move haproxy, hyperscan, mc, R, httpd, liblognorm and postfix packages to pcre2
- Move haproxy, hyperscan, mc, R, httpd, liblognorm and postfix packages to pcre2
- Apply patch to liblognorm to support pcre2
**NO**
- Local build
- Pipeline build id: [545544](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=545544&view=results)
- Installation testing through containerized build:
=> Move haproxy, hyperscan, mc, R, httpd, liblognorm, postfix to pcre2

SPECS/cups/CVE-2023-4504.patch, SPECS/cups/cups.spec
---
Adds and applies a patch for CVE-2023-4504.
- Modified patch based on upstream commit to match our version of cups.
- Added the patch.
- Applied the patch.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-4504
- Fix: https://github.com/OpenPrinting/cups/commit/2431caddb7e6a87f04ac90b5c6366ad268b6ff31
- Tested applying patch locally.
- Local build succeeds.
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=547983&view=results
=> cups: patch CVE-2023-4504

toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go, toolkit/tools/pkg/osmodifierlib/modifierutils.go
---
Allow emu to update hostname
Allow emu to update hostname
NO
Will validate on trident side
=> OSModifier: Enable hostname update

toolkit/imageconfigs/packagelists/base-image-packages.json, toolkit/imageconfigs/packagelists/cloud-init-packages.json
in the 'base-image-packages' add the openssh-server package in the 'cloud-init-packages' add the cloud-utils-growpart package
=> toolkit: update package lists to include some needed packages

SPECS/nodejs/CVE-2024-27983.patch, SPECS/nodejs/nodejs18.spec
---
This PR is needed to fix CVE-2024-27983 related to nodejs package.
- Patch CVE-2024-27983.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-27983
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=548195&view=results
- Local build succeeded
=> Add patch to nodejs to fix CVE-2024-27983

SPECS/kata-packages-uvm/kata-packages-uvm.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Correct change log

toolkit/tools/imagecustomizer/docs/configuration.md, toolkit/tools/imagecustomizerapi/config.go, toolkit/tools/imagecustomizerapi/os.go, toolkit/tools/imagecustomizerapi/scripts.go, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/pkg/imagecustomizerlib/customizeboot.go, toolkit/tools/pkg/imagecustomizerlib/customizeoverlay.go, toolkit/tools/pkg/imagecustomizerlib/customizepackages.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/customizeverity.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go, toolkit/tools/pkg/imagecustomizerlib/testdata/consume-space.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/overlays-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-config.yaml, toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/finalizecustomizationscript.sh, toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/finalizeimagescript.sh, toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/postcustomizationscript.sh, toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/postinstallscript.sh, toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
1. Only regenerate the initramfs file once during customization, to save time.
2. Regenerate the initramfs file by directly calling `mkinitrd` instead of reinstalling the `initramfs` package, to save time and reduce complexity.
3. Remove the existing `os.postInstallScripts` and `os.finalizeImageScripts` properties, and replace them with new `scripts.postCustomization` and `scripts.finalizeCustomization` properties.
4. Move of the setting SELinux mode to be before the `postCustomization` scripts.
5. Move the adding of the verity and overlayfs dracut modules to be before the `postCustomization` scripts.
---
NO
=> Image Customizer: Operation ordering + scripts refactor.

.pipelines/containerSourceData/scripts/BuildBaseContainers.sh, toolkit/imageconfigs/core-container-builder.json, toolkit/imageconfigs/packagelists/core-container-builder-packages.json
---
This PR adds a new base core container builder image with packages required to bootstrap some docker build actions during the core container builds.
Addition of files:
- `toolkit/imageconfigs/core-container-builder.json`
- `toolkit/imageconfigs/packagelists/core-container-builder-packages.json`
Updates to files:
- `.pipelines/containerSourceData/scripts/BuildBaseContainers.sh`
**NO**
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=549006&view=results
=> base container builder image

toolkit/scripts/tools.mk, toolkit/tools/internal/exe/exe_test.go
---
We've missed updating out Go `ldflags` after the #8774 change. Fixing that and adding a test to verify the value is not empty.
No.
- #8774
- Local test.
- PR checks.
=> Fixed setting of the `ToolkitVersion` variable for our Go tools.

SPECS/libgudev/libgudev.signatures.json, SPECS/libgudev/libgudev.spec, cgmanifest.json
---
Bump version to 238
- bump version
- lint spec
NO
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=550558)
Install of package libgudev-devel fails for x86_64/aarch64. Did not debug.
Tried below commands on worker chroot preserved in local build with CLEANUP_PACKAGE_BUILDS=n
1. cd CBL-Mariner
2. sudo mkdir -p build/worker/chroot/libgudev-238-1.azl3/test
3. sudo cp out/RPMS/x86_64/libgudev-* build/worker/chroot/libgudev-238-1.azl3/test/
4. sudo -E PATH=$PATH chroot build/worker/chroot/libgudev-238-1.azl3/
5. createrepo --compatibility /test
6. repo_content=$(cat << EOF
[builtpackages]
name=Local Built Packages(x86_64) …
=> libgudev: Upgrade to version 238

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
- msft-golang: upgrade 1.21.8 -> 1.22.2
- msft-golang: upgrade 1.21.8 -> 1.22.2
**NO**
- [50100328](https://microsoft.visualstudio.com/OS/_workitems/edit/50100328)
- NA
- Local Build
- Pipeline build id: [PR-8794](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=550439&view=results)
=> msft-golang: upgrade 1.21.8 -> 1.22.2

SPECS/msft-golang/msft-golang.signatures.json, SPECS/msft-golang/msft-golang.spec, cgmanifest.json
---
Cherry-pick of a fast-track change #8794.
No.
- #8794
- PR check for the `fasttrack/2.0` change.
=> msft-golang: upgrade 1.21.8 -> 1.22.2 (CP: #8794)

SPECS/ig/ig.spec
---
Fix `%check` of `ig`.
- Fix `%check`
**NO**
=> ig: fix %check.

SPECS/libaec/libaec.signatures.json, SPECS/libaec/libaec.spec, cgmanifest.json
---
Upgrades libaec from 1.0.4 to 1.1.3
- Version bump to 1.1.3
**NO**
- #xxxx
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=551188&view=results
=> upgrade libaec to 1.1.3

SPECS/coredns/CVE-2024-22189.patch, SPECS/coredns/coredns.spec
---
Fix CVE-2024-22189 in coredns by patching vendored package quic-go
- Fix CVE-2024-22189 in coredns by patching vendored package quic-go
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-22189
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552037&view=results
=> Fix CVE-2024-22189 in coredns by patching vendored package quic-go

SPECS/azurelinux-release/azurelinux-release.spec
---
Azure Linux release bump for preview
- Bump azurelinux release version
=> Bump Azure Linux release version

SPECS/clamav/clamav.spec
---
Fix build break in `clamav`:
```
ERROR - CMake Error at cmake/FindSYSTEMD.cmake:123 (message):
INFO -   SYSTEMD_UNIT_DIR was defined but pkg-config was not able to find systemd!
```
- Fix build break in `clamav`
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552474&view=results
=> clamav: fix build break

SPECS/pcsc-lite/pcsc-lite.spec
---
Fix build break in `pcsc-lite`:
```
ERROR - error: File not found: /usr/src/azl/BUILDROOT/pcsc-lite-1.9.5-2.azl3.x86_64/usr/lib/systemd/system/pcscd.service
INFO - Processing files: pcsc-lite-1.9.5-2.azl3.x86_64
INFO - error: File not found: /usr/src/azl/BUILDROOT/pcsc-lite-1.9.5-2.azl3.x86_64/usr/lib/systemd/system/pcscd.socket
```
- Fix build break in `pcsc-lite`
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552427&view=results
=> pcsc-lite: fix build break

SPECS/collectd/collectd.spec, SPECS/collectd/fix_missing_longintrepr_header.patch
---
Fix build break in `collectd` by adding a patch from upstream.
- Fix `collectd` build break
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552504&view=results
=> collectd: fix build break

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json, SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, cgmanifest.json
---
Updating SymCrypt-OpenSSL to the latest version. Latest sources can be found here: https://github.com/microsoft/SymCrypt-OpenSSL/releases/tag/v1.4.1
Updates SymCrypt-OpenSSL to v1.4.1
- RSASSA-PSS key support
- SP800-108 KDF (KBKDF)
- Fixes existing tests and adds new tests for OpenSSL 3
NO
- local build
- pipeline build (SymCrypt-OpenSSL)
=> Update SymCrypt-OpenSSL to 1.4.1

SPECS-EXTENDED/gupnp/gupnp.spec, SPECS-EXTENDED/libotr/libotr-4.1.1-socket-h.patch, SPECS-EXTENDED/libotr/libotr.spec, SPECS-EXTENDED/samba/samba.spec
---
Fix extended build breaks in main of the following packages: `libotr`, `gupnp`, and `samba`
- Fix `libotr`
- Fix `gupnp`
- Fix `samba`
**NO**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552716&view=results
- Extended X64 build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552704&view=results
=> fix extended build breaks in main: libotr, gupnp, samba

toolkit/tools/internal/safechroot/safechroot.go
Summary of PR comments for #8807 in case this helps.
=> Summary of PR comments for #8807.

.pipelines/containerSourceData/scripts/PublishContainers.sh
---
This PR update container publishing script to attach an EOL manifest to images we publish.
File updated:
- .pipelines/containerSourceData/scripts/PublishContainers.sh
**NO**
[552541](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552541&view=results)
=> attach eol manifest using oras

SPECS/bpftrace/bpftrace-0.20-llvm18.patch, SPECS/bpftrace/bpftrace.signatures.json, SPECS/bpftrace/bpftrace.spec, cgmanifest.json
---
upgrade bpftrace to 0.20.3 and add patch for llvm18 support
- upgrade bpftrace to 0.20.3
- patch bpftrace for llvm18 support
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=553091&view=results
=> upgrade bpftrace to 0.20.3 and add patch for llvm18 support

SPECS/glib/glib.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Change pcre2 dependency in glib because pcre2-devel dependency caused disk footprint increase of ~20 MB.
- Change pcre2 dependency in glib
**YES**
- Local build
- Buddy build id: [554394](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=554394&view=results)
- Full build id: [554448](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=554448&view=results)
=> Change pcre2 dependency in glib

.pipelines/CodeQL/CodeQL.yml
---
fix trigger issue for Azl3 CodeQL
- Change
- Change
- Change
**NO**
- #xxxx
=> fix trigger issue for Azl3 CodeQL

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go, toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
---
It is possible customers may want to patch an existing image with verity enabled. The implementation should have some consistency and clearly calls out expectations - Options:
- Error out when that happens 
- Override the existing calculated verity hash and kernel args
We choose to achieve the first option erroring out when seeing the situation.
**NO**
- internal bug tracking: https://dev.azure.com/mariner-org/ECF/_workitems/edit/6830/
- Pipeline build id: local MIC build.
=> Error out when customizing a verity enabled base image.

SPECS/skopeo/skopeo.signatures.json, SPECS/skopeo/skopeo.spec, cgmanifest.json
---
See https://github.com/containers/skopeo/compare/v1.14.1...v1.14.2 for the details of the update. 
0.14.2 fixes version compatibility issues with docker 25.0.0 onwards. 
- Update skopeo to 0.14.2 resolving Docker Daemon issue
- Change
- Change
**NO**
=> Upgrade package skopeo to 0.14.2, to take Docker Daemon fix

.github/CODEOWNERS
---
Adding admins as required approvers of modifications to the set of trusted CAs.
No.
- Local tests with `.gitignore`.
=> Adding admin approval for certificate changes.

.pipelines/containerSourceData/scripts/BuildGoldenContainer.sh, .pipelines/containerSourceData/scripts/PublishContainers.sh
---
This PR update container publishing script to attach an EOL manifest to images we publish. It also updates the BuildGoldenContainer.sh script to create and publish the EOL manifest for the image when the image is created.
File updated:
- .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
- .pipelines/containerSourceData/scripts/PublishContainers.sh
**NO**
[552541](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552541&view=results)
=> attach EOL manifest to container images using oras

toolkit/tools/pkg/rpmssnapshot/rpmssnapshot.go, toolkit/tools/pkg/simpletoolchroot/simpletoolchroot.go, toolkit/tools/pkg/specarchchecker/specarchchecker.go
---
Make the simple chroot tool more general purpose for future use in a few tools:
- Don't imply the mount point is just for `./SPECS`
- Easy way to turn on network
- Generalize `SimpleToolChroot`
**NO**
- Local
=> Generalize simple chroot tool

SPECS/python-virtualenv/python-virtualenv.spec
---
Add `python-filelock` as a runtime requirement of `python-virtualenv`, in order to resolve the following error:
```
$ virtualenv -q -p python3 venv 
Traceback (most recent call last):
File "/usr/bin/virtualenv", line 5, in <module>
from virtualenv.__main__ import run_with_catch
File "/usr/lib/python3.12/site-packages/virtualenv/__init__.py", line 3, in <module>
from .run import cli_run, session_via_cli
File "/usr/lib/python3.12/site-packages/virtualenv/run/__init__.py", line 7, in <module>
from virtualenv.app_data import make_app_data
File "/usr/lib/python3.12/site-packages/virtualenv/app_data/__init__.py", line 11, in <module>
from …
```
=> python-virtualenv: update runtime requirements

SPECS/sos/copy-kernel-config.patch, SPECS/sos/create-azure-kdump-class.patch, SPECS/sos/create-azure-plugin.patch, SPECS/sos/sos.spec
---
- This is the 3.0 version of https://github.com/microsoft/azurelinux/pull/8857
- https://microsoft.visualstudio.com/OS/_workitems/edit/49177429
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=557020&view=results
- Installed the sos report rpm into a 3.0 Azure VM and ensured the changes are present and sos report is functional
=> Update sos to copy kernel config and vmcore

SPECS/clamav/clamav.signatures.json, SPECS/clamav/clamav.spec, cgmanifest.json
---
clamav: upgrade to 1.0.6
- Upgrade clamav package to 1.0.6
**NO**
- Local build
- Pipeline build id: [557120](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=557120&view=results)
=> clamav: upgrade to 1.0.6

SPECS/mariner-release/mariner-release.spec
=> Replace "April Update 2" with "May Update" in changelog

SPECS/kubernetes/kubernetes.spec
---
fix missing .patch being applied by using %autopatch (instead of individual %patch)
- Change
- Change
- Change
**NO**
- #xxxx
=> Kubernetes - fix missing auto patch

cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Use AZL3 preview msopenjdk RPMS in toolchain
- Use AZL3 preview msopenjdk RPMS in toolchain
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/50310623
- Full build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=557292&view=results
=> Use msopenjdk 17 from AZL3 Preview repo in toolchain

.pipelines/containerSourceData/nodejs/distroless/nodejs18.pkg, .pipelines/containerSourceData/prometheus/distroless/prometheus.pkg, .pipelines/containerSourceData/prometheusadapter/distroless/prometheusadapter.pkg, .pipelines/containerSourceData/python/distroless/python.pkg, SPECS/distroless-packages/distroless-packages.spec, toolkit/imageconfigs/packagelists/distroless-packages-container-minimal.json, toolkit/imageconfigs/packagelists/distroless-packages-container.json, toolkit/imageconfigs/packagelists/distroless-packages-debug.json
---
Cherry-pick of #8651.
The toolkit cannot currently handle resolving dependencies on distroless-only packages (`prebuilt-ca-certificates` and `prebuilt-ca-certificates-base`). Before a proper fix is available, we're moving out these packages from specs' `Requires` and into images package lists.
No.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=541291&view=results)
=> Moved distroless cert dependencies out of the meta package `distroless-packages`. (CP: #8651)

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json, SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, SPECS/SymCrypt/SymCrypt.spec, cgmanifest.json
---
Updates SymCrypt-OpenSSL to version 1.4.2. This version includes fixes to the SymCrypt provider for TLS connections.
- Fixed outstanding bugs in the SymCrypt provider found in testing
- Added support for additional TLS scenarios and parameters missing in the SymCrypt provider
- Detailed list of changes can be found here: https://github.com/microsoft/SymCrypt-OpenSSL/pull/78
NO
- local build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=557858&view=results
=> Update SymCrypt-OpenSSL to 1.4.2

SPECS/python-tensorboard/0000-Use-system-package.patch, SPECS/python-tensorboard/dockerfile, SPECS/python-tensorboard/genereate_source_tarball.sh, SPECS/python-tensorboard/python-tensorboard.signatures.json, SPECS/python-tensorboard/python-tensorboard.spec, SPECS/tensorflow/tensorflow.spec, cgmanifest.json
---
Update tensorboard to 2.16.2 and tensorboard-data-server to 0.8
- Change: Update tensorboard to 2.16.2
- Change: Add tensorboard as runtime req of tensorflow
- Change: Add auto upgrade script for easy tensorboard update in the future
**YES/NO**
NO
- Pipeline build id: [559826](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=559826&view=results)
=> Update tensorboard to 2.16.2

toolkit/tools/depsearch/depsearch.go
---
Fix log formatting in depsearch
- Remove leading and trailing whitespace
- Remove trailing '...'
- Replace enclosing variable output in '' with () for string variable
- Remove enclosing '' or () for non string variable output
**NO**
- Rebuilt tools successfully
=> fix depsearch log format

SPECS/kubernetes/CVE-2023-5408.patch, SPECS/kubernetes/kubernetes.spec
---
Fix kubernetes missing autopatch
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-5408
=> Fix kubernetes missing autopatch for CVE-2023-5408

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/mathops/mathops.go, toolkit/tools/internal/mathops/mathops_test.go
---
The modified code has been flagged as potentially missing an overflow. While unlikely, it's better to be safe than sorry. Added a new function to check for over-/underflows during addition of integers.
No.
- Local tests.
=> Resolved overflow warnings from `installutils.go:ProvisionUserSSHCerts`.

SPECS/azurelinux-release/azurelinux-release.spec
Bump Azurelinux Release for preview
- Bump Azurelinux Release
=> Bump Azurelinux-Release Version for Preview Release

SPECS/libdwarf/CVE-2024-2002.patch, SPECS/libdwarf/libdwarf.spec
---
- Fix CVE-2024-2002. See patch https://github.com/davea42/libdwarf-code/commit/404e6b1b14f60c81388d50b4239f81d461b3c3ad
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-2002
- 
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=560487&view=results
=> libdwarf: Mitigate CVE-2024-2002

toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
The operation that searches for the rootfs partition fails if it encounters a partition that it can't mount. For example, the BIOS boot partition. This change fixes this. Also, improve some logging and error messages.
---
NO
=> Image Customizer: Fix find rootfs.

SPECS/nodejs/nodejs18.signatures.json, SPECS/nodejs/nodejs18.spec, cgmanifest.json
---
Cherry-pick of CVE fixes for `nodejs`:
- CVE-2023-42282
- CVE-2024-24806
- CVE-2024-22025
- CVE-2024-27983
No.
- #8921
- PR check.
=> Upgrade nodejs18 to 18.20.2 address CVEs (CP: #8921)

toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
---
Update image customizer dependencies in the dockerfile
**YES/**NO****
Tested locally
=> Update image customizer container dependencies.

toolkit/tools/imagecustomizer/main.go, toolkit/tools/pkg/imagecustomizerlib/customizeboot.go, toolkit/tools/pkg/imagecustomizerlib/customizeoverlay.go, toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go, toolkit/tools/pkg/imagecustomizerlib/customizeutils.go, toolkit/tools/pkg/imagecustomizerlib/customizeverity.go, toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
Add some additional logs and error messages to help improve debuggability.
---
---
NO
=> Image Customizer: Improve logs and error messages.

SPECS/frr/CVE-2024-27913.patch, SPECS/frr/frr.spec
---
Patch CVE-2024-27913
- Create the patch
- Update changelog
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-27913
- Pipeline build id: [528407](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=528407&view=results)
=> frr: patch CVE-2024-27913

SPECS/golang/golang.signatures.json, SPECS/golang/golang.spec, cgmanifest.json
---
Bump golang version to 1.21.9-1
- Bump golang version to 1.21.9-1
- https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M
No
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543256&view=results
=> Bump golang version to 1.21.9-1

SPECS/php-pecl-zip/php-pecl-zip.spec
---
Add tzdata dependency to pass php test suite
- Add tzdata dependency to pass php test suite
NO
- Pipeline build id: 562087
=> Add tzdata dependency for php-pecl-zip

SPECS/bluez/CVE-2023-50229.patch, SPECS/bluez/bluez.spec
---
Apply upstream patch for CVE-2023-50229 in bluez
- Patch CVE-2023-50229 in bluez
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-50229
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=562552&view=results
=> bluez: patch CVE-2023-50229

SPECS/telegraf/CVE-2024-28110.patch, SPECS/telegraf/telegraf.spec
---
- Add back patch file to fix CVE-2024-28110 for telegraf
- Re-add patch for CVE-2024-28110
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-28110
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=564260&view=results
=> [2.0] Re-Fix telegraf CVE-2024-28110

toolkit/tools/downloader/downloader.go, toolkit/tools/pkg/downloader/downloader.go
---
refactor downloader into main tool and utils
- refactor downloader into main tool and utils
- part of series of similar changes across the toolkit
**NO**
- Built package successfully with REBUILD_TOOLS=y
- Built all tools (make go-tools REBUILD_TOOLS=y)
=> refactor downloader

SPECS/gnupg2/gnupg2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Disabling keyboxd for `gnupg2` completely. We are still experiencing hangs and issues with TDNF not finding the keys imported by `azurelinux-repos-shared`.
Yes.
- #8621
- #9035
- https://microsoft.visualstudio.com/OS/_workitems/edit/50552745
- Local build.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565387&view=results)
=> Disabled keyboxd for `gnupg2`.

SPECS/ansible/CVE-2024-0690.patch, SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
---
- Re-fix CVE-2023-5764
- Revert version from 2.14.4 to 2.14.12
- Add patch for CVE-2024-0690
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-5764
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=564545&view=results
=> [2.0] Resolved regressed ansible CVE-2023-5764

SPECS/python-daemon/python-daemon.signatures.json, SPECS/python-daemon/python-daemon.spec, cgmanifest.json
---
The PTest for python-daemon was failing, after investigation a new version is available. Upgrading to the new version fixes test failures due to newer python version on 3.0-dev
- Upgrade python-daemon to version 3.0.1
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565895&view=results
=> Upgrade python-daemon to Version 3.0.1

SPECS/python-fastjsonschema/python-fastjsonschema.spec
---
The PTest for python-fastjsonschema is not passing following being added to 3.0-dev. This PR resolves the issue.
- Add iniconfig pip install to %check section for tests.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566063&view=results
=> PTest Fix for python-fastjsonschema

SPECS/coredns/CVE-2024-0874.patch, SPECS/coredns/coredns.spec
---
CVE fix
- CVE-2024-0874
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-0874
- Pipeline build id: [565775](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565775&view=results)
=> coredns: Patched cache plugin to address CVE-2024-0874

SPECS/python-rich/python-rich.spec
---
Rename Pygments to pygments
- Change: Rename Pygments to pygments
**YES/NO**
NO
=> Rename Pygments to pygments for python-rich

toolkit/imageconfigs/full-aarch64.json, toolkit/imageconfigs/full.json
---
10-console-messages.conf was removed from additional files. Remove lingering references which are causing build failures.
PR which removed console messages : https://github.com/microsoft/azurelinux/pull/9011
- Remove 10-console-messages.conf from image configs
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build?definitionId=2064
=> Remove 10-console-messages.conf from image configs

.pipelines/containerSourceData/tensorflow/tensorflow.pkg
---
There's a difference between packages required for older tensorflow in 2.0 Mariner vs Azl3.0's tensorflow. 
- Change: Change package require for tensorflow
**YES/NO**
NO
- Pipeline build id: [569869](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=569869&view=results)
=> Fix tensorflow golden container

SPECS/python-tqdm/CVE-2024-34062.patch, SPECS/python-tqdm/python-tqdm.spec
---
Patches CVE-2024-34062 in the python-tqdm package.
- patch CVE-2024-34062
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-34062
- Pipeline build id: 569383
=> python-tqdm: patch CVE-2024-34062

SPECS/python-wheel/python-wheel.signatures.json, SPECS/python-wheel/python-wheel.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
[What does the PR accomplish, why was it needed?
python-wheel: upgrade to 0.43.0
- Upgrade python-wheel to 0.43.0
**YES**
- Local build
- Latest pipeline build id: [569969](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=569969&view=results)
- Delta build id: [567474](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=567474&view=results)
- Full build id: [567492](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=567492&view=results)
=> python-wheel: upgrade to 0.43.0

SPECS/python-werkzeug/CVE-2024-34069.patch, SPECS/python-werkzeug/python-werkzeug.spec
---
Patch CVE-2024-34069
- CVE-2024-34069
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-34069
- Pipeline build id: 570115
=> python-werkzeug: Patch CVE-2024-34069

toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md, toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go, toolkit/tools/pkg/imagecustomizerlib/bootcustomizer_test.go, toolkit/tools/pkg/imagecustomizerlib/testdata/bootcfgtests/2.0-default-grub, toolkit/tools/pkg/imagecustomizerlib/testdata/bootcfgtests/2.0-grub.cfg, toolkit/tools/pkg/imagecustomizerlib/testdata/bootcfgtests/3.0-default-grub
=> Image Customizer: Add tests for BootCustomizer type.

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json, SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, cgmanifest.json
---
This PR updates SymCrypt-OpenSSL to 1.4.3 with various bugfixes
- Additional bugfixes for TLS connections using the SymCrypt provider
- Add variable-length IV support for AES-GCM in the SymCrypt engine
NO
- fixes microsoft/SymCrypt-OpenSSL#79
- Manual build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=571230&view=results
=> Update SymCrypt-OpenSSL to 1.4.3

.github/CODEOWNERS
---
Cherry-pick of 2.0's #8859.
Adding admins as required approvers of modifications to the set of trusted CAs.
No.
- Local tests with `.gitignore`.
=> Adding admin approval for certificate changes. (CP: #8859)

SPECS/httpd/httpd.spec
---
Some small house cleaning, namespace httpd-devel header files into a httpd directory
- Namespace and put httpd header files into /usr/include/httpd
**NO**
- Build package 
```
azaugg@azaugg-ld77 [ ~/CBL-Mariner/toolkit ]$ sudo make build-packages -j$(nproc) REBUILD_TOOLS=y SRPM_PACK_LIST="httpd" PACKAGE_REBUILD_LIST="httpd" REFRESH_WORKER_CHROOT=y RUN_CHECK=y
...
...
...
INFO[0000][scheduler] Building 68 nodes with 8 workers
INFO[0000][scheduler] Building: httpd-2.4.56-4.cm2.src.rpm
INFO[0065][scheduler] Built: httpd-2.4.56-4.cm2.src.rpm -> [/home/azaugg/CBL-Mariner/out/RPMS/x86_64/httpd-2.4.56-4.cm2.x86_64.rpm /home/azaugg/CBL-Mariner/out/RPMS/x86_64/httpd-debuginfo-2.4.56-4.cm2. …
```
=> Namespace httpd include files into its own directory

SPECS/ruby/CVE-2024-27282.patch, SPECS/ruby/ruby.spec
---
This fixes CVE-2024-27282
- Patch CVE-2024-27282
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-27282
- Pipeline build id: 571152
=> ruby: Patch CVE-2024-27282

SPECS/cmake/cmake.spec, SPECS/nodejs/nodejs.spec, SPECS/python-gevent/python-gevent.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
bump release to build with fixed libuv CVE-2024-24806
- bump release to build with fixed libuv CVE-2024-24806
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-24806
- No build
=> bump release to build with fixed libuv CVE-2024-24806

SPECS/azurelinux-release/azurelinux-release.spec
Update azurelinux-release number for preview update
- Update azurelinux-release number for preview update
=> Update azurelinux-release for preview release

SPECS/mariner-release/mariner-release.spec
Bump Mariner 2.0 Release for June 2024 Update
=> Bump Mariner 2.0 Release for June 2024 Update

toolkit/imageconfigs/additionalconfigs/cloud-init.cfg
---
Fixes: #9149
**NO**
- #9149
- NA
- NA
=> imageconfigs: cloud-init: fix typo AureLinux -> AzureLinux

SPECS/azcopy/azcopy.signatures.json, SPECS/azcopy/azcopy.spec, cgmanifest.json
---
Update azcopy to latest to fix multiple security issues
- Upgrade azcopy to 10.24.0
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=574846&view=results
=> Upgrade azcopy to 10.24.0 to fix multiple security issues

SPECS/cups/CVE-2022-26691.patch, SPECS/cups/cups.spec
---
Patch CVE in cups.
- CVE 2022-26691
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-26691
- Tested that patches apply cleanly locally.
- Build succeeds locally.
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=573502&view=results
=> cups: patch CVE-2022-26691.

SPECS/telegraf/CVE-2024-27289.patch, SPECS/telegraf/telegraf.spec
---
- Add patch file to resolve CVE-2024-27289
- Add patch to resolve CVE-2024-27289
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-27289
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=577368&view=results
=> [2.0] Resolve telegraf CVE-2024-27289

SPECS/ig/ig.signatures.json, SPECS/ig/ig.spec, cgmanifest.json
---
Bump `ig` version to `v0.26.0`.
- Bump to version 0.26.0.
**NO**
=> ig: Bump version to v0.26.0.

SPECS/cert-manager/cert-manager.spec, SPECS/helm/CVE-2024-26147.patch, SPECS/helm/helm.spec
---
fix CVE-2024-26147
- fix CVE-2024-26147
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-26147
- Local build with all tests passing
- Successful buddyBuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=573984&view=results
=> helm: fix CVE-2024-26147

SPECS-EXTENDED/python-openpyxl/python-openpyxl.signatures.json, SPECS/python-openpyxl/python-openpyxl.signatures.json, SPECS/python-openpyxl/python-openpyxl.spec, cgmanifest.json
Changes to be committed:
deleted:    SPECS-EXTENDED/python-openpyxl/python-openpyxl.signatures.json
new file:   SPECS/python-openpyxl/python-openpyxl.signatures.json
renamed:    SPECS-EXTENDED/python-openpyxl/python-openpyxl.spec -> SPECS/python-openpyxl/python-openpyxl.spec
modified:   cgmanifest.json
---
Need to update openpyxl package for superbenchmark support
Changes to be committed:
deleted:    SPECS-EXTENDED/python-openpyxl/python-openpyxl.signatures.json
new file:   SPECS/python-openpyxl/python-openpyxl.signatures.json
renamed:    SPECS-EXTENDED/python-openpyxl/python-openpyxl.spec -> SPECS/python-openpyxl/python-openpyxl.spec
modified:   cgmanifest.json
NO
- Pipeline build …
=> Update python openpyxl package

.pipelines/containerSourceData/rabbitmqserver/Dockerfile-rabbitmq-server
---
Fix Rabbitmq-server Golden Container 
- Change: Remove Hardcoded rabbitmq-server version 
**YES/NO**
NO
- Pipeline build id: [578366](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578366&view=results)
=> Remove hardcoded version to fix Rabbitmq Golden Container

SPECS/dpdk/dpdk.spec
- Add `-Denable_kmods=true` to the meson build configuration to enable the Kernel Network Interface (KNI) module.
- Ensure the KNI module is built as part of the DPDK package without automatically loading it.
This change ensures that the KNI module is available for use when needed, without being loaded by default.
---
This pull request enables the Kernel Network Interface (KNI) module in the DPDK build process. The KNI module is a key component for packet processing in user space, and enabling it as part of the build ensures it is available for use when needed. Enabling the KNI module provides flexibility for network applications that require fast packet processing. By building the …
=> Enable KNI module in DPDK build

SPECS/fluent-bit/fluent-bit.signatures.json, SPECS/fluent-bit/fluent-bit.spec, cgmanifest.json
---
fluent-bit: Update to v3.0.6 to fix CVE-2024-4323
- fluent-bit: Update to v3.0.6 to fix CVE-2024-4323
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-4323
- Local build
- Pipeline build successful (error in installation): https://dev.azure.com/mariner-org/mariner/_build/results?buildId=577409&view=results
=> fluent-bit: Update to v3.0.6 to fix CVE-2024-4323

SPECS/cert-manager/CVE-2024-26147.patch, SPECS/cert-manager/cert-manager.spec
---
Adds patch for CVE-2024-26147
- Patches CVE-2024-26147
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-26147
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578920&view=results
=> Patch CVE-2024-26147 for cert-manager

SPECS/unixODBC/CVE-2024-1013.patch, SPECS/unixODBC/unixODBC.spec
---
unixODBC: patch CVE-2024-1013
- unixODBC: patch CVE-2024-1013
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-1013
- Local build
- Pipeline build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578138&view=results
=> unixODBC: patch CVE-2024-1013

SPECS/python-tensorboard/python-tensorboard.spec, SPECS/python-werkzeug/python-werkzeug.signatures.json, SPECS/python-werkzeug/python-werkzeug.spec, SPECS/tensorflow/tensorflow.spec, cgmanifest.json
---
python-werkzeug: Update to 3.0.3 to fix CVE-2024-34069
- python-werkzeug: Update to 3.0.3 to fix CVE-2024-34069
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-34069
- Pipeline build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578788&view=results
=> python-werkzeug: Update to 3.0.3 to fix CVE-2024-34069

SPECS/clang/clang.spec, SPECS/compiler-rt/compiler-rt.spec, SPECS/lld/lld.spec, SPECS/lldb/lldb.spec, SPECS/llvm/CVE-2024-31852.patch, SPECS/llvm/llvm.spec, SPECS/rust/rust.spec, SPECS/tensorflow/tensorflow.spec
---
llvm: patch CVE-2024-31852
- llvm: patch CVE-2024-31852
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-31852
- Local build
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578195&view=results
=> llvm: patch cve-2024-31852

SPECS/moby-engine/CVE-2023-44487.patch, SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine to address CVE-2023-44487
- Patch moby-engine to address CVE-2023-44487
**NO**
- Upstream source: https://github.com/grpc/grpc-go/pull/6703
- https://github.com/advisories/GHSA-m425-mq94-257g
- BuddyBuild: [579257
](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=579257&view=results)
=> Patch moby-engine to address CVE-2023-44487

SPECS/nodejs/nodejs.spec
---
Separate npm from nodejs package to its own nodejs-npm subpackage. 
- Change: Separate npm from nodejs package to its own nodejs-npm subpackage. 
**YES/NO**
NO
- Pipeline build id: [580480](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580480&view=results)
=> Separate npm from nodejs package.

SPECS/cert-manager/cert-manager.spec, SPECS/helm/CVE-2024-25620.patch, SPECS/helm/helm.spec
---
helm: patch cve-2024-25620
- helm: patch cve-2024-25620
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-25620
- Pipeline build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578276&view=results
- Local build, all tests passed
=> helm: patch cve-2024-25620

SPECS/cri-o/cri-o.signatures.json, SPECS/cri-o/cri-o.spec, SPECS/cri-o/generate_source_tarball.sh, cgmanifest.json
---
Upgrade cri-o to address CVEs (3.0-dev)
- Change
- Change
- Change
**NO**
- #xxxx
=> Upgrade cri-o to address CVEs (3.0-dev)

SPECS/cmake/CVE-2024-24806.patch, SPECS/cmake/cmake.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
cmake address CVE-2024-24806
buddy build -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578852&view=results
Full build 
toolchain -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=579187&view=result
- Change
- Change
- Change
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-24806
=> cmake address CVE-2024-24806

SPECS/crash/crash.signatures.json, SPECS/crash/crash.spec
---
crash fix CVE 2022 37434
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE 2022 37434
=> crash fix CVE 2022 37434

SPECS/golang/golang.signatures.json, SPECS/golang/golang.spec, cgmanifest.json
---
Bump golang version to 1.22.4-1
- Bump golang version to 1.22.4-1
No
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=581302&view=results
=> Bump golang version to 1.22.4-1

SPECS/librsvg2/librsvg2.signatures.json, SPECS/librsvg2/librsvg2.spec, cgmanifest.json
---
upgrade libsrvg2 to address critical CVEs
- Change
- Change
- Change
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=581870&view=results
=> upgrade libsrvg2 to address critical CVEs

SPECS/libglvnd/CVE-2019-11834.patch, SPECS/libglvnd/libglvnd.spec
---
libglvnd - address CVE-2019-11834 and CVE-2019-11835
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-11834
- https://nvd.nist.gov/vuln/detail/CVE-2019-11835
=> libglvnd - address CVE-2019-11834 and CVE-2019-11835

SPECS/ig/ig.signatures.json, SPECS/ig/ig.spec, cgmanifest.json
---
Bump `ig` to latest released version.
- Bump ig to `v0.29.0`.
**NO**
Test Build: [PR-9274](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580256&view=results) ✅
=> ig: Bump version to v0.29.0.

SPECS/sysbench/CVE-2019-19391.patch, SPECS/sysbench/sysbench.spec
---
sysbench address CVE 2019 19391
- Change
- Change
- Change
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-19391
- Pipeline build id: 582422
=> sysbench address CVE 2019 19391

SPECS/nodejs/nodejs.signatures.json, SPECS/nodejs/nodejs.spec, cgmanifest.json
---
upgrade nodejs to 20.14.0 to address CVEs
- Change
- Change
- Change
**YES/
- #xxxx
- Pipeline build id: 582865
=> upgrade nodejs to 20.14.0 to address CVEs

SPECS/fio/fio.spec
---
update fio to build without ceph dependencies 
Fix for blocked package, which is due to `fio` requiring `librbd1-devel` which is provided by `ceph`, which was moved to extended in PR #9157 
```
"Blocked SRPMs:"
"--> fio-3.37-1.azl3.src.rpm"
```
- update fio to build without ceph dependencies 
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582607&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582899&view=results
=> update fio to build without ceph dependencies

toolkit/scripts/setuplkgtoolchain.sh
---
Add a parameter to `toolkit/scripts/setuplkgtoolchain.sh` that allows us to get the manifests for a given build id. This way, if LKG is broken or if we want a specific day's build, it's easy to get the manifests.
- Updated script
**NO**
=> add parameter for specific build to setuplkgtoolchain.sh

SPECS/python-cryptography/python-cryptography.spec
---
Updating the minimum version for OpenSSL where the CVE-2023-50782 is fixed.
Refer to https://github.com/microsoft/azurelinux/pull/9318 for more information
- CVE-2023-50782
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-50782
- Pipeline build id: [583018](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=583018&view=results)
=> python-cryptography: Update OpenSSL version to fix CVE-2023-50782 

SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec, SPECS/kernel-mos/config, SPECS/kernel-mos/kernel-mos.signatures.json, SPECS/kernel-mos/kernel-mos.spec, cgmanifest.json
---
Update kernel-mos to 5.15.158.2
- Update kernel-mos to 5.15.158.2
NO
- Pipeline build id: 582965
=> Update kernel-mos to 5.15.158.2

SPECS/azl-compliance/azl-compliance.signatures.json, SPECS/azl-compliance/azl-compliance.spec, cgmanifest.json
---
Upgrade `azl-compliance` to latest version, to move us closer to FedRAMP compliance for AZL on AKS.
- Upgrade `azl-compliance` to latest version.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582412&view=results
=> Upgrade azl-compliance to version 1.0.2

SPECS/python-xlrd/python-xlrd.spec
---
Fix build break in `python-xldr` from #9322 by removing duplicate files (which seem to be from a "with_python3_other" package in the [Fedora spec](https://src.fedoraproject.org/rpms/python-xlrd/c/87393a786a110d761901ab4145491443c1580bdb).
- Fix break in `python-xlrd`
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=583387&view=results
=> python-xlrd: fix build break

SPECS/edk2/CVE-2024-1298.patch, SPECS/edk2/edk2.spec
---
edk2: add patch for CVE-2024-1298
- edk2: add patch for CVE-2024-1298
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-1298
=> edk2: add patch for CVE-2024-1298

SPECS-SIGNED/hvloader-signed/hvloader-signed.spec, SPECS/hvloader/CVE-2024-1298.patch, SPECS/hvloader/hvloader.spec
---
Fixes CVE
- hvloader: add patch to resolve CVE-2024-1298
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-1298
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582257&view=results
- Kata Dev image build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582273&view=results
- Relevant conf tests run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582284&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=c7c10b6c-9240-5a39-cc00-91d242e4cf32
=> hvloader: add patch to resolve CVE-2024-1298

.pipelines/containerSourceData/nodejs/distroless/nodejs.pkg, .pipelines/containerSourceData/nodejs/nodejs.pkg
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> add nodejs-npm to nodejs golden container

SPECS/php/php.signatures.json, SPECS/php/php.spec, cgmanifest.json
---
php: udpate to v8.3.8 to fix CVEs
- php: udpate to v8.3.8 to fix CVEs
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-4577
- https://nvd.nist.gov/vuln/detail/CVE-2024-5458
- https://nvd.nist.gov/vuln/detail/CVE-2024-5585
- Local build
=> php: udpate to v8.3.8 to fix CVEs

SPECS/azurelinux-release/azurelinux-release.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Bump azurelinux release for preview

SPECS/libarchive/CVE-2024-26256.patch, SPECS/libarchive/libarchive.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fixes CVE-2024-26256
- Patch CVE-2024-26256
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-26256
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582430&view=results
=> libarchive: add patch to resolve CVE-2024-26256

.pipelines/containerSourceData/memcached/Dockerfile-Memcached
---
This PR updates the memcached dockerfile to include shadow-utils so that the useradd command can succeed.
- Change
- Change
- Change
**NO**
Tested this change locally.
=> add oneliner to memcached dockerfile to add user

SPECS/libndp/CVE-2024-5564.patch, SPECS/libndp/libndp.spec
---
Patch CVE-2024-5564 in libndp
- Patch CVE-2024-5564 in libndp
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-5564
- Pipeline build id: 586752
=> [3.0-dev] Patch CVE-2024-5564 in libndp

SPECS/nano/CVE-2024-5742.patch, SPECS/nano/nano.spec
---
Patch CVE-2024-5742 in nano
- CVE-2024-5742
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-5742
- Uniform Buddy Build: [586298](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586298&view=results)
=> Patch CVE-2024-5742 in nano
