SPECS/pytorch/CVE-2024-27319.patch
SPECS/pytorch/CVE-2024-31580.patch
SPECS/pytorch/CVE-2024-31583.patch
SPECS/pytorch/pytorch.spec

---
PAtches 'pytorch' package for cve-2024-31580, cve-2024-31583, cve-2024-27319
PAtches 'pytorch' package for cve-2024-31580, cve-2024-31580, cve-2024-27319
- Change
- Change
- Change
/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/cve-2024-31580
- https://nvd.nist.gov/vuln/detail/cve-2024-31583
- https://nvd.nist.gov/vuln/detail/cve-2024-27319
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=555643&view=results

pytorch: fix cve-2024-31580, cve-2024-31583, cve-2024-27319

---

toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go

When building a Live-CD using the image customizer, if the user accidentally removes the grub2-efi-binary or shim packages, then the error for what is wrong isn't particularly helpful. This change improves the error message.
---
NO
- Added UTs.

Image Customizer: Improve error message for missing EFI files.

---

toolkit/resources/manifests/package/update_manifests.py

Create a new script that updates the contents of the toolchain manifest files using the contents of a toolchain archive tarball. This is intended as a replacement for the existing `update_manifests.sh` script, with  hopefully better handling the package ordering. Specifically, it uses the ordering from the existing manifest files instead of recreating the ordering manually.
---
NO
- Ran script manually.

New toolchain manifest update from tarball script.

---

SPECS/sos/copy-kernel-config.patch
SPECS/sos/create-azure-kdump-class.patch
SPECS/sos/create-azure-plugin.patch
SPECS/sos/sos.spec

---
- This PR backports changes from upstream sos to gather more information in the sosreport
- 3 patches have been introduced
- `create-azure-plugin.patch` - upstream [change](https://github.com/sosreport/sos/pull/3576)
- Created an AzurePlugin class - This will help us create custom Azure classes for plugins
- Changed the distribution website to point to `https://github.com/microsoft/azurelinux` instead of `https://github.com/microsoft/CBL-Mariner`
- Modified the `check` function to also check for `Microsoft Azure Linux` in `/etc/os-release`
- `copy-kernel-config.patch`  - upstream [change](https://github.com/sosreport/sos/pull/3580) …

Update sos to copy kernel config and vmcore

---

SPECS/git-lfs/CVE-2023-45288.patch
SPECS/git-lfs/git-lfs.signatures.json
SPECS/git-lfs/git-lfs.spec
cgmanifest.json

---
- git-lfs: upgrade version 3.4.1 -> 3.5.1 to address CVE-2023-39325 & CVE-2023-45288
- git-lfs: upgrade version 3.4.1 -> 3.5.1 to address CVE-2023-39325 & CVE-2023-45288
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-39325
- Local Build & Test
- Pipeline build id: [PR-8871](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=555912&view=results)

git-lfs: upgrade version 3.4.1 -> 3.5.1 to address CVE-2023-39325 & CVE-2023-45288

---

SPECS/kata-packages-uvm/kata-packages-uvm.spec

---
Cherry-pick changes on to 3.0.
Ref PR: https://github.com/microsoft/azurelinux/pull/8762/files
- kata-packages-uvm: add cifs-utils as dependency
**YES**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=556056&view=results

kata-cc: kata-packages-uvm: add cifs-utils as dependency

---

.pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
.pipelines/containerSourceData/scripts/PublishContainers.sh

---
This PR updated the BuildGoldenContainer.sh script to create and publish the EOL manifest for the image when the image is created.
- .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
- .pipelines/containerSourceData/scripts/PublishContainers.sh
**NO**
[Test build 555713](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=555713&view=logs&j=73f98e25-130a-588e-bd98-f793ccaa0793&t=4db77840-7115-5ba4-8b35-d5a6e1db5c3d&l=1059)

attach EOL during image creation

---

toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/corruptionoption.go
toolkit/tools/imagecustomizerapi/corruptionoption_test.go
toolkit/tools/imagecustomizerapi/verity.go
toolkit/tools/imagecustomizerapi/verity_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

---
Mariner should not go into an endless reboot loop when one of files protected by verity becomes corrupted.
We could expose separate verity action, that does not cause kernel panic.
The options added are all that systemd supports today.
**NO**
- Pipeline build id: local MIC build
Related internal task tracking: https://dev.azure.com/mariner-org/ECF/_workitems/edit/7151/

Expose verity hash corruption options besides panic.

---

SPECS/terraform/CVE-2024-3817.patch
SPECS/terraform/terraform.spec

---
Patch the vendored copy of `go-getter` in `terraform` with  [this patch](https://github.com/hashicorp/go-getter/pull/483) to resolve CVE-2024-3817.
- Patch CVE-2024-3817 in `terraform`.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-3817
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=555704&view=results
- Local build

Patch CVE-2024-3817 in terraform's vendored go-getter

---

SPECS/frr/0000-remove-babeld-and-ldpd.patch
SPECS/frr/0001-enable-openssl.patch
SPECS/frr/0003-fips-mode.patch
SPECS/frr/0004-remove-grpc-test.patch
SPECS/frr/0008-Add-FIPS_mode-compatibility-macro.patch
SPECS/frr/frr.signatures.json
SPECS/frr/frr.spec
SPECS/libyang/libyang.signatures.json
SPECS/libyang/libyang.spec
cgmanifest.json

---
Upgrade `frr` to version 9.1. Also upgrade `libyang` to version 2.1.148, required by `frr`.
- frr: upgrade to 9.1
- libyang: upgrade to 2.1.148
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=556704&view=results

frr: upgrade to 9.1

---

SPECS/selinux-policy/0042-getty-grant-checkpoint_restore.patch
SPECS/selinux-policy/selinux-policy.spec

Patch cherry-picked from upstream. Fixes new issue seen in SELinux BVT.
---
Fix SELinux denial for agetty.
- Cherry-pick patch from upstream for getty checkpoint restore.
**NO**
- Pipeline build id: 556124

selinux-policy: Add checkpoint restore for getty.

---

SPECS/systemd/azurelinux-use-system-auth-in-pam-systemd-user.patch
SPECS/systemd/systemd.spec

While Fedora uses a single 'system-auth' file to contain common configuration for all pam types, azurelinux uses separate files per pam type, i.e. 'system-account', 'system-session', etc.
This fixes the failure to start the systemd user service (i.e. `user@$UID.service`)

systemd: adjust /lib/pam.d/systemd-user to include correct pam files

---

SPECS/cri-o/CVE-2021-3602.patch
SPECS/cri-o/CVE-2021-44716.patch
SPECS/cri-o/CVE-2022-21698.patch
SPECS/cri-o/CVE-2022-27651.patch
SPECS/cri-o/CVE-2022-29526.patch
SPECS/cri-o/CVE-2022-2995.patch
SPECS/cri-o/CVE-2023-42821.patch
SPECS/cri-o/CVE-2023-44487.patch
SPECS/cri-o/CVE-2024-28180.patch
SPECS/cri-o/cri-o.spec

---
Patch cri-o CVEs
CVE-2021-3602
CVE-2021-44716
CVE-2022-21698
CVE-2022-27651
CVE-2022-29526
CVE-2022-2995
CVE-2023-42821
CVE-2023-44487
CVE-2024-28180
CVE-2024-21626
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=556259&view=results

Apply patches to fix CVE-2021-3602, CVE-2022-27651, CVE-2022-2995, CVE-2023-42821

---

toolkit/Makefile

---
PMC has `ms-oss` instead of `Microsoft` for 3.0:
https://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/
https://packages.microsoft.com/azurelinux/3.0/preview/ms-oss/
We need these to grab `msopenjdk`.
- Update PACKAGE_URL_LIST to use new PMC layout.
**YES**

Update Makefile to use ms-oss PMC url instead of Microsoft

---

SPECS/xxhash/xxhash.spec

---
Modify `xxhash` to build with `XXH_X86DISPATCH_ALLOW_AVX` set, which is need after PR #8846 changed gcc to use `-march=x86-64-v3`. This should be ok for us since we will not support v2 or earlier architecture levels, so AVX should always be available. For more details see: `https://github.com/Cyan4973/xxHash/issues/839`
Fixes error:
```
ERROR - xxh_x86dispatch.c:93:4: error: #error \"Error: if xxh_x86dispatch.c is compiled with AVX enabled, the resulting binary will crash on sse2-only cpus !! \" \"If you nonetheless want to do that, please enable the XXH_X86DISPATCH_ALLOW_AVX build variable\" 
INFO - 93 | # error \"Error: if …
```

xxhash: fix build issue with x86-64-v3

---

SPECS/strace/strace.signatures.json
SPECS/strace/strace.spec
cgmanifest.json

---
Upgrade `strace` to 6.8
- Upgrade `strace` to 6.8
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=557621&view=results

strace: upgrade to 6.8

---

SPECS/php-pecl-zip/php-pecl-zip.spec

---
The runtime requirements for `php-pecl-zip` were not met after `php` was upgraded to version 8.3.4 in #8888. This PR fixes them to match the versions specified in the php 8.3.4 source:
```
Zend/zend_modules.h:34:#define ZEND_MODULE_API_NO 20230831
main/php.h:25:#define PHP_API_VERSION 20230831
```
This fixes the following unresolved dependencies:
```
"Unresolved dependencies:" 
"--> php(api):C:'='V:'20210902-64',C2:''V2:''" 
"--> php(zend-abi):C:'='V:'20210902-64',C2:''V2:''" 
```
- php-pecl-zip: fix runtime requirements to match php 8.3.4
**NO**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=558062&vi …

php-pecl-zip: fix runtime requirements to match php 8.3.4

---

SPECS/python-libclang/python-libclang.signatures.json
SPECS/python-libclang/python-libclang.spec
cgmanifest.json

---
Upgrades `python-libclang` from `14.0.6` to `18.1.1`
- Upgraded `python-libclang` from `14.0.6` to `18.1.1`
NO
- Pipeline build id: 557817

Upgrading `python-libclang` from `14.0.6` from `18.1.1`

---

SPECS/redis/redis.spec

---
This PR enables building **redis** with `BUILD_TLS=yes` option. This resolves the bug: https://microsoft.visualstudio.com/OS/_workitems/edit/49786797/.
- Updated SPECS/redis/redis.spec
**NO**
Unified ADO Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=558589&view=results
Test: Installed redis-6.2.14-2 and the `redis-cli --tls` command does not return error: `Unrecognized option or bad number of args for: '--tls'`. Instead we get the following message (which means that we successfully built redis with tls enabled):
```
redis-cli --tls
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not …
```

build redis with BUILD_TLS=yes

---

.pipelines/containerSourceData/scripts/BuildBaseContainers.sh

---
This change adds EOL (End-of-Life) manifest to base container images. We previously only added this manifest for golden container images and after validating that change, we are now adding them to the base container images as well.
- .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
**NO**
[558655](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=558655&view=results)

attach EOL manifest to base containers as well

---

SPECS/rocksdb/rocksdb.spec

---
rocksdb: fix compilation issue with x86-64-v3 architecture
rocksdb is failing to compile with the recent change to use -march=x86-64-v3. (PR #8846)
```
INFO -                  from /usr/src/azl/BUILD/rocksdb-8.9.1/util/math.h:13,
INFO -                  from /usr/src/azl/BUILD/rocksdb-8.9.1/util/crc32c.cc:22:
INFO - In function '__m128i _mm_clmulepi64_si128(__m128i, __m128i, int)',
INFO -     inlined from 'uint64_t rocksdb::crc32c::CombineCRC(size_t, uint64_t, uint64_t, uint64_t, const uint64_t*)' at /usr/src/azl/BUILD/rocksdb-8.9.1/util/crc32c.cc:555:41,
INFO -     inlined from 'uint32_t rocksdb::crc32c::crc32c_3way(uint32_t, const …
```

rocksdb: fix compilation issue with x86-64-v3 architecture

---

SPECS/zeromq/zeromq.signatures.json
SPECS/zeromq/zeromq.spec
cgmanifest.json

---
zeromq: upgrade to 4.3.5. This contains a [fix](https://github.com/zeromq/libzmq/pull/4215) for the following broken test (occasionally fails when run on heavily loaded ptest pipeline)
```
"./config/test-driver: line 112: 256129 Aborted                 (core dumped) \"$@\" >> \"$log_file\" 2>&1"
"FAIL: tests/test_inproc_connect"
```
- zeromq: upgrade to 4.3.5
**NO**
- [Bug 50444828](https://microsoft.visualstudio.com/OS/_workitems/edit/50444828): [2.0] zeromq test_inproc_connect.cpp fails
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=559971&view=results

[2.0] zeromq: upgrade to 4.3.5

---

toolkit/tools/downloader/downloader.go
toolkit/tools/graphPreprocessor/graphPreprocessor.go
toolkit/tools/graphanalytics/graphanalytics.go
toolkit/tools/grapher/grapher.go
toolkit/tools/graphpkgfetcher/graphpkgfetcher.go

---
Fix log formatting in downloader, graphanalytics, grapher, graphpkgfetcher, graphPreprocessor
Test Methodology
- Remove leading and trailing whitespace
- Remove trailing '...'
- Replace enclosing variable output in '' with () for string variable
- Remove enclosing '' or () for non string variable output
**NO**
- Rebuilt tools successfully

fix log format in go-tools

---

toolkit/tools/imagecustomizer/docs/configuration.md

When the SELinux mode was moved during the API refactor, the docs weren't correctly updated. This change fixes this.
In addition, this change include a couple of extra minor cleanup/fixes.
---
NO
- n/a

Image Customizer: Doc fixes for SELinux mode.

---

SPECS/moby-engine/moby-engine.spec

---
Upgrading moby-engine to 24.0.9 included moving docker-proxy from /usr/bin/docker-proxy into /usr/libexec/docker-proxy
- Symlink /usr/bin/docker-proxy to /usr/libexec/docker-proxy for back-compat
**NO**
- Bug 50492689
- Local Package build succeeded
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=561171&view=results
- Installed the new package on an Azure VM. Verified that containers run and that `which docker-proxy` returns `/usr/bin/docker-proxy` as expected.

moby-engine: add back-compat symlink for docker-proxy

---

SPECS/cri-o/CVE-2023-44487.patch
SPECS/cri-o/CVE-2024-21626.patch
SPECS/cri-o/cri-o.spec

---
Patch cri-o for CVE-2024-21626 and patch additional file for CVE-2023-44487
- Patch cri-o for CVE-2024-21626 and patch additional file for CVE-2023-44487
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-21626
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=561328&view=results

Add patch in cri-o for CVE-2024-21626

---

.pipelines/containerSourceData/scripts/BuildBaseContainers.sh
.pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh

---
This PR updates the Build Containers scripts to use docker buildx.
- .pipelines/containerSourceData/scripts/BuildBaseContainers.sh
- .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
**NO**
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=561228&view=results

use docker buildx

---

toolkit/tools/internal/resources/assets/grub2/grub

---
We need to escape the '$' character in /etc/default/grub for the $kernelopts variable itself to render into the generated grub.cfg
- escape '$' in /etc/default/grub
NO
- pipelines started

fix: address missing kernelopts in generated grub.cfg

---

toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/imager/imager.go
toolkit/tools/internal/safechroot/safechroot.go
toolkit/tools/internal/safemount/safemount_test.go
toolkit/tools/pkg/imagecustomizerlib/imageutils.go
toolkit/tools/pkg/isomakerlib/isomaker.go

1. Don't call `sfdisk --delete` on disks that are known to be empty.
2. Don't call `gpgconf --kill` in chroot contexts that don't have the default mounts (e.g. /proc) since the call won't work.
3. Don't log the stderr of `dd` and `mkisofs` to WARN since those commands use stderr for information messages.
---
NO
- Ran UTs.
- Manually built and tested installer ISO.

Image Customizer: Cleanup warning messages.

---

toolkit/tools/imagegen/diskutils/diskutils.go

---
Issues are reported when detaching the loopback devices where it will timeout before the detach is completely done.
```
2024/05/01 23:02:48 image customization failed: timed out waiting for loopback device (/dev/loop36) for disk (/customizer/image.raw) to close
```
The change increments the number of attempts which also increases the delay with each and overall timeout.
**YES/**NO****
Local testing, no repro anymore with the change.

Image Customizer: Increase timeout for loopback detach

---

SPECS/python-jwt/python-jwt.signatures.json
SPECS/python-jwt/python-jwt.spec
cgmanifest.json

---
Upgrading `python-jwt` from `2.4.0` to `2.8.0` for 3.0
- Upgrading `python-jwt` from `2.4.0` to `2.8.0`
NO
- Pipeline build id: 562003

Upgrading `python-jwt` from `2.4.0` to `2.8.0`

---

SPECS/php/php.signatures.json
SPECS/php/php.spec
cgmanifest.json

---
Upgrade php from 8.1.22 to 8.1.28 to fix CVE-2024-2756 and CVE-2024-3096
- Upgrade php from 8.1.22 to 8.1.28 to fix CVE-2024-2756 and CVE-2024-3096
- Update BuildRequires, libpq is now provided by postgresql
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-2756
- https://nvd.nist.gov/vuln/detail/CVE-2024-3096
- Pipeline build id: 561390

Upgrade php to 8.1.28 to fix CVE-2024-2756, CVE-2024-3096

---

SPECS/kata-containers-cc/kata-containers-cc.signatures.json
SPECS/kata-containers-cc/kata-containers-cc.spec
SPECS/kata-containers/kata-containers.signatures.json
SPECS/kata-containers/kata-containers.spec
SPECS/kata-packages-uvm/kata-packages-uvm.spec
cgmanifest.json

---
Upgrade kata and kata-cc to [3.2.0.azl1](https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl1)
- kata-containers
- kata-containers-cc
- kata-packages-uvm
**NO**
- kata upgrade: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=562013&view=results
- buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=562036&view=results
- image build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=562229&view=results
- test: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=562258&view=results

Kata: uprade to 3.2.0.azl1

---

SPECS/keda/keda.signatures.json
SPECS/keda/keda.spec
cgmanifest.json

---
This PR will upgrade the Kubernetes Event Driven Autoscaling package from 2.4.0 to 2.14.0 
The only notable change (packaging-wise) is that this adds the new binary `keda-admission-webhooks` which was added in [2.10.0](https://github.com/kedacore/keda/releases#:~:text=New%20admission%20webhook%20for%20validating%20ScaledObjects)
- Upgrade keda from 2.4.0 to 2.14.0
- Add the keda-webhook-admissions binary to Keda rpm
NO
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=564289&view=results
- Local build

keda: upgrade from 2.4.0 to 2.14.0

---

toolkit/tools/internal/file/file.go
toolkit/tools/internal/file/file_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeboot.go

In Azure Linux 3.0, the `mkinitrd` script was removed in favor of using `dracut` directly. This change fixes the image customizer tool so that it uses the appropriate tool for updating the initramfs file depending on the base image being used.
---
---
NO

Image Customizer: Handle removal of mkinitrd in 3.0.

---

toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
toolkit/tools/pkg/imagecustomizerlib/testdata/install-package-disk-space.yaml

The `tdnf` tool reports a high-level error message to `stderr`. This change ensures that this error message is included in the image customizer's error message.
However, when `tdnf` hits an installation failure due to insufficient disk space, the error message is the unhelpful and overly generic message of "rpm transaction failed". Fortunately, `tdnf` does report more details in `stdout`. This change detects when `tdnf` has added RPM transaction error details to `stdout` and logs them as WARN messages.
---
NO

Image Customizer: Improve package install error messages.

---

SPECS/python3-pytest-asyncio/python3-pytest-asyncio.signatures.json
SPECS/python3-pytest-asyncio/python3-pytest-asyncio.spec
cgmanifest.json

---
Upgrade python3-pytest-asyncio to 0.23.6
- Upgrade python3-pytest-asyncio to 0.23.6
- Change the source file link
**NO**
- Local build: 
- Pipeline build id: [565288](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565288&view=results)

python3-pytest-asyncio: upgrade to 0.23.6

---

.pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh

---
This PR updates the distroless golden container build script to use the legacy builder in docker builds. There is an unidentified issue in the ADO pipeline that is halting the build process when executing the docker build for distroless golden containers. This issue started after the upgrade of moby-engine from `20.10.27` to `24.0.9`.
- .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
**NO**
- ADO Build_Golden_Containers_AMD64 pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565692&view=results
- ADO Build_Golden_Containers_ARM64 pipeline run: …

Use legacy builder for distroless golden containers

---

SPECS/python-cstruct/python-cstruct.spec

---
Package test for python-cstruct is failing on 3.0-dev, this PR resolves the test failure.
- Add missing python dependency to check section via pip install
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565236&view=results

PTest Fix for python-cstruct

---

.pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh

---
Cherry picking change from `main` into `fasttrack/2.0` to help with building the distroless golden containers.
- .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
**NO**
ADO bug to track this issue: https://microsoft.visualstudio.com/OS/_workitems/edit/50674863

Use legacy builder for distroless golden containers (#9041)

---

toolkit/tools/internal/packagerepo/repoutils/repoquery.go

---
There is a window when we do not have a fully released repo, but we DO have a preview repo, available. By default the worker chroot will look to the base repo for packages. The `precacher` tool needs to install `dnf-utils` to get the `repoquery` tool. In this situation that package is only available as a preview package. We need the precacher tool to be able to check more places for repoquery.
By default we should continue to use the default repo in the chroot, but now there is a fallback to enables all the other repos the user passes if that install fails.
- Allow `precacher` to install `repoquery` from `REPO_LIST` sources (like preview).
**NO**
- …

Fall back to using all repo files in precacher for repoquery

---

SPECS/python-editables/python-editables.spec

---
When python-editables was added to 3.0-dev the PTest was not passing. This PR resolves the issue
- Add %with_check for pytest dep
- Add iniconfig as pip install for test
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=565948&view=results

PTest Fix for python-editables

---

SPECS/python-flit/python-flit.spec

---
The PTest for python-flit is failing on 3.0-dev due to missing dependencies. This PR resolves the issue.
- add missing pyyaml install to 
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566089&view=results

PTest fix for python-flit

---

SPECS/python-filelock/python-filelock.signatures.json
SPECS/python-filelock/python-filelock.spec
cgmanifest.json

---
Upgrading `python-filelock` to `3.13.4`
- Upgrading `python-filelock` to `3.13.4`
NO
- Pipeline build id: 566032

Upgrading `python-filelock` to `3.14.0`

---

SPECS/azurelinux-release/90-default.preset
SPECS/azurelinux-release/azurelinux-release.signatures.json
SPECS/azurelinux-release/azurelinux-release.spec

---
In Azure Linux 3.0 the systemd's default behavior was overridden by introducing default presets. In this PR we add ephemeral-disk-warning.service to the default systemd presets to enable it during boot.
- fix ephemeral-disk-warning.service not running on boot
**NO**
- Pipeline build id: [BuddyBuild](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566424&view=results)

fix: ephemeral-disk-warning service not running on boot

---

toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

Create debug logs for reporting the free disk space after OS customization, including after errors. In addition, report a warning if the free space on a disk/partition is below a certain threshold.
---
NO

Image Customizer: Warn on low free disk space.

---

.pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh

---
This PR updates the distroless golden container build script to use the legacy builder in docker builds. There is an unidentified issue in the ADO pipeline that is halting the build process when executing the docker build for distroless golden containers. This issue started after the upgrade of moby-engine from 20.10.27 to 24.0.9.
Corresponding `main` branch PR: https://github.com/microsoft/azurelinux/pull/9041
ADO bug to track this issue: https://microsoft.visualstudio.com/OS/_workitems/edit/50674863
- .pipelines/containerSourceData/scripts/BuildGoldenDistrolessContainer.sh
**NO**
ADO Build_Golden_Containers_AMD64 pipeline …

use DOCKER_BUILDKIT=0

---

.github/CODEOWNERS

---
Adding the missing group from #8859.
No.
- Local tests with `.gitignore`.

Fixed `CODEOWNERS` group for certificates.

---

SPECS/python-chardet/chardetect.1
SPECS/python-chardet/python-chardet.signatures.json
SPECS/python-chardet/python-chardet.spec
cgmanifest.json

---
python-chardet: upgrade to 5.2.0
- Upgrade python-chardet to 5.2.0
- Add chardetect.1 file as another source of the spec
**NO**
- Local build
- Pipeline build id: [566881](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566881&view=results)

python-chardet: upgrade to 5.2.0

---

SPECS/dracut/0010-fix-remove-microcode-check-based-on-CONFIG_MICROCODE_AMD-INTEL.patch
SPECS/dracut/dracut.spec

---
When installing a new kernel, dracut spits out this message while generating initramfs: "dracut: Disabling early microcode, because kernel does not support it. CONFIG_MICROCODE_(AMD|INTEL)!=y"
However, these config options were removed in commit e6bcfdd "x86/microcode: Hide the config knob". Additionally, the kernel enables "CONFIG_MICROCODE" https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/e6bcfdd75d53390a67f67237f4eafc77d9772056
Therefore, take upstream dracut patch ([6c80408](https://github.com/dracutdevs/dracut/commit/6c80408c8644a0add1907b0593eb83f90d6247b1)) which fixes microcode check.
- Patch microcode output check based on CONFIG_MICROCODE_AMD/INTEL
**NO**
- …

dracut: Patch microcode output check based on CONFIG_MICROCODE_AMD/INTEL

---

SPECS/systemd/10-console-messages.conf
SPECS/systemd/systemd.signatures.json
SPECS/systemd/systemd.spec
toolkit/resources/imageconfigs/additionalfiles/iso_initrd/10-console-messages.conf
toolkit/resources/imageconfigs/iso_initrd.json
toolkit/resources/imageconfigs/iso_initrd_arm64.json

---
During normal use, many low level debug messages are printing to the console which is causing usability issues for the user. To deal with this, install a sysctl configuration to run on boot which will change the default kernel printk value to "4 4 1 7".
This PR is based off of findings from: https://github.com/microsoft/azurelinux/pull/8331
and expands this [PR's ](https://github.com/microsoft/azurelinux/blob/3.0-dev/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/10-console-messages.conf)changes from specifically iso images to all images 
- Supply 10-console-messages.conf sysctl to lower the default kernel messages to the console
**NO**
- …

systemd: suppress debug messages to console by default

---

SPECS/ceph/CVE-2021-24032.patch
SPECS/ceph/CVE-2021-28361.patch
SPECS/ceph/CVE-2022-3650.patch
SPECS/ceph/CVE-2022-3854.patch
SPECS/ceph/ceph.spec

---
Patch ceph to fix CVE-2021-24032, CVE-2021-28361, CVE-2022-3650, CVE-2022-3854
Explicitly disable seastar (it was implicit before) to ensure disputed CVEs don't sneak in.
- Patch ceph to fix CVE-2021-24032, CVE-2021-28361, CVE-2022-3650, CVE-2022-3854
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-24032
- https://nvd.nist.gov/vuln/detail/CVE-2021-28361
- https://nvd.nist.gov/vuln/detail/CVE-2022-3650
- https://nvd.nist.gov/vuln/detail/CVE-2022-3854
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=567500&view=results

ceph: patch multiple CVEs

---

toolkit/tools/imagecustomizer/README.md

In the Image Customizer README.md file, add a section that documents things to avoid in the user's custom scripts. In particular, it warns that chroot doesn't protect the build host kernel from being changed by the scripts.
---
NO
- n/a

Image Customizer: Improve docs for chroot.

---

SPECS-EXTENDED/facter/facter.signatures.json
SPECS-EXTENDED/facter/facter.spec
cgmanifest.json

Minimum version of facter that supports Mariner facts.
https://puppet.atlassian.net/browse/FACT-3142
---
The version of facter that currently ships with Mariner does not set the correct facts. Bumping the version to the minimum supported version that will expose the correct Mariner facts for puppet
- Bump version of facter to 3.2.13
- 
**NO**
- Was hoping to use buddy build system to test

Update facter version to support Mariner

---

SPECS/python-virt-firmware/python-virt-firmware.signatures.json
SPECS/python-virt-firmware/python-virt-firmware.spec
cgmanifest.json

---
python-virt-firmware upgrade to 24.4 to unblock edk2 build
latest ver: https://src.fedoraproject.org/rpms/python-virt-firmware/blob/f40/f/python-virt-firmware.spec 
python-virt-firmware upgrade to 24.4 to unblock edk2 build
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=569960&view=results

python-virt-firmware: package upgrade to 24.4

---

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

Fix a crash for when an ISO is generated from an image file (e.g. vhdx) and no changes are made to the OS.
---
NO

Image Customizer: Fix ISO gen without changes.

---

SPECS/graphviz/CVE-2023-46045.patch
SPECS/graphviz/graphviz.spec
SPECS/python-sphinx/python-sphinx.spec

---
- graphviz: address CVE-2023-46045
- Switch to autosetup to actually fix CVE-2020-18032
- Address CVE-2023-46045 & CVE-2020-18032
**NO**
- 
- https://nvd.nist.gov/vuln/detail/CVE-2020-18032
- https://nvd.nist.gov/vuln/detail/CVE-2023-46045
- Pipeline build id: [PR-9093](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=569573&view=results)

graphviz: address CVE-2023-46045 & CVE-2020-18032

---

SPECS/pytorch/CVE-2024-27318.patch
SPECS/pytorch/pytorch.spec

---
Add patch for CVE-2024-27318
References:
https://github.com/onnx/onnx/issues/6028
https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.16.0
https://github.com/onnx/onnx/pull/5917
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-27318
NOTE: The amd64 test is failing for package libguestfs, not related to pytorch.
=================
INFO[2791][scheduler] Failed SRPMs tests:                          
INFO[2791][scheduler] --> libguestfs-1.44.0-19.cm2.src.rpm , for details see: /mnt/vss/_work/1/s/build/logs/pkggen/rpmbuilding/libguestfs-1.44.0-19.cm2.src.rpm.test.log 
=================

pytorch: Add patch for CVE-2024-27318

---

toolkit/scripts/toolchain.mk

`make toolchain && make compress-toolchain-final-rpms` will create out/toolchain_final_extracted_rpms.tar.gz.
This may be used with future calls to `make ... TOOLCHAIN_ARCHIVE=toolchain_final_extracted_rpms.tar.gz` to hydrate a toolchain.
---
make toolchain && make compress-toolchain-final-rpms will create out/toolchain_final_extracted_rpms.tar.gz.
This command facilitates creating a toolchain archive.
- Change
- Change
- Change
**YES/NO**
- #xxxx

Add new compress-toolchain-final-rpms target to makefile

---

SPECS/selinux-policy/0043-cloudinit-Add-support-for-cloud-init-growpart.patch
SPECS/selinux-policy/booleans_targeted.conf
SPECS/selinux-policy/selinux-policy.signatures.json
SPECS/selinux-policy/selinux-policy.spec

---
Add SELinux policy rules to allow cloud-init growpart to work.
- Add SELinux policy rules to allow cloud-init growpart to work.
**NO**
- Pipeline build id: 569807
- Local test
- SELinux BVT

selinux-policy: Add fix for cloud-init growpart.

---

toolkit/tools/depsearch/depsearch.go
toolkit/tools/pkg/depsearch/depsearch.go

---
refactor depsearch into tool and utils
- refactor depsearch into tool and utils
- part of series of similar changes across the toolkit
**NO**
- Built package successfully with REBUILD_TOOLS=y
- Built all tools (make go-tools REBUILD_TOOLS=y)
- Ran depsearch tool to make sure it runs

refactor depsearch

---

toolkit/tools/internal/tdnf/tdnf.go
toolkit/tools/internal/tdnf/tdnf_test.go

---
Fixing a but where the `tdnf.InstallPackageRegex` regular expression was filtering out packages with a non-zero epoch.
Opening against fast-track to fix test triggering in the fast-track pipelines.
No.
- Local tooling tests.
- Image build tests by @anphel31.

Fixing epoch matching in 'InstallPackageRegex'.

---

toolkit/tools/internal/tdnf/tdnf.go
toolkit/tools/internal/tdnf/tdnf_test.go

---
Cherry-pick of 2.0's #9131.
Fixing a but where the `tdnf.InstallPackageRegex` regular expression was filtering out packages with a non-zero epoch.
Opening against fast-track to fix test triggering in the fast-track pipelines.
No.
- Local tooling tests.
- Image build tests by @anphel31.

Fixing epoch matching in 'InstallPackageRegex'. (CP #9131)

---

SPECS/prometheus-adapter/CVE-2024-24786.patch
SPECS/prometheus-adapter/prometheus-adapter.spec

---
Fix CVE-2024-24786 in prometheus-adapter
**NO**
- #xxxx
- Pipeline build id: [571039](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=571039&view=results)

prometheus-adapter: Fix CVE-2024-24786

---

SPECS/python-repoze-lru/python-repoze-lru.spec

---
Fix the package test for python-repoze-lru for 3.0 with python 3.12
- Call test script directly through setup.py
- remove redef of sitelibs macro
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=570560&view=results

Fix PTest for python-repoze-lru

---

SPECS/kubevirt/CVE-2024-24786.patch
SPECS/kubevirt/kubevirt.spec

---
Fix CVE-2024-24786 in kubevirt
**NO**
- #xxxx
- PR Check

kubevirt: Add patch for CVE-2024-24786

---

SPECS/iperf3/iperf3.signatures.json
SPECS/iperf3/iperf3.spec
cgmanifest.json

---
- iperf3: upgrade 3.14 -> 3.17 to address CVE-2024-26306
- Bump version to 3.17
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-26306
- Pipeline build id: [PR-9119](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=570706&view=results)

iperf3: upgrade 3.14 -> 3.17 to address CVE-2024-26306

---

SPECS/msft-golang/msft-golang.signatures.json
SPECS/msft-golang/msft-golang.spec
cgmanifest.json

---
Bump version 1.22.2 -> 1.22.3 to address CVE
Changelog: https://go.dev/doc/devel/release#go1.22.0
- Introduce function to simplify bootstrapping
**NO**
- NA
- Pipeline build id: [PR-9108](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=570302&view=results)

msft-golang: upgrade 1.22.2 -> 1.22.3 to address CVE-2024-24787 & CVE-2024-24788

---

toolkit/Makefile
toolkit/docs/building/building.md
toolkit/scripts/precache.mk

Allow a custom path to be specified for the rpm snapshot summary file.
---
`make rpm_snapshot ...` generates the RPMs snapshot under a specific folder, with a hard coded name (rpms_snapshot.json) and `make pre-cache ...` refers to that generated snapshot file without any consideration for a custom file path/name. This is an inconvenience for builds that run on different platform architecture, that we often prefer to have the arch as part of the file name.
This PR allows setting PRECACHER_SNAPSHOT parameter for `make pre-cache`.
- Change
- Change
- Change
**YES/NO**
Tested in Azure Linux derivative image, where rpms snapshot is …

Allow a custom path to be specified for custom snapshot for the pre-cacher

---

SPECS-EXTENDED/libdwarf/libdwarf.signatures.json
SPECS/libdwarf/libdwarf.signatures.json
SPECS/libdwarf/libdwarf.spec
SPECS/libdwarf/libdwarf_skip_test.patch
cgmanifest.json

---
This PR cherry-picks https://github.com/microsoft/azurelinux/pull/6827 to 3.0-dev branch.
- Change
- Change
- Change
**YES/NO**
- #xxxx
- Pipeline build id: [571543](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=571543&view=results)

[CHERRY-PICK] Upgrade and move libdwarf from extended to core (#6827)

---

SPECS/cloud-init/Add-Network-Interface-Renaming-Support-for-CAPM3-Met.patch
SPECS/cloud-init/cloud-init.spec

---
Add patch to add network interface renaming support for CAPM3 Met.
This patch is being attached from our internal afo-packages for now, however, we want it to be applied to AZL directly.
- Add patch to add network interface renaming support for CAPM3 Met.
- Make changes to the pkg tests to work with the patch introduced
**NO**
- #xxxx
- Pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566667&view=results

Add patch to add network interface renaming support for CAPM3 Met

---

SPECS/postgresql/postgresql.signatures.json
SPECS/postgresql/postgresql.spec
cgmanifest.json

---
postgresql: update to v16.3 to fix CVE-2024-4317
- postgresql: update to v16.3 to fix CVE-2024-4317
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-4317
- Local build
- Successful buddyBuild, with unrelated error in install phase: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=573375&view=results

postgresql: update to v16.3 to fix CVE-2024-4317

---

SPECS/cmake/cmake.spec
SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
SPECS/cyrus-sasl/cyrus-sasl.spec
SPECS/ethtool/ethtool.spec
SPECS/libdb/libdb.spec
SPECS/librdkafka/librdkafka.spec
SPECS/lmdb/lmdb.spec
SPECS/qemu/qemu.spec
SPECS/userspace-rcu/userspace-rcu.spec
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
As part of https://github.com/microsoft/azurelinux/pull/8776 we would like to disable documentation on specific size-constrained images. However, there is a complication: many packages do not use the `%license` tag in their `%files` section to accurately tag license files. If such an image was distributed it would run afoul of open source licensing requirements (ie it would not include the required license files with the corresponding binary files). A tool was created that attempts to detect these cases (early draft here: https://github.com/microsoft/azurelinux/pull/9060) and will be integrated into the normal build flow in the future.
In the mean time, to unblock the …

Sanitize licenses in core image packages

---

SPECS/jasper/CVE-2024-31744.patch
SPECS/jasper/jasper.spec

---
jasper: patch CVE-2024-31744
- jasper: patch CVE-2024-31744
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-31744
- Local build with all tests passing
- Successful buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=573496&view=results

jasper: patch CVE-2024-31744

---

SPECS/python-pytest-flakes/python-pytest-flakes.spec

---
The package test for python-pytest-flakes was not running properly due to a missing dependency on pip
- Add pip as check dependency
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=573394&view=results

PTest Fix for python-pytest-flakes Package

---

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
toolkit/tools/internal/retry/retry.go
toolkit/tools/pkg/downloader/downloader.go
toolkit/tools/precacher/precacher.go
toolkit/tools/srpmpacker/srpmpacker.go

---
Cherry-pick of 2.0's #7445.
We continue to intermittently see HTTP 502 errors (Bad Gateway) when TDNF downloads packages from packages.microsoft.com, usually in build pipelines. This PR introduces granular retry logic for that specific failure case. (We can't retry on any HTTP error, as 404 is an expected error that shows up in normal execution.)
- Update the `rpmrepcloner` to inspect stderr on TDNF download failure. If an error string indicating a 5XX error is found, then we retry with exponential backoff.
- Unified the retry logic for network downloads.
- Removed outdated logic from `rpmrepocloner` looking for errors related with the `toybox` package.
No.
- #7373
- #7445
- …

Specialcased 5XX errors during package downloads. (CP: #7445)

---

SPECS-EXTENDED/gdal/gdal.spec
SPECS-EXTENDED/netcdf/netcdf.spec

---
Remove the explicit version in build/runtime dependency on hdf5 to unblock  the arm64 build.
- [Remove newly added explicit version dependencies in gdal and netcdf](https://github.com/microsoft/azurelinux/commit/44ebcfbb4c12e27433203a5fddea0cad9368f3dc)
**NO**
- Build break.
- n/a
- Pipeline buddy build.

Remove newly added explicit version dependencies in gdal and netcdf.

---

SPECS/ruby/ruby.spec
SPECS/rubygem-rexml/add-support-for-old-strscan.patch
SPECS/rubygem-rexml/rubygem-rexml.signatures.json
SPECS/rubygem-rexml/rubygem-rexml.spec
cgmanifest.json

---
rubygem-rexml: fix CVE-2024-35176
- rubygem-rexml: fix CVE-2024-35176
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-35176
- Local build
- Successful buddy build, error unrelated to the change: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=574806&view=results

rubygem-rexml: fix CVE-2024-35176

---

toolkit/tools/internal/grub/commands.go
toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
toolkit/tools/pkg/imagecustomizerlib/bootcustomizer_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/defaultgrubutils.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

Fix the handling of the grub config file when provisioning verity on images that use grub-mkconfig (e.g. Azure Linux 3.0).
Known issues: Network provisioning fails during boot on verity enabled Azure Linux 3.0 images.
---
NO
- Added UTs.

Image Customizer: Verity on 3.0 images.

---

SPECS/libvirt/CVE-2024-4418.patch
SPECS/libvirt/libvirt.spec

Add patch to fix CVE-2024-4418
---
Fix patch CVE-2024-4418
- CVE-2024-4418
**NO**
- https://bugzilla.redhat.com/show_bug.cgi?id=2278616
- https://nvd.nist.gov/vuln/detail/CVE-2024-4418
- Pipeline build id: [574211](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=574211&view=results)

libvirt:  Patch for CVE-2024-4418

---

SPECS/gnutls/gnutls.signatures.json
SPECS/gnutls/gnutls.spec
cgmanifest.json

---
gnutls: update to v3.8.3 to fix CVE-2024-0553
- gnutls: update to v3.8.3 to fix CVE-2024-0553
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-0553
- Local build
- Buddy build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=575547&view=results

gnutls: update to v3.8.3 to fix CVE-2024-0553

---

toolkit/tools/imagecustomizer/README.md
toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
toolkit/tools/imagecustomizer/container/build-mic-container.sh
toolkit/tools/imagecustomizer/container/run-mic-container.sh

1. Add `parted` to the list of prerequisites.
2. Add list of Mariner 2.0 prerequisites to README.
3. Fix prereqs list in Dockerfile.
4. In `build-mic-container.sh`, use `imagecustomizer` binary location that is generated by running `make go-imagecustomizer REBUILD_TOOLS=y`.
5. Remove use of `sudo` from scripts.
6. Fix `imagecustomizer` container path so that version is treated as a tag and not a part of the path.
NO

Image Customizer: Fix prereqs list + container fixes.

---

.pipelines/containerSourceData/kubevirt/Dockerfile-kubevirt-virt-launcher
SPECS/cryptsetup/cryptsetup.spec

---
Bug: https://microsoft.visualstudio.com/OS/_workitems/edit/50691749
Kubevirt golden container build fails with the following error:
```
#11 [7/8] RUN cp /usr/share/kube-virt/virt-launcher/nsswitch.conf /etc/
#11 0.283 cp: cannot stat '/usr/share/kube-virt/virt-launcher/nsswitch.conf': No such file or directory
#11 ERROR: executor failed running [/bin/sh -c cp /usr/share/kube-virt/virt-launcher/nsswitch.conf /etc/]: exit code: 1
------
> [7/8] RUN cp /usr/share/kube-virt/virt-launcher/nsswitch.conf /etc/:
#11 0.283 cp: cannot stat '/usr/share/kube-virt/virt-launcher/nsswitch.conf': No such file or directory
------
dockerfile:43 …
```

Removing nsswitch.conf from Dockerfile for building Kubevirt Golden Containers

---

toolkit/tools/imagecustomizer/docs/building-packages.md
toolkit/tools/imagecustomizer/docs/cli.md

Add a quick guide for how to build custom packages for Azure Linux. This guide uses a normal Azure Linux core container and directly uses `rpmbuild`, instead of using the Azure Linux toolkit, since it is a lot simpler.
---
NO
n/a

Image Customizer: Add doc for building custom packages.

---

toolkit/tools/internal/network/network.go

Attempt to mitigate TLS handshake timeouts we've seen by increasing the timeout from the default 10 seconds to 30 seconds.
---
Two changes:
1- Fixes the log message in the retry patch to use the correct error variable.
2- Increases TLS handshake timeouts from the golang default (10 seconds) to 30 seconds; this is a speculative attempt to mitigate the timeouts we've seen from [packages.microsoft.com](http://packages.microsoft.com/)
- Change
- Change
- Change
**NO**
- #xxxx
This change has been working in one of the Azure Linux derivative's pipeline for a while and it addressed the issue …

Increase TLS handshake timeout

---

SPECS/moby-compose/CVE-2023-2253.patch
SPECS/moby-compose/CVE-2024-23650.patch
SPECS/moby-compose/CVE-2024-24786.patch
SPECS/moby-compose/moby-compose.spec

---
Addresses CVE-2024-24786, CVE-2024-23650, CVE-2023-2253 for moby-compose
- CVE-2024-23650
- CVE-2023-2253
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-23650
- https://nvd.nist.gov/vuln/detail/CVE-2023-2253
- local build
- Pipeline build id: [577555](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=577555)

moby-compose: Fix CVE-2024-24786, CVE-2024-23650, CVE-2023-2253

---

SPECS/qtbase/qtbase.signatures.json
SPECS/qtbase/qtbase.spec
cgmanifest.json

---
qtbase: upgrade to version 6.6.2 to fix CVE-2023-51714
- qtbase: upgrade to version 6.6.2 to fix CVE-2023-51714
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-51714
- Local build
- Successfully built buddy build pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=577491&view=results
- Test passed after fix:

qtbase: upgrade to version 6.6.2 to fix CVE-2023-51714

---

toolkit/docs/building/building.md
toolkit/scripts/pkggen.mk

---
We need a make option for hydrating SRPMs, similar to hydrating the RPMS. Hydrating the SRPMS is one of the steps in reusing the prebuilt/LKS SRPM artifacts to populate the local cache.
**NO**
Running `make hydrate-srpms PACKAGE_ARCHIVE=...`  generates the desired output result.

Add hydrate-srpms option to make

---

SPECS/memcached/memcached.signatures.json
SPECS/memcached/memcached.spec
cgmanifest.json

---
Upgrading `memcached` to `1.6.27` & splitting the service into a subpackage. Upgrade addresses CVEs & the split is to make the base package smaller for our containers.
- Updating `memcached` to `1.6.27`
- Separating out service functionality into a subpackage
- Fixes CVE-2023-46853
- Fixes CVE-2023-46852
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-46853
- https://nvd.nist.gov/vuln/detail/CVE-2023-46852
- Pipeline build id: 574804

Upgrading `memcached` to `1.6.27` & splitting the service into a subpackage

---

SPECS/rubygem-rexml/CVE-2024-35176.patch
SPECS/rubygem-rexml/rubygem-rexml.spec

---
Add upstream patch for rubygem-rexml CVE-2024-35176
- Add upstream [patch](https://github.com/ruby/rexml/pull/126/files#diff-93b40740603234e79b1d9be5ff2b3af80f3964a146183cbd698f14d7336726e9) for rubygem-rexml CVE-2024-35176
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-35176
- Pipeline build id: local package build with RUN_CHECK=y
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578305&view=results

add patch for rubygem-rexml CVE-2024-35176

---

SPECS/dracut/0011-Remove-reference-to-kernel-module-zlib-in-fips-module.patch
SPECS/dracut/dracut.spec

---
In 3.0-dev, Dracut will fail early during initramfs regeneration in the case that a kernel module is not found. This presents a problem as the dracut-fips module is still searching for zlib, which has long since been deprecated as a buildable module in kernel since v4.6. 
Remove reference to zlib from dracut-fips module setup to address pedantic initramfs regeneration behavior.
- Remove reference to zlib from dracut-fips module
NO
- See that initramfs is successfully built with this version of dracut in fips images (core-fips.json)

dracut: Remove reference to zlib in dracut-fips module

---

SPECS/libkcapi/fipshmac-openssl.sh
SPECS/libkcapi/libkcapi.signatures.json
SPECS/libkcapi/libkcapi.spec
SPECS/libkcapi/sha512hmac-openssl.sh

---
libkcapi v1.5.0 comes with a breaking change with regards to dracut, fips boot. https://www.chronox.de/libkcapi/releases/1.5.0/index.html
> move all sha* applications to the libexec directory to allow them to coexist with other packages sha* applications - the caller is expected to make a symlink to them
I also observe in the build that, instead of producing sha*hmac bins, all functionality is now put in libkapi-hasher.
These changes cause sha512hmac to go missing from the perspective of Dracut, who expects to find it in the PATH. Furthermore, due to how our spec file was written for 1.3.1, the soft links 1.5.0 produces in libexec …

libkcapi: Package proper measurements & binary aliases in libkcapi for fips boot

---

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
Our delta toolchain builds were skipping a rebuild of a spec, which needed to build more than once in the toolchain phase (for example `pam` or `selinux`). Building more than once is required, if we couldn't provide the package with all of its required build-time dependencies, because these dependencies required that package to build them. Later builds are expected to run with more/all build-time dependencies where the final build should have all of them.
During the delta toolchain build, we would build the spec for the first time but later attempts would be skipped, because we'd check for the presence of the RPM files produced by the built spec. Since they were all present from …

Fixing toolchain rebuilds for delta builds. (CP: #8680)

---

SPECS/ruby/CVE-2024-35176.patch
SPECS/ruby/ruby.spec

---
add patch for ruby CVE-2024-35176
- Add upstream [patch](https://github.com/ruby/rexml/pull/126/files#diff-93b40740603234e79b1d9be5ff2b3af80f3964a146183cbd698f14d7336726e9) for ruby CVE-2024-35176
/NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-35176
- buddy build: [578929](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578929&view=results)

add patch for ruby CVE-2024-35176

---

SPECS/cryptsetup/cryptsetup.spec

---
Fix package build error seen in 3.0-dev.
```
time="2024-05-29T12:35:52Z" level=info msg="Failed SRPMs:" 
time="2024-05-29T12:35:52Z" level=info msg="--> cryptsetup-2.4.3-6.azl3.src.rpm , error: exit status 2, for details see: /mnt/vss/_work/1/s/outDir/build/logs/pkggen/rpmbuilding/cryptsetup-2.4.3-6.azl3.src.rpm.log" 
time="2024-05-29T12:35:52Z" level=info msg="--> perl-Net-SSLeay-1.92-3.azl3.src.rpm , error: exit status 2, for details see: /mnt/vss/_work/1/s/outDir/build/logs/pkggen/rpmbuilding/perl-Net-SSLeay-1.92-3.azl3.src.rpm.log" 
time="2024-05-29T10:03:25Z" level=debug msg="RPM build errors:"
time="2024-05-29T10:03:25Z" …
```

cryptsetup: fix package build error

---

SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec

---
Fix build break in `perl-Net-SSLeay` package:
```
time="2024-05-29T09:09:40Z" level=debug msg="*** Could not find OpenSSL"
time="2024-05-29T09:09:40Z" level=debug msg="    If it's already installed, please set the OPENSSL_PREFIX environment"
time="2024-05-29T09:09:40Z" level=debug msg="    variable accordingly. If it isn't installed yet, get the latest version"
time="2024-05-29T09:09:40Z" level=debug msg="    from http://www.openssl.org/."
```
- Change `perl-Net-SSLeay` package
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=579005&view=results

perl-net-ssleay: fix build break from missing openssl package

---

toolkit/tools/imagecustomizer/docs/iso.md
toolkit/tools/pkg/imagecustomizerlib/testdata/cloud-init-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/cloud-init-iso-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/files/cloud-init/meta-data
toolkit/tools/pkg/imagecustomizerlib/testdata/files/cloud-init/network-config
toolkit/tools/pkg/imagecustomizerlib/testdata/files/cloud-init/user-data

There is a behavior in cloud-init where if you use the `seedfrom` arg on the kernel command-line, then the `network-config` file is ignored. So, change the example ISO configs that embed cloud-init configs to a solution that doesn't ignore the `network-config` file.
Also, add a couple of test ISO config files.
---
NO
n/a

Image Customizer: Fix cloud-init ISO examples.

---

toolkit/tools/pkg/imagecustomizerlib/extractpartitions_test.go

Image Customizer: Fix TestCustomizeImageNopShrink test.

---

toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils.go

Currently, when the image customizer disables SELinux in an image it doesn't bother modifying the `/etc/selinux/config` file and instead only modifies the kernel command-line args. While this is technically fine, it is confusing for the user. So, this change fixes this so that `/etc/selinux/config` is kept in sync with the kernel command-line args.
---
NO

Image Customizer: Modify /etc/selinux/config on SELinux disable.

---

toolkit/scripts/setuplkgtoolchain.sh

---
Our `setuplkgtoolchain.sh` script uses `uname -p` which is non-portable and does not work in `azl3`. This change updates it to use `uname -m` which is the portable way to get the same information.
- Update to use `uname -m`.
**NO**
- Locally tested that this works properly on `azl3` and `azl2`.

setuplkgtoolchain: use uname -m instead of uname -p to get processor

---

SPECS/fluent-bit/CVE-2024-34250.patch
SPECS/fluent-bit/fluent-bit.spec

---
Fix CVE-2024-34250 by backporting the fix https://github.com/bytecodealliance/wasm-micro-runtime/pull/3352
- Fix CVE-2024-34250 with a patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-34250
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=578695&view=results

Fix fluent-bit CVE-2024-34250 with a patch

---

toolkit/tools/imagecustomizer/container/build-mic-container.sh
toolkit/tools/imagecustomizer/container/run-mic-container.sh

Change the `build-mic-container.sh` script to take the full container tag as a single param instead of as individual components. This makes the script more flexible and easier to use.
---
NO
- Manually built and ran Image Customizer container.

Image Customizer: Simplify container build script.

---

toolkit/scripts/containerized-build/resources/setup_functions.sh

---
containerized-rpmbuild: enable azurelinux-official-base for 3.0
- containerized-rpmbuild: enable azurelinux-official-base for 3.0
**NO**
- Local build: could install packages from `azurelinux-official-base`

containerized-rpmbuild: enable azurelinux-official-base for 3.0

---

toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
toolkit/tools/pkg/imagecustomizerlib/defaultgrubutils.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go

---
This change enables the generation of iso images from 3.0 Azure Linux images:
- Update dracut configuration
- Explicitly set the no host-only configuration (new dmsquash-live requirement).
- Include the `rd.live.overlay.overlayfs` kernel command line to create the overlay fs (new dmsquash-live requirement).
- Ensure pkgs required by dracut live os are installed
-  dracut live os modules require the following pkgs: squashfs-tools, tar, "device-mapper. However, the 3.0 baremetal image does not have them pre-installed. The changes in this PR will check their presence, and if any is missing, the image build will stop and report and error.
- Update grub.cfg generation
- The 3.0 …

[mic][iso] Add support for Azure Linux 3.0 images

---

toolkit/tools/internal/safechroot/safechroot.go

---
We have logic to kill several `gpgconf` agents inside our chroots. They hold open the `/dev` mount point and block graceful cleanup. 
This logic was failing for the ISO installer:
```
...
WARN[0063][liveinstaller] DEBU[0063][imager] Calling unmount on path(/installroot/dev/pts) with flags (0)
WARN[0064][liveinstaller] DEBU[0064][imager] Unmounting (/installroot/run)
WARN[0064][liveinstaller] DEBU[0064][imager] Calling unmount on path(/installroot/run) with flags (0)
WARN[0064][liveinstaller] DEBU[0064][imager] Unmounting (/installroot/sys)
WARN[0064][liveinstaller] DEBU[0064][imager] Calling unmount on path(/installroot/sys) with flags (0)
WARN[0064][liveinstaller] …
```

Check if gpgconf is in chroot, not host env, when cleaning up chroot

---

toolkit/scripts/tools.mk
toolkit/tools/internal/network/network_test.go

---
Some of the unit tests expect to validate against wall-clock time. I've noticed that on occasion the tests will stall, making these specific tests fail.
Use a local server instead of relying on github.com. This gives us much more reliable timing.
- Use a local http sever for network tests.
**NO**

Use local http server for unit tests

---

toolkit/docs/building/prerequisites-mariner.md
toolkit/docs/building/prerequisites-ubuntu.md

---
We have a number of scripts in the toolkit folder which require `jq`, so I've added this to the list of prerequisites
- Change prerequisites to include `jq`
**NO**
- N/A. documentation change

Update prerequisites with jq

---

SPECS/protobuf/protobuf.spec

---
Protobuf ptests are dropped during the package upgrade to 3.0 as the build system changed from make to cmake.
This PR brings back the ptests. Protobuf is now built with tests. The tests are enabled and passing. (refer [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580291&view=results))
Fixes the work item https://microsoft.visualstudio.com/OS/_workitems/edit/49669184
- Enable ptest using system gtest package
**NO**
- #xxxx
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580291&view=results
- Latest Buddy builds:
- With …

Enable protobuf ptest

---

SPECS/prometheus/prometheus.spec

---
Fix a build break in prometheus:
```
"cd web/ui && npm install"
"/bin/sh: line 1: npm: command not found"
```
`npm` is now provided by `nodejs-npm` instead of `nodejs`. See #9288 
- Fix a build break in prometheus
**NO**
- Local build
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582451&view=results

fix prometheus build break

---

SPECS/hvloader/hvloader.signatures.json
SPECS/hvloader/hvloader.spec

---
Update hvloader to use edk2-stable202305 submodule tag. The new submodule tag addresses multiple CVEs found in OpenSSL by upgrading to a newer version that has the CVEs fixed.
Cherry-picked and adapted from: https://github.com/microsoft/azurelinux/pull/9275
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-1292
- https://nvd.nist.gov/vuln/detail/CVE-2023-0286
- https://nvd.nist.gov/vuln/detail/CVE-2023-0215
- https://nvd.nist.gov/vuln/detail/CVE-2022-4450
- https://nvd.nist.gov/vuln/detail/CVE-2022-4304
- Pipeline build id: [582122](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582122&view=results)

fix: update hvloader to use edk2-stable202305 submodule tag

---

toolkit/tools/imagecustomizer/docs/configuration.md

The field `args` was renamed to `arguments` but the docs weren't updated.
---
NO
n/a

Image Customizer: Fix script docs.

---

SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
SPECS-SIGNED/kernel-hci-signed/kernel-hci-signed.spec
SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS/hyperv-daemons/CVE-2024-35848.nopatch
SPECS/hyperv-daemons/hyperv-daemons.signatures.json
SPECS/hyperv-daemons/hyperv-daemons.spec
SPECS/kernel-azure/config
SPECS/kernel-azure/config_aarch64
SPECS/kernel-azure/kernel-azure.signatures.json
SPECS/kernel-azure/kernel-azure.spec
SPECS/kernel-hci/config
SPECS/kernel-hci/kernel-hci.signatures.json
SPECS/kernel-hci/kernel-hci.spec
SPECS/kernel-headers/kernel-headers.signatures.json
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/CVE-2024-26900.nopatch
SPECS/kernel/config
SPECS/kernel/config_aarch64
SPECS/kernel/kernel.signatures.json
SPECS/kernel/kernel.spec
cgmanifest.json
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

5.15.157.1 introduced a failure with network hairpinning on AKS. Upgrade to 5.15.158.2 which has the commit [dceb683] reverted.
---
5.15.157.1 introduced a failure with network hairpinning on AKS. Upgrade to 5.15.158.2 which has the commit [dceb683] https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/dceb683ab87ca3666a9bb5c0158528b646faedc4 reverted.
Revert commit: https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/20e00f82783e6ba78214d49a9c266bcb6e18a2f1
- Upgrade kernel to 5.15.158.2
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/51540596
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582922&view=results
- …

Upgrade kernel to 5.15.158.2

---

SPECS/cri-o/CVE-2024-3154.patch
SPECS/cri-o/cri-o.spec

---
Fix CVE-2024-3154 in package cri-o
- Patch CVE-2024-3154 for cri-o
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-3154
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=580253&view=results
Arbitrary sytemd pod annotations can be copied to the OCI. So, it may affect the host. So, explicitly hard-code the systemd annotations to AllAllowedAnnotations file.
Ref: [[annotations: add OCI runtime specific annotations to the AllowedAnnot… · haircommander/cri-o@976ab1f (github.com)](https://github.com/haircommander/cri-o/commit/976ab1f4c916099fc1f2e6569f13e45df2f26b4f)](https://github.com/haircommander/cri-o/commit/976ab1f4c916099fc1f2e6569f13e45df2f2 …

Fix CVE-2024-3154 in package cri-o

---

toolkit/tools/imagecustomizerapi/bootloaderresettype_test.go
toolkit/tools/imagecustomizerapi/config.go
toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/dirconfig.go
toolkit/tools/imagecustomizerapi/dirconfig_test.go
toolkit/tools/imagecustomizerapi/disksize_test.go
toolkit/tools/imagecustomizerapi/identifiedpartition.go
toolkit/tools/imagecustomizerapi/identifiedpartition_test.go
toolkit/tools/imagecustomizerapi/iso.go
toolkit/tools/imagecustomizerapi/iso_test.go
toolkit/tools/imagecustomizerapi/main_test.go
toolkit/tools/imagecustomizerapi/module.go
toolkit/tools/imagecustomizerapi/moduleLoadMode.go
toolkit/tools/imagecustomizerapi/module_test.go
toolkit/tools/imagecustomizerapi/mountpoint.go
toolkit/tools/imagecustomizerapi/mountpoint_test.go
toolkit/tools/imagecustomizerapi/os.go
toolkit/tools/imagecustomizerapi/os_test.go
toolkit/tools/imagecustomizerapi/overlay.go
toolkit/tools/imagecustomizerapi/overlay_test.go
toolkit/tools/imagecustomizerapi/partitionsize_test.go
toolkit/tools/imagecustomizerapi/password_test.go
toolkit/tools/imagecustomizerapi/script_test.go
toolkit/tools/imagecustomizerapi/scripts_test.go
toolkit/tools/imagecustomizerapi/service.go
toolkit/tools/imagecustomizerapi/service_test.go
toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/user_test.go
toolkit/tools/imagecustomizerapi/utils_test.go

This change adds tests for the image customizer API package, so that the vast majority of lines have test coverage. The only lines remaining are related to validity checking for kernel command-line args, since these will very likely be changed/remove in the future (when the API is changed from a string to a list of strings).
In addition, some of the error messages were cleaned up / made more consistent.
---
NO
- Ran new UTs.

Image Customizer: Add tests for API package.

---

SPECS/containerized-data-importer/CVE-2024-3727.patch
SPECS/containerized-data-importer/containerized-data-importer.spec

---
Address CVE-2024-3727 by patching vendored github.com/containers/image.
- Create patch from PR: https://[patch-diff.githubusercontent.com/raw/containers/image/pull/2403.patch](https://patch-diff.githubusercontent.com/raw/containers/image/pull/2403.patch)
- Adjust patch for containers/image version and vendored files (only docker folder is vendored)
- Adjust patch paths to reflect vendored paths
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582455&view=results
- validated golden containers (built with: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=582648&view=results) using kubevirt …

Address CVE-2024-3727 by patching vendored github.com/containers/image

---

SPECS/conntrack-tools/conntrack-tools.signatures.json
SPECS/conntrack-tools/conntrack-tools.spec
SPECS/libnetfilter_conntrack/libnetfilter_conntrack.signatures.json
SPECS/libnetfilter_conntrack/libnetfilter_conntrack.spec
cgmanifest.json

---
Update conntrack-tools to v1.4.8 which addresses situations where conntrack flush command exits with error code 1. To update conntrack-tools to v1.4.8, libnetfilter_conntrack dependency needs to also be updated.
**NO**

Update conntrack-tools and dependency

---

SPECS/cloud-init/cloud-init.spec
SPECS/cloud-init/dhcp_support_dhclient_unknown_121.patch

---
Cloud-init does not configure rfc3442-classless-static-routes if dhclient not patched to support them or it is not configured with. Currently, our dhclient package does not support rfc3442-classless-static-routes. So add an upstream up to resolve this. This change will resolve this and remove an DHCP error in cloud-init.log due to this.
- Add [upstream patch](https://github.com/canonical/cloud-init/pull/5146) for this issue
NO
- [Bug 51407171](https://microsoft.visualstudio.com/OS/_workitems/edit/51407171): [Core][3.0] cloud-init in Azure Linux 3.0 needs to be updated to 24.2
- Azure VM …

Add patch for cloud init dhcp issue

---

SPECS/shadow-utils/shadow-utils.spec

---
Change #7761 upgraded `shadow-utils` and took part of a [change from upstream](https://github.com/vmware/photon/commit/96763cf667979d81003ee084b8d33a96fe5a2d46) that modifies `/etc/login.defs` so that `USERGROUPS_ENAB` is set to `no`. This makes all users be created in the same group (in our case `users`) rather than created with their own group.
This change undoes that, so users will once again be created with their own group with the same name as the user.
- Removed code in `shadow-utils.spec` that changed the setting.
**NO**
- Built locally and verified change to `/etc/login.defs`
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=583292&view=results
- Full Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=583291&view=results
- …

Fix shadow-utils to reenable user groups

---

SPECS/systemd/systemd.spec

---
LLMNR poisoning is a MitM attack used to capture credential material by tampering with LLMNR request and response messages.
To prevent LLMNR poisoning, disable LLMNR in systemd. LLMNR is actively being phased out in favor of mDNS.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/51548568
- Pipeline build id: [586465](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586465&view=results)

systemd: disable llmnr by default

---

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
SPECS/grub2/disable-checksum-code-optimization.patch
SPECS/grub2/grub2.spec

---
With the current gcc version, the code optimization leads to incorrect checksums of packets in some cases. This, consequently, leads to those packets getting dropped by receiving client due to their incorrect checksums. This broke our PXE boot scenario.
The fix here is a work around where we disable code optimization for the function in question. Future versions of gcc might fix this issue - at which point, this fix can be reverted.
- [Disable code optimization for ip frame checksum calculation](https://github.com/microsoft/azurelinux/commit/80307229fcc7cfe5062018bde59a3a65d9f333c6)
**NO**
- [7849: [mic][iso][pxe] [commodore] 3.0 isos created by mic are failing to be pxe …

[grub] Disable code optimization for ip frame checksum calculation.

---

SPECS/annobin/annobin.spec

---
The Package tests for `annobin` were failing due to `debufinfod` not being present. Since we are not building with debuginfod, the flag has been turned off
- Build annobin with option `--without-debuginfod`
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586612&view=results

Test Fix for Package annobin

---

SPECS/brotli/brotli.spec

---
After an upgrade for Azure Linux 3.0, brotli package tests are failing. With the latest update, the old make targets used for testing are deprecated. Now using cmake instead.
- Migrate from using make targets to cmake for testing
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586674&view=results

Test Fix for Package brotli

---

SPECS/babel/babel.signatures.json
SPECS/babel/babel.spec
cgmanifest.json

---
Package tests for babel are failing. This PR upgrades the package to support python3.12 (the default version for azure linux 3.0) and take a few fixes to support python3.12 f-string parsing.
- Upgrade babel to version 2.15.0
- use pytest instead of setup.py for testing
- favor azure linux packages over pip install for stability
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586673&view=results

Upgrade babel to Version 2.15.0 to Fix Package Tests

---

.pipelines/containerSourceData/kubevirt/Dockerfile-kubevirt-virt-launcher
.pipelines/containerSourceData/kubevirt/virt-launcher.pkg
.pipelines/containerSourceData/multus/Dockerfile-Multus

---
- Removing edk2-ovmf package from virt-launcher dockerfile
- Adding edk2-ovmf to virt-launcher.pkg
- Changing name for multus entrypoint to get it to work with 3.0 golden container image build
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586092&view=results

Changes to kubevirt, multus to build container images on 3.0

---

SPECS/python-xlsxwriter/python-xlsxwriter.spec

Fix build issue
---
Fix build issue
modified:   python-xlsxwriter.spec
NO
[- Pipeline build id: xxxx](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586727&view=results)

xlsxwriter build issue

---

SPECS/kata-containers-cc/kata-containers-cc.spec
SPECS/kata-containers/kata-containers.spec

---
Update `kata-containers` and `kata-containers-cc` to support cgroupv2.
- Enable sandbox_cgroup_only configuration in kata-containers and kata-containers-cc
- Remove cgroupv1 kernel parameter in kata-containers
**NO**
- BuddyBuild: [584233](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=584233&view=results)

kata-containers(-cc): enable sandbox_cgroup_only to support cgroupv2

---

toolkit/scripts/preview.mk

---
Fix an issue for derivative builds using `make package-toolkit` if the destination didn't have a `./SPECS/.../*.repo file` file to grab, and `make` thought the existing version was out of date.
- Fix USE_PREVIEW_REPO=y for derivative builds.
**NO**
- Local tests

Fix ordering issues with new preview repo handling in derivative builds

---

SPECS/libnvidia-container/libnvidia-container.signatures.json
SPECS/libnvidia-container/libnvidia-container.spec
SPECS/libnvidia-container/nvidia-modprobe.patch
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
cgmanifest.json

---
- Upgrade nvidia-container-toolkit and libnvidia-container to the latest v1.15.0 version
- Enable generation of config.toml file which is required by nvidia container runtime
- Generate config.toml file during %posttrans step 
- Upgrade to version 1.15.0
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=586258&view=results

[3.0] Fix and upgrade nvidia-container-toolkit and libnvidia-container

---

SPECS/nodejs/nodejs18.signatures.json
SPECS/nodejs/nodejs18.spec
cgmanifest.json

---
Fixes CVE-2024-28863 and addresses #9334 
- Upgrades nodejs18 to fix CVE-2024-28863
**NO**
- Fixes #9334
- https://nvd.nist.gov/vuln/detail/CVE-2024-28863
- Pipeline build id: 586006

nodejs18: upgrade nodejs18 to 18.20.3 to fix CVE-2024-28863

---

SPECS/python-jsonschema/python-jsonschema.signatures.json
SPECS/python-jsonschema/python-jsonschema.spec
cgmanifest.json

---
The jsonschema package after upgrade does not work as expected, as was found by attempting to use it in azurelinux-sysinfo package. It is missing the following prerequisites:
attrs 23.2.0
jsonschema-specifications 2023.12.1
referencing 0.35.1
rpds-py 0.18.1
While we have the attrs package, we don't have the others in SPECS. 
In light of the upcoming GA and a desire for a stable release, this PR seeks to revert the upgrade so that we have a working version of jsonschema.
- Revert upgrade for python-jsonschema
**NO**
- https://dev.azure.com/mariner-org/ECF/_workitems/edit/7801
- GA blocking bug: https://microsoft.visualstudio.com/OS/_workitems/edit/51858899 …

python-jsonschema: revert upgrade

---

SPECS/telegraf/CVE-2024-35255.patch
SPECS/telegraf/telegraf.spec

---
telegraf: patch CVE-2024-35255
How was this patch generated:
- Based on https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-35255, this CVE is fixed on versions >= 1.6.0
- There is no version of telegraf available yet that uses azure-sdk-for-go >= 1.6.0. So we need to patch
- Based on release notes in https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fazidentity%2Fv1.6.0 , the fix for CVE seems to be https://github.com/Azure/azure-sdk-for-go/commit/50774cd9709905523136fb05e8c85a50e8984499 and https://github.com/Azure/azure-sdk-for-go/commit/48d39a82091b3aebe3df3505bd5372294b3461ed
- Confirmed with commit author …

telegraf: patch CVE-2024-35255

---

SPECS/mysql/mysql.signatures.json
SPECS/mysql/mysql.spec
cgmanifest.json

---
- Upgrade mysql from 8.0.35 to 8.0.36
**YES/NO**
- #xxxx
- CVE-2024-20961
- CVE-2024-20963
- CVE-2024-20965
- CVE-2024-20967
- CVE-2024-20969
- CVE-2024-20971
- CVE-2024-20973
- CVE-2024-20977
- CVE-2024-20981
- CVE-2024-20985
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=588569&view=results

mysql: upgrade to 8.0.36 to fix 10 CVEs

---

toolkit/docs/formats/imageconfig.md
toolkit/imageconfigs/core-efi.json
toolkit/imageconfigs/core-legacy.json

---
Roll out the locales removal for core images. This should remove `/usr/share/locale/*` from `core-efi` and `core-legacy` images.
Locales off (3.3MB):
Locales on, re-install with `tdnf -y reinstall $(rpm -qa)` (19MB):
- Set `"DisableRpmDocs": true` and `"OverrideRpmLocales": "NONE"` for both `core-efi.json` and `core-legacy.json`.
- Add some documentation on restoring files
**NO**
- Local check of build images, checked size, re-enabled locales and re-installed all files

Remove locales from core images, add documentation on restoring locales

---

SPECS/bash/bash-2.03-profile.patch
SPECS/bash/bash.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

i.e., when invoked via 'su - <user> -c ...'. This is done by Fedora and Ubuntu (and other distros).
---
Bash loads startup scripts when it runs, based on some logic to detect if it is a login/normal prompt, and interactive/non-interactive. (profile, bashrc, etc..., depending on those modes).
Tools like `su` in `util-linux` can explicitly request login/non-login mode (`su - other_user ...` (`-` == `-l` == `--login`). It informs bash of this choice by  prepending a '-' to `argv[0]` (i.e., `-bash`). By default `bash` ignores this, but can be [configured to respect it via a "hidden" define](https://git.savannah.gnu.org/cgit/bash.git/tree/config-top.h#n105) `NON_INTERACTIVE_LOGIN_SHELLS`. …

Patch bash to load startup files when invoked with '-bash'

---

toolkit/tools/imagecustomizer/docs/configuration.md

1. Call out that you can set the `/etc/resolv.conf` file using a `finalizeCustomization` script.
2. Fix the example given for `finalizeCustomization` scripts.
---
NO
- n/a

Image Customizer: Minor doc updates.

---

SPECS/R/CVE-2024-27322.patch
SPECS/R/R.spec

---
R: patch CVE-2024-27322
Interesting to note: 
- Post claiming the vulnerability still hasn't been fixed: https://rud.is/b/2024/05/03/cve-2024-27322-should-never-have-been-assigned-and-r-data-files-are-still-super-risky-even-in-r-4-4-0/
- Rebuttal from upstream maintainers claiming it is indeed fixed: https://blog.r-project.org/2024/05/10/statement-on-cve-2024-27322/index.html
- Same patch used by Fedora: https://src.fedoraproject.org/rpms/R/blob/f39/f/R-CVE-2024-27322.patch
- R
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-27322
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=589803&view=res …

R: patch CVE-2024-27322

---

SPECS/cri-o/CVE-2024-3727.patch
SPECS/cri-o/cri-o.spec

---
Address https://github.com/advisories/GHSA-6wvf-f2vw-3425 by patching vendored github.com/containers/image.
- Cherry pick commits in https://github.com/containers/image/pull/2403
- Prune to only the relevant sections.
- Adjustments to backport the fix. 
**NO**
- github.com/containers/image w/ patch built locally.
- github.com/containers/image w/ and w/o patch produce same results for `make test`.
- Built specfile with patch locally in 2.0 container.
- PR checks succeeded below.

Fix CVE-2024-3727 in cri-o by patching vendored github.com/containers/image

---

SPECS/crash/crash.spec

---
Support analyzing arm64 kernel dump files with crash on x86-64 host machines. I've added a new binary `/usr/bin/crash-target-arm64` in subpackage `crash-target-arm64` that supports this scenario. The existing `/usr/bin/crash` tool is unmodified, and continues to support analyzing crash dumps of the native architecture (x86-64 dumps on x86-64 machines, and arm64 dumps on arm64 machines).
- Create crash-target-arm64.x86_64 subpackage to generate `crash-target-arm64`
**NO**
- Needed for 3.0 GA, dependency and tasks are:
- https://microsoft.visualstudio.com/OS/_workitems/edit/51621462
- …

crash: add crash-target-arm64 binary

---

SPECS/skopeo/CVE-2024-3727.patch
SPECS/skopeo/skopeo.spec

---
Backport fix CVE-2024-3727 in skopeo
> **NOTE:** The original patch at [upstream PR](https://github.com/containers/image/pull/2418) had **pkg/blobcache** as well but its not present in our vendor directory hence **pkg/blobcache** is not included in this patch.
- CVE-2024-3727
**NO**
- #xxxx
- Github PR check

Fix CVE-2024-3727 in skopeo

---

toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/hostname-config.yaml

Image Customizer: Add test for hostname.

---

SPECS/kata-packages-uvm/kata-packages-uvm.spec

---
Due to udevadm being moved to systemd-udev subpackage, implicit behavior we relied upon for baking UVM images in 2.0 went away. To restore systemd-udevd.service functionality in UVM images, explicitly require systemd-udev. 
- explicitly require systemd-udev for Kata-CC UVM images
NO
- Manually built UVM with systemd-udev added, see that kata-cc pods come up now. 
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=589712&view=results

Kata-CC: Add explicit systemd dependencies for UVM

---

SPECS/libtpms/0001-Export-RSA-private-key-primes-to-OpenSSL.patch
SPECS/libtpms/libtpms.spec

---
Recent testing found an incompatibility between libtpms and the SymCrypt provider. Version 0.9.6 of libtpms is using the old OpenSSL APIs and does not export the RSA key primes as part of RSA private key export. SymCrypt expects these primes to import the RSA private key. This PR adds a patch to libtpms to export the expected primes.
The latest changes to libtpms appear to fix this issue and update to the OpenSSL 3 APIs, so this patch is only necessary until those changes make it to release.
- Add patch to fix compatibility between libtpms and the SymCrypt provider
NO
- Local build. Confirmed bug is no repro
- Buddy Build: …

Fix libtpms <-> SymCrypt provider compatibility

---

SPECS/libxcrypt/libxcrypt.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Now that glibc no longer builds libcrypt.so, we can directly use libxcrypt's version of libcrypt.so
and remove the override macros in the libxcrypt spec.
The override_glibc logic was added by us to workaround an issue with adding this improved version of libcrypt into Mariner 1.0 while it was already released. And in 1.0, 2.0, and pre-Nov 2023 3.0, the macro was %bcond_without override_glibc, but after Nov 2023, the macro was changed to %bcond_with override_glibc which means all these overrides are currently inert and are now just diffs from the original spec.
The only real functional change here is the addition of `Requires: glibc%{?_isa} >= %{glibc_minver}` 
Signed-off-by: …

fix: remove override_glibc logic from libxcrypt

---

SPECS/libarchive/CVE-2024-26256.patch
SPECS/libarchive/CVE-2024-37407.patch
SPECS/libarchive/libarchive.signatures.json
SPECS/libarchive/libarchive.spec
SPECS/libarchive/update-appledouble-support-directories.patch
cgmanifest.json
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
update libarchive to v3.7.4 to fix CVEs 2024-26256 and 2024-37407
- update to v3.7.4 to fix CVEs 2024-26256 and 2024-37407
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-26256
- https://nvd.nist.gov/vuln/detail/CVE-2024-37407
- Successful buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593425&view=results. Failures are unrelated to changes

libarchive: update to v3.7.4 to fix CVEs 2024-26256 and 2024-37407

---

toolkit/tools/imagecustomizer/DEV.md
toolkit/tools/pkg/imagecustomizerlib/customizepackages_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
toolkit/tools/pkg/imagecustomizerlib/main_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/install-package-disk-space.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/lists/golang.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/packages-add-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/packages-update-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/testrpms/.gitignore
toolkit/tools/pkg/imagecustomizerlib/testdata/testrpms/download-test-rpms.sh
toolkit/tools/pkg/imagecustomizerlib/testdata/testrpms/downloader/Dockerfile

1. Add tests for installing/updating/removing packages, including variants for both online and offline installs.
2. Add a script that will download the RPM files needed for the offline package install tests.
3. Add a developers guide, which includes building the image customizer tool and how to run the tests.
---
NO
- Ran new UTs.

Image Customizer: Add package tests.

---

.pipelines/containerSourceData/multus/Dockerfile-Multus

---
Renaming the entrypoint to `thin_entrypoint` from `multus-entrypoint` to unblock golden container runs.
**NO**
- #xxxx
- Pipeline build id: [run](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=595468&view=results)

Dockerfile changes for Multus Golden Containers in 3.0

---

SPECS/conda/conda.spec

---
The ptest for conda has been failing due to dependency issues. Additionally, some test can be skipped for the lack of an external conda package, `conda_libmamba_solver`, which we don't ship so these tests must be skipped.
- Add missing dependencies via pip install and BuildRequires
- Add skips for tests using `conda_libmamba_solver` 
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=588908&view=results

Ptest Fix for package conda

---

toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
toolkit/tools/imagecustomizer/container/build-mic-container.sh

There is currently an issue where `oras` can't be downloaded when the container is being built because the container doesn't have the `ca-certificates` package installed. This problem could be fixed by adding `ca-certificates` to the list of packages installed. But instead, this change downloads `oras` binary outside of the `Dockerfile`. Doing it this way will help reduce the size of the container.
---
NO
- Built and ran MIC container.

Image Customizer: Fix container build.

---

toolkit/docs/formats/imageconfig.md
toolkit/tools/imagegen/configuration/systemconfig.go
toolkit/tools/imagegen/installutils/installutils.go

---
The systemd package creates `/etc/machine-id` when it installs (in m2 it did not create this file). If this file is populated on a vm image, every instance of that vm will have the same id. This will break networking, k8s, etc. To avoid this, we need to clear the state before creating the image. The correct first-boot behavior is to set the id to 'uninitialized' and let the system generate a new one on boot. Clearing the file is similar, systemd will generate a new id on boot, but it will not run the first-boot setup.
We will keep the current behavior with `/etc/machine-id` being empty. A new config flag will allow an image to use the first-boot flow.
As part of …

Clear systemd state when creating an image

---

toolkit/scripts/build_tag_imagecustomizer.mk

NO
- Build image customizer tool.

Image Customizer: Bump build tag to 0.5.0

---

SPECS/openssh/CVE-2024-6387.patch
SPECS/openssh/openssh.spec

---
This PR patches openssh for [CVE-2024-6387](https://nvd.nist.gov/vuln/detail/CVE-2024-6387) using [debian source](https://launchpadlibrarian.net/737504733/openssh_1%3A8.9p1-3ubuntu0.7_1%3A8.9p1-3ubuntu0.10.diff.gz) as guidance.
This CVE, nicknamed "Regression", is an unauthenticated Remote Code Execution (RCE) vulnerability in OpenSSH’s server (sshd) on glibc-based Linux systems.
See [this post](https://www.qualys.com/regresshion-cve-2024-6387/) for further details on this CVE, nicknamed "Regresshion"
- Patch for CVE-2024-6387 using debian source as guidance
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-6387
- local build
- buddy build from stable-2.0: …

openssh: fix "regresshion" CVE, CVE-2024-6387, with patch from debian.

---

SPECS/kata-containers-cc/kata-containers-cc.spec

---
Enable and start tardev-snapshotter.service after installation of kata-containers-cc.
- Enable and start tardev-snapshotter.service after installation of kata-containers-cc
**NO**
- BuddyBuild: [598004](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=598004&view=results)
- ImageBuild: [598019](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=598019&view=results)

kata-containers-cc: enable and start tardev-snapshotter.service after installation

---

toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/internal/resources/assets/efi/grub/grub.cfg
toolkit/tools/internal/resources/assets/efi/grub/grubEncrypt.cfg

---
The new grub config flow did not handle the specialized `grubEncrypt.cfg` file. This file is almost identical to the normal grub config, so unify them into one file.
We also have not used `{{.EncryptedVolume}}` in the grub config for a very long time, so repurpose the existing `setGrubCfgEncryptedVolume()` function to instead optionally add `cryptomount -a` to the start of the EFI grub config via `{{.CryptoMountCommand}}` instead.
- Remove `grubEncrypt.cfg` template file
- Add `{{.CryptoMountCommand}}` to the normal EFI `grub.cfg` file.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/52146800
- Local testing of ISO
- ~Will test offline build as well~ Encryption …

Fix encrypted root handling for new grub mkconfig flow

---

SPECS/openssh/openssh.signatures.json
SPECS/openssh/openssh.spec
cgmanifest.json

---
This upgrade resolves Critical CVE-2024-6387 which is a regression for CVE-2006-5051.  Note that this version of openssh splits the server into two binaries, so there is a packaging difference from the previous version.  The server/listener (sshd) and a separate binary that hosts the session (sshd-session). 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-6387
Buddy build and manually installed the client and server package.  Verified that I could connect to the server and verified that the ssh client functioned.
Note that the pTest currently fails for ssh because the Azure Linux version of openssh does not include the secure-key (libraries).  A separate bug is tracking to …

Upgrade OpenSSH to 9.8p1 to resolve the Regresshion CVE

---

SPECS/wayland-protocols/wayland-protocols.signatures.json
SPECS/wayland-protocols/wayland-protocols.spec
cgmanifest.json

---
Update wayland-protocols to v1.36, this is required to update xserver package.
- Change
- Change
- Change
**NO**
- #xxxx

3.0-dev: update wayland-protocols to v1.36

---

SPECS/selinux-policy/0033-cloud-init-and-kmod-fixes.patch
SPECS/selinux-policy/selinux-policy.spec

---
Fix udevadm and kmod issues when run from cloud-init.
- Add labeling for /run/modprobe.d
- Add permissions for udevadm and kmod to log to cloud-init (redirected stdout)
**NO**
- Pipeline build id: 597242

selinux-policy: Add udev and kmod fixes.

---

SPECS/blobfuse2/CVE-2023-44487.patch
SPECS/blobfuse2/blobfuse2.spec
SPECS/blobfuse2/generate_source_tarball.sh

---
Patching CVE-2023-44487 in `blobfuse2`.
Also cleaned-up the spec a bit and switched to using the `generate_source_tarball.sh` script for building the vendor tarballs.
No.
- Local build.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601390&view=results)

Patched CVE-2023-44487 in 'blobfuse2'.

---

toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/imagegen/diskutils/fstab.go

Prior to util-linux v2.37, when a command is outputting a list in JSON and there aren't any items, then stdout would be empty. This change checks for this scenario and handles it appropriately.
---
NO
https://microsoft.visualstudio.com/OS/_workitems/edit/52123611
- Manually ran the image customizer tool.

Toolkit: Fix JSON parsing of util-linux commands.

---

toolkit/docs/formats/imageconfig.md
toolkit/imageconfigs/packagelists/core-packages-image.json
toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
toolkit/tools/imagecustomizerapi/user.go
toolkit/tools/imagegen/configuration/systemconfig.go
toolkit/tools/imagegen/configuration/user.go
toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/internal/userutils/userutils.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils.go

This PR is a combination of the following changes that's been in review process once:
1- https://github.com/microsoft/azurelinux/pull/6957
2- https://github.com/microsoft/azurelinux/pull/6876
---
This PR accomplishes the following goals:
1- Add support to specify home directory and primary group when creating users. We needed this to overwrite those defaults for some of the service's users that are predefined in an Azure Linux derivative image. Also, added a validation step in imageconfigvalidator to ensure "shadow-utils" package is added to the packages list. 
2- Add support to define a list of users and groups when building a rootFS …

Improve user/group creation in image build

---

SPECS/kexec-tools/kexec-tools.spec

---
dhcp-client package is not actually needed for kexec-tools to function. Additionally the dhcp package is deprecated upstream.
Remove the dhcp-client dependency from kexec-tools.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/52409721
- Pipeline build id: [601676](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601676&view=results)
- Local kdump testing without `dhcp-client` is functional. vmcore can be analyzed with crash

fix: remove dhcp-client requires from kexec-tools

---

SPECS/python-attrs/python-attrs.spec

---
The package test for python-attrs is failing due to a failed tox install. The install was failing due to a failed python-packaging upgrade by pip, the specified version fixes this.
- Add explicit version of python-packaging in pip install
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=598782&view=results

PTest Fix for package python-attrs

---

SPECS/ntopng/CVE-2017-18214.patch
SPECS/ntopng/CVE-2022-33099.patch
SPECS/ntopng/ntopng.spec

---
Add patches to ntopng for bundled software; for CVE-2022-33099 (lua) and CVE-2017-18214 (moment.js)
- Add CVE patches to `ntopng`
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-33099
- https://nvd.nist.gov/vuln/detail/CVE-2017-18214
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602179&view=results

ntopng: add patches for CVE-2017-18214 and CVE-2022-33099

---

SPECS/kube-vip-cloud-provider/CVE-2023-47108.patch
SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.signatures.json
SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
cgmanifest.json

---
Upgrade `kube-vip-cloud-provider` to `v0.0.10`, which fixes CVE-2023-45142. Also apply patch to fix CVE-2023-47108.
- Upgrade `kube-vip-cloud-provider` to `v0.0.10`.
- Re-create vendor tarball.
- Patch CVE-2023-47108
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-45142
- https://nvd.nist.gov/vuln/detail/CVE-2023-47108
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602669&view=results

Upgrade kube-vip-cloud-provider to fix CVE-2023-45142 and manually patch CVE-2023-47108

---

SPECS/cert-manager/cert-manager.signatures.json
SPECS/cert-manager/cert-manager.spec
SPECS/cert-manager/generate_source_tarball.sh
cgmanifest.json

---
Upgrade `cert-manager` to `1.12.12`, which fixes CVE-2023-45142 and CVE-2024-26147. There are more recent version, but `1.13.0` has some notes about breaking changes and it feels too close to GA to take that risk.
- Upgrade to `1.12.12`.
- Change how we vendor and build the code -- they did a refactor that means we need to build slightly differently.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-45142
- https://nvd.nist.gov/vuln/detail/CVE-2024-26147
- Local Build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602798&view=results

Upgrade cert-manager to 1.12.12 to fix CVE-2023-45142 and CVE-2024-26147

---

SPECS/influxdb/CVE-2019-0205.patch
SPECS/influxdb/influxdb.spec

---
This PR patches CVE-2019-0205 within vendored go module for `influxdb`
- adds patch for CVE-2019-0205
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2019-0205
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602751&view=results

Patch CVE-2019-0205 for influxdb in 3.0

---

SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.spec
SPECS/systemd/systemd.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Disable building kernel-uki and systemd-boot on aarch64 to unblock build pipeline. We will re-enable these 2 packages with testing when we have the actual use case for it.
- Add `ExclusiveArch: x86_64` to kernel-uki spec.
- Only generate systemd-boot if arch is x86_64
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602776&view=results

Build kernel-uki and systemd-boot on x86_64 exclusively

---

SPECS/edk2/CVE-2022-3996.patch
SPECS/edk2/edk2.spec

---
Patch CVE-2022-3996 in bundled openssl in edk2
- CVE-2022-3996
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-3996
- Unified Buddy Build: [601832](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601832&view=results)

Patch CVE-2022-3996 in bundled openssl in edk2

---

SPECS/irqbalance/0001-define-IRQBALANCE_ARGS-as-empty-string.patch
SPECS/irqbalance/irqbalance.spec

---
Our 3.0 images produce some extra noise during boot:
irqbalance: "Referenced but unset environment variable evaluates to an empty string: IRQBALANCE_ARGS"
This is due to the variable IRQBALANCE_ARGS, referenced in irqbalance.service, not being defined in the EnvironmentFile pointed to by that service. Sed the Environment file to uncomment IRQBALANCE_ARGS, explicitly setting it to the empty string. 
- Sed the Environment file for irqbalance to uncomment IRQBALANCE_ARGS, explicitly setting it to the empty string
NO
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=597498&view=results

irqbalance: Tweak irqbalance environment file to squelch systemd warning

---

SPECS/containerized-data-importer/CVE-2022-2879.patch
SPECS/containerized-data-importer/containerized-data-importer.spec

---
- Add patch for CVE-2022-2879 affecting vendored library for containerized-data-importer
- CVE-2022-2879
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-2879
- Local build

containerized-data-importer: add patch for CVE-2022-2879

---

SPECS/application-gateway-kubernetes-ingress/CVE-2022-21698.patch
SPECS/application-gateway-kubernetes-ingress/CVE-2022-41273.patch
SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec

---
- Add patch for CVE-2022-21698, CVE-2022-41273 affecting vendored libraries for application-gateway-kubernetes-ingress
- CVE-2022-21698
- CVE-2022-41273
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-41273
- Local build

application-gateway-kubernetes-ingress: add patch for CVE-2022-21698, CVE-2022-41273

---

toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

When verity is enabled in the config, check that the NBD module is loaded before starting the customization process.
---
NO

Image Customizer: Pre-check for NBD module.

---

toolkit/resources/assets/meta-user-data/user-data

---
Fix an invalid cloud-init schema error in user-data as it downgraded cloud-init status and failed BVT cloud-init test. user-data is used to generate the user-meta-data.iso
- Fix an invalid cloud-init schema error in user-data
NO
- [Bug 52070135](https://microsoft.visualstudio.com/OS/_workitems/edit/52070135): 3.0 BVT "cloud-init" test failing
- local image build.
- Verify the schema error is gone after the fix by running "sudo cloud-init schema --system"
- BVT test pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603459&view=results

fix cloud-init userdata schema error

---

SPECS/libcontainers-common/CVE-2022-2879.patch
SPECS/libcontainers-common/CVE-2023-45288.patch
SPECS/libcontainers-common/CVE-2024-1753.patch
SPECS/libcontainers-common/CVE-2024-3727.patch
SPECS/libcontainers-common/CVE-2024-37298.patch
SPECS/libcontainers-common/libcontainers-common.spec

---
- libcontainers-common: address CVE-2022-2879
- libcontainers-common: address CVE-2023-45288
- libcontainers-common: address CVE-2024-1753
- libcontainers-common: address CVE-2024-3727
- libcontainers-common: address CVE-2024-37298
- libcontainers-common: switch to patch command instead of %patch macro in %build section
- libcontainers-common: switch to patch command instead of %patch macro in %build section
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-37298
- https://nvd.nist.gov/vuln/detail/CVE-2024-1753
- …

libcontainers-common: address CVE-2022-2879, CVE-2023-45288, CVE-2024-1753, CVE-2024-3727 & CVE-2024-37298

---

toolkit/tools/imagecustomizer/docs/cli.md
toolkit/tools/imagecustomizer/main.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

Add support for outputting image as fixed-size VHD, which is required by VMs in Azure.
---
NO

Image Customizer: Support fixed-size VHD.

---

SPECS/hvloader/CVE-2023-0464.patch
SPECS/hvloader/CVE-2024-1298.patch
SPECS/hvloader/hvloader.spec

This PR cherry-picks the following commits to fix mentioned CVEs.
- CVE-2024-1298 [PR](https://github.com/microsoft/azurelinux/pull/9337)
- CVE-2023-0464 [PR](https://github.com/microsoft/azurelinux/pull/9443)
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603776&view=results

hvloader: add patch for CVE-2024-1298 (#9337) and CVE-2023-0464 (#9443)

---

SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
cgmanifest.json

This is a pull request to cherry-pick commit https://github.com/microsoft/azurelinux/commit/96142f62a7c084ab76f70b75d40b19773bc0a2cc to 3.0-dev. Original PR: https://github.com/microsoft/azurelinux/pull/9609
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603777&view=results

cloud-hypervisor-cvm: update to 38.0.72.2 (#9609)

---

SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.spec
SPECS/systemd/systemd.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

A build break was stopping ARM64 to build for preview, this change fixes the issue by restricting package architecture.
- cherry pick https://github.com/microsoft/azurelinux/commit/ded92cfc965d519f0844c9d8a6c240e943b0ee09
**YES**

Cherry-Pick kernel-uki and systemd-boot fix to 3.0

---

SPECS/python-nocasedict/python-nocasedict.signatures.json
SPECS/python-nocasedict/python-nocasedict.spec
cgmanifest.json

---
the ptests are failing for python-nocasedict due to incompatibilities with python versions. The minor version upgrade fixes these.
- Upgrade python-nocasedict to version 2.0.3
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603515&view=results

Upgrade python-nocasedict to fix ptests

---

SPECS/python-iniparse/python-3.11-test-compat.patch
SPECS/python-iniparse/python-iniparse.spec

---
Package tests for python-iniparse are failing. This is due to python 3.11 compatibility issues. Adding a patch from upstream to fix this.
- Add upstream patch to fix the package tests
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603515&view=results

add patch to fix python 3.11 compat for ptest in python-iniparse

---

SPECS/python-jsonschema/python-jsonschema.spec
SPECS/python-jsonschema/tox-test.patch

---
since the upgrade being reverted, the ptests for python-jsonschema have been failing. This pr adds a patch to fix the ptests via deps management and removal of docs test, as well as adding a py312 environment
- Add patch for tox environment fixes
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=605559&view=results

Ptest Fix for Package python-jsonschema

---

SPECS/kata-containers-cc/kata-containers-cc.signatures.json
SPECS/kata-containers-cc/kata-containers-cc.spec
SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
SPECS/kata-containers/kata-containers.signatures.json
SPECS/kata-containers/kata-containers.spec
SPECS/kata-containers/mariner-build-uvm.sh

---
During UVM build, the default OS' clean target is executed - which is Ubuntu.
- Change make clean call to clean up the artifacts for the cbl-mariner distro: `rm -rf /opt/kata-containers/uvm/tools/osbuilder/.ubuntu_rootfs.done /opt/kata-containers/uvm/tools/osbuilder/ubuntu_rootfs`
**NO**
- N/A
- N/A
- Pipeline build id: 605606, showing the clean-up for: `rm -rf /opt/kata-containers/uvm/tools/osbuilder/.cbl-mariner_rootfs.done /opt/kata-containers/uvm/tools/osbuilder/cbl-mariner_rootfs`

kata-cc: Fix make clean call in UVM build

---

SPECS/moby-engine/daemon.json
SPECS/moby-engine/enable-docker-proxy-libexec-search.patch
SPECS/moby-engine/moby-engine.signatures.json
SPECS/moby-engine/moby-engine.spec

---
Our moby-engine-24.0.9-1 package brought in a new daemon.json file to inform the newer moby-engine version of docker-proxy's location. Adding daemon.json to the package regressed several use cases, instead we'll rely on backporting a recent upstream change (https://github.com/moby/moby/pull/47804) that implicitly looks for docker-proxy in libexec so that we can drop daemon.json.
- Backport https://github.com/moby/moby/pull/47804 so moby-engine finds docker-proxy in libexec
- Remove daemon.json from our moby-engine package.
**NO**
- fixes #8961
- Buddy build: [succeeded](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=598825&view=results)
- …

moby-engine: remove daemon.json with backported fix

---

toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/iso-files-and-args-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/iso-os-prereqs-config.yaml

Add tests for:
- vhdx to ISO, with and without OS changes.
- ISO to ISO, with and without OS changes.
- Kernel command-line args.
- .iso.additionalFiles
---
NO
- Manually ran new UTs

Image Customizer: Add ISO tests.

---

SPECS/moby-engine/daemon.json
SPECS/moby-engine/enable-docker-proxy-libexec-search.patch
SPECS/moby-engine/moby-engine.signatures.json
SPECS/moby-engine/moby-engine.spec

---
This is a cherry-pick of https://github.com/microsoft/azurelinux/pull/9551 into fasttrack.
Our moby-engine-24.0.9-1 package brought in a new daemon.json file to inform the newer moby-engine version of docker-proxy's location. Adding daemon.json to the package regressed several use cases, instead we'll rely on backporting a recent upstream change (https://github.com/moby/moby/pull/47804) that implicitly looks for docker-proxy in libexec so that we can drop daemon.json.
- Backport https://github.com/moby/moby/pull/47804 so moby-engine finds docker-proxy in libexec
- Remove daemon.json from our moby-engine package.
**NO**
- fixes #8961
- Buddy build: …

moby-engine: remove daemon.json with backported fix (#9551)

---

SPECS/ceph/CVE-2024-38517.patch
SPECS/ceph/CVE-2024-39684.nopatch
SPECS/ceph/ceph.spec

---
High severity security fix for CVE-2024-38517 and CVE-2024-39684
- Add SPECS/ceph/CVE-2024-38517.patch
- Add SPECS/ceph/CVE-2024-39684.nopatch describing this CVE as a duplicate of the above
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-38517
- https://nvd.nist.gov/vuln/detail/CVE-2024-39684
- Pipeline build id: 605590

ceph: Fix high CVE-2024-38517 and CVE-2024-39684

---

toolkit/tools/pkg/imagecustomizerlib/customizeboot.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml

Firstly, replace the use of `qemu-nbd` with a loopback block device.
Secondly, add a test for verity. This verifies that the grub.cfg kernel args are set and that running `veritysetup verify` succeeds.
---
NO
- Ran added UTs.

Image Customizer: Verity: Use loopback + Add tests.

---

SPECS/core-packages/core-packages.spec

This change removes the 3.0-preview scaffolding and defaults Azure Linux to use the production repositories instead of the preview repositories.

Restore Core-Packages to include production repositories

---

SPECS/kata-containers-cc/kata-containers-cc.signatures.json
SPECS/kata-containers-cc/kata-containers-cc.spec
SPECS/kata-containers-cc/mariner-coco-build-uvm.sh
SPECS/kata-containers/kata-containers.signatures.json
SPECS/kata-containers/kata-containers.spec
SPECS/kata-containers/mariner-build-uvm.sh

---
Use OS_VERSION=3.0 for invocation of the UVM image builder. Needed to fix an issue where UVM builder tried to pull from PMC/azurelinux/2.0, which 404s. The correct path is PMC/azurelinux/3.0.
- Use OS_VERSION=3.0 for invocation of the UVM image builder
NO
- Buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602692&view=results

Update 3.0 kata-containers build invocations to use OS_VERSION=3.0

---

toolkit/tools/imagecustomizerapi/fileconfig.go
toolkit/tools/imagecustomizerapi/fileconfig_test.go

When you implement a custom unmarshaller, the `KnownFields()` option to the YAML parser is ignored when you call `yaml.Node.Decode()`. So, we have to manually enforce this check.
---
NO
- Ran existing UTs.
- Added UTs.

Image Customizer: Validate fields on FileConfig.

---

toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml

The verity hash partition must be given a placeholder filesystem type. This should probably be `fat32` for simplicty's sake. But currently, the verity example config uses `ext4`. This causes a problem when the `--shrink-filesystems` is set because it means the verity hash partition gets shrunk to almost nothing and therefore isn't big enough to store the hash tree.
This change fixes this problem by ensuring that the verity hash partition is never subject to being shrunk regardless of its placeholder filesystem type. A test is added to verify this.
---
NO
- Added UT.

Image Customizer: Do not shrink verity hash partition.

---

SPECS/rapidjson/CVE-2024-38517.patch
SPECS/rapidjson/CVE-2024-39684.nopatch
SPECS/rapidjson/rapidjson.spec

---
Fix for high severity CVE-2024038517 and CVE-2024-39684
- patch file for CVE-2024-38517
- nopatch file for CVE-2024-39684 as it is a duplicate of CVE-2024-38517
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-38517
- https://nvd.nist.gov/vuln/detail/CVE-2024-39684
- Pipeline build id: 607293

rapidjson: fix CVE-2024-38517 and CVE-2024-39684

---

SPECS/cf-cli/CVE-2021-43565.patch
SPECS/cf-cli/cf-cli.spec

---
cf-cli: patch CVE-2021-43565
- patch CVE-2021-43565
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-43565
- Pipeline build id:  https://dev.azure.com/mariner-org/mariner/_build/results?buildId=609768&view=results

cf-cli: patch CVE-2021-43565

---

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

The gpg command, and by extension, the tdnf command expects the USER and HOME environment variables to be valid for the OS they are running under (including under chroot). Since, the image customizer tool is typically run under `sudo` and since root is always a valid user, this generally isn't a problem. But this isn't true if `sudo -E` is used. And this can result in strange difficult to diganose errors in tdnf. So, this change verifies that `sudo -E` isn't being used.
---
NO
- Manually tested image customizer tool.

Image Customizer: Validate HOME and USER env vars.

---

toolkit/tools/imagegen/diskutils/diskutils.go

Ubuntu seems to like to call dumpe2fs on ext4 partitions when you mount a disk (even if you don't mount any of the partitions). Depending the size of partition, this can take a little bit of time to run, which can block the loopback from detaching.
The Image Customizer tool uses loopback devices a lot, some of which are only used for a short period of time. So, it can timeout waiting for the loopback to detach. So, this change increases the timeout.
---
NO
- Ran image customizer UTs.

Image Customizer: Increase loopback detach timeout.

---

toolkit/tools/imagecustomizer/README.md
toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/config.go
toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/resetpartitionuuidtype.go
toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitionsuuids.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
toolkit/tools/pkg/imagecustomizerlib/imageutils.go
toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
toolkit/tools/pkg/imagecustomizerlib/testdata/newpartitionsuuids-config.yaml

Add support for resetting the partition and filesystem UUIDs without needing to customize the partition layout.
In addition, this change has necessitated adding support for resetting the bootloader configuration even when the partition layout isn't customized.
---
NO
- Added UTs.

Image Customizer: Partition UUID reset.

---

toolkit/tools/scheduler/schedulerutils/printresults.go

---
In preparation for adding more data (licensing checks) to the build summary, use structs to pass build data around. The function signatures were getting unmanageable.
- Pass data inside `PrintBuildResult()` via new structs: `srpmBuildDataContainer` and `srpmTestDataContainer`.
**NO**
- #xxxx

Use structs to pass data to scheduler prints

---

toolkit/Makefile
toolkit/docs/building/building.md
toolkit/resources/manifests/package/daily_build_repo.repo.template
toolkit/scripts/chroot.mk
toolkit/scripts/daily_build.mk
toolkit/scripts/get_lkg_id.sh
toolkit/scripts/manifests.mk
toolkit/scripts/pkggen.mk
toolkit/scripts/preview.mk
toolkit/scripts/toolchain.mk
toolkit/scripts/update_manifest.sh

---
Refresh/Reimplementation of https://github.com/microsoft/azurelinux/pull/7873.
Based on top of https://github.com/microsoft/azurelinux/pull/9856.
Add a new mechanism to support `DAILY_BUILD_ID=lkg` which automatically updates the toolchain/chroot manifests to match the most recent successful daily build.
The new daily builds will no longer offer the modified `azurelinux-repos` package with modified repos, so we need to use `REPO_LIST=...` to pass the new repo file.
From #7873 I've dropped `DAILY_BUILD_ID=lkg-force`, it just prints an error and tells the user to revert the modified manifests.
**FYI:** I broke up the changes into targeted commits to hopefully make review easier.
- …

Add automatic mode for DAILY_BUILD_ID pass 2

---

SPECS/bind/bind.signatures.json
SPECS/bind/bind.spec
SPECS/bind/nongit-fix.patch
cgmanifest.json

---
- **bind: upgrade 9.19.21 -> 9.20.0 to address CVE-CVE-2024-0760, CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076**
- **bind: upgrade 9.19.21 -> 9.20.0 to address CVE-CVE-2024-0760, CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076**
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-0760
- https://nvd.nist.gov/vuln/detail/CVE-2024-1737
- https://nvd.nist.gov/vuln/detail/CVE-2024-1975
- https://nvd.nist.gov/vuln/detail/CVE-2024-4076
- Pipeline build id: [PR-9918](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=611570&view=results)

bind: upgrade 9.19.21 -> 9.20.0 to address CVE-CVE-2024-0760, CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076

---

SPECS/compiler-rt/compiler-rt.spec
cgmanifest.json

---
Fix the path used for libraries in compiler-rt from `/usr/lib/clang/18.1.2/...` to `/usr/lib/clang/18/...`
- Change compiler-rt to fix path
- Remove cgmanifest entry for unused `libomp` package. This was removed in #5244 
**NO**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=612114&view=results

compiler-rt: fix path issue

---

toolkit/tools/imagegen/configuration/partitiontabletype.go
toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml

When creating partitions using `parted`, the API is:
- MBR: `parted mkpart <partition-type> <fs-type> ...`
- GPT: `parted mkpart <partition-label> <fs-type> ...`
But currently we are treating the first param as always being the `<partition-type>`, when for GPT it is `<partition-label>`. This has the effect that GPT partitions are given a default label of "primary", which is a tad silly. (If an explicit label is provided by the user, then the label is overridden in a subsequent step.)
This change fixes this behavior so that GPT partitions have a default label of nothing ("").
---
NO
- Added UT.

Toolkit: Do not give GPT partitions a default label of "primary".

---

toolkit/docs/building/prerequisites-ubuntu.md

With the update to use go-1.21 we should also update the link commands to do the same not go-1.20
- Update docs
**NO**

update go link commands for go-1.21 in ubuntu prereq

---

SPECS/libcontainers-common/CVE-2024-37298.patch
SPECS/libcontainers-common/libcontainers-common.spec

---
Introduce patch to address CVE-2021-44716
- Introduce patch to address CVE-2021-44716
**NO**
- #9737
- https://nvd.nist.gov/vuln/detail/CVE-2024-37298
- Pipeline build id: [PR-9917](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=611000&view=results)

libcontainers-common: introduce patch to address CVE-2024-37298

---

SPECS/terraform/CVE-2024-6257.patch
SPECS/terraform/terraform.spec

---
Patch CVE-2024-6257
go-getter versions until 1.7.4 is affected. Version 1.7.5 fixes the issue.
The patch is based on the diff between release tags 1.7.4 & 1.7.5.
Reference:
https://discuss.hashicorp.com/t/hcsec-2024-13-hashicorp-go-getter-vulnerable-to-code-execution-on-git-update-via-git-config-manipulation/68081
https://github.com/hashicorp/go-getter/compare/v1.7.4...v1.7.5
- Add patch for CVE-2024-6257
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-6257

Add Patch in terraform for CVE-2024-6257.

---

.github/workflows/check-circular-deps.yml

---
The toolchain download massively benefits from running with high parallelism, so set -j30 in the circular deps check. We also now have an automatic way to calculate lkg, so use that.
The circular dependency check is the long pole PR gate currently, this should shave ~1.5 minutes (out of 5).
- `check-circular-deps.yml` uses `-j30` for faster toolchain download
- `check-circular-deps.yml` uses new `DAILY_BUILD_ID=lkg` mechanism
**NO**
- Run GitHub actions for this PR.

Make check-circular-deps.yml faster with -j, use lkg

---

toolkit/scripts/imggen.mk
toolkit/scripts/pkggen.mk
toolkit/tools/scheduler/scheduler.go
toolkit/tools/scheduler/schedulerutils/buildworker.go
toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
toolkit/tools/scheduler/schedulerutils/pkglicensechecker.go
toolkit/tools/scheduler/schedulerutils/printresults.go

---
The license checker added in https://github.com/microsoft/azurelinux/pull/9060 needs to be integrated into the day-to-day build process. Currently its configured to operate with warnings only, since there are a lot of packages with licensing issues.
This change adds two integrations:
- Package build
- As each node in the graph is processed, pass the associated RPMs to an instance of the `LicenseChecker`. The rpms are copied into a working directory and the scan is run. Each scan returns intermediate data (yes/no for errors & warnings) while the actual results are accumulated in the `LicenseChecker`. Once the full graph has been built the results are saved to a .json file and a …

Integrate new license checker package into image and package builds.

---

toolkit/scripts/toolchain.mk
toolkit/scripts/toolchain/download_toolchain_rpm.sh

---
In preparation for a new explicit validation mechanism break out the toolchain downloader logic into a real script.
The new script will handle the logic that was previously baked into the makefile, while also addressing the issue of log overwriting.
- Move toolchain download logic into `download_toolchain_rpms.sh`
**YES**
- #xxxx

Better toolchain downloader

---

SPECS/golang/CVE-2024-24790.patch
SPECS/golang/golang-1.18.spec
SPECS/golang/golang.signatures.json
SPECS/golang/golang.spec
cgmanifest.json

- [ x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`) …

Upgrade default golang to 1.22.5 and backport the fix for 1.18

---

toolkit/tools/internal/file/file.go
toolkit/tools/internal/file/filecopybuilder.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/infinite-file-config.yaml

1. When calling `cp`, include the last line of `stderr` in the error message.
2. Ensure that the `file.CopyDir` function adds useful information to the error message.
3. Add path information to error message for `.os.additionalDirs` errors.
---
NO
- Added image customizer UTs.

Image Customizer: Improve copy directory error message.

---

SPECS/coreutils/coreutils.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
coreutils brings in libselinux which causes dependency cycle when combined with [this PR](https://github.com/microsoft/azurelinux/pull/9977).
Change imported from fedora.
- Change: Remove runtime requires on libselinux for coreutils
libselinux is no more a requirement similar to what we seen in fedora's runtime requirement.
Previously we had an unnecessary requires on libselinux as show in the diagram below. 
**YES/NO**
YES
- Pipeline build id: [615339](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615339&view=results)
- Toolchain build: [615347](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=6153 …

Remove unnecessary Requires:libselinux from coreutils to fix Circular dependency

---

toolkit/tools/imagecustomizer/README.md
toolkit/tools/imagecustomizer/container/Dockerfile.mic-container
toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml

1. Use either the `grub-install` or `grub2-install` command, whichever is available on the build host.
2. Add `grub2-install` to the image customizer prerequisites list in the README.
3. Add `grub2-install` to the image customizer container.
4. Remove the `grub2` package from the legacy boot config, since it isn't needed.
5. Allow the `USER` environment variable to be empty, which is the case in docker containers.
---
NO
- Added image customizer UT.

Image Customizer: Fixes for grub2-install.

---

toolkit/tools/internal/systemd/systemd.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go

Add tests for enabling and disabling services, both for services that exist and ones that don't exist.
Also, fix a bug in the `IsServiceEnabled` function where the disabled state isn't being properly distinguished from other types of errors.
---
NO
- Added UTs.

Image Customizer: Add tests for services enable/disable.

---

toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go

In PR #9932, a bug fix was made to ensure that GPT partitions don't receive a default label of "primary". Unfortunately, that change relies on a bug fix to `parted` that was made in v3.5, which is relatively recent.
For reference:
- Ubuntu 22.04: 3.4
- Ubuntu 24.04: 3.6
- Azure Linux 2.0: 3.4
- Azure Linux 3.0: 3.6
This change provides a workaround by giving partitions a default name of "primary", if the build host has an older version of parted.
---
NO
- Ran image customizer UTs on Ubuntu 22.04 and Mariner 2.0.

Fix call to `parted mkpart`.

---

toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go

PR #9944 and #9978 were merged at the same time but had a hidden merge conflict.
---
NO
- Ran image customizer UTs.

Image Customizer: Fix merge in 'TestCustomizeImagePartitionsLegacy'.

---

.github/workflows/check-circular-deps.yml

Forgot to remove the old, limiting -j flag from `check-circular-deps.yml`
---
Forgot to remove the old `-j$(nproc)` from https://github.com/microsoft/azurelinux/commit/806d57df3639d423321a958823d9a52b8b1288de
- Remove old `-j` flag from ` check-circular-deps.yml`
**NO**

Remove old -j flag from check-circular-deps.yml

---

toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt
toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
Update the copy of msopenjdk in the toolchain to version "msopenjdk-17-17.0.12-1" from the 3.0 Prod repo on PMC.
Add a sha256 hash verification of the downloaded RPM.
- Change msopenjdk to version msopenjdk-17-17.0.12-1
- Add hash verification step
- Move msopenjdk RPM download to the beginning of toolchain script, before compiling other packages.
**YES**
- Delta build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615511&view=results

msopenjdk: update to latest prod version and add hash verification

---

SPECS/skopeo/CVE-2024-6104.patch
SPECS/skopeo/skopeo.spec

---
Fixes CVE-2024-6104 in github.com/hashicorp/go-retryablehttp with a patch
- Fix CVE-2024-6104 in github.com/hashicorp/go-retryablehttp with a patch
**NO**
- #xxxx
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615788&view=results

Fix CVE-2024-6104 in skopeo  with a patch - 3.0

---

SPECS/frr/frr.signatures.json
SPECS/frr/frr.spec
cgmanifest.json

---
Bump version to 9.1.1 to fix CVE-2024-31950 & CVE-2024-31951
https://github.com/FRRouting/frr/releases/tag/frr-9.1.1
- bump version
- update cgmanifest entry
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-31950
- https://nvd.nist.gov/vuln/detail/CVE-2024-31951
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=617196&view=results)
[install failure due to known libcrypto.so.3()(64bit) issue]

Bump frr to 9.1.1 to fix CVE-224-31950 & CVE-2024-31951

---

SPECS/valgrind/valgrind.signatures.json
SPECS/valgrind/valgrind.spec
cgmanifest.json

---
Catching-up the 3.0 version of `valgrind` with the one in 2.0.
No.
- [Buddy build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=617325&view=results)

Upgraded `valgrind` to version 3.22.0.

---

toolkit/resources/manifests/package/local.repo

---
`tdnf` has been updated to support priorities. As part of this it appears to have changed its behavior when selecting packages. To try and get our old behavior back lets use priorities in our local repo definitions. 
Lower number is higher priority, so set the toolchain lowest, followed by local repo, followed by cache.
- Add explicit priorities to `local.repo` for package builds.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53064337
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=616897&view=results

Add priorities to local repos

---

SPECS/dracut/0013-revert-fix-crypt-unlock-encrypted-devices-by-default.patch
SPECS/dracut/dracut.spec

A change to dracut in v102 (https://github.com/dracut-ng/dracut-ng/commit/2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1) made root decryption fail when booting an image with root partition encrypted. Normally, user is prompted for a password to unlock the encrypted partition during boot. With the above change in v102, no prompt is shown during initrd and eventually the boot fails. The commit is already reverted upstream and is supposed to appear in dracut v104. Adding this patch to revert the change in the meantime.
For CVM images, auto unlock of root partition with TPM enrollment also does not work, likely due to this bug.
- Upstream bug: https://github.com/dracut-ng/dracut-ng/issues/492
- https://microsoft.visualstudio.com/OS/_workitems/edit/51090393

dracut: add fix for initrd not showing prompt when root device is locked

---

SPECS/WALinuxAgent/0001-add-azurelinux-support.patch
SPECS/WALinuxAgent/0002-fix-bump-version-to-2.11.8.8.patch
SPECS/WALinuxAgent/WALinuxAgent.signatures.json
SPECS/WALinuxAgent/WALinuxAgent.spec
SPECS/WALinuxAgent/ephemeral-disk-warning.service
SPECS/WALinuxAgent/fix-argument-to-goalstate.patch
cgmanifest.json

---
Upgrade WALinuxAgent to the most recent release - 2.11.1.4.
Add patch to include azurelinux support into the agent. The patch should
be removed in the next 2.12 update.
Also because WALinuxAgent will automatically update at runtime, thus
removing the patched-in support for azurelinux, add another patch to
bump the version to 2.11.8.8 so further 2.11 hotfixes are not taken.
Since 2.12 will have azurelinux support, the agent will be able to
automatically upgrade to 2.12 at runtime.
fix: correct changelog date warning
fix: use /usr/bin and /usr/lib/systemd paths 
In the upstream code's setup.py, the bin path and systemd path are set
through calls into the distro's osutil class. In …

fix: upgrade walinuxagent to 2.11.1.4 and add azurelinux patch

---

SPECS/influxdb/CVE-2024-6104.patch
SPECS/influxdb/influxdb.spec

---
Fix CVE-2024-6104 in influxdb by patching vendor gomodule
- Fix CVE-2024-6104 in influxdb by patching vendor gomodule
**NO**
- Pipeline build id: [615599](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615599&view=results)

Fix CVE-2024-6104 in influxdb by patching vendor gomodule

---

SPECS/postgresql/postgresql.spec

---
Fix package build errors seen in the following packages: `apr-util` `cyrus-sasl` `python-psycopg2` `sysbench`
These packages all depend on `postgresql` and hit the following errors during preinstall due to missing the groupadd/useradd programs (from `shadow-utils`)
```
"/var/tmp/rpm-tmp.B3ftfS: line 3: /sbin/groupadd: No such file or directory"
"/var/tmp/rpm-tmp.B3ftfS: line 7: /sbin/useradd: No such file or directory"
"error: %prein(postgresql-16.3-2.azl3.x86_64) scriptlet failed, exit status 127"
"error: postgresql-16.3-2.azl3.x86_64: install failed"
```
- Change postgresql to add requirements
**NO**
- Buddy build: …

postgresql: add requires for shadow-utils

---

SPECS/dracut/0013-revert-fix-crypt-unlock-encrypted-devices-by-default.patch
SPECS/dracut/dracut.spec

Signed-off-by: Thien Trung Vuong <tvuong@microsoft.com>
(cherry picked from commit c6b19b50301ead2dd853d1051129a1f1c53cfc84)

dracut: add fix for initrd not showing prompt when root device is locked (#10039)

---

SPECS/nghttp2/nghttp2.signatures.json
SPECS/nghttp2/nghttp2.spec
cgmanifest.json
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
- **nghttp2: upgrade version 1.59.0 -> 1.61.0 to address CVE-2024-28182**
- **nghttp2: upgrade version 1.59.0 -> 1.61.0 to address CVE-2024-28182**
**Yes**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-28182
- Local build
- Pipeline build id: [PR-10064](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618260&view=results)

nghttp2: upgrade version 1.59.0 -> 1.61.0 to address CVE-2024-28182

---

SPECS/vim/CVE-2024-41957.patch
SPECS/vim/CVE-2024-41965.patch
SPECS/vim/fix_save_unnamed_buffer_correctly.patch
SPECS/vim/vim.spec

---
Add patch to resolve CVE-2024-41957 & CVE-2024-41965
Reference
[GHSA-f9cr-gv85-hcr4](https://github.com/vim/vim/security/advisories/GHSA-f9cr-gv85-hcr4)
[GHSA-46pw-v7qw-xc2f](https://github.com/vim/vim/security/advisories/GHSA-46pw-v7qw-xc2f)
- Add patch files
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-41957
- https://nvd.nist.gov/vuln/detail/CVE-2024-41965
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618901&view=results)

vim: Add patch to resolve CVE-2024-41957 & CVE-2024-41965

---

SPECS/azcopy/azcopy.signatures.json
SPECS/azcopy/azcopy.spec
cgmanifest.json

Cherry-picked from https://github.com/microsoft/azurelinux/pull/9581
Buddy Build Link: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=617231&view=results

azcopy: upgrade version to 10.25.1 to fix CVE-2024-35255

---

toolkit/scripts/containerized-build/create_container_build.sh
toolkit/scripts/containerized-build/resources/azl-3_repo
toolkit/scripts/containerized-build/resources/azl.Dockerfile
toolkit/scripts/containerized-build/resources/macros.with-check
toolkit/scripts/containerized-build/resources/setup_functions.sh

---
This change simplifies the `containerized-rpmbuild` scripts in a few ways, which makes it easier to maintain and simpler to use.
1. Completely remove `azl-3_repo` and the associated settings. It ends up being the same as the "real" repo, so it only added complexity.
2. Switched from using a `MACROS` environment variable that wrapper functions like `rpmspec` and `rpm` had to use in favor of a `macros.with-check` file that gets copied to the appropriate place and does the same thing without the need to use the environment variable. This allowed me to completely remove the `rpmspec` wrapper function.
3. Similar with `TDNF_ARGS`. Since we no longer need to point to `azl-3_repo`, all …

containerized-rpmbuild: switch up strategy for defaults and return command exit codes

---

SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
toolkit/tools/internal/tdnf/tdnf.go

---
`tdnf provides <pkgname>` is used to find non-obvious requirements for the build (ie mapping `cap(thing)` to `thing-pkg`). `tdnf` will switch to case-insensitive matching if it can't find a result (`perl(mypkg)` will match with `perl(MyPkg)`), but this isn't actually a valid result. We convert these results into an actual `*.rpm` file path and expect future steps to be able to install this package to satisfy the requirement. During package build, we may never need to install a package so this (i.e. its a runtime requirement of a node which is never itself used in another build). Only at image generation time (or ad-hoc install by a user) will the lack of valid dependency be …

Ignore bogus case-insensitive provides results from repocloner

---

SPECS/packer/CVE-2024-6104.patch
SPECS/packer/packer.spec

---
Fix CVE-2024-6104 by patching vendor gomodule
- Fix CVE-2024-6104 by patching vendor gomodule
**NO**
- Pipeline build id: [615285](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615285&view=results)

Fix CVE-2024-6104 in Packer by patching vendor gomodule

---

SPECS/prometheus/CVE-2024-6104.patch
SPECS/prometheus/prometheus.spec

---
Fix CVE-2024-6104 by patching vendor gomodule
- Fix CVE-2024-6104 by patching vendor gomodule
**NO**
- Pipeline build id: [615287](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615287&view=results)

Fix CVE-2024-6104 in Prometheus by patching vendor gomodule

---

SPECS/rook/CVE-2024-6104.patch
SPECS/rook/rook.spec

---
Fix CVE-2024-6104 in rook by patching vendor gomodule
- Fix CVE-2024-6104 in rook by patching vendor gomodule
**NO**
- Pipeline build id: [615291](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615291&view=results)

Fix CVE-2024-6104 in rook by patching vendor gomodule

---

SPECS/cri-o/CVE-2024-6104.patch
SPECS/cri-o/cri-o.spec

---
Fix CVE-2024-6104 in cri-o by patching vendor package source
- Add new patch to fix CVE-2024-6104 in cri-o package
**NO**
- Pipeline build id: [615191](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615191&view=results)

Fix CVE-2024-6104 in cri-o by patching vendor package source

---

SPECS/influxdb/CVE-2024-6104.patch
SPECS/influxdb/influxdb.spec

---
Fix CVE-2024-6104 in influxdb by patching vendor package source
- Patch gomodule which is a dependency of influxdb
**NO**
- Pipeline build id: [615196](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615196&view=results)

Fix CVE-2024-6104 in influxdb by patching vendor package source

---

.pipelines/prchecks/PackageBuildPRCheck.yml

---
Manual cherry-pick of fast-track's #9795.
No.
- #9795
- PR check runs for #9795.

Disabled PR check debug mode by default. (CP: #9795)

---

toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/storage_test.go
toolkit/tools/pkg/imagecustomizerlib/typeConversion.go

Add a pre-check for the case where a partition is specified but there isn't a corresponding filesystem entry. This both reports the problem earlier and provides a more useful error message.
---
NO
- Added new UT.
- Ran existing UTs.

Image Customizer: Improve error message for missing filesystem entry.

---

toolkit/docs/formats/imageconfig.md
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt

---
In https://github.com/microsoft/azurelinux/pull/9037/files#diff-4399971797c1c0942b710773d3f583fb0c697de6dd1edc655a5b80e4e1f79462R169 we accidentally dropped the `openssl` command line tools from the chroot environment. This won't have affected most packages since they will be using `openssl-devel`, or have explicit `BuildRequires: openssl`, but it DOES affect offline image build (since that uses the chroot as an isolation layer). A call to `openssl passwd ...` to hash a plain-text password from the user would fail with `exec: "openssl": executable file not found in $PATH`. (But only for aarch64, we install `grub2-pc` https://github.com/microsoft/azurelinux/blob/0f0a7df7243ed42e376 …

Fix error when doing password hashing for aarch64 offline image builds

---

toolkit/tools/pkg/imagecustomizerlib/customizeos.go
toolkit/tools/pkg/imagecustomizerlib/installedkernelcheck.go
toolkit/tools/pkg/imagecustomizerlib/installedkernelcheck_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/no-kernel-config.yaml

Add a check to ensure the user didn't uninstall the kernel package without installing a substitute package.
---
NO
- Added UT.

Image Customizer: Add check for installed kernel.

---

toolkit/tools/internal/rpm/rpm.go
toolkit/tools/internal/rpm/rpm_test.go

---
Don't include the epoch when deriving the cached rpm paths for conflicting rpms in `WhatProvides()`. Previously we would do:
`D: ========== +++ perl-4:5.34.1-489.cm2 x86_64-linux 0x0` -> `perl-4:5.34.1-489.cm2.x86_64`, but actual rpms don't include the epoch. We want:
`perl-5.34.1-489.cm2.x86_64` instead.
This results in the build scheduler thinking some of these rpms are missing, since its looking for files that include the epoch.
- Remove epoch from rpm names generated by `ResolveCompetingPackages()`
**NO**
- https://teams.microsoft.com/l/message/19:2ba2ab8d23224ab88eadf431ebee29c1@thread.v2/1721255564669?context=%7B%22contextType%22%3A%22chat%22%7D
- Local testing only, was …

Don't include epoch in rpm name when resolving conflicts

---

toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/disk.go
toolkit/tools/imagecustomizerapi/disk_test.go
toolkit/tools/imagecustomizerapi/disksize.go
toolkit/tools/imagecustomizerapi/disksize_test.go
toolkit/tools/imagecustomizerapi/storage_test.go

For disks partitioned with the GPT partitioning scheme, the last few sectors of the disk are used for storing the GPT footer (which contains the backup partition table). The Image Customizer tool does fail if you try to use this space for a partition, but only because `parted` is doing the check. This change properly accounts for this footer in the config validation, so that a nicer error message can be provided to the user.
---
NO
- Fixed existing UTs.

Image Customizer: Account for GPT footer when validating partitions.

---

SPECS/libtiff/CVE-2024-7006.patch
SPECS/libtiff/libtiff.spec

---
- This PR addresses CVE-2024-7006 in libtiff by patching the vulnerable code in the `tif_dirinfo.c` and `tif_dirread.c` files. The patch checks the return value of `_TIFFCreateAnonField()` to prevent a NULL pointer dereference and ensure the function is called correctly.
- https://gitlab.com/libtiff/libtiff/-/issues/624
- https://gitlab.com/libtiff/libtiff/-/merge_requests/560
- Patch CVE-2024-7006
**NO**
- https://gitlab.com/libtiff/libtiff/-/issues/624
- https://nvd.nist.gov/vuln/detail/CVE-2024-7006
- Buddy build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=621952&view=results

Patch CVE-2024-7006 in libtiff

---

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
cgmanifest.json

---
Updates SymCrypt-OpenSSL to 1.5.0 with bugfixes for TPM2 libraries.
- Fixes bugs found when using the SymCrypt provider for TPM2 operations
- Allow export of ECC key X and Y coordinates, which tpm2-tss needs
- Fix the AES-CFB interface to behave the same as the OpenSSL default provider
NO
- Local build, tested on AZL3 Hyper-V VM

Update SymCrypt-OpenSSL to 1.5.0

---

SPECS/unbound/CVE-2024-43168.patch
SPECS/unbound/unbound.spec

---
- This PR addressed CVE-2024-43168 in unbound
- A heap-buffer-overflow flaw was found in the cfg_mark_ports function within Unbound's config_file.c, which can lead to memory corruption
- CVE-2024-43168
**NO**
- https://github.com/NLnetLabs/unbound/issues/1039
- https://nvd.nist.gov/vuln/detail/CVE-2024-43168
- Buddy build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=622700&view=results

Add patch for CVE-2024-43168 in unbound

---

SPECS/perl-HTTP-Message/perl-HTTP-Message.spec
SPECS/pyOpenSSL/pyOpenSSL.signatures.json
SPECS/pyOpenSSL/pyOpenSSL.spec
SPECS/python-pytest-mock/fix__test_failure_message.patch
SPECS/python-pytest-mock/python-pytest-mock.spec
cgmanifest.json

---
Fix several ptest failures.
- `perl-HTTP-Message` was missing two `BuildRequires` for the check section
- `python-pytest-mock` relies on the format of messages from `Python`, this message changed in `3.11.7`. Backport the fixes to our version so it works with our version of `Python`.
- `pyOpenSSL` has a dependency on `python-cryptography`, we updated `python-cryptography` beyond what our version of `pyOpenSSL` supports so update to a newer version based on F41.
**NO**
- ~https://dev.azure.com/mariner-org/mariner/_build/results?buildId=623323&view=results~ https://dev.azure.com/mariner-org/mariner/_build/results?buildId=623347&view=results

Fix tests for perl-HTTP-Message, python-pytest-mock, upgrade pyOpenSSL

---

toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/internal/userutils/main_test.go
toolkit/tools/internal/userutils/passwdfile.go
toolkit/tools/internal/userutils/passwdfile_test.go
toolkit/tools/internal/userutils/testdata/etc/passwd
toolkit/tools/internal/userutils/userutils.go
toolkit/tools/internal/userutils/userutils_test.go

When populating the `.ssh/authorized_keys` path, the toolkit currently assumes the standard home directory path is being used. This is particularly unfortunate given that the toolkit supports overridding the home directory when creating a user. This change pulls the home directory from the `/etc/passwd` file.
---
NO
- Added UTs.

Toolkit: Respect overridden home directory for .ssh path.

---

SPECS/openssh/openssh-8.2p1-visibility.patch
SPECS/openssh/openssh.spec

---
Fixing the ptests for `openssh`. Switching to building with `-fvisibility=hidden` caused issues building a dummy test library.
No.
- Local build.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=623239&view=results).

Fixed `openssh` ptests.

---

SPECS/e2fsprogs/e2fsprogs.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Fix `e2fsprogs` package tests by removing a known failing test. According to [Linux from Scratch](https://www.linuxfromscratch.org/lfs/downloads/stable/LFS-BOOK-12.1-NOCHUNKS.html#ch-system-e2fsprogs), the `m_assume_storage_prezeroed` test is bad:
```
"One test named m_assume_storage_prezeroed is known to fail."
```
See also:
https://lfs.fsf.org.cn/lfs/errata/11.3/
https://github.com/tytso/e2fsprogs/issues/134
- remove known-bad ptest in e2fsprogs
**YES**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=624595&view=results

e2fsprogs: fix ptest

---

SPECS/WALinuxAgent/WALinuxAgent.spec
SPECS/WALinuxAgent/update-setup.patch

---
Add patch to update WALinuxAgent's setup.py to support azurelinux
**NO**
- Pipeline build id: [622170](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=622170&view=results)

fix: add patch in WALinuxAgent to update setup.py to support azurelinux

---

toolkit/imageconfigs/packagelists/azurevm-packages.json

---
Azure Linux marketplace image definitions by default should provide all the memory to the user. However since kexec-tools is installed, the crashkernel= boot parameter is added to reserve a certain amount of memory for the kdump kernel. This results in a loss of usable memory for the user, especially if kdump is not armed or being used.
The use of kdump is an opt-in choice by the user, so this change removes pre-loading kexec-tools altogether from the Azure Linux VM images.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53162418

feat: remove kexec-tools from azure vm definition

---

SPECS/avahi/avahi.spec

---
avahi-daemon hangs in libssp when built with libssp support enabled. SSP support is dynamically set when avahi's configure scans the current build environment for the presence of the standalone libssp built by gcc.
This standalone implementation of libssp is generally obsoleted in most modern systems, and instead the libc's implementation of SSP is used.
So we will remove the libssp files from here if we find they are present. Avahi's configure will instead use glibc's ssp implementation which does not hang and is proper.
**NO**
- #10013
-  https://dev.azure.com/mariner-org/ECF/_workitems/edit/7073 …

fix: remove libssp files to fix avahi hang

---

SPECS/tensorflow/CVE-2023-33976.patch
SPECS/tensorflow/tensorflow.spec

---
- This PR addresses CVE-2023-33976 - `array_ops.upper_bound` causes a segfault when not given a rank 2 tensor
- CVE-2023-33976
**NO**
- https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gjh7-xx4r-x345
- https://nvd.nist.gov/vuln/detail/CVE-2023-33976
- Buddy build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=622613&view=results

Add patch for CVE-2023-33976 in tensorflow

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageBuild.yml
toolkit/Makefile
toolkit/scripts/pkggen.mk
toolkit/tools/scheduler/schedulerutils/buildworker.go

---
We have some flaky ptests in our set of packages. During daily builds we re-run them once in an attempt to separate most of such tests from constantly failing ones. This change aligns the PR check with the behaviour of the daily builds.
No.
- PR check.

Set ptest retries to 1 for PR package build check.

---

toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/internal/userutils/groupfile.go
toolkit/tools/internal/userutils/shadowfile.go
toolkit/tools/internal/userutils/userutils.go
toolkit/tools/pkg/imagecustomizerlib/customizeusers.go
toolkit/tools/pkg/imagecustomizerlib/customizeusers_test.go

Add tests for installing and updating users.
This change include parsers for the /etc/group and /etc/shadow files, so that it is easier for the tests to verify the contents of these files.
In addition, this change includes some minor cleanup to error messages and logging.
---
NO
- Added UT.

Image Customizer: Add tests for users API.

---

toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/extractpartitions.go
toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go

It seems that in most cases, the lsblk and fdisk commands output partitions in the correct order. But this isn't actually guaranteed and there have been user reports of unusual errors that are the result of assuming this is the case. This change fixes the code so that it is agnostic to the ordering of the partitions.
---
NO
- Ran UTs.

Image Customizer: Be robust to lsblk and fdisk output ordering.

---

toolkit/scripts/update_manifest.sh

---
There are situations where the calling username may not have an assotiated group name. Call chown without explicitly setting the group name and leave the group ownership the same.
- Leave default group in place
**YES**
-Prior to change
```
Manifests are the same, not updating toolchain_x86_64.txt
Running update_manifest.sh as azaugg
2024-08-21 19:29:47 URL:https://mariner3dailydevrepo.blob.core.windows.net/lkg/2024-08-21-3.0-dev.json [332/332] -> "/home/azaugg/CBL-Mariner/build/daily_build_id/2024-08-21-3.0-dev.json.V87Yhf" [1]
Checking for updates to pkggen_core_x86_64.txt manifest from https://raw.githubusercontent.com/microsoft/CBL-Mariner/ce47a7432e5e86214aa034dbe39fa935f4bbec …
```

Toolkit bugfix: update_manifest.sh group name may not allways exist

---

SPECS/moby-cli/CVE-2023-45288.patch
SPECS/moby-cli/moby-cli.spec

---
Add patch to resolve CVE-2023-45288
NO
- #xxxx

moby-cli: Add patch to resolve CVE-2023-45288

---

SPECS/libsndfile/CVE-2022-33065.patch
SPECS/libsndfile/libsndfile.spec

---
Add patch to resolve CVE-2022-33065
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-33065
- Pipeline build id:[ Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=626766&view=results)

libsndfile: Add patch to resolve CVE-2022-33065

---

toolkit/scripts/toolchain.mk

---
When using the Docker compatible reusable chroots (`CHROOT_DIR=...`), a number of mount points need to be established external to the toolkit. One set is `./build/toolchain_rpms{x86_64,aarch64,noarch}:chroot-1/toolchainrpms/{x86_64,aarch64,noarch}` (and similar for other chroots).
As part of #9899 and #9963 the `$(STATUS_FLAGS_DIR)/toolchain_auto_cleanup.flag` was added which removes all toolchain rpms from the repo folder `./build/toolchain_rpms` (to remove the chance of unexpected conflicts with signatures or validation state). It simply removed the outer `./build/toolchain_rpms` directory, breaking the mountpoints in the docker environment.
Oddly, as the build runs, it …

Toolkit: Fix readdirent toolchain errors for reusable chroots

---

SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
SPECS/systemd/systemd.spec
SPECS/systemd/use-none-scheduler.patch

---
On Azure, it is recommended to use an i/o scheduler that passes the scheduling decisions to the underlying Hyper-V hypervisor. In our case, we should use the "none" scheduler, which is also ideal for fast random I/O devices like NVMe. So we update Fedora's bfq patch to change the udev rule to select "none" instead of Fedora's default Budget Fair Queuing (bfq) and rename the patch from referencing "bfq" to "none".
https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-for-running-linux-on-hyper-v#use-io-scheduler-noopnone-for-better-disk-io-performance
**NO**
- …

fix: change bfq patch to select "none" scheduler as default

---

SPECS/ceph/ceph.spec

---
ceph fails to install in environments where shadow-utils is missing.  This change adds a dependency to shadow-utils
**NO**
Buddy built shadow-utils

Add missing shadow-utils requirement to ceph

---

SPECS/jx/CVE-2023-45288.patch
SPECS/jx/jx.spec

---
Add patch to resolve CVE-2023-45288
NO
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=626018&view=results)

jx: Add patch to resolve CVE-2023-45288

---

SPECS/nfs-utils/nfs-utils.spec

---
Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service
In NFS rpc.svcgssd and rpc.gssd play crucial roles in providing security through the RPCSEC_GSS protocol.
**rpc.svcgssd**
Role: This is the server-side daemon responsible for handling security context establishment on the NFS server.
Function: It communicates with the Linux kernel to manage security contexts for incoming RPC requests. This ensures that the server can authenticate and authorize clients securely.
**rpc.gssd**
Role: This is the client-side daemon that manages security contexts for the NFS client.
Function: It interacts with the NFS server on …

Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service

---

SPECS/nfs-utils/nfs-utils.spec

---
Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd
In NFS rpc.svcgssd and rpc.gssd play crucial roles in providing security through the RPCSEC_GSS protocol.
**rpc.svcgssd**
Role: This is the server-side daemon responsible for handling security context establishment on the NFS server.
Function: It communicates with the Linux kernel to manage security contexts for incoming RPC requests. This ensures that the server can authenticate and authorize clients securely.
**rpc.gssd**
Role: This is the client-side daemon that manages security contexts for the NFS client.
Function: It interacts with the NFS server on behalf of …

Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd

---

SPECS/cert-manager/CVE-2024-6104.patch
SPECS/cert-manager/cert-manager.spec

---
Fix CVE-2024-6104 in cert-manager by patching vendor gomodules
- Fix CVE-2024-6104 in cert-manager by patching vendor gomodules
**NO**
- Pipeline build id: [629162](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=629162&view=results)

Fix CVE-2024-6104 in cert-manager by patching vendor gomodules

---

toolkit/Makefile

---
The new toolchain validation step relies on `$(TOOLCHAIN_GPG_VALIDATION_KEYS)` to check the toolchain rpms against. This variable is by default a list of gpg keys from `./SPECS/azurelinux-repos/`. 
When using `make package-toolkit` these keys are included in `./toolkit/repos`. The search is `$(wildcard $(PROJECT_ROOT)/SPECS/azurelinux-repos/MICROSOFT-*-GPG-KEY) $(wildcard $(toolkit_root)/repos/MICROSOFT-*-GPG-KEY)`.
This works well for common use cases, but if the user selects a custom `SPECS_DIR=...` with the core repo the validation will fail. Instead use `$(PROJECT_ROOT)/SPECS` which is a stable directory (similar to https://github.com/microsoft/azurelinux/blob/9f8d0fad669392e8 …

fix: use static search path for toolchain GPG keys during validation

---

SPECS/cloud-hypervisor-cvm/0001-hypervisor-mshv-Fix-panic-when-rejecting-extended-gu.patch
SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec

---
This change adds a patch file for an upstream commit that resolves a CLH crash that occurs when attempting to retrieve the extended attestation report.
- Add patch: [hypervisor: mshv: Fix panic when rejecting extended guest
report](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/ca88d4449e843ddb69d72a3908e7447d536517e2)
**NO**
- PR: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6682
- N/A
- Internal validation based on e2e tests
- Minimal binary that queries (extended) attestation reports

cloud-hypervisor-cvm: Add upstream patch to prevent crash when SEV-SNP guest queries ext. att. report

---

SPECS/nghttp2/nghttp2.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
In 3.0 we've modified the toolkit to not ignore the casing of the package dependencies. This is by design and it broke test builds for `nghttp2`, which declares a dependency on `cunit`, where in reality the package is called `CUnit`. Fixing this here.
Yes.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=630875&view=results).
- Local build.

Fixed `nghttp2` test-time dependency on `CUnit`.

---

SPECS/nbdkit/nbdkit.spec

---
In 3.0 we've changed the file paths for files provided by `iproute`, which included a switch from `/sbin/ss` to `/usr/sbin/ss`. We've missed updating a test-time dependency on `/sbin/ss` in `nbdkit`, however. Fixing this here.
**NOTE**: `nbdkit` ptest failures are a known issue and not a regression. Fixing them will be done in a separate PR.
No.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=630900&view=results).

Fixed `nbdkit` test-time dependency on `/sbin/ss`.

---

SPECS/ocaml-base/ocaml-base.spec
SPECS/ocaml-cinaps/ocaml-cinaps.spec
SPECS/ocaml-sexplib/ocaml-sexplib.spec

---
Fix missing dependencies when running tests with ocaml packages.
- ocaml-base: remove unneeded test dependencies
- ocaml-cinaps: disable check section
- ocaml-sexplib: remove unneeded test dependencies
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53283659
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=631054&view=results

fix ocaml test issues

---

.pipelines/templatesWithCheckout/SodiffCheck.yml
toolkit/scripts/analysis.mk
toolkit/scripts/sodiff/mariner-sodiff.sh

---
sodiff checks were broken for Azure Linux 3.0. This PR ports the fix which was needed for 2.0 that did not originally make it into 3.0.
2.0 PR here: https://github.com/microsoft/azurelinux/pull/6698
- Add Sodiff debuginfo filtering and adjustments to 3.0
**NO**
- Full build
- ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=630778&view=results
- AMD64:  https://dev.azure.com/mariner-org/mariner/_build/results?buildId=630745&view=results

Filter out debuginfo packages when running sodiff (#6698)

---

SPECS/nss/nss.spec

This change disables building the DBM backend in the NSS library.
For the NSS library and tools, a replacement SQLite database backend has been available since v3.12. The DBM backend has been deprecated since v3.35. Also, the DBM backend code is scheduled for deletion in a future release. As such any found CVEs (e.g. CVE-2017-11695) are being WONTFIXed by upstream.
---
- nss: Disable DBM backend
- CVE-2017-11695
- CVE-2017-11696
- CVE-2017-11697
- CVE-2017-11698
NO
- Built package and dependencies.

nss: Disable DBM backend.

---

SPECS/python-packaging/python-packaging.spec
SPECS/python-pygments/python-pygments.spec
SPECS/python-setuptools/python-setuptools.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt
toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
Rebuild python-packaging in the toolchain to resolve a circular dependency and fix the auto-generated provides for this package.
Before:
```
" Traceback (most recent call last):
"   File "/usr/lib/rpm/pythondistdeps.py", line 22, in <module>
"     from packaging.requirements import Requirement as Requirement_
" ModuleNotFoundError: No module named 'packaging'
" Provides: python-packaging = 23.2-3.azl3 python3-packaging = 23.2-3.azl3 python3.12-packaging = 23.2-3.azl3
```
```
$ rpm -q --provides ../out/RPMS/noarch/python3-packaging-23.2-2.azl3.noarch.rpm
python-packaging = 23.2-2.azl3
python3-packaging = 23.2-2.azl3 …
```

python-packaging: fix provides

---

SPECS/containerized-data-importer/CVE-2022-32149.patch
SPECS/containerized-data-importer/CVE-2022-41717.patch
SPECS/containerized-data-importer/CVE-2024-28180.patch
SPECS/containerized-data-importer/containerized-data-importer.spec

---
- Address CVE-2022-41717
- Address CVE-2022-32149
- Address CVE-2024-28180
- Create patches from upstream commits
- Adjust patch paths and remove paths that are not vendored
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-41717
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=626235&view=results
- fasttrack/2.0: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633961&view=results

cdi:  CVE-2022-41717, CVE-2022-32149, CVE-2024-28180

---

.github/workflows/go-test-coverage.yml
.github/workflows/lint-specs.yml

GitHub actions is complaining that we are using an old, deprecated version of the `actions/upload-artifact` task.
---
NO
- Ran GitHub actions.

GitHub actions: Update version of actions/upload-artifact task

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageBuild.yml
toolkit/Makefile
toolkit/scripts/pkggen.mk
toolkit/tools/scheduler/schedulerutils/buildworker.go

---
We have some flaky ptests in our set of packages. During daily builds we re-run them once in an attempt to separate most of such tests from constantly failing ones. This change aligns the PR check with the behaviour of the daily builds.
No.
- Original PR checks.

Set ptest retries to 1 for PR package build check. (CP: #10133)

---

SPECS/python-pip/CVE-2024-3651.patch
SPECS/python-pip/python-pip.spec
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
CVE-2024-3651 affects idma versions before 3.7. Therefore,
update vendored version of idma in pip to 3.7.
This patch is a combination of 2 upstream commits:
[[d83c9e3](https://github.com/pypa/pip/commit/d83c9e3)] Upgrade idna to 3.6
[[cba5b13](https://github.com/pypa/pip/commit/cba5b13)] Upgrade idna to 3.7
Additionally, python3-wheel and python3-pip are both in the
toolchain so address "TODO" and add python3-wheel as a
BR to fix non-toolchain builds.
Note that python-pip has new versions (such as 24.2) but the 
setup.py script was removed. They removed setup.py here: https://github.com/pypa/pip/commit/0ad4c94be74cc24874c6feb5bb3c2152c398a18e
Therefore, patch CVE directly to …

Patch CVE-2024-3651 for python-pip

---

SPECS/kubevirt/kubevirt.spec

---
The PR looks to address [Bug 8599](https://dev.azure.com/mariner-org/ECF/_workitems/edit/8599?src=WorkItemMention&src-action=artifact_link) raised by Nexus - 
```
When attempting to use launch a kubevirt vm the requires tpm, virt-handler/virt-launcher fails to start with the following error:
spec snippet:
devices:
tpm: {}
features:
smm: {}
firmware:
bootloader:
efi:
secureBoot: true
Results in:
Warning  SyncFailed        2s (x12 over 7s)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=70, Message='Unable to find 'swtpm' binary in $PATH: No such file or directory')"
It seems the …
```

Adding swtpmtools to list of required packages for kubevirt

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageBuild.yml
toolkit/Makefile
toolkit/scripts/pkggen.mk
toolkit/tools/scheduler/schedulerutils/buildworker.go

---
Cherry-picking two PR check changes:
- From 2.0: #8503.
- From 3.0: #10133.
No.
- #8503
- #10133
- PR check.

Enabled ccache and set ptest retries to 1 for PR checks (CP: #8503, #10133)

---

SPECS/vim/CVE-2024-43374.patch
SPECS/vim/vim.spec

---
The Cherry-pick bot did not create the PR for the main merge. Hence the manual cherry-pick PR.
Fix for CVE-2024-43374
CP for #10192.
- Create patch to fix CVE-2024-43374
- Update spec version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-43374
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625113&view=results
- fasttrack/2.0: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633992&view=results

[cherry-pick] vim: CVE-2024-43374 (mariner 2) (#10192)

---

SPECS/kubevirt/CVE-2022-32149.patch
SPECS/kubevirt/CVE-2023-26484.patch
SPECS/kubevirt/kubevirt.spec

---
The Cherry-pick bot did not create the PR for the main merge. Hence the manual cherry-pick PR.
CVE-2022-32149 and CVE-2023-26484
CP for #10232.
- CVE-2022-32149
- CVE-2023-26484: CVE references [kubevirt issue](https://github.com/kubevirt/kubevirt/issues/9109) that refers to 2 independent PRs [11982](https://github.com/kubevirt/kubevirt/pull/11982) and [12009](https://github.com/kubevirt/kubevirt/pull/12009) ... 11982 requires more recent KubeVirt (mariner 2.0 uses 0.59) which uses K8s libraries 0.30 (we use 0.23.5), so only 12009 is used in patch.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-26484
- …

[cherry-pick] kubevirt: CVE-2022-32149 and CVE-2023-26484 (#10232)

---

SPECS/krb5/CVE-2024-26461.patch
SPECS/krb5/krb5.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Fixes CVE-2024-26458 and CVE-2024-26461 in krb5 package
- Patch CVE-2024-26458 and CVE-2024-26461
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-26458
- https://nvd.nist.gov/vuln/detail/CVE-2024-26461
- Pipeline build id: [632804](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=632804&view=results) (The tests fail here because it uninstalls some packages like curl, openssl, etc which have a dependency on krb5 and at the end tdnf as well. This is an expected behaviour)

krb5: Add patch for fixing CVE-2024-26458 and CVE-2024-26461

---

toolkit/tools/imagecustomizer/docs/configuration.md

The 'sshPublicKeys' field is missing from the docs.
---
NO
n/a

Image Customizer: Add doc for 'sshPublicKeys'.

---

toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/disk.go
toolkit/tools/imagecustomizerapi/disk_test.go
toolkit/tools/imagecustomizerapi/partition.go
toolkit/tools/imagecustomizerapi/partition_test.go
toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/storage_test.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-size-only-config.yaml
toolkit/tools/pkg/imagecustomizerlib/typeConversion.go

Allow the partition start to be inferred from the previous partition's end. Also, allow the disk's maxSize to be inferred from the size/end of the last partition.
In addition, since the partition start can now be omitted, require the partitions to be specified in order. Fortunately, most users do this anyway.
---
NO
- Added tests.

Image Customizer: Allow omitting disk maxSize and partition start.

---

toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/filesystemtype.go
toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/storage_test.go
toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml

The FAT filesystem is a tad confusing. Technically, FAT12, FAT16, and FAT32 refer to a fat filesystem with 12, 16, and 32 bit addressing respectively. However, you can't just use FAT32 for everything since each variant has different min and max partition sizes. So, instead you have to dynamically select the correct one based on the partition size. However, a lot of partioning tools (including Windows) hide this complexity and just use 'fat32' to mean either FAT12, FAT16, or FAT32.
There is also VFAT which refers to any FAT filesystem variants where long filename support is enabled. Nowadays it is pretty much always enabled. So, it isn't unusual for tools (including the Linux kernel) to use 'vfat' as a generic term to refer to any of the FAT filesystem variants.
The image customizer tool …

Image Customizer: Add support for 'vfat' filesystem.

---

.github/workflows/go-test-coverage.yml
.github/workflows/lint-specs.yml
SPECS/nbdkit/nbdkit.spec
SPECS/nghttp2/nghttp2.spec
SPECS/ocaml-base/ocaml-base.spec
SPECS/ocaml-cinaps/ocaml-cinaps.spec
SPECS/ocaml-sexplib/ocaml-sexplib.spec
SPECS/python-packaging/python-packaging.spec
SPECS/python-pygments/python-pygments.spec
SPECS/python-setuptools/python-setuptools.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt
toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
A set of cherry-pick from `3.0-dev` to unblock the 3.0 fast-track builds.
No.
- #10289 
- #10290
- #10298
- #10299
- #10349
- PR check.
- Relying on tests in the dev branch.

Applied fixes to unblock 3.0 fast-track builds. (Multiple cherry-picks.)

---

SPECS/wget/0002-normalize-path-in-url.patch
SPECS/wget/0003-Allow-option-no-tcp-fastopen-to-work-on-Linux-kernel.patch
SPECS/wget/0004-Disable-OCSP-by-default.patch
SPECS/wget/0005-Accept-progress-dot-.-for-backwards-compatibility.patch
SPECS/wget/0006-Disable-TCP-Fast-Open-by-default.patch
SPECS/wget/wget.spec

---
Since we upgraded wget for 3.0 with change #7672, upstream Fedora has added several packages that would be useful to us. These include patches that disable `ocsp` and `tcp-fastopen` by default (you can still set them on the command-line). A combination of these two things causes some issues on certain urls when downloading from a local hyper-v vm, and generally we'd rather have them disabled by default.
This change takes all the patches that fedora currently applies to wget.
- Applied patches from fedora upstream.
- Cleaned up some build warnings.
- Stop installing a test-only binary
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=639060&view …

update wget with patches from fedora

---

SPECS/cloud-init/0001-feat-azure-Add-ProvisionGuestProxyAgent-OVF-setting.patch
SPECS/cloud-init/0002-feat-azure-parse-ProvisionGuestProxyAgent-as-bool-51.patch
SPECS/cloud-init/0003-feat-azure-add-support-for-azure-proxy-agent.patch
SPECS/cloud-init/cloud-init.spec

---
Add support for azure proxy agent. Initial [PR](https://github.com/microsoft/azurelinux/pull/9878) was reverted due to failure in ptest. 
Azure Guest Proxy Agent is a new feature in Azure that offers a key exchange protocol to secure communication between guest and host using eBPF.
Add opt-in feature which enables the Azure Guest Proxy Agent when ovf-env.xml has ProvisionGuestProxyAgent=True. Report provisioning failures if ProvisionGuestProxyAgent is enabled but images do not have azure-proxy-agent installed or functional.
- add patch files to support azure-proxy-agent
- remove the headers_cb, mock_report_dmesg_to_kvp, unit tests …

cloud-init add azure proxy agent

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageBuild.yml
.pipelines/templates/PackageTestResultsAnalysis.yml
.pipelines/templates/ToolchainCalculatePackageRetests.yml

---
Backport of #10389.
We have a bug in the PR check where a change to a toolchain package prevents ptest from being run for all non-toolchain packages. This change moves toolchain ptests to a separate job, so the original `BuildAndTest` will build and test only non-toolchain packages.
No.
- PR check.

Separated toolchain tests from non-toolchain package builds.

---

SPECS/libcontainers-common/CVE-2024-3727.patch
SPECS/libcontainers-common/libcontainers-common.spec
SPECS/libcontainers-common/podman-CVE-2024-3727.patch

---
Upstream fix for CVE-2024-3727 was incompatible with the `containers/image` package vendored in this package. 
The patch differs significantly from the [upstream](https://github.com/containers/image/pull/2403/), also have two different versions of `containers/image` vendored` ( podmand has older version). 
- Fix CVE-2024-3727
**NO**
- #xxxx
- Pipeline build id: [Link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=638922&view=results)

Backport CVE-2024-3727 fix for libcontainers-common

---

SPECS/keepalived/CVE-2024-41184.patch
SPECS/keepalived/keepalived.signatures.json
SPECS/keepalived/keepalived.spec
cgmanifest.json

---
Upgrade keepalived and add patch to resolve CVE-2024-41184.
- Upgrade keepalived
- Add patch to resolve CVE-2024-41184
**NO**
- https://github.com/acassen/keepalived/issues/2447#issuecomment-2231329734
- https://nvd.nist.gov/vuln/detail/CVE-2024-41184
- Buddy Build pipeline build id: [639927](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=639927&view=results)

Upgraded keepalived to 2.3.1 and patched CVE-2024-41184.

---

SPECS/wget/fix-ssl-read-and-write-error-check.patch
SPECS/wget/wget.spec

---
With our configuration of `wget2`, which uses the `openssl` `tls` provider, we can get into an infinite loop with certain error conditions. The issue is that for both `SSL_read` and `SSL_open`, a return value of `0` is an error but the code treats it as success.
This is tracked upstream with [this issue](https://github.com/rockdaboot/wget2/issues/342).
- Apply patch to fix error handling in `openssl` `tls` povider.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=641218&view=results
- Installed and tested on a local hyperv vm

update wget to fix potential infinite loop

---

SPECS/ruby/ruby.signatures.json
SPECS/ruby/ruby.spec
cgmanifest.json

---
Upgrade `ruby` to version 3.3.5 to fix CVE-2024-41946. The current version of Ruby (3.3.3) contains the bundled gem `rexml` version 3.2.8 which is affected by this CVE. Upgrading `ruby` to version `3.3.5` increments the version of the bundled gem `rexml` to `3.3.6`, which has the CVE fixed.
- Upgrade ruby to 3.3.5 to fix CVE-2024-41946 by including bundled gem rexml v3.3.6
- Update versions of default gems
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-41946
- Buddy Build Pipeline build id: [637390](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=637390&view=results)
- Buddy Build Pipeline build id: [641262](https://dev.azure.com/mariner-org/mariner/_build/res …

Resolve CVE-2024-41946

---

SPECS/cert-manager/cert-manager.signatures.json
SPECS/cert-manager/cert-manager.spec
cgmanifest.json

Upgrade cert-manager to 1.12.13 to get upstream patches for CVE-2024-25620 and CVE-2024-26147
---
[CVE-2024-26147](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-26147) is fixed in Helm 3.14.2, [CVE-2024-25620](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-25620) is fixed in Helm 3.14.1. Helm is a vendored package used by `cert-manager` package. The current version of `cert-manager` 1.12.12 carries Helm 3.12.0. 1.12.13 of `cert-manager` carries Helm 3.14.2, hence fixing both CVEs. As such, this PR is also removing the custom patch for CVE-2024-25620 that was added into the `cert-manager` spec file.
- Fixes CVE-2024-26147 by updating to 1.12.13
- Removes need for a …

Upgrade cert-manager to 1.12.13 to get upstream patches for CVE-2024-25620 and CVE-2024-26147

---

SPECS/ccache/ccache.spec
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Our ccache package creates a link to a binary not provided by gcc, which caused build breaks in some packages (including php-pecl-apcu). Remove the dangling link, ex: `/usr/lib/ccache/x86_64-pc-linux-gnu-cc -> /usr/bin/ccache`
From config.log generated by the configure script in php-pecl-apcu:
```
"configure:3112: checking for C compiler version"
"configure:3121: x86_64-pc-linux-gnu-cc --version >&5"
"ccache: error: Could not find compiler \"x86_64-pc-linux-gnu-cc\" in PATH"
```
- Remove bad link from ccache
**YES**
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642258&view=results

ccache: remove dangling link to host-cc

---

toolkit/tools/pkg/imagecustomizerlib/grubcfgutils.go
toolkit/tools/pkg/osmodifierlib/modifydefaultgrub.go

---
there is one linux cmdline in grub.cfg in trident verity test images, however, there are 2 linux in regular trident test images, one is recovery mode
- Allow 2 linux cmdline
no
locally tested with sample grub.cfg, 
and with the new function, it only extract linux cmdline object in non recovery mode menuentry:
- Will publish new EMU and test in trident e2e pipeline

OSModifier: allow two linux cmdline in grub.cfg

---

SPECS/wget/set-debug_skip_body-for-OCSP-requests-in-openssl-tls-provider.patch
SPECS/wget/wget.spec

---
`wget` using `openssl` for `tls` (which we compile with), with `--debug` turned on prints the body of `ocsp` requests (if `--ocsp` is specified; it's off by default) to `stderr` even though it's the body is binary.
This change patches `wget` with the [proposed fix](https://github.com/rockdaboot/wget2/pull/345) for [upstream issue](https://github.com/rockdaboot/wget2/issues/344).
- Patch `wget` to fix binary debug spew issue.
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642524&view=results

patch wget to prevent debug output from printing binary request bodies

---

SPECS/xorg-x11-server/CVE-2024-0229.patch
SPECS/xorg-x11-server/CVE-2024-0409.patch
SPECS/xorg-x11-server/CVE-2024-21886.patch
SPECS/xorg-x11-server/xorg-x11-server.spec

---
Add patch for for CVE-2024-0229, CVE-2024-0409 & CVE-2024-21886.
Reference: https://lists.x.org/archives/xorg-announce/2024-January/003444.html
- Add patch files
- lint spec
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-0229
- https://nvd.nist.gov/vuln/detail/CVE-2024-0409
- https://nvd.nist.gov/vuln/detail/CVE-2024-21886

Patch xorg-x11-server for CVE-2024-0229, CVE-2024-0409 & CVE-2024-21886

---

SPECS/kubevirt/kubevirt.spec

---
This PR corrects the path where the SELinux policy virt_launcher.cil is installed in the virt-handler container. A previous commit had incorrectly changed this location, which has caused virt-handler to be unable to find the policy file, resulting in initialization failure of virt-handler.
- Change the installation path of SELinux policy virt_launcher.cil in the virt-handler container
**NO**
- Buddy Build Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=631495&view=results
- RPM built by buddy-build was downloaded and installed on 3.0 container to check that the virt_launcher.cil file exists at the correct location.

[Cherry-pick] Update virt_launcher.cil installation path in virt-handler container

---

SPECS/vim/CVE-2024-41957.patch
SPECS/vim/CVE-2024-41965.patch
SPECS/vim/vim.spec

---
Add patch to resolve CVE-2024-41957 & CVE-2024-41965
Reference
https://github.com/vim/vim/security/advisories/GHSA-f9cr-gv85-hcr4
https://github.com/vim/vim/security/advisories/GHSA-46pw-v7qw-xc2f
- Add patch files
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-41957
- https://nvd.nist.gov/vuln/detail/CVE-2024-41965
- Pipeline build id:[ Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618868&view=results)

vim: Add patch to resolve CVE-2024-41957 & CVE-2024-41965.

---

.pipelines/containerSourceData/scripts/BuildGoldenContainer.sh

---
Use Toolchain RPMS while building GC containers
- Change: Use Toolchain RPMS while building GC containers
**YES/NO**
NO
- Pipeline build id: [642171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642171&view=results)

[3.0] Use Toolchain RPMS when building Golden Container

---

SPECS/cf-cli/CVE-2022-32149.patch
SPECS/cf-cli/cf-cli.spec

Fixes CVE-2022-32149 by backporting the fix as a patch file
---
This PR fixes CVE-2022-32149, which is present in one of the vendored dependencies. The issue was fixed in a single commit, and this PR brings that commit as a patch file. The patch has been modified to accurately reflect the vendored paths and the test file was removed, as it is not part of the vendored files.
- Adds a patch file with a fix for CVE-2022-32149
**NO**

Fixes CVE-2022-32149 by backporting the fix as a patch file

---

toolkit/tools/internal/logger/log.go
toolkit/tools/internal/shell/shell.go
toolkit/tools/pkgworker/pkgworker.go
toolkit/tools/scheduler/buildagents/chrootagent.go
toolkit/tools/scheduler/buildagents/definition.go
toolkit/tools/scheduler/buildagents/testagent.go
toolkit/tools/scheduler/scheduler.go
toolkit/tools/scheduler/schedulerutils/buildworker.go

---
When we queue a package to build (or test), we set a timeout (by default 8h). If the build has not finished by then we forcibly stop the build and mark it as failed.
We also support `PACKAGE_BUILD_RETRIES` and `CHECK_BUILD_RETRIES`, which will cause failed builds to re-run.
However, each time the retry was triggered the timeout would reset. For example in the buddy builds this means that a stuck package test could take 4x8=32h to build, which would exceed pipeline time limits. We want to exit gracefully with an error state so that we can generate and publish logs correctly. If the pipeline forces the timeout, it can be difficult to debug.
Instead of resetting the timeout with …

Fix bad interactions between timeouts and build retires

---

SPECS/gdk-pixbuf2/CVE-2022-48622.patch
SPECS/gdk-pixbuf2/gdk-pixbuf2.spec

---
Add patch for CVE-2022-48622
Even though the build is configured with -Dbuiltin_loaders=png, the `ani` loader is built by default in `gdk-pixbuf/meson.build`
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-48622

Patch gdk-pixbuf2 for CVE-2022-48622.

---

SPECS/cmake/CVE-2023-27533.patch
SPECS/cmake/CVE-2023-27534.patch
SPECS/cmake/cmake.spec
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Patch CVE-2023-27534 in cmake
- CVE-2023-27534
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-27534

Patch CVE-2023-27534 in cmake

---

SPECS/gdk-pixbuf2/CVE-2022-48622.patch
SPECS/gdk-pixbuf2/gdk-pixbuf2.spec

---
Add patch for https://github.com/advisories/GHSA-2pj9-xmx5-6fv3
Even though the build is configured with -Dbuiltin_loaders=png, the ani loader is built by default in gdk-pixbuf/meson.build
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-48622
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=643011&view=results)

Patch gdk-pixbuf2 for CVE-2022-48622

---

SPECS/wget/fix-ssl-read-and-write-error-check.patch
SPECS/wget/wget.spec

---
Change #10461  fixed `wget2` an [upstream issue with openssl error handling](https://github.com/rockdaboot/wget2/issues/342) using the [proposed fix](https://github.com/rockdaboot/wget2/pull/343). However, in the end the upstream owner went with a [different fix](https://github.com/rockdaboot/wget2/commit/8877050c3f00a19d43e539029d2346d1040d8c02) that included a minor refactor.
This change swaps out the original fix for the upstream, to keep us closer to the upstream for future patching.
- Swapped `fix-ssl-read-and-write-error-check.patch` for the upstream version of the fix.
**YES**
- Built locally and tested resulting rpms in an environment that reproed the bug infinite loop bug.
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=645530&view=results

swap fix-ssl-read-and-write-error-check.patch for a slightly different version from upstream

---

toolkit/tools/pkg/imagecustomizerlib/bootcustomizer.go
toolkit/tools/pkg/osmodifierlib/modifydefaultgrub.go

---
In trident e2e pipeline there are deployments not using verity test images, and in those images, root device path is not /dev/mapper/root, thus it cause the failure: `/dev/mapper/root does not exist`. It is incorrect for EMU to always set root device to /dev/mapper/root, and it should read it from grub.cfg,  for example, root=UUID=2303cd9a-ab00-4e39-9b5a-8bf8da5a6118, we need to pass the real root device either via UUID= or PARTUUID=. With this change, EMU should be able to handle all test images in that pipeline. 
**NO**
- tested locally and will publish new EMU and rerun trident pipeline

OSModifier: Read root device from grub.cfg

---

SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.signatures.json
SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
SPECS/cloud-hypervisor-cvm/upgrade-openssl-to-3.3.2-to-address-CVE-2024-6119.patch

Update openssl to 3.3.2 under cloud-hypervisor-cvm in order to address CVE-2024-6119
---
This PR updates `openssl` dependency of `cloud-hypervisor-cvm` to version `3.3.2`, as that is the version that contains a patch for CVE-2024-6119. The patch has been included into the vendored archive and is also part of this change.
- Cargo.lock patch of the openssl version and updated vendored archive name
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-6119

Update openssl to 3.3.2 under cloud-hypervisor-cvm in order to address CVE-2024-6119

---

SPECS/reaper/CVE-2024-43796.patch
SPECS/reaper/reaper.spec

---
Patch CVE-2024-43796 in reaper
- CVE-2024-43796
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-43796
- Pipeline build id: [646807](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=646807&view=results)

Patch CVE-2024-43796 in reaper

---

toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-size-only-config.yaml

Handle a missed rename from `fileSystems` to `filesystems`.
---
NO
- Ran test.

Image Customizer: Fix 'TestCustomizeImagePartitionsSizeOnly' test.

---

toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/dirconfig.go
toolkit/tools/imagecustomizerapi/dirconfig_test.go
toolkit/tools/imagecustomizerapi/os_test.go
toolkit/tools/pkg/imagecustomizerlib/customizefiles.go
toolkit/tools/pkg/imagecustomizerlib/customizefiles_test.go
toolkit/tools/pkg/imagecustomizerlib/testdata/adddirs-config.yaml

Rename `sourcePath` and `destinationPath` to `source` and `destination`.
---
NO
- Ran tests.

Image Customizer: Rename additionDirs fields.

---

toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/disk.go
toolkit/tools/imagecustomizerapi/filesystemtype.go
toolkit/tools/imagecustomizerapi/partition.go
toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/storage_test.go
toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
toolkit/tools/pkg/imagecustomizerlib/typeConversion.go

Allow partitions to be specified without specifying a filesystem type. This is particularly useful for the BIOS boot partition and the verity hash partition.
---
NO
- Added/updated UTs.

Image Customizer: Support filesystem-less partitions.

---

SPECS-EXTENDED/python-argcomplete/python-argcomplete.spec

NOTE: The target of the PR is to enable the build of python-argcomplete instead of break the build. As a result we have commented a `BuildRequire: fish`, which will result in failing ptest.
The ptest fixing is not in the scope of this PR as it is for unblocking a new added package.
The fixing of ptest will be taken up in a new PR.
---
Drop BR on `fish` (check) to enable build
For WorkItem: [389-ds-base](https://microsoft.visualstudio.com/OS/_workitems/edit/51717004)
- Drop BR on `fish` (check) to enable build
**NO**
- #10545
- NA
- …

python-argcomplete: drop check dep BR fish to enable build

---

toolkit/imageconfigs/marketplace-gen2-aarch64-fips.json

---
This commit adds a new Azure VM ARM64 image with FIPS enabled by default. 
This image definition is identical to the current marketplace ARM64 image definition, except for the following specific changes:
1. Include the fips-packages.json package list before the initramfs package in the overall package list
2. Set KernelCommandLine.EnableFIPS to true, to inform image generation tools to enable FIPS during image creation
3. Set basename for image as "cblmariner-arm64-gen2-fips"
NO
https://microsoft.visualstudio.com/OS/_workitems/edit/46521359
- local arm image build and test on Azure
- Check FIPS is enabled by: 
sudo cat …

add Azure marketplace ARM64 FIPS image definition

---

toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/config.go
toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/idtype.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitionsfilecopy.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
toolkit/tools/pkg/imagecustomizerlib/customizeverity_test.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/imageutils.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
toolkit/tools/pkg/imagecustomizerlib/testdata/verity-partition-labels.yaml

Permit the verity 'hashPartition' and 'dataPartition' to be specified by partition 'id' instead of needing to be specified by partition 'label'.
---
NO
- Updated tests.

Image Customizer: Allow verity partitions to be specified by 'id'.

---

toolkit/scripts/check_entangled_specs.py

---
The entanglement PR check was not expanding macros in the checked tags (`Version`, `Epoch`, etc.). This caused it to fail for cases where some versions were expressed in form of macro. This change adds a step, which replaces the macros with their values.
This issue came up in a [PR check](https://github.com/microsoft/azurelinux/actions/runs/11114493630/job/30881072622?pr=10329) for #10329.
No.
- #10329
- Local run for changes from #10329.

Fixed spec entanglement PR check

---

toolkit/scripts/check_entangled_specs.py

---
The entanglement PR check was not expanding macros in the checked tags (`Version`, `Epoch`, etc.). This caused it to fail for cases where some versions were expressed in form of macro. This change adds a step, which replaces the macros with their values.
This issue came up in a [PR check](https://github.com/microsoft/azurelinux/actions/runs/11114493630/job/30881072622?pr=10329) for #10329.
No.
- #10585
- PR check in the 3.0 PR.

Fixed spec entanglement PR check (CP: #10585)

---

toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
toolkit/tools/internal/tdnf/tdnf.go
toolkit/tools/internal/tdnf/tdnf_test.go

---
We've recently started seeing builds failing with following errors:
```
failed to clone (7.70-506.azl3.noarch) from RPM repo
```
This seems to be related with invalid parsing of the `tdnf provides` output where the tool's regex failed to take a potential `:` into the account. A few lines above the mentioned error, we can see TDNF finding the right package:
```
time="2024-09-30T21:52:54Z" level=debug msg="Executing: [tdnf provides perl(ExtUtils::MakeMaker) --releasever=3.0 --disablerepo=* --enablerepo=toolchain-repo]"
time="2024-09-30T21:52:54Z" level=debug msg="tdnf search for provide 'perl(ExtUtils::MakeMaker)':
Loaded plugin: tdnfrepogpgcheck
[using capability match for …
```

Fixed `tdnf provides` parsing to recognize epochs in package names.

---

SPECS/azurelinux-release/90-default.preset
SPECS/azurelinux-release/azurelinux-release.signatures.json
SPECS/azurelinux-release/azurelinux-release.spec

---
Default presets were introduced here https://github.com/microsoft/azurelinux/pull/8028. The default firewall was firewalld which is not fully supported for Azl3. Therefore, set as iptables. 
- For an image upgrade, this PR will cause the iptables.service to run by default and thus, will introduce firewall rules by default.
- For a package upgrade to `azurelinux-release-3.0-20`, the iptables service will be recognized as being allowed by the preset but will NOT be enabled by default. That being said, if an iptables.rpm upgrade comes in afterwards, the rules WILL be turned on
- For a package downgrade to an older package (< `azurelinux-release-3.0-20`), the preset will show that …

Enable iptables by default

---

SPECS/heimdal/CVE-2022-3116.patch
SPECS/heimdal/heimdal.spec

---
- Add patch for fixing CVE-2022-3116.
NOTE: This was the original upstream fix available for this CVE - [CVE-2022-3116 fix](https://github.com/heimdal/heimdal/commit/7a19658c1f4fc4adf85bb7bea96caae5ba57b33e)
The code in this package's version of heimdal is not exactly the same as the one being considered in the original version of this patch. Function acceptor_start was changed by commit 4fb6a6adc9, and therefore, the block that is moved outside of the 'if(!first_ok)' conditional in 7a19658c1 is not the same as the one in the original code for this version of heimdal (this block being 'if (ctx->selected_mech_type == GSS_C_NO_OID)' …

heimdal: Add backported patch for fixing CVE-2022-3116

---

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec

---
Changes build of `SymCrypt-OpenSSL` so sources are included in the `debuginfo` rpm. We had been building with `CMAKE_BUILD_TYPE` set to `Release` rather than `RelWithDebInfo`. [Here's a good discussion of the differences](https://stackoverflow.com/questions/48754619/what-are-cmake-build-type-debug-release-relwithdebinfo-and-minsizerel).
- set `-DCMAKE_BUILD_TYPE=` to `RelWithDebInfo`
**NO**
- Built locally and tested symbols and source in gdb.
- Ran a [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=650766&view=results) and used `rpm2cpio` on the resulting `debuginfo` rpm to confirm the sources are there.
- Did a verbose build before and after and …

use build type RelWithDebInfo to generate debug info with sources

---

SPECS/libsolv/libsolv.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt
toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
In 3.0, `createrepo_c`'s default behavior is to create repodata files compressed using zstd; prior to this change, `libsolv` didn't support `zstd`, though, so `tdnf`/`dnf`/et al. couldn't actually handle those repos. As a workaround, the toolkit and manual invocations of `createrepo_c` for 3.0 have needed to use the `--compatibility` flag. Standard OSS tooling doesn't know to do this (nor should it have to), though; the right thing to do is to add support for zstd to `libsolv`, as other distros have done.
Enable zstd support in `libsolv` at compile time.
Yes.
Local build + pipeline build through and including toolchain (phase 1).

libsolv: enable zstd support to match createrepo_c

---

toolkit/tools/graphpkgfetcher/graphpkgfetcher.go
toolkit/tools/internal/rpm/rpm.go
toolkit/tools/internal/rpm/rpm_test.go
toolkit/tools/precacher/precacher.go
toolkit/tools/scheduler/schedulerutils/preparerequest.go

---
We've recently started seeing builds failing with following errors:
```
failed to clone (7.70-506.azl3.noarch) from RPM repo
```
This seems to be related with invalid parsing of the `tdnf provides` output where the tool's regex failed to take a potential `:` into the account. A few lines above the mentioned error, we can see TDNF finding the right package:
```
time="2024-09-30T21:52:54Z" level=debug msg="Executing: [tdnf provides perl(ExtUtils::MakeMaker) --releasever=3.0 --disablerepo=* --enablerepo=toolchain-repo]"
time="2024-09-30T21:52:54Z" level=debug msg="tdnf search for provide 'perl(ExtUtils::MakeMaker)':
Loaded plugin: tdnfrepogpgcheck
[using capability match for …
```

Fixed toolkit's handling of RPMs with epoch values in their name

---

SPECS/dracut/dracut.spec

kata-containers-cc has a dependency on dracut and dracut has a dependency on systemd.  During the build dracut cannot satisfy the systemd dependency and kata-containers-cc does fails to build.  The theory is that dracut needs to rebuild against the latest version of systemd.

Build Break: Bump dracut to rebuild with latest systemd

---

SPECS/libnvidia-container/common.mk.patch
SPECS/libnvidia-container/libnvidia-container.signatures.json
SPECS/libnvidia-container/libnvidia-container.spec
SPECS/libnvidia-container/libtirpc.patch
SPECS/libnvidia-container/nvidia-modprobe.patch
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
cgmanifest.json

---
This PR fixes  to fix critical CVE-2024-0132 and medium CVE-2024-0133 in `nvidia-container-toolkit` by upgrading the version to `1.16.2`.
- CVE-2024-0132
- CVE-2024-0133
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-0132
- https://nvd.nist.gov/vuln/detail/CVE-2024-0133
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=653725&view=results

Upgrade nvidia-container-toolkit to fix CVE-2024-0132 CVE-2024-0133

---

toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh

---
The raw toolchain build in the container needs `--disable-liblastlog2` set to align with https://github.com/microsoft/azurelinux/pull/10497. This didn't crop up before because we avoid re-running the raw toolchain rebuilds in the pipelines for most use-cases. 
As follow up work I'm planning to enhance the debuggability and error handling of the raw toolchain builds with two PRs:
- https://github.com/microsoft/azurelinux/pull/10662
- https://github.com/microsoft/azurelinux/pull/10663
- Disable liblastlog2 during raw bootstrap builds of `util-linux`
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/54315733
- Local building
- …

Disable liblastlog2 for util-linux in raw toolchain build

---

toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh

Cherry pick of #10661 from 3.0 to 3.0-dev.

Cherrypick #10661: Disable liblastlog2 for util-linux in raw toolchain build

---

toolkit/scripts/toolchain.mk
toolkit/scripts/toolchain/create_toolchain_in_container.sh

---
When we build the raw bootstrap toolchain and the official toolchain rpms, we do not generate log files in a durable way. This change will log the script output via `tee`, and also extract the logs from the docker container once the build is complete.
We also detect a failure of the build in the raw toolchain by checking for the presence of `status_building_in_chroot_complete`. Currently the docker build may abort at any point in `docker run ...` and we will continue as it if worked. We won't see failures until we try to use the raw container later.
- Collect log files from the toolchain build stages
- Explicitly fail the raw toolchain build if any part fails
**YES**
- …

Generate log files for raw toolchain builds

---

SPECS/gh/CVE-2022-32149.patch
SPECS/gh/gh.spec

---
gh: address CVE-2022-32149
- gh: address CVE-2022-32149
- Fix changelog which was corrupted due to a merge conflict
**NO**
- NA
- Pipeline build id: [PR-10334](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633729&view=results)

gh: address CVE-2022-32149

---

SPECS/cni-plugins/CVE-2023-3978.patch
SPECS/cni-plugins/cni-plugins.spec

---
Add patch to resolve CVE-2023-3978
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-3978
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=655164&view=results)

Patch cni-plugins to resolve CVE-2023-3978

---

SPECS/influxdb/CVE-2023-45288.patch
SPECS/influxdb/influxdb.spec

---
Patch CVE-2023-45288
NO
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=655057&view=results)

Patch influxdb to resolve CVE-2023-45288

---

toolkit/tools/imagecustomizer/docs/configuration.md
toolkit/tools/imagecustomizerapi/boottype.go
toolkit/tools/imagecustomizerapi/config.go
toolkit/tools/imagecustomizerapi/config_test.go
toolkit/tools/imagecustomizerapi/partition.go
toolkit/tools/imagecustomizerapi/storage.go
toolkit/tools/imagecustomizerapi/storage_test.go
toolkit/tools/pkg/imagecustomizerlib/customizebootloader.go
toolkit/tools/pkg/imagecustomizerlib/customizeos.go
toolkit/tools/pkg/imagecustomizerlib/customizepartitions.go
toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go
toolkit/tools/pkg/imagecustomizerlib/testdata/newpartitionsuuids-config.yaml

This change moves the `resetPartitionsUuidsType` property to `storage.resetPartitionsUuidsType`.
Most of this change is just handling the fact that we can no longer use the existence of `storage` to indicate that the partitions are being customized. This will be beneficial when `verity` is also moved into `storage`.
---
NO
- Ran UTs.

Image Customizer: Move `resetPartitionsUuidsType` into `storage`.

---

toolkit/scripts/imggen.mk
toolkit/scripts/pkggen.mk

---
When using the precacher, the cache directory can be removed after creation causing a file not found, breaking the build. Rather than removing the folder, we will instead delete all of the rpms contained within.
- use find -exec rm to clean up cached rpms instead of rm -rf the cache folder
**NO**

Change rm to use find to avoid deleting cache directory during snapshot cleanup

---

SPECS/libarchive/CVE-2024-20696.patch
SPECS/libarchive/CVE-2024-48957.patch
SPECS/libarchive/CVE-2024-48958.patch
SPECS/libarchive/libarchive.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Patch CVE-2024-48957, CVE-2024-48958, CVE-2024-20696 by using the upstream patches:
- https://github.com/libarchive/libarchive/pull/2172
- https://github.com/libarchive/libarchive/pull/2148
- https://github.com/libarchive/libarchive/pull/2149
- Patch CVE-2024-48957, CVE-2024-48958, CVE-2024-20696
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-48957
- https://nvd.nist.gov/vuln/detail/CVE-2024-48958
- https://nvd.nist.gov/vuln/detail/CVE-2024-20696
- Pipeline build id: [658790](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=658790&view=results)

libarchive: Patch CVE-2024-48957, CVE-2024-48958, CVE-2024-20696

---

toolkit/tools/imagecustomizerapi/utils.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
toolkit/tools/pkg/imagecustomizerlib/savedconfigs.go

---
[mix][iso] Save input ISO configuration as yaml.
'SavedConfigs' is a subset of the Image Customizer input configurations that needs to be saved on the output media so that it can be used in subsequent runs of the Image Customizer against that same output media.
This change updates the code from saving just the kernel parameters in a plain-text file, to saving the same yaml that's using in the input configuration. This allows the code to scale when we want to save other input configuration constructs. This is a step preparing for adding PXE specific configurations.
Background:
This preservation of input configuration is necessary for subsequent runs if the configuration does not …

[mic][iso] Save input ISO configuration as yaml

---

SPECS/ebtables/ebtables.spec
SPECS/iptables/iptables.spec

---
Enable building iptables with nftables to provide both iptables-legacy & iptables-nft with default being set to legacy.
This PR fixes https://microsoft.visualstudio.com/OS/_workitems/edit/53647336.
- Enable build with nftables
- 
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/54527124
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=660912&view=results)

iptables: Enable nftables

---

SPECS/fluent-bit/CVE-2024-25629.patch
SPECS/fluent-bit/CVE-2024-26455.patch
SPECS/fluent-bit/fluent-bit.spec

---
Patches for fluent-bit CVEs: CVE-2024-26455, CVE-2024-25629
- fluent-bit: Add patch for CVE-2024-26455
- fluent-bit: Add patch for CVE-2024-25629
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-26455
- https://nvd.nist.gov/vuln/detail/CVE-2024-25629
- Ran UTs,

fluent-bit: CVE-2024-26455, CVE-2024-25629

---

SPECS/fluent-bit/CVE-2024-25629.patch
SPECS/fluent-bit/CVE-2024-28182.patch
SPECS/fluent-bit/CVE-2024-34250.patch
SPECS/fluent-bit/fluent-bit.spec

---
Patches for fluent-bit CVEs: CVE-2024-34250, CVE-2024-25629, CVE-2024-28182
- fluent-bit: Add patch for CVE-2024-34250
- fluent-bit: Add patch for CVE-2024-25629
- fluent-bit: Add patch for CVE-2024-28182
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-34250
- https://nvd.nist.gov/vuln/detail/CVE-2024-25629
- https://nvd.nist.gov/vuln/detail/CVE-2024-28182
- Ran package tests.

fluent-bit: CVE-2024-34250, CVE-2024-25629, CVE-2024-28182

---

toolkit/scripts/imggen.mk
toolkit/scripts/pkggen.mk

---
This is a fix-up for #10756. We've missed doing a check for the existence of the searched directory before running `find`.
No.
- #10756

Added directory check before cleaning-up the RPM caches.

---

toolkit/tools/pkg/imagecustomizerlib/customizeoverlays.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go

You don't need to call "sudo" if the entire program is run as root already.
---
NO
- Ran UTs.

Image Customizer: Remove "sudo" calls.

---

SPECS/rubygem-async-http/0001-add-patch.patch
SPECS/rubygem-async-http/remove-http-protocol1-dep.patch
SPECS/rubygem-async-http/rubygem-async-http.spec

---
Remove version dependency of rubygem-protocol-http1 from rubygem-async-http. This will allow upgrades of rubygem-protocol-http1 where both packages are installed on the host.
- Remove version dependency of rubygem-protocol-http1 from rubygem-async-http
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657278&view=results

rubygem-async-http: remove version dependency of rubygem-protocol-http1

---

SPECS/php/php-8.3.12-systzdata-v25.patch
SPECS/php/php.signatures.json
SPECS/php/php.spec
cgmanifest.json

---
php: upgrade to 8.3.12 to fix CVE-2024-8927, CVE-2024-8925
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-8927
- CVE-2024-8925
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=658479&view=results

php: upgrade to 8.3.12 to fix CVE-2024-8927, CVE-2024-8925

---

SPECS/clamav/clamav.signatures.json
SPECS/clamav/clamav.spec
cgmanifest.json

---
Fixes CVE-2024-20506, CVE-2024-20505
- Fixes https://github.com/advisories/GHSA-h5fr-q576-q7rv, https://github.com/advisories/GHSA-6qcx-p3rr-pfwf
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-20506
- https://nvd.nist.gov/vuln/detail/CVE-2024-20505
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=659441&view=results

clamav: upgrade 1.0.6 -> 1.0.7

---

SPECS/gdb/CVE-2023-39128.patch
SPECS/gdb/CVE-2023-39129.patch
SPECS/gdb/CVE-2023-39130.patch
SPECS/gdb/gdb.spec

---
Add patch for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130
- Add patch for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39128
- https://nvd.nist.gov/vuln/detail/CVE-2023-39129
- https://nvd.nist.gov/vuln/detail/CVE-2023-39130
- BuddyBuild: [654944](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654944&view=results)

Patch gdb 13.2 for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130

---

SPECS/gdb/CVE-2023-39128.patch
SPECS/gdb/CVE-2023-39129.patch
SPECS/gdb/CVE-2023-39130.patch
SPECS/gdb/gdb.spec

---
Add patch for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130 in gdb
- Add patch for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130 in gdb
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39128
- https://nvd.nist.gov/vuln/detail/CVE-2023-39129
- https://nvd.nist.gov/vuln/detail/CVE-2023-39130
- BuddyBuild: [654939](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654939&view=results)

Patch gdb 11.2 for CVE-2023-39128, CVE-2023-39129, CVE-2023-39130

---

SPECS/curl/CVE-2024-8096.patch
SPECS/curl/curl.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Address CVE-2024-8096
- Address CVE-2024-8096
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-8096
- Pipeline build id: [PR-10729](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657777)

curl: address CVE-2024-8096

---

SPECS/apr/apr.signatures.json
SPECS/apr/apr.spec
SPECS/apr/skip-known-test-failure.patch
cgmanifest.json

---
- **apr: upgrade version 1.7.4 -> 1.7.5 to address CVE-2023-49582**
- **apr: upgrade version 1.7.4 -> 1.7.5 to address CVE-2023-49582**
**NO**
- #10749
- https://nvd.nist.gov/vuln/detail/CVE-2023-49582
- Pipeline build id: [PR-10750](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=658517&view=results)

apr: upgrade version 1.7.4 -> 1.7.5 to address CVE-2023-49582

---

SPECS/gnutls/gnutls.signatures.json
SPECS/gnutls/gnutls.spec
cgmanifest.json

---
- **gnutls: upgrade 3.7.7 -> 3.7.11 to address CVE-2023-5981, CVE-2024-28835, CVE-2024-28834, CVE-2024-0553**
Reference: https://gitlab.com/gnutls/gnutls/-/blob/gnutls_3_7_x/NEWS
- Upgrade 3.7.7 -> 3.7.11 to address CVE-2023-5981, CVE-2024-28835, CVE-2024-28834, CVE-2024-0553
- Drop patches already in upstream
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-5981
- https://nvd.nist.gov/vuln/detail/CVE-2024-28835
- https://nvd.nist.gov/vuln/detail/CVE-2024-28834
- https://nvd.nist.gov/vuln/detail/CVE-2024-0553
- Pipeline build id: [PR-10578](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=649236&view=results)

gnutls: upgrade 3.7.7 -> 3.7.11 to address CVE-2023-5981, CVE-2024-28835, CVE-2024-28834 & CVE-2024-0553

---

toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go

When making changes to partitions or filesystems, it is recommended to take a file lock over the disk block device as this informs the host OS that you are making changes and that it should avoid scanning or changing the device until you are done. While most of the relevant operations are covered, there a few places that are missing the lock. For example, when calling `mkfs` or `resize2fs`.
---
NO
- Ran image customizer UTs.

Toolkit: Add missing `flock` calls.

---

SPECS/kata-containers/kata-containers.spec

We don't build kata(-cc) for ARM, so we should only build it for x86_64.
---
We don't build kata(-cc) for ARM, so we should only build it for x86_64. Solves package build failure on ARM (https://dev.azure.com/mariner-org/mariner/_build/results?buildId=662858&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=88a626d5-bd2d-5bcb-0f14-68ce5ab12667&l=11755)
- kata-containers
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=663899&view=results [See how this package is now skipped on ARM instead of failing]

kata-containers: only build for x86_64

---

toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go

In change #10789, the `imagecustomizerapi.FileSystem` type had an internal field added called `PartitionId` which is filled in by the API validity checks.
ISO to ISO customization supports cracking open the squashfs file and modifying the Live-OS. However, to do this, a temporary OS image must be created. This creation logic uses the `imagecustomizerapi.FileSystem` type but the code wasn't updated to ensure the `PartitionId` field has a value.
---
NO
- Ran UTs.

Image Customizer: Fix ISO customization.

---

toolkit/tools/pkg/imagecustomizerlib/imagecustomizer.go

Currently, the size of outputted VHDX files can be substantially larger than VHD or qcow2 files. This behavior occurs because `qemu-img` dynamically sets the block-size based on the size of the disk. And larger blocks sizes means the file format is less space efficient, which results in a larger image file.
This change sets the block-size to 2 MiB for VHDX files. This matches the `qemu-img` defaults for VHD and QCOW2.
For reference, Windows seems to use a default block-size of 1 MiB for VHDX files.
---
NO

Image Customizer: Set VHDX block-size to 2 MiB.

---

SPECS/avahi/CVE-2023-1981.patch
SPECS/avahi/avahi.spec

---
Avahi has an [issue here](https://github.com/avahi/avahi/issues/375) with a fix in [this PR](https://github.com/avahi/avahi/pull/407).
I have also enabled the basic built-in tests for the package. If we get a new version of Avahi (>=9.0) we will get even more tests ([for example](https://github.com/avahi/avahi/pull/420/files))
**NOTE: 2.0 PR is here: https://github.com/microsoft/azurelinux/pull/10881**
- Patch CVE-2023-1981
- Enable %check section for Avahi
**NO**
- https://brave-ocean-0baeae310.5.azurestaticapps.net/#/cve/CVE-2023-1981
- Local build
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=666009&view=results

Avahi: Fix CVE-2023-1981, add %check section

---

SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Removing noxsaves from UKI cmdline since Hyper-V fix has been rolled out on Azure.
- Remove noxsaves parameter from UKI cmdline
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/51618524/
- Local build succeeds
- Built a CVM image and deployed on Azure. Boot succeeds

kernel-uki: remove noxsaves parameter from cmdline

---

toolkit/tools/pkg/imagecustomizerlib/imageutils.go
toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go

The change #10804 (Toolkit: Add missing flock calls) seems to have caused a problem where on Ubuntu 22.04 build hosts, the partition info isn't populated quickly enough after partition creation and formatting. So, the `lsblk` call might return missing information. Adding a `partprobe` call before the `lsblk` call seems to fix the problem.
---
NO
- Ran UTs.

Image Customizer: Fix partition creation on Ubuntu build hosts.

---

SPECS/ruby/CVE-2024-49761.patch
SPECS/ruby/ruby.spec
SPECS/rubygem-rexml/CVE-2024-49761.patch
SPECS/rubygem-rexml/rubygem-rexml.spec

---
- ruby: patch CVE-2024-49761
- rubygem-rexml: patch CVE-2024-49761
- CVE-2024-49761
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-49761
buddy build: 
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=669359&view=results

ruby and rubygem-rexml: patch CVE-2024-49761

---

SPECS/prometheus/CVE-2023-39325.patch
SPECS/prometheus/CVE-2023-45288.patch
SPECS/prometheus/prometheus.spec

---
[2.0] prometheus address CVE-2023-39325 CVE-2023-45288
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-39325 

[2.0] prometheus address CVE-2023-39325 CVE-2023-45288

---

SPECS/skopeo/CVE-2024-24786.patch
SPECS/skopeo/CVE-2024-28180.patch
SPECS/skopeo/CVE-2024-9676.patch
SPECS/skopeo/skopeo.spec

---
Fixes multiple High and Medium CVEs for skopeo package (listed below)
- CVE-2024-9676
- CVE-2024-28180
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-9676
- Local Build
- Github PR checks
- rubygem-rake
- libguestfs
- rubygem-introspection
- rubygem-metaclass

Fix multiple CVEs in Skopeo

---

SPECS/python-werkzeug/CVE-2024-49767.patch
SPECS/python-werkzeug/python-werkzeug.spec

---
Patch CVE-2024-49767 in python-werkzeug
-  CVE-2024-49767
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-49767
- Unified Buddy build is [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=669499&view=results)

Patch CVE-2024-49767 in python-werkzeug

---

SPECS/glib/CVE-2024-52533.patch
SPECS/glib/glib.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Fixes CVE-2024-52533. 
Based on upstream patch: [25833cefda24c60af913d6f2d532b5afd608b821](https://gitlab.gnome.org/GNOME/glib/-/commit/25833cefda24c60af913d6f2d532b5afd608b821.patch)
- CVE-2024-52533
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-52533
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=675632&view=results

glib: Fix for CVE-2024-52533

---

SPECS/libnvidia-container/libnvidia-container.signatures.json
SPECS/libnvidia-container/libnvidia-container.spec
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
cgmanifest.json

---
- Upgrade nvidia container tookit to v1.17.1 to resolve https://github.com/advisories/GHSA-7jm9-xpwx-v999
- Upgrade libnvidia-containers to v1.17.1 to keep in sync with nvidia container toolkit
- Upgrade to v1.17.1 to resolve https://github.com/advisories/GHSA-7jm9-xpwx-v999
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-0134
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=673589&view=results

[3.0] Upgrade nvidia container toolkit and libnvidia-containers to v1.17.1

---

toolkit/docs/building/prerequisites-mariner.md
toolkit/docs/building/prerequisites-ubuntu.md
toolkit/scripts/chroot.mk
toolkit/scripts/tools.mk
toolkit/scripts/utils.mk
toolkit/tools/containercheck/containercheck.go
toolkit/tools/internal/buildpipeline/buildpipeline.go
toolkit/tools/pkggen/worker/create_worker_chroot.sh

---
There have been several issues with a mismatch between the build environment and the detected state by the toolkit. When running in docker, the chroots generally need to be configured externally with their mounts and re-used. This can be done via setting `CHROOT_DIR=/path/to/reusable/chroots`, and if the toolkit thinks it's in a container, it will switch modes.
See https://github.com/microsoft/azurelinux-tutorials/tree/main/build-in-container for more details.
Some builds are currently failing because what is ostensibly a container environment does not have `/.dockerenv` present. 
In the opposite direction, there are also situations where WSL images (which should work fine as a …

Toolkit: Use systemd-detect-virt instead of /.dockerenv to detect container builds.

---

SPECS/tar/CVE-2022-48303.patch
SPECS/tar/CVE-2023-39804.patch
SPECS/tar/tar.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
- Fix CVE-2022-48303 and CVE-2023-39804
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-48303
- https://nvd.nist.gov/vuln/detail/CVE-2023-39804
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=678670&view=results

[2.0] tar: Fix CVE-2022-48303 and CVE-2023-39804

---

.pipelines/templates/PackageBuild.yml

---
The `PackageBuild.yml` template was capturing only a subset of build logs. This PR aligns the contents with how our other builds upload logs.
No.
- #11086
- [PR check build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=676083&view=results).

Updated package build templates to capture all build logs.

---

SPECS/cups/CVE-2024-35235.patch
SPECS/cups/cups.spec

---
- Add patch for CVE-2024-35235
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35235
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=679925&view=results

Fix CVE-2024-35235 for cups :2.0

---

SPECS/ebtables/ebtables.spec
SPECS/iptables/iptables.spec

---
This PR enables nftables in iptables to provide iptables-nft (default) & iptables-legacy commands.
This PR fixes https://microsoft.visualstudio.com/OS/_workitems/edit/53647336.
- When upgrading iptables to this variant, introduction of alternatives provides **nft** variant as default for iptables | ip6tables | ebtables | arptables.
The legacy iptables is installed as **-legacy** variant
- The upgrade of iptables will start the iptables service and use the nft variant to restore the ipv4|ipv6 configs (by default the one provided as part of the package)
- The equivalent nft ruleset can be seen by using `nft` provided by nftables. …

iptables: Enable nftables.

---

SPECS/libsoup/CVE-2024-52530.patch
SPECS/libsoup/CVE-2024-52531.patch
SPECS/libsoup/CVE-2024-52532.patch
SPECS/libsoup/libsoup.spec

---
Add patches for CVE-2024-52530, CVE-2024-52531, CVE-2024-52532 affecting libsoup
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-52530
- https://nvd.nist.gov/vuln/detail/CVE-2024-52531
- https://nvd.nist.gov/vuln/detail/CVE-2024-52532

libsoup: add patches for CVE-2024-52530, CVE-2024-52531, CVE-2024-52532

---

SPECS/nano/CVE-2024-5742.patch
SPECS/nano/nano.spec

---
- Address CVE-2024-5742
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-5742
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=679990&view=results

Fix CVE-2024-5742 for nano :3.0

---

SPECS/unzip/CVE-2022-0529.patch
SPECS/unzip/unzip.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
- Fix CVE-2022-0529 and CVE-2022-0530
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-0529
- https://nvd.nist.gov/vuln/detail/CVE-2022-0530
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=682479&view=results

Fix CVE-2022-0529 and CVE-2022-0530 for unzip :3.0

---

toolkit/docs/building/prerequisites-mariner.md
toolkit/docs/building/prerequisites-ubuntu.md
toolkit/scripts/chroot.mk
toolkit/scripts/tools.mk
toolkit/tools/containercheck/containercheck.go
toolkit/tools/internal/buildpipeline/buildpipeline.go
toolkit/tools/pkggen/worker/create_worker_chroot.sh

---
Backport of https://github.com/microsoft/azurelinux/pull/11039. Removed the calls to `logger.PrintMessageBox()` and replaced with `logger.Log.Warn()`.
Previous PR description follows:
<blockquote>
There have been several issues with a mismatch between the build environment and the detected state by the toolkit. When running in docker, the chroots generally need to be configured externally with their mounts and re-used. This can be done via setting `CHROOT_DIR=/path/to/reusable/chroots`, and if the toolkit thinks it's in a container, it will switch modes.
See https://github.com/microsoft/azurelinux-tutorials/tree/main/build-in-container for more details.
Some builds are currently …

Backport toolkit container detection using systemd-detect-virt

---

SPECS/kata-packages-uvm/kata-packages-uvm.spec

---
Further streamline/simplify UVM builds
- add explicit dependency to `make` for kata-packages-uvm-bulid: allows for builds without relying on kata-packages-uvm-coco-sign (the latter package requires build-essentials with requires make).
- remove commented package dependencies for msigvm and cose1sign tools
**NO**
- N/A
- N/A
- Pipeline build id: [Pipelines - Run mahuber+uvm-install+kata-packages-uvm+unknown](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=682872&view=results)

kata-packages-uvm: Add make dependency

---

SPECS/shim-unsigned-aarch64/shim-unsigned-aarch64.spec
SPECS/shim-unsigned-x64/shim-unsigned-x64.spec
SPECS/shim/shim.spec

---
Prior ARM64 images and installations historically used "shim-unsigned" v15.4 in order to boot without Secure Boot enforcing.
To ensure a seamless upgrade experience from the older unsigned shim to this new signed shim, include additional RPM dependency logic (Obsoletes on "shim-unsigned" so older installations with "shim-unsigned" installed will upgrade cleanly from the unsigned shim v15.4 to this new signed version of the shim v15.8+
Unlike dnf, our current tdnf does not gracefully handle Obsoletes properly.
When the user runs "tdnf install shim-unsigned". The proper
behavior with Obsoletes only in place is for this transaction to
complete with nothing to do, which is what dnf …

Add obsoletes and provides to fix errors in shim-unsigned upgrade to shim

---

toolkit/scripts/containerized-build/create_container_build.sh
toolkit/scripts/containerized-build/resources/azl.Dockerfile
toolkit/scripts/containerized-build/resources/setup_functions.sh

---
In a `containerized-rpmbuild` environment, the function `install_dependencies` will install all `BuildRequires` dependencies from a spec file. However, it wasn't able to handle file dependencies like `BuildRequires: %{_bindir}/cmp`, which requires looking up the package that provides the file.
This change uses `tdnf repoquery` to get the appropriate package.
I also added usage of `jq` in that function, so I added it to the list of packages we always install (it's useful anyway), and did a minor refactor of how we do that.
- Updated `install_dependencies` to support file dependencies.
- Minor refactor of how we pass packages to add to a container to the docker file.
- Added `jq` …

make install_dependencies work with file dependencies

---

SPECS/cloud-init/cloud-init.signatures.json
SPECS/cloud-init/cloud-init.spec
SPECS/cloud-init/module-setup.sh

---
Add a new module-setup.sh azure module for dracut to consume to make sure 66-azure-ephemeral.rules is applied beforehand. Dracut is used to create initramfs and 66-azure-ephemeral.rules is provided by cloud-init.
This script is to prevent an intermittent issue where ephemeral disk not being formatted by cloud-init on Azure due to possibly racing condition due to ephemeral resource disk does not exist.
- Add module-setup.sh azure module and install it under dracut modules. Path for install: /usr/lib/dracut/modules.d/99azure-cloud
NO
- [Bug 54009131](https://microsoft.visualstudio.com/OS/_workitems/edit/54009131)
- Azure provisioning …

Cloud-init add module-setup.sh azure module for dracut to run

---

SPECS/dracut/0016-Handle-SELinux-configuration-for-overlayfs-folders.patch
SPECS/dracut/90overlayfs/azl-configure-selinux.sh
SPECS/dracut/dracut.signatures.json
SPECS/dracut/dracut.spec
SPECS/selinux-policy/0038-enable-liveos-iso-flow.patch
SPECS/selinux-policy/selinux-policy.spec

---
To enable SELinux for the LiveOS ISO flow we need to:
- update the selinux policies.
- this is done through the patch to the selinux-policy package.
- label the new overlay folders with `root_t` so that they match the expect context of the root `/`.
- this is done by adding a new pre-pivot script to the dracut's overlayfs module which will mark the new folders correctly when SELinux is enabled.
- [Enable selinux for liveos iso flow](https://github.com/microsoft/azurelinux/pull/11198/commits/8bf2c274c327de7c0c8ccd0176edc2e7a4962270)
- **NO**
- #xxxx
- n/a
- Build baremetal images with SELinux enabled in enforcing mode.
- Use MIC to create a LiveOS ISO, boot it, and log-in.

Enable selinux for liveos iso flow

---

toolkit/tools/imagegen/diskutils/diskutils.go
toolkit/tools/imagegen/diskutils/encryption.go

---
Resolves [[Core][ISO][3.0] ISO installer encrypted root doesn't boot](https://microsoft.visualstudio.com/OS/_workitems/edit/54417272)
Cause: [Grub does not recognize ext4 partition with certain features enabled](https://badrpc.net/20230728-grub-does-not-recognise-ext4/)
- Disable unsupported mkfs option for creating partitions
**YES**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=688906&view=results
- Fixed ISO Link for testing (use with disabled secure boot, this is not prod image): …

fix: ISO installer encrypted root doesn't boot

---

toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
toolkit/tools/imageconfigvalidator/testdata/bogus-list.json
toolkit/tools/imageconfigvalidator/testdata/dummy-list.json
toolkit/tools/imageconfigvalidator/testdata/fips-list.json
toolkit/tools/imageconfigvalidator/testdata/pinned-shadowutils-list.json
toolkit/tools/imageconfigvalidator/testdata/pinned-shadowutils-ws-list.json
toolkit/tools/imageconfigvalidator/testdata/selinux-policy-list.json
toolkit/tools/imageconfigvalidator/testdata/shadowutils-list.json
toolkit/tools/imageconfigvalidator/testdata/test-config.json

---
Several features require specific packages also be installed to function (selinux, fips, etc.). One of these is `shadow-utils` which is needed for user changes.
We also have an undocumented feature where you can pin packages to specific versions in a package list via "pkg-name = 1.2.3-4". These two features conflict with each other since the validator assumed only basic package names would be used.
Also flesh out the unit tests a bit for the validator and rely less on using the built-in configs and instead use a dedicated test config file.
There is a limitation however, we cannot distinguish between `pkg-long-name` and `pkg-version-release` even though tdnf will accept that, so …

Fix issue when version pinning packages that are checked by the configvalidator tool

---

SPECS/iptraf-ng/iptraf-ng.signatures.json
SPECS/iptraf-ng/iptraf-ng.spec
cgmanifest.json

This is an auto-generated pull request to cherry-pick commit 574ad383aa465de5b37c9d24cf109d57c7d63cf0 to main. Original PR: #11568

[AUTO-CHERRYPICK] iptraf-ng: upgrade to 1.2.2 - branch main

---

SPECS/dpdk/dpdk.signatures.json
SPECS/dpdk/dpdk.spec
cgmanifest.json

This is an auto-generated pull request to cherry-pick commit 674e0763a633d836b373e98987b1ef6aed0de69c to 3.0-dev. Original PR: #11631

[AUTO-CHERRYPICK] Upgrade DPDK for CVE-2024-11614 - branch 3.0-dev

---

SPECS/docker-buildx/CVE-2024-45337.patch
SPECS/docker-buildx/docker-buildx.spec
SPECS/moby-engine/CVE-2024-45337.patch
SPECS/moby-engine/moby-engine.spec

This is an auto-generated pull request to cherry-pick commit b83da2ac6c19b819ddc644bf7ede47aca72ca554 to 3.0-dev. Original PR: #11618

[AUTO-CHERRYPICK] docker-buildx, moby-engine: patch CVE-2024-45337 - branch 3.0-dev

---

SPECS/cf-cli/CVE-2024-45337.patch
SPECS/cf-cli/cf-cli.spec
SPECS/kubevirt/CVE-2024-45337.patch
SPECS/kubevirt/kubevirt.spec
SPECS/packer/CVE-2024-45337.patch
SPECS/packer/packer.spec

This is an auto-generated pull request to cherry-pick commit 73bc2e1b27f805e6cee9e3bbd73b56af2446f0be to 3.0-dev. Original PR: #11620

[AUTO-CHERRYPICK] cf-cli, kubevirt, packer: patch CVE-2024-45337 - branch 3.0-dev

---

SPECS/dbus/dbus.spec

---
Package build of the `oddjob` extended package fails, because that package `BuildRequires: dbus-x11`. We've removed the standalone `dbus-x11` package a while ago and replaced it with a `Provides` in the `dbus.spec`. We've missed adding an `Obsoletes` to that spec, however, which caused the build to prefer the old `dbus-x11` with a dependency on an older version of `dbus`, which conflicted with a newer version required through `BuildRequires: dbus-devel`.
No.
- Full dev build 699550.

Added missing `Obsoletes: dbus-x11` in `dbus.spec`

---

SPECS-EXTENDED/gcr/gcr.signatures.json
SPECS-EXTENDED/gcr/gcr.spec
cgmanifest.json

---
We've recently hit a build break in `gcr` [reported upstream](https://gitlab.gnome.org/GNOME/gcr/-/issues/48). Bumping `gcr` to 3.38.1, where the fix was added.
No.
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=702860&view=results).

Bumped `gcr` to 3.38.1 to fix a build break.

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageBuild.yml
.pipelines/templatesWithCheckout/SodiffCheck.yml

---
Updating the `PackageBuild.yml` template to be agnostic about the source of the input tarballs. This way the callers have the freedom to store them as they see fit.
No.
- [PR check pipeline build.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=704571&view=results)
- ADO fast-track dev builds.

Made `PackageBuild.yml` accept arbitrary input sources.

---

SPECS/fluent-bit/fluent-bit.spec

---
Azure Linux 2.0 doesn't have luajit support built-in for fluent-bit. The rpm version 1.8 which has Lua support is no longer supported. This patch enables Lua support so that fluent-bit can be updated in those environments where luajit support is mandatory.
- Change
- Change
- Change
**NO**
- #xxxx
- Validated local build compilation and installation of luajit enabled fluent bit binary. Also, verified the fluent bit unit tests which has luajit tests as well.

Enabled support of luajit for fluent-bit

---

toolkit/imageconfigs/marketplace-gen2-aarch64-fips.json

---
Add definition for arm64 FIPS image, allowing us to build these out of the box rather than require customers to enable FIPS mode on these images themselves.
- Add image definition for arm64 FIPS
**NO**
- Build Build Root: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=708892&view=results
Created azure vm using image from [the pipeline](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=708935&view=artifacts&pathAsName=false&type=publishedArtifacts).
- Successfully connected (so networking and some crypto works).
- Confirmed kernel is in FIPS mode.
- Confirmed dracut and kernel ran FIPS checks on boot.
- Confirmed openssl uses the SymCrypt provider …

add arm64 fips image definition

---

.CodeQL.yml

---
Adding CodeQL configuration to skip analyzing spec sources.
No.
- ADO pipeline runs.

Added CodeQL configuration to exclude external sources.

---

toolkit/tools/imageconfigvalidator/imageconfigvalidator.go
toolkit/tools/imagegen/installutils/installutils.go
toolkit/tools/imagegen/installutils/installutils_test.go

---
#11442 was only a partial fix, we had similar logic inside the imager tool itself. Make a common function both tools can use to validate the shadow-utils package.
- Add `installutils.PackagelistContainsPackage()`
- Use new function in both `imageconfigvalidator` and `imager`.
**NO**
- https://microsoft.visualstudio.com/OS/_queries/edit/55399616/?triage=true
- Local build of customer's config with version issues, including a full image build

Fix shadow-utils detection in imager as well as validator

---

SPECS/cmake/CVE-2024-11053.patch
SPECS/cmake/cmake.spec
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Fix CVE-2024-11053 in vendored curl in cmake
- Backport upstream fix for CVE-2024-11053 to vendored curl 8.8.0 in cmake
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-11053
- Patched 8.8.0 curl standalone, passed existing and new netrc unit tests then applied patch to vendored cmake
- Built cmake package locally and check section succeeded
- Pipeline build id: 712153
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712153&view=results

cmake: patch CVE-2024-11053

---

SPECS/rsync/rsync.signatures.json
SPECS/rsync/rsync.spec
cgmanifest.json

---
- Upgrade rsync to version 3.4.1 to fix CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, CVE-2024-12088, CVE-2024-12747
- Upgrade rsync to version 3.4.1 to fix CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, CVE-2024-12088, CVE-2024-12747
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-12084 (Critical)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12085 (High)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12086 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12087 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12088 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12747 (Medium)
- Local build and %check section succeeded
- Pipeline …

rsync: upgrade to 3.4.1 to fix multiple CVEs

---

SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.signatures.json
SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.spec
cgmanifest.json

---
Upgrade: python-rpmfluff version to 0.6.5
- modified:   SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.signatures.json
- modified:   SPECS-EXTENDED/python-rpmfluff/python-rpmfluff.spec
**NO**
- #xxxx

Upgrade: python-rpmfluff version to 0.6.5

---

SPECS/vim/CVE-2025-22134.patch
SPECS/vim/vim.spec

- [* ] The toolchain has been rebuilt successfully (or no changes were made to it) …

Fix CVE-2025-22134 in vim for 3.0

---

SPECS/qtbase/qtbase.signatures.json
SPECS/qtbase/qtbase.spec
cgmanifest.json

---
There are two files need patch: https://codereview.qt-project.org/c/qt/qtbase/+/544314
However, realized these two files will be patched by upgrading the version to v6.6.3, so, choose this way to solve the CVE.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-30161
- Local build
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712142&view=results

CVE-2024-30161: qtbase upgrades to version 6.6.3

---

SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS/kernel-64k/kernel-64k.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/config
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.signatures.json
SPECS/kernel/kernel.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Performance improvement.
In 6.1, the recommended default for DEBUG_PREEMPT was y. However, this led to performance hits and overhead due to frequent calls to __this_cpu_preempt_check().
The defualt was later changed in "[[cc60039](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/cc60039)] lib/Kconfig.debug: do not enable DEBUG_PREEMPT by default".
Therefore, go with new recommeded default to improve performance.
[Kconfig](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-3/6.6.64.1/lib/Kconfig.debug#L1274)
- Disable debug preemption in x86_64
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/55530233
- …

Disable debug preemption in x86_64

---

SPECS/influxdb/CVE-2024-28180.patch
SPECS/influxdb/influxdb.spec

---
- Fix CVE-2024-28180
**NO**
- #xxxx
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=716347&view=results

influxdb: Fix CVE-2024-28180 [Medium]

---

SPECS/containerd2/add-tardev-support.patch
SPECS/containerd2/containerd2.spec

---
Add containerd2 patch to support tardev-snapshotter
- Add containerd2 patch to support tardev-snapshotter
**NO**
- buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=708461&view=results
- imagebuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=709233&view=results
- AKS Tests:
- Conformance tests: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=709285&view=results
- Performance tests: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=709286&view=results
- Pre-release-tests: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712140&view=results
- E2E tests (the Ubuntu tests are failing in …

Add containerd2 tardev-snapshotter patch

---

SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
SPECS/mft_kernel/mft_kernel.spec
cgmanifest.json

---
To comply AZL spec standard mandates renaming kernel-mft*.rpm to mft_kernel rpm and add a provides to satisfy dependencies to the old name.
- Change
- Change
- Change
**YES/NO**
NO
- #xxxx

Change kernel-mft rpm name to mft_kernel

---

SPECS-EXTENDED/ocaml-markup/ocaml-markup.signatures.json
SPECS-EXTENDED/ocaml-markup/ocaml-markup.spec
cgmanifest.json

---
opencl-markup: update to 1.0.3
- Initial Azure Linux import from Fedora 41 (license: MIT)
**NO**
- #xxxx

ocaml-markup: update to 1.0.3

---

SPECS/postgresql/postgresql.spec

---
This is to enable the toast compression in Postgres: [https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DEFAULT-TOAST-COMPRESSION](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.postgresql.org%2Fdocs%2Fcurrent%2Fruntime-config-client.html%23GUC-DEFAULT-TOAST-COMPRESSION&data=05%7C02%7Curismiley%40microsoft.com%7C919e1e8b8aad45afe93208dd1a13f536%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638695395197141759%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=217CTBcn0rWuRmERldHymSsy0XSkZhy5t7zcX6uQPpE%3D&res …

Add LZ4 Compression Support for PostgreSQL

---

SPECS/haproxy/haproxy.spec

Enabled compilation flag USE_PROMEX to support prometheus exporter in HAProxy.
---
- This PR adds support for Prometheus exporter in HAProxy module as per the customer requirement.
- Change
- Change
- Change
**NO**
- Fixes WorkItem: [55931268](https://microsoft.visualstudio.com/OS/_workitems/edit/55931268)
- fixes #12011
- Pipeline build id: [718262](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=718262&view=results)
- Checked that installed package has flag USE_PROMEX=1 enabled by running `haproxy -vv` 
```
$ haproxy -vv
HAProxy version 2.9.11-3c54f78 2024/09/19 - https://haproxy.org/
...
OPTIONS = USE_GETADDRINFO=1 …
```

Support for Prometheus exporter in HAProxy

---

SPECS/python-conda-package-handling/python-conda-package-handling.spec

---
python-conda-package-handling ptest fails due to missing modules, pip install the missing modules to allow the test to run
- add pip install for conda_package_streaming and zstandard
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=724876&view=results

Add missing modules for python-conda-package-handling ptest

---

SPECS-EXTENDED/ucx/ucx.spec

Enable UCX KNEM & XPMEM subpackages
---
Enable UCX KNEM & XPMEM subpackages needed for CUDA drivers
SPECS/ucx/ucx.spec
**NO**
Local build on x86_64 system and confirm that sub packages are build
ucx-xpmem-1.18.0-2.azl3.x86_64.rpm
ucx-knem-1.18.0-2.azl3.x86_64.rpm

Enable UCX KNEM & XPMEM subpackages

---

SPECS/ceph/CVE-2012-6708.patch
SPECS/ceph/CVE-2014-5461.patch
SPECS/ceph/CVE-2015-9251.patch
SPECS/ceph/CVE-2020-22217.patch
SPECS/ceph/ceph.spec

---
Fix CVE-2014-5461
- May not be required as per #11999 : 448eeeaf0fd4307c78d3db5bf18902f51c9162d5
- Patch CVE-2014-5461
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2014-5461
- Local build

[Medium] Patch ceph to fix CVE-2014-5461

---

SPECS-EXTENDED/python-dbus-client-gen/python-dbus-client-gen.signatures.json
SPECS-EXTENDED/python-dbus-client-gen/python-dbus-client-gen.spec
cgmanifest.json

---
Upgrade: python-dbus-client-gen version to 0.5.1
- modified:   SPECS-EXTENDED/python-dbus-client-gen/python-dbus-client-gen.signatures.json
- modified:   SPECS-EXTENDED/python-dbus-client-gen/python-dbus-client-gen.spec
**NO**
- #xxxx

Upgrade: python-dbus-client-gen version to 0.5.1

---

SPECS/golang/golang-1.22.spec
SPECS/golang/golang.spec

---
NOTE: This change obviates #11343
`golang` -- both the [primary (1.23) package](https://github.com/microsoft/azurelinux/blob/3.0-dev/SPECS/golang/golang.spec) and the [1.22 package](https://github.com/microsoft/azurelinux/blob/3.0-dev/SPECS/golang/golang-1.22.spec) -- has warnings during both package install and package uninstall.
For package install, we things like:
```
Installing/Updating: golang-1.23.3-2.azl3.x86_64
/sbin/ldconfig: relative path `1' used to build cache
warning: %post(golang-1.23.3-2.azl3.x86_64) scriptlet failed, exit status 1
package golang-1.23.3-2.azl3.x86_64: script warning in %postin
```
This is caused by #10654, which added the use of `alternatives` in …

fix golang post install and post uninstall sriptlets

---

.pipelines/containerSourceData/cdi/Dockerfile-cdi-apiserver
.pipelines/containerSourceData/cdi/Dockerfile-cdi-controller
.pipelines/containerSourceData/cdi/Dockerfile-cdi-importer
.pipelines/containerSourceData/cdi/Dockerfile-cdi-operator
.pipelines/containerSourceData/cdi/Dockerfile-cdi-uploadproxy
.pipelines/containerSourceData/cdi/Dockerfile-cdi-uploadserver
SPECS/containerized-data-importer/containerized-data-importer.spec

The cdi binaries are misnamed in the SPEC file leading to additional Dockerfile commands to rename the binaries. Changing the SPEC file naming conventions to align with upstream and removing Dockerfile workarounds.
---
The cdi binaries are misnamed in the SPEC file leading to additional Dockerfile commands to rename the binaries. Changing the SPEC file naming conventions to align with upstream and removing Dockerfile workarounds.
**NO**
- #56050776
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=727053&view=results
- Container Pipeline Build: …

cdi: Renaming binaries in the SPEC file to align with upstream naming conventions

---

.pipelines/containerSourceData/scripts/BuildNvidiaDriverContainers.sh

---
`BuildNvidiaDriverContainers.sh` generates a string `COMPONENT_VERSION` to pass to `generate-container-sbom.sh` when generating an SBOM. `COMPONENT_VERSION` typically looks like this `550.54.15-3_6.6.57.1.7`, but recently a new package "cuda-open" was added, causing this variable to contain both version numbers separated by a newline:
```
Component Version             -> 560.35.03-1_6.6.64.2.7
560.35.03-1_6.6.64.2.7
```
This causes an incorrect parameter to be passed to the SBOM script.
- Change handling of COMPONENT_VERSION in `BuildNvidiaDriverContainers.sh`
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56077373
- …

BuildNvidiaDriverContainers.sh: fix processing of cuda RPM version

---

SPECS-EXTENDED/adobe-mappings-cmap/adobe-mappings-cmap.signatures.json
SPECS-EXTENDED/adobe-mappings-cmap/adobe-mappings-cmap.spec
cgmanifest.json

---
adobe-mappings-cmap: Update to version 20231115
SPECS-EXTENDED/adobe-mappings-cmap/adobe-mappings-cmap.signatures.json
SPECS-EXTENDED/adobe-mappings-cmap/adobe-mappings-cmap.spec
**NO**
- #xxxx

adobe-mappings-cmap: Update to version 20231115

---

SPECS-EXTENDED/aopalliance/aopalliance.spec

---
aopalliance: Updating javac source and javac target from 1.6 to 1.8.
SPECS-EXTENDED/aopalliance/aopalliance.spec
**NO**
- #xxxx

aopalliance: Updating javac source and javac target from 1.6 to 1.8.

---

SPECS-EXTENDED/accountsservice/0001-mocklibc-Fix-compiler-warning.patch
SPECS-EXTENDED/accountsservice/0002-user-manager-Fix-another-compiler-warning.patch
SPECS-EXTENDED/accountsservice/accountsservice.signatures.json
SPECS-EXTENDED/accountsservice/accountsservice.spec
cgmanifest.json

---
accountsservice: Update to version 23.13.9
SPECS-EXTENDED/accountsservice/accountsservice.signatures.json
SPECS-EXTENDED/accountsservice/accountsservice.spec
**NO**
- #xxxx

accountsservice: Update to version 23.13.9

---

SPECS-EXTENDED/perl-Class-Singleton/perl-Class-Singleton.signatures.json
SPECS-EXTENDED/perl-Class-Singleton/perl-Class-Singleton.spec
cgmanifest.json

---
Upgrade: perl-Class-Singleton version to 1.6
-   SPECS-EXTENDED/perl-Class-Singleton/perl-Class-Singleton.signatures.json
-  SPECS-EXTENDED/perl-Class-Singleton/perl-Class-Singleton.spec
-   cgmanifest.json
**NO**
- #xxxx

Upgrade: perl-Class-Singleton version to 1.6

---

SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.signatures.json
SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
cgmanifest.json

---
Upgrade: python-into-dbus-python version to 0.8.2
- modified:   SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.signatures.json
- modified:   SPECS-EXTENDED/python-into-dbus-python/python-into-dbus-python.spec
**NO**
- #xxxx

Upgrade: python-into-dbus-python version to 0.8.2

---

toolkit/scripts/build_go_vendor_cache.sh

---
This script has not been used for a while and we started creating lots of of these scripts within packages them. But all of them share the same code and do the same thing. So this PR modifies this script to universally work for all go packages and allow it to be used by the upgrade tool
- Makes script use 4 input parameters like other scripts
- Makes script use compression when creating tarball
- Makes script output to specific folder provided by the inputs
**NO**

Modify toolkit's `build_go_vendor_cache.sh` script to be used for most go packages

---

SPECS-EXTENDED/pipewire/pipewire.spec

Removing dependency on bluez5-codec-aac

Remove bluez5-codec-aac support

---

SPECS-EXTENDED/perl-IO-AIO/perl-IO-AIO.signatures.json
SPECS-EXTENDED/perl-IO-AIO/perl-IO-AIO.spec
cgmanifest.json

---
Update to `4.81`
- Version bump
**NO**
- Local build.

Update perl-IO-AIO to version 4.81-1

---

toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Following [this merge](https://github.com/microsoft/azurelinux/commit/e74674bef28d8f5b860bb9f96f6e673fa456d569#diff-8ae08a90bd244ee8cd964cd58eb528903d93d33fc51982b37905944e29bf9d77L551), the release number for python3-libs went from 6 to 5 unintentionally. PR to fix the issue
- update toolchain manifest files for fasttrack to have correct version of python3-libs
**YES**
- PR checks

fix merge issue with release bump down for python3 libs in toolchain manifests

---

SPECS/dracut/avoid-mktemp-collisions-with-find-not-path.patch
SPECS/dracut/dracut.spec

---
dracut.sh uses mktemp to create temporary workspace.  The pattern provided is dracut.XXXXXX.  Rarely, the temporary folder is dracut.ko*.  This conflicts with a find filter used in dracut.sh: `-not -path '*.ko*'`.   When the conflict occurs, dracut fails to install many required modules (including systemd-core), resulting in an initramfs that cannot be booted.
The patch prevents this conflict by prepending `d` to the mktemp substitution.
The matching upstream PR: https://github.com/dracut-ng/dracut-ng/pull/1198
- add patch to modify dracut.sh
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=727939&view=results

avoid dracut collision between [mktemp] and [find -not -path '*.ko*']

---

toolkit/docs/building/prerequisites-mariner.md
toolkit/docs/building/prerequisites-mariner.sh
toolkit/docs/building/prerequisites-ubuntu.md
toolkit/docs/building/prerequisites-ubuntu.sh
toolkit/scripts/toolkit.mk

---
As part of a new test pipeline, it is necessary to install build dependencies for the toolkit. Instead of relying on a hard-coded list of packages that will get out-of-date, provide a mechanism to automatically install build dependencies when building on azl (ubuntu is possible, but would require more than just running `tdnf -y install...`).
To this end, add a canonical source of truth for requirements (`prerequisites-src.json`). This is validated against changes in our documentation with a github action. The requirements change so rarely I don't believe its worth the complexity of automating this processes, detection and alerting should be sufficient.
A user may then call `sudo …

Toolkit: provide mechanism to auto-install build deps

---

.github/workflows/check-package-update-gate.yml
.github/workflows/packagelist-gate.csv
SPECS/packer/packer.spec

---
We are not letting some of the packages to be updated using this PR check gate. 
i) redis cannot be updated to 7.4 and above 
ii) packer cannot be updated to 1.10.0 and above
iii) terraform cannot be updated to 1.6.0 and above
iv) no version bump or addition of fdk-aac-free opus-file, and opus.
- Change: Gate for barring some of the package updates
- Added a csv file to that shows what version of packages cannot be added to the Azure Linux 
**YES/NO**
NO 
- Pipeline build id: locally and using the PR checks

PR check for terraform, redis, fdk-aac-free, opus and packer

---

SPECS/binutils/CVE-2025-0840.patch
SPECS/binutils/binutils.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
- Fix CVE-2025-0840 for binutils
**YES**
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=728577&view=results

[Medium] Fix CVE-2025-0840 for binutils

---

SPECS-EXTENDED/clucene/0001-Fix-missing-include-time.h.patch
SPECS-EXTENDED/clucene/0001-Make-sure-to-return-value-from-non-void-function.patch
SPECS-EXTENDED/clucene/0002-Avoid-deadlock-in-TestIndexSearcher.patch
SPECS-EXTENDED/clucene/clucene.spec

---
This PR is add essential patches for build fix of the package clucene along with fixing dependent package's build failures
- SPECS-EXTENDED/clucene/0001-Fix-missing-include-time.h.patch
- SPECS-EXTENDED/clucene/0001-Make-sure-to-return-value-from-non-void-function.patch
- SPECS-EXTENDED/clucene/0002-Avoid-deadlock-in-TestIndexSearcher.patch
- SPECS-EXTENDED/clucene/clucene.spec
**NO**
- #xxxx

Build fix of the package clucene

---

SPECS/cri-o/CVE-2023-0778.patch
SPECS/cri-o/CVE-2023-6476.patch
SPECS/cri-o/cri-o.spec

---
Patch CVE-2023-6476 & CVE-2023-0778
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-6476
- https://nvd.nist.gov/vuln/detail/CVE-2023-0778

Patch cri-o for CVE-2023-6476 & CVE-2023-0778 [MEDIUM]

---

SPECS/binutils/CVE-2025-1176.patch
SPECS/binutils/CVE-2025-1181.patch
SPECS/binutils/CVE-2025-1182.patch
SPECS/binutils/binutils.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Fix binutils CVEs CVE-2025-1176 CVE-2025-1181 CVE-2025-1182
- Fix binutils CVE-2025-1176 CVE-2025-1181 CVE-2025-1182
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1176
- https://nvd.nist.gov/vuln/detail/CVE-2025-1181
- https://nvd.nist.gov/vuln/detail/CVE-2025-1182
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=736132&view=results

Fix binutils CVE-2025-1176 CVE-2025-1181 CVE-2025-1182

---

SPECS-EXTENDED/python-PyMySQL/python-PyMySQL.signatures.json
SPECS-EXTENDED/python-PyMySQL/python-PyMySQL.spec
cgmanifest.json

---
Upgrade: python-PyMySQL version to 1.1.1
- modified:   SPECS-EXTENDED/python-PyMySQL/python-PyMySQL.signatures.json
- modified:   SPECS-EXTENDED/python-PyMySQL/python-PyMySQL.spec
**NO**
- #xxxx

Upgrade: python-PyMySQL version to 1.1.1

---

SPECS-EXTENDED/sdparm/sdparm.signatures.json
SPECS-EXTENDED/sdparm/sdparm.spec
cgmanifest.json

---
Upgrade: sdparm version 1.12
../SPECS-EXTENDED/sdparm/sdparm.signatures.json
../SPECS-EXTENDED/sdparm/sdparm.spec
**NO**
- #xxxx

Upgrade: sdparm version to 1.12

---

SPECS-EXTENDED/sbc/sbc.signatures.json
SPECS-EXTENDED/sbc/sbc.spec
cgmanifest.json

---
- Upgrade: sbc version to 2.0
- SPECS-EXTENDED/sbc/sbc.signatures.json
- SPECS-EXTENDED/sbc/sbc.spec
**NO**
- #xxxx

Upgrade: sbc version to 2.0

---

SPECS-EXTENDED/wavpack/wavpack.signatures.json
SPECS-EXTENDED/wavpack/wavpack.spec
cgmanifest.json

---
- SPECS-EXTENDED/wavpack/wavpack.signatures.json
- SPECS-EXTENDED/wavpack/wavpack.spec
**NO**
- #xxxx

Upgrade:wavpack to version 5.7.0

---

SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.signatures.json
SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
cgmanifest.json

---
**perl-Test-Synopsis: update version to 0.17**
- modified: SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
- modified: SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.signatures.json
**NO**
- #xxxx

perl-Test-Synopsis: Update Version from 0.16 -> 0.17

---

SPECS-EXTENDED/ocaml-calendar/ocaml-calendar.signatures.json
SPECS-EXTENDED/ocaml-calendar/ocaml-calendar.spec
cgmanifest.json

---
ocaml-calendar: update to 3.0.0
../SPECS-EXTENDED/ocaml-calendar/ocaml-calendar.signatures.json
../SPECS-EXTENDED/ocaml-calendar/ocaml-calendar.spec
[ocaml-calendar-3.0.0-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18202411/ocaml-calendar-3.0.0-1.azl3.src.rpm.log)
**NO**
- #xxxx

ocaml-calendar: update to 3.0.0

---

SPECS-EXTENDED/perl-Crypt-OpenSSL-Guess/perl-Crypt-OpenSSL-Guess.signatures.json
SPECS-EXTENDED/perl-Crypt-OpenSSL-Guess/perl-Crypt-OpenSSL-Guess.spec
cgmanifest.json

---
Upgrade: perl-Crypt-OpenSSL-Guess to 0.15
- SPECS-EXTENDED/perl-Crypt-OpenSSL-Guess/perl-Crypt-OpenSSL-Guess.signatures.json
**NO**
- #xxxx

Upgrade: perl-Crypt-OpenSSL-Guess to 0.15

---

SPECS-EXTENDED/libdmx/libdmx.signatures.json
SPECS-EXTENDED/libdmx/libdmx.spec
cgmanifest.json

---
Upgrade: libdmx version to 1.1.5
- SPECS-EXTENDED/libdmx/libdmx.signatures.json
- SPECS-EXTENDED/libdmx/libdmx.spec
**NO**
- #xxxx
- 
[libdmx-1.1.5-1.azl3.src.rpm.log](https://github.com/user-attachments/files/17815350/libdmx-1.1.5-1.azl3.src.rpm.log)

Upgrade: libdmx version to 1.1.5

---

SPECS-EXTENDED/libdap/libdap-offline.patch
SPECS-EXTENDED/libdap/libdap.signatures.json
SPECS-EXTENDED/libdap/libdap.spec
cgmanifest.json

---
Upgrade: libdap version to 3.21.0.27
SPECS-EXTENDED/libdap/libdap.signatures.json
SPECS-EXTENDED/libdap/libdap.spec
**NO**
- #xxxx

Upgrade: libdap version to 3.21.0.27

---

SPECS-EXTENDED/libcmis/libcmis.signatures.json
SPECS-EXTENDED/libcmis/libcmis.spec
SPECS-EXTENDED/libcmis/libxmis-0.6.2-libxml2-2.12.0-includes.patch
cgmanifest.json

---
Upgrade: libcmis version to 0.6.2
-SPECS-EXTENDED/libcmis/libcmis.signatures.json
-SPECS-EXTENDED/libcmis/libcmis.spec
**NO**
- #xxxx

Upgrade: libcmis version to 0.6.2

---

SPECS-EXTENDED/libjcat/libjcat.signatures.json
SPECS-EXTENDED/libjcat/libjcat.spec
cgmanifest.json

---
Update `libjcat` to current upstream
**NO**
- Local build.

Update libjcat to 0.2.2

---

SPECS-EXTENDED/fuse-overlayfs/fuse-overlayfs.signatures.json
SPECS-EXTENDED/fuse-overlayfs/fuse-overlayfs.spec
cgmanifest.json

---
fuse-overlayfs: Update to 1.14
-SPECS-EXTENDED/fuse-overlayfs/fuse-overlayfs.signatures.json
-SPECS-EXTENDED/fuse-overlayfs/fuse-overlayfs.spec
**NO**
- #xxxx

fuse-overlayfs: Update to 1.14

---

SPECS-EXTENDED/google-api-python-client/google-api-python-client.signatures.json
SPECS-EXTENDED/google-api-python-client/google-api-python-client.spec
cgmanifest.json

---
google-api-python-client: update to 2.140.0
../SPECS-EXTENDED/google-api-python-client/google-api-python-client.signatures.json
../SPECS-EXTENDED/google-api-python-client/google-api-python-client.spec
[google-api-python-client-2.140.0-1.azl3.src.rpm.log](https://github.com/user-attachments/files/17843883/google-api-python-client-2.140.0-1.azl3.src.rpm.log)
**NO**
- #xxxx

google-api-python-client: update to 2.140.0

---

SPECS-EXTENDED/ocaml-csv/ocaml-csv-bytes.patch
SPECS-EXTENDED/ocaml-csv/ocaml-csv.signatures.json
SPECS-EXTENDED/ocaml-csv/ocaml-csv.spec
cgmanifest.json

---
ocaml-csv: update to 2.4
../SPECS-EXTENDED/ocaml-csv/ocaml-csv.signatures.json
../SPECS-EXTENDED/ocaml-csv/ocaml-csv.spec
[ocaml-csv-2.4-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18245935/ocaml-csv-2.4-1.azl3.src.rpm.log)
**NO**
- #xxxx

ocaml-csv: update to 2.4

---

SPECS/emacs/CVE-2025-1244.patch
SPECS/emacs/emacs.spec

---
- Address CVE-2025-1244
- CVE-2025-1244
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1244
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=737278&view=results)

Patch `emacs` for CVE-2025-1244 [High]

---

SPECS/kured/CVE-2023-45288.patch
SPECS/kured/kured.spec

---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=736020&view=results)

Patch kured to fix CVE-2023-45288 [High]

---

toolkit/scripts/utils.mk

---
We are seeing very occasional failures in the toolkit. The symptoms are generally go tools reporting directories are not present. The way the Makefile is setup this should never be possible. Unfortunately we do not print any errors from the directory creation process currently, so it is not possible to debug further.
This adds a print for any stderr output from the mkdir commands. Hopefully this will give more insight into this failure if it occurs again.
- Update the Makefile's `create_folder` function to print `stderr` if any is generated by `mkdir`.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56157284
- Multiple runs of the sanity test, e.g.: …

Print errors when creating directories in Makefile

---

SPECS-EXTENDED/python-podman-api/python-podman-api.spec

---
Build fix: adding a macro for python-podman-api
- SPECS-EXTENDED/python-podman-api/python-podman-api.spec
**NO**
- #xxxx

Build fix: adding a macro for python-podman-api

---

SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.signatures.json
SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.spec
cgmanifest.json

---
Upgrade: python-pytest-subtests version to 0.12.1
- modified:   SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.signatures.json
- modified:   SPECS-EXTENDED/python-pytest-subtests/python-pytest-subtests.spec
**NO**
- #xxxx

Upgrade: python-pytest-subtests version to 0.12.1

---

SPECS-EXTENDED/asio/asio.signatures.json
SPECS-EXTENDED/asio/asio.spec
cgmanifest.json

---
Updates `asio` to current upstream version
- Bumped package version and had to include a new file in the `%files` installed.
**NO**
- Local build

Upgrade asio to 1.31.0-1

---

SPECS/libxml2/CVE-2024-56171.patch
SPECS/libxml2/CVE-2025-24928.patch
SPECS/libxml2/CVE-2025-27113.patch
SPECS/libxml2/libxml2.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
- Address CVE-2025-24928, CVE-2025-27113 & CVE-2024-56171 
- CVE-2025-24928
- CVE-2024-56171
- CVE-2025-27113
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-56171
- https://nvd.nist.gov/vuln/detail/CVE-2025-24928
- https://nvd.nist.gov/vuln/detail/CVE-2025-27113
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=743198&view=results)

 Patch `libxml2` for CVE-2025-24928, CVE-2025-27113 & CVE-2024-56171 [High]

---

SPECS/ldns/fix-intermittent-build-failure-with-milti-job-build.patch
SPECS/ldns/ldns.spec

---
`ldns` fails to build intermittently due to a problem with parallel builds.
[Upstream issue](https://github.com/NLnetLabs/ldns/issues/271).
This change applies the fix to the above issue.
- Apply upstream patch to fix `make -j` issues.
**NO**
ADO: https://microsoft.visualstudio.com/OS/_workitems/edit/56322679
- Built locally in a loop 10 times with 0 failures.
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=745639&view=results

ldns fix intermittent build failure

---

SPECS/libcap/CVE-2025-1390.patch
SPECS/libcap/libcap.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

Cherry Pick of https://github.com/microsoft/azurelinux/commit/9c3e6fd109bd04945a4cce474c412db1cb223a82 to 3.0-dev

Patch `libcap` for CVE-2025-1390 [Medium] (#12558)

---

SPECS/bind/bind.spec

---
`bind` has a warning during uninstall:
```
<snip>
Removing: bind-9.20.5-1.azl3.x86_64
/var/tmp/rpm-tmp.o0lrpa: line 12: Vendor:: command not found
/var/tmp/rpm-tmp.o0lrpa: line 13: Distribution:: command not found
warning: %postun(bind-9.20.5-1.azl3.x86_64) scriptlet failed, exit status 127
package bind-9.20.5-1.azl3.x86_64: script warning in %postun
```
The issue is that we we're missing a new-line at the of the `%postun` scriptlet, which makes the `Vendor:` and `Distribution:` lines sneak into that script, which means `bash` tries to run them as programs. Interestingly, if you drop an executable file at, say, `/usr/bin/Vendor:`, this will run it. Fun.
This has been there for …

fix bind postun

---

SPECS/dracut/0006-dracut.sh-validate-instmods-calls.patch
SPECS/dracut/dracut.spec

---
When we rebased our patches onto dracut-ng v102, block listing of crypto modules during fips module-setup.sh stopped working, throwing a series of errors due to a missing directory. This PR fixes the issue by adjusting the patch to block list the crypto modules correctly.
The theoretical purpose of this block list is to prevent unloading and loading crypto modules later on at runtime, which would then require re-running the selftests by reloading the tcrypt module
See: https://github.com/dracut-ng/dracut-ng/issues/1202 
- Reformat 0006-dracut.sh-validate-instmods-calls.patch
NO
- Test image build: …

[3.0] Adjust dracut patch to fix fips module block list behavior

---

SPECS/gnutls/CVE-2024-12133.patch
SPECS/gnutls/gnutls.spec

---
Address CVE-2024-12133 in gnutls package
- Add patch for CVE-2024-12133 in gnutls package
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-12133
-Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=746473&view=results

gnutls: Address CVE-2024-12133 [Medium]

---

SPECS/bind/bind.spec
SPECS/bind/fix-maybe-uninitialized-warning-in-dlz_mysqldyn_mod.patch

---
When building bind, we see a warning like this:
```
cc -fPIC -I../include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/azl/default-hardened-cc1    -fcommon -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/azl/default-hardened-ld  -shared -o dlz_mysqldyn_mod.so \
dlz_mysqldyn_mod.c dlz_dbi.o -L/usr/lib/ -lmariadb
dlz_mysqldyn_mod.c: In function 'build_query':
dlz_mysqldyn_mod.c:464:22: warning: 'arglist.head' may be used uninitialized …
```

patch bind uninitialized memory error

---

SPECS-EXTENDED/scl-utils/BZ-2056462-do-not-error-out-on-SIGINT.patch
SPECS-EXTENDED/scl-utils/BZ-2091000-remove-tmp-file.patch
SPECS-EXTENDED/scl-utils/brp-python-hardlink.patch
SPECS-EXTENDED/scl-utils/rpm-bare-words.patch
SPECS-EXTENDED/scl-utils/scl-utils.signatures.json
SPECS-EXTENDED/scl-utils/scl-utils.spec
cgmanifest.json

---
Upgrade: scl-utils version to 2.0.3
Please build following package with scl-utils:
iso-codes
- Depends on #10821 
- ../SPECS-EXTENDED/scl-utils/BZ-2056462-do-not-error-out-on-SIGINT.patch
- ../SPECS-EXTENDED/scl-utils/BZ-2091000-remove-tmp-file.patch
- ../SPECS-EXTENDED/scl-utils/brp-python-hardlink.patch
-  ../SPECS-EXTENDED/scl-utils/rpm-bare-words.patch
- ../SPECS-EXTENDED/scl-utils/scl-utils.signatures.json
-  ../SPECS-EXTENDED/scl-utils/scl-utils.spec
-  ../cgmanifest.json
**NO**
- #xxxx

Upgrade: scl-utils version to 2.0.3

---

SPECS-EXTENDED/speexdsp/speexdsp.signatures.json
SPECS-EXTENDED/speexdsp/speexdsp.spec
cgmanifest.json

---
Upgrade: speexdsp version to 1.2.1
../SPECS-EXTENDED/speexdsp/speexdsp.signatures.json
../SPECS-EXTENDED/speexdsp/speexdsp.spec
**NO**
- #xxxx

Upgrade: speexdsp version to 1.2.1

---

SPECS-EXTENDED/python-configshell/python-configshell.signatures.json
SPECS-EXTENDED/python-configshell/python-configshell.spec
cgmanifest.json

---
This PR is to upgrade the package python-configshell to version 1.1.30
- SPECS-EXTENDED/python-configshell/python-configshell.signatures.json
- SPECS-EXTENDED/python-configshell/python-configshell.spec
**NO**
- #xxxx
- Local Build

Upgrade: python-configshell to version 1.1.30

---

SPECS-EXTENDED/pyserial/pyserial.signatures.json
SPECS-EXTENDED/pyserial/pyserial.spec
cgmanifest.json

---
This PR is to upgrade the package pyserial to version 3.5
- SPECS-EXTENDED/pyserial/pyserial.signatures.json
- SPECS-EXTENDED/pyserial/pyserial.spec
**NO**
- #xxxx
- Local Build

Upgrade: pyserial to version 3.5

---

SPECS-EXTENDED/ps_mem/ps_mem.1
SPECS-EXTENDED/ps_mem/ps_mem.py
SPECS-EXTENDED/ps_mem/ps_mem.signatures.json
SPECS-EXTENDED/ps_mem/ps_mem.spec
cgmanifest.json

---
This PR is to upgrade the package ps_mem to version 3.14
- SPECS-EXTENDED/ps_mem/ps_mem.1
- SPECS-EXTENDED/ps_mem/ps_mem.py
- SPECS-EXTENDED/ps_mem/ps_mem.signatures.json
- SPECS-EXTENDED/ps_mem/ps_mem.spec
**NO**
- #xxxx
- Local Build

Upgrade: ps_mem to version 3.14

---

SPECS-EXTENDED/hunspell-nl/hunspell-nl.signatures.json
SPECS-EXTENDED/hunspell-nl/hunspell-nl.spec
cgmanifest.json

---
- SPECS-EXTENDED/hunspell-nl/hunspell-nl.signatures.json
- SPECS-EXTENDED/hunspell-nl/hunspell-nl.spec
**NO**
- #xxxx

Upgrade:hunspell-nl to version 2.20.19

---

SPECS-EXTENDED/perl-Regexp-Pattern-Perl/perl-Regexp-Pattern-Perl.signatures.json
SPECS-EXTENDED/perl-Regexp-Pattern-Perl/perl-Regexp-Pattern-Perl.spec
cgmanifest.json

---
**perl-Regexp-Pattern-Perl: update version to 0.007**
- modified: SPECS-EXTENDED/perl-Regexp-Pattern-Perl/perl-Regexp-Pattern-Perl.spec
- modified: SPECS-EXTENDED/perl-Regexp-Pattern-Perl/perl-Regexp-Pattern-Perl.signatures.json
NO
- #xxxx

perl-Regexp-Pattern-Perl: Update Version from 0.006 -> 0.007

---

SPECS-EXTENDED/go-rpm-macros/go-rpm-macros.signatures.json
SPECS-EXTENDED/go-rpm-macros/go-rpm-macros.spec
cgmanifest.json

---
go-rpm-macros: update to 3.6.0
../SPECS-EXTENDED/go-rpm-macros/go-rpm-macros.signatures.json
../SPECS-EXTENDED/go-rpm-macros/go-rpm-macros.spec
[go-rpm-macros-3.6.0-3.azl3.src.rpm.log](https://github.com/user-attachments/files/17834347/go-rpm-macros-3.6.0-3.azl3.src.rpm.log)
**NO**
- #xxxx

go-rpm-macros: update to 3.6.0

---

SPECS-EXTENDED/babl/babl.signatures.json
SPECS-EXTENDED/babl/babl.spec
cgmanifest.json

---
Update `babl` to current upstream
- Pretty simple version bump, though I had to change from `babl.pc` to `babl-0.1.pc` in `%{libdir}`
**NO**
- Local build

Update babl to 0.1.108-1

---

SPECS-EXTENDED/libthai/libthai.signatures.json
SPECS-EXTENDED/libthai/libthai.spec
cgmanifest.json

---
**libthai: update version to 0.1.29**
Please build the following package along with libthai:
**libdatrie**
- modified: SPECS-EXTENDED/libthai/libthai.spec
- modified: SPECS-EXTENDED/libthai/libthai.signatures.json
**NO**
- #xxxx

libthai: Update Version from 0.1.28 -> 0.1.29

---

SPECS-EXTENDED/libsigsegv/libsigsegv.signatures.json
SPECS-EXTENDED/libsigsegv/libsigsegv.spec
cgmanifest.json

---
The PR is to upgrade the package libsigsegv to version 2.14
- SPECS-EXTENDED\libsigsegv\libsigsegv.signatures.json
- SPECS-EXTENDED\libsigsegv\libsigsegv.spec
**NO**
- #xxxx

Upgrade: libsigsegv version to 2.14

---

SPECS-EXTENDED/libsigc++20/libsigc++20.signatures.json
SPECS-EXTENDED/libsigc++20/libsigc++20.spec
cgmanifest.json

---
The PR is to upgrade the libsigc++20 package to version 2.12.1
- SPECS-EXTENDED/libsigc++20/libsigc++20.signatures.json
- SPECS-EXTENDED/libsigc++20/libsigc++20.spec
**NO**
- #xxxx

Upgrade: libsigc++20 version to 2.12.1

---

SPECS-EXTENDED/libsass/libsass.signatures.json
SPECS-EXTENDED/libsass/libsass.spec
cgmanifest.json

---
The PR is to upgrade the libsass package to version 3.6.6
- SPECS-EXTENDED/libsass/libsass.signatures.json
- SPECS-EXTENDED/libsass/libsass.spec
**NO**
- #xxxx

Upgrade: libsass version to 3.6.6

---

SPECS-EXTENDED/libteam/libteam.signatures.json
SPECS-EXTENDED/libteam/libteam.spec
cgmanifest.json

---
**libteam: upgrade version to 1.32**
- modified: SPECS-EXTENDED/libteam/libteam.spec
- modified: SPECS-EXTENDED/libteam/libteam.signatures.json
**NO**
- #xxxx

libteam: Upgrade Version from 1.30 -> 1.32

---

SPECS-EXTENDED/libipt/libipt.signatures.json
SPECS-EXTENDED/libipt/libipt.spec
cgmanifest.json

---
Update `libipt` to current upstream
- Update to 2.1.1
**NO**
- Local build.

Update libipt to 2.1.1-1

---

SPECS-EXTENDED/edac-utils/13.patch
SPECS-EXTENDED/edac-utils/edac-utils.signatures.json
SPECS-EXTENDED/edac-utils/edac-utils.spec
cgmanifest.json

---
The PR is to upgrade the edac-utils package to version 0.18
- SPECS-EXTENDED/edac-utils/13.patch
- SPECS-EXTENDED/edac-utils/edac-utils.signatures.json
- SPECS-EXTENDED/edac-utils/edac-utils.spec
**NO**
- #xxxx

Upgrade: edac-utils version to 0.18

---

SPECS-EXTENDED/discount/define_destructor.patch
SPECS-EXTENDED/discount/discount-c99.patch
SPECS-EXTENDED/discount/discount.signatures.json
SPECS-EXTENDED/discount/discount.spec
SPECS-EXTENDED/discount/set_deps.patch
cgmanifest.json

---
**discount: update version to 2.2.7**
- newfile: SPECS-EXTENDED/discount/define_destructor.patch
- newfile: SPECS-EXTENDED/discount/discount-c99.patch
- newfile: SPECS-EXTENDED/discount/set_deps.patch
- modified: SPECS-EXTENDED/discount/discount.spec
- modified: SPECS-EXTENDED/discount/discount.signatures.json
**No**
- #xxxx

discount: Update Version from 2.2.4 -> 2.2.7

---

SPECS-EXTENDED/graphene/graphene.signatures.json
SPECS-EXTENDED/graphene/graphene.spec
cgmanifest.json

---
Bump `graphene` to 1.10.8
- I had to change the download URL as for the 1.10.8 release there was not
a named release like before (graphene-1.10.4.tar.xz), instead it was
just a versioned release (1.10.8.tar.gz)
**NO**
- Local build

Upgrade graphene to 1.10.8-1

---

SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
SPECS-SIGNED/iser-signed/iser-signed.spec
SPECS-SIGNED/isert-signed/isert-signed.spec
SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
SPECS-SIGNED/srp-signed/srp-signed.spec
SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
SPECS/fwctl/fwctl.spec
SPECS/iser/iser.spec
SPECS/isert/isert.spec
SPECS/kernel-64k/kernel-64k.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.spec
SPECS/knem/knem.spec
SPECS/mft_kernel/mft_kernel.spec
SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
SPECS/srp/srp.spec
SPECS/xpmem/xpmem.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Adding slang-devel to kernel spec, enabling perf tui
Perf's Makefile has a slang-devel check, which enables tui when slang is detected. (https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-3/6.6.78.1/tools/perf/Makefile.config#L765). Adding this package at built time will allow
perf --tui support
- Add slang-devel as a BR to enable tui for perf
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53509572
[Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=753668&view=results)
Validate fix
```
sudo tdnf install -y  kernel-tools-6.6.78.1-2.azl3.x86_64.rpm
perf record -e cycles -a -- ls
perf report
```
Example without …

Enable to tui for perf

---

SPECS-EXTENDED/apache-commons-daemon/apache-commons-daemon-build.xml
SPECS-EXTENDED/apache-commons-daemon/apache-commons-daemon.signatures.json
SPECS-EXTENDED/apache-commons-daemon/apache-commons-daemon.spec

---
apache-commons-daemon: Fix the build error
- apache-commons-daemon.signatures.json
- apache-commons-daemon-build.xml
**NO**
- #xxxx

apache-commons-daemon: Fix the build error

---

SPECS-EXTENDED/perl-Text-CSV_XS/perl-Text-CSV_XS.signatures.json
SPECS-EXTENDED/perl-Text-CSV_XS/perl-Text-CSV_XS.spec
cgmanifest.json

---
This PR is to upgrade the package perl-Text-CSV_XS version to 1.60
- SPECS-EXTENDED/perl-Text-CSV_XS/perl-Text-CSV_XS.signatures.json
- SPECS-EXTENDED/perl-Text-CSV_XS/perl-Text-CSV_XS.spec
**NO**
- #xxxx
- Local Build

Upgrade: perl-Text-CSV_XS version to 1.60

---

SPECS-EXTENDED/python-suds/python-suds.signatures.json
SPECS-EXTENDED/python-suds/python-suds.spec
SPECS-EXTENDED/python-suds/suds-pyname.patch
cgmanifest.json

---
Upgrade: python-suds version to 1.1.2
- SPECS-EXTENDED/python-suds/python-suds.signatures.json
- SPECS-EXTENDED/python-suds/python-suds.spec
- SPECS-EXTENDED/python-suds/suds-pyname.patch
**NO**
- #xxxx

Upgrade: python-suds version to 1.1.2

---

SPECS-EXTENDED/yelp-xsl/yelp-xsl.signatures.json
SPECS-EXTENDED/yelp-xsl/yelp-xsl.spec
cgmanifest.json

---
Upgrade: yelp-xsl vesion to 42.1
Please build following package with yelp-xsl:
python3-mallard-ducktype
- Depends on #11946 
- SPECS-EXTENDED/yelp-xsl/yelp-xsl.signatures.json
- SPECS-EXTENDED/yelp-xsl/yelp-xsl.spec
**NO**
- #xxxx

Upgrade: yelp-xsl vesion to 42.1

---

SPECS-EXTENDED/spausedd/spausedd.signatures.json
SPECS-EXTENDED/spausedd/spausedd.spec
cgmanifest.json

---
Upgrade: spausedd version to 20210719
- The PR is a leaf PR which builds alone successfully.
../SPECS-EXTENDED/spausedd/spausedd.signatures.json
../SPECS-EXTENDED/spausedd/spausedd.spec
- Change
- Change
- Change
**NO**
- #xxxx

Upgrade: spausedd version to 20210719

---

SPECS-EXTENDED/ocaml-tyxml/ocaml-tyxml-seq.patch
SPECS-EXTENDED/ocaml-tyxml/ocaml-tyxml.signatures.json
SPECS-EXTENDED/ocaml-tyxml/ocaml-tyxml.spec
cgmanifest.json

---
ocaml-tyxml: update to 4.6.0
- Depends on approved PR, ocaml-markup, #11723 
../SPECS-EXTENDED/ocaml-tyxml/ocaml-tyxml.signatures.json
../SPECS-EXTENDED/ocaml-tyxml/ocaml-tyxml.spec
[ocaml-tyxml-4.6.0-12.azl3.src.rpm.log](https://github.com/user-attachments/files/18231006/ocaml-tyxml-4.6.0-12.azl3.src.rpm.log)
**NO**
- #xxxx

ocaml-tyxml: update to 4.6.0

---

SPECS-EXTENDED/perl-Role-Tiny/perl-Role-Tiny.signatures.json
SPECS-EXTENDED/perl-Role-Tiny/perl-Role-Tiny.spec
cgmanifest.json

---
**perl-Role-Tiny: update version to 2.002004**
Please build the following package along with perl-Role-Tiny:
**perl-Class-Method-Modifiers**
- modified: SPECS-EXTENDED/perl-Role-Tiny/perl-Role-Tiny.spec
- modified: SPECS-EXTENDED/perl-Role-Tiny/perl-Role-Tiny.signatures.json
**NO**
- #xxxx

perl-Role-Tiny: Update Version from 2.001004 -> 2.002004

---

SPECS/dracut/90overlayfs/azl-configure-selinux.sh
SPECS/dracut/dracut.signatures.json
SPECS/dracut/dracut.spec

- [n/a] The toolchain has been rebuilt successfully (or no changes were made to it)
- [n/a] The toolchain/worker package manifests are up-to-date
- [ok] Any updated packages successfully build (or no packages were changed)
- [n/a] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ok] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ok] All package sources are available
- [ok] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, …

Dracut: Update Dracut overlay module to correctly locate 'chcon'

---

SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.signatures.json
SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.spec
cgmanifest.json

---
ocaml-extlib: update to 1.7.9
../SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.signatures.json
../SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.spec
[ocaml-extlib-1.7.9-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18203428/ocaml-extlib-1.7.9-1.azl3.src.rpm.log)
**NO**
- #xxxx

ocaml-extlib: update to 1.7.9

---

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh

---
Add hash verification for msopenjdk RPM downloaded during toolchain build process. This is a backport of the similar change for 3.0 in PR #10019 
Prevents error seen in the following buildRPMS pipeline when a corrupted file was downloaded: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=740797&view=logs&j=4e0f61e4-1b30-550f-20e5-747c73e9a1b3&t=e7762c05-aed0-53b0-82ec-2fcc69be9c17)
- Change toolchain script to hash verify and retry msopenjdk RPM download
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56349003
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId= …

[2.0] add msopenjdk rpm hash verification

---

SPECS-EXTENDED/perl-Net-Telnet/perl-Net-Telnet.signatures.json
SPECS-EXTENDED/perl-Net-Telnet/perl-Net-Telnet.spec
cgmanifest.json

---
**perl-Net-Telnet: update version to 3.05**
- modified: SPECS-EXTENDED/perl-Net-Telnet/perl-Net-Telnet.spec
- modified: SPECS-EXTENDED/perl-Net-Telnet/perl-Net-Telnet.signatures.json
**NO**
- #xxxx

perl-Net-Telnet: Update Version from 3.04 -> 3.05

---

SPECS/moby-containerd-cc/CVE-2023-39325.patch
SPECS/moby-containerd-cc/CVE-2023-44487.patch
SPECS/moby-containerd-cc/moby-containerd-cc.spec

---
This PR fixes CVE-2023-44487 for moby-containerd-cc. It also renames the file originally called "CVE-2023-44487.patch" to "CVE-2023-39325.patch", as that is the CVE which it actually patches. There was a time when it was thought that these two CVEs were equivalent. They are similar, but different. 
- Fixes CVE-2023-44487
**NO**
- #xxxx
- Pipeline build id: [754601](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=754601)

Fix CVE-2023-44487 for moby-containerd-cc

---

SPECS/bash-completion/bash-completion.spec
SPECS/influx-cli/influx-cli.spec

---
This PR is sort of a revert of this old PR #5583 . After doing investigation I have found that the `influx` completion file shipped by `bash-completion` package doesn't not functionally work well anymore with modern version of influx-cli. So, this pr makes the file be shipped by `influx-cli-bash-completion` subpackage instead. Fixed bug https://microsoft.visualstudio.com/OS/_workitems/edit/44770292
- Removed `%{_datadir}/bash-completion/completions/influx` completion file in `bash-completion` package as it no longer works well for modern version of influx
- Added bash `influx-cli-bash-completion` subpackage which ships `%{_datadir}/bash-completion/completions/influx` completion …

Restore back influx-cli-bash-completion subpackage and remove it from bash-completion

---

SPECS/gdb/gdb.spec

---
Enable cross-debugging all targets with gdb (to support debugging an AARCH64 crash dump on X86_64 host machine, for example)
- Change gdb to support all debugging targets
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=727086&view=results

gdb: enable debugging all targets

---

SPECS/cri-o/CVE-2025-27144.patch
SPECS/cri-o/cri-o.spec

---
Patch cri-o for CVE-2025-27144
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=768750&view=results

Patch cri-o for CVE-2025-27144 [medium]

---

toolkit/resources/manifests/package/license_file_exceptions.json

---
The license checker found several potential mishandled license files in `openssl-devel`. However, after looking at them, all of them are false positives that refer to APIs, not licenses.
- Update the license checker exception file to ignore these files.
**NO**
- ADO: https://microsoft.visualstudio.com/OS/_workitems/edit/56749229
- Manually ran `make license-check` on openssl rpms to verify these are now ignored.
- Manually tested the regex against the contents of `openssl-devel` to make sure it didn't exclude anything I didn't want excluded.
- Buddy Build shows no license check issues: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=767826&view=results
(TODO: Check arm64 build once it's done)

add license checker exceptions for openssl

---

SPECS/heimdal/CVE-2022-45142.patch
SPECS/heimdal/heimdal.spec

---
- Patch CVE-2022-45142
- CVE-2022-45142
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-45142
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=772491&view=results)

Patch `heimdal` for CVE-2022-45142 [High]

---

SPECS/telegraf/CVE-2024-51744.patch
SPECS/telegraf/CVE-2025-22870.patch
SPECS/telegraf/telegraf.spec

---
telegraf: Patch for CVE-2025-22870 and CVE-2024-51744
- new file: **SPECS/telegraf/CVE-2025-22870.patch**
- new file: **SPECS/telegraf/CVE-2024-51744.patch**
- modified: **SPECS/telegraf/telegraf.spec**
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22870

[Medium] Patch telegraf for CVE-2025-22870 and CVE-2024-51744

---

SPECS/moby-runc/CVE-2024-45310.patch
SPECS/moby-runc/moby-runc.spec

---
This PR adds a patch to moby-runc 1.1.9 to address CVE-2024-45310. 
- Patch CVE-2024-45310
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45310
[BuddyBuid](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=762778&view=resultss) rpm build succeded.
[AKS pre-release-tests](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=762236&view=results) passed.
[BVT](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=763101&view=results) passed

moby-runc: Add a patch to fix CVE 2024 45310

---

SPECS/msft-golang/msft-golang.signatures.json
SPECS/msft-golang/msft-golang.spec
cgmanifest.json

---
Update `msft-golang` to version 1.24.1 on 2.0 to fix the CVES mentioned below. I followed the 3.0 version of this spec to bump to the same version and add the same additional bootstrap step.
- Update msft-golang to 1.24.1
- Update golang bootstrap
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-34158
- https://nvd.nist.gov/vuln/detail/CVE-2024-45336
- https://nvd.nist.gov/vuln/detail/CVE-2024-45341
- https://nvd.nist.gov/vuln/detail/CVE-2025-22870
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=776256&view=results

msft-golang update to 1.24.1 for CVE-2025-22870, CVE-2024-45341, CVE-2024-45336, CVE-2024-34158

---

SPECS/sysbench/sysbench-1.0.20-fix_deprecated_egrep_call.patch
SPECS/sysbench/sysbench.spec

---
- Addresses an issue with the ptest by adding a patch to replace the deprecated egrep command with grep -E.
- Upstream Patch Reference : [Ref](https://github.com/akopytov/sysbench/commit/604c3c9f2ba4bb54b9f4d1e6f13886e323afeb5c) 
- Actual Failing Result
[Fasttrack Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=777947&view=results)
[3.0-dev Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=778182&view=results)
- Add patch to replace deprecated egrep with grep -E in SPEC, `sysbench-1.0.20-fix_deprecated_egrep_call.patch`
- Release Bump in SPEC file.
**NO**
- #xxxx …

[3.0] Fix ptest for `sysbench`

---

toolkit/tools/licensecheck/licensecheck.go
toolkit/tools/pkg/licensecheck/licensecheck.go
toolkit/tools/pkg/licensecheck/licensecheck_test.go
toolkit/tools/pkg/licensecheck/testdata/not_a_json.json

---
See this ADO bug: https://microsoft.visualstudio.com/OS/_workitems/edit/56788175
nil was being passed as the value of named return newLicenseChecker, which was being dereferenced within the cleanup function to do chroot cleanup. This caused the tool to break if malformed json files were used for names or exceptions.
- set newLicenseChecker to nil only after chroot cleanup has occurred if needed.
- fix a typo "whey" -> "they"
- add 2 new unit tests for the identified bad json scenarios
**NO**
- sudo make build-packages REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n DAILY_BUILD_ID=lkg SRPM_PACK_LIST=vim LICENSE_CHECK_MODE=warn -j100
- sudo make …

Add nil error trapping to licensecheck.go to allow for chroot cleanup on failure and exit gracefully

---

SPECS/libsepol/libsepol.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

It is needed by selinux-policy builds starting with 2.20250213.
---
Restore the chkcon tool in the libsepol-devel package.
- Restore the chkcon tool in the libsepol-devel package.
**YES** but only the libsepol-devel subpackage
- Pipeline build id: 778807

libsepol: Install chkcon tool in libsepol-devel.

---

SPECS/selinux-policy/0041-rpm-Allow-gpg-agent-run-in-rpm-scripts-to-watch-secr.patch
SPECS/selinux-policy/selinux-policy.spec

… root's secrets dir.
---
Add fix for gpg-agent use in rpm scripts for watching root's secrets dir
- Add fix for gpg-agent use in rpm scripts for watching root's secrets dir
**NO**
- Pipeline build id: 779916

selinux-policy: Add fix for gpg-agent use in rpm scripts for watching root's secrets dir

---

SPECS/curl/CVE-2025-0167.patch
SPECS/curl/curl.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
curl: Patch for CVE-2025-0167
- new file: **SPECS/curl/CVE-2025-0167.patch**
- modified: **SPECS/curl/curl.spec**
- modified: **toolkit/resources/manifests/package/pkggen_core_aarch64.txt**
- modified: **toolkit/resources/manifests/package/pkggen_core_x86_64.txt**
- modified: **toolkit/resources/manifests/package/toolchain_aarch64.txt**
- modified: **toolkit/resources/manifests/package/toolchain_x86_64.txt**
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-0167

[Low] Patch curl for CVE-2025-0167

---

SPECS/libssh2/libssh2.signatures.json
SPECS/libssh2/libssh2.spec
cgmanifest.json
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Bump to version 1.11.1 to fix CVE-2023-48795
- Bump version
- update cgmanifest
- update toolchain & package manifests
YES
- #xxxx
- Pipeline build id: [Full Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=779562&view=results)

Upgrade libssh2 to 1.11.1 for CVE-2023-48795 [Medium]

---

.github/workflows/check-srpm-duplicates.yml
toolkit/scripts/check_srpm_duplicates.py

---
In 3.0 we've recently noticed that some of our specs generate SRPMs with identical names. This was causing the following issues:
- In monthly production builds we'd end up publishing only one of the SRPMs out of all specs generating the same SRPM.
- In fast-track builds we'd fail the build during the (S)RPM signing phase as it detects duplicate RPM files.
This issue is not present in 2.0, so this change only backport the duplicate SRPMs PR check.
**NOTE**
Two specs may have the same `Name` tag but still generate different SRPMs due to differences in versions. These are expected and are not considered to be duplicates. Examples:
- `golang.spec` and `golang-1.23.spec`
- the two …

Adding SRPM duplicates check.

---

SPECS/flux/flux.spec

---
In the `%prep` section of the flux spec, it applies an inline patch using a heredoc with the ending token of `EOF` for the patch. This comes from upstream OpenSUSE. However, due to a copy-paste error in #4712 we don't have the ending `EOF`. This results in including the rest of the `%prep` script -- including the extra parts that `rpmbuild` itself adds that kills any outstanding jobs -- into the patch file. `patch` itself is smart enough to just ignore the "junk" at the end of a patch file, and warns about it. Fix for this is to add the `EOF`.
- Fix `EOF` issue.
**NO**
- ADO: https://microsoft.visualstudio.com/OS/_queries/edit/56985288/?queryId=29c5f91d-06aa-4d7e-83f2-d78e490cac48 …

flux warnings 2.0

---

SPECS/kata-packages-uvm/kata-packages-uvm.spec

---
Introduce kata-packages-uvm-debug metapackage
- Introduce kata-packages-uvm-debug metapackage
- Move curl, cpio, gzip, iputils, lvm2, tar, procps-ng to debug metapackage
- Remove bash, grep, readline, util-linux from all metapackages (implicit deps of existing requirements)
- Add findutils to debug metapackage
**YES/NO**
- #xxxx
- Tested via kata image build, kata conformance tests pass https://dev.azure.com/mariner-org/mariner/_build/results?buildId=760112&view=results 
- Deployed dev image, inspected the new set of images. Noted a net saving of ~8Mb in image size for the release UVM …

[3.0] Introduce debug and metapackage and reduce size of non-debug metapackage

---

SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
SPECS/edk2/CVE-2024-13176.patch
SPECS/edk2/CVE-2024-4741.patch
SPECS/edk2/edk2.spec

---
Fixes CVE-2024-13176 in the edk2 package's vendored openssl code.
Updated patch for CVE-2024-4741. Note that the previous patch applied correctly and fixed the vulnerability -- this is really a name change.
- Apply patch for CVE-2024-13176 in openssl vendored code in edk2
- Changed name of patch file for CVE-2024-4741 to standard name, replacing it with the patch for the correct version of openssl.
**NO**
- ADO: https://microsoft.visualstudio.com/OS/_workitems/edit/57166398
- https://nvd.nist.gov/vuln/detail/CVE-2024-13176
- Manually verified that the patches applied properly and code was changed.
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=787262&view=results

[Medium] edk2 openssl CVE-2024-13176

---

SPECS/flannel/CVE-2024-51744.patch
SPECS/flannel/flannel.spec

---
patch flannel to fix CVE-2024-51744
- flannel.spec
**YES/NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2024-51744

[Low]patch flannel for CVE-2024-51744

---

SPECS/telegraf/CVE-2024-35255.patch
SPECS/telegraf/CVE-2025-27144.patch
SPECS/telegraf/telegraf.spec

---
Patch telegraf for CVE-2024-35255 and CVE-2025-27144 [Medium].
- CVE-2024-35255 and CVE-2025-27144.patch with an upstream patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35255
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749066&view=results

Patch telegraf for CVE-2024-35255 and CVE-2025-27144 [Medium].

---

SPECS/ocaml-ctypes/ocaml-ctypes-stdlib-shims.patch
SPECS/ocaml-ctypes/ocaml-ctypes.spec

---
Fix ocaml-ctypes ptest 
- Change:  remove ocaml-shims deps from the test
**YES/NO**
NO
- Pipeline build id: [788138](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788138&view=results)

Fix ocaml-ctypes ptest

---

SPECS/ocaml-astring/ocaml-astring-ocaml5.patch
SPECS/ocaml-astring/ocaml-astring.spec

---
Fix Ocaml-Astring ptest by importing ocaml-astring-ocaml5 patch from Fedora
- Change: Char.compare in Ocaml 5 was changed. The patch import accounts for the change in the test expected values  
**YES/NO**
NO
- Pipeline build id: [788129](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788129&view=results)

Fix ocaml-astring ptest

---

SPECS/libsoup/CVE-2025-32906.patch
SPECS/libsoup/CVE-2025-32913.patch
SPECS/libsoup/libsoup.spec

---
Patch `libsoup` for CVE-2025-32913, CVE-2025-32906
- Add patch for CVE-2025-32913
- Add patch for CVE-2025-32906
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32913
- https://nvd.nist.gov/vuln/detail/CVE-2025-32906
- Local build

[High] Patch libsoup for CVE-2025-32913, CVE-2025-32906

---

SPECS/moby-containerd/CVE-2024-40635.patch
SPECS/moby-containerd/moby-containerd.spec

---
- Patch moby-containerd for CVE-2024-40635
- CVE-2024-40635
**NO**
- https://github.com/containerd/containerd/security/advisories/GHSA-265r-hfxg-fhmg
- https://nvd.nist.gov/vuln/detail/CVE-2024-40635
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783479&view=results (Pass)
- aks-pre-release tests: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783734&view=results (Running)

Patch moby-containerd for CVE-2024-40635 [medium]

---

SPECS/crash/crash.signatures.json
SPECS/crash/crash.spec

---
- Update gdb-10.2-3.tar.gz to address CVE-2021-20197, CVE-2022-47673, CVE-2022-47696
- CVE-2021-20197
- CVE-2022-47673
- CVE-2022-47696
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-20197
- https://nvd.nist.gov/vuln/detail/CVE-2022-47673
- https://nvd.nist.gov/vuln/detail/CVE-2022-47696
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792389&view=results)

Fix `crash` for CVE-2021-20197, CVE-2022-47673, CVE-2022-47696, CVE-2022-37434 [High]

---

SPECS/python-iniparse/0001-Fix-tests-with-python-3.12.1.patch
SPECS/python-iniparse/python-iniparse.spec

---
Import a patch from Fedora to fix a ptest case. A file was not properly imported inside the test that was failing. 
- Change: Import a patch from fedora to fix a ptest case
**YES/NO**
NO
- Pipeline build id: [782638](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782638&view=results)

fix python-iniparse ptest

---

SPECS-EXTENDED/ansible-freeipa/ansible-freeipa.signatures.json
SPECS-EXTENDED/ansible-freeipa/ansible-freeipa.spec
cgmanifest.json

---
ansible-freeipa: Update to 1.13.2
../SPECS-EXTENDED/ansible-freeipa/ansible-freeipa.signatures.json
../SPECS-EXTENDED/ansible-freeipa/ansible-freeipa.spec
**NO**
- #xxxx

ansible-freeipa: Update to 1.13.2

---

SPECS-EXTENDED/perl-Config-AutoConf/perl-Config-AutoConf.signatures.json
SPECS-EXTENDED/perl-Config-AutoConf/perl-Config-AutoConf.spec
cgmanifest.json

---
This PR is to upgrade the package perl-Config-AutoConf to version 0.320
- SPECS-EXTENDED/perl-Config-AutoConf/perl-Config-AutoConf.signatures.json
- SPECS-EXTENDED/perl-Config-AutoConf/perl-Config-AutoConf.spec
**NO**
- #xxxx
- Local Build

Upgrade: perl-Config-AutoConf version to 0.320

---

SPECS-EXTENDED/perl-Test2-Tools-Explain/perl-Test2-Tools-Explain.spec

---
Build Fix for perl-Test2-Tools-Explain version 0.02
- modified:   SPECS-EXTENDED/perl-Test2-Tools-Explain/perl-Test2-Tools-Explain.spec
**NO**
- #xxxx

Build Fix for perl-Test2-Tools-Explain version 0.02

---

SPECS-EXTENDED/python-IPy/python-IPy.signatures.json
SPECS-EXTENDED/python-IPy/python-IPy.spec
cgmanifest.json

---
This PR is to upgrade the package python-IPy to version 1.01
- SPECS-EXTENDED/python-IPy/python-IPy.signatures.json
- SPECS-EXTENDED/python-IPy/python-IPy.spec
**NO**
- #xxxx
- Local Build

Upgrade: python-IPy to version 1.01

---

SPECS-EXTENDED/rubygem-pkg-config/rubygem-pkg-config.signatures.json
SPECS-EXTENDED/rubygem-pkg-config/rubygem-pkg-config.spec
cgmanifest.json

---
Upgrade: rubygem-pkg-config version to 1.5.7
- modified:   SPECS-EXTENDED/rubygem-pkg-config/rubygem-pkg-config.signatures.json
- modified:   SPECS-EXTENDED/rubygem-pkg-config/rubygem-pkg-config.spec
**NO**
- #xxxx
Installing rubygem-pkg-config & rubygem-pkg-config-doc
Uninstalling rubygem-pkg-config & rubygem-pkg-config-doc

Upgrade: rubygem-pkg-config version to 1.5.7

---

SPECS/postfix/postfix.signatures.json
SPECS/postfix/postfix.spec
cgmanifest.json

---
Upgrade `postfix` to version 3.7.4, which is the first version to support compiling with Linux kernel 6.x
- Upgrade `postfix` to version 3.7.4
**NO**
- Bug: https://microsoft.visualstudio.com/OS/_workitems/edit/57268477
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=794577&view=results

postfix: upgrade to 3.7.4 [2.0]

---

SPECS/prometheus-adapter/CVE-2025-22872.patch
SPECS/prometheus-adapter/prometheus-adapter.spec

---
Patch prometheus-adapter for CVE-2025-22872
- SPECS/prometheus-adapter/CVE-2025-22872.patch
- SPECS/prometheus-adapter/prometheus-adapter.spec
**NO**
- #xxxx

[MEDIUM] Patch prometheus-adapter for CVE-2025-22872

---

SPECS/bcc/CVE-2025-29481.patch
SPECS/bcc/bcc.spec

---
patch bcc for CVE-2025-29481
-bcc.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-29481

[Medium] patch bcc for CVE-2025-29481

---

SPECS-EXTENDED/marisa/marisa.signatures.json
SPECS-EXTENDED/marisa/marisa.spec
cgmanifest.json

---
Upgrade: marisa version to 0.2.6
- SPECS-EXTENDED/marisa/marisa.signatures.json
- SPECS-EXTENDED/marisa/marisa.spec
**NO**
- #xxxx

Upgrade: marisa version to 0.2.6

---

SPECS/libxml2/CVE-2025-32414.patch
SPECS/libxml2/CVE-2025-32415.patch
SPECS/libxml2/libxml2.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
libxml2: Patch for CVE-2025-32414 and CVE-2025-32415
- new file: **SPECS/libxml2/CVE-2025-32414.patch**
- new file: **SPECS/libxml2/CVE-2025-32415.patch**
- modified: **SPECS/libxml2/libxml2.spec**
- modified: **toolkit/resources/manifests/package/pkggen_core_aarch64.txt**
- modified: **toolkit/resources/manifests/package/pkggen_core_x86_64.txt**
- modified: **toolkit/resources/manifests/package/toolchain_aarch64.txt**
- modified: **toolkit/resources/manifests/package/toolchain_x86_64.txt**
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-32414

[Medium] Patch libxml2 for CVE-2025-32414 and CVE-2025-32415

---

.pipelines/prchecks/PackageBuildPRCheck.yml
.pipelines/templates/PackageTestResultsAnalysis.yml

---
We're migrating all workloads to agents running AZL 3.0 and that includes this fast-track PR check as well.
Had to switch from installing our `python3-junit-xml` to a `pip install junit_xml`, because 3.0 AZL doesn't have the `python3-junit-xml` package. The `python3-junitxml` is a different Python module.
2.0 counterpart: #13701.
No.
- This PR check.

Switched the fast-track PR check to run on an AZL 3.0 agent pool.

---

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec

---
Change the management of the `/var/log/keysinuse` directory in the `SymCrypt-OpenSSL` spec from shell commands in the `%post` and `%postun` scriptlets to a `%dir` directive in the `%files` section. This has a few advantages:
1. It removes the implicit dependency on `/bin/sh` that the scriptlets pull in to run the shell commands. This dependency is undesirable on distroless containers and this package is installed by default everywhere, including distroless.
2. We no longer delete the log files on uninstall. According [Fedora's draft guidance](https://fedoraproject.org/wiki/PackagingDrafts/Logfiles), it is more correct to leave them.
3. It informs `rpm` that this package owns …

SymCrypt-OpenSSL -- Update mechanism for creating keysinuse logging directory.

---

SPECS/mock/disable-copying-ca-trust-dirs.patch
SPECS/mock/mock.spec

---
Backports to AZL3.0 an upstream `mock` change to fix runtime errors we've seen using `mock` to build Azure Linux 3.0 RPMs that have a build-time requirement on `ca-certificates`. The change allows us to disable `mock` from copying ca-trust dirs from the host system into the build root; this let us work around problems on an Azure Linux 3.0 host due to symlinks under `/etc/pki/ca-trust` causing conflicts within the build root.
More details can be found on the upstream change: https://github.com/rpm-software-management/mock/pull/1573.
Ports the linked PR to the version of `mock` in Azure Linux 3.0.
No
Local build + buddy build

mock: backport upstream change for disabling ca-trust copying

---

SPECS/python-asn1crypto/python-asn1crypto.spec
SPECS/python-asn1crypto/remove-import.patch
SPECS/python-gast/python-gast.spec
SPECS/python-mako/python-mako.spec
SPECS/python-nocasedict/python-nocasedict.spec

---
Fix ptest for python-asn1crypto, python-mako, python-gast, and python-nocasedict
- Change: Fix ptest for python-mako, python-gast, and python-nocasedict by using tox
- Change: Fix ptest for python-asn1crypto by using a different import module 
**YES/NO**
NO
- Pipeline build id: [808638](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=808638&view=results)

Fix ptest for python-asn1crypto, python-mako, python-gast, and python-nocasedict 

---

SPECS/rpm-ostree/CVE-2024-2905.patch
SPECS/rpm-ostree/rpm-ostree.spec

---
patch rpm-ostree for CVE-2024-2905
**YES/NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-2905

[Medium] patch rpm-ostree for CVE-2024-2905

---

SPECS/yasm/CVE-2023-37732.patch
SPECS/yasm/CVE-2023-51258.patch
SPECS/yasm/yasm.spec

---
patch yasm for CVE-2023-51258 and CVE-2023-37732
- SPECS/yasm/yasm.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-51258
- https://nvd.nist.gov/vuln/detail/CVE-2023-37732

[Medium] Patch yasm for CVE-2023-51258 and CVE-2023-37732

---

SPECS/docker-buildx/CVE-2025-0495.patch
SPECS/docker-buildx/docker-buildx.spec

---
Patch docker-buildx for CVE-2025-0495 [Medium]
- CVE-2025-0495
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-0495
- Pipeline build id: [807970](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=807970&view=results)

Patch docker-buildx for CVE-2025-0495 [Medium]

---

SPECS/pytorch/CVE-2025-2953.patch
SPECS/pytorch/pytorch.spec

---
Patch pytorch for CVE-2025-2953
- SPECS/pytorch/CVE-2025-2953.patch
- SPECS/pytorch/pytorch.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-2953

[MEDIUM] Patch pytorch for CVE-2025-2953

---

SPECS/javapackages-bootstrap/javapackages-bootstrap.spec

---
Avoid the following build failure regularly seen in nightly builds by not building in parallel and attempting the build twice. Add the incremental flag to avoid rebuilding if the first attempt fails. This same error has been reported [upstream](https://github.com/fedora-java/javapackages-bootstrap/issues/84). Note that this error has been seen regularly on nightly builds in 2.0 (with version 1.5.0), but the newer version of javapackages-bootstrap (1.14.0) on AZL 3.0 does not hit the same error.
```
"+ ./mbi.sh build -parallel"
"Exception in thread \"main\" java.lang.IllegalStateException: Dependency cycle: mbi-pdc -> maven-plugin-tools -> mbi-pdc"
"\tat …
```

[2.0] javapackages-bootstrap build reliability

---

SPECS/perl-Module-Implementation/perl-Module-Implementation.spec
SPECS/perl-Net-SSLeay/compatible-openssl.patch
SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec
SPECS/perl-URI/perl-URI.spec
SPECS/rubygem-introspection/rubygem-introspection.spec
SPECS/rubygem-metaclass/rubygem-metaclass.spec

---
Fix 5 ptest: perl-Net-SSLeay perl-Module-Implementation perl-URI rubygem-introspection rubygem-metaclass
- Change: perl-Net-SSLeay Add patch from the upstream to fix the failing test. 
- Change: perl-Module-Implementation : add missing test package
- Change: perl-URI : add missing test package
- Change: rubygem-introspection: Disable bundler while testing and disable a known failing test (imported from fedora 42).
- Change: rubygem-metaclass: disable bundler while testing 
**YES/NO**
NO
- Pipeline build id: [815406](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=815406&view=results)

Fix 5 more ptests (perl-Net-SSLeay perl-Module-Implementation perl-URI rubygem-introspection rubygem-metaclass)

---

SPECS/moby-engine/CVE-2024-51744.patch
SPECS/moby-engine/moby-engine.spec

---
Patch moby-engine for CVE-2024-51744
- new file:   SPECS/moby-engine/CVE-2024-51744.patch
- modified:   SPECS/moby-engine/moby-engine.spec
**NO**
- #xxxx

[Low] Patch moby-engine for CVE-2024-51744

---

SPECS/nodejs/CVE-2025-47279.patch
SPECS/nodejs/nodejs.spec

---
Address CVE-2025-47279
Upstream Patch: https://github.com/nodejs/undici/commit/f317618ec28753a4218beccea048bcf89c36db25
Excluded the below files as they were meant for testing and the testing infrastructure is missing from our current version of code.
test/pool-connection-error-memory-leak.js
test/tls-cert-leak.js
- modified: SPECS/nodejs/nodejs.spec
- added: SPECS/nodejs/CVE-2025-47279.patch
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2025-47279
- Due to insufficient memory in vm could not get a successful build. It fails with the same error even without my changes

[LOW] Patch nodejs for CVE-2025-47279

---

SPECS/cert-manager/CVE-2025-22872.patch
SPECS/cert-manager/CVE-2025-32386.patch
SPECS/cert-manager/cert-manager.spec

---
Patch `cert-manager` for CVE-2025-32386, CVE-2025-32387, and CVE-2025-22872
- Add patch for CVE-2025-32386 and CVE-2025-32387
- Add patch for CVE-2025-22872
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32386
- https://nvd.nist.gov/vuln/detail/CVE-2025-32387
- Local build

[Medium] Patch cert-manager for CVE-2025-32386, CVE-2025-32387, CVE-2025-22872

---

SPECS/jq/CVE-2024-23337.patch
SPECS/jq/jq.spec

---
Patch jq for CVE-2024-23337
- new file:   SPECS/jq/CVE-2024-23337.patch
- modified:   SPECS/jq/jq.spec
- 
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-23337

[Medium] Patch jq for CVE-2024-23337

---

SPECS/libvirt/CVE-2024-4418.patch
SPECS/libvirt/libvirt.spec

---
Addresses libvirt CVE-2024-4418
Patch file: https://gitlab.com/libvirt/libvirt/-/commit/8074d64dc2eca846d6a61efe1a9b7428a0ce1dd1
- Added: SPECS/libvirt/CVE-2024-4418.patch
- Modified: SPECS/libvirt/libvirt.spec
- Fixes CVE: CVE-2024-4418
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-4418
- local build

[MEDIUM] Patch libvirt for CVE-2024-4418

---

SPECS/nodejs/CVE-2025-23165.patch
SPECS/nodejs/CVE-2025-23166.patch
SPECS/nodejs/nodejs.spec

---
Address CVE-2025-23165 CVE-2025-23166
CVE-2025-23166 Upstream Patch Reference: https://github.com/nodejs/node/commit/6c57465920cf1b981a63031e71b1e4a73bf9beaa
CVE-2025-23165 Upstream Patch Reference: https://github.com/nodejs/node/commit/9e13bf0a81e15c7b3a9f1826dccbcea991d7e63a
- modified:   SPECS/nodejs/nodejs.spec
- added:  SPECS/nodejs/CVE-2025-23165.patch
- added:  SPECS/nodejs/CVE-2025-23166.patch
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2025-23165
- https://nvd.nist.gov/vuln/detail/CVE-2025-23166
- Due to insufficient memory in vm could not get a successful build. It fails with the same error even without my changes

[MEDIUM] Patch nodejs for CVE-2025-23165 CVE-2025-23166

---

SPECS/binutils/CVE-2025-5244.patch
SPECS/binutils/CVE-2025-5245.patch
SPECS/binutils/binutils.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Address CVE-2025-5245 CVE-2025-5244
CVE-2025-5245 Upstream Patch Reference: https://sourceware.org/git?p=binutils-gdb.git;a=patch;h=6c3458a8b7ee7d39f070c7b2350851cb2110c65a
CVE-2025-5244 Upstream Patch Reference: https://sourceware.org/git?p=binutils-gdb.git;a=patch;h=d1458933830456e54223d9fc61f0d9b3a19256f5
No modification in patches. Both patches applied cleanly.
Checked Build logs for successful application of both the patches.
- SPECS/binutils/CVE-2025-5244.patch
- SPECS/binutils/CVE-2025-5245.patch
- SPECS/binutils/binutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- …

[Medium] Patch binutils-2.37 for CVE-2025-5245 and CVE-2025-5244

---

SPECS/moby-buildx/CVE-2025-0495.patch
SPECS/moby-buildx/moby-buildx.spec

---
Addresses moby-buildx CVE-2025-0495 [MEDIUM]
Link to Debian patch that was referred while creating this patch:
https://github.com/docker/buildx/commit/0982070af84d476b232d2d75ab551c3222592db1
- modified:   ../SPECS/moby-buildx/moby-buildx.spec
- added: ../SPECS/moby-buildx/CVE-2025-0495.patc
**NO**
- None
- https://nvd.nist.gov/vuln/detail/CVE-2025-0495
- local build
- docker install
-

[MEDIUM] Patch moby-buildx for CVE-2025-0495

---

SPECS/opa/CVE-2025-46569.patch
SPECS/opa/opa.spec

---
Patch opa for CVE-2025-46569
Upstream patch applies cleanly
- Taken patch https://github.com/open-policy-agent/opa/commit/ad2063247a14711882f18c387a511fc8094aa79c from upstream. NIST mentions here https://nvd.nist.gov/vuln/detail/CVE-2025-46569 that it fixes this CVE.
- new file:   SPECS/opa/CVE-2025-46569.patch
- modified:   SPECS/opa/opa.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-46569
- Local Build

[High] Patch opa for CVE-2025-46569

---

SPECS/frr/CVE-2024-55553.patch
SPECS/frr/frr.spec

---
- Address CVE-2024-55553 by backport
Removes "revalidate all routes" logic and associated thread fields.
Changes bgpd_sync_callback to only revalidate affected prefixes, not all routes.
Removes is_stopping() static function in favor of direct access to the rtr_is_stopping field.
Removes t_revalidate_all from peer struct and related thread logic.
Introduces revalidate_single_prefix.
Cleans up memory and thread handling accordingly.
- CVE-2024-55553,
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-55553,
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=835318&view=results)

Patch `frr` for CVE-2024-55553 [High]

---

SPECS-EXTENDED/kernel-ipe/kernel-ipe.spec
SPECS-SIGNED/kernel-64k-signed/kernel-64k-signed.spec
SPECS-SIGNED/kernel-signed/kernel-signed.spec
SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
SPECS/kernel-64k/kernel-64k.spec
SPECS/kernel-headers/kernel-headers.spec
SPECS/kernel/kernel-uki.spec
SPECS/kernel/kernel.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
This PR updates the kernel spec file to ensure that the BTF (BPF Type Format) section is preserved in all built kernel modules. Specifically, it introduces the following change:
```
%define _find_debuginfo_opts --keep-section '.BTF'
```
This directive prevents the `find-debuginfo.sh` script (invoked during RPM build and packaged in debugedit) from removing the `.BTF` ELF section when stripping debug information from kernel modules.
`_find_debuginfo_opts` is an RPM macro for additional options passed to `find-debuginfo.sh`. ([link](https://github.com/rpm-software-management/rpm/blob/master/macros.in#L161))
`--keep-section` is an argument to find-debuginfo.sh as defined in [the …

Prevent stripping of BTF data from kernel modules

---

SPECS/libsoup/CVE-2025-32907.patch
SPECS/libsoup/libsoup.spec

---
Adds a patch for `libsoup` to fix CVE-2025-32907
- Also fix bogus date from previous change
Patch applies cleanly
Upstream Patch References:
1. https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/452/diffs?commit_id=9bb92f7a685e31e10e9e8221d0342280432ce836
2. https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/452/diffs?commit_id=eeace39ec686094ff6a05a43e5fce06e9c37f376
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32907
- Local build

[High] Patch libsoup for CVE-2025-32907

---

SPECS/nbdkit/CVE-2025-47711.patch
SPECS/nbdkit/CVE-2025-47712.patch
SPECS/nbdkit/nbdkit.spec

---
- Patch nbdkit for CVE-2025-47711 & CVE-2025-47712
- For CVE-2025-47711
- Patch Modified: No
- Astrolabe patch reference: https://gitlab.com/nbdkit/nbdkit/-/commit/c3c1950867ea8d9c2108ff066ed9e78dde3cfc3f 
-  For CVE-2025-47712
- Patch Modified: No
- Astrolabe patch reference: https://gitlab.com/nbdkit/nbdkit/-/commit/a486f88d1eea653ea88b0bf8804c4825dab25ec7
- 
- new file:  CVE-2025-47711.patch
- new file:  CVE-2025-47712.patch
- Modified file: nbdkit.spec
- Bump up the release.
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-47711
- https://nvd.nist.gov/vuln/detail/CVE-2025-47712
- Local Build log: 
[nbdkit-1.35.3-4.cm2.src.rpm.log](https://github.com/user-attachments/ …

[Medium] Patch nbdkit for CVE-2025-47711 & CVE-2025-47712

---

SPECS/protobuf/CVE-2025-4565.patch
SPECS/protobuf/protobuf.spec

---
Patch protobuf for CVE-2025-4565
- A new parameter `current_depth` has been added for the  files `decoder.py` and `python_message.py` from upstream v29.5 for proper application of patch.
- Apart from upstream patch, a file `python_message.py` was also backported to fix the build for `python-tensorboard`
- `python/google/protobuf/internal/decoder_test.py` is not present in source tarball. So, patch is not applied for that file.
- Some changes in the upstream patch are already included in the source tarball, so they won't appear in the modified patch.
Astrolabe Patch Reference: https://github.com/protocolbuffers/protobuf/commit/17838beda2943d08b8a9d4df5b68f5f04f2 …

[High] Patch protobuf for CVE-2025-4565

---

SPECS/rubygem-webrick/CVE-2025-6442.patch
SPECS/rubygem-webrick/rubygem-webrick.spec

---
Patch rubygem-webrick for CVE-2025-6442
**CVE-2025-6442**
**Patch Details**
- Patch Modified: Yes. Patch is modified in test/webrick/test_httprequest.rb file for backporting.
- Astrolab Reference: https://github.com/ruby/webrick/commit/ee60354bcb84ec33b9245e1d1aa6e1f7e8132101
- SPECS/rubygem-webrick/CVE-2025-6442.patch
- SPECS/rubygem-webrick/rubygem-webrick.spec
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-6442
- Local Build
[rubygem-webrick-1.7.0-2.cm2.src.rpm.log](https://github.com/user-attachments/files/20950947/rubygem-webrick-1.7.0-2.cm2.src.rpm.log)

[HIGH] Patch rubygem-webrick for CVE-2025-6442

---

SPECS/msft-golang/CVE-2025-22874.patch
SPECS/msft-golang/CVE-2025-4673.patch
SPECS/msft-golang/msft-golang.spec

---
Patch msft-golang for CVE-2025-22874 & CVE-2025-4673
- Patches are considered from Astrolabe
- No modifications are done for both CVE patches
- CVE-2025-22874.patch reference: https://go.googlesource.com/go/+/9bba799955e68972041c4f340ee4ea2d267e5c0e
- CVE-2025-4673.patch reference: https://go.googlesource.com/go/+/4d1c255f159d90557b43ede07f8b9a209e1fb49c
- SPECS/msft-golang/CVE-2025-22874.patch
- SPECS/msft-golang/CVE-2025-4673.patch
- SPECS/msft-golang/msft-golang.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22874
- https://nvd.nist.gov/vuln/detail/CVE-2025-4673
- …

[HIGH] Patch msft-golang for CVE-2025-22874 & [MEDIUM] CVE-2025-4673

---

SPECS/xorg-x11-server/CVE-2025-49175.patch
SPECS/xorg-x11-server/CVE-2025-49176.patch
SPECS/xorg-x11-server/CVE-2025-49178.patch
SPECS/xorg-x11-server/CVE-2025-49179.patch
SPECS/xorg-x11-server/CVE-2025-49180.patch
SPECS/xorg-x11-server/xorg-x11-server.spec

---
Patch xorg-x11-server for CVE-2025-49175, CVE-2025-49176, CVE-2025-49178, CVE-2025-49179 & CVE-2025-49180
- Patches are all taken from Astrolabe
- CVE-2025-49175 - https://gitlab.freedesktop.org/xorg/xserver/-/commit/0885e0b26225c90534642fe911632ec0779eebee
- CVE-2025-49176 - https://gitlab.freedesktop.org/xorg/xserver/-/commit/03731b326a80b582e48d939fe62cb1e2b10400d9
- CVE-2025-49178 - https://gitlab.freedesktop.org/xorg/xserver/-/commit/d55c54cecb5e83eaa2d56bed5cc4461f9ba318c2
- CVE-2025-49179 - https://gitlab.freedesktop.org/xorg/xserver/-/commit/2bde9ca49a8fd9a1e6697d5e7ef837870d66f5d4
- CVE-2025-49180 - …

[MEDIUM] Patch xorg-x11-server for CVE-2025-49175, CVE-2025-49176, CVE-2025-49178, CVE-2025-49179 & CVE-2025-49180

---

SPECS/xorg-x11-server-Xwayland/CVE-2025-49175.patch
SPECS/xorg-x11-server-Xwayland/CVE-2025-49177.patch
SPECS/xorg-x11-server-Xwayland/CVE-2025-49178.patch
SPECS/xorg-x11-server-Xwayland/CVE-2025-49179.patch
SPECS/xorg-x11-server-Xwayland/CVE-2025-49180.patch
SPECS/xorg-x11-server-Xwayland/xorg-x11-server-Xwayland.spec

---
Patch `xorg-x11-server-Xwayland` for CVE-2025-49175, CVE-2025-49177, CVE-2025-49178, CVE-2025-49179, CVE-2025-49180
**All patches sourced from Astrolabe**
- Add patch for CVE-2025-49175
* Patch unchanged from upstream besides adding upstream patch link
* Patch applied cleanly:
- Add patch for CVE-2025-49177
* Only edit to the upstream patch was because the patcher could not find where to position a hunk
* Patch applied cleanly:
- Add patch for CVE-2025-49178
* Patch unchanged from upstream besides adding upstream patch link
* Patch applied cleanly:
- Add patch for CVE-2025-49179
* Edited the include as compared with upstream because upstream moved
the include in a prior commit.
* …

[Medium] Patch xorg-x11-server-Xwayland for CVE-2025-49175, CVE-2025-49177, CVE-2025-49178, CVE-2025-49179, CVE-2025-49180

---

SPECS/redis/CVE-2025-48367.patch
SPECS/redis/redis.spec

---
Patches `redis` for CVE-2025-48367
- Add patch for CVE-2025-48367.patch
- Patch needed no modification besides adding upstream link (https://github.com/redis/redis/commit/0fe67435935cc5724ff6eb9c4ca4120c58a15765.patch)
- Patch applies cleanly:
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-48367
- Local build (some tests timed out twice in a row, I don't think I introduced any failures, I want to see if it passes the pipeline)

[High] Patch redis for CVE-2025-48367

---

SPECS/helm/CVE-2025-53547.patch
SPECS/helm/helm.spec

---
patch helm for CVE-2025-53547
Astrolabe Patch Reference: https://github.com/helm/helm/commit/4b8e61093d8f579f1165cdc6bd4b43fa5455f571
- helm.spec
- CVE-2025-53547.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-53547
- Verified patch is applied.
-  Verified build locally.
[helm-3.14.2-7.cm2.src.rpm.test.log](https://github.com/user-attachments/files/21179061/helm-3.14.2-7.cm2.src.rpm.test.log)
[helm-3.14.2-7.cm2.src.rpm.log](https://github.com/user-attachments/files/21179065/helm-3.14.2-7.cm2.src.rpm.log)

[High] patch helm for CVE-2025-53547

---

SPECS/ruby/CVE-2025-6442.patch
SPECS/ruby/ruby.spec

---
Patch `ruby` for CVE-2025-6442
- Patch found in astrolabe, modified by me so that it would apply. Link: https://github.com/ruby/webrick/commit/ee60354bcb84ec33b9245e1d1aa6e1f7e8132101.patch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-6442
- Local build
- Patch applies:

[High] Patch ruby for CVE-2025-6442

---

SPECS/git/CVE-2025-27613.patch
SPECS/git/CVE-2025-48384.patch
SPECS/git/CVE-2025-48385.patch
SPECS/git/git.spec

---
patch git for CVE-2025-48384, CVE-2025-48385 and CVE-2025-27613
- CVE-2025-48384
Astrolabe Patch Reference: https://github.com/git/git/commit/05e9cd64ee23bbadcea6bcffd6660ed02b8eab89
- CVE-2025-48385
Astrolabe Patch Reference: https://github.com/git/git/commit/35cb1bb0b92c132249d932c05bbd860d410e12d4
- CVE-2025-27613
https://nvd.nist.gov/vuln/detail/CVE-2025-27613https://nvd.nist.gov/vuln/detail/CVE-2025-27613 mentioned https://github.com/j6t/gitk/compare/7dd272eca153058da2e8d5b9960bbbf0b4f0cbaa..67a128b91e25978a15f9f7e194d81b441d603652 .
- git.spec
- CVE-2025-27613.patch
- CVE-2025-48385.patch
- CVE-2025-48384.patch …

[High] patch git for CVE-2025-48384, CVE-2025-48385 and CVE-2025-27613

---

SPECS/qtbase/CVE-2025-5455.patch
SPECS/qtbase/qtbase.spec

---
Patch qtbase for CVE-2025-5455
Upstream Patch reference: https://www.qt.io/blog/security-advisory-recently-discovered-issue-in-qdecodedataurl-in-qtcore-impacts-qt (v6.5)
Astrolabe Patch Reference:
for test: https://codereview.qt-project.org/c/qt/qtbase/+/642006/7/tests/auto/corelib/io/qdataurl/tst_qdataurl.cpp
Patches Modified: No
- new file:   SPECS/qtbase/CVE-2025-5455.patch
- modified:   SPECS/qtbase/qtbase.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-5455
- Local Build

[Medium] Patch qtbase for CVE-2025-5455

---

SPECS/git/Ptest-fix-git-config-syntax.patch
SPECS/git/git.spec

---
Coordinated fix for CVE-2025-48384.
For 3.0 branch, inorder to fix CVE-2025-48384, we performed version upgrade from 2.45.3-> 2.45.4.
With the upgrade, following two files 
1. `t1300.237 - writing value with trailing CR not stripped on read`
2. `t7450.50  submodule must not checkout into different directory`
had used new git config syntax (get, set, unset) which is not available in the older releases.
Reference: https://git-scm.com/docs/git-config#_deprecated_modes
So following are the changes in git subcommands which are being transitioned
| Old subcommand | New subcommand style|
| ------- | ------- |
| git config --get <name> | …

Fix git ptest with new git config syntax

---

SPECS/libxml2/CVE-2025-49794_CVE-2025-49796.patch
SPECS/libxml2/CVE-2025-6021.patch
SPECS/libxml2/CVE-2025-6170.patch
SPECS/libxml2/libxml2.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Added Patches for libxml2 for CVE-2025-49794, CVE-2025-49796[CRITICAL], CVE-2025-6021[MED], CVE-2025-6170[LOW]
- Added Patches for libxml2 CVEs
- Updated toolchain version for the package
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-49794
- https://nvd.nist.gov/vuln/detail/CVE-2025-49796
- https://nvd.nist.gov/vuln/detail/CVE-2025-6021
- https://nvd.nist.gov/vuln/detail/CVE-2025-6170
- Pipeline build id: [873677](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=873677&view=results)

Patch libxml2 for CVE-2025-49794, CVE-2025-49796[CRITICAL], CVE-2025-6021[MED], CVE-2025-6170[LOW]

---

SPECS/nodejs/CVE-2025-7656.patch
SPECS/nodejs/nodejs18.spec

---
Patch `nodejs18` for CVE-2025-7656
- Add [patch](https://chromium.googlesource.com/v8/v8/+/c58fda1f0ec46429dd66c2cacf6a98fac001e4fd%5E%21/) for CVE-2025-7656 (edited slightly during the `git apply` process so that it applies cleanly
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-7656
- Local build

[High] Patch nodejs18 for CVE-2025-7656

---

SPECS/rubygem-webrick/CVE-2023-40225-content-length-validation.patch
SPECS/rubygem-webrick/CVE-2025-6442.patch
SPECS/rubygem-webrick/rubygem-webrick.spec

---
- The  patch CVE-2025-6442.patch adds some tests, but it doesn't include the actual code those tests are meant to check. Because of this, the tests fail when this patch is applied.(These patches can be removed when upgraded to 1.8.2)
- Added an extra patch that brings in the missing code.  (Although it is patch version upgrade, starting from version 1.8.2, Webrick depends on a new gem called test-unit-ruby-core. Before that, it used some test helper files that were part of the same repo.But since test-unit-ruby-core is not available in Azure Linux, we're staying on version 1.8.1 for now and using patches.)
- Add %check section
- Add …

rubygem-webrick: Add %check section

---

SPECS/cri-tools/CVE-2025-22872.patch
SPECS/cri-tools/cri-tools.spec

---
Address CVE-2025-22872
Backported from upstream patch: https://github.com/golang/net/commit/e1fcd82abba34df74614020343be8eb1fe85f0d9
Excluded token_test.go as this file and the test infrastructure is absent in the current version of our code.
- modified: SPECS/cri-tools/cri-tools.spec
- added: SPECS/cri-tools/CVE-2025-22872.patch
**NO**
- NA
- local build

[MEDIUM] Patch cri-tools for CVE-2025-22872

---

SPECS/glib/CVE-2025-4373.patch
SPECS/glib/glib.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Address CVE-2025-4373
Upstream Patch Applies Cleanly: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4588.patch
Patch commit in astrolabe: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4588/diffs?commit_id=cc647f9e46d55509a93498af19659baf9c80f2e3
Also checked local build log file to ensure patch applied cleanly.
- modified:   ../SPECS/glib/glib.spec
- modified:   resources/manifests/package/pkggen_core_aarch64.txt
- modified:   resources/manifests/package/pkggen_core_x86_64.txt
- modified:   resources/manifests/package/toolchain_aarch64.txt
- modified:   resources/manifests/package/toolchain_x86_64.txt
- added:   ../SPECS/glib/CVE-2025-4373.patch
**YES**
- #NA
- …

[MEDIUM] Patch glib for CVE-2025-4373

---

toolkit/imageconfigs/files/common/99-dhcp-eth0.network
toolkit/imageconfigs/files/osguard/repart.d/14-root-a.conf
toolkit/imageconfigs/files/osguard/repart.d/18-root-b.conf
toolkit/imageconfigs/linuxguard-amd64.yaml
toolkit/imageconfigs/osguard-amd64.yaml
toolkit/imageconfigs/scripts/common/move-iptables-scripts-to-usr.sh
toolkit/imageconfigs/scripts/common/remove-getty-import-credential.sh
toolkit/imageconfigs/scripts/common/tmp-no-exec.sh
toolkit/scripts/generate-repartd.sh

---
- Enables stable interface names
- Works around missing credentials directory
- Stops reinstalling initramfs
- Reenables selinux-policy-ci
- Reorders AKS packages for cleanliness
- Removes custom eth0 configuration
- Disables SSHD (though it gets reenabled in runtime anyway)
**NO**
- Image built using BuildVariants dev pipelines and validated by creating custom BYOI AKS cluster

Additional cleanup for the OSGuard image definition

---

SPECS/apache-commons-lang3/CVE-2025-48924.patch
SPECS/apache-commons-lang3/apache-commons-lang3.spec

---
Addresses CVE-2025-48924
Patch backported : Yes
Excluded ClassUtilsOssFuzzTest.java file during backporting since its a binary test file
Patch reference from Astrolabe: https://github.com/apache/commons-lang/commit/b424803abdb2bec818e4fbcb251ce031c22aca53
- modified: SPECS/apache-commons-lang3/apache-commons-lang3.spec
- added: SPECS/apache-commons-lang3/CVE-2025-48924.patch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-48924
- local build:
- Patch applies cleanly: 
- build log: 
[apache-commons-lang3-3.8.1-6.cm2.src.rpm.log](https://github.com/user-attachments/files/21264611/apache-commons-lang3-3.8.1-6.cm2.src.rpm.log)

[MEDIUM] Patch apache-commons-lang3 for CVE-2025-48924

---

SPECS/ruby/CVE-2025-24294.patch
SPECS/ruby/ruby.spec

---
Patch ruby for [CVE-2025-24294](https://nvd.nist.gov/vuln/detail/CVE-2025-24294)
Upstream Patch Reference: https://ubuntu.com/security/CVE-2025-24294 navigates to https://github.com/ruby/resolv/commit/4c2f71b5e80826506f78417d85b38481c058fb25
- new file:   SPECS/ruby/CVE-2025-24294.patch
- modified:   SPECS/ruby/ruby.spec
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-24294
- Local build
- Build is successful -
[ruby-3.1.7-3.cm2.src.rpm.log](https://github.com/user-attachments/files/21230740/ruby-3.1.7-3.cm2.src.rpm.log)
- Test is successful -
[ruby-3.1.7-3.cm2.src.rpm.test.log](https://github.com/user-attachments/files/21230762/ruby-3 …

[Medium] Patch ruby for CVE-2025-24294

---

SPECS/python-urllib3/CVE-2025-50181.patch
SPECS/python-urllib3/python-urllib3.spec

---
[Medium] Patch python-urllib3 for CVE-2025-50181
Astrolabe patch reference:  https://github.com/urllib3/urllib3/commit/f05b1329126d5be6de501f9d1e3e36738bc08857
- The bug fix change details are added in v1.26.19 instead of v2.5.0. Because the azure linux source version is v1.26.19. Here, the upstream patch is for v2.5.0
- Two files are not available: emscripten.rst, app.py.
- And one test file also not available: test_emscripten.py
- Modified File: python-urllib3.spec
- New file: CVE-2025-50181.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-50181
- Local build
- This Patch has been applied cleanly.
- This is the log before i applied my …

[Medium] Patch python-urllib3 for CVE-2025-50181

---

toolkit/imageconfigs/files/osguard/repart.d/12-usr-a.conf
toolkit/imageconfigs/files/osguard/repart.d/16-usr-b.conf
toolkit/scripts/generate-repartd.sh

---
To avoid mismatch of partition type information between original
partitioning and repart.d configuration, this change updates the
repart.d generation script for osguard to use the type already present
rather than overwriting the partition type information.
The change also regenerates the osguard repart.d files so the usr-a/b
type information matches what is present in the osguard image, so
systemd-repartd is successful.
**NO**
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/14618
- Pipeline build id: [895311](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=895311&view=results)

osguard: fix usr-a/b repart.d types to match image

---

SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.signatures.json
SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.spec
cgmanifest.json

---
This PR is to upgrade the package perl-Locale-Maketext-Gettext version to 1.32
- SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.signatures.json
- SPECS-EXTENDED/perl-Locale-Maketext-Gettext/perl-Locale-Maketext-Gettext.spec
**NO**
- #xxxx
- Local Build

Upgrade: perl-Locale-Maketext-Gettext version to 1.32

---

SPECS/sqlite/CVE-2025-6965.patch
SPECS/sqlite/CVE-2025-7458.patch
SPECS/sqlite/sqlite.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Patch sqlite for CVE-2025-6965 and CVE-2025-7458
- Added patches for CVE-2025-6965 and CVE-2025-7458
- Updated toolchain manifest and sqlite spec file
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-6965
- https://nvd.nist.gov/vuln/detail/CVE-2025-7458
- Pipeline build id: [889318](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=889318&view=results)

Patch sqlite for CVE-2025-6965[HIGH], CVE-2025-7458[MEDIUM]

---

toolkit/tools/internal/azureblobstorage/azureblobstorage.go
toolkit/tools/internal/ccachemanager/ccachemanager.go

---
Internal Microsoft policy requires us to not use `NewDefaultAzureCredential` when logging into Azure. In all cases where we used the default method in our builds we relied on Azure CLI credentials, thus the switch to `NewAzureCLICredential`.
For more information see the [AzureCLICredential docs](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-authenticating-during-local-development).
The change also has minor Go linting clean-up.
No.
- [Internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/58688069).
- PR checks.
- Local runs of the code downloading blob contentents.

[3.0] Change default AZ creds to AZ CLI creds.

---

SPECS/conda/conda.spec

---
=> This PR fixes bash init issue: This issue is when the customer does conda init bash, it fails. 
=> To fix the 1st issue added the missing shell files. These new hook files will never be used as we do not provide xsh and fish shell but conda does look for them regardless when we init conda for bash. 
- Change: Fix conda init bash
**YES/NO**
NO
Fixes bug: [58420438](https://microsoft.visualstudio.com/OS/_workitems/edit/58420438) 
- Pipeline build id: [893035](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=893035&view=results)

Fix "Conda init bash" issue.

---

SPECS/glib/CVE-2025-4373.patch
SPECS/glib/CVE-2025-6052.patch
SPECS/glib/glib.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Address CVE-2025-4373 and CVE-2025-6052
CVE-2025-4373:
Upstream Patch reference: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4588.patch
Patch link found in Astrolabe
CVE-2025-6052:
Upstream Patch Applies cleanly: https://gitlab.gnome.org/GNOME/glib/-/commit/37eecaa7efc48a0df22277444ff25ff791ac0ac1
Patch link found in Astrolabe
- modified:   ../SPECS/glib/glib.spec
- modified:   resources/manifests/package/pkggen_core_aarch64.txt
- modified:   resources/manifests/package/pkggen_core_x86_64.txt
- modified:   resources/manifests/package/toolchain_aarch64.txt
- modified:   resources/manifests/package/toolchain_x86_64.txt
- added: …

[MEDIUM] Patch glib for CVE-2025-4373 and CVE-2025-6052

---

SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
SPECS/systemd/systemd.spec

---
Following along the addition of the unsigned aarch64 systemd-boot package in PR #14449 , this adds the signed systemd-boot package for aarch64 architecture.
- Update systemd-boot-signed SPEC to include building the aarch64 package
NO
- pipeline BuildID: 911568
- Verified a signed systemd-boot.aarch64.rpm was built, contents were signed, and booted an image with sdboot
- pipeline BuildID: 912594
- Verified a signed systemd-boot.x86_64.rpm was built and contents were signed

systemd-boot-signed: add aarch64 package

---

SPECS/glib/CVE-2024-34397.patch
SPECS/glib/glib.spec
toolkit/resources/manifests/package/pkggen_core_aarch64.txt
toolkit/resources/manifests/package/pkggen_core_x86_64.txt
toolkit/resources/manifests/package/toolchain_aarch64.txt
toolkit/resources/manifests/package/toolchain_x86_64.txt

---
Patch glib for CVE-2024-34397
- Patch considered from Astrolabe
- Upstream Patch Reference: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4039.diff
- Slight modification in patch line:243 - changed `g_set_str ` ->  `g_strrstr ` to match the source 
- added: SPECS/glib/CVE-2024-34397.patch
- modified: SPECS/glib/glib.spec
- modified: toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- modified: toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- modified: toolkit/resources/manifests/package/toolchain_aarch64.txt
- modified: toolkit/resources/manifests/package/toolchain_x86_64.txt
**YES**
- #xxxx
- …

[MEDIUM] Patch glib for CVE-2024-34397

---

SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.signatures.json
SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
cgmanifest.json

---
This PR is to upgrade the package perl-Crypt-OpenSSL-RSA to version 0.33
- SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.signatures.json
- SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
**NO**
- #xxxx
- Local Build. (Needs to be build along with perl-Crypt-OpenSSL-Bignum, perl-Crypt-OpenSSL-Guess, perl-Crypt-OpenSSL-Random)
- Installation/Uninstallation verified on 3.0 container

Upgrade: perl-Crypt-OpenSSL-RSA to version 0.33

---

SPECS/python-virtualenv/CVE-2025-50181v0.patch
SPECS/python-virtualenv/CVE-2025-50181v1.patch
SPECS/python-virtualenv/CVE-2025-50181v2.patch
SPECS/python-virtualenv/CVE-2025-50181v3.patch
SPECS/python-virtualenv/python-virtualenv.spec

---
Addresses python-virtualenv CVE-2025-50181
https://github.com/advisories/GHSA-pq67-6m6q-mj2v
-- Patch modified: Yes
-- Patch was backported for poolmanager.py, rest of the files [CHANGES.rst, docs/reference/contrib/emscripten.rst, dummyserver/app.py, test/contrib/emscripten/test_emscripten.py, test/test_poolmanager.py, test/with_dummyserver/test_poolmanager.py] are not available for the version of urllib3 being used along with this package.
-- Patch link found in Astrolabe: https://github.com/urllib3/urllib3/commit/f05b1329126d5be6de501f9d1e3e36738bc08857
- modified: SPECS/python-virtualenv/python-virtualenv.spec
- added: SPECS/python-virtualenv/CVE-2025-50181v0.patch
- added: …

[MEDIUM] Patch for python-virtualenv CVE-2025-50181

---

SPECS/coredns/CVE-2025-47950.patch
SPECS/coredns/coredns.spec

---
We were getting random failure for `coredns` and an investigation has revealed that it's due to `make` sometimes attempting to run this `coredns` target defined in `Makefile`:
```make
core/plugin/zplugin.go core/dnsserver/zdirectives.go: plugin.cfg
go generate coredns.go
go get
```
The two z*.go files along with `plugin.cfg` are present inside the repository but patch `CVE-2025-47950.patch` modifies all of them starting with the z*.go files. This made it possible for the mtime for `plugin.cfg` to sometimes be newer than for the z*.go files, causing `make` to believe the z*.go files are stale. Since the target for these files runs `go get`, this failed the builds when the network …

Fixed `coredns` random rebuilds bug.

---

SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
SPECS/systemd/CVE-2025-4598.patch
SPECS/systemd/systemd.spec

---
Patch systemd for CVE-2025-4598
**For CVE-2025-4598:**
- Modified the file `man/version-info.xml` by adding XML id (from upstream), because the file `systemd-coredump.xml` introduced new id in upstream patch. Without this modification the build fails. Except this, every file change matches with upstream patch.
Taken patch https://github.com/systemd/systemd-stable/commit/254ab8d2a7866679cee006d844d078774cbac3c9 from upstream. Debian mentions here https://security-tracker.debian.org/tracker/CVE-2025-4598 , https://www.qualys.com/2025/05/29/apport-coredump/apport-coredump.txt that it fixes this CVE
- new file:   SPECS/systemd/CVE-2025-4598.patch
- modified: …

[Medium] Patch systemd for CVE-2025-4598

---

SPECS/erlang/CVE-2025-48039.patch
SPECS/erlang/erlang.spec

---
Patch erlang for CVE-2025-48039
Modified patch: YES
- Some of the changes in the upstream patch are already in the azl source, these were included in previous patches.
- last hunk in the file `lib/ssh/test/ssh_sftpd_SUITE.erl` of upstream patch is already introduced by one of the existing patches. So, excluded that change in this patch.
Taken patch https://github.com/erlang/otp/commit/043ee3c943e2977c1acdd740ad13992fd60b6bf0 from upstream. Debian mentions here https://security-tracker.debian.org/tracker/CVE-2025-48039 that it fixes this CVE.
- new file:   SPECS/erlang/CVE-2025-48039.patch
- modified:   SPECS/erlang/erlang.spec
**NO**
- #xxxx
- …

[Medium] Patch erlang for CVE-2025-48039
