- SPECS/vte291/CVE-2024-37535.patch
- SPECS/vte291/vte291.spec
---
vte291: patch CVE-2024-37535
- vte291: patch CVE-2024-37535
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-37535
> vte291: patch CVE-2024-37535

- SPECS/libndp/CVE-2024-5564.patch
- SPECS/libndp/libndp.spec
---
Patches CVE-2024-5564 in libndp
- Patches CVE-2024-5564 in libndp
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-5564
- Pipeline build id: see PR check builds.
> Patch CVE-2024-5564 in libndp

- SPECS/yasm/CVE-2021-33454.patch
- SPECS/yasm/yasm.spec
---
yasm: patch CVE-2021-33454 (upstream patch https://github.com/yasm/yasm/pull/244/commits/48ced849ed621a05cec4c04d4567323af3a76e81)
- yasm
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=588803&view=results
> yasm: patch CVE-2021-33454

- toolkit/scripts/update_toolchain_manifest.py
---
add script to update toolchain and package manifest
- add script to update toolchain and package manifest
**NO**
- Local build
`python3 update_toolchain_manifest.py ../resources/manifests/package/pkggen_core_x86_64.txt ../../SPECS/cmake/cmake.spec .
./../SPECS/glibc/glibc.spec ../../SPECS/grpc/grpc.spec`
updated manifest for cmake and glibc (if a version or release number was detected), and no changes for grpc as the package is not a part of manifest
> add script to update toolchain and package manifest

- SPECS/influxdb/CVE-2021-4238.patch
- SPECS/influxdb/influxdb.spec
---
fix CVE-2021-4238
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-4238
- Pipeline build id: 589695
> 3.0-dev - influxdb fix CVE-2021-4238

- SPECS/wget/CVE-2024-38428.patch
- SPECS/wget/wget.spec
---
wget: patch CVE-2024-38428. Upstream patch from https://git.savannah.gnu.org/cgit/wget.git/commit/?id=ed0c7c7e0e8f7298352646b2fd6e06a11e242ace
- wget
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-38428
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=589564&view=results
> wget: patch CVE-2024-38428

- SPECS/azurelinux-release/azurelinux-release.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> azurelinux-release: bump to 3.0-15 for June preview update 2

- SPECS/mariadb/CVE-2024-0901.patch
- SPECS/mariadb/mariadb.spec
---
mariadb: patch CVE-2024-0901
- mariadb: patch CVE-2024-0901
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-0901
> [3.0] mariadb: patch CVE-2024-0901

- toolkit/tools/pkg/imagecustomizerlib/runscripts_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/runscripts-writefiles-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/kangaroo.sh
- toolkit/tools/pkg/imagecustomizerlib/testdata/scripts/wombat.py
> Image Customizer: Add tests for scripts.

- SPECS/coredns/CVE-2023-44487.patch
- SPECS/coredns/CVE-2023-45288.patch
- SPECS/coredns/CVE-2023-49295.patch
- SPECS/coredns/CVE-2024-0874.patch
- SPECS/coredns/CVE-2024-22189.patch
- SPECS/coredns/coredns.spec
---
Address CVE-2023-44487, CVE-2023-45288, CVE-2023-49295, CVE-2024-0874, CVE-2024-22189
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-44487, 
- https://nvd.nist.gov/vuln/detail/CVE-2023-45288, 
- https://nvd.nist.gov/vuln/detail/CVE-2023-49295, 
- https://nvd.nist.gov/vuln/detail/CVE-2024-0874, 
- https://nvd.nist.gov/vuln/detail/CVE-2024-22189
- Pipeline build id: 592413
> 3.0-dev - coredns - Address CVE-2023-44487, CVE-2023-45288, CVE-2023-49295, CVE-2024-0874, CVE-2024-22189

- SPECS/vitess/generate_source_tarball.sh
- SPECS/vitess/vitess.signatures.json
- SPECS/vitess/vitess.spec
- cgmanifest.json
---
upgrade vitess to 19.0.4 to address CVEs
- Change
- Change
- Change
**NO**
- #xxxx
- Pipeline build id: 593162
> upgrade vitess to 19.0.4 to address CVEs

- SPECS/c-ares/c-ares.signatures.json
- SPECS/c-ares/c-ares.spec
- cgmanifest.json
---
update to v1.30.0 to fix CVE-2024-25629
- update to v1.30.0 to fix CVE-2024-25629
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-25629
> c-ares: update to v1.30.0 to fix CVE-2024-25629

- SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
---
This PR adds libselinux-utils as a requirement in azurelinux-sysinfo package. It's needed for the getenforce command to work. 
- Add requirement libselinux-utils in azurelinux-sysinfo spec.
**NO**
- Tested in local VM with Mariner image
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=592643&view=results
> azurelinux-sysinfo: add libselinux-utils as a requirement

- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/selinux-enforcing-nopackages.yaml
> Image Customizer: Add SELinux tests.

- SPECS/openssh/CVE-2023-28531.patch
- SPECS/openssh/openssh.spec
---
Add a patch for CVE-2023-28531 for openssh package
- Add patch for CVE-2023-28531
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-28531
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593315&view=results
> Patch openssh to fix CVE-2023-28531

- SPECS/ntfs-3g/CVE-2023-52890.patch
- SPECS/ntfs-3g/ntfs-3g.spec
---
Patch CVE-2023-5289 in ntfs-3g
- NA
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-52890
- Unified Buddy Build is [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=587784&view=results)
> Patch CVE-2023-52890 in ntfs-3g

- SPECS/moby-engine/CVE-2022-2879.patch
- SPECS/moby-engine/moby-engine.spec
---
moby-engine - Address CVE-2022-2879
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-2879
> moby-engine - Address CVE-2022-2879

- SPECS/containerd/CVE-2023-44487.patch
- SPECS/containerd/CVE-2023-47108.patch
- SPECS/containerd/containerd.spec
---
containerd - Address CVE-2023-44487 and CVE-2023-47108
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-47108
- Pipeline build id: 594180
> containerd - Address CVE-2023-44487 and CVE-2023-47108

- SPECS/skopeo/CVE-2022-2879.patch
- SPECS/skopeo/skopeo.signatures.json
- SPECS/skopeo/skopeo.spec
- cgmanifest.json
---
Upgrade to v1.14.4, address CVE-2022-2879
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/ CVE-2022-2879
> skopeo - Upgrade to v1.14.4, address CVE-2022-2879

- SPECS/SymCrypt/SymCrypt.signatures.json
- SPECS/SymCrypt/SymCrypt.spec
- cgmanifest.json
---
Updating SymCrypt to the latest version 103.4.2 for FIPS certification
- Update SymCrypt to 103.4.2
NO
- Local build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=594329&view=results
> Update SymCrypt to 103.4.2

- SPECS/vitess/CVE-2017-14623.patch
- SPECS/vitess/vitess.spec
---
vitess address CVE-2017-14623
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2017-14623
> 3.0-dev - vitess address CVE-2017-14623

- toolkit/imageconfigs/baremetal.json
Reverts microsoft/azurelinux#8772
> Revert "Temporarily set selinux to permissive in the baremetal image to unblock tests"

- SPECS/poetry/poetry.signatures.json
- SPECS/poetry/poetry.spec
- cgmanifest.json
---
While working on patching CVE-2022-21699 in `poetry`, I've noticed we're missing the `%check` section, so I enabled it.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2022-21699
- Local build and tests.
- [Buddy build and tests](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=598127&view=results).
> Enabled `poetry` package tests.

- SPECS/systemtap/systemtap.spec
---
- Change systemtap
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/50900808
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=592583&view=results
> systemtap: add stapio

- SPECS/kernel/CVE-2021-3847.nopatch
- SPECS/kernel/CVE-2024-26913.nopatch
- SPECS/kernel/CVE-2024-26933.nopatch
- SPECS/kernel/CVE-2024-26978.nopatch
- SPECS/kernel/CVE-2024-36477.nopatch
- SPECS/kernel/CVE-2024-36481.nopatch
- SPECS/kernel/CVE-2024-38664.nopatch
- SPECS/kernel/CVE-2024-39291.nopatch
---
- Address CVE-2021-3847, CVE-2024-26913, CVE-2024-26933, CVE-2024-26978, CVE-2024-36477, CVE-2024-36481, CVE-2024-38664, CVE-2024-39291
- Address CVE-2021-3847, CVE-2024-26913, CVE-2024-26933, CVE-2024-26978, CVE-2024-36477, CVE-2024-36481, CVE-2024-38664, CVE-2024-39291
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3847
- https://nvd.nist.gov/vuln/detail/CVE-2024-26913
- https://nvd.nist.gov/vuln/detail/CVE-2024-26933
- https://nvd.nist.gov/vuln/detail/CVE-2024-26978
- https://nvd.nist.gov/vuln/detail/CVE-2024-36477
- https://nvd.nist.gov/vuln/detail/CVE-2024-36481
- https://nvd.nist.gov/vuln/detail/CVE-2024-38664
- https://nvd.nist.gov/vuln/detail/CVE-2024-39291
> Address Kernel CVE-2021-3847, CVE-2024-26913, CVE-2024-26933, CVE-2024-26978, CVE-2024-36477, CVE-2024-36481, CVE-2024-38664, CVE-2024-39291

- SPECS/packer/CVE-2022-3064.patch
- SPECS/packer/CVE-2023-45288.patch
- SPECS/packer/CVE-2023-49569.patch
- SPECS/packer/packer.signatures.json
- SPECS/packer/packer.spec
- cgmanifest.json
---
Patching `packer` to fix CVE-2022-3064.
This change also pulls in 2.0's #8758 and #8866 to bring `packer` to the latest version and fixes from 2.0.
No.
- #8758 
- #8866
- https://nvd.nist.gov/vuln/detail/CVE-2022-3064
- Local build and tests.
- [Buddy build and tests](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=597561&view=results).
> Fixed CVE-2022-3064 in `packer`

- SPECS/libtiff/CVE-2023-52356.patch
- SPECS/libtiff/libtiff.spec
Co-authored-by: xiaohongdeng <“worldsky86rough@gmail.com”>
(cherry picked from commit c477bcd9d0c3e4055f35f4552b96434b3b6eacbb)
---
Patch for CVE-2023-52356.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-52356
Buddy build change only
> Patch libtiff for CVE-2023-52356 (#8298)

- SPECS/dcos-cli/CVE-2020-26160.patch
- SPECS/dcos-cli/dcos-cli.spec
---
dcos-cli: patch CVE-2020-26160
- dcos-cli: patch CVE-2020-26160
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-26160
- buddy build successful : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=600135&view=results
> [3.0] dcos-cli: patch CVE-2020-26160

- SPECS/azurelinux-release/azurelinux-release.spec
bump the release version for preview
- bump the release version for preview
**NO**
> Bump release version for preivew

- SPECS/core-packages/core-packages.spec
---
Add missing ms-oss preview repo to bas container. 
- Change: Add missing ms-oss preview repo to bas container. 
NO 
- Pipeline build id: Buddy Build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601475&view=results
> Add ms-oss preview repo to the base container

- SPECS/python-urllib3/CVE-2024-37891.patch
- SPECS/python-urllib3/python-urllib3.signatures.json
- SPECS/python-urllib3/python-urllib3.spec
- cgmanifest.json
---
Bump package version to 2.0.7 to address CVE-2023-43804 & CVE-2023-45803.
Add patch to address CVE-2024-37891.
- Bump package version to 2.0.7.
- Add patch file for CVE-2024-37891.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-43804
- https://nvd.nist.gov/vuln/detail/CVE-2023-45803
- https://nvd.nist.gov/vuln/detail/CVE-2024-37891
- Local Build
- [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602544&view=results)
> python-urllib3 Address CVE-2023-43804, CVE-2023-45803 & CVE-2024-37891.

- SPECS/glusterfs/CVE-2023-26253.patch
- SPECS/glusterfs/glusterfs.spec
---
Patching CVE-2023-26253 in `glusterfs`. Using [unreleased upstream patch](https://github.com/gluster/glusterfs/pull/4023). According to the [resolved upstream issue](https://github.com/gluster/glusterfs/issues/3954) regarding this CVE, this should be sufficient.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-26253
- Local build and test.
- [Buddy build and test](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601473&view=results).
> Patched CVE-2023-26253 in `glusterfs`.

- SPECS/glusterfs/CVE-2023-26253.patch
- SPECS/glusterfs/glusterfs.spec
---
Cherry-pick of #9717.
Patching CVE-2023-26253 in `glusterfs`. Backported an [unreleased upstream patch](https://github.com/gluster/glusterfs/pull/4023). According to the [resolved upstream issue](https://github.com/gluster/glusterfs/issues/3954) regarding this CVE, this should be sufficient.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2023-26253
- [Buddy build and test](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=601497&view=results).
> Patched CVE-2023-26253 in `glusterfs`. (CP: #9717)

- SPECS/ntfs-3g/CVE-2023-52890.patch
- SPECS/ntfs-3g/ntfs-3g.spec
---
Patch ntfs-3g for CVE-2023-52890.
- Patch ntfs-3g for CVE-2023-52890.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-52890.
- Built in containerized-rpmbuild environment
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603363&view=results
> Patch ntfs-3g to fix CVE-2023-52890

- SPECS/ig/ig.signatures.json
- SPECS/ig/ig.spec
- cgmanifest.json
Hi!
---
Bump `ig` to v0.30.0.
- Bump to version 0.30.0
- Update how binary version is set while building
**NO**
> ig: Bump to v0.30.0.

- SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
- SPECS/hvloader/CVE-2023-0464.patch
- SPECS/hvloader/hvloader.spec
---
hvloader: add patch for CVE-2023-0464
- hvloader: add patch for CVE-2023-0464
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0464
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=589441&view=results
- Successful Image build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=602492&view=results
> hvloader: add patch for CVE-2023-0464

- SPECS/cups/cups-failover-backend.patch
- SPECS/cups/cups-lspp.patch
- SPECS/cups/cups-no-export-ssllibs.patch
- SPECS/cups/cups.signatures.json
- SPECS/cups/cups.spec
- cgmanifest.json
---
- cups: upgrade version 2.3.3op2 -> 2.4.10 to address CVE-2023-34241
- cups: add changelog
- cups: cgmanifest: update entry
- cups: upgrade version 2.3.3op2 -> 2.4.10 to address CVE-2023-34241
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-34241
- Pipeline build id: [PR-9815](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603766&view=results)
> cups: upgrade version 2.3.3op2 -> 2.4.10 to address CVE-2023-34241

- SPECS/httpd/httpd.signatures.json
- SPECS/httpd/httpd.spec
- cgmanifest.json
---
Upgrade httpd to 2.4.61 to fix CVE-2024-38473
- Upgrade httpd to 2.4.61 
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-38473
- Build in containerized-rpmbuild environment
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603420&view=results
> Upgrade httpd to 2.4.61 to fix CVE-2024-38473

- SPECS/telegraf/CVE-2024-37298.patch
- SPECS/telegraf/telegraf.spec
---
Patch CVE-2024-37298
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-37298
-[ Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=603112&view=results)
> Patch telegraf for CVE-2024-37298 in vendored sources

- SPECS/telegraf/CVE-2024-37298.patch
- SPECS/telegraf/telegraf.spec
---
Add patch for CVE-2024-37298
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-37298
> telegraf: Add patch for CVE-2024-37298

- SPECS/kata-containers-cc/kata-containers-cc.spec
---
This copes with changes made to the upstream fork where the KVER variable needs to be supplied to build the tarfs module. At the moment, supplying is optional and non-destructive
- Change tarfs make install target
**NO**
- N/A
- N/A
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=604437&view=results
> kata-containers-cc: Adapt tarfs make install trgt

- SPECS/curl/curl.signatures.json
- SPECS/curl/curl.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- curl: upgrade version 8.5.0 -> 8.8.0 to address CVE-2024-2398
- curl: cgmanifest: update entry
- curl: manifests: update entry
- curl: upgrade version 8.5.0 -> 8.8.0 to address CVE-2024-2398
**YES**
- #9832
- https://nvd.nist.gov/vuln/detail/CVE-2024-2398
- Pipeline build id: [PR-9833](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=605374&view=results)
> curl: upgrade version 8.5.0 -> 8.8.0 to address CVE-2024-2398

- SPECS/selinux-policy/modules_targeted.conf
- SPECS/selinux-policy/selinux-policy.signatures.json
- SPECS/selinux-policy/selinux-policy.spec
This will allow disabling/removing unconfined domains.
---
Change unconfined to a separate module so it can be disabled (optionally).
- Change unconfined to a separate module.
**NO**
- Pipeline build id: 607819
> selinux-policy: Change unconfined to a separate module.

- toolkit/tools/imagecustomizer/README.md
> Image Customizer: Add `modprobe` to list of chroot incompatible commands.

- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
Removing an unused `buildState` argument accidentally added in #8777.
No.
- #8777
- Local run of Go tests.
> Removed unused argument in `preparerequest.go`.

- README.md
- toolkit/docs/quick_start/quickstart.md
- toolkit/docs/security/iso-image-verification.md
This change updates documentation for Azure Linux 3.0.
> Update Readme and associated documentation in anticipation of 3.0 GA

- SPECS/rapidjson/CVE-2024-38517.patch
- SPECS/rapidjson/CVE-2024-39684.nopatch
- SPECS/rapidjson/rapidjson.spec
---
Fix for high severity CVE-2024038517 and CVE-2024-39684. This PR applies to 3.0-dev. The same fix for fasttrack/2.0 is https://github.com/microsoft/azurelinux/pull/9865
- patch file for CVE-2024-38517
- nopatch file for CVE-2024-39684 as it is a duplicate of CVE-2024-38517
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-38517
- https://nvd.nist.gov/vuln/detail/CVE-2024-39684
- Pipeline build id: 607339
> [3.0-dev]rapidjson: fix high CVE-2024-38517 and CVE-2024-39684

- SPECS/libguestfs/libguestfs.spec
---
Add back the tests and the log comment that I removed during the package upgrades
- Add back the tests and the log comment that I [removed during the package upgrades](https://github.com/microsoft/azurelinux/pull/8620) 
**NO**
- Pipeline build id: [608045](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=608045&view=results)
> libguestfs: restore removed tests

- SPECS/cri-o/CVE-2021-43565.patch
- SPECS/cri-o/cri-o.spec
---
cri-o: patch CVE-2021-43565
- Patch CVE-2021-43565
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-43565
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=609777&view=results
> cri-o: patch CVE-2021-43565

- .pipelines/containerSourceData/scripts/PublishContainers.sh
---
- This PR adds implementation for publishing the NVIDIA GPU driver container
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=607560&view=results
> Onboard NVIDIA Driver Container to PublishContainer script

- .pipelines/containerSourceData/cuda/nvidia.pkg
---
This PR adds the libnvidia-nscq package into the build process of the NVIDIA GPU driver container. The change is to sync with the upstream [change](https://github.com/NVIDIA/gpu-driver-container/pull/42) that adds libnvidia-nscq into the source code.
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=611374&view=results
> [3.0] Add libnvidia-nscq to NVIDIA GPU driver container image

- SPECS/httpd/httpd.signatures.json
- SPECS/httpd/httpd.spec
- cgmanifest.json
---
Bump package version to 2.4.62 to address CVE-2024-40725
Reference: https://httpd.apache.org/security/vulnerabilities_24.html
- Bump source version
- update cgmanifest entry
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-40725
> Upgrade httpd to 2.4.62 to address CVE-2024-40725

- SPECS/gtk2/CVE-2024-6655.patch
- SPECS/gtk2/gtk2.spec
- SPECS/gtk3/CVE-2024-6655.patch
- SPECS/gtk3/gtk3.spec
---
Patch CVE-2024-6655
Patch CVE-2024-6655
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-6655
- Pipeline build id: 610712
> Add patch for CVE-2024-6655

- SPECS/curl/curl.signatures.json
- SPECS/curl/curl.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- curl: upgrade 8.5.0 -> 8.8.0 to address CVE-2024-2398
- curl: cgmanifest: update entry
- curl: manifests: update entry
- curl: upgrade 8.5.0 -> 8.8.0 to address CVE-2024-2398
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-2398
- Pipeline build id: [PR-9832](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=605376&view=results)
> curl: upgrade 8.5.0 -> 8.8.0 to address CVE-2024-2398

- SPECS/cf-cli/CVE-2023-39325.patch
- SPECS/cf-cli/cf-cli.spec
---
- **cf-cli: address CVE-2023-39325**
- **cf-cli: fix CF_BUILD_SHA to have correct build sha in binary**
- **cf-cli: address CVE-2023-39325**
- **cf-cli: fix CF_BUILD_SHA to have correct build sha in binary**
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-39325
- Pipeline build id: [PR-9949](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=613495&view=results)
> cf-cli: address CVE-2023-39325

- SPECS/terraform/CVE-2024-6104.patch
- SPECS/terraform/terraform.spec
---
Add patch for CVE-2024-6104
- Add patch for CVE-2024-6104
NO
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=613642&view=results)
> terraform: Patch CVE-2024-6104 for bundled hashicorp/go-retryablehttp.

- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/WALinuxAgent/add_firewall_rules.patch
---
Add EnableFirewall flag to waagent.conf to protect access to Azure host node services.
This reverts commit eb626444921c30cdf6810248ee25410f76bcf3c4.
- Patch waagent.conf to add firewall rules to protect access to Azure host node
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/48759369
> Patch waagent.conf to add firewall rules

- toolkit/tools/imagecustomizerapi/disk.go
- toolkit/tools/imagecustomizerapi/disk_test.go
- toolkit/tools/imagecustomizerapi/storage.go
- toolkit/tools/imagecustomizerapi/storage_test.go
If a partition's mount point uses the partition's label as a target, then ensure the partition's label is not empty and ensure that there are not any duplicate partition labels.
---
NO
- Added UTs.
> Image Customizer: Add checks for missing/duplicate partition labels.

- SPECS/coreutils/CVE-2024-0684.patch
- SPECS/coreutils/coreutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- coreutils: introduce patch to address CVE-2024-0684
- coreutils: introduce patch to address CVE-2024-0684
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-0684
- Pipeline build id: [PR-9910](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=610483&view=results)
> coreutils: introduce patch to address CVE-2024-0684

- SPECS/postgresql/postgresql.service
- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
---
- Added systemd service, installation path, %pre %post and %postun required for the service in the postgresql package
**YES/NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/49405931
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=610383&view=results
> Adding systemd service to postgresql

- SPECS/cyrus-sasl-bootstrap/cyrus-sasl-bootstrap.spec
- SPECS/cyrus-sasl/cyrus-sasl.spec
- SPECS/harfbuzz/harfbuzz.spec
- SPECS/rrdtool/rrdtool.spec
---
Fix duplicate file issues in harfbuzz, cyrus-sasl and rrdtool
- Change `harfbuzz` to fix duplicate `libharfbuzz-icu.so` files
- Change `rrdtool` to fix duplicate `librrd.so` and `tclrrd1.8.0.so` files
- Change `cyrus-sasl` to fix duplicate `saslpasswd2` and `sasldblistusers2` files
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=614990&view=results
> Fix duplicate file issues in harfbuzz, cyrus-sasl and rrdtool

- toolkit/scripts/build_tag_imagecustomizer.mk
> Image Customizer: Bump release version to v0.6.

- SPECS/azcopy/azcopy.signatures.json
- SPECS/azcopy/azcopy.spec
- cgmanifest.json
---
Update azcopy
- azcopy: upgrade version to 10.25.1 to fix CVE-2024-35255
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35255
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615174&view=results
> azcopy: upgrade version to 10.25.1 to fix CVE-2024-35255

- SPECS/moby-engine/moby-engine.spec
---
Cherry-pick of CVE-2024-41110 from fast-track branch to main branch was malformed. Correct the inconsistency by keeping "-7" release version as the CVE fix since this is what is published via fast-track, and then update https://github.com/microsoft/azurelinux/pull/9877 to be "-8" release, which will be built and published at next opportunity.
fixes: https://github.com/microsoft/azurelinux/pull/9966 : "[AUTO-CHERRYPICK] fix CVE-2024-41110 in moby-engine - branch main"
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53043429
- Pipeline build id: [617111](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=6171 …
> fix: correct moby-engine cherry-pick to keep consistency

- SPECS/prometheus/CVE-2024-6104.patch
- SPECS/prometheus/prometheus.spec
---
- Change
- Change
- Change
**NO**
- #xxxx
- Pipeline build id: [615641](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615641&view=results)
> Fix CVE-2024-6104 in prometheus by patching vendor gomodule

- SPECS/python-twisted/CVE-2024-41671.patch
- SPECS/python-twisted/CVE-2024-41810.patch
- SPECS/python-twisted/python-twisted.spec
---
Fix CVE-2024-41671 and CVE-2024-41810 in python-twisted
- Fix CVE-2024-41671 and CVE-2024-41810 with patches
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-41671
- https://nvd.nist.gov/vuln/detail/CVE-2024-41810
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615619&view=results
> Fix CVE-2024-41671 and CVE-2024-41810 in 3.0 python-twisted

- SPECS/libcontainers-common/CVE-2024-6104.patch
- SPECS/libcontainers-common/libcontainers-common.spec
---
- Change
- Change
- Change
**NO**
- #xxxx
- 
- Pipeline build id: [615639](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615639&view=results)
> Fix CVE-2024-6104 in libcontainers-common by patching gomodule

- SPECS/packer/CVE-2024-6104.patch
- SPECS/packer/packer.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
- 
- Pipeline build id: [616591](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=616591&view=results)
> Fix CVE-2024-6104 in packer by patching the vendor golang

- toolkit/docs/building/building.md
---
Update toolkit build instructions to reference 3.0 as appropriate.
- Change toolkit build instructions to reference 3.0 as appropriate.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53024411
- N/A, documentation change
> documentation: update toolkit building docs for 3.0

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/pkg/imagecustomizerlib/customizeutils.go
- toolkit/tools/pkg/imagecustomizerlib/customizeutils_test.go
---
renames /etc/mariner-customizer-release to /etc/image-customizer-release
- rename in docs, customizeutils, and test
**NO**
- MIC run locally, run go test locally
> image customizer: rename /etc/mariner-customizer-release to /etc/image-customizer-release

- toolkit/tools/pkg/imagecustomizerlib/customizepartitions_test.go
- toolkit/tools/pkg/imagecustomizerlib/imagecustomizer_test.go
- toolkit/tools/pkg/imagecustomizerlib/main_test.go
Add tests that use a legacy boot image as the base image.
---
NO
- Manually ran new UTs.
> Image Customizer: Expand legacy boot tests.

- toolkit/resources/manifests/package/local.repo
---
Extending the comments in `local.repo` to document the reason behind the repository order, in which we search for dependencies.
No.
- #10025
- N/A.
> Explaining package usage order.

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel-uki.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Bumping kernel release number to rebuild UKI with new initrd, with dracut change from https://github.com/microsoft/azurelinux/pull/10039
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618005&view=results
> kernel-uki: UKI with new initrd

- SPECS/cloud-init/0001-feat-azure-Add-ProvisionGuestProxyAgent-OVF-setting-.patch
- SPECS/cloud-init/0002-feat-azure-parse-ProvisionGuestProxyAgent-as-bool-51.patch
- SPECS/cloud-init/0003-feat-azure-add-support-for-azure-proxy-agent.patch
- SPECS/cloud-init/cloud-init.spec
---
Adds preliminary support for azure-proxy-agent into cloud-init. This is opt-in only with fallbacks if the command isn't available.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/52451730
- Pipeline build id: [618060](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618060&view=results)
> feat(cloud-init): add support for azure-proxy-agent

- toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/iso-files-and-args-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/iso-os-prereqs-config.yaml
---
We need to have curl persent on the image to download the rootfs in the PXE flow. Given that we are aiming to have an iso image whose artifacts can be used to PXE boot a machine, the PXE scenario is not separate from the iso scenario and so is its requirements (i.e. curl).
- [[mic][iso] Add curl to the list of required dependencies for iso creation](https://github.com/microsoft/azurelinux/commit/0c2755ea0f3beb35fafdea4945d4cb2ae3655604)
**NO**
- [7939: [mic iso][PXE] "curl" is required by dracut in 3.0 - however, it's missing in the baremetal image.](https://dev.azure.com/mariner-org/ECF/_workitems/edit/7939)
- n/a
- create an PXE bootable iso and load using PXE.
> [mic][iso] Add curl to the list of required dependencies for iso creation.

- toolkit/tools/imagegen/diskutils/diskutils.go
---
- On older build machines, using `parted`'s [`type` session command](https://www.gnu.org/software/parted/manual/html_node/type.html) may fail, since this command is only supported in version 3.6+. This PR checks for the current version of parted on the build machine and prints out a warning if the command is not supported.
- Local build on Mariner 2 vs Azl3 machines
> toolkit: check for parted version before setting partition type

- toolkit/resources/manifests/package/local.repo
cherry-pick #10025 to 3.0 branch
> [cherry-pick to 3.0] Add priorities to local repos

- SPECS-EXTENDED/js-jquery/CVE-2019-20149.patch
- SPECS-EXTENDED/js-jquery/js-jquery.spec
---
Patches CVE in kind-of package
https://github.com/jonschlinkert/kind-of/pull/31
- Added modified patch file
- Updated spec to apply patch successfully
**NO**
[- https://nvd.nist.gov/vuln/detail/CVE-2019-20149](https://nvd.nist.gov/vuln/detail/CVE-2019-20149)
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=619214&view=results
> js-jquery: Patch CVE-2019-20149 in kind-of 

- SPECS-EXTENDED/js-jquery/CVE-2019-20149.patch
- SPECS-EXTENDED/js-jquery/js-jquery.spec
---
Patches CVE in kind-of package
https://github.com/jonschlinkert/kind-of/pull/31
- Added modified patch file
- Updated spec to apply patch successfully
**NO**
[- https://nvd.nist.gov/vuln/detail/CVE-2019-20149](https://nvd.nist.gov/vuln/detail/CVE-2019-20149)
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=619177&view=results
> js-jquery: Patch CVE-2019-20149 in kind-of

- SPECS/iperf3/iperf3.signatures.json
- SPECS/iperf3/iperf3.spec
- cgmanifest.json
---
- **iperf3: upgrade version 3.16 -> 3.17.1 to address CVE-2024-26306**
- **iperf3: upgrade version 3.16 -> 3.17.1 to address CVE-2024-26306**
**NO**
- #9119
- https://nvd.nist.gov/vuln/detail/CVE-2024-26306
- Pipeline build id: [PR-10084](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=619102&view=results)
> iperf3: upgrade version 3.16 -> 3.17.1 to address CVE-2024-26306

- SPECS/libtiff/CVE-2023-6277.patch
- SPECS/libtiff/libtiff.spec
---
Add patch for CVE-2023-6277
Reference: https://gitlab.com/libtiff/libtiff/-/issues/614
- Add patch for CVE-2023-6277
- 
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-6277
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=617764&view=results)
> libtiff: Add patch to resolve CVE-2023-6277

- SPECS/cert-manager/CVE-2024-6104.patch
- SPECS/cert-manager/cert-manager.spec
---
Fix CVE-2024-6104 by patching vendor directory
- Fix CVE-2024-6104 by patching vendor directory
**NO**
- Pipeline build id: [614698](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=614698)
> Fix CVE-2024-6104 in cert-manager by patching vendor package sources

- SPECS/keda/CVE-2024-6104.patch
- SPECS/keda/keda.spec
---
Fix CVE-2024-6104 in keda by patching vendor gomodule
- Patch vendor gomodule
**NO**
- Pipeline build id: [615284](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=615284&view=results)
> Fix CVE-2024-6104 in keda by patching vendor gomodule

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel-uki-dracut.conf
- SPECS/kernel/kernel-uki.signatures.json
- SPECS/kernel/kernel-uki.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Explicitly include systemd-cryptsetup in the dracut config used to generate initrd for UKI.
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/52965269/
- Local image build - generate a new CVM image with this change -> encrypt root and boot -> will be prompted for a password when root fails to be decrypted.
> kernel-uki: include systemd-cryptsetup in initrd

- SPECS/perl-NetAddr-IP/perl-NetAddr-IP.spec
---
This package didn't show up in the log search used to find https://github.com/microsoft/azurelinux/pull/10020, fix it now.
- Fix invalid case in perl-NetAddr-IP (perl(Autoloader) -> perl(AutoLoader))
**NO**
- Local build
> Fix perl(AutoLoader) capitalization for perl-NetAddr-IP BR

- SPECS/rust/CVE-2024-31852.patch
- SPECS/rust/CVE-2024-32884.patch
- SPECS/rust/rust.spec
---
Patches rust package for CVE-2024-32884 and CVE-2024-31852
- Patch CVE-2024-32884 and CVE-2024-31852 in rust
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-32884
- https://nvd.nist.gov/vuln/detail/CVE-2024-31852
- Pipeline build id: [619147](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=619147)
- Local build, including install and build of sample program.
> Patch CVE-2024-32884 and CVE-2024-31852 in rust

- SPECS/edk2/edk2.spec
---
Add new condition to not apply patch with warning suppress if azl
- Add new condition to not apply patch with warning suppress if azl
**NO**
- Pipeline build id: [620360](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=620360&view=results)
> edk2: not apply patch with warning suppress if azl

- SPECS/busybox/CVE-2021-42380.patch
- SPECS/busybox/CVE-2023-42363.patch
- SPECS/busybox/CVE-2023-42365.patch
- SPECS/busybox/busybox.spec
---
Address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365
- Address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-42380
- https://nvd.nist.gov/vuln/detail/CVE-2023-42363
- https://nvd.nist.gov/vuln/detail/CVE-2023-42364
- https://nvd.nist.gov/vuln/detail/CVE-2023-42365
- Pipeline build id: [PR-10107](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=620085&view=results)
> busybox: address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365

- SPECS/tpm2-tss/tpm2-tss.signatures.json
- SPECS/tpm2-tss/tpm2-tss.spec
- cgmanifest.json
---
Bump version to 4.0.2 to resolve CVE-2024-29040
- Bump package version
- update cgmanifest entry
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-29040
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=620161&view=results)
> tpm2-tss: Bump version to 4.0.2 to resolve CVE-2024-29040

- SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
- SPECS/kernel-mos/config
- SPECS/kernel-mos/kernel-mos.signatures.json
- SPECS/kernel-mos/kernel-mos.spec
- cgmanifest.json
---
Update kernel-mos to 5.15.164.1
- Update kernel-mos to 5.15.164.1
NO
- Pipeline build id: 620375, 620416
> Update kernel-mos to 5.15.164.1

- SPECS/busybox/CVE-2021-42380.patch
- SPECS/busybox/CVE-2023-42363.patch
- SPECS/busybox/CVE-2023-42365.patch
- SPECS/busybox/busybox.spec
---
Address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365
This is actually a cherry-pick from [PR-10107](https://github.com/microsoft/azurelinux/pull/10107)
- CVE-2021-42380
- CVE-2023-42363
- CVE-2023-42364
- CVE-2023-42365
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-42380
- https://nvd.nist.gov/vuln/detail/CVE-2023-42363
- https://nvd.nist.gov/vuln/detail/CVE-2023-42364
- https://nvd.nist.gov/vuln/detail/CVE-2023-42365
> Address CVE-2021-42380, CVE-2023-42363, CVE-2023-42364 & CVE-2023-42365

- SPECS/bind/CVE-2024-1737.patch
- SPECS/bind/CVE-2024-1975.patch
- SPECS/bind/CVE-2024-4076.patch
- SPECS/bind/bind.signatures.json
- SPECS/bind/bind.spec
- cgmanifest.json
---
- **bind: upgrade version 9.16.48 -> 9.16.50**
- **bind: patch CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076**
- **bind: upgrade version 9.16.48 -> 9.16.50**
**NO**
- #9918
- https://nvd.nist.gov/vuln/detail/CVE-2024-1737
- https://nvd.nist.gov/vuln/detail/CVE-2024-1975
- https://nvd.nist.gov/vuln/detail/CVE-2024-4076
- Local Build
- Pipeline build id: [PR-10037](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=617347&view=results)
> bind: upgrade version 9.16.48 -> 9.16.50 & patch CVE-2024-1737, CVE-2024-1975 & CVE-2024-4076

- toolkit/tools/imagecustomizer/container/build-mic-container.sh
- toolkit/tools/imagecustomizer/container/run-mic-container.sh
- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
---
Fixes some typos in MIC
- variables used for tdnf: tnf* renamed correctly to tdnf*
- in run-mic-container script, fix usage 
- other minor stuff like capitalization
**NO**
- Locally ran mic
> image customizer: fix typos

- SPECS/WALinuxAgent/WALinuxAgent.signatures.json
- SPECS/WALinuxAgent/WALinuxAgent.spec
- SPECS/WALinuxAgent/module-setup.sh
---
The initramfs doesn't have some of the utilities required by walinuxagent's udev rules. Properly install them in the initramfs as part of WaLinuxAgent. 
- Package dracut setup script with WaLinuxAgent
NO
- #10021
- Buddy built and tested in AKS custom image. validated by running a CSI container
> WaLinuxAgent: Package dracut setup script with WaLinuxAgent

- toolkit/tools/imagecustomizer/container/test-mic-container.sh
---
Adds a test for the mic container. It runs the run.sh script which is a wrapped for the imagecustomizer binary, both located inside the container. Takes in one parameter for the container tag.
- Add test script.
**NO**
- Ran it locally.
> image customizer: test mic container script

- toolkit/tools/pkg/imagecustomizerlib/customizeverity.go
---
The PR addresses an issue in the MIC tool where unclear error messages were generated during the Verity setup process if the lvm2 package was missing. The fix ensures that the MIC tool checks for the presence of required packages like lvm2 before proceeding, and installs them if necessary.
**NO**
- Internal MS Bug: https://dev.azure.com/mariner-org/ECF/_sprints/taskboard/Mariner%20Operator%20Edge/ECF/2408?workitem=8009
- Local MIC build succeed.
> ImageCustomizer: Bugfix Verity dependency handling in Azl3.

- toolkit/tools/imagecustomizer/container/build-mic-container.sh
- toolkit/tools/imagecustomizer/container/run-mic-container.sh
- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
Cherry pick PR mistakenly made to 3.0 for 3.0-dev
Original PR: https://github.com/microsoft/azurelinux/pull/10135
> image customizer: fix typos (#10135)

- .pipelines/containerSourceData/scripts/BuildContainerCommonSteps.sh
---
Fixing a bug introduced by this PR: https://github.com/microsoft/azurelinux/pull/8946 where some containers were not getting published.
- .pipelines/containerSourceData/scripts/BuildContainerCommonSteps.sh
**NO**
> fix function to publish containers

- toolkit/tools/imagecustomizer/docs/container.md
Updated container docs to include usage of `run.sh` script.
- Updated container docs to include usage of `run.sh` script.
**NO**
> image customizer: docs for run.sh

- SPECS/bash/bash-tty-tests.patch
- SPECS/bash/bash.spec
- toolkit/resources/manifests/package/macros.override
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Fix the check tests for bash
- Remove macros.override change that disabled running bash tests
**YES**
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=623313&view=results
> bash: fix package tests

- SPECS/gdb/gdb.spec
---
- Fix gdb package tests
- Enable unit tests for gdb
**NO**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=623743&view=results
> gdb: fix package tests

- toolkit/tools/pkg/imagecustomizerlib/customizepackages.go
- toolkit/tools/pkg/imagecustomizerlib/customizepackages_test.go
Ensure that when updating/installing packages, the repo metadata is always refreshed to ensure it is up to date. This fixes a bug where running imagecustomizer twice over an image can fail if a local RPM source is updated between the two runs.
In addition, this change ensures that the repo metadata is not refreshed while in the middle of installing/updating the packages.
---
NO
- Added UT.
> Image Customizer: Always refresh RPM repo metadata.

- SPECS/make/make.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix `make` package tests by running as non-root user
- Fix `make` package tests
**YES**
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=624623&view=results
> make: fix package tests

- SPECS/cert-manager/CVE-2024-25620.patch
- SPECS/cert-manager/cert-manager.spec
- [* ] The toolchain has been rebuilt successfully (or no changes were made to it) …
> Fix for CVE-2024-25620 in cert-manager

- SPECS/vim/CVE-2024-43374.patch
- SPECS/vim/vim.spec
---
Fix for CVE-2024-43374
- Create patch to fix CVE-2024-43374
- Update spec version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-43374
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625114&view=results
> vim: CVE-2024-43374 (azl 3)

- SPECS/frr/CVE-2024-44070.patch
- SPECS/frr/frr.spec
---
fix for CVE-2024-44070
- Create patch for CVE-2024-44070
**YES/NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-44070
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625600&view=results
> frr: CVE-2024-44070 (azl 3)

- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
- cgmanifest.json
---
Updates SymCrypt-OpenSSL to 1.5.1 with bugfixes for .NET and golang wrapper libraries.
- Fixes bugs found when using SymCrypt-OpenSSL with .NET and golang-fips wrapper library
- microsoft/SymCrypt-OpenSSL#86
- microsoft/SymCrypt-OpenSSL#87
NO
[dotnet/runtime#106330](https://github.com/dotnet/runtime/pull/106330#issuecomment-2299401967)
- Local build. manual test and SymCrypt-OpenSSL pipeline
> Update SymCrypt-OpenSSL to 1.5.1

- toolkit/scripts/containerized-build/create_container_build.sh
---
Add container image for 3.0 for test mode
- Add container image for AZL 3.0 for test mode
**NO**
- Local test: was able to bring up the tool in test mode using AZL 3.0 container image.
> containerized-rpmbuild: add container image for 3.0

- SPECS/openldap/CVE-2023-2953.patch
- SPECS/openldap/openldap.spec
---
Add patch to resolve CVE-2023-2953
References:
https://bugzilla.redhat.com/show_bug.cgi?id=2210651
https://bugs.openldap.org/show_bug.cgi?id=9904
https://ubuntu.com/security/CVE-2023-2953
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-2953
> openldap: Add patch to resolve CVE-2023-2953

- SPECS/jx/CVE-2023-45288.patch
- SPECS/jx/jx.spec
---
Add patch to resolve CVE-2023-45288
- 
NO
- #xxxx
> jx: Add patch to resolve CVE-2023-45288

- SPECS/rpm-ostree/CVE-2023-26964.patch
- SPECS/rpm-ostree/rpm-ostree.spec
---
Add patch to resolve CVE-2023-26964 in vendored h2 sources.
Reference:
https://github.com/hyperium/h2/commit/5bc8e72e5fcbd8ae2d3d9bc78a1c0ef0040bcc39
https://github.com/hyperium/h2/commit/d3f37e9fbad6608ba74419c355eb1892bd55d977
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-26964
> rpm-ostree: Add patch to resolve CVE-2023-26964 in vendored h2 sources

- SPECS-SIGNED/kernel-mos-signed/kernel-mos-signed.spec
- SPECS/kernel-mos/config
- SPECS/kernel-mos/kernel-mos.signatures.json
- SPECS/kernel-mos/kernel-mos.spec
- cgmanifest.json
---
Update kernel-mos to 5.15.164.1
This is a cherry-pick from the main branch to run critical changes through the fasttrack. The PR for the main is: https://github.com/microsoft/azurelinux/pull/10114
- Change: Update kernel-mos to 5.15.164.1
**YES/NO**
- #xxxx
> [Cherry-pick] Update kernel-mos to 5.15.164.1 (#10114)

- SPECS/sysstat/sysstat.signatures.json
- SPECS/sysstat/sysstat.spec
- cgmanifest.json
---
- **sysstat: upgrade 12.7.4 -> 12.7.6 to address CVE-2018-19416**
- **sysstat: upgrade 12.7.4 -> 12.7.6 to address CVE-2018-19416**
**NO**
- #10244
- https://nvd.nist.gov/vuln/detail/CVE-2018-19416
- Pipeline build id: [PR-10245](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=626836&view=results)
> sysstat: upgrade 12.7.4 -> 12.7.6 to address CVE-2018-19416

- SPECS/cert-manager/CVE-2023-2253.patch
- SPECS/cert-manager/CVE-2023-3978.patch
- SPECS/cert-manager/CVE-2024-24786.patch
- SPECS/cert-manager/CVE-2024-28180.patch
- SPECS/cert-manager/cert-manager.spec
---
- Address CVEs with patches. 
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-2253
- https://nvd.nist.gov/vuln/detail/CVE-2023-3978
- 
- Local build
> cert-manager: Address CVE-2023-3978, CVE-2024-24786, CVE-2024-28180, CVE-2023-2253

- SPECS/unbound/CVE-2024-33655.patch
- SPECS/unbound/unbound.spec
---
Add patch to resolve CVE-2024-33655
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-33655
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=628425&view=results)
> unbound: Add patch to resolve CVE-2024-33655

- SPECS/multus/CVE-2023-3978.patch
- SPECS/multus/multus.spec
---
Add patch to resolve CVE-2023-3978
NO
- https://nvd.nist.gov/vuln/detail/CVE-2023-3978
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625428&view=results)
> multus: Add patch to resolve CVE-2023-3978

- SPECS/tensorflow/CVE-2024-7592.patch
- SPECS/tensorflow/tensorflow.spec
---
Take python CVE-2024-7592 patch and modify to apply it to SOURCE1
- Take python patch and modify to apply it to SOURCE1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-7592
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=629308&view=results
> tensorflow: CVE-2024-7592

- SPECS/extra-cmake-modules/extra-cmake-modules.signatures.json
---
remove unused source signature in extra-cmake-modules package
- remove unused source signature
- source was removed in this(https://github.com/microsoft/azurelinux/pull/8242) PR, but signature was not updated
**NO**
- None
> remove unused source signature

- SPECS/vte291/CVE-2024-37535.patch
- SPECS/vte291/vte291.spec
---
vte291: apply correct patch for cve-2024-37535 fix
- vte291: apply correct patch for cve-2024-37535 fix. The patch applied before didn't carry all the commits needed for the fix
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-37535
- Pipeline build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=630825&view=results
> vte291: apply correct patch for cve-2024-37535 fix

- SPECS/telegraf/CVE-2024-24786.patch
- SPECS/telegraf/CVE-2024-28180.patch
- SPECS/telegraf/telegraf.spec
---
Address CVE-2024-24786
- Address CVE-2024-24786
**NO**
- NA
- Pipeline build id: [PR-10203](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625345&view=results)
- Run V2: [PR-10203](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=626003&view=results)
> telegraf: address CVE-2024-24786 & CVE-2024-28180

- toolkit/Makefile
---
Fix a typo in a Makefile comment. Reference `clean-imagegen` (found in `toolkit/scripts/imggen.mk`) instead of `clean-imggen`
- Change typo in makefile
**NO**
- N/A
> Makefile: fix typo clean-imggen

- SPECS-SIGNED/kernel-signed/kernel-signed.spec
- SPECS-SIGNED/kernel-uki-signed/kernel-uki-signed.spec
- SPECS/kernel-headers/kernel-headers.spec
- SPECS/kernel/kernel-uki-dracut.conf
- SPECS/kernel/kernel-uki.signatures.json
- SPECS/kernel/kernel-uki.spec
- SPECS/kernel/kernel.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
When systemd is included in initrd usrmount is not needed as it is a no-operation. This PR should slightly increase initrd generation and help reasoning about the list of dracut modules.
See https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/98usrmount/module-setup.sh#L16
**YES**
CC @trungams @ddstreetmicrosoft
> kernel-uki: remove usrmount from initrd

- SPECS/rabbitmq-server/rabbitmq-server.signatures.json
---
remove unused source signature in rabbitmq-server
- remove unused source signature
- source was removed in this(https://github.com/microsoft/azurelinux/pull/8670) PR, but signature was not updated
**NO**
- None
> remove unused source signature: rabbitmq-server

- SPECS/plexus-utils/plexus-utils.signatures.json
---
remove unused source signature in plexus-utils
- remove unused source signature
- source was removed in this(https://github.com/microsoft/azurelinux/pull/8249) PR, but signature was not updated
**NO**
- None
> remove unused source signature: plexus-utils

- .pipelines/prchecks/PackageBuildPRCheck.yml
---
Updating raw toolchain source for 3.0 PR checks.
No.
- PR check.
> Updated raw toolchain source for 3.0 PR check ADO builds.

- SPECS/moby-engine/CVE-2024-29018.patch
- SPECS/moby-engine/moby-engine.spec
---
Patch CVE-2024-29018 in moby-engine
- CVE-2024-29018
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-29018
- Uniform Buddy build: [624239](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=624239&view=results)
> Patch CVE-2024-29018 in moby-engine

- SPECS/python-tensorboard/CVE-2024-43788.patch
- SPECS/python-tensorboard/python-tensorboard.spec
---
fix CVE-2024-43788 in python-tensorboard
- CVE-2024-43788
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-43788
- Pipeline build id: [632767](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=632767&view=results) (only x86_64 test passing, because this package is available in x86_64 only)
> Add patch to fix CVE-2024-43788 in python-tensorboard

- SPECS/perl-Sub-Install/perl-Sub-Install.signatures.json
- SPECS/perl-Sub-Install/perl-Sub-Install.spec
- cgmanifest.json
---
upgrade perl-sub-install
- upgrade perl-sub-install
**NO**
- [53283603](https://microsoft.visualstudio.com/OS/_workitems/edit/53283603)
- Pipeline build successful: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=629349&view=results
> upgrade perl-sub-install to v0.929

- SPECS/perl-Match-Simple/perl-Match-Simple.spec
- SPECS/perl-Sub-Infix/perl-Sub-Infix.spec
---
add missing vendor and distribution tags in new specs
- add missing vendor and distribution tags in new specs
**NO**
- N/A
> add missing vendor and distribution tags in new specs

- SPECS/kubevirt/kubevirt.spec
---
This PR corrects the path where the SELinux policy virt_launcher.cil is installed in the virt-handler container. A previous commit had incorrectly changed this location, which has caused virt-handler to be unable to find the policy file, resulting in initialization failure of virt-handler.
- Change the installation path of SELinux policy virt_launcher.cil in the virt-handler container
**NO**
- Buddy Build Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=631495&view=results
- RPM built by buddy-build was downloaded and installed on 3.0 container to check that the virt_launcher.cil file exists at the correct location.
> Update virt_launcher.cil installation path in virt-handler container

- SPECS-EXTENDED/python-extras/python-extras.spec
- SPECS-EXTENDED/python-pymongo/python-pymongo.spec
- SPECS-EXTENDED/python-pyrsistent/python-pyrsistent.spec
- SPECS-EXTENDED/python-pytest-runner/python-pytest-runner.spec
- SPECS-EXTENDED/python-recommonmark/python-recommonmark.spec
- SPECS-EXTENDED/python-testscenarios/python-testscenarios.spec
- SPECS-EXTENDED/python-testtools/python-testtools.spec
- SPECS/bc/bc.spec
- SPECS/ccache/ccache.spec
- SPECS/dejavu-fonts/dejavu-fonts.spec
- SPECS/docbook-style-xsl/docbook-style-xsl.spec
- SPECS/hardening-check/hardening-check.spec
- SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
- SPECS/local-path-provisioner/local-path-provisioner.spec
- SPECS/ncompress/ncompress.spec
- SPECS/uuid/uuid.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
- toolkit/scripts/check_spec_guidelines.py
- toolkit/tools/internal/rpm/testdata/no_default_package_or_check.spec
- toolkit/tools/internal/rpm/testdata/no_exclusive_architecture.spec
- toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec
- toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
- toolkit/tools/internal/rpm/testdata/with_epoch_and_check.spec
---
Adding a check for the existence of the `Distribution` and `Vendor` tags. Also, adding a check if the `Vendor` tag is correct and updating the few spec files, which used "Microsoft" instead of "Microsoft Corporation", which is used across other spec files.
Related to #10327.
No.
- PR checks.
- Local package build for `python-pymongo`.
> Extended spec PR check to validate the `Distribution` and `Vendor` tags.

- SPECS/vim/CVE-2024-43374.patch
- SPECS/vim/vim.spec
---
Fix for CVE-2024-43374
- Create patch to fix CVE-2024-43374
- Update spec version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-43374
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625113&view=results
- fasttrack/2.0: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633992&view=results
> vim: CVE-2024-43374 (mariner 2)

- .github/workflows/go-test-coverage.yml
- .github/workflows/lint-specs.yml
---
Updating the `upload-artifact` GitHub Action as the old version [has gotten deprecated](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).
Related: #10349.
No.
- PR check.
> Updated the `upload-artifact` GitHub Action to version 4.

- .github/workflows/go-test-coverage.yml
- .github/workflows/lint-specs.yml
---
Updating the `upload-artifact` GitHub Action as the old version [has gotten deprecated](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).
Related: #10349.
No.
- PR check.
> Updated the `upload-artifact` GitHub Action to version 4.4.0.

- toolkit/scripts/build_tag_imagecustomizer.mk
> Image Customizer: Bump version to v0.7

- SPECS/build-essential/build-essential.spec
- SPECS/rtctl/rtctl.spec
- SPECS/trace-cmd/trace-cmd.spec
- SPECS/vte291/vte291.spec
---
add missing vendor and distribution tags in core specs
- add missing vendor and distribution tags in core specs
**NO**
- N/A
> add missing tags

- SPECS/libzip/always_generate_regression_tests.patch
- SPECS/libzip/libzip.spec
---
Fix `libzip` package tests
- Fix `libzip` package tests
**NO**
- Pipeline build id: [link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=634189&view=results) [1](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633694&view=results) [2](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=624683&view=results)
> libzip: fix package tests

- toolkit/tools/pkg/imagecustomizerlib/kernelmoduleutils.go
- toolkit/tools/pkg/imagecustomizerlib/kernelmoduleutils_test.go
Add functional tests for the kernel modules API. There are already good test coverage for this feature from unit tests. So, the functional tests don't need to be that extensive.
---
NO
- Ran new test.
> Image Customizer: Functional tests for kernel modules API.

- SPECS/moby-buildx/CVE-2021-41092.patch
- SPECS/moby-buildx/CVE-2022-41717.patch
- SPECS/moby-buildx/CVE-2023-45288.patch
- SPECS/moby-buildx/CVE-2023-48795.patch
- SPECS/moby-buildx/moby-buildx.spec
---
Fix multiple CVEs in moby-buildx by patching vendor go modules
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41092
- https://nvd.nist.gov/vuln/detail/CVE-2022-41717
- Pipeline build id: [634715](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=634715&view=results)
> Fix multiple CVEs in moby-buildx package

- toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json
---
Fix for Azure Linux 3.0 OS installation issue with Arm64 ISO.
This seems to be a regression issue and the 3.0 toolkit is expecting the shadow-utils package to be present in the core image packages list. For Arm64, it was missing and has been added now.
- Change
Fix for Azure Linux 3.0 OS installation issue with Arm64 ISO.
**NO**
- #xxxx
> Fix for Azure Linux 3.0 Arm64 ISO OS installation issue

- toolkit/pkgbld.sh
---
Add ccache toggle switch to `pkgbld.sh` and also switch on QUICK_REBUILD_PACKAGES=y to ensure all packages are precached from upstream
**NO**
- NA
- NA
- Local Build
> toolkit: pkgbld: add ccache option & switch QUICK_REBUILD_PACKAGES=y

- SPECS/ig/ig.signatures.json
- SPECS/ig/ig.spec
- cgmanifest.json
---
Bump `ig` to v0.32.0.
- Bump `ig` to v0.32.0.
- Bump `ig` to v0.31.0.
**NO**
> ig: Bump to v0.32.0.

- SPECS/tpm2-tss/CVE-2024-29040.patch
- SPECS/tpm2-tss/tpm2-tss.spec
---
Patch CVE-2024-29040
Reference: https://github.com/tpm2-software/tpm2-tss/security/advisories/GHSA-837m-jw3m-h9p6
- Add patch for CVE-2024-29040
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-29040
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=618964&view=resultshttps://dev.azure.com/mariner-org/mariner/_build/results?buildId=618964&view=results)
> tpm2-tss: Add patch to resolve CVE-2024-29040

- SPECS/postgresql/postgresql.service
- SPECS/postgresql/postgresql.signatures.json
- SPECS/postgresql/postgresql.spec
---
To add postgresql-service as a sub-package
- Change
- Change
- Change
**YES/NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/53282984
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=632704&view=results
> Add postgresql-service subpackage

- SPECS/azurelinux-sysinfo/azurelinux-sysinfo.spec
---
Adds rpm package as a requirement. The collect-sysinfo script uses it to get the package count.
- Adds rpm as a requirement.
**NO**
- Pipeline build id: [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=636936&view=results)
> azurelinux-sysinfo: add rpm as a requirement 

- SPECS/curl/CVE-2024-6197.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- This PR addresses [CVE-2024-6197](https://nvd.nist.gov/vuln/detail/CVE-2024-6197) in curl by removing a superfluous `free()` call in `x509asn1.c`.
- https://curl.se/docs/CVE-2024-6197.html
- Patch CVE-2024-6197
**YES**
- https://github.com/microsoft/azurelinux/pull/10125
- https://nvd.nist.gov/vuln/detail/CVE-2024-6197
- Buddy build - [passed](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=634106&view=results)
- Started a Stage 0 [dev build ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=634096&view=results) to make sure the toolchain builds
- AMD toolchain pipeline - …
> Patch CVE-2024-6197 in curl

- SPECS/application-gateway-kubernetes-ingress/CVE-2022-32149.patch
- SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
---
The Cherry-pick bot did not create the PR for the main merge. Hence the manual PR. 
Fix CVE-2022-32149 in a golang vendor package
CP for #10274.
- Fix CVE-2022-32149 with a patch
**NO**
- #xxxx
- Buddy build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=629743&view=results
- Buddy build2: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=631227&view=results
> [Cherry-Pick] Fix CVE-2022-32149 in application-gateway-kubernetes-ingress (#10274)

- SPECS/expat/expat.signatures.json
- SPECS/expat/expat.spec
- cgmanifest.json
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade expat to 2.6.3 to fix CVE-2024-45490, CVE-2024-45491, CVE-2024-45492
- Upgrade expat to 2.6.3 to fix CVE-2024-45490, CVE-2024-45491, CVE-2024-45492
YES
- https://nvd.nist.gov/vuln/detail/CVE-2024-45490
- https://nvd.nist.gov/vuln/detail/CVE-2024-45491
- https://nvd.nist.gov/vuln/detail/CVE-2024-45492
- Pipeline build id: 636988 (full), 636996 (buddy)
> Upgrade expat to 2.6.3 to fix CVE-2024-45490, CVE-2024-45491, CVE-2024-45492

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/config_test.go
- toolkit/tools/imagecustomizerapi/storage.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/install-package-disk-space.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/legacyboot-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/mshvkernel-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/overlays-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-config.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/partitions-selinux-enforcing.yaml
- toolkit/tools/pkg/imagecustomizerlib/testdata/verity-config.yaml
> Image Customizer: Rename 'fileSystems' to 'filesystems'.

- toolkit/tools/imagecustomizerapi/storage_test.go
#10404 and #10383 were merged at a similar time but had a hidden merge conflict.
---
NO
- Ran tests.
> Image Customizer: Fix merge conflict.

- SPECS/python-wheel/CVE-2022-40898.patch
- SPECS/python-wheel/python-wheel.spec
---
- Fix CVE-2022-40898
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-40898
- Pipeline build id: [Link](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=635282&view=results)
> Fix CVE-2022-40898 for python-wheel

- SPECS/glibc/glibc.spec
---
The check section for glibc was enabled in this PR: https://github.com/microsoft/azurelinux/pull/10277
However, the check section results on the pipeline appears to have different results than the tests done locally. Therefore, do not fail on a check section test failure.
This package has not yet been released and the source code is unchanged, therefore avoid rebuilding toolchain and dependent packages
Additionally, a bug has been filed to understand why there is a difference for the test results in the pipelines
https://microsoft.visualstudio.com/OS/_workitems/edit/53845722
- Remove exit 1 for glibc check section
**NO**
- …
> Remove exit 1 for glibc check section

- SPECS/mokutil/mokutil.spec
---
Enable building mokutil for aarch64 also for Azure Linux 3.0.
- Change
Enable building mokutil for aarch64 also for Azure Linux 3.0
**NO**
- #xxxx
- Local build.
> Enable building mokutil for aarch64 

- SPECS/nfs-utils/nfs-utils.spec
---
Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service. 
This is actually a cherry-pick from main.
- NA
**NO**
- NA
- NA
> Fix nfs-utils to build rsc.svcgssd and provide the missing rpc-gssd service

- SPECS/selinux-policy/0036-fstools-Add-additional-perms-for-cloud-utils-growpar.patch
- SPECS/selinux-policy/0037-docker-Fix-dockerc-typo-in-container_engine_executab.patch
- SPECS/selinux-policy/selinux-policy.spec
---
- Add additional required permissions for cloud-utils-growpart.
- Add additional required permissions for cloud-utils-growpart.
- Cherry-pick upstream fix for typo in docker module.
**NO**
- Pipeline build id: 639156
> selinux-policy: Add cloud-utils-growpart fix.

- .pipelines/containerSourceData/busybox/Dockerfile-Busybox
---
/var/lib/rpm location contains database with all the package information. Using this db information to create the busybox sbom as present in [this PR](https://dev.azure.com/mariner-org/mariner/_git/CBL-Mariner-Pipelines/pullrequest/20284).
- Change:  Preserve /var/lib/rpm location in the busybox container
**YES/NO**
NO 
- Pipeline build id: [637046](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=637046&view=results)
> Creating Busybox SBOM by not deleting the rpm db

- .pipelines/containerSourceData/busybox/Dockerfile-Busybox
---
/var/lib/rpm location contains database with all the package information. Using this db information to create the busybox sbom as present in [this PR](https://dev.azure.com/mariner-org/mariner/_git/CBL-Mariner-Pipelines/pullrequest/20284).
- Change:  Preserve /var/lib/rpm location in the busybox container
**YES/NO**
NO 
- Pipeline build id: [637046](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=637046&view=results)
> [3.0] Creating Busybox SBOM by not deleting the rpm db

- .github/workflows/check-circular-deps.yml
---
Enabling circular dependency checks for fast-track 3.0 PRs.
No.
- PR check.
> Enabled circular deps PR check for fast-track PRs.

- SPECS/cloud-init/0001-add-PPS-support-for-azure-proxy-agent.patch
- SPECS/cloud-init/cloud-init.spec
---
Azure provisioning team request a change to support azure proxy agent. This PR add cloud -init [upstream patch](https://github.com/canonical/cloud-init/pull/5601) for PPS support of azure proxy agent and improves error logging. This PR completes the change from previous [PR adding azure proxy agent](https://github.com/microsoft/azurelinux/pull/10455)
- add patch for PPS support of azure proxy agent
NO
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=639911&view=results
- Azure VM provisioning test
> cloud-init add patch for PPS support of auzre-proxy-agent

- toolkit/scripts/check_entangled_specs.py
- toolkit/scripts/check_spec_guidelines.py
- toolkit/scripts/check_static_glibc.py
- toolkit/scripts/license_map.py
- toolkit/scripts/spec_source_attributions.py
- toolkit/scripts/update_cgmanifest.py
- toolkit/scripts/update_toolchain_manifest.py
---
Use python interpreter as `#!/bin/env python3` instead of hardcoding.
This helps in levarging virtualenvs for scripts and not disturbing the systemd wide python installation
**NO**
- NA
- NA
- Local Testing of the scripts
> toolkit: scripts: use '#!/usr/bin/env python3' instead of hardcoding interpreter

- .pipelines/containerSourceData/scripts/BuildGoldenContainer.sh
---
Use Toolchain RPMS while building GC containers
- Change: Use Toolchain RPMS while building GC containers
**YES/NO**
NO
- Pipeline build id: [642171](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642171&view=results)
> [2.0] Use Toolchain RPMS when building Golden Container

- SPECS/libxml2/CVE-2024-25062.patch
- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add patch to resolve CVE-2024-25062
Reference: https://gitlab.gnome.org/GNOME/libxml2/-/compare/v2.11.6...v2.11.7?from_project_id=1665&straight=false
- Update toolchain manifest entries
YES
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-25062
- PrepareBuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=641717&view=results
- AMD64 Toolchain: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=641724&view=results
- ARM64 Toolchain: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=641725&view=results
> Patch libxml2 to resolve CVE-2024-25062

- SPECS/ruby/CVE-2024-41946.patch
- SPECS/ruby/ruby.signatures.json
- SPECS/ruby/ruby.spec
- cgmanifest.json
---
Revert ruby back to version 3.3.3 and apply a patch to the bundled gem rexml to resolve the CVE-2024-41946.
- Revert ruby back to 3.3.3 to avoid build failure of rubygems-* packages
- Add patch for CVE-2024-41946 for bundled gem rexml
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-41946
- Buddy build Pipeline build id: [642579](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642579&view=results)
> Revert ruby to 3.3.3 and fix CVE-2024-41946 in bundled gem rexml

- SPECS/influxdb/CVE-2022-32149.patch
- SPECS/influxdb/influxdb.spec
---
Add patch to resolve CVE-2022-32149
NO
- #xxxx
> Patch influxdb to resolve CVE-2022-32149

- SPECS/cni/CVE-2022-32149.patch
- SPECS/cni/cni.spec
---
Address CVE-2022-32149
- Address CVE-2022-32149
**NO**
- NA
- Pipeline build id: [PR-10371](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=635190&view=results)
> cni: address CVE-2022-32149

- SPECS/ruby/CVE-2024-41946.patch
- SPECS/ruby/ruby.spec
- SPECS/rubygem-rexml/CVE-2024-41946.patch
- SPECS/rubygem-rexml/rubygem-rexml.spec
---
Add a patch for CVE-2024-41946 to specs of ruby and rubygem-rexml packages.
- Add a patch for CVE-2024-41946 to ruby
- Add a patch for CVE-2024-41946 to rubygem-rexml
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-41946
- Buddy Build Pipeline build id: [643145](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=643145&view=results)
> Add patch for CVE-2024-41946 to ruby and rubygem-rexml

- SPECS/moby-engine/CVE-2024-29018.patch
- SPECS/moby-engine/moby-engine.spec
---
Patch CVE-2024-29018 in moby-engine to fix
- CVE-2024-29018
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-29018
- Unified Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=625297&view=results
> Patch CVE-2024-29018 in moby-engine to fix

- SPECS/rabbitmq-server/rabbitmq-server.signatures.json
- SPECS/rabbitmq-server/rabbitmq-server.spec
- cgmanifest.json
---
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-50966
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642505&view=results
> rabbitmq-server: upgrade to 3.13.7 to fix CVE-2023-50966

- SPECS/nodejs/CVE-2019-10906.patch
- SPECS/nodejs/nodejs.spec
---
Patch CVE-2019-10906 in nodejs
- CVE-2019-10906
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2019-10906
- Uniform Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=643704&view=results
> Patch CVE-2019-10906 in nodejs

- SPECS/edk2/CVE-2024-6119.patch
- SPECS/edk2/edk2.spec
---
Add patch for edk2 CVE-2024-6119
- Add upstream [patch](https://github.com/openssl/openssl/commit/05f360d9e849a1b277db628f1f13083a7f8dd04f) for edk2 CVE-2024-6119
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-6119
- Pipeline build id: local package build with RUN_CHECK=y
> add patch for edk2 CVE-2024-6119

- toolkit/tools/imagecustomizer/docs/configuration.md
---
Update MIC doc to reference overlay driver and fstab for overlay feature.
**NO**
> Update MIC doc to reference overlay driver and fstab for overlay feature.

- SPECS/haproxy/haproxy.signatures.json
- SPECS/haproxy/haproxy.spec
- cgmanifest.json
---
haproxy: upgrade to 2.9.11 to fix CVE-2024-45506
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45506
- Pipeline build id: [646375](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=646375&view=logs&j=8fc237db-d9de-5497-d5bc-7b55eebfb9b4&t=8fc237db-d9de-5497-d5bc-7b55eebfb9b4)
> haproxy: upgrade to 2.9.11 to fix CVE-2024-45506

- SPECS/python-tensorboard/CVE-2024-43796.patch
- SPECS/python-tensorboard/python-tensorboard.spec
---
Patch CVE-2024-43796 in python-tensorboard
- CVE-2024-43796
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-43796
- Pipeline build id: [646773](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=646773&view=results)
> Patch CVE-2024-43796 in python-tensorboard

- SPECS/openldap/openldap.spec
---
Enable build with `slapd`
For WorkItem: [389-ds-base](https://microsoft.visualstudio.com/OS/_workitems/edit/51717004)
- Configure with `--enable-slapd`
**NO**
- [389-ds-base](https://microsoft.visualstudio.com/OS/_workitems/edit/51717004)
- NA
- Pipeline build id: [PR-10545](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=646910&view=results)
> openldap: enable slapd

- SPECS/cmake/cmake.signatures.json
- SPECS/cmake/cmake.spec
- cgmanifest.json
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Fix CVE-2024-24806
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-24806
- Pipeline build id: 646540
> cmake: Update to 3.30.3 to fix CVE-2024-24806

- SPECS/python-tensorboard/CVE-2024-45590.patch
- SPECS/python-tensorboard/python-tensorboard.spec
---
Fix CVE-2024-45590 in python-tensorboard
- CVE-2024-45590
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45590
- Pipeline build id: [647577](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=647577&view=results)
> Patch CVE-2024-45590 in python-tensorboard

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/overlay.go
- toolkit/tools/imagecustomizerapi/overlay_test.go
- toolkit/tools/pkg/imagecustomizerlib/customizeoverlays.go
- toolkit/tools/pkg/imagecustomizerlib/testdata/overlays-config.yaml
---
NO
- Updated and ran tests.
> Image Customizer: Rename 'isRootfsOverlay' to 'isInitrdOverlay'.

- SPECS-EXTENDED/python-ldap/python-ldap.signatures.json
- SPECS-EXTENDED/python-ldap/python-ldap.spec
- cgmanifest.json
---
Upgrade version to 3.4.4
Enable ptests (All tests Pass)
For WorkItem: [389-ds-base](https://microsoft.visualstudio.com/OS/_workitems/edit/51717004)
- Upgrade version to 3.4.4
- Enable ptests (All tests Pass)
**NO**
- #10546
- #10545
- NA
- [PR-10570](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=648044&view=results)
- [PR-10570](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=648048&view=results)
> python-ldap: upgrade 3.4.0 -> 3.4.4

- SPECS/blobfuse2/blobfuse2.signatures.json
- SPECS/blobfuse2/blobfuse2.spec
- cgmanifest.json
---
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35255
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=648226&view=logs&j=bac295d9-f2e0-5165-e63e-e76f383e1a27&t=fc61cdd1-f1d9-5cb2-a40a-f38df7d5de65
> blobfuse2: upgrade to 2.3.2 to fix CVE-2024-35255

- SPECS/keda/keda.signatures.json
- SPECS/keda/keda.spec
- cgmanifest.json
---
- Change
- Change
- Change
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=648311&view=results
> keda: upgrade to 2.14.1 to fix CVE-2024-35255

- SPECS/python-platformdirs/python-platformdirs.spec
---
Enable check section in python-platformdirs as dependencies are available in AzLinux now
- Enable check section in python-platformdirs
- Add dependencies for ptest
**NO**
- Pipeline build id: [651002](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=651002&view=results)
> Enable check section in python-platformdirs

- SPECS/mariner-release/mariner-release.spec
Bump release number for AZL2.0 2024 October Update
> Prepare October 2024 Update

- SPECS/kubevirt/CVE-2023-48795.patch
- SPECS/kubevirt/kubevirt.spec
---
This PR fixes CVE-2023-48795 in kubevirt in Azure Linux 3.0.
- CVE-2023-48795
**NO**
- Pipeline build id: [652910](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=652910&view=results)
> add fix for CVE-2023-48795 in kubevirt

- SPECS/oath-toolkit/CVE-2024-47191.patch
- SPECS/oath-toolkit/oath-toolkit-2.6.9-lockfile.patch
- SPECS/oath-toolkit/oath-toolkit.spec
---
This PR fixes CVE-2024-47191 in oath-toolkit.
- CVE-2024-47191
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-47191
- Pipeline build id: FastTrack build - [652433](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=652433&view=results)
> Fix CVE-2024-47191 against oath-toolkit

- SPECS/oath-toolkit/CVE-2024-47191.patch
- SPECS/oath-toolkit/oath-toolkit.spec
---
This PR fixes CVE-2024-47191 in oath-toolkit.
- CVE-2024-47191
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-47191
- Pipeline build id: FastTrack Build - [652431](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=652431&view=results)
> Fix CVE-2024-47191 in oath-toolkit

- SPECS/dcos-cli/CVE-2024-28180.patch
- SPECS/dcos-cli/dcos-cli.spec
- SPECS/kubernetes/CVE-2024-28180.patch
- SPECS/kubernetes/kubernetes.spec
---
- Resolve CVE-2024-28180 for dcos-cli and kubernetes
- Add patch to resolve CVE-2024-28180
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=650210&view=results
> Resolve CVE-2024-28180 for dcos-cli and kubernetes

- toolkit/docs/nvidia/nvidia.md
---
The instructions in the nvidia repo pointed to an invalid URL for the 3.0 nvidia repofile. Fixed the URL path in markdown (repofile itself is correct).
- Updated markdown instructions to reference the right repo url.
- Change
- Change
**NO**
- #xxxx
> Update nvidia repo instructions with the appropriate 3.0 repofile

- SPECS/reaper/CVE-2024-45590.patch
- SPECS/reaper/reaper.spec
---
Fix CVE-2024-45590 in reaper
- CVE-2024-45590
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45590
- Pipeline build id: [647539](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=647539&view=results)
> Patch CVE-2024-45590 in reaper

- SPECS/unbound/CVE-2024-33655.patch
- SPECS/unbound/CVE-2024-43167.patch
- SPECS/unbound/CVE-2024-8508.patch
- SPECS/unbound/unbound.spec
add modifications for patch to apply to current version
---
Patch 3 CVEs in unbound package for mariner 2.0
- Add patch for CVE-2024-33655 (HIGH)
- Add patch for CVE-2024-43167 (LOW)
- Add patch for CVE-2024-8508 (MEDIUM)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-33655
- https://nvd.nist.gov/vuln/detail/CVE-2024-43167
- https://nvd.nist.gov/vuln/detail/CVE-2024-8508
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654202&view=results
> Patch unbound to fix CVE-2024-33655, CVE-2024-8508, and CVE-2024-43167

- SPECS/unbound/CVE-2024-43167.patch
- SPECS/unbound/CVE-2024-8508.patch
- SPECS/unbound/unbound.spec
---
Patch 2 CVEs in unbound package for azure linux 3.0
- Add patch for CVE-2024-43167
- Add patch for CVE-2024-8508
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-43167
- https://nvd.nist.gov/vuln/detail/CVE-2024-8508
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654173&view=results
> Patch unbound to fix CVE-2024-43167 and CVE-2024-8508

- SPECS/OpenIPMI/OpenIPMI.signatures.json
- SPECS/OpenIPMI/OpenIPMI.spec
- cgmanifest.json
---
Upgrade OpenIPMI to 2.0.36 which will also fix the CVE-2024-42934
- CVE-2024-42934
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-42934
- Unified buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657063&view=results)
> Upgrade OpenIPMI to 2.0.36 to fix CVE-2024-42934

- SPECS/giflib/CVE-2022-28506.patch
- SPECS/giflib/CVE-2023-48161.patch
- SPECS/giflib/giflib.spec
---
Patch CVE-2022-28506 and CVE-2023-48161 in giflib
- CVE-2022-28506
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2022-28506
- Unified Buddy Build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=655604&view=results)
> Patch CVE-2022-28506 and CVE-2023-48161 in giflib

- SPECS/dcos-cli/CVE-2024-28180.patch
- SPECS/dcos-cli/dcos-cli.spec
---
- Resolve CVE-2024-28180 for dcos-cli
- Add patch to resolve CVE-2024-28180
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654205&view=results
> [2.0] Resolve dcos-cli CVE-2024-28180

- SPECS/kubernetes/CVE-2024-28180.patch
- SPECS/kubernetes/kubernetes.spec
---
- Resolve CVE-2024-28180 for kubernetes
- Add patch to resolve CVE-2024-28180
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654250&view=results
> [2.0] Resolve kubernetes CVE-2024-28180

- SPECS/python-gevent/CVE-2024-25629.patch
- SPECS/python-gevent/python-gevent.spec
---
Add patch to resolve CVE-2024-25629
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-25629
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657080&view=results)
> Patch python-gevent to resolve CVE-2024-25629

- SPECS/prometheus/CVE-2024-24786.patch
- SPECS/prometheus/prometheus.signatures.json
- SPECS/prometheus/prometheus.spec
- cgmanifest.json
---
Fix CVE 2024 24786 for prometheus
Bump to version 2.37.9 to fix https://github.com/advisories/GHSA-xrjj-mj9h-534m
- Add a protojson patch for prometheus
https://go-review.googlesource.com/c/protobuf/+/569356
- Bump package version
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-41717
- Local successful build
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657775&view=results
> Fix CVE 2024 24786 and CVE 2022 41717 for prometheus

- SPECS/vim/CVE-2024-43802.patch
- SPECS/vim/vim.spec
fix patch to apply without test files
---
Patch CVE-2024-43802 within vim on Mariner 2.0
bring forward 2 other CVE fixes from main for vim as well.
- Add patch for CVE-2024-43802
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-43802
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=655960&view=results
> Patch vim to resolve CVE-2024-43802

- SPECS/kubernetes/CVE-2024-24786.patch
- SPECS/kubernetes/kubernetes.spec
---
- Resolve CVE-2024-24786 for kubernetes
- Add patch to resolve CVE-2024-24786
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=657619&view=results
> [2.0] Resolve kubernetes CVE-2024-24786

- SPECS/libpcap/CVE-2024-8006.patch
- SPECS/libpcap/libpcap.spec
---
- Backport fixes for CVE-2024-8006
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-8006
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=660887&view=results
> libpcap: Backport fixes for CVE-2024-8006

- SPECS/apr/apr.signatures.json
- SPECS/apr/apr.spec
- SPECS/apr/skip-known-test-failure.patch
- cgmanifest.json
---
- **apr: upgrade version 1.7.2 -> 1.7.5 to address CVE-2023-49582**
- **apr: upgrade version 1.7.2 -> 1.7.5 to address CVE-2023-49582**
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2023-49582
- Pipeline build id: [PR-10749](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=658518&view=results)
> apr: upgrade version 1.7.2 -> 1.7.5 to address CVE-2023-49582

- SPECS/nghttp2/CVE-2024-28182.patch
- SPECS/nghttp2/nghttp2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2024-28182
- Address CVE-2024-28182
**NO**
- #10076
- #10064
- https://nvd.nist.gov/vuln/detail/CVE-2024-28182
- Pipeline build id: [PR-10656](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=653776&view=results)
> nghttp2: address CVE-2024-28182

- SPECS/curl/CVE-2024-8096.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2024-8096
**YES**
- #10729
- https://nvd.nist.gov/vuln/detail/CVE-2024-8096
- Pipeline build id: [validating]
> curl: address CVE-2024-8096

- SPECS/libpcap/libpcap.signatures.json
- SPECS/libpcap/libpcap.spec
- cgmanifest.json
---
- Upgrade to version 1.10.5 (fixes CVE-2024-8006)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-8006
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=660944&view=results
> Upgrade libpcap version to 1.10.5 to fix CVE-2024-8006

- SPECS/reaper/CVE-2024-45590.patch
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Add missing patch to fasttrack/2.0 from main

- SPECS/kernel-mshv/kernel-mshv.spec
---
This PR tries to increase verbosity to try to better tackle a sporadic build issue we are currently experiencing. More context in https://microsoft.visualstudio.com/OS/_workitems/edit/54699970
- V=1 : Based on https://thelinuxcode.com/linux-kernel-makefile-explained/ and https://stackoverflow.com/questions/5820303/how-do-i-force-make-gcc-to-show-me-the-commands
- KBUILD_VERBOSE=1 : Based on https://www.kernel.org/doc/html/v5.15/kbuild/kbuild.html#kbuild-verbose
- kernel-mshv
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=663969&view=results
> kernel-mshv: Increase build verbosity

- SPECS/kata-containers/kata-containers.spec
cherry pick #10849  into 3.0 to fix build break on arm64:
```
INFO[0005][srpmpacker] Skipping (/specs/kernel-uvm/kernel-uvm.spec) since it cannot be built on current architecture. 
...
INFO[7773][scheduler] Unresolved dependencies: 
INFO[7773][scheduler] --> kernel-uvm:C:''V:'',C2:''V2:''
```
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> 3.0: kata-containers: only build for x86_64 (#10849)

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizerapi/mountpoint.go
---
Currently the API looks like:
```
storage:
filesystems:
- deviceId: boot
type: ext4
mountPoint:
path: /boot
```
This PR adds support for:
```
storage:
filesystems:
mountPoint: /boot
```
for when the user doesn't want to add mount options.
**NO**
- Validated with local testing
> Image Customizer: Support string mountPoint

- toolkit/tools/imagecustomizer/docs/configuration.md
- toolkit/tools/imagecustomizer/docs/verity.md
Missing docs fixes associated with #10789.
---
NO
n/a
> Image Customizer: Fix verity docs.

- SPECS/ebtables/ebtables.spec
- SPECS/iptables/iptables.spec
---
This reverts commit 301637a05a0a70254a8cd6e9335d8d12efce3bc0.
Issue discovered with iptables service after this change - https://microsoft.visualstudio.com/OS/_workitems/edit/54604746
https://microsoft.visualstudio.com/OS/_workitems/edit/54730738
**NO**
- Pipeline build id: [661796](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=661796&view=results)
> Revert "iptables: Enable nftables (#10786)"

- SPECS/expat/CVE-2024-50602.patch
- SPECS/expat/expat.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2024-50602 in fasttrack/3.0
- Fix CVE-2024-50602 with a patch
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-50602
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=666116&view=results
> Fix expat CVE-2024-50602 fasttrack 3.0

- SPECS/pam/CVE-2024-22365.patch
- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Porting #8320 from 2.0, which patched CVE-2024-22365 in `pam`.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2024-22365.
- PR check.
> Patched CVE-2024-22365 in `pam`. (CP: #8320)

- SPECS/avahi/CVE-2023-1981.patch
- SPECS/avahi/avahi.spec
---
Avahi has an [issue here](https://github.com/avahi/avahi/issues/375) with a fix in [this PR](https://github.com/avahi/avahi/pull/407).
~I have also enabled the basic built-in tests for the package. If we get a new version of Avahi (>=9.0) we will get even more tests ([for example](https://github.com/avahi/avahi/pull/420/files))~ Tests don't work on 2.0.
**NOTE: 3.0 PR is here: https://github.com/microsoft/azurelinux/pull/10882**
- Patch CVE-2023-1981
- ~Enable %check section for Avahi~
**NO**
- https://brave-ocean-0baeae310.5.azurestaticapps.net/#/cve/CVE-2023-1981
- Local build
- Buddy build: ~https://dev.azure.com/mariner-org/mariner/_build/results?buildId=666003&view=results~ …
> Avahi: Fix CVE-2023-1981, add %check section

- toolkit/tools/pkg/imagecustomizerlib/imageutils.go
- toolkit/tools/pkg/imagecustomizerlib/partitionutils.go
- toolkit/tools/pkg/imagecustomizerlib/shrinkfilesystems.go
Reverts microsoft/azurelinux#10897. Wrong branch. :-(
> Revert "Image Customizer: Fix partition creation on Ubuntu build hosts."

- SPECS/gnutls/CVE-2024-28834.patch
- SPECS/gnutls/CVE-2024-28835.patch
- SPECS/gnutls/gnutls.spec
---
Grab patches from 3.8.4 for both CVE-2024-28834 and CVE-2024-28835: https://gitlab.com/gnutls/gnutls/-/merge_requests/1823/commits?commit_id=e369e67a62f44561d417cb233acc566cc696d82d
- Patch gnutls CVE-2024-28834
- Patch gnutls CVE-2024-28835
- 
**NO**
- https://brave-ocean-0baeae310.5.azurestaticapps.net/#/cve/CVE-2024-28834
- https://brave-ocean-0baeae310.5.azurestaticapps.net/#/cve/CVE-2024-28835
- Local
- ~https://dev.azure.com/mariner-org/mariner/_build/results?buildId=666619&view=results~
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=667229&view=results
> gnutls: Fix CVE-2024-28834, CVE-2024-28835

- toolkit/tools/imagegen/diskutils/diskutils.go
Reverting toolkit/imager changes in #10804. Leaving off the changes to image customizer to avoid conflicts with #10902,
> Partial revert of "Toolkit: Add missing `flock` calls. (#10804)".

- SPECS/binutils/CVE-2022-47007.patch
- SPECS/binutils/CVE-2022-47008.patch
- SPECS/binutils/CVE-2022-47010.patch
- SPECS/binutils/CVE-2022-47011.patch
- SPECS/binutils/binutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2022-47007, CVE-2022-47008, CVE-2022-47010, CVE-2022-47011
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-47007
- https://nvd.nist.gov/vuln/detail/CVE-2022-47008 
- https://nvd.nist.gov/vuln/detail/CVE-2022-47010 
- https://nvd.nist.gov/vuln/detail/CVE-2022-47011
- Pipeline build id: 669273
> Address CVE-2022-47007, CVE-2022-47008, CVE-2022-47010, CVE-2022-47011

- toolkit/scripts/build_tag_imagecustomizer.mk
> Image Customizer: Bump to v0.8

- SPECS/mysql/mysql.spec
---
Switching `mysql` to explicitly not build with `curl` instead of the defaults. At the moment defaults are set to `none` anyway but this change makes sure that independent updates to `mysql` don't trigger building with the bundled version without us knowing it.
No.
- [Fast-track package build check](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=669949&view=results).
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=670395&view=results).
> Modified `mysql` to explicitly not use `curl`.

- toolkit/imageconfigs/packagelists/read-only-root-packages.json
- toolkit/resources/imageconfigs/packagelists/iso-initrd-packages-arm64.json
- toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
---
Part 2/3 of https://github.com/microsoft/azurelinux/pull/9567. See that PR for details.
We no longer need to have the image configs which reference dm-verity.
- Remove `veritysetup` from ISO
- Remove `readonly-root`
**NO**
- Cumulative build with 1,2: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=671241&view=results
> Remove all references to old dm-verity boot tooling [2/3]

- SPECS/cloud-hypervisor-cvm/cloud-hypervisor-cvm.spec
- SPECS/cloud-hypervisor-cvm/microsoft-cloud-hypervisor-6695.patch
---
Follow-up to #10247: add patches from cloud-hypervisor/cloud-hypervisor#6695 to work around the lack of support for extended guest requests by writing zeros to the extended area.
Bug: https://microsoft.visualstudio.com/OS/_queries/edit/53409400/
**NO**
* Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=633500&view=results
* Image build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=638946&view=results
* Conformance: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=639056&view=results
> cloud-hypervisor-cvm: add upstream patch to work around lack of support for extended guest requests

- SPECS/python-werkzeug/CVE-2024-49767.patch
- SPECS/python-werkzeug/python-werkzeug.spec
---
Patch CVE-2024-49767 in python-werkzeug
- CVE-2024-49767
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-49767
- Unified buddy build results are [here](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=669485&view=results)
> Patch CVE-2024-49767 in python-werkzeug

- .pipelines/fasttrack/FasttrackMergeNotifier.yml
---
This is a YAML definition for a pipeline set-up in our ADO project. The intent is for it to serve as a notification for other pipelines, which cannot be have their definitions kept in the GitHub repo but need to know, when a merge happens to any of the fast-track branches.
No.
- #11034
- [CI test runs against this branch](https://dev.azure.com/mariner-org/mariner/_build?definitionId=4032&_a=summary).
> Added the 3.0 fast-track merge notifier pipeline.

- .github/workflows/merge-conflict-check.yml
---
Just like PR #10812 this add PR merge conflict check to 2.0
- Add merge conflict github PR check
**NO**
- Same as the other PR
> Add merge conflict github PR check

- SPECS/xorg-x11-server/CVE-2024-9632.patch
- SPECS/xorg-x11-server/xorg-x11-server.spec
---
Fix CVE-2024-9632 for xorg-x11-server
- Change
Fix CVE-2024-9632 for xorg-x11-server
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-9632
- Local build
> Fix CVE-2024-9632 for xorg-x11-server

- SPECS/libnvidia-container/libnvidia-container.signatures.json
- SPECS/libnvidia-container/libnvidia-container.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- cgmanifest.json
---
- Upgrade nvidia container tookit to v1.17.1 to resolve CVE-2024-0134
- Upgrade libnvidia-containers to v1.17.1 to keep in sync with nvidia container toolkit
- Upgrade to v1.17.1 to resolve CVE-2024-0134
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-0134
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=673590&view=results
> [2.0] Upgrade nvidia container toolkit and libnvidia-containers to v1.17.1

- SPECS/sriov-network-device-plugin/CVE-2024-24786.patch
- SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
---
CVE fix for sriov's vendored google.golang.org/protobuf
- Add patch to fix CVE-2024-24786 in sriov's vendored google.golang.org/protobuf
**NO**
- Pipeline build id: 680227
> sriov: Patch CVE-2024-24786 in vendored google.golang.org/protobuf

- SPECS/wget/CVE-2024-10524.patch
- SPECS/wget/wget.spec
---
- Fix CVE-2024-10524
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-10524
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=679866&view=results
> Fix CVE-2024-10524 for wget :2.0

- SPECS/nmap/CVE-2023-7256.patch
- SPECS/nmap/CVE-2024-8006.patch
- SPECS/nmap/nmap.spec
---
- Fix CVE-2023-7256 and CVE-2024-8006
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-8006
- https://nvd.nist.gov/vuln/detail/CVE-2023-7256
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=677670&view=results
> Fix CVE-2023-7256 and CVE-2024-8006 for nmap : 3.0

- SPECS/unzip/CVE-2022-0529.patch
- SPECS/unzip/unzip.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Fix CVE-2022-0529 and CVE-2022-0530
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-0529
- https://nvd.nist.gov/vuln/detail/CVE-2022-0530
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=682493&view=results
> Fix CVE-2022-0529 and CVE-2022-0530 for unzip: 2.0

- SPECS/rabbitmq-server/generate-rabbitmq-server-tarball.sh
- SPECS/rabbitmq-server/rabbitmq-server.signatures.json
- SPECS/rabbitmq-server/rabbitmq-server.spec
- cgmanifest.json
- [ *] The toolchain has been rebuilt successfully (or no changes were made to it) …
> Fix CVE-2023-46118 for rabbitmq-server

- SPECS/perl-Module-ScanDeps/CVE-2024-10224.patch
- SPECS/perl-Module-ScanDeps/perl-Module-ScanDeps.spec
---
Adding one more CVE fix to the ones added in #11147. See: "[functional followup fix](https://github.com/rschupp/Module-ScanDeps/commit/49468814a24221affe113664899be21aef60e846)" in [Debian's security tracker](https://security-tracker.debian.org/tracker/[CVE-2024-10224](https://security-tracker.debian.org/tracker/CVE-2024-10224)).
Also adding test-only dependencies to fix the ptests, which started failing after the version bump.
No.
- #11147
- https://nvd.nist.gov/vuln/detail/CVE-2024-10224
- [Pipeline build + test](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=682977&view=results).
- Local build + test.
> Extended CVE-2024-10224 patch and fixed ptests in `perl-Module-ScanDeps`.

- toolkit/tools/scheduler/scheduler.go
- toolkit/tools/scheduler/schedulerutils/graphbuildstate.go
- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
Backport of https://github.com/microsoft/CBL-Mariner/pull/7928, the 2.0 builds are occasionally showing the same symptoms.
- Backport #7928: Print error on unexpected package rebuild, but continue
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/49027231/?triage=true
- https://microsoft.visualstudio.com/DefaultCollection/OS/_queries/edit/55231652/?triage=true
- Failed before backport: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=683139&view=results
- Worked after: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=683207&view=logs&j=75cba72d-09cb-503a-3927-4ab61ac4a179&t=96d12790-e2a0-56cb-1f4c-4eb56738aded&l=3791 (Note warning …
> Don't allow multiple build queues (#7928)

- SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
- SPECS/hvloader/CVE-2024-5535.patch
- SPECS/hvloader/hvloader.spec
---
Fix CVE-2024-5535 in hvloader
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-5535
- local build
> Fix CVE-2024-5535 in hvloader

- SPECS/cf-cli/CVE-2024-24786.patch
- SPECS/cf-cli/cf-cli.spec
- SPECS/containerd/CVE-2024-24786.patch
- SPECS/containerd/containerd.spec
- SPECS/containerized-data-importer/CVE-2024-24786.patch
- SPECS/containerized-data-importer/containerized-data-importer.spec
- SPECS/coredns/CVE-2024-24786.patch
- SPECS/coredns/coredns.spec
- SPECS/docker-cli/CVE-2024-24786.patch
- SPECS/docker-cli/docker-cli.spec
- SPECS/influxdb/CVE-2024-24786.patch
- SPECS/influxdb/influxdb.spec
- SPECS/kubevirt/CVE-2024-24786.patch
- SPECS/kubevirt/kubevirt.spec
- SPECS/libcontainers-common/CVE-2024-24786.patch
- SPECS/libcontainers-common/libcontainers-common.spec
- SPECS/moby-containerd-cc/CVE-2024-24786.patch
- SPECS/moby-containerd-cc/moby-containerd-cc.spec
- SPECS/moby-engine/CVE-2024-24786.patch
- SPECS/moby-engine/moby-engine.spec
- SPECS/node-problem-detector/CVE-2024-24786.patch
- SPECS/node-problem-detector/node-problem-detector.spec
- SPECS/packer/CVE-2024-24786.patch
- SPECS/packer/packer.spec
- SPECS/prometheus/CVE-2024-24786.patch
- SPECS/prometheus/prometheus.spec
---
Fix CVE-2024-24786 in multiple packages by patching
- Fix CVE-2024-24786
**NO**
- Pipeline build id: [682739](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=682739&view=results)
- Pipeline build id (containerd and moby-containerd-cc are passing) - [683410](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=683410&view=results)
- Pipeline build id (libcontainers-common) - [686504](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=686504&view=results)
- Pipeline build id (node-problem-detector) - [686533](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=686533&view=result …
> Fix CVE-2024-24786 in multiple packages by patching

- README.md
- toolkit/docs/security/iso-image-verification.md
---
Update docs to reference ARM64 3.0 ISO
- Change README.md
- Change iso-image-verification.md
**NO**
- Manually ran the iso-image-verification instructions for ARM64
> Documentation: Add references to ARM64 3.0 ISO

- toolkit/tools/scheduler/schedulerutils/preparerequest.go
---
The cherrypick https://github.com/microsoft/azurelinux/pull/11222 also needs the associated fix https://github.com/microsoft/azurelinux/pull/7992.
See https://dev.azure.com/mariner-org/mariner/_build/results?buildId=685241&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=b85ceaf1-cf43-56e0-c161-c7d217bb7eb3&l=5845
- Backport #7992 
**NO**
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=689328&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=689331&view=results
> Fix call to IsSRPMTestActive in new multi build fix (#7992)

- README.md
- toolkit/docs/security/iso-image-verification.md
Cherry-pick #11327 into 3.0 branch.
> [3.0] Documentation: Add references to ARM64 3.0 ISO

- SPECS/fluent-bit/CVE-2024-27532.patch
- SPECS/fluent-bit/fluent-bit.spec
---
- Fix CVE-2024-27532
- Rebased with latest changes & retargeted to fasttrack/3.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-27532
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=675468
- New Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=691857&view=results
- After Rebase: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=693533&view=results
> Fix CVE-2024-27532 for fluent-bit

- SPECS-SIGNED/systemd-boot-signed/systemd-boot-signed.spec
- SPECS/systemd/systemd.spec
---
`systemd-boot` also requires the new secureboot keys, version bump so we re-sign them.
Add space recommends/conflicts as https://github.com/microsoft/azurelinux/pull/10995/files#diff-9dd7fef1e850ad265fea94cbe5a86e163172ee833f8ec954d946d57b0ca44ce4
- Version bump `systemd-boot-signed` and `systemd` to force a resign with the new keys
**NO**
- 575013955
- tbd, will need testing before final publish
> Release bump systemd-boot to use new keys

- SPECS/libnvidia-container/libnvidia-container.signatures.json
- SPECS/libnvidia-container/libnvidia-container.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- cgmanifest.json
---
- Upgrade NVIDIA container toolkit and libnvidia-containers to v1.17.3
- Upgrade to v1.17.3
- Add nvidia-cdi-hook binary to nvidia-container-toolkit-base package
- Add nvidia-container-toolkit-base as runtime requirement for nvidia-container-toolkit
NO
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=692991&view=results
> [2.0 Fast-track] Upgrade nvidia container toolkit and libnvidia-container to v1.17.3

- SPECS/moby-cli/CVE-2024-24786.patch
- SPECS/moby-cli/moby-cli.spec
---
Patch CVE-2024-24786 in moby-cli
**NO**
- NA
> Patch CVE-2024-24786 in moby-cli

- toolkit/docs/building/building.md
- toolkit/scripts/daily_build.mk
- toolkit/scripts/toolchain.mk
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Provide an option not to auto-clean toolchain during daily-build

- SPECS/cert-manager/CVE-2024-45337.patch
- SPECS/cert-manager/cert-manager.spec
---
Add patch to resolve CVE-2024-45337 in cert-manager vendor source
- Patch CVE-2024-45337 in cert-manager
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45337
> cert-manager: patch CVE-2024-45337

- SPECS/moby-compose/CVE-2024-45337.patch
- SPECS/moby-compose/moby-compose.spec
---
Add patch to resolve CVE-2024-45337 in moby-compose vendor source
- Patch CVE-2024-45337 in moby-compose
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45337
> moby-compose: patch CVE-2024-45337

- SPECS/moby-engine/CVE-2024-45337.patch
- SPECS/moby-engine/moby-engine.spec
---
Add patch to resolve CVE-2024-45337 in moby-engine vendor source
- Patch CVE-2024-45337 in moby-engine
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45337
> moby-engine: patch CVE-2024-45337

- SPECS/pam/CVE-2024-10041.patch
- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add patch for CVE-2024-10041, had to create a new PR because I messed up the rebasing of 3.0-dev 
- CVE-2024-10041
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-10041
- Pipeline build id: 696625 succeeded 
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=696625&view=results
> pam: Add patch for CVE-2024-10041

- SPECS/python-zipp/CVE-2024-5569.patch
- SPECS/python-zipp/python-zipp.spec
This is an auto-generated pull request to cherry-pick commit 67e848f8b24ea6857390175f2fb1aca538a0ca15 to 3.0-dev. Original PR: #11515
> [AUTO-CHERRYPICK] Patch python-zipp for CVE-2024-5569 - branch 3.0-dev

- SPECS/etcd/CVE-2024-24786.patch
- SPECS/etcd/etcd.spec
This is an auto-generated pull request to cherry-pick commit 98236f43e474ce33345a1460e812c8977e766d8c to 3.0-dev. Original PR: #11385
> [AUTO-CHERRYPICK] Fix CVE-2024-24786 for etcd in 3.0 - branch 3.0-dev

- SPECS/grpc/CVE-2023-32067.patch
- SPECS/grpc/grpc.spec
This is an auto-generated pull request to cherry-pick commit 4baf82743629d4cf8a0e6a182b84c4efe75dad11 to main. Original PR: #11394
> [AUTO-CHERRYPICK] grpc: Address CVE-2023-32067  - branch main

- SPECS/avahi/CVE-2023-38469.patch
- SPECS/avahi/CVE-2023-38470.patch
- SPECS/avahi/CVE-2023-38471.patch
- SPECS/avahi/CVE-2023-38472.patch
- SPECS/avahi/CVE-2023-38473.patch
- SPECS/avahi/avahi.spec
This is an auto-generated pull request to cherry-pick commit 0f715e98e63b91cb9b6c4588a53aceabcb8b00a7 to main. Original PR: #11251
> [AUTO-CHERRYPICK] Patch avahi for multiple CVEs - branch main

- SPECS/moby-engine/CVE-2024-24786.patch
- SPECS/moby-engine/moby-engine.spec
This is an auto-generated pull request to cherry-pick commit db971fcec21d7aca4ec3324a462f2cf1690c8f50 to main. Original PR: #11323
> [AUTO-CHERRYPICK] Patch CVE-2024-24786 in moby-engine - branch main

- SPECS/cf-cli/CVE-2024-45337.patch
- SPECS/cf-cli/cf-cli.spec
- SPECS/kubevirt/CVE-2024-45337.patch
- SPECS/kubevirt/kubevirt.spec
- SPECS/packer/CVE-2024-45337.patch
- SPECS/packer/packer.spec
---
Patch CVE-2024-45337 for:
* cf-cli
* kubevirt
* packer
**NO**
- Pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=697943&view=results
> cf-cli, kubevirt, packer: patch CVE-2024-45337

- SPECS/dpdk/dpdk.signatures.json
- SPECS/dpdk/dpdk.spec
- cgmanifest.json
---
Upgrade dpdk to fix CVE-2024-11614
> Upgrade DPDK for CVE-2024-11614

- SPECS/azurelinux-release/azurelinux-release.spec
Bumping release for Azure Linux 3.0 January 2025 Update.
> Bump Release for January 2025 Update

- .pipelines/containerSourceData/cuda/core.pkg
---
- Fix NVIDIA GPU driver container by onboarding kernel-drivers-gpu package into the build flow, who was recently added as a runtime requirement of the CUDA RPM
- Add kernel-drivers-gpu package to be installed when building the NVIDIA GPU driver container image
NO
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/10109/?view=edit
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=687124&view=results
> [3.0] Add kernel-drivers-gpu package to NVIDIA GPU driver container build

- SPECS/libxml2/CVE-2024-40896.patch
- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- **libxml2: address CVE-2024-40896**
- Patch CVE-2024-40896
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-40896
- Pipeline build id: [validating]
> libxml2: address CVE-2024-40896

- .github/workflows/check-manifests.yml
- .github/workflows/check-package-cgmanifest.yml
---
Looks like GitHub updated `ubuntu-latest` to use 24.04 version of that system from 22.04. This change addresses the PR checks failures this has caused.
No.
- PR checks for this PR.
> Fixing RPM macros check.

- SPECS-EXTENDED/certmonger/certmonger.signatures.json
- SPECS-EXTENDED/certmonger/certmonger.spec
- cgmanifest.json
---
Fix build issues with certmonger package to include it in extended repo as per the request - https://microsoft.visualstudio.com/OS/_workitems/edit/52967653
- Upgraded certmonger version to 0.79.20 to build it successfully so that it can be published and made available in extended repo.
**NO**
- #52967653
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=691159&view=results
> Fix "certmonger" extended package to make it available for linkedin - P0 work item 52967653

- SPECS/rsync/rsync.signatures.json
- SPECS/rsync/rsync.spec
- cgmanifest.json
---
- Upgrade rsync to version 3.4.1 to fix CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, CVE-2024-12088, CVE-2024-12747
- Upgrade rsync to version 3.4.1 to fix CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, CVE-2024-12088, CVE-2024-12747
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-12084 (Critical)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12085 (High)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12086 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12087 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12088 (Medium)
- https://nvd.nist.gov/vuln/detail/CVE-2024-12747 (Medium)
- Local build and %check section succeeded
- Pipeline …
> rsync: upgrade to 3.4.1 to fix multiple CVEs

- SPECS/cmake/CVE-2024-11053.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2024-11053 in vendored curl in cmake
- Backport upstream fix for CVE-2024-11053 to vendored curl 7.77.0 in cmake
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-11053
- Patched 7.77.0 curl standalone, passed existing and new netrc unit tests then applied patch to vendored cmake
- Built cmake package locally and check section succeeded
- Pipeline build id: 712007
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712007
> cmake: patch CVE-2024-11053

- SPECS-EXTENDED/perl-Lingua-EN-Inflect/perl-Lingua-EN-Inflect.signatures.json
- SPECS-EXTENDED/perl-Lingua-EN-Inflect/perl-Lingua-EN-Inflect.spec
- cgmanifest.json
---
Update to current upstream
- Version bump
**NO**
- Local build.
> Update perl-Lingua-EN-Inflect to version 1.905-1

- SPECS/tensorflow/CVE-2024-35195.patch
- SPECS/tensorflow/tensorflow.spec
---
- CVE-2024-35195
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35195
- Pipeline build id: [712917](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712917&view=results)
> Patch tensorflow for CVE-2024-35195

- SPECS/git/git.signatures.json
- SPECS/git/git.spec
- cgmanifest.json
---
Patch CVE-2024-50349 and CVE-2024-52006 in git
- CVE-2024-50349
- CVE-2024-52006
**NO**
- #xxxx
> Patch CVE-2024-50349 and CVE-2024-52006 in git

- SPECS/vim/CVE-2025-22134.patch
- SPECS/vim/vim.spec
- [* ] The toolchain has been rebuilt successfully (or no changes were made to it) …
> Fix CVE-2025-22134 in vim for 2.0

- SPECS/qtbase/CVE-2024-56732.patch
- SPECS/qtbase/qtbase.spec
---
Added a patch to address CVE-2024-56732 for qtbase.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-56732
- Local build
- Pipeline buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=713001&view=results
> Added a patch to address CVE-2024-56732 for qtbase.

- SPECS/fwctl/fwctl.spec
- SPECS/iser/iser.spec
- SPECS/isert/isert.spec
- SPECS/knem/knem.spec
- SPECS/mft_kernel/mft_kernel.spec
- SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
- SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
- SPECS/srp/srp.spec
- SPECS/xpmem/xpmem.spec
- toolkit/scripts/check_entangled_specs.py
---
This PR adds a logic to PR checker to ensure OOT module specs gets upgrade along with kernel upgrade. This version bump in OOT module specs is necessary to make sure they are getting rebuilt over kernel upgrades.
**NO**
Tested locally and ensured the desired behavior.
> Add logic to PR checker to detect kernel upgrade for OOT module specs

- SPECS/libtiff/CVE-2023-3164.patch
- SPECS/libtiff/libtiff.spec
- [ *] The toolchain has been rebuilt successfully (or no changes were made to it) …
> Fix CVE-2023-3164 in libtiff package for 3.0

- SPECS-EXTENDED/rdma-core/rdma-core.signatures.json
- SPECS-EXTENDED/rdma-core/rdma-core.spec
- cgmanifest.json
---
Add latest version of rdma-core which is one of the MOFED dependencies to PMC's extended repo.
- Change
- Change
- Change
**NO**
- Pipeline build id: [707690](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=707690&view=results)
> Add rdma-core to PMC's extended repo

- SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
- SPECS-SIGNED/iser-signed/iser-signed.spec
- SPECS-SIGNED/isert-signed/isert-signed.spec
- SPECS-SIGNED/knem-signed/knem-modules-signed.spec
- SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
- SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
- SPECS-SIGNED/mlnx-ofa_kernel-signed/mlnx-ofa_kernel-modules-signed.spec
- SPECS-SIGNED/srp-signed/srp-signed.spec
- SPECS-SIGNED/xpmem-signed/xpmem-modules-signed.spec
- SPECS/fwctl/fwctl.spec
- SPECS/iser/iser.spec
- SPECS/isert/isert.spec
- SPECS/knem/knem.spec
- SPECS/mft_kernel/mft_kernel.spec
- SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
- SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
- SPECS/srp/srp.spec
- SPECS/xpmem/xpmem.spec
---
https://github.com/microsoft/azurelinux/pull/11479 added mofed and dependencies along with their signed specs. Signed specs had errors which broke the build after snap. Apparently, those specs were not parsed the same way in earlier dev and test builds.
**YES/NO**
NO
- #xxxx
Since signed specs are built only in prod builds these were tested with a local mock build.
> mofed and deps signed spec cleanup

- SPECS/terraform/CVE-2023-0475.patch
- SPECS/terraform/terraform.spec
---
Patch terraform to fix CVE-2023-0475
- CVE-2023-0475
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-0475
- Pipeline build id: [716309](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=716309&view=results)
> Patch terraform to fix CVE-2023-0475

- SPECS/mlnx-ofa_kernel/001-fix-module-init-for-ibt.patch
- SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
---
IBT (Indirect Branch Tracking) and CFI (Control Flow Integrity) do not play well together since Link Time Optimization (LTO) may optimize away the relevant symbol. Add a patch to mlnx-ofa_kernel driver init to make sure this does not happen to module init.
- Change
- Change
- Change
**YES/NO**
NO
- #xxxx
> Add patch to mlnx-ofa_kernel module for IBT compatibility

- SPECS/cni/CVE-2022-29526.patch
- SPECS/cni/CVE-2024-45338.patch
- SPECS/cni/cni.spec
---
- Fix CVE-2022-29526 and CVE-2024-45338 for cni package
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-29526
- https://nvd.nist.gov/vuln/detail/CVE-2024-45338
- Pipeline build :https://dev.azure.com/mariner-org/mariner/_build/results?buildId=717401&view=results
> cni : Fix CVE-2022-29526 and CVE-2024-45338

- SPECS/xerces-c/CVE-2024-23807.patch
- SPECS/xerces-c/xerces-c.signatures.json
- SPECS/xerces-c/xerces-c.spec
- cgmanifest.json
---
- Fix CVE-2024-23807
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-23807
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=717579&view=results
> xerces-c : Fix CVE-2024-23807

- SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
- SPECS/mft_kernel/mft_kernel.spec
---
"mft_kernel" rpm was forced to be built as kernel-mft*rpm. This upset dependency checker for signed packages. Instead of renaming we retain the name mft_kernel*rpm and add a provides for kernel-mft.
- Change
- Change
- Change
**YES/NO**
NO
- #xxxx
> rollback mft_kernel rpm name and add provides for kernel-mft

- SPECS/vim/CVE-2025-24014.patch
- SPECS/vim/vim.spec
---
patch vim to fix CVE-2025-24014
- vim.spec
- CVE-2025-24014.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-24014
> [Medium] patch vim to fix CVE-2025-24014

- SPECS/cmake/CVE-2024-9681.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch cmake to fix CVE-2024-9681
- cmake.spec
- CVE-2024-9681.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-9681
> [Medium] Patch cmake to fix CVE-2024-9681

- SPECS/xerces-c/CVE-2024-23807.patch
- SPECS/xerces-c/xerces-c.spec
- cgmanifest.json
---
- Fix CVE-2024-23807
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-23807
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=717601&view=results
> xerces-c: Fix CVE-2024-23807

- SPECS/git-lfs/CVE-2024-53263.patch
- SPECS/git-lfs/git-lfs.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Fix CVE-2024-53263 in git-lfs

- SPECS/libxml2/CVE-2022-49043.patch
- SPECS/libxml2/libxml2.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add Patch libxml2 for CVE-2022-49043
- Reference: https://github.com/GNOME/libxml2/commit/5a19e21605398cef6a8b1452477a8705cb41562b
- Update toolchain manifest entries
- 
- CVE-2022-49043
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-49043
- Pipeline build id: [720883](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=720883&view=results)
- Prepare Build- [PrepareBuild](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=720886&view=results)
- AMD64 Toolchain : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=720900&view=results
- ARM64 Toolchain : …
> Patch libxml2 for CVE-2022-49043

- toolkit/tools/precacher/precacher.go
---
Added logging for one `err` variable we never printed.
No.
- PR check Go tests.
> Added logging for missed pre-cacher download error.

- SPECS-EXTENDED/perl-File-ShareDir-Install/perl-File-ShareDir-Install.signatures.json
- SPECS-EXTENDED/perl-File-ShareDir-Install/perl-File-ShareDir-Install.spec
- cgmanifest.json
---
Update `perl-File-ShareDir-Install` to version `0.14-1`
- Version bump
**NO**
- Local build
> Update perl-File-ShareDir-Install to version 0.14

- SPECS/ostree/ostree.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Update URL for ostree

- SPECS/openmpi/CVE-2022-47022.patch
- SPECS/openmpi/openmpi.spec
---
patch openmpi to fix CVE-2022-47022
- openmpi.spec
- CVE-2022-47022.patch
**NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2022-47022
> [Medium] patch openmpi to fix CVE-2022-47022

- SPECS/rook/CVE-2024-28180.patch
- SPECS/rook/rook.spec
---
- Address CVE-2024-28180
- CVE-2024-28180
**NO**
- #xxxx
- Pipeline build id: [722671](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=722671&view=results)
- The test_install_amd64_test_built_packages & test_install_arm64_test_built_packages failure is known [2.0-rook Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=722683&view=results)
> Patch rook for CVE-2024-28180

- SPECS/dmidecode/dmidecode.signatures.json
- SPECS/dmidecode/dmidecode.spec
- cgmanifest.json
---
Updation of dmidecode version from 3.5 to 3.6, which will help in proper listing of NVIDA GB200 properties, which will be helpful in  B200 Server Certification.
Auto-upgrade to 3.6 - 55875043 - NVIDIA (GB200) properties support
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/55875043
- NA
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=718277&view=results
-  Properties can be seen properly
> Upgrade dmidecode to 3.6

- SPECS/pugixml/pugixml.spec
---
The ptest for pugixml is failing currently due to using the wrong command to run the tests.
- Change `make check` to `make test` per upstream makefile
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=724213&view=results
> Fix ptest for pugixml

- SPECS/subunit/subunit.spec
---
The package test for subunit is failing due to missing python modules. Added the missing modules to resolve the issue.
- Add pip installs for various missing modules.
**NO**
- Local Build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=725146&view=results
> Fix ptest for subunit via pip installs

- SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
- SPECS-SIGNED/iser-signed/iser-signed.spec
- SPECS-SIGNED/isert-signed/isert-signed.spec
- SPECS-SIGNED/knem-modules-signed/knem-modules-signed.spec
- SPECS-SIGNED/mft_kernel-signed/mft_kernel-signed.spec
- SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
- SPECS-SIGNED/mlnx-ofa_kernel-modules-signed/mlnx-ofa_kernel-modules-signed.spec
- SPECS-SIGNED/srp-signed/srp-signed.spec
- SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
---
Update MOFED signed SPECS to avoid stripping signatures off OOT kernel modules by os_install_post macro.
- Change
Update MOFED signed SPECS to avoid stripping signatures off OOT kernel modules by os_install_post macro 
**NO**
- #xxxx
- Local build.
> Update MOFED signed SPECS to avoid stripping signatures off OOT kernel modules by os_install_post macro 

- SPECS/vitess/CVE-2024-45339.patch
- SPECS/vitess/vitess.spec
---
- Fix CVE-2024-45339
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45339
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=724782&view=results
- Skipping tests during the build process due to failures in the official test
> vitess: Fix CVE-2024-45339

- SPECS-EXTENDED/perl-Class-C3-XS/perl-Class-C3-XS.signatures.json
- SPECS-EXTENDED/perl-Class-C3-XS/perl-Class-C3-XS.spec
- cgmanifest.json
---
Upgrade: perl-Class-C3-XS version to 0.15
- SPECS-EXTENDED/perl-Class-C3-XS/perl-Class-C3-XS.signatures.json
- SPECS-EXTENDED/perl-Class-C3-XS/perl-Class-C3-XS.spec
**NO**
- #xxxx
>  Upgrade: perl-Class-C3-XS version to 0.15

- SPECS-EXTENDED/pywbem/0001-use-unittest-mock.patch
- SPECS-EXTENDED/pywbem/0002-coverity-deadcode.patch
- SPECS-EXTENDED/pywbem/0003-coverity-forward-null.patch
- SPECS-EXTENDED/pywbem/0004-coverity-identifier-typo.patch
- SPECS-EXTENDED/pywbem/0005-python3_12.patch
- SPECS-EXTENDED/pywbem/pywbem.signatures.json
- SPECS-EXTENDED/pywbem/pywbem.spec
- cgmanifest.json
---
Upgrade: pywbem version to 0.17.6
- new file:   SPECS-EXTENDED/pywbem/0001-use-unittest-mock.patch
- new file:   SPECS-EXTENDED/pywbem/0002-coverity-deadcode.patch
- new file:   SPECS-EXTENDED/pywbem/0003-coverity-forward-null.patch
- new file:   SPECS-EXTENDED/pywbem/0004-coverity-identifier-typo.patch
- new file:   SPECS-EXTENDED/pywbem/0005-python3_12.patch
- modified:   SPECS-EXTENDED/pywbem/pywbem.signatures.json
- modified:   SPECS-EXTENDED/pywbem/pywbem.spec
**NO**
- #xxxx
> Upgrade: pywbem version to 0.17.6

- SPECS-EXTENDED/re2c/re2c.signatures.json
- SPECS-EXTENDED/re2c/re2c.spec
- cgmanifest.json
---
Upgrade: re2c version to 3.1
- modified:   SPECS-EXTENDED/re2c/re2c.signatures.json
- modified:   SPECS-EXTENDED/re2c/re2c.spec
**NO**
- #xxxx
> Upgrade: re2c version to 3.1

- SPECS-EXTENDED/blosc/blosc.signatures.json
- SPECS-EXTENDED/blosc/blosc.spec
- cgmanifest.json
---
Update `blosc` to current upstream. This will require its [sources](https://github.com/Blosc/c-blosc/archive/v1.21.6/blosc-1.21.6.tar.gz) to be uploaded to the blobstore.
- Change/verify new BSD licensing
- Version bump
**NO**
- Local build.
> Update blosc to 1.21.6-1

- SPECS-EXTENDED/fabtests/fabtests.signatures.json
- SPECS-EXTENDED/fabtests/fabtests.spec
- cgmanifest.json
---
fabtests: update version to 1.18.0
- SPECS-EXTENDED/fabtests/fabtests.signatures.json
- SPECS-EXTENDED/fabtests/fabtests.spec
- 
**NO**
- #xxxx
>  fabtests: update version to 1.18.0

- SPECS-EXTENDED/liblouis/liblouis.signatures.json
- SPECS-EXTENDED/liblouis/liblouis.spec
- cgmanifest.json
---
Upgrade liblouis to 3.31.0
**NO**
- Local build
> Update liblouis to 3.31.0

- SPECS-EXTENDED/volume_key/volume_key-0.3.12-fix_resource_leaks.patch
- SPECS-EXTENDED/volume_key/volume_key.spec
---
volume_key: fix build
(Required to build libbloackdev)
- SPECS-EXTENDED/volume_key/volume_key.spec
**NO**
- #xxxx
> volume_key: fix build

- SPECS/sriov-network-device-plugin/CVE-2024-45339.patch
- SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
---
- Fix CVE-2024-45339
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45339
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=724791&view=results
> sriov-network-device-plugin: Fix CVE-2024-45339

- SPECS-EXTENDED/deltarpm/deltarpm.signatures.json
- SPECS-EXTENDED/deltarpm/deltarpm.spec
- cgmanifest.json
---
**deltarpm: update version to 3.6.5**
- modified: SPECS-EXTENDED/deltarpm/deltarpm.spec
- modified: SPECS-EXTENDED/deltarpm/deltarpm.signatures.json
- #xxxx
> deltarpm: Update Version from 3.6.2 -> 3.6.5

- SPECS/msft-golang/CVE-2024-45336.patch
- SPECS/msft-golang/CVE-2024-45341.patch
- SPECS/msft-golang/msft-golang.spec
---
- Address [CVE-2024-45336](https://nvd.nist.gov/vuln/detail/CVE-2024-45336), [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341)
- [CVE-2024-45336](https://nvd.nist.gov/vuln/detail/CVE-2024-45336)
- [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341)
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45336
- https://nvd.nist.gov/vuln/detail/CVE-2024-45341
- Pipeline build id: [Buddy Build -727702](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=727702&view=results)
> Patch msft-golang for CVE-2024-45336, CVE-2024-45341 [High] 

- SPECS/golang/CVE-2024-45336.patch
- SPECS/golang/CVE-2024-45341.patch
- SPECS/golang/golang-1.18.spec
- SPECS/golang/golang.spec
---
- Address [CVE-2024-45336](https://nvd.nist.gov/vuln/detail/CVE-2024-45336), [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341)
- Address [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341) for go1.18.8
- [CVE-2024-45336](https://nvd.nist.gov/vuln/detail/CVE-2024-45336)
- [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341)
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45336
- https://nvd.nist.gov/vuln/detail/CVE-2024-45341
- Pipeline build id: [Buddy Build -727710](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=727710&view=results)
> Patch golang for CVE-2024-45336, CVE-2024-45341 [High]

- SPECS-EXTENDED/acpid/acpid.signatures.json
- SPECS-EXTENDED/acpid/acpid.socket
- SPECS-EXTENDED/acpid/acpid.spec
- cgmanifest.json
---
acpid : Update version to 2.0.34
- SPECS-EXTENDED/acpid/acpid.signatures.json
-SPECS-EXTENDED/acpid/acpid.socket
-SPECS-EXTENDED/acpid/acpid.spec
**NO**
- #xxxx
- 
[acpid-2.0.34-1.azl3.src.rpm.log](https://github.com/user-attachments/files/17815998/acpid-2.0.34-1.azl3.src.rpm.log)
> acpid : Update version to 2.0.34

- SPECS-EXTENDED/adobe-mappings-pdf/adobe-mappings-pdf.signatures.json
- SPECS-EXTENDED/adobe-mappings-pdf/adobe-mappings-pdf.spec
- cgmanifest.json
---
adobe-mappings-pdf: Update version to 20230118
SPECS-EXTENDED/adobe-mappings-pdf/adobe-mappings-pdf.signatures.json
SPECS-EXTENDED/adobe-mappings-pdf/adobe-mappings-pdf.spec
**NO**
- #xxxx
> adobe-mappings-pdf: Update version to 20230118

- SPECS-EXTENDED/diffstat/diffstat.signatures.json
- SPECS-EXTENDED/diffstat/diffstat.spec
- cgmanifest.json
---
**diffstat: update version to 1.66**
- modified: SPECS-EXTENDED/diffstat/diffstat.spec
- modified: SPECS-EXTENDED/diffstat/diffstat.signatures.json
**NO**
- #xxxx
> diffstat: Update Version from 1.63 -> 1.66

- SPECS-EXTENDED/glew/glew-2.2.0-gcc12-cplusplus.patch
- SPECS-EXTENDED/glew/glew.signatures.json
- SPECS-EXTENDED/glew/glew.spec
- cgmanifest.json
---
Update to 2.2.0-1
../SPECS-EXTENDED/glew/glew-2.2.0-gcc12-cplusplus.patch
../SPECS-EXTENDED/glew/glew.signatures.json
../SPECS-EXTENDED/glew/glew.spec
[glew-2.2.0-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18271869/glew-2.2.0-1.azl3.src.rpm.log)
**NO**
- #xxxx
> glew: Update to 2.2.0

- SPECS-EXTENDED/libbytesize/libbytesize.signatures.json
- SPECS-EXTENDED/libbytesize/libbytesize.spec
- cgmanifest.json
---
libbytesize: update version to 2.11
-  SPECS-EXTENDED/libbytesize/libbytesize.signatures.json
-  SPECS-EXTENDED/libbytesize/libbytesize.spec
-  cgmanifest.json
**NO**
- #xxxx
>  libbytesize: update version to 2.11

- SPECS-EXTENDED/libdeflate/libdeflate.signatures.json
- SPECS-EXTENDED/libdeflate/libdeflate.spec
- cgmanifest.json
---
Update libdeflate version to 1.22
-SPECS-EXTENDED/libdeflate/libdeflate.signatures.json
-SPECS-EXTENDED/libdeflate/libdeflate.spec
**NO**
- #xxxx
>  Update libdeflate version to 1.22

- SPECS-EXTENDED/ocaml-zarith/ocaml-zarith.signatures.json
- SPECS-EXTENDED/ocaml-zarith/ocaml-zarith.spec
- cgmanifest.json
---
ocaml-zarith: update to 1.14
../SPECS-EXTENDED/ocaml-zarith/ocaml-zarith.signatures.json
../SPECS-EXTENDED/ocaml-zarith/ocaml-zarith.spec
[ocaml-zarith-1.14-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18230225/ocaml-zarith-1.14-1.azl3.src.rpm.log)
**NO**
- #xxxx
> ocaml-zarith: update to 1.14

- SPECS-EXTENDED/orc/0001-powerpc-fix-div255w-which-still-used-the-inexact-sub.patch
- SPECS-EXTENDED/orc/orc.signatures.json
- SPECS-EXTENDED/orc/orc.spec
- cgmanifest.json
---
Upgrade: orc version to 0.4.39
- SPECS-EXTENDED/orc/orc.signatures.json
- SPECS-EXTENDED/orc/orc.spec
**NO**
- #xxxx
> Upgrade: orc version to 0.4.39

- SPECS-EXTENDED/parallel/parallel.signatures.json
- SPECS-EXTENDED/parallel/parallel.spec
- cgmanifest.json
---
Upgrade: parallel version to 20240922
- SPECS-EXTENDED/parallel/parallel.signatures.json
- SPECS-EXTENDED/parallel/parallel.spec
**NO**
- #xxxx
> Upgrade: parallel version to 20240922

- SPECS-EXTENDED/perl-Algorithm-Diff/perl-Algorithm-Diff.signatures.json
- SPECS-EXTENDED/perl-Algorithm-Diff/perl-Algorithm-Diff.spec
- cgmanifest.json
---
Upgarde: perl-Algorithm-Diff version to 1.201
-  SPECS-EXTENDED/perl-Algorithm-Diff/perl-Algorithm-Diff.signatures.json
-  SPECS-EXTENDED/perl-Algorithm-Diff/perl-Algorithm-Diff.spec
-  cgmanifest.json
**NO**
- #xxxx
>  Upgarde: perl-Algorithm-Diff version to 1.201

- SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.signatures.json
- SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.spec
- cgmanifest.json
---
Upgrade: perl-Config-IniFiles version to 3.000003
-SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.signatures.json
- SPECS-EXTENDED/perl-Config-IniFiles/perl-Config-IniFiles.spec
**NO**
- #xxxx
> Upgrade: perl-Config-IniFiles version to 3.000003

- SPECS-EXTENDED/python-dbus-signature-pyparsing/python-dbus-signature-pyparsing.signatures.json
- SPECS-EXTENDED/python-dbus-signature-pyparsing/python-dbus-signature-pyparsing.spec
- cgmanifest.json
---
Upgrade: python-dbus-signature-pyparsing version to 0.4.1
- modified:   SPECS-EXTENDED/python-dbus-signature-pyparsing/python-dbus-signature-pyparsing.signatures.json
- modified:   SPECS-EXTENDED/python-dbus-signature-pyparsing/python-dbus-signature-pyparsing.spec
**NO**
- #xxxx
> Upgrade: python-dbus-signature-pyparsing version to 0.4.1

- SPECS-EXTENDED/python-justbases/python-justbases.signatures.json
- SPECS-EXTENDED/python-justbases/python-justbases.spec
- cgmanifest.json
---
Upgrade: python-justbases version to 0.15.2
- modified:   SPECS-EXTENDED/python-justbases/python-justbases.signatures.json
- modified:   SPECS-EXTENDED/python-justbases/python-justbases.spec
**NO**
- #xxxx
> Upgrade: python-justbases version to 0.15.2

- SPECS-EXTENDED/python-justbytes/python-justbytes.signatures.json
- SPECS-EXTENDED/python-justbytes/python-justbytes.spec
- cgmanifest.json
---
Upgrade: python-justbytes version to 0.15.2
- modified:   SPECS-EXTENDED/python-justbytes/python-justbytes.signatures.json
- modified:   SPECS-EXTENDED/python-justbytes/python-justbytes.spec
**NO**
- #xxxx
> Upgrade: python-justbytes version to 0.15.2

- SPECS-EXTENDED/python-kmod/python-kmod.signatures.json
- SPECS-EXTENDED/python-kmod/python-kmod.spec
- cgmanifest.json
---
Upgrade: python-kmod version to 0.9.2
- modified:   SPECS-EXTENDED/python-kmod/python-kmod.signatures.json
- modified:   SPECS-EXTENDED/python-kmod/python-kmod.spec
**NO**
- #xxxx
> Upgrade: python-kmod version to 0.9.2

- SPECS-EXTENDED/python-sphinxcontrib-apidoc/python-sphinxcontrib-apidoc.signatures.json
- SPECS-EXTENDED/python-sphinxcontrib-apidoc/python-sphinxcontrib-apidoc.spec
- cgmanifest.json
---
Upgrade: python-sphinxcontrib-apidoc version to 0.3.0
- modified:   SPECS-EXTENDED/python-sphinxcontrib-apidoc/python-sphinxcontrib-apidoc.signatures.json
- modified:   SPECS-EXTENDED/python-sphinxcontrib-apidoc/python-sphinxcontrib-apidoc.spec
**NO**
- #xxxx
> Upgrade: python-sphinxcontrib-apidoc version to 0.3.0

- SPECS-EXTENDED/python-uritemplate/python-uritemplate.signatures.json
- SPECS-EXTENDED/python-uritemplate/python-uritemplate.spec
- cgmanifest.json
---
Upgrade: python-uritemplate version to 4.1.1
- modified:   SPECS-EXTENDED/python-uritemplate/python-uritemplate.signatures.json
- modified:   SPECS-EXTENDED/python-uritemplate/python-uritemplate.spec
**NO**
- #xxxx
> Upgrade: python-uritemplate version to 4.1.1

- SPECS-EXTENDED/python-xmltodict/python-xmltodict.signatures.json
- SPECS-EXTENDED/python-xmltodict/python-xmltodict.spec
- cgmanifest.json
---
Upgrade: python-xmltodict version to 0.13.0
- modified:   SPECS-EXTENDED/python-xmltodict/python-xmltodict.signatures.json
- modified:   SPECS-EXTENDED/python-xmltodict/python-xmltodict.spec
**NO**
- #xxxx
> Upgrade: python-xmltodict version to 0.13.0

- SPECS/flannel/CVE-2023-44487.patch
- SPECS/flannel/flannel.spec
---
Update flannel package to address CVE-2023-44487.
- Update flannel package to address CVE-2023-44487
- Fix changelog to eliminate warning about malformed date.
**NO**
- #xxxx
- Pipeline build id: [733528](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=733528&view=results)
> Patch flannel to fix CVE-2023-44487

- SPECS/busybox/CVE-2022-48174.patch
- SPECS/busybox/busybox.spec
---
- Address CVE-2022-48174
- CVE-2022-48174
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-48174
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734879&view=results)
> Patch busybox to fix CVE-2022-48174 [Critical]

- SPECS/avahi/CVE-2024-52616.patch
- SPECS/avahi/avahi.spec
---
- Address CVE-2024-52616
- CVE-2024-52616
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-52616
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734737&view=results)
> Patch avahi to fix CVE-2024-52616 [Medium]

- SPECS-SIGNED/srp-signed/srp-signed.spec
- SPECS/srp/srp.spec
---
production build is broken in 3.0 for build errors on fasttrack 3.0. This PR should fix the issue by fixing the bad macro added under this PR#11479.
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734229&view=logs&j=9b40b75c-2778-509d-a176-86ba477400c9&t=13b53a61-b541-5ea4-4d99-460c0af7800d&l=86
- Fix %{azl} macro to 0%{?azl}
**NO**
- PR check
> Update 0%{azl} macro to 0%{?azl} macro for parsing on build machines for srp.spec

- SPECS/kubevirt/CVE-2023-3978.patch
- SPECS/kubevirt/kubevirt.spec
---
Fix CVE-2023-3978 for kubevirt
- CFix CVE-2023-3978 for kubevirt
**NO**
- #xxxx
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=728605&view=results
> [Medium] Fix CVE-2023-3978 for kubevirt

- SPECS/rabbitmq-server/CVE-2023-50966.patch
- SPECS/rabbitmq-server/rabbitmq-server.spec
---
- Address CVE-2023-50966
- CVE-2023-50966
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-50966
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=735160&view=results)
> Patch rabbitmq-server to fix CVE-2023-50966 [Medium]

- SPECS/curl/CVE-2024-11053.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Backport patch for CVE-2024-11053 for curl. Reference: https://[launchpadlibrarian.net/763265128/curl_8.5.0-2ubuntu10.5_8.5.0-2ubuntu10.6.diff.gz](https://launchpadlibrarian.net/763265128/curl_8.5.0-2ubuntu10.5_8.5.0-2ubuntu10.6.diff.gz)
- Backport patch for CVE-2024-11053 for cul.
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2024-11053
- buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734651&view=results
> curl: patch CVE-2024-11053

- SPECS/coredns/coredns-example-net-test.patch
- SPECS/coredns/coredns.spec
---
coredns does not have a %check section in Azl3, but does in Mariner 2. This PR ports that forwards since both azl3 and mariner2 use the same version of coredns
- Add %check section from Mariner 2
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56118784/
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=732925&view=results
> Add ptest for coredns from 2.0 to 3.0

- SPECS/coredns/coredns-example-net-test.patch
- SPECS/coredns/coredns.spec
---
Upstream change taken to change the location of a test network away from example.net which updated to use akamai for load balancing causing the test to fail. Added patch to fix the issue.
- Add upstream patch to change test net away from example.net
**NO**
- Fixes: https://microsoft.visualstudio.com/OS/_workitems/edit/56118784/
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=732886&view=results
> Patch coredns to fix its %check

- SPECS-EXTENDED/systemd-bootchart/systemd-bootchart.signatures.json
- SPECS-EXTENDED/systemd-bootchart/systemd-bootchart.spec
- cgmanifest.json
---
systemd-bootchart.: Update to version 235
- systemd-bootchart.signatures.json
- systemd-bootchart.spec
**NO**
- #xxxx
> systemd-bootchart.: Update to version 235

- SPECS-EXTENDED/perl-File-Remove/perl-File-Remove.signatures.json
- SPECS-EXTENDED/perl-File-Remove/perl-File-Remove.spec
- cgmanifest.json
---
Update `perl-File-Remove` to version `1.61`
- Version bump
**NO**
- Local build.
> Update perl-File-Remove to version 1.61-1

- SPECS-EXTENDED/perl-Test-File/perl-Test-File.signatures.json
- SPECS-EXTENDED/perl-Test-File/perl-Test-File.spec
- cgmanifest.json
---
**perl-Test-File: update version to 1.99.3**
- modified: SPECS-EXTENDED/perl-Test-File/perl-Test-File.spec
- modified: SPECS-EXTENDED/perl-Test-File/perl-Test-File.signatures.json
**NO**
- #xxxx
> perl-Test-File: Update Version from  1.44.3 -> 1.99.3

- SPECS-EXTENDED/perl-Test-EOL/perl-Test-EOL.signatures.json
- SPECS-EXTENDED/perl-Test-EOL/perl-Test-EOL.spec
- cgmanifest.json
---
**perl-Test-EOL: update version to 2.02**
- modified: SPECS-EXTENDED/perl-Test-EOL/perl-Test-EOL.spec
- modified: SPECS-EXTENDED/perl-Test-EOL/perl-Test-EOL.signatures.json
**NO**
- #xxxx
> perl-Test-EOL: Update Version from 2.00 -> 2.02

- SPECS-EXTENDED/gom/gom.signatures.json
- SPECS-EXTENDED/gom/gom.spec
- cgmanifest.json
---
gom: update to 0.5.3
../SPECS-EXTENDED/gom/gom.signatures.json
../SPECS-EXTENDED/gom/gom.spec
[gom-0.5.3-3.azl3.src.rpm.log](https://github.com/user-attachments/files/17828762/gom-0.5.3-3.azl3.src.rpm.log)
**NO**
- #xxxx
> gom: update to 0.5.3

- SPECS-EXTENDED/libuninameslist/libuninameslist.signatures.json
- SPECS-EXTENDED/libuninameslist/libuninameslist.spec
- cgmanifest.json
---
**libuninameslist: update version to 20230916**
- modified: SPECS-EXTENDED/libuninameslist/libuninameslist.spec
- modified: SPECS-EXTENDED/libuninameslist/libuninameslist.signatures.json
**NO**
- #xxxx
> libuninameslist: Update Version from 20200313 -> 20230916

- SPECS-EXTENDED/libmediaart/libmediaart.signatures.json
- SPECS-EXTENDED/libmediaart/libmediaart.spec
- cgmanifest.json
---
Update `libmediaart` to `1.9.6`
- Version bump
- Switch from `configure` to `meson`
- Obsolete `libmediaart-tests` (inspired by fedora's packaging)
**NO**
- Local build.
> Update libmediaart to 1.9.6-1

- SPECS-EXTENDED/libraqm/libraqm-3f50e35.patch
- SPECS-EXTENDED/libraqm/libraqm.signatures.json
- SPECS-EXTENDED/libraqm/libraqm.spec
- cgmanifest.json
---
The PR is to upgrade the libraqm package to version 0.8.0
- SPECS-EXTENDED/libraqm/libraqm-3f50e35.patch
- SPECS-EXTENDED/libraqm/libraqm.signatures.json
- SPECS-EXTENDED/libraqm/libraqm.spec
**NO**
- #xxxx
> Upgrade: libraqm version to 0.8.0

- SPECS-EXTENDED/iprutils/iprutils-2.4.19-covscan.patch
- SPECS-EXTENDED/iprutils/iprutils.signatures.json
- SPECS-EXTENDED/iprutils/iprutils.spec
- cgmanifest.json
---
The PR is to upgrade the iprutils package to version 2.4.19
- SPECS-EXTENDED/iprutils/iprutils-2.4.19-covscan.patch
- SPECS-EXTENDED/iprutils/iprutils.signatures.json
- SPECS-EXTENDED/iprutils/iprutils.spec
**NO**
- #xxxx
> Upgrade: iprutils version to 2.4.19

- SPECS-EXTENDED/ipcalc/ipcalc.signatures.json
- SPECS-EXTENDED/ipcalc/ipcalc.spec
- cgmanifest.json
---
The PR is to upgrade the ipcalc package to version 1.0.3
- SPECS-EXTENDED/ipcalc/ipcalc.signatures.json
- SPECS-EXTENDED/ipcalc/ipcalc.spec
**NO**
- #xxxx
> Upgrade: ipcalc version to 1.0.3

- SPECS-EXTENDED/pyatspi/pyatspi.signatures.json
- SPECS-EXTENDED/pyatspi/pyatspi.spec
- cgmanifest.json
---
The PR is to upgrade the pyatspi package to version 2.46.1
- SPECS-EXTENDED/pyatspi/pyatspi.signatures.json
- SPECS-EXTENDED/pyatspi/pyatspi.spec
**NO**
- #xxxx
> Upgrade: pyatspi version to 2.46.1

- SPECS-EXTENDED/ioping/ioping.signatures.json
- SPECS-EXTENDED/ioping/ioping.spec
- cgmanifest.json
---
The PR is to upgrade the ioping package to version 1.3
- SPECS-EXTENDED/ioping/ioping.signatures.json
- SPECS-EXTENDED/ioping/ioping.spec
**NO**
- #xxxx
> Upgrade: ioping version to 1.3

- SPECS-EXTENDED/python-augeas/python-augeas-test-package-installation.patch
- SPECS-EXTENDED/python-augeas/python-augeas.signatures.json
- SPECS-EXTENDED/python-augeas/python-augeas.spec
- cgmanifest.json
---
Upgrade: python-augeas version to 1.1.0
- new file:   SPECS-EXTENDED/python-augeas/python-augeas-test-package-installation.patch
- modified:   SPECS-EXTENDED/python-augeas/python-augeas.signatures.json
- modified:   SPECS-EXTENDED/python-augeas/python-augeas.spec
**NO**
- #xxxx
> Upgrade: python-augeas version to 1.1.0

- SPECS-EXTENDED/libgee/libgee.signatures.json
- SPECS-EXTENDED/libgee/libgee.spec
- cgmanifest.json
---
libgee: update to 0.20.6-8
../SPECS-EXTENDED/libgee/libgee.signatures.json
../SPECS-EXTENDED/libgee/libgee.spec
[libgee-0.20.6-8.azl3.src.rpm.log](https://github.com/user-attachments/files/17922303/libgee-0.20.6-8.azl3.src.rpm.log)
**NO**
- #xxxx
> libgee: update to 0.20.6-1

- SPECS-EXTENDED/tlog/tlog.signatures.json
- SPECS-EXTENDED/tlog/tlog.spec
- SPECS-EXTENDED/tlog/tlog.sysusers
- cgmanifest.json
---
Upgrade: tlog version to 14
Please build following package with tlog:
libutempter
- Depends on #11116 
- ../SPECS-EXTENDED/tlog/tlog.sysusers
- ../cgmanifest.json
- ../SPECS-EXTENDED/tlog/tlog.spec
- ../SPECS-EXTENDED/tlog/tlog.signatures.json
**NO**
- #xxxx
> Upgrade: tlog version to 14

- SPECS/emacs/CVE-2025-1244.patch
- SPECS/emacs/emacs.spec
---
- Address CVE-2025-1244
- CVE-2025-1244
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1244
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=737273&view=results)
> Patch `emacs` for CVE-2025-1244 [High]

- SPECS/prometheus-node-exporter/CVE-2023-45288.patch
- SPECS/prometheus-node-exporter/prometheus-node-exporter.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=736099&view=results)
> Patch prometheus-node-exporter to fix CVE-2023-45288 [High]

- SPECS/cf-cli/CVE-2023-45288.patch
- SPECS/cf-cli/cf-cli.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=736057&view=results)
> Patch cf-cli to fix CVE-2023-45288 [High]

- SPECS/node-problem-detector/CVE-2023-45288.patch
- SPECS/node-problem-detector/node-problem-detector.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=735977&view=results)
> Patch node-problem-detector to fix CVE-2023-45288 [High]

- SPECS/flannel/CVE-2023-45288.patch
- SPECS/flannel/flannel.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=735971&view=results)
> Patch flannel to fix CVE-2023-45288 [High]

- SPECS/moby-engine/CVE-2023-45288.patch
- SPECS/moby-engine/moby-engine.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=735913&view=results)
> Patch moby-engine to fix CVE-2023-45288 [High]

- toolkit/scripts/utils.mk
---
2.0 backport of https://github.com/microsoft/azurelinux/pull/12335
- Update the Makefile's `create_folder` function to print stderr if any is generated by `mkdir`.
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56157284
- Full build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734272&view=results
- Sanity test: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=734274&view=results (note, this failed since the sanity test can only build stable/preview branches, but the directory creation part worked).
> Print errors when creating directories in makefile

- SPECS/binutils/CVE-2025-1178.patch
- SPECS/binutils/binutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2025-1178
- Fix CVE-2025-1178
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1178
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=738270&view=results
> [Medium] Fix binutils CVE-2025-1178

- SPECS/reaper/CVE-2020-24025.patch
- SPECS/reaper/reaper.spec
---
- Address CVE-2020-24025
- CVE-2020-24025
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2020-24025
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=738364&view=results)
> Patch `reaper` for CVE-2020-24025 [Medium]

- SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.signatures.json
- SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.spec
- cgmanifest.json
---
Upgrade: python-pytest-relaxed version to 2.0.2
- modified:   SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.signatures.json
- modified:   SPECS-EXTENDED/python-pytest-relaxed/python-pytest-relaxed.spec
**NO**
- #xxxx
> Upgrade: python-pytest-relaxed version to 2.0.2

- SPECS-EXTENDED/perl-MIME-Charset/perl-MIME-Charset.signatures.json
- SPECS-EXTENDED/perl-MIME-Charset/perl-MIME-Charset.spec
- cgmanifest.json
---
Upgrade: perl-MIME-Charset version to 1.013.1
- Version bump up to 1.013.1
**NO**
- #xxxx
> Upgrade: perl-MIME-Charset version to 1.013.1

- SPECS/gh/CVE-2025-25204.patch
- SPECS/gh/gh.spec
---
Patch gh for cli issue [10418](https://github.com/cli/cli/issues/10418)
- Patch gh for [CVE-2025-25204](https://nvd.nist.gov/vuln/detail/CVE-2025-25204)
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-25204
- Pipeline build id: [#PR-12539](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=741901&view=results)
> gh: Address CVE-2025-25204 [Medium]

- SPECS/libcap/CVE-2025-1390.patch
- SPECS/libcap/libcap.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Address CVE-2025-1390
- CVE-2025-1390
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1390
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=742958&view=results)
> Patch `libcap` for CVE-2025-1390 [Medium]

- SPECS/vim/CVE-2025-1215.patch
- SPECS/vim/CVE-2025-26603.patch
- SPECS/vim/vim.spec
---
- Address CVE-2025-26603 & CVE-2025-1215
- CVE-2025-1215
- CVE-2025-26603
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-26603
- https://nvd.nist.gov/vuln/detail/CVE-2025-1215
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=743127&view=results)
> Patch `vim` for CVE-2025-26603 & CVE-2025-1215 [Medium]

- SPECS-EXTENDED/servletapi4/java160_build.patch
---
This PR is to provide build fix for package servletapi4
- SPECS-EXTENDED/servletapi4/java160_build.patch
**NO**
- #xxxx
- Local Build
> Build fix for servletapi4

- SPECS-EXTENDED/python-waitress/python-waitress.signatures.json
- SPECS-EXTENDED/python-waitress/python-waitress.spec
- cgmanifest.json
---
Upgrade: python-waitress version to 3.0.1
- Version bump up to 3.0.1
**NO**
- #xxxx
> Upgrade: python-waitress version to 3.0.1

- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add `%check` section to `curl`.
- Add `%check` section to `curl`.
**YES**
- ADO: https://microsoft.visualstudio.com/OS/_workitems/edit/56428488
- Built locally and tests work.
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=747771&view=results
> curl add ptests

- SPECS/opensc/CVE-2023-40660.patch
- SPECS/opensc/CVE-2024-1454.patch
- SPECS/opensc/opensc.spec
---
opensc: Fix CVE-2023-40660 and CVE-2024-1454
- new file: **SPECS/opensc/CVE-2024-1454.patch**
- new file: **SPECS/opensc/CVE-2023-40660.patch**
- modified: **SPECS/opensc/opensc.spec**
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-1454
- https://nvd.nist.gov/vuln/detail/CVE-2023-40660
> [Medium] opensc: Fix CVE-2023-40660 and CVE-2024-1454

- SPECS/fluent-bit/CVE-2024-50608.patch
- SPECS/fluent-bit/CVE-2024-50609.patch
- SPECS/fluent-bit/fluent-bit.spec
---
Addresses [CVE-2024-50608, CVE-2024-50609](https://www.ebryx.com/blogs/exploring-cve-2024-50608-and-cve-2024-50609)
- Added check for content length zero header as per [CVE-2024-50608, CVE-2024-50609](https://www.ebryx.com/blogs/exploring-cve-2024-50608-and-cve-2024-50609)
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-50608
- https://nvd.nist.gov/vuln/detail/CVE-2024-50609
- Pipeline build id: [747308](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=747308&view=results)
> Patch fluent-bit for CVE-2024-50608 [HIGH] and CVE-2024-50609 [HIGH] 

- SPECS/curl/CVE-2024-9681.patch
- SPECS/curl/curl.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch curl for CVE-2024-9681
- Patch curl for CVE-2024-9681 
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-9681
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=746152&view=results
> Patch curl for CVE-2024-9681 [Medium]

- SPECS/python-execnet/python-execnet.spec
---
- Change python-execnet to fix ptests
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56190965
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=740485&view=results
> python-execnet: fix ptest

- SPECS/python-execnet/python-execnet.spec
---
Change python-execnet to fix ptests
- Change python-execnet to fix ptests
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56190965
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=744813&view=results
> [3.0] python-execnet: fix package test

- SPECS/libcap/libcap.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- fixes the ptest
- Change
- Change
- Change
**YES**
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=746024&view=results)
> [2.0] fix ptest for `libcap`

- SPECS/erlang/CVE-2025-26618.patch
- SPECS/erlang/erlang.spec
---
- Address CVE-2025-26618
- CVE-2025-26618
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-26618
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=748928&view=results)
> Patch `erlang` for CVE-2025-26618 [High]

- SPECS/keda/CVE-2025-27144.patch
- SPECS/keda/keda.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749104&view=results)
> Patch `keda` for CVE-2025-27144 [Medium]

- SPECS/cert-manager/CVE-2025-27144.patch
- SPECS/cert-manager/cert-manager.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749190&view=results)
> Patch `cert-manager` for CVE-2025-27144 [Medium]

- SPECS/packer/CVE-2025-27144.patch
- SPECS/packer/packer.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749261&view=results)
> Patch `packer` for CVE-2025-27144 [Medium]

- SPECS/kube-vip-cloud-provider/CVE-2025-27144.patch
- SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749283&view=results)
> Patch `kube-vip-cloud-provider` for CVE-2025-27144 [Medium]

- SPECS-EXTENDED/python-soupsieve/python-soupsieve.signatures.json
- SPECS-EXTENDED/python-soupsieve/python-soupsieve.spec
- cgmanifest.json
---
- SPECS-EXTENDED/python-soupsieve/python-soupsieve.signatures.json
- SPECS-EXTENDED/python-soupsieve/python-soupsieve.spec
**NO**
- #xxxx
> Upgarde: python-soupsieve to version 2.6

- SPECS-EXTENDED/python-isort/python-isort.signatures.json
- SPECS-EXTENDED/python-isort/python-isort.spec
- cgmanifest.json
---
**python-isort: upgrade version to 5.13.2**
- modified: SPECS-EXTENDED/python-isort/python-isort.spec
- modified: SPECS-EXTENDED/python-isort/python-isort.signatures.json
**NO**
- #xxxx
> python-isort: Upgrade Version from 4.3.21 -> 5.13.2

- SPECS-EXTENDED/python-openstackdocstheme/0001-Remove-all-Google-Analytics-tracking.patch
- SPECS-EXTENDED/python-openstackdocstheme/python-openstackdocstheme.signatures.json
- SPECS-EXTENDED/python-openstackdocstheme/python-openstackdocstheme.spec
- cgmanifest.json
---
Upgrade: python-openstackdocstheme version to 3.0.0
- SPECS-EXTENDED/python-openstackdocstheme/0001-Remove-all-Google-Analytics-tracking.patch
- SPECS-EXTENDED/python-openstackdocstheme/python-openstackdocstheme.signatures.json
- SPECS-EXTENDED/python-openstackdocstheme/python-openstackdocstheme.spec
**NO**
- #xxxx
> Upgrade: python-openstackdocstheme version to 3.0.0

- SPECS-EXTENDED/python-testscenarios/python-testscenarios.signatures.json
- SPECS-EXTENDED/python-testscenarios/python-testscenarios.spec
- cgmanifest.json
---
python testscenarios: fixed build
Please build following packages:
python-testtools : https://github.com/microsoft/azurelinux/pull/12565
-python-testscenarios.spec
**YES/NO**
- #xxxx
> python-testscenarios: fixed build

- SPECS-EXTENDED/uriparser/uriparser-inet-ntop.patch
- SPECS-EXTENDED/uriparser/uriparser.signatures.json
- SPECS-EXTENDED/uriparser/uriparser.spec
- cgmanifest.json
---
This PR is to upgrade the package uriparser to version 0.9.8
- SPECS-EXTENDED/uriparser/uriparser-inet-ntop.patch
- SPECS-EXTENDED/uriparser/uriparser.signatures.json
- SPECS-EXTENDED/uriparser/uriparser.spec
**NO**
- #xxxx
- Local Build
> Upgrade: uriparser to version 0.9.8

- SPECS-EXTENDED/python-tornado/3374.patch
- SPECS-EXTENDED/python-tornado/Do-not-turn-DeprecationWarning-into-Exception.patch
- SPECS-EXTENDED/python-tornado/python-tornado-Python-3.12.patch
- SPECS-EXTENDED/python-tornado/python-tornado.signatures.json
- SPECS-EXTENDED/python-tornado/python-tornado.spec
- cgmanifest.json
---
This PR is to upgrade the package python-tornado to version 6.3.3
- SPECS-EXTENDED/python-tornado/3374.patch
- SPECS-EXTENDED/python-tornado/Do-not-turn-DeprecationWarning-into-Exception.patch
- SPECS-EXTENDED/python-tornado/python-tornado-Python-3.12.patch
- SPECS-EXTENDED/python-tornado/python-tornado.signatures.json
- SPECS-EXTENDED/python-tornado/python-tornado.spec
**NO**
- #xxxx
- Local Build
> Upgrade: python-tornado to version 6.3.3

- SPECS-EXTENDED/python-humanize/python-humanize.signatures.json
- SPECS-EXTENDED/python-humanize/python-humanize.spec
- cgmanifest.json
---
Upgrade `python-humanize` to version `4.11.0`
- Upgrade to current upstream
**NO**
- Local build.
> Upgrade python-humanize to version 4.11.0

- SPECS-EXTENDED/uthash/uthash.signatures.json
- SPECS-EXTENDED/uthash/uthash.spec
- cgmanifest.json
---
uthash: update to 2.3.0
- ../SPECS-EXTENDED/uthash/uthash.signatures.json
- ../SPECS-EXTENDED/uthash/uthash.spec
- ../cgmanifest.json
[uthash-2.3.0-9.azl3.src.rpm.log](https://github.com/user-attachments/files/18489810/uthash-2.3.0-9.azl3.src.rpm.log)
**NO**
- #xxxx
> uthash: update to 2.3.0

- SPECS-EXTENDED/python-testpath/python-testpath.signatures.json
- SPECS-EXTENDED/python-testpath/python-testpath.spec
- cgmanifest.json
---
Upgrades python-testpath to version 0.6.0
- modified:   SPECS-EXTENDED/python-testpath/python-testpath.signatures.json
- modified:   SPECS-EXTENDED/python-testpath/python-testpath.spec
**NO**
- NA
- NA
- local build
> Upgrades python-testpath to version 0.6.0

- SPECS-EXTENDED/tn5250/tn5250.signatures.json
- SPECS-EXTENDED/tn5250/tn5250.spec
- cgmanifest.json
---
Upgrade: tn5250 version to 0.17.6
Please build following package with tn5250:
xterm
- Depends on #11892 
libutempter
- Depends  on #11116 
- SPECS-EXTENDED/tn5250/tn5250.signatures.json
- SPECS-EXTENDED/tn5250/tn5250.spec
**NO**
- #xxxx
> Upgrade: tn5250 version to 0.17.6

- SPECS-EXTENDED/uchardet/uchardet.signatures.json
- SPECS-EXTENDED/uchardet/uchardet.spec
- cgmanifest.json
---
Upgrade: uchardet version to 0.0.8
- SPECS-EXTENDED/uchardet/uchardet.signatures.json
- SPECS-EXTENDED/uchardet/uchardet.spec
**NO**
- #xxxx
> Upgrade: uchardet version to 0.0.8

- SPECS-EXTENDED/twolame/twolame.signatures.json
- SPECS-EXTENDED/twolame/twolame.spec
- cgmanifest.json
---
Upgrade: twolame version to 0.4.0
- SPECS-EXTENDED/twolame/twolame.signatures.json
- SPECS-EXTENDED/twolame/twolame.spec
**NO**
- #xxxx
> Upgrade: twolame version to 0.4.0

- SPECS-EXTENDED/tss2/tss2.signatures.json
- SPECS-EXTENDED/tss2/tss2.spec
- cgmanifest.json
---
Upgrade: tss2 version to 2.3.2
- SPECS-EXTENDED/tss2/tss2.signatures.json
- SPECS-EXTENDED/tss2/tss2.spec
- 
**NO**
- #xxxx
> Upgrade: tss2 version to 2.3.2

- SPECS-EXTENDED/sip/sip-4.18-no_rpath.patch
- SPECS-EXTENDED/sip/sip-4.18-no_strip.patch
- SPECS-EXTENDED/sip/sip-4.19.18-no_hardcode_sip_so.patch
- SPECS-EXTENDED/sip/sip-4.19.25-py_ssize_t_clean.patch
- SPECS-EXTENDED/sip/sip-4.19.25-pyframe_getback.patch
- SPECS-EXTENDED/sip/sip.signatures.json
- SPECS-EXTENDED/sip/sip.spec
- cgmanifest.json
---
Upgrade: sip version 4.19.25
SPECS-EXTENDED/sip/sip-4.18-no_rpath.patch
SPECS-EXTENDED/sip/sip-4.18-no_strip.patch
SPECS-EXTENDED/sip/sip-4.19.18-no_hardcode_sip_so.patch
SPECS-EXTENDED/sip/sip.signatures.json
SPECS-EXTENDED/sip/sip.spec
SPECS-EXTENDED/sip/sip-4.19.25-py_ssize_t_clean.patch
SPECS-EXTENDED/sip/sip-4.19.25-pyframe_getback.patch
- Change
- Change
- Change
**NO**
- #xxxx
> Upgrade: sip version 4.19.25

- SPECS-EXTENDED/procmail/procmail-3.24-coverity-scan-fixes.patch
- SPECS-EXTENDED/procmail/procmail-3.24-gcc-14-fix.patch
- SPECS-EXTENDED/procmail/procmail-3.24-ipv6.patch
- SPECS-EXTENDED/procmail/procmail-3.24-rhconfig.patch
- SPECS-EXTENDED/procmail/procmail.signatures.json
- SPECS-EXTENDED/procmail/procmail.spec
- cgmanifest.json
---
This PR is to upgrade the package procmail to version 3.24
- SPECS-EXTENDED/procmail/procmail-3.24-coverity-scan-fixes.patch
- SPECS-EXTENDED/procmail/procmail-3.24-gcc-14-fix.patch
- SPECS-EXTENDED/procmail/procmail-3.24-ipv6.patch
- SPECS-EXTENDED/procmail/procmail-3.24-rhconfig.patch
- SPECS-EXTENDED/procmail/procmail.signatures.json
- SPECS-EXTENDED/procmail/procmail.spec
**NO**
- #xxxx
- Local Build
> Upgrade: procmail to version 3.24

- SPECS-EXTENDED/perl-Test-Manifest/perl-Test-Manifest.signatures.json
- SPECS-EXTENDED/perl-Test-Manifest/perl-Test-Manifest.spec
- cgmanifest.json
---
**perl-Test-Manifest: update version to 2.024**
- modified: SPECS-EXTENDED/perl-Test-Manifest/perl-Test-Manifest.spec
- modified: SPECS-EXTENDED/perl-Test-Manifest/perl-Test-Manifest.signatures.json
**NO**
- #xxxx
> perl-Test-Manifest: Update Version from 2.021 -> 2.024

- SPECS-EXTENDED/perl-Mail-IMAPTalk/perl-Mail-IMAPTalk.signatures.json
- SPECS-EXTENDED/perl-Mail-IMAPTalk/perl-Mail-IMAPTalk.spec
- cgmanifest.json
---
**perl-Mail-IMAPTalk: upgrade version to 4.06**
Please build the following packages along with perl-Mail-IMAPTalk:
**perl-GSSAPI perl-Authen-SASL perl-Encode-IMAPUTF7**
- modified: SPECS-EXTENDED/perl-Mail-IMAPTalk/perl-Mail-IMAPTalk.spec
- modified: SPECS-EXTENDED/perl-Mail-IMAPTalk/perl-Mail-IMAPTalk.signatures.json
**NO**
- #xxxx
> perl-Mail-IMAPTalk: Upgrade Version from 4.04 -> 4.06

- SPECS-EXTENDED/perl-PAR-Dist/perl-PAR-Dist.signatures.json
- SPECS-EXTENDED/perl-PAR-Dist/perl-PAR-Dist.spec
- cgmanifest.json
---
**perl-PAR-Dist: update version to 0.53**
- modified: SPECS-EXTENDED/perl-PAR-Dist/perl-PAR-Dist.spec
- modified: SPECS-EXTENDED/perl-PAR-Dist/perl-PAR-Dist.signatures.json
**NO**
- #xxxx
> perl-PAR-Dist: Update Version from 0.51 -> 0.53

- SPECS-EXTENDED/perl-Object-HashBase/perl-Object-HashBase.signatures.json
- SPECS-EXTENDED/perl-Object-HashBase/perl-Object-HashBase.spec
- cgmanifest.json
---
**perl-Object-HashBase: update version to 0.013**
- modified: SPECS-EXTENDED/perl-Object-HashBase/perl-Object-HashBase.spec
- modified: SPECS-EXTENDED/perl-Object-HashBase/perl-Object-HashBase.signatures.json
**NO**
- #xxxx
> perl-Object-HashBase: Update Version from 0.009 -> 0.013

- SPECS-EXTENDED/perl-Devel-Size/perl-Devel-Size.signatures.json
- SPECS-EXTENDED/perl-Devel-Size/perl-Devel-Size.spec
- cgmanifest.json
---
Update `perl-Devel-Size` to `0.84`
- Version bump
**NO**
- Local build.
> Update perl-Devel-Size to version 0.84

- SPECS-EXTENDED/perl-Parallel-Iterator/perl-Parallel-Iterator.signatures.json
- SPECS-EXTENDED/perl-Parallel-Iterator/perl-Parallel-Iterator.spec
- cgmanifest.json
---
**perl-Parallel-Iterator: update version to 1.002**
- modified: SPECS-EXTENDED/perl-Parallel-Iterator/perl-Parallel-Iterator.spec
- modified: SPECS-EXTENDED/perl-Parallel-Iterator/perl-Parallel-Iterator.signatures.json
NO
- #xxxx
> perl-Parallel-Iterator: Update Version from 1.00 -> 1.002

- SPECS-EXTENDED/perl-Mozilla-CA/Mozilla-CA-20240730-Redirect-to-ca-certificates-bundle.patch
- SPECS-EXTENDED/perl-Mozilla-CA/perl-Mozilla-CA.signatures.json
- SPECS-EXTENDED/perl-Mozilla-CA/perl-Mozilla-CA.spec
- cgmanifest.json
---
**perl-Mozilla-CA: update version to 20240730**
- deleted:   SPECS-EXTENDED/perl-Mozilla-CA/Mozilla-CA-20200520-Redirect-to-ca-certificates-bundle.patch
- added:     SPECS-EXTENDED/perl-Mozilla-CA/Mozilla-CA-20240730-Redirect-to-ca-certificates-bundle.patch
- modified: SPECS-EXTENDED/perl-Mozilla-CA/perl-Mozilla-CA.spec
- modified: SPECS-EXTENDED/perl-Mozilla-CA/perl-Mozilla-CA.signatures.json
NO
- #xxxx
> perl-Mozilla-CA: Update Version from 20200520 -> 20240730

- SPECS-EXTENDED/perl-Net-Daemon/perl-Net-Daemon.signatures.json
- SPECS-EXTENDED/perl-Net-Daemon/perl-Net-Daemon.spec
- cgmanifest.json
---
**perl-Net-Daemon: update version to 0.49**
- modified: SPECS-EXTENDED/perl-Net-Daemon/perl-Net-Daemon.spec
- modified: SPECS-EXTENDED/perl-Net-Daemon/perl-Net-Daemon.signatures.json
NO
- #xxxx
> perl-Net-Daemon: Update Version from 0.48 -> 0.49

- SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.signatures.json
- SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.spec
- cgmanifest.json
---
**perl-MRO-Compat: update version to 0.15**
- modified: SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.spec
- modified: SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.signatures.json
**NO**
- #xxxx
> perl-MRO-Compat: Update Version from 0.13 -> 0.15

- SPECS-EXTENDED/perl-Math-Int64/perl-Math-Int64.signatures.json
- SPECS-EXTENDED/perl-Math-Int64/perl-Math-Int64.spec
- cgmanifest.json
---
**perl-Math-Int64: update version to 0.57**
- modified: SPECS-EXTENDED/perl-Math-Int64/perl-Math-Int64.spec
- modified: SPECS-EXTENDED/perl-Math-Int64/perl-Math-Int64.signatures.json
NO
- #xxxx
> perl-Math-Int64: Update Version from 0.54 -> 0.57

- SPECS-EXTENDED/perl-Net-LibIDN2/perl-Net-LibIDN2.signatures.json
- SPECS-EXTENDED/perl-Net-LibIDN2/perl-Net-LibIDN2.spec
- cgmanifest.json
---
perl-Net-LibIDN2: Upgrade to 1.02
- SPECS-EXTENDED/perl-Net-LibIDN2/perl-Net-LibIDN2.signatures.json
- SPECS-EXTENDED/perl-Net-LibIDN2/perl-Net-LibIDN2.spec
- 
**NO**
- #xxxx
> perl-Net-LibIDN2: Upgrade to 1.02

- SPECS-EXTENDED/perl-ColorThemeBase-Static/perl-ColorThemeBase-Static.signatures.json
- SPECS-EXTENDED/perl-ColorThemeBase-Static/perl-ColorThemeBase-Static.spec
- cgmanifest.json
---
Update to latest upstream
**NO**
- Local build.
> Update perl-ColorThemeBase-Static to version 0.009

- SPECS-EXTENDED/perl-Color-ANSI-Util/perl-Color-ANSI-Util.signatures.json
- SPECS-EXTENDED/perl-Color-ANSI-Util/perl-Color-ANSI-Util.spec
- cgmanifest.json
---
Updates `perl-Color-ANSI-Util` to current upstream
**NO**
- Local build
> Update perl-Color-ANSI-Util to 0.165

- SPECS-EXTENDED/libvarlink/libvarlink.signatures.json
- SPECS-EXTENDED/libvarlink/libvarlink.spec
- cgmanifest.json
---
**libvarlink: update version to 23**
- modified: SPECS-EXTENDED/libvarlink/libvarlink.spec
- modified: SPECS-EXTENDED/libvarlink/libvarlink.signatures.json
**NO**
- #xxxx
> libvarlink: Update Version from 18 -> 23

- SPECS-EXTENDED/librabbitmq/librabbitmq.signatures.json
- SPECS-EXTENDED/librabbitmq/librabbitmq.spec
- cgmanifest.json
---
The PR is to upgrade the librabbitmq package to version 0.14.0
- SPECS-EXTENDED/librabbitmq/librabbitmq.signatures.json
- SPECS-EXTENDED/librabbitmq/librabbitmq.spec
**NO**
- #xxxx
> Upgrade: librabbitmq version to 0.14.0

- SPECS-EXTENDED/intel-cmt-cat/0001-alter-install-paths.patch
- SPECS-EXTENDED/intel-cmt-cat/0002-remove-build-and-install-of-examples.patch
- SPECS-EXTENDED/intel-cmt-cat/0003-allow-debian-flags-to-be-added.patch
- SPECS-EXTENDED/intel-cmt-cat/intel-cmt-cat.signatures.json
- SPECS-EXTENDED/intel-cmt-cat/intel-cmt-cat.spec
- cgmanifest.json
---
The PR is to upgrade the intel-cmt-cat package to version 24.05
- SPECS-EXTENDED/intel-cmt-cat/0001-alter-install-paths.patch
- SPECS-EXTENDED/intel-cmt-cat/0002-remove-build-and-install-of-examples.patch
- SPECS-EXTENDED/intel-cmt-cat/0003-allow-debian-flags-to-be-added.patch
- SPECS-EXTENDED/intel-cmt-cat/intel-cmt-cat.signatures.json
- SPECS-EXTENDED/intel-cmt-cat/intel-cmt-cat.spec
**NO**
- #xxxx
> Upgrade: intel-cmt-cat version to 24.05

- SPECS-EXTENDED/libpinyin/libpinyin.signatures.json
- SPECS-EXTENDED/libpinyin/libpinyin.spec
- cgmanifest.json
---
The PR is to upgrade the libpinyin package to version 2.9.92
- SPECS-EXTENDED/libpinyin/libpinyin-2.8.x-head.patch
- SPECS-EXTENDED/libpinyin/libpinyin.signatures.json
- SPECS-EXTENDED/libpinyin/libpinyin.spec
**NO**
- #xxxx
> Upgrade: libpinyin version to 2.9.92

- SPECS-EXTENDED/efi-rpm-macros/0001-Don-t-have-arm-as-an-alt-arch-of-aarch64.patch
- SPECS-EXTENDED/efi-rpm-macros/0002-Makefile-fix-permission-on-boot-efi-EFI.patch
- SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.signatures.json
- SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.spec
- cgmanifest.json
---
The PR is to upgrade the efi-rpm-macros package to version 5
- SPECS-EXTENDED/efi-rpm-macros/0001-Don-t-have-arm-as-an-alt-arch-of-aarch64.patch
- SPECS-EXTENDED/efi-rpm-macros/0002-Makefile-fix-permission-on-boot-efi-EFI.patch
- SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.signatures.json
- SPECS-EXTENDED/efi-rpm-macros/efi-rpm-macros.spec
**NO**
- #xxxx
> Upgrade: efi-rpm-macros version to 5

- SPECS-EXTENDED/libplist/libplist.signatures.json
- SPECS-EXTENDED/libplist/libplist.spec
- cgmanifest.json
---
Upgrade `libplist` to current upstream (2.6.0)
- Only affects other `libimobiledevice` packages, required as a build dependency for their upgrades.
**NO**
- Local build
> Upgrade libplist to 2.6.0

- SPECS-EXTENDED/exiv2/exiv2.signatures.json
- SPECS-EXTENDED/exiv2/exiv2.spec
- cgmanifest.json
---
exiv2: Update to version 0.28.3
-SPECS-EXTENDED/exiv2/exiv2.signatures.json
-SPECS-EXTENDED/exiv2/exiv2.spec
**NO**
- #xxxx
> exiv2: Update to version 0.28.3

- SPECS-EXTENDED/gssntlmssp/gssntlmssp.signatures.json
- SPECS-EXTENDED/gssntlmssp/gssntlmssp.spec
- cgmanifest.json
---
Upgrade gssntlmssp to 1.3.1 for azl 3.0
- Upgrade gssntlmssp to 1.3.1 for azl 3.0
- Switch from fedorahosted source to github, as fedorahosted has been decomissioned.
- Verified license
**NO**
- Local build
> Upgrade gssntlmssp to 1.3.1-1

- SPECS-EXTENDED/gssdp/gssdp.signatures.json
- SPECS-EXTENDED/gssdp/gssdp.spec
- cgmanifest.json
---
Upgrade `gssdp` to current upstream
- Upgrade `gssdp` to current upstream
- Verified license
**NO**
- Local build
> Upgrade gssdp to 1.6.3

- SPECS-EXTENDED/dotconf/dotconf.signatures.json
- SPECS-EXTENDED/dotconf/dotconf.spec
- cgmanifest.json
---
The PR is to upgrade the dotconf package to version 1.4.1
- SPECS-EXTENDED/dotconf/dotconf.signatures.json
- SPECS-EXTENDED/dotconf/dotconf.spec
**NO**
- #xxxx
> Upgrade: dotconf version to 1.4.1

- SPECS-EXTENDED/advancecomp/advancecomp.signatures.json
- SPECS-EXTENDED/advancecomp/advancecomp.spec
- cgmanifest.json
---
advancecomp: Upgraded to 2.6 version
- Depends on libdeflate pkgconfig(libdeflate)-V1.19 zopfli-devel
- SPECS-EXTENDED/advancecomp/advancecomp.signatures.json
- SPECS-EXTENDED/advancecomp/advancecomp.spec
- 
**NO**
- #xxxx
> advancecomp: Upgraded to 2.6 version

- SPECS/blobfuse2/CVE-2025-22868.patch
- SPECS/blobfuse2/blobfuse2.spec
---
- Address CVE-2025-22868
- CVE-2025-22868
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22868
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=751775&view=results)
> Patch `blobfuse2` for CVE-2025-22868 [High]

- SPECS/node-problem-detector/CVE-2025-22868.patch
- SPECS/node-problem-detector/node-problem-detector.spec
---
- Address CVE-2025-22868
- CVE-2025-22868
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22868
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=751783&view=results)
> Patch `node-problem-detector` for CVE-2025-22868 [High]

- SPECS/coredns/CVE-2025-22868.patch
- SPECS/coredns/coredns.spec
---
- Address CVE-2025-22868
- CVE-2025-22868
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22868
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=751786&view=results)
> Patch `coredns` for CVE-2025-22868 [High]

- SPECS/local-path-provisioner/CVE-2023-44487.patch
- SPECS/local-path-provisioner/local-path-provisioner.spec
---
Patch CVE-2023-44487
- Patch CVE-2023-44487
**NO**
- #xxxx
- Pipeline build id: [753311](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=753311&view=results)
> Fix CVE-2023-44487 in local-path-provisioner

- SPECS/prometheus/CVE-2023-44487.patch
- SPECS/prometheus/prometheus.spec
---
Fix CVE-2023-44487
- Fix CVE-2023-44487
**NO**
- #xxxx
- Pipeline build id: [753421](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=753421&view=results)
> Fix CVE-2023-44487 for prometheus

- SPECS-EXTENDED/libpfm/libpfm.signatures.json
- SPECS-EXTENDED/libpfm/libpfm.spec
- SPECS-EXTENDED/pcp/pcp-gcc15.patch
- SPECS-EXTENDED/pcp/pcp-xsos-fixes.patch
- SPECS-EXTENDED/pcp/pcp.signatures.json
- SPECS-EXTENDED/pcp/pcp.spec
- cgmanifest.json
- toolkit/scripts/toolchain/download_toolchain_rpm.sh
---
Work item 56110140 - PCP request from linkedin
- pcp
- libpfm
**NO**
- 56110140 
- Since pcp have lot of package dependencies, I have used full extended build pipeline to build and test it.
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=753781&view=results
> Upgrade pcp to 6.3.2 and libpfm to 4.13.0

- SPECS-EXTENDED/jbigkit/jbigkit-2.1-shlib.patch
- SPECS-EXTENDED/jbigkit/jbigkit-ldflags.patch
- SPECS-EXTENDED/jbigkit/jbigkit.spec
---
jbigkit :fixed build
- jbigkit.spec
**NO**
- #xxxx
> jbigkit :fixed build

- SPECS-EXTENDED/python-semantic_version/python-semantic_version.signatures.json
- SPECS-EXTENDED/python-semantic_version/python-semantic_version.spec
- cgmanifest.json
---
This PR is to upgrade the package python-semantic_version to version 2.10.0
- SPECS-EXTENDED/python-semantic_version/python-semantic_version.signatures.json
- SPECS-EXTENDED/python-semantic_version/python-semantic_version.spec
**NO**
- #xxxx
- Local Build
> Upgrade: python-semantic_version to version 2.10.0

- SPECS-EXTENDED/perl-YAML-Syck/perl-YAML-Syck.signatures.json
- SPECS-EXTENDED/perl-YAML-Syck/perl-YAML-Syck.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-YAML-Syck version to 1.34
- SPECS-EXTENDED/perl-YAML-Syck/perl-YAML-Syck.signatures.json
- SPECS-EXTENDED/perl-YAML-Syck/perl-YAML-Syck.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-YAML-Syck version to 1.34

- SPECS-EXTENDED/perl-Tree-DAG_Node/perl-Tree-DAG_Node.signatures.json
- SPECS-EXTENDED/perl-Tree-DAG_Node/perl-Tree-DAG_Node.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Tree-DAG_Node version to 1.32
- SPECS-EXTENDED/perl-Tree-DAG_Node/perl-Tree-DAG_Node.signatures.json
- SPECS-EXTENDED/perl-Tree-DAG_Node/perl-Tree-DAG_Node.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Tree-DAG_Node version to 1.32

- SPECS-EXTENDED/perl-Test-Warn/perl-Test-Warn.signatures.json
- SPECS-EXTENDED/perl-Test-Warn/perl-Test-Warn.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Test-Warn version to 0.37
- SPECS-EXTENDED/perl-Test-Warn/perl-Test-Warn.signatures.json
- SPECS-EXTENDED/perl-Test-Warn/perl-Test-Warn.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Test-Warn version to 0.37

- SPECS-EXTENDED/perl-Term-UI/perl-Term-UI.signatures.json
- SPECS-EXTENDED/perl-Term-UI/perl-Term-UI.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Term-UI version to 0.50
- SPECS-EXTENDED/perl-Term-UI/perl-Term-UI.signatures.json
- SPECS-EXTENDED/perl-Term-UI/perl-Term-UI.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Term-UI version to 0.50

- SPECS-EXTENDED/perl-Pod-Markdown/perl-Pod-Markdown.signatures.json
- SPECS-EXTENDED/perl-Pod-Markdown/perl-Pod-Markdown.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Pod-Markdown version to 3.400
- SPECS-EXTENDED/perl-Pod-Markdown/perl-Pod-Markdown.signatures.json
- SPECS-EXTENDED/perl-Pod-Markdown/perl-Pod-Markdown.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Pod-Markdown version to 3.400

- SPECS-EXTENDED/perl-PerlIO-utf8_strict/perl-PerlIO-utf8_strict.signatures.json
- SPECS-EXTENDED/perl-PerlIO-utf8_strict/perl-PerlIO-utf8_strict.spec
- cgmanifest.json
---
This PR is to upgrade package perl-PerlIO-utf8_strict version to 0.010
- SPECS-EXTENDED/perl-PerlIO-utf8_strict/perl-PerlIO-utf8_strict.signatures.json
- SPECS-EXTENDED/perl-PerlIO-utf8_strict/perl-PerlIO-utf8_strict.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-PerlIO-utf8_strict version to 0.010

- SPECS-EXTENDED/perl-File-Slurper/perl-File-Slurper.signatures.json
- SPECS-EXTENDED/perl-File-Slurper/perl-File-Slurper.spec
- cgmanifest.json
---
This PR is to upgrafe the package perl-File-Slurper version to 0.014
- SPECS-EXTENDED/perl-File-Slurper/perl-File-Slurper.signatures.json
- SPECS-EXTENDED/perl-File-Slurper/perl-File-Slurper.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-File-Slurper version to 0.014

- SPECS-EXTENDED/python-sniffio/python-sniffio.signatures.json
- SPECS-EXTENDED/python-sniffio/python-sniffio.spec
- cgmanifest.json
---
Upgrade: python-sniffio version to 1.3.1
- modified:   SPECS-EXTENDED/python-sniffio/python-sniffio.signatures.json
- modified:   SPECS-EXTENDED/python-sniffio/python-sniffio.spec
**NO**
- #xxxx
> Upgrade: python-sniffio version to 1.3.1

- SPECS-EXTENDED/targetcli/targetcli.signatures.json
- SPECS-EXTENDED/targetcli/targetcli.spec
- cgmanifest.json
---
Upgrade: targetcli version to 2.1.58
Please build following package with targetcli :
python-rtslib
- Depends on #11700 
python-kmod
- Depends on #11636 
python-configshell
- Depends on #11672 
- SPECS-EXTENDED/targetcli/targetcli.signatures.json
- SPECS-EXTENDED/targetcli/targetcli.spec
**NO**
- #xxxx
> Upgrade: targetcli version to 2.1.58

- SPECS-EXTENDED/perl-SNMP_Session/SNMP_Session-1.13-fix_ivp6.patch
- SPECS-EXTENDED/perl-SNMP_Session/perl-SNMP_Session.signatures.json
- SPECS-EXTENDED/perl-SNMP_Session/perl-SNMP_Session.spec
- cgmanifest.json
---
**perl-SNMP_Session: update version to 1.16**
- new file: SPECS-EXTENDED/perl-SNMP_Session/SNMP_Session-1.13-fix_ivp6.patch
- modified: SPECS-EXTENDED/perl-SNMP_Session/perl-SNMP_Session.spec
- modified: SPECS-EXTENDED/perl-SNMP_Session/perl-SNMP_Session.signatures.json
**NO**
- #xxxx
> perl-SNMP_Session: Update Version from 1.13 -> 1.16

- SPECS-EXTENDED/perltidy/perltidy.signatures.json
- SPECS-EXTENDED/perltidy/perltidy.spec
- cgmanifest.json
---
This PR is to Upgrade the package perltidy to version 20240903
- SPECS-EXTENDED/perltidy/perltidy.signatures.json
- SPECS-EXTENDED/perltidy/perltidy.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perltidy to version 20240903

- SPECS-EXTENDED/perl-Scope-Upper/perl-Scope-Upper.signatures.json
- SPECS-EXTENDED/perl-Scope-Upper/perl-Scope-Upper.spec
- cgmanifest.json
- [x cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
---
**perl-Scope-Upper: update version to 0.34**
- modified: SPECS-EXTENDED/perl-Scope-Upper/perl-Scope-Upper.spec
- modified: SPECS-EXTENDED/perl-Scope-Upper/perl-Scope-Upper.signatures.json
**NO**
- #xxxx
> perl-Scope-Upper: Update Version from 0.32 -> 0.34

- SPECS-EXTENDED/perl-Module-Signature/perl-Module-Signature.signatures.json
- SPECS-EXTENDED/perl-Module-Signature/perl-Module-Signature.spec
- cgmanifest.json
---
perl-Module-Signature.: Upgrade to 0.89
-SPECS-EXTENDED/perl-Module-Signature/perl-Module-Signature.signatures.json
-SPECS-EXTENDED/perl-Module-Signature/perl-Module-Signature.spec
**NO**
- #xxxx
- Tried installation of squid package in mariner container. It installed succesfully.
> perl-Module-Signature: Upgrade  version to 0.89

- SPECS-EXTENDED/gsl/gsl.signatures.json
- SPECS-EXTENDED/gsl/gsl.spec
- cgmanifest.json
---
Upgrade gsl to current upstream
- Upgrade gsl to current upstream
- Verify License
**NO**
- Local build
> Upgrade gsl to 2.8-1

- SPECS-EXTENDED/bats/bats.signatures.json
- SPECS-EXTENDED/bats/bats.spec
- cgmanifest.json
---
Upgrade bats to `1.11.0-1`
Please build the following packages with bats:
parallel
- Verify License
- Bump Package version
**NO**
- Local build
> Upgrade bats to 1.11.0-1

- SPECS/rsyslog/issue5158.patch
- SPECS/rsyslog/rsyslog.spec
---
- Add patch to rsyslog
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/54823335
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=728031&view=results
> [3.0] rsyslog - add patch for issue #5158

- CONTRIBUTING.md
---
The contributing guide was missing 3.0 branches and included refrences to 1.0 branches which is deprecated. Therefore, update to include 3.0 and remove 1.0 development branches. 
- Update contributing guide to use 3.0 branches
**NO**
> Update contributing guide to use 3.0 branches

- SPECS-EXTENDED/v4l-utils/0002-libv4lconvert-Fix-v4lconvert_yuv420_to_rgb-bgr24-not.patch
- SPECS-EXTENDED/v4l-utils/0003-libv4lconvert-Fix-v4lconvert_rgb565_to_rgb-bgr24-not.patch
- SPECS-EXTENDED/v4l-utils/0004-libv4lconvert-Fix-v4lconvert_nv12_-not-taking-stride.patch
- SPECS-EXTENDED/v4l-utils/0005-libv4lconvert-Fix-v4lconvert_nv16_to_yuyv-not-taking.patch
- SPECS-EXTENDED/v4l-utils/v4l-utils.spec
---
v4l-utils: fixed build
-v4l-utils.spec
**NO**
- #xxxx
> v4l-utils: fixed build

- SPECS-EXTENDED/glassfish-annotation-api/glassfish-annotation-api-build.xml
- SPECS-EXTENDED/glassfish-annotation-api/glassfish-annotation-api.signatures.json
- SPECS-EXTENDED/glassfish-annotation-api/glassfish-annotation-api.spec
---
- glassfish-annotation-api: Build error fix
- Build error fix
**NO**
- #xxxx
> glassfish-annotation-api: Build error fix

- SPECS-EXTENDED/relaxngDatatype/relaxngDatatype.spec
---
- Fix the build error
- No
**NO**
- #xxxx
> relaxngDatatype: fix the build error

- SPECS/binutils/CVE-2025-1744.patch
- SPECS/binutils/binutils.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Patch for CVE-2025-1744
- Fix CVE-2025-1744
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1744
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=759561&view=results
> Patch binutils for CVE-2025-1744 [CRITICAL]

- SPECS/ceph/CVE-2025-1744.patch
- SPECS/ceph/ceph.spec
---
- Patch for CVE-2025-1744
- Fix CVE-2025-1744
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-1744
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=759302&view=results
- The install step is failing, and this issue is not related to the CVE. The failure can be verified from this build run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=759570&view=results
> Patch ceph for  CVE-2025-1744 [CRITICAL]

- SPECS/kubevirt/CVE-2025-22869.patch
- SPECS/kubevirt/kubevirt.spec
---
- Fixes CVE-2025-22869
**NO**
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=758526&view=results
> Fix CVE-2025-22869 for kubevirt [HIGH]

- SPECS/terraform/CVE-2025-22869.patch
- SPECS/terraform/terraform.spec
---
- Fixes CVE-2025-22869
**NO**
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=758541&view=results
> Fix CVE-2025-22869 for terraform [HIGH]

- SPECS/telegraf/CVE-2025-27144.patch
- SPECS/telegraf/telegraf.spec
---
Patch telegraf for CVE-2025-27144 [Medium].
- Fix CVE-2025-27144 with an upstream patch
**NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2025-27144
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749387&view=results
> Patch telegraf for CVE-2025-27144 [Medium].

- SPECS/wget/wget.spec
---
Add missing check section to wget as per https://microsoft.visualstudio.com/OS/_workitems/edit/53862582
- Add %check to wget.spec
**NO**
- Local build
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=744326&view=results
> Add %check section to wget

- CONTRIBUTING.md
This PR adds a single character to correctly link the user to the Pull Request Guidelines. 
This will make it a bit easier for new contributors to navigate the useful documentation early.
- Added an anchor tag to the Pull Request Guidelines link.
No
- fixes #12793
> Update Pull Request guidelines link to anchor

- SPECS-EXTENDED/perl-Config-Tiny/perl-Config-Tiny.signatures.json
- SPECS-EXTENDED/perl-Config-Tiny/perl-Config-Tiny.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Config-Tiny version to 2.30
- SPECS-EXTENDED/perl-Config-Tiny/perl-Config-Tiny.signatures.json
- SPECS-EXTENDED/perl-Config-Tiny/perl-Config-Tiny.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Config-Tiny version to 2.30

- SPECS-EXTENDED/python-urwid/python-urwid.signatures.json
- SPECS-EXTENDED/python-urwid/python-urwid.spec
- cgmanifest.json
---
Upgrade python-urwid version to 2.6.14
-python-urwid.signatures.json
-python-urwid.spec
**NO**
- #xxxx
> Upgrade python-urwid version to 2.6.14

- SPECS-EXTENDED/libdazzle/libdazzle.signatures.json
- SPECS-EXTENDED/libdazzle/libdazzle.spec
- cgmanifest.json
---
Upgrade: libdazzle version to 3.44.0
xorg-x11-drv-libinput xorg-x11-server
-SPECS-EXTENDED/libdazzle/libdazzle.signatures.json
-SPECS-EXTENDED/libdazzle/libdazzle.spec
**NO**
- #xxxx
> Upgrade: libdazzle version to 3.44.0

- SPECS-EXTENDED/libdc1394/libdc1394-sdl.patch
- SPECS-EXTENDED/libdc1394/libdc1394.signatures.json
- SPECS-EXTENDED/libdc1394/libdc1394.spec
- cgmanifest.json
---
Upgrade: libdc1394 version to 2.2.7
libraw1394
-SPECS-EXTENDED/libdc1394/libdc1394-sdl.patch
-SPECS-EXTENDED/libdc1394/libdc1394.signatures.json
-SPECS-EXTENDED/libdc1394/libdc1394.spec
**NO**
- #xxxx
-Verified on 3.0 container
> Upgrade: libdc1394 version to 2.2.7

- SPECS-EXTENDED/libsecret/libsecret.signatures.json
- SPECS-EXTENDED/libsecret/libsecret.spec
- cgmanifest.json
---
The PR is to upgrade the package libsecret to version 0.21.4
- SPECS-EXTENDED/libsecret/libsecret.signatures.json
- SPECS-EXTENDED/libsecret/libsecret.spec
**NO**
- #xxxx
- Local build
> Upgrade: libsecret version to 0.21.4

- SPECS-EXTENDED/ogdi/ogdi.signatures.json
- SPECS-EXTENDED/ogdi/ogdi.spec
- cgmanifest.json
---
ogdi: update to 4.1.1
../SPECS-EXTENDED/ogdi/ogdi.signatures.json
../SPECS-EXTENDED/ogdi/ogdi.spec
[ogdi-4.1.1-3.azl3.src.rpm.log](https://github.com/user-attachments/files/18319309/ogdi-4.1.1-3.azl3.src.rpm.log)
**NO**
- #xxxx
> ogdi: update to 4.1.1

- SPECS-EXTENDED/perl-Test-Inter/perl-Test-Inter.signatures.json
- SPECS-EXTENDED/perl-Test-Inter/perl-Test-Inter.spec
- cgmanifest.json
---
**perl-Test-Inter: update version to 1.11**
- modified: SPECS-EXTENDED/perl-Test-Inter/perl-Test-Inter.spec
- modified: SPECS-EXTENDED/perl-Test-Inter/perl-Test-Inter.signatures.json
**NO**
- #xxxx
> perl-Test-Inter: Update Version from 1.09 -> 1.11

- SPECS-EXTENDED/optipng/optipng.signatures.json
- SPECS-EXTENDED/optipng/optipng.spec
- cgmanifest.json
---
optipng: update to 0.7.8
../SPECS-EXTENDED/optipng/optipng.signatures.json
../SPECS-EXTENDED/optipng/optipng.spec
[optipng-0.7.8-5.azl3.src.rpm.log](https://github.com/user-attachments/files/18433021/optipng-0.7.8-5.azl3.src.rpm.log)
**NO**
- #xxxx
> optipng: update to 0.7.8

- SPECS/cloud-hypervisor/CVE-2025-1744.patch
- SPECS/cloud-hypervisor/cloud-hypervisor.spec
---
- Recreated patch for CVE-2025-1744 to address a bug introduced by the previous patch. This update includes both the CVE fix and the bug fix.
- Update to https://github.com/microsoft/azurelinux/pull/12794
- CVE-2025-1744
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-1744
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=759942&view=results)
> Recreated `cloud-hypervisor` patch for CVE-2025-1744 [Critical]

- SPECS/cmake/CVE-2023-35945.patch
- SPECS/cmake/CVE-2023-44487.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This PR re-patches CVE-2023-44487 and CVE-2023-35945 in cmake. The patch files for these two CVEs were inappropriately removed in a prior PR (#7642).
- Re-patch CVE-2023-44487
- Re-patch CVE-2023-35945
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-35945
- Pipeline build id: [756162](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=756162)
> Patch CVE-2023-44487 and CVE-2023-35945 in cmake

- toolkit/scripts/toolchain.mk
- toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
- toolkit/scripts/toolchain/download_toolchain_rpm.sh
---
Modify msopenjdk RPM download in toolchain to contain 3 retries, with a 10 second wait, and retry refused connections.
- Change toolchain msopenjdk download
**YES**
- https://microsoft.visualstudio.com/OS/_workitems/edit/56349003
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=754766&view=results
> [3.0] modify retries for msopenjdk download

- SPECS-EXTENDED/perl-File-Slurp/perl-File-Slurp.signatures.json
- SPECS-EXTENDED/perl-File-Slurp/perl-File-Slurp.spec
- cgmanifest.json
---
Update `perl-File-Slurp` to version `9999.32`
- Version bump
**NO**
- Local build.
> Update perl-File-Slurp to version 9999.32-1

- SPECS/moby-engine/CVE-2025-22868.patch
- SPECS/moby-engine/CVE-2025-22869.patch
- SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine for CVEs
- CVE-2025-22868
- CVE-2025-22869
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-22868
- https://nvd.nist.gov/vuln/detail/CVE-2025-22869
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=764964&view=results
> Patch moby-engine for CVE-2025-22868 and CVE-2025-22869 [Medium][High]

- SPECS/emacs/CVE-2024-53920.patch
- SPECS/emacs/emacs.spec
---
- Fix CVE-2024-53920 for emacs
- Add patch to resolve CVE-2024-53920
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-53920
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=765049&view=results
> [3.0] Resolve emacs CVE-2024-53920

- SPECS/emacs/CVE-2024-53920.patch
- SPECS/emacs/emacs.spec
---
- Fix CVE-2024-53920 for emacs
- Add patch to resolve cve-2024-53920
NO
- https://nvd.nist.gov/vuln/detail/CVE-2024-53920
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=765054&view=results
> [2.0] Resolve emacs CVE-2024-53920 [Critical]

- SPECS/ig/CVE-2025-27144.patch
- SPECS/ig/ig.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=762071&view=results)
> Patch `ig` for CVE-2025-27144 [Medium]

- SPECS/kata-containers-cc/CVE-2023-44487.patch
- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers/CVE-2023-44487.patch
- SPECS/kata-containers/kata-containers.spec
---
Manual backport of the fix for grpc for version 1.47.0. The upstream grpc CVE fix was only backported to 1.56.3.
- Add patch file to kata-containers and kata-containers-cc SPECs
**NO**
- N/A
- end-to-end via package builds, deployment in AKS, example internal package build ID: 761141
> kata-containers(-cc): Fix CVE-2023-44487

- SPECS/selinux-policy/0036-fstools-Add-additional-perms-for-cloud-utils-growpar.patch
- SPECS/selinux-policy/selinux-policy.spec
---
Misc. SELinux policy fixes for BVT and also cherry-picked fixes from upstream.
- Add tmpfs fix for cloud-utils-growpart.
**NO**
- Pipeline build id: 755378
> selinux-policy: Add cloud-utils-growpart tmpfs fix.

- SPECS/qemu/CVE-2023-5088.patch
- SPECS/qemu/CVE-2023-6683.patch
- SPECS/qemu/CVE-2023-6693.patch
- SPECS/qemu/qemu.spec
---
Patch `qemu` for assorted CVEs
- [Medium] Add patch for CVE-2023-6683
- [Medium] Add patch for CVE-2023-6693
- [High] Add patch for CVE-2023-5088
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-6683
- https://nvd.nist.gov/vuln/detail/CVE-2023-6693
- https://nvd.nist.gov/vuln/detail/CVE-2023-5088
- Local build
> [High] Patch qemu for CVE-2023-6683, CVE-2023-6693, CVE-2023-5088

- SPECS/pam/CVE-2024-10041.patch
- SPECS/pam/pam.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add patch to fix CVE-2024-10041
- CVE-2024-10041
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-10041
Buddy build passed in building and testing the package: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=688182&view=results (installing the package works but pipeline tries to install the lang,devel,debuginfo, packages separately which isn't needed)
> pam: Add patch to fix CVE-2024-10041

- toolkit/imageconfigs/core-efi-aarch64.json
---
Arm core vhd is not bootable in qemu, but non-arm vhd is.  The absence of the virt-guest-packages seems to be the issue.
- add virt-guest-packages.json to arm core image composition
**NO**
> ARM64 vhd: add virt-guest-packages

- SPECS/ig/CVE-2025-29786.patch
- SPECS/ig/ig.spec
---
Addresses [CVE-2025-29786](https://github.com/expr-lang/expr/pull/762)
- Added patch for CVE-2025-29786
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-29786
- Pipeline build id: [770804](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=770804&view=results)
> Patch ig for CVE-2025-29786 [HIGH]

- SPECS/coredns/CVE-2025-29786.patch
- SPECS/coredns/coredns.spec
---
Addresses [CVE-2025-29786](https://github.com/expr-lang/expr/pull/762)
- Added patch for CVE-2025-29786
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-29786
- Pipeline build id: [770803](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=770803&view=results)
> Patch coredns for CVE-2025-29786 [HIGH]

- SPECS/keda/CVE-2025-29786.patch
- SPECS/keda/keda.spec
---
Addresses [CVE-2025-29786](https://github.com/expr-lang/expr/pull/762)
- Added patch for CVE-2025-29786
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-29786
- Pipeline build id: [770785](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=770785&view=results)
> Patch keda for CVE-2025-29786 [HIGH]

- SPECS/qtbase/CVE-2025-30348.patch
- SPECS/qtbase/qtbase.spec
---
patch qtbase to fix CVE-2025-30348
- qtbase.spec
- 
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-30348
> [Medium] patch qtbase to fix CVE-2025-30348

- toolkit/docs/amd/amd.md
---
Add amdgpu installation instruction doc under toolkit/docs
- Add amdgpu installation instruction doc
NO
- Pipeline build id: 769750
> Add amdgpu installation instruction doc

- SPECS/coredns/CVE-2025-30204.patch
- SPECS/coredns/coredns.spec
---
Addresses [CVE-2025-30204](https://github.com/golang-jwt/jwt/commit/0951d184286dece21f73c85673fd308786ffe9c3)
- Added patch for CVE-2025-30204
**NO**
- #xxxx
- Pipeline build id: [775667](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775667&view=results)
> Patch coredns for CVE-2025-30204 [HIGH]

- SPECS/azcopy/CVE-2025-30204.patch
- SPECS/azcopy/azcopy.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=774400&view=results)
> Patch `azcopy` for CVE-2025-30204 [High]

- SPECS/cert-manager/CVE-2025-30204.patch
- SPECS/cert-manager/cert-manager.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=774423&view=results)
> Patch cert-manager for CVE-2025-30204 [High]

- SPECS/packer/CVE-2025-30204.patch
- SPECS/packer/packer.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=774979&view=results)
> Patch `packer` for CVE-2025-30204 [High]

- SPECS/coredns/CVE-2025-30204.patch
- SPECS/coredns/coredns.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=774994&view=results)
> Patch `coredns` for CVE-2025-30204 [High]

- SPECS/kubernetes/CVE-2025-30204.patch
- SPECS/kubernetes/kubernetes.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775009&view=results)
> Patch `kubernetes` for CVE-2025-30204 [High]

- SPECS/prometheus/CVE-2025-30204.patch
- SPECS/prometheus/prometheus.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775220&view=results)
> Patch `prometheus` for CVE-2025-30204 [High]

- SPECS/flannel/CVE-2025-30204.patch
- SPECS/flannel/flannel.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775238&view=results)
> Patch `flannel` for CVE-2025-30204 [High]

- SPECS/keda/CVE-2025-29923.patch
- SPECS/keda/CVE-2025-30204.patch
- SPECS/keda/keda.spec
---
- Address CVE-2025-30204, CVE-2025-29923
- CVE-2025-30204 [High]
- CVE-2025-29923 [Low]
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-29923
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775495&view=results)
> Patch `keda` for CVE-2025-30204, CVE-2025-29923 [High]

- SPECS/telegraf/CVE-2025-30204.patch
- SPECS/telegraf/telegraf.spec
---
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775683&view=results)
> Patch `telegraf` for CVE-2025-30204 [High]

- SPECS/pytorch/CVE-2021-22569.patch
- SPECS/pytorch/CVE-2024-7776.patch
- SPECS/pytorch/pytorch.spec
---
- Address CVE-2021-22569, CVE-2024-7776
- CVE-2024-7776
- CVE-2021-22569
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-7776
- https://nvd.nist.gov/vuln/detail/CVE-2021-22569
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775933&view=results)
> Patch `pytorch` for CVE-2021-22569, CVE-2024-7776 [High]

- SPECS/kata-containers-cc/kata-containers-cc.signatures.json
- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers/kata-containers.signatures.json
- SPECS/kata-containers/kata-containers.spec
- cgmanifest.json
---
Security-critical fixes
- Prevent hanging when ReadStreamRequest is blocked by policy
- Have the agent reformat CreateContainer requests in order to improve policy validation
- Fix for https://github.com/advisories/GHSA-qppj-fm5r-hxr3
**NO**
- N/A
- https://github.com/advisories/GHSA-qppj-fm5r-hxr3
- Pipeline build id: 776359, 774306
> kata(-cc): upgrade kata-containers(-cc) to 3.2.0.azl5

- SPECS-EXTENDED/perl-Importer/perl-Importer.signatures.json
- SPECS-EXTENDED/perl-Importer/perl-Importer.spec
- cgmanifest.json
---
Update to current upstream
- Version bump
**NO**
- Local build.
> Update perl-Importer to version 0.026

- SPECS/libsndfile/CVE-2024-50612.patch
- SPECS/libsndfile/libsndfile.spec
---
Patch CVE-2024-50612
- Patch CVE-2024-50612
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2024-50612
- Pipeline build id: [PR-11805](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=706689&view=results)
> libsndfile: patch CVE-2024-50612

- SPECS/augeas/CVE-2025-2588.patch
- SPECS/augeas/augeas.spec
---
Addresses [CVE-2025-2588](https://github.com/sailfishos-mirror/augeas/commit/af2aa88ab37fc48167d8c5e43b1770a4ba2ff403)
- Added patch for CVE-2025-2588
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-2588
- Pipeline build id: [775676](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=775676&view=results)
> Patch augeas for CVE-2025-2588 [MEDIUM]

- SPECS/erlang/CVE-2025-30211.patch
- SPECS/erlang/erlang.spec
---
Patch erlang to fix CVE-2025-30211 [High]
- CVE-2025-30211
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-30211
- Pipeline build id: [Buddy Build 779345](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=779345&view=results)
> Patch erlang for CVE-2025-30211 [High]

- SPECS/libarchive/CVE-2024-48615.patch
- SPECS/libarchive/libarchive.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Patch CVE-2024-48615
- Fix CVE-2024-48615
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-48615
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=781343&view=results
> Patch libarchive for CVE-2024-48615 [High]

- SPECS/cri-o/CVE-2025-21614.patch
- SPECS/cri-o/cri-o.spec
---
- Add patch to resolve CVE-2025-21614 for cri-o package
- Add patch for CVE-2025-21614
NO
- https://nvd.nist.gov/vuln/detail/CVE-2025-21614
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=781819&view=results
> [High][2.0] Resolve cri-o CVE-2025-21614

- SPECS/zsh/zsh.spec
---
Stop using egrep in the failing test case. instead using grep -E inside the test. 
- Change: Stop using egrep in the failing test case. instead using grep -E inside the test.
**YES/NO**
NO
- Pipeline build id: [782569](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782569&view=results)
> Fix ptest zsh

- SPECS/tar/tar-1.33-fix-capabilities-test.patch
- SPECS/tar/tar-1.35-add-forgotten-tests-from-upstream.patch
- SPECS/tar/tar.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
getcap output changed in the newer. This particular tar test case was expecting the older output.
- Change: Import patches to fix getcap issue. Also import a missing testcase.
**YES/NO**
YES
- Pipeline build id: [782589](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782589&view=results)
> Fix tar Ptest

- SPECS/python-jwt/python-jwt.spec
---
Tox is not installed properly.  %check crashes out saying tox is not found.
- Change: Added `--ignore-installed` to `pip3 install tox` in `SPECS/python-jwt/python-jwt.spec` 
**YES/NO**
NO 
NO
- Pipeline build id: [782606](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782606&view=results)
> fix python-jwt ptest

- SPECS/git-lfs/CVE-2025-22870.patch
- SPECS/git-lfs/git-lfs.spec
---
Patch git-lfs for CVE-2025-22870
- Patch git-lfs for CVE-2025-22870
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22870
- Github PR check
> Patch git-lfs for CVE-2025-22870 [Medium]

- SPECS/moby-containerd-cc/CVE-2025-27144.patch
- SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
Fix for CVE-2025-27144, similar to other containerd SPECS
- Fix for CVE-2025-27144
**NO**
- N/A
- Pipeline build id: 782548
> Patch moby-containerd-cc for CVE-2025-27144 [Medium]

- SPECS/jx/CVE-2024-51744.patch
- SPECS/jx/jx.spec
---
patch jx to fix CVE-2024-51744
- jx.spec
**YES/NO**
- #xxxx
> [Low]patch jx for CVE-2024-51744

- SPECS/cert-manager/CVE-2024-51744.patch
- SPECS/cert-manager/cert-manager.spec
---
patch cert-manager to fix CVE-2024-51744
- cert-manager.spec
**NO**
- #xxxx
> [Low] patch cert-manager for CVE-2024-51744

- SPECS/kube-vip-cloud-provider/CVE-2024-51744.patch
- SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
---
patch kube-vip-cloud-provider to fix CVE-2024-51744
- kube-vip-cloud-provider.spec
**NO**
- #xxxx
> [Low]patch kube-vip-cloud-provider for CVE-2024-51744

- SPECS/application-gateway-kubernetes-ingress/CVE-2024-51744.patch
- SPECS/application-gateway-kubernetes-ingress/application-gateway-kubernetes-ingress.spec
---
patch application-gateway-kubernetes-ingress to fix CVE-2024-51744
- application-gateway-kubernetes-ingress.spec
**NO**
- #xxxx
> [Low] patch application-gateway-kubernetes-ingress for CVE-2024-51744

- SPECS/kubernetes/CVE-2024-51744.patch
- SPECS/kubernetes/kubernetes.spec
---
kubernetes: Patch for CVE-2024-51744
- new file: **SPECS/kubernetes/CVE-2024-51744.patch**
- modified: **SPECS/kubernetes/kubernetes.spec**
**NO**
- #xxxx
> [Low] Patch kubernetes for CVE-2024-51744

- SPECS-EXTENDED/zziplib/zziplib.signatures.json
- SPECS-EXTENDED/zziplib/zziplib.spec
- cgmanifest.json
---
Upgrade zziplib to 0.13.74
- zziplib.signatures.json
- zziplib.spec
**NO**
- #xxxx
- Verified on 3.0-container
-
> Upgrade zziplib to 0.13.74

- SPECS-EXTENDED/powertop/powertop.signatures.json
- SPECS-EXTENDED/powertop/powertop.spec
- cgmanifest.json
---
This PR is to upgrade the package powertop to version 2.15
- SPECS-EXTENDED/powertop/powertop.signatures.json
- SPECS-EXTENDED/powertop/powertop.spec
**NO**
- #xxxx
- Local Build
> Upgrade: powertop to version 2.15

- SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.signatures.json
- SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.spec
- cgmanifest.json
---
Upgrade: perl-Archive-Extract version to 0.88
Please build following packages with perl-Archive-Extract:
lzip perl-Compress-Raw-Lzma  perl-Test-CPAN-Meta perl-Test-CPAN-Meta-JSON perl-IO-Compress-Lzma 
-  SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.signatures.json
-  SPECS-EXTENDED/perl-Archive-Extract/perl-Archive-Extract.spec
-  cgmanifest.json
**NO**
- #xxxx
>  Upgrade: perl-Archive-Extract version to 0.88

- SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.signatures.json
- SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.spec
- cgmanifest.json
---
Upgrade: perl-Date-Manip version to 6.95
perl-Test-Inter
- SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.signatures.json
- SPECS-EXTENDED/perl-Date-Manip/perl-Date-Manip.spec
**NO**
- #xxxx
- Installing & uninstalling Verified with 3.0 container
> Upgrade: perl-Date-Manip version to 6.95

- SPECS-EXTENDED/libgxps/libgxps.signatures.json
- SPECS-EXTENDED/libgxps/libgxps.spec
- cgmanifest.json
---
libgxps: update to 0.3.2
../SPECS-EXTENDED/libgxps/libgxps.signatures.json
../SPECS-EXTENDED/libgxps/libgxps.spec
[libgxps-0.3.2-10.azl3.src.rpm.log](https://github.com/user-attachments/files/17947687/libgxps-0.3.2-10.azl3.src.rpm.log)
**NO**
- #xxxx
> libgxps: update to 0.3.2

- SPECS-EXTENDED/liblqr-1/liblqr-1.signatures.json
- SPECS-EXTENDED/liblqr-1/liblqr-1.spec
- cgmanifest.json
---
Upgrade `liblqr-1` to 0.4.3
- Annotate GPLv3 use
**NO**
- Local build.
> Update liblqr-1 to 0.4.3

- SPECS-EXTENDED/libblockdev/libblockdev.signatures.json
- SPECS-EXTENDED/libblockdev/libblockdev.spec
- cgmanifest.json
---
libblockdev: Version update to 3.2.0
- libbytesize
- Depends on volume-key: **(https://github.com/microsoft/azurelinux/pull/10952)**
-SPECS-EXTENDED/libblockdev/libblockdev.signatures.json
-SPECS-EXTENDED/libblockdev/libblockdev.spec
**NO**
- #xxxx
- Verified on 3.0 container
> libblockdev: Version update to 3.2.0

- SPECS-EXTENDED/hyphen-it/hyphen-it.signatures.json
- SPECS-EXTENDED/hyphen-it/hyphen-it.spec
- cgmanifest.json
---
**hyphen-it: update version to 5.1.1**
Please build following packages with perl-Archive-Extract:
**hyphen**
- modified: SPECS-EXTENDED/hyphen-it/hyphen-it.spec
- modified: SPECS-EXTENDED/hyphen-it/hyphen-it.signatures.json
**NO**
- #xxxx
> hyphen-it: Update Version from 0.20071127 -> 5.1.1

- SPECS/skopeo/skopeo.spec
---
- Remove extraction command from build
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783894&view=results)
> [3.0] Fix Patch Application for `skopeo`

- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
---
- Removed extra extraction command from prep
- Change
- Change
- Change
**NO**
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783982&view=results)
> [3.0] Fix Patch Application for `nvidia-container-toolkit`

- SPECS/fluent-bit/CVE-2025-31498.patch
- SPECS/fluent-bit/fluent-bit.spec
---
Address CVE-2025-31498 in fluent-bit package
- Add patch for CVE-2025-31498
- Upstream reference: https://github.com/c-ares/c-ares/compare/69e1ad5..82489f2
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-31498
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=784667&view=results
> Patch `fluent-bit` for CVE-2025-31498 [High]

- SPECS/unzip/CVE-2021-4217.patch
- SPECS/unzip/unzip.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch unzip to fix CVE-2021-4217
- SPECS/unzip/CVE-2021-4217.patch
- SPECS/unzip/unzip.spec
**NO**
- #xxxx
> [LOW] Patch unzip to fix CVE-2021-4217

- SPECS/nfs-utils/nfs-utils.spec
- [* ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [* ] The toolchain/worker package manifests are up-to-date …
> Fix to include idmapd.conf and id_resolver.conf in nfs-utils for 3.0

- SPECS/libbpf/CVE-2025-29481.patch
- SPECS/libbpf/libbpf.spec
---
patch for CVE-2025-29481
- libbpf.spec
**NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2025-29481
> [Medium] patch libbpf for CVE-2025-29481

- SPECS/qemu/CVE-2023-3019.patch
- SPECS/qemu/CVE-2023-3180.patch
- SPECS/qemu/CVE-2023-3255.patch
- SPECS/qemu/CVE-2023-3301.patch
- SPECS/qemu/qemu.spec
---
Patch `qemu` for assorted CVEs
- Add patch for CVE-2023-3019
- Add patch for CVE-2023-3180
- Add patch for CVE-2023-3255
- Add patch for CVE-2023-3301
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-3019
- https://nvd.nist.gov/vuln/detail/CVE-2023-3180
- https://nvd.nist.gov/vuln/detail/CVE-2023-3255
- https://nvd.nist.gov/vuln/detail/CVE-2023-3301
- Local build
> [Medium] Patch qemu for CVE-2023-3019, CVE-2023-3180, CVE-2023-3301, CVE-2023-3255

- SPECS/perl-JSON-Any/perl-JSON-Any.spec
---
Fix perl-json-any ptest
- Change: Add missing test deps
**YES/NO**
NO 
- Pipeline build id: [788142](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788142&view=results)
> Fix perl-json-any ptest

- SPECS/rubygem-rake/rubygem-rake.spec
---
Fix rubygem-rake ptest 
- Change:  remove discovery of test files. Instead used rakefile from the tests directory to run the test.
**YES/NO**
NO
- Pipeline build id: [788131](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788131&view=results)
> Fix rubygem-rake ptest

- SPECS/python-ecdsa/308.patch
- SPECS/python-ecdsa/python-ecdsa.spec
---
fix python-ecdsa ptest
- Change: import patch from fedora to fix a ptest.  patch basically tighten the value generated by the hypothesis python package by 1. 
- Change: use pytest instead of tox to test
- Change: Add missing test deps
**YES/NO**
NO
- Pipeline build id: [788106](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788106&view=results)
> Fix Ptest for python-ecdsa

- SPECS-EXTENDED/amtk/amtk.signatures.json
- SPECS-EXTENDED/amtk/amtk.spec
- cgmanifest.json
---
amtk: upgrade to 5.6.1
- Bump up the version to 5.6.1
**NO**
- #xxxx
> amtk: upgrade to 5.6.1

- SPECS-EXTENDED/python-kdcproxy/Drop-coverage-from-tests.patch
- SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.signatures.json
- SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.spec
- cgmanifest.json
---
Upgrade: python-kdcproxy version to 1.0.0
- new file:   SPECS-EXTENDED/python-kdcproxy/Drop-coverage-from-tests.patch
- modified:   SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.signatures.json
- modified:   SPECS-EXTENDED/python-kdcproxy/python-kdcproxy.spec
**NO**
- #xxxx
> Upgrade: python-kdcproxy version to 1.0.0

- SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.signatures.json
- SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.spec
- cgmanifest.json
---
Upgrade: python-lazy-object-proxy version to 1.10.0
-  modified:   SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.signatures.json
- modified:   SPECS-EXTENDED/python-lazy-object-proxy/python-lazy-object-proxy.spec
**NO**
- #xxxx
> Upgrade: python-lazy-object-proxy version to 1.10.0

- SPECS/prometheus/CVE-2024-35255.patch
- SPECS/prometheus/prometheus.spec
---
Patch prometheus for CVE-2024-35255 [Medium]. 
- Fix CVE-2024-35255 with an upstream patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-35255
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=749203&view=results
> Patch prometheus for CVE-2024-35255 [Medium]. 

- SPECS/openssh/CVE-2025-32728.patch
- SPECS/openssh/openssh.spec
---
Fix CVE-2025-32728
- Change
- Change
- Change
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=790247&view=results
> Patch openssh for CVE-2025-32728 [MEDIUM]

- SPECS/telegraf/CVE-2025-30215.patch
- SPECS/telegraf/telegraf.spec
---
- Change
- Change
- Change
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=789629&view=results
> Patch telegraf for CVE-2025-30215 [CRITICAL]

- SPECS/erlang/erlang.signatures.json
- SPECS/erlang/erlang.spec
- cgmanifest.json
---
Upgrade erlang to fix CVE-2025-32433 [CRITICAL]
- CVE-2025-32433
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32433
- Pipeline build id: [789553](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=789553&view=results)
> Upgrade erlang to 26.2.5.11 for CVE-2025-32433 [CRITICAL]

- SPECS/giflib/CVE-2025-31344.patch
- SPECS/giflib/giflib.spec
---
- Fix CVE-2025-31344
**NO**
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788567&view=results
> Patch giflib for CVE-2025-31344 [HIGH]

- SPECS/golang/CVE-2024-34158.patch
- SPECS/golang/golang-1.18.spec
---
Addresses CVE-2024-34158 with an upstream patch
- Added patch for CVE-2024-34158
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-34158
- Pipeline build id: [790376](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=790376&view=results)
> Patch golang-1.18 for CVE-2024-34158 [HIGH]

- SPECS/ceph/CVE-2020-14378.patch
- SPECS/ceph/ceph.spec
---
Patch ceph for CVE-2020-14378
- SPECS/ceph/CVE-2020-14378.patch
- SPECS/ceph/ceph.spec
**NO**
- #xxxx
> [LOW] Patch ceph for CVE-2020-14378

- SPECS/golang/CVE-2025-22871.patch
- SPECS/golang/golang-1.18.spec
- SPECS/golang/golang.spec
---
Fix CVE-2025-22871 for golang & golang-1.18
- Fix CVE-2025-22871 for golang & golang-1.18
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-22871
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=787856&view=results)
> Patch golang for CVE-2025-22871[High] 

- SPECS/graphviz/CVE-2023-46045.patch
- SPECS/graphviz/graphviz.spec
---
- Address CVE-2023-46045 with an upstream patch
- CVE-2023-46045
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-46045
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792227&view=results)
> Patch `graphviz` for CVE-2023-46045 [High]

- SPECS/gdb/CVE-2022-47673.patch
- SPECS/gdb/CVE-2022-47696.patch
- SPECS/gdb/gdb.spec
---
- CVE-2022-47673
- CVE-2022-47696
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2022-47673
- https://nvd.nist.gov/vuln/detail/CVE-2022-47696
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792256&view=results)
> Patch `gdb` for CVE-2022-47673, CVE-2022-47696 [High]

- SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec
- SPECS/grub2/0203-fgrep-with-grep.patch
- SPECS/grub2/0203-replace-fgrep-with-grep.patch
- SPECS/grub2/grub2.spec
---
- Post installation of some packages, new grub configuration file is generated which gives a fgrep warning as below, This PR removes that warning
- `fgrep: warning: fgrep is obsolescent; using grep -F`
- Replace fgrep with grep -F
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/51969265
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=789335&view=results
> grub2: Replace fgrep with grep

- SPECS/giflib/CVE-2021-40633.patch
- SPECS/giflib/giflib.spec
---
- CVE-2021-40633
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-40633
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792509&view=results)
> Patch `giflib` for CVE-2021-40633 [High]

- SPECS/moby-engine/CVE-2025-30204.patch
- SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine for CVE-2025-30204
- Patch moby-engine for CVE-2025-30204
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792678&view=results
> [High] Patch moby-engine for CVE-2025-30204

- SPECS/crash/crash.signatures.json
- SPECS/crash/crash.spec
---
- Update gdb-10.2-3.tar.gz to address CVE-2021-20197, CVE-2022-47673, CVE-2022-47696
- CVE-2021-20197
- CVE-2022-47673
- CVE-2022-47696
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-20197
- https://nvd.nist.gov/vuln/detail/CVE-2022-47673
- https://nvd.nist.gov/vuln/detail/CVE-2022-47696
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792387&view=results)
> Fix `crash` for CVE-2021-20197, CVE-2022-47673, CVE-2022-47696 [High]

- SPECS/containerd/CVE-2024-40635.patch
- SPECS/containerd/containerd.spec
- SPECS/containerd2/CVE-2024-40635.patch
- SPECS/containerd2/containerd2.spec
---
- Patch containerd and containerd2 for CVE-2024-40635 [medium] 
- CVE-2024-40635
**NO**
- https://github.com/containerd/containerd/security/advisories/GHSA-265r-hfxg-fhmg
- https://nvd.nist.gov/vuln/detail/CVE-2024-40635
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783609&view=results (Pass)
- aks-pre-release tests: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=783775&view=results (Running)
> Patch containerd and containerd2 for CVE-2024-40635 [medium]

- SPECS/moby-containerd-cc/CVE-2024-40635.patch
- SPECS/moby-containerd-cc/moby-containerd-cc.spec
---
- Patch moby-containerd-cc for CVE-2024-40635 [medium] 
- CVE-2024-40635
**NO**
- https://github.com/containerd/containerd/security/advisories/GHSA-265r-hfxg-fhmg
- https://nvd.nist.gov/vuln/detail/CVE-2024-40635
- Pipeline build ids: 789578, 789647
> Fix CVE-2024-40635 for moby-containerd-cc with an upstream patch

- SPECS/python-sphinxcontrib-htmlhelp/python-sphinxcontrib-htmlhelp.spec
- SPECS/python-sphinxcontrib-jsmath/python-sphinxcontrib-jsmath.spec
- SPECS/python-sphinxcontrib-qthelp/python-sphinxcontrib-qthelp.spec
- SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec
---
- Change: Use compatible sphinx version for test
-  use pytest instead of test. 
**YES/NO**
NO
- Pipeline build id: [793555](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=793555&view=results)
> Fix sphinxcontrib-xxxx ptests

- SPECS/python-cherrypy/python-cherrypy.spec
- SPECS/python-cherrypy/test-session-py3.8above.patch
---
Fix ptest.
- Change: backport a fix from upstream to fix a test case issue
**YES/NO**
NO
- Pipeline build id: [793514](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=793514&view=results)
> Fix python cherrypy ptest

- SPECS/perl-YAML-Tiny/perl-YAML-Tiny.spec
---
=> Fix perl-YAML-Tiny ptest
- Change: Adding missing runtime dep
**YES/NO**
NO
- Pipeline build id: [793487](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=793487&view=results)
> fix perl-yaml-tiny ptest

- SPECS/python-typing-extensions/python-typing-extensions.spec
- SPECS/python-typing-extensions/test_generic_protocols_special_from_protocol.patch
---
Ptest fails with class Protocol issue. 
- Change: Import patch from fedora to fix the failing ptest.
**YES/NO**
NO
- Pipeline build id: [782625](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782625&view=results)
> Fix python typing extensions ptest

- SPECS/pytorch/CVE-2025-32434.patch
- SPECS/pytorch/CVE-2025-3730.patch
- SPECS/pytorch/pytorch.spec
---
- Address CVE-2025-32434, CVE-2025-3730
- CVE-2025-32434
- CVE-2025-3730
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-32434
- https://nvd.nist.gov/vuln/detail/CVE-2025-3730
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=793989)
> Patch `pytorch` for CVE-2025-32434, CVE-2025-3730 [Critical]

- SPECS-EXTENDED/python-curio/python-curio.signatures.json
- SPECS-EXTENDED/python-curio/python-curio.spec
- cgmanifest.json
---
This PR is to upgrade the package python-curio version to 1.6^1.1484546
- SPECS-EXTENDED/python-curio/python-curio.signatures.json
- SPECS-EXTENDED/python-curio/python-curio.spec
**NO**
- #xxxx
- Local Build
> Upgrade: python-curio version to 1.6^1.1484546

- SPECS-EXTENDED/tk/tk-8.6.12-conf.patch
- SPECS-EXTENDED/tk/tk-8.6.12-make.patch
- SPECS-EXTENDED/tk/tk.signatures.json
- SPECS-EXTENDED/tk/tk.spec
- cgmanifest.json
---
Upgrade: tk version to 8.6.14
- SPECS-EXTENDED/tk/tk-8.6.12-conf.patch
- SPECS-EXTENDED/tk/tk-8.6.12-make.patch
- SPECS-EXTENDED/tk/tk.signatures.json
- SPECS-EXTENDED/tk/tk.spec
**NO**
- #xxxx
> Upgrade: tk version to 8.6.13

- SPECS-EXTENDED/perl-Term-Table/perl-Term-Table.signatures.json
- SPECS-EXTENDED/perl-Term-Table/perl-Term-Table.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-Term-Table version to 0.024
- SPECS-EXTENDED/perl-Term-Table/perl-Term-Table.signatures.json
- SPECS-EXTENDED/perl-Term-Table/perl-Term-Table.spec
**NO**
- #xxxx
- Local Build
> Upgrade: perl-Term-Table version to 0.024

- SPECS-EXTENDED/freexl/freexl.signatures.json
- SPECS-EXTENDED/freexl/freexl.spec
- cgmanifest.json
---
freexl : Update to version 2.0.0
-  libbsd minizip
-SPECS-EXTENDED/freexl/freexl.signatures.json
-SPECS-EXTENDED/freexl/freexl.spec
**NO**
- #xxxx
Verified on 3.0 container
> freexl : Upgrade to version 2.0.0

- SPECS-EXTENDED/hyphen-tk/hyph-tk.tex
- SPECS-EXTENDED/hyphen-tk/hyphen-tk-cleantex.patch
- SPECS-EXTENDED/hyphen-tk/hyphen-tk.signatures.json
- SPECS-EXTENDED/hyphen-tk/hyphen-tk.spec
- cgmanifest.json
---
**hyphen-tk: update version to 0.20210322**
Please build the following package along with hypen-tk:
**hyphen**
- modified: SPECS-EXTENDED/hyphen-tk/hyphen-tk-cleantex.patch
- modified: SPECS-EXTENDED/hyphen-tk/hyph-tk.tex
- modified: SPECS-EXTENDED/hyphen-tk/hyphen-tk.spec
- modified: SPECS-EXTENDED/hyphen-tk/hyphen-tk.signatures.json
**NO**
- #xxxx
> hyphen-tk: Update Version from 0.20110620 -> 0.20210322

- SPECS-EXTENDED/librevenge/librevenge.signatures.json
- SPECS-EXTENDED/librevenge/librevenge.spec
- cgmanifest.json
---
The PR is to upgrade the librevenge package to version 0.0.5
- SPECS-EXTENDED/librevenge/librevenge.signatures.json
- SPECS-EXTENDED/librevenge/librevenge.spec
**NO**
- #xxxx
> Upgrade: librevenge version to 0.0.5

- SPECS-EXTENDED/perl-Alien-pkgconf/Alien-pkgconf-0.19-Accept-pkgconf-1.9.patch
- SPECS-EXTENDED/perl-Alien-pkgconf/perl-Alien-pkgconf.signatures.json
- SPECS-EXTENDED/perl-Alien-pkgconf/perl-Alien-pkgconf.spec
- cgmanifest.json
---
Upgrade perl-Alien-pkgconf version to 0.20
-  Alien-pkgconf-0.19-Accept-pkgconf-1.9.patch
-  perl-Alien-pkgconf.signatures.json
-  perl-Alien-pkgconf.spec
**NO**
- #xxxx
> Upgrade perl-Alien-pkgconf version to 0.20

- SPECS-EXTENDED/python-blinker/python-blinker.signatures.json
- SPECS-EXTENDED/python-blinker/python-blinker.spec
- cgmanifest.json
---
Upgrades python-blinker to version 1.7.0
Please build following packages with python-blinker:
python-tox python-toml
- modified:   SPECS-EXTENDED/python-blinker/python-blinker.signatures.json
- modified:   SPECS-EXTENDED/python-blinker/python-blinker.spec
**NO**
- NA
- NA
- local build
> Upgrades python-blinker to version 1.7.0

- SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-framelocalsproxy.patch
- SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-loadTestsFromModule.patch
- SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-parse_qs.patch
- SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-protect-cgi.patch
- SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-typeerror.patch
- SPECS-EXTENDED/python-cheetah/python-cheetah.signatures.json
- SPECS-EXTENDED/python-cheetah/python-cheetah.spec
- SPECS-EXTENDED/python-cheetah/tox-no-basepython.patch
- cgmanifest.json
---
Upgrades python-cheetah to version 3.2.6.post1
Please build following packages with python-cheetah:
python-toml python-tox
- added: SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-framelocalsproxy.patch
- added: SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-loadTestsFromModule.patch
- added: SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-parse_qs.patch
- added: SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-protect-cgi.patch
- added: SPECS-EXTENDED/python-cheetah/cheetah3-3.2.6.post1-typeerror.patch
- added: SPECS-EXTENDED/python-cheetah/tox-no-basepython.patch
- modified: SPECS-EXTENDED/python-cheetah/python-cheetah.signatures.json
- modified: …
> Upgrades python-cheetah to version 3.2.6.post1

- SPECS-EXTENDED/xfconf/xfconf.signatures.json
- SPECS-EXTENDED/xfconf/xfconf.spec
- cgmanifest.json
---
Upgrade: xfconf version to 4.18.3
- SPECS-EXTENDED/xfconf/xfconf.signatures.json
- SPECS-EXTENDED/xfconf/xfconf.spec
**NO**
- #xxxx
> Upgrade: xfconf version to 4.18.3

- SPECS/qtsvg/qtsvg.spec
---
Bump the `qtsvg` package release number to force it to recompile against `qtbase-devel` 6.6.3. The `qtsvg` currently published to PMC was compiled against 6.6.2 and causes the ISO installer to fail to load.
- Change
- Change
- Change
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/57003084
- Buddybuild: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=782114&view=results
> qtsvg: bump release to recompile with latest qtbase-devel

- SPECS-EXTENDED/libutempter/libutempter.signatures.json
- SPECS-EXTENDED/libutempter/libutempter.spec
- cgmanifest.json
---
**libutempter: update version to 1.2.1**
- modified: SPECS-EXTENDED/libutempter/libutempter.spec
- modified: SPECS-EXTENDED/libutempter/libutempter.signatures.json
NO
- #xxxx
> libutempter: Update Version from 1.1.6 -> 1.2.1

- SPECS/mariadb-connector-c/mariadb-connector-c.spec
---
When installing the mariadb-connector-c package, the new libraries that are installed as part of the package are not immediately known by ld. Call ldconfig as part of package installation and removal to ensure the ld cache is refreshed
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/57098928
- Pipeline build id: [795463](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=795463&view=results)
```
azureuser@chrco-dev-vm-3 [ ~ ]$ ldconfig -p|grep mariadb
azureuser@chrco-dev-vm-3 [ ~ ]$ sudo dnf install mariadb-connector-c-3.3.8-3.azl3.x86_64.rpm mariadb-connector-c-config-3.3.8-3.azl3.noarch.rpm --rpmverbosity=debug
Azure Linux Official Microsoft …
```
> Add a post and postun for mariadb-connector-c, ensuring ldconfig is run

- SPECS/qemu/CVE-2024-3447.patch
- SPECS/qemu/CVE-2024-4467.patch
- SPECS/qemu/CVE-2024-6505.patch
- SPECS/qemu/qemu.spec
---
Added patches for CVE-2024-4467 [HIGH], CVE-2024-3447, CVE-2024-6505 [MEDIUM]
- Added patches for CVE-2024-4467 [HIGH], CVE-2024-3447, CVE-2024-6505 [MEDIUM]
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-3447
- https://nvd.nist.gov/vuln/detail/CVE-2024-4467
- https://nvd.nist.gov/vuln/detail/CVE-2024-6505
- Pipeline build id: [794932](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=794932&view=results)
> Patch qemu for CVE-2024-4467 [HIGH], CVE-2024-3447, CVE-2024-6505 [MEDIUM]

- SPECS/libsoup/CVE-2025-32908.patch
- SPECS/libsoup/CVE-2025-32914.patch
- SPECS/libsoup/libsoup.spec
---
Added patches for libsoup to fix CVE-2025-32908, CVE-2025-32914
- CVE-2025-32908
- CVE-2025-32914
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32908
- https://nvd.nist.gov/vuln/detail/CVE-2025-32914
- Pipeline build id: [795497](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=795497&view=results)
- https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/451
- https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/450
> Patch libsoup for CVE-2025-32908, CVE-2025-32914 [HIGH]

- SPECS/keda/CVE-2025-22872.patch
- SPECS/keda/keda.spec
---
- Address CVE-2025-22872
- CVE-2025-22872
**NO**
- #xxxx
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=795574&view=results)
> Patch `keda` for CVE-2025-22872 [Medium]

- SPECS-EXTENDED/libunicap/0001-Address-po-files-issues.patch
- SPECS-EXTENDED/libunicap/libunicap.spec
---
**libunicap: Fixed build issues**
Please build the following package along with libunicap:
**libraw1394  v4l-utils**
- new file:   SPECS-EXTENDED/libunicap/0001-Address-po-files-issues.patch
- modified:   SPECS-EXTENDED/libunicap/libunicap.spec
**NO**
- #xxxx
> libunicap: Fixed build issues

- SPECS/sriov-network-device-plugin/CVE-2025-22872.patch
- SPECS/sriov-network-device-plugin/sriov-network-device-plugin.spec
---
patch sriov-network-device-plugin for CVE-2025-22872?
-  sriov-network-device-plugin .spec 
**NO**
- #xxxx
> [Medium] patch sriov-network-device-plugin for CVE-2025-22872

- SPECS/docker-compose/CVE-2025-22872.patch
- SPECS/docker-compose/docker-compose.spec
---
patch docker-compose for CVE-2025-22872
- docker-compose.spec
**NO**
- #xxxx
> [Medium] patch docker-compose for CVE-2025-22872

- SPECS/kubevirt/CVE-2025-22872.patch
- SPECS/kubevirt/kubevirt.spec
---
kubevirt: Patch for CVE-2025-22872
- new file: **SPECS/kubevirt/CVE-2025-22872.patch**
- modified: **SPECS/kubevirt/kubevirt.spec**
**NO**
- #xxxx
> [Medium] Patch kubevirt for CVE-2025-22872

- SPECS/cni-plugins/CVE-2025-22872.patch
- SPECS/cni-plugins/cni-plugins.spec
---
cni-plugins: Patch for CVE-2025-22872
- new file: **SPECS/cni-plugins/CVE-2025-22872.patch**
- modified: **SPECS/cni-plugins/cni-plugins.spec**
**NO**
- #xxxx
> [Medium] Patch cni-plugins for CVE-2025-22872

- SPECS/containerized-data-importer/CVE-2025-22872.patch
- SPECS/containerized-data-importer/containerized-data-importer.spec
---
Patch containerized-data-importer for CVE-2025-22872
- SPECS/containerized-data-importer/CVE-2025-22872.patch
- SPECS/containerized-data-importer/containerized-data-importer.spec
**NO**
- #xxxx
> [MEDIUM] Patch containerized-data-importer for CVE-2025-22872

- SPECS/packer/CVE-2025-22872.patch
- SPECS/packer/packer.spec
---
Patch packer for CVE-2025-22872
- SPECS/packer/CVE-2025-22872.patch
- SPECS/packer/packer.spec
**NO**
- #xxxx
> [MEDIUM] Patch packer for CVE-2025-22872

- SPECS/gh/CVE-2025-22872.patch
- SPECS/gh/gh.spec
---
patch gh for CVE-2025-22872
-gh.spec
**NO**
- #xxxx
-https://nvd.nist.gov/vuln/detail/CVE-2025-22872
> [Medium] patch gh for CVE-2025-22872

- SPECS/kube-vip-cloud-provider/CVE-2025-22872.patch
- SPECS/kube-vip-cloud-provider/kube-vip-cloud-provider.spec
---
Patch `kube-vip-cloud-provider` for CVE-2025-22872
- Add a patch for CVE-2025-22872
**NO**
- Local build
> [Medium] Patch kube-vip-cloud-provider for CVE-2025-22872

- SPECS/tinyxml2/CVE-2024-50615.patch
- SPECS/tinyxml2/tinyxml2.spec
---
Patch tinyxml2 for CVE-2024-50615
- SPECS/tinyxml2/CVE-2024-50615.patch
- SPECS/tinyxml2/tinyxml2.spec
**NO**
- #xxxx
> [MEDIUM] Patch tinyxml2 for CVE-2024-50615

- SPECS/python-pytest-forked/Pytest-Output-Fix.patch
- SPECS/python-pytest-forked/python-pytest-forked.spec
---
Fix ptest for python-pytest-forked
- Change: Add patch from upstream to account for pytest output change
**YES/NO**
NO 
- Pipeline build id: [799115](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=799115&view=results)
> Fix ptest for Python-pytest-forked

- SPECS/python-msgpack/python-msgpack.spec
---
Fix Ptest for python-msgpack 
- Change: use ptest instead of tox to fix the ptest
**YES/NO**
NO
- Pipeline build id: [799135](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=799135&view=results)
> Fix python-msgpack ptest

- SPECS/python-more-itertools/python-more-itertools.spec
---
fix ptest for python-more-itertools
- Change: switch to pytest
**YES/NO**
NO
- Pipeline build id: [799095](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=799095&view=results)
> Fix python-more-itertools Ptest

- SPECS/python-markdown/python-markdown.spec
---
Fix Ptest for python-markdown
- Change:  use Proper command to run the ptest
**YES/NO**
NO
- Pipeline build id: [799123](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=799123&view=results)
> Fix Ptest for python-markdown

- SPECS/influxdb/CVE-2025-22872.patch
- SPECS/influxdb/influxdb.spec
---
influxdb: Patch for CVE-2025-22872
- new file: **SPECS/influxdb/CVE-2025-22872.patch**
- modified: **SPECS/influxdb/influxdb.spec**
**NO**
- #xxxx
> [Medium] Patch influxdb for CVE-2025-22872

- SPECS/kubernetes/CVE-2025-22872.patch
- SPECS/kubernetes/kubernetes.spec
---
kubernetes: Patch for CVE-2025-22872
- new file: **SPECS/kubernetes/CVE-2025-22872.patch**
- modified: **SPECS/kubernetes/kubernetes.spec**
**NO**
- #xxxx
> [Medium] Patch kubernetes for CVE-2025-22872

- SPECS-EXTENDED/python-dmidecode/python-dmidecode-rhbz2154949.patch
- SPECS-EXTENDED/python-dmidecode/python-dmidecode.signatures.json
- SPECS-EXTENDED/python-dmidecode/python-dmidecode.spec
- cgmanifest.json
---
Upgrade: python-dmidecode version to 3.12.3
- new file:   SPECS-EXTENDED/python-dmidecode/python-dmidecode-rhbz2154949.patch
- modified:   SPECS-EXTENDED/python-dmidecode/python-dmidecode.signatures.json
- modified:   SPECS-EXTENDED/python-dmidecode/python-dmidecode.spec
**NO**
- #xxxx
- Patch application
> Upgrade: python-dmidecode version to 3.12.3

- SPECS/busybox/CVE-2023-39810.patch
- SPECS/busybox/busybox.spec
---
Added patch to busybox to fix CVE-2023-39810
- CVE-2023-39810
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2023-39810
- Pipeline build id: [800811](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=800811&view=results)
- https://git.busybox.net/busybox/commit/?id=9a8796436b9b0641
> Patch busybox for CVE-2023-39810 [HIGH]

- SPECS/boost/boost-1.81-phoenix-multiple-defn.patch
- SPECS/boost/boost.spec
---
Fixes boost by adding phoenix multiple defn patch
Needed by libetonyek PR: https://github.com/microsoft/azurelinux/pull/13609
- modified: ../SPECS/boost/boost.spec
- added: ../SPECS/boost/boost-1.81-phoenix-multiple-defn.patch
**NO**
- NA
- NA
- local build
> Fixes boost by adding phoenix multiple defn patch needed by libetonyek

- SPECS/multus/CVE-2025-22872.patch
- SPECS/multus/multus.spec
---
Patch `multus` for CVE-2025-22872
- Add patch for CVE-2025-22872
**NO**
- Local build
> [Medium] Patch multus for CVE-2025-22872

- SPECS-EXTENDED/generic-logos/generic-logos.spec
---
- generic-logos: fix the build error
- Build error fix
**NO**
- #xxxx
> generic-logos: fix the build error

- SPECS/telegraf/CVE-2025-22872.patch
- SPECS/telegraf/telegraf.spec
---
Patch telegraf for CVE-2025-22872 [Medium]
- Fix  CVE-2025-22872 with an upstream patch
**NO**
- #xxxx
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=792837&view=results
> Patch telegraf for CVE-2025-22872 [Medium]

- SPECS-EXTENDED/perl-File-DesktopEntry/perl-File-DesktopEntry.spec
---
Fixes broken build of perl-File-DesktopEntry
Please build following packages with perl-File-DesktopEntry:
perl-BSD-Resource 
perl-IPC-System-Simple 
perl-File-BaseDir
- Change: SPECS-EXTENDED/perl-File-DesktopEntry/perl-File-DesktopEntry.spec
**NO**
- NA
- NA
- local build & docker install
-
> Fixes broken build of perl-File-DesktopEntry

- SPECS/helm/CVE-2025-22872.patch
- SPECS/helm/CVE-2025-32386.patch
- SPECS/helm/CVE-2025-32387.nopatch
- SPECS/helm/helm.spec
---
Patch helm for CVE-2025-32386 & CVE-2025-22872
- SPECS/helm/CVE-2025-32386.patch
- SPECS/helm/CVE-2025-22872.patch
- SPECS/helm/helm.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-32386
> [MEDIUM] Patch helm for CVE-2025-32386 & CVE-2025-22872

- SPECS-EXTENDED/python-beautifulsoup4/python-beautifulsoup4.signatures.json
- SPECS-EXTENDED/python-beautifulsoup4/python-beautifulsoup4.spec
- SPECS-EXTENDED/python-beautifulsoup4/soupsieve26.patch
- cgmanifest.json
---
Upgrade python-beautifulsoup4 version to 4.12.3
- python-beautifulsoup4.signatures.json
- python-beautifulsoup4.spec
- soupsieve26.patch
- 
**NO**
- #xxxx
> Upgrade python-beautifulsoup4 version to 4.12.3

- .pipelines/prchecks/PackageBuildPRCheck.yml
- .pipelines/templates/PackageTestResultsAnalysis.yml
---
We're migrating all workloads to agents running AZL 3.0 and that includes this fast-track PR check as well.
Had to switch from installing our `python3-junit-xml` to a `pip install junit_xml`, because 3.0 AZL doesn't have the `python3-junit-xml` package. The `python3-junitxml` is a different Python module.
2.0 counterpart: #13661.
No.
- This PR check.
> Switched the fast-track PR check to run on an AZL 3.0 agent pool.

- SPECS-SIGNED/hvloader-signed/hvloader-signed.spec
- SPECS/hvloader/CVE-2023-45236.patch
- SPECS/hvloader/CVE-2023-45237.patch
- SPECS/hvloader/hvloader.spec
---
Patch hvloader for CVE-2023-45236, CVE-2023-45237 [High] 
- Fix CVE-2023-45236 and CVE-2023-45237 with an upstream patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-45236
- https://nvd.nist.gov/vuln/detail/CVE-2023-45237
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=798396&view=results
> Patch hvloader for CVE-2023-45236, CVE-2023-45237 [High]

- SPECS/python-cryptography/python-cryptography.spec
---
Fix python-cryptography ptest 
- Change: there's a mismatch between test package and the python-cryptography package
**YES/NO**
NO 
- Pipeline build id: [804377](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=804377&view=results)
> Fix Ptest python-Cryptography 

- SPECS-EXTENDED/python-blinker/python-blinker.signatures.json
- SPECS/python-blinker/python-blinker.signatures.json
- SPECS/python-blinker/python-blinker.spec
- SPECS/python-oauthlib/python-oauthlib.spec
- cgmanifest.json
---
Fix ptest for python-oauthlib
- Change:  Move python-blinker to core and upgrade to 1.9.0
- Change: Add missing runtime dep for python-oauthlib
**YES/NO**
NO
- Pipeline build id: [799190](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=799190&view=results)
> Fix python-oauthlib ptest

- SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
---
Fix perl-CPAN-Meta-check ptest 
- Change: Add missing checktime dep
**YES/NO**
NO
- Pipeline build id: [804447](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=804447&view=results)
> fix perl-cpan-meta-check ptest

- SPECS-EXTENDED/zenity/zenity.signatures.json
- SPECS-EXTENDED/zenity/zenity.spec
- cgmanifest.json
---
Upgrade: zenity version to 3.44.1
- SPECS-EXTENDED/zenity/zenity.signatures.json
- SPECS-EXTENDED/zenity/zenity.spec
**NO**
- #xxxx
> Upgrade: zenity version to 3.44.1

- SPECS/libsoup/CVE-2025-32053.patch
- SPECS/libsoup/libsoup.spec
---
Patch libsoup for CVE-2025-32053 in 2.0
- Patch libsoup for CVE-2025-32053 in 2.0
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-32053
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=804628&view=results) - Recent after resolving merge conflicts
> Patch libsoup for CVE-2025-32053 [Medium]

- toolkit/tools/go.mod
- toolkit/tools/go.sum
---
Fixes: https://github.com/microsoft/azurelinux/security/dependabot/17
NOTE: Github Dashboard marks this as a `HIGH 8.7/10` security issue.
- Upgrade the toolkit `golang-jwt to 5.2.2`
**NO**
- https://github.com/microsoft/azurelinux/security/dependabot/17
- https://github.com/microsoft/azurelinux/security/dependabot/17
- NA
> toolkit: golang-jwt: 5.2.1 -> 5.2.2 to address excessive memory allocation during header parsing (CVE-2025-30204)

- SPECS/cmake/CVE-2024-8096.patch
- SPECS/cmake/cmake.spec
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch cmake for CVE-2024-8096
- SPECS/cmake/CVE-2024-8096.patch
- SPECS/cmake/cmake.spec
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-8096
> [MEDIUM] Patch cmake for CVE-2024-8096

- SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
- SPECS/edk2/CVE-2024-2511.patch
- SPECS/edk2/CVE-2024-38796.patch
- SPECS/edk2/CVE-2024-4603.patch
- SPECS/edk2/edk2.spec
---
Patch edk2 for CVE-2024-2511, CVE-2024-38796 & CVE-2024-4603
- SPECS-SIGNED/edk2-hvloader-signed/edk2-hvloader-signed.spec
- SPECS/edk2/CVE-2024-2511.patch
- SPECS/edk2/CVE-2024-38796.patch
- SPECS/edk2/CVE-2024-4603.patch
- SPECS/edk2/edk2.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-2511
-  https://nvd.nist.gov/vuln/detail/CVE-2024-38796 
-  https://nvd.nist.gov/vuln/detail/CVE-2024-4603
> [MEDIUM] Patch edk2 for CVE-2024-2511, CVE-2024-38796 & CVE-2024-4603

- SPECS/qemu/CVE-2024-26327.patch
- SPECS/qemu/CVE-2024-26328.patch
- SPECS/qemu/qemu.spec
---
Added patches for CVE-2024-26327, CVE-2024-26328 [MEDIUM]
- Added patches for CVE-2024-26327, CVE-2024-26328 [MEDIUM]
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-26327
- https://nvd.nist.gov/vuln/detail/CVE-2024-26328
- Pipeline build id: [805024](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=805024&view=results)
- https://gitlab.com/qemu-project/qemu/-/commit/313e746958967a4b941ad4bbb80726727318edfa
- https://gitlab.com/qemu-project/qemu/-/commit/98f3488c1b6090024299f8d6362aa6aac03fe26d
> Patch qemu for CVE-2024-26327, CVE-2024-26328 [MEDIUM]

- SPECS-EXTENDED/jsch/jsch-0.1.54-sourcetarget.patch
- SPECS-EXTENDED/jsch/jsch-osgi-manifest.patch
- SPECS-EXTENDED/jsch/jsch.spec
---
Build Fix: jsch
Please build following package with jsch:
- jzlib
- SPECS-EXTENDED/jsch/jsch-0.1.54-sourcetarget.patch
- SPECS-EXTENDED/jsch/jsch-osgi-manifest.patch
- SPECS-EXTENDED/jsch/jsch.spec
**NO**
- #xxxx
> Build Fix: jsch 0.1.55

- SPECS-EXTENDED/objenesis/objenesis-javadoc.patch
- SPECS-EXTENDED/objenesis/objenesis.signatures.json
- SPECS-EXTENDED/objenesis/objenesis.spec
- cgmanifest.json
---
Upgrades objenesis to version 3.3
- added: SPECS-EXTENDED/objenesis/objenesis-javadoc.patch
- modified: SPECS-EXTENDED/objenesis/objenesis.signatures.json
- modified: SPECS-EXTENDED/objenesis/objenesis.spec
**NO**
- NA
- NA
- local build
> Upgrades objenesis to version 3.3

- SPECS-EXTENDED/libgeotiff/libgeotiff.signatures.json
- SPECS-EXTENDED/libgeotiff/libgeotiff.spec
- SPECS-EXTENDED/libgeotiff/libgeotiff_cmake.patch
- cgmanifest.json
---
- Upgrade: libgeotiff version to 1.7.3
- Depends on proj-9.2.1
- Bump up the version
**NO**
- #xxxx
> Upgrade: libgeotiff version to 1.7.3

- SPECS-EXTENDED/perl-JSON-MaybeXS/perl-JSON-MaybeXS.signatures.json
- SPECS-EXTENDED/perl-JSON-MaybeXS/perl-JSON-MaybeXS.spec
- cgmanifest.json
---
- Upgrade: perl-JSON-MaybeXS version to 1.004008
- Depends on perl-Cpanel-JSON-XS-4.39
- Bump up the version
**NO**
- #xxxx
> Upgrade: perl-JSON-MaybeXS version to 1.004008

- SPECS/pytorch/CVE-2025-2953.patch
- SPECS/pytorch/pytorch.spec
---
Patch pytorch for CVE-2025-2953
- SPECS/pytorch/CVE-2025-2953.patch
- SPECS/pytorch/pytorch.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-2953
> [MEDIUM] Patch pytorch for CVE-2025-2953

- SPECS/syslog-ng/CVE-2024-47619.patch
- SPECS/syslog-ng/syslog-ng.spec
---
- CVE-2024-47619
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-47619
- Pipeline build id: [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=806004&view=results)
> Patch `syslog-ng` for CVE-2024-47619 [High]

- SPECS/kata-containers-cc/kata-containers-cc.signatures.json
- SPECS/kata-containers-cc/kata-containers-cc.spec
- SPECS/kata-containers/kata-containers.signatures.json
- SPECS/kata-containers/kata-containers.spec
- cgmanifest.json
---
Upgrade of the Kata Containers sources to upstream's version 3.15.0
- Rebase our forked changes to the upstream 3.15.0 release
**NO**
- N/A
- N/A
- Pipeline build ids: 798056, 798351, 799140, 798863, 799130, 800392
> kata-containers(-cc): Update to 3.15.0.aks0 release

- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.signatures.json
- SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
- cgmanifest.json
---
Upgrades `SymCrypt-OpenSSL` to version `1.8.1`. This contains a fix for a memory leak during TLS handshake, which has been reported by customers.
- Update to 1.8.1
**NO**
- ADO: https://microsoft.visualstudio.com/OS/_workitems/edit/57447202
- Upstream memory leak fix work item: https://github.com/microsoft/SymCrypt-OpenSSL/issues/115
Big Build Root: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=808671&view=results
With the images that eventually built, I created the following azure vms:
- AMD64 non-FIPS
- AMD64 FIPS
- ARM64 non-FIPS
- ARM64 FIPS
For each of those, I did the following:
1. Confirmed SymCrypt-OpenSSL was the correct version and was installed as …
> Upgrade SymCrypt-OpenSSL to 1.8.1

- SPECS/azurelinux-release/azurelinux-release.spec
> Prepare May 2025 Update 2

- SPECS/bmake/bmake.spec
- SPECS/bmake/do-not-run-tests-on-install.patch
---
Add patch to `bmake` so that tests can be run in %check section instead of during %install
- Change bmake to run tests in check section
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/57304584
- Pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=810899&view=results
> [3.0] bmake: move tests to check section

- SPECS/bmake/bmake.spec
- SPECS/bmake/do-not-run-tests-on-install.patch
---
Improve reliability of `bmake` package build by skipping a test that is known to be flaky (fails every week or two in daily builds).  
The unit tests currently run during the %install section - I've changed this, so the tests run in a %check section.
- Change bmake to skip failing test
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/57304584
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=810848&view=results
> [2.0] bmake: fix test issue

- SPECS/mdadm/CVE-2023-28938.patch
- SPECS/mdadm/mdadm.spec
---
Patch mdadm for CVE-2023-28938
- modified:   SPECS/mdadm/mdadm.spec
- newfile:      SPECS/mdadm/CVE-2023-28938.patch
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-28938
> [Low] Patch mdadm for CVE-2023-28938

- SPECS/iniparser/CVE-2023-33461.patch
- SPECS/iniparser/iniparser.spec
---
iniparser: Patch for CVE-2023-33461
- new file: **SPECS/iniparser/CVE-2023-33461.patch**
- modified: **SPECS/iniparser/iniparser.spec**
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-33461
> [Medium] Patch iniparser for CVE-2023-33461

- SPECS/yasm/CVE-2023-37732.patch
- SPECS/yasm/CVE-2023-51258.patch
- SPECS/yasm/yasm.spec
---
Patch yasm for CVE-2023-51258 & CVE-2023-37732
- SPECS/yasm/yasm.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2023-51258
- https://nvd.nist.gov/vuln/detail/CVE-2023-37732
> [Medium] Patch yasm for CVE-2023-51258 & CVE-2023-37732

- SPECS-EXTENDED/cassandra/cassandra.spec
---
cassandra: fix build
- cassandra.spec
**YES/NO**
- #xxxx
> cassandra: fix build

- SPECS/containerd2/CVE-2025-22872.patch
- SPECS/containerd2/containerd2.spec
---
Address CVE-2025-22872
Backported from upstream patch: https://github.com/golang/net/commit/e1fcd82abba34df74614020343be8eb1fe85f0d9
Excluded token_test.go as this file and the test infrastructure is absent in the current version of our code.
- modified: SPECS/containerd2/containerd2.spec
- added: SPECS/containerd2/CVE-2025-22872.patch
**NO**
- NA
- local build
> [MEDIUM] Patch containerd2 for CVE-2025-22872

- SPECS/net-tools/CVE-2025-46836.patch
- SPECS/net-tools/net-tools.spec
---
Addresses CVE-2025-46836
- modified: SPECS/net-tools/net-tools.spec
- added: SPECS/net-tools/CVE-2025-46836.patch
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2025-46836
- local build
> [MEDIUM] Patch net-tools for CVE-2025-46836

- SPECS-EXTENDED/tang/tang.signatures.json
- SPECS-EXTENDED/tang/tang.spec
- cgmanifest.json
---
Upgrade: tang version to 15
Please build following package with tang:
- jose
- llhttp
- SPECS-EXTENDED/tang/tang.signatures.json
- SPECS-EXTENDED/tang/tang.spec
**NO**
- #xxxx
> Upgrade: tang version to 15

- SPECS-EXTENDED/jose/jose.signatures.json
- SPECS-EXTENDED/jose/jose.spec
- cgmanifest.json
---
Upgrade: jose version to 14
- SPECS-EXTENDED/jose/jose.signatures.json
- SPECS-EXTENDED/jose/jose.spec
**NO**
- #xxxx
> Upgrade: jose version to 14

- toolkit/tools/scheduler/scheduler.go
---
In #13705 I've broken reporting of package build failures. The error from the new `schedulerutils.PrintHiddenBuildBlockers` function overrode the build failure's error and caused a build to look like it succeeded regardless of the actual status.
[Example build with failing packages, which was marked as green by the pipeline.](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=817443&view=logs&j=bac295d9-f2e0-5165-e63e-e76f383e1a27&t=7f5db2cb-55fd-544b-1225-ab0632880ca5&l=3262)
No.
- #13705
- #13889
- [Buddy build, which should fail with the fix for package build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=817734&view=results).
- [Buddy build, …
> Fixed reporting of build errors (CP: #13889)

- SPECS-SIGNED/fwctl-signed/fwctl-signed.spec
- SPECS-SIGNED/iser-signed/iser-signed.spec
- SPECS-SIGNED/isert-signed/isert-signed.spec
- SPECS-SIGNED/mlnx-nfsrdma-signed/mlnx-nfsrdma-signed.spec
- SPECS-SIGNED/srp-signed/srp-signed.spec
- SPECS-SIGNED/xpmem-modules-signed/xpmem-modules-signed.spec
- SPECS/fwctl/fwctl.spec
- SPECS/iser/iser.spec
- SPECS/isert/isert.spec
- SPECS/mlnx-nfsrdma/mlnx-nfsrdma.spec
- SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec
- SPECS/srp/srp.spec
- SPECS/xpmem/xpmem.spec
---
address bug in OOT spec that depend on mlnx - bump to right mlnx release nb
- Change
- Change
- Change
**NO**
- #xxxx
> address bug in OOT spec that depend on mlnx - bump to right mlnx release nb

- SPECS/nodejs/CVE-2025-47279.patch
- SPECS/nodejs/nodejs18.spec
---
Address CVE-2025-47279
Upstream Patch: https://github.com/nodejs/undici/commit/f317618ec28753a4218beccea048bcf89c36db25
Excluded the below files as they were meant for testing and the testing infrastructure is missing from our current version of code.
test/pool-connection-error-memory-leak.js
test/tls-cert-leak.js
- modified: SPECS/nodejs/nodejs18.spec
- added: SPECS/nodejs/CVE-2025-47279.patch
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2025-47279
- Due to insufficient memory in vm could not get a successful build. It fails with the same error even without my changes
> [LOW] Patch nodejs for CVE-2025-47279

- SPECS-EXTENDED/python-argparse-manpage/0001-Fix-setuptools-v60.patch
- SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.spec
---
- Fix ptests in python-argparse-manpage
- Fix ptets
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/57716088/
- Pipeline build : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=821782&view=results
> python-argparse-manpage: Fix ptests

- SPECS-EXTENDED/xalan-j2/xalan-j2.spec
- cgmanifest.json
---
xalan-j2: Build Fix
- xalan-j2.spec
**YES/NO**
- #xxxx
> xalan-j2: Build Fix

- SPECS-EXTENDED/gcr/fix-meson-packages-build-keyword.patch
- SPECS-EXTENDED/gcr/gcr.spec
gcr does not compile with the meson build system 0.61.0 and greater and with azl3 shipping version 1.3.1 gcr will fail in compile stage.
Adding a patch to fix the meson build syntax.
---
- Change
- Change
- Change
**NO**
- #xxxx
> Add patch to gcr allowing meson to build

- SPECS/glib/CVE-2025-3360.patch
- SPECS/glib/glib.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch glib for CVE-2025-3360
- SPECS/glib/CVE-2025-3360.patch
- SPECS/glib/glib.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-3360
> [LOW] Patch glib for CVE-2025-3360

- SPECS/ntopng/CVE-2021-44964.patch
- SPECS/ntopng/ntopng.spec
---
patch ntopng for CVE-2021-44964
-ntopng.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-44964
> [Medium] patch ntopng for CVE-2021-44964

- SPECS/valkey/CVE-2025-49112.patch
- SPECS/valkey/valkey.spec
---
Patch valkey for CVE-2025-49112
- **CVE-2025-49112**
Astrolab Reference: https://github.com/valkey-io/valkey/commit/374718b2a365ca69f715d542709b7d71540b1387
Going with this reference for obtaining the patch
**patch details:**
patch applies cleanly without any modification.
- New File: SPECS/valkey/CVE-2025-49112.patch
- Modified: SPECS/valkey/valkey.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-49112
> [Low] Patch valkey for CVE-2025-49112

- SPECS/coredns/CVE-2025-47950.patch
- SPECS/coredns/coredns.spec
---
Address CVE-2025-47950
Upstream Patch Reference: https://github.com/coredns/coredns/commit/efaed02c6a480ec147b1f799aab7cf815b17dfe1
Upstream patch applies cleanly? 
**NO**
hunk Failed for 4 of the 10 files.
List of files unavailable/skipped during backporting
- None: All 10 files listed in the upstream patch were included during patch creation.
Note: There is an existing test failure for this package and I verified that it was not introduced during this CVE fix.
- modified: SPECS/coredns/coredns.spec
- modified: SPECS/coredns/CVE-2025-47950.patch
**NO**
- #NA
- https://nvd.nist.gov/vuln/detail/CVE-2025-47950
- Patch applies cleanly during package …
> [HIGH] Patch coredns for CVE-2025-47950

- SPECS/valkey/CVE-2025-27151.patch
- SPECS/valkey/valkey.spec
---
Patch valkey for CVE-2025-27151
**CVE-2025-27151**
**patch details:**
- Patch Modified: No
- Patch applies cleanly without any modification.
- Astrolab Reference: https://github.com/valkey-io/valkey/commit/73696bf6e2cf754acc3ec24eaf9ca6b879bfc5d7. Going with this reference for obtaining the patch
- SPECS/valkey/CVE-2025-27151.patch
- SPECS/valkey/valkey.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-27151
- Verified patch is applied.
> [Medium] Patch valkey for CVE-2025-27151

- SPECS/dasel/CVE-2024-45338.patch
- SPECS/dasel/CVE-2025-22872.patch
- SPECS/dasel/dasel.spec
---
Patch dasel for CVE-2024-45338 & CVE-2025-22872
- CVE-2024-45338.patch is applied without modifications. 
Upstream Patch link : https://github.com/golang/net/commit/8e66b04771e35c4e4125e8c60334b34e2423effb
- CVE-2025-22872.patch is modified to remove token_test.go file which is not present in our source.
Upstream Patch link : https://github.com/golang/net/commit/e1fcd82abba34df74614020343be8eb1fe85f0d9
- SPECS/dasel/CVE-2024-45338.patch
- SPECS/dasel/CVE-2025-22872.patch
- SPECS/dasel/dasel.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-45338 …
> [MEDIUM] Patch dasel for CVE-2024-45338 & CVE-2025-22872

- SPECS-EXTENDED/rasqal/define-printf.patch
- SPECS-EXTENDED/rasqal/rasqal-configure-c99-2.patch
- SPECS-EXTENDED/rasqal/rasqal.spec
---
rasqal: fixed build
Depends on: (raptor2) https://github.com/microsoft/azurelinux/pull/12845
- rasqal.spec
**NO**
- #xxxx
> rasqal: fixed build

- SPECS/pam/CVE-2025-6020.patch
- SPECS/pam/Upgrade-pam_namespace-to-1.7.0-and-post-11-patches.patch
- SPECS/pam/pam.spec
- SPECS/pam/sync_pam_namespace_module_to_version_1.7.0.patch
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
patch pam for CVE-2025-6020
- patch is backported.
Reference: https://launchpadlibrarian.net/799962342/pam_1.5.3-5ubuntu5.4_source.changes
- pam.spec
- Upgrade-pam_namespace-to-1.7.0-and-post-14-patches.patch
- CVE-2025-6020.patch
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-6020
- Verified patches are applied.
> [High] patch pam for CVE-2025-6020

- SPECS/ruby/CVE-2025-6442.patch
- SPECS/ruby/ruby.spec
---
Patch `ruby` for CVE-2025-6442
- Patch found in astrolabe, modified by me so that it would apply. Link: https://github.com/ruby/webrick/commit/ee60354bcb84ec33b9245e1d1aa6e1f7e8132101.patch
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-6442
- Local build
- Patch applies:
> [High] Patch ruby for CVE-2025-6442

- toolkit/docs/building/prerequisites-mariner.md
- toolkit/docs/building/prerequisites-mariner.sh
- toolkit/docs/building/prerequisites-ubuntu.md
- toolkit/docs/building/prerequisites-ubuntu.sh
- toolkit/scripts/toolkit.mk
- toolkit/scripts/tools.mk
---
Separate out the tooling parts of this previous PR https://github.com/microsoft/azurelinux/pull/13991 
- Update prereqs documents with new flow
- Add new make option `install-prereqs-and-configure`
- Add new warning to go version to consider new targets
**NO**
- New Ubuntu 22.04 VM
- fresh repo clone
- run `sudo make install-prereqs-and-configure` -> `sudo reboot`
- `sudo make build-packages DAILY_BUILD_ID=lkg REBUILD_TOOLS=y SRPM_PACK_LIST=words PACKAGE_REBUILD_LIST=words -j100`
- New Azure Linux 3.0 VM
- fresh repo clone
- run `sudo make install-prereqs-and-configure` -> `sudo reboot`
- `sudo make build-packages DAILY_BUILD_ID=lkg …
> add install-prereqs-and-configure option, update docs

- .pipelines/containerSourceData/scripts/PublishContainers.sh
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> detach old eol annotations

- SPECS-EXTENDED/paps/paps-0.6.8-glib282.patch
- SPECS-EXTENDED/paps/paps-c99.patch
- SPECS-EXTENDED/paps/paps-fix-build.patch
- SPECS-EXTENDED/paps/paps-fix-cpi.patch
- SPECS-EXTENDED/paps/paps-fix-src-to-paps.patch
- SPECS-EXTENDED/paps/paps-glib282.patch
- SPECS-EXTENDED/paps/paps.signatures.json
- SPECS-EXTENDED/paps/paps.spec
- cgmanifest.json
---
Upgrade: paps version to 0.8.0
-SPECS-EXTENDED/parallel/parallel.signatures.json
-SPECS-EXTENDED/parallel/parallel.spec
**NO**
- #xxxx
> Upgrade: paps version to 0.8.0

- SPECS-EXTENDED/foomatic-db/foomatic-db.signatures.json
- SPECS-EXTENDED/foomatic-db/foomatic-db.spec
- cgmanifest.json
---
foomatic-db: Update to version 4.0.20241027
- python-cups
SPECS-EXTENDED/foomatic-db/foomatic-db.signatures.json
SPECS-EXTENDED/foomatic-db/foomatic-db.spec
**NO**
- #xxxx
> foomatic-db: Upgrade to version 4.0.20250311

- SPECS-EXTENDED/PyGreSQL/PyGreSQL.signatures.json
- SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec
- cgmanifest.json
---
Upgrade PyGreSQL version to 6.0.1
-SPECS-EXTENDED/PyGreSQL/PyGreSQL.signatures.json
-SPECS-EXTENDED/PyGreSQL/PyGreSQL.spec
**NO**
- #xxxx
>     Upgrade PyGreSQL version to 6.0.1

- SPECS/yasm/CVE-2024-22653.patch
- SPECS/yasm/yasm.spec
---
Patch yasm for CVE-2024-22653
- No modification made to the upstream patch.
- Upstream Patch Reference: https://patch-diff.githubusercontent.com/raw/yasm/yasm/pull/263.diff [Same as found in Astrolabe]
- SPECS/yasm/CVE-2024-22653.patch
- SPECS/yasm/yasm.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2024-22653
[yasm-1.3.0-17.cm2.src.rpm.log](https://github.com/user-attachments/files/20863705/yasm-1.3.0-17.cm2.src.rpm.log)
- Pipeline build id: 850230
- Buddy Build link : https://dev.azure.com/mariner-org/mariner/_build/results?buildId=850230&view=results
> [MEDIUM] Patch yasm for CVE-2024-22653

- SPECS/libtpms/CVE-2025-49133.patch
- SPECS/libtpms/libtpms.spec
---
Patch libtpms for CVE-2025-49133
- No modification made to the upstream patch. 
- Upstream Patch Reference : https://github.com/stefanberger/libtpms/commit/9f9baccdba9cd3fc32f1355613abd094b21f7ba0
- SPECS/libtpms/CVE-2025-49133.patch
- SPECS/libtpms/libtpms.spec
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-49133
[libtpms-0.9.6-8.azl3.build.log](https://github.com/user-attachments/files/20774244/libtpms-0.9.6-8.azl3.src.rpm.log)
[libtpms-0.9.6-8.azl3.test.log](https://github.com/user-attachments/files/20774255/libtpms-0.9.6-8.azl3.src.rpm.test.log)
> [MEDIUM] Patch libtpms for CVE-2025-49133

- SPECS/nodejs/CVE-2025-23166.patch
- SPECS/nodejs/nodejs18.spec
---
[High] Patch nodejs for CVE-2025-23166
Astrolabe patch reference: https://github.com/nodejs/node/commit/6c57465920cf1b981a63031e71b1e4a73bf9beaa
- New file: CVE-2025-23166.patch
- Modified file: nodejs18.spec
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-23166
- [Buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=866895&view=results) log
> [High] Patch nodejs18 for CVE-2025-23166

- SPECS/krb5/CVE-2025-3576.patch
- SPECS/krb5/krb5.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch krb5 for CVE-2025-3576
- CVE-2025-3576 patch not found in Astrolabe, found patches in https://security-tracker.debian.org/tracker/CVE-2025-3576
- Two patches are found for single CVE, hence combined both into a single patch.
- No modification is made for the upstream patch.
Upstream Patch Reference link: 
1. https://github.com/krb5/krb5/commit/2cbd847e0e92bc4e219b65c770ae33f851b22afc
2. https://github.com/krb5/krb5/commit/1b57a4d134bbd0e7c52d5885a92eccc815726463
- SPECS/krb5/CVE-2025-3576.patch
- SPECS/krb5/krb5.spec
**YES**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2025-3576
- Pipeline build id: 847216 …
> [MEDIUM] Patch krb5 for CVE-2025-3576

- toolkit/imageconfigs/full-64k-arm64.yaml
- toolkit/imageconfigs/postinstallscripts/imagecustomizer/isoinstaller_postinstalltask.sh
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Copy the installer RPMs

- SPECS/libarchive/CVE-2025-5914.patch
- SPECS/libarchive/CVE-2025-5915.patch
- SPECS/libarchive/CVE-2025-5916.patch
- SPECS/libarchive/CVE-2025-5917.patch
- SPECS/libarchive/CVE-2025-5918.patch
- SPECS/libarchive/libarchive.spec
- toolkit/resources/manifests/package/pkggen_core_aarch64.txt
- toolkit/resources/manifests/package/pkggen_core_x86_64.txt
- toolkit/resources/manifests/package/toolchain_aarch64.txt
- toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> Patch libarchive for CVE-2025-5914, CVE-2025-5915, CVE-2025-5916, CVE-2025-5917, CVE-2025-5918

- SPECS/git/git.spec
---
- **git: git fix git-subtree sub-package**
- **git: git fix git-subtree sub-package**
**NO**
- #13907
- NA
- Pipeline build id: [PR-13954](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=827561&view=results)
> git: fix git-subtree subpackage

- SPECS/doxygen/CVE-2025-6140.patch
- SPECS/doxygen/doxygen.spec
---
Patch doxygen for CVE-2025-6140
Patch Modified - No 
Astrolabe Patch Reference: https://github.com/gabime/spdlog/commit/10320184df1eb4638e253a34b1eb44ce78954094
- new: SPECS/doxygen/CVE-2025-6140.patch
- modified: SPECS/doxygen/doxygen.spec
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-6140
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=863100&view=results
> Patch doxygen for CVE-2025-6140 [Medium]

- SPECS/libnvidia-container/libnvidia-container.signatures.json
- SPECS/libnvidia-container/libnvidia-container.spec
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json
- SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
- cgmanifest.json
---
Upgrade nvidia-container-toolkit and libnvidia-container to version 1.17.8 to resolve CVE-2025-23266 and CVE-2025-23267
- Upgrade nvidia-container-toolkit to version 1.17.8
- upgrade libnvidia-container to version 1.17.8
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-23266
- https://nvd.nist.gov/vuln/detail/CVE-2025-23267
- PR Check
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=878921&view=results
> [2.0] Upgrade nvidia-container-toolkit and libnvidia-container to 1.17.8 to resolve CVE-2025-23266

- SPECS/valkey/valkey.signatures.json
- SPECS/valkey/valkey.spec
- cgmanifest.json
---
Update `valkey` to `8.0.4` to fix CVE-2025-32023, CVE-2025-48367
- CVE-2025-32023 
- CVE-2025-48367
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2025-32023
- https://nvd.nist.gov/vuln/detail/CVE-2025-48367
- Local build
> [High] Update valkey to fix CVE-2025-32023, CVE-2025-48367

- SPECS-EXTENDED/libappstream-glib/libappstream-glib.signatures.json
- SPECS-EXTENDED/libappstream-glib/libappstream-glib.spec
- cgmanifest.json
---
upgrade libappstream-glib veesion to 0.8.3
- libappstream-app.spec
- libappstream-app.signatures.json
**NO**
- #xxxx
> Upgrade libappstream-glib version to 0.8.3

- SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros-drop-yaml.patch
- SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros-epoch-in-req.patch
- SPECS-EXTENDED/fonts-rpm-macros/fonts-rpm-macros.spec
- SPECS-EXTENDED/fonts-rpm-macros/update_for_azl.patch
---
fixed build for fonts-rpm-macros
- fonts-rpm-macros.spec
**NO**
- #xxxx
> fixed build for fonts-rpm-macros

- toolkit/imageconfigs/osguard-amd64.yaml
---
Adds usr verity root hash export into the OSGuard image definition. This is needed for signing of said root hash.
**NO**
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=894735&view=results and manually deployed VM in Azure.
> Export osguard root hash for signing

- SPECS/python3/CVE-2025-123.patch
- SPECS/python3/python3.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
> addinga dummy fix for py

- SPECS/sdbus-cpp/sdbus-cpp.spec
---
Fix warning from %post and %postun in sdbus-cpp.spec
- remove newlines to allow -p /sbin/ldconfig to work as intended for %post and %postun
**NO**
- Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=794311&view=results
- [this bug](https://microsoft.visualstudio.com/OS/_workitems/edit/57246961)
> Fix post and postun sections in sdbus-cpp.spec

- .github/workflows/verify-osguard-imageconfigs.yml
- toolkit/scripts/generate-osguard-imageconfigs.sh
---
Since we are now generating osguard configurations from templates, there is a possibility the template changes get out-of-sync with what is committed. Add github action check to verify osguard config generation from templates always match the config present in the default location, otherwise fail to block PR.
**NO**
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/14673
- Config generation matches checked-in config (expect pass) - https://github.com/christopherco/CBL-Mariner/actions/runs/16957933023/job/48063745741?pr=19
- Config generation differs from checked-in config (expect fail) -> …
> ci: introduce osguard imageconfig verifier

- toolkit/imageconfigs/files/osguard/selinux-ci-uki.semanage
- toolkit/imageconfigs/osguard-amd64.yaml
- toolkit/imageconfigs/templates/osguard-base.yaml
---
Remove duplicate veritysetup entry.
Remove commented-out packages.
Create an selinux-ci-uki.semanage in osguard files and reference file from new location.
**NO**
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/14673
- Pipeline build id: [899361](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=899361&view=results)
> refactor: clean up osguard base definition

- toolkit/imageconfigs/files/linuxguard/selinux-ci-uki.semanage
- toolkit/imageconfigs/files/osguard/selinux-ci-uki.semanage
- toolkit/imageconfigs/scripts/common/selinux-ci-config.py
---
tardev-snapshotter is not present or used in our linuxguard / osguard
images. So remove SELinux label for it.
Also enable azureci_prod SELinux module to prevent tampering with
SELinux and IPE settings at runtime.
**NO**
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/14632
- Pipeline build id: [14546](https://github.com/microsoft/azurelinux/pull/14546)
> OS Guard: Remove unnecessary SELinux context mapping and enable SELinux and IPE lockout module

- SPECS/graphviz/graphviz.spec
---
- Enable pdf support in graphviz
- Modified file: graphviz.spec
**NO**
- #xxxx
- Build log from local VM.
- <img width="626" height="302" alt="image" src="https://github.com/user-attachments/assets/523ad3ea-9721-4adb-93a5-8b1f77b48767" />
- [graphviz-2.42.4-13.azl3.src.rpm.log](https://github.com/user-attachments/files/21849282/graphviz-2.42.4-13.azl3.src.rpm.log)
- [graphviz-2.42.4-13.azl3.src.rpm.test.log](https://github.com/user-attachments/files/21849322/graphviz-2.42.4-13.azl3.src.rpm.test.log)
> Bug 58271905: Enable pdf support in graphviz

- SPECS/kubevirt/CVE-2024-33394.patch
- SPECS/kubevirt/kubevirt.spec
---
Patch kubevirt for CVE-2024-33394
Astrolabe Patch Reference: https://github.com/kubevirt/kubevirt/pull/12089/commits/772bb22826affed017e240822486ac3cabba4606
- new: SPECS/kubevirt/CVE-2024-33394.patch
- modified: SPECS/kubevirt/kubevirt.spec
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2024-33394
- Local build
- Build is successful -
[kubevirt-1.2.0-19.azl3.src.rpm.log](https://github.com/user-attachments/files/21259437/kubevirt-1.2.0-19.azl3.src.rpm.log)
> [Medium] Patch kubevirt for CVE-2024-33394

- toolkit/imageconfigs/osguard-amd64.yaml
- toolkit/imageconfigs/osguard-ci-amd64.yaml
- toolkit/imageconfigs/templates/osguard-base.yaml
---
The "which" binary is generally expected to be available in the base image so include the which package.
**NO**
- https://dev.azure.com/mariner-org/mariner/_workitems/edit/14884
- Pipeline build id: [911744](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=911744&view=results)
> osguard: add "which" package to OS Guard base images

- SPECS-EXTENDED/python-genshi/python-genshi.signatures.json
- SPECS-EXTENDED/python-genshi/python-genshi.spec
- cgmanifest.json
---
- SPECS-EXTENDED/python-genshi/python-genshi.signatures.json
- SPECS-EXTENDED/python-genshi/python-genshi.spec
**YES/NO**
- #xxxx
> Upgrade: python-genshi to version 0.7.9

- SPECS-EXTENDED/python-betamax/python-betamax.signatures.json
- SPECS-EXTENDED/python-betamax/python-betamax.spec
- cgmanifest.json
---
This PR is to upgrade the package python-betamax to version 0.9.0
- SPECS-EXTENDED/python-betamax/python-betamax.signatures.json
- SPECS-EXTENDED/python-betamax/python-betamax.spec
**NO**
- #xxxx
- Local Build
> Upgrade: python-betamax to version 0.9.0

- SPECS/kata-containers/kata-containers.signatures.json
- SPECS/kata-containers/kata-containers.spec
- cgmanifest.json
---
Upgrade kata to https://github.com/microsoft/kata-containers/releases/tag/3.19.1.kata1
- kata
**NO**
- CI: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=910801&view=results [failed due to test flake] :
- test reruns: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=910878&view=results and https://dev.azure.com/mariner-org/mariner/_build/results?buildId=911556&view=results
> Upgrade Kata packages

- SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.signatures.json
- SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.spec
- cgmanifest.json
---
This PR is to upgrade the package perl-XML-Writer to version 0.900
- SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.signatures.json
- SPECS-EXTENDED/perl-XML-Writer/perl-XML-Writer.spec
**NO**
- #xxxx
- Local Build. (needs to we build along with perl-Algorithm-Diff to resolve the Dependencies)
> Upgrade: perl-XML-Writer to version 0.900

- toolkit/tools/internal/azureblobstorage/azureblobstorage.go
- toolkit/tools/srpmpacker/srpmpacker.go
Just some proposed tweaks instead of comments in the original PR.
> Proposed tweaks.

- SPECS-EXTENDED/resource-agents/resource-agents.signatures.json
- SPECS-EXTENDED/resource-agents/resource-agents.spec
- cgmanifest.json
---
Upgrade: resource-agents version to 1.16.0
Please build following package with resource-agents:
- libnet
- perl-MailTools
- perl-IO-Socket-INET6
- perl-Net-IMAP-Simple-SSL
- SPECS-EXTENDED/resource-agents/resource-agents.signatures.json
- SPECS-EXTENDED/resource-agents/resource-agents.spec
**NO**
- #xxxx
> Upgrade: resource-agents version to 4.16.0

- SPECS-EXTENDED/libpeas/libpeas.signatures.json
- SPECS-EXTENDED/libpeas/libpeas.spec
- cgmanifest.json
---
Upgrade: libpeas version to 1.36.0
-  SPECS-EXTENDED/libpeas/libpeas.signatures.json
- SPECS-EXTENDED/libpeas/libpeas.spec
**NO**
- #xxxx
> Upgrade: libpeas version to 1.36.0

- SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.signatures.json
- SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.spec
- cgmanifest.json
---
perl-Test-Script version to 1.29
Please build following package with perl-Test-Scipt:
perl-Test-Simple
- Depends on #12946 
perl-Term-Table
- Depends on #13019
Build along with following 16 packages:
"perl-Term-Table sombok perl-Unicode-LineBreak perl-Encode-EUCJPASCII perl-MIME-Charset libdatrie libthai perl-Term-Size-Perl perl-Term-Size-Any perl-App-FatPacker perl-Module-Pluggable perl-Importer libthai perl-Scope-Guard perl-Sub-Info perl-Probe-Perl perl-Test2-Suite perl-Test-Script"
- SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.signatures.json
- SPECS-EXTENDED/perl-Test-Script/perl-Test-Script.spec
**NO**
- …
> Upgrade: perl-Test-Script version to 1.29

- SPECS-EXTENDED/gl-manpages/gl-manpages.spec
---
- gl-manpages: Build error fix
- Build error fix
**NO**
- #xxxx
> gl-manpages: Build error fix

- SPECS/keras/CVE-2025-8747.patch
- SPECS/keras/keras.spec
This is an auto-generated pull request to cherry-pick commit 8ce78fb41e433ba2053e58325014ad143f069181 to aaruagrawal/autoPRdummy3.0-dev. Original PR: #14485
> [AUTO-CHERRYPICK] [High] Patch keras for CVE-2025-8747 - branch aaruagrawal/autoPRdummy3.0-dev

- SPECS-EXTENDED/mythes/mythes.signatures.json
- SPECS-EXTENDED/mythes/mythes.spec
- cgmanifest.json
---
Upgrades mythes to version 1.2.5
- modified:   SPECS-EXTENDED/mythes/mythes.signatures.json
- modified:   SPECS-EXTENDED/mythes/mythes.spec
**NO**
- NA
- NA
- local build
> Upgraded mythes to version 1.2.5

- .pipelines/containerSourceData/scripts/PublishContainers.sh
- SPECS/azurelinux-image-tools/azurelinux-image-tools.signatures.json
- SPECS/azurelinux-image-tools/azurelinux-image-tools.spec
- cgmanifest.json
---
- Updates Image Customizer from 0.19.0 to v1.0.0 GA release
- Changes 0.19 → 0.19.0 for imagecustomizer containers
- Adds latest tag that gets overridden with each new version
- Only affects imagecustomizer, no impact on other containers
- Maintains backward compatibility for all other container types
**NO**
> Update ImageCustomizer to v1.0.0 and add semantic version and latest tag support for imagecustomizer golden container

- SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.signatures.json
- SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.spec
- cgmanifest.json
---
Upgrades perl-File-MimeInfo to version 0.35
Please build following packages with perl-File-MimeInfo:
perl-BSD-Resource 
perl-IPC-System-Simple 
perl-File-BaseDir 
perl-File-DesktopEntry
Also depends on https://github.com/microsoft/azurelinux/pull/13477
- Change: SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.signatures.json
- Change: SPECS-EXTENDED/perl-File-MimeInfo/perl-File-MimeInfo.spec
- Change: cgmanifest.json
**NO**
- NA
- NA
- local build
> Upgrades perl-File-MimeInfo to version 0.35

- SPECS/nginx/nginx.spec
---
Enable nginx package to include the stream SSL preread module
- Enable stream ssl preread module
**NO**
- https://microsoft.visualstudio.com/OS/_workitems/edit/58672870
- 
- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=897901&view=results
> Bug 58672870: Enable stream ssl preread in nginx
