SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
**What does the PR accomplish, why was it needed?**
This change stops mariner-release package from depending on /bin/sh. This is a part of the cleanup effort.
- Remove empty %post section from mariner-release
**YES**
- Local build passed.
=> Remove %post section from mariner-release

SPECS/etcd/etcd.signatures.json, SPECS/etcd/etcd.spec, cgmanifest.json
---
- Update etcd to v3.3.25 to fix several CVEs.
- Update etcd to v3.3.25 to fix CVE-2020-15106,  CVE-2020-15112, CVE-2020-15114, and CVE-2020-15115.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-15106
- https://nvd.nist.gov/vuln/detail/CVE-2020-15112
- https://nvd.nist.gov/vuln/detail/CVE-2020-15114
- https://nvd.nist.gov/vuln/detail/CVE-2020-15115
- Local build
=> Update etcd to 3.3.25 for CVE fixes

.github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/go-test-coverage.yml
---
The Github Actions workflows were only targeting the main branch. This PR will expand that to also run the CI for dev, 1.0, 1.0-dev branches. Also fixed an issue with the cgmanifest CI which made it only run properly for PRs.
- Target `[ main, dev, 1.0* ]` for pushes and PRs for all existing workflows
- Update `check-package-cgmanifest.yml` to check the cgmanifest during pushes as well
NO
- Ran workflows on my fork (see https://github.com/dmcilvaney/CBL-Mariner/pull/8)
=> Update workflows to target all current branches

toolkit/docs/building/building.md
---
Expand and clarify the quickstart guide to better reflect what a new user may want to experience.
- Update the quickstart guide to include:
- No package build ISO/VHDX options for quick builds
- Streamline the toolchain a bit (we don't need to use the toolchain archive for local builds)
- Provide non-bootstrap build options
NO
- Validated with local builds following the instructions (minus full bootstrap build, those instructions are unchanged)
=> Expand on the quickstart guide

SPECS/qemu-kvm/CVE-2020-15863.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
- Change
- Change
- Change
**YES**
NO
- #xxxx
=> fix qemu CVE-2020-15863

toolkit/Makefile
---
This PR is need so minor-id version get into account when file exist (align with a build pipeline change)
minor makefile change
NO
=> match new naming rule for config files (version minor id)

SPECS/tpm2-tools/tpm2-tools.signatures.json, SPECS/tpm2-tools/tpm2-tools.spec, SPECS/tpm2-tss/tpm2-tss.signatures.json, SPECS/tpm2-tss/tpm2-tss.spec, cgmanifest.json
Signed-off-by: Daniel McIlvaney <damcilva@microsoft.com>
---
Updating TPM2 tools gives access to a the tpm2_eventlog tool, among other improvements. tpm2-tss is updated to 2.4.0 to support the newer tpm2 tools.
- Update tpm2-tss to version 2.4.0
- Update tpm2-tools to version 4.2
NO
- Local builds, tested on a hyper-v VM with TPM enabled
- Tested as part of the IMA changes
=> Update tpm2 tools to 4.2, tss to 2.4.0

toolkit/imageconfigs/full.json
---
Currently, when installing CBL-Mariner via ISO, the ISO will
install the standard kernel package or the kernel-hyperv package
depending on if the platform is a HyperV VM or not.
The HyperV kernel is still under evaluation so use the standard kernel
package across the board.
- Delete `hyperv` entries in `full.json`'s `KernelOptions`
NO
- #129 
- Local build
=> imageconfigs/full: Always install the standard kernel package

SPECS/mariner-repos/mariner-preview.repo, SPECS/mariner-repos/mariner-repos.signatures.json, SPECS/mariner-repos/mariner-repos.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh
---
We're adding a new .repo file to enable discovery and access to the preview repository containing packages in their pre-release version.
- Extended `mariner-repos` with the `mariner-repos-preview` subpackage.
No.
- Local build of the `mariner-repos` package.
=> Adding new 'preview' repository.

SPECS/libarchive/libarchive.spec, SPECS/libassuan/libassuan.spec, SPECS/pkgconf/pkgconf.spec
---
Fix entries in three spec's changelogs that were not merged correctly in https://github.com/microsoft/CBL-Mariner/pull/163 
- Restore correct license changelog line in `libarchive`.
- Restore correct license changelog line in `libassuan`.
- Add missing changelog entry in `pkgconf` for revision `1.7.0-3`
NO
- Local build
=> Spec changelog fixes

cgmanifest.json
---
Updating `cgmanifest.json` to prevent failures from a recently-added PR check.
- Updated `cgmanifest.json` to match the packages currently in the repo.
No.
- The PR check no longer fails.
=> Updating cgmanifest.json.

SPECS/librelp/librelp.spec
---
The `valgrind` tests on `librelp` was diabled as they required unstripped `ld.so`. In the current `glibc` package this problem is already resolved, so enable those tests.
- Remove the workaround comment and `sed` call inside `librelp.spec`'s `%check` seciton.
YES
**NO**
- #xxxx
=> Enable valgrind tests for librelp

SPECS/cloud-init-vmware-guestinfo/cloud-init-vmware-guestinfo.spec
---
Adding a missing `%{?dist}` to align with our package-naming requirements.
- Added a `%{?dist}` tag.
No.
- No tests, a simple change.
=> Adding a missing '%{?dist}' tag.

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [ x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ x] Documentation has been updated to match any changes to the build system
- [ x] Ready to merge
---
This change fix an …
=> enable fetching RPMs from pacakges.microsoft.com for Docker based build

toolkit/tools/grapher/grapher.go
---
**tl;dr**: We should recompute cycles after manipulating the graph.
During cycle resolution the graph could be corrupted. After running Johnson's algorithm to detect cycles we attempt to fix all detected cycles and then rerun Johnson's again. However, fixing a single cycle may resolve or alter other cycles. This results in having a stale summary of cycles which may refer to edges in the graph that no longer exist. If we attempt to fix a stale cycle it may create an unsolvable graph.
The fix is to recompute all cycles in the graph after fixing a single cycle rather than batching them.
- Rerun Johnson's algorithm after each cycle fixed.
- Improve logging in cycle resolution.
- Fix …
=> Fix graph corruption during cycle resolution

toolkit/.gitignore, toolkit/scripts/toolchain/create_toolchain_in_container.sh
- toolchain-local-wget-list was been left at the end of a toolchain build. It shows up on `git status` when toolchain is built locally.
- Another solution would be adding it to `.gitignore`.
---
toolchain-local-wget-list was been left at the end of a toolchain build. It shows up on `git status` when toolchain is built locally.
- Remove toolchain-local-wget-list after it has been used by Docker.
YES
**NO**
- #xxxx
- Local build
=> Remove toolchain-local-wget-list after use

SPECS/libffi/libffi.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
Use gnu.org server to download libffi sourcecode, instead of sourceaware.org ftp server. Recent internal builds have been frequently timing out when accessing the sourceaware ftp.
- Update toolchain-remote-wget-list with new URL
- Update libffi.spec with new URL, as well as the release number and references to this package
**YES**
NO
- N/A
- N/A
- Locally built toolchain past the point of downloading and verifying this libffi source tarball.
=> Pull libffi source from more reliable gnu.org server

.github/workflows/mariner-spec-cleaner.patch
---
Update spec-cleaner to commit dd195077
- Fix define macro ordering
- Fix parsing of dates in changelog
- Stop removing soft dependencies
- Additions to bracket exclude list
**NO**
=> Update spec-cleaner to dd195077

.github/workflows/mariner-spec-cleaner.patch
---
Update mariner-spec-cleaner.patch after fixing upstream patch generation pipeline handling of unicode characters
- Update mariner-spec-cleaner patch with proper unicode encoding
**NO**
- Local testing of patch file
=> Unicode patch for mariner-spec-cleaner

.github/pull_request_template.md
---
While adding/removing a new package, one needs to update the license files under `./SPECS/LICENSES-AND-NOTICES`. Add a check in the PR template.
- Add a new line to the PR template about the license files.
**YES**
NO
- #xxxx
=> Add a new check in the PR template for license files

SPECS/brotli/brotli.spec, SPECS/gzip/gzip.spec, SPECS/python-certifi/python-certifi.spec, toolkit/resources/manifests/package/macros.override, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix some check tests for the specs listed below. Disable VIM check test because it is causing a hang
- Fix check tests for brotli, gzip and python-certifi
- Update toolchain manifest for gzip
- Disable VIM check test in macros.override
**YES**
NO
=> Fix check tests for brotli, gzip and python-certifi

SPECS/unbound/CVE-2020-12662.patch, SPECS/unbound/unbound.spec
---
- Apply upstream patch that fixes CVE-2020-12662 and CVE-2020-12663.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-12662
- https://nvd.nist.gov/vuln/detail/CVE-2020-12663
=> Patch unbound CVE-2020-12662 and CVE-2020-12663

SPECS/ant/ant.spec, cgmanifest.json
---
Resolve CVE-2020-11979
- Change version from 1.10.8 to 1.10.9
- Resolve CVE-2020-11979
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-11979
- Local Build
=> Fix Ant CVE-2020-11979

SPECS/sqlite/sqlite.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Nopatching CVE-2015-3717 because it only impacts iOS and OS X.
CVE tracker references from other distros: https://security-tracker.debian.org/tracker/CVE-2015-3717 
- Nopatch CVE-2015-3717.
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2015-3717
- Local build
=> Nopatch sqlite CVE-2015-3717

SPECS/omi/buildtool.patch, SPECS/omi/omi.signatures.json, SPECS/omi/omi.spec, cgmanifest.json
---
Adds the OMI package to the public CBL-Mariner repository.
- `omi` package added to public repository
- Source file updated to point to current release (1.6.6)
NO
- Locally built
=> Adding omi package

SPECS/ant/ant.signatures.json
---
The ant signatures file is referencing an old source, regenerate it.
- Regenerate ant signatures.
NO
- Local srpm generation.
=> Update ant signatures

SPECS/cairo/CVE-2018-19876.patch, SPECS/cairo/cairo.spec
---
Patch CVE-2018-19876
Patch CVE-2018-19876
No
None
https://nvd.nist.gov/vuln/detail/CVE-2018-19876
Local build
=> Patch CVE-2018-19876 (Cairo)

SPECS/redis/CVE-2020-14147.patch, SPECS/redis/redis.spec
---
Fix CVE-2020-14147
- Add patch file CVE-2020-14147.patch
- Fix CVE-2020-14147
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2020-14147
- Local Build
=> Fix redis CVE-2020-14147

SPECS/openldap/CVE-2015-3276.patch, SPECS/openldap/openldap.spec
---
Fix CVE-2015-3276
- Use autosetup
- Add patch to resolve CVE-2015-3276
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2015-3276
- Local Build
=> Fix openldap CVE-2015-3276

SPECS/cloud-init/CVE-2020-8631.patch, SPECS/cloud-init/CVE-2020-8632.patch, SPECS/cloud-init/cloud-init.spec
---
Patch CVE-2020-8631 and CVE-2020-8632
Patch CVE-2020-8631 and CVE-2020-8632
No
None
- https://nvd.nist.gov/vuln/detail/CVE-2020-8632
- https://nvd.nist.gov/vuln/detail/CVE-2020-8631
- Local build
=> Patch CVE-2020-8631 and CVE-2020-8632 in cloud-init

.github/pull_request_template.md
---
Small PR template update to keep it up to date
- We recently added `.github/workflows/cgmanifest.json`, keeping that list up to date in the merge checklist
- Update CVE link template with a better template
NO
=> Update PR template- CVE link and new cgmanifest file

SPECS/nginx/CVE-2019-20372.patch, SPECS/nginx/nginx.spec
---
Resolved CVE-2019-20372
- Used autosetup
- Added patch to resolve CVE-2019-20372
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-20372
- Local Build
=> Fix nginx CVE-2019-20372

SPECS/qemu-kvm/CVE-2020-13791.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Patch CVE-2020-13791 in qemu.
Upstream patch:
- https://lists.gnu.org/archive/html/qemu-devel/2020-06/msg00706.html
- https://lists.gnu.org/archive/html/qemu-devel/2020-06/msg00831.html
- Patch CVE-2020-13791 in qemu
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-13791
=> Patch CVE-2020-13791 in qemu

SPECS/net-snmp/net-snmp.signatures.json, SPECS/net-snmp/net-snmp.spec, cgmanifest.json
---
Updating `net-snmp` to fix CVE-2019-20892. Applying a patch required backporting it to our current version and we have no users currently depending on this package, so I've decided to go with updating the package.
- Updated `net-snmp` to version 5.9.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2019-20892
Local package build.
=> Updating `net-snmp` to fix CVE-2019-20892.

SPECS/coreutils/coreutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
No patch CVE-2013-0221 and CVE-2016-2781. CVE-2013-0221 is already fixed, and upstream community agreed to not patch CVE-2016-2781.
- No patch CVE-2013-0221
- No patch CVE-2016-2781
Yes
None
- https://nvd.nist.gov/vuln/detail/CVE-2013-0221
- https://nvd.nist.gov/vuln/detail/CVE-2016-2781
- Local build
=> No patch CVE-2013-0221 and CVE-2016-2781

SPECS/flex/flex.signatures.json, SPECS/flex/flex.spec, SPECS/flex/lex, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
No patch CVE-2019-6293. Upstream community decided to not patch this: https://github.com/westes/flex/issues/414
- No patch CVE-2019-6293
Yes
- None
- https://nvd.nist.gov/vuln/detail/CVE-2019-6293
- Local build
=> No Patch CVE-2019-6293

SPECS/libev/libev.spec
---
libevent-devel and libev-devel both contain header files named event.h, causing conflicts when both -devel packages are required. Split into libev-libevent-devel subpackage to resolve.
Reference: https://src.fedoraproject.org/rpms/libev/blob/master/f/libev.spec
- Split libev-libevent-devel subpackage to resolve event.h conflicts with libevent-devel.
**NO**
=> [dev] Resolve header file conflict between `libevent-devel` and `libev-devel`

SPECS/audit/audit.spec, SPECS/dbus/dbus.spec
---
Add additional provides to `audit` and `dbus` that are commonly used.
- Provide `dbus-libs`.
- Provide `audit-libs-devel`.
- Provide `audit-libs-python3`.
NO
- Local build.
=> [dev] Add additional provides to dbus and audit

SPECS/nghttp2/nghttp2.signatures.json, SPECS/nghttp2/nghttp2.spec, cgmanifest.json
---
Updating `nghttp2` to 1.41.0 to fix CVE-2020-11080.
- Updated `nghttp2` to 1.41.0.
- Addressed linter's suggestions.
- Cleaned-up the spec and verified the license.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2020-11080
Local package build.
=> Updating `nghttp2` to 1.41.0 to fix CVE-2020-11080.

SPECS/dbus/CVE-2019-12749.patch, SPECS/dbus/dbus.spec
---
Patch CVE-2019-12749 in dbus
- Fixes CVE-2019-12749
**No**
- https://nvd.nist.gov/vuln/detail/CVE-2019-12749
- Local build
=> Patch CVE-2019-12749 in dbus

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
Restore code that disables preview repo when set. Was accidentally lost during the merge.
- Restore code that disables preview repo when set.
NO
- Local build.
=> [dev] Restore preview repo support after merge

SPECS/clamav/clamav.signatures.json, SPECS/clamav/clamav.spec, cgmanifest.json
---
Updating `clamav` to fix: CVE-2019-12625, CVE-2019-15961.
- Updated `clamav` to 0.103.0.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2019-12625;
- https://nvd.nist.gov/vuln/detail/CVE-2019-15961;
Local package build.
=> Updating `clamav` to 0.103.0 to fix CVE-2019-12625 and CVE-2019-15961.

SPECS/openssh/openssh.spec
---
No patch CVE-2007-2768. Community agreed to not fix this.
See this discussion: https://bugzilla.suse.com/show_bug.cgi?id=628772&_ga=2.49772064.749617865.1604006580-702856597.1603302979
- No patch CVE-2007-2768
No
None
- https://nvd.nist.gov/vuln/detail/CVE-2007-2768
- Local build
=> OpenSSH: No patch CVE-2007-2768

SPECS/trousers/CVE-2020-24331.nopatch, SPECS/trousers/trousers.spec
---
Add nopatch for CVE-2020-24332 
- CVE-2020-24332 is patched by CVE-2020-24330.patch, adding nopatch to reflect that
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-24332
- Local Build
=> Nopatch for trousers CVE-2020-24332

SPECS/brotli/CVE-2020-8927.patch, SPECS/brotli/brotli.spec
---
Patch CVE-2020-8927
- Use backported patch for CVE-2020-8927
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-8927
- Local build of package
=> Patch CVE-2020-8927 in brotli

toolkit/tools/scheduler/schedulerutils/printresults.go
---
As part of the build summary print any unresolved dependencies that exist. Missing dependencies can result in failed builds, but exactly what package is missing is often buried in the logs. Print this information at the end of the build.
- Print any unresolved nodes as part of the build summary.
NO
=> [dev] Print unresolved dependencies in build summary

toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
`man-pages-5.02.tar.xz` hosting has been moved from https://www.kernel.org/pub/linux/docs/man-pages/man-pages-5.02.tar.xz to https://www.kernel.org/pub/linux/docs/man-pages/Archive/man-pages-5.02.tar.xz
- Update URL for man-pages to use an active URL.
**YES**
- N/A
=> [dev] Update url for raw toolchain man-pages

SPECS/qemu-kvm/CVE-2015-7504.nopatch, SPECS/qemu-kvm/CVE-2016-7161.nopatch, SPECS/qemu-kvm/CVE-2017-14167.nopatch, SPECS/qemu-kvm/CVE-2017-5931.nopatch, SPECS/qemu-kvm/CVE-2018-19665.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Patch CVE-2018-19665 in qemu-kvm
- Use patch listed in NVD to fix CVE-2018-19665
- Remove nopatches associated with incorrect NVD information
NO
- https://nvd.nist.gov/vuln/detail/CVE-2018-19665
- Local build
=> Patch CVE-2018-19665 in qemu

toolkit/scripts/toolchain/container/toolchain-remote-wget-list
---
Cherrypick: https://github.com/microsoft/CBL-Mariner/pull/347
`man-pages-5.02.tar.xz` hosting has been moved from https://www.kernel.org/pub/linux/docs/man-pages/man-pages-5.02.tar.xz to https://www.kernel.org/pub/linux/docs/man-pages/Archive/man-pages-5.02.tar.xz
- Update URL for man-pages to use an active URL.
**YES**
- N/A
=> Update url for raw toolchain man-pages

SPECS/golang/golang-1.13.spec
---
The RPM path macros refer to the paths on the system where the package gets installed, while these paths are local to this single package build. They are not the same thing and may change completely independently from each other. 
- Revert some changes from #326 
- Does not increment the revision number in the package- package has not been built since #326 was merged
NO
- local build
=> Remove RPM path macros from local package build contexts in golang

SPECS/openssh/CVE-2020-14145.nopatch, SPECS/openssh/openssh.spec
---
Nopatching CVE-2020-14145. This issue is considered a won't fix by OpenSSH (see: [here](https://www.fzi.de/fileadmin/user_upload/2020-06-26-FSA-2020-2.pdf)).
- Added a nopatch for CVE-2020-14145.
- Addressed linter's suggestions.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2020-14145
N/A.
=> Nopatching CVE-2020-14145.

SPECS/systemd/systemd.spec
---
Update provide `systemd-unit` to `systemd-units`.
- Update `systemd-unit` to `systemd-units`.
**YES**
- Local build.
=> [dev] Update systemd-units provide

SPECS/python3/CVE-2020-27619.patch, SPECS/python3/python3.signatures.json, SPECS/python3/python3.spec, cgmanifest.json
---
Upgrades python3 package to 3.7.9 to fix several CVEs. Separately patches CVE-2020-27619
- Upgrade Python3 to 3.7.9 to fix several CVEs listed in title
- Additionally, patches CVE-2020-27619
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-27619
- https://nvd.nist.gov/vuln/detail/CVE-2019-20907
- https://nvd.nist.gov/vuln/detail/CVE-2020-26116
- https://nvd.nist.gov/vuln/detail/CVE-2019-18348
- https://nvd.nist.gov/vuln/detail/CVE-2020-14422
- Local build of package
=> Python 3: Upgrade to fix CVE-2019-20907, CVE-2020-26116, CVE-2019-18348, CVE-2020-14422, Patch CVE-2020-27619

SPECS/coreutils/coreutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Our version of coreutils-8.30-i8n-1.patch for coreutils includes fixes for CVE-2013-0222 and CVE-2013-0223, so we nopatch those.
- Nopatch CVE-2013-0222 and CVE-2013-0223
- Change Source0 to use HTTPS
- Remove references to Linux From Scratch in patches- our patches are actually from Red Hat 
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2013-0222
- https://nvd.nist.gov/vuln/detail/CVE-2013-0223
- Local build of package outside toolchain
- Not testing a complete rebuild of the toolchain due to low risk of these changes
=> Nopatch CVE-2013-0222, CVE-2013-0223 in coreutils

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
Package summary JSON files for package builds were always built with the assumption that the package fetcher downloaded and moved them into `[root-dir]/outputrpms`. This is not the case for Docker-based builds, where the packages end up under `[root-dir]/upstream-cached-rpms`. This PR is making that distinction.
- Creating packages summary for correct repo for Docker builds.
- Tooling change, ran `sudo make go-tidy-all` and `sudo make go-test-coverage`.
=> Creating packages summary for correct repo for Docker builds.

toolkit/tools/isomaker/maker.go
Repetition removal suggestions.
=> Repetition removal suggestions.

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
When pam is built in the toolchain environment, cracklib-devel is not installed. This results in pam's auto configure skipping cracklib integration. However pam's cracklib integration is needed by other packages such as shadowutils.
- Install cracklib before pam is built in the toolchain.
**YES**
- Local end to end build.
=> [dev] Install cracklib in toolchain before building pam

toolkit/tools/graphanalytics/graphanalytics.go, toolkit/tools/imager/imager.go, toolkit/tools/internal/buildpipeline/buildpipeline.go, toolkit/tools/internal/network/network.go, toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go, toolkit/tools/internal/pkgjson/pkgjson.go, toolkit/tools/internal/rpm/rpm.go, toolkit/tools/internal/safechroot/safechroot.go, toolkit/tools/isomaker/isomaker.go, toolkit/tools/isomaker/maker.go, toolkit/tools/pkgworker/pkgworker.go, toolkit/tools/scheduler/buildagents/definition.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/depsolver.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/implicitprovides.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/specreader/specreader.go, toolkit/tools/srpmpacker/srpmpacker.go
---
Fix various minor typos in toolkit comments with a spelling linter.
- Fix various minor typos with a spelling linter.
NO
- Built go tools, no logic modified.
=> [dev] Fix minor toolkit typos

SPECS/perl-JSON-Any/perl-JSON-Any.spec, SPECS/perl-List-MoreUtils/perl-List-MoreUtils.spec, SPECS/perl-Net-SSLeay/perl-Net-SSLeay.spec, SPECS/perl-YAML/perl-YAML.spec, SPECS/wget/wget.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Package test dependencies on Perl packages were being installed but not found due to the fact, that `cpan` installs the Perl libraries into user's local Perl library folder, which is not part of the default search path for Perl, so tests failed to load the dependencies they required.
The current fix is temporary, as ideally `BuildRequires: perl(library::name)` should be sufficient, but this that's not the case for `1.0-dev` and we will switch to that model once we integrate the parity changes coming in from `dev`.
- Added an additional `cpan local::lib` line to package tests with dependencies on additional Perl libraries.
No.
=> Adding `local::lib` perl5 library to fix package tests.

SPECS/tcpdump/CVE-2020-8037.patch, SPECS/tcpdump/tcpdump.spec
---
Patch CVE-2020-8037 in tcpdump
- Take upstream patch for CVE-2020-8037
- Lint tcpdump spec to Mariner style
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-8037
- Local build + ran check for affected package
=> Patch CVE-2020-8037 in tcpdump

toolkit/tools/pkgworker/pkgworker.go
---
Some package tests download additional dependencies inside the `%check` section, which may fail due to missing certificates. Installing an additional `ca-certificates` package to the worker chroot **only** for ptest runs.
- Added the `ca-certificates` package for ptest runs.
No.
- Local tools build and a test package build run.
=> Installing `ca-certificates` package for ptest builds.

SPECS/qemu-kvm/CVE-2020-12829.nopatch, SPECS/qemu-kvm/qemu-kvm.spec
---
Tracing the configs indicates that CVE-2020-12829 only affects powerPC and SuperH emulation. We only support native arch emulation so this does not affect us. There is also no back-port of this fix to from 5.0.0 to 4.2.0.
The issue is in the sm501 video driver, CONFIG_SM501 is selected by CONFIG_SAM460EX and CONFIG_R2D (from ppc-softmmu and sh4 targets respectively). We only build the aarch64 and x86_64 targets so this doesn't affect us.
- Nopatch CVE-2020-12829
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-12829
- `make input-srpms`, no functional changes to the package other than version bump.
=> Nopatch QEMU CVE-2020-12829

SPECS/nginx/nginx.spec
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [ x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ x] `sudo make go-tidy-all` and `sudo make …
=> nopatch nginx CVE-2009-4487

SPECS/openssh/CVE-2020-15778.nopatch, SPECS/openssh/openssh.spec
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [ x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ x] `sudo make go-tidy-all` and `sudo make …
=> CVE-2020-15778 - no patch

SPECS/python-setuptools/python-setuptools.spec, SPECS/python3/python3.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
The package `python(3)-setuptools` has a runtime dependency on `python(3)-xml`, which wasn't specified in the spec and thus the package wouldn't work after installation unless you manually also installed its dependency. This PR fixes that.
- Add `Requires` for `python(3)-xml`.
Yes.
=> Adding missing runtime dependency.

toolkit/tools/imagegen/configuration/partitiontabletype.go, toolkit/tools/imagegen/configuration/partitiontabletype_test.go, toolkit/tools/imagegen/diskutils/diskutils.go
---
parted uses the msdos option to create an MBR disk. So let's pass the correct msdos
option to parted instead of mbr when the user wants to make an MBR disk.
- Create new `ConvertToPartedArgument` method to convert a given `PartitionTableType` to its associated `parted` argument
- Add unit tests for `ConvertToPartedArgument` method
- Pass "msdos" option to parted instead of "mbr" in `diskutils`
NO
- Local build
=> diskutils: Add MBR disk setup

SPECS/subversion/subversion.spec
---
Fixing `subversion` ptests.
- Added `BuildRequires` to unblock `subversion` ptests.
No.
=> Fixing `subversion` ptests.

SPECS/json-c/json-c.spec, SPECS/libmodulemd/libmodulemd.spec, SPECS/libpwquality/libpwquality.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix check tests for json-c, libmodulemd, libpwquality
- Modify %check sections
**YES**
NO
=> Fix check tests for json-c, libmodulemd, libpwquality

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- [ x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [ x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ x] `sudo make go-tidy-all` and `sudo make …
=> increment release number for CBL-Mariner November release

toolkit/resources/assets/isomaker/iso_root_static_files/boot/grub2/grub.cfg
---
Update grub command line with inst.stage2 label CDROM. This is required to boot when ISO laydown to USB and boot on Ampere, Cavium SoCs
- Change
- Change
- Change
YES
**NO**
- #xxxx
- Built ISO for Arm64 and X64 with this change. 
Verified Arm64 ISO by laying down to USB, installed Mariner OS and successfully booted on Arm64 Ampere SoC, RPi4 and HyperV VM. 
X64 ISO verified on Intel NUC and HyperV Gen1 and Gen2.
=> Update grub command line required to boot on some specific hardware SoCs 

toolkit/tools/internal/packagerepo/repocloner/rpmrepocloner/rpmrepocloner.go
---
Generalizing and simplifying TDNF output regex for reading RPM repo contents. Currently Docker builds are still not correctly listing the downloaded packages.
- Made the regex ignore the repository name, as it may differ depending on the build and it doesn't matter.
- Simplified the regex and extended a comment explaining what it does.
No.
- Local tools build.
- Pipeline package build in a Docker container.
=> Generalizing and simplifying TDNF output regex for reading RPM repo contents.

toolkit/resources/manifests/package/macros.override
---
Skipping `tdnf` package tests as they tend to hang and block other package tests in our pipeline. We'll investigate and fix the hang separately in another PR.
- Excluded `tdnf` package tests from being executed.
No.
- Pipeline package test build.
=> Skipping `tdnf` package tests.

SPECS/ruby/ruby.spec
---
Unblocking `ruby` test from being run. There are still 80+ failing tests, which will be addressed in a future PR (or a set of PRs, if fixing all in one go would make the PR to big).
- Added `BuildRequires` on `sudo` and `shado-utils` to allow `ruby` package tests to run.
No.
=> Unblocking `ruby` test from being run.

SPECS/WALinuxAgent/WALinuxAgent.spec, SPECS/WALinuxAgent/add-distro.patch
---
In WALinuxAgent, move "waagent" to sbindir from bindir.
Since waagent modifies several system configurations (ex: user accounts, host name, swap space config, etc.), waagent requires root privileges. CentOS, RHEL, and Ubuntu use sbindir instead of bindir. Additionally, other Azure extensions assume waagent exists in sbindir (see "VMEncryption/main/Utils/WAAgentUtil.py" in [Azure Linux Extensions](https://github.com/Azure/azure-linux-extensions))
- Move "waagent" and "waagent2.0" to sbindir from bindir
No
None
None
Local build
=> Move "waagent" to sbindir in WALinuxAgent

SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec, SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec, SPECS/kernel/0002-efi-libstub-tpm-enable-tpm-eventlog-function-for-ARM.patch, SPECS/kernel/kernel.spec
---
Currently, the kernel does not publish the EFI tpm2 eventlog when booting on ARM. There is a v5.5 upstream patch that fixes this issue: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/?id=d99c1ba6a73b9e93e2884b7893fe19e3c082ba03
So backport this patch to our kernel.
- Add kernel patch to publish tpm2 eventlog on ARM
- Bump `kernel-signed-<arch>` release to match the `kernel` release
NO
local build
=> kernel: Add tpm eventlog patch for arm

SPECS/json-glib/json-glib.spec, SPECS/libuv/libuv.spec, SPECS/pango/pango.spec
---
Fix broken check tests for json-glib, libuv, pango packages.
- Modify %check sections
YES
**NO**
=> Fix check tests for json-glib, libuv, pango

toolkit/scripts/pkggen.mk, toolkit/tools/pkgworker/pkgworker.go, toolkit/tools/unravel/unravel.go
---
Current logs when running package tests got very noisy, so I've decreased the warnings to debug messages  and added one warning printed right before the first package starts building.
- Decreased logging level for package builds when running with tests.
No.
- Local tools build.
=> Decreasing logging noise for package test builds.

SPECS/Cython/Cython.spec, SPECS/apr/apr.spec, SPECS/autoconf213/autoconf213.spec, SPECS/librelp/librelp.spec, SPECS/libserf/libserf.spec
---
Fix check tests for Cython, libserf, librelp, apr and autoconf213
- Modify SPECs to fix %check tests
YES
**NO**
=> Fix check tests for Cython, libserf, librelp, apr and autoconf213

SPECS/autoconf213/autoconf213.spec
---
Fix build break:
INFO[0000] Calculating SPECs to repack
WARN[0000] error: bad date in %changelog: Mon Dev 07 2020 Andrew Phelps <anphel@microsoft.com> 2.13-47
- Fix typo
YES
**NO**
=> Fix bad changelog date in autoconf213

SPECS/WALinuxAgent/WALinuxAgent.signatures.json, SPECS/WALinuxAgent/WALinuxAgent.spec, SPECS/WALinuxAgent/add-distro.patch, cgmanifest.json
---
Upgrade WALinuxAgent to latest version to satisfy customer feature request
- Upgrade to version 2.2.52
- Update add-distro.patch
NO
- #xxxx
- Local Build
=> Upgrade WALinuxAgent to 2.2.52

SPECS/openldap/CVE-2020-25692.patch, SPECS/openldap/openldap.spec
---
Patch CVE-2020-25692 in openldap.
- Patch CVE-2020-25692.
NO
https://nvd.nist.gov/vuln/detail/CVE-2020-25692
- Local build.
=> Patch openldap CVE-2020-25692

SPECS/javapackages-tools/javapackages-tools.spec, SPECS/javapackages-tools/remove-epoch-from-java-requires.patch
---
Patch the maven dependency generator in `javapackages-tools` to not prepend an epoch of 1 to required java versions. CBL-Mariner's java is epoch 0, which would exclude it from satisfy any generated java requirements.
- Patch out epoch 1 prepending from the maven dependency generator.
NO
=> [dev] Patch maven dependency generator to remove epoch

SPECS/rpm-ostree/rpm-ostree.spec
---
Fixing `rpm-ostree` ptests. More details in the comments added to the spec.
- Fixed `lib-introspection` ptest.
- Skipped `ucontainer` ptest.
- Removed `sha1` macros from the spec.
- Verified the package's license.
No.
=> Fixing `rpm-ostree` ptests.

SPECS/cpprest/cpprest.spec, SPECS/libpipeline/libpipeline.spec, SPECS/librsync/librsync.spec, SPECS/postgresql/postgresql.spec, toolkit/resources/manifests/package/macros.override, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix the %check tests for packages cpprest, libpipeline, librsync, postgresql. Also enables the %check for the libsoup package, which is working now that networking is enabled during test builds.
- Change specs to resolve %check issues for cpprest, libpipeline, librsync, postgresql
- Modify macros.override to enable libsoup check test
YES
**NO**
=> Fix check tests for cpprest, libpipeline, librsync, postgresql, libsoup

SPECS/audit/audit.spec, SPECS/cni/cni.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/kubernetes/kubernetes-1.16.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/runc/runc.spec, SPECS/telegraf/telegraf.spec
---
We have updated the golang spec to use golang 1.15 (see #420). In order to ensure any package that builds with golang is rebuilt with 1.15 and published to packages.microsoft.com, I have updated the release versions.
- Increment Release version for any spec that "BuildRequires: golang"
YES
**NO**
=> Increment release for all specs building with golang 1.15

SPECS/python-sphinx/python-sphinx.spec
---
Make python2 support optional in python-sphinx and reserve unversioned binaries for python3-sphinx.
- Make python3- package default and python2- optional.
- Reserve unversioned sphinx-* binaries for python3.
- Rename python2 sphinx-* binaries to sphinx-*-2.
**NO**
- Local package build: validate packages with python-sphinx, python3-sphinx dependencies.
=> [dev] Optional python2 support in python-sphinx

SPECS/curl/CVE-2020-8177.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch curl CVE-2020-8177.
Patch obtained from: https://curl.se/docs/CVE-2020-8177.html
- Patch curl CVE-2020-8177
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-8177
- Local toolchain and full package build. (complete)
=> Patch curl CVE-2020-8177

toolkit/docs/building/prerequisites.md
---
Update build machine prerequisite steps to reference the current version of golang, 1.15.
- Change prerequisites
YES
**NO**
- N/A, text change only
=> Update prerequisites with golang 1.15

SPECS/libaio/libaio.spec, SPECS/llvm/llvm.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Modify llvm and libaio SPECS to fix %check test issues
- Fix llvm test
- Fix libaio test
YES
**NO**
- Local build
=> Fix tests for llvm and libaio

SPECS/curl/CVE-2020-8231.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Patch curl CVE-2020-8231.
Patch obtained from: https://curl.se/docs/CVE-2020-8231.html 
- Patch curl CVE-2020-8231
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-8231
- Local toolchain and full package build. (complete)
=> Patch curl CVE-2020-8231

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Incrementing `mariner-release` release number for the December release of CBL-Mariner.
- Incremented release for `mariner-release`.
No.
Small change, no builds run.
=> Updating `mariner-release.spec` for the December release.

SPECS/glib/glib-CVE-2020-35457.patch, SPECS/glib/glib.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adds CVE-2020-35457 patch to glib.
- Adds CVE-2020-35457 patch file to glib, updated spec.
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-35457
=> Added patch for glib CVE-2020-35457

toolkit/tools/imagegen/installutils/installutils.go
This is a cherry-pick of #500 containing a regression fix to setting the user password for generated images.
=> Mamalisz/fix chage shadow (#500)

SPECS/p11-kit/p11-kit.signatures.json, SPECS/p11-kit/p11-kit.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade p11-kit to 0.23.22, which resolves the following CVEs:
- CVE-2020-29361
- CVE-2020-29362
- CVE-2020-29363
- Upgrade p11-kit to 0.23.22
Yes
None
- https://nvd.nist.gov/vuln/detail/CVE-2020-29361
- https://nvd.nist.gov/vuln/detail/CVE-2020-29362
- https://nvd.nist.gov/vuln/detail/CVE-2020-29363
Local build
=> Upgrade p11-kit to 0.23.22

SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
---
Update ansible to version 2.9.12, which resolves CVE-2020-10744.
Note: NIST lists versions 2.9.10+ as patched versions, but 2.9.12 is the first version that has the patch.
- Upgrade ansible to version 2.9.12
No
None
https://nvd.nist.gov/vuln/detail/CVE-2020-10744
Local build
=> Update ansible to version 2.9.12

SPECS/kubernetes/kubernetes-1.17.11.spec, SPECS/kubernetes/kubernetes-1.17.13.spec, SPECS/kubernetes/kubernetes-1.18.10.spec, SPECS/kubernetes/kubernetes-1.18.8.spec, SPECS/kubernetes/kubernetes-1.19.1.spec, SPECS/kubernetes/kubernetes-1.19.3.spec
---
Kubernetes : no patch for CVE-2020-8564, CVE-2020-8565, CVE-2020-8566
create nopatch files and change spec accordingly
NO
CVE links:
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-8564
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-8565
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-8566
=> Kubernetes: No patch CVE-2020-8564, CVE-2020-8565, CVE-2020-8566

SPECS/util-linux/util-linux.signatures.json, SPECS/util-linux/util-linux.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
As of `util-linux` v2.34, the standalone `hardlink` program was merged into `util-linux`. Upgrade `util-linux` to the latest version to ship this tool.
- Upgrade `util-linux` to v2.36.
- Enable `hardlink` in `util-linux`.
**YES**
- Local build.
=> [dev] Update util-linux to ship hardlink

SPECS/gawk/gawk.spec, SPECS/grep/grep.spec, SPECS/mozjs60/mozjs60.spec, toolkit/resources/manifests/package/macros.override, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Improves ptests
- Fix check section for gawk, grep, mozjs60
- Skip jna test
**YES**
NO
- Local build
=> Fix tests for grep, gawk, mozjs60, skip jna test

SPECS/libisoburn/libisoburn.spec
---
libisoburn tests fail due to the lack of `file` and `which` dependencies. This PR fixes test dependencies.
- Add BuildRequires for file and which when running check sections
NO
=> libisoburn: fix package test

SPECS/librepo/librepo.spec
---
The librepo spec was not properly invoking the package tests. This PR fixes the package tests.
- Enable package tests for librepo
NO
=> librepo: enable package tests

SPECS/python-bcrypt/python-bcrypt.spec, SPECS/python-pynacl/python-pynacl.spec
---
Switch python-bcrypt and python-pynacl to python3 tests
- python-bcrypt: test using python3
- python-pynacl: test using python3
NO
=> python-bcrypt, python-pynacl: Fix package tests

SPECS/libsoup/libsoup.spec
---
Enable gobject-introspection support in libsoup.
- Update gobject-introspection-devel as a build requirement.
- Configure libsoup to build with gobject-introspection support.
- Package additional *.gir and *typelib files.
**NO**
=> [dev] Enable gobject-instrospection support in `libsoup`

SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec, SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2020-27777.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
No patch kernel CVE-2020-27777 since the patch is already in the kernel source code.
- No patch kernel CVE-2020-27777
Yes
None
- https://nvd.nist.gov/vuln/detail/CVE-2020-27777
Local build
=> No patch kernel CVE-2020-27777

SPECS/valgrind/valgrind.spec
---
Update `valgrind` to provide `valgrind-devel`.
- Update `valgrind` to provide `valgrind-devel`.
NO
- Local build.
=> [dev] Provide valgrind-devel

SPECS/libunistring/libunistring.spec, toolkit/resources/manifests/package/macros.override
---
Fix libunistring and skip strongswan tests
- Fix the libunistring test by modifying a linker setting
- Skip the strongswan tests temporarily, since they are occasionally hanging and breaking the ptest pipeline
YES
**NO**
- Local package build with RUN_TESTS=y
=> Fix libunistring test and skip strongswan

SPECS/gettext/gettext.spec, toolkit/resources/manifests/package/macros.override, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Improve %check test pass rate
- Modify the gettext spec to fix the check tests
- Correct a typo in macros.override to make sure strongswan tests are disabled
**YES**
NO
=> Fix gettest test and correct typo to disable strongswan test

.github/workflows/check-entangled-specs.yml, .github/workflows/check_entangled_specs.py
---
Currently, there are sets of specs that must have matching attributes ("entangled" specs). Namely, the signed specs must match their unsigned counterparts in both version and release. Also, we want to ensure that packages using kernel sources have matching versions. This PR adds a python script and accompanying github workflow to ensure these requirements are met.
- Add python script for checking if certain specs have matching attributes
- Add github actions workflow to run aforementioned script on PRs/pushes to important branches that touch spec files
NO
- Tested workflow on personal fork
- [Example output](https://github.com/thcrain-msft/CBL-Mariner/runs/1683133903?check_suite_f …
=> Add workflow to check entangled specs

.github/workflows/check-entangled-specs.yml, .github/workflows/check_entangled_specs.py
Cherry-pick of #528 for the dev branch
---
Currently, there are sets of specs that must have matching attributes ("entangled" specs). Namely, the signed specs must match their unsigned counterparts in both version and release. Also, we want to ensure that packages using kernel sources have matching versions. This PR adds a python script and accompanying github workflow to ensure these requirements are met.
- Add python script for checking if certain specs have matching attributes
- Add github actions workflow to run aforementioned script on PRs/pushes to important branches that touch spec files
NO
- Tested workflow on personal fork
- [Example …
=> [dev] Add workflow to check entangled specs

SPECS/libtalloc/libtalloc.signatures.json, SPECS/libtalloc/libtalloc.spec, cgmanifest.json
---
Upgrade libtalloc to 2.3.1 for compatibility and provide `python3-*` versions of the packages.
- Upgrade libtalloc to 2.3.1.
- Fix description in libtalloc.
- Provide python3-talloc and python3-talloc-devel.
NO
- Local build.
=> [dev] Upgrade libtalloc to 2.3.1

.github/workflows/check_entangled_specs.py, SPECS/ca-certificates/ca-certificates.spec, SPECS/prebuilt-ca-certificates-base/prebuilt-ca-certificates-base.spec
---
The `ca-certificates` and `prebuilt-ca-certificates-base` packages provide the same functionality, but are mutually exclusive. In order to make it clearer you have the same certificate settings, it's better to keep both their releases and versions aligned. This way it is also easier to re-use our "entangled" specs check.
- Added `ca-certificates` and `prebuilt-ca-certificates-base` to entangled specs
No.
- Verified that the "entangled" specs check succeeded.
=> Adding `ca-certificates` and `prebuilt-ca-certificates-base` to entangled specs

SPECS/qemu-kvm/CVE-2020-15469.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Updates CVE-2020-15469 to fix the bug with qemu functionality
- Update CVE-2020-15469
**YES**
NO
- #xxxx
- Local Build
=> Update qmu-kvm CVE-2020-15469 to resolve QEMU bug

SPECS/ModemManager/ModemManager.spec, SPECS/chrony/chrony.spec
---
Fix check tests for the chrony and ModemManager packages.
- Add test dependencies for chrony
- Add test dependencies for ModemManager
YES
**NO**
=> Fix tests: chrony and ModemManager

SPECS/meson/meson.signatures.json, SPECS/meson/meson.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updating `meson` to version 0.56.0. Some of CBL-Mariner derivatives require a newer version of `meson` and currently are forced to provide their own version of this spec.
- Updated `meson` to version 0.56.0.
Yes.
- Local build of the package.
=> Updating `meson` to version 0.56.0.

SPECS/cloud-init/cloud-init.spec, SPECS/python-pycurl/python-pycurl.spec
---
Fix the check tests for cloud-init and python-pycurl
- Fix the check tests for cloud-init and python-pycurl
YES
**NO**
=> Fix tests: cloud-init and python-pycurl

SPECS/kubernetes/kubernetes-1.17.11.spec, SPECS/kubernetes/kubernetes-1.17.13.spec, SPECS/kubernetes/kubernetes-1.18.10.spec, SPECS/kubernetes/kubernetes-1.18.8.spec, SPECS/kubernetes/kubernetes-1.19.1.spec, SPECS/kubernetes/kubernetes-1.19.3.spec, toolkit/scripts/kubernertes-container/CreateContainerImages.sh, toolkit/scripts/kubernertes-container/Dockerfile-Distroless, toolkit/scripts/kubernertes-container/InstallComponentsBase.sh
---
Build kubernetes components/RPMs for client/container images
Kubernetes spec
NO
=> kubernetes: build RPM for containers and build containers

SPECS/python-pycurl/python-pycurl.spec, SPECS/swig/swig.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix tests for swig, remove unreliable memtest from python-pycurl
- Fix check tests for swig. Add boost-devel build requirement. Set PERL_USE_UNSAFE_INC=1, which allows the current directory to be included in the @INC variable, and is required to run the tests as they are currently written. Note that this is not set during build/install/runtime, only in the check section.
- Ensure python-pycurl test suite is reliable by removing memory_mgmt_test.py. These tests pass when run locally on a fast machine but fail in nightly build machines that are building other packages in parallel. 
YES
**NO**
=> Fix tests for swig, remove unreliable memtest from python-pycurl

toolkit/imageconfigs/distroless-base.json, toolkit/imageconfigs/distroless-debug.json, toolkit/imageconfigs/distroless-minimal.json, toolkit/imageconfigs/packagelists/distroless-packages-container-minimal.json, toolkit/tools/imagegen/configuration/systemconfig.go
---
Add minimal distroless image configuration.
- Add minimal distroless image config.
NO
=> Add minimal distroless image configuration

SPECS/bc/bc.spec, SPECS/coreutils/coreutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix check tests for coreutils and bc
- Fix check tests for coreutils and bc
- Update manifests
**YES**
NO
=> Fix check tests for coreutils and bc

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update for CBL-Mariner monthly release.
**YES**
NO
=> Update Mariner-Release Version

toolkit/tools/imagegen/diskutils/diskutils.go
---
`util-linux` was updated in https://github.com/microsoft/CBL-Mariner/pull/508. In this update, the json output of `lsblk` changed -- disk size went from being represented as a `string` to an `uint64`.  This results in the attended ISO failing due to not being able to parse `lsblk` output. Update the go tools to use the new contract.
- Update the `lsblk` json contract to use an `uint64` to represent disk size.
NO
- Local build
=> [dev] Update lsblk json contract in go tools to match updated version

SPECS/acl/acl.spec, SPECS/mercurial/mercurial.spec, SPECS/nss/nss.spec, SPECS/perl-IO-Socket-SSL/perl-IO-Socket-SSL.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix check test failures for nss and mercurial
- Fix nss tests
- Fix mercurial tests
- Fix nss tests
- Fix perl-IO-Socket-SSL tests
- Update manifests
YES
**NO**
=> Fix check tests: acl, mercurial, nss, perl-IO-Socket-SSL

SPECS/coredns/coredns-1.6.5.signatures.json, SPECS/coredns/coredns-1.6.5.spec, SPECS/coredns/coredns-1.6.7.signatures.json, SPECS/coredns/coredns-1.6.7.spec, SPECS/coredns/coredns-1.7.0.signatures.json, SPECS/coredns/coredns-1.7.0.spec, SPECS/coredns/makefile-buildoption-commitnb-1.6.5.patch, SPECS/coredns/makefile-buildoption-commitnb.patch, SPECS/etcd/etcd-3.4.13.signatures.json, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.4.3.signatures.json, SPECS/etcd/etcd-3.4.3.spec, SPECS/flannel/buid-no-static-glibc.patch, SPECS/flannel/flannel.signatures.json, SPECS/flannel/flannel.spec, SPECS/kubernetes/Readme.txt, cgmanifest.json
---
Update etcd versions and add coredns and flannel
update or create the relevant spec files
NO
=> Update etcd versions and add coredns and flannel

SPECS/python3/CVE-2021-3177.patch, SPECS/python3/python3.spec
Pick Python's CVE fixes from 1.0-dev
=> Pick Python and CVE fixes to 1.0 

SPECS/td-agent/td-agent.spec
---
- Change
- Change
- Change
**YES**
NO
- #xxxx
- Local build
=> Fix td-agent installation

SPECS/net-snmp/net-snmp.spec
---
Add minor provides for net-snmp-utils
- Provides net-snmp-utils from net-snmp
**YES**
NO
- #xxxx
- Local Build
=> [dev] Add Provides net-snmp-utils

SPECS/golang/golang-1.15.signatures.json, SPECS/golang/golang-1.15.spec, cgmanifest.json
---
Update to latest golang 1.15 release which fixes CVE-2021-3114
- Update golang spec
- update cgmanifest
YES
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-3114
- Local build of golang and all specs that require golang to build
=> Update golang version to 1.15.7

SPECS/libkcapi/libkcapi.spec
---
Libkcapi fails to build in our pipeline. The libkcapi build uses libkcapi's hmac functions to generate hmac files for integrity checking. In our builds, Docker has trouble using the kernel's NETLINK_CRYPTO interface [similar issue in Stack Overflow(](https://stackoverflow.com/questions/62290523/access-linux-kernel-crypto-api-from-docker).
For now, use OpenSSL to do the hmac calculations until the above issue can get resolved.
- Use OpenSSL to perform hmac in libkcapi
No
None
None
Local build
=> Use OpenSSL to perform hmac in libkcapi

SPECS/golang/golang-1.15.spec
---
Golang update in 3f2b61ebccef408a866d5572525616dbed251f3e had a minor changelog entry syntax error that causes the srpm packing step to fail with the following error:
INFO[0000] Calculating SPECs to repack                  
WARN[0000] error: %changelog entries must start with *
error: query of specfile /data2/vsts/_work/26/s/SPECS/golang/golang-1.15.spec failed, can't parse 
FATA[0000] Failed to query SPEC (/data2/vsts/_work/26/s/SPECS/golang/golang-1.15.spec), error: exit status 1 
Fix the changelog entry to start with `*` instead of `-` in first line
No
Pipeline build
=> Update golang changelog entry

SPECS/kernel-hyperv/kernel-hyperv.spec
---
Add sha512hmac-openssl to kernel-hyperv source. Previously missing.
- Add sha512hmac-openssl to kernel-hyperv source
No
None
None
Local build
=> Add sha512hmac-openssl to kernel-hyperv source

toolkit/scripts/toolchain/cross/Dockerfile, toolkit/scripts/toolchain/cross/busybox_container.sh
---
Adds a script which creates a basic aarch64 container from the binaries created by the other cross compile scripts.
Run:
```
busybox_container.sh [-n=NAME] [-c]
```
`-c` will clear old containers
`-n` will give a custom name to the container
- Add `busybox_container.sh` which will create a busybox based container from cross-compiled components.
NO
- Local
=> [cross]Add busybox container script

toolkit/scripts/toolchain/cross/busybox.patch, toolkit/scripts/toolchain/cross/busybox_cross.sh, toolkit/scripts/toolchain/cross/gcc_cross.sh
---
Script to cross compile busybox
- Change
- Change
- Change
**YES**
NO
- #xxxx
- Local build
=> Script to cross compile busybox

toolkit/imageconfigs/core-fips.json, toolkit/imageconfigs/packagelists/fips-packages.json, toolkit/tools/imageconfigvalidator/imageconfigvalidator.go, toolkit/tools/imageconfigvalidator/imageconfigvalidator_test.go
---
Add FIPS-enabled Mariner core image
- Add FIPS-enabled Mariner core image JSON config
- Add fips=1 image config validation/test
No
None
None
Local build
=> Add FIPS-enabled core image

toolkit/scripts/kubernertes-container/CreateContainerImages.sh
---
create container for etcd, coredns and flannel
script that creates the containers
NO
=> create etcd, coredns and flannel containers

SPECS/qemu-kvm/CVE-2020-17380.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
- Add patch for qemu CVE-2020-17380
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-17380
- local build
=> Add patch for qemu CVE-2020-17380

SPECS/mysql/mysql.signatures.json, SPECS/mysql/mysql.spec, cgmanifest.json
---
- Upgrade to 8.0.23. Fixes CVE-2020-15358.
- Upgrade to 8.0.23. Fixes CVE-2020-15358.
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-15358
- local package build on x86 and image build
- ran %check and passed all tests
=> Update mysql to version 8.0.23 for CVE-2020-15358

SPECS-CROSS/binutils_cross/binutils_cross.spec, SPECS-CROSS/kernel-headers_cross/kernel-headers_cross.signatures.json, SPECS-CROSS/kernel-headers_cross/kernel-headers_cross.spec
---
We need a copy of the kernel headers in the sysroot directory, so we need a cross aware headers package.
Also update more of the macros which are needed for other packages.
- Add `kernel-headers_cross.spec`
- Update cross macros in binutils package to match latest.
NO
- Local testing in docker
=> [cross] Add kernel-headers package, update macros

toolkit/docs/formats/imageconfig.md, toolkit/tools/imagegen/configuration/configuration_test.go, toolkit/tools/imagegen/configuration/partitionsetting.go, toolkit/tools/imagegen/configuration/testdata/test_configuration.json, toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imagegen/installutils/overlay.go, toolkit/tools/imager/imager.go, toolkit/tools/roast/formats/diff.go, toolkit/tools/roast/formats/rdiff.go, toolkit/tools/roast/roast.go
---
This is merge of overlay based installer code which was earlier reviewed. Here is the link to the commit. https://dev.azure.com/mariner-org/mariner/_git/mariner/commit/11351e26c7f5606ffbf8f10b0aa444129e422377?refName=refs%2Fheads%2Fmaster&path=%2Ftoolkit%2Ftools%2Fimagegen%2Finstallutils%2Finstallutils.go
This commit never made it to the github repo. 
Description from the commit: 
Here is a link to the spec https://microsoft-my.sharepoint.com/:w:/g/personal/arvindka_microsoft_com1/ESrYHTpWUPBOgdi7LjDsE14Bf1mHSLG702551XctkFX1mA?e=CyCc2j . This is for early feedback on the approach.
It introduces a new element, BaseImage for each partition. Instead of creating a complete new …
=> Overlay based diff image creation cherry pick

SPECS/python-jwt/python-jwt.spec
---
Remove duplicate distribution and vendor tags from `python-jwt`.
- Remove duplicate distribution and vendor tags from `python-jwt`.
NO
- N/A
=> [dev] Remove duplicate distribution tag from python-jwt

SPECS/net-snmp/net-snmp.spec
---
Replace incorrect `%{_lib}` macro in `net-snmp` with `%{_libdir}`. Since there hasn't been a build with this change yet, skip bumping the version.
- Replace incorrect `%{_lib}` macro in `net-snmp` with `%{_libdir}`.
NO
- N/A
=> [dev] Fix incorrect lib macro usage in net-snmp

SPECS/mariner-repos/mariner-extras-preview.repo, SPECS/mariner-repos/mariner-extras.repo, SPECS/mariner-repos/mariner-repos.signatures.json, SPECS/mariner-repos/mariner-repos.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh
---
This PR enables the mariner-extras repository.
- Added mariner-extras repo
**YES**
- Local package & toolchain build.
=> Add mariner extras repo

toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Previous PRs didn't include the necessary changes to the package manifests. This PR fixes the mismatch.
- Add UI and UI-preview to the toolchain list.
- Add extras-preview to the toolchain list.
NO
=> Update manifests with missing packages

toolkit/docs/quick_start/quickstart.md
---
Change quickstart git clone command to use https instead of ssh.
- Change quickstart git clone command to use https instead of ssh.
- Incorporate markdown linter fixes
NO
- #567
=> quickstart: update git clone to use https

toolkit/scripts/toolchain/cross/gcc_cross_test.sh
---
This PR adds a script to run the GCC compile only tests to verify that the ARM64 cross toolchain was built correctly.
**NO**
- Tested in an Ubuntu docker environment with 0 failures
=> Add GCC compile.exp tests

SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap_cross.spec, SPECS-CROSS/gcc-bootstrap_cross/gcc.signatures.json
---
Add stage one gcc boot strap package.
- Add `gcc-bootstrap_cross.spec`
NO
- Local testing in docker
=> [cross] Add version 1 of gcc bootstrap stage 1

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update the Mariner-Release version for the February 2021 update
**YES**
NO
=> Update for February release

SPECS/sudo/sudo.spec
---
New version update included changes to the configuration file. The resulting changes could overwrite some of the user's settings. This PR fixes this problem.
- Add default directives before @includedir
NO
=> Update default sudo config

SPECS/python-sqlalchemy/python-sqlalchemy.spec
---
Fix python-sqlalchemy test. 
Local test run results: "================== 8354 passed, 958 skipped in 252.68 seconds =================="
- Modify python-sqlalchemy spec to fix check tests
- Use tox to install test dependencies and run the tests. 
- Pull upstream change to fix one failing test: "FAILED test/sql/test_query.py::QueryTest_sqlite+pysqlite_3_32_3::test_order_by_nulls"
YES
**NO**
- #xxxx
=> Fix python-sqlalchemy test

SPECS/openvswitch/CVE-2020-35498.patch, SPECS/openvswitch/openvswitch.spec
---
- Fix CVE-2020-35498 in `openvswitch`
- Bring the CVE fix commit as a patch, it needed slight changes to apply cleanly.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-35498
- Pipeline build id: mrgirgin-69476
=> Fix CVE-2020-35498 in openvswitch

SPECS/linux-firmware/linux-firmware.spec
---
Add bnx2x and qed firmware, which are needed for the corresponding driver to function.
Add WHENCE and license files into produced RPMs.
- Add bnx2x and qed firmware
- Add WHENCE and license files
- Lint spec
NO
Local build
=> linux-firmware: Add bnx2x and qed firmware, WHENCE, and license files

toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh
---
While I was adding the `mariner-repos-ui*` packages I forgot to update the `update_manifests.sh` script accordingly. I'm doing this now + adding a bit of clean-up by following SpellCheck extension's suggestion.
- Removed the `mariner-repos-ui*` packages while running `upate_manifests.sh`.
- Cleaned-up the script a bit.
No.
=> Updating 'update_manifests.sh' script to remove the UI repo

SPECS/ntopng/ntopng.spec
---
Small fix to the `Source` tags inside `ntopng.spec` to use correct URLs.
- Updated `Source` tag URLs.
No.
- N/A, minor fix-up.
=> Fixing `ntopng` source URLs.

SPECS/openldap/CVE-2021-27212.patch, SPECS/openldap/openldap.spec
---
resolve openldap cve-2021-27212
openldap spec and patch file
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-27212..
=> openldap: fix CVE-2021-27212

SPECS/bind/CVE-2020-8625.patch, SPECS/bind/bind.spec
---
fix Bind CVE-2020-8625
change spec file and add patch file
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-8625
=> bind: fix CVE-2020-8625

SPECS/mariner-rpm-macros/macros
---
Fix unnecessary line in _smp_build_cpus definition
- Fix unnecessary line in _smp_build_cpus definition in mariner-rpm-macros
YES
- #xxxx
- Local Build
=> [dev] Fix smp_build_cpus macro definition

SPECS/python-distro/python-distro.signatures.json, SPECS/python-distro/python-distro.spec, SPECS/python-requests/python-requests.spec, SPECS/python-requests/test_requests_support_pytest_4.patch, SPECS/python-requests/test_requests_typeerror_testfix.patch, cgmanifest.json
---
Fix tests for python-distro and python-requests
- Fix python-distro tests. The tests were failing because the source tarball was missing tox.ini. I've changed this to pull the source from the official github page as listed on https://pypi.python.org/pypi/distro (which is https://github.com/nir0s/distro)
- Fix python-requests tests by running with tox and adding upstream test fixes
- Update cgmanifets.json
YES
**NO**
=> Fix tests for python-distro and python-requests

SPECS-CROSS/cross-gcc/cross-gcc.spec, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap2_cross.signatures.json, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap2_cross.spec, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap3_cross.signatures.json, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap3_cross.spec, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap_cross.signatures.json, SPECS-CROSS/gcc-bootstrap_cross/gcc-bootstrap_cross.spec, SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap2_cross.signatures.json, SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap2_cross.spec, SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap_cross.signatures.json, SPECS-CROSS/glibc-bootstrap_cross/glibc-bootstrap_cross.spec
Add package which merges all the bootstrapped compiler components together into one package.
Note: Waiting on full bootstrap PR before merging.
=> [cross] Add cross gcc meta package

SPECS/apparmor/apparmor-update-severity-db.patch, SPECS/apparmor/apparmor.spec, SPECS/python-pycurl/python-pycurl.spec, SPECS/redis/disable_active_defrag_big_keys.patch, SPECS/redis/redis.spec, toolkit/resources/manifests/package/macros.override
---
Fix check tests for apparmor, redis, skip WALinuxAgent
- Add patch to fix apparmor tests
- Add patch to fix redis tests
- Skip WALinuxAgent tests which break build machines
- Skip an unreliable test in python-pycurl. This test seems to fail with limited resources (as on our build machines running parallel build/test), as well as single core machines (see: https://github.com/pycurl/pycurl/issues/541)
YES
**NO**
=> Fix check tests for apparmor, redis, python-pycurl, skip WALinuxAgent

toolkit/resources/imageconfigs/packagelists/accessibility-packages.json, toolkit/tools/imagegen/attendedinstaller/attendedinstaller.go, toolkit/tools/imagegen/attendedinstaller/primitives/progressbar/progressbar.go, toolkit/tools/imagegen/attendedinstaller/speakuputils/speakuputils.go, toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go
---
Improves several aspects of the ISO installer based upon internal accessibility review feedback
- Clear speakup buffer in proper place
- Use speakup in highlight tracking mode
- Improve certain UI text for clearer text-to-speech interpretation
- Add back in a truncated version of install progress bar percentage
NO
- Local image build
=> Improve text-to-speech experience in the ISO installer

SPECS/nss/nss.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Enable FIPS mode for NSS.
When "fips=1" is set on the kernel command line, NSS goes into FIPS mode. NSS failed to initialize since the integrity "chk" files were not produced properly. This PR fixes those "chk" files and enables the FIPS startup tests.
- Enable FIPS mode for NSS.
Yes
None
None
Local build
=> Enable FIPS mode for NSS

SPECS/cyrus-sasl/cyrus-sasl.spec
---
CVE-2020-8032 does not apply to the way we package cyrus-sasl, since it is not openSUSE-derived.
- Nopatch CVE-2020-8032 in cyrus-sasl
NO
- https://nvd.nist.gov/vuln/detail/CVE-2020-8032
=> Nopatch CVE-2020-8032 in cyrus-sasl

SPECS/bash-completion/bash-completion.spec
---
Some specs from other distros will expect the `bash-completion` package to contain a pkg-config file, since other distros ship it as a single package. We put our pkg-config file in the devel subpackage, so we are incompatible with other distros' specs in that aspect. Mutually requiring `bash-completion` and `bash-completion-devel` solves this problem.
- Require bash-completion-devel from bash-completion
NO
=> [dev] Make bash-completion compatible with other distros

toolkit/docs/building/prerequisites.md
---
Fixing a minor typo in prerequisites.md
- Update prerequisites.md
**NO**
- Documentation change only
=> Fix typo in prerequisites.md

toolkit/tools/internal/file/file.go
---
Print out the data being appended by file.Append() into
the debug log. This is useful for debugging some of the image
generation flows like /etc/fstab update.
NO
Local build and test
=> file: add append data to debug output

toolkit/tools/imagegen/installutils/installutils.go
---
Found constant "efiAssetDir" was not being used in installutils and thus, removed it.
Remove constant unused "efiAssetDir"
NO
- local tool rebuild
- local image build (x86 tested on hyper-v)
=> installutils: Remove stale constant

SPECS/python3/python3.spec, SPECS/ruby/macros.ruby, SPECS/ruby/macros.rubygems, SPECS/ruby/operating_system.rb, SPECS/ruby/ruby-2.1.0-Prevent-duplicated-paths-when-empty-version-string-i.patch, SPECS/ruby/ruby-2.3.0-ruby_version.patch, SPECS/ruby/ruby.signatures.json, SPECS/ruby/ruby.spec, SPECS/ruby/rubygems.attr, SPECS/ruby/rubygems.con, SPECS/ruby/rubygems.prov, SPECS/ruby/rubygems.req, SPECS/rubygem-bundler/rubygem-bundler.spec, cgmanifest.json
---
- Upgrade ruby version to 2.7.2
- Modify ruby configuration, install additional necessary components and add provides
- Add provides for rubygem(bundler) and rubygem-bundler-doc for rubygem-bundler
**ruby:** 
- Upgrade to version 2.7.2
- Add files like macros.rubygems, imported from Fedora 32 (license: MIT)
- Add patches to prevent ruby vesion abuse
- Modify ruby configuration
- Install necessary binaries for bigdecimal, irb, io-console and psych
- Add provides for /usr/local/bin/ruby, ruby(release), rubygems, rubygems-devel, ruby-libs,
ruby(rubygems), rubygem(irb), rubygem(bigdecimal), rubygem(io-console), rubygem(psych), …
=> [dev] Upgrade and modify ruby and rubygem-bundler

SPECS/swig/swig.signatures.json, SPECS/swig/swig.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade swig to the latest version to align with the version update of ruby
- Upgrade to version 4.0.2
- Remove sha1 define
YES
- #xxxx
- Local Build
=> [dev] Upgrade swig

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imagegen/installutils/installutils_test.go
---
grub2-pc package is only available for x86_64 systems so if the tools
attempt to use it on arm64 image builds, the build will fail.
This fix checks the current architecture and only includes grub2-pc if
running on an x86_64 machine.
Also add `installutils_test` package and unit test for
`GetRequiredPackagesForInstall` to quickly test return values for each
architecture.
Also fix empty required package return
If no required packages are present, always return a slice
with no elements instead of a nil pointer.
NO
local amd64 go-test. emulated arm64 container go-test.
=> installutils: only return grub2-pc on amd64 install

SPECS/perl-Crypt-SSLeay/Use_TLS_client_method-with-OpenSSL-1.1.1.patch, SPECS/perl-Crypt-SSLeay/perl-Crypt-SSLeay.spec
---
Fix perl-Crypt-SSLeay test failures by adding a patch for Openssl tests
- Fix perl-Crypt-SSLeay test
YES
**NO**
=> Fix perl-Crypt-SSLeay test

SPECS/grpc/grpc.signatures.json, SPECS/grpc/grpc.spec, cgmanifest.json
---
Add grpc modules (grpc, grpc-devel, grpc-plugins) version 1.35.0 to mariner. 
- Add grpc modules (grpc, grpc-devel, grpc-plugins) version 1.35.0 to mariner.
- No CVE's affected.
NO
- Local build
=> Add grpc to mariner

SPECS/qemu-kvm/CVE-2021-20203.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Add patch to qemu-kvm to fix resolve CVE-2021-20203
- Add patch to qemu-kvm to fix resolve CVE-2021-20203
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-20203
- Local build
=> Add patch to qemu-kvm to fix CVE-2021-20203

SPECS/qemu-kvm/CVE-2021-20255.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Add patch to qemu-kvm to fix CVE-2021-20255
- Add patch to fix CVE-2021-20255
NO
https://nvd.nist.gov/vuln/detail/CVE-2021-20255
- Local build
=> Add patch to qemu-kvm to fix CVE-2021-20255

SPECS/subversion/CVE-2020-17525.patch, SPECS/subversion/subversion.spec
---
Patch CVE-2020-17525 in subversion
- Patch CVE-2020-17525 in subversion
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-17525
- Local build
- RUN_CHECK=y for subversion passed.
=> subversion patch CVE-2020-17525

SPECS/python-pygments/CVE-2021-27291.patch, SPECS/python-pygments/python-pygments.spec
---
Patch CVE-2021-27291 in python-pygments
- Patch CVE-2021-27291 in python-pygments
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-27291
- Local build
- RUN_CHECK=y showed all python-pygments tests passed.
=> python-pygments patch CVE-2021-27291

SPECS/grpc/grpc.spec
---
Make grpc use system zlib and openssl
- Make grpc use system zlib and openssl
NO
- https://github.com/microsoft/CBL-Mariner/pull/798
- Local build
=> Make grpc use system zlib and openssl

SPECS/python-pygments/CVE-2021-20270.patch, SPECS/python-pygments/python-pygments.spec
---
Patch CVE-2021-20270 in python-pygments
- Patch CVE-2021-20270 in python-pygments
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-20270
- Local build
=> python-pygments patch CVE-2021-20270

toolkit/scripts/toolchain.mk, toolkit/tools/imagegen/attendedinstaller/uitext/uitext.go, toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
Modified dropdown options to provide user with a list which can be cycled through using arrow keys. This improves the experience for TTS.
- Change dropdown fields in terminal installer to special input fields.
NO
=> Change dropdown menus to accessible input fields

toolkit/scripts/toolchain/container/toolchain-jdk8-md5sums, toolkit/scripts/toolchain/container/toolchain-jdk8-wget.sh
---
Cleanup to remove an unused file "toolchain-jdk8-md5sums". All md5sums are in file "toolchain-md5sums"
- Remove toolchain-jdk8-md5sums
**YES**
NO
- sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y DOWNLOAD_SRPMS=y
=> Remove unused file toolchain-jdk8-md5sums

toolkit/tools/internal/pkggraph/pkggraph.go
---
We've seen instances where bad version constraints can cause the `pkggraph` tool to resolve dependencies to a remote run node with the bad version. When the bad version is never built/resolved, we have no way to fall back to a valid, built local package (if one exists). 
For now, we just want to log when this behavior occurs.
- Add warning log to pkggraph when above situation happens
NO
- Local build and run
=> [dev] pkggraph: Add warning when resolving dependency to remote node over local node

SPECS/glibc/CVE-2020-27618.patch
---
Fix to CVE patch to unbreak build 
glibc CVE patch updated to fix build.
**YES**
- See PR #775 
- Local build, both in CBL-MarinerDemo and CBL-Mariner
=> CVE-2020-27618 patch fixed to enable glibc build

SPECS/curl/curl.signatures.json, SPECS/curl/curl.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update curl to 7.76.0. This resolves CVE-2021-22876 and CVE-2021-22890.
- Update curl to 7.76.0
Yes
None
-  Local build
=> Update curl to 7.76

SPECS-SIGNED/grub2-efi-binary-signed-aarch64/grub2-efi-binary-signed-aarch64.spec, SPECS-SIGNED/grub2-efi-binary-signed-x64/grub2-efi-binary-signed-x64.spec, SPECS/grub2/grub2.spec
---
Nopatch so that tooling resolves
- CVE-2021-3418
- CVE-2020-14372
- CVE-2020-25632
- CVE-2020-25647
- CVE-2020-27779
- CVE-2021-20233
- CVE-2020-10713
- CVE-2020-14308
- CVE-2020-14309
- CVE-2020-14310
- CVE-2020-14311
- CVE-2020-27749
- CVE-2021-20225
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-3418
- https://nvd.nist.gov/vuln/detail/CVE-2020-14372
- https://nvd.nist.gov/vuln/detail/CVE-2020-25632
- https://nvd.nist.gov/vuln/detail/CVE-2020-25647
- https://nvd.nist.gov/vuln/detail/CVE-2020-27779
- https://nvd.nist.gov/vuln/detail/CVE-2021-20233
- https://nvd.nist.gov/vuln/detail/CVE-2020-10713
- https://nvd.nist.gov/vuln/detail/CVE-2020-14308
- …
=> grub2: Add nopatches for tooling

toolkit/docs/building/building.md
---
Update community build instructions to use SOURCE_URL instead of DOWNLOAD_SRPMS
Remove unneeded values from PACKAGE_IGNORE_LIST
- Update documentation
YES
**NO**
- Local builds
=> update community instructions

SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec, SPECS/httpd/macros.httpd
---
Many packages that depends on httpd-devel requires the usage of certain macros which are currently not defined by httpd. Create the macros.httpd file to include the necessary macros for those packages to build.
- Add macros.httpd to provide necessary httpd macros
NO
- #xxxx
- Local Build
=> [dev] Update httpd to include necessary macros

toolkit/scripts/addcerts.sh, toolkit/scripts/preparemacros.sh, toolkit/tools/pkggen/worker/create_worker_chroot.sh
---
While trying to figure out build issues for #841 @henryli001 and I discovered, that missing to include an empty line at the end of the toolchain or worker chroot manifests made the tooling skip the last package. This seems to be a [common issue](https://stackoverflow.com/questions/12916352/shell-script-read-missing-last-line) and fortunately has a simple solution.
- Fixed reading data out of files missing an empty line at the end.
No.
- Tested during a build for #841.
=> Fixing parsing toolchain and worker chroot manifests

SPECS/git/git.signatures.json, SPECS/git/git.spec, cgmanifest.json
---
Update git version to 2.23.4 for CVE-2021-21300
- Change
Update git version to 2.23.4 for CVE-2021-21300
**YES**
NO
- #xxxx
- https://github.blog/2021-03-09-git-clone-vulnerability-announced/
- Verified local building git package.
=> Update git version to 2.23.4 for CVE-2021-21300

SPECS/mariadb/mariadb.signatures.json, SPECS/mariadb/mariadb.spec, cgmanifest.json
---
Upgrade mariadb to 10.3.28.
This resolves CVE-2021-27928
- Upgrade mariadb to 10.3.28.
No
- None
- https://nvd.nist.gov/vuln/detail/CVE-2021-27928
- Local build
=> Upgrade mariadb to 10.3.28

SPECS/openvswitch/openvswitch.signatures.json
---
Update openvswitch signatures file to version 2.12.3.
Fixes build break.
- Update openvswitch signatures file to version 2.12.3
Yes
None
None
Local Build
=> Update openvswitch signatures file to version 2.12.3

SPECS/azure-iotedge/azure-iotedge.spec
---
A small typo fix from in the spec for a `BuildRequires` which might have been confusing our tooling during one of our builds.
- Changed `==` to a [valid](http://ftp.rpm.org/api/4.4.2.2/dependencies.html) `=`.
No.
- None, typo fix.
=> Fixing azure-iotedge.spec `BuildRequires` typo from '==' to '='.

SPECS/dtc/dtc-disable-warning.patch, SPECS/dtc/dtc.spec
---
fix dtc build error by disable treating warning as errors and add missing packages to the file section
- Disable treating warning as errors
- Add %{python3_sitearch}/
**YES**
NO
- #xxxx
- Local build
=> [dev] Fix dtc build error

SPECS/moby-cli/generate-sources.sh, SPECS/moby-cli/moby-cli.signatures.json, SPECS/moby-cli/moby-cli.spec, SPECS/moby-engine/generate-sources.sh, SPECS/moby-engine/moby-engine.signatures.json, SPECS/moby-engine/moby-engine.spec, cgmanifest.json
---
Update moby-engine and moby-cli packages to latest to resolve recent CVEs
- Change moby-cli
- Change moby-engine
YES
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-21284
- https://nvd.nist.gov/vuln/detail/CVE-2021-21285
- Local package build. Local VHDX build. Ran VHDX in VM and tested basic docker commands and installed azure-iotedge and ran "sudo iotedge check"
=> Update moby-engine and moby-cli to version 19.10.15

SPECS-SIGNED/kernel-signed-aarch64/kernel-signed-aarch64.spec, SPECS-SIGNED/kernel-signed-x64/kernel-signed-x64.spec, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2021-29648.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
-  Add no patch for CVE-2021-29648 since introducing commit not present
- Upstream introducing commit - 5329722057d41aebc31e391907a501feaa42f7d9
- Upstream fix commit - 350a5c4dd2452ea999cc5e1d4a8dbf12de2f97ef
-  Add no patch for CVE-2021-29648 
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-29648
- local build (full toolchain, kernel package, vhdx)
=> kernel: Add no patch for CVE-2021-29648

toolkit/docs/building/building.md
---
Adding a bit of clarification regarding the file paths inside our config JSONs. This change is related to [a PR from the demo repository](https://github.com/microsoft/CBL-MarinerDemo/pull/5).
- Added clarification relative and absolute paths inside our config JSONs.
No.
- N/A, documentation change.
=> Adding clarifications about config file paths.

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imager/imager.go
---
Don't configure grub encryption settings in chroot.
If run in chroot, settings will not be detected during grub install.
- Don't configure grub encryption settings in chroot.
No
None
None
Local build
=> Don't Configure Grub Encryption Settings in Chroot

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/imager/imager.go
---
Don't Configure Grub Encryption Settings in Chroot.
Cherry picked from: https://github.com/microsoft/CBL-Mariner/pull/864
-None
No
None
None
Local build
=> Don't Configure Grub Encryption Settings in Chroot (#864)

SPECS/at/at.spec
---
Fix installation and removal of atd.service. This fixes a bug whereby "tdnf remove at" fails. 
- Fix installation and removal of atd.service
No
None
- None
Local build
=> Fix installation and removal of atd.service

SPECS/clamav/clamav.signatures.json, SPECS/clamav/clamav.spec, cgmanifest.json
---
Upgrade to ClamAV 0.103.2 fixes CVE-2021-1252, CVE-2021-1404, CVE-2021-1405.
- Upgrade ClamAV to 0.103.2
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-1252
- https://nvd.nist.gov/vuln/detail/CVE-2021-1404
- https://nvd.nist.gov/vuln/detail/CVE-2021-1405
=> Upgrade ClamAV to 0.103.2 to fix multiple CVEs

SPECS/kubernetes/kubernetes-1.18.17.signatures.json
---
During the latest update of the `kubernetes` packages (#869), I missed verifying the new 1.18.17 version and its signatures JSON was missing the file added in this PR leading to a build break.
- Updated signatures for the 1.1.8.17 version of `kubernetes`.
No.
=> Adding missing patch signature for "kubernetes-1.18.17".

SPECS/sqlite/sqlite.signatures.json, SPECS/sqlite/sqlite.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update sqlite to a more recent version to address security issues
- Update sqlite to 3.34.1
- Change
- Change
YES
- https://nvd.nist.gov/vuln/detail/CVE-2021-20227
- Local Build
=> Update sqlite to 3.34.1 to fix CVE-2021-20227

SPECS/azure-iotedge/azure-iotedge.spec, SPECS/cloud-hypervisor/cloud-hypervisor.spec, SPECS/rpm-ostree/rpm-ostree.spec, SPECS/rust/CVE-2021-28879.patch, SPECS/rust/rust.spec
---
Patch CVE-2021-28879 in Rust
- Patch CVE-2021-28879 in Rust
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-28879
- Local build and test of rustc
=> Patch CVE-2021-28879 in Rust

toolkit/imageconfigs/core-efi-aarch64.json, toolkit/imageconfigs/full-aarch64.json, toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json, toolkit/imageconfigs/packagelists/core-packages-image.json, toolkit/resources/imageconfigs/packagelists/iso-initrd-packages.json
---
* iso-initrd: Use signed shim package
* core-packages: Use signed shim package
* core-efi-aarch64: Add new core-efi-aarch64 image
aarch64 images still need to use the shim-unsigned package. Add a new
core-efi-aarch64 image configuration and add a new
core-packages-image-aarch64 packagelist with the shim-unsigned package.
When a signed aarch64 shim is available, we can consider removing this
image configuration and package list.
* full-aarch64: Add new full-aarch64 iso config
NO
Local/pipeline build
=> Incorporate signed shim package into default images/iso

SPECS/mysql/mysql.signatures.json, SPECS/mysql/mysql.spec, cgmanifest.json
---
Upgrade mysql to 8.0.24 to fix 30 CVEs
- Upgrade mysql to 8.0.24
- Change source URL to most recent formatk
NO
- [Listed in Oracle's latest patch update notice](https://www.oracle.com/security-alerts/cpuapr2021.html#AppendixMSQL)
- None yet
=> Upgrade mysql to 8.0.24 to fix 30 CVEs

SPECS/glib/glib.spec
---
Fix typo in the glib spec to resolve build break
YES
- #xxxx
- Local Build
=> [dev] Fix typo in glib spec

SPECS/LICENSES-AND-NOTICES/data/licenses.json, SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.6.7.spec, SPECS/coredns/coredns-1.7.0.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.4.3.spec, SPECS/flannel/flannel.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/golang-1.15.signatures.json, SPECS/golang/golang-1.15.spec, SPECS/kubernetes/kubernetes-1.18.14.spec, SPECS/kubernetes/kubernetes-1.18.17.spec, SPECS/kubernetes/kubernetes-1.19.7.spec, SPECS/kubernetes/kubernetes-1.19.9.spec, SPECS/kubernetes/kubernetes-1.20.2.spec, SPECS/kubernetes/kubernetes-1.20.5.spec, SPECS/moby-runc/moby-runc.spec, SPECS/nvidia-container-runtime/nvidia-container-runtime.spec, SPECS/runc/runc.spec, SPECS/telegraf/telegraf.spec, cgmanifest.json
---
golang: update to version 1.15.11 to address CVE-2021-27918
golang spec file and all specs which build requires golang
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-27918
=> golang: update to version 1.15.11 to address CVE-2021-27918

SPECS/cifs-utils/CVE-2021-20208.patch, SPECS/cifs-utils/cifs-utils.spec
---
Adding a patch for [CVE-2021-20208](https://nvd.nist.gov/vuln/detail/CVE-2021-20208).
- Added a patch for [CVE-2021-20208](https://nvd.nist.gov/vuln/detail/CVE-2021-20208).
- Updated the `URL` tag to use HTTPS.
- Verified the package's license.
- Cleaned-up the spec.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-20208
=> Patching CVE-2021-20208 in `cifs-utils`.

SPECS/groff/groff.spec
---
Our version of `groff` was not providing the same paths as Fedora's, which was causing some packages to break. Adding symbolic links for the same binaries and man pages as Fedora does to get us unblocked.
- Added symbolic links to multiple `groff` binaries and man pages.
No.
=> [dev] Adding symbolic links to `groff`.

SPECS/libserf/libserf.spec
---
Disable test_ssl_handshake in libserf
OpenSSL version 1.1.1i+ regressed this test. Disable for now.
Discussion in serf community: https://www.mail-archive.com/dev@serf.apache.org/msg01917.html
- Disable test_ssl_handshake in libserf
No
None
None
Local build
=> Disable test_ssl_handshake in libserf

toolkit/tools/pkgworker/pkgworker.go
---
Adding a heartbeat log for our package builds so it's easier to tell what we are still waiting for in longer builds.
- Added a heartbeat log for package builds.
No.
=> Adding heartbeat log for package builds.

SPECS/td-agent/td-agent.patch, SPECS/td-agent/td-agent.spec
---
td-agent encounters a build break due to the recent upgrade of ruby to version 2.6.7. Update td-agent to use ruby 2.6.7 for build.
- Update patch to use ruby 2.6.7
NO
- #xxxx
- Local build
=> Fix td-agent build break

toolkit/docs/quick_start/quickstart.md
---
We now support secure boot out of the box, so update the instructions to
keep Secure Boot enabled in Hyper-V and to utilize the "Microsoft UEFI
Certificate Authority" for verification.
NO
Documentation change
=> quickstart: add Secure Boot instructions on HyperV

SPECS/Cython/Cython.spec, SPECS/Cython/cython_testfix_with_outer_raising.patch, SPECS/python-lxml/python-lxml.spec
---
Add a version of the Cython package that is built with Python3. SELinux packages require a version of Cython with python3.
Replaces #902 
- Change Cython package to build with python3
**NO**
- Local package build of Cython, python-lxml
=> Add python3-Cython subpackage

SPECS/aspnetcore-runtime-3.1/aspnetcore-runtime-3.1.signatures.json, SPECS/aspnetcore-runtime-3.1/aspnetcore-runtime-3.1.spec, SPECS/dotnet-runtime-3.1/dotnet-runtime-3.1.signatures.json, SPECS/dotnet-runtime-3.1/dotnet-runtime-3.1.spec, SPECS/dotnet-sdk-3.1/dotnet-sdk-3.1.signatures.json, SPECS/dotnet-sdk-3.1/dotnet-sdk-3.1.spec, cgmanifest.json
---
Update dotnet-runtime and aspnetcore-runtime to 3.1.14 and dotnet-sdk to 3.1.114
change relevant spec files and json signatures
NO
=> Update dotnet-runtime and aspnetcore-runtime to 3.1.14 and dotnet-sdk to 3.1.114

SPECS/sos/sos.spec
---
Previous PR adding `sos` package was missing a commit deleting files that were installed in two different places. This fixes that.
- Remove python-packaged licenses/docs in `sos` package
NO
- Local Build
=> Fix doubly packaged file in sos package

SPECS/aspnetcore-runtime-3.1/aspnetcore-runtime-3.1.signatures.json, SPECS/aspnetcore-runtime-3.1/aspnetcore-runtime-3.1.spec, SPECS/dotnet-runtime-3.1/dotnet-runtime-3.1.signatures.json, SPECS/dotnet-runtime-3.1/dotnet-runtime-3.1.spec, SPECS/dotnet-sdk-3.1/dotnet-sdk-3.1.signatures.json, SPECS/dotnet-sdk-3.1/dotnet-sdk-3.1.spec, cgmanifest.json
---
Update dotnet packages to resolve CVE-2021-31204
- Update aptnetcore-runtime to version 3.1.15
- Update dotnet-runtime to version 3.1.15
- Update dotnet-sdk to version 3.1.115
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-31204
=> Update dotnet runtime and aspnetcore to 3.1.15 and sdk to 3.1.115

SPECS/moby-runc/generate-sources.sh, SPECS/moby-runc/getgosyssources.sh, SPECS/moby-runc/moby-runc.signatures.json, SPECS/moby-runc/moby-runc.spec, cgmanifest.json
---
Update moby-runc to latest version
- Update moby-runc SPEC to use latest
- Update moby-runc dependencies to latest versions (golang-sys, golang-crypto, logrus, urfave-cli)
- Update cgmanifest.json with dependency packages listed above
- Add generate-sources.sh script to create moby-runc-v1.0.0-rc94.tar.gz (latest code does not build without .git)
NO
- #xxxx
=> Update moby-runc to version 1.0.0~rc94+azure

.github/workflows/check_entangled_specs.py, SPECS/azure-iotedge/azure-iotedge.signatures.json, SPECS/azure-iotedge/azure-iotedge.spec, SPECS/libiothsm-std/libiothsm-std.signatures.json, SPECS/libiothsm-std/libiothsm-std.spec, cgmanifest.json
---
Update azure-iotege
- Update azure-iotedge to version 1.1.2
- Update libiothsm-std to version 1.1.2
- Update cgmanifest
NO
- Local package build. Installed both packages on build "1.0.20210513" from 1.0-dev branch. Add sample connection string to /etc/iotedge/config.yaml. Restart the service with "sudo systemctl restart iotedge" and then observe results of "sudo iotedge check" which were all green.
=> Update azure-iotedge and libiothsm-std to version 1.1.2

SPECS/mariner-rpm-macros/macros.rust-srpm, SPECS/mariner-rpm-macros/mariner-rpm-macros.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add support for Fedora's Rust SRPM macros to our toolchain. These are taken from Fedora's [rust2rpm python package](https://pagure.io/fedora-rust/rust2rpm/tree/master).
- Add macros.rust-srpm to the mariner-rpm-macros package
**YES**
- Local Build
=> Add Rust SRPM macros to mariner-rpm-macros

SPECS/moby-runc/generate-sources.sh, SPECS/moby-runc/moby-runc.signatures.json, SPECS/moby-runc/moby-runc.spec, cgmanifest.json
---
Update moby-runc to 1.0.0-rc95 to fix CVE
- Update moby-runc
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-30465
- Local package build. Installed on recent image and tested docker commands.
=> Update moby-runc to 1.0.0-rc95

SPECS/moby-runc/moby-runc.signatures.json, SPECS/moby-runc/moby-runc.spec
---
Cleanup merge issues from moby-runc cherry-pick to 1.0 branch
- update moby-runc spec and signatures.json
NO
=> fix moby-runc merge issues in 1.0 branch

toolkit/docs/building/building.md
---
Extending documentation about the `REPO_LIST` argument to mention existing CBL-Mariner repos.
- Added a few lines to the docs about `REPO_LIST`.
No.
- Local markdown viewer check.
=> Adding documentation about the `REPO_LIST` argument.

.github/pull_request_template.md
- [x ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x ] All source files have up-to-date …
=> PR Template fixes

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS-SIGNED/kernel-signed/sha512hmac-openssl.sh, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Recalculate sha512hmac on signed kernel binary. Needed for FIPS.
- Recalculate sha512hmac on signed kernel binary
Yes
None
None
Local build
=> Recalculate sha512hmac on signed kernel binary

SPECS/cdrkit/cdrkit.spec
---
- `cdrkit` provides `genisoimage` but it was not explicity marked in the spec.
**NO**
local build
=> cdrkit: add an explicit provides for 'genisoimage'

SPECS/itstool/itstool.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
We've missed updating a toolchain package `itstool` to move it from Python 2 to Python 3. This ended up causing package build issues in our pipelines.
Change is an extension of the following PRs: #919 and #968.
- Modified `itstool` to build against and rely on Python 3 packages.
- Updated toolchain scripts to remove Python 2 leftovers.
Yes.
=> [dev] Fixing `itstool` build and switching it to use Python 3 packages.

SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
---
We forgot to upload the source to our servers before merging #886. I've done this now, but unfortunately the manually generated "vendor" source has a different hash every time it's re-generated locally (I'll need to update the instructions on how to avoid that once I learn how to do that), so I had to update the signatures for the sake of this fix. I didn't have the original tarball.
- Update "vendor" tarball's signature to match the version in our sources server.
No.
- N/A, relying on the build check from #886.
=> Updating `nvidia-container-toolkit` signatures to match source.

SPECS/libwebp/libwebp.signatures.json, SPECS/libwebp/libwebp.spec, cgmanifest.json
---
Update libwebp to 1.0.3 to fix various CVEs.
- Update libwebp to 1.0.3
NO
- https://nvd.nist.gov/vuln/detail/CVE-2018-25009
- https://nvd.nist.gov/vuln/detail/CVE-2018-25010
- https://nvd.nist.gov/vuln/detail/CVE-2018-25011
- https://nvd.nist.gov/vuln/detail/CVE-2018-25012
- https://nvd.nist.gov/vuln/detail/CVE-2018-25013
- https://nvd.nist.gov/vuln/detail/CVE-2018-25014
- https://nvd.nist.gov/vuln/detail/CVE-2020-36329
- https://nvd.nist.gov/vuln/detail/CVE-2020-36330
- https://nvd.nist.gov/vuln/detail/CVE-2020-36331
- Local build
=> Update libwebp to 1.0.3, fixing CVEs.

SPECS/fluent-bit/fluent-bit.signatures.json, SPECS/fluent-bit/fluent-bit.spec, SPECS/p7zip/p7zip.spec, cgmanifest.json
---
1) Update fluent-bit version to 1.5.2
2) Add no patch for CVE-2018-5996 to p7zip
- Change
Fluent-bit: Update to version 1.5.2
- Change
p7zip: Add nopatch for CVE-2018-5996
YES
**NO**
Local build
=> Update fluent-bit version and add nopatch for p7zip

SPECS/libgudev/libgudev.spec
---
Other distros can sometimes call their `libgudev` packages `libgudev1`, in reference to the major version of the library. So, we provide this name to meet this expectation.
- Provide `libgudev1` and `libgudev1-devel` from `libgudev` and `libgudev-devel`, respectively
NO
- Local build
=> [dev] Add libgudev1* provides to libgudev spec

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
`kernel-headers` was historically provided by the glibc package, and was named `glibc-kernheaders`. We add a provides statement to the package to remain backwards-compatible with older external specs. 
- Provide `glibc-kernheaders` from `kernel-headers`
**YES**
- Local build
=> [dev] Add glibc-kernheaders provides to kernel-headers

toolkit/tools/imagegen/attendedinstaller/primitives/enumfield/enumfield.go, toolkit/tools/imagegen/attendedinstaller/views/diskview/manualpartitionwidget/manualpartitionwidget.go
---
This PR implements an accessible input field with enumerable selection for the attended installer.
- Create EnumField, an accessible input field with enumerable selection for the attended installer.
- Integrate EnumField with attended installer.
NO
- local build
=> Implement and integrate enumfield

SUPPORT.md
Signed-off-by: Jim Perrin <Jim.Perrin@microsoft.com>
---
Adds a SUPPORT.md file to the repository as part of project documentation
- Added SUPPORT.md file to repository for project documentation
NO
=> Add SUPPORT.md file to repo

SPECS/dhcp/CVE-2021-25217.patch, SPECS/dhcp/dhcp.spec
---
YES
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-25217
=> Patch dhcp for CVE-2021-25217

SPECS/coredns/coredns-1.6.7.signatures.json, SPECS/coredns/coredns-1.6.7.spec, SPECS/coredns/coredns-1.7.0.signatures.json, SPECS/coredns/coredns-1.7.0.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.signatures.json, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec
---
Attempts to reproduce a vendor source tarball from the specs modified in this PR often failed, because `tar` included additional metadata, which were different depending on the user's environment. This changes addresses that issue by following the [directions from reproducible-builds.org](https://reproducible-builds.org/docs/archives/).
NOTE: I'll update the sources at the time this PR is merged. I'll wait for the appropriate time to not disturb any running builds.
- Updated vendor tarballs generation instructions and tarball signatures to match the new ones generated according to the new instruction.
No.
- None, comment and sources update without changing build steps.
=> Making vendor tarballs reproducible for `coredns` and `nvidia-container-toolkit`

SPECS/coredns/coredns-1.6.7.signatures.json, SPECS/coredns/coredns-1.6.7.spec, SPECS/coredns/coredns-1.7.0.signatures.json, SPECS/coredns/coredns-1.7.0.spec
---
Attempts to reproduce a vendor source tarball from the specs modified in this PR often failed, because `tar` included additional metadata, which were different depending on the user's environment. This changes addresses that issue by following the [directions from reproducible-builds.org](https://reproducible-builds.org/docs/archives/).
NOTE: I'll update the sources at the time this PR is merged. I'll wait for the appropriate time to not disturb any running builds.
This change reflects updates from #983.
- Updated vendor tarballs generation instructions and tarball signatures to match the new ones generated according to the new instruction.
No.
- None, comment and sources update …
=> [dev] Updating `coredns` signatures

SPECS/mariner-rpm-macros/macros.fonts, SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json, SPECS/mariner-rpm-macros/mariner-rpm-macros.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
We need these macros in the chroot during the specs parsing phase to correctly detect packages provided by different specs.
- Add the macros from `macros.fonts` to `mariner-rpm-macros`.
No.
=> Adding macros from 'macros.fonts'.

SPECS/polkit/CVE-2021-3560.patch, SPECS/polkit/polkit.spec
---
YES
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3560
=> Fix polkit CVE-2021-3560

toolkit/docs/nvidia/mariner-nvidia.repo, toolkit/docs/nvidia/nvidia.md
---
This PR adds documentation to explain how users can configure their package manager to access the NVIDIA PMC RPMs. The documentation also includes the NVIDIA Licensing statement to meet our legal requirements.
- Creation of nvidia.md documentation
- Creation of mariner-nvidia.repo file
**YES**
NO
=> Creating nvidia repo file and user instructions

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Dash roll the mariner-release file for the May Update.
=> Update mariner-release for May Update

.github/workflows/check-entangled-specs.yml, .github/workflows/check-license-map.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/go-test-coverage.yml, .github/workflows/lint-specs.yml
---
Adding human-readable names to our automated checks to make it easier to enable/disable them when needed in the repo's settings.
- Adding nicer names to GitHub actions.
No.
- Checked as part of this PR.
=> Making GitHub checks' names more human-readable.

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2020-25672.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2020-25672 with a no patch.
- Address CVE-2020-25672
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-25672
- local toolchain and package build
=> Kernel: Address CVE-2020-25672

SPECS/dhcp/dhcp.spec
---
The dhcp packages does not have an explicit provides for `dhclient` even though we ship it.
**NO**
- Local Build
=> dhcp: add explicit provides for dhclient

.github/pull_request_template.md
---
Update pull request template with section covering package tests. 
- Change github PR template
**NO**
- N/A
=> Update PR template with package test check

SPECS/qemu-kvm/CVE-2021-20181.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
This PR patches qemu-kvm CVE-2021-20181
- Patch CVE-2021-20181
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-20181
- Local Build
=> Patch qemu-kvm: CVE-2021-20181

SPECS/python-execnet/python-execnet.spec, SPECS/python-repoze-lru/python-repoze-lru.spec
---
Fix check tests for python-execnet and python-repoze-lru
- Change tox arguments in python-repoze-lru.spec
- Change tox arguments in python-execnet.spec
- Fix incorrect version in changelogs
**NO**
=> Fix check tests for python-execnet and python-repoze-lru

SPECS/polkit/polkit.spec
---
Enable polkit check tests
- Enable polkit check tests
**NO**
=> Enable polkit check tests

SPECS/man-db/man-db.spec
---
add explicit provides for `man-pages-reader`
**NO**
- local build
=> [dev] man-db: add explicit provides for 'man-pages-reader'

SPECS/nss/CVE-2020-12403.patch, SPECS/nss/nss.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
This PR patches CVE-2020-12403 in nss by disabling multi-part ChaCha20 and forcing a strict tag length.
- Patch nss CVE-2020-12403
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2020-12403
- Local Build
=> Patch nss CVE-2020-12403

.github/pull_request_template.md
---
Update pull request template with section covering package tests.
Cherry-pick #1025 into 1.0 branch since the default branch (1.0) is used for pull requests on other branches
- Change github PR template
**NO**
- N/A
=> Update PR template with package test check (1.0 branch)

SPECS/postgresql/postgresql.signatures.json, SPECS/postgresql/postgresql.spec, cgmanifest.json
This is a cherry-pick of CVE fix from PR #1039
=> Cherry-pick #1039

toolkit/tools/imagegen/installutils/installutils.go
---
File owner does not need write permissions to /etc/machine-id.
So let's remove the owner's write permission from this file by
default. systemd will still bind-mount the system's unique
machine-id to this file and preserve permissions.
- Change default permissions from /etc/machine-id from 644 to 444
No
Local build
=> installutils: remove machine-id owner write perms

.github/workflows/check-entangled-specs.yml
---
This check doesn't run if no .spec files were changed and it's set as one of the required checks. [It looks like GitHub doesn't yet support conditionally requiring a check](https://github.community/t/feature-request-conditional-required-checks/16761/8) and is not smart enough to figure that requirement from the paths the check is triggered for, so for now we'd need to keep running for all PRs. Fortunately, the check itself is lightweight.
- Enabled spec entanglement check for all PRs.
No.
- This PR run.
=> Unblocking spec entanglement check.

toolkit/tools/imagegen/installutils/installutils.go
---
populate user's ssh/authorized_keys with pubkey provided in image config
- This copies the pubkey provided in image config to user's ~/.ssh/authorized_keys file.
- Package openssh-server exists in azurevm-packages.json, and is already being built in marketplace image.
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/32546954
- None
- Built marketplace gen1 image and tested on Hyper-v VM. Confirmed that the pubkey got added to user's ~/.ssh/authorized_keys file and user could SSH using the key.
=> populate user's ssh/authorized_keys

toolkit/imageconfigs/marketplace-gen1.json, toolkit/imageconfigs/marketplace-gen2.json
---
Change image config for Marketplace VM Offer
- Increased the OS disk size and changed kernel parameters so that the image passes validation.
NO
- None
- None
- Image built locally and tested by Chris and Henry Li on Azure. It passed all the tests.
=> change image config for Marketplace VM Offer

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> Update mariner-release version number

SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
---
Update ansible to version 2.9.18. This resolves CVE-2021-20191 and CVE-2021-20178
- Update ansible to version 2.9.18
No
None
- https://nvd.nist.gov/vuln/detail/CVE-2021-20191
- https://nvd.nist.gov/vuln/detail/CVE-2021-20178
- Local build
=> Update ansible to version 2.9.18

cgmanifest.json
---
We want to keep our `cgmanifest.json` ordered and it looks like we've missed a few packages.
- Sorted `cgmanifest.json`.
No.
- N/A, nothing to build, manifest gets checked automatically by PR actions.
=> Sorting 'cgmanifest.json'.

SPECS/harfbuzz/harfbuzz.spec
---
Harfbuzz ICU support is required for some packages. This fixes that problem by adding fontconfig and icu to the build environment. Additionally, this fixes the package test for harfbuzz and cleans up the spec.
For harfbuzz:
- Build with icu libraries, fontconfig libraries
- Use pkgconfig(*)-style dependencies
- Provide harbuzz-icu from devel subpackage
- Use macros throughout the spec
- Fix package tests by fixing Python shabangs
- Update URL
**NO**
=> [dev] Update harfbuzz to have icu support

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Add --force flag when installing RPMs during second part of toolchain build process. This resolves toolchain build issues seen on some build machines.
- Add --force flag to second phase toolchain build script
**YES**
=> Force install RPMs in toolchain build

SPECS/iptables/iptables.spec
---
Add dependency on `iana-etc`. This is needed since the mangle table prerouting rules specify `--dport ssh`. Without `iana-etc`, iptables fails to boot with an "`invalid port/service 'ssh' specified`" message.
- Add dependency on iana-etc
**NO**
- fixes #1049 
- local build
=> iptables: Add dependency on iana-etc

SPECS/nghttp2/nghttp2.spec
---
The binaries we provide through the `nghttp2*` packages are also known under the names `libnghttps*`, so we're adding the `Provides` statements to cover such cases.
- Added `libnghttp2*` `Provides` to `nghttp2`.
No.
=> [dev] Adding `libnghttp2*` `Provides` to `nghttp2`.

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Add --force flag when installing RPMs during second part of toolchain build process. This resolves toolchain build issues seen on some build machines.
Porting from 1.0-dev branch from #1041 
- Pull #1041 from 1.0-dev
**YES**
- Pipeline toolchain build. buildId=104644
=> [dev] Force install RPMs in toolchain build

SPECS/httpd/CVE-2021-26691.patch, SPECS/httpd/httpd.spec
Fix CVE-2021-26691 for httpd
---
Fix CVE-2021-26691 for httpd
- Change
CVE-2021-26691 fix
**NO**
- #xxxx
Local build
=> Fix CVE-2021-26691 for httpd

SPECS/protobuf-c/protobuf-c.signatures.json, SPECS/protobuf-c/protobuf-c.spec, cgmanifest.json
---
The recent version update for `protobuf` has introduced a breaking change for `protobuf-c` tests, which was resolved in its 1.3.2 version. For details see: [here](https://github.com/protobuf-c/protobuf-c/pull/342).
- Updated `protobuf-c` to version 1.3.2.
No.
- Local package build of `protobuf-c`, `collectd`, and `moby-runc`.
=> Updating `protobuf-c` to version 1.3.2 to work with the new 3.14.0 version of `protobuf`.

SPECS/harfbuzz/harfbuzz.spec
---
#1066 changed the `freetype-devel` dependency in the `harfbuzz` spec to `pkgconfig(freetype)`. That was incorrect, the proper requirement there should be `pkgconfig(freetype2)`.
- Harfbuzz: `BR: pkgconfig(freetype)` -> `BR: pkgconfig(freetype2)`
**NO**
- Local build
=> [dev] Fix harfbuzz dependency on freetype

SPECS/python-jwt/python-jwt.spec, SPECS/python-pecan/python-pecan.spec, SPECS/python-remoto/python-remoto.spec, SPECS/python-routes/python-routes.spec
---
Pass the check section for python-jwt, python-pecan, python-routes and python-remoto
- Pass the check section for python-jwt, python-pecan, python-routes and python-remoto
NO
- https://microsoft.visualstudio.com/OS/_workitems/edit/33757927
- None
=> Pass tests in python packages jwt, pecan, routes, remoto

SPECS/curl/CVE-2021-22897.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Fix CVE-2021-22897 for curl.
---
Fix CVE-2021-22897 for curl
- Change
Fix CVE-2021-22897 for curl
**YES**
- #xxxx
Local build.
=> Fix CVE-2021-22897 for curl

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update release number for June 2021 release
- Update mariner-release version
**YES**
=> Update release number for June 2021 release

SPECS/libusb/libusb.signatures.json, SPECS/libusb/libusb.spec, cgmanifest.json
---
This PR upgrades `libusb` to 1.0.24. Additionally, it modernizes the spec and adds compatibility provides for the `libusbx`, `libusb1` names.
- Upgrade `libusb` to 1.0.24
- Modernize `libusb` spec
- Provide `libusbx`, `libusb1` from the `libusb` base package
- Provide `libusbx-devel`, `libusb1-devel` from the `libusb-devel` package
**NO**
=> [dev] Upgrade libusb to 1.0.24, add compatibility provides

cgmanifest.json
---
Update cgmanifest.json with source versions that are used in toolchain build process.
- Update cgmanifest
**NO**
- N/A
=> Add toolchain sources to cgmanifest.json

SPECS/libconfig/libconfig.spec
---
This is an update to PR #1100 to make sure we are not overly aggressive in the version of the shared library we expect. In most projects only a change to the major version number is a sign of a potential breaking change, which requires recompilation of the dependencies.
- Removed the minor version number from expected file name.
No.
- None, simple spec change.
=> Fixing shared libraries declaration.

SPECS/python-six/python-six.spec
---
Some packages expect `python2-six` instead of `python-six` and this PR addresses that issue.
- Added `Provides: python2-six` to the `python-six` package.
No.
- None, simple spec update.
=> Adding alternative 'Provides' for 'python-six'.

SPECS/file/file.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh
---
Adding the `python3-magic` subpackage to `file`. It's required by some other packages.
- Added the `python3-magic` subpackage to `file`.
Yes.
=> Enabling `python3-magic` subpackage.

SPECS/python-urllib3/python-urllib3.signatures.json, SPECS/python-urllib3/python-urllib3.spec, SPECS/ragel/ragel.spec, cgmanifest.json
---
- Revert the version upgrade change to python-urllib3 to resolve ceph build break
- Remove unneeded Provides from ragel
- Revert python-urllib3 to version 1.25.9
- Remove Provides bundled(aapl)
NO
- #xxxx
- Local Build
=> Resolve 1.0-dev Build Break

SPECS/ruby/ruby.spec
---
The gemification of the ruby standard library means some packages will expect parts of the standard library to reside in the gems directory. This PR installs ruby's json library into the gems directory, and makes the ruby package provide the rubygem-json package.
Additionally, adds attribution to Fedora's spec where appropriate.
- Add attribution for parts of the install script taken from Fedora (license: MIT)
- Add provides for rubygem(json), and install json gem into the gemdir
- Modernize spec with macros
**NO**
=> [dev] Install ruby's json library as a gem

SPECS/moby-containerd/generate-sources.sh, SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec
---
Update moby-containerd to version 1.4.4
- Change moby-containerd to version 1.4.4
**NO**
- #xxxx
=> Update moby-containerd to version 1.4.4

SPECS/python-psycopg2/python-psycopg2.spec
---
Adds a doc subpackage for psycopg2
NO
- NA
- NA
- local build
=> [dev] psycopg2: add doc subpackage

SPECS/newt/newt.spec
---
It add a subpackage `python3-newt` for pkg `newt`.
- Enable python3-newt
NO
- NA
- NA
- local build
=> [dev] newt: enable subpackage python3-newt

SPECS/bazel/bazel.spec, SPECS/bazel/fix-jni-build-error.patch
---
bazel fails to build on aarch64 due to an error with jni header files. Apply the fix to enable bazel building on aarch64
- Apply patch to resolve jni build error on aarch64
NO
- #xxxx
- Local Build
=> [dev] Resolve bazel aarch64 build break

toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Ensure PAM package has selinux support by (re)building the PAM package after libselinux is available.
- Modify toolchain script to rebuild pam
**YES**
- Pipeline build, local toolchain build.
=> Build PAM with selinux support

SPECS/moby-containerd/generate-sources.sh, SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec
---
Port the moby-containerd update to version 1.4.4 into the 1.0 branch
- Change moby-containerd to 1.4.4
**NO**
- #xxxx
=> Update moby-containerd to version 1.4.4 - port to 1.0 branch

SPECS/libtasn1/libtasn1.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adds a provides to `libtasn1-tools` for compatibility with other distros.
- Add an explicit provides.
- Annotate pkgconfig with release-version.
**YES**
- NA
- NA
- local build of the package
=> libtasn1: add provides for tools subpackage

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/config, SPECS/kernel-hyperv/kernel-hyperv.signatures.json, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/config, SPECS/kernel/kernel.signatures.json, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Partner requested that CONFIG_PROC_EVENTS=y is set. This config also
requires CONFIG_CONNECTOR=y.
- Set CONFIG_PROC_EVENTS=y and CONFIG_CONNECTOR=y in x86_64 config. Already set in ARM64 config.
- Bump kernel-related package release numbers
**YES**
Local build. Local test. Pipeline builds.
=> kernel: Enable CONFIG_PROC_EVENTS

SPECS/libvirt/libvirt.spec
---
One of our build pipelines started failing while attempting to build `libvirt`. Since the issues is non-trivial to debug, I'm reverting the change for now to unblock other changes. We're going to keep the additional packages added to enable the new subpackages, as they don't cause any issues and are going to be needed for future work.
- Reverted the sum of `libvirt.spec` changes from the following PRs: #1134, #1150, #1155.
No.
- Local build of `libvirt`.
=> Reverting extension of `libvirt` by 25 subpackages.

toolkit/imageconfigs/packagelists/core-packages-image-aarch64.json, toolkit/imageconfigs/packagelists/core-packages-image.json
---
Typically crond and logrotate are included as part of the default image.
Let's include both into the default core packagelist which is typically
used by our top-level imageconfigs.
**NO**
Local build
=> packagelist: Add cronie and logrotate to images

SPECS/dtc/dtc.spec, SPECS/net-snmp/net-snmp.spec
---
A small fix to two spec files changed recently in #1192.
- Used `$LDFLAGS` instead of undefined `%{ldflags}` inside `dtc.spec`.
- Added a missing hyphen in `--with-defaults` inside `net-snmp,spec`.
No.
- #1192
=> Fixing `dtc` and `net-snmp` specs.

SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
---
Fix test for perl-CPAN-Meta-Check
- Install Test::Deep dependency for perl-CPAN-Meta-Check check tests
**NO**
- Local test build:
time sudo make build-packages PACKAGE_BUILD_LIST="perl-CPAN-Meta-Check" PACKAGE_REBUILD_LIST="perl-CPAN-Meta-Check" -j8 REBUILD_TOOLS=y SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core REBUILD_DEP_CHAINS=n CONFIG_FILE= RUN_CHECK=y
=> Fix test for perl-CPAN-Meta-Check

SPECS/python-twisted/python-twisted.signatures.json, SPECS/python-twisted/python-twisted.spec, cgmanifest.json
---
Upgrade python-twisted to 20.3.0 to fix CVE-2020-10108, CVE-2020-10109
- Upgrade python-twisted to version 20.3.0
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-10108
- https://nvd.nist.gov/vuln/detail/CVE-2020-10109
- Local build of python-twisted and dependent packages
- Package tests do not pass. Tests were erroneously counting as passing in the previous version- no net change.
=> Upgrade python-twisted to 20.3.0 to fix CVE-2020-10108, CVE-2020-10109

SPECS/libvirt/libvirt.spec
This reverts commit a1f02c913fed211a9fa65ce7a6a03065292da9e5.
---
After fixing the build issue, we're bringing back the `libvirt` updates with 25 new subpackages. This is a revert of #1174.
- Updating `libvirt.spec` to produce 25 new subpackages.
No.
- Local package build and official build.
=> [dev] Bringing back `libvirt` subpackages. Revert of #1174.

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/hyperv-daemons/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/0001-Revert-scsi-sr-Return-appropriate-error-code-when-di.patch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Our validation found that cdrom eject is causing a udev event storm and
regressing many performance metrics. Issue isolated to a commit
introduced upstream and backported to stable kernel. Reverting this
commit to mitigate the issue. We will be working with LKML in the
meantime to fix the underlying issue.
**YES**
Local build, Pipeline build
=> kernel: Add patch to revert a cdrom eject commit

SPECS/swig/swig.signatures.json, SPECS/swig/swig.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update swig to version 4.0.2 to meet a dependency request.
- Update swig to version 4.0.2
**YES**
- Confirmed that %check section passes
=> Update swig to 4.0.2

SPECS/swig/swig.signatures.json, SPECS/swig/swig.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update swig to 4.0.2 for a dependency request
- Update swig to 4.0.2
**YES**
- %check section passes
=> Update swig to 4.0.2 (#1236)

SPECS/libdb/libdb.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
nopatch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981 
- add nopatch file and increment release nb of spec
**NO**
- #xxxx
CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981 and CVE-2020-2981
- https://nvd.nist.gov/vuln/detail/CVE-2017-3604
- https://nvd.nist.gov/vuln/detail/CVE-2017-3605
- https://nvd.nist.gov/vuln/detail/CVE-2017-3606
- https://nvd.nist.gov/vuln/detail/CVE-2017-3607
- https://nvd.nist.gov/vuln/detail/CVE-2017-3608
- https://nvd.nist.gov/vuln/detail/CVE-2017-3609
- https://nvd.nist.gov/vuln/detail/CVE-2017-3610
- https://nvd.nist.gov/vuln/detail/CVE-2017-3611
- https://nvd.nist.gov/vuln/detail/CVE-2017-3612
- https://nvd.nist.gov/vuln/detail/CVE-2017-3613
- …
=> libdb - no patch CVE-2017-3604 to CVE-2017-3617 and CVE-2020-2981

SPECS/rubygem-addressable/rubygem-addressable.signatures.json, SPECS/rubygem-addressable/rubygem-addressable.spec, cgmanifest.json
---
Move to 2.8.0 to fix CVE-2021-3274
- Change spec file
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-3274
=> rubygem-addressable - Move to 2.8.0 to fix CVE-2021-3274

SPECS/qt5-qtbase/qt5-qtbase.signatures.json, SPECS/qt5-qtbase/qt5-qtbase.spec, SPECS/qt5-qtdeclarative/qt5-qtdeclarative.signatures.json, SPECS/qt5-qtdeclarative/qt5-qtdeclarative.spec, SPECS/qt5-qtsvg/qt5-qtsvg.signatures.json, SPECS/qt5-qtsvg/qt5-qtsvg.spec, SPECS/qt5-qttools/qt5-qttools.signatures.json, SPECS/qt5-qttools/qt5-qttools.spec, SPECS/qt5-rpm-macros/qt5-rpm-macros.spec, cgmanifest.json
---
update to version 5.12.11 to address CVE-2015-9541, CVE-2020-0570 and CVE-2020-13962
relevant spec files
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2015-9541
- https://nvd.nist.gov/vuln/detail/CVE-2020-0570
- https://nvd.nist.gov/vuln/detail/CVE-2020-13962
=> qt5-qtbase fix CVE-2015-9541, CVE-2020-0570 and CVE-2020-13962

SPECS/python-psutil/python-psutil.signatures.json, SPECS/python-psutil/python-psutil.spec, cgmanifest.json
---
Update to 5.6.7 to fix CVE-2019-18874
spec and signature file
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-18874
=> python-psutil - Update to 5.6.7 to fix CVE-2019-18874

SPECS/qt5-qtbase/qt5-qtbase.spec
---
The qt5-qtbase pkg-config file (Qt5.pc) contained an incorrect version number; fix this to use the version variable. This also caused the package test to fail
- Change qt5-qtbase spec
**NO**
=> Fix qt5-qtbase Qt5.pc version

SPECS/util-linux/CVE-2021-37600.patch, SPECS/util-linux/util-linux.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adding a patch to fix a critical CVE 2021-37600.
- Patched CVE 2021-37600.
Yes.
- https://nvd.nist.gov/vuln/detail/CVE-2021-37600
=> Fixing CVE 2021-37600 in `util-linux`

SPECS/core-packages/core-packages.spec, SPECS/dnf/dnf.spec
---
Update release in core-packages
- Update release number in core-packages
NO
- Local build
=> Update release in core-packages

SPECS/qt5-qtbase/qt5-qtbase.spec
---
The qt5-qtbase pkg-config file (Qt5.pc) contained an incorrect version number; fix this to use the version variable. This also caused the package test to fail
- Change qt5-qtbase spec
**NO**
=> Fix qt5-qtbase Qt5.pc version (1.0 branch)

SPECS/openvswitch/openvswitch.signatures.json, SPECS/openvswitch/openvswitch.spec, cgmanifest.json
---
Updated `openvswitch` to version 2.15.1 to fix CVE-2021-36980.
- Updated spec to version 2.15.1.
- Removed no longer present OVN components.
- Changed the source URL to use HTTPS.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-36980
=> Updating `openvswitch` to version 2.15.1 to fix CVE-2021-36980.

SPECS/fipscheck/fipscheck.spec
---
Requires for the binary fipscheck causes build error in internal
pipeline. So removing it. It will not cause any problem as the binary is
provided by the same spec file.
- Remove `Requires /usr/bin/fipscheck` from fipscheck package
**NO**
- #xxxx
=> Remove `Requires /usr/bin/fipscheck` from fipscheck package

SPECS/krb5/krb5.signatures.json, SPECS/krb5/krb5.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Bump the version of krb5 1.17 -> 1.18.
Version 1.18 is a requirement for other packages.
- Bump version to 1.18
**YES**
- NA
- NA
- localbuild
=> [dev] krb5: bump version to 1.18

SPECS/qemu-kvm/CVE-2021-3682.patch, SPECS/qemu-kvm/qemu-kvm.spec
---
Fixing CVE-2021-3682 in `qemu-kvm`.
- Added a patch for CVE-2021-3682.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-3682
=> Fixing CVE-2021-3682 in `qemu-kvm`.

SPECS/nettle/nettle.signatures.json, SPECS/nettle/nettle.spec, cgmanifest.json
Bump version: 3.7.2 -> 3.7.3
---
Fix CVE-2021-3580
- Bump version: 3.7.2 -> 3.7.3
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3580
- localbuild
=> nettle: fix CVE-2021-3580

SPECS/rust/CVE-2021-29922.patch, SPECS/rust/rust.spec
---
Fix CVE-2021-29922
- NA
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-29922
- localbuild
=> rust: fix CVE-2021-29922

SPECS/cpio/CVE-2021-38185.patch, SPECS/cpio/cpio.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix CVE-2021-38185
- Adjust the fuzz factor for `patch` command as 2.
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-38185
- localbuild
=> cpio: fix CVE-2021-38185

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping Mariner-Release version in support of off-cycle kernel and toolchain updates.
=> Bump mariner-release for off-cycle update

SPECS/zstd/zstd.signatures.json, SPECS/zstd/zstd.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- zstd: fix CVE-2021-24031
- zstd: update manifests
---
Fix CVE-2021-24031
- Bump version: 1.4.4 -> 1.4.9
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-24031
- localbuild
=> zstd: fix CVE-2021-24031

SPECS/ctags/CVE-2014-7204.patch, SPECS/ctags/ctags.spec
---
Fix CVE-2014-7204
- Patch with fix for CVE-2014-7204
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2014-7204
- localbuild
=> ctags: fix CVE-2014-7204

SPECS/python3/python3.spec
---
There was a broken symlink with a python3 so file. To fix, move the symlink to the devel section so that it is only added when it's destination is hydrated. 
To replicate: 
docker run -it cblmariner.azurecr.io/base/core:1.0 /bin/bash
```
root [ / ]# find -xtype l # will show list of symlinks that are broken 
root [ / ]# file ./usr/lib/libpython3.7.so
./usr/lib/libpython3.7.so: broken symbolic link to libpython3.7m.so
```
- Move libpython3.7.so to devel files to resolve broken symlink 
NO
- local build (passed %check and verified in vm)
=> python3: Resolve python3 broken symlink

SPECS/perl-File-HomeDir/perl-File-HomeDir.spec, SPECS/perl-File-Which/perl-File-Which.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Due to a quirk of how the package graph calculates rebuilds, `perl-File-HomeDir` and `perl-File-Which`'s absences from the toolchain caused some toolchain packages (`openldap`, `audit`, `shadow-utils`, etc.) to rebuild during the regular package build phase. Toolchain packages are not meant to be rebuilt in that fashion, and building in such a manner may fail. This PR adds the two packages to the toolchain to avoid these rebuilds. 
- Add `perl-File-HomeDir`, `perl-File-Which` to the toolchain
**YES**
=> [dev] Add perl-File-HomeDir, perl-File-Which to the toolchain to avoid rebuilds

SPECS/cronie/cronie.spec
---
Adding `Provides: anacron` to `cronie` as that's our package name for what `anacron` provides in Fedora for instance.
- Added `Provides: anacron` to `cronie`.
No.
=> [dev] Adding `Provides: anacron` to `cronie`

SPECS/apr-util/apr-util.spec
---
Adding a few more `apt-util` subpackages to cover the most common requirements.
Also removed NSS components, as they are not needed for our scenarios.
- Added subpackages:
- `*-bdb`;
- `*-mysql`;
- `*-odbc`.
- Split out the `*-openssl` subpackage out of the default `apr-util`.
- Removed NSS components.
- Basic spec clean-up.
No.
- Local package build with `RUN_CHECK=y` - tests passed.
=> `apt-util`: adding more subpackages

SPECS/util-linux/util-linux.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
While we did have `uuidd` available through `util-linux`, it failed to run due to missing directories, which I'm now adding. Also, added a `Provides: uuidd` to better align with user expectations.
- Added directories required by `uuidd`.
- Made `util-linux` provide `uuidd`.
- Basic spec linting.
Yes.
- Local package build and installation in a CBL-Mariner container.
=> `util-linux`: fixing `uuidd`

SPECS/binutils/binutils.spec, SPECS/binutils/export-demangle-header.patch, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Match the behavior of other distributions by exporting the `demangle.h` header from libiberty in the `binutils` package.
- Add Fedora 34 patch to export `demangle.h` in the `binutils-devel` subpackage
**YES**
=> [dev] Export demangle.h from libiberty in binutils

SPECS/collectd/collectd.spec
---
`libvirt` changes from #1175 did not fully fix the official build break mentioned in #1174 that caused their revert in the first place. While that build quirk is being investigated, we workaround the issue and unblock the build by disabling the dependency on `libvirt-devel` by `collectd`. This is done by disabling the `collectd-virt` subpackage.
Similar purpose to #1245.
- Disable collectd-virt subpackage
**NO**
- Local build
=> Disable collectd-virt subpackage due to build break

SPECS/binutils/binutils.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
This reverts commit daf69ca4ef96f3928515689130f56ce8dc24e8ef.
---
Looks like #1340 broke our build. Reverting for now to get people unstuck and we can investigate offline.
- Revert #1340.
Yes.
=> [dev] Revert "[dev] binutils: export libiberty for devel subpackage (#1340)"

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> Update CBL-Mariner Version Number for August Update

SPECS/hyperv-daemons/hyperv-daemons.signatures.json, SPECS/hyperv-daemons/hyperv-daemons.spec, SPECS/kernel-headers/kernel-headers.signatures.json, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/config, SPECS/kernel-hyperv/kernel-hyperv.signatures.json, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/config, SPECS/kernel/config_aarch64, SPECS/kernel/kernel.signatures.json, SPECS/kernel/kernel.spec, SPECS/mariner-release/mariner-release.spec, SPECS/mysql/mysql.spec
Previous merge included diff markings by accident. These have been removed.
=> Remove diff glyphs

SPECS/git/git.signatures.json, SPECS/git/git.spec, cgmanifest.json
---
Bump git version: 2.23.4 -> 2.33.0
- Bump version to 2.33.0
**NO**
- NA
- NA
- localbuild
=> [dev] git: bump version to 2.33.0

SPECS/rsyslog/rsyslog.spec, SPECS/syslog-ng/syslog-ng.conf, SPECS/syslog-ng/syslog-ng.signatures.json, SPECS/syslog-ng/syslog-ng.spec
---
1. Enable omuxsock in rsyslog
2. Add customized syslog-ng.conf for Mariner
- Change
Enable omuxsock in rsyslog
- Change
Add customized syslog-ng.conf for Mariner
**NO**
- #xxxx
- Local build
=> Enable omuxsock in rsyslog and add customized syslog-ng conf

SPECS/cpio/CVE-2021-38185.patch, SPECS/cpio/cpio.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add a patch to fix CVE-2021-38185 for the cpio package.
The previous patch (#1294 ) was reverted due to build breaks. This PR includes a modified patch with 3 merged commits
- Add patch to cpio
- Update manifests
**YES**
#1294 
- https://nvd.nist.gov/vuln/detail/CVE-2021-38185
- Pipeline build id: 126790
=> fix cpio CVE-2021-38185

SPECS/git/git.spec
---
Adds subpackages to git [daemon, svn & subtree]
- Add subpackages
**NO**
- #xxxx
- localbuild
=> [dev] git: enable subpackages deamon, subtree & svn

SPECS/clang/clang.spec
---
Add a subpackage `git-clang-format`
- Add subpackage `git-clang-format`
**NO**
- NA
- NA
- localbuild
=> [dev] clang: add git-clang-format subpackage

README.md, toolkit/docs/quick_start/quickstart.md
=> Provide link for ISO Image

SPECS/rsyslog/rsyslog.spec, SPECS/syslog-ng/syslog-ng.conf, SPECS/syslog-ng/syslog-ng.signatures.json, SPECS/syslog-ng/syslog-ng.spec
Cherry-pick rsyslog addition to 1.0 branch
=> Enable omuxsock in rsyslog and add customized syslog-ng conf (#1367)

SPECS/cpio/CVE-2021-38185.patch, SPECS/cpio/cpio.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
=> cherrypick: fix cpio cve (#1365)

toolkit/imageconfigs/packagelists/azurevm-packages.json
Add rsyslog feature package by default to Mariner cloud images.
---
Most of customers leverages syslog in some form as OS logging standard. 
Adding rsyslog feature package by default to Mariner cloud images which is commonly used.
- Change
Add rsyslog by default to Mariner cloud images
**NO**
- #xxxx
- Local validation
=> Add rsyslog by default to Mariner cloud images

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Export `bpftool` subpackage.
- Export `bpftool` subpackage.
**YES**
- NA
- NA
- localbuild
=> [dev] kernel: export bpftool subpackage

SPECS/fluent-bit/fluent-bit.spec
Enable systemd plug-in in fluent-bit to support journal reader.
---
Enable systemd plug-in in fluent-bit to support journal reader.
- Change
Enable plug-in for systemd support
**NO**
- #xxxx
- Local build.
=> Enable systemd plug-in in fluent-bit to support journal reader

SPECS/cyrus-sasl/cyrus-sasl.spec, SPECS/librdkafka/librdkafka.spec, SPECS/openldap/openldap.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Extending the `cyrus-sasl` package by adding multiple commonly used plug-in libraries. I've also split the existing plug-ins into their separate subpackages to reduce the package sizes.
- Introduced following subpackages using Fedora 32 (license: MIT) specs as guidance:
- cyrus-sasl-gs2,
- cyrus-sasl-ldap,
- cyrus-sasl-lib,
- cyrus-sasl-md5,
- cyrus-sasl-ntlm,
- cyrus-sasl-plain,
- cyrus-sasl-scram,
- cyrus-sasl-sql.
- Moving common libs into the `*-devel` and `*-libs` subpackages.
- Moving MD5 plug-in libs into the `*-md5` subpackage.
- Removed SRP libs as they were unused.
Yes.
- Ran tests - all pass.
=> [dev] `cyrus-sasl`: adding and splitting subpackages

SPECS/cyrus-sasl/cyrus-sasl.spec, SPECS/librdkafka/librdkafka.spec, SPECS/openldap/openldap.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
This reverts commit a80f503b1f8e05e2753619652432549b54c0b4c1.
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Revert "[dev] `cyrus-sasl`: adding and splitting subpackages (#1394)"

.github/workflows/check-spec.yml
---
It runs the spec github check only for those spec files which were modified in the PR
- It gets the status of all spec files in the PR and runs the spec github check only for those spec files which were modified
NO
- None
- None
- Tested on local bash script
=> get file status, run check only for specs modified

SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec
---
Adding missing signatures for `httpd` sources. I missed including them in my recent changes to `httpd`.
- Add missing signatures.
- Whitespace fixes.
No.
=> [dev]: adding missing signatures for `httpd` sources.

SPECS/libdb/CVE-2019-2708.patch, SPECS/libdb/libdb.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Fix CVE-2019-2708 for libdb
- Patch CVE-2019-2708
YES
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2019-2708
- Local Build
=> Fix libdb CVE-2019-2708

SPECS/curl/CVE-2021-22945.patch, SPECS/curl/CVE-2021-22946.patch, SPECS/curl/CVE-2021-22947.patch, SPECS/curl/curl.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Fix curl CVE-2021-22945, CVE-2021-22946, CVE-2021-22947
- Fix CVE-2021-22945, CVE-2021-22946, CVE-2021-22947
YES
- #xxxx
- https://curl.se/docs/CVE-2021-22945.html
- https://curl.se/docs/CVE-2021-22946.html
- https://curl.se/docs/CVE-2021-22947.html
- Local Build
=> Fix curl CVE-2021-22945, CVE-2021-22946, CVE-2021-22947

SPECS/WALinuxAgent/WALinuxAgent.spec, SPECS/rsyslog/rsyslog.spec
---
Fixing permissions on /etc/rsyslog.d and /sys/devices/virtual/dmi/id/product_uuid to improve compat with AMA and ASA VM extensions.
- Create /etc/rsyslog.d explicitly with correct permissions in the rsyslog package
- Add product_uuid permission udev rule to WALinuxAgent package
**NO**
- Built and booted a new Marketplace image in Azure. Confirmed permissions and AMA/ASA functionality.
=> Fix rsyslog.d and product_uuid permissions

SPECS/helm/CVE-2021-21303.patch, SPECS/helm/helm.spec
---
Patch CVE-2021-21303 in helm
- Backport CVE-2021-21303 patch to helm 3.4.1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-21303
- Local Build
=> Patch helm CVE-2021-21303

SPECS/helm/CVE-2021-21303.patch, SPECS/helm/helm.spec
---
Patch CVE-2021-21303 in helm
- Backport CVE-2021-21303 patch to helm 3.4.1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-21303
- Local Build
=> [dev] Patch helm CVE-2021-21303

SPECS/helm/CVE-2021-32690.patch, SPECS/helm/helm.spec
---
Patch helm CVE-2021-32690
- Backport helm CVE-2021-32690 patch from 3.6.1 release.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-32690
- Local Build
=> Patch helm CVE-2021-32690

SPECS/helm/CVE-2021-32690.patch, SPECS/helm/helm.spec
---
Patch helm CVE-2021-32690
- Backport helm CVE-2021-32690 patch from 3.6.1 release.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-32690
- Local Build
=> [dev] Patch helm CVE-2021-32690

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Export bpftool subpackage. Cherry-pick of #1375 
- Export bpftool subpackage.
**YES**
- Pipeline build id (AMD): 134348
- Pipeline build id (ARM): 134247- RPMS
- local build
=> kernel: export bpftool subpackage

SPECS/graphviz/CVE-2020-18032.patch, SPECS/graphviz/graphviz.spec
---
Patch graphviz CVE-2020-18032
- Patch graphviz CVE-2020-18032
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2020-18032
- Local Build
=> Patch graphviz CVE-2020-18032

SPECS/bison/bison.spec, SPECS/dracut/dracut.spec, SPECS/nodejs/nodejs.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Adding a few `Provides` into our specs to make finding CBL-Mariner packages easier.
- Added `bison-runtime` to `bison`.
- Added `dracut-caps` to `dracut`.
- Added `npm` to `nodejs`.
Yes.
=> [dev] Adding `Provides` for common packages

toolkit/tools/roast/roast.go
---
When we ask for `diff` or `rdiff` artifacts for a partition, we would only ever get those diff artifacts, even if we also asked for an `.ext4` for example.
- Now respect all partition artifacts in the config file when selecting diff or rdiff artifacts.
**NO**
- Local builds
=> Don't override all artifact settings if using diff

SPECS/dpdk/dpdk.spec
---
Enable `tools` subpackage by default
- Enable `tools` subpackage by default
**NO**
- NA
- NA
- localbuild
=> [dev] dpdk: enable `tools` subpackage by default

SPECS/rpm-ostree/rpm-ostree.signatures.json, SPECS/rpm-ostree/rpm-ostree.spec, cgmanifest.json
---
`rpm-ostree` package broke on upgrade to new version of `libmodulemd`. Upgrade rpm-ostree to v2021.11 (latest release) to fix.
- Upgrade rpm-ostree to v2021.11, using new source with bundled dependencies included
**NO**
=> [dev] Upgrade rpm-ostree to 2021.11

SPECS/gettext/gettext.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- gettext: export 'common-devel' & 'libs' subpackage
- gettext: update manifests
---
Exports subpackages 'libs' & 'common-devel'
- export subpackage 'libs' & 'common-devel'
**YES**
- NA
- NA
- localbuild
=> [dev] gettext: enable subpackages 'libs' & 'common-devel'

SPECS/clang/clang.signatures.json, SPECS/clang/clang.spec
---
Splitting `clang` into smaller subpackages and adding the `clang-tools-extra` subpackage to extend the usefulness of the package.
- Split out the `clang-analyzer` and `clang-libs` subpackages.
- Added the `clang-tools-extra` subpackage.
No.
- Local package build of `clang` and packages depending on it.
=> [dev] `clang`: splitting into subpackages and adding extra tools subpackages

SPECS/qt5-qtsvg/qt5-qtsvg.spec
Mark nopatch for CVE-2021-38593 and CVE-2018-21035 for qt5-qtsvg.
---
Mark nopatch for CVE-2021-38593 and CVE-2018-21035 for qt5-qtsvg.
- Change
Add nopatches for CVE-2021-38593 and CVE-2018-21035
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-38593
- https://nvd.nist.gov/vuln/detail/CVE-2018-21035
- Local build.
=> Add no patches for qt5-qtsvg

SPECS/ipset/ipset.service, SPECS/ipset/ipset.signatures.json, SPECS/ipset/ipset.spec, SPECS/ipset/ipset.start-stop, SPECS/iptables/iptables.spec
---
Add ipset service files and subpackage from Fedora 35. Additionally, add services subpackage provides for the iptables package.
- ipset: Add service subpackage
- iptables: Add services subpackage provides from main package
**NO**
=> [dev] Add ipset service subpackage

toolkit/docs/building/prerequisites-mariner.md, toolkit/docs/building/prerequisites-ubuntu.md, toolkit/docs/building/prerequisites.md
- [x ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x ] Ready to merge
---
Make the documentation ready to build Mariner on top of Mariner, rather than on Ubuntu
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> update documentation to cover building on mariner

SPECS/moby-engine/CVE-2021-41089.patch, SPECS/moby-engine/CVE-2021-41091.patch, SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine CVE-2021-41091 and CVE-2021-41089
- Patch moby-engine CVE-2021-41091 
- Patch moby-engine CVE-2021-41089
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41091
- https://github.com/moby/moby/security/advisories/GHSA-3fwx-pjgw-3558
- https://nvd.nist.gov/vuln/detail/CVE-2021-41089
- https://github.com/moby/moby/security/advisories/GHSA-v994-f8vw-g7j4
- Local build
- Updated to new package and pulled some containers
=> Fix moby-engine CVE-2021-41091 CVE-2021-41089

SPECS/moby-engine/CVE-2021-41089.patch, SPECS/moby-engine/CVE-2021-41091.patch, SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine CVE-2021-41091 and CVE-2021-41089
Cherry-pick from 1.0-dev https://github.com/microsoft/CBL-Mariner/pull/1495
- Patch moby-engine CVE-2021-41091 
- Patch moby-engine CVE-2021-41089
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41091
- https://github.com/moby/moby/security/advisories/GHSA-3fwx-pjgw-3558
- https://nvd.nist.gov/vuln/detail/CVE-2021-41089
- https://github.com/moby/moby/security/advisories/GHSA-v994-f8vw-g7j4
- Local build
- Updated to new package and pulled some containers
=> Fix moby-engine CVE-2021-41091 CVE-2021-41089 (#1495)

.gitignore, toolkit/imageconfigs/full.json, toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller
---
Cherry picker packer related changes from 1.0-dev into dev
- full.json and runliveinstaller
**NO**
- #1426
=> [dev] Cherry pick packer related changes from 1.0-dev into dev

SPECS/moby-engine/CVE-2021-41089.patch, SPECS/moby-engine/CVE-2021-41091.patch, SPECS/moby-engine/moby-engine.spec
---
Patch moby-engine CVE-2021-41091 and CVE-2021-41089
Cherry-pick from 1.0-dev https://github.com/microsoft/CBL-Mariner/pull/1495
- Patch moby-engine CVE-2021-41091 
- Patch moby-engine CVE-2021-41089
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41091
- https://github.com/moby/moby/security/advisories/GHSA-3fwx-pjgw-3558
- https://nvd.nist.gov/vuln/detail/CVE-2021-41089
- https://github.com/moby/moby/security/advisories/GHSA-v994-f8vw-g7j4
- Local build
- Updated to new package and pulled some containers
=> [dev] Fix moby-engine CVE-2021-41091 CVE-2021-41089

SPECS/grpc/grpc.spec
---
Cherry-pick Fix grpc-devel file conflict (#1468) to dev
- Change
- Change
- Change
**NO**
=> Fix grpc-devel file conflict (dev branch)

toolkit/scripts/toolchain/check_manifests.sh, toolkit/tools/internal/rpm/rpm.go, toolkit/tools/internal/rpm/rpm_test.go, toolkit/tools/internal/rpm/testdata/no_exclusive_architecture.spec, toolkit/tools/internal/rpm/testdata/supported_unsupported_architectures.spec, toolkit/tools/internal/rpm/testdata/unsupported_architectures.spec
---
Porting changes from `1.0-dev` made in #1511. Mostly adding tests + a small fix to the `check_manifest.sh` script.
- Added test for `ExclusiveArch` parsing.
- Fixed `check_manifest.sh` to work with multiple entries in the `ExclusiveArch` tag.
- Refactoring.
No.
- #1511
- Local package build and test run.
=> [dev]: Adding tests for `ExclusiveArch` parsing from #1511

SPECS/rpm/rpm.spec
---
Re-adding two `install` lines we accidentally removed in #1510.
- Adding back `brp-*` scripts into `rpm-build`.
Yes
- None, reverting previous change.
=> [dev] Restoring `brp-*` scripts in `rpm-build`

SPECS/ansible/ansible.signatures.json, SPECS/ansible/ansible.spec, cgmanifest.json
- [-] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- check fails. But its not a regression.
---
- Fixing below CVEs
- https://nvd.nist.gov/vuln/detail/CVE-2021-3583, 
- https://nvd.nist.gov/vuln/detail/CVE-2020-14330, 
- https://nvd.nist.gov/vuln/detail/CVE-2021-20228
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3583, 
- https://nvd.nist.gov/vuln/detail/CVE-2020-14330, 
- https://nvd.nist.gov/vuln/detail/CVE-2021-20228
- Manual test
=> CVE fix for ansible

SPECS/powershell/powershell.spec
---
Needed to move the spec section, in which we're manually extracting the source tarball in `powershell.spec`. The tarball was extracted in the `%prep` section directly to the `%{buildroot}` but with the recent version updated for `rpm`, the `%{buildroot}` gets removed and created anew at the beginning of the `%{install}` section, so the extracted files ended up being deleted.
- Moved source extraction to the `%install` section.
No.
=> [dev] `powershell`: moving source extraction to the `%install` section

SPECS/openscap/openscap.signatures.json, SPECS/openscap/openscap.spec, cgmanifest.json
---
The current 1.3.1 version of openscap has a bug where --stig-viewer
output is malformed due to a change in official STIG URI. The fix for
this issue was upstreamed and released in 1.3.2. So update our openscap
pacakge to 1.3.2. to pick up this fix.
**NO**
Local build
=> openscap: Update to 1.3.2

SPECS/babel/CVE-2021-42771_3a700b.patch, SPECS/babel/CVE-2021-42771_5caf71.patch, SPECS/babel/babel.spec
---
This change updates the patches provided by our autopatcher so they apply cleanly to the babel base source. Also fixes some spec linting issues.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-42771
Local build
=> Fix babel autopatching

cgmanifest.json
---
Update cgmanifest's mysql version to 8.0.27 and align with this recent commit: d088d94e83e54e7690978d7ef6de4ca375fcf3da
This is to add in changes from https://github.com/microsoft/CBL-Mariner/pull/1600
**NO**
=> cgmanifest: Update mysql version to 8.0.27

SPECS/strongswan/CVE-2021-41990.patch, SPECS/strongswan/CVE-2021-41991.patch, SPECS/strongswan/strongswan.spec
---
Take `strongswan` upstream's backport patches for CVE-2021-41990 and CVE-2021-41991.
- Patch CVE-2021-41990, CVE-2021-41991 in `strongswan`
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41990
- https://nvd.nist.gov/vuln/detail/CVE-2021-41991
=> Add patch for strongswan CVE-2021-41990, CVE-2021-41991

SPECS/curl/curl.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Add nopatch file for `curl` CVE-2021-22926. This CVE only applies to builds on macOS.
- Add nopatch file for CVE-2021-22926
- Lint spec
- Update curl-associated URLs to reflect new domain
- Fix licensing packaging (should go in `libs` subpackage instead of main package)
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-22926
=> Add nopatch file for curl CVE-2021-22926

SPECS/mc/mc.signatures.json, SPECS/mc/mc.spec, cgmanifest.json
---
Upgrade `mc` to version 4.8.27 to fix CVE-2021-36370
- Upgrade `mc` to 4.8.27, lint spec, verify license
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-36370
=> Upgrade mc to 4.8.27 to fix CVE-2021-36370

SPECS/libsolv/libsolv.signatures.json, SPECS/libsolv/libsolv.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade libsolv to version 0.7.19 to fix several CVEs.
- Upgrade libsolv to 0.7.19 to fix several CVEs- see below for a full list.
- Move libraries from `%{_lib64dir}` to `%{_libdir}`
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-33928
- https://nvd.nist.gov/vuln/detail/CVE-2021-33929
- https://nvd.nist.gov/vuln/detail/CVE-2021-33930
- https://nvd.nist.gov/vuln/detail/CVE-2021-33938
- https://nvd.nist.gov/vuln/detail/CVE-2021-3200
- Local toolchain build, package build of downstream components
=> Update libsolv to 0.7.19 to solve several CVEs

SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.7.0.spec, SPECS/coredns/coredns-1.8.0.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/flannel/flannel.spec, SPECS/glide/glide.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/golang-1.16.signatures.json, SPECS/golang/golang-1.16.spec, SPECS/helm/helm.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/node-problem-detector/node-problem-detector.spec, SPECS/nvidia-container-runtime/nvidia-container-runtime.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, SPECS/telegraf/telegraf.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade `golang` to 1.16.9 from 1.16.7. The 1.16.8 upgrade fixes CVE-2021-39293, while the 1.16.9 upgrade fixes CVE-2021-38297.
- Upgrade `golang` to 1.16.9 from 1.16.7
- Bump release version of packages which require `golang` at build-time to force republishing
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-38297
- https://nvd.nist.gov/vuln/detail/CVE-2021-39293
- Local build
=> Upgrade golang to 1.16.9 to fix CVE-2021-38297, CVE-2021-39293

SPECS/mariner-rpm-macros/gen-ld-script.sh, SPECS/mariner-rpm-macros/mariner-rpm-macros.signatures.json, SPECS/mariner-rpm-macros/mariner-rpm-macros.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix error seen from gen-ld-script.sh:
grep: support for the -P option is not compiled into this --disable-perl-regexp binary
Also fix error when building rpm packages with CBL-Mariner outside typical package build environment;
/usr/src/mariner/BUILD/module_info.ld: No such file or directory
- Change script to use sed instead of grep -p
- Change script to create directory for module_info.ld when needed
- Update manifests
**YES**
- Local build
=> Fix gen-ld-script.sh issues with grep and missing directory

SPECS/grpc/grpc.spec
---
Re-adding the `libaddress_sorting` library we've removed in #1468. We just carved out a bit too much.
- Brought back the `libaddress_sorting` library.
No.
- #1468
=> `grpc`: bringing back the `libaddress_sorting` library

SPECS/vim/vim.spec
---
Recent update of vim included a change to where colors are defined. This new color definition file is not in the base vim package by default, which causes a failure when loading vim without vim-extra installed. So, we move the necessary file to the base package.
- Move vim default color list to base package from extra package
**NO**
- Local image test
=> Move default color list to vim base package

SPECS/bind/bind.signatures.json, SPECS/bind/bind.spec, cgmanifest.json
---
Updated bind to 9.16.22 to address CVE-2021-25219
Updated bind to 9.16.22 to address CVE-2021-25219. Removed older, now unnecessary patch files.
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-25219
- local build
=> Updated bind to 9.16.22 to address CVE-2021-25219

SPECS/bash-completion/bash-completion.spec, SPECS/colm/colm.spec, SPECS/crash/crash.spec, SPECS/dpdk/dpdk.spec, SPECS/fmt/fmt.spec, SPECS/kyua/kyua.spec, SPECS/libglvnd/libglvnd.spec, SPECS/mesa/mesa.spec, SPECS/ragel/ragel.spec, SPECS/systemtap/systemtap.spec, SPECS/xorg-x11-font-utils/xorg-x11-font-utils.spec, SPECS/xorg-x11-server/xorg-x11-server.spec, SPECS/xorg-x11-xauth/xorg-x11-xauth.spec
---
Removes the `Epoch` tag from the specs as we do not support it.
- bash-completion: remove epoch
- colm: remove epoch
- crash: remove epoch
- dpdk: remove epoch
- fmt: remove epoch
- kyua: remove epoch
- libglvnd: remove epoch
- mesa: remove epoch
- ragel: remove epoch
- systemtap: remove epoch
- xorg-x11-font-utils: remove epoch
- xorg-x11-xauth: remove epoch
**NO**
- NA
- NA
- local build
=> [dev] SPECS: drop epoch tag from specs

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Updates vim to 8.2.3582
- Updates vim to 8.2.3582
- Fixes CVE-2021-3927, CVE-2021-3928
**NO**
- Local build
=> Updated vim to 8.2.3582 to address CVEs

SPECS/libacvp/libacvp.signatures.json, SPECS/libacvp/libacvp.spec, SPECS/libacvp/openssl.patch, cgmanifest.json
---
Update libacvp to version 1.3.0 and add support for additional OpenSSL tests.
Cherry-pick of 6b35da67f7e9336345270d5cadffa6727fe917f3
**NO**
local build
=> [dev] Patch Libacvp to Support Additional OpenSSL Tests

SPECS/golang/golang-1.16.signatures.json, SPECS/golang/golang-1.16.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updated golang to version 1.16.10 to address multiple CVEs
- Updated golang to version 1.16.10 to address multiple CVEs
- Fixes CVE-2021-41771 and CVE-2021-41772; the latter fixes a vulnerability where an attacker can cause unexpected panics with a malformed ZIP file.
**YES**
- Local build, local toolchain build
=> Updated golang to version 1.16.10 to address multiple CVEs

SPECS/uclibc-ng/CVE-2021-43523.patch, SPECS/uclibc-ng/uclibc-ng.spec
---
Adding a patch for CVE-2021-43523.
- Added a patch for CVE-2021-43523.
No.
- https://nvd.nist.gov/vuln/detail/CVE-2021-43523
=> `uclibc-ng`: fixing CVE-2021-43523.

SPECS/uclibc-ng/CVE-2021-43523.patch, SPECS/uclibc-ng/uclibc-ng.spec
---
Cherry-pick from `1.0-dev`, PR #1654.
- Cherry-pick from `1.0-dev`, PR #1654.
No.
- #1654
- https://nvd.nist.gov/vuln/detail/CVE-2021-43523
=> `uclibc-ng`: fixing CVE-2021-43523. (#1654)

SPECS/gmp/CVE-2021-43618.patch, SPECS/gmp/gmp.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fixing CVE-2021-43618 in `gmp`.
- Applied a patch to fix CVE-2021-43618 in `gmp`.
Yes.
- https://nvd.nist.gov/vuln/detail/CVE-2021-43618
=> `gmp`: fixing CVE-2021-43618.

SPECS/uclibc-ng/CVE-2021-43523.patch, SPECS/uclibc-ng/uclibc-ng.spec
---
Port of a CVE fix from #1654.
- Fixed CVE-2021-43523.
No.
- #1654
- https://nvd.nist.gov/vuln/detail/CVE-2021-43523
=> [dev] `uclibc-ng`: fixing CVE-2021-43523. Port of #1654.

SPECS/ant/ant.spec
---
Disable ant debuginfo to allow the package to successfully build exclusively for arm64
- Change ant.spec to disable debuginfo
**NO**
- Pipeline build id: 148104
=> Disable ant debuginfo

SPECS/iana-etc/iana-etc-LICENSE, SPECS/iana-etc/iana-etc.signatures.json, SPECS/iana-etc/iana-etc.spec, cgmanifest.json
---
Switched to a new upstream source for the `iana-etc` package and upgraded to the latest version. 
- Switch to new upstream source used by LFS and upgrade to latest
- Use new release version corresponding to IANA source update dates
- Include original IANA XML sources in packaging
- License verified (now MIT, old upstream was OSL 3.0)
**NO**
- Local build
=> [dev] Upgrade iana-etc to version 20211115

SPECS/librelp/librelp.signatures.json, SPECS/librelp/librelp.spec, cgmanifest.json
---
Upgrade `librelp` to latest upstream version 1.10.0. Previously packaged version is incompatible with the new version of `automake` introduced in #1670.
- Upgrade `librelp` to 1.10.0
- Remove static libraries from packaging
- Lint spec, verify license
**NO**
=> [dev] Upgrade librelp to 1.10.0 to fix build failure

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
- vim: bump version to fix CVE-2021-{3968, 3973, 3974}
- cgmanifest: vim: bump version 8.2.3582 -> 8.2.3668
---
Bumps the version of vim:  8.2.3582 -> 8.2.3668 to fix CVEs
- Bump version of vim: 8.2.3582 -> 8.2.3668
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3968
- https://nvd.nist.gov/vuln/detail/CVE-2021-3973
- https://nvd.nist.gov/vuln/detail/CVE-2021-3974
- Local Build with `RUN_CHECK=y`
=> vim: bump version to fix CVE-2021-{3968, 3973, 3974}

CONTRIBUTING.md
---
Adds a guideline for any new contributors to raise a PR against `1.0-dev` instead of `1.0`
Related PR: #1133
NA
NA
NA
NA
NA
=> CONTRIBUTING: add guidelines for raising a PR

SPECS/grpc/grpc.spec
---
This is porting changes from #1665. By default `grcp` always builds with C++11, but since it depends on external packages like `abseil-cpp` build with the default C++ version used by GCC 9 (C++14), we may run into build-/run-time issues. This change makes sure `grpc` uses the defaults for whatever version of GCC we're going to build other packages with.
- Made `grpc` build with C++14.
- Removed outdated comment about sources.
No.
- #1665
=> `grcp`: forcing a build with our default C++ standard version.

SPECS/iproute/iproute.signatures.json, SPECS/iproute/iproute.spec, cgmanifest.json
---
Upgrades `iproute` package to latest upstream version 5.15.0
- Add relevant build/runtime requirements
**NO**
=> [dev] Upgrade iproute to 5.15.0

SPECS/blobfuse/blobfuse.signatures.json, SPECS/blobfuse/blobfuse.spec, cgmanifest.json
---
Upgrades the blobfuse package to the latest upstream version 1.4.2 from 1.3.6
- Upgrade blobfuse to 1.4.2 and lint spec
**NO**
=> [dev] Upgrade blobfuse to 1.4.2

toolkit/.gitignore
---
Our toolkit `.gitignore` file was missing various patch files that are copied into the container folder during raw toolchain builds. This PR adds them to the list.
- Update toolkit `.gitignore` to reflect all copied-in patch files for raw toolchain builds
**NO**
- N/A, low risk change
=> [dev] Add new patch files to toolkit gitignore

SPECS/c-ares/c-ares.signatures.json, SPECS/c-ares/c-ares.spec, cgmanifest.json
- c-ares: bump version to fix CVE-2021-3672
- cgmanifest: c-ares: bump version 1.17.1 -> 1.18.1
---
Bump version to fix CVE-2021-3672
It's a `cherry-pick` of -> #1684
- Bump version 1.17.1 -> 1.18.1
**NO**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-3672
- Local Build with `RUN_CHECK=y`
=> [dev] c-ares: bump version to fix CVE-2021-3672

SPECS/azure-iotedge/azure-iotedge.spec, SPECS/azure-iotedge/fix-missing-dyn-attribute.patch, SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json, SPECS/cloud-hypervisor/cloud-hypervisor.spec, cgmanifest.json, toolkit/scripts/build_cargo_cache.sh
---
Fixing build of `azure-iotedge` and `cloud-hypervisor`, since they started failing after a recent update of `rust` to version 1.56.1.
- Added a patch to `azure-iotedge`.
- Updated `cloud-hypervisor` to version 19.0.
No.
=> [dev] Fixing 'azure-iotedge' and 'cloud-hypervisor' builds.

SPECS/bond/bond.spec
---
I found two binary files with a total size of ~80 MB inside the `SPECS/bond` directory. Moving them to our sources server.
- Removed binary files from `SPECS/bond`.
No.
- None, simple file removal.
=> Removing binaries from `SPECS/bond`.

SPECS/python-certifi/python-certifi.spec
---
python-certifi: fix typo s/BuildRequiers/BuildRequires
- Fix typo in spec
**NO**
- NA
- NA
- Local Build
=> python-certifi: fix typo s/BuildRequiers/BuildRequires

SPECS/bond/bond.spec
---
Cherry-pick of #1695. Removing binary files accidentally checked-in into the repo.
- Removed `bond` binaries from the repo.
No.
- #1695
=> Removing binaries from `SPECS/bond`. (#1695)

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2021-43057.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Make a nopatch to address CVE-2021-43057
- Address CVE-2021-43057
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-43057
- local build
=> kernel: Address CVE-2021-43057

SPECS/openscap/openscap.spec
---
Small fix where we accidentally added a dependency on `libxmlsec1` instead of `xmlsec1`.
- Fixed `openscap` dependencies.
No.
=> [dev] Fixing `openscap` build.

SPECS/openscap/openscap.spec, SPECS/psmisc/psmisc.signatures.json, SPECS/psmisc/psmisc.spec, SPECS/tcl/tcl.signatures.json, SPECS/tcl/tcl.spec, cgmanifest.json
---
Update tcl and psmisc packages to their latest released versions. Also verified license for openscap.
- Update tcl and psmisc SPECS to latest versions
- Update cgmanifest to reflect the new versions
- Verify license for openscap
**YES**
local build
=> [main] Update tcl and psmisc

SPECS/atftp/atftp.signatures.json, SPECS/atftp/atftp.spec, SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Add vim updates up through 8.2.3582 and atftp to 0.7.5
Cherry-pick of 30e720dc353cc47da30ee7fe508e5402f14b10c9 8931d0b9b79fe92dc28c22494e7b21c9f3dea945 8abde10b54e527b1cbb1ab8157f54a6e79a5763d 8a11f88edb7720c794322f02f3f6191d5eef142c 0ba671d72dbc533a760b9bc9a9f900af45cbb37c d7a066de8cb5aab97296423175e69398a5ac421d
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-3778
- https://nvd.nist.gov/vuln/detail/CVE-2021-3796
- https://nvd.nist.gov/vuln/detail/CVE-2021-41054
- https://nvd.nist.gov/vuln/detail/CVE-2021-3875
- https://nvd.nist.gov/vuln/detail/CVE-2021-3872
- https://nvd.nist.gov/vuln/detail/CVE-2021-3903
- …
=> [main] Update vim to 8.2.3582 and atftp to 0.7.5

SPECS/groff/groff.signatures.json, SPECS/groff/groff.spec, cgmanifest.json
---
Update groff to its latest version v1.22.4
- Update groff spec to latest version
- Update cgmanifest to reflect new version
**NO**
local build
=> [main] Update groff to 1.22.4

SPECS/ostree/0001-ostree-Copying-photon-config-to-boot-directory.patch, SPECS/ostree/0002-ostree-Adding-load-env-to-menuentry.patch, SPECS/ostree/0003-ostree-converting-osname-to-mariner.patch, SPECS/ostree/dualboot-support.patch, SPECS/ostree/ostree.signatures.json, SPECS/ostree/ostree.spec, SPECS/rpm-ostree/rpm-ostree-disable-selinux.patch, SPECS/rpm-ostree/rpm-ostree-gcc-11-2.patch, SPECS/rpm-ostree/rpm-ostree-libdnf-build.patch, SPECS/rpm-ostree/rpm-ostree.signatures.json, SPECS/rpm-ostree/rpm-ostree.spec, cgmanifest.json
---
Update ostree and rpm-ostree to latest versions.
In ostree spec ostree-system-generator file is now placed under /lib/systemd/system-generators.
- Change
Update ostree and rpm-ostree versions
**NO**
- #xxxx
- Local build.
=> Update ostree and rpm-ostree versions

SPECS/less/less.signatures.json, SPECS/less/less.spec, cgmanifest.json
---
Update less to version 590
- Update less to version 590
**NO**
- Pipeline build
=> Update less to version 590

toolkit/scripts/pkggen.mk, toolkit/tools/depsearch/depsearch.go, toolkit/tools/go.mod, toolkit/tools/go.sum, toolkit/tools/graphanalytics/graphanalytics.go, toolkit/tools/internal/pkggraph/pkggraph.go, toolkit/tools/internal/pkggraph/pkggraph_test.go, toolkit/tools/internal/sliceutils/sliceutils.go, toolkit/tools/pkgworker/pkgworker.go, toolkit/tools/scheduler/scheduler.go, toolkit/tools/scheduler/schedulerutils/buildworker.go, toolkit/tools/scheduler/schedulerutils/graphbuildstate.go, toolkit/tools/scheduler/schedulerutils/implicitprovides.go, toolkit/tools/scheduler/schedulerutils/preparerequest.go, toolkit/tools/scheduler/schedulerutils/printresults.go
---
While switching from using `make` targets in favour of the scheduler we've removed the functionality to skip building packages on request. This PR restores that functionality.
- Updated the scheduler and build workers to allow for skipping package builds.
No.
- Local package build tests.
- Pipeline toolchain and package builds.
=> [main] Restoring `PACKAGE_IGNORE_LIST` functionality

SPECS/perl-XML-Parser/perl-XML-Parser.signatures.json, SPECS/perl-XML-Parser/perl-XML-Parser.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update perl-xml-parser to current release 2.46
- Update perl-xml-parser to build latest version 2.46
- Update cgmanifest to reflect new perl-xml-parser version
- Update toolchain to build/use new perl-xml-parser
**YES**
local build
=> [main] Update perl-xml-parser to 2.46

SPECS/pkgconf/pkgconf.signatures.json, SPECS/pkgconf/pkgconf.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update pkgconf to current release 1.8.0
- Update pkgconf to build latest version 1.8.0
- Update cgmanifest to reflect new pkgconf version
- Update toolchain to build/use new pkgconf
**YES**
local build
=> [main] Update pkgconf to 1.8.0

SPECS/autoconf213/autoconf213.spec, cgmanifest.json
---
Switched `autoconf213`'s source URL to use GNU's HTTPS URL, instead of MIT's FTP mirror
- Switched `autoconf213`'s source URL to use GNU's HTTPS URL, instead of MIT's FTP mirror
**YES/NO**
=> Use HTTPS URL for autoconf213

SPECS/mariner-repos/mariner-repos.signatures.json
---
Fix input-srpms creation by modifying mariner-official-base.repo sha256 signature
- Change mariner-repos.signatures.json
**NO**
- Local build.
=> Fix mariner-official-base.repo signature

SPECS/numpy/fix-setup-py-install.patch, SPECS/numpy/numpy.spec
---
There is a known install stage build break on install_clib
when building numpy 1.16 with python3.
See github issue: https://github.com/numpy/numpy/issues/13265
The fix for this issue is present in 1.17+, so this commit backports
the patch to 1.16.
**NO**
Local build
=> [main] numpy: fix build break in install_clib

SPECS/core-packages/core-packages.spec
---
For the minimal required packages, remove the dnf-automatic and
check-restart packages. Users who need these automatic update features
are expected to incorporate them as an add-on package in their image
configuration.
**NO**
=> core-packages: remove check-restart/dnf-automatic

SPECS/WALinuxAgent/WALinuxAgent.spec, toolkit/imageconfigs/marketplace-gen1.json, toolkit/imageconfigs/marketplace-gen2.json
---
This creates a 500 M partition at /boot and symlinks at /dev/disk/azure location in marketplace images, as required for adding ADE support to Mariner
This creates a 500 M partition at /boot and symlinks at /dev/disk/azure location in marketplace images, as required for adding ADE support to Mariner. 
NO
- N/A
- N/A
- Local build. Tested the image with a VM on Azure, and the requirements were satisfied.
=> Add partition and storage-rule for Azure VM extensions

SPECS/lapack/CVE-2021-4048.patch, SPECS/lapack/lapack.spec
---
Fix CVE-2021-4048 for package lapack
- (CVE-2021-4048)[https://nvd.nist.gov/vuln/detail/CVE-2021-4048]
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4048
- Local build
=> Fix CVE-2021-4048 for package lapack

.github/workflows/validate-cg-manifest.sh, SPECS-EXTENDED/log4j/log4j.spec, SPECS-EXTENDED/python-cliff/python-cliff.spec, SPECS-EXTENDED/python-keystoneauth1/python-keystoneauth1.spec, SPECS-EXTENDED/python-keystoneclient/python-keystoneclient.spec, SPECS-EXTENDED/python-novaclient/python-novaclient.spec, SPECS-EXTENDED/python-oslo-config/python-oslo-config.spec, SPECS-EXTENDED/python-oslo-serialization/python-oslo-serialization.spec, SPECS-EXTENDED/python-oslo-utils/python-oslo-utils.spec, cgmanifest.json
---
Our `.github/workflows/validate-cg-manifest.sh` check script was skipping all specs it was unable to parse, which could cause us to miss updates to `cgmanifest.json`. This PR updates the script and cleans-up 9 spec files to make sure all of our specs can be now parsed. Any future failures to parse the spec will be considered a failure of the GitHub check and will required the user to either clean up the spec file or update the script itself.
**NOTE**: I didn't increment the release number for the modified specs, as none of the packages built by them have been published, yet.
- Updated the  `.github/workflows/validate-cg-manifest.sh` script to make it successfully parse all spec …
=> Making sure all specs can be parsed by the check script.

toolkit/Makefile
---
With the recent splitting out of our debuginfo repos, toolchain population using direct file download fails. This is because the debuginfo repos are not present in the `PACKAGE_URL_LIST` make variable. This adds the prod/preview debuginfo repo URLs to that variable when the corresponding base repos are used.
- Add debuginfo repos to `PACKAGE_URL_LIST` make variable
**NO**
- Populated toolchain locally using this patch
=> [main] Add debuginfo repos to PACKAGE_URL_LIST

SPECS/bond/bond.spec
* fix bond build break for ARM64 on main branch
* fix bond build break for ARM64 on main branch
* fix bond build break for ARM64 on main branch
Co-authored-by: nicolas guibourge <nicolasg@microsoft.com>
---
cherry pick bond changes (commit ID 0fe2f6f30d3fa70a6d628cc3bb8263c9ae94953a)
- Change
- Change
- Change
**NO**
- #xxxx
=> Only build bond against x86_64 architecture (#1800)

SPECS/binutils/CVE-2021-45078.patch, SPECS/binutils/binutils.spec, toolkit/.gitignore, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/scripts/toolchain.mk, toolkit/scripts/toolchain/container/Dockerfile, toolkit/scripts/toolchain/container/toolchain_build_in_chroot.sh, toolkit/scripts/toolchain/container/toolchain_build_temp_tools.sh, toolkit/scripts/toolchain/create_toolchain_in_container.sh
---
Patches binutils to fix CVE-2021-45078
- binutils: patch CVE-2021-45078
**YES**
- NA
- https://nvd.nist.gov/vuln/detail/CVE-2021-45078
- Build in progress
=> binutils: fix CVE-2021-45078

SPECS/httpd/httpd-2.4.52-blfs_layout-1.patch, SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec, cgmanifest.json
---
httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790
- relevant spec and files
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-44224
- https://nvd.nist.gov/vuln/detail/CVE-2021-44790
=> httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790

SPECS/httpd/httpd-2.4.52-blfs_layout-1.patch, SPECS/httpd/httpd.signatures.json, SPECS/httpd/httpd.spec, cgmanifest.json
* httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790
* httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790
Co-authored-by: nicolas guibourge <nicolasg@microsoft.com>
---
cherry-pick httpd CVE fix from 1.0-dev into 1.0
(original PR -> "httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790 (#1806)")
- Change
- Change
- Change
**NO**
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-44224
- https://nvd.nist.gov/vuln/detail/CVE-2021-44790
=> httpd: upgrade to 2.4.52 to fix CVE-2021-44224, CVE-2021-44790 (#1806)

SPECS/kmod/kmod.signatures.json, SPECS/kmod/kmod.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update kmod version to 29.
- Change
Update kmod version to 29
**YES**
- #xxxx
=> Update kmod version to 29

SPECS/powershell/powershell.signatures.json, SPECS/powershell/powershell.spec, cgmanifest.json
---
Update Powershell to 7.2.1 to resolve CVE-2021-43896
- Update Powershell to 7.2.1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-43896
- Local build
- Installed package in latest container and ran pwsh.
=> Update powershell to 7.2.1 to resolve CVE-2021-43896

SPECS/sanlock/sanlock.signatures.json, SPECS/sanlock/sanlock.spec, cgmanifest.json
---
Update sanlock to v3.8.4
- Update sanlock to v3.8.4
NO
- None
- None
- Local build
=> Update sanlock to v3.8.4

SPECS/vim/CVE-2021-4136.patch, SPECS/vim/vim.spec
---
Backport vim CVE-2021-4136 patch from upstream.
- Patch vim CVE-2021-4136
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4136
- Local build
- Installed the resulting vim package in a container
=> Patch vim CVE-2021-4136

SPECS-EXTENDED/ripgrep/cargo_config, SPECS-EXTENDED/ripgrep/ripgrep.signatures.json, SPECS-EXTENDED/ripgrep/ripgrep.spec, SPECS-EXTENDED/rubygem-asciidoctor/rubygem-asciidoctor.signatures.json, SPECS-EXTENDED/rubygem-asciidoctor/rubygem-asciidoctor.spec, cgmanifest.json
---
Add ripgrep and its dependency rubygem-asciidoctor SPECS to Mariner
- Change
Add ripgrep to Mariner
**YES/NO**
- #xxxx
- Pipeline build id: Local Build.
=> Add ripgrep to Mariner

SPECS/powershell/powershell.signatures.json, SPECS/powershell/powershell.spec, cgmanifest.json
---
Update Powershell to 7.2.1 to resolve CVE-2021-43896
- Update Powershell to 7.2.1
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-43896
- Local build
=> [main] Update powershell to 7.2.1 to resolve CVE-2021-43896

SPECS/numpy/CVE-2021-41496.patch, SPECS/numpy/numpy.spec
---
Backport numpy upstream patch for CVE-2021-41496
- Patch numpy CVE-2021-41496
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41496
- Local build
=> Patch numpy CVE-2021-41496

SPECS/numpy/CVE-2021-41496.patch, SPECS/numpy/numpy.spec
---
Backport numpy upstream patch for CVE-2021-41496
- Patch numpy CVE-2021-41496
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-41496
- Local build
=> [main] Patch numpy CVE-2021-41496

SPECS/cmake/cmake.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
A port of #1750 fixing ptests in the latest `cmake`.
- Ported #1750.
Yes.
- #1750
=> `cmake`: porting test fixes from 2.0.

SPECS/sos/sos.signatures.json, SPECS/sos/sos.spec, cgmanifest.json
---
Update sos to v4.2
- Update sos to v4.2
NO
- None
- None
- Local build
=> Update sos to v4.2

toolkit/tools/roast/formats/qcow.go, toolkit/tools/roast/roast.go
---
Add config to create qcow image
- Add config to create qcow image
NO
- None
- None
- Built qcow image and created a VM using qemu.
=> Add config to create qcow image

SPECS/ceph/ceph.signatures.json, SPECS/ceph/ceph.spec, cgmanifest.json
---
Update ceph to v16.2.5
- Update ceph to v16.2.5
NO
- None
- None
=> Update ceph to v16.2.5

SPECS/sysstat/sysstat.signatures.json, SPECS/sysstat/sysstat.spec, cgmanifest.json
---
Update sysstat to v12.5.4
- Update sysstat to v12.5.4
NO
- None
- None
- Local build
=> Update sysstat to v12.5.4

SPECS/strongswan/strongswan.signatures.json, SPECS/strongswan/strongswan.spec, cgmanifest.json
---
Update strongswan to v5.9.3
- Update strongswan to v5.9.3
NO
- None
- None
=> Update strongswan to v5.9.3

SPECS/sshpass/sshpass.signatures.json, SPECS/sshpass/sshpass.spec, cgmanifest.json
---
Update sshpass to 1.09
- Update sshpass to 1.09
NO
- None
- None
- Local build
=> Update sshpass to 1.09

SPECS/qemu/disable_qos_test.patch, SPECS/qemu/qemu.spec
---
qos test of qemu hungs indefinitely sometimes. So I skipped it from running.
qos test of qemu hungs indefinitely sometimes. So I skipped it from running.
**NO**
- Local build
=> Skip qos test for qemu

SPECS/vnstat/vnstat.signatures.json, SPECS/vnstat/vnstat.spec, cgmanifest.json
---
Update vnstat to v2.7
- Update vnstat to v2.7
NO
- None
- None
- Local build
=> Update vnstat to v2.7

.github/workflows/check-clean-stage.yml, .github/workflows/check-entangled-specs.yml, .github/workflows/check-license-map.yml, .github/workflows/check-manifests.yml, .github/workflows/check-package-cgmanifest.yml, .github/workflows/validate-cg-manifest.sh, SPECS-EXTENDED/opencl-filesystem/opencl-filesystem.spec
---
Some of the GitHub checks weren't set to fire for changes to the `2.0*` branches. This PR addresses these issues.
- Updated GitHub check to fire for `2.0*` branches.
- Included specs with no source URLs in the ignore list for the `cgmanifest.json` check.
- Linted `opencl-filesystem.spec` because why not?
No.
- Check run for this PR.
=> [main] Updating GitHub checks to include 2.0 changes.

SPECS/dstat/dstat.spec, SPECS/dstat/fix-py3-deprecation-warning.patch
---
`dstat` was missing a requirement on `python-six`. I decided to go ahead and switch `dstat` to use Python 3 while fixing that issue.
- Use python3 in place of ambiguous "/usr/bin/env python" in installed scripts
- Add explicit dependency on python3-six
- Lint spec
**NO**
- Mock build, installed and tested functionality in container environment
=> [1.0-dev] Make dstat use Python 3 and fix implicit dependencies

SPECS/openldap/openldap.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The current openldap package contains binaries that use a poorly defined RPATH, meaning they'll prefer .so files from a path that's not already in use and secured on Mariner, opening them up to .so injections. Explicitly setting enable-dynamic in the configure flags disables this behavior.
- Add enable-dynamic to openldap configure flags to disable RPATH use.
**YES**
- Verified removal of RPATHs in binaries with "readelf -d"
=> Update openldap configure flags to disable rpath

SPECS/openldap/openldap.spec
---
The current openldap package contains binaries that use a poorly defined RPATH, meaning they'll prefer .so files from a path that's not already in use and secured on Mariner, opening them up to .so injections. Explicitly setting enable-dynamic in the configure flags disables this behavior.
- Add enable-dynamic to openldap configure flags to disable RPATH use.
**NO**
- Local SRPM build
- Verified removal of RPATHs in binaries with "readelf -d"
=> [main] Update openldap configure flags to disable rpath

toolkit/docs/how_it_works/0_intro.md
---
Fixes a broken link in the documentation
NO
=> Fix broken link in docs/how_it_works/0_intro.md

SPECS/tree/tree.signatures.json, SPECS/tree/tree.spec, cgmanifest.json
---
Update tree to v1.8.0
- Update tree to v1.8.0
NO
- None
- None
- Local build
=> Update tree to v1.8.0

SPECS/sg3_utils/sg3_utils.signatures.json, SPECS/sg3_utils/sg3_utils.spec, cgmanifest.json
---
Update sg3_utils to v1.46
- Update sg3_utils to v1.46
NO
- None
- None
- Local build
=> Update sg3_utils to v1.46

SPECS/libmbim/libmbim.signatures.json, SPECS/libmbim/libmbim.spec, cgmanifest.json
---
- Update libmbim to latest version 1.26.2
- Change
- Change
- Change
NO
- #xxxx
- Local Build
=> [main] Update libmbim to v1.26.2

SPECS/libkcapi/libkcapi.signatures.json, SPECS/libkcapi/libkcapi.spec, SPECS/liblognorm/liblognorm.signatures.json, SPECS/liblognorm/liblognorm.spec, SPECS/libmaxminddb/libmaxminddb.signatures.json, SPECS/libmaxminddb/libmaxminddb.spec, cgmanifest.json
---
- Upgrade libkcapi to version 1.3.1, liblognorm to version 2.0.6, libmaxminddb to version 1.6.0 
- Change
- Change
- Change
NO
- #xxxx
- Local build
=> [main] Upgrade libkcapi to v1.3.1, liblognorm to v2.0.6, libmaxminddb to v1.6.0

SPECS/tmux/tmux.signatures.json, SPECS/tmux/tmux.spec, cgmanifest.json
---
Update tmux to v3.2a
- Update tmux to v3.2a
NO
- Local build
=> Update tmux to v3.2a

SPECS/tinyxml2/tinyxml2.signatures.json, SPECS/tinyxml2/tinyxml2.spec, cgmanifest.json
---
Update tinyxml2 to v9.0.0
- Update tinyxml2 to v9.0.0
NO
- None
- None
- Local build
=> Update tinyxml2 to v9.0.0

SPECS/rsync/rsync.signatures.json, SPECS/rsync/rsync.spec, cgmanifest.json
---
Update rsync to v3.2.3
- Update rsync to v3.2.3
- Remove CVE-2017-16548.nopatch (doesn't affect this version as per the CVE description page)
NO
=> Update rsync to v3.2.3

SPECS/libndp/libndp.signatures.json, SPECS/libndp/libndp.spec, SPECS/libnetfilter_conntrack/libnetfilter_conntrack.signatures.json, SPECS/libnetfilter_conntrack/libnetfilter_conntrack.spec, SPECS/libnetfilter_queue/libnetfilter_queue.signatures.json, SPECS/libnetfilter_queue/libnetfilter_queue.spec, SPECS/libnftnl/libnftnl.signatures.json, SPECS/libnftnl/libnftnl.spec, cgmanifest.json
---
- Update libndp to v1.8, libnetfilter_conntrack to v1.0.8, libnetfilter_queue to v1.0.5, libnftnl to v1.2.1
- Change
- Change
- Change
NO
- #xxxx
- Local Build
=> [main] Update libndp to v1.8, libnetfilter_conntrack to v1.0.8, libnetfilter_queue to v1.0.5, libnftnl to v1.2.1

SPECS/gd/gd.spec
---
Fixes libgd test suite due to failure introduced in upgrade #1714 .
Error was caused by [bug](https://github.com/libgd/libgd/issues/763) in libgd test suite.
- Added TMPDIR definition to libgd's check section.
**NO**
- Local test
=> Fixed libgd test failures in 2.3.3

SPECS/mc/mc.signatures.json, SPECS/mc/mc.spec, cgmanifest.json
---
Upgrading mc package to v4.8.27. Cherry picking upgrade from 1.0.
- Cherry picking mc upgrade from main
**NO**
- Local Build
=> mc upgrade to 4.8.27

SPECS/libnl3/libnl3.signatures.json, SPECS/libnl3/libnl3.spec, SPECS/libnsl2/libnsl2.signatures.json, SPECS/libnsl2/libnsl2.spec, SPECS/libpcap/libpcap.signatures.json, SPECS/libpcap/libpcap.spec, SPECS/libpipeline/libpipeline.signatures.json, SPECS/libpipeline/libpipeline.spec, SPECS/libpsl/libpsl.signatures.json, SPECS/libpsl/libpsl.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Update libnl3 to v3.5.0, libnsl2 to v2.0.0, libpcap to v1.10.1, libpipeline to v1.5.5, libpsl to v0.21.1
- Change
- Change
- Change
YES
- #xxxx
- Local Build
=> [main] Update libnl3 to v3.5.0, libnsl2 to v2.0.0, libpcap to v1.10.1, libpipeline to v1.5.5, libpsl to v0.21.1

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2021-45485.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2021-45485
- Address CVE-2021-45485
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-45485
- Local build
=> kernel: Address CVE-2021-45485

SPECS/mariner-release/mariner-release.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping release for January update.
=> Bump Releease for January update

SPECS-SIGNED/kernel-signed/kernel-signed.spec
---
Porting fix from #1472 to main to prevent signed build break.
Fix a build break that appears during signed kernel build.
“Installed (but unpackaged) file(s) found: /module_info.ld"
The fix is already merged to 1.0 branch. Not updating changelog since this version of kernel has not yet been released.
- exclude module_info.ld in kernel-signed.spec
**NO**
=> [main] Exclude module_info.ld from kernel-signed

toolkit/tools/imagegen/installutils/installutils.go
---
`main` branch cherry-pick of #1347.
When installutils processes a user's provided SSH public keys, it creates the $HOME/.ssh/authorized_keys file regardless of whether the user provided any public keys. However, due to an error in our code, we only gave the user's SSH directory the proper permissions if keys were provided in the system configuration. This means that when a user is configured without keys, that user would need to fix the SSH directory permissions manually at a later date.
Since ssh handles the creation of a user's SSH directory when not present, we choose to skip generation of the SSH directory and the authorized keys file entirely when public keys are not …
=> [main] installutils: Fix user ssh directory permissions when key empty

SPECS/WALinuxAgent/WALinuxAgent.signatures.json, SPECS/WALinuxAgent/WALinuxAgent.spec, cgmanifest.json
---
Update WALinuxAgent to v2.3.1.1
- Update WALinuxAgent to v2.3.1.1
NO
=> Update WALinuxAgent to v2.3.1.1

SPECS/libatomic_ops/libatomic_ops.signatures.json, SPECS/libatomic_ops/libatomic_ops.spec, cgmanifest.json
---
Upgrade libatomic_ops to the latest. Separate the static library (needed by some packages in extended) into a separate subpackage.
- Move static libraries to a separate subpackage
- Install licenses using just the %%license macro
**NO**
=> [main] Upgrade libatomic_ops to 7.6.12 and add static subpackage

SPECS/userspace-rcu/userspace-rcu.signatures.json, SPECS/userspace-rcu/userspace-rcu.spec, cgmanifest.json
---
Update userspace-rcu to v0.13.0
- Update userspace-rcu to v0.13.0
NO
=> Update userspace-rcu to v0.13.0

SPECS/dwz/dwz.signatures.json, SPECS/dwz/dwz.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update dwz to 0.14
- update dwz to 0.14
yes
- rebuilt toolchain locally, performed local build, installed in 2.0 vm
=> [main] Update dwz to v0.14

SPECS/btrfs-progs/btrfs-progs.signatures.json, SPECS/btrfs-progs/btrfs-progs.spec, cgmanifest.json
---
update btrfs-progs to 5.16
- update btrfs-progs to 5.16
NO
- Locally built and installed in test vm
=> [1.0] update btrfs-progs to 5.16

SPECS/expat/CVE-2022-22822.patch, SPECS/expat/expat.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Apply patch for CVE-2022-22822 to CVE-2022-22827
- Apply patch for expat
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-22822
- https://nvd.nist.gov/vuln/detail/CVE-2022-22823
- https://nvd.nist.gov/vuln/detail/CVE-2022-22824
- https://nvd.nist.gov/vuln/detail/CVE-2022-22825
- https://nvd.nist.gov/vuln/detail/CVE-2022-22826
- https://nvd.nist.gov/vuln/detail/CVE-2022-22827
- local toolchain and package build
=> Expat: Address CVE-2022-22822 to CVE-2022-22827

SPECS/lttng-tools/lttng-tools.signatures.json, SPECS/lttng-tools/lttng-tools.spec, SPECS/lttng-ust/lttng-ust.signatures.json, SPECS/lttng-ust/lttng-ust.spec, cgmanifest.json
---
Upgrading lttng-tools to v2.13.2 and lttng-ust to v2.13.1
lttng-tools
- Upgrading to 2.13.2
- Updated source url.
- Updating lttng-ust requirement to version 2.13.1
lttng-ust
-   Upgrading to 2.13.1
**NO**
- Local build
=> Upgrading lttng-tools to v2.13.2 and lttng-ust to v2.13.1

SPECS/expat/expat.signatures.json, SPECS/expat/expat.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Update to expat 2.4.3
Cherry-pick of #1937 
- Update to expat 2.4.3
**YES**
- local build (in progress)
=> [main] Expat: Update to 2.4.3

SPECS/tracelogging/tracelogging.signatures.json, SPECS/tracelogging/tracelogging.spec, cgmanifest.json
---
Upgrade `tracelogging` package to latest upstream version. This is needed due to the upgrade of the `lttng-ust` package in #1931.
- Upgrade to latest upstream version for lttng-ust 2.13 compatibility
- Use CMake options to avoid pulling in catch-devel in non-test builds
- Add version constraints to requirements
- Lint spec
NO
- Reseed build from latest main commit
=> [main] Upgrade tracelogging to 0.3

SPECS-EXTENDED/perl-Authen-SASL/perl-Authen-SASL.signatures.json, SPECS-EXTENDED/perl-Module-Install-AuthorTests/perl-Module-Install-AuthorTests.signatures.json
---
fix LICENSE.PTR signature
- relevant signature files
**NO**
- #xxxx
=> fix LICENSE.PTR signature

SPECS/mariner-release/mariner-release.spec, toolkit/Makefile, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping Release number for Mariner 2.0 Preview-B Image
=> Bump Mariner 2.0 Release for Preview-C Image

.github/workflows/validate-spec.sh, SPECS/moby-runc/generate-sources.sh, SPECS/moby-runc/moby-runc.signatures.json, SPECS/moby-runc/moby-runc.spec, cgmanifest.json
---
- Upgrade to version 1.1.0+azure to resolve CVE-2021-43784
- Upgrade to version 1.1.0+azure to resolve CVE-2021-43784
- Update Source0 URL
NO
- #xxxx
- https://nvd.nist.gov/vuln/detail/CVE-2021-43784
- Local Build
=> Fix moby-runc CVE-2021-43784

SPECS/LICENSES-AND-NOTICES/data/licenses.json, SPECS/netplan/netplan.signatures.json, SPECS/netplan/netplan.spec, cgmanifest.json, toolkit/scripts/spec_source_attributions.py
---
Add netplan feature from Mariner 1.0.
- Change
Add netplan from Mariner 1.0
**YES/NO**
- #xxxx
- Pipeline build id: Local Build.
=> Add netplan to Mariner

SPECS/chkconfig/chkconfig.spec
---
Mask the `check` section which depends on `beakerlibs` which currently are not provided by CBL-Mariner.
- Skip `check` section
**NO**
- NA
- NA
=> chkconfig: mask check section which depends on beakerlibs

SPECS/make/make.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- make: fix ptest via explict BR on `perl(lib)`
- make: manifests: bump release 4.3-1 -> 4.3-2
---
Fix ptest for `make`.
- Add an explict BuildRequires on `perl(lib)`
**YES**
- NA
- NA
- Pipeline build id: LocalBuild
=> make: fix ptest via explicit BR on `perl(lib)`

SPECS/btrfs-progs/btrfs-progs.signatures.json, SPECS/btrfs-progs/btrfs-progs.spec, cgmanifest.json
---
update btrfs-progs to 5.16
- update btrfs-progs to 5.16
NO
- Locally built and installed in test vm
=> [main] cherry pick btrfs progs update

toolkit/scripts/safeunmount.sh
- [ x cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
---
I noticed that in 2.0 the workers are more likely to abort when hitting ctrl+c, leaving many files behind. (in 1.0 they would tend to run to completion before exiting).
This update to the cleanup script should make walking the worker chroot directories much faster. It starts at the root directory and unmounts things bottom up. It also checks if it has already removed a directory by unmounting its parent, and just skips it if so.
- safeunmount.sh now orders its unmount operations so they can …
=> [main] Optimize mount cleanup script

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
---
Update erlang to 24.2
- Update erlang to 24.2
NO
- Locally built with checks, installed and tested in vm
=> [1.0] Update erlang to 24.2

SPECS/ipvsadm/ipvsadm.signatures.json, SPECS/ipvsadm/ipvsadm.spec, cgmanifest.json
---
Update to 1.31
- Update to 1.31
**NO**
- local build
=> [main] ipvsadm: Update to 1.31

SPECS/audit/audit.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt, toolkit/resources/manifests/package/update_manifests.sh, toolkit/scripts/toolchain/build_official_toolchain_rpms.sh
---
Removed indirect dependency on finger to remove potentially vulnerable fingerd service from base image.
- Removed tcp_wrapper support from audit, indirectly removing finger as a dependency.
- Removed tcp_wrapper and finger from toolchain.
**YES**
- Pipeline build id: local toolchain build
=> Removed audit indirect dependency on finger

SPECS/firewalld/firewalld-only-MDNS-default.patch, SPECS/firewalld/firewalld.signatures.json, SPECS/firewalld/firewalld.spec, cgmanifest.json
---
Update to 1.0.3
- Update to 1.0.3
- Add firewalld-test subpackage
- Fix configure command to point to python3
**NO**
- local build
=> [main] firewalld: update to 1.0.3

SPECS-EXTENDED/ocaml-camlp5/ocaml-camlp5.signatures.json, SPECS-EXTENDED/ocaml-camlp5/ocaml-camlp5.spec, cgmanifest.json
---
Upgrade ocaml-camlp5 package to 8.00.02 to fix build failure with latest version of ocaml.
- Upgrade ocaml-camlp5 to 8.00.02
**NO**
- Mock build against latest good main build
=> [main] [extended] Upgrade ocaml-camlp5 to 8.00.02

SPECS/tpm2-abrmd/tpm2-abrmd.signatures.json, SPECS/tpm2-abrmd/tpm2-abrmd.spec, SPECS/tpm2-tools/tpm2-tools.signatures.json, SPECS/tpm2-tools/tpm2-tools.spec, SPECS/tpm2-tss/tpm2-tss.signatures.json, SPECS/tpm2-tss/tpm2-tss.spec, cgmanifest.json
---
Updates cryptsetup to the latest stable release (2.4.3).
**NOTE:** Disabled the new ssh token feature since we don't have libssh in 2.0 at this time.
- Update tpm2-tools to 4.3.2
- Update tpm2-tss to 2.4.6
- Update tpm2-abrmd to 2.4.0
**NO**
Local build, waiting on pipeline build
=> [main] [tpm2-tools] [tpm2-abrmd] [tpm2-tss] Update tpm2-* packages

SPECS/cryptsetup/cryptsetup.signatures.json, SPECS/cryptsetup/cryptsetup.spec, cgmanifest.json
---
Updates cryptsetup to the latest stable release (2.4.3).
**NOTE:** Disabled the new ssh token feature since we don't have libssh in 2.0 at this time.
- Update cryptsetup to 2.4.3.
**NO**
Local build, waiting on pipeline build
=> [main] [cryptsetup] Update cryptsetup to 2.4.3

SPECS/colm/colm.signatures.json, SPECS/colm/colm.spec, cgmanifest.json
---
Updating `colm` requires an update to `ragel` but the two new versions together have build issues, so I'm reverting the `colm` update temporarily to unblock our builds.
- Reverted 'colm` back to 0.13.0.7.
No.
- #1969
- Pipeline package build.
=> [main] Reverting `colm` to 0.13.0.7.

SPECS/systemd/systemd-bootstrap.signatures.json, SPECS/systemd/systemd-bootstrap.spec, SPECS/systemd/systemd.signatures.json, SPECS/systemd/systemd.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Systemd has released version 250.3, so we should update to this latest version.
- Update systemd and systemd-bootstrap to version 250.3
**YES**
=> [main] Update systemd to v250.3

SPECS/python-netaddr/python-netaddr.signatures.json, SPECS/python-netaddr/python-netaddr.spec, cgmanifest.json
---
Upgrade python-netaddr to latest upstream version 0.8.0 to keep packages current.
- Upgrade python-netaddr to 0.8.0
**NO**
=> [main] [core] Upgrade python-netaddr to 0.8.0

SPECS/python-psutil/disable-tests-python-psutil.patch, SPECS/python-psutil/python-psutil.signatures.json, SPECS/python-psutil/python-psutil.spec, cgmanifest.json
---
Upgrade `python-psutil` package to 5.9.0.
- Update skipped tests patch
- Lint spec
**NO**
- Local mock build with latest good main build
=> [main] [core] Upgrade python-psutil to 5.9.0

SPECS/libstoragemgmt/libstoragemgmt.signatures.json, SPECS/libstoragemgmt/libstoragemgmt.spec, cgmanifest.json
---
- Upgrade libstoragemgmt to v1.9.3
- Upgrade to version 1.9.3
- Remove subpackage libstoragemgmt-netapp-plugin and libstoragemgmt-nstor-plugin
- Fix file paths
NO
- #xxxx
- Local Build
=> [main] Upgrade libstoragemgmt to v1.9.3

SPECS/Cython/Cython.signatures.json, SPECS/Cython/Cython.spec, cgmanifest.json
---
Upgrade Cython to the latest release, 0.29.26
- Upgrade Cython to 0.29.26
- Add check section
**NO**
=> [main] [core] Upgrade Cython to 0.29.26

SPECS/python-distro/python-distro.signatures.json, SPECS/python-distro/python-distro.spec, cgmanifest.json
---
Upgrade python-distro to latest upstream version 1.6.0
- Upgrade python-distro to latest upstream version 1.6.0
- Use updated upstream URL/Source0
- Tidy up requirements
**NO**
=> [main] [core] Upgrade python-distro to 1.6.0

SPECS/iotop/iotop-itervalues.patch, SPECS/iotop/iotop-use-py3.patch, SPECS/iotop/iotop.spec
---
Update `iotop` to build using `python3` instead of `python2`.
- iotop: Add upstream patches to build with python3
- iotop: Document lack of tests
- iotop: Lint spec
**NO**
- Local mock build against last good main build
=> [main] [core] iotop: Use python3 instead of python2

SPECS/libffi/libffi.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
The `libffi` package has an incorrect `Provides: pkgconfig(libffi)` in the base package. The correct location for this would be the devel subpackage, which contains `libffi.pc`. It looks like our toolchain is finally able to generate `pkgconfig(*)` provides automatically, so we can just take the statement out of the spec.
- Remove `Provides: pkgconfig(libffi)` from `libffi` spec
**YES**
- Will run a pipeline build to validate
=> [main] [core] Remove bad pkgconfig provides in libffi

toolkit/imageconfigs/packagelists/azurevm-packages.json
---
Add `python3-distro` to the `azurevm-packages.json` package list. Temporary workaround for the issue fixed in the main branch by #2013.
- Add python3-distro to `azurevm-packages.json`. Impacts gen1/gen2 marketplace images.
**NO**
- N/A
=> [2.0] Add python3-distro to azurevm-packages packagelist

SPECS/python-pyasn1/python-pyasn1.signatures.json, SPECS/python-pyasn1/python-pyasn1.spec, cgmanifest.json
---
Upgrade `python-pyasn1` to the latest upstream version to keep our 2.0 packages current.
- `python-pyasn1`: Upgrade to latest upstream version
- `python-pyasn1`: Use nicer Source0
- `python-pyasn1`: License verified
**NO**
=> [main] [core] Upgrade python-pyasn1 to 0.4.8

SPECS/erlang/erlang.signatures.json, SPECS/erlang/erlang.spec, cgmanifest.json
---
Update erlang to 24.2
- Update erlang to 24.2
NO
- Pipeline id: 161095
=> [main] cherry-pick erlang update from 1.0

SPECS/ethtool/ethtool.signatures.json, SPECS/ethtool/ethtool.spec, cgmanifest.json
---
Update ethtool to 5.16
- Update ethtool to 5.16
NO
- Built locally with check, installed and tested in VM
=> [main] ethtool: update to 5.16

SPECS/fdupes/fdupes.signatures.json, SPECS/fdupes/fdupes.spec, cgmanifest.json
---
fdupes: update to 2.1.2
- fdupes: update to 2.1.2
NO
- Local build + installed on test VM
=> [main] fdupes: update to 2.1.2

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/CVE-2021-4083.nopatch, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Address CVE-2021-4083
- Address CVE-2021-4083
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4083
- local build
=> kernel: Address CVE-2021-4083

SPECS/libmspack/libmspack.signatures.json, SPECS/libmspack/libmspack.spec, cgmanifest.json
---
- Update libmspack to the latest version 0.10.1alpha
- Upgrade to version 0.10.1alpha
- Remove binaries under /usr/bin
- Add README, TODO, ChangeLog, AUTHORS to the main package
NO
- #xxxx
- Local Build
=> [main] Update libmspack to v0.10.1alpha

SPECS-EXTENDED/python-ethtool/python-ethtool.signatures.json, SPECS-EXTENDED/python-ethtool/python-ethtool.spec, cgmanifest.json
---
The `python-ethtool` package currently uses a source in the form of `ethtool-%{version}.tar.gz`, which potentially has collisions with our `ethtool` package. Just as a precaution, we will switch to using the full SRPM name in the `Source0` tag.
- Fix source name collision with ethtool package
- Use github source tarball instead of pypi
**NO**
=> [main] [extended] Fix python-ethtool source name collision

SPECS/patchelf/patchelf.signatures.json, SPECS/patchelf/patchelf.spec, cgmanifest.json
---
Upgrading patchelf to 0.14.3
- Upgrading patchelf to 0.14.3
**NO**
- Local build and install on vm + basic functionality test
- Pipeline build [here ](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=162158&view=results). Failed due to autofs but patchelf built along with all packages with patchelf BR
=> [main] upgrading patchelf to 0.14.3

SPECS/extra-cmake-modules/extra-cmake-modules.signatures.json, SPECS/extra-cmake-modules/extra-cmake-modules.spec, cgmanifest.json
---
Update extra-cmake-modules to 5.90.0
- Update extra-cmake-modules to 5.90.0
NO
- Build locally with check
- Installed in a VM
=> [main] extra-cmake-modules: update to 5.90.0

SPECS/inotify-tools/inotify-tools.signatures.json, SPECS/inotify-tools/inotify-tools.spec, cgmanifest.json
---
update to 3.22.1.0
- update to 3.22.1.0
**NO**
- local build
=> [main] inotify-tools: update to 3.22.1.0

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Update to 8.2.4151 to address CVE-2022-0318.
- Update vim to 8.2.4151
- Update cgmanifest with new vim version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0318
Local build
Closes #2033
=> vim: update to 8.2.4151 to address CVE-2022-0318

SPECS/prometheus/0001-Fixed-TestChunkDiskMapper_WriteChunk_Chunk_IterateCh.patch, SPECS/prometheus/prometheus.spec
- prometheus: fix ptest by changing 'go check' -> 'go test'
- prometheus: backport patch to fix test in tsdb/chunks
---
Fixes ptest build for `prometheus`
- Use `go test` instead of `go check`
- Backport a patch to fix breaking tests.
**NO**
- NA
- NA
=> prometheus: fix ptest build

SPECS-EXTENDED/libguestfs/libguestfs.spec
---
Replace perl(Locale::TextDomain) BR in libguestfs with actual package due to a pipeline failure to resolve between multiple providers in the extended build.
- Replace perl(Locale::TextDomain) BR in libguestfs with perl-libintl-perl
**NO**
- N/A
=> [2.0] Replace perl(Locale::TextDomain) BR in libguestfs with actual package

SPECS/linux-firmware/linux-firmware.signatures.json, SPECS/linux-firmware/linux-firmware.spec, cgmanifest.json
---
linux-firmware: update to 20211216
- Update linux-firmware to 20211216
- Update cgmanifest entry for linux-firmware to 20211216 
**NO**
Local build
=> linux-firmware: update to 20211216

SPECS/fmt/fmt.signatures.json, SPECS/fmt/fmt.spec, cgmanifest.json
---
Update fmt to 8.1.1
- Update fmt to 8.1.1
NO
- Locally built using mock
- Tested in Mariner VM
=> [main] update fmt to 8.1.1

SPECS/numactl/numactl.signatures.json, SPECS/numactl/numactl.spec, cgmanifest.json
---
- Upgrading numactl to v2.0.14
**NO**
- Local build and install on test vm 
- Pipeline build id: [163421](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=163525&view=results)
=> [main] Upgrading numactl to v2.0.14

SPECS/gcovr/gcovr.signatures.json, SPECS/gcovr/gcovr.spec, cgmanifest.json
---
update gcovr to v5.0
- update gcovr to v5.0
NO
- Mock build
=> [main] update gcovr to v5.0

SPECS-SIGNED/kernel-signed/kernel-signed.spec, SPECS/kernel-headers/kernel-headers.spec, SPECS/kernel-hyperv/kernel-hyperv.spec, SPECS/kernel/kernel.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
As a result of the new install method for msopenjdk (from 40d19ce), the libperf-jvmti.so is now available and can be added to the tools package. This is because the previous install method did not pass the check for openjdk in the kernel's perf tools check (instead would return this message:  https://github.com/torvalds/linux/blob/f40ddce88593482919761f74910f42f4b84c004b/tools/perf/Makefile.config#L1017)
- Add libperf-jvmti.so to tools package
**YES**
- Pipeline build id: 163861
=> [main] kernel: Add libperf-jvmti.so to tools package

SPECS/fping/fping.signatures.json, SPECS/fping/fping.spec, cgmanifest.json
---
update fping to v5.0
- update fping to v5.0
NO
- Mock build
- Installed and tested in VM
=> [main] update fping to v5.0

SPECS/libstoragemgmt/libstoragemgmt.spec
---
Gracefully handle ptest failure instead of breaking the build
- Handle ptest failure instead of bailing out and breaking the build
**NO**
- NA
- NA
- Pipeline build id: Local Build with `RUN_CHECK=y`
=> libstoragemgmt: fix ptest build break

SPECS/iproute/iproute.spec
---
Fix ptest for `iproute`. All tests pass!
- add explicit BR on sudo & libmnl-devel to fix ptest
**NO**
- NA
- NA
=> iproute: add explicit BR on sudo & libmnl-devel to fix ptest

SPECS/memcached/memcached.spec
---
Fix ptest for `memcached`. All tests pass!
- Add explicit BR on `perl-{FindBin,lib,fields} to appease ptest.
- Drop dependency on `sudo` & `shadow-utils`.
- Test with the default user instead of creating a new `test` user.
**NO**
- NA
- NA
- Pipeline build id: LocalBuild
=> memcached: add explict BR on perl-{FindBin,lib,fields} to fix ptest

SPECS/fluent-bit/fluent-bit.signatures.json, SPECS/fluent-bit/fluent-bit.spec, cgmanifest.json
---
Update fluent-bit to 1.8.12. Referenced Fedora spec in updating build/install logic. 
- Update fluent-bit to 1.8.12
NO
- Locally built using mock
- Installed and tested inside Mariner VM
=> [main] Update fluent-bit to 1.8.12

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Update vim to 8.2.4233 to address CVE-2022-0392, CVE-2022-0393,
CVE-2022-0359, CVE-2022-0361, CVE-2022-0368.
- Update to vim to 8.2.4233
- Update changelog entry for vim
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0392
- https://nvd.nist.gov/vuln/detail/CVE-2022-0393
- https://nvd.nist.gov/vuln/detail/CVE-2022-0359
- https://nvd.nist.gov/vuln/detail/CVE-2022-0361
- https://nvd.nist.gov/vuln/detail/CVE-2022-0368
Local build
Closes #2081 #2082 #2083 #2084 #2085
=> vim: update to 8.2.4233 to address 5 CVEs

SPECS/libarchive/0001-test_write_disk_secure-properly-check-if-lchmod-is-s.patch, SPECS/libarchive/libarchive.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
- libarchive: backport a patch from upstream to fix ptest
- libarchive: manifests: bump release version
---
Fix ptest for `libarchive`
NOTE: There happens to be a miss in bumping the release version from last update.
- Backport a patch from upstream to fix ptest
**YES**
- NA
- NA
=> libarchive: fix ptest

SPECS/python-packaging/python-packaging.signatures.json, SPECS/python-packaging/python-packaging.spec, cgmanifest.json
---
Upgrade python-packaging to the latest upstream version 21.3
- Use github source URL instead of pypi
**NO**
- Local mock non-check and check build
=> [main] [core] Upgrade python-packaging to 21.3

SPECS/rrdtool/rrdtool.signatures.json, SPECS/rrdtool/rrdtool.spec, cgmanifest.json
---
Updates rrdtool to 1.7.2
- Update rrdtool spec to use 1.7.2
- Update cgmanifest entry for rrdtool
**NO**
Local build of rrdtool and packages dependent on it
=> rrdtool: update to 1.7.2

SPECS/librsvg2/librsvg2.spec, SPECS/mesa-libGLU/mesa-libGLU.spec
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> [main] cleanup spec files for mesa-LibGLU and librsvg2

SPECS/brotli/brotli.spec
---
Fix ptest for `brotli`. All test pass!
- Use `make` instead of `ctest` to enable ptest
**NO**
- NA
- NA
=> brotli: use `make` instead of `ctest` to enable ptest

toolkit/resources/manifests/package/macros.override
---
The %check section in gnutls hangs and sabotages the whole ptest pipeline to a griding halt.
Temporarily disable the check section.
- Skip check for `gnutls`
**NO**
- NA
- NA
- Pipeline build id: LocalBuild
=> manifests: macros: skip check section for gnutls

SPECS/gd/gd.spec
---
Fix `ptest` for `gd`. All tests pass!
- Add an explicit BR on `fontawesome-fonts` to fix ptest
**NO**
- NA
- NA
- Pipeline build id: LocalBuild with RUN_CHECK=1
=> gd: add explicit BR on fontawesome-fonts to enable ptest

SPECS/pango/0001-skip-tests-which-are-known-to-fail.patch, SPECS/pango/pango.spec
---
Fix ptest for `pango`. All tests pass!
- Use `%meson_test` instead of `make`
**NO**
- NA
- NA
=> pango: use %meson_test to fix ptest failure

SPECS/redis/redis.signatures.json, SPECS/redis/redis.spec, cgmanifest.json
---
Bump version 6.2.5 -> 6.2.6 to:
- fix ptest. All tests pass!
- security fixes
- Bump version to fix ptest
**NO**
- NA
- NA
=> redis: bump version 6.2.5 -> 6.2.6 to fix ptest

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Port https://github.com/microsoft/CBL-Mariner/pull/2022, https://github.com/microsoft/CBL-Mariner/pull/2056, https://github.com/microsoft/CBL-Mariner/pull/2090
- upgrade to v8.2.4120 to fix CVE-2022-0261
- upgrade to v8.2.4151 to fix CVE-2022-0318
- upgrade to v8.2.4233 to fix 5 CVEs
NO
- https://nvd.nist.gov/vuln/detail/CVE-2022-0261
- https://nvd.nist.gov/vuln/detail/CVE-2022-0318
- https://nvd.nist.gov/vuln/detail/CVE-2022-0392
- https://nvd.nist.gov/vuln/detail/CVE-2022-0393
- https://nvd.nist.gov/vuln/detail/CVE-2022-0359
- https://nvd.nist.gov/vuln/detail/CVE-2022-0361
- https://nvd.nist.gov/vuln/detail/CVE-2022-0368
- Local build
=> [main] port vim version updates from 1.0

SPECS/kernel-rt/kernel-rt.spec
---
kernel-rt is failing on ARM. It can't find the .config file because the config is copied to .config only on x86. As we don't have any ARM platforms currently targeted for realtime, simply make kernel-rt a ExclusiveArch: x86_64
- make kernel-rt a ExclusiveArch: x86_64
NO
- None
=> make kernel-rt ExclusiveArch x86_64

SPECS/rpcsvc-proto/rpcsvc-proto.signatures.json, SPECS/rpcsvc-proto/rpcsvc-proto.spec, cgmanifest.json
---
rpcsvc-proto: update to 1.4.3
Upstream rpcsvc-proto moved to a pure BSD-3 license. So update the license field in the spec.
- Update rpcsvc-proto to version 1.4.3
- Update license to BSD-3
- Update cgmanifest
**NO**
Local build
=> rpcsvc-proto: update to 1.4.3

SPECS/fontconfig/fontconfig.signatures.json, SPECS/fontconfig/fontconfig.spec, cgmanifest.json
---
- update fontconfig to v2.13.95
NO
- Mock build
=> [main] update fontconfig to v2.13.95

SPECS/pyparsing/pyparsing.signatures.json, SPECS/pyparsing/pyparsing.spec, cgmanifest.json
---
Upgrade `pyparsing` package to latest upstream version 3.0.7
- Add %check section tests
**NO**
=> [main] [core] Upgrade pyparsing to 3.0.7

SPECS/python-appdirs/python-appdirs.signatures.json, SPECS/python-appdirs/python-appdirs.spec, cgmanifest.json
---
Upgrade `python-appdirs` to latest upstream version 1.4.4
- Upgrade to latest upstream release version
- Use github release tarball
**NO**
=> [main] [core] Update python-appdirs to 1.4.4

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Update vim version to 8.2.4281 to fix 10 CVEs
Update version to 8.2.4281 to fix CVE-2022-0443, CVE-2022-0417, CVE-2022-0413, 
CVE-2022-0408, CVE-2022-0407,
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0443
- https://nvd.nist.gov/vuln/detail/CVE-2022-0417
- https://nvd.nist.gov/vuln/detail/CVE-2022-0413
- https://nvd.nist.gov/vuln/detail/CVE-2022-0408
- https://nvd.nist.gov/vuln/detail/CVE-2022-0407
- Local build + install on test vm + basic manual testing of vim.
=> [1.0-dev] vim: update to 8.2.4281 to address 5 CVEs

SPECS/libzip/libzip.signatures.json, SPECS/libzip/libzip.spec, SPECS/lmdb/lmdb.signatures.json, SPECS/lmdb/lmdb.spec, SPECS/lsof/lsof.signatures.json, SPECS/lsof/lsof.spec, SPECS/lsscsi/lsscsi.signatures.json, SPECS/lsscsi/lsscsi.spec, cgmanifest.json
---
- Update libzip to v1.8.0, lmdb to v0.9.29, lsof to v4.94.0, lsscsi to v0.32
- Change
- Change
- Change
NO
- #xxxx
- Local Build
=> [main] Update libzip to v1.8.0, lmdb to v0.9.29, lsof to v4.94.0, lsscsi to v0.32

SPECS/python-websocket-client/python-websocket-client.spec
---
Enable ptest build. All tests pass!
- pip install `six` & `unittest2`
**NO**
- NA
- NA
=> python-websocket-client: pip install 'six' & 'unittest2' to enable ptest

SPECS/python-process-tests/python-process-tests.signatures.json, SPECS/python-process-tests/python-process-tests.spec, cgmanifest.json
---
Upgrade `python-process-tests` to latest upstream version 2.1.2
- Remove %%python3_pkgversion boilerplating
- Use upstream github source
**NO**
=> [main] [core] Upgrade python-process-tests to 2.1.2

SPECS/python-m2r/python-m2r.signatures.json, SPECS/python-m2r/python-m2r.spec, cgmanifest.json
---
Upgrade `python-m2r` to latest upstream version 0.2.1
**NO**
=> [main] [core] Upgrade python-m2r to 0.2.1

SPECS/python-virtualenv/python-virtualenv.spec
---
- Add an explict BR on `python3-pip` to enable ptest.
**NO**
- NA
- NA
=> virtualenv: add an explict BR on 'pip' to enable ptest

SPECS/python-pyvmomi/python-pyvmomi.spec
---
Fix ptest build. All tests Pass!
- Add an explict BR on `pip` to enable ptest.
**NO**
- NA
- NA
=> python-pyvmomi: add an explicit BR on `pip` to enable ptest

SPECS/python-cherrypy/python-cherrypy.signatures.json, SPECS/python-cherrypy/python-cherrypy.spec, cgmanifest.json
---
- Bump version & use `py39` as tox environment to enable ptest.
**NO**
- NA
- NA
=> python-cherrypy: bump version 18.6.0 -> 18.6.1 to enable ptest

SPECS/python-webob/python-webob.signatures.json, SPECS/python-webob/python-webob.spec, cgmanifest.json
---
Upgrade python-webob to latest upstream version 1.8.7
- Use github source tarball
**NO**
=> [main] [core] Upgrade python-webob to 1.8.7

SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec, cgmanifest.json
---
fix build break due to wrong version for moby-containerd
- Moby-containerd
**NO**
- #xxxx
=> fix build break due to wrong version for moby-containerd

SPECS/python-kubernetes/python-kubernetes.signatures.json, SPECS/python-kubernetes/python-kubernetes.spec, cgmanifest.json
---
upgrade python-kubernetes
- upgrade python-kubernetes
**NO**
- #xxxx
=> upgrade python-kubernetes

SPECS-EXTENDED/postfix/pflogsumm-1.1.5-syslog-name-underscore-fix.patch, SPECS-EXTENDED/postfix/postfix-3.6.2-glibc-234-build-fix.patch, SPECS-EXTENDED/postfix/postfix-3.6.2-whitespace-name-fix.patch, SPECS-EXTENDED/postfix/postfix.service, SPECS-EXTENDED/postfix/postfix.signatures.json, SPECS-EXTENDED/postfix/postfix.spec, cgmanifest.json
---
Our `php` build got blocked by a failing `postfix` build (GCC update broke it). Updating it to the latest version resolved the issue.
- Updated `postfix` to build with latest version of GCC.
No.
=> [main] Fixing `php` build.

SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.signatures.json, SPECS-EXTENDED/ocaml-extlib/ocaml-extlib.spec, cgmanifest.json
---
Upgrade to latest upstream version of `ocaml-extlib`. Previous version is broken with our version of `ocaml`.
- Lint spec
**NO**
=> [main] [extended] Upgrade ocaml-extlib to 1.7.8

SPECS/pugixml/pugixml.signatures.json, SPECS/pugixml/pugixml.spec, cgmanifest.json
---
upgrade pugixml to v1.11.4
- upgrade pugixml to v1.11.4
No
A local build with RUN_CHECK=y
=> upgrade pugixml to v1.11.4

SPECS/git/git.spec
---
Remove python2 from the git build and replace with python3. 
- Replace python2 depdendency with python3
- Lint spec
- Fix ambiguous python shebang lines
**NO**
=> [main] [core] Remove python2 from git

SPECS/graphviz/graphviz.spec
---
Currently, the `graphviz` spec provides the option to build with `python2`. As part of our effort to remove `python2`, we remove that option from the spec.
- Remove option to build `graphviz` with python2
**NO**
=> [main] [core] Remove python2 build option from graphviz

SPECS/cloud-hypervisor/cloud-hypervisor.signatures.json, SPECS/cloud-hypervisor/cloud-hypervisor.spec, SPECS/cri-tools/cri-tools.signatures.json, SPECS/cri-tools/cri-tools.spec, cgmanifest.json
---
- Update cloud-hypervisor to v21.0, cri-tools to v1.23.0
- Change
- Change
- Change
NO
- #xxxx
- Local Build
=> [main] Update cloud-hypervisor to v21.0, cri-tools to v1.23.0

SPECS/python-execnet/python-execnet.spec
---
- Use tox environment `py39` instead of `py37`
**NO**
- NA
- NA
=> python-execnet: use `py39` as tox environment to enable ptest

SPECS/python-imagesize/python-imagesize.spec
---
- Remove stray `popd` in `%check` section
**NO**
- NA
- NA
=> python-imagesize: remove stray `popd` to enable ptest

SPECS/python-mistune/python-mistune.spec
---
- Add an explicit BR on 'pip' to enable ptest.
**NO**
- NA
- NA
=> python-mistune: add an explicit BR on 'pip' to enable ptest

SPECS/python-oauthlib/python-oauthlib.spec
---
- Add an explicit BR on 'pip'
- Install 'wheel' to enable ptest
**NO**
- NA
- NA
=> python-oauthlib: install 'wheel' to enable ptest

SPECS/python-bcrypt/python-bcrypt.signatures.json, SPECS/python-bcrypt/python-bcrypt.spec, cgmanifest.json
---
Upgrades bcrypt to 3.2.0 as part of general 2.0 update process.
- Updated python-bcrypt to 3.2.0
**NO**
- local build
=> Updated python-bcrypt to 3.2.0

SPECS/cni/build.sh, SPECS/cni/cni.signatures.json, SPECS/cni/cni.spec, cgmanifest.json
---
- update cni to version 1.0.1
- Upgrade to version 1.0.1
- Add vendor source, which is required to build
- Modify build.sh to build using vendor source
NO
- #xxxx
- Local Build
=> [main] Upgrade cni to v1.0.1

SPECS/python-bcrypt/python-bcrypt.spec
---
- Add an explict BR on `pip` to enable ptest
**NO**
- NA
- NA
=> python-bcrypt: add an explicit BR on 'pip' to enable ptest

SPECS/python-pbr/python-pbr.signatures.json, SPECS/python-pbr/python-pbr.spec, cgmanifest.json
---
- Bump version 5.1.2 -> 5.8.1
- Use `tox` to enable ptest
**NO**
- NA
- NA
=> python-pbr: bump version to 5.8.1 & use `tox` to enable ptest

SPECS-SIGNED/grub2-efi-binary-signed/grub2-efi-binary-signed.spec, SPECS/grub2/grub2.signatures.json, SPECS/grub2/grub2.spec, cgmanifest.json
---
Update grub2 to latest 2.06 release and include the efinet and tftp modules to support PXE boot flows when booting using grubx64.efi or grubaa64.efi.
- Update grub2 to 2.06 release
- Update cgmanifest entry for grub2
- Add efinet and tftp to module list to compile in when creating the grub efi binaries
**NO**
Local build
=> grub2: Update to 2.06 and include tftp support

SPECS/python-certifi/python-certifi.signatures.json, SPECS/python-certifi/python-certifi.spec, cgmanifest.json
---
Updated python-certifi to 2021.10.08
- Updated python-certifi to 2021.10.08
**NO**
- local build
=> [main] Updated python-certifi to 2021.10.08

SPECS/python-cachetools/python-cachetools.signatures.json, SPECS/python-cachetools/python-cachetools.spec, cgmanifest.json
---
Updated cachetools to 5.0.0 for 2.0.
- Updated cachetools to 5.0.0
**NO**
- local build
=> [main] Updated cachetools to 5.0.0

SPECS/nmi/modify-go-build-option.patch, SPECS/nmi/nmi.signatures.json, SPECS/nmi/nmi.spec, cgmanifest.json
---
- Update nmi to v1.8.7
- Upgrade to version 1.8.7
- Update modify-go-build-option.patch
- License Verified
NO
- #xxxx
- Local Build
=> [main] Update nmi to v1.8.7

SPECS/jansson/jansson.signatures.json, SPECS/jansson/jansson.spec, cgmanifest.json
---
update jansson to v2.14
- update jansson to v2.14
NO
=> [main] update jansson to v2.14

SPECS/fribidi/fribidi-drop-bundled-gnulib.patch, SPECS/fribidi/fribidi.signatures.json, SPECS/fribidi/fribidi.spec, cgmanifest.json
---
Upgrade fribidi to v1.0.10
- Upgrade fribidi to v1.0.10
- Update the patch file to agree with the new version v1.0.10
No
- Local build by RUN_CHECK=y
=> fribidi v1.0.10 update

SPECS/python-six/python-six.signatures.json, SPECS/python-six/python-six.spec, cgmanifest.json
---
- Bump version 1.11.0 -> 1.16.0
- Use `%pytest` to enable ptest
**NO**
- NA
- NA
- Pipeline build id: Local Build iwth RUN_CHECK=y
=> python-six: bump version to 1.16.0 & use `%pytest` to enable ptest

SPECS/python-twisted/python-twisted.spec
---
- Add an explicit BR on 'pip' & 'sudo'
- Use `py39` as tox environment to enable ptest
**NO**
- NA
- NA
=> python-twisted: use `py39` as tox environment to enable ptest

SPECS/python-pycparser/python-pycparser.spec
---
- Use correct test file path `tests/all_tests.py` instead of `all_tests.py`
- Drop stray `pushd/popd`
**NO**
- NA
- NA
=> python-pycparser: use correct test file path to enable ptest

SPECS/libmspack/libmspack.spec
---
- Use `make -k check` to enable ptest
**NO**
- NA
- NA
=> libmspack: use `make -k check` to enable ptest

SPECS/m2crypto/0001-skip-test_tls1_nok-which-cant-be-run-in-FIPS.patch, SPECS/m2crypto/m2crypto.spec
---
- Skip a non FIPS mode test & a TLS1 test which fails on Mariner.
**NO**
- NA
- NA
=> m2crypto: skip testing TLS1 & a non FIPS test to enable ptest

SPECS/python-repoze-lru/python-repoze-lru.spec
---
- Use `py39` as tox env to enable ptest
**NO**
- NA
- NA
=> python-repoze-lru: use `py39` as tox env to enable ptest

SPECS/freetype/freetype.signatures.json, SPECS/freetype/freetype.spec, cgmanifest.json
---
update freetype to 2.11.1
- update freetype to 2.11.1
NO
=> [main] update freetype 2.11.1

SPECS/babeltrace2/00-fix-lttng-live-array-access.patch, SPECS/babeltrace2/babeltrace2.spec
---
add 00-fix-lttng-live-array-access.patch to babeltrace2
- babeltrace2
**NO**
- #xxxx
=> add 00-fix-lttng-live-array-access.patch to babeltrace2

SPECS/python-attrs/python-attrs.spec
---
- Use `py39` as tox env to enable ptest
**NO**
- NA
- NA
=> python-attrs: use `py39` as tox env to enable ptest

SPECS/python-zope-interface/python-zope-interface.spec
=> python-zope-interface: add an explicit BR on 'pip' to enable ptest

SPECS/python-routes/python-routes.spec
---
- Use tox env `py39` to enable ptest
**NO**
- NA
- NA
=> python-routes: use `py39` as tox environment to enable ptest

SPECS/python-certifi/python-certifi.spec
---
- Drop un-needed deps
- Use `%pytest` to enable ptest
**NO**
- NA
- NA
=> python-certifi: use `%pytest` to enable ptest

SPECS/python-chardet/python-chardet.signatures.json, SPECS/python-chardet/python-chardet.spec, cgmanifest.json
---
Updated python-chardet to 4.0.0 for 2.0
- Updated python-chardet to 4.0.0
**NO**
- local build
=> [main] Updated python-chardet to 4.0.0

SPECS/python-cffi/python-cffi.signatures.json, SPECS/python-cffi/python-cffi.spec, cgmanifest.json
---
Updated python-cffi to 1.15.0 for 2.0 effort.
- Updated python-cffi to 1.15.0
**NO**
- local build
=> [main] Updated python-cffi to 1.15.0

SPECS/e2fsprogs/e2fsprogs.signatures.json, SPECS/e2fsprogs/e2fsprogs.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- e2fsprogs: bump version 1.46.4 -> 1.46.5 to enable ptest
**YES**
- Reference: https://github.com/tytso/e2fsprogs/issues/80
- NA
=> e2fsprogs: bump version to 1.46.5 to enable ptest

SPECS/sed/sed.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- sed: add an explicit BR on `perl(File::Find)` to enable ptest
- sed: manifests: bump release
**YES**
- NA
- NA
=> sed: add an explicit BR on `perl(File::Find)` to enable ptest

SPECS/at/at.signatures.json, SPECS/at/at.spec
---
Add BRs for making PTEST to pass
**NO**
- Local build
=> Fix ptest of package at

SPECS/rdma-core/0001-kernel-boot-Do-not-perform-device-rename-on-OPA-devi.patch, SPECS/rdma-core/rdma-core.signatures.json, SPECS/rdma-core/rdma-core.spec, cgmanifest.json
---
Updated rdma-core to v39.0
- Updated rdma-core to v39.0
- Modified patch to apply to the new version
NO
=> Update rdma-core to v39.0

SPECS/at/at.spec
---
It seems we've accidentally surrounded a few parameterized RPM macros with brackets, which is an invalid way of invoking them (see: [here for details](http://ftp.rpm.org/api/4.4.2.2/macros.html)).
- Removed curly brackets around RPM parameterized macros.
No.
- #2212
- Local package build and installation.
=> [main] Fixing `at.spec` function calls.

SPECS/pyproject-rpm-macros/macros.pyproject, SPECS/pyproject-rpm-macros/pyproject-rpm-macros.signatures.json
---
While working on #2220 I've been using a stale worked chroot and missed my own updated to `pyproject-rpm-macros`. This PR addresses that and should fix the build failures for `python-tox-current-env` and `python-charset-normalizer`.
- Updated macro definitions to search for the scripts under the correct paths.
Yes.
- #2220
- Local package build and worker chroot reconstruction.
=> [main] Fixing `pyproject-rpm-macros`.

toolkit/imageconfigs/packagelists/azurevm-packages.json
---
The azure-kvp configs are included in the Azure VM package list for 1.0 but they are missing in 2.0.
Add the cloud-init-azure-kvp subpackage into the 2.0 Azure VM package list.
- Add cloud-init-azure-kvp subpackage into the 2.0 Azure VM package list
**NO**
- Verified that the cloud-init-azure-kvp package is available in 2.0 builds.
=> Add cloud-init-azure-kvp to azurevm package list

toolkit/imageconfigs/packagelists/azurevm-packages.json
---
Fix the remaining delta between 1.0 and 2.0 azurevm package lists.
- Add python-xml and rsyslog to 2.0 azurevm package list.
**NO**
- Checked that both packages are in 2.0 repo
- Booted VM in Azure and observed KVP enabled during cloud-init, rsyslog systemd service is running, and python-xml is installed.
=> Sync 2.0 azurevm-packages with 1.0

SPECS/pcre2/pcre2.signatures.json, SPECS/pcre2/pcre2.spec, cgmanifest.json
---
upgrading pcre2 to v10.39
- Upgrading to v10.39
- Fixing source URL. 
**NO**
- Local build and installed on test vm.
- Pipeline build running currently.
=> [main] upgrading pcre2 to v10.39

SPECS/python-hyperlink/python-hyperlink.signatures.json, SPECS/python-hyperlink/python-hyperlink.spec, cgmanifest.json
---
Updated python-hyperlink to 21.0.0 for 2.0
- Updated python-hyperlink to 21.0.0 for 2.0
**NO**
- local build
=> Updated python-hyperlink to 21.0.0

SPECS/python-hypothesis/python-hypothesis.signatures.json, SPECS/python-hypothesis/python-hypothesis.spec, cgmanifest.json
---
Updated python-hypothesis to 6.36.2 for 2.0
- Updated python-hypothesis to 6.36.2
**NO**
- local build
=> Updated python-hypothesis to 6.36.2

SPECS/python-idna/python-idna.signatures.json, SPECS/python-idna/python-idna.spec, cgmanifest.json
---
Updated python-idna to 3.3 for 2.0
- Updated python-idna to 3.3
**NO**
- local build
=> Updated python-idna to 3.3

SPECS/openssl/CVE-2021-4160.nopatch, SPECS/openssl/openssl.spec
---
CVE-2021-4160 - Only affects the MIPS32 and MIPS64 platforms
- Nopatch openssl CVE-2021-4160
No code changes
- https://nvd.nist.gov/vuln/detail/CVE-2021-4160
No code changes
=> [1.0] [CVEs] Nopatch openssl CVE-2021-4160

SPECS/gnuplot/gnuplot.signatures.json, SPECS/gnuplot/gnuplot.spec, cgmanifest.json
---
update gnuplot to v5.4.3
- update gnuplot to v5.4.3
NO
- Local mock build, installed and tested in Mariner VM
=> [main] Update gnuplot to v5.4.3

toolkit/docs/security/ca-certificates.md
---
Updating our doc regarding installation of custom trusted CAs to make it a bit easier to understand.
- Updated docs.
No.
- N/A
=> Clarifying certificates' configuration docs.

SPECS/python-jsonpatch/python-jsonpatch.signatures.json, SPECS/python-jsonpatch/python-jsonpatch.spec, cgmanifest.json
---
Upgrade python-jsonpatch to the latest upstream version 1.32
- Use github source tarball
**NO**
=> [main] [core] Upgrade python-jsonpatch to 1.32

SPECS/pytz/pytz.signatures.json, SPECS/pytz/pytz.spec, cgmanifest.json
---
- Bump version 2018.5 -> 2021.3
- Add an explict BR on `pip`
- Use correct test files to enable ptest
**NO**
- NA
- NA
=> pytz: bump version to 2021.3 & fix check to enable ptest

SPECS/python-mako/python-mako.signatures.json, SPECS/python-mako/python-mako.spec, cgmanifest.json
---
Bump verison and fix ptest build. All tests pass!
- Bump version 1.0.7 -> 1.1.5
- Drop BR on `python3-pytest`
- Use `tox` instead of `pytest` to enable ptest
**NO**
- NA
- NA
=> python-mako: bump version to 1.1.5 & use `tox` to enable ptest

toolkit/docs/security/ca-certificates.md
---
Cherry-picking documentation updates from `1.0-dev`, PR #2226.
- Cherry-pick of #2226.
No.
- #2226
- N/A
=> [main] Clarifying certificate configuration. (CP of #2226)

SPECS/pcaudiolib/pcaudiolib.signatures.json
---
Fix the `signature.json` file.
- NA
**NO**
- Seems like there was an oversight in: #2219
- NA
=> pcaudiolib: fix signature.json

SPECS/python-lxml/python-lxml.spec
---
Remove extraneous `%files` section from the `python-lxml` main package. This section causes an empty RPM to be produced, which we don't want.
- Remove %files section for main package to avoid outputting an empty RPM
**NO**
=> [main] [core] Prevent empty python-lxml RPM from being produced

SPECS/man-pages/man-pages.signatures.json, SPECS/man-pages/man-pages.spec, cgmanifest.json
---
Upgrade man-pages to v5.13
- Upgrade man-pages to v5.13
- 
**NO**
- Local build and install on test vm
=> [main] Upgrade man-pages to v5.13

SPECS/ansible/ansible.spec, SPECS/llvm/llvm.spec, SPECS/syslog-ng/syslog-ng.spec
---
Remove python2 usage from `ansible`, `llvm`, and `syslog-ng` to aid in our `python2` eradication efforts. 
- `ansible`: Remove stray BR on `python-setuptools`
- `llvm`: Exchange `python2` BRs for `python3` BRs
- `syslog-ng`: Remove separate python2 build and python2 subpackage
**NO**
- Pipeline build
=> [main] [core] Remove python2 from ansible, llvm, syslog-ng packages

SPECS/mm-common/mm-common.signatures.json, SPECS/mm-common/mm-common.spec, cgmanifest.json
---
upgrading mm-common 1.0.4
- upgrading mm-common 1.0.4
**NO**
- Local build and install on test vm
=> [main] upgrading mm-common 1.0.4

SPECS/haveged/haveged.signatures.json, SPECS/haveged/haveged.spec, cgmanifest.json
---
Update haveged to v1.9.17
- Update haveged to v1.9.17
NO
- Mock build with checks, installed and tested in VM
=> [main] Update haveged to v1.9.17

SPECS/strongswan/CVE-2021-45079.patch, SPECS/strongswan/strongswan.spec
---
Patch strongswan CVE-2021-45079
- Patch strongswan CVE-2021-45079
NO
- https://nvd.nist.gov/vuln/detail/CVE-2021-45079
- Mock build
=> [1.0] [CVEs] Patch strongswan CVE-2021-45079

SPECS/hdparm/hdparm.signatures.json, SPECS/hdparm/hdparm.spec, cgmanifest.json
---
Update hdparm to v9.63
- Update hdparm to v9.63
NO
- Mock build
=> [main] Update hdparm to v9.63

SPECS/audit/audit.spec, SPECS/blobfuse/blobfuse.spec, SPECS/cni/cni.spec, SPECS/coredns/coredns-1.7.0.spec, SPECS/coredns/coredns-1.8.0.spec, SPECS/coredns/coredns-1.8.4.spec, SPECS/cri-tools/cri-tools.spec, SPECS/etcd/etcd-3.4.13.spec, SPECS/etcd/etcd-3.5.0.spec, SPECS/flannel/flannel.spec, SPECS/glide/glide.spec, SPECS/go-md2man/go-md2man.spec, SPECS/gobject-introspection/gobject-introspection.spec, SPECS/golang/golang-1.16.signatures.json, SPECS/golang/golang-1.16.spec, SPECS/helm/helm.spec, SPECS/moby-buildx/moby-buildx.spec, SPECS/moby-cli/moby-cli.spec, SPECS/moby-containerd/moby-containerd.spec, SPECS/moby-engine/moby-engine.spec, SPECS/moby-runc/moby-runc.spec, SPECS/node-problem-detector/node-problem-detector.spec, SPECS/nvidia-container-runtime/nvidia-container-runtime.spec, SPECS/nvidia-container-toolkit/nvidia-container-toolkit.spec, SPECS/telegraf/telegraf.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade to `golang` from 1.16.12 to 1.16.14 to fix several CVEs. Please see the [release announcement email](https://groups.google.com/g/golang-announce/c/SUsQn0aSgPQ) for more details on this release.
- Upgrade `golang` to version 1.16.14 to resolve CVE-2022-23806, CVE-2022-23772, CVE-2022-23773
- Bump 23 specs that are dependent on `golang` to force rebuild/republish
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-23806
- https://nvd.nist.gov/vuln/detail/CVE-2022-23772
- https://nvd.nist.gov/vuln/detail/CVE-2022-23773
- Ongoing pipeline build
=> [1.0-dev] golang: Upgrade to 1.16.14 to fix several CVEs

SPECS/libcacard/libcacard.spec
---
- Add an explicit BR on `opensc` & `softhsm` to enable ptest
**NO**
- NA
- NA
=> libcacard: add an explicit BR on `softhsm` & `opensc` to enable ptest

SPECS/libaio/fix-gcc11-bug-and-parity-with-upstream.patch, SPECS/libaio/libaio.spec
---
- Switch to `%autosetup` instead of `%setup`
- Introduce patch to fix gcc-11 bug & have parity with upstream
**NO**
- NA
- NA
=> libaio: introduce patch to fix gcc-11 bug to enable ptest

SPECS/autogen/autogen.spec, cgmanifest.json
---
Fix pipeline build & enable ptest. All tests pass!
- Add an explicit BR on `perl(lib)` to enable pipeline build
- Drop parallel `%{?_smp_mflags}` make flags to enable ptest
**NO**
- NA
- NA
=> autogen: add an explicit BR on `perl(lib)` to fix build & enable ptest

SPECS/vim/vim.signatures.json, SPECS/vim/vim.spec, cgmanifest.json
---
Upgrade vim to 8.2.4432 to fix CVE-2022-0554.
- Upgrade vim to latest upstream version
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2022-0554
=> [1.0-dev] vim: Upgrade to 8.2.4432 to fix CVE-2022-0554

SPECS/nss/nss.spec
---
Drop `Provides: nss-tools` in favour of adding an explicit subpackage. Tools provided by the package were not packaged.
- Drop `Provides: nss-tools`
- Add subpackage `nss-tools`
- Switch to `%autosetup` instead of `%setup`
**NO**
- NA
- NA
=> nss: add subpackage `nss-tools` & drop `Provides: nss-tools`

toolkit/Makefile
---
My apologies, y'all- I accidentally checked in my local `Makefile` changes in #2252. Reverting those changes to return the file to its previous state.
- Revert Makefile changes from #2252
**NO**
- N/A
=> [main] Revert accidental Makefile changes from #2252

SPECS/iputils/iputils.signatures.json, SPECS/iputils/iputils.spec, SPECS/iputils/ping_test_ipv6_localhost.patch, cgmanifest.json
---
- Use meson to build and install
update source to 20211215
- traceroute removed: https://github.com/iputils/iputils/pull/362
- tracepath, clockdiff, and arping install to bin so create symlink in sbin.
- update source to 20211215
**NO**
=> [main] iputils: Update to 20211215

SPECS/tracelogging/tracelogging.signatures.json, SPECS/tracelogging/tracelogging.spec, cgmanifest.json
---
Update tracelogging to v0.3.1 for proper compatibility with lttng-ust >= 2.13
- Upgrade tracelogging to v0.3.1
**NO**
Local build with `rpm-build`.
=> Upgrade tracelogging to v0.3.1

SPECS/http-parser/http-parser.signatures.json, SPECS/http-parser/http-parser.spec, cgmanifest.json
---
Update http-parser to v2.9.4
- Update http-parser to v2.9.4
NO
- Mock build
=> [main] Update http-parser to v2.9.4

SPECS/harfbuzz/harfbuzz.signatures.json, SPECS/harfbuzz/harfbuzz.spec, cgmanifest.json
---
Update harfbuzz to v3.4.0
- Update harfbuzz to v3.4.0
NO
- Mock build with checks
=> [main] Update harfbuzz to v3.4.0

SPECS/python-jwt/python-jwt.signatures.json, SPECS/python-jwt/python-jwt.spec, cgmanifest.json
---
Updated PyJWT to 2.3.0 for 2.0. Changes to build for PyJWT as the upgrade was substantial.
- Updated to 2.3.0.
- Removed pyjwt binary as it no longer exists.
- Updated Python dependency to at least 3.6.
- Updated cryptography dependency to at least 3.0
- Updated build and install sequence to use CBL-Mariner macros.
- Removed removal of setup.cfg as it no longer installs additional dependencies.
**NO**
=> [main] Updated PyJWT to 2.3.0

SPECS/meson/meson.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Drop BR on `gmock-devel` & `gtest-devel`
- Add an explicit BR on `libgcrypt-devel, glib, gtest, gmock, cmake & git` to enable ptest
**YES**
- NA
- NA
=> meson: add explicit BR's & drop un-needed BR's to enable ptest

SPECS/irqbalance/irqbalance.signatures.json, SPECS/irqbalance/irqbalance.spec, cgmanifest.json
---
Update irqbalance to v1.8.0
- Update irqbalance to v1.8.0
NO
- Mock build
=> [main] Update irqbalance to v1.8.0

SPECS/i2c-tools/i2c-tools.signatures.json, SPECS/i2c-tools/i2c-tools.spec, cgmanifest.json
---
Update i2c-tools to v4.3
- Update i2c-tools to v4.3
NO
- mock build, installed in test VM
=> [main] Update i2c-tools to v4.3

SPECS/grep/grep.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add an explicit BR on `perl(File::Find)` & tweak configure opts to enable ptest
- Cosmetic cleanup of `%changelog`
**YES**
- NA
- NA
- Pipeline build id: LOCAL_BUILD with & without RUN_CHECK=y
=> grep: add an explicit BR on `perl(File::Find)` & tweak configure opts to enable ptest

SPECS/gnupg2/gnupg2.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Add an explicit softlink `gpg2 -> gpg` in check section to enable ptest
**YES**
- NA
- NA
=> gnupg2: add an explicit softlink `gpg2 -> gpg` in check section to enable ptest

SPECS/lvm2/lvm2-set-default-preferred_names.patch, SPECS/lvm2/lvm2.signatures.json, SPECS/lvm2/lvm2.spec, cgmanifest.json
---
upgrading lvm2 to v2.03.15
- upgrading lvm2 to v2.03.15
**NO**
- Local build and install on test vm
=> [main] upgrading lvm2 to v2.03.15

SPECS/mercurial/mercurial.signatures.json, SPECS/mercurial/mercurial.spec, cgmanifest.json
---
upgrading mercurial to v6.0.3
-   Upgrading to latest version 6.0.3
-   Switching from python2 to python3.
**NO**
- Local Build and install on test vm
=> [main] upgrading mercurial to v6.0.3

SPECS/nginx/nginx.signatures.json, SPECS/nginx/nginx.spec, cgmanifest.json
---
upgrading nginx to v 1.20.2
- upgrading nginx to v 1.20.2
**NO**
- Local buikd and installed on test vm
=> [main] upgrading nginx to v 1.20.2

SPECS/isns-utils/isns-utils.signatures.json, SPECS/isns-utils/isns-utils.spec, cgmanifest.json
---
Update isns-utils to v0.101
- Update isns-utils to v0.101
NO
- Mock build
=> [main] Update isns-utils to v0.101

SPECS/python-coverage/python-coverage.signatures.json, SPECS/python-coverage/python-coverage.spec, cgmanifest.json
---
Updates python-coverage to 6.3.2 for 2.0.
- Updated python-coverage to 6.3.2
**NO**
=> [main] Updated python-coverage to 6.3.2

SPECS/gobject-introspection/gobject-introspection.signatures.json, SPECS/gobject-introspection/gobject-introspection.spec, cgmanifest.json
---
Update gobject-introspection to v1.71.0
- Update gobject-introspection to v1.71.0
NO
=> [main] Update gobject-introspection to v1.71.0

SPECS/python-docutils/python-docutils.signatures.json, SPECS/python-docutils/python-docutils.spec, cgmanifest.json
---
Updated docutils to 0.18.1 for 2.0
- Updated docutils to 0.18.1
**NO**
=> [main] updated python-docutils to 0.18.1

SPECS/javapackages-tools/javapackages-tools.signatures.json, SPECS/javapackages-tools/javapackages-tools.spec, SPECS/javapackages-tools/remove-headless-from-java-requires.patch, cgmanifest.json
---
Update javapackages-tools to v6.0.0
- Update javapackages-tools to v6.0.0
NO
- Mock build
=> [main] Update javapackages-tools to v6.0.0

SPECS/python-incremental/python-incremental.signatures.json, SPECS/python-incremental/python-incremental.spec, cgmanifest.json
---
Updates python-incremental to 21.3.0 for 2.0.
**NO**
=> [main] Updated incremental to 21.3.0

SPECS/ntopng/ntopng.signatures.json, SPECS/ntopng/ntopng.spec, cgmanifest.json
---
upgrading ntopng to v5.2.1
- upgrading ntopng to v5.2.1
- upgrading ndpi tarball to 4.2 to build ntopng
**NO**
- Local build and install on test vm
=> [main] upgrading ntopng to v5.2.1

SPECS/expat/expat.signatures.json, SPECS/expat/expat.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Upgrade to 2.4.6 to fix multiple CVEs.
- expat: Upgrade to latest upstream version to fix CVE-2022-25313, CVE-2022-25314, CVE-2022-25315, CVE-2022-25235, CVE-2022-25236
**YES**
- https://nvd.nist.gov/vuln/detail/CVE-2022-25313
- https://nvd.nist.gov/vuln/detail/CVE-2022-25314
- https://nvd.nist.gov/vuln/detail/CVE-2022-25315
- https://nvd.nist.gov/vuln/detail/CVE-2022-25235
- https://nvd.nist.gov/vuln/detail/CVE-2022-25236
- Pipeline build
=> [1.0-dev] expat: Upgrade to 2.4.6 to fix multiple CVEs

SPECS/ocaml/0004-remove-unused-var-in-alloc_aync_stubs.patch, SPECS/ocaml/ocaml.spec
---
- Introduce patch to enable ptest.
**NO**
Related PR:
- https://github.com/ocaml/ocaml/pull/11067
- NA
=> ocaml: introduce patch to remove unused var to enable ptest

.github/CODEOWNERS
---
Adding a [`CODEOWNERS` file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#syntax-exceptions) to ensure modification to core packages are approved by at least one CBL-Mariner repo admin. We can also further extend this file in the future, if needed.
- Added a [`CODEOWNERS` file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#syntax-exceptions).
No.
- N/A
=> [main] Adding `CODEOWNERS` to restrict core packages updates.

SPECS/glibmm/glibmm.spec
---
Fix glibmm check; PTests were failing because make check is no longer a target. Use meson_test instead.
- Use meson_test in glibmm
NO
- Mock build with check
=> [main] Fix glibmm check

SPECS/git/git.spec
---
Git has an unspecified dependency on openssh package. This causes git to not work out of the box after installing it on a Mariner system without openssh (such as Mariner containers).
- Add runtime openssh dependency for git
**NO**
- Local build
=> Add openssh dependency for git

.github/CODEOWNERS
---
Cherry-pick of #2353.
Adding a [`CODEOWNERS` file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#syntax-exceptions) to ensure modification to core packages are approved by at least one CBL-Mariner repo admin. We can also further extend this file in the future, if needed.
- Added a [`CODEOWNERS` file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#syntax-exceptions).
No.
- #2353
- N/A
=> [1.0] Adding `CODEOWNERS` to restrict core packages updates. (CP #2353)

SPECS/utf8proc/utf8proc.spec
---
Fix PTEST failure for utf8proc package
- BR ruby
- Set locale while executing tests
**NO**
- Local build
=> fix utf8proc ptest

SPECS/initscripts/initscripts.signatures.json, SPECS/initscripts/initscripts.spec, cgmanifest.json
---
Update initscripts to v10.15
- Update initscripts to v10.15
- build with python3
NO
- Mock build, installed in VM
=> [main] Update initscripts to v10.15

SPECS/perl-JSON/perl-JSON.spec
---
- Add an explicit BR on `perl(Tie::Array)` to enable ptest
**NO**
- NA
- NA
=> perl-JSON: add an explicit BR on `perl(Tie::Array)` to enable ptest

SPECS/perl-CPAN-Meta-Check/perl-CPAN-Meta-Check.spec
---
- Add an explicit BR on `perl(Test::Deep)` to enable ptest
**NO**
- NA
- NA
=> perl-CPAN-Meta-Check: add an explicit BR on `perl(Test::Deep)` to enable ptest

SPECS/swig/swig.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix ptest for package swig
- Add BRs to swig package to run Ptest successfully
- Pass additional arguments to make check to use Python3
**YES**
Local build
=> fix swig ptest

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/shell/shell.go
---
Distroless container images do not contain a package manager, so it is difficult to tell which packages were used to build the image. Modify the tooling to create files with information about the packages in the image, whenever the configuration file contains "RemoveRpmDb": true
"/var/lib/rpmmanifest/container-manifest-1" contains the output of "rpm -qa"
"/var/lib/rpmmanifest/container-manifest-2" contains the output of "rpm -qa -qf %{NAME}\t%{VERSION}-%{RELEASE}\t%{INSTALLTIME}\t%{BUILDTIME}\n"
- Change image tools to generate manifest files
**NO**
=> Generate rpm manifests for distroless container images

SPECS/python-botocore/python-botocore.spec
---
- Drop un-needed BRs for `%check` section
- Switch to `tox` for testing.
**NO**
- NA
- NA
=> python-botocore: drop un-needed BRs & switch to tox to enable ptest

SPECS/tboot/tboot.signatures.json
---
Fix signatures.json file.
- NA -- Fixing `signautres.json`
**NO**
- #2357
- NA
=> tboot: fix signatures.json

SPECS/pycairo/pycairo.spec
---
- Add an explict BR on `python3-pip`
- pip install deps in `%check` section to enable ptest
**NO**
- NA
- NA
=> pycairo: add an explicit BR on `pip` & pip install deps to enable ptest

toolkit/tools/imagegen/installutils/installutils.go, toolkit/tools/internal/shell/shell.go
---
Distroless container images do not contain a package manager, so it is difficult to tell which packages were used to build the image. Modify the tooling to create files with information about the packages in the image, whenever the configuration file contains "RemoveRpmDb": true
"/var/lib/rpmmanifest/container-manifest-1" contains the output of "rpm -qa"
"/var/lib/rpmmanifest/container-manifest-2" contains the output of "rpm -qa -qf %{NAME}\t%{VERSION}-%{RELEASE}\t%{INSTALLTIME}\t%{BUILDTIME}\n"
Port #2391 to main
- Change image tools to generate manifest files
**NO**
- sudo make image …
=>  Generate rpm manifests for distroless container images (main)

SPECS/pcre/pcre.spec, cgmanifest.json, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Compile in JIT support in the PCRE library (only on supported architectures).
- Compile in JIT support in the PCRE library.
- Update source download URL.
- Update manifests.
**YES**
Local build
=> Enable JIT feature on supported architectures

SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec, SPECS/SymCrypt/SymCrypt.spec
---
SymCrypt is currently failing ARM builds because Cmake cannot find clang. Mitigating by adding an ExclusiveArch.
- SymCrypt.spec: ExclusiveArch x86
NO
- #xxxx
=> [main] Temporarily make SymCrypt exclusivearch x86_64

SPECS/mariner-release/mariner-release.spec, toolkit/Makefile, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
Bumping version for Preview-E Release.
=> Bumping version for Preview-E Release.

SPECS/python-jinja2/python-jinja2.signatures.json, SPECS/python-jinja2/python-jinja2.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Updated jinja2 to 3.0.3
- Updated jinja2 to 3.0.3
- Updated source URL
- Updated check section to work with new Jinja testing infra
**YES**
=> [main] Upgraded jinja2 to 3.0.3

toolkit/scripts/tools.mk, toolkit/tools/internal/exe/exe.go
---
ToolkitVersion is hard-coded and needs to be updated for the main/2.0 branches.
This change sets the ToolkitVersion to RELEASE_VERSION. Ex:
./out/tools/depsearch --version
2.0.20220304.2135
- Change ToolkitVersion in exe.go
**NO**
- sudo make go-tools REBUILD_TOOLS=y
- ./out/tools/imager --version
=> Update ToolkitVersion to RELEASE_VERSION at compile time

SPECS/msgpack/msgpack.signatures.json, SPECS/msgpack/msgpack.spec, cgmanifest.json
---
Upgrade msgpack to 3.3.0
- Upgrade msgpack to 3.3.0. We don't upgrade to newest version 4.1.0 as the new msgpack releases separate C part and C++ part.
No
=> upgrade msgpack to 3.3.0

SPECS/nlohmann-json/nlohmann-json.spec
---
- Switch to `%autosetup -S git`
- Add an explicit BR on `git` to enable ptest
**NO**
- NA
- NA
=> nlohmann-json: add an explicit BR on `git` to enable ptest

SPECS/libxslt/libxslt.spec, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
Fix ptest build. All test pass!
- libxslt: drop fuzz testing to enable ptest
**YES**
- NA
- NA
=> libxslt: drop fuzz testing to enable ptest

SPECS/c-ares/c-ares.spec
---
- Add configure option `--enable-tests`
- Use explicit testing as per offcial CI (from github) to enable ptest
**NO**
- NA
- NA
=> c-ares: refactor check section to enable ptest

SPECS/libstoragemgmt/libstoragemgmt.spec
---
- Cleanup duplicate BRs
- Add an explicit BR on `git` to enable ptest
**NO**
- NA
- NA
=> libstoragemgmt: add an explicit BR on `git` to enable ptest

SPECS/rust/rust.spec
---
Fix ptest for Rust
- Build rustfmt tool as it is required for PTest
- Create a softlink for rustfmt tool in stage0
**NO**
Local build
=> Fix rust ptest

SPECS/python-wheel/python-wheel.spec
---
Make PTest of python-wheel to run successfully
- BR multiple python modules required by PTest
- pip install other modules which are not provided by Mariner RPMs
**NO**
Local build
=> fix python-wheel ptest

SPECS/python-jinja2/python-jinja2.signatures.json, SPECS/python-jinja2/python-jinja2.spec, cgmanifest.json, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
This reverts commit 99953ac7eb9451950d79f44010e42905d4fbdf42. to fix build break
=> Build break: Revert "[main] Upgraded jinja2 to 3.0.3 (#2397)"

SPECS/python-sphinxcontrib-websupport/add_deps_in_tox.patch, SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.signatures.json, SPECS/python-sphinxcontrib-websupport/python-sphinxcontrib-websupport.spec, SPECS/python-wheel/python-wheel.spec, cgmanifest.json
---
Upgrade to latest version to run PTest
- Package version upgrade
- BR to python-six
**NO**
Local build
=> Fix sphinxcontrib websupport ptest

SPECS/crash-gcore-command/crash-gcore-command.signatures.json, SPECS/crash-gcore-command/crash-gcore-command.spec, SPECS/go-md2man/go-md2man.signatures.json, SPECS/go-md2man/go-md2man.spec, SPECS/kexec-tools/kexec-tools.signatures.json, SPECS/kexec-tools/kexec-tools.spec, cgmanifest.json
---
Update the following packages to the latest versions:
crash-gcore-command go-md2man kexec-tools
- Update crash-gcore-command
- Update go-md2man
- Update kexec-tools
**NO**
- Local build
=> Update packages: crash-gcore-command go-md2man kexec-tools

SPECS/moby-containerd/containerd.service, SPECS/moby-containerd/moby-containerd.signatures.json, SPECS/moby-containerd/moby-containerd.spec
---
containerd service file change to enable containerd service restart on a crash
* Thu Mar 03 2022 Anirudh Gopal <angop@microsoft.com> - 1.5.9+azure-4
- Enable containerd service restart
**NO**
- #xxxx
Verified the service file change and behavior by manually killing the containerd service with the RPM build artifact from pipeline: 172538
=> Restart containerd service 10 sec after crash

SPECS/git/git.spec
---
- Add an explicit BR on `perl{(lib), (IO::File), (Getopt::Long)}`
- Skip `git-send-email` (t9001) tests to enable ptest
**NO**
- NA
- NA
=> git: add explicit BRs & skip `send-email` tests to enable ptest

SPECS/python-jsonschema/python-jsonschema.signatures.json, SPECS/python-jsonschema/python-jsonschema.spec, cgmanifest.json
---
Bump version & fix ptest build. All tests pass!
- Bump version 2.6.0 -> 3.2.0
- Add an explicit BR on `python3-pip` & `python3-wheel`
- Switch to `tox` to enable ptest
**NO**
- NA
- NA
=> python-jsonschema: bump version to 3.2.0 & switch to tox to enable ptest

SPECS/gawk/gawk.spec, toolkit/resources/manifests/package/pkggen_core_aarch64.txt, toolkit/resources/manifests/package/pkggen_core_x86_64.txt, toolkit/resources/manifests/package/toolchain_aarch64.txt, toolkit/resources/manifests/package/toolchain_x86_64.txt
---
- Generate locale `en_US.iso88591` in `%check` section to enable ptest
- Lint spec
**YES**
- NA
- NA
=> gawk: generate locale `en_US.iso88591` in `%check` section to enable ptest

SPECS/fillup/fillup-test-create-DIFFERENCE-dir-before-testing.patch, SPECS/fillup/fillup.spec
---
`NOTE: This repo is ~8 years old and the tests do not pass on the upstream.`
- Introduce patch to fix `make test`
**NO**
- NA
- NA
=> fillup: introduce patch to enable ptest

SPECS/kernel/CVE-2021-20320.nopatch, SPECS/kernel/CVE-2021-20321.nopatch, SPECS/kernel/CVE-2021-4090.nopatch, SPECS/kernel/CVE-2021-4093.nopatch, SPECS/kernel/CVE-2022-0382.nopatch, SPECS/kernel/CVE-2022-0617.nopatch, SPECS/kernel/CVE-2022-25265.nopatch, SPECS/kernel/kernel.spec
---
Address several cves with nopatches
- Address CVE-2021-4090, CVE-2021-4093,
CVE-2022-25265, CVE-2021-20320, CVE-2021-20321, CVE-2022-0382,
CVE-2022-0617
**NO**
- https://nvd.nist.gov/vuln/detail/CVE-2021-4090 
- https://nvd.nist.gov/vuln/detail/CVE-2021-4093
- https://nvd.nist.gov/vuln/detail/CVE-2022-25265
- https://nvd.nist.gov/vuln/detail/CVE-2021-20320
- https://nvd.nist.gov/vuln/detail/CVE-2021-20321
- https://nvd.nist.gov/vuln/detail/CVE-2022-0382
- https://nvd.nist.gov/vuln/detail/CVE-2022-0617
- local build
=> kernel: Address CVE-2021-4090, CVE-2021-4093, CVE-2022-25265, CVE-2021-20320, CVE-2021-20321, CVE-2022-0382, CVE-2022-0617

SPECS/envoy/envoy.spec
---
- Remove envoy-source subpackage from CBL-Mariner
- Change
- Change
- Change
NO
- #xxxx
- Local build
=> [main] Remove envoy-source

SPECS/td-agent/td-agent.patch, SPECS/td-agent/td-agent.spec
---
- td-agent enforces the ruby version to use for building. Due to the recent upgrade in ruby, need to update the patch file to point to the correct ruby version in order to build
- Update td-agent.patch due to the upgrade in ruby
NO
- #xxxx
- Local Build
=> [1.0-dev] Fix td-agent build break

SPECS-EXTENDED/spirv-headers/spirv-headers.signatures.json, SPECS-EXTENDED/spirv-headers/spirv-headers.spec, SPECS-EXTENDED/spirv-tools/fix-gcc12-build.patch, SPECS-EXTENDED/spirv-tools/spirv-tools.signatures.json, SPECS-EXTENDED/spirv-tools/spirv-tools.spec, cgmanifest.json
---
A separate fix for `spirv-tools` requiring an update of `spirv-headers`.
- Updated `spirv-tools` to version 2022.1.
- Updated `spirv-headers` to version 1.5.5 + pre-release 1.6.1 commits.
No.
=> [main][SPECS-EXTENDED] Fixing `spirv-tools` build.

SPECS/sudo/sudo.signatures.json, SPECS/sudo/sudo.spec, cgmanifest.json
---
- Change
- Change
- Change
**YES/NO**
- #xxxx
=> Upgrade Sudo to 1.9.10

SPECS/python-tox-current-env/python-tox-current-env.spec
---
Run tox to run PTest
- Use tox in check section
**NO**
Local method
=> fix tox-current-env ptest
